### ISSUE TITLE
Integrate "Team" Functionality

### ISSUE THREAD

**Issue by jordan-wright** [gophish/gophish#10]
Some companies (specifically pentesting companies) would like to group gophish users by teams.

This might be a "pro" or paid feature. We'll see :smile:

**Comment by the-useless-one** [comment]
That is a great idea! Or at least, a way to share resources (user groups, templates, etc.) between gophish users.

Thanks for your awesome tool!

**Comment by jordan-wright** [comment]
Closing this, since I don't anticipate implementing any form of RBAC any time soon.
