### ISSUE TITLE
Submit button does nothing

### ISSUE THREAD

**Issue by CM19** [gophish/gophish#1006]
**What version of Gophish are you using?**: 0.5.0

**Brief description of the issue:** 
Putting in credentials and hitting submit does nothing. The button does nothing. I've tried linking the submit button to another random page, which it does then go to, but the credentials don't appear to be captured; maybe it takes a while for the system to update? 

**What are you expecting to see happen? :** Not entirely sure what's supposed to happen, ideally I want to create another page saying "thank you, your credentials were not found on the compromised list, have a good day!". Also would expect credentials to be captured

**What are you seeing happen?**
Nothing. I'm seeing nothing.  This is the first time I've ever used html, it's been a learning curve. Please tell me what I'm doing wrong and what I need to do to fix it?

```html

	<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
	<title></title>
	<style type="text/css">body{
    padding-left: 35px;
    padding-right: 35px;
    padding-top: 25px;
}
.button{
	clear: both;
    background-color: #aaa;
    border: 0 none;
    border-radius: 4px;
    color: #FFFFFF;
    cursor: pointer;
    display: inline-block;
    font-size: 15px;
    font-weight: bold;
    height: 32px;
    line-height: 32px;
    margin: 0 5px 10px 0;
    padding: 0 22px;
    text-align: center;
    text-decoration: none;
    vertical-align: top;
    white-space: nowrap;
    width: auto;
}
	</style>
</head>
<body data-gramm="true" data-gramm_editor="true" data-gramm_id="9aba6f6c-5dbc-8c4d-9c63-18da3394fa64" style="margin:10px;">
<p>&nbsp;</p>

<p><font color="#4d4f53" face="arial"><b>Urgent Staff Password Reset</b></font></p>

<p><font color="#4d4f53" face="arial">You have been directed to this page because suspicious</g> activity has been detected on files attached to your account. To verify if your account has been compromised, please log in below. If your account has been compromised, you will be required to change your password immediately.</font></p>

<p>&nbsp;</p>

<form action="" color="#4d4f53" face="arial" font="" method="post" name="form">
<p><label>Username:</label> <input name="username" type="text" /></p>

<p><label>Password:&nbsp;</label>&nbsp;<input name="password" type="password" /></p>
</form>

<p><input class="button" footer="" id="mc-embedded-submit" name="submit" type="submit" value="Submit" /></p>

<div class="footer_right_section">
<p class="bg_none">&nbsp;</p>
</div>
</body>
</html>
"""

**Comment by S0larflare** [comment]
Keep it simple with something like this:

```
<form action="" method="post" name="signIn" novalidate="">
<h1>Sign in</h1>
<div><label for="ap_email">Email </label></div>
<input name="email_address" type="email" />
<div><label for="ap_password">Password </label></div>
<input type="password" />
<input type="submit" name="submit" value="Sign In"/>
<div data-a-input-name="rememberMe"><input tabindex="4" type="checkbox" value="true" /> Keep me signed in</div>
</form>
```

Does that still not work? Is this the landing page hosted on your gophish server? Do you get a click registered when you click the link in the email?

**Comment by CM19** [comment]
@S0larflare Thank you for getting back to me. 

That worked!!! 
Yes I was getting a link clicked when I clicked it from the email, and that time it worked and it actually registered that credentials were captured.  I created the pages on the GoPhish editor thingy, so I'm assuming they are.

Now I need to figure out how to create another page that says "All good your credentials do not appear to have been compromised! Please continue with your life as normal". Can I do that with another GoPhish page and somehow link them? Or create with another page builder such as wix etc.?

Thanks again!

**Comment by jordan-wright** [comment]
Gophish has the option to redirect to a URL after credentials are submitted. This would let you redirect to any site you'd like which could host that informational page. However, it likely can't be hosted easily on Gophish itself.

We do have plans to implement a new style of campaign builder in #223 that would make this easy, but I don't have a timeline for this yet.

Glad to hear @S0larflare was able to help you resolve the issue!

**Comment by CM19** [comment]
@S0larflare So I've come back several months later to build anotehr page lol, and I'm having the same problem. 
I've tried using the code you've given above and it's not working. I'm currently clicking the button and it's not redirecting the page at all; Help!! Please!!!  
"""<form action="" method="post" name="signIn" novalidate="" style="padding-left: 35%; width: 40%; line-height: 0px;">
<div class="fieldset" style=" line-height: 0px;"><span style="font-family: &#39;Segoe UI&#39;; font-size: 14px; font-weight: 600;"><label for="username">Username or email</label></span></div>

<p><input name="email_address" style="width: calc(100% - 25px);line-height: 40px;border-color: #ccc;border-width:1px;border-style:solid;border-radius: 4px;" type="email;"/></p>

<p> </p>

<p><span style="font-family: &#39;Segoe UI&#39;; font-size: 14px; font-weight: 600;">Password</span></p>

<p><input name="password" style="width: calc(100% - 25px);line-height: 40px;border-color: #ccc;border-width:1px;border-style:solid;border-radius: 4px;" type="password"/></p>

<p> </p>
<input name="submit" style="width: calc(100% - 25px);border-radius: 4px; background-color: #005ec2;
    color: white;
    font-family: Segoe UI; font-size: 12pt;
    padding: 9px 15px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    opacity: 0.9;" type="submit" value="Sign In"/> </form>
</div>
"""

I've tried even just copy pasting your code in as-is, and the submit button still doesn't do anything :/ Pretty behind on this project now, please please help.
