### ISSUE TITLE
easy clickers and how much time user spend in landing page 

### ISSUE THREAD

**Issue by oded86w** [gophish/gophish#1010]
Hi , It's could be nice to view in report who is easy clicker ,User that click immediately on link .

And how much time they spend in landing page ,If thy see and read or close the landing page  immediately  .
Thank you :)

**Comment by jordan-wright** [comment]
Hi @oded86w, thanks for reaching out!

I'm afraid we don't have plans to add either of these at this time. The first suggestion for the time between email received and the user clicking on the link can be calculated from the information we provide in our REST API.

The second suggestion doesn't really have much weight in terms of what we want to report on with Gophish. At the end of the day, a click is a click. If you'd like to determine how long the user stayed on the page, I suggest putting some custom Javascript in your landing page that sends that information to another web server you control.

Hope this helps! Thanks again for getting in touch.
