### ISSUE TITLE
Cannot access admin page from remote machine

### ISSUE THREAD

**Issue by sdcexn** [gophish/gophish#1011]
What version of Gophish are you using?: 
0.5

Brief description of the issue: 
Unable to access GoPhish admin page from remote machine.

What are you expecting to see happen? :
Should be able to access the GoPhish admin page from a remote machine.

What are you seeing happen?
When attempting to access the GoPhish admin page from the local machine, it works perfectly. When attempting to access the GoPhish admin page from a remote machine, all browsers tested (IE, Firefox, Chrome) throw up an error.

Errors are:
_______________________
IE (with SSLv2 disabled):
This page can’t be displayed

Turn on TLS 1.0, TLS 1.1, and TLS 1.2 in Advanced settings and try connecting to https://<gophish_IP>:3333  again. If this error persists, it is possible that this site uses an unsupported protocol or cipher suite such as RC4 (link for the details), which is not considered secure. Please contact your site administrator. 
_______________________
IE (with SSLv2 enabled):
This page can’t be displayed

•Make sure the web address https://<gophish_IP>:3333 is correct.
•Look for the page with your search engine.
•Refresh the page in a few minutes
_______________________
Firefox:
Secure Connection Failed

The connection to the server was reset while the page was loading.

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

Learn more…

Report errors like this to help Mozilla identify and block malicious sites
_______________________
Chrome:
This site can’t be reached

The webpage at https://<gophish_IP>:3333/ might be temporarily down or it may have moved permanently to a new web address.
ERR_CONNECTION_ABORTED
_______________________

The console output shows the error as:
http: TLS handshake error from <source_IP>:<source_port> read tcp <gophish_IP>:3333-><source_IP>:<source_port>: read: connection reset by peer.

This happens whether the certificate being used is a self signed certificate generated during the startup process, or a signed certificate.

It doesn't appear to be a firewall blocking issue as it can connect to the GoPhish IP and port but for some reason the client doesn't like the SSL information and is resetting the information.

Any ideas why I cannot connect to the admin console from a remote machine?

**Comment by sdcexn** [comment]
![gophish](https://user-images.githubusercontent.com/37405127/37462962-9924f364-284b-11e8-86f0-26eefbad2ae5.PNG)

Attached is the the screenshot of the config.json file.

**Comment by S0larflare** [comment]
What does the console show? if you change the admin_server listen_url to the IP of the server, can you get in then?

**Comment by sdcexn** [comment]
With it set to listen on any IP:
![gophish2](https://user-images.githubusercontent.com/37405127/37463343-dc8ea87e-284c-11e8-9dc6-63daa163ca38.PNG)

with it set to listen on the server IP:
![gophish3](https://user-images.githubusercontent.com/37405127/37463346-e246b93c-284c-11e8-9039-b75e40a6f41b.PNG)

**Comment by S0larflare** [comment]
Is 203.0.113.20 a load balancer or firewall or something? Is it going through anything that could try to do SSL inspection or anything?

**Comment by sdcexn** [comment]
Yeah it's a firewall doing source NAT. However no SSL decryption/inspection enabled.

And you've just pointed me to the issue. Firewall is an application aware firewall which was only allowing SSL traffic through on 443 not 3333. All working now.

Explaining the problem to others always helps to get you out of the mindset rut you are in.

Thanks a lot!

**Comment by S0larflare** [comment]
No problem, glad I could help :)
