### ISSUE TITLE
GoPhish Crash /Mailer Issue

### ISSUE THREAD

**Issue by heathy3210** [gophish/gophish#1012]
Having a few Issues, 
i successfully created a campaign and used port 8080 instead of port 80.
when setting up the campain i set the IP address to my machine http://10.128.10.100:8080
as soon as i pressed the start campaign button the application crashed including the webserver.
now every time i try to start gophish with ./gophish it fails as it is trying to run that mail job every time and failing on an error, therefore the web interface doesnt load up so i cant even delete the campaign.

Is there a way to purge the mail job so that i can load up Gophish again?

Here is my output:

```
root@kali:~/Apps/GoWork/src/github.com/gophish/gophish# ./gophish
 2018/03/16 12:18:59 worker.go:26: Background Worker Started Successfully - Wait                                                                                                                                                             ing for Campaigns
goose: no migrations to run. current version: 20171208201932
 2018/03/16 12:18:59 gophish.go:120: Starting phishing server at http://10.128.1                                                                                                                                                             0.100:8080
 2018/03/16 12:18:59 gophish.go:103: Starting admin server at https://10.128.10.                                                                                                                                                             100:3334
 2018/03/16 12:19:59 worker.go:65: Sending 1 maillogs to Mailer
 2018/03/16 12:19:59 mailer.go:78: Mailer got 1 mail to send
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x607562]

goroutine 46 [running]:
net/url.(*URL).Query(0x0, 0x12)
        /usr/lib/go-1.9/src/net/url/url.go:975 +0x22
github.com/gophish/gophish/models.(*MailLog).Generate(0xc4201d6690, 0xc4206682a0                                                                                                                                                             , 0x0, 0xc4206682a0)
        /root/Apps/GoWork/src/github.com/gophish/gophish/models/maillog.go:224 +                                                                                                                                                             0x384
github.com/gophish/gophish/mailer.sendMail(0x1030480, 0xc4201f4280, 0x1029200, 0                                                                                                                                                             xc4201f8ee8, 0xc4201225b0, 0x1, 0x1)
        /root/Apps/GoWork/src/github.com/gophish/gophish/mailer/mailer.go:145 +0                                                                                                                                                             x18a
github.com/gophish/gophish/mailer.(*MailWorker).Start.func1(0x1030480, 0xc4201f4                                                                                                                                                             280, 0xc4201225b0, 0x1, 0x1)
        /root/Apps/GoWork/src/github.com/gophish/gophish/mailer/mailer.go:84 +0x                                                                                                                                                             165
created by github.com/gophish/gophish/mailer.(*MailWorker).Start
        /root/Apps/GoWork/src/github.com/gophish/gophish/mailer/mailer.go:77 +0x                                                                                                                                                             81
```

Thanks,
Jordan

**Comment by S0larflare** [comment]
If you do ./gophish --disable-mailer that should disable it (I tried thinking of a better way to word that without sounding like an idiot, but failed). You should then be able to delete the campaign and restart gophish normally (I think, I haven't looked in to the new mailer code so I'm not sure if deleting the campaign will clear it or not, but it's worth a try for a quick fix).

**Comment by heathy3210** [comment]
Okay, thats great it lets me in to the web interface now ill have to keep that switch in mind.
just checking am i stating the port correctly in the campaign? as every time i put the port in it seems to crash again.
ive attatched what ive entered below>
![campaign](https://user-images.githubusercontent.com/37443198/37521616-38b2dff4-2919-11e8-9c2b-f6965a335507.png)

**Comment by S0larflare** [comment]
I can't see why that would make it crash. I've tried recreating that and it worked fine for me. What version of Gophish are you using?

**Comment by heathy3210** [comment]
I have just done it again following the previous crash and seems to be fine now have done about 10 test campaigns to verify its working again, no idea what caused it but seems to be okay now. weird.
Thanks for your help!

**Comment by jordan-wright** [comment]
Hi @heathy3210, glad to hear this one's been worked out.

For whatever reason, Gophish can't find a proper URL after it's parsed. My guess is that it's a result of calling `url.Parse` with an invalid URL. *But*, we don't catch this when the campaign is submitted- only when it's being executed.

I'll make a note to have error checking occur earlier on to try and catch this in the future.

Thanks for sending this in!
