### ISSUE TITLE
Can't start gophish

### ISSUE THREAD

**Issue by Yil81** [gophish/gophish#1016]
Hi there,

i've downloaded gophish-v0.5.0-osx-64bit from this website https://github.com/gophish/gophish/releases 
when i run the binairy it's not starting. This is what i'm getting:

<img width="682" alt="screen shot 2018-03-19 at 15 26 30" src="https://user-images.githubusercontent.com/37545153/37602020-c6ce8f4e-2b8b-11e8-9ecc-b7b028155fff.png">

Am i doing something wrong here? I don't get it. I found another thread with the same issue but what was suggested there was not the case. I downloaded the binary and not the source.
https://github.com/gophish/gophish/issues/824

**Comment by S0larflare** [comment]
Are you in the gophish directory when you're trying to run it? Is there a VERSION file in there?

**Comment by Yilkee** [comment]
I'm definitely in the gophish directory when trying to run it. Yes there is a file called VERSION in there.

**Comment by S0larflare** [comment]
How are you running the binary file? cd into the directory and then ./gophish ?

**Comment by Yilkee** [comment]
cd into directory and then i do `open gophish`

**Comment by S0larflare** [comment]
I don't have a mac, so don't use OSX...Rather than 'open', can you do `./gophish` instead?

**Comment by Yilkee** [comment]
Ah... ok, i'm still much of a linux n00b. Learning though but bit by bit. Anywho we're getting one step closer but now i'm getting the following:

<img width="941" alt="screen shot 2018-03-19 at 15 56 18" src="https://user-images.githubusercontent.com/37545153/37603246-77540522-2b8e-11e8-8f2d-b631eb2c0cb4.png">

`bind: permission denied`

**Comment by S0larflare** [comment]
So that means you don't have permission to use port 80 or it is already in use. You'll either need to use good old sudo: `sudo ./gophish` or if there is already something (like apache for example) running on that port, then either kill it or change the phishing server port in your config.json

**Comment by Yilkee** [comment]
I used top to see if i could find a process using port 80 but didn't see anything. The system is a clean install from an hour ago so it's not clogged with crap. Not seeing anything there i proceeded to sudo it and now i'm running into another issue. It first does what you see in the pink box. then i go to the browser and enter http://localhost:3333. The page doesn't load. When i go back to the terminal window i see what comes after the prink box.

<img width="990" alt="screen shot 2018-03-19 at 16 14 50" src="https://user-images.githubusercontent.com/37545153/37604361-13864d36-2b91-11e8-89f3-ec808f60dc4f.png">

I'm starting to wonder if i'm too much of a newbie for this....

**Comment by jordan-wright** [comment]
Try https://localhost:3333 (note the "s" in "https"). Then, you'll need to accept the certificate warning and you'll be up and running.

Hope this helps!

**Comment by Yil81** [comment]
Thanks all! It's working now :) 
Man i feel like a n00b. Ah well, everybody need to learn somehow right. Hope that someone else who has the same problems can find this and get up and running too. Then at least there's that :)

**Comment by avikagg** [comment]
@Xun-876 were you able to resolve this? I am getting same error.

**Comment by masterloka** [comment]
were you able to resolve this? I am getting same error.  by "sudo ./gophish"

**Comment by glennzw** [comment]
Please share a screenshot of what you're seeing.

'command not found' means you're likely not inside the gophish directory.

**Comment by masterloka** [comment]
> Please share a screenshot of what you're seeing.
> 
> 'command not found' means you're likely not inside the gophish directory.

Problem solved. I opened the 3333 Port.

**Comment by isaacomondi2002** [comment]
Hello I get ' Bash:./gophish: permission denied ' problem.Someone please help

**Comment by Emdad05** [comment]
> Hello I get ' Bash:./gophish: permission denied ' problem.Someone please help

Same err i got

**Comment by glennzw** [comment]
Try 'chmod +x gophish' first

**Comment by twcg** [comment]
> Try 'chmod +x gophish' first

Worked for me on the zsh: permission denied. Thank you
