### ISSUE TITLE
Gmail smtp

### ISSUE THREAD

**Issue by manoxus** [gophish/gophish#1018]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  5.0 

Brief description of the issue: using gmail as a smtp server 

What are you expecting to see happen? : max connection attempts reached 

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
I'm using gmail as my Smtp server on smtp.gmail.com:465 and I can telnet to this port. 
 * Step 2 - 
I have disabled 2FA and enabled less secure apps on my gmail
I'm still getting max connection attempts reached with a test and a campain. 
![cmd](https://user-images.githubusercontent.com/37455148/37650563-3395571a-2c2d-11e8-911f-0206c1fb93f8.jpg)

Wireshark shows me this 

![image](https://user-images.githubusercontent.com/37455148/37651595-88604b6c-2c30-11e8-96a7-10841bc4c5d4.png)

**Comment by jordan-wright** [comment]
Hi @manoxus, thanks for reaching out.

Are there any logs from the time that the SMTP connection was occurring? I don't see any information about that in the screenshot you posted.

Also, I recommend checking out the [other various Gmail related issues](https://github.com/gophish/gophish/search?q=gmail&type=Issues&utf8=%E2%9C%93) in the past if you haven't already. There's been quite a bit of discussion in those issues that may help you resolve the issue.

**Comment by manoxus** [comment]
Unfortunately I don't have access to logs from gmail and having a similiar issue with hotmail or other SMTP providers. Is there any recommended one ?

**Comment by atropineal** [comment]
when using gmail as the sender, try gmail-smtp-in.l.google.com - works for me

when sending from a domain you control, make sure that spf, dkim and dmarc are set up correctly, and that the server's rdns entry is correct.  check how good your mailserver looks at https://mxtoolbox.com/diagnostic.aspx

also the content of your email will affect how spammy it looks, and being consigned to spam in one mailbox does not necessarily mean the same for another (e.g. i've had gmail/outlook mark something as spam but it's arrived at non gmail/outlook engagement client mailboxes with no issue)

**Comment by jordan-wright** [comment]
Generally, for running phishing simulations against your own organization, you almost certainly have infrastructure to send emails so you should use that as your SMTP server.

If you're a security provider running authorized simulations for customers you can create your own local sendmail instance and [set up SPF/DKIM/DMARC for your domain](https://www.trustedsec.com/2018/03/take-employees-phishing/) to help prevent getting caught in spam filters. However, I'd also recommend just working with the organization to get them to whitelist your sending IP addresses, since:

* This is an authorized simulation
* You're testing the people aspect of their security, not the infrastructure aspect.

Hope this helps!
