### ISSUE TITLE
Viewing Captured Credentials

### ISSUE THREAD

**Issue by mcreel31** [gophish/gophish#1023]
What version of Gophish are you using?: 
I am using version 0.5.0

Brief description of the issue:
I can see that credentials have been submitted, but cannot find where the credentials are stored. I have checked both "Capture Submitted Data" and "Capture Passwords."

Where can I view the submitted data?

I am experiencing the issue with all my landing pages, but as a simple test I copied some html from a different issue (#510). Whenever I make the action "post" (as suggested in that issue) and save the template, the action is blank when I reopen it.

![image](https://user-images.githubusercontent.com/19213753/37719649-d66939d8-2cfb-11e8-9ddf-866b8a4fba2b.png)

Thanks in advance for the help!

**Comment by mcreel31** [comment]
The code must be correct, I've found submitted credentials after exporting raw events from the campaigns page. Is there anywhere in the interface where captured credentials are updated in real time?

**Comment by jordan-wright** [comment]
Hi @mcreel31, if you expand a result in the UI, you should see an entry for captured credentials that you can expand to view the data.

You can see a screenshot here: https://twitter.com/jw_sec/status/694745865198514176

Hope this helps!
