### ISSUE TITLE
Maximum number of users per campaign

### ISSUE THREAD

**Issue by Microv** [gophish/gophish#1024]
Hi, 

is there a limit of users to be included in a single campaign?

If I try to import a CSV file with 3000 records, may I have problems?

Thank you.

**Comment by S0larflare** [comment]
You should be fine. I have ran campaigns with double the number of targets without issue :)

**Comment by GregCFTS** [comment]
When I imported a large CSV file, it took a moment to load, don't refresh the page or close it down. Just wait and it should be good.

**Comment by zsk009** [comment]
We have found campaigns of 5000 or more to slow down the UI considerably almost to the point of being unusable. Are there any plans to improve the interface response time on large campaigns?

**Comment by S0larflare** [comment]
Since the map has been removed, I don’t notice much of an issue with large campaigns anymore. There’s a small delay while the status is first fetched, but it isnt too severe

Sent from my iPhone

On 22 Mar 2018, at 21:49, zsk009 <notifications@github.com<mailto:notifications@github.com>> wrote:


We have found campaigns of 5000 or more to slow down the UI considerably almost to the point of being unusable. Are there any plans to improve the interface response time on large campaigns?

**Comment by jordan-wright** [comment]
@zsk009 what version of Gophish are you using, and where in the UI is it sluggish? I do have concrete ideas of ways we can make this faster, but it'll take some work for sure. If there's an area in particular you're experiencing problems, let me know and we can work together to try and make it better.

FWIW, the API should always be snappy as a last resort 😄 

And @Microv, @S0larflare is correct, it'll work but for now you'll just need to give it a bit to process the CSV.

**Comment by zsk009** [comment]
Thanks for the support @jordan-wright 
We are running Gophish 0.4. The part of the UI that gives us the most issue is when we want to view the results of a large campaign. 

For example, if I go to the Campaign -> Details of a campaign of 5000 users, the initial load of the page takes about a minute, and every action performed (clicking on complete button, export csv button, etc) also takes about a minute per click. The larger the campaign is, the longer these actions take. 

Please let me know if there is anything specific we can provide to assist. Thanks.

**Comment by rfdevere** [comment]
Use the API, ran 50k groups before - USE A HIGH SPEC SERVER

**Comment by jordan-wright** [comment]
Hi everyone,

Since the original question has been addressed and there haven't been any updates to this in a while, I'm going to go ahead and close this out.

Thanks again for getting in touch!
