### ISSUE TITLE
Can't establish gophish as a service

### ISSUE THREAD

**Issue by hybrok** [gophish/gophish#1031]
What version of Gophish are you using?: 
v0.4.0

Brief description of the issue: 
I'm able to get gophish to work properly when using ./gophish, but not as a service

What are you expecting to see happen? :
Gophish to start at boot up

What are you seeing happen?
Gophish does not start

Please provide any terminal output that may be relevant below:

These are the steps that I have taken to install gophish on Ubuntu 16.04 on Digitalocean server.
```
Setup ufw firewall

ufw reset
ufw default deny incoming
ufw default allow outgoing
ufw allow 80/tcp
ufw allow from [my ip address] to any port 3333 proto tcp
ufw allow from [my ip address] to any port 22 proto tcp
ufw enable
ufw status

2. Install go

# cd into /tmp for install
cd /tmp

# Download archive
curl -LO https://storage.googleapis.com/golang/go1.8.1.linux-amd64.tar.gz

# Verify download's hash
sha256sum go1.8*.tar.gz && echo a579ab19d5237e263254f1eac5352efcf1d70b9dacadb6d6bb12b0911ede8994

# Install gophish
sudo tar -C /usr/local/ -xvzf ./go1.8.1.linux-amd64.tar.gz

# Create Go workspace
mkdir -p /opt/goapps/{bin,pkg,src}

# Setup path for Go
sudo vim /etc/profile.d/path.sh

# Add the following line, then save and exit:
export PATH=$PATH:/usr/local/go/bin

# Configure environment variables
vim ~/.bash_profile

# Add the following lines, then save and exit:
export GOBIN="/opt/goapps/bin"
export GOPATH="/opt/goapps"

# Apply the changes
source /etc/profile && source ~/.bash_profile
3. Install gophish
cd /opt/goapps/src
mkdir gophish
cd gophish
wget https://github.com/gophish/gophish/releases/download/v0.4.0/gophish-v0.4-linux-64bit.zip
sudo unzip gophish-v0.4-linux-64bit.zip 
sudo mv gophish-v0.4-linux-64bit/ gophish/

4. Install letsencrypt

Download LetsEncrypt certbot:

sudo wget https://dl.eff.org/certbot-auto 
sudo chmod a+x certbot-auto

Create the DNS cert challenge.

./certbot-auto certonly -d [my domain name] --manual --preferred-challenges dns 


These Certs will be output to /etc/letsencrypt/live//. I typically move them out to the Gophish directory out of laziness.

sudo cp /etc/letsencrypt/live/[my domain name]/fullchain.pem ./domain.crt 
sudo cp /etc/letsencrypt/live/[my domain name]/privkey.pem ./domain.key

vim config.json

Change the config file to point to your new certs, and to listen on port 443.

"phish server" : {
	"listen_url" : "0.0.0.0:443",
	"use_tls" : true,
	"cert_path" : "domain.crt",
	"key_path" : "domain.key"

Change the following line.

"admin_server" : {
	"listen_url" : "[my ip address]:3333",


You can now start Gophish, be sure to change the default password.

sudo ./gophish

5. Gophish as a service - this part is where it fails

sudo vim /etc/init.d/gophish

Copy and paste in this code into the file:

#!/bin/bash
# /etc/init.d/gophish
# initialization file for stop/start of gophish application server
#
# chkconfig: - 64 36
# description: stops/starts gophish application server
# processname:gophish
# config:/opt/goapps/src/gophish/gophish/config.json

# define script variables

processName=gophish
process=gophish
appDirectory=/opt/goapps/src/gophish/gophish
logfile=/var/log/gophish/gophish.log
errfile=/var/log/gophish/gophish.error

start() {
    echo 'Starting '${processName}'...'
    cd ${appDirectory}
    nohup sudo ./$process >>$logfile 2>>$errfile &
    sleep 1
}

stop() {
    echo 'Stopping '${processName}'...'
    pid=$(/usr/sbin/pidof ${process})
    kill ${pid}
    sleep 1 
}

status() {
    pid=$(/usr/sbin/pidof ${process})
    if [[ "$pid" != "" ]]; then
        echo ${processName}' is running...'
    else
        echo ${processName}' is not running...'
    fi
}

case $1 in
    start|stop|status) "$1" ;;
esac

Run the following commands to finish setup:

apt -y install sysv-rc-conf
chmod +x /etc/init.d/gophish
sysv-rc-conf --level 2345 gophish on


Restart the server:

Shutdown -r now

```

**Comment by jordan-wright** [comment]
Hi @hybrok - thanks for reaching out!

I'm afraid I'm not too familiar with troubleshooting Linux services that aren't starting up on boot. Is there perhaps any logfiles you could check to see why this might be the case?

**Comment by acklenx** [comment]
This helped me remendously: https://medium.com/@immure/setting-up-gophish-on-aws-c2f2fd78b7e9
(after I remembered you have to hit port 3333 and NOT port 80)

I ran into this problem with not being able to get the service to start a couple of different ways.  I didn't have sufficient privileges.  I see you're using sudo in your script so none of this may apply... But I installed as root but the service didn't run as root.  So I created a gophish user with permissions to access the gophish files.  But then that gophish user didn't have permission to listen on port 80.  So I used this command:

setcap 'cap_net_bind_service=+ep' /opt/gophish/gophish

that set the capabilities of the gophish to include binding to port 80.  In one install it worked but in another it did not.  I think you actually have to enable and start the service (and maybe stop it too) and then run that command.  Some combination of stopping, starting and rerunning setcap did it for me (not terribly helpful, but maybe it will jog someones mind).

**Comment by justaskingquestions** [comment]
Another (a bit more elaborte) option to handle the whole privileged ports issue is to use an actual webserver like like nginx or apache as a reverse proxy. The web server acts as a front and handles the communication with the gophish server while being transparent to the "victim" accessing the page. This as the added benefit that you do not need to make the gophish ports accessible from an external IP but only from the system your reverse-proxy is running on (be it the same box or another one)

**Comment by glennzw** [comment]
> when ever I try to launch gophish by "sudo ./gophish" its saying command not found. I'm using kali linux OS 64bit

If you're still stuck please open a new issue. 

Closing this one out.
