### ISSUE TITLE
Recommendation of smtp mail servers or third party service to use for gophish

### ISSUE THREAD

**Issue by brijq** [gophish/gophish#1032]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.5.0
Brief description of the issue: 
Recommendation of smtp mail servers or third party service to use for gophish
What are you expecting to see happen? :
Nil
What are you seeing happen?
Nil
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:
Nil
```html
Insert code here
```
Nil
Please provide any terminal output that may be relevant below:
Nil
```
Insert output here
```
Nil
Please provide as many steps as you can to reproduce the problem:
Any good recommendation for third party mail service or any programs to introduce? As I am still struggling to find a good third party mail server or service to use. 

 Please note that considering the issues as vm is set up in GCP as port 25 is blocked only 2525 is opened instead.

**Comment by jordan-wright** [comment]
Hi @brijq - thanks for reaching out!

The issue of which mail provider to use has been discussed recently in #1007. The features of mail providers will be very similar across the board, but the trick to make it work well is to be as transparent as possible when running phishing campaigns. That helps the mail provider understand what you're trying to accomplish with your campaigns.

Hope this helps!

**Comment by VTH8** [comment]
https://github.com/gophish/gophish/issues/2591#issue-1366944013

**Comment by VTH8** [comment]
#2591 https://github.com/gophish/gophish/issues/2591#issue-1366944013

**Comment by VTH8** [comment]
What version of Gophish are you using?: gophish-v0.12.0-windows-64bit

Brief description of the issue: I have setup the sending profile properly, but when I try to have a test mail then I'm getting may errors

What are you expecting to see happen? : send test mail

What are you seeing happen? getting error "501 5.1.7 Invalid address" and not sending test mail

Please provide any terminal output that may be relevant below:
Screenshot 2022-09-09 013023
Screenshot 2022-09-09 013209

Insert output here
Plz, anyone provide solution for this....

**Comment by VTH8** [comment]
What version of Gophish are you using?: gophish-v0.12.0-windows-64bit

Brief description of the issue: I have setup the sending profile properly, but when I try to have a test mail then I'm getting may errors

What are you expecting to see happen? : send test mail

What are you seeing happen? getting error "501 5.1.7 Invalid address" and not sending test mail


Please provide any terminal output that may be relevant below:
![Screenshot 2022-09-09 013023](https://user-images.githubusercontent.com/112782175/189217201-c7ecf44b-38fc-43b8-a46a-b1acf3f9f0b7.jpg)
![Screenshot 2022-09-09 013209](https://user-images.githubusercontent.com/112782175/189217256-2ef9c9f7-219d-4c5b-bc24-99dae4d2c131.jpg)

```
Insert output here
```

Plz, anyone provide solution for this....
