### ISSUE TITLE
Feature Request: Throttle Email Option

### ISSUE THREAD

**Issue by rmikehodges** [gophish/gophish#1033]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
v0.5.0

Brief description of the issue: 
When attempting to send to multiple participants through Office 365, the messages per minute limit will block emails requiring that targets be split up into small groups on different campaigns.

What are you expecting to see happen? :
I would like it if you could specify a throttle value that would throttle the sending of emails per minute such as 30 emails per minute or 5 emails per minute.

What are you seeing happen?
Emails are all sent at once.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi @rmikehodges - thanks for reaching out!

Throttling the email sending is something that's been on our radar for a while, and is one of the very next things we plan to knock out. There's been other issues such as #611, #110, and #501 that discuss the various ways we might approach this. To try and keep things consolidated, I'm going to go ahead and close this one out in favor of those.

I'll keep you updated and thanks again for getting in touch! 😄
