### ISSUE TITLE
Having trouble getting the email link to work/ email doesn't track if it's been opened or if they clicked the link

### ISSUE THREAD

**Issue by schrute-farms** [gophish/gophish#1038]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.5.0

Brief description of the issue: I cant get the email link to go to the correct website and the campaign won't track anything after the email is sent

What are you expecting to see happen? :
take the user to the correct website and track results
What are you seeing happen?
404 error and no tracking details
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:
Landing page: ********************************
sending SMTP: ***************
```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - build campaign
 * Step 2 - use outgoing IP of my machine (the one i'm using for gophish) to start campaign

**Comment by S0larflare** [comment]
I think you’ve misunderstood how it works a little. The page you have created and linked here needs to be made within GoPhish. Take the html there and create a landing page, then for the campaign url use the ip/domain name of your GoPhish server and choose your landing campaign.

**Comment by schrute-farms** [comment]
Thanks for the quick responce
Excuse me for being a bit inexperienced here but here's what i've done and still have questions about:
1) imported the sharefile link I posted to create the landing page, I currently have the same link as the redirect - should I change that? 
2) how do find the ip of the gophish server?
thanks for the help

**Comment by S0larflare** [comment]
1. Yes, the ‘campaign url’ needs to be to your phish server, for example http://gophish.com

2. It is the IP address / hostname of the server you have installed GoPhish on and are connected to when you are setting up the campaign (just make sure you use the ‘phish server’ rather than the ‘admin server’ details (the one that defaults to  be port 80 rather than 3333)

Sent from my iPhone

On 11 Apr 2018, at 21:01, schrute-farms <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the quick responce
Excuse me for being a bit inexperienced here but here's what i've done and still have questions about:

  1.  imported the sharefile link I posted to create the landing page, I currently have the same link as the redirect - should I change that?
  2.  how do find the ip of the gophish server?
thanks for the help

**Comment by schrute-farms** [comment]
so if I installed go phish on my machine it is just my ip address?

**Comment by S0larflare** [comment]
Yes, so it would be the public ip address. Your phishing server needs to be reachable by your targets

Sent from my iPhone

On 11 Apr 2018, at 21:10, schrute-farms <notifications@github.com<mailto:notifications@github.com>> wrote:


so if I installed go phish on my machine it is just my ip address?

**Comment by schrute-farms** [comment]
the test takes me to a blank page now, It still isnt collecting data.

**Comment by S0larflare** [comment]
Are you using {{.URL}} in your email template?

**Comment by schrute-farms** [comment]
I updated the email URL (thanks for the help with that), it takes the test account to the right website now but I still cant get it to track weather the email was opened or if the link was clicked

**Comment by jordan-wright** [comment]
> it takes the test account to the right website 
>  still cant get it to track weather the email was opened or if the link was clicked

This doesn't quite make sense to me. If you're seeing the correct page when you click the link, then it should be tracked. What do you see in the URL bar when you click the link? Do you see the connection attempt in the Gophish terminal? If it's not pointing to your Gophish instance, then you'll need to revisit what you're putting in the "URL" field when building a campaign.

**Comment by schrute-farms** [comment]
I have been using my IP address followed by :80 (xx.xxx.x.xx:80)

**Comment by schrute-farms** [comment]
that was my understanding of this comment earlier in the thread, maybe I misunderstood.  
"It is the IP address / hostname of the server you have installed GoPhish on and are connected to when you are setting up the campaign (just make sure you use the ‘phish server’ rather than the ‘admin server’ details (the one that defaults to  be port 80 rather than 3333)"

**Comment by S0larflare** [comment]
![image](https://user-images.githubusercontent.com/8939757/38735971-63cd2b1c-3f22-11e8-9d4c-5f25dc52c5bb.png)

**Comment by schrute-farms** [comment]
I have used mp ip and my ip:80, both do not work. The link goes straight to the page without showing that it connected to my ip first.

**Comment by S0larflare** [comment]
If you have used {{.URL}} in your email template, then when you hover over the link you should see something similar to

`http://192.168.0.5/?track=bfH7rGA`

is that what you see?

**Comment by jordan-wright** [comment]
To add to this, we still need your answers to the other questions in my previous comment. We need to know:

* What do you see when you hover over the link in the email?
* What do you see in the URL bar when you click the link?
* Do you see the connection attempt in the Gophish terminal?

**Comment by schrute-farms** [comment]
I have made a few changes to the email template but I am still getting the same result, the url shows the IP address I have for the campaign, after I get it to work correctly I want the link embedded in the word "here" but for now I am sticking with {{.url}}
1. when I put the mouse on the URL it shows the website I want it to link to (sharefile)
2. when I click the link, it shows what i am assuming is the IP for a split second (not long enough for me to verify what it is) then goes to the page I have set for it to link to 
3. I'm not sure what you mean by this or where to view the terminal, on the senders end or the receivers end?

**Comment by jordan-wright** [comment]
> when I put the mouse on the URL it shows the website I want it to link to (sharefile)

What you want to see is the IP address/domain name that points to your Gophish server. If it's pointing to an external site, then there's no way we can record that the link was clicked. If you don't see an address that points to your Gophish server, you'll need to adjust what you're using as the "URL" field when creating a campaign.

> I'm not sure what you mean by this or where to view the terminal, on the senders end or the receivers end?

I'm asking if you see any log entries in the window running Gophish when the link is clicked. If the link is pointing to your Gophish server, you should see an access log for that connection attempt.

**Comment by jordan-wright** [comment]
Awesome! Glad you were able to get this to work.

The best way to avoid spam filters is either to whitelist the Gophish mail server (recommended and shouldn't be a problem if you have permission to use Gophish to test an organization's exposure to phishing) or to follow best email practices. You can find more information [here](https://www.trustedsec.com/2018/03/take-employees-phishing/).

Since the original issue has been cleared up, I'm going to go ahead and close this one out. Thanks again for getting in touch, and please don't hesitate to let us know if you continue to run into issues!
