### ISSUE TITLE
SMTP not working

### ISSUE THREAD

**Issue by sbisschop** [gophish/gophish#1040]
What version of Gophish are you using?: 

GoPhish v0.5

Brief description of the issue: 

I have installed GoPhish in Kali Linux and i've set up a MailHog SMTP server. However when I try to send a test mail, it won't work. 

GoPhish: 
127.0.0.1 - - [12/Apr/2018:14:50:48 -0400] "POST /api/util/send_test_email?api_key=7685951bd658130cbbb286085db95d18ee0b05e8571f58eb4f5d463a3205b4d1 HTTP/2.0" 500 86 "https://127.0.0.1:3333/sending_profiles" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
 2018/04/12 14:51:08 mailer.go:78: Mailer got 1 mail to send
 2018/04/12 14:51:24 mailer.go:78: Mailer got 1 mail to send

MailHog:
2018/04/12 14:50:48 [SMTP 127.0.0.1:54952] Starting session
2018/04/12 14:50:48 [SMTP 127.0.0.1:54952] [PROTO: INVALID] Started session, switching to ESTABLISH state
2018/04/12 14:50:48 [SMTP 127.0.0.1:54952] Sent 35 bytes: '220 mailhog.example ESMTP MailHog\r\n'
2018/04/12 14:50:48 [SMTP 127.0.0.1:54952] Received 11 bytes: 'EHLO kali\r\n'
2018/04/12 14:50:48 [SMTP 127.0.0.1:54952] [PROTO: ESTABLISH] Processing line: EHLO kali
2018/04/12 14:50:48 [SMTP 127.0.0.1:54952] [PROTO: ESTABLISH] In state 1, got command 'EHLO', args 'kali'
2018/04/12 14:50:48 [SMTP 127.0.0.1:54952] [PROTO: ESTABLISH] In ESTABLISH state
2018/04/12 14:50:48 [SMTP 127.0.0.1:54952] [PROTO: ESTABLISH] Got EHLO command, switching to MAIL state
2018/04/12 14:50:48 [SMTP 127.0.0.1:54952] Sent 16 bytes: '250-Hello kali\r\n'
2018/04/12 14:50:48 [SMTP 127.0.0.1:54952] Sent 16 bytes: '250-PIPELINING\r\n'
2018/04/12 14:50:48 [SMTP 127.0.0.1:54952] Sent 16 bytes: '250 AUTH PLAIN\r\n'
2018/04/12 14:50:48 [SMTP 127.0.0.1:54952] Received 6 bytes: 'QUIT\r\n'
2018/04/12 14:50:48 [SMTP 127.0.0.1:54952] [PROTO: MAIL] Processing line: QUIT
2018/04/12 14:50:48 [SMTP 127.0.0.1:54952] [PROTO: MAIL] In state 6, got command 'QUIT', args ''
2018/04/12 14:50:48 [SMTP 127.0.0.1:54952] [PROTO: MAIL] Got QUIT verb, staying in MAIL state
2018/04/12 14:50:48 [SMTP 127.0.0.1:54952] Sent 9 bytes: '221 Bye\r\n'
2018/04/12 14:50:48 [SMTP 127.0.0.1:54952] Session ended

![image](https://user-images.githubusercontent.com/38330985/38698285-d3169b9a-3e94-11e8-9c2b-0afe2dc2e4cd.png)

Could anybody help me?

**Comment by jordan-wright** [comment]
Hi there, thanks for reaching out!

Are there any other messages that appear in the Gophish logs as the email is sent? Something makes me think that there's an issue actually rendering the email (parsing the template).

I'd also recommend reviewing the template for any cases where you use the `{{x}}` template syntax to make sure it matches the list of [valid template variables](https://gophish.gitbooks.io/user-guide/content/template_reference.html).

**Comment by jordan-wright** [comment]
Going ahead and closing this out since there haven't been any updates in a week. @sbisschop if you're still running into issues, please provide the information requested above and I'll be happy to re-open and continue troubleshooting.

Thanks again for getting in touch!

**Comment by Yashvendra** [comment]
Hey @jordan-wright, I have setup mailhog and gophish. When I try to send testmail to a target email id, it says email sent. When I open my inbox, I see no test emails from gophish both in inbox and spam. And when I open my **mailhog** inbox, I see one email has been received. but I want that email to reach the target email Id through mailhog.

Gophish sent the mail:
<img width="403" alt="gophish3" src="https://user-images.githubusercontent.com/23001311/87137067-f26a1c00-c2b9-11ea-8bb4-1140176a3722.PNG">

MailHog Received the mail:
<img width="952" alt="gophish-mailhog" src="https://user-images.githubusercontent.com/23001311/87137039-ea11e100-c2b9-11ea-90c4-00dfc0c0fcf3.PNG">

Can you please tell me how will I be able to send mails to the target email address through mailhog??
