### ISSUE TITLE
Campaign not found looks messy

### ISSUE THREAD

**Issue by S0larflare** [gophish/gophish#1041]
This is pretty picky of me, but in a previous version of gophish, if I went to an invalid campaign in the console, I would be greeted with this:
![image](https://user-images.githubusercontent.com/8939757/38739377-ad27ca56-3f2c-11e8-8a5c-0fb4c5d26a92.png)

But in the latest version, I get this:
![image](https://user-images.githubusercontent.com/8939757/38739429-d10cdcb8-3f2c-11e8-9117-8b13dc0b0a84.png)

Like I say, very picky, but could we stop the table from being drawn?

**Comment by jordan-wright** [comment]
Ewww.... yeah, that doesn't look good. I'll fix that.

Good call!

**Comment by jordan-wright** [comment]
All fixed. Sorry about that! Thanks for letting me know about it.
