### ISSUE TITLE
Documentation API not available

### ISSUE THREAD

**Issue by Cycl0pe** [gophish/gophish#1050]
Hi,

I just figured out today that the documentation for the API (https://getgophish.com/documentation/api/) give me a 404.

Cycl0pe

**Comment by jordan-wright** [comment]
Hi @Cycl0pe - thanks for reaching out!

Where are you seeing that link? The current website points to https://gophish.gitbooks.io/api-documentation/content/ which appears to resolve fine for me. It's possible we have an outdated link somewhere so if you can help us track it down I'll be happy to get it fixed 😄

**Comment by jordan-wright** [comment]
Closing this since there haven't been any updates in about a week. @Cycl0pe if you could let us know where you ran into that error, I'll be happy to track it down and get it fixed.

Thanks!
