### ISSUE TITLE
How to delete "Users & Groups" using api?

### ISSUE THREAD

**Issue by dipeshpatel306** [gophish/gophish#1054]
Hello, 

     I'm trying to delete phishing campaign and user group using api. I am able to delete campaign but not able to delete user's group.  anybody know how to delete user's group using api?

**Comment by jordan-wright** [comment]
If you're using the Python API client, you can use `api.groups.delete(group_id)` as shown [here](https://gophish.gitbooks.io/python-api-client/content/groups.html).

If you're doing this some other way, you just need to send `DELETE /api/groups/<id>`.

Hope this helps! If you encounter errors, let us know and we can troubleshoot.

**Comment by dipeshpatel306** [comment]
@jordan-wright  thanks its deleting as an aspected.
