### ISSUE TITLE
Landing page downloads corrupt file or 404

### ISSUE THREAD

**Issue by acklenx** [gophish/gophish#1055]
What version of Gophish are you using?: 
5.0

Brief description of the issue: 
Landing pages don't show any content and even trying to load static (issue 220) content does not work

What are you expecting to see happen? :  
I would expect to have to landing page load when a use clicks on link in the email template `<a href="{{.URL}}">test link2</a>`

What are you seeing happen? 
The page either shows a 404 if I make a request without the ?rid=xxxx (which is expected, if undesirable - there are many tickets for this).  But when I request a page with the ?rid=xxxx some iberish is immediately downloaded.  But I want to see my landing page!  I get the 404 behavior if I request a static resource such as http://mydomain.com/static/gophish_purple.png 

!! As I was search for more example urls it suddenly started working!  https does not work  (but I have tls set to false on port 80 and true on port 3333 (using the same let encrypt certificates for both ports). I will restart with tls true since that's the way I want to landing page to be served (https).  OK with TLS true when I request/reload the same page (still http), a file downloads and the server logs the message: 
`2018/05/04 04:46:29 http: TLS handshake error from 23.137.95.56:46192: tls: first record does not look like a TLS handshake`
(ip address slightly munged to protect the guilty ;)
Ideally http would automatically redirect to https.  changing the protocol to https and reloading gets a connection refused message in the browser and no log entry on the server.  So it looks like things work if I only use HTTP (which is definitely less than desirable).

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

Landing page below (works with http)
```html
<html><head><base href="http://54.148.147.161/Presentation/"/>
<link rel="shortcut icon" href="http://34.215.171.221/Presentation/favicon.ico"/>		<style>
			body {
				color: #212121;
				font-family: roboto, arial, sans-serif;
				font-size: 14px;
			}

			main {
				position: relative;
				height: 100%;
				width: 100%;
				margin: 0 auto;
				resize: both;
				overflow: auto;
			}

			.box {
				background: white;
				width: 370px;
				height: 420px;
				transform: translate(-50%, -50%);
				position: absolute;
				top: 50%;
				left: 50%;
				padding: 40px;
				overflow: none;
				box-shadow: 1px 2px 3px gray;
			}

			.boxFooter {
				position: absolute;
				bottom: -40px;
				width: 450px;
				left: 0px;
			}

			input {
				border-top: none;
				border-left: none;
				border-right: none;
				width: 100%;
			}

			.link {
				color: #4285f4;
				font-size: 14px;
				cursor: pointer;

			}

			.text {
				font-size: 14px;
			}

			.button {
				font-size: 15px;
				color: white;
				background-color: #4285f4;
				cursor: pointer;
				padding: 10px 22px;
				float: right;
				border-radius: 3px;
				box-shadow: 1px 2px 5px gray;
			}

			.otherLink {
				color: #757575;
				cursor: pointer;
				float: right;
				margin-left: 32px;
				font-size: 12px;

			}

			.smaller {
				font-size: 12px;
				cursor: pointer;
			}
		</style>
		<script>
			function login()
			{
				var id = document.getElementById( "email" ).value;
				document.location.href = document.location.href + "/ERROR/?userId=" + id;
			}

			function checkLogin( event )
			{
				if( event.which === 13 || event.keyCode === 13 )
				{
					login();
					return false;
				}
				return true;
			}
		</script>
	</head>
	<body background="bg.png">
		<main>

			<div class="box">
				<div>
					<table width="380">
						<tbody><tr>
							<td>
								<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEkAAAAYCAIAAAA5w0fZAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4gIWEAwUMqNzCwAABm1JREFUWMPVV01MG2cafubHeGDGBbQKNpFqWpKCVKl2GpQeCpTVaokPSxql5JBoKVwStk2qSgltclqicivdEmmlIHXbC1G7m0PYqoFKC2mlAnEOXSWNXSlSHMjKHMBDtsXGM2HGnplvD98wDIOh21xC3tP486v55nl/nud9GUIIXJbJkXjKiN8zZ2VT1QEgGuaaG7nmBj5UyeBJ292f51YNTSqraKx6/hedGQebouHyTGH038WSfqIfR18p6271PVlsXRPv38v+Z/+uFz/53cAvOvMOsLNfrM7JFv0ZfIaJ1nGhKiaTJYm0Ka8QVcfITIGA9LSW4Skx3gOsvoY93V62r45zO91Jm4NjuigwnQeeGmA2tkvXdQrs1Re484cESfA67avj/naiAsDmv3Y0tkyOTP5o0DosCYza04XKxjb6vU0ePa+VPTYAouSNufsAuGCIDe3eznN5CgzDCGEIz23lo2iYW7IARMPs//kBVmbBlDMAfNH969hmZZM+xSL8Y6CyMgvq5c+0yXHnhA3WBk6dKWv+7QY/I2um3iOLl9cJuvo19vk/M9VtHlTD3+gTScMh59Pt/lnZmpOtPUH2dHuJbi/Ev8sPX7TkRfu1oiT29Ja/cQwAn5y3AERKRWgiaTjXeGyoSwBgzKayfW8RVdmAVl7MXTgXeL9fiHXYR/k7xu12GLmNCZw2l9u5Fz9lanvoyaxsnf18lYoqNVXH4Lj9m4Bs/gxtYjz/0QYxIKqiDA+ZiwvS6bPb5SqTsxLz5jYOuf73KLDyI8eEWAcrSYXEbWX4Y6Kq+Y8GuFCtL9oEwEgepcDYZ99hdh1myuuspWvWgwGYK+bdk5zwHM3eh2M6BXbwJT4W4SWBSaTN4W8K25QMBcaIonSqz9/cRpR8fniocHN69csr/pY2PvgMI68QOVciKqFK1pNPOUvkFeLEzFrKAKh484TY00sPhdBufk/D8ltdAB6N/qMy2kQWR6DNU2Bsw5Bdt+F3mUDUvN0OwJr/K1fdNpE0HixZAN444HNqb2+QlQTGSZ3HHo1eoQ+VA3+hQSRKnlvrdvXyp/yeICuvmHKOZHLEM1XFIrynCT8c0ympAtDj39GHis7jG9hpb4Mv8nIx+UPh5jQAa+majae+f8NAVN3GVLWS7Az57xiAG/fs13pmg1iEH5kuOAF1WzFxCwBf/4Iv2lRM3Hr0zyuF+JR9V01IONjBtzTyN++bAEamC+cP+bdnjkTadJqTKHn6akYKeNx80aZi8geHRQBACIOv8s571W0kO2OziE6oDm3m6mAVUxKb8eA+AEtVfvrjYYdLhIN/EGIdNI28E5jJH41YhPdMJG4b/b5I72hp4D0XeDth7SZX18+X0AMt7TkpiUHRthiFRZGoKr2LrQkJsY6KzuPuQLMATh2009V/VbuTLk0eN1LmyEyB8nIs4gPgX2P5wlpxOlqnx6doSmly7POHX3lUgTy8BgBSxB2vGynTs5fQPtxsNDkApLfP/Obv18SeXgqMKHlaUyyAlgaODviqjr4vtMFxPe66IJ4yB8f1C1c1SmIDR+3Zxd/cxogigJXBAVr6lLuyfW/b5Nl5HAC7u5v+Zd49QZan1uXOIc/abgDNjbzoB4DBsfX4ZnKk/6q2VR05fa5Nfk3BOB/w85+6iolb6zvORNLYipHcSupmF7e8sMFaVgoYcyk7qJGXq4Y+sTO2OGLePbk2vEUZXyVZnrbrqqqVa/p28wfsCbKSn3ErUCTMXuwq9+w4+cEPtMmv19K4H0AxcZv+LD9yjHczUrSOG5kuOEzotkiYPX9I8BApVWcqaJa86LRZ+ZFjYs/J9cao7eEA814fzBUoCael2GffcZMnjdql67qqw9m26mtYAA+WLMlfYjMOnLvAiIHVL6+4UTGiKHb3lnceZzx7N+3deMrI5CxH5aJ13DZLN20wM7MAgJUC/ua20iOlkSUPvyKraaKlGaGO3fU6AvtKMsdEspjJEapvsQj/+seqqqO71bfV6mhlFvT4lJlZZCSJlQJCrIM2XglsT9BupMx9Yc4tA4qGw0MqgFO/L+t85ddt/fwOQaVo6P3skbxCYhH+XMe6zF66bndgdGtx2unYJMHW6ImkkcmS5kZO1XAnbVI6iYTZvUH2175zB9WkouHM56ub1ay+hr3YVf4Yu+XO6jeqBP9KFudkS9VRX8O2NHKdBx5zaf4f5wUXgrzUN4gAAAAASUVORK5CYII="/>
							</td>
							<td></td>
						</tr>
						<tr>
							<td>

								<br/>
								<span style="font-size:24px;">Sign in</span>
								<br/>
								<span class="text">with your <span class="letter">G</span><span class="letter">o</span><span style="display:none;">0000</span><span class="letter">o</span><span class="letter">g</span><span class="letter">l</span><span class="letter">e</span> Account</span>
								<br/>
								<br/>
								<br/>
								<br/>

							</td>
						</tr>

						<tr>
							<td>
								<input name="email" id="email" onkeypress="checkLogin(event)" type="text" placeholder="Email or phone"/>
							</td>
						</tr>
						<tr>

							<td>
								<br/>
								<br/>
								<span class="link">Forgot email?</span>
								<br/>
								<br/>
								<br/>

							</td>

						</tr>
						<tr>
							<td>

								<span class="link">More options</span>

								<div class="button" onclick="login()">NEXT</div>
							</td>
						</tr>
					</tbody></table>
					<div class="boxFooter">
				<span class="smaller">
				English (United States)
				</span> <span class="otherLink">Terms</span> <span class="otherLink">Privacy</span>
						<span class="otherLink">Help</span>
					</div>
				</div>
			</div>

		</main>
	

</body></html>
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - edit config.json and set phish_server.use_tls = false   (this is the default)
 * Step 2 - restart gophish
 * Step 3 - click on email link with rid set
 * Step 4 - observe page loads properly

 * Step 5 - edit config.json and set phish_server.use_tls = true   (this is the default)
 * Step 6 - restart gophish
 * Step 7 - click on email link with rid set
 * Step 8 - observe page does not load at all - ERR_CONNECTION_REFUSED

**Comment by acklenx** [comment]
What a maroon!  After posting I resigned myself to running with just http, no tls, on port 80.... duh.  I change the port to 443 and tls works now!  Of course http on port 80 doesn't work, but since I control that links that's OK (even if a bit odd).  And static content will still not load for me even with the rid appending - /static/gophish_purple.png?rid=KmAskiE

**Comment by jordan-wright** [comment]
Glad you were able to get it figured out! You're correct that if you want to load the landing page over HTTPS, you have to set the port to 443, use_tls to True, and set the TLS cert/private key.

If you're still running into issues serving the static content, I recommend giving the bottom of [this page](https://gophish.gitbooks.io/user-guide/content/documentation/landing_pages.html) a read if you haven't already. Otherwise, feel free to open a separate issue for us to troubleshoot the static file serving.

In the meantime, I'm going to go ahead and close this one out since the root issue (how to load the landing page over HTTPS) has been solved. Thanks for getting in touch!
