### ISSUE TITLE
RFC: Let's Talk About Transparency

### ISSUE THREAD

**Issue by jordan-wright** [gophish/gophish#1057]
Hello everyone!

I wanted to take a moment to let you know about some important upcoming changes to Gophish and to hear your feedback before implementing these changes.

The goal behind all of these changes is simple: **We can do a better job of running friendly phishing simulations.**

### The Problem

Over the past few months, I've heard from service providers having to investigate phishing exercises conducted with Gophish. The scenario is usually straightforward - an organization launches a phishing simulation that spoofs the service provider's brand, sending out fake phishing emails to employees. These emails are reported back to the service provider using standard spam feedback loops/tools, and the service provider must now investigate if this is an authorized exercise or a legitimate phishing campaign targeting users.

Unfortunately, the way Gophish is current set up, it's difficult for service providers to make this call. They have to try and figure out who and what is generating these emails, which causes them more time, energy, and money than necessary.

**This isn't ok. It's my fault things are this way. We can do better.**

### The Goals

I think with a few simple changes, we can make it much easier for service providers to respond to these incidents, quickly determining that the emails were generated with Gophish, and who to contact about these emails to verify it was a legitimate exercise.

However, when considering what changes to make, it's equally important to me to preserve your privacy.

That said, here's my proposal:

### The Solution

* **Add a contact address** - I will add a `contact_address` configuration parameter to `config.json` that can include an email address you would like to receive abuse reports at. This is the address service providers can use to contact you about potential phishing emails the detect. This will not be required, but Gophish will give a warning in the terminal every time it is started without one.

* **Show Information When Requested with "+"** - I will add an endpoint similar to the one [used by Bitly](https://support.bitly.com/hc/en-us/articles/230905028-What-is-the-Bitly-info-plus-page-) wherein a "+" added to the end of a **valid** `rid` parameter will return the contact address, if configured, as well as a simple message indicating the email was generated by Gophish.

* **Add an X-Mailer Header** - I will add an X-Mailer header that will default to the value "Gophish" to indicate to service providers that the email was generated with Gophish. You can replace this by specifying your own X-Mailer header in your sending profile.

* **Add an X-Gophish-Contact Header to Outgoing Emails** - If the contact address is configured, I will add an X-Gophish-Contact header with this address to all outgoing emails to let service providers know who to contact about the emails they are investigating.

* **Add a "First Run" Modal with Tips on Friendly Campaigns** - These changes are just one step towards running friendly campaigns. I plan to add a modal that pops up the first time (and only the first time) you run Gophish that gives other helpful tips on running good, friendly phishing simulations such as setting up proper WHOIS records, how to avoid directly spoofing brands, and more.

### Final Thoughts

As you can see, the (optional but recommended!) contact address and the fact you're using Gophish is only accessible with a valid email or a valid Gophish link (with the `rid` parameter), helping preserve your privacy.

I can almost certainly assure you these changes will not influence the success rate of your campaigns. In fact, if you have an astute user who reports an email based on these traits, **reward them!** This would be an incredible thing and a sign that your users care about suspicious emails.

Finally, please remember: **we're the "good guys"**. We don't want service providers to be spending their time looking into the well-intentioned, authorized exercises being conducted and instead focus their efforts on the actual people trying to phish our users and spoof their brand. These changes will help us be more transparent about what we're doing, saving them time and helping us run more friendly campaigns.

Please let me know if you have any questions / comments / other feedback!

**Comment by snori74** [comment]
Very pleased to see this. I've run foul of a couple of local banks in the past. so now keep my emails very bland. From discussion with their security teams I think however that they just don't like anyone using their brand, logos etc.

So, not sure that I'd get their blessing going in - but as you say, anything to make it easier for them to recognise that we're the 'good guys' doing authorised work is a plus.

My only suggestion is somewhere to add text such as "Authorized whitehat 'phishing test' campaign".

**Comment by jordan-wright** [comment]
Hey @snori74, thanks for the quick response!

> My only suggestion is somewhere to add text such as "Authorized whitehat 'phishing test' campaign".

Thanks for this suggestion!

My concern with something like this (and please let me know if I'm misunderstanding the intention) is that it might provide a false sense of security for the service provider, that perhaps we did something on our end to ensure that this is an exercise when it's _possible_ that in fact Gophish is being misused to run actual phishing campaigns (there unfortunately [have been incidents of this](https://citizenlab.ca/2017/02/nilephish-report/)).

Instead, my goal is that by just providing a contact address, service providers can choose to follow-up according to their protocols.

**Comment by snori74** [comment]
Fair point. In practice good contact details are probably the best approach.

**Comment by zados** [comment]
Hey @jordan-wright,

I think you made an excellent point as this is a real problem. I like the idea with the contact address and the extension of the link by using +. However if the "X-Gophish-Contact" header are added automatically, it is much more easy to spot the phish.

If some tech-savvy person looks at the headers, I am really happy as this means they are really checking the mail, **but** when I try to run a campaign to check where the standing of a company is when being attacked, those people might just check the headers for "X-Gophish-Contact" and then delete the email. But then still falling for the real phishing, as it does not contain the header and they cannot be sure if this is a valid mail.
Of course those people are a low percentage, but this needs to be considered.

I'd really like to set up the contact address, however there should be an option to disable the "X-Gophish" header.

**Comment by jordan-wright** [comment]
Hi @zados! Thanks for the feedback!

My plan was that if the `X-Gophish-Contact` header is provided in the SMTP profile, then we won't add it automatically. The same goes for the `X-Mailer` header. This will mean that for the majority of the cases, the headers will be added automatically, but you can "opt-out" if you want to. Let me know if this doesn't work for you!

And if a user manages to check the headers and recognizes that Gophish is a phishing simulation platform and then just deletes the email instead of reporting it to security, I'd recommend:

1) Definitely praise that user for being vigilant. That's really cool that they're in the vast minority of people who check email headers 🎊 
2) Suggest that instead of deleting the email, they should still report it. Who says it's not a malicious actor using Gophish to actually phish them? Sadly, since Gophish is self-hosted and open source there are the few people who do this ☹️

**Comment by zados** [comment]
Sounds like a good plan.

to 1.) Of course that is what I do ;-) But I still wanted to mention that danger.
to 2.) Exactly what I want to achieve. I am currently thinking on how to implement this in a proper way instead of emails or instant messaging. 

Thanks!

**Comment by stracire** [comment]
The best solution would be if everyone did configure and use their own mailserver for phishing tests. However configuring a mailserver isn't as easy as configuring Gophish. Maybe it would contribute to the cause if the manual does link to a good tutorial about configuring mailservers. Since nearly any online mailservice is happy with real of test phishing mails. It's quite hard to find out if a campaign is hosted by someone friendly or dangerous.

**Comment by jorchmacias** [comment]
This is a really good thing to do in order to reduce a negative position from third-parties -like service providers- towards legitimate phishing campaings.  I can see one possible drawback, what if real phishing attacks start including the Gophish X- headers in order to bypass either automatic or manual reviews?

**Comment by jordan-wright** [comment]
Closing this issue since most of the tips have been implemented. The last one is part of a bigger attempt to revamp the initial dashboard screen with helpful tips and progress updates.

**Comment by Blackbear710** [comment]
Is there any extra configuration needed for capturing data?? 

I am trying to test on myself, but I am not getting any Submitted Data from my Phish 

Importing URL,  adding said URL to email 

On the Results, after I login with my credentials onto said Phish.  I do not see any submitted data
