### ISSUE TITLE
Running Admin and Phish Server on Different Servers

### ISSUE THREAD

**Issue by mirkatson** [gophish/gophish#1060]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  Gophish v0.5.0

Brief description of the issue: Running Admin and Phish Server on Different Servers

What are you expecting to see happen? :
Example: I'm running admin server on www.gophishserver.com:3333, how can I run the Phish server on another server so that when I'm launching a campaign, the landing page I can point it to www.phishingserver.com instead (with tracking statistics)? How do I link both servers to use the admin server's database in config.json?

{
        "admin_server" : {
                "listen_url" : "0.0.0.0:3333",
                "use_tls" : true,
                "cert_path" : "cert.pem",
                "key_path" : "privkey.pem"
        },
        "phish_server" : {
                "listen_url" : "phishingserver-external-ip:443",
                "use_tls" : true,
                "cert_path" : "phishingserver-cert.pem",
                "key_path": "phishingserver-privkey.pem"
        },
        "db_name" : "sqlite3",
        "db_path" : "gophish.db",
        "migrations_prefix" : "db/db_"
}

What I'm trying to achieve is not to expose the admin server IP/domain name.

Thank you!

**Comment by jordan-wright** [comment]
Hi there!

To start, you'll need to ensure that both servers are using MySQL and they're pointed to the same instance. This will make sure that they're both working off the same data.

The problem with this is that both servers will then attempt to send emails every time a new campaign is launched. I recently [added a flag](https://github.com/gophish/gophish/commit/1426376aa595c5c7ca83c8a2d2f50a219335f5ae) to disable the mailer, which you could then use on one of the servers, but this hasn't been included in a release yet.

I just switched up development environments this week so I'm working to get everything back up and running. The timeline for me pushing out a new release with the latest code is probably later this week into this weekend. If you need this capability before then, you can build Gophish from source and you should be good to go 😄 

Hope this helps!

**Comment by mirkatson** [comment]
Thanks for your time to reply this, Jordan. Appreciate it!

I'm now running the latest version 0.6 and MySQL on both servers. In this case, how do I disable the mailer on one of the servers? Thank you.
