### ISSUE TITLE
Redirect not working

### ISSUE THREAD

**Issue by robp1234** [gophish/gophish#1064]
Hello,

I suspect I am missing something obvious, but any help much appreciate.

thanks

Rob

What version of Gophish are you using?: 

0.5.0

Brief description of the issue: 

Everything is working aside from the re-direct. When I submit my credentials on my phishing page, I get a 404. My aim is to take the phish victim to a training page on another site if they have actually submitted credentials.

The problem is caused because after I hit submit my browser is sent to:

http://my-phishing-domain.com/https/www.my-learning-domain.com

I can't work out why this is happening. In the landing page template I have the redirect set to:

https://www-my-learning-domain.com

What are you expecting to see happen? :

Redirect to https://www-my-learning-domain.com

What are you seeing happen?

404 because http://my-phishing-domain.com/https/www.my-learning-domain.com does not exist

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

Login portion:

<div class="login_inner_container">
                        <div class="inner_container cred">
                            <div class="login_workload_logo_container">
                            </div>
                            <div class="login_cta_container normaltext">
                                <div id="login_cta_text" class="cta_message_text 1">Sign in with your organizational account</div>
                            </div>
                            <ul class="login_cred_container">
                                <li class="login_cred_field_container">
                                    <div id="cred_userid_container" class="login_textfield textfield">
                                        <span class="input_field textfield">
                 <label for="UsernameForm" class="no_display">User account</label>
                  <div class="input_border">

                                        <form method="POST" action="" name="LoginForm" autocomplete="off"><input type="hidden" value="http://my-phishing-domain.com/?rid=jrgdzlE"/>
                                            <br/>
                                            <input type="text" tabindex="1" class="login_textfield textfield required email field normaltext" placeholder="someone@example.com "/>
                                            <br/>
                                            <br/>
                                            <input type="password" aria-label="Password" placeholder="Password" class="login_textfield textfield required field normaltext" tabindex="2" type="password"/>
                                            <br/>
                                            <br/>
                                            <br/>
                                            <input type="submit" class="button normaltext cred_sign_in_button refresh_domain_state" value="Sign In"/>
                                        </form>
                                    </div>
                                    <div id="cred_password_container" class="login_textfield textfield">
                                        <span class="input_field textfield">
                  <label for="PasswordForm" class="no_display">Password</label>
                  <div class="input_border">
                  </div>

**Comment by S0larflare** [comment]
You seem to have written https:/./ rather than https:// ?

Sent from my iPhone

On 11 May 2018, at 16:31, robp1234 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

I suspect I am missing something obvious, but any help much appreciate.

thanks

Rob

What version of Gophish are you using?:

0.5.0

Brief description of the issue:

Everything is working aside from the re-direct. When I submit my credentials on my phishing page, I get a 404. My aim is to take the phish victim to a training page on another site if they have actually submitted credentials.

The problem is caused because after I hit submit my browser is sent to:

http://my-phishing-domain.com/https/www.my-learning-domain.com

I can't work out why this is happening. In the landing page template I have the redirect set to:

https://www-my-learning-domain.com

What are you expecting to see happen? :

Redirect to https://www-my-learning-domain.com

What are you seeing happen?

404 because http://my-phishing-domain.com/https/www.my-learning-domain.com does not exist

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

Login portion:

Sign in with your organizational account

  *
User account

                                    <form method="POST" action="" name="LoginForm" autocomplete="off"><input type="hidden" value="http://my-phishing-domain.com/?rid=jrgdzlE"/>
                                        <br/>
                                        <input type="text" tabindex="1" class="login_textfield textfield required email field normaltext" placeholder="someone@example.com<mailto:someone@example.com> "/>
                                        <br/>
                                        <br/>
                                        <input type="password" aria-label="Password" placeholder="Password" class="login_textfield textfield required field normaltext" tabindex="2" type="password"/>
                                        <br/>
                                        <br/>
                                        <br/>
                                        <input type="submit" class="button normaltext cred_sign_in_button refresh_domain_state" value="Sign In"/>
                                    </form>
                                </div>
                                <div id="cred_password_container" class="login_textfield textfield">
                                    <span class="input_field textfield">
              <label for="PasswordForm" class="no_display">Password</label>
              <div class="input_border">
              </div>

**Comment by robp1234** [comment]
Hello, I can't see where?

**Comment by robp1234** [comment]
But, you are correct. I did have a typo. https// instead of https://. 

I've been staring at that for a couple of hours!

Thanks - please close this (non)issue. 

Rob
