### ISSUE TITLE
Landing Page Too Large - MySQL - Uploading

### ISSUE THREAD

**Issue by tamtu** [gophish/gophish#1067]
What version of Gophish are you using?: 
----------------------------------------
0.6, MySQL

Brief description of the issue: 
------------------------------

If you want to upload a large page through the editor, it will be silently cut off. 

The problem is that the "html" column in the "pages" table is only TEXT (maximum 65535 characters apparently).

It can be easily altered in the db by issuing "alter table pages modify html LONGTEXT;". (you could also use MEDIUMTEXT, to taste)

It would be best to have that in the initial db creation script probably, if there's one. I can see something happening in this file:

db/db_mysql/migrations/20160118194630_init.sql

**Comment by tamtu** [comment]
I've added a pull request for this: https://github.com/gophish/gophish/pull/1069

Please feel free to correct me if I'm wrong :)

**Comment by tamtu** [comment]
Ok, looks like that will not work well, sice SQLite doesn't have LONGTEXT or MEDIUMTEXT, just TEXT. There would have to be some logic to figure out which database is being used and set the proper type based on that.

**Comment by jordan-wright** [comment]
Hi @tamtu,

I've gone ahead and added a migration file for MySQL in da6091e0212782f8784fb54addca343484fda301 that should resolve this issue.

Thanks again for getting in touch!
