### ISSUE TITLE
Can't connect to gophish admin page

### ISSUE THREAD

**Issue by Hemza** [gophish/gophish#107]
Dear Developers,
i've installed Gophish , and finish the installation, i've tried to connect to the admin page http://127.0.0.1:3333  but can't connet to the server admin page , an error is returned : network error

**Comment by Hemza** [comment]
![gophish](https://cloud.githubusercontent.com/assets/3252236/12701142/a562b070-c7ff-11e5-8aa4-c7f06e4418a0.PNG)

**Comment by rfdevere** [comment]
Hamza this isn't an error, in fact it's a informative feature. What it's saying in computer speak is that the port is already in use. Pop open a browser and head to http://127.0.0.1 and what do you see? Probably some kind of web page?

It's saying that Port 80 is in use. 

Know off what ever is using that port e.g.:
"sudo servise apache2 stop"
Then re run the ./gophish

**Comment by rfdevere** [comment]
@jordan-wright Issues like this are where you will have to decide whether you wish this to be a professional product or suitable for a mass market. For any infosec professional it's clear to see what was meant by that error message and you have to question anyone looking to Phish with this that doesn't understand about TCP ports. (and it's adequately descriptive) but if you want this suitable for all, it might be worth adding a little tip at this point explaining how to kill a port.

Your call either way.

**Comment by Hemza** [comment]
i've killed all the processes that use the port but it return : 404 page not found
sorry for this question but i've novice in linux , i didn't work withit for a long time , i'm not really professional on linux

**Comment by rfdevere** [comment]
No worries Hemza, no such thing as a bad question and I am sure all feedback is appreciated from the Devs. If you have a 404 page this is the web server you have running saying it can't find the page... so by this we do know you have a web server running that needs to be stopped before running ./gophish If you had the port free and no web server running it would display "Connection error"

Linux is a beautiful thing and you'll always find help from other uses along the way, for now though take a look at this:
http://www.cyberciti.biz/faq/ubuntu-linux-start-restart-stop-apache-web-server/

Can I ask what your intentions with gophish are - there is no wrong answer just curious? Straight malicious phishing? Testing your friends? Testing staff?

**Comment by Hemza** [comment]
Thank you , i've just finish the installation of gophish and i'm trying to test it on big company and send you the feed back , it's a great pleasir for me to get help and assistance from your part ,  i'm running go Phish fir the first time ,

**Comment by rfdevere** [comment]
Hemza I am assuming you have the permission of the company in question? and could you share with us the company you intend testing it on?

**Comment by Hemza** [comment]
![gophish after stoping apach](https://cloud.githubusercontent.com/assets/3252236/12701309/ec5ce710-c805-11e5-8c5a-17c1553fdb1c.PNG)

**Comment by Hemza** [comment]
at this moment we didn't decide to use officially gophish  so we're trying to make some tests before using it, and there i 'll share with juste with you some informations , and why not future projects but on private mode,

Thank you freind

**Comment by rfdevere** [comment]
looks fine to my eyes.. head to http://127.0.0.1:3333 and log in. Good luck, keep it legal friend.

**Comment by Hemza** [comment]
![error](https://cloud.githubusercontent.com/assets/3252236/12701356/b53a3b50-c807-11e5-91f7-6c2f02c68e14.PNG)
Networkerror i thik it's related to the port

**Comment by Hemza** [comment]
i deactivate the use of proxy for local addresses but the same error is returned

**Comment by Hemza** [comment]
do have any idea about this probleme

**Comment by Hemza** [comment]
can you any one tell me what's exactly the probleme

**Comment by jordan-wright** [comment]
Hi @Hemza, thanks for contacting us.

@rfdevere has correctly diagnosed your original issue - there was a web server already running on TCP port 80 that needed to be stopped. It looks like stopping apache fixed that issue (here's to hoping you didn't need Apache running :smile:).

Your next issue is directly related to having a proxy configured. It would appear that you are trying to make a connection that (for whatever reason) is being sent to a proxy server. So, the proxy is trying to connect to localhost, where it can't connect since it isn't the one running gophish.

To this end, I'm afraid we won't be able to help you as we don't know your proxy configuration. I would recommend talking with your sysadmin to determine what proxy configuration is in place and how to properly disable it for any local connections.

**Comment by jordan-wright** [comment]
I'm going to go ahead and close this for now, as it definitely appears to be an issue with your proxy config and not an issue with gophish. If you find out other details and require more help, you can comment here and we'll help any way we can.

Thanks!

**Comment by Fornacula** [comment]
I had the same issue. No proxy conf was present. My problem was related to not realizing that there is a difference in `config.json` file between lines `"listen_url": "127.0.0.1:3333"` and `"listen_url": "0.0.0.0:80"`. As I was setting it up in a server environment then of course accessing 127.0.0.1 did not resolve into my server's domain name. Changing the 127.0.0.1 to 0.0.0.0 and specifying my custom port did the quick trick. Though I will probably configure it more thoroughly later on.
