### ISSUE TITLE
Plugin API

### ISSUE THREAD

**Issue by justaskingquestions** [gophish/gophish#1070]
Does gophish have a means to add functionality (e.g. reporting feature) via extension/plugins?
I do know there is the wonderful REST API, but I am more interested in future extensions of server-side functionality (i.e. some component that might even provide an API in itself).

**Comment by jordan-wright** [comment]
Hi @justaskingquestions - thanks for reaching out!

At this time, Gophish does not support a plugin architecture and we don't have plans to add one in the immediate future. The code is open source, so there is always the ability to add modules as you see fit, and you're correct that we have an established, comprehensive API that can be used to automate the use of Gophish. 😄 

Hope this helps!
