### ISSUE TITLE
Multiple emails sent for the same user 

### ISSUE THREAD

**Issue by GBvenkatesh** [gophish/gophish#1074]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  0.5.0 Linux 64 Bit

Brief description of the issue: Multiple emails sent for the same email id 

What are you expecting to see happen? : One email to one mail id 

What are you seeing happen? 3 times the same mail was sent to the user 

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi @GBvenkatesh, thanks for reaching out!

My guess is that this is similar to #1073 which seems to be the same issue. As such, I'll close this one out as a duplicate and we'll work together out of that issue to figure out a resolution.

In the meantime, if there's any information you can add to that issue including the group size, whether or not the user was duplicated in the group, if there are any logs from the Gophish terminal, etc. that would be helpful for us to continue working to track it down. 😄
