### ISSUE TITLE
All files in gophish/static/endpoint can be listed in the browser

### ISSUE THREAD

**Issue by bobhello** [gophish/gophish#1077]
**What version of Gophish are you using?:** 
0.6.0

**Brief description of the issue:** 
It is possible for anyone to list all "resource" files (that are in the directory gophish/static/endpoint)
For example, if my gophish is hosted on example.com, anyone can go to example.com/static/ and see all files present in the directory gophish/static/endpoint

**What are you expecting to see happen? :**
I would expect to see a 404 error, as happens when you go to example.com/static (no ending /)
Why? In GoPhish, we may host many phishing sites with many different resources. Anyone should not be able to go to this site to see all the resources we are hosting. At least in my opinion, this is not a good idea.

**What are you seeing happen?**
A list of all files in directory gophish/static/endpoint appears with clickable links to these resources

**Please provide as many steps as you can to reproduce the problem:**
 * Step 1 - 
Get the domain where your GoPhish is hosted, e.g. example.com
 * Step 2 - 
Go to example.com/static/ (including last slash!) in a browser and see a list of resources.
 
 
By the way! Thank you for making this excellent product! It really is a bliss to setup and use. Much appreciated.

**Comment by S0larflare** [comment]
So this is an interesting one and I think is more to do with how Go creates webservers. The static folder needs to be there for your assets and needs to be routable for them. I could be wrong, but it would probably be pretty easy to add to the router function so that /static/* is only reachable if you are authenticated (via logging in to the console or using a valid api key). 

The only issue I can see though is if you are putting things in /static/endpoint/ then surely you are using that as a landing page or similar, so actually you want that to be visible to your targets?

**Comment by S0larflare** [comment]
Ohhhhhhh! Wait, I think it just clicked what you actually meant. I assume you mean that you get an index of all the resources under /static/endpoint if someone goes to phishserver.com/static/landingpage.htm and then decides to get rid of the landingpage.htm part in their browser. 

In that case, disregard what I said, I had misunderstood what you meant. I think it should be possible to sort that, I think it has been raised before, it just hasn't been put as a high priority.

**Comment by jordan-wright** [comment]
Hi @bobhello - thanks for reaching out!

You're right that currently static content is listable. Unfortunately, this is the default behavior of Golang's file server.

You're also right that this _should_ be fixed. We have an open issue at #815 to track this, but I haven't had time yet to add a solution. I have some time this evening so I'll see if I can knock it out. 😄

**Comment by jordan-wright** [comment]
This should be fixed in the latest source. Let me know if you continue to run into issues with this.

Thanks for the report!

**Comment by bobhello** [comment]
Thank you for your kind and quick help, @jordan-wright !
Really cool to see how friendly and helpful you are in this project. Great job. =)
I have not tested the patch yet, but probably will later.

**Here's the workaround I am using currently in case anyone can benefit:**

I simply add an empty index.html file inside the static/endpoint folder. This means an empty page will be shown if a user goes to example.com/static/ instead of the directory listing.
