### ISSUE TITLE
Results Export Requests

### ISSUE THREAD

**Issue by kmackinley** [gophish/gophish#1079]
**What version of Gophish are you using?:** 
0.5.0

**Brief description of the issue:** 
When exporting Results, it would be great to have the click and submission time and date for each target listed instead of having to pare it from the Raw Events. For campaigns with hundreds of targets, not having the Click and Submissions time and date in the exported Results is a huge burden.

Additionally, the send_date gives the time in UTC, which is not a huge deal but it would be nice for it to be congruent with the time that is given in the Campaign Results page which seems to be the same as the servers time.

I'd be glad to help if possible on any of these if you can point me in the right direction.

**Comment by jordan-wright** [comment]
Hi @kmackinley thanks for reaching out!

I didn't realize that we didn't have a last modified field for results. We definitely should, so I'll get that added. As part of the database migration, I'll backfill the date with the date of the latest event so that it's filled in when the CSV is downloaded.

Thanks for sending this in! I'll get this fixed ASAP.

**Comment by kmackinley** [comment]
Thanks for looking into this, is it possible to get the time they clicked on the link and the time they submitted data in separate columns in the CSV Results?

**Comment by jordan-wright** [comment]
That's a good question @kmackinley. I think for now I'm going to focus on having just a last modified date that corresponds to the latest event. The reason for this is that I'm soon going to start work on #223 which completely changes the structure of campaigns to where there are different "steps" that are executed as opposed to a single email with a single click and a single data submission.

In terms of implementation, this is turning out to be a bit trickier than I thought! But, I think it'll clean some things up. I'm having to refactor some of the logic, do a bit of SQL cleverness, etc. All in all, having a last modified date will be a net-add to the Gophish code, which is a good thing! 😄 

Hope this helps!

**Comment by jordan-wright** [comment]
Got this done in 420410b52c6d7ada6ac675a42d36ef0c84431f6f where now results have a `modified_date` field in the CSV export as well as the API.

Hope this helps! Thanks again for getting in touch.
