### ISSUE TITLE
Phishing server not serving on HTTPS

### ISSUE THREAD

**Issue by omni-shambles** [gophish/gophish#1081]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: **v0.5.0**

Brief description of the issue: **When attempting to use Let's Encrypt generated certificate, the phishing server will not launch at https:// , instead launching at http://. **

What are you expecting to see happen? : **Phishing server launching over https, landing pages reachable.**

What are you seeing happen?
"Starting admin server at https://0.0.0.0:3333
Starting phishing server at http://0.0.0.0:443"
^With similar config.
As would be expected with this issue:
- https://<domain> URL produces ssl error: ERR_SSL_PROTOCOL_ERROR (_"This page cannot provide a secure connection."_ ; <domain> sent an invalid response)
- <domain> and <domain> campaign URL for sanding page produces ssl error: ERR_CONNECTION_REFUSED (_"This site can’t be reached."_ ;
<domain> refused to connect.)

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html

```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Set up GoPhish server and created multiple campaigns. Everything works over HTTP successfully.
 * Step 2 - Created cert using Let's Encrypt's Cert Bot for custom domain (for landing page).
 * Step 3 - Modified config to enable tls, with path to certificate replacing default certificates
 * Step 4 - Relaunched GoPhish. GoPhish admin server launches at https://0.0.0.0:3333 (serves over valid HTTPS with Let's Encrypt cert). However, the phish server launches at http://0.0.0.0:443, even with 'use_tls = "true"' and the gophish service listening on https. As a result, landing pages in phishing campaigns will not work as expected, with ssl errors.

Please let me know if any other information is required to help me address this issue.

Thanks!

**Comment by S0larflare** [comment]
It says there


Starting phishing server at http://0.0.0.0:443"

Have you tried changing that to https in config.json?

Sent from my iPhone

On 25 May 2018, at 17:29, omni-shambles <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for reaching out! We're happy to help resolve issues as quickly as possible.

Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our documentation<https://getgophish.com/documentation/>, which covers how to use Gophish.

What version of Gophish are you using?: v0.5.0

Brief description of the issue: **When attempting to use Let's Encrypt generated certificate, the phishing server will not launch at https:// , instead launching at http://. **

What are you expecting to see happen? : Phishing server launching over https, landing pages reachable.

What are you seeing happen?
"Starting admin server at https://0.0.0.0:3333
Starting phishing server at http://0.0.0.0:443"
^With similar config.
As would be expected with this issue:

  *   https:// URL produces ssl error: ERR_SSL_PROTOCOL_ERROR ("This page cannot provide a secure connection." ; sent an invalid response)
  *   and campaign URL for sanding page produces ssl error: ERR_CONNECTION_REFUSED ("This site can’t be reached." ;
refused to connect.)

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

Please provide any terminal output that may be relevant below:

Insert output here


Please provide as many steps as you can to reproduce the problem:

  *   Step 1 - Set up GoPhish server and created multiple campaigns. Everything works over HTTP successfully.
  *   Step 2 - Created cert using Let's Encrypt's Cert Bot for custom domain (for landing page).
  *   Step 3 - Modified config to enable tls, with path to certificate replacing default certificates
  *   Step 4 - Relaunched GoPhish. GoPhish admin server launches at https://0.0.0.0:3333 (serves over valid HTTPS with Let's Encrypt cert). However, the phish server launches at http://0.0.0.0:443, even with 'use_tls = "true"' and the gophish service listening on https. As a result, landing pages in phishing campaigns will not work as expected, with ssl errors.

Please let me know if any other information is required to help me address this issue.

Thanks!

**Comment by jordan-wright** [comment]
I guess to help us find the problem quicker, could you please post your config.json here @omni-shambles? That'll help us track things down a bit quicker.

**Comment by omni-shambles** [comment]
Hi, @S0larflare & @jordan-wright.

Thanks for reaching out so quickly.

If I change my config.json from "0.0.0.0:443" to "https://0.0.0.0:433", the service will not start. I'm presented with as follows:

"_Starting phishing server at http://https://0.0.0.0:80
gophish.go:116: listen tcp: address https://0.0.0.0:80: too many colons in address_".

My config.json is below:

```
{
        "admin_server" : {
                "listen_url" : "0.0.0.0:3333",
                "use_tls" : true,
                "cert_path" : "fullchain.pem",
                "key_path" : "privkey.pem"
        },
        "phish_server" : {
                "listen_url" : "https://0.0.0.0:80",
                "use_tls" : "true",
                "cert_path" : "fullchain.pem",
                "key_path": "privkey.pem"
        },
        "db_name" : "sqlite3",
        "db_path" : "gophish.db",
        "migrations_prefix" : "db/db_"
}`.
```

**Comment by S0larflare** [comment]
I meant try https://0.0.0.0 or https://0.0.0.0:443, you’re kind of asking it to run https on the standard http port, I wouldn’t be surprised if it’s trying to append 443 on the end, coming up with https://0.0.0.0:80:443 and throwing that error

Sent from my iPhone

On 25 May 2018, at 18:12, omni-shambles <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, @S0larflare<https://github.com/S0larflare> & @jordan-wright<https://github.com/jordan-wright>.

Thanks for reaching out so quickly.

If I change my config.json from "0.0.0.0:443" to "https://0.0.0.0:433", the service will not start. I'm presented with as follows:

"Starting phishing server at http://https://0.0.0.0:80
gophish.go:116: listen tcp: address https://0.0.0.0:80: too many colons in address".

My config.json is below:

{
        "admin_server" : {
                "listen_url" : "0.0.0.0:3333",
                "use_tls" : true,
                "cert_path" : "fullchain.pem",
                "key_path" : "privkey.pem"
        },
        "phish_server" : {
                "listen_url" : "https://0.0.0.0:80",
                "use_tls" : "true",
                "cert_path" : "fullchain.pem",
                "key_path": "privkey.pem"
        },
        "db_name" : "sqlite3",
        "db_path" : "gophish.db",
        "migrations_prefix" : "db/db_"
}`.

**Comment by jordan-wright** [comment]
It looks like there are two problems:

* Change `https://0.0.0.0:443` to just `0.0.0.0:443`. That should be the `listen_url` for the phish_server.

* Change "true" to true (remove the quotes). Gophish isn't seeing this as a valid option so I believe it's defaulting to false.

Hope this helps!

**Comment by omni-shambles** [comment]
My apologies, @S0larflare. The service is currently on an AWS public IP. The https was throwing up a 404 error on https://<ip>, and firewall error on http://<ip>.

@jordan-wright you are indeed correct on the second point! Much appreciated.

Thanks so much for the quick reply, and the assistance (as embarrassed as I am). Safe to say your user service is as good as the service you've build here. We're looking forward to seeing how you guys continue to develop and improve it.

**Comment by jordan-wright** [comment]
> (as embarrassed as I am)

Please don't be! You gave all the information we could ask for and helped us track down the problem quickly. This community is full of awesome people like @S0larflare who help each other out. The community is what makes Gophish great, and I'm excited to have another member 😄 

I'm assuming things are working as intended now? If so, you can either close the issue or let me know and I'll get it closed out. Thanks again for getting in touch, and let us know if you run into any other issues!

**Comment by omni-shambles** [comment]
Apologies for the delay, guys.

Will close the issue now.

Thanks again for the help.

**Comment by Menx2** [comment]
Guys how do I edit the config.jason file

**Comment by jordan-wright** [comment]
Use a text editor to edit the file.

**Comment by Menx2** [comment]
What’s the command 😅

**Comment by jordan-wright** [comment]
This issue tracker is specifically for bugs in Gophish.

For learning how to use text editors, I would need to point you to Google. There are a variety of editors, and knowing how to edit text files is a prerequisite for effectively using Gophish.

**Comment by Menx2** [comment]
Thanks, I'll check it out.
