### ISSUE TITLE
Question about updates and how they effect the database structure

### ISSUE THREAD

**Issue by TymeOfNight** [gophish/gophish#1082]
**What version of Gophish are you using?:** 
0.6.0

**Brief description of the issue:** 

I'm adding tables to the GoPhish database, and am wondering how they and database data are affected by version updates.  If and when a new version is released, will I ever have to worry about my added tables or existing data being moved/deleted?

Thanks in advance, and thank you for your good work. :-)

**Comment by jordan-wright** [comment]
Hi @TymeOfNight, thanks for reaching out!

This is a good question. Gophish updates the database using migration files. If you are doing manual changes to the DB, we can't guarantee that your changes will stay in-tact but they _should_ under normal circumstances.

The migrations we run usually just add or alter tables or columns, so assuming there aren't any fundamental table changes on your end, things should be fine.

Hope this helps! Let me know if you have any other questions.
