### ISSUE TITLE
Need {{.SURL}} for Reference src= variable in Templates

### ISSUE THREAD

**Issue by H4xl0r** [gophish/gophish#1085]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

UptoDate

Brief description of the issue: 

When using Static References in Mails (Best Way) Like:

dest.: `http://phishserver/static/image.png`
emailpart:  `<img src="http://phishserver/static/image.png" alt="Alternate" height="42" width="42"> `

**It Would be massive helpful to have a {{.SURL}} (ServerURL) TAG to make it variable like:**

dest.:  `http://???????/static/image.png ( variable thanks to {{.SURL}}) `
emailpart:   `<img src="http://{{.SURL}}/static/image.png" alt="Alternate" height="42" width="42"> ` 

What are you expecting to see happen? :

Owner is Seeing the benefits of this idea and implements it :-)
I also Posted a Pull request with some Basic Login Page to Implement.
So Users can copy it and customize .

Nice Work.
Go on.
Will donate...

**Comment by H4xl0r** [comment]
U could get that variable {{.SURL}} via Setting it in the Panel Menu Settings. (user input)
 With something like Domain Setting / Server Setting.

U could get that variable {{.SURL}} via Settings in the Email Template Editor. (user input) 
 Choose Domain to use Dropdown Menu / or input.

Or u could implement a Menu tap with functions to store and edit used domains.(BEST WAY)(User Input once, supporting multiple domains now !) 
So it would be possible to link more then one domain to it and make them variable.
with {{.SURL}}

**Comment by jordan-wright** [comment]
Hi @H4xl0r,

Thanks for reaching out! I apologize for the delay in getting back to you.

I recently received another issue that appears similar in #1182. The good news is that I'm planning on getting this implemented. 😄 

For now, I'm going to close this one out to try and consolidate issues. We'll track everything through #1182. I'd encourage you to keep an eye there for updates as this gets implemented.

Thanks again for reaching out!
