### ISSUE TITLE
Gophish fails on start - "no valid version found"

### ISSUE THREAD

**Issue by TymeOfNight** [gophish/gophish#1088]
What version of Gophish are you using?: 
0.6.0

Brief description of the issue: 
After installing v.0.6.0 and setting it up to run with mysql, the gophish client will not stay running, and throws a "no valid version found" error. 

What are you expecting to see happen? :
Gophish should start running normally.

What are you seeing happen?

We installed v0.6.0 on top of an exsisting v0.5 install.  Both versions were built from source; we deleted /opt/goapps/github.com and all of its contents before recompiling the source.  We tested the new Gophish install, and it was working swimmingly [ ;-) ].  Then, we modified the config.json file to be able to hook up to a mysql database.  We never deleted the old database, and were expecting the new version to just pick up the old connection and work.  (I tried adding the reported column to the results table of the old database, since I know that that changed between versions, but the same error message as below was given.)  We are getting the following error:

```
time="2018-05-29T17:21:28-04:00" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
time="2018-05-29T17:21:28-04:00" level=error msg="no valid version found"
time="2018-05-29T17:21:28-04:00" level=fatal msg="no valid version found"
```

Our config.json looks like this:
```
       "admin_server" : {
                "listen_url" : "x.x.x.x:3333",
                "use_tls" : true,
                "cert_path" : "gophish_admin.crt",
                "key_path" : "gophish_admin.key"
        },
        "phish_server" : {
                "listen_url" : "0.0.0.0:80",
                "use_tls" : false,
                "cert_path" : "example.crt",
                "key_path": "example.key"
        },
        "db_name" : "mysql",
        "db_path" : "redacted:redacted@localhost:3306/gophish?charset=latin1_swedish_ci&parseTime=True&loc=UTC",
        "migrations_prefix" : "db/db_"
}
```

Our connection information for MySQL (regarding the time format discrepancy) is the same as it was for version 0.5.0; we didn't change it during the install.

In case it's relevant, we installed GoPhish from source using these instructions: [http://www.jaspher.com/blog/install-go-and-gophish-on-centos-7](http://www.jaspher.com/blog/install-go-and-gophish-on-centos-7)

If you could provide any insight on this, we would be appreciative.  Thanks!

**Comment by jordan-wright** [comment]
Thanks for reaching out!

> We installed v0.6.0 on top of an exsisting v0.5 install

What do you mean by this? Traditionally, we recommend downloading the new release separately and moving over your `config.json` and your SQLite database, if applicable. If you're building from source, it's probably fine to do a standard `git pull` to get the latest source, so maybe that's what you did here?

> We never deleted the old database, and were expecting the new version to just pick up the old connection and work.

What do you mean by this? I'm guessing you were using SQLite and switched it to MySQL? If so, the connection should work, but just know that it won't migrate all your objects to MySQL from SQLite. You'd have to start from scratch.

> I tried adding the reported column to the results table of the old database, since I know that that changed between versions, but the same error message as below was given.

If you can undo this, I'd recommend it, only because we have a migration file that handles this now.

From looking at your config.json (I've redacted a few things), things _seem_ reasonable. I'm guessing you're running Gophish from within the install directory (where there's a `db/` folder at the root).

What does your `db/db_mysql/migrations/` folder look like? It seems like the migration script is having difficulty finding those migrations.

**Comment by TymeOfNight** [comment]
First of all, thank you for your quick support, and for redacting that information. (heh)

> We installed v0.6.0 on top of an exsisting v0.5 install 

We wanted to update to v0.6, but v0.5 was built from source, as my supervisor had heard that people were generally happier with a source build, and had heard rumors of memory issues/inefficiency in the prebuilt binaries.  Because of this, it didn't seem like the update instructions provided with the new release were applicable, as we didn't want to use the prebuilt binary, but wanted a compiled source version.  The commands didn't work as expected because I didn't have elevated permissions, but my supervisor and I didn't realize that at the time, and so we ended up deleting the "github.com" folder, and reinstalling from scratch.

> We never deleted the old database, and were expecting the new version to just pick up the old connection and work.

After installing Gophish v0.6 from scratch, we set up the listening ports, and were able to successfully log in to the Administrator portal.  We realized, however, that the default database used is SQLite, and we wanted to use MySQL.  Our Gophish 0.5 install was using a MySQL database, installed as part of XAMPP or a similar LAMP package, meaning the database was preserved when Gophish was wiped.  So, we edited the config.json to have the connection string shown above.  That is when we started receiving the error.

> I tried adding the reported column...

I can undo this.

Here's what the file structure in db_mysql/migrations looks like:

```
20160118194630_init.sql
20160131153104_0.1.2_add_event_details.sql
20160211211220_0.1.2_add_ignore_cert_errors.sql
20160217211342_0.1.2_create_from_col_results.sql
20160225173824_0.1.2_capture_credentials.sql
20160227180335_0.1.2_store-smtp-settings.sql
20160317214457_0.2_redirect_url.sql
20160605210903_0.2_campaign_scheduling.sql
20161202153627_AttachmentFix.sql
20170104231222_0.2_result_statuses.sql
20170219122503_0.2.1_email_headers.sql
20170828220440_0.4_utc_dates.sql
20171027213457_0.4.1_maillogs.sql
20171208201932_0.4.1_next_send_date.sql
20180223101813_0.5.1_user_reporting.sql
20180524203752_0.7.0_result_last_modified.sql
```

**Comment by TymeOfNight** [comment]
Wanted to write back to say that we fixed our error.  We ended up backing up the database to an SQL script, deleting it, re-installing Gophish again, and then recreating the database and importing the data.  The nuclear option, but it worked.  Thanks for your support! :-)
