### ISSUE TITLE
Trouble with campaign URL entry

### ISSUE THREAD

**Issue by bradphillips921** [gophish/gophish#1091]
**What version of Gophish are you using?:** 
v.0.6.0

**Brief description of the issue:** 
I'm trying to run a new campaign with a template email directing the user to a landing page. I've completed both the template and landing page.  I changed the phishing server port to 87 and forwarded that port to the server with GoPhish in my router.  When creating the campaign I have tried using my public IP address and the local server address, neither work.

**What are you expecting to see happen? :**
I'm expecting to see the landing page

**What are you seeing happen?**
I get the error:
This site can’t be reached
The webpage at http://xxx.xxx.xxx.xxx:87/?rid=xelVbAs might be temporarily down or it may have moved permanently to a new web address.
(xxx.xxx.xxx.xxx is my public IP address)

I have changed the phishing server port in my config.json file.  When starting GoPhish I see this in my terminal
...msg="Starting phishing server at http:/0.0.0.0:87\n"

My question is, if my public IP address is xxx.xxx.xxx.xxx and I'm using port 87 for the phishing server, what do I enter for "URL" when creating a campaign? I need users outside of my LAN to be able to access the landing page.

Thanks!

**Comment by thryb** [comment]
Are you sure you are starting the server with sudo? 87 is a reserve port (i.e. 1-1024) and need elevated privilege to open.

**Comment by bradphillips921** [comment]
I'm running the Gophish server on a windows 7 machine.  I've tried running the program as administrator. Is that the same as sudo?

**Comment by thryb** [comment]
Yes sorry, I should've ask "or administrator".
Is your firewall on, on that windows machine?

**Comment by thryb** [comment]
No you don't. Right now I am 99.9% sure the problem reside in the fact that the port forwarding isn't working properly and your machine is not reachable from the internet.

I suggest you try a free instance of AWS or Google and deploy it there (for the time of testing). Much less trouble and you are sure you are facing. Only need to configure the firewall rules to allow access.

As this is software issues support and your problem looks like it comes from the "routing/forwarding" around your instance of GoPhish. I recommend you make sure everything is good to go on the net side and reopen an issue if you still have problems.

**Comment by bradphillips921** [comment]
Sounds good. Thanks for the help!

**Comment by S0larflare** [comment]
I see this in my terminal
...msg="Starting phishing server at http:/0.0.0.0:87\n"


Have you copied and pasted that? It’s missing a 2nd / and seems to have a trailing new line at the end of it or something ?

Sent from my iPhone

On 31 May 2018, at 23:37, bradphillips921 <notifications@github.com<mailto:notifications@github.com>> wrote:


Sounds good. Thanks for the help!

**Comment by bradphillips921** [comment]
Sorry, I missed the 2nd /.  I didn't copy and paste, my terminal window wouldn't let me copy.

I did get canyouseeme.org to see my computer now.  I created a firewall rule to allow port 87.

But, now I'm having a different issue. GoPhish is crashing after about two minutes.  I have to pack it in for tonight. I'll look at it again tomorrow.

**Comment by jordan-wright** [comment]
> I did get canyouseeme.org to see my computer now. I created a firewall rule to allow port 87.

Glad to hear you were able to resolve that problem! If you could, let's move the separate issue into a different Github issue just to keep things as organized as possible.

In that issue, if you could provide any terminal output when Gophish crashes, what you're doing at the time of the crash, etc. it'll help us track things down as quickly as possible. 😄 

Thanks again for getting in touch!
