### ISSUE TITLE
This website can not be accessed. Page 127.0.0.1 has rejected the connection

### ISSUE THREAD

**Issue by jpiana** [gophish/gophish#1097]
**What version of Gophish are you using?**: Gophish v0.6.0

**Brief description of the issue:** When I enter the address 127.0.0.1:3333, it sends me this message: "This website can not be accessed, page 127.0.0.1 has rejected the connection." I also probe by typing the "http" and the "https" but the problem persists. I am using windows 8.1.

**What are you expecting to see happen?** : I want to do a phishing campaign in my organization.

**Comment by jpiana** [comment]
![image](https://user-images.githubusercontent.com/39836940/40853309-3ee5b73c-6593-11e8-9ab4-65862fb03226.png)

**Comment by jordan-wright** [comment]
Hi there!

Can you please post:

* Your `config.json` file
* The terminal output when you start Gophish

That will help us troubleshoot the problem quicker 😄 

Thanks for getting in touch!

**Comment by jpiana** [comment]
**config.json**
{
	"admin_server" : {
		"listen_url" : "127.0.0.1:3333",
		"use_tls" : true,
		"cert_path" : "gophish_admin.crt",
		"key_path" : "gophish_admin.key"
	},
	"phish_server" : {
		"listen_url" : "0.0.0.0:80",
		"use_tls" : false,
		"cert_path" : "example.crt",
		"key_path": "example.key"
	},
	"db_name" : "sqlite3",
	"db_path" : "gophish.db",
	"migrations_prefix" : "db/db_"
}

Thanks

**Comment by jordan-wright** [comment]
The config looks fine. We still need the terminal output when you launch Gophish to make sure that everything is started successfully.

And make sure you're putting the right address (in this case https://localhost:3333) in your address bar.

**Comment by jpiana** [comment]
**When I run the Gophish, it shows me this screen for 1 second and then it closes**.

![123](https://user-images.githubusercontent.com/39836940/40981267-2b354ada-68a0-11e8-92ef-33287a84745e.jpg)

**Comment by kush-1277** [comment]
I had faced a similar problem recently, and one of the possible reasons can be that you might have changed your ip address settings in your system. I had changed my system's ip address settings and the connection could not be established and the GoPhish terminal used to vanish very soon without showing any error. Then I changed it back to default by deselecting the option to enter the ip address and select the default one. The following link shows how to setup the ip address, you just need to select the "Obtain IP address automatically" option. Repeat same with DNS option.

https://kb.netgear.com/27476/How-to-set-a-static-IP-address-in-Windows

You have to Unset IP address.

Hope this helps.

**Comment by jpiana** [comment]
I tell you that I had to install a virtual machine with windows 10 and the gophish was executed normally. I still do not know why the problem of its execution in windows 8.1 .

**Comment by jordan-wright** [comment]
Hi @jpiana - sorry for the delay.

I'm glad to hear you found a workaround by installing Gophish in a VM. Regarding the error message you saw in your terminal, [these issues](https://github.com/gophish/gophish/search?q=%22in+a+way+forbidden%22&type=Issues) may help give a solution.

Since a workaround was found, I'm going to go ahead and close this out. Thanks again for getting in touch!
