### ISSUE TITLE
Gophish is not returning the status of campaign,email and landing page template not working as expected

### ISSUE THREAD

**Issue by ade18** [gophish/gophish#1099]
What version of Gophish are you using?: Gophish v0.6.0

Brief description of the issue: when i launch the campaign it does not update on gophish when the mail has been opened,clicked or reported. Also on the mail sent, clicking the link doesnt open the clone webpage. It just gives a blank page.

What are you expecting to see happen?: the cloned webpage when target clicks the link, the notification that it has been opened,clicked or data submitted on gophish.
Steps Used:
Setting up Landing Page:
import site http://example.com
added tracking image
redirect http://example.com

Step Two:
Setting up email content:
 import email
change links to point to landing page
save changes

**Comment by jordan-wright** [comment]
Can you show an example of the email template and landing page you're using? You need to be sure to setup tracking on the email template and use the `{{.URL}}` tag in your email template to point to your landing page.

> clicking the link doesnt open the clone webpage. It just gives a blank page.

What are you using as the URL when building a campaign? You need to use something like `http://x.x.x.x` where `x.x.x.x` is the external IP address of the server running Gophish. Whatever you use, it needs to point to your Gophish instance and be reachable by the people receiving the emails.

**Comment by ade18** [comment]
Hi,
Thank you for your the response. I am using the {{.URL}} tag in the email template but i believe the challenge may be from the URL i am using to build the campaign. Could it be that its part of the reason its not updating on gophish when them mail has been opened and link clicked?
I registered a domain but i think i need to register with a vps provider. However, i will appreciate if you can give me set of steps to take in order to configure the domain properly after registering a domain and if there is anything am meant to link up with once i have rented the vps.
Thanks again

**Comment by jordan-wright** [comment]
> I registered a domain but i think i need to register with a vps provider. However, i will appreciate if you can give me set of steps to take in order to configure the domain properly after registering a domain and if there is anything am meant to link up with once i have rented the vps.

You need to setup a DNS record to point the domain to your Gophish IP address. How to do this depends on your DNS provider. I'm afraid that's out of the scope of the support we can provide.

**Comment by ade18** [comment]
Hi,
Thanks again so far, I have a DNS record pointing to the domain which has  the IP Go phish is running on.  I still dont know why its not reporting back. Will keep trying anyways.

**Comment by ade18** [comment]
I think i may have solved my problem. the issue was partly from the DNS  provider as it was not pointing the IP address to the domain. 

Thank you very much.

**Comment by jordan-wright** [comment]
Glad to hear you were able to resolve the issue!

**Comment by Chancard-Lucky** [comment]
I need help setting up Gophish in my PC
