### ISSUE TITLE
Add delays between email deliveries

### ISSUE THREAD

**Issue by grutz** [gophish/gophish#110]
It would be nice to be able to spread out a campaign's e-mail delivery to not trip monitoring systems. Sending 100 e-mails, all with very similar payload data, within a 5-10 minute period is usually grounds for instant containment of any future mail.

Some options per campaign:
- Delay rand(x) seconds after group of y mails have been sent
- Delay rand(x) seconds after group of rand(y) mails have been sent
- Delay rand(x) seconds after each mail

**Comment by jordan-wright** [comment]
Hey @grutz - this is a great idea! Let me poke around a bit to see if I can find a good way of implementing this on the back end.

**Comment by rfdevere** [comment]
Seconded! Whilst on the subject further builds could have a randomised email subject (not truly random, from a pre formed list) this will help further limit basic spam email filtering programs.

**Comment by jordan-wright** [comment]
Interesting thought! I'll see what I can come up with. I think right now you can use template values in the subject. So, I can at least do something like "{{.FirstName}} - Your password has been reset" and it will be dynamically generated.

I'll double check on that, and I'll see what I can do about the list of subjects. Thanks for the suggestion!

**Comment by 4144414D** [comment]
Ideally a feature such as emailing x number of people between a date range. 

i.e. emailing 100 people at random intervals of the course of a week.

**Comment by rfdevere** [comment]
Winning idea^

**Comment by mubix** [comment]
The randomized subject name should probably be it's own issue so that tracking of the email delay randomization can be better tracked

**Comment by jordan-wright** [comment]
Agreed - I'll make a separate issue for this.

**Comment by NoahJaehnert** [comment]
+1 on this. Currently using a different tool that has the same limitations - no delay/randomization in sending emails. So, we create separate campaigns and schedule them at different intervals/times. However, this makes reporting a nightmare. 

Would be great to have this randomization/delay feature available in GoPhish.

**Comment by chkconfig** [comment]
this feature would be really cool. i'm unsure if we can do this at the moment but x emails to x accounts between x and x dates and in x and x hours would be amazing.
