### ISSUE TITLE
css file issue - whole system appears incorrect

### ISSUE THREAD

**Issue by daviddeakin2018** [gophish/gophish#1101]
Version 0.6.0

Brand new install (i have never installed it before mind).  Page does not load correctly on IE, Edge, Chrome or Firefox - looks as though the CSS file is missing or unreadable.

If live editing the CSS file within chrome dev tools a single removal of a space or entering a space anywhere will then allow the page to render.    Have tried manually editing the CSS file under the /static/css/dist/gophish.css folder however this does not let the page render correctly.  The file when placed into Dreamweaver does not parse correctly and also checked with https://jigsaw.w3.org/css-validator/validator there are lots (863) of parsing errors through the file.
![standard css](https://user-images.githubusercontent.com/39494965/40967550-30f3827e-68ab-11e8-9b26-a7856235e772.jpg)
![with new line added to bottom of css](https://user-images.githubusercontent.com/39494965/40967551-310f9aa4-68ab-11e8-9995-4ee788d12627.jpg)
The two attached images show what happens when adding a single line to the CSS in live view.  Oddly, adding this extra line to the raw css files does not make a difference - but does get shown on the css panel in Chrome.

**Comment by jordan-wright** [comment]
Hi @daviddeakin2018 - thanks for reaching out!

This is the first I've heard of this issue. I'll see if I can reproduce it sometime tomorrow and will report back. I'm guessing this is with the standard Windows install?

**Comment by daviddeakin2018** [comment]
Hi,

That is correct.  Downloaded from https://github.com/gophish/gophish/releases/download/v0.6.0/gophish-v0.6.0-linux-64bit.zip

Dave

**Comment by daviddeakin2018** [comment]
Sorry.  It should have read https://github.com/gophish/gophish/releases/download/v0.6.0/gophish-v0.6.0-windows-64bit.zip

**Comment by daviddeakin2018** [comment]
Hi,

Any updates on this issue?

Thanks,

Dave

**Comment by jordan-wright** [comment]
Hi @daviddeakin2018,

Sorry for the delay! I was hoping to have this latest release out earlier than I did. I recommend giving 0.7.0 a shot to see if that helps fix the issue. I confirmed that the CSS files appear to be in that release, so hopefully that fixes the issue. I just don't have a Windows machine close by to help test it at the moment 🙁 

If, however, you notice that this is still broken with the latest release, let me know and I'll re-open this so we can worth together to troubleshoot. Thanks again for reporting this!

**Comment by daviddeakin2018** [comment]
Hi,

Problem still exists. Currently just tested again on v 0.7.1

Regards

**Comment by daviddeakin2018** [comment]
Hi Jordan,

These are also the steps I tried too…

Though I do see an error at the end of the gibberish mentioning TLS handshake issues – could this be related?


[cid:image001.png@01D46D0A.A4BB8400]

**Comment by jordan-wright** [comment]
Hi @daviddeakin2018,

Thanks for the quick response! I'm afraid it looks like the image didn't attach correctly. You may try uploading to something like [imgur.com](https://imgur.com/) to see if that helps.

**Comment by daviddeakin2018** [comment]
Hi Jordan,

Have attached it to this email rather than inline as before.  Chances are inline will only work if you are using MS Outlook your end.

Regards,

Dave

**Comment by jordan-wright** [comment]
Hi Dave,

I’m afraid it doesnt show up in the email or on this issue. If possible, please upload it one more time so that it shows up here. If it helps, Github supports dragging and dropping the image into the comment box, where it will automatically upload the image for you.

Thanks!

**Comment by daviddeakin2018** [comment]
![gophos screenshot](https://user-images.githubusercontent.com/39494965/47601921-016a4700-d9cf-11e8-8b1d-ee6bca58dd99.png)

**Comment by jordan-wright** [comment]
Hmmm... how odd. 🤔 everything looks fine in the terminal- you’re getting HTTP 200 status codes for the assets you’re requesting.

Out of curiosity, do you see the same behavior in an incognito tab? The goal here is to figure out if a browser extension may be interfering somehow.

**Comment by daviddeakin2018** [comment]
Hi Jordan,

Same issue on IE and Firefox.  Have not tried incognito mode – as the both IE and Firefox gave the same results I came to conclusion it was not a browser issue.

The other oddity is that if I use Chrome’s dev tools and bring up the CSS for the page – simply making any modification to the css (even a space in a white space area) suddenly makes Chrome render the page perfectly.  Obviously moving to the next page then it will look odd again – rinse and repeat etc.

Reading online I see things about CSS compression / decompression causing this same thing – however I’m not a web programmer or designer so have no need to dive that deep into this stuff.

Thanks,

Dave

**Comment by jordan-wright** [comment]
Sounds good, thanks Dave! Definitely something odd happening, but since I can't seem to replicate this no matter what I try and haven't heard of this happening to anyone else, there isn't much we'll be able to do.

If you ever figure out the root cause, I'd be very interested to hear what was causing the issue! 😄
