### ISSUE TITLE
Import site Api endpoint don't Work

### ISSUE THREAD

**Issue by script-tornado** [gophish/gophish#1102]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.5.0

Brief description of the issue: 
Import/site Endpoint don't work

What are you expecting to see happen? :
Response 201

What are you seeing happen?
with postman
{
    "message": "Method not allowed",
    "success": false,
    "data": null
}
 response 400 with python

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - make post request with Postman
https://xxx.xxx.xxx.xxx:3333/api/import/site/?api_key=xxxxxx
 * Option  2 - 
 post request with python
def importWebsite(website):
    r = requests.post("https://xxx.xxx.xxx.xxx:3333/api/import/site/?api_key=xxxxxx" + api_key, json={
        "url": "http://stripe.com"},headers=headersJson, verify=False)
    print(r.status_code, r.reason)

**Comment by jordan-wright** [comment]
Hi there! Thanks for reaching out.

I'm afraid I'm not quite sure what specific issue you'd be running into, but this seems to work fine for me:

```python
url = 'http://x.x.x.x'
api_key='redacted'
response = requests.post('https://localhost:3333/api/import/site?api_key={}'.format(api_key), json={'url': url}, verify=False).json()
```

Hope this helps!

**Comment by script-tornado** [comment]
It return 200k with you line of code and the website is not imported in gophish

**Comment by jordan-wright** [comment]
Oh, I see the problem. So, this api endpoint doesn’t actually save the page into Gophish. It’s mainly used as a “fetch” call that tells Gophish to get the HTML of the URL and return it. In the UX, this populates the editor with the HTML.

If you’re wanting to make a new page in Gophish, you will need to use this HTML when making a new landing page. You can find some sample code [here](https://gophish.gitbook.io/python-api-client/landing-pages).

In all reality, if you’re just needing to fetch the HTML to add to a page, you can probably skip the import site API and use requests directly. It’s mainly there for the UI- I only expose it and document it for transparency.

I hope this helps!
