### ISSUE TITLE
it doesnt work on my microsoft live login page

### ISSUE THREAD

**Issue by killercoderz4** [gophish/gophish#1103]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.6.0

Brief description of the issue: 
Good day. i setup gophish on ubuntu linux. it working fine and test email and everything. i sent a test campaign on my test workstation. the landing page i used was my https://login.live.com login page. i cloned it and used it as my landing page. when i opened my email and went  to the cloned page , if i type my outlook email it shows an error incorrect data, but on the main microsft live site it works. i noticed it can only work on sites like github with username and password field in one page. my live  site when username is put and you click next it redirect to the password page. but in this case the clone page just writes out an error, no data captured , no reports made. it doesn't just work. you can try it yourself.any help would be appreciated. Thanks
What are you expecting to see happen? :

What are you seeing happen?
i expect it to acknowledge my outlook username and redirect me to password page were i input my pasword and it redirect to a page based on the redirect page i setup in ,landing page. and finally gophish captures submitted data. but none of this happens. no submitted data captured  ,or it doesnt even go past the username page in the cloned site.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:
no terminal output error
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - easiest way is so setup a test campaign for https://login.live.com/ . you would see that typing your personal valid username of of your microsoft account throws error wrong contact . and it doesnt handle site with redirects to login page were the username is on one page and password on the other.just try a campaign on live login Microsoft
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi there!

I'm afraid that multi-step landing pages are not currently supported by Gophish. We have plans to build a more comprehensive campaign creator in #223, but I don't have an ETA on that quite yet.

In the meantime, I recommend just adjusting the imported page to include any other input fields (such as a password) that you might need for your phishing simulation.

Sorry there's not more we can do to help resolve this!
