### ISSUE TITLE
Credentials are not captured 

### ISSUE THREAD

**Issue by mcvaa** [gophish/gophish#1105]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  Gophish version 0.5.0

Brief description of the issue: 

What are you expecting to see happen? :  Credentials Captured 

What are you seeing happen? 
![image](https://user-images.githubusercontent.com/14318521/41166102-661606ac-6b0d-11e8-9b72-73e568b9cf0a.png)

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:
<html>
<head>
	<title></title>
</head>
<body>
<p>{{.FirstName}}</p>

<p>We would like to inform you the Personal Security Key for your ESI account will require authentication before the new usr accounts expire.</p>

<p>This email sent to safeguard the ESI {{.Email}} against authorized activity. For safety to your online account click the link below to reactivate your key:</p>

<p><a href="{{.URL}}">ESI Link</a></p>

<p>Thank you for your cooperation with this matter.</p>

<p>IT Services</p>

<p>{{.Tracker}}</p>
</body>
</html>

```html
Insert code here
```

Please provide any terminal output that may be relevant below: 
Clicking on the link of the email I am able to access the landing page input the credentials and am redirected to the web page. The credentials are not recorded in the gophish server. 
```
Insert output here
```
![image](https://user-images.githubusercontent.com/14318521/41166366-14fd84e2-6b0e-11e8-9c33-690dbabcb17b.png)

Please provide as many steps as you can to reproduce the problem:
 * Step 1 -  After logging into the phishing landing page I am redirected to the website created for our training. Verifying the information in the submitted data I am only receiving variables as the screen shot shows.

**Comment by mcvaa** [comment]
I have gone ahead and updated to the latest Gophish version 0.6.0 having the same issue.

**Comment by dudsan** [comment]
There could be something wrong with your landing page. Can you provide it?

**Comment by mcvaa** [comment]
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml"><head>
	<base href="https://store.esi.net/Login/Login.aspx"/><script type="text/javascript" src="../JScripts/Common/jquery-1.7.1.min.js"></script><noscript>jquery javascript</noscript><script type="text/javascript" src="../JScripts/JQueryModelpopup/jquery.ui.core.js"></script><noscript>ui javascript</noscript><script type="text/javascript" src="../JScripts/JQueryModelpopup/jquery.ui.widget.js"></script><noscript>ui widget javascript</noscript><script type="text/javascript" src="../JScripts/JQueryModelpopup/jquery.ui.button.js"></script><noscript>ui button javascript</noscript><script type="text/javascript" src="../JScripts/JQueryModelpopup/jquery.ui.position.js"></script><noscript>ui position javascript</noscript><script type="text/javascript" src="../JScripts/JQueryModelpopup/jquery.ui.dialog.js"></script><noscript>ui dialog javascript</noscript><script src="../JScripts/Common/jquery.validate.min.js" type="text/javascript"></script><noscript>validate javascript</noscript><script type="text/javascript" src="../JScripts/Page/jquery.Login.js"></script><noscript>page javascript</noscript><meta name="description" content="Login"/><meta name="keywords" content="Login"/><meta name="robots" content="noindex, nofollow"/>
	<title>LogOn | ESI SmartStore</title>
	<link href="https://www.varstreet.com/VarstreetXCStoreThemes/Template6/VSFooter.css" rel="stylesheet" type="text/css"/>
	<link href="https://www.varstreet.com/VarstreetXCStoreThemes/Template6/VSHeader.css" rel="stylesheet" type="text/css"/>
	<link href="../App_Themes/Template6/CartPreview.css" rel="stylesheet" type="text/css"/>
	<link href="../App_Themes/Template6/JQueryModelPopupCss/jquery.ui.button.css" rel="stylesheet" type="text/css"/>
	<link href="../App_Themes/Template6/JQueryModelPopupCss/jquery.ui.core.css" rel="stylesheet" type="text/css"/>
	<link href="../App_Themes/Template6/JQueryModelPopupCss/jquery.ui.datepicker.css" rel="stylesheet" type="text/css"/>
	<link href="../App_Themes/Template6/JQueryModelPopupCss/jquery.ui.dialog.css" rel="stylesheet" type="text/css"/>
	<link href="../App_Themes/Template6/JQueryModelPopupCss/jquery.ui.theme.css" rel="stylesheet" type="text/css"/>
	<link href="../App_Themes/Template6/ProductListing.css" rel="stylesheet" type="text/css"/>
	<link href="../App_Themes/Template6/Template6.css" rel="stylesheet" type="text/css"/>
	<link href="../App_Themes/Template6/VSGrid.css" rel="stylesheet" type="text/css"/><script type="text/javascript"></script>
</head>
<body class="vsBody">
<form action="" method="post" name="form"> </form>

<form action="" id="frmLogin" method="post" name="frmLogin"><input type="hidden" value="https://store.esi.net/Login/Login.aspx./Login.aspx"/> <input id="__VIEWSTATE" type="hidden" value="3Abkh4cBe1P+ldpYp0++3/2aIMS6INrsvjVefbZmO4kNlQMDu/jDT7Lq1mSy38zOmVbfBmMhbjcJNJCdLhW00PzauJKO/DjbGn6X106HRzQTro36zq2tMARK6Ys77yTi4zBKbhIIzjL4vAr3ipLDLDV3Kk2Ns8puSjnTyPhJCa+cWpIEJP/g5U6nGTb39WG01uR7NsinQDG34j4XbJNi6v5cyujmPSxWXUZ4dsst1iY7KM3a1HrQqVLjiEen1TZYl7jrCFj4y1wdiohZ3VDX5e+IHOy+yPYdy4UC4bL5F0IMeOxzeTc6BvjhcE/8F2K9eLxcgra8k2y9BxxL6HKQNZsReoslf6gxEO7K1iqpgXVkaSrtozw9H8L/VnE0/NLL3ihE4/KHxmZ3RQaxXJvFnJghmqTvkHJwL8ZJEfO8uHHpyvuT"/> <input id="__VIEWSTATEGENERATOR" type="hidden" value="1806D926"/> <input id="__PREVIOUSPAGE" type="hidden" value="bdahKpN5ZX0ZiggkQy3s8r6vYp-RwaX-b6rbcSsgFkGhQc4Q1fJgkeMgADgiCBVLuQEajZl6XEN2KE1JhKVDSDPHjHI1"/> <input id="__EVENTVALIDATION" type="hidden" value="jFhEDBFseUvHImXCx0hkX5kxpJcX8iTNQC394fsscjOd4wU0TjTvkQK56O4LdboSJ39tDj8LyDZxFvFN7s4xtHdVQa2r8JuaocmHzG/CHBKMMMiHW3HxyPbRxrC3Fg2OXRDEYlG7gk5r0b+UChyHiOJspVJcNsyukdiTWKKX4vzkIZtKufYn9tV1nW5dr0Xxu+3pQDYUT8zUI7CwBeWB/xZ5uFfe1h8QMduvRd1c1dIyF1ijrswZEeZXCzocsw3NO5L3yA=="/> <input id="hdnShowLegalTerms" type="hidden" value="N"/>
<div id="CenterDiv">
<table border="0" cellpadding="0" cellspacing="0" id="tblMain" width="980">
	<tbody>
		<tr>
			<td colspan="3" id="tdHeader" valign="top">
			<table border="0" cellpadding="0" cellspacing="0" class="vsTableLoginHeaderControl" id="ctl27_VSHeaderControl">
				<tbody>
					<tr>
						<td width="1%"> </td>
						<td align="Left" valign="Middle" width="40%">
						<table border="0" cellpadding="3" cellspacing="0" id="ctl27_ctl03_tblHeaderLogo">
							<tbody>
								<tr>
									<td align="center" valign="middle"><span><span><a href="#" style="border: 0px currentColor; border-image: none;"><img align="Middle" alt="Electronic Systems, Inc." border="0" src="https://cdn.varstreet.com/VarstreetXCStoreDesign/6295\Store_323\Logo\VerticalStoreLogo_130535325471036938_Img_9576.JPG" title="Electronic Systems, Inc."/></a></span></span></td>
								</tr>
							</tbody>
						</table>
						</td>
					</tr>
				</tbody>
			</table>
			</td>
		</tr>
		<tr>
			<td id="tdCentralPane" valign="middle">
			<table border="0" class="Login" id="tblLoginMain" width="100%">
				<tbody>
					<tr>
						<td width="2%"> </td>
						<td width="45%">
						<table border="1" class="vsTableLoginControl" id="tblLogin" width="245">
							<tbody>
								<tr>
									<th align="center" class="LoginHeader" style="padding-left: 10px;" valign="middle"><span class="vsLabelLoginHeader">Logon to Site</span></th>
								</tr>
								<tr class="LoginBody">
									<td>
									<table border="0" cellpadding="2" width="100%">
										<tbody>
											<tr>
												<td align="left" colspan="2" valign="middle">
												<div class="vsErrorClass" id="errorContainer">
												<p><strong>FAILURE:</strong></p>
												</div>
												</td>
											</tr>
											<tr>
												<td align="right" valign="middle" width="30%"><span class="vsLabelDisplayBold" id="lblUserName">E-mail:</span></td>
												<td width="70%"><input class="vsTextbox" id="txtUserName" maxlength="50" title="UserName" type="text"/></td>
											</tr>
											<tr id="trPassword">
												<td align="right" valign="middle" width="30%"><span class="vsLabelDisplayBold" id="VSPassword">Password:</span></td>
												<td width="70%"><input class="vsTextbox" id="txtPassword" maxlength="20" title="Password" type="password"/> <input id="hdnIsByodFlag" type="hidden" value="0"/></td>
											</tr>
											<tr>
												<td align="right" colspan="2" style="padding-right: 6px;" valign="middle"><input alt="Submit" border="0" class="vsImageButtonSubmit" id="imgBtnSubmit" src="../App_Themes/Template6/Images/Login/Submit.png" title="Submit" type="image"/></td>
											</tr>
											<tr>
												<td align="left" colspan="2" valign="middle"><span class="vsLabelDisplayBold" id="lblNotRegistered">Not Registered ?</span></td>
											</tr>
											<tr>
												<td align="left" colspan="2" valign="middle"> </td>
											</tr>
											<tr>
												<td align="left" colspan="2" valign="middle"><span class="vsLabelDisplayBold" id="lblCustomerSupport">Customer Support Center</span></td>
											</tr>
											<tr id="trCallUs">
												<td align="left" colspan="2" valign="middle"><span class="vsLabelDisplay" id="lblCallUs">Call us </span></td>
											</tr>
											<tr id="trLoginDisplayMessage">
												<td align="left" colspan="2" valign="middle"> </td>
											</tr>
											<tr>
												<td align="left" colspan="2" valign="middle"><span class="vsLabelDisplay" id="lblEmailUs">eMail us </span></td>
											</tr>
										</tbody>
									</table>
									</td>
								</tr>
							</tbody>
						</table>
						</td>
						<td align="right" valign="bottom" width="50%">
						<table border="0" cellpadding="1" cellspacing="3" id="tblMessages" width="100%">
							<tbody>
								<tr>
									<td align="left" valign="middle"> </td>
								</tr>
								<tr>
									<td align="left" valign="middle"> </td>
								</tr>
								<tr>
									<td style="height: 20px;"> </td>
								</tr>
							</tbody>
						</table>
						</td>
					</tr>
				</tbody>
			</table>
			</td>
		</tr>
		<tr>
			<td colspan="3" id="tdFooter" valign="bottom">
			<table border="0" cellpadding="0" cellspacing="0" id="ctl28_VSFooterControl" width="100%">
				<tbody>
					<tr>
						<td>
						<table cellpadding="0" cellspacing="0" class="vsTableFooterControl" width="100%">
							<tbody>
								<tr>
									<td align="Left" valign="Middle" width="33%">
									<table border="0" cellpadding="1" cellspacing="0" class="vsTableTAndCControl" id="ctl28_ctl05_VSTAndCControl">
										<tbody>
											<tr>
												<td align="Left" valign="Middle" width="100%"> </td>
											</tr>
										</tbody>
									</table>
									</td>
									<td align="Center" valign="Middle" width="34%">
									<table border="0" cellpadding="1" cellspacing="0" class="vsTableSecurityImageListControl" height="32" id="ctl28_ctl07_VSSecurityImageListControl" width="70%">
										<tbody>
											<tr>
												<td align="Center" valign="Bottom" width="25%"><span><span><img alt="McAfee Secure sites help keep you safe from identity theft, credit card fraud, spyware, spam, viruses and online scams" border="0" onclick="window.open(&#39;https://www.mcafeesecure.com/RatingVerify?ref=www.varstreet.com&#39;,&#39;newwindow&#39;,&#39;width=600,height=400,scrollbars=yes,resizable=yes&#39;);return false;" src="https://images.scanalert.com/meter/www.varstreet.com/13.gif" title="McAfee Secure sites help keep you safe from identity theft, credit card fraud, spyware, spam, viruses and online scams"/></span></span></td>
											</tr>
										</tbody>
									</table>
									</td>
									<td align="Right" valign="Middle" width="33%">
									<table border="0" cellpadding="1" cellspacing="0" class="vsTableCreditCardTypeListControl" height="45" id="ctl28_ctl09_VSCCTypeListControl">
										<tbody>
											<tr>
												<td align="Center" valign="Middle" width="100%"> </td>
											</tr>
										</tbody>
									</table>
									</td>
								</tr>
							</tbody>
						</table>
						</td>
					</tr>
				</tbody>
			</table>
			</td>
		</tr>
	</tbody>
</table>
</div>

<div class="vsTableCartSuggestions" id="LegalTermsDiv" title="Legal Terms &amp; Conditions">
<div align="center" cellpadding="3" id="divCotent" style="width: 100%; text-align: justify; color: rgb(0, 0, 0); font-family: Verdana,Courier; font-size: 10px; font-style: normal; font-weight: normal;"> </div>
</div>
</form>


</body></html>

**Comment by dudsan** [comment]
Hello again.

Sorry, but I wasn't able to reproduce your issue. I managed to capture the submitted data. Here's what I got (note not only the x and y parameters have been captured, but also others, amongst them txtUserName):

![captured](https://user-images.githubusercontent.com/32961787/41181485-2b7a7588-6b48-11e8-836a-bbb0559dd045.jpg)

Please bear in mind I, myself, am also a newbie here, but I'd suggest you go through the docs and try to create your campaign again. Perhaps you are missing something?

Cheers.

**Comment by jordan-wright** [comment]
Hi @mcvaa - thanks for reaching out!

A common issue when using an imported page to capture credentials is that sometimes the forms are submitted via Javascript, which can cause all sorts of issues that we wouldn't be able to account for when importing the page. So one thing you'll want to do is to try and remove any Javascript that might be submitting the form on the page's behalf.

Another thing you'll want to do is to add a `name` attribute to each `input` element on the page. Consider this element:

```
<input class="vsTextbox" id="txtUserName" maxlength="50" title="UserName" type="text"/>
```

In this case, since there is no `name` attribute, the parameter won't be sent. If you change this to instead look like this:

```
<input class="vsTextbox" name="txtUserName" id="txtUserName" maxlength="50" title="UserName" type="text"/>
```

The parameter should be sent with no issues. In the future, I might consider updating our site import to handle cases where the parameter has an `id` parameter, but no `name` parameter and add a `name` parameter that matches the `id` since I see this come up relatively frequently.

Hope this helps!

**Comment by mcvaa** [comment]
@jordan-wright 

Updating the input worked perfectly, thank you. :)

**Comment by maddy45** [comment]
thanks @jordan-wright it was so helpful
