### ISSUE TITLE
Trouble With Import Group API - Target Method Undefined

### ISSUE THREAD

**Issue by loza0269** [gophish/gophish#1106]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
.4
Brief description of the issue: 
Attempting to run the sample code on the API documentation, but receiving error that the the method 'Target' is undefined.

What are you expecting to see happen? :
It should import a new group with the target emails inside of it.

What are you seeing happen?
from gophish import Gophish
from gophish.models import *

are not importing the correct methods

Please provide any terminal output that may be relevant below:

C:\Python36-32>python.exe C:\Users\clozach\Documents\Python\gophishPostGroup.py
Traceback (most recent call last):
  File "C:\Users\clozach\Documents\Python\gophishPostGroup.py", line 15, in <mod
ule>
    Target(first_name='John', last_name='Doe', email='johndoe@example.com'),
NameError: name 'Target' is not defined

Please provide as many steps as you can to reproduce the problem:
`import urllib.parse
import requests
import time
import http.client
from gophish import Gophish
from gophish.models import *

api_key = 'fakeapikey'
api = Gophish(api_key, host = 'http://xxx.xxx.xxx.xxx:3333/', verify = False)

targets = [
	Target(first_name='John', last_name='Doe', email='johndoe@example.com'),
	Target(first_name='John', last_name='Doe', email='johndoe@example.com')]
	
group = Group(name='Does', targets=targets)
group = api.groups.post(group)
print (group.id)`

**Comment by jordan-wright** [comment]
My apologies! It seems that our API documentation was incorrect. While I represent members of a group as "Targets" internally to Gophish, I didn't think this would be the best way to represent them in the API client.

Instead, I chose to make a `User` class, which represents the member of a group. This should be used instead of `Target` as follows:

```python
import requests
from gophish import Gophish
from gophish.models import Group, User

api_key = 'redacted'
api = Gophish(api_key, host='x.x.x:3333', verify=False)

targets = [
    User(
        first_name='John',
        last_name='Doe',
        email='foo@example.com',
        position='Systems Administrator'
    )
]

group = Group(name='Test Group', targets=targets)
group = api.groups.post(group)

print(group.id)
```

Also note that the API client currently only supports Python 2.7 (I noticed this when I was testing out this script, so I'll get that fixed).

Hope this helps!
