### ISSUE TITLE
Static content is being served from the

### ISSUE THREAD

**Issue by hunbelievable** [gophish/gophish#1113]
What version of Gophish are you using?: 
0.6.0
Brief description of the issue: 
Static content is only accessible from the admin server. That is to say that I can reach static assets when I go to: https://somedomain.com:3333/images/logo.png but I can not reach them at http://somedomain.com/images/logo.png.

What are you expecting to see happen? :
If I go to http://somedomain.com/images/logo.png I would see the gophish logo

What are you seeing happen?
I get a 404

Why is this a problem?
Perhaps I have a misunderstanding on how the pages are to be built, but the static content being served from the admin_server means that I have to have valid certs on the server for content to be trusted on the landing page. I would prefer to have the page served http vs https as that is another cue that I want users to observe and avoid...

Is there a way for me to serve static content from the phish_server?

config.json:
{
        "admin_server" : {
                "listen_url" : "0.0.0.0:3333",
                "use_tls" : true,
                "cert_path" : "gophish_admin.crt",
                "key_path" : "gophish_admin.key"
        },
        "phish_server" : {
                "listen_url" : "0.0.0.0:80",
                "use_tls" : false,
                "cert_path" : "example.crt",
                "key_path": "example.key"
        },
        "db_name" : "sqlite3",
        "db_path" : "gophish.db",
        "migrations_prefix" : "db/db_"
}

Workarounds:
fix certs
serve static content from a CDN or other...

comments:
Thanks for any help!

**Comment by jordan-wright** [comment]
Hi @hunbelievable,

Thanks for reaching out!

There is a way to do that. You can refer to #220 or [our documentation](https://gophish.gitbook.io/user-guide/documentation/landing-pages#static-assets) for more info on how to do this.

In a nutshell, you'll want to put the image under the static/endpoint directory in your folder structure. So, my Gophish folder may look something like this:

```
/
    static/
        endpoint/
            logo.png
```

Then, to actually reference it in the phishing server, you would do `http://site/static/logo.png` (note that we don't include "endpoint" here).

Hope this helps!

**Comment by hunbelievable** [comment]
Thanks Jordan! I had read that post before asking, and it just didn't click for me... 
I guess that I would note that there are a bunch of folders in "static" (css, db, font, images, js) but none of them were endpoint. Obviously I could create that, but that wasn't very intuitive for me... Perhaps having that directory in the build by default would help? I would also suggest that there be similar directory structure in the "endpoint" directory (css, db, font, images, js) so that it can be kept clean. 

Either way thanks for the help and wicked fast reply!
