### ISSUE TITLE
Campaign not working

### ISSUE THREAD

**Issue by Shrutirupa** [gophish/gophish#1115]
I am able to send test email via gophish but when I am trying to send via campaign, I only get a message that email has been sent but in reality, the email has not been sent yet. 

Initially, I could send mail only to few email ids but now, none of them are receiving any mails via campaign, where as the test mail is working absolutely fine.

I am using the latest version of gophish.

Thanks in advance.

**Comment by jordan-wright** [comment]
Hi @Shrutirupa,

Sorry for the delay in getting back to you. I'm afraid it'll be difficult to troubleshoot this with the information you provided. If you're still encountering issues, could you please create a new issue and fill in our issue template as much as possible? This will help us more quickly and easily troubleshoot what the issue might be in this case.

I apologize for the inconvenience!
