### ISSUE TITLE
Dashboard is wrong

### ISSUE THREAD

**Issue by DaveCach** [gophish/gophish#1124]
Firstly, thank you for such an amazing product.

I understand you are working w/ Duo, we may be working with them in my organization soon and was surprised to see GoPhish built in. Nice!!

What version of Gophish are you using?: 
0.6.0

Brief description of the issue: 
**The dashboard is showing incorrect statistics.**

What are you expecting to see happen? :
**I have email logs saying 7000 messages were sent, however, gophish says only 600 were sent. I can also confirm that mail was sent to users where in GoPhish it says 'sending' still. **

What are you seeing happen?
**The GoPhish logs indicate that the mail was sent, but dashboard is wrong.**

**Comment by jordan-wright** [comment]
Hi @DaveCach,

Thanks for reaching out!

> I understand you are working w/ Duo, we may be working with them in my organization soon and was surprised to see GoPhish built in. Nice!!

Thanks for the kind words, and thanks for considering Duo! I should note that [Duo Insight](https://insight.duo.com/) is actually a completely separate product from Gophish, and they don't share any of the same code.

From having been involved in the development of both, I can say that while Gophish has more features and flexibility, Duo Insight is _great_ for giving quality tests really quickly. It was built by incredibly talented engineers, so I'm a huge fan of it. And it's free! I recommend taking it for a spin if you have the chance.

I'm sorry to hear that the dashboard isn't reflecting accurate information. If you download the results, do they also say "Sending", or do they show the email as having been sent?

Gophish should update the result status as soon as an email has been sent successfully. You can see an example of that [here](https://github.com/gophish/gophish/blob/master/models/result.go#L58). I'm not sure off the top of my head what would cause the inaccurate information, unless Gophish was told by the mail server that the email wasn't sent successfully. If you expand the result in the campaign results page (to see the timeline), what does it say? Have there been any temporary errors that occurred, causing Gophish to back off?

Sorry I can't be more help out the gate. If there's any other information or redacted logs you could provide, it'd be much appreciated!

Thanks again for getting in touch.

**Comment by DaveCach** [comment]
Hi Jordan! 

Thanks for the response. 

In the raw / summary (csv) files it says that the email was 'sent' not sending.  We did have an issue with the campaign crashing within the first hour of it being sent, I am assuming I underspecced the VM. I rebooted it and upgraded it, and it continued OK from there out. 

Is there a safe way to get you the logs without providing them in a public setting? I just don't want the email addressees leaked (I could remove the domain name, if that is OK?)

**Comment by DaveCach** [comment]
Hey Jordan. 

I just had a second campaign (8000 ish email addresses) where the same thing happened.  Emails were sent, it initially showed them as sent, but GoPhish crashed and a significant amount of the recipients are in a 'sending' state.

**Comment by jordan-wright** [comment]
Hey @DaveCach!

Sorry for the delay in getting back to you. I'm sorry to hear that you encountered the issue again.

If the recipients are in a "Sending" state, then you may look in the database to see if there are any entries in the `mail_logs` table. This is a table that holds records about which emails need to be sent, and when they should be sent. If you see rows in here and they show as "locked" (the "processing" field is set to true), and you don't see Gophish actively sending them, then you might try manually running a SQL query to set that field to false. Then, on the next minute when the worker starts back up, it should pick these up and send them out.

I'd also be interested if you have any information on why Gophish crashed. For example, if it spit out a stack trace in the terminal or if you off hand know what caused it to tip over. Anything I can do to make Gophish more resilient is of interest to me! 😄

**Comment by jordan-wright** [comment]
Going ahead and closing this since there haven't been any updates in a while.

@DaveCach, if you're still running into issues, please don't hesitate to let me know. It's worth noting that I recently fixed a different bug in #1242 which may have been causing similar symptoms.

Thanks again for getting in touch!
