### ISSUE TITLE
Refresh function not working

### ISSUE THREAD

**Issue by DustinEJD** [gophish/gophish#1126]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
**0.6.0**
Brief description of the issue: 
**I have made GoPhish a service on my workstation using NSSM, and now whenever I launch a campaign I am only able to see if the person opened the email. None of the other stats are getting populated and the refresh button does not seem to function (I press it and it immediately finishes the processing animation of refreshing). I am using the same exact campaign as before I made GoPhish a service. So maybe it has something to do with making it a service? **
What are you expecting to see happen? :
**Some type of explanation of how to fix the error**
What are you seeing happen?
**Refresh button does not process as long as it used to**
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - **create campaign**
 * Step 2 - **press refresh button**

**Comment by jordan-wright** [comment]
Hi @DustinEJD,

Thanks for reaching out!

There's a few different things we'll need to track down. First, let's make sure that events are actually happening. Are you sending a copy of the email to yourself? If so, what does the link look like that you click in the email? Does it point to Gophish? And, if it does, do you see your landing page when you click then link? You'll also want to make sure you see a connection log appear in the Gophish terminal when you click the link.

Assuming all that works, then we need to figure out why the events aren't showing up in the dashboard. What do you see if you open the developer tools in the browser and watch the network traffic? Does it return a 200 OK status? Do you see the request sent out to get the new data? If you look at the console, do you see any Javascript errors? 

I know this is a lot of questions, but handling these one by one should help us figure out what's going on here.

Thanks again for getting in touch!

**Comment by DustinEJD** [comment]
Hi @jordan-wright,

I think I narrowed it down to the email not linking to GoPhish, it just seems to point to the actual landing page. I have gone through the settings, do you know off hand if I am forgetting a setting somewhere?

Thanks,
Dustin

**Comment by DustinEJD** [comment]
@jordan-wright I apologize, I forgot to put the {{.URL}} within the link, which is why it did not function. Thank you for the help!

**Comment by jordan-wright** [comment]
Glad you were able to get it working! Thanks for the update, and thanks again for getting in touch 😄
