### ISSUE TITLE
"From" Field Gives Option for email address only and not for Name

### ISSUE THREAD

**Issue by kashif23** [gophish/gophish#1129]
What version of Gophish are you using?: V0.6

Brief description of the issue: From Field Gives Option for email address only and not for Name

What are you expecting to see happen? : I want to send email using Name of the sender as well. i.e in recipient mailbox, the name of the sender should be visible along with his email address

What are you seeing happen?: The option for From field in Sending Profiles gives option for only email address and not for Sender's name.

Please provide as many steps as you can to reproduce the problem:
  Step 1 - Set up a sending profile
  Step 2 - In the sending profile, you only find option to enter Sender's email address and not his name

**Comment by jordan-wright** [comment]
Hi @kashif23,

Thanks for reaching out!

Take a look at [this page](https://gophish.gitbook.io/user-guide/building-your-first-campaign/creating-the-sending-profile) in our docs, and you'll find an example showing the syntax of how to input a name along with the email address.

If you run into any issues with that, if you could provide the input you're putting into the sending profile, it'll help us track down what may be the issue and I will be more than happy to re-open this so we can continue troubleshooting.

Thanks again for getting in touch!
