### ISSUE TITLE
Python API for Summary View

### ISSUE THREAD

**Issue by the1aughingman** [gophish/gophish#1133]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.6.0

Brief description of the issue: Trying to use the python API to show the summary of a campaign keeps throwing an error.

What are you expecting to see happen? :

summary = api.campaigns.summary(campaign_id=6)
print(summary.stats.as_dict())

to show the summary of campaign ID 6

What are you seeing happen?:

Traceback (most recent call last):
  File "test.py", line 14, in <module>
    summary = api.campaigns.summary(campaign_id=6)
TypeError: summary() got multiple values for keyword argument 'campaign_id'

I have been using the code provided by the python-api-documentation page as a stepping stone but have had no luck yet. Here is my code below:

![code](https://user-images.githubusercontent.com/33363346/42703909-f626136e-869b-11e8-9dae-e8cc513282c2.PNG)

I have tried several different modifications with no luck either. I also referenced a previous similar issue from last year and used the same code that the user provided and still got the same error. My error can be seen below as well.

![error](https://user-images.githubusercontent.com/33363346/42703952-1c4fe9de-869c-11e8-9833-e183373d8476.PNG)

I have run a pip update for gophish, installed everything to the exact versions in the documentations, tried rollbacks, and modifications but just can't seem to find a solution to this one.

**Comment by the1aughingman** [comment]
I think I fixed it but the workaround is strange. Updating my build via pip gave me a different version from what has been posted with the documentation on github. Copying the gophish folder from the api-client-python page on github into the /.local/lib/python2.7/site-packages/gophish/api directory to replace the version from pip made everything work proper. I'm not sure why the version that kept coming with the pip install -u gophish had different code for the files but now it works.

![works](https://user-images.githubusercontent.com/33363346/42705258-bf85d920-86a0-11e8-8ee5-ec906ebc606c.PNG)

**Comment by jordan-wright** [comment]
Hi @the1aughingman,

Thanks for reaching out! Sorry for the delay in getting back to you. I've bumped up the version in PyPi to 0.1.5 which includes the fix for the campaign summary. Updating from pip should give you the correct version 😄 

Thanks again for letting me know about this!
