### ISSUE TITLE
Hide RID in URL

### ISSUE THREAD

**Issue by Clunkline** [gophish/gophish#1135]
**What version of Gophish are you using?:**
0.6.0
**Brief description of the issue:** 
Is it possible to dont show the rid in url on landing page?
**What are you expecting to see happen? :**
When a user clicks a link from the mail, it is redirected to the landing page and it looks like "normal"
**What are you seeing happen?**
When users click on a link to my phishing page, there is the RID code in the URL, which in "real life" would not be the there. This is a huge indication for users to realize that the page might be phishing.

Is there any way to hide it or it possible for example to redirect or something?

Thanks!
J

**Comment by jordan-wright** [comment]
Hi @Clunkline,

Thanks for reaching out! The `rid` parameter is how Gophish knows who clicked the link. There's no way to remove it completely but if you'd like to change it from `rid` to something else, you can build from source, modifying [this variable](https://github.com/gophish/gophish/blob/master/models/campaign.go#L123). Just know that any campaigns that were launched previously won't work anymore, since Gophish will be looking for a different parameter when events like clicks and email opens are received.

Hope this helps!

**Comment by antonbek89** [comment]
> Hi @Clunkline,
> 
> Thanks for reaching out! The `rid` parameter is how Gophish knows who clicked the link. There's no way to remove it completely but if you'd like to change it from `rid` to something else, you can build from source, modifying [this variable](https://github.com/gophish/gophish/blob/master/models/campaign.go#L123). Just know that any campaigns that were launched previously won't work anymore, since Gophish will be looking for a different parameter when events like clicks and email opens are received.
> 
> Hope this helps!

So I deleted the old campaign.go file
create a new campaign.go file and change the rid

Next, I run the gophish and its not work for me

Did I miss some steps?

**Comment by ankitk323** [comment]
Hi @jordan-wright 

Thank you for your guidance it's working for me. I want to convert the value of the "rid" parameter to base64.

Thanks
Ankit

**Comment by Genesiss2** [comment]
> Hi @Clunkline,
> 
> Thanks for reaching out! The `rid` parameter is how Gophish knows who clicked the link. There's no way to remove it completely but if you'd like to change it from `rid` to something else, you can build from source, modifying [this variable](https://github.com/gophish/gophish/blob/master/models/campaign.go#L123). Just know that any campaigns that were launched previously won't work anymore, since Gophish will be looking for a different parameter when events like clicks and email opens are received.
> 
> Hope this helps!

Hi
I changed gophish/models
/campaign.go const RecipientParameter = "user"; Saved it, reloaded the server, but the changes did not take effect, where does it get the rid from - when gophish is installed?

**Comment by Brumbpo-Tungus** [comment]
> Hi @Clunkline,
> 
> Thanks for reaching out! The `rid` parameter is how Gophish knows who clicked the link. There's no way to remove it completely but if you'd like to change it from `rid` to something else, you can build from source, modifying [this variable](https://github.com/gophish/gophish/blob/master/models/campaign.go#L123). Just know that any campaigns that were launched previously won't work anymore, since Gophish will be looking for a different parameter when events like clicks and email opens are received.
> 
> Hope this helps!

Hey, is this now L130? Just checking as the campaign.go file seems to have changed.
