### ISSUE TITLE
GoPhish on cPanel account bluehost, hostmonster or hostgator

### ISSUE THREAD

**Issue by hakeem19** [gophish/gophish#1137]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.6

Brief description of the issue: Hi everyone, thanks for this very useful tool. Newbie here so excuse me if my request is not applicable. The tool worked with me perfectly on windows but I'm looking to installing and configuring it cPanel shared hosting account on Hostmonster to make it public. Is it possible? Is there any sort of guide or procedure available, I couldn't find any. Thanks,

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by stracire** [comment]
You need a server/VPS instead of a webhost. Most likely it will not work on a webhost.

**Comment by hakeem19** [comment]
So I figured, thanks for your reply

**Comment by jordan-wright** [comment]
@stracire is correct- a VPS is almost certainly needed to run Gophish. Going ahead and closing this since the original question has been answered. Thanks for getting in touch @hakeem19!
