### ISSUE TITLE
The system cannot find the file specified.

### ISSUE THREAD

**Issue by octavian1213** [gophish/gophish#1138]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.6.0
Brief description of the issue: 
error message running on windows
What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:
time="2018-07-18T12:28:30-04:00" level=info msg="open gophish_admin.key: The system cannot find the file specified."
```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by octavian1213** [comment]
config.json 
	"admin_server" : {
		"listen_url" : "127.0.0.1:3333",
		"use_tls" : true,
		"cert_path" : "gophish_admin.crt",
		"key_path" : "gophish_admin.key"
	},
	"phish_server" : {
		"listen_url" : "0.0.0.0:80",
		"use_tls" : false,
		"cert_path" : "example.crt",
		"key_path": "example.key"
	},
	"db_name" : "sqlite3",
	"db_path" : "gophish.db",
	"migrations_prefix" : "db/db_"
}

**Comment by octavian1213** [comment]
i was able to get this working.

**Comment by justaskingquestions** [comment]
Care sharing what the problem was? file removed? permissions?

**Comment by octavian1213** [comment]
Not sure i re downloaded and redid stuff and worked l


Sent from Yahoo Mail for iPhone


On Thursday, July 19, 2018, 10:01 AM, justaskingquestions <notifications@github.com> wrote:


Care sharing what the problem was? file removed? permissions?

**Comment by jordan-wright** [comment]
Good to hear you were able to resolve the issue!
