### ISSUE TITLE
not able to get results

### ISSUE THREAD

**Issue by octavian1213** [gophish/gophish#1140]
after trying with external ip of my network where my gophish is and the domain.
i get no results.

**Comment by justaskingquestions** [comment]
Sorry @octavian1213 , but with that little info you cannot reasonably expect your problem to be fixed.

What do you mean by trying?
What do you mean by "external ip of my network"? 
Is this hosted somehwere on a cloud provider or at your own network? 
Did you forward the port to your gophish server?
What do you mean by "no results"? No emails opened? No clicks?

What does the logging output of gophish say for the time you accesssed it?

**Comment by octavian1213** [comment]
nevermind, we were able to work around this .
was a thing with our network security .

**Comment by jordan-wright** [comment]
Glad to hear you were able to get it resolved!
