### ISSUE TITLE
Suggestion for improvement

### ISSUE THREAD

**Issue by onixdclxvi** [gophish/gophish#1141]
Please add the possibility of randomization of attached files, for example, that in the company, each new letter attached file by reference to the site.

**Comment by jordan-wright** [comment]
Hi @onixdclxvi,

Thanks for reaching out!

The attachment support in Gophish is already very simple - it only supports the attaching of files to emails, and the open/tracking of those attachments isn't currently supported.

With the little value we get out of attachments now, I'm afraid I don't plan to dedicate the development time to implementing randomized attachments at this time. This would be tricky to implement server-side, and arguably even harder to implement in the UI to make it easy to understand.

Thanks again for getting in touch!
