### ISSUE TITLE
Scheduled emails stopped being sent.

### ISSUE THREAD

**Issue by apomies** [gophish/gophish#1142]
Greetings!
I have downloaded GoPhish and configured a campaign with a group of 1800+ users.
The point is, emails was sent correctly for half of the group (900+ users) but the rest of them remains "Scheduled".
The campaign was scheduled to start at, lets say "July 19 4:40 pm", but today the remaining users says "Scheduled" for July 19 4:40 pm.
Is there any way to force the Scheduled emails to be sent or is there some preconfigured delay after a large part of the user`s group was reached?
There are no errors in any email sent, and the campaing is still working, because the Open, Clicked and Submitted info is being updated.

Thanks!!

**Comment by jordan-wright** [comment]
Hi @apomies,

I'm afraid it's tricky to tell what's going on based off the description. What I'd suggest doing is checking the `maillogs` table in the database to check the values of the `send_at` field. This is the field that determines when each email is set to send.

Also, are there any logs in the Gophish terminal that may indicate what's going on?

**Comment by apomies** [comment]
Thanks for your answer, @jordan-wright 

I have checked the maillogs table and I only see the mails that weren`t sent.
Their send_date are OK, but they are not being sent.
Should I change them manually to a more recent date or maybe restart the service?
I assume this wont stop the running campaign.

**Comment by apomies** [comment]
UPDATE:

It seems that restarting the service resolve this issue.
Maybe it stopped because of the large list of users, and restarting force it to "re-take" the database values, sending the delayed mails.

Thanks for your help!

**Comment by jordan-wright** [comment]
Ah, interesting. Glad to hear that restarting Gophish fixed the issue. Thanks for keeping us updated!
