### ISSUE TITLE
windows 10 installation 

### ISSUE THREAD

**Issue by alek-smit** [gophish/gophish#1153]
I've downloaded all the needed packages and I still don't know what to, I've tried running gocode on 
 sublime and I failed, I really need help a step by step instructions on what to do to install gophish
thank you

**Comment by jordan-wright** [comment]
Hi @alek-smit,

Thanks for reaching out! You can find the installation instructions in our documentation [here](https://gophish.gitbook.io/user-guide/installation).

Hope this helps!
