### ISSUE TITLE
Personalised landing page

### ISSUE THREAD

**Issue by sssseossss** [gophish/gophish#1156]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.6.0
Brief description of the issue: 
I cannot put {{.EMAIL}} into the landing page .
What are you expecting to see happen? :
Email added to the login field - so that user does not have to type it in. Name would be also very handy as this would allow a minimum personalisation for the landing page. 
What are you seeing happen?
It gets me error 404 when I try opening landing page.
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:
just adding```
 value="{{.EMAIL}}"
```
Is it not supported? Many thanks!

**Comment by jordan-wright** [comment]
Hi @sssseossss,

Just curious, have you tried `{{.Email}}`? The template variables are case specific from [here](https://gophish.gitbook.io/user-guide/template-reference).

Also, what does the link in the email look like? Does it have an `rid` parameter? If you are visiting the Gophish server directly and not using a link sent by Gophish, you will see a 404.

Finally, are there any messages in the Gophish terminal that may give an indication as to what's going on?

**Comment by sssseossss** [comment]
My friend, your sharp eye identified the issue immediately. Many thanks!
