### ISSUE TITLE
add user reports statistic to GoReport

### ISSUE THREAD

**Issue by oded86w** [gophish/gophish#1160]
What version of Gophish are you using?: 
0.6
Brief description of the issue: 
add reports statistic to GoReport

Hey , Are you can help me to add to GoReport the new feature users reports to docx report ?
Thank you .

**Comment by jordan-wright** [comment]
Hi @oded86w,

I see that there's an issue already created at https://github.com/chrismaddalena/GoReport/issues/16. I recommend working through that issue, since this is related to GoReport.

Thanks!
