### ISSUE TITLE
"gcc": executable file not found in $PATH

### ISSUE THREAD

**Issue by yahirlevine** [gophish/gophish#1161]
root@debian-s-1vcpu-1gb-lon1-01:~# go get github.com/gophish/gophish
# github.com/mattn/go-sqlite3
exec: "gcc": executable file not found in $PATH

**Comment by ad0nis** [comment]
This means that you don't have GCC installed, and it's needed. You can probably get away with 'apt-get install gcc', but I usually use 'apt-get install build-essential'.

**Comment by jordan-wright** [comment]
@ad0nis is absolutely correct. To build Gophish from source, you will need to have `gcc` installed.

Hope this helps! Thanks for getting in touch!
