### ISSUE TITLE
static page 

### ISSUE THREAD

**Issue by pastechecker** [gophish/gophish#1162]
What version of Gophish are you using?: Current Version: 0.6.0

**Brief description of the issue:** 
I want to create a static website that is mirroring the original one on the TLD level. If I send the email to my targets, they might go and check the website without specific URL, just to the URI. Eg. instead of going to http://example.com/YOUR_RID to http://example.com. The DNS is pointing to the phishing server. 

I have not found a way to do it. Can it be possibly accomplished within the current framework or it is further down in the development pipeline?

**What are you expecting to see happen? :**

I would like to receive the website that is mimicking the fake one if accessed directly using URI.
If a user clicks my link in the email, I would like to present them a special website that tells "You have been coaxed to click here, but in the future, you should do XYZ. "

**Comment by pastechecker** [comment]
I believe there is no other way than placing Apache / NGINX and do proxy/URL rewrite and run gophish on localhost. On the proxy, you rewrite only /?rid= requests which are sent in the email.

**Comment by pastechecker** [comment]
Apache basic configuration to separate /?rid=XXXXX from requests like / etc. 
<VirtualHost *:80>
ServerName example.com
ServerAdmin email@examiple.com
DocumentRoot /var/www/html
ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined
RewriteEngine On
RewriteCond %{QUERY_STRING} rid=(.+)
RewriteRule ^/$ http://127.0.0.1:81/?rid=%1 [P]
</VirtualHost>

**Comment by jordan-wright** [comment]
Hi @pastechecker,

You're correct that right now there's no way to customize the root static page. That's something I might add later, but it'll be a lower-priority item.

For now, the Apache workaround you listed seems like a great option. Thanks for putting that together and sharing it back to the community!
