### ISSUE TITLE
Configure DNS locally

### ISSUE THREAD

**Issue by alexisZambranodtt** [gophish/gophish#1164]
Hi everyone.

I'm running Gophish in MS Windows server 2016, I'm using G Suite as SMTP service with a domain registered in godaddy. I've already configured all the necessary in the DNS console. 
Do I have to configure any DNS stuff in my local server?
Roles? 
Inbound/Outbound rules? 
Ports?

Thanks.

**Comment by jordan-wright** [comment]
Hi @alexisZambranodtt,

You just need to make sure that your domain has an A record pointing to your Gophish instance. That way, if you use the domain in your emails, users will be able to reach Gophish.

Hope this helps!
