### ISSUE TITLE
Instructions for postfix setup? 

### ISSUE THREAD

**Issue by datgb** [gophish/gophish#1169]
What version of Gophish are you using?: 
4.0

Im trying to follow a couple tutorials on setting this up from postfix in a vps.

This worked for getting it installed and accessible. https://medium.com/@immure/setting-up-gophish-on-aws-c2f2fd78b7e9

However no test email could be sent.

This https://ninja.style/post/deploygophish/
has more info on postfix install but that didnt work either.

When I go to send a test email it it just keeps loading on the send button. 

What is the username and password? server login? 

Ive been googling and cant find much on this.

**Comment by jordan-wright** [comment]
Hi @datgb,

I'm afraid we don't have any official instructions at the moment. You can try to use the [Postfix configuration file](https://github.com/gophish/gophish/blob/master/ansible-playbook/roles/gophish/templates/main.cf.j2) from our Ansible playbook. You will need to adjust the template `{{ variables }}` with the correct information, but it should give you a good start.

[This blog post](https://www.trustedsec.com/2018/03/take-employees-phishing/) from TrustedSec also gives good info on how to set up things like SPF, DKIM, and DMARC.

Hope this helps!
