### ISSUE TITLE
Issue creating campaign

### ISSUE THREAD

**Issue by colemic** [gophish/gophish#117]
Hi, when I create a campaign, I can't add groups...  looks like an html issue or something maybe, not sure?  Groups are there, just can't add them.  Tried IE and chrome.
![gophish1](https://cloud.githubusercontent.com/assets/10284226/12753549/35ad7e38-c98d-11e5-8481-71add197260e.PNG)
![gophish2](https://cloud.githubusercontent.com/assets/10284226/12753553/37595928-c98d-11e5-85c6-b306d19b0077.PNG)

Thanks!

Mike C
mcole@ffin.com

**Comment by rfdevere** [comment]
Are you typing the first letter of the title of each field to bring up the autocomplete? Got me too on first use but I now like it this way.

**Comment by colemic** [comment]
The only field I have a problem with is the group name field. I have two groups set up for testing and under group name, when I create a campaign, it says showing 1 of 1 entries and nothing is displayed. Tried typing first letter but no go.

**Comment by jordan-wright** [comment]
Interesting - so all the other autocomplete fields work ok?

**Comment by colemic** [comment]
Correct

**Comment by jordan-wright** [comment]
@colemic What's your screen resolution? It sounds like it might be some kind of CSS bug.

**Comment by colemic** [comment]
1920x1080

**Comment by snori74** [comment]
Ha, ha, had the same problem in Chromium and Firefox (on Ubuntu) - then twigged that it's necessary to not only type the first few letters of the group name, select it and let it fill the Group fields - but ALSO to click the "+Add" button to the right - this adds it to the list of groups below.

Suggestion; maybe rename the fields like this: "Groups" > "Add groups", "Group Name" > "Sending to these groups"

**Comment by colemic** [comment]
That helps!  Was able to create a campaign.  Does appear to be some kind of bug though.

**Comment by jordan-wright** [comment]
I'm planning on fixing this in the next release (where you don't have to also click the +Add button). I'll keep this issue open as a reference.

**Comment by jordan-wright** [comment]
I'm going to go ahead and move this to 0.2, where I'm planning a small re-design of the campaign creation modal.

**Comment by jordan-wright** [comment]
I believe the changes from @rcutmore in #296 should help address this issue, so I'll close this out for now.
