### ISSUE TITLE
Issue Bulk Uploading From CSV

### ISSUE THREAD

**Issue by zieba88** [gophish/gophish#1171]
What version of Gophish are you using?: 
gophish-v0.6.0-linux-64bit

Brief description of the issue: 
When bulk uploading users from csv using format in documentation provided here:
https://gophish.gitbook.io/user-guide/building-your-first-campaign/importing-groups#importing-from-csv
All fields except First Name upload.

What are you expecting to see happen? :
All fields to upload including First Name.

What are you seeing happen?
All fields are uploaded except First Name

See Attached for more insight
![bulcsv](https://user-images.githubusercontent.com/13650910/44098822-c8d18956-9fa6-11e8-97d2-5673576e4257.JPG)
![bulk](https://user-images.githubusercontent.com/13650910/44098824-c8dff0b8-9fa6-11e8-8bb3-a005906d04b7.JPG)

**Comment by jordan-wright** [comment]
Hi @zieba88,

Thanks for reaching out. I'm not quite sure what the issue would be in this case. The CSV you're using _seems_ fine. In the current source, we have a link that allows you to download the following template:

```
First Name,Last Name,Email,Position
Example,User,foobar@example.com,Systems Administrator
```

We also have some changes to make the CSV parsing a bit more flexible, so maybe those would help as well? For now, you might try building from source to see if that fixes the issue until we're able to create a new release (no ETA on when this will happen atm).

Sorry for the hassle! Hopefully there's just something odd going on and using this template or building from source will help resolve the issue.

Let me know if you continue to run into problems!

**Comment by zieba88** [comment]
Hi Jordan,

Thanks for following up. I did some additional testing and it seems to be related to how its parsing the csv. I was able to work around the issue using the following format. Hope it helps someone if they experience the same issue until its fixed. Note I don't care for the Position field as I do not use it in my campaign.

See attached:
![error](https://user-images.githubusercontent.com/13650910/44161578-632f3c00-a083-11e8-8944-383f4121875c.JPG)
![workaround](https://user-images.githubusercontent.com/13650910/44161581-64f8ff80-a083-11e8-8d1c-dc9250951438.JPG)

**Comment by zieba88** [comment]
The workaround I found was to use the format below. I didn't care for the Position field so this workaround omits it. Please copy the syntax below exactly, save it to a csv and give it a try. If it doesn't work, please upload your similar sample set and I can try to help you find a work around until they fix the bug.

Position,First Name,Last Name,Email
,John,Doe,jdoe@example.com

**Comment by TinderMahal** [comment]
I have tried that to no avail. I still have the same issue.

Here's a sample (obvious things changed) of my CSV below:

Position,First Name,Last Name,Email Address
,Robin,Stewart,rhstewart@armstrong.co
,Jason,McCleFresh,jkmcclefresh@armstrong.co
,Service,Account,servcount@armstrong.co
,AA,Administrator,aadministrator@armstrong.co

Thank you!

**Comment by zieba88** [comment]
Please make your first line 
"Position,First Name,Last Name,Email" without quotes

you have "Position,First Name,Last Name,Email Address" 

Let me know if that works. I tried it both ways and after making the change it uploaded just fine.

**Comment by TinderMahal** [comment]
I'm not sure how I overlooked that...

Okay, so changing that in both my sample and the full CSV has zero results for me. It still will only upload and display the last entry's First Name and Last Name. No addresses, unfortunately.

**Comment by zieba88** [comment]
what version are you running? I am on gophish-v0.6.0-windows-64bit, but also tested the same release in Linux. 
Here is a screenshot of the file and bulk upload output using your sample

![test](https://user-images.githubusercontent.com/13650910/44857970-8981d980-ac36-11e8-9bce-31b7c5bddf64.JPG)

**Comment by TinderMahal** [comment]
I'm attempting to use both Ubuntu x64 and Kali x64. I have the same issue on both...

**Comment by TinderMahal** [comment]
![Image of issue](https://i.imgur.com/wK52OQi.jpg)

**Comment by zieba88** [comment]
I am able to recreate the issue you are having when the format is Position,First Name,Last Name,Email Address

When I remove Address from Position,First Name,Last Name,Email it loads normally, are you sure you saved the csv after you made the change? Also noticed you have an extra . on the end of ,Jason,McCleFresh,jkmcclefresh@armstrong.co.

**Comment by TinderMahal** [comment]
I actually just exported the CSV file from Exchange. It adds "Email Address" automatically - perhaps I could just open it and save it "As Is" so that it initially doesn't save with "Address" on it? There are around 400 email addresses that I need to import with this CSV file.

**Comment by TinderMahal** [comment]
It looks like that worked! Opening the document and changing what needed changing it before actually saving it to my local computer.

**Comment by zieba88** [comment]
TinderMahal, 
Glad to hear the workaround helped worked for you. I had a similar issue with about 250 users and somehow stumbled upon this workaround.

**Comment by jordan-wright** [comment]
Hey everyone,

Is anyone using the latest version of Gophish from source? I made some modifications a while back to make this much more reliable, but if they aren't working for y'all, then I would love to see the data that you are trying to import so that I can track down the issue.

In the meantime, I apologize for the issues getting things imported! I have a few more features to knock out, and then I'll upload a new release with the import fixes 😄

**Comment by jordan-wright** [comment]
Hey everyone,

Now that [version 0.7.0](https://github.com/gophish/gophish/releases/tag/v0.7.0) has been released which includes better CSV importing, I'm going to go ahead and close this issue.

If, when using the release, you still encounter this same issue, please let me know and I'll be more than happy to reopen this issue and we can continue troubleshooting 😄 

Thanks again for getting in touch!
