### ISSUE TITLE
Credential Capture and Redirect not working

### ISSUE THREAD

**Issue by aarmstrong089** [gophish/gophish#1172]
What version of Gophish are you using?: 

Brief description of the issue: V0.6.0

What are you expecting to see happen? : Credentials captured and user redirected

What are you seeing happen? Nothing at all...

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
<!DOCTYPE html><html><head>
    <meta charset="UTF-8"/>
    <title>Sign Into Your Microsoft Account</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style>
	body{
	background-image: url(https://auth.gfx.ms/16.000.27868.00/images/Backgrounds/0.jpg?x=a5dbd4393ff6a725c7e62b61df7e72f0);
	}
	
</style>

  </head>
  <body>
  
	<div class="container">
		<div class="row">
			<div class="col-md-4"></div>
			<div class="col-md-4" style="background-color: white; margin-top: 200px;">
				<div class="row">
					<div class="col-xs-1"></div>
					<div class="col-xs-5">
						<img class="responsive" style="height: 120px" src="https://logos-download.com/wp-content/uploads/2016/02/Microsoft_logo_small.png"/>
					</div>
					<div class="col-xs-6"></div>
				</div>
				<div class="row">
					<div class="col-xs-1"></div>
					<div class="col-xs-5">
						<h3 style="margin-top:0px;"> Sign In </h3>
					</div>
					<div class="col-xs-6"></div>
				</div>
				<div class="row">
					<div class="col-xs-1"></div>
					<div class="col-xs-10">
					<form action="" name="form">
						<input type="text" name="login" style="border: none; width:100%; border-bottom: 1px solid gray; height:40px;" placeholder="Email, Phone, or Skype"/>
					</form></div>
					<div class="col-xs-1"></div>
				</div>
				<div class="row">
					<div class="col-xs-1"></div>
					<div class="col-xs-10">
						<input type="password" name="password" style="width:100%; border: none; border-bottom: 1px solid gray; height:40px;" placeholder="Password"/>
					</div>
					<div class="col-xs-1"></div>
				</div><br/>	
				<div class="row">
					<div class="col-xs-1"></div>
					<div class="col-xs-7">
						No Account? <a href="#">Create One! </a>
					</div>
					<div class="col-xs-4"></div>
				</div>	
				<div class="row">
					<div class="col-xs-1"></div>
					<div class="col-xs-7"></div>
					<div class="col-xs-3">
						<input name="submit" class="btn btn-primary" style="margin-bottom: 20px;" type="submit" value="Sign In"/>
					</div>
					<div class="col-xs-1"></div>
				</div>	
				
				
			</div>
			<div class="col-md-4"></div>
		</div>
	</div>
  
</body></html>
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 - 
 
I have searched previous instances - they all state that JS is the issue so i made the landing page from scratch. Or that the input fields need named, which i have also done. 

Cant think of anything else and ive tried searching documentation and others answers

**Comment by Rzqu** [comment]
Im having the same problem with sites that ive cloned and the forms not submitting and re-directing to the inputted url. 

I even tried the page in this issue and fixed the form part as you advised and still not working

Nothing happens after hitting enter or clicking login.

**Comment by jordan-wright** [comment]
Hi @Rzqu, since it's likely you're having a separate issue, please open a new issue here on Github, providing the information requested in our issue template. Then we can help troubleshoot.

For now, since there haven't been any updates in over a week, I'm going to go ahead and close this one out. @aarmstrong089 if you're still encountering issues, let me know if the above comment helps and we can continue troubleshooting as needed.
