### ISSUE TITLE
LDAP integration with gophish

### ISSUE THREAD

**Issue by 2295ad** [gophish/gophish#1173]
Has anyone worked on integrating LDAP with gophish? Is this feature available?
Gophish version - 0.6.0

TIA !!

**Comment by jordan-wright** [comment]
Hi @2295ad, thanks for reaching out. We don't have any plans to support LDAP integration within Gophish natively at the moment.

However, @ILiedAboutCake has created a Powershell script that makes it easy to create groups from AD that you may find useful [here](https://github.com/ILiedAboutCake/DirectoryPhish).

Hope this helps!

**Comment by adonix-dev** [comment]
I just made a script to synchronise LDAP Groups with Gophish.

Here it's how:
- in "main.bat" set your API_URL and your API_TOKEN
- then "call main.bat" with 2 parameters : first the groupeID (see gophish doc) and the LDAP group name.

[LDAP_groups_to_gophish.zip](https://github.com/gophish/gophish/files/5446085/LDAP_groups_to_gophish.zip)
