### ISSUE TITLE
Fetch data from mysql db & to display it in dashboard.

### ISSUE THREAD

**Issue by 2295ad** [gophish/gophish#1174]
Guys I needed to display some data from mysql table to dashboard. 
 I have been trying this out for some time now, but didn't succeed..anyone over here has worked on it?
If yes, can you pls guide me which go file i need to make changes so that i would be able to fetch data from a table in mysql and display that value in dashboard.

TIA!!

**Comment by jordan-wright** [comment]
Hi @2295ad, thanks for reaching out!

I'm afraid this is trickier than it seems. You would need to add a route in `controllers/api.go`. Then, you'll need to adjust the `static/js/src/app/dashboard.js`, as well as `templates/dashboard.html`.

After you make the JS changes, you'll need to rebuild the frontend minified files using `gulp`. You'll also need to recompile the Gophish binary after making the Golang changes.

I hope this helps! Unfortunately, it's not as simple as modifying a single file, and heavily depends on what you're trying to do.

**Comment by 2295ad** [comment]
Thanks for the quick response @jordan-wright ..will try this out!!
