### ISSUE TITLE
Introduce a {{.rid}} placeholder

### ISSUE THREAD

**Issue by atropineal** [gophish/gophish#1178]
It would be great to introduce a placeholder that substituted-in the ID of the recipient, e.g. where the URL is <whatever>?rid=feh76324, {{.rid}} would be replaced with feh76324.  This would allow users the freedom to serve recipient-specific content, and also to correlate actions with recipients in useful ways.

**Comment by jordan-wright** [comment]
Hi @atropineal,

Could you expand on this a bit? Right now, we have [these template variables](https://gophish.gitbook.io/user-guide/template-reference) which include a `{{.URL}}` variable which is the URL with the `rid` parameter already included.

And, other than that, I have good news! There [should be](https://github.com/gophish/gophish/blob/9f334281ab7b768ab201a14040ffda658b34044b/models/template_context.go#L25) an `{{.RId}}` parameter at least in the latest version, so if that doesn't work for you now (worth a shot with a test campaign to yourself!), then it should work in the future 😄 

Let me know if this helps!

**Comment by atropineal** [comment]
Hey :-)  Thanks for the good news!  The use case was for including links to
other resources that could then be traced back to a user via the rid.  For
example if I want my recipients to complete a survey (hosted at
surveymonkey or similar), then unless I can pass the rid as a parameter to
the survey site then I lose traceability.  I can see opens, clicks and
survey completions, but there would be no correlator between a click and a
specific survey's results.  Hope that explains things.  I'll check out the
latest gophish. :-)

**Comment by jordan-wright** [comment]
@atropineal just checking in to let you know I've confirmed the `{{.RId}}` parameter seems to work in the latest version of Gophish. With this being the case, I'm going to go ahead and close this issue out.

Thanks again for getting in touch!

**Comment by pat-inthe-hat** [comment]
Can you confirm this was was implemented in v0.7.1? When adding {{.RID}} to an email template, I receive the following error: 
`template: template:3:69: executing "template" at <.RID>: can't evaluate field RID in type models.PhishingTemplateContext`
