### ISSUE TITLE
Arch linux - cannot assign requested address - fatal error

### ISSUE THREAD

**Issue by Biedubbeljoe** [gophish/gophish#1179]
]$ ./gophish
time="2018-08-29T10:09:04+02:00" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
time="2018-08-29T10:09:04+02:00" level=warning msg="No contact address has been configured."
time="2018-08-29T10:09:04+02:00" level=warning msg="Please consider adding a contact_address entry in your config.json"
goose: no migrations to run. current version: 20180527213648
time="2018-08-29T10:09:04+02:00" level=info msg="Starting phishing server at http://xxx.xxx.xxx.41:80"
time="2018-08-29T10:09:04+02:00" level=fatal msg="listen tcp xxx.xxx.xxx.41:80: bind: cannot assign requested address"

Gophish is installed on my Arch linux. Go build and Gophish build on this PC went well. I adjusted the json config file to my external IP address and port 80. Admin default settings. crt and key created and in the root of gophish. If I start gophish I get the above error.

Any ideas?

**Comment by jordan-wright** [comment]
Hey there! Thanks for reaching out.

Since port 80 is privileged, you may need to run Gophish as root, or do something like [this](https://superuser.com/questions/710253/allow-non-root-process-to-bind-to-port-80-and-443) to allow non-privileged users to bind to those ports.

**Comment by Biedubbeljoe** [comment]
Thanks for the quick reply. This did the trick.
