### ISSUE TITLE
Credential Capture & Redirect Not working

### ISSUE THREAD

**Issue by Rzqu** [gophish/gophish#1180]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.6.0

Brief description of the issue: 
When clicking the submit button on the landing page the page does not redirect to the set redirection URL

What are you expecting to see happen? :
Expecting credentials in GoPhish and then page redirect

What are you seeing happen?
Nothing

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
<!DOCTYPE html><html><head>
    <meta charset="UTF-8"/>
    <title>Sign Into Your Microsoft Account</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style>
	body{
	background-image: url(https://auth.gfx.ms/16.000.27868.00/images/Backgrounds/0.jpg?x=a5dbd4393ff6a725c7e62b61df7e72f0);
	}
	
</style>

  </head>
  <body>
  
	<div class="container">
		<div class="row">
			<div class="col-md-4"></div>
			<div class="col-md-4" style="background-color: white; margin-top: 200px;">
				<div class="row">
					<div class="col-xs-1"></div>
					<div class="col-xs-5">
						<img class="responsive" style="height: 120px" src="https://logos-download.com/wp-content/uploads/2016/02/Microsoft_logo_small.png"/>
					</div>
					<div class="col-xs-6"></div>
				</div>
				<div class="row">
					<div class="col-xs-1"></div>
					<div class="col-xs-5">
						<h3 style="margin-top:0px;"> Reset Your Password </h3>
					</div>
					<div class="col-xs-6"></div>
				</div>
				<div class="row">
					<div class="col-xs-1"></div>
					<div class="col-xs-10">
					<form action="" name="form" method="POST">
						<input type="text" name="username" style="border: none; width:100%; border-bottom: 1px solid gray; height:40px;" placeholder="Email"/>
					</div>
					<div class="col-xs-1"></div>
				</div>
				<div class="row">
					<div class="col-xs-1"></div>
					<div class="col-xs-10">
						<input type="password" name="password" style="width:100%; border: none; border-bottom: 1px solid gray; height:40px;" placeholder="Password"/>
					</div>
					<div class="col-xs-1"></div>
				</div><br/>	
				<div class="row">
					<div class="col-xs-1"></div>
					<div class="col-xs-10">
						<input type="password" name="Npassword" style="width:100%; border: none; border-bottom: 1px solid gray; height:40px;" placeholder="Enter New Password"/>
					</div>
					<div class="col-xs-1"></div>
				</div><br/>	
				<div class="row">
					<div class="col-xs-1"></div>
					<div class="col-xs-7">
						No Account? <a href="#">Create One! </a>
					</div>
					<div class="col-xs-4"></div>
				</div>	
				<div class="row">
					<div class="col-xs-1"></div>
					<div class="col-xs-7"></div>
					<div class="col-xs-3">
						<input type="submit" class="btn btn-primary" style="margin-bottom: 20px;" value="Reset"/>
					</div>
					<div class="col-xs-1"></div>
				</form></div>	
				
				
			</div>
			<div class="col-md-4"></div>
		</div>
	</div>
  
</body></html>
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by Rzqu** [comment]
I have tested this HTML page on a website that renders HTML code and the button function works fine. https://htmledit.squarefree.com/

I amended the code to submit to google.co.uk just to test and as expected i click the submit button and get an error back from googles servers.

It seems when using this HTML page on GoPhish it doesnt allow you to click the submit button.

If i enter a username in the field then press the enter key(not clicking the submit button), the redirection works but then it only captures the username in the GoPhish admin page but no passwords.

**Comment by Rzqu** [comment]
@jordan-wright Any ideas?

**Comment by jordan-wright** [comment]
Hey @Rzqu,

Sorry for the delay. It looks like the `<form>` tag is misaligned. You'll need to move it outside the div that it's in to be properly nested.

Also, I'm going to repeat the same word of caution that I did in #1172:

> Also, as a quick side note, I see that you're using Microsoft's brand within your phishing page. I recommend against using their brand since it could hurt the user's trust in them Instead, you make simple modifications such as "Sign into your account", and removing the logo. You will almost certainly see the same results in terms of click through rates, and you will avoid potentially infringing on their brand. You can find other tips on #1057.

Hope this helps!
