### ISSUE TITLE
Adding {{.server}} variable for landing pages

### ISSUE THREAD

**Issue by Cycl0pe** [gophish/gophish#1182]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.6.0

Brief description of the issue: While using static files for a landing page, I was wondering if there is a way to complete the attribute of an img in a template without fulfilling the complete address of the src (https://phishing_server/static/file) but using the variable {{.server}} corresponding to the the variable URL when creating a new campaign ({{.server}}/static/file).

This variable will allow us to reuse the landing pages even if we change the domain name used.

Cycl0pe

**Comment by jordan-wright** [comment]
Hey @Cycl0pe,

Thanks for reaching out! This seems reasonable. I had originally thought about making a template tag for static files, but making one for the root url (minus the `rid`) seems more generic and useful. And I think `{{.Server}}` or perhaps `{{.RootURL}}` would be good choices for this.

Give me a bit and I'll see about making this happen. 😄

**Comment by Cycl0pe** [comment]
Hey @jordan-wright,

Thanks for your quick response! Could you give me a hint where these variables are defined?

I will try to come up with something to implement it.

**Comment by jordan-wright** [comment]
Hey @Cycl0pe!

I appreciate your willingness to help. I had some time today so I went ahead and got a `{{.BaseURL}}` tag merged in. You can see how I did it in https://github.com/gophish/gophish/commit/15e57b6cd081139e34af236e0eda56f209d287f7.

Normally, I would have been more than happy to help you get this implemented, but my goal is to drop a new release tomorrow morning 🎊 and I wanted this to be in it 😄. I hope this is ok!

If when looking through the code you have any questions, please let me know!
