### ISSUE TITLE
VERSION file was not updated for release 0.7.0 still 0.6.0

### ISSUE THREAD

**Issue by ismailyenigul** [gophish/gophish#1185]
Thanks for new version
It seems that you forgot to update VERSON file. it still show 0.6.0
 
unzip gophish-v0.7.0-linux-64bit.zip 

 cat VERSION 
0.6.0

**Comment by ismailyenigul** [comment]
Also, it would be good to mention about copying confing.json file from old directory to new one to the  upgrade procedure.

**Comment by jordan-wright** [comment]
Whoops, sorry about that! I've bumped the `VERSION` file and updated the release. I've kept the old hashes in place in case anyone downloaded the release before the updates were rolled out.

Good catch!
