### ISSUE TITLE
Additional feature to compliment the new time delay feature

### ISSUE THREAD

**Issue by Gradle999** [gophish/gophish#1186]
Is it possible to look into a feature to randomise the email template sent to the recipient? 

It's great that we can now space out the emails in a campaign over a period of time so that they all don't get sent at the same time, but I think it would be great to also be able to randomise the email that is sent as well throughout that time period. 

Perhaps by specifying the email templates, sending profiles and user groups you wish to use and the period of time to send them over, then they are evenly distributed across each user.

**Comment by jordan-wright** [comment]
Hi @Gradle999,

Thanks for reaching out! This is an interesting idea, but would be a significant architecture overhaul to make this happen. I have some plans for redesigning the way campaigns are created in #223 that I haven't had a chance to fully implement yet, but I think that's more of the direction I'm planning to take things.

I do appreciate the feature suggestion though! Please keep them coming! While I can't guarantee to implement everything, I love hearing new ideas. 😄
