### ISSUE TITLE
Redirect from landing page The specified URL cannot be found. 

### ISSUE THREAD

**Issue by mcvaa** [gophish/gophish#1187]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.7.0

**Brief description of the issue:**  Internal intranet I am able to access the redirect web page after clicking sign in and all is recording properly. When we set our external access the server does not redirect the web page after clicking on sign in on the page and after a few minutes a web page comes back stating the specified URL Cannot be found. See screenshot

**What are you expecting to see happen?** : our training web page which we are able to access and record information when we are accessing the site internally.

What are you seeing happen? Check Screen shot

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

``
![image](https://user-images.githubusercontent.com/14318521/45168644-ccf5be00-b1c9-11e8-97d1-640b27d472f7.png)

```


Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 -External access:  we are able to redirect to the https://aquarest.esi.net web site but after entering the credentials on the web page the site returns the following. "The specified URL cannot be found."
 
* Step 2 - It does not redirect what is being sent from the gophish server. The interesting part is that it is redirecting properly internally, but it does not record properly see next submitted information: 

The really interesting part is that if you directly type in the URL in the address bar it is accessible externally. So there is a connection between accessing the site externally to when you click the submit button and does not record.

**Comment by mcvaa** [comment]
Testing the campaign with 2 users, the email is sent to both users but the Email Opened Clicked Link and Submitted data reports under one user it does not accurately report under the user that is clicking the link. 

Please assist or let me know if this needs to be another ticket. 

![image](https://user-images.githubusercontent.com/14318521/45175254-fec35080-b1da-11e8-9624-575d3e4f6181.png)

Mike was the one that submitted the information but it recorded under Colleen 

![image](https://user-images.githubusercontent.com/14318521/45175308-23b7c380-b1db-11e8-9c48-2ff89f8ee94f.png)

**Comment by mcvaa** [comment]
Her is the landing page source:

<!DOCTYPE html><html lang="en-US"><head>
	<base href="https://fs.global-imaging.com/adfs/ls/?client-request-id=d4b17c3e-6cf8-44ba-8dcd-92d9d18807e6&amp;wa=wsignin1.0&amp;wtrealm=urn%3afederation%3aMicrosoftOnline&amp;wctx=LoginOptions%3D3%26estsredirect%3d2%26estsrequest%3drQIIAYWSPW_TUBiF46RJP4SgQh06FqkSEpKTa-fGTSIV4cSuY1Lnq04Te6BynOvEiePr2jc4ifgBZUCqGDsydoMJ9SdUQhTEQkcGQEyIqSOJWLpxhqN3OMPRed5HMSbJ5LfBP3H0wmlgWQxtosV1S_79tfXHL95-uXEuhFcfXn_9dLL8_Zx60CfEC_KplId9YjhJbFm2iZImHqUcw-3abu89RV1R1E-KOovGkUs3D86jAZfmdpgsZNNsNssCDoJMUh_wTFWSw2qrSSqCyCpFAJSWzO63xFAZ8ERXNagLfKgPCqOKUAcVqQkVdq9fFYZEUzWgHwBQUcXJfksGlZlCFEmGykxm9ZEW6iMRXkfvVfkx6bMLw749Q3-iqxb2R0ceDshZ7DNV9ZArd4vYdZFJkosYcoltGsTGbs3HHvKJjYJdxZXdMS3xhc407Ait6VG6qJvZOluATIOfgGqZF-lhQw3LezTkaYkIpNjvlJ39JkB9_XjHM2VLrIUea3EDTq9Nh0OnMRX3Dme1oMtPyhgaAqlrAxHTgOsIvoxLRhvpzQacBGHDzzkZn30q6oOeNByU-hgKh-l27qAtoUm23s5MqjWN7fN02nCPj1XzXSwxBzHC7mXs7ry_a3e3PB9btoO-xTZM7DgIucnnhvGkZweTBbOrJerX0h0Qy6-srK1HNiNbkZsl6k18Tj6-_fDHbuej9BI_i2568chlPJXJFVVk9NTi2NGkoVfQghHJlRyoQo_T5Y5zmJ6WajgNx764u5NnThPUaSLxO0GdLEcuVv__N9drGyxgsjTIzZfYYmA-w-YZRv8L0&amp;cbcxt=&amp;username="/><meta http-equiv="X-UA-Compatible" content="IE=10.000"/><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/><meta http-equiv="content-type" content="text/html;charset=UTF-8"/><meta http-equiv="cache-control" content="no-cache,no-store"/><meta http-equiv="pragma" content="no-cache"/><meta http-equiv="expires" content="-1"/><meta name="mswebdialog-title" content="Connecting to Global Imaging Inc."/>
	<title>Sign In</title>
	<script type="text/javascript">
//<![CDATA[
function LoginErrors(){this.userNameFormatError = 'Enter your user ID in the format \u0026quot;domain\\user\u0026quot; or \u0026quot;user@domain\u0026quot;.'; this.passwordEmpty = 'Enter your password.'; this.passwordTooLong = 'Password must be shorter than 128 characters.';}; var maxPasswordLength = 128;
//]]>
</script><script type="text/javascript">
//<![CDATA[
// Copyright (c) Microsoft Corporation.  All rights reserved.
function InputUtil(errTextElementID, errDisplayElementID) {

    if (!errTextElementID)  errTextElementID = 'errorText'; 
    if (!errDisplayElementID)  errDisplayElementID = 'error'; 

    this.hasFocus = false;
    this.errLabel = document.getElementById(errTextElementID);
    this.errDisplay = document.getElementById(errDisplayElementID);
};
InputUtil.prototype.canDisplayError = function () {
    return this.errLabel && this.errDisplay;
}
InputUtil.prototype.checkError = function () {
    if (!this.canDisplayError){
        throw new Error ('Error element not present');
    }
    if (this.errLabel && this.errLabel.innerHTML) {
        this.errDisplay.style.display = '';        
        var cause = this.errLabel.getAttribute('for');
        if (cause) {
            var causeNode = document.getElementById(cause);
            if (causeNode && causeNode.value) {
                causeNode.focus();
                this.hasFocus = true;
            }
        }
    }
    else {
        this.errDisplay.style.display = 'none';
    }
};
InputUtil.prototype.setInitialFocus = function (input) {
    if (this.hasFocus) return;
    var node = document.getElementById(input);
    if (node) {
        if ((/^\s*$/).test(node.value)) {
            node.focus();
            this.hasFocus = true;
        }
    }
};
InputUtil.prototype.setError = function (input, errorMsg) {
    if (!this.canDisplayError) {
        throw new Error('Error element not present');
    }
    input.focus();

    if (errorMsg) {
        this.errLabel.innerHTML = errorMsg;
    }
    this.errLabel.setAttribute('for', input.id);
    this.errDisplay.style.display = '';
};
InputUtil.makePlaceholder = function (input) {
    var ua = navigator.userAgent;

    if (ua != null && 
        (ua.match(/MSIE 9.0/) != null || 
         ua.match(/MSIE 8.0/) != null ||
         ua.match(/MSIE 7.0/) != null)) {
        var node = document.getElementById(input);
        if (node) {
            var placeholder = node.getAttribute("placeholder");
            if (placeholder != null && placeholder != '') {
                var label = document.createElement('input');
                label.type = "text";
                label.value = placeholder;
                label.readOnly = true;
                label.style.position = 'absolute';
                label.style.borderColor = 'transparent';
                label.className = node.className + ' hint';
                label.tabIndex = -1;
                label.onfocus = function () { this.nextSibling.focus(); };

                node.style.position = 'relative';
                node.parentNode.style.position = 'relative';
                node.parentNode.insertBefore(label, node);
                node.onkeyup = function () { InputUtil.showHint(this); };
                node.onblur = function () { InputUtil.showHint(this); };
                node.style.background = 'transparent';

                node.setAttribute("placeholder", "");
                InputUtil.showHint(node);
            }
        }
    }
};
InputUtil.focus = function (inputField) {
    var node = document.getElementById(inputField);
    if (node) node.focus();
};
InputUtil.hasClass = function(node, clsName) {
    return node.className.match(new RegExp('(\\s|^)' + clsName + '(\\s|$)'));
};
InputUtil.addClass = function(node, clsName) {
    if (!this.hasClass(node, clsName)) node.className += " " + clsName;
};
InputUtil.removeClass = function(node, clsName) {
    if (this.hasClass(node, clsName)) {
        var reg = new RegExp('(\\s|^)' + clsName + '(\\s|$)');
        node.className = node.className.replace(reg, ' ');
    }
};
InputUtil.showHint = function (node, gotFocus) {
    if (node.value && node.value != '') {
        node.previousSibling.style.display = 'none';
    }
    else {
        node.previousSibling.style.display = '';
    }
};
//]]>
</script>
	<link href="/adfs/portal/css/style.css?id=D74D4D6943F32AE6F7F11D14D601DBB0E1A58919176EE512150366B6279AAF99" rel="stylesheet" type="text/css"/>
	<style type="text/css">.illustrationClass {background-image:url(/adfs/portal/illustration/illustration.png?id=183128A3C941EDE3D9199FA37D6AA90E0A7DFE101B37D10B4FEDA0CF35E11AFD);}
	</style>
</head>
<body class="body" dir="ltr">
<div id="noScript" style="width: 100%; height: 100%; position: static; z-index: 100;">
<h1>JavaScript required</h1>

<p>JavaScript is required. This web browser does not support JavaScript or JavaScript in this web browser is not enabled.</p>

<p>To find out if your web browser supports JavaScript or to enable JavaScript, see web browser help.</p>
</div>
<script type="text/javascript" language="JavaScript">
         document.getElementById("noScript").style.display = "none";
    </script>

<div id="fullPage">
<div class="float" id="brandingWrapper">
<div id="branding"> </div>
</div>

<div class="float" id="contentWrapper">
<div id="content">
<div id="header">Global Imaging Inc.
                 Authenticate to Access</div>

<div id="workArea">
<div class="groupMargin" id="authArea">
<div id="loginArea">
<div class="groupMargin" id="loginMessage">Sign in with your organizational account</div>

<form action="" autocomplete="off" id="loginForm" method="post" novalidate="novalidate" onkeypress="if (event &amp;&amp; event.keyCode == 13) Login.submitLoginRequest();"><input name="__original_url" type="hidden" value="https://fs.global-imaging.com/adfs/ls/?client-request-id=d4b17c3e-6cf8-44ba-8dcd-92d9d18807e6&amp;wa=wsignin1.0&amp;wtrealm=urn%3afederation%3aMicrosoftOnline&amp;wctx=LoginOptions%3D3%26estsredirect%3d2%26estsrequest%3drQIIAYWSPW_TUBiF46RJP4SgQh06FqkSEpKTa-fGTSIV4cSuY1Lnq04Te6BynOvEiePr2jc4ifgBZUCqGDsydoMJ9SdUQhTEQkcGQEyIqSOJWLpxhqN3OMPRed5HMSbJ5LfBP3H0wmlgWQxtosV1S_79tfXHL95-uXEuhFcfXn_9dLL8_Zx60CfEC_KplId9YjhJbFm2iZImHqUcw-3abu89RV1R1E-KOovGkUs3D86jAZfmdpgsZNNsNssCDoJMUh_wTFWSw2qrSSqCyCpFAJSWzO63xFAZ8ERXNagLfKgPCqOKUAcVqQkVdq9fFYZEUzWgHwBQUcXJfksGlZlCFEmGykxm9ZEW6iMRXkfvVfkx6bMLw749Q3-iqxb2R0ceDshZ7DNV9ZArd4vYdZFJkosYcoltGsTGbs3HHvKJjYJdxZXdMS3xhc407Ait6VG6qJvZOluATIOfgGqZF-lhQw3LezTkaYkIpNjvlJ39JkB9_XjHM2VLrIUea3EDTq9Nh0OnMRX3Dme1oMtPyhgaAqlrAxHTgOsIvoxLRhvpzQacBGHDzzkZn30q6oOeNByU-hgKh-l27qAtoUm23s5MqjWN7fN02nCPj1XzXSwxBzHC7mXs7ry_a3e3PB9btoO-xTZM7DgIucnnhvGkZweTBbOrJerX0h0Qy6-srK1HNiNbkZsl6k18Tj6-_fDHbuej9BI_i2568chlPJXJFVVk9NTi2NGkoVfQghHJlRyoQo_T5Y5zmJ6WajgNx764u5NnThPUaSLxO0GdLEcuVv__N9drGyxgsjTIzZfYYmA-w-YZRv8L0&amp;cbcxt=&amp;username=/adfs/ls/?client-request-id=d4b17c3e-6cf8-44ba-8dcd-92d9d18807e6&amp;wa=wsignin1.0&amp;wtrealm=urn%3afederation%3aMicrosoftOnline&amp;wctx=LoginOptions%3D3%26estsredirect%3d2%26estsrequest%3drQIIAYWSPW_TUBiF46RJP4SgQh06FqkSEpKTa-fGTSIV4cSuY1Lnq04Te6BynOvEiePr2jc4ifgBZUCqGDsydoMJ9SdUQhTEQkcGQEyIqSOJWLpxhqN3OMPRed5HMSbJ5LfBP3H0wmlgWQxtosV1S_79tfXHL95-uXEuhFcfXn_9dLL8_Zx60CfEC_KplId9YjhJbFm2iZImHqUcw-3abu89RV1R1E-KOovGkUs3D86jAZfmdpgsZNNsNssCDoJMUh_wTFWSw2qrSSqCyCpFAJSWzO63xFAZ8ERXNagLfKgPCqOKUAcVqQkVdq9fFYZEUzWgHwBQUcXJfksGlZlCFEmGykxm9ZEW6iMRXkfvVfkx6bMLw749Q3-iqxb2R0ceDshZ7DNV9ZArd4vYdZFJkosYcoltGsTGbs3HHvKJjYJdxZXdMS3xhc407Ait6VG6qJvZOluATIOfgGqZF-lhQw3LezTkaYkIpNjvlJ39JkB9_XjHM2VLrIUea3EDTq9Nh0OnMRX3Dme1oMtPyhgaAqlrAxHTgOsIvoxLRhvpzQacBGHDzzkZn30q6oOeNByU-hgKh-l27qAtoUm23s5MqjWN7fN02nCPj1XzXSwxBzHC7mXs7ry_a3e3PB9btoO-xTZM7DgIucnnhvGkZweTBbOrJerX0h0Qy6-srK1HNiNbkZsl6k18Tj6-_fDHbuej9BI_i2568chlPJXJFVVk9NTi2NGkoVfQghHJlRyoQo_T5Y5zmJ6WajgNx764u5NnThPUaSLxO0GdLEcuVv__N9drGyxgsjTIzZfYYmA-w-YZRv8L0&amp;cbcxt=&amp;username="/>
<div class="fieldMargin error smallText" id="error"> </div>

<div id="formsAuthenticationArea">
<div id="userNameArea"><input autocomplete="off" class="text fullWidth" id="userNameInput" name="UserName" placeholder="someone@example.com" spellcheck="false" tabindex="1" type="email" value=""/></div>

<div id="passwordArea"><input autocomplete="off" class="text fullWidth" id="passwordInput" type="password" placeholder="Password" tabindex="2"/></div>

<div id="kmsiArea" style="display: none;"><input id="kmsiInput" name="Kmsi" tabindex="3" type="checkbox" value="true"/> <label for="kmsiInput">Keep me signed in</label></div>

<div class="submitMargin" id="submissionArea"><span class="submit" id="submitButton" onclick="return Login.submitLoginRequest();" onkeypress="if (event &amp;&amp; event.keyCode == 32) Login.submitLoginRequest();" tabindex="4">Sign in</span></div>
</div>
<input id="optionForms" name="AuthMethod" type="hidden" value="FormsAuthentication"/> </form>

<div id="authOptions">
<form action="" id="options" method="post"><input name="__original_url" type="hidden" value="https://fs.global-imaging.com:443/adfs/ls/?client-request-id=d4b17c3e-6cf8-44ba-8dcd-92d9d18807e6&amp;wa=wsignin1.0&amp;wtrealm=urn%3afederation%3aMicrosoftOnline&amp;wctx=LoginOptions%3D3%26estsredirect%3d2%26estsrequest%3drQIIAYWSPW_TUBiF46RJP4SgQh06FqkSEpKTa-fGTSIV4cSuY1Lnq04Te6BynOvEiePr2jc4ifgBZUCqGDsydoMJ9SdUQhTEQkcGQEyIqSOJWLpxhqN3OMPRed5HMSbJ5LfBP3H0wmlgWQxtosV1S_79tfXHL95-uXEuhFcfXn_9dLL8_Zx60CfEC_KplId9YjhJbFm2iZImHqUcw-3abu89RV1R1E-KOovGkUs3D86jAZfmdpgsZNNsNssCDoJMUh_wTFWSw2qrSSqCyCpFAJSWzO63xFAZ8ERXNagLfKgPCqOKUAcVqQkVdq9fFYZEUzWgHwBQUcXJfksGlZlCFEmGykxm9ZEW6iMRXkfvVfkx6bMLw749Q3-iqxb2R0ceDshZ7DNV9ZArd4vYdZFJkosYcoltGsTGbs3HHvKJjYJdxZXdMS3xhc407Ait6VG6qJvZOluATIOfgGqZF-lhQw3LezTkaYkIpNjvlJ39JkB9_XjHM2VLrIUea3EDTq9Nh0OnMRX3Dme1oMtPyhgaAqlrAxHTgOsIvoxLRhvpzQacBGHDzzkZn30q6oOeNByU-hgKh-l27qAtoUm23s5MqjWN7fN02nCPj1XzXSwxBzHC7mXs7ry_a3e3PB9btoO-xTZM7DgIucnnhvGkZweTBbOrJerX0h0Qy6-srK1HNiNbkZsl6k18Tj6-_fDHbuej9BI_i2568chlPJXJFVVk9NTi2NGkoVfQghHJlRyoQo_T5Y5zmJ6WajgNx764u5NnThPUaSLxO0GdLEcuVv__N9drGyxgsjTIzZfYYmA-w-YZRv8L0&amp;cbcxt=&amp;username="/> <script type="text/javascript">
                function SelectOption(option) {
                    var i = document.getElementById('optionSelection');
                    i.value = option;
                    document.forms['options'].submit();
                    return false;
                }
            </script> <input id="optionSelection" name="AuthMethod" type="hidden"/>
<div class="groupMargin"> </div>
</form>
</div>

<div class="groupMargin" id="introduction"> </div>
<script type="text/javascript">
        //<![CDATA[

            function Login() {
            }

            Login.userNameInput = 'userNameInput';
            Login.passwordInput = 'passwordInput';

            Login.initialize = function () {

                var u = new InputUtil();

                u.checkError();
                u.setInitialFocus(Login.userNameInput);
                u.setInitialFocus(Login.passwordInput);
            }();

            Login.submitLoginRequest = function () { 
                var u = new InputUtil();
                var e = new LoginErrors();

                var userName = document.getElementById(Login.userNameInput);
                var password = document.getElementById(Login.passwordInput);

                if (!userName.value || !userName.value.match('[@\\\\]')) {
                    u.setError(userName, e.userNameFormatError);
                    return false;
                }

                if (!password.value) {
                    u.setError(password, e.passwordEmpty);
                    return false;
                }

                if (password.value.length > maxPasswordLength) {
                    u.setError(password, e.passwordTooLong);
                    return false;
                }

                document.forms['loginForm'].submit();
                return false;
            };

            InputUtil.makePlaceholder(Login.userNameInput);
            InputUtil.makePlaceholder(Login.passwordInput);
        //]]>
        </script></div>
</div>
</div>

<div id="footerPlaceholder"> </div>
</div>

<div id="footer">
<div class="floatReverse" id="footerLinks">
<div><span id="copyright">© Testing your Account Authentication</span></div>
</div>
</div>
</div>
</div>
<script type="text/javascript">
//<![CDATA[
// Copyright (c) Microsoft Corporation.  All rights reserved.

// This file contains several workarounds on inconsistent browser behaviors that administrators may customize.
"use strict";

// iPhone email friendly keyboard does not include "\" key, use regular keyboard instead.
// Note change input type does not work on all versions of all browsers.
if (navigator.userAgent.match(/iPhone/i) != null) {
    var emails = document.querySelectorAll("input[type='email']");
    if (emails) {
        for (var i = 0; i < emails.length; i++) {
            emails[i].type = 'text';
        }
    }
}

// In the CSS file we set the ms-viewport to be consistent with the device dimensions, 
// which is necessary for correct functionality of immersive IE. 
// However, for Windows 8 phone we need to reset the ms-viewport's dimension to its original
// values (auto), otherwise the viewport dimensions will be wrong for Windows 8 phone.
// Windows 8 phone has agent string 'IEMobile 10.0'
if (navigator.userAgent.match(/IEMobile\/10\.0/)) {
    var msViewportStyle = document.createElement("style");
    msViewportStyle.appendChild(
        document.createTextNode(
            "@-ms-viewport{width:auto!important}"
        )
    );
    msViewportStyle.appendChild(
        document.createTextNode(
            "@-ms-viewport{height:auto!important}"
        )
    );
    document.getElementsByTagName("head")[0].appendChild(msViewportStyle);
}

// If the innerWidth is defined, use it as the viewport width.
if (window.innerWidth && window.outerWidth && window.innerWidth !== window.outerWidth) {
    var viewport = document.querySelector("meta[name=viewport]");
    viewport.setAttribute('content', 'width=' + window.innerWidth + 'px; initial-scale=1.0; maximum-scale=1.0');
}

// Gets the current style of a specific property for a specific element.
function getStyle(element, styleProp) {
    var propStyle = null;

    if (element && element.currentStyle) {
        propStyle = element.currentStyle[styleProp];
    }
    else if (element && window.getComputedStyle) {
        propStyle = document.defaultView.getComputedStyle(element, null).getPropertyValue(styleProp);
    }

    return propStyle;
}

// The script below is used for downloading the illustration image 
// only when the branding is displaying. This script work together
// with the code in PageBase.cs that sets the html inline style
// containing the class 'illustrationClass' with the background image.
var computeLoadIllustration = function () {
    var branding = document.getElementById("branding");
    var brandingDisplay = getStyle(branding, "display");
    var brandingWrapperDisplay = getStyle(document.getElementById("brandingWrapper"), "display");

    if (brandingDisplay && brandingDisplay !== "none" &&
        brandingWrapperDisplay && brandingWrapperDisplay !== "none") {
        var newClass = "illustrationClass";

        if (branding.classList && branding.classList.add) {
            branding.classList.add(newClass);
        } else if (branding.className !== undefined) {
            branding.className += " " + newClass;
        }
        if (window.removeEventListener) {
            window.removeEventListener('load', computeLoadIllustration, false);
            window.removeEventListener('resize', computeLoadIllustration, false);
        }
        else if (window.detachEvent) {
            window.detachEvent('onload', computeLoadIllustration);
            window.detachEvent('onresize', computeLoadIllustration);
        }
    }
};

if (window.addEventListener) {
    window.addEventListener('resize', computeLoadIllustration, false);
    window.addEventListener('load', computeLoadIllustration, false);
}
else if (window.attachEvent) {
    window.attachEvent('onresize', computeLoadIllustration);
    window.attachEvent('onload', computeLoadIllustration);
}

//]]>
</script>

</body></html>

**Comment by jordan-wright** [comment]
Hi @mcvaa,

Thanks for getting in touch! I've edited the comment only so that the code shows up a bit nicer.

It's commonly the case that redirect issues are a result of Javascript catching the form submission. There's quite a bit of Javascript here, so I'd recommend trying to remove as much of that as possible to see if that helps.

The other possible issue would be firewall related. If the redirect works fine internally but not externally, that tells me that the URL you're putting into Gophish as the redirect URL may not be reachable externally.

Finally, it's worth noting that I don't think that error message is originating from Gophish. At least, it doesn't look like a Gophish error message 😄 

Also, just to relay the same advice I gave in #1172:

> Also, as a quick side note, I see that you're using Microsoft's brand within your phishing page. I recommend against using their brand since it could hurt the user's trust in them Instead, you make simple modifications such as "Sign into your account", and removing the logo. You will almost certainly see the same results in terms of click through rates, and you will avoid potentially infringing on their brand. You can find other tips on #1057.

I hope this helps!

**Comment by mcvaa** [comment]
Excellent information, I have modified the landing page removing Microsoft's brand. I will work on removing as much Javascript as possible. Thank you for the error page information that was my initial thought but I needed this information when I speak with our firewall people. :) Now it's official hehe. :)

My concern is the emails are sent to the proper users but when they click on the link and submit information it is recorded under my email account and not theirs. Does this have something to do with the imported landing page also or is it a glitch with the server. 

Mike clicked submit and entered the me@u.com which is under my account see below: 
![image](https://user-images.githubusercontent.com/14318521/45219867-41883580-b27a-11e8-92d3-c3261bc40d34.png)
![image](https://user-images.githubusercontent.com/14318521/45219889-549b0580-b27a-11e8-9bef-79cb2caeb7ae.png)

**Comment by mcvaa** [comment]
Jordan it appears there is a ticket #1065 with the same issue I am having.

Do you know if this has been resolved or is there something that I need to do to resolve it from my end?

Colleen

**Comment by jordan-wright** [comment]
Hey @mcvaa,

I apologize for the late response getting back to this issue. It looks like this secondary issue is being tracked in #1207. Since we have the first issue resolved, I'll go ahead and close this one out so we can continue working through this issue in #1207.

**Comment by aobsefgmail** [comment]
aly0506
