### ISSUE TITLE
Is there anyway to Alias your URL?

### ISSUE THREAD

**Issue by geead** [gophish/gophish#1188]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: **0.6.0**

Brief description of the issue: **I want to try mask the IPv4 Public IP Address which I use in my Phishing Simulation so that it isn't too obvious to users that it is a Fake Webpage.**

What are you expecting to see happen? : **Expecting to see a different URL (rather than an IP Address) once they click the link in the Phishing Email during the simulation.**

What are you seeing happen? **Currently when the click the link in the Phishing Email I've setup it appears as the IPv4 Public Address.**

**Comment by jordan-wright** [comment]
Hi @geead, thanks for reaching out!

I'm not quite sure what you're asking. If you want a domain name to appear instead of the IP address, you simply have to register a domain name and setup DNS to point the domain name to your Gophish IP address. This is all done outside of Gophish. Then, you put the domain instead of the IP address as the "URL" when building a campaign.

Is that what you're looking to do?

**Comment by geead** [comment]
Hi Jordan,

Thanks again for the quick response!

Ah yes, looks like this query is in fact something setup outside of Gophish. I'm trying to figure a way to point my EC2 IPv4 Public Address to my domain name on Godaddy, I'm not sure whether this can be done free of charge however (researched something about linking the two via Route 53 on AWS Console). If you have any further info. regarding this that would be great (even though it probably isn't a Gophish matter).

Thanks for the help so far anyway! :)

**Comment by jordan-wright** [comment]
If you have a domain name already purchased through Godaddy, you just need to create a DNS "A" record that points the domain to your EC2 IP address. More information can be found [here](https://www.godaddy.com/help/change-my-ip-address-20134).

I hope this helps! Thanks again for getting in touch.
