### ISSUE TITLE
Error when inserting email template when {{.BaseURL}} is used

### ISSUE THREAD

**Issue by rubberducky69** [gophish/gophish#1189]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
**Version 0.7**

Brief description of the issue: 
**I noticed from the commits that {{.BaseURL}} has been added as a templating reference, and I wanted to try it out. But it seems that there is an error inserting the email template when using {{.BaseURL}}**

**Is it not supported yet?**

What are you expecting to see happen? :
**The template is inserted, and when used the {{.BaseURL}} is replaced with the URL specified in the campaign**

What are you seeing happen?
**The email template is not inserted. However, when the {{.BaseURL}} is removed from the template is is inserted into the database.**

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```
<html>
    <body style="background-color: white;">
        <table cellpadding="0" cellspacing="0" border="0" style="width: 600px; background-color: #aaa;" align="center">
            <tr>
                <td style="background-color: #222; color: white; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; font-size: 24pt; text-align: center;">
                    This is a test of GoPhish 0.7
                </td>
            </tr>
            <tr>
                <td style="padding: 20px; text-align: center; color: white; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; font-size: 14pt;">
                    Here should be a picture below using baseURL: {{.BaseURL}}<br>
                    <center><img src="{{.BaseURL}}/static/test-image.png"></center>
                </td>
            </tr>

            <tr>
                <td style="padding: 20px; text-align: center; color: white; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; font-size: 14pt;">
                    ... and here should be a link for the webpage {{.URL}}<br>
                    <a href="{{.URL}}">URL</a>
                </td>
            </tr>
        </table>
    </body>
</html>
```

Please provide any terminal output that may be relevant below:

```
time="2018-09-07T10:48:39+02:00" level=error msg="template: template:12:191: executing \"template\" at <.BaseURL>: can't evaluate field BaseURL in type struct { models.Result; URL string; TrackingURL string; Tracker string; From string }"
```

Please provide as many steps as you can to reproduce the problem:
* Insert {{.BaseURL}} in your HTML code for an email template
* Attempt to save it

**Comment by jordan-wright** [comment]
Hi @rubberducky69,

Thanks for reaching out. This is definitely not intended.

I'm able to reproduce this (I swear I checked this - no idea how it slipped through) so I'll get this fixed this weekend and push out a hotfix version 0.7.1.

Thanks for the heads up, and I'm sorry about the inconvenience!

**Comment by rubberducky69** [comment]
@jordan-wright 

Thanks! Nice, quick fix and works like a charm now

**Comment by vinojebastin** [comment]
I am getting this error " Error inserting template into database" please someone help me to save an email template
