### ISSUE TITLE
Campaign Result Inaccurate

### ISSUE THREAD

**Issue by netektives** [gophish/gophish#119]
Hi,

When reviewing the results of a campaign, the last action is listed under status where it should be the most critical status.  For example, if I send myself a campaign, and open the email it will display Email Opened.  If I click the link, it will change to Success.  If i re-open the email, the status changes back to Email Opened.  I can see the "Clicked Link" in the timeline for the user, but it should still be Success for status.  In the results export, it also only lists last event, not the worse case.

**Comment by jordan-wright** [comment]
Hi there!

Thanks for this report! Unfortunately, this is a known bug that we are working to fix. If the user clicks the link, were going to "stick" the status so it doesn't get overwritten.

I'll keep this open until we get this knocked out.

Thanks again!

**Comment by jordan-wright** [comment]
Making this high priority due to the amount of emails/issues we've received about this.
