### ISSUE TITLE
Can't visit landing page

### ISSUE THREAD

**Issue by dickens88** [gophish/gophish#1191]
What version of Gophish are you using?: 0.7.1

Brief description of the issue: After I created a new Campaign, I can receive a phishing mail, and then I click the link in the email which is linked to my landing page. But I can only see a `404 page not found` on the top of the page. The landing page I used for an example is just the example in the template folder `login.html`
I also observed that when I click the phishing link, there is an error in gophish log:

> 
time="2018-09-10T17:51:38+08:00" level=error msg="template: html_template:1: unexpected \"&\" in define clause"

What are you expecting to see happen? : should see the landing page

What are you seeing happen? 404

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
{{ define "base" }}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Gophish - Open-Source Phishing Toolkit">
    <meta name="author" content="Jordan Wright (http://github.com/jordan-wright)">
    <link rel="shortcut icon" href="../../docs-assets/ico/favicon.png">

    <title>Gophish - {{ .Title }}</title>

    <link href="/css/dist/gophish.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,600,700' rel='stylesheet' type='text/css'>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img class="navbar-logo" src="/images/logo_inv_small.png" />
                <a class="navbar-brand" href="/">&nbsp;gophish</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a id="login-button" href="/login">
                            <button type="button" class="btn btn-primary">Login</button>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container">
        <form class="form-signin" action="" method="POST">
            <img id="logo" src="/images/logo_purple.png" />
            <h2 class="form-signin-heading">Please sign in</h2>
            {{template "flashes" .Flashes}}
            <input type="text" name="username" class="form-control top-input" placeholder="Username" required autofocus>
            <input type="password" name="password" class="form-control bottom-input" placeholder="Password" autocomplete="off" required>
            <input type="hidden" name="csrf_token" value="{{.Token}}" />
            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        </form>
    </div>
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/js/dist/vendor.min.js"></script>
</body>

</html>
{{ end }}
```

Please provide any terminal output that may be relevant below:

```
time="2018-09-10T17:51:38+08:00" level=error msg="template: html_template:1: unexpected \"&\" in define clause"
10.25.30.237 - - [10/Sep/2018:17:51:38 +0800] "GET /?rid=ZSmf6my HTTP/1.1" 404 19 "" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Create a Campaign
 * Step 2 - click the link in phishing mail

**Comment by jordan-wright** [comment]
Hi @dickens88,

Thanks for reaching out! It's worth noting that this type of validation for pages has been improved in 0.7.1, so these types of errors should now be caught before sending out the campaign.

In this case, the templates we use in Gophish are more complex, since they are hierarchical. This is what the `{{define "base"}}` at the beginning means.

These templates will have to be cleaned up before you can use them as actual landing pages. Specifically the only things in `{{ }}` should be template values that we define [in the documentation](https://gophish.gitbook.io/user-guide/template-reference). This means you'll want to remove the `define` and `end` tags as well as the `template`, `Title`, and `Token` variables in there.

I hope this helps! Let me know if you continue running in trouble and I can re-open this so we can continue troubleshooting.

**Comment by dickens88** [comment]
Hi @jordan-wright , Thank you so much for your reply. I changed another template and everything works fine.
