### ISSUE TITLE
Cleaning up gophish.db

### ISSUE THREAD

**Issue by dsmurf** [gophish/gophish#1196]
when a template is deleted it is only the referal that is deletede and the gophish.db gets big and long very fast, if something is deleted please also delete from db.

**Comment by jordan-wright** [comment]
Hi @dsmurf,

Are you referring to email templates or landing pages? Either way, I've confirmed with the latest version that the templates and pages are deleted from the database after they are deleted in the UI.

Are you using SQLite or MySQL? And what do you mean by "it is only the referal that is deleted"?

Thanks!

**Comment by dsmurf** [comment]
I use sqlite4 (standart), but it seems that you answered my question, and with much saticefaction. So thank you so much, ill close task.
LOVE Gophish.
