### ISSUE TITLE
Import CSV Issue (Not Importing First Name)

### ISSUE THREAD

**Issue by Rzqu** [gophish/gophish#1197]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

0.60

Brief description of the issue: 

When importing bulk users via CSV it does not display first name in the GUI

What are you expecting to see happen? :

Expecting to see First Name in the GUI 

What are you seeing happen?

GUI is not displaying the First Name but has successfully imported all other columns

**Comment by Rzqu** [comment]
@jordan-wright 

![image](https://user-images.githubusercontent.com/39829605/45424333-16dd1900-b68e-11e8-8643-07111e870bd4.png)

**Comment by jordan-wright** [comment]
Hi @Rzqu,

Thanks for reaching out! This should be fixed in the latest 0.7.1 release. If you upgrade and continue running into the issue, let me know and I'll reopen this to continue troubleshooting.
