### ISSUE TITLE
Broken Image When Using Static Assets

### ISSUE THREAD

**Issue by phil-nguyen** [gophish/gophish#1198]
What version of Gophish are you using?: 
v.0.7.1

Brief description of the issue: 
I can't get a a static file such as an image or PDF to show up on my landing page. 

I might be confused on what is meant by the following:
Any resources copied into the static/endpoint/ directory can be referenced in email templates and landing pages by linking to http://x.x.x.x/static/image.png, where x.x.x.x is the ip of your gophish instance and image.png is the resource.

By gophish instance this should be the phish_server and not admin_server  from what I understand. Do I need to include the port number? Does it matter if my gophish folder is not directly under root? Are PDFs compatible with this method?

I have an image named gophish.jpg in static/endpoint. I must be doing something wrong. I've made sure the server's IP is accessible to the outside. In this case, the outside is our internal network.

What are you expecting to see happen? :
Load static landing page image via http[s]://phishing_server/static/filename.jpg

What are you seeing happen?
A broken image symbol

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<p><img src="http://xxx.xxx.xxx.xxx/static/Gophish1.jpg" /></p>
</body>
</html>
```

Please provide any terminal output that may be relevant below:
```
time="2018-09-12T08:47:25-04:00" level=info msg="x.x.x.x - - [12/Sep/2018:08:47:25 -0400] \"PUT /api/pages/6?api_key=e90ca2091ee669fab1907862c90b48682b990ce446fd4c16c380a1a878f595fb HTTP/2.0\" 200 479 \"https://x.x.x.x:6666/landing_pages\" \"Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0\""
time="2018-09-12T08:47:25-04:00" level=info msg="x.x.x.x - - [12/Sep/2018:08:47:25 -0400] \"GET /api/pages/?api_key=e90ca2091ee669fab1907862c90b48682b990ce446fd4c16c380a1a878f595fb&{} HTTP/2.0\" 200 74795 \"https://x.x.x.x:6666/landing_pages\" \"Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0\""

```
Please provide as many steps as you can to reproduce the problem:
 * Step 1 - go to landing pages
 * Step 2 - try to load .jpg, .png, or .pdf via static/filename method
 * Step 3 - broken image

I've looked at the following documentation/related issues:
https://github.com/gophish/gophish/issues/220
https://github.com/gophish/gophish/issues/507
https://github.com/gophish/gophish/issues/164
https://gophish.gitbook.io/user-guide/documentation/landing-pages#static-assets

**Comment by jordan-wright** [comment]
Hi @phil-nguyen,

Thanks for reaching out!

> By gophish instance this should be the phish_server and not admin_server from what I understand. 

That's correct.

> Do I need to include the port number?

Not if the phishing server is on port 80 or 443

Does it matter if my gophish folder is not directly under root?

The only thing that matters is if the resources are in the static/endpoint/ directory.

Are PDFs compatible with this method?

They should be compatible.

So providing an example, my Gophish folder structure looks like this:

```
gophish/
    gophish
    static
    `--   endpoint
            `--- test.txt
    templates
    db
    etc. 
```

Then, my config has my phishing server listening on `0.0.0.0:80`.

Finally, the IP address of my Gophish server is `192.168.1.1`. 

This means that static assets like `test.txt` can be linked to within templates using this URL:

```
http://192.168.1.1/static/test.txt
```

I hope this helps! Let me know if you run into any other issues and I can re-open this so we can continue troubleshooting.
