### ISSUE TITLE
New v7.1 won't load prevous gophish.db

### ISSUE THREAD

**Issue by turnerdb** [gophish/gophish#1199]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
v7.1
Brief description of the issue: 
After bringing in the new version, we copied over the old gophish.db file like we have done in all previous upgrades.  When we go to start the binary, the servers don't start up all the way and the console log stops at this:
time="2018-09-12T14:15:54Z" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
time="2018-09-12T14:15:54Z" level=warning msg="No contact address has been configured."
time="2018-09-12T14:15:54Z" level=warning msg="Please consider adding a contact_address entry in your config.json"
goose: migrating db environment 'production', current version: 20180223101813, target: 20180830215615
What are you expecting to see happen? :
I'm expecting to see the message of admin and phishing server along with their IPs are started.
What are you seeing happen?
See above
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:
time="2018-09-12T14:15:54Z" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
time="2018-09-12T14:15:54Z" level=warning msg="No contact address has been configured."
time="2018-09-12T14:15:54Z" level=warning msg="Please consider adding a contact_address entry in your config.json"
goose: migrating db environment 'production', current version: 20180223101813, target: 20180830215615

Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by turnerdb** [comment]
Tried a different db file from a current deployment and am now receiving this error:

goose: migrating db environment 'production', current version: 20171027213457, target: 20180830215615
**2018/09/12 18:35:14 FAIL 20171208201932_0.4.1_next_send_date.sql (duplicate column name: send_date), quitting migration.**

**Comment by jordan-wright** [comment]
Hi @turnerdb,

Thanks for reaching out! Just curious, you haven't done any manual work on that database, have you? For example, you haven't manually created a `send_date` column somewhere? That's strange that the migrations are failing. I haven't heard any other reports of this happening. 🙁 

Let me know and we'll continue troubleshooting to track down the problem 😄

**Comment by turnerdb** [comment]
No sir no modifications were made.  I even pulled the fully functioning db file from our prod box and tested it on the new version and that is where the second error came from.  Works fine as long as I don't use a previous db file and let it create its own.

**Comment by Rzqu** [comment]
I too have this issue, just tried to upgrade and now the system wont start


time="2018-09-13T14:44:12Z" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
time="2018-09-13T14:44:12Z" level=warning msg="No contact address has been configured."
time="2018-09-13T14:44:12Z" level=warning msg="Please consider adding a contact_address entry in your config.json"
time="2018-09-13T14:44:12Z" level=error msg="no valid version found"
time="2018-09-13T14:44:12Z" level=fatal msg="no valid version found"

**Comment by Rzqu** [comment]
@jordan-wright Also, even though it says in the error log "No contact address has been configured" i do actually have it in my config.json? but at the system wont fire up, just repeatedly get the messages in my post above.

**Comment by turnerdb** [comment]
No issues with the most current centos7 kernal are there?
Kernal version:  3.10.0-862.11.6.el7.x86_64

**Comment by Rzqu** [comment]
@jordan-wright Hi Jordan, this is what my directory looks like pre upgrade, are you saying i need to move the gophish.db into the /db/db_sqlite3 directory for the migration to pick it up?

![image](https://user-images.githubusercontent.com/39829605/45537897-7148b780-b7fd-11e8-8c4e-a0047d2a709b.png)

**Comment by turnerdb** [comment]
I am upgrading from stable release v6.0

**Comment by Rzqu** [comment]
Hi @jordan-wright , my config.json is 
`{
	"admin_server" : {
		"listen_url" : "0.0.0.0:3333",
		"use_tls" : true,
		"cert_path" : "gophish_admin.crt",
		"key_path" : "gophish_admin.key"
	},
	"phish_server" : {
		"listen_url" : "0.0.0.0:8443",
		"use_tls" : true,
		"cert_path" : "/root/##############/certificate.crt",
		"key_path": "/root/###############/private.key"
	},
	"db_name" : "sqlite3",
	"db_path" : "gophish.db",
	"migrations_prefix" : "db/db_"
}
`

I also see the following in my directories

gophish/db/db_mysql/migrations/
gophish/db/db_mysql/dbconf.yml

gophish/db/db_sqlite3/migrations/
gophish/db/db_sqlite3/dbconf.yml

Thanks.

**Comment by Rzqu** [comment]
Btw, i am using a debian based linux distro (TurnKey)

Thanks.

**Comment by Rzqu** [comment]
@jordan-wright Hi Jordan, any thoughts to the above on what might be happening?

Thanks.

**Comment by jordan-wright** [comment]
Hi @Rzqu,

Sorry for the delay in getting back to you. Just out of curiosity, you say you have a contact address configured, but I don't see one in the config output above? Could you confirm the contents of that config file where you have the contact address and make sure it's named `config.json` in your gophish directory?

**Comment by Rzqu** [comment]
Hi @jordan-wright ive tried with both configs, with and without the contact address line. It makes no difference with either one. i still have the same issue.

**Comment by jordan-wright** [comment]
The reason I mention the other config is that, if a contact address is specified, it's odd that Gophish isn't seeing it. If we can confirm that the contact address is listed correctly (I didn't see it in the snippet you posted earlier), then that might help narrow things down a bit.

**Comment by Rzqu** [comment]
@jordan-wright 

Sorry for the delay in my response, this is probably something i should of tried before originally posting, but i have now input an email address into the contact address field and now everything is working and the system has migrated to 0.7.1 including the database.

Originally what i was doing was leaving the field blank so there was no contact address, i guess the system doesn't like that?

I understand your reasons for putting the contact address field in but if i wanted to leave it blank the system would not upgrade.

Since upgrading ive removed the address from the contact address field so it is now blank and the system comes up fine. 

So im assuming that something during the upgrade process relies on the contact address being populated?

Thanks.

**Comment by pat-inthe-hat** [comment]
I was actually experiencing the same issue as turnerdb and rzqu. I was able to resolve this by inputting my data into the new config.json file, whereas I was previously using the same config.json between versions. I noticed after performing a diff against my v6 and the new v7 config, all the lines we unique, even if they should have been the same (i.e. lines 1 and 2).

**Comment by turnerdb** [comment]
Completely removed the downloaded v7.1 files.  Pulled down a fresh copy and used the new config.  Our DB file is quite large so the new migration took about 10 mins but did complete.  v7.1 is now functioning.
