### ISSUE TITLE
Gophish - Event Logging for all task performed on gophish by a user

### ISSUE THREAD

**Issue by TheManiac3** [gophish/gophish#1209]
What version of Gophish are you using?: 

0.6 build from source

Brief description of the issue: 

i know there is event logging on phishing but i want event log of the current user performing task. This is to understand the process of the user who is creating campaign and other things, after logging every event i will change some UI or add/remove features for him so that he could use it easily. The people who are going to use gophish are not tech savvy and are prone to use only MS Office.

**Comment by jordan-wright** [comment]
Hey @TheManiac3, thanks for reaching out!

We have pretty comprehensive logging in Gophish as-is. I recommend reviewing those logs to determine what actions are being taken.

To make this a bit easier, I've just added the ability to log to a file in addition to stderr. This will hopefully make it easier to gather and review what's being done in Gophish.

I hope this helps!
