### ISSUE TITLE
unable to send email

### ISSUE THREAD

**Issue by phathutshedzo1993** [gophish/gophish#1211]
morning 
my name is netsianda phathutshedzo , i am unable to start gophish , i am getting the following error 
" Max connection attempts exceeded - 535 5.7.8 Username and Password not accepted. Learn more at 5.7.8 https://support.google.com/mail/?p=BadCredentials r30-v6sm2585704wrc.90 - gsmtp
can you please help me i really want to finish this before cyber security months start.

**Comment by jordan-wright** [comment]
Hi @phathutshedzo1993,

Thanks for reaching out. I'm afraid this is an error returned by Google, which is suggesting that the provided username and password aren't correct. This means that there isn't anything we can do on the Gophish side to resolve this issue.

I recommend referring to the link provided in the error message for help to resolve the issue.

Sorry for the inconvenience!

**Comment by phathutshedzo1993** [comment]
jordan-wrigh thanks for the reply , the problem was with my gmail account , i did it now , because it wanted  me to enable allow access secure apps , thanks for the application its very interesting jordan take care

**Comment by phathutshedzo1993** [comment]
thansk i got it jordan , the problem was on my side

**Comment by darkomih** [comment]
Hello Guys.
This doesn't work for me, either gmail, either yahoo, getting the same results as above mentioned from google (despite the Less secure app access is On), and "Max connection attempts exceeded - 535 5.7.0 (#AUTH005) Too many bad auth attempts." from Yahoo.
Please, I'm kindly asking for support

KR,
Darko

**Comment by azamet90** [comment]
i did enabled it like you but one email is working another not i dont know why my credinentals are correct but i get Max connection attempts exceeded - 535 5.7.8 Username and Password not accepted.

**Comment by azamet90** [comment]
okay problem solved! please pin this: i receive security alert and less secure apps is disabled i enabled it tryed again same thing happend i did it maybe 3-4 times and now it is no more blocked from google tryed with 3 different emails result is same but this style it works at the end

**Comment by azamet90** [comment]
@jordan-wright jordan-wright

**Comment by gkhnkckkrts** [comment]
https://www.google.com/settings/security/lesssecureapps

**Comment by ozlou** [comment]
> ![ 222](https://user-images.githubusercontent.com/19945397/176431568-2481b34f-256a-43fd-b82b-3dc092fef78b.png) 

Merhabalar, Bana ulasabilir misiniz ? instagram : oozlemcann
Tesekur ederim simdiden

**Comment by Amine07a** [comment]
Hi guys anyone found a solution for this help me plz

**Comment by Amine07a** [comment]
> okay problem solved! please pin this: i receive security alert and less secure apps is disabled i enabled it tryed again same thing happend i did it maybe 3-4 times and now it is no more blocked from google tryed with 3 different emails result is same but this style it works at the end

Hey did u found a solution

**Comment by sm-711** [comment]
hello guys, this the solution that worked for me : 
As of May 30 2022 google has removed the less secure apps option. There is no way to turn this on as it no longer exists. Enable 2 steps authentication on your google account and create an apps password and use that in place of your true password in your code.
