### ISSUE TITLE
Feature request: Altering random ID-link

### ISSUE THREAD

**Issue by CyberM070** [gophish/gophish#1213]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.7.1

Brief description of the issue: Feature request

What are you expecting to see happen? : At this moment the generated random ID looks like this 
?rid=SN4rXjd or something similar. Is there anyway to be able to alter the random ID link, or add something to it? Let's say that I have a domain name: www.organizationX.com, and I would like to send a phishing mail which has a survey request as theme. I would like to show the landing page link as: www.organizationX.com/phishingsurvey followed by the random ID that is generated. This makes it more realistic and harder for employees to recognize. Another cool feature would be to use employee numbers as random ID since these are familiar for them, and more personalized. If you would like to do something similar at this moment you should host your website and create webpages et cetera, which could save a lot of time when imbedded in the tool.  

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by rubberducky69** [comment]
You could use a subdomain instead, www.phishingsurvey.organizationx.com

**Comment by CyberM070** [comment]
> You could use a subdomain instead, [www.phishingsurvey.organizationx.com](http://www.phishingsurvey.organizationx.com)

Yes but then you would have to setup webhosting for that domain which is not convenient at all times.

**Comment by S0larflare** [comment]
You can already do this, just type what you want the link to be when you set up the campaign

Sent from my iPhone

On 28 Sep 2018, at 08:00, CyberM070 <notifications@github.com<mailto:notifications@github.com>> wrote:


You could use a subdomain instead, www.phishingsurvey.organizationx.com<http://www.phishingsurvey.organizationx.com>

Yes but then you would have to setup webhosting for that domain which is not convenient at all times.

**Comment by jordan-wright** [comment]
Hi @CyberM070, thanks for reaching out!

> I would like to show the landing page link as: www.organizationX.com/phishingsurvey followed by the random ID that is generated.

This is possible. You can create URLs with any arbitrary path or parameters, however the `rid` parameter will still be included at the end.

> Another cool feature would be to use employee numbers as random ID since these are familiar for them, and more personalized.

I'm afraid this won't be possible. Gophish creates a unique ID (the `rid` parameter) that is associated with not only a recipient, but also a campaign. If we were to use some sort of static employee ID, we wouldn't know what campaign an event belongs to.

The only thing we support right now is changing the actual name of the parameter, "rid", to something else, however this requires you to change [the code](https://github.com/gophish/gophish/blob/master/models/campaign.go#L129) and rebuild from source. Also, this would apply to all campaigns, in that it's not configurable per-campaign.

I hope this helps! Let me know if you have any other questions.
