### ISSUE TITLE
creating a campaign

### ISSUE THREAD

**Issue by phathutshedzo1993** [gophish/gophish#1215]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: v0.7.1

Brief description of the issue: when i start my campaign it shows that the email has been send , and when i open that email link it does not show anything it load and after that it will say page can not be reach and it show the ip of my Go phish , i want to know if the is other way to link the link with my ip address of my gophish because i have have been trying it its now showing the results , i want to know what URL do i have to use when i start a campaign. because i have use the ip address i have go when i install go phish     

What are you expecting to see happen? : i am expecting to the the page i have redirected my link to , when i press the link  

What are you seeing happen?i am see the blank page when i press the link on the email i have send during the campaign. it say page can not be reach and it shows the ip address i have put on my URL 

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi @phathutshedzo1993,

When creating a campaign, you need to put the URL pointing to your Gophish server, specifically making sure that the port is pointing to whatever you have as your `phish_server` in your `config.json`. This URL must be reachable by whoever receives the emails.

You can find more information about this (with an example) in our [documentation](https://docs.getgophish.com/user-guide/building-your-first-campaign/launching-the-campaign). 

If you continue to run into issues, please provide your `config.json`, what URL you're using in your campaign, and the contents of your email template (specifically where you reference the `{{.URL}}`). Once this is received, I would be happy to re-open the issue so we can continue troubleshooting.

I hope this helps!
