### ISSUE TITLE
"Copy Campaign" is not reliable

### ISSUE THREAD

**Issue by sjb-commarc** [gophish/gophish#1221]
What version of Gophish are you using?:  **0.6.0**

Brief description of the issue: 

If an existing campaign is selected on the "Campaigns" screen and the "Copy Campaign" icon clicked, the fields in the resulting screen in fact seem to show a hodge-podge of content. The "Name" field seems fine - always has the original name with "Copy of " prefix, but I've had instances where the "Email Template", "Landing Page" or "Sending Profile" pick seeming random values from the database. 

"Group" seems to be always blank, but this may be by design.

What are you expecting to see happen? :

All detail but the "Name" to be the same as what we're copying from.

The screenshots included from a test just now, show the "Email Template" and "Sending Profile" changing - but this report was prompted by several cases today on a live engagement where the "Landing Page" changed.

PS: Note that this also means that there's no way to reliably view/inspect the configuration of a campaign.

![one](https://user-images.githubusercontent.com/24516130/46334842-0bc04c00-c682-11e8-8645-1bfba414098c.png)
![two](https://user-images.githubusercontent.com/24516130/46334850-111d9680-c682-11e8-90db-20febe619d6e.png)

**Comment by jordan-wright** [comment]
Hi @sjb-commarc,

Thanks for reaching out! I've heard other similar issues in #549 and others. The problem has been that I've never been able to reliably reproduce them.

Let's work through #549 to keep things consolidated- I'll post a follow-up comment there with more information so we can continue tracking this down. As soon as I can manage to reproduce the issue, I'll be able to implement a fix.

Sorry for the hassle!
