### ISSUE TITLE
Unique report various campaigns

### ISSUE THREAD

**Issue by bofhzen** [gophish/gophish#1232]
Good morning!
I'm launching some campaigns to split users mails. All is OK and is perfectly tracked.
My question is:
Is it possible to generate a report of all of the campaigns in a single report? I mean, if I have 9 campaigns, generate a report at finish with the information of all, without generate it separately campaign by campaign .
Thank you
Regards

**Comment by pat-inthe-hat** [comment]
> Is it possible to generate a report of all of the campaigns in a single report? 

Look into GoReport. That should fulfill what you're looking for 
https://github.com/chrismaddalena/GoReport

**Comment by bofhzen** [comment]
> 
> 
> > Is it possible to generate a report of all of the campaigns in a single report?
> 
> Look into GoReport. That should fulfill what you're looking for
> https://github.com/chrismaddalena/GoReport

Thank you!
The problem is i'm using windows environment to make the campaign.
Is it possible to run in windows?
Thank you
Regards

**Comment by jordan-wright** [comment]
Hey @bofhzen,

@pat-inthe-hat is correct that GoReport is a fantastic tool that can handle this. It's Python, so it should run on Windows just fine assuming you have Python installed.

Alternatively, if you'd prefer to do the coding yourself, we have excellent [API documentation](https://docs.getgophish.com/api-documentation/) and a [Python client](https://docs.getgophish.com/python-api-client/) to make this pretty easy.

I hope this helps!

**Comment by bofhzen** [comment]
Thank you !
I will try to install phyton but is a server managed by other so I hope they allow me to install it :P
