### ISSUE TITLE
Automatically Enroll Phished Users Into Training Courses

### ISSUE THREAD

**Issue by RCPMAD** [gophish/gophish#1233]
Would be nice to have. It does mean expanding the application further. Take it even further and track those who complete the training course.

**Comment by dsmurf** [comment]
i am using this with awareness training and we are using a playform where results are shown via API, Gophish is not training, so im not sure what you are asking for?

**Comment by RCPMAD** [comment]
At the moment I am using the redirect page to take users to a static intranet page where they have to follow instructions on what to do next. It would be nice to have an additional option where the redirect page is created within Gophish where we can add custom training with a complete button at the end.

**Comment by securitygeneration** [comment]
I currently use the 'reporting' functionality to track this. In the static training site, you can create a button that does a request to `/report?rid=xxxxx` and it will get marked for that user as 'Reported' which you can just take as 'Completed Training'. Note that this does mean you need to have a way to pass the RId.

**Comment by jordan-wright** [comment]
Hi @RCPMAD,

Thanks for reaching out! I'm afraid custom training is something that I don't plan to support in Gophish in the near future. It's one of those features that everyone would want fully functioning out of the box, and everyone would have different requirements (hooking up to their own LMS, which has it's own format, or wanting full training that's customizable within Gophish, and more).

I recommend taking an approach similar to what @securitygeneration suggests. I've _just_ added the ability to add template tags like `{{.RId}}` to the redirect URL, so if you point the redirect URL to your training using something like `http://trainingurl.com?rid={{.RId}}`, it can parse that out and use that ID in subsequent API calls to Gophish to, say, hit the `/report` endpoint, or something else.

Sorry I couldn't be of more help!
