### ISSUE TITLE
Pass RId in Landing Page redirect

### ISSUE THREAD

**Issue by securitygeneration** [gophish/gophish#1235]
I sometimes like to redirect users to another page (static or otherwise) after the landing page, but would still like to be able to track them individually (using their RId). One example is when redirecting to a training site - or a fake 'post login' page. I've tried putting `/static/page?rid={{.RId}}` into the Redirect To parameter in the Landing Page template, however this doesn't get populated.

The simplest way I can think of doing this is to populate {{.RId}} into the Redirect To value.

**Comment by securitygeneration** [comment]
This is related to #1178, where the `{{.RId}}` was introduced, but it just doesn't appear to get inserted into the Redirect To parameter.

**Comment by jordan-wright** [comment]
Ah, good call. I could see this being useful. I'll get it added.

Thanks for the suggestion!

**Comment by fjbosscha** [comment]
I have the following redirect URL:

https://kerstpakket.nhistenden.com/?rid={{.RId}}

For some reason the RId is not passed to the index.php file. What have I done wrong?

**Comment by fjbosscha** [comment]
The version I have is 0.7.1. Or do I need to update some files?

**Comment by securitygeneration** [comment]
@fjbosscha Yeah, this feature hasn't been included in a release yet. You'll need need to compile from source for that in the meantime.

**Comment by fjbosscha** [comment]
When will a new release be available. I tried to compile it, but get a lot of missing packages.
