### ISSUE TITLE
Display Result ID in Campaign Results View

### ISSUE THREAD

**Issue by danimelo59** [gophish/gophish#1239]
```html
Is there a way to get the rid parameter for a given recipient?
a database query?
a script?

thank you for your help
```

**Comment by S0larflare** [comment]
Assuming you are using the default setup and have access to sqlite3:

1) cd into your gophish directory
2) sqlite3
3) attach "gophish.db" as db1;
4) .headers ON
5) select r_id,email from db1.results LIMIT 10;  //This will give you the last 10 results
6) select r_id,email from db1.results where email="youremail@goeshere"; //will find the rid for a specific email

**Comment by securitygeneration** [comment]
Users' RIds per-campaign are also available within the campaign's 'Results' CVS export. It might be a nice idea to show that value in the UI somewhere too... 

![image](https://user-images.githubusercontent.com/1046239/47141850-7f389f00-d2b9-11e8-88f0-871ea22aac74.png)

**Comment by jordan-wright** [comment]
Agreed completely with @securitygeneration. I'll add the RID to the results view. This is a case of my getting so used to my workflow (spending time in the Chrome devtools) that I didn't realize this could and should be made easier.

I'll post up a fix soon. Thanks for the great feedback everyone!
