### ISSUE TITLE
Feature Enhancement: Submitted Credential Handling

### ISSUE THREAD

**Issue by swannysec** [gophish/gophish#124]
As a result of our twitter conversation, some thoughts around submitted credentials and potential enhancements:
-Encrypt these at rest.
-Mask them on display and reveal them behind additional auth or only display last x characters.
-Include an easy on/off toggle for credential gathering.
-Allow username to be harvested and a yes/no recorded for a password submitted instead of the password itself.

Compliance issues could make storage or display of credentials in the clear a non-starter for gophish in some environments.

**Comment by rfdevere** [comment]
Good ideas and I see your aims, masking them though is rather quaint as to access the masked creds surely you will be authenticated and able to unmask them? 

The on off switch for red harvesting is cool.

The Yes/No might fail when staff input "get lost" in the password field and you think you have a valid cred.

**Comment by swannysec** [comment]
Good point about the yes/no.  As for masking, while I agree with you, our compliance accounts for shoulder-surfing, so they have in the past asked that sensitive data such as SSNs be visibly masked unless absolutely necessary.  Silly perhaps, but a reality for some.

Also, masking would allow me to utilize contractual or volunteer labor to work with/respond to phishing victims without access to their full password.

**Comment by rfdevere** [comment]
Totally understand. The worst case scenario would be someone dropping this box and taking with it 50 sets of client creds.

**Comment by jordan-wright** [comment]
So I was thinking about this today, and it's going to be difficult. I need a way to encrypt data in one column. Symmetric key encryption makes sense, but I need to figure out what I'll use as the key.

Storing the key in the db won't work, so API keys are out. Next most common is the user's password. That is fine, but it makes it a huge pain to deal with w/ regards to the API. Specifically, we would have to document that the client would get a base64 encrypted blob back that they have to manually decrypt. Doable- but not ideal.

Any crypto experts out there have a better suggestion?

**Comment by snori74** [comment]
Saving the creds is a probably a bad idea for the sort of blue-team use case I have - where they are likely to be for external banking sites. LinkedIn etc, and I really _don't_ want to be responsible for these. Fine if it's an *option*, but I'd rather they be collected and discarded in the browser, as some other similar systems do.

**Comment by jordan-wright** [comment]
I think what I might do is at the very least include a UI checkbox in the landing page modal that says "collect passwords" or something similar.

If the checkbox is checked when the form is saved, no action will be taken. If the checkbox is *not* checked (the passwords are not to be collected), I can remove the "name" attribute from the input elements that are of the type ```password``` so that they are not sent.

How does that sound for a start?

**Comment by swannysec** [comment]
That'll make compliance a lot easier.  How difficult would a binary yes/no for "user entered credentials" be?  Obviously it fails to account for those that fill in junk, but it may give good data for many recipients.  It represents a sort of middle ground until a way to encrypt creds is found.

**Comment by jcamil** [comment]
Homomorphic Encryption, maybe?

**Comment by jordan-wright** [comment]
Just an update on this one. I'm close to having two checkboxes: "Capture credentials" and "Include passwords" that do as expected. They will manipulate the form fields via javascript so that, when the landing page is saved, only the relevant data is setup to be captured.

For now, I'm running into a roadblock modifying the data in CKEditor. I have an [open question](https://stackoverflow.com/questions/35399568/how-to-modify-element-in-ckeditor/35418611), so we'll see how it goes.

**Comment by swannysec** [comment]
Sounds great Jordan.  I appreciate the flexibility.  It will make gophish a
lot more amenable to my compliance overlords.

**Comment by jordan-wright** [comment]
Looks like this isn't coming along like I would have hoped. I was hoping to keep this on the frontend only and not add any new information to the database or the API.

But, with the way CKEditor structures their data, their isn't an easy way to accomplish this. I think for now I'm going to transition towards just making these fields in the database.

To show some progress, here are the UI elements:

![image](https://cloud.githubusercontent.com/assets/1317288/13305740/34d1dbf6-db23-11e5-8c16-65e0791d52c3.png)

**Comment by jordan-wright** [comment]
Hey @swannysec - mind giving this a shot? The changes are in master.

Let me know if you run into any issues!

**Comment by swannysec** [comment]
Thanks Jordan, great work.

**Comment by swannysec** [comment]
Will do, will try in the AM.

**Comment by swannysec** [comment]
Apologies for the delay, but I tested this today and it looks great.  I
think this is a very reasonable approach until/unless some form of
encryption can be worked out.  Out of curiosity, is there a roadmap for
gophish somewhere?

**Comment by jordan-wright** [comment]
Hey John,

No major roadmap other than the issues on GH. We use these to keep milestones for upcoming releases.

As we move forward with an enterprise offering, there will likely be a more defined roadmap hosted on the website or elsewhere.

**Comment by rschwass** [comment]
I cant find the usernames in the db
