### ISSUE TITLE
SSL Landing Page Issue

### ISSUE THREAD

**Issue by anarey3117** [gophish/gophish#1241]
What version of Gophish are you using?: 0.7.1

Brief description of the issue: After following the following guide: https://www.n00py.io/2017/09/phishing-with-gophish-and-letsencrypt/ (requesting a certificate from Let's Encrypt, pointing the config.json file to the new files, restarting the service and forcing the subdomain to https://), I still get Not Secure with the certificate being Invalid.

What are you expecting to see happen? : To have the nice shiny green padlock on my landing page.

What are you seeing happen? Not secure in the top left, with the certificate being invalid.

Browser error message:
![image](https://user-images.githubusercontent.com/44260615/47148244-202e5680-d2c8-11e8-9742-14b30097de3f.png)

Browser cert info:
![image](https://user-images.githubusercontent.com/44260615/47148311-51a72200-d2c8-11e8-8545-3cc716aa6e9d.png)

More browser cert info:
![untitled](https://user-images.githubusercontent.com/44260615/47148354-700d1d80-d2c8-11e8-858a-2793fc94bcaa.png)

Code for my config.json file:

{
	"admin_server": {
		"listen_url": "142.93.37.104:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "gophish_admin.key"
	},
	"phish_server": {
		"listen_url": "0.0.0.0:443",
		"use_tls": true,
		"cert_path": "/opt/goapps/src/github.com/gophish/gophish/dropbx.crt",
		"key_path": "/opt/goapps/src/github.com/gophish/gophish/dropbx.key"
	},
	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": "",
	"logging": {
		"filename": ""
	}
}

Is there anything blatantly obvious that I'm missing?

Any help would be highly appreciated.

Thanks!

**Comment by anarey3117** [comment]
Issue resolved - didn't add *. to SSL cert when creating the cert. Please close.

**Comment by jordan-wright** [comment]
@anarey3117, I'm glad you were able to get this resolved!

I'm afraid that multiple SSL certificates are not supported at this time. Eventually, I plan to include Let's Encrypt support that should help with this, but I don't have an ETA on this yet. For now, the only thing I can suggest would be to add the other domains as subject alternate names on the certificate.

**Comment by jinrowarrior** [comment]
"Issue partly resolved - I didn't add *. for the SSL certificate."
where we need to add *. ?
