### ISSUE TITLE
Setting Send By Date via API

### ISSUE THREAD

**Issue by material3dge** [gophish/gophish#1245]
What version of Gophish are you using?: 0.71

Brief description of the issue: 

I can't seem to figure out how to specify the Send By Date via API. I found a reference in campaign.go (I think?) to what appeared to be the campaign creation syntax with SendDelay, but adding that to the API request didn't work. 

I am able to create campaigns using the API without issue.

Any idea how to set 'Send By Date' via API?

**Comment by jordan-wright** [comment]
Hey @material3dge,

Thanks for reaching out! If you're running at least 0.7.1, then you should be able to set it as an ISO8601 formatted datetime. Here's an example:

```
  "send_by_date": "2018-10-23T21:00:00Z",
```

You can find more information about it in our revised [API documentation](https://docs.getgophish.com/api-documentation/campaigns#spreading-out-emails).

I hope this helps!

**Comment by material3dge** [comment]
Ah! That was it. I updated the key and BOOM. Working as expected.

Thanks for the quick response!
