### ISSUE TITLE
Last email address showing as opened immediately

### ISSUE THREAD

**Issue by dfsec** [gophish/gophish#1248]
What version of Gophish are you using?: 0.7.0

Brief description of the issue: Two test campaigns today are showing that the last email sent is immediately opened. The first instance never made it to the mail account.

What are you expecting to see happen? : Assistance in understanding why this may be happening so the results are accurate and the deliveries are consistent.

What are you seeing happen? I created a campaign with 3 email addresses, the last being my gmail address. Upon submitting the campaign, the entry for my gmail address said it was almost immediately opened and the email never made it to my inbox. I could not locate it in the account at all. I created a second campaign with 6 email addresses in it. This time, with someone elses gmail address as the last. Upon submitting the campaign, my gmail address received the email fine with no 'opened' status, but the new gmail address at the end of the list showed as immediately opened and the email did get delivered. I created a third campaign with the same 6 email addresses, they all got delivered, and none showed as opened after I submitted. I have attached screenshots of the two instances where the emails were immediately opened. Any assistance or explanation is appreciated! Thanks!
![problem2](https://user-images.githubusercontent.com/44448605/47459838-1f576200-d7ab-11e8-802f-a7d65c3ffba7.png)
![problem1](https://user-images.githubusercontent.com/44448605/47459839-1feff880-d7ab-11e8-86d2-f21b1339b3a5.png)

**Comment by jordan-wright** [comment]
Thanks for reaching out! At first glance, I assume this is probably related to the image proxy Gmail uses. You can find more information [here](https://blog.filippo.io/how-the-new-gmail-image-proxy-works-and-what-this-means-for-you/).

If you look in the raw event export, what does the user agent of the email opened events look like?

**Comment by dfsec** [comment]
Thanks for the prompt response! Apologies for the delay. That makes sense. I forgot about that. I'll check the events and see what shows up there.

**Comment by jordan-wright** [comment]
Going ahead and closing this out since there haven't been any updates in a couple of weeks. @dfsec if you continue to run into issues, let me know and I'll be happy to re-open.

Thanks again for reaching out!

**Comment by aczietlow** [comment]
We're experiencing an identical issue. For many of our users, as soon as the image is cached on Google's end, the campaign returns the open result almost as soon as the email is sent.  We're trying to provide phishing audits to organizations, some of whom use g suite enterprise email solutions. Is there any way around Google's image caching? 

![image](https://user-images.githubusercontent.com/1714659/53766925-4bde6180-3ea2-11e9-9f25-acba19746c5a.png)

**Comment by aczietlow** [comment]
After poking at this last evening I'm curious if Google will respect caching headers if returned when it tries to pre-fetch images

**Comment by danish31** [comment]
I am facing the same issue with Microsoft outlook. As soon as I am sending mails, email opened is getting triggered. I have added traffic policy, added exception in spam filter, added x-ms-exchange-organization-safelink-processing to value 1.Also added the domain in safe sender list. Still I am facing the issue.

Can someone help?
