### ISSUE TITLE
Can't Capture Data

### ISSUE THREAD

**Issue by gremioreheart** [gophish/gophish#1253]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.7.1

Brief description of the issue: I cant capture any data even if i already open the email and link the link i think this is related to #982 

What are you expecting to see happen? : To capture data and to see in the dashboard

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

![image](https://user-images.githubusercontent.com/43837365/47627599-f4368f00-db6b-11e8-94e1-248c288b7ae0.png)

![image](https://user-images.githubusercontent.com/43837365/47627601-f8fb4300-db6b-11e8-8a4e-c00a3f17687a.png)

![image](https://user-images.githubusercontent.com/43837365/47627604-fe588d80-db6b-11e8-8e90-5f4177ac1e2e.png)

![image](https://user-images.githubusercontent.com/43837365/47627609-04e70500-db6c-11e8-89fb-53e25298f0a9.png)

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 - 
 
 Thank you

**Comment by jordan-wright** [comment]
Hi @gremioreheart,

We’ll want to start with the template you’re using. Are you using the `{{.URL}}` template tag in your links? What does the link in the email you receive look like?

What do you see when you click that link? What URL are you using when creating your campaign?

**Comment by gremioreheart** [comment]
Regard with template i dont use import email template i just make my own letter and this is what i see if i receive  the email 
![image](https://user-images.githubusercontent.com/43837365/47690441-fc083900-dc28-11e8-81a8-3690b82b0cd4.png)

When i click  the link the link : 
![image](https://user-images.githubusercontent.com/43837365/47690469-1cd08e80-dc29-11e8-9f54-d8dc99e0c8be.png)

URL : 
![image](https://user-images.githubusercontent.com/43837365/47690493-340f7c00-dc29-11e8-999b-2456be663313.png)

**Comment by jordan-wright** [comment]
The URL field when building a campaign needs to be a URL that resolves to your Gophish server. In this case, `mail.sampleemail` isn't a valid FQDN. You'll want to replace this with either the external IP address of the Gophish server, or a domain that resolves to the IP address of the Gophish server.

**Comment by gremioreheart** [comment]
what you do mean with the domain IP address of the gophish server?

**Comment by jordan-wright** [comment]
The links in the emails sent by Gophish will use whatever you put in the URL field. This means that the URL has to be either the external IP address of the server that is running Gophish, or a domain that resolves through DNS to the external IP address of the server running Gophish.

The example you gave isn’t a real domain, so it won’t work. You can find more information about this in our documentation: https://docs.getgophish.com/user-guide/documentation/campaigns

**Comment by gremioreheart** [comment]
ahh ok i will try it Thank you i will just comment if not still working

**Comment by gremioreheart** [comment]
Hello Jordan i change the url to my gophish server
![image](https://user-images.githubusercontent.com/43837365/47765077-30e8be80-dd03-11e8-92ef-e360d8d4b749.png)

this is what happen i got a error of r0r pager b
![image](https://user-images.githubusercontent.com/43837365/47765106-5b3a7c00-dd03-11e8-8ea9-f6c41e556aa7.png)

**Comment by jordan-wright** [comment]
You’re close! It looks like the IP is probably correct, but it’s being put in the wrong place.

In your email template, you want to use the template tag “{{.URL}}” like we show in the docs. This tells Gophish to dynamically put in whatever URL you use in your campaign into that space.

Then, when you actually build your campaign, the URL field is where you want to put your IP address.

**Comment by gremioreheart** [comment]
Hello Sir what do you mean put in the wrong place ?

**Comment by gremioreheart** [comment]
time="2018-11-01T09:40:23+08:00" level=info msg="10.2.70.8 - - [01/Nov/2018:09:40:23 +0800] \"GET /api/groups/summary?api_key=8d658c4b0372c7416d8586c5015b493730422e97a84e26211bc8b31f9d33839d&{} HTTP/2.0\" 200 154 \"https://192.168.19.56:3333/users\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36\""
10.2.70.8 - - [01/Nov/2018:09:49:21 +0800] "GET / HTTP/1.1" 404 19 "" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"


is this what happen when i click the link

**Comment by jordan-wright** [comment]
Refer back to the documentation where we show how to build an example campaign and you'll see what I mean. Check out how we put the `{{.URL}}` template tag when we make our [email template](https://docs.getgophish.com/user-guide/building-your-first-campaign/creating-the-template).

Then, when it comes time to build a campaign, _that's_ where [we put the IP address of our Gophish server.](https://docs.getgophish.com/user-guide/building-your-first-campaign/launching-the-campaign).

It looks like you have the two switched - you're trying to put the IP address in the template, instead of using the `{{.URL}}` tag.

**Comment by gremioreheart** [comment]
Hello Sir Jordan wright Thank You for the support i already fix the error and also you have a good product that is very useful
