### ISSUE TITLE
campign namechange

### ISSUE THREAD

**Issue by dsmurf** [gophish/gophish#1254]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.71

Is there a way to change the name of a campaign that has run?

**Comment by jordan-wright** [comment]
Hi @dsmurf,

I’m afraid it’s not currently possible to edit a camapaign after it’s been launched, except to complete it or delete it.

It’s _possible_ I’ll add this in the future, but I’m afraid it will be a low priority item. For now, you can always edit the campaign name in the database directly.

Sorry I couldn’t be of more help!

**Comment by dsmurf** [comment]
I just dont want anything to get messed up by editing manually.

**Comment by S0larflare** [comment]
You could take a copy of the database and edit that one. I don’t have access to look at the minute but I think there is only one reference to a campaign name, so the change should be a simple one

Sent from my iPhone

On 29 Oct 2018, at 13:13, Henrik Krai Eckhoff <notifications@github.com<mailto:notifications@github.com>> wrote:


I just dont want anything to get messed up by editing manually.

**Comment by dsmurf** [comment]
Thanks
