### ISSUE TITLE
Admin server can't be reached

### ISSUE THREAD

**Issue by caneno** [gophish/gophish#1259]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
Gophish v0.7.1
Brief description of the issue: 
I am kind of new here and I hoe I do not trouble anybody but, I installed gophish on a digitalocean server, and every time I try to access https://0.0.0.0.:3333 I get site can't be reached. I checked for firewalls and I do not see any. If this is a stupid question I apologized in advance.

This is what the terminal looks like:

```html
root@ubuntu-s-1vcpu-1gb-sfo2-01:~/gophish# ./gophish 
time="2018-11-05T22:17:51Z" level=warning msg="No contact address has been configured."
time="2018-11-05T22:17:51Z" level=warning msg="Please consider adding a contact_address entry in your config.json"
time="2018-11-05T22:17:51Z" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
goose: no migrations to run. current version: 20180830215615
time="2018-11-05T22:17:51Z" level=info msg="Starting phishing server at http://0.0.0.0:80"
time="2018-11-05T22:17:51Z" level=info msg="Starting admin server at https://0.0.0.0:3333"
177.47.192.80 - - [05/Nov/2018:22:27:46 +0000] "GET / HTTP/1.1" 404 19 "" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"

```

**Comment by jordan-wright** [comment]
Hey @caneno, thanks for reaching out!

It looks like things are starting up correctly. Just make sure you're putting the IP address of your droplet in your browser like this: `https://x.x.x.x:3333`. From what I can see in the logs, it looks like you might be omitting the port in the URL.

**Comment by caneno** [comment]
@jordan-wright 
Thank you for you help I was able to access the admin server. I was actually using https://0.0.0.0:3333 instead of using the VPS ip address. Again thanks for your help

**Comment by jordan-wright** [comment]
👍 Good deal! I'm glad we were able to help.
