### ISSUE TITLE
Adding docker container to the wiki

### ISSUE THREAD

**Issue by MatteoGgl** [gophish/gophish#126]
Hi! Today I created a simple [docker container](https://hub.docker.com/r/matteoggl/gophish/) ([repo here](https://github.com/MatteoGgl/docker-gophish)) to provide a quick local install of gophish version 0.1.1.

I wonder if there's any interest in incorporating this install method into the wiki or somewhere else.

**Comment by jordan-wright** [comment]
Thanks for this! I'll give this a lookover, and if everything looks good we can include it in the README.md as an unofficial docker container.

Would it be better to have a Dockerfile just in the root directory that uses a standard trusted container and installs gophish on it? I'm new to all that stuff, so I could be way off base.

**Comment by MatteoGgl** [comment]
The best way to distribute an images is through the Docker Hub: one can simply download and run the image on his system by typing 
```bash
docker run name/image
```
with the appropriate flags. Creating a GitHub repository associated with the docker image makes you able to automate the image building process and connect it to branches and tags. ([more info here](https://docs.docker.com/docker-hub/builds/)). 
I'd say a Dockerfile is out of the scope of the readme, since it's not directly related to gophish; it can be used to customize the image if someone wants to improve it and/or build it theirself.

**Comment by jordan-wright** [comment]
Thanks for this! https://github.com/gophish/gophish/blob/master/README.md#docker

**Comment by MatteoGgl** [comment]
Great! Glad I could help!
