### ISSUE TITLE
Inconsistent donut graphs

### ISSUE THREAD

**Issue by mcvic1rj** [gophish/gophish#1261]
What version of Gophish are you using?: 
0.7
Brief description of the issue: 
Donut chart on main page has the number of actions and the highlighted part in the chart is the percentage. Within individual campaigns, the donut charts highlighted text shows the number, which is a duplicate of what is in the center of the donut.

What are you expecting to see happen? :
to have both donut charts be consistent

What are you seeing happen?
inconsistent behavior

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - View main page dashboard, note donut chart ![image](https://user-images.githubusercontent.com/10363041/48084766-94bd2c80-e1c6-11e8-8596-a1f94a14ce02.png)
 * Step 2 - See specific campaign dashboard, note the difference in donut chart ![image](https://user-images.githubusercontent.com/10363041/48084774-9dadfe00-e1c6-11e8-8e7a-2f983a628a58.png)

**Comment by jordan-wright** [comment]
Thanks for this suggestion! You’re absolutely right that this appears to be a UI inconsistency. I’ll get this fixed so that the tooltip shows the percentage, matching the main dashboard.

**Comment by jordan-wright** [comment]
Closed via #1264.
