### ISSUE TITLE
Send Emails By does not exactly provide an even distribution

### ISSUE THREAD

**Issue by rubberducky69** [gophish/gophish#1262]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
**0.7.1**

Brief description of the issue: 
**When sending campaigns that are throttled (with a specified end-date), the emails are not actually distributed evenly between the two specified dates.**

**An example:**
_**I want to send 250 mails with a rate of 10 mails per minute (6 second interval). I specify a starting date: 12/7/2018 16:00 PM and an end date: 12/7/2018 16:25 PM. This results in 10 mails being scheduled to send every minute, and once the campaign is started, the 10 mails are sent with 1 second intervals.**_

What are you expecting to see happen? :
**When two dates are specified it takes the difference between the two dates, and divide it with 250, thus resulting in an interval of 6 seconds and an even distribution of emails.**

**I would love to see a change to this, or even an extra option with a MPM-rate (Mails Per Minute) that can be specified on campaign launch.**

**Comment by jordan-wright** [comment]
Hi @rubberducky69,

Thanks for reaching out! You're correct, but I'm afraid this isn't something that we'll be able to fix.

The worker responsible for sending the emails polls the database for new emails once per minute. This is to balance frequent polls without taking the chance of overwhelming the database in the case of larger campaigns.

This means that when creating our send dates for emails, we round it to the nearest minute. Then, when new emails are picked up to be sent that particular minute, we send them immediately so we can both send emails quickly as well as reuse the existing SMTP connection.

At the very least, I'll update the documentation to be more clear that emails aren't evenly spaced down to the second, but rather to the minute. Sorry for any inconvenience this caused!
