### ISSUE TITLE
Url Launching campaigns

### ISSUE THREAD

**Issue by albus45** [gophish/gophish#1263]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: the last one, for windows 64bit

Brief description of the issue: hello, i'm a beginner and despite the fact I read similar issue, I still cannot come up with my problem. I followed all the steps and when it comes to launch campaigns it says: error sending email to "target". I can't understand what i should write in url field. I tried with the ip of my pc, with the ip given at the beginning of the prompt open on gophish app and so on. Can u help me? thank u in advance and sorry for my inexperience.

What are you expecting to see happen? : launching the campaigns correctly

What are you seeing happen? it starts but doesn't send the email

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here time="2018-11-07T23:37:16+01:00" level=info msg="127.0.0.1 - - [07/Nov/2018:23:37:16 +0100] \"GET /api/groups/?api_key=e9e642eb0149772c4e85881d01c0c52a6d2c939ad9712905cff2e3e14acda5e7&{} HTTP/2.0\" 200 1062 \"https://127.0.0.1:3333/campaigns\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0\""
time="2018-11-07T23:37:16+01:00" level=info msg="127.0.0.1 - - [07/Nov/2018:23:37:16 +0100] \"GET /api/templates/?api_key=e9e642eb0149772c4e85881d01c0c52a6d2c939ad9712905cff2e3e14acda5e7&{} HTTP/2.0\" 200 2991 \"https://127.0.0.1:3333/campaigns\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0\""
time="2018-11-07T23:37:16+01:00" level=info msg="127.0.0.1 - - [07/Nov/2018:23:37:16 +0100] \"GET /api/pages/?api_key=e9e642eb0149772c4e85881d01c0c52a6d2c939ad9712905cff2e3e14acda5e7&{} HTTP/2.0\" 200 19399 \"https://127.0.0.1:3333/campaigns\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0\""
time="2018-11-07T23:37:16+01:00" level=info msg="127.0.0.1 - - [07/Nov/2018:23:37:16 +0100] \"GET /api/smtp/?api_key=e9e642eb0149772c4e85881d01c0c52a6d2c939ad9712905cff2e3e14acda5e7&{} HTTP/2.0\" 200 350 \"https://127.0.0.1:3333/campaigns\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0\""
time="2018-11-07T23:37:56+01:00" level=info msg="Creating maillog for giosette4575@gmail.com to send at 2018-11-07 22:37:00 +0000 UTC\n"
time="2018-11-07T23:37:56+01:00" level=info msg="127.0.0.1 - - [07/Nov/2018:23:37:56 +0100] \"POST /api/campaigns/?api_key=e9e642eb0149772c4e85881d01c0c52a6d2c939ad9712905cff2e3e14acda5e7 HTTP/2.0\" 201 21819 \"https://127.0.0.1:3333/campaigns\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0\""
time="2018-11-07T23:37:57+01:00" level=info msg="127.0.0.1 - - [07/Nov/2018:23:37:57 +0100] \"GET /campaigns/9 HTTP/2.0\" 200 2090 \"https://127.0.0.1:3333/campaigns\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0\""
time="2018-11-07T23:37:59+01:00" level=info msg="127.0.0.1 - - [07/Nov/2018:23:37:59 +0100] \"GET /docs-assets/ico/favicon.png HTTP/2.0\" 404 19 \"\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0\""
time="2018-11-07T23:37:59+01:00" level=info msg="127.0.0.1 - - [07/Nov/2018:23:37:59 +0100] \"GET /api/campaigns/9/results?api_key=e9e642eb0149772c4e85881d01c0c52a6d2c939ad9712905cff2e3e14acda5e7&{} HTTP/2.0\" 200 606 \"https://127.0.0.1:3333/campaigns/9\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0\""
time="2018-11-07T23:38:00+01:00" level=info msg="127.0.0.1 - - [07/Nov/2018:23:38:00 +0100] \"GET /campaigns HTTP/2.0\" 200 2515 \"https://127.0.0.1:3333/campaigns/9\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0\""
time="2018-11-07T23:38:01+01:00" level=info msg="127.0.0.1 - - [07/Nov/2018:23:38:01 +0100] \"GET /docs-assets/ico/favicon.png HTTP/2.0\" 404 19 \"\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0\""
time="2018-11-07T23:38:01+01:00" level=info msg="127.0.0.1 - - [07/Nov/2018:23:38:01 +0100] \"GET /api/campaigns/summary?api_key=e9e642eb0149772c4e85881d01c0c52a6d2c939ad9712905cff2e3e14acda5e7&{} HTTP/2.0\" 200 950 \"https://127.0.0.1:3333/campaigns\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0\""
time="2018-11-07T23:38:02+01:00" level=warning msg="Max connection attempts exceeded - 535 5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials h16-v6sm2185092wrb.73 - gsmtp"
time="2018-11-07T23:38:03+01:00" level=info msg="127.0.0.1 - - [07/Nov/2018:23:38:03 +0100] \"GET /campaigns/8 HTTP/2.0\" 200 2090 \"https://127.0.0.1:3333/campaigns\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0\""
time="2018-11-07T23:38:04+01:00" level=info msg="127.0.0.1 - - [07/Nov/2018:23:38:04 +0100] \"GET /api/campaigns/8/results?api_key=e9e642eb0149772c4e85881d01c0c52a6d2c939ad9712905cff2e3e14acda5e7&{} HTTP/2.0\" 200 961 \"https://127.0.0.1:3333/campaigns/8\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0\""
time="2018-11-07T23:38:04+01:00" level=info msg="127.0.0.1 - - [07/Nov/2018:23:38:04 +0100] \"GET /docs-assets/ico/favicon.png HTTP/2.0\" 404 19 \"\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0\""
time="2018-11-07T23:38:13+01:00" level=info msg="Deleting campaign" campaign_id=8
time="2018-11-07T23:38:13+01:00" level=info msg="127.0.0.1 - - [07/Nov/2018:23:38:13 +0100] \"DELETE /api/campaigns/8?api_key=e9e642eb0149772c4e85881d01c0c52a6d2c939ad9712905cff2e3e14acda5e7 HTTP/2.0\" 200 84 \"https://127.0.0.1:3333/campaigns/8\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0\""
time="2018-11-07T23:38:15+01:00" level=info msg="127.0.0.1 - - [07/Nov/2018:23:38:15 +0100] \"GET /campaigns HTTP/2.0\" 200 2513 \"https://127.0.0.1:3333/campaigns/8\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0\""
time="2018-11-07T23:38:15+01:00" level=info msg="127.0.0.1 - - [07/Nov/2018:23:38:15 +0100] \"GET /api/campaigns/summary?api_key=e9e642eb0149772c4e85881d01c0c52a6d2c939ad9712905cff2e3e14acda5e7&{} HTTP/2.0\" 200 494 \"https://127.0.0.1:3333/campaigns\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0\""
time="2018-11-07T23:38:16+01:00" level=info msg="127.0.0.1 - - [07/Nov/2018:23:38:16 +0100] \"GET /docs-assets/ico/favicon.png HTTP/2.0\" 404 19 \"\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0\""
time="2018-11-07T23:38:17+01:00" level=info msg="127.0.0.1 - - [07/Nov/2018:23:38:17 +0100] \"GET /campaigns/9 HTTP/2.0\" 200 2095 \"https://127.0.0.1:3333/campaigns\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0\""
time="2018-11-07T23:38:18+01:00" level=info msg="127.0.0.1 - - [07/Nov/2018:23:38:18 +0100] \"GET /docs-assets/ico/favicon.png HTTP/2.0\" 404 19 \"\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0\""
time="2018-11-07T23:38:18+01:00" level=info msg="127.0.0.1 - - [07/Nov/2018:23:38:18 +0100] \"GET /api/campaigns/9/results?api_key=e9e642eb0149772c4e85881d01c0c52a6d2c939ad9712905cff2e3e14acda5e7&{} HTTP/2.0\" 200 963 \"https://127.0.0.1:3333/campaigns/9\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0\""
time="2018-11-07T23:38:23+01:00" level=info msg="Deleting campaign" campaign_id=9
time="2018-11-07T23:38:23+01:00" level=info msg="127.0.0.1 - - [07/Nov/2018:23:38:23 +0100] \"DELETE /api/campaigns/9?api_key=e9e642eb0149772c4e85881d01c0c52a6d2c939ad9712905cff2e3e14acda5e7 HTTP/2.0\" 200 84 \"https://127.0.0.1:3333/campaigns/9\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0\""

this are some oh the last outputs concerning my attempts
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by mcvic1rj** [comment]
The url field in the campaign is the URL that you want to replace the `{{.URL}}` token in the email templates.

If you system is not sending email, that sounds like it might be an issue with the sending profile.

Can you attached screenshots of the campaign creation screen and the sending profile? Remember to censor out anything sensitive

**Comment by albus45** [comment]
here u are.
![screenshot_20181108085834](https://user-images.githubusercontent.com/44852261/48185236-afadaf00-e334-11e8-9dce-32fc58384c03.png)
![screenshot_20181108085627](https://user-images.githubusercontent.com/44852261/48185237-afadaf00-e334-11e8-9176-dedf1d56c077.png)

**Comment by jordan-wright** [comment]
It sounds like your anti-virus is recognizing that Gophish is trying to send emails (which, for malicious software would be fairly common since they may be trying to send spam) and so it’s shutting things down.

You’ll need to whitelist Gophish in your AV to avoid this issue.

**Comment by mcvic1rj** [comment]
As far as what goes in the URL Field, this would be the Domain name or IP address that you use to get to your Gophish server.
Example:
Server Public IP: 123.123.123.123 
DNS: thisismyphishingsite.com (which points to the public IP)

In that box I would put http://thisismyphishingsite.com (or https if you enalbe it)

If you are just testing out gophish on your local machine, you can put something like http://127.0.0.1 in there.

**Comment by albus45** [comment]
so, i should have a personal domain hosted somewhere, ma i right?

**Comment by albus45** [comment]
am* / if so, might u suggest me where to get one?

**Comment by jordan-wright** [comment]
You don’t have to have a domain. You can just use the servers IP address if you want.

I’d encourage you to search for the right domain registrar for you. A quick google search for buying a domain will give tons of recommendations that you can use. I’m afraid this forum is mainly to help with issues specific to Gophish. We assume that, if you’re using a domain, you’ve already purchased it and have set it up to point to your Gophish IP address.

**Comment by albus45** [comment]
thank u for your availability. I now have a domain and a hosting site. how can I set it to point to my gophish ip address? is my gophish ip address the one i find on cmd prompt? perhpas i misunderstood the way this system works, but i thought that, provided a site tipying a proper url in campaign page, gophish itself would give content to that blank site, thanks to the set up landing pages. if it doesn't, what is exctly landing page? 
i'm sorry fot this apparentely silly questions. please, answer me, i feel i'm close to the success

**Comment by jordan-wright** [comment]
@albus45,

Gophish is a web server. This means that when people make web requests to it, it will serve the correct landing page. Everything is done on the local machine. Gophish doesn't actually reach out anywhere to copy landing pages.

> I now have a domain and a hosting site. how can I set it to point to my gophish ip address? is my gophish ip address the one i find on cmd prompt?

You need to get the server's external IP address. It's _possible_ that it's the same one in the command prompt, but it's not a guarantee. Getting the IP address is beyond the scope of the support we can provide, since that's a networking question, not a question about Gophish.

**Comment by jordan-wright** [comment]
Closing this since the issue at this point appears to be outside the scope of the support we provide and there haven't been any updates in nearly a week.
