### ISSUE TITLE
Updating the name of a ran campaign

### ISSUE THREAD

**Issue by jnelson30** [gophish/gophish#1265]
Hi, I created and ran a campaign with the date in the title - 10/18/2018.  I need to change the name of the campaign because it will not pull down a report into goReport because of the "/" which I did not realize.  Can someone tell me how to update the name of the title of the campaign??

**Comment by jordan-wright** [comment]
Hi @jnelson30, thanks for reaching out!

I'm afraid this isn't possible within the Gophish UI. You will need to manually update the database entry to update the name of your campaign. You can refer to #1254 for more information and an example on how to do this.

Sorry there isn't more we can do to help!
