### ISSUE TITLE
TLS handshake error

### ISSUE THREAD

**Issue by filebe777** [gophish/gophish#1274]
root@kali:/opt/goapps/src/github.com/gophish/gophish# ./gophish
time="2018-11-12T10:24:10-09:00" level=warning msg="No contact address has been configured."
time="2018-11-12T10:24:10-09:00" level=warning msg="Please consider adding a contact_address entry in your config.json"
time="2018-11-12T10:24:10-09:00" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
goose: no migrations to run. current version: 20180830215615
time="2018-11-12T10:24:11-09:00" level=info msg="Starting admin server at https://127.0.0.1:3333"
time="2018-11-12T10:24:11-09:00" level=info msg="Starting phishing server at http://0.0.0.0:80"
2018/11/12 10:25:27 http: TLS handshake error from 127.0.0.1:54546: tls: first record does not look like a TLS handshake
2018/11/12 10:25:28 http: TLS handshake error from 127.0.0.1:54548: tls: first record does not look like a TLS handshake
2018/11/12 10:25:28 http: TLS handshake error from 127.0.0.1:54550: tls: first record does not look like a TLS handshake

**Comment by filebe777** [comment]
my bad.. it works now

**Comment by azamet90** [comment]
> my bad.. it works now

hi can u help me too pls? i run this command
`openssl req -newkey rsa:2048 -nodes -keyout gophish.key -x509 -days 365 -out gophish.crt`
after i put it in to root folder of gophish and json setup correctly but i still get this error?

how did u set the certificate? thx

**Comment by Thiati** [comment]
time="2024-02-15T03:12:02+01:00" level=warning msg="No contact address has been configured."
time="2024-02-15T03:12:02+01:00" level=warning msg="Please consider adding a contact_address entry in your config.json"
goose: no migrations to run. current version: 20220321133237
time="2024-02-15T03:12:02+01:00" level=info msg="Starting IMAP monitor manager"
time="2024-02-15T03:12:02+01:00" level=info msg="Starting phishing server at http://0.0.0.0:80"
time="2024-02-15T03:12:02+01:00" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
time="2024-02-15T03:12:02+01:00" level=info msg="Starting admin server at https://127.0.0.1:3333"
time="2024-02-15T03:12:02+01:00" level=info msg="Starting new IMAP monitor for user admin"

I need help,I can't find the password
