### ISSUE TITLE
website

### ISSUE THREAD

**Issue by juniorzee** [gophish/gophish#1279]
how do i host my gophish on a different platform and give it a domain name as website? cause anytime i close my gophish.exe and open later i have to start all over again. i want to make my gophish a website i can visit anytime whereby my saved stuffs are intact

**Comment by orangemacaroon** [comment]
you can install your goPhish on VPS

**Comment by jordan-wright** [comment]
Hi @juniorzee,

As @orangemacaroon mentioned, you will need to install and run Gophish on a server that you own, so that the Gophish process isn't closed.

I hope this helps!
