### ISSUE TITLE
Phishing status not updated on dashboard when simulating from domain

### ISSUE THREAD

**Issue by atheriqbal** [gophish/gophish#1280]
Hi, 

We have launched a campaign and emails are successfully sent. For testing purpose, we are using gmail address to send emails. Gophish is running on server www.domain.com:3333.

When campaign is launched, we give the URL as 'http://www.domain.com:8081' (phishing server's port is 8081).  Upon receiving the email, dial for email sent is correctly updated. But nothing else gets updated when link is clicked. 

Link in gmail has this format -> http://www.domain.com:8081/?rid=IIZw4EK
We just get the error 'The connection has timed out'. 

Config file is as follows:

```html

	"admin_server": {
		"listen_url": "0.0.0.0:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "gophish_admin.key"
	},
	"phish_server": {
		"listen_url": "0.0.0.0:8081",
		"use_tls": false,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": "",
    "moodle_address": "https://www.domain.com"

````
Any help would be appreciated. 
Thanks

**Comment by atheriqbal** [comment]
Just an after thought, maybe I need to open port 8081 on my server.

**Comment by orangemacaroon** [comment]
what is this for: moodle_address": "https://www.domain.com?

**Comment by atheriqbal** [comment]
Moodle is deployed on the same server, so it's a button in gophish menu redirecting to Moodle admin page.

**Comment by orangemacaroon** [comment]
ahh just search it is a learning platform? https://moodle.org/

**Comment by atheriqbal** [comment]
Yes. Has no connection with the issue I'm having though

**Comment by orangemacaroon** [comment]
@atheriqbal can you assist me on #1277

**Comment by atheriqbal** [comment]
So should I give the IP in the URL ?

**Comment by orangemacaroon** [comment]
challenge is if IP will be use it is obvious as phishing.. it defeats the purpose of internal social engineering.. just my thought.

**Comment by jordan-wright** [comment]
Hi @atheriqbal,

Take a look at the documentation I just posted [here](https://docs.getgophish.com/user-guide/faq#events-arent-showing-up-on-the-dashboard) and let me know if it helps track down the problem. Yes, you will need to make sure the port is open on the server.

Thanks!

**Comment by atheriqbal** [comment]
All steps in the documentation are followed. Let me open the port and get back to you all.

**Comment by atheriqbal** [comment]
Opening the port resolved the issue as I suspected. 
I had to run the phishing server on a different port because Moodle was running on 80.
Maybe this scenario could be of help to any user. 

Thanks @jordan-wright  and @orangemacaroon .
