### ISSUE TITLE
Timeline for users not working after link is opened

### ISSUE THREAD

**Issue by bardurc** [gophish/gophish#1282]
Timeline for each user disappears as soon as they have clicked the link. It shows everything up until the email is opened. If the user clicks on the link, the timeline disappears and the console reads "Uncaught ReferenceError: UAParser is not defined".

Screenshot from Timeline section up until email has been opened:

![timeline-before-link-clicked](https://user-images.githubusercontent.com/17271185/48650885-28c19c00-e9f0-11e8-8f0f-7d59df403c28.png)

As soon as the link is opened, the timeline disappears.

Screenshot from console in developer tool after link is clicked:

![uaparser-is-not-defined](https://user-images.githubusercontent.com/17271185/48650904-42fb7a00-e9f0-11e8-83d5-daf2b4d2530f.png)

Gophish version: 0.7.1 (Docker)
OS: Ubuntu 18.04
Browser: Chromium 70

Update:
After stopping docker container and starting it again, it works?! No idea why.

**Comment by jordan-wright** [comment]
Hi @bardurc,

Thanks for reaching out- glad you were able to get this resolved!

This to me looks like an old JS file was being used. It’s possible restarting the container caused the new one to be used instead.
