### ISSUE TITLE
about Email Reported

### ISSUE THREAD

**Issue by Imanfeng** [gophish/gophish#1283]
hi We really like this project！

I would like to ask what is the Email Reported role of this module?...

![2018-11-17 2 25 43](https://user-images.githubusercontent.com/24694387/48657976-13428580-ea75-11e8-9b2b-59f4fa5d889e.png)

We want to change the point of this display to another functional result display. I don't know if it will affect the overall operation.

Thank you very much, look forward to your reply.

**Comment by jordan-wright** [comment]
Hi there,

Please see [our documentation](https://docs.getgophish.com/user-guide/documentation/email-reporting) which explains the purpose behind email reporting.

Thanks!
