### ISSUE TITLE
 ERROR: server IP address could not be found. DNS_PROBE_FINISHED_NXDOMAI

### ISSUE THREAD

**Issue by gatmon** [gophish/gophish#1289]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
V.0.7.0
Brief description of the issue: 
When I click on the phished link I receive the following:
 server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIn

What are you expecting to see happen? :
To be taken to the landing pave 

What are you seeing happen?
server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIn

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - I have basically used https://ninja.style/post/deploygophish/* with the exception of the postfix install. I am on Digital Ocean and have tried various domains, various OS's (Ubuntu, Debian) I still receive the same error. From googling, the guidance is to flush DNS and make sure to add google servers as DNS. Pretty much have done all the solutions provided on google but no success. Any help will be appreciated!

**Comment by jordan-wright** [comment]
Hi @gatmon,

You need to be sure that whatever URL you use when building a campaign resolves to the Gophish IP address. In this case, whatever you're using as the URL isn't a valid hostname.

You can find more information on how to troubleshoot this step-by-step in the "Check the Campaign URL" section of our [our FAQ](https://docs.getgophish.com/user-guide/faq#events-arent-showing-up-on-the-dashboard).

I hope this helps!
