### ISSUE TITLE
Campaign External URL

### ISSUE THREAD

**Issue by orangemacaroon** [gophish/gophish#1290]
I created a campaigns and used URL=http//x.x.x.x (public IP of my gophish server hosted on digital ocean).

My issues/concerns are:

When I click the URL it got redirected to http://x.x.x.x (public IP of gosphish). Should it be the https://website.com (website i purchased).

The website is hosted in NameCheap I added DNS A record of my gophish public IP. Is this correct? I also change the name server of namecheap and use the digital ocean. 

(Once i complete this and work I plan to create a document and share).

**Comment by jordan-wright** [comment]
Hi @orangemacaroon,

The domain you purchased should have a DNS A record that points to your Digital Ocean droplet's public IP address.

Then, when creating a campaign, you should put `http://website.com` as the URL. Only put `https://` if you have Gophish configured to use TLS for your phishing server.

More information on how to verify that your URL is correct can be found under the "Check the Campaign URL" section of [our FAQ](https://docs.getgophish.com/user-guide/faq#events-arent-showing-up-on-the-dashboard).

I hope this helps!
