### ISSUE TITLE
Only email sent is being reported rest (Email clicked, link) are not being tracked

### ISSUE THREAD

**Issue by GauthamB123** [gophish/gophish#1295]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  0.7.1

Brief description of the issue: Email Sent is being reported but rest are not being triggered when the link is clicked and credentials submitted. I have hosted a sample html page with a form for the users to enter their credentials on CENTOS. I have hosted gophish on the same CENTOS box. I have used same URL in the email template and in the Campaign. I also see the RID when I click on the link.

What are you expecting to see happen? : I am expecting to see link clicked, submitted get triggered

What are you seeing happen? only email sent is being reported

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

EMAIL TEMPLATE:

![image](https://user-images.githubusercontent.com/45346464/48992140-72e21480-f18a-11e8-8034-b3f537c8419f.png)

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by GauthamB123** [comment]
@jordan-wright Can I get a response please?

**Comment by jordan-wright** [comment]
Hi @GauthamB123,

Please understand that support on this forum is 100% a volunteer effort. I respond to issues as quickly as my time allows, but asking for an update 3 hours after your issue was opened is unreasonable.

That said, please confirm you’ve read through our FAQ, specifically [the section](https://docs.getgophish.com/user-guide/faq#events-arent-showing-up-on-the-dashboard) that discusses how to troubleshoot this exact issue. If this isn’t working, please indicate the exact step where the documentation differs from what you’re seeing and we can continue troubleshooting.

**Comment by GauthamB123** [comment]
Hey @jordan-wright thanks for getting back to me. I wasn't actually expecting a response immediately it is just that I tagged you to let you know that I raised something. Was more of a question/request

I did go through this section however I will double check again and come back.

**Comment by GauthamB123** [comment]
So we have gophish hosted in AWS has both private IP and elastic IP associated with it. I went throught the section it says "use external IP" however our the domain name to the internal IP and that IP is reachable by all the users. Just checking is it mandatory to mention external IP in the campaign URL or make sure our domain name resolves to external IP?

**Comment by jordan-wright** [comment]
Hi @GauthamB123,

No, it's not mandatory to use the external IP. I put that there to help potentially new users who otherwise wouldn't know which IP to use.

The important thing is that whatever URL you use in a campaign (be it a domain name that points to an IP or the IP itself) is reachable by all the recipients. This is simply because we use that URL in the email links so they need to be able to click on it 😄 

I hope this helps! Let me know if you continue to run into issues, and I'd be happy to re-open this so we can continue troubleshooting.

PS:
> I wasn't actually expecting a response immediately it is just that I tagged you to let you know that I raised something

My apologies for the initial response. I've had issues in the past where unreasonable expectations were being set so I misinterpreted this one. In the future, know that for any new issue or new comment, I automatically get an email.

Thanks again for reaching out!

**Comment by GauthamB123** [comment]
Thanks Jordan. I am hosting a sample HTML webpage and gophish on the same EC2. Also, yeah the private IP is reachable by the recipients. I put the http://x.x.x.x in the campaign that points to gophish listener URL. I used the {{.URL}} tag in the email template.  but still dont see the email link triggered. I get the unique rid though.

**Comment by jordan-wright** [comment]
> I am hosting a sample HTML webpage and gophish on the same EC2

To make sure we're on the same page, is this HTML webpage being hosted by something other than Gophish?

Landing pages are hosted by Gophish- that's how it receives campaign events. Hosting the HTML on a different page is not supported at this time.

**Comment by GauthamB123** [comment]
The html webpage is hosted on EC2 instance and has DNS resolution and accessible when entered in URL bar. and gophish is also installed on the same instance. When creating a landing page in gophish, I imported the website. I didn't manually create a landing page in gophish.

**Comment by jordan-wright** [comment]
I’m afraid this still won’t work.

Gophish requires landing pages to be served from itself. You will need to import the existing landing page, save it, and use that when building a campaign. You will also need to point the campaign URL to the IP and port of Gophish,  not the other web server.

**Comment by GauthamB123** [comment]
> I’m afraid this still won’t work. Gophish requires landing pages to be served from itself. You will need to import the existing landing page, save it, and use that when building a campaign. You will also need to point the campaign URL to the IP and port of Gophish, not the other web server.
> […](#)
> On Dec 1, 2018, at 4:30 AM, GauthamB123 ***@***.***> wrote: The html webpage is hosted on EC2 instance and has DNS resolution and accessible when entered in URL bar. and gophish is also installed on the same instance. When creating a landing page in gophish, I imported the website. I didn't manually create a landing page in gophish. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.

-->Yes landing page is on the machine where gophish is installed. 
1. Are you saying we can't import the site to create a landing page?
2. Or you mean we need to create the landing page in the gophish portal itself ? 
Please could you clarify?

**Comment by GauthamB123** [comment]
This is the landing page I created and imported in Gophish landing page section.

<html><head>
    <link rel="stylesheet" type="text/css" href="style.css">
<script type="text/javascript">
    function Alert()
    {
    var x = window.open("http://www.starsgroup.com/press-center/the-stars-group-news/the-stars-group-enters-into-agreements-to-increase-ownership-in-crownbet-and-acquire-william-hill-australia")
    }
</script>

</head>
    <body>
    <div class="login-box">
      <div style="max-height: 50px;">
                <div>
                        <h1>Microsoft</h1>
                        <img src="http://gophi.betdev.com.au/microsoftlogo.png" class="img">
                </div>
          </div>
      <form action="/index.html" method="POST">
             <p>
                          <label>Sign in</label>
                          <input class="" name="login" type="text" placeholder="Email, Phone, or Skype"></p>
                          <p>
                         <input class="" name="password" type="password" placeholder="Enter Password"></p>
                         <p>
            <input type="submit" value="Login" onclick="Alert()">
            <br/>
                        <br/>
                        <a href="#"><u>Forget Password?</u></a>
      </form>
        </div>
</body></html>

**Comment by GauthamB123** [comment]
Hey @GauthamB123 I got it working. Thank you.
