### ISSUE TITLE
GoPhish IP or Domain Name

### ISSUE THREAD

**Issue by orangemacaroon** [gophish/gophish#1296]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 1.8

Brief description of the issue: Setup of GoPhish hosted in Digital Ocean and Website is from NameCheap

What are you expecting to see happen? : When I hover the mouse on URL in the email it shows the domain of Digital Ocean Go Phish, When I click the URL and fill the username and password it will reflect on GoPhish campaign page. 

What are you seeing happen? IP address when hover, when I click the URL it goes straight to landing page (website hosted in NameCheap).

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 - 
 
 
Current Setup and Tshoot:
Digital Ocean - installed and host the GoPhish Server
NameCHeap - installed and host the Landing Page
Email Template - There is a link goes to Copied Landing Page
Landing Page - Redirect traffic/URL in email to domain bought in NameCheap
Campaigns - URL is http://Public_IP_Digital_Ocean

Concerns/Questions:
-How can I make the URL as Name instead of IP?
-On Digital Ocean, should i create a Domain different name on my website in Digital Ocean? Example: NameCheap Domain: school.com, Digital Ocean domain should doschool.com
-What changes should i made to Digital Ocean?
-What changes should i made to NameCheap?

I read that I must add a DNS A in NameCheap record that points to Digital Ocean Public IP. I am having hard time also on testing as every time i made changes i need to wait 24hrs before it reflect. 

Thank you so much for helping...

**Comment by orangemacaroon** [comment]
@jordan-wright  -just to confirm:
1. will configure Digital Ocean, create a domain, add A record and direct to public IP of GoPhish?
2. configure NameCheap, change the nameServers and point to Digital Ocean?

**Comment by jordan-wright** [comment]
That sounds correct to me.

**Comment by orangemacaroon** [comment]
thanks for quick response. I have website hosted in NameCheap... should the domain that I will create in goPhish be the same in NameCheap?

**Comment by jordan-wright** [comment]
No, whatever website you have hosted in namecheap likely won't be compatible with Gophish.

Gophish expects to serve the landing page itself. That's why you're pointing your domain to it's IP address. The only way you can have the user hit something on NameCheap will be to set it as the redirect URL in your landing page. But even then, it will only be hit if the user first hits Gophish, then submits data via a form.

All in all, the best course of action is to assume that everything needs to go through Gophish and is self-contained.

**Comment by orangemacaroon** [comment]
the website is not accessible now.. 

*Not real website and IP but same setup

Website is www.homeschool.com in NameCheap
the domain is homeschool.com hosted in NameCheap
IP address is 1.1.1.1

Digital Ocean that hosted the GoPhish
IP address is 2.2.2.2

-Digital Ocean, I added domain homeshool.com
-In Digital Ocean, added CNAME www.homeschool.com and A outlook.com direct to 2.2.2.2
-NameCheap, Add NameServer CustomDNS added ns1.digitalocean.com, ns2.digitalocean.com and ns3.digitalocean.com

**Comment by jordan-wright** [comment]
> IP address is 1.1.1.1

Where is this coming from? If this isn't related to the Gophish server, it won't be useful here.

> A outlook.com direct to 2.2.2.2

This should be an A record for homeschool.com -> 2.2.2.2.

So essentially, you should _start_ by just doing the A record and following the steps in our FAQ to verify that you can reach the domain and get a "404 page not found" error, as well as seeing the connection in the Gophish terminal. If that works, then you'll know DNS is set up correctly. Then you can add the CNAME and try the same thing for the www.* domain.

**Comment by orangemacaroon** [comment]
1.1.1.1 is the IP address that server host of NameCheap and IP associated on website.

yup I addedd A record homeschool.com 2.2.2.2

The problem is when i browse homeshool.com this site can't be reached.

**Comment by jordan-wright** [comment]
@orangemacaroon you will need to provide more information when explaining the issues you're running into.

When you say "this site can't be reached", that's a good opportunity to provide a screenshot which shows the URL you're going to. I can't see your screen, so I can only troubleshoot based on the information you provide.

> 1.1.1.1 is the IP address that server host of NameCheap and IP associated on website.

I still don't know where this is coming from. There is no way for Gophish to use any website hosted on Namecheap, other than setting it as the redirect URL which does not sound like what you're trying to do.

**Comment by jordan-wright** [comment]
Hi @orangemacaroon,

It seems you’ve posted a follow-up question to this in #1308, so I guess we’ll work through that issue and I’ll close this one out.

**Comment by orangemacaroon** [comment]
Yup Jordan this can be closed just finishing stuff and will write up on my blog the step by step.

**Comment by tarzan538** [comment]
Hi,

I am not a big technical person and would like your input in my setup;
 1. LAN PC running Gophish "1.1.1.1"
2.  Hosting account with new domain and DNS A record pointing to my public facing gateway IP (this is the gateway for 1.1.1.1)
3. Firewall rule to redirect traffic from Public facing IP gateway to 1.1.1.1
4. Then config.json;
{
	"admin_server": {
		"listen_url": "127.0.0.1:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "gophish_admin.key"
	},
	"phish_server": {
		"listen_url": "http://domainname.com:80",
		"use_tls": false,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": "",
	"logging": {
		"filename": ""
	}
}

Question: Is there is something I am missing as I cannot make this work?

**Comment by suriyagk** [comment]
I installed Gophish on Kali Linux and make it reachable by a static IP
And I have a domain in Godaddy, I created A Record that points to my IP and how to add my domain in Gophish server.
Now I am running campaigns the landing page is working properly outside the network but inside the network it is unreachable. 
How I add Gophish port in my Domain and I am not able to get the Emails Reported, how I solve this issue.
If anyone Knows, Please make a reply
