### ISSUE TITLE
Landing Page URL Issue - This site can't be reached

### ISSUE THREAD

**Issue by anarey3117** [gophish/gophish#1297]
What version of Gophish are you using?: 0.7.1

Brief description of the issue: When loading the phishing email, the site always comes up as "This site can't be reached" and that "IP HERE refused to connect". Regardless of what domain I put in here (yes, the DNS settings of the domains already point to my phishing server) it doesn't load. Even if I type in http://*IP of server here*, that still doesn't work.

What are you expecting to see happen? : For the landing pages to show and have my custom domain name.

What are you seeing happen? A Site can't be reached - ERR_CONNECTION_REFUSED message in Chrome.

My config.json file if it helps:

```{
        "admin_server": {
                "listen_url": "0.0.0.0:3333",
                "use_tls": true,
                "cert_path": "gophish_admin.crt",
                "key_path": "gophish_admin.key"
        },
        "phish_server": {
                "listen_url": "0.0.0.0:443",
                "use_tls": false,
                "cert_path": "hmrc.crt",
                "key_path": "hmrc.key"
        },
        "db_name": "sqlite3",
        "db_path": "gophish.db",
        "migrations_prefix": "db/db_",
        "contact_address": "",
        "logging": {
                "filename": ""
        }
}
```

Thanks in advance,

**Comment by jordan-wright** [comment]
Hi @anarey3117 ,

Your config.json has conflicting information. You're setting the port to 443, which is normal for TLS connections, but then you set `use_tls` to false.

If you're trying to have connections go over HTTPS, you'll need to set `use_tls` to `true`. Then, try `https://your_ip`.
