### ISSUE TITLE
Variable for Unique target rid

### ISSUE THREAD

**Issue by Tw1sm** [gophish/gophish#1299]
What version of Gophish are you using?: 
0.6.0 (Need to upgrade 0.7.1 when I have the time, and it looks like that has half of what I'm looking for)

Brief description of the issue: 
This is a feature request: I'd like to be able to use a variable (e.g., {{.rid}}) to separate out the base url (which it looks like has been added as a variable in 0.7.1) and the rid related to each target's specific url.

The reason for this is to attempt to bypass some link checking using a method such as setting the base url ```<base href="https://mydomain.com/">``` and then setting the hyperlink to go directly to the rid ```<a href="?rid=xxxxx">Click here</a>``` Looks like setting the base url is possible now, but it would be great if we could set the link to the rid using ```href="?rid={{.rid}"```

Thanks!

**Comment by jordan-wright** [comment]
Can you explain a bit more what you’re looking to do? I’m afraid it’s still not clear what problem you’re aiming to solve. Any examples you can provide would be really helpful.

**Comment by Tw1sm** [comment]
Oops, forgot to tickmark code example in the original post - edited so now the example actually shows.

My understanding of how Gophish's tracking works is that each email recipient gets a unique rid assigned to them, and the rid value becomes part of the {{.URL}} variable we for hyperlinks in the email template. I'd like to be able to access the rid value through a variable (i.e. {{.rid}}) so that the {{.URL}} value can be created through combining the {{.BaseURL}} and {{.rid}} values.

The idea would be have an email template like this:
```
<html>
<head>
	<title></title>
        <base href="https://mydomain.com/">
</head>
<body>
<p>
<span>My email body</span><br />
<br />
<a href="{{.rid}}">Click this link!</a><br />
<br />
<br />
Sincerely,<br />
<br />
Sender</p>

<p>{{.Tracker}}</p>
</body>
</html>
```

Doing it this way, the full link to a landing page is not in a singular href value.

**Comment by jordan-wright** [comment]
Hi @Tw1sm,

It sounds like you're just looking for the `{{.RId}}` variable, which has been a [valid template variable](https://docs.getgophish.com/user-guide/template-reference) for a while (I think 😄).

If I'm missing something and you're looking for something else, please let me know and I'll be happy to re-open this issue.
