### ISSUE TITLE
Compagne Config

### ISSUE THREAD

**Issue by Hemza** [gophish/gophish#130]
Dear developperes 

can any one give me and exemple of a real config that works on gophish, ex: smtp server , email...
because i've tried to configure gophish but it didn't work,
could you send me a config manuel

Regards

**Comment by rfdevere** [comment]
Setup a gmail.

1.) smtp.gmail.com:25
2.) email address as user
3.) password

You might have to select 'allow insecure older apps' as its on tcp:25

**Comment by jordan-wright** [comment]
Thanks @rfdevere!

@Hemza, also, just make sure to specify a "From" address. That should be all you need. You can reference the [User Guide](https://getgophish.com/documentation/Gophish%20User%20Guide.pdf) for a complete example.
