### ISSUE TITLE
cant track email open and link click

### ISSUE THREAD

**Issue by hudabasloom** [gophish/gophish#1303]
I had problem cant track email open and email link 
I try to read other pepol experiance but it did not work 

here is my configuration 
{
	"admin_server": {
		"listen_url": "0.0.0.0:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "gophish_admin.key"
	},
	"phish_server": {
		"listen_url": "0.0.0.0:443",
		"use_tls": true,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": ""
}
----------------------\

the email as follw:

```
http://www.ihomestore.com/Account/Register
{{.Tracker}}
<p><img src="https://www.3orods.com/wp-content/uploads/2017/12/image-1-33.jpg"/></p>
```

**Comment by jordan-wright** [comment]
Hi @hudabasloom,

Please refer to our [FAQ](https://docs.getgophish.com/user-guide/faq#events-arent-showing-up-on-the-dashboard) for information on how to troubleshoot this.

If you still run into issues, please let us know exactly what you tried, which step in that FAQ failed, and what you're seeing occur.
