### ISSUE TITLE
Mail header : ESMTPS

### ISSUE THREAD

**Issue by dyneko** [gophish/gophish#1304]
Hi,

I use postfix as server to send mail, I made the test with lucy and gophish and swordphish.
The strange thing is that only, gophish use ESMTPS, the other use ESMTP.
I try to find out on the gophish/gomail library, but I found nothing.
I guess you can help me? 

Thank you

**Comment by jordan-wright** [comment]
Gophish uses opportunistic TLS. If it's advertised by the SMTP server, Gophish will use it. This is done through the `smtp.Client` set up in our [`gomail` library](https://github.com/gophish/gomail/blob/cf7e1a5479be7fad1ae12b2fc574f5287f4ec712/smtp.go#L81).

If you wanted to change this, you'd need to fork the mail library, edit out that section, and update Gophish to use your version of the mail library. This isn't something we offer natively in Gophish.

I hope this helps!
