### ISSUE TITLE
Installing SSL certificate on gophish running on AWS windows 2016 server

### ISSUE THREAD

**Issue by KrishanKanagarajah** [gophish/gophish#1310]
Looking for assistance in Installing SSL certificate on gophish running on AWS windows 2016 server

I want to make the URL secure. I have already purchased the SSL from Godaddy and I got stuck with the CSR request to set up the certificate. Since there is no web server, I do not know how to get the CSR information. 

Since Gophish is hosting the login page, I reckon the certification need to be installed in the Gophishsite. I have done a google search and found some article but they are not exactly solving my issue or I am lacking some knowledge to understand it.

Thanks for your help in advance.

Krishan

**Comment by horllste** [comment]
Did you have hangout?

**Comment by jordan-wright** [comment]
Hi @KrishanKanagarajah,

I'm afraid generating the SSL certificate is out of scope for the support we provide. You will need to follow the instructions from your certificate authority (Godaddy) on how to generate the CSR and have them sign it.

Once you have the certificate and private key, you can add them to the Gophish configuration as shown in the last step [in our documentation](https://docs.getgophish.com/user-guide/installation#creating-ssl-certificate-and-private-keys).

I hope this helps!

**Comment by KrishanKanagarajah** [comment]
Hi Jordan, 

Thanks for the reply. However, those instruction in your document for the SSL are only for the gophish application itself, not for the site hosted in Gophish (i mean the landing page) and they are applicable for Ubuntu (if I am not mistaken).

As I said, I am running in Windows flat form and where I could able to get the CSR information from gophish? Hope my question is with your support preview.

Krishan

**Comment by KrishanKanagarajah** [comment]
> hangout


> Did you have hangout?
Yes. I am.

**Comment by KrishanKanagarajah** [comment]
Update: I have already got a domain and made DNS entry to show the URL rather than the AWS IP address for the landing page.

Apologies for not quoting this information earlier and happy to clarify if i missed any information.

Krishan

**Comment by KrishanKanagarajah** [comment]
I have generated the files( certificates files)  and downloaded the files from Godaddy. Now having trouble using them on Gophish.

**Comment by jordan-wright** [comment]
Please review the documentation I linked to earlier. It explains that you need to provide the full path to the certificate and the private key in the config.json. This is the same on windows.

There is no other configuration needed.

**Comment by KrishanKanagarajah** [comment]
Thanks, Jordan for the reply. I will try them and let you know how it goes.

**Comment by KrishanKanagarajah** [comment]
> offer to guide you through.

Thanks horllste  for the offer. I will try as suggested by Jordan and let you know if any assistance needed.

**Comment by KrishanKanagarajah** [comment]
Update: I have followed the process and managed to get the Private key too.

However, the landing page is still not loading with the https. I think I need to wait for sometime till it gets updated. If not,  should do some DNS setting changes?

Krishan

**Comment by KrishanKanagarajah** [comment]
Result:
![image](https://user-images.githubusercontent.com/17286421/49568042-d129a700-f983-11e8-9525-21e53db65f88.png)
