### ISSUE TITLE
Where are the campaign results that are exported?

### ISSUE THREAD

**Issue by myarboro5886** [gophish/gophish#1315]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 03

Brief description of the issue: Where are campaign results downloaded?

What are you expecting to see happen? :  download option to local machine

What are you seeing happen? nothing

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
What browser are you using?

**Comment by myarboro5886** [comment]
Safari

-------------------------------------------------
--Martin

Martin Yarborough and Associates LLC
8451 Deerwood Forest Drive
Fort Worth, TX  76126

O(817)952-9993
M(817)408-5725
F(817)887-3371

https://www.martinyarborough.com

**Comment by jordan-wright** [comment]
You're not stupid! This is an [open bug](https://github.com/gophish/gophish/issues/250) that I have yet to track down. There's no way you could have known that.

Since we're tracking this bug in #260, I'm going to go ahead and close this one out. Thanks for getting in touch!
