### ISSUE TITLE
Email recipients

### ISSUE THREAD

**Issue by orangemacaroon** [gophish/gophish#1316]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: current

Brief description of the issue: 

What are you expecting to see happen? : I am sending multiple bulk email and wanting to add the first name on email template. i tried to add "[[first_name]]," after the initial greetings but it dont worked.

What are you seeing happen? Hi [[first_name]],
Should be Hi Jose, 

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```
[[first_name]],

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by S0larflare** [comment]
You need {{.FirstName}}

It might be worth checking that in the documentation, but it is something very similar to that if not exactly that

Sent from my iPhone

On 6 Dec 2018, at 21:05, orangemacaroon <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for reaching out! We're happy to help resolve issues as quickly as possible.

Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our documentation<https://getgophish.com/documentation/>, which covers how to use Gophish.

What version of Gophish are you using?: current

Brief description of the issue:

What are you expecting to see happen? : I am sending multiple bulk email and wanting to add the first name on email template. i tried to add "[[first_name]]," after the initial greetings but it dont worked.

What are you seeing happen? Hi [[first_name]],
Should be Hi Jose,

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

Insert code here

[[first_name]],

Please provide any terminal output that may be relevant below:

Insert output here


Please provide as many steps as you can to reproduce the problem:

  *   Step 1 -
  *   Step 2 -

**Comment by jordan-wright** [comment]
Yes, you can find all the template variables in our documentation: https://docs.getgophish.com/user-guide/template-reference
