### ISSUE TITLE
gophish tracking not work with me

### ISSUE THREAD

**Issue by hudabasloom** [gophish/gophish#1319]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

What version of Gophish are you using?: 
current version 0.7.1 
I use EXE not code version

Brief description of the issue: 
Send email work but track email and open not work 
I try and read  multiple subject but cant find solution
What are you expecting to see happen? :
no of email opende and link click

What are you seeing happen?
nothing just mail sent 

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:
<html>
<head>
	<title></title>
</head>
{{.FirstName}}

{{.URL}}

<p><img src="http://alzheimer.ca/sites/default/files/images/chapters-on/bhq/fundraising/hootie.jpg"/></p><body>
{{.Tracker}}</body>
</html>

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by hudabasloom** [comment]
_**Tip: Remember that the campaign URL must be reachable by the recipients clicking the links. If they can't reach the Gophish server, Gophish can't record those events.**_

i choose any link from the internet like:
https://mawdoo3.com/

**Comment by hudabasloom** [comment]
Is there something missing in template or landing page

I removed every thing in landing page except Hello

in the template I put
{{.Tracker}}  and {{.URL}}

**Comment by jordan-wright** [comment]
> i choose any link from the internet like:

No, the URL used in your campaign must point to your Gophish server. From the FAQ:

When creating a campaign, the URL field **must point to the server running Gophish and must be reachable by the person opening the emails.** This can either be the external IP address of the server, or a domain name that has a DNS A record pointing to the server's IP address.

Please follow the steps provided in the FAQ which show how to troubleshoot this and let us know which step you encounter issues with so we can continue troubleshooting.

Thanks!

**Comment by hudabasloom** [comment]
I try yesterday to add the same server in the URL 
still no any response

Is there any configuration in config file??

**Comment by dehinde007** [comment]
> 

Hello Jordan, so for trackers to work, gophish must be hosted publicly i.e VPS and then give the IP of this VPS in the URL field when launching your campaign?
