### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by orangemacaroon** [gophish/gophish#1320]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: current

Brief description of the issue: installation failed

What are you expecting to see happen? : successful installation

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

Error msg:

root@s:xxx# ./gophish
time="2018-12-12T13:21:25-07:00" level=info msg="Background Worker Started Succssfully - Waiting for Campaigns"
time="2018-12-12T13:21:25-07:00" level=warning msg="No contact address has beenconfigured."
time="2018-12-12T13:21:25-07:00" level=warning msg="Please consider adding a contact_address entry in your config.json"
goose: no migrations to run. current version: 20180830215615
time="2018-12-12T13:21:25-07:00" level=info msg="Starting phishing server at http://0.0.0.0:80"
time="2018-12-12T13:21:25-07:00" level=fatal msg="listen tcp 0.0.0.0:80: listen:address already in use"
root@s:xxx# 
```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by S0larflare** [comment]
Something is already running on port 80. Change the port or stop whatever is running already

Sent from my iPhone

On 12 Dec 2018, at 20:50, orangemacaroon <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for reaching out! We're happy to help resolve issues as quickly as possible.

Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our documentation<https://getgophish.com/documentation/>, which covers how to use Gophish.

What version of Gophish are you using?: current

Brief description of the issue: installation failed

What are you expecting to see happen? : successful installation

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

Insert code here

Please provide any terminal output that may be relevant below:

Error msg:

root@s:xxx# ./gophish
time="2018-12-12T13:21:25-07:00" level=info msg="Background Worker Started Succssfully - Waiting for Campaigns"
time="2018-12-12T13:21:25-07:00" level=warning msg="No contact address has beenconfigured."
time="2018-12-12T13:21:25-07:00" level=warning msg="Please consider adding a contact_address entry in your config.json"
goose: no migrations to run. current version: 20180830215615
time="2018-12-12T13:21:25-07:00" level=info msg="Starting phishing server at http://0.0.0.0:80"
time="2018-12-12T13:21:25-07:00" level=fatal msg="listen tcp 0.0.0.0:80: listen:address already in use"
root@s:xxx#

Insert output here


Please provide as many steps as you can to reproduce the problem:

  *   Step 1 -
  *   Step 2 -

**Comment by orangemacaroon** [comment]
hosted on go daddy.. not sure where is the service that uses port 80.. 

if i will change on json file the port 80, does it have impact?

**Comment by S0larflare** [comment]
Something like netstat -tulpn | grep 80 should show what is using the port

Sent from my iPhone

On 12 Dec 2018, at 20:54, orangemacaroon <notifications@github.com<mailto:notifications@github.com>> wrote:


hosted on go daddy.. not sure where is the service that uses port 80..

if i will change on json file the port 80, does it have impact?

**Comment by orangemacaroon** [comment]
i just change the port on gophish 80 to something different... it worked. 

any issue here?

**Comment by S0larflare** [comment]
It’s not an issue, you can’t have two different services bound to the same port at the same time. If you go to your ip/host name on port 80 there will likely be a website already hosted on it

Sent from my iPhone

On 12 Dec 2018, at 21:02, orangemacaroon <notifications@github.com<mailto:notifications@github.com>> wrote:


i just change the port on gophish 80 to something different... it worked.

any issue here?

**Comment by jordan-wright** [comment]
@S0larflare, as always, is exactly correct.

To bind Gophish to port 80, you would need to figure out what process is listening on the port already and kill that process. You can change the port Gophish uses, but you would need to specify the new port in your URL when creating campaigns in the future.

**Comment by jordan-wright** [comment]
Hi @orangemacaroon,

This question, like the original one in the issue, has been seen multiple times [in previous issues](https://github.com/gophish/gophish/search?q=attempt+to+write+a+readonly+database&type=Issues). As the issue template suggests, I highly recommend searching for any error messages you encounter before filing a new issue.
