### ISSUE TITLE
Can not get group to update

### ISSUE THREAD

**Issue by GerryOldMan** [gophish/gophish#1322]
What version of Gophish are you using?: 
0.6.0 and gophish python api version 0.2.2

Brief description of the issue: 
When trying to update an existing group using the api I get an error 'AttributeError: 'Group' object has no attribute 'as_json''

I can import the group from the api and then add a new target to the group but when I try and update the group from the api get this error.

Please provide as many steps as you can to reproduce the problem:
```python
from gophish import Gophish
from gophish.models import *
api_key = 'Redacted'
api = Gophish(api_key,host='', verify=False)
apiGroup = api.groups.get(group_id=4) 
api.targets.append(User(first_name='Gerry',last_name='Grant',email='gerry@example.com'))
test = api.groups.put(apiGroup)
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gerrygrant/Phish/phishApi/lib/python2.7/site-packages/gophish/api/groups.py", line 19, in put
    return super(API, self).put(group)
  File "/Users/gerrygrant/Phish/phishApi/lib/python2.7/site-packages/gophish/api/api.py", line 95, in put
    response = self.api.execute("PUT", endpoint, json=resource.as_json())
AttributeError: 'Group' object has no attribute 'as_json'

Any help appreciated.

**Comment by jordan-wright** [comment]
Hi @GerryOldMan!

I’ll see about getting this fixed. Thanks so much for the report!

**Comment by jordan-wright** [comment]
Hi @GerryOldMan,

I've pushed out version 0.2.3 of the API client, which should fix the issue you're encountering. You can install the update with `pip install -U gophish`.

Let me know if you continue to run into issues!
