### ISSUE TITLE
Scan error on column index 2: unsupported Scan, storing driver.Value type []uint8 into type *time.Time

### ISSUE THREAD

**Issue by S0larflare** [gophish/gophish#1331]
What version of Gophish are you using?: Latest source (upgrading from ~0.2)

Brief description of the issue: Something seems to have changed with how datetime is handled in the campaigns table. I'm getting an error which stops campaigns being read on the database (a fresh database that get set up is fine)

What are you expecting to see happen? : Campaigns and the dashboard to be populated

What are you seeing happen? Errors

Please provide any terminal output that may be relevant below:

On the dashboard I get:

```
time="2018-12-28T10:42:19Z" level=error msg="sql: Scan error on column index 2: unsupported Scan, storing driver.Value type []uint8 into type *time.Time; sql: Scan error on column index 2: unsupported Scan, storing driver.Value type []uint8 into type *time.Time; sql: Scan error on column index 2: unsupported Scan, storing driver.Value type []uint8 into type *time.Time; sql: Scan error on column index 2: unsupported Scan, storing driver.Value type []uint8 into type *time.Time; sql: Scan error on column index 2: unsupported Scan, storing driver.Value type []uint8 into type *time.Time; sql: Scan error on column index 2: unsupported Scan, storing driver.Value type []uint8 into type *time.Time; sql: Scan error on column index 2: unsupported Scan, storing driver.Value type []uint8 into type *time.Time; sql: Scan error on column index 2: unsupported Scan, storing driver.Value type []uint8 into type *time.Time; sql: Scan error on column index 2: unsupported Scan, storing driver.Value type []uint8 into type *time.Time; sql: Scan error on column index 2: unsupported Scan, storing driver.Value type []uint8 into type *time.Time; sql: Scan error on column index 2: unsupported Scan, storing driver.Value type []uint8 into type *time.Time; sql: Scan error on column index 2: unsupported Scan, storing driver.Value type []uint8 into type *time.Time; sql: Scan error on column index 2: unsupported Scan, storing driver.Value type []uint8 into type *time.Time; sql: Scan error on column index 2: unsupported Scan, storing driver.Value type []uint8 into type *time.Time; sql: Scan error on column index 2: unsupported Scan, storing driver.Value type []uint8 into type *time.Time; sql: Scan error on column index 2: unsupported Scan, storing driver.Value type []uint8 into type *time.Time; sql: Scan error on column index 2: unsupported Scan, storing driver.Value type []uint8 into type *time.Time; sql: Scan error on column index 2: unsupported Scan, storing driver.Value type []uint8 into type *time.Time; sql: Scan error on column index 2: unsupported Scan, storing driver.Value type []uint8 into type *time.Time; sql: Scan error on column index 2: unsupported Scan, storing driver.Value type []uint8 into type *time.Time; sql: Scan error on column index 2: unsupported Scan, storing driver.Value type []uint8 into type *time.Time; sql: Scan error on column index 2: unsupported Scan, storing driver.Value type []uint8 into type *time.Time"

```

and on the campaigns page I get 

```
time="2018-12-28T10:43:09Z" level=error msg="sql: Scan error on column index 3: unsupported Scan, storing driver.Value type []uint8 into type *time.Time: campaign not found"
```

Now looking at the database I've noticed a difference between my old one and a freshly created one (after running a quick test campaign and completing it):

[new db]
![image](https://user-images.githubusercontent.com/8939757/50513921-e2516980-0a92-11e9-816f-840bcb914fdb.png)

[old db]
![image](https://user-images.githubusercontent.com/8939757/50513929-ff863800-0a92-11e9-8c02-30ec94c591f3.png)

Essentially it seems that new campaigns get created with a different format for the time as it has .01254564 on the end - when did this change? Any ideas on the best way of me fixing this one? I appreciate it is a pretty niche case as it is updating from a very old build, but I'd prefer to be able to keep the database rather than having to start anew.

**Comment by jordan-wright** [comment]
Hey @S0larflare!

Thanks for reaching out. This is definitely the first I’ve heard about this so I appreciate you giving such a detailed description!

I’ll look into this on my side. I don’t _think_ I explicitly changed this anywhere though I’ll need to do some digging.

Are you using MySQL or SQLite?

**Comment by S0larflare** [comment]
Knew I'd forgotten to add something - it's the standard SQLite

**Comment by jordan-wright** [comment]
Awesome, thanks!

Just to give a quick update, I installed a local version of 0.3 (kept getting weird CSRF errors for 0.2 🤷‍♂️) and saw the date format you described:

```
sqlite> select * from campaigns;
1|1|Demo Campaign|2018-12-28 14:33:42.2485637+00:00|0001-01-01 00:00:00+00:00|1|1|In progress|http://localhost|1|2018-12-28 08:33:40.560053-06:00
```

The difference is that after downloading the latest source, I see the migrations run successfully and the dates are automatically updated in the database:

```
sqlite> select * from campaigns;
1|1|Demo Campaign|2018-12-28 14:33:42+00:00|0001-01-01 00:00:00+00:00|1|1|In progress|http://localhost|1|2018-12-28 14:33:40+00:00|
```

I'm then able to load the dashboard without issue.

If you make a copy of your database and run the latest version from source, are the migrations run successfully? Upgrading from 0.3, I saw:

```
OK    20170827141312_0.4_utc_dates.sql
OK    20171027213457_0.4.1_maillogs.sql
OK    20171208201932_0.4.1_next_send_date.sql
OK    20180223101813_0.5.1_user_reporting.sql
OK    20180524203752_0.7.0_result_last_modified.sql
OK    20180527213648_0.7.0_store_email_request.sql
OK    20180830215615_0.7.0_send_by_date.sql
```

If they are run successfully, do you see the dates in the database get updated? I'm just trying to pinpoint where the problem is occurring. And just to give some peace of mind, at the very worst case we can always write a quick script to manually adjust the database values into the right format. We'll work together to make sure you can use your existing database 😄 

(Heads up I'll be off/on throughout the day today, so I may be a bit slow to respond)

**Comment by jordan-wright** [comment]
One more quick update - I'll need to confirm, but it seems like the change may be occurring as part of the transition to UTC datetimes [here.](https://github.com/gophish/gophish/blob/master/db/db_sqlite3/migrations/20170827141312_0.4_utc_dates.sql)

**Comment by S0larflare** [comment]
Yes, all of the migrations run (although it takes quite a long time all in all) but the datetime doesn't get converted in any of the fields. Weirdly though, you seem to have things the opposite way round to me there. It is the _new_ database which has the longer datetime, the _old_ one is the default that is more recognisable?

![image](https://user-images.githubusercontent.com/8939757/50519012-bf35b280-0ab0-11e9-8951-c034f8ec5941.png)

So now I'm even more confused :/

So I just went back and looked at the old database before migrations are run and that has the longer datetime. This might be a weird quirk of copying things over from a database when it comes to sqlite. I think this problem is solely my end to be honest, leave it with me.

**Comment by S0larflare** [comment]
Well copy-paste didn't fix the problem, so it could be outside of the campaign table where the issue is. I'll go back to the start and rerun the upgrade a few times next week to try to narrow down where the problems are coming from.

**Comment by S0larflare** [comment]
OK, so I sorted this - not a gophish problem.

I overestimated SQLite's abilities when copying data (it doesn't copy the schema of a table over). All sorted now :+1:
