### ISSUE TITLE
SMTP Username and Password using Python API

### ISSUE THREAD

**Issue by cyber-jack** [gophish/gophish#1332]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.7.1

Brief description of the issue: Hi all. I've been using the python api and was trying to create a sending profile when I noticed that you cannot set the SMTP username and password through the python api. Is there anything I'm missing ?

I'm using the basic code from the documentation:

from gophish import Gophish
​
api_key = 'API_KEY'
api = Gophish(api_key)
​
smtp = SMTP(name='Test SMTP')
smtp.host = "localhost:25"
smtp.from_address = "John Doe <johndoe@example.com>"
smtp.interface_type = "SMTP"
smtp.ignore_cert_errors = True
​
smtp = api.smtp.post(smtp)
print smtp.id

Thank you

What are you expecting to see happen? : 

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi @cyber-jack,

Thanks for reaching out! You're not missing anything - I am. It looks like the API client doesn't have that implemented. I'll get a fix out pronto.

Thanks again for the heads up!

**Comment by jordan-wright** [comment]
Hi @cyber-jack,

This should be fixed in 0.2.4. A `pip install -U gophish` should get the update for you.

Let me know if you run into any issues!

**Comment by cyber-jack** [comment]
Hi @jordan-wright 

Thank you for the prompt fix! Appreciate it!
