### ISSUE TITLE
RFC: Implementing RBAC 

### ISSUE THREAD

**Issue by jordan-wright** [gophish/gophish#1333]
👋 Hi everyone!

I wanted to get some feedback on a proposal for implementing simple RBAC into Gophish.

To keep things simple, right now each user in Gophish is completely separate, and has all the same permissions. There’s no such thing as roles, or the ability to limit users from doing certain things.

This worked well enough so far. There’s been the [occasional issue filed](https://github.com/gophish/gophish/search?q=rbac&type=Issues) about wanting RBAC (including one from me!), but it’s never given us enough benefit to make it worth the effort compared to other features.

Now that Gophish is getting more mature, I think it’s time to reconsider adding RBAC- at least, to a limited extent. My goal is to start small and simple, only building out when we need to. To start, I want to create three roles:

* Administrator
* User
* Viewer

Here's a little bit about the goals for each role and what we aim to accomplish.

## Administrator Role
Right now, every user is pretty much an administrator. This works fine in smaller teams, but for enterprise users there may be a separation between the team that manages the Gophish infrastructure and the team that launches the phishing simulations.

The Administrator role aims to limit system-level administration to a smaller number of users. To start, this would include:

* User management
* URL management

I have to include URL management since URLs will need to be shared amongst all users due to needing consistent TLS settings.

## User Role
The user role will be able to do everything an administrator can do, with the exception of managing other users or system-wide settings like URLs. They will be able to interact with objects like sending profiles, groups, etc., as well as launching and viewing the campaign output.

## Viewer Role
The viewer role will be a read-only role. Users with this role will not be able to do any kind of system-management, or create/edit any objects. They will only be able to view objects and campaign information.

## I'd love your feedback

This is a simple start, but hopefully it should hopefully take care of quite a few use cases while adding limited complexity. We can always expand this out later, but if anyone has feedback on this initial proposal, I'd love to hear your thoughts!

**Comment by S0larflare** [comment]
This is pretty much exactly as I would want it implimenting. I'd had a look at this a while back and I was considering having a crack at it (as there aren't that many direct mentions of the current user that you'd have to change to allow this to work), but this seems to be more comprehensive than my first attempt was going to be :)

**Comment by MarkJaroski** [comment]
We need this at my organization. We've been running campaigns up to several times per month, and until now just one team member has had access to the tool, but we would like to allow the team lead and others to be able to view data at least, etc.

**Comment by MarkJaroski** [comment]
It had occurred to me that I could sort of achieve this by using a reverse proxy and SAML to simulate multi-user access, basically logging all (3) permitted users in as the same service account, but that's pretty much a cludge. Actually implementing access by multiple users to a given campaign is much much better.

**Comment by jordan-wright** [comment]
Hi everyone!

I wanted to provide an update on where this is at. The most immediate thing to mention is that the roles I'm setting up for this initial release is changing slightly. Specifically, I won't be including a "Viewer" role. This is because right now, Gophish is set up where every object belongs only to the user that created it. This means that a view-only user wouldn't be useful, since there'd be nothing to view!

I am, however, going to continue with the addition of an Administrator Role and a User Role, with the difference being that the Administrator role can manage system-wide objects, such as shared URLs as well as performing user management.

Alluding to @MarkJaroski point, the next step after building this out would be to consider a "team" functionality would look like. I understand that many of you have the use case where you want team members to share objects such as groups and campaigns. This is my plan as well, and architecturally it should fit nicely into the permission framework that I'm building. I'll draft a separate RFC to discuss the ins-and-outs of that feature.

With the minor change in roles aside, I'm happy to say that I'm almost ready to roll this out. I'm making some minor adjustments and trying to test things as exhaustively as possible, but things are looking good!

**Comment by MarkJaroski** [comment]
Hey, that's great @jordan-wright. This will easily bolster our position for the choice of Gophish over commercial options. Thanks so much.

**Comment by MarkJaroski** [comment]
Thanks so much for implementing this!

**Comment by H4xl0r** [comment]
URL management ?
Viewer Role ?

Dont see any implementations here .... its 2019 !

**Comment by jordan-wright** [comment]
I’m not sure what you’re comment is supposed to mean @H4xl0r. Before I respond, I want to make sure I’m understanding you correctly to avoid a miscommunication. 

Are you suggesting that Gophish is missing features that are needed and, even more, expected in 2019?

**Comment by mailnatalie** [comment]
Is RBAC now a feature?  How do I add an additional Administrator.  Does this have to be updated by the UNIX/Linux guys? or can I do it from the app?
![settings](https://user-images.githubusercontent.com/45234110/69806369-ece31a00-119f-11ea-8120-6b0cce051730.PNG)
version 0.7.1

**Comment by jordan-wright** [comment]
Hi there!

You’ll need to make sure you’re running the 0.8.0 release https://github.com/gophish/gophish/releases/tag/v0.8.0

Due to a small bug, it’ll show as 0.7.1, but you’ll want to still make sure that’s the actual binary you’re running since it adds RBAC support.

**Comment by mailnatalie** [comment]
Thank you.  I get our Linux team to do the backend stuff.  I am not familiar.  I will send this to them and see if they can figure it out.

Thanks.

Natalie
(403) 592-8290 ext 81237
[2pawprints]
Be the person that your pets already think you are..

**Comment by mailnatalie** [comment]
Jordan, is there anyway to have GoPhish talk to our LDAP/AD/Gal for the users and groups rather than manually adding the separate lists?


Natalie
(403) 592-8290 ext 81237
[2pawprints]
Be the person that your pets already think you are..

**Comment by jordan-wright** [comment]
There’s not an official way. However there are some community tools like [this one](https://github.com/ILiedAboutCake/DirectoryPhish) from @ILiedAboutCake that seems to solve this problem, though I haven’t taken it for a spin.

**Comment by GigaByteRex** [comment]
This is an awesome update, great job!
Have you drafted the RFC for "team functionality" yet, or is this sort of functionality put on a expected timeline?
Being able to share campaigns and other objects between users is really the only thing missing for me in this RBAC implementation. For now I'm "hacking" it by just creating a new shared account for specific engagements that requires multiple team members, but this is pretty cumbersome with regards to sharing new credentials per engagement.

**Comment by MarkJaroski** [comment]
This has made a big difference for us. Thanks again!
