### ISSUE TITLE
not able to see admin dashboard on ec2 instance public ip but show on localhost of ec2

### ISSUE THREAD

**Issue by pankaj0812** [gophish/gophish#1335]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: v0.2

Brief description of the issue: not able to view my admin server on the ec2 instance public ip

What are you expecting to see happen? : expecting to see admin panel on going to my public ip of ubuntu 16.04 server 

What are you seeing happen?: shows 404 error in html (possibly the phishing server)

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:
2019/01/03 12:53:42 worker.go:36: Background Worker Started Successfully - Waiting for Campaigns
goose: no migrations to run. current version: 20160605210903
 2019/01/03 12:53:42 gophish.go:76: Starting phishing server at http://0.0.0.0:80
 2019/01/03 12:53:42 gophish.go:59: Starting admin server at https://127.0.0.1:3333
127.0.0.1 - - [03/Jan/2019:12:53:45 +0000] "GET /api/campaigns/3/results?api_key=23c9ce779e1d9ec73ab76c5e78cf8408f8b1820f5b37ad319a07d123ba67b4b2&{} HTTP/2.0" 200 390 "https://0.0.0.0:3333/campaigns/3" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0"
^[[2~127.0.0.1 - - [03/Jan/2019:12:53:55 +0000] "GET /api/campaigns/3/results?api_key=23c9ce779e1d9ec73ab76c5e78cf8408f8b1820f5b37ad319a07d123ba67b4b2&{} HTTP/2.0" 200 390 "https://0.0.0.0:3333/campaigns/3" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0"

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by S0larflare** [comment]
> 2019/01/03 12:53:42 gophish.go:59: Starting admin server at https://127.0.0.1:3333

You're only allowing the admin server access to the localhost IP there, it's unlikely to work from the public IP. To do so you'd want to change this line to the public IP or to 0.0.0.0:3333. However, is this something you really want to do? In general exposing admin interfaces to the internet isn't a great idea, you're likely to get a lot of people knocking on your door...

**Comment by pankaj0812** [comment]
Hey thanks for the quick response , I just did that and understood the issue , but I have pulled it down for the time being. Anyway thanks for the help, I've understood the risks in that

**Comment by S0larflare** [comment]
You're welcome :smile:
