### ISSUE TITLE
[OS X] ./ gophish errors out (listen tcp 0.0.0.0:80: bind: permission denied)

### ISSUE THREAD

**Issue by Shamya** [gophish/gophish#134]
Hi,

When i try to execute the gophish script i get an error-
   gophish.go:71: Starting phishing server at http://0.0.0.0:80
   gophish.go:59: Starting admin server at http://127.0.0.1:3333
-->gophish.go:72:** listen tcp 0.0.0.0:80: bind: permission denied**

Port 80 is free (lsof -i tcp:80). But, I guess this is because its a non root process trying to bind to a privileged port. Could you kindly suggest a "secure" way to resolve this.

**Comment by wjwoodson** [comment]
Hi

As you determined this is a function of attempting to bind to a privileged port without root permissions. 

Running gophish via sudo is the easiest way to solve this issue for the purpose of evaluation. A more secure deployment may use a reverse proxy (apache mod_proxy, etc.) to forward traffic to the phish server process or port forwarding, authbind as described [here](http://apple.stackexchange.com/questions/37418/how-can-i-open-port-80-so-a-non-root-process-can-bind-to-it).

**Comment by Shamya** [comment]
Thank you !
