### ISSUE TITLE
Getting "mail: no angle-addr" in SMTP Options on plain addresses (similar to #135)

### ISSUE THREAD

**Issue by oxblue-rbollig** [gophish/gophish#1340]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.7.1

Brief description of the issue: When setting up SMTP account, get message "mail: no angle-addr" in red bar.  Cannot save configuration.

What are you expecting to see happen? : Expecting no error and ability to save SMTP configuration.

What are you seeing happen? Unexpected error message "mail: no angle-addr"

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

Please provide any terminal output that may be relevant below:

```
192.168.1.91 - - [09/Jan/2019:21:13:32 +0000] "POST /api/util/send_test_email?api_key=7d565f6d1309ddc33d1f860ac17eb5edb963bcb9c8c4cf3e8e63a6f3bffddfd6 HTTP/1.1" 400 74 "http://192.168.1.209:3333/sending_profiles" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0"
time="2019-01-09T21:13:45Z" level=error msg="record not found"
time="2019-01-09T21:13:45Z" level=error msg="mail: no angle-addr"

```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Start a new SMTP profile, fill in the information
 * Step 2 - Attempt to send a test email
 * Step 3 - When submitting the test request, observe error message
 * Step 4 - Cancel test message
 * Step 5 - Attempt to save and exit configuration modal, observe error message again.
 
 
Note: Some previous issues discuss this as an issue with Chinese or other characters in the email address; however, in this case I am using a very plain address.
Note: It looks like this error is passed from a GoLang library.

**Comment by jordan-wright** [comment]
Hi @oxblue-rbollig,

Can you please provide an example of the email syntax you're using, or a sample email address that is causing this error to occur?

**Comment by oxblue-rbollig** [comment]
We tried lots of really basic addresses... test@example.com was one of them.  Obviously that is not a valid address.  My own address is a similar user@domain.com address.  I'd rather not say it here so that it gets picked up by spam harvesters... but the base64 is cmJvbGxpZ0BveGJsdWUuY29t

In a new clue... I powered down the VM that I was testing on, so it had restart the process.  When I tested it this morning, addresses that were producing the error yesterday were working today.  It's almost as though there were some underlying service that had crashed out, but since it produced a lot entry, I don't think that's the case.

I'll play with it some more and see if I can get it to happen again; otherwise I guess close this out as "cannot reproduce" and my advice in the future is to try restarting it.

**Comment by jordan-wright** [comment]
Hi @oxblue-rbollig,

Sorry for the late reply. I appreciate the update! I'm glad to hear that, while odd, restarting the process seems to have fixed the issue.

If you run into this again, let me know and we can continue troubleshooting. Thanks again for getting in touch!

**Comment by deletehead** [comment]
I had this issue today with `mail: no angle-addr`. For me, it was due to my "From" field only having a name (`Canyu Diggit`) vs a name and addr (`Canyu Diggit <canyu.diggit@evil.org>`).

After that, the "no angle-addr" error made a lot more sense. Hope this helps someone else.

**Comment by NoelHG** [comment]
I had the same issue but I didn't understand the error message.  In my case in dev I had something like Name <email@localhostdigits> which correctly triggered the error. Just print the email.To field to the console and make sure it makes sense.

**Comment by lawrenceamer** [comment]
i think newer updates of gophish has not a lot of logical bugs , same error still occurs

**Comment by jasoncoke** [comment]
I also encountered such a problem. After investigation, I found that the From attribute did not contain information about the sender's email address, for example: <your email address>. But after I modified it, the error disappeared and the program was normal.

**Comment by jasoncoke** [comment]
I also encountered such a problem. After investigation, I found that the From attribute did not contain information about the sender's email address, for example: <your email address>. But after I modified it, the error disappeared and the program was normal.

**Comment by jasoncoke** [comment]
I also encountered such a problem. After investigation, I found that the From attribute did not contain information about the sender's email address, for example: < your email address >. But after I modified it, the error disappeared and the program was normal.

**Comment by Bevis100** [comment]
> I also encountered such a problem. After investigation, I found that the From attribute did not contain information about the sender's email address, for example: < your email address >. But after I modified it, the error disappeared and the program was normal.

please i just encounter the same error while trying to perform a 'send email test', how were you able to modify it to resolve the error ?
