### ISSUE TITLE
Problem with logs on phishing server

### ISSUE THREAD

**Issue by Cycl0pe** [gophish/gophish#1345]
What version of Gophish are you using?: **0.7.1**

Brief description of the issue: **When analyzing the logs, I do not find any event linked to the phishing server.**

What are you expecting to see happen? : **Request of the different users on the phishing server listed in the logs.**

What are you seeing happen? **There is no input in the log file when doing a request on the phishing server.**

**I don't know if I miss a feature but before pulling commit dating from 15 december until now, I did have some logs of the requests made to the phishing server.**

Cycl0pe

**Comment by jordan-wright** [comment]
Can you give more information about what you're referring to @Cycl0pe?

What do you mean by "When analyzing the logs, I do not find any event linked to the phishing server." Are you referring to the raw Gophish logs? As in, not the events we store in the database, rather, the raw web server logs?

**Comment by Cycl0pe** [comment]
I was referring to the logs

**Comment by Cycl0pe** [comment]
I was referring to the logs concerning the connection to the port 80 or 443 (phishing server), not the logs concerning the administration server.

For example, this kind of log is not displayed on the current version:

`time="2018-10-03T09:10:38Z" level=info msg="XXX.XXX.XXX.162 - - [03/Oct/2018:09:10:38 +0000] \"GET /?rid=BVtofz3 HTTP/2.0`

I hope I was more crystal-clear.

Cycl0pe

**Comment by rfdevere** [comment]
GoPhish captures the logs and activities from the phishing campaigns in a DB, but I think you are referring to the 'logs' as the terminal output from the binary? If so just grab it in **[script](https://unix.stackexchange.com/questions/200637/save-all-the-terminal-output-to-a-file)**.

**Comment by Cycl0pe** [comment]
@rfdevere: Yes, I'm referring to the 'logs' as the terminal output from the binary. I can use script for it or juste fulfil the filename field in config.json. But it does not resolve the fact that I don't see any output from the binary related to the phishing server.

Cycl0pe

**Comment by jordan-wright** [comment]
Hey there!

Just wanted to provide an update. I've tracked down the root cause and will get this fixed ASAP.

Thanks for the report, and sorry for the hassle!
