### ISSUE TITLE
Sqlite does not honour varchar(size) but mysql does

### ISSUE THREAD

**Issue by Cobra1978** [gophish/gophish#1346]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.7.1

Brief description of the issue: 
the column redirect_url is a varchar(255) in the pages table is a varchar(255), but this could be to short, 

What are you expecting to see happen? :
Import db data from sqlite to mysql without problem

What are you seeing happen?
the column  redirect_url get's truncated

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Install gophis with the sqlite database
 * create a redirect_url with more than 255 characthers, sqlite threat this as text filed and accepts it
 * export sqlite db and import in an empty gophish db on mysql
 * redirect_url get's truncated becaus emysql honour the carchar(255) size

I think that the right choiche is defining the field as text in sqlite and mysql to avoid inconistencies.

Best Regards

**Comment by jordan-wright** [comment]
Hi there!

Thanks for reaching out. This is something I can fix with a migration so that MySQL can support the longer URLs.

Great catch!
