### ISSUE TITLE
Unable to install WIN 64

### ISSUE THREAD

**Issue by hoherzler** [gophish/gophish#1349]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

hat version of Gophish are you using?: 7.1

Brief description of the issue: unable to install 

What are you expecting to see happen? : final install able to launch

What are you seeing happen? last line item is starting admin server - no other line items

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 - 
 
 [](url)

**Comment by hoherzler** [comment]
![capture](https://user-images.githubusercontent.com/47044915/51781167-07151d00-20e3-11e9-8d9b-40f47d0c6381.PNG)

**Comment by jordan-wright** [comment]
Hi there!

Things seem like they are starting just fine. What do you see when you browse to https://127.0.0.1:3333?

**Comment by jordan-wright** [comment]
Going ahead and closing this since there hasn't been any updates in a while. @hoherzler if you're still running into issues, let me know and we can re-open this issue to continue troubleshooting.
