### ISSUE TITLE
Unicode Issue: SMTP Options - From

### ISSUE THREAD

**Issue by thesoulkiller** [gophish/gophish#135]
Hi,
I've encountered a bug while starting a campaign,
In SMTP Options I've entered "From:" part non-ASCII characters as name like "Barış <email>". Then I started the campaign and program crashed. In command-line it says like 
`goroutine 22 [IO wait, 1 minutes]:
net.runtime_pollWait(0x11c9960, 0x72, 0xc0823920d0)
        C:/Go/src/runtime/netpoll.go:157 +0x67
net.(*pollDesc).Wait(0xc082038770, 0x72, 0x0, 0x0)
        C:/Go/src/net/fd_poll_runtime.go:73 +0x41
net.(*ioSrv).ExecIO(0xc082028c08, 0xc082038660, 0xb04a90, 0x7, 0xc0d348, 0x1d, 0x0, 0x0)
...
...
...
net/http.(*conn).serve(0xc082406a50)
        C:/Go/src/net/http/server.go:1319 +0x72e
created by net/http.(*Server).Serve
        C:/Go/src/net/http/server.go:1910 +0x3fd
`

And I tried to send a test mail on "SMTP Options - New Campaign" and it exposed an error as `mail no angle-addr.`.
I believe this is an utf-8 parsing issue.

By the way this is a great solution for "secure minded companies". Keep up the good work.
Barış Güvercin

**Comment by jordan-wright** [comment]
Interesting.. I could have sworn my email library (https://github.com/jordan-wright/email) supported unicode characters in the "From" header.

I'll take a look and see if I can reproduce. Can you show me an example of what you're typing in the "From" field?

**Comment by jordan-wright** [comment]
It looks as though this might be an issue with the standard Go library: https://play.golang.org/p/qCw3-rKKAg

I'll see if I can find any information on how to handle it (if we can).

**Comment by thesoulkiller** [comment]
Thank you, I found the same issue on go's github https://github.com/golang/go/issues/12492
I changed your code a bit, but it's not error safe :)
https://play.golang.org/p/xzkdKJwIkV

**Comment by jordan-wright** [comment]
Interesting - thanks! So, it looks like this will only work with email addresses that contain non-ascii characters? https://github.com/golang/go/issues/12492#issuecomment-140060316

**Comment by thesoulkiller** [comment]
I think so, https://github.com/golang/go/issues/12492#issuecomment-140062827 this handles the both cases(ASCII & non-ASCII) with line 19. I am not familiar with Go, so I don't know about how to handle error properly.

**Comment by jordan-wright** [comment]
Looks good! I'm going to try and get this implemented this week.

**Comment by noelvang** [comment]
Hi @jordan-wright ,

I am still experiencing this issue.

Did you implement any fix? 

This is with last version of github code.

example: "Noel Vøng<noel@mail.com>" fails with above errors.

**Comment by jordan-wright** [comment]
Hey @noelvang - sorry for the delay in getting back to you. I switched from my own email library to gomail, which I was hoping would solve a bunch of these mail problems.

If you're still seeing this, we'll need to continue trying to track down the issue.

**Comment by joenwoei** [comment]
I still can not fill chinese charater in <from> field in Sending Profile.
Is this issue resolved?
thanks

**Comment by jordan-wright** [comment]
This should be fixed now. Sorry for the delay everyone.

If anyone can build from source and test it on their own, it'd be much appreciated!

**Comment by rimvel** [comment]
Hello. No matter what i try i get the same error in "New Sending profile": "mail: no angle-addr" 
![image](https://user-images.githubusercontent.com/8319563/43464891-d267f17a-94e4-11e8-9cb1-94b1e9ffd34b.png)

Any ideas?

**Comment by Rzqu** [comment]
@rimvel Im getting this too..

**Comment by httpnotonly** [comment]
still happens

**Comment by httpnotonly** [comment]
This is because you need to put email in field "from"

**Comment by ravier2000** [comment]
I had the **mail: no angle-addr** because I forgot to put the port in the Host field (_smtp.xxx.com:yourport_) on my sending profile

**Comment by adarshvs** [comment]
I am still facing the same issue
