### ISSUE TITLE
Send By Date Field Not Staggering Emails

### ISSUE THREAD

**Issue by ntoenis** [gophish/gophish#1350]
What version of Gophish are you using?: v0.7.1

Brief description of the issue: Send by date doesn't appear to be being checked or used as expected. Also doesn't trigger a popup picker like launch date does. I have been copying the launch date to the send by date during my testing (i.e. formatted as so 01/28/2019 8:38 AM )

What are you expecting to see happen? : Emails to be distributed evenly between launch date and send by date.

What are you seeing happen? Emails labeled as "Scheduled to send at false" and the send by date can be set below the launch date. All emails are sent at once as soon as the time hits the launch date and the send by field appears to not function.

I an not sure if this is user error or a issue behind the scenes, but documentation on this feature feels very limited.

**Comment by jordan-wright** [comment]
Hi there!

Thanks for reaching out. If you're not seeing a popup for the datepicker, that might indicate that something is wrong with the Gophish installation. You should see something similar to this:

![image](https://user-images.githubusercontent.com/1317288/51878523-974aa080-2335-11e9-93e6-dfe110490e57.png)

Is this a fresh installation of Gophish, or did you upgrade from a previous version? You might also try a fresh installation to see if the problem persists, just in case something didn't get copied over correctly (or some other odd issue occurred).

**Comment by ntoenis** [comment]
Ah, it appears I had a botched update that although reported to be version 7.1 it was not complete. Redownloading and applying update fixed.
