### ISSUE TITLE
Settings API - Create/register user/login, get users/logins and API keys

### ISSUE THREAD

**Issue by vanditamathur** [gophish/gophish#1351]
With reference to GoPhish Settings APIs:
I would like to do the following from my code using APIs:

- Create/register multiple GoPhish users (logins) and get their API keys and other details.

The reason for this requirement is that I want to create and segregate campaigns for different users using their API keys. 
Right now, I am able to do this manually through the GoPhish console by registering new users and using their logins to create separate campaigns for them. However, I have to get these users and their API keys into my code manually, since there is no API to get this.

Is this something that is available or coming up? I could not find this in the API documentation.

**Comment by Cycl0pe** [comment]
Hey @vanditamathur,

I think your are talking about role-based access control (RBAC) and @jordan-wright has open a request for comment [here](#1333 ).

This feature is not available for the moment but will come soon hopefully.

Cycl0pe

**Comment by vanditamathur** [comment]
Hi @Cycl0pe , 
Thanks for your response. 

I had a look at the RBAC feature. That is good to have - however, my requirement is much simpler. I just need the APIs to do something that is already doable from the Settings in the GoPhish console.
I am ok with the multiple user and API key creation that is currently supported - only that I need the APIs for that.

**Comment by jordan-wright** [comment]
Hi @vanditamathur,

Thanks for reaching out! This is semi-related to the RBAC issue, in that when I'm finished with the initial implementation, I plan to add user management API's for all system admins. This will include creating/deleting users, changing passwords, resetting API keys, etc.

I'll keep this issue open for tracking the progress. It won't be super soon, but it's one of the higher items on the agenda 😄 

Thanks again for getting in touch!

**Comment by vanditamathur** [comment]
Thanks. Will keep a look out for this.

**Comment by jordan-wright** [comment]
Closed via 84096b8724b468a5e26329cb009d49a1914474c1.
