### ISSUE TITLE
What Values Are Required for start a Campaign?

### ISSUE THREAD

**Issue by Saridal17** [gophish/gophish#1355]
Hello. I am using your API for start a campaign. But I don't know What Values Are Required for start a Campaign? 

My post code like: 

`var data = {
            "id": 17,
            What values do I need to send to the API here?
             bla bla bla codes ...
        }
        Create('/api/campaigns/', data);`

Please help me. Thanks.

**Comment by jordan-wright** [comment]
Hi @Saridal17, thanks for reaching out!

The answer to this can be found in our [API documentation](https://docs.getgophish.com/api-documentation/campaigns#create-campaign).

If you run into any specific issues when trying to create a campaign, please don't hesitate to file an issue with the payload you're using in the API request and the error you're receiving and we'll be more than happy to troubleshoot.
