### ISSUE TITLE
Universal Variable

### ISSUE THREAD

**Issue by mother2110** [gophish/gophish#1357]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.7.1

Brief description of the issue: 
Creating a custom Email template
What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
I was just curious is there were any documentation on how to create custom landing pages and email templates? I have a collection of html login pages from various sites and want to use them with GoPhish but not sure about editing the html and email to work GoPhish

**Comment by jordan-wright** [comment]
Hi @mother2110,

Thanks for reaching out! All the documentation about email templates and landing pages can be found in our [User Guide](https://docs.getgophish.com/user-guide/documentation/landing-pages).

If you run into specific questions, don't hesitate to reach out with what you've tried and what you're seeing happen and we'd be happy to help troubleshoot.
