### ISSUE TITLE
Feature Request: Simple Button

### ISSUE THREAD

**Issue by notaaron** [gophish/gophish#1359]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.7.1
Brief description of the issue: 
Before I begin, thanks for the great product!! Excellent work! 

I would like to see something like https://ckeditor.com/cke4/addon/simplebutton added to the CKEditor
What are you expecting to see happen? :
If this were introduced, it would make making clickable buttons such as "View Files" easier to make.

What are you seeing happen?
Unless I'm just missing something, I'm not sure how I would make a legitimate "button" for our end users to be enticed by. This would help make the emails look and feel more advanced for just such campaigns.

If I am in fact "missing it", could someone point me in the right direction to add that in? Maybe I just have to get into the source and build it that way? Additional help would be appreciated there as well as I'm not very familiar with HTML...yet anyway.

Thanks!!  

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi @notaaron,

Thanks for reaching out!

There are a bunch of tricks needed to make nice email buttons (or really nice emails in general) due to the nature of what CSS different email clients support. I don't believe the SimpleButton CKEditor plugin accounts for this, so I'm not sure it would give us what we're looking for.

Instead, I recommend using something like https://buttons.cm/ to build the convincing buttons.

I hope this helps!
