### ISSUE TITLE
Tracking image can't really be deselected

### ISSUE THREAD

**Issue by colemic** [gophish/gophish#136]
When creating an email template, if you deselect the tracking button and save, if you view the template again, it is not there...  but after you run a campaign, and then you go look at the template you just used, the 'add tracking image' button is checked, and the campaign is run with it...  getting the dreaded 'red x' in the email when trying to download the pic, since my Outlook defaults block it from downloading initially, what is the source for the tracking file? Wonder if I have a proxy issue in retrieving the image.

**Comment by jordan-wright** [comment]
Interesting - thanks for the report! I'll try to reproduce with the details you posted, and will let you know if I can confirm it as a bug.

**Comment by jordan-wright** [comment]
One thing worth noting is that the "Use Tracking Image" is strictly a UI shortcut. It tells the javascript to add a {{.Tracker}} immediately after the closing </body>. Unfortunately, there isn't a way to store this information on the backend.

What I could do, I suppose, is check for the presence of a tracker when the template is viewed. Then, I could set the checkbox based on the result. I'll look into that as an option.

**Comment by jordan-wright** [comment]
Hey @colemic, I think I may have gotten this fixed. Can you give it a shot when you get a chance?

**Comment by jordan-wright** [comment]
I'm going to go ahead and close this out for now. @colemic if you still run into issues with this, let me know and I can re-open.
