### ISSUE TITLE
record not found and campaign not found - unable to access admin console

### ISSUE THREAD

**Issue by Halizone** [gophish/gophish#1361]
Hello,

I'm seeing really odd behavior and unable to access the admin console. This was working after the update to 0.7.1 and we successfully ran a campaign in November.

What version of Gophish are you using?: 0.7.1

Brief description of the issue: 

I'm unable to access the admin console and seeing weird terminal entries. When trying to access the admin console I get this chrome error:

This site can’t be reached 
The webpage at https://0.0.0.0:3333/ might be temporarily down or it may have moved permanently to a new web address.
ERR_TUNNEL_CONNECTION_FAILED

The terminal is showing this:

time="2019-02-12T13:39:19Z" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
time="2019-02-12T13:39:19Z" level=warning msg="No contact address has been configured."
time="2019-02-12T13:39:19Z" level=warning msg="Please consider adding a contact_address entry in your config.json"
goose: no migrations to run. current version: 20180830215615
time="2019-02-12T13:39:19Z" level=info msg="Starting phishing server at http://0.0.0.0:30000"
time="2019-02-12T13:39:19Z" level=info msg="Starting admin server at https://0.0.0.0:3333"
time="2019-02-12T13:40:19Z" level=error msg="record not found: campaign not found"
time="2019-02-12T13:40:19Z" level=error msg="record not found"
time="2019-02-12T13:40:19Z" level=error msg="record not found: campaign not found"
time="2019-02-12T13:40:19Z" level=error msg="record not found"
time="2019-02-12T13:40:19Z" level=error msg="record not found: campaign not found"
time="2019-02-12T13:40:19Z" level=error msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=error msg="record not found: campaign not found"
time="2019-02-12T13:40:19Z" level=error msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=error msg="record not found: campaign not found"
time="2019-02-12T13:40:19Z" level=error msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"
time="2019-02-12T13:40:19Z" level=warning msg="record not found"

Config.json:

{
	"admin_server" : {
		"listen_url" : "0.0.0.0:3333",
		"use_tls" : true,
		"cert_path" : "gophish_admin.crt",
		"key_path" : "gophish_admin.key"
	},
	"phish_server" : {
		"listen_url" : "0.0.0.0:30000",
		"use_tls" : false,
		"cert_path" : "example.crt",
		"key_path": "example.key"
	},
	"db_name" : "sqlite3",
	"db_path" : "gophish.db",
	"migrations_prefix" : "db/db_"
}

When I first set this up I used NSSM to keep it running. Tried this as a service and launching the .exe with the same result. Running this on Server 2012R2.

Many thanks for any help or advice on this. I'm a bit stuck!

Cheers!

**Comment by jordan-wright** [comment]
Hi there!

Looking around it appears that `ERR_TUNNEL_CONNECTION_FAILED` is typically the result of having proxy issues. I’d start by double checking your proxy settings.

Is Gophish running on the same machine you’re using to access it? If so, you can try using https://127.0.0.1 instead of 0.0.0.0 in your browser.

**Comment by Halizone** [comment]
Hi Jordan,

Thanks so much for coming back to me on this issue.

Yes, I'm doing everything on one machine. Tried https://127.0.0.1 but it's still not working. Also tried sticking localhost in config.json for good measure but that didn't help.

I've made sure there are no proxy settings on that server and checked that firewall rules are present to allow 3333 and 30000.

**Comment by jordan-wright** [comment]
If you're still seeing the `ERR_TUNNEL_CONNECTION_FAILED`, I'd recommend just double-checking your proxy settings, or perhaps making sure there isn't a VPN set up since everything I can find on that error suggests it's proxy related. I know you said you already checked them, but that's the only reason I could see for that error occurring.

Otherwise, everything else looks set up correctly. You're listening on port 3333, specify to use TLS, and you're making a request to https://localhost:3333 which is all correct and straightfoward.

I'm sorry there isn't much more that I can do to help. This appears to be some kind of issue with the host configuration, but I'm not quite sure what 🙁

**Comment by Halizone** [comment]
I've found what was happening here and it wasn't anything to do with GoPhish. 

Another member of my team decided to push out legacy browser support for Chrome via group policy. This has prevented me from contacting https://serverip:3333 and even localhost from the server itself. The plugin was hidden which made this all the  more challenging.

Thank you again for your time and helping me with this Jordan, it's very much appreciated. Also, I love using GoPhish, I think it's top notch! Please close this issue off.
