### ISSUE TITLE
[Feature Reqeust] Bulk manage items

### ISSUE THREAD

**Issue by pranavperfect** [gophish/gophish#1364]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.7.1

Brief description of the issue: Bulk manage items such as user groups, old campaigns, e-mail templates, landing pages etc.

What are you expecting to see happen? : Via a checkbox/select all functionality, be able to delete/archive the selected content.

What are you seeing happen?: This functionality isn't present in the latest release.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi @pranavperfect,

Thanks for reaching out! This is an active issue at #1193. I don't have an ETA when this will be released, but I do plan to get to it eventually.

Since we have an issue we're tracking this through, I'm going to go ahead and close this one out.

Thanks again for getting in touch!
