### ISSUE TITLE
Unable to Connect to Admin or Phishing Servers

### ISSUE THREAD

**Issue by riab-tam** [gophish/gophish#1365]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: v0.7.1

Brief description of the issue: Hi. I'm new to Go and running a Go service on a server. Following the instructions to install and run GoPhish on a clean CentOS 7 server as specified here: http://www.jaspher.com/blog/install-go-and-gophish-on-centos-7. After successfully installing the golang and GoPhish on the server, I can start the service and see messages that the servers have started, but when I go to the IP address of the server where GoPhish is running, it's not working. I have tried disabling firewalld and the same errors outlined below are showing. If I install and run apache, the default port 80 goes to the apache homepage, not the GoPhish server when it's running.

What are you expecting to see happen? : The admin landing page when going to the admin server address.

What are you seeing happen?

When going to the admin server via a web browser at "https://x.x.x.x:3333", the below errors are shown on the server side. See terminal output pasted below.

When going to "http://x.x.x.x", which should be the phishing server address, it's resulting in a general "Unable to Connect" error.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
[gophish@servername gophish]$ ./gophish
goose: no migrations to run. current version: 20180830215615
time="2019-02-19T10:16:26-06:00" level=info msg="Starting admin server at https://0.0.0.0:3333"
time="2019-02-19T10:16:26-06:00" level=info msg="Starting phishing server at http://0.0.0.0:80"
time="2019-02-19T10:16:26-06:00" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
2019/02/19 10:16:39 http: TLS handshake error from y.y.y.y:8463: read tcp x.x.x.x:3333->y.y.y.y:8463: read: connection reset by peer
2019/02/19 10:16:39 http: TLS handshake error from y.y.y.y:41492: read tcp x.x.x.x:3333->y.y.y.y:41492: read: connection reset by peer
2019/02/19 10:16:39 http: TLS handshake error from y.y.y.y:2837: read tcp x.x.x.x:3333->y.y.y.y:2837: read: connection reset by peer
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by S0larflare** [comment]
It looks like you are trying to go to http://your.ip go to https://your.ip and it should connect

Sent from my iPhone

On 19 Feb 2019, at 16:34, riab-developer <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for reaching out! We're happy to help resolve issues as quickly as possible.

Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our documentation<https://getgophish.com/documentation/>, which covers how to use Gophish.

What version of Gophish are you using?: v0.7.1

Brief description of the issue: Hi. I'm new to Go and running a Go service on a server. Following the instructions to install and run GoPhish on a clean CentOS 7 server as specified here: http://www.jaspher.com/blog/install-go-and-gophish-on-centos-7. After successfully installing the golang and GoPhish on the server, I can start the service and see messages that the servers have started, but when I go to the IP address of the server where GoPhish is running, it's not working. I have tried disabling firewalld and the same errors outlined below are showing. If I install and run apache, the default port 80 goes to the apache homepage, not the GoPhish server when it's running.

What are you expecting to see happen? : The admin landing page when going to the admin server address.

What are you seeing happen?

When going to the admin server via a web browser at "https://x.x.x.x:3333", the below errors are shown on the server side. See terminal output pasted below.

When going to "http://x.x.x.x", which should be the phishing server address, it's resulting in a general "Unable to Connect" error.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

Insert code here

Please provide any terminal output that may be relevant below:

[gophish@servername gophish]$ ./gophish
goose: no migrations to run. current version: 20180830215615
time="2019-02-19T10:16:26-06:00" level=info msg="Starting admin server at https://0.0.0.0:3333"
time="2019-02-19T10:16:26-06:00" level=info msg="Starting phishing server at http://0.0.0.0:80"
time="2019-02-19T10:16:26-06:00" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
2019/02/19 10:16:39 http: TLS handshake error from 71.190.247.17:8463: read tcp 23.253.54.155:3333->71.190.247.17:8463: read: connection reset by peer
2019/02/19 10:16:39 http: TLS handshake error from 71.190.247.17:41492: read tcp 23.253.54.155:3333->71.190.247.17:41492: read: connection reset by peer
2019/02/19 10:16:39 http: TLS handshake error from 71.190.247.17:2837: read tcp 23.253.54.155:3333->71.190.247.17:2837: read: connection reset by peer
2019/02/19 10:16:41 http: TLS handshake error from 71.190.247.17:34624: read tcp 23.253.54.155:3333->71.190.247.17:34624: read: connection reset by peer
2019/02/19 10:16:41 http: TLS handshake error from 71.190.247.17:18928: read tcp 23.253.54.155:3333->71.190.247.17:18928: read: connection reset by peer
2019/02/19 10:16:41 http: TLS handshake error from 71.190.247.17:61664: read tcp 23.253.54.155:3333->71.190.247.17:61664: read: connection reset by peer


Please provide as many steps as you can to reproduce the problem:

  *   Step 1 -
  *   Step 2 -

**Comment by riab-tam** [comment]
Hi S0larflare.

No, I'm explicitly going to "https://x.x.x.x:3333" when trying to access the admin server and getting the tls handshake error in the GoPhish console. When I go to "http://x.x.x.x[:80]", it resulted in a connection error and no output in the GoPhish console. After granting privileged port access to the GoPhish service, going to the plain http URL now just returns a 404 page not found error and again, no output in the GoPhish console.

If it helps, I'm testing this on a clean CentOS 7 build on a Rackspace cloud server.

Thanks in advance.

**Comment by jordan-wright** [comment]
What does your `config.json` look like?

**Comment by riab-tam** [comment]
Hi Jordan.

Below is our current config.json:

{
	"admin_server": {
		"listen_url": "0.0.0.0:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "gophish_admin.key"
	},
	"phish_server": {
		"listen_url": "0.0.0.0:80",
		"use_tls": false,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": "",
	"logging": {
		"filename": ""
	}
}

**Comment by riab-tam** [comment]
Hmm, I set this up on a separate Amazon EC2 Ubuntu instance, thinking it may be a Rackspace/CentOS issue, and it's producing the same TLS handshake error results.

**Comment by S0larflare** [comment]
What browser are you using to connect?

Sent from my iPhone

On 20 Feb 2019, at 16:12, riab-developer <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmm, I set this up on a separate Amazon EC2 Ubuntu instance, thinking it may be a Rackspace/CentOS issue, and it's producing the same TLS handshake error results.

**Comment by riab-tam** [comment]
S0larflare,

I've tried both Chrome and Firefox. Same results.

**Comment by riab-tam** [comment]
Quick update on this: we had a VNC server installed and started on one of the Rackspace servers we're testing this with and was able to access the GoPhish admin page that way via a VNC viewer and the local "https://127.0.0.1:3333" URL (and after adding the self signed security exception to Firefox).

Though this makes me unsure if the actual phishing server part of this will work once we start testing campaigns. With the GoPhish service running, are we supposed to get any response from a web browser if going to the IP address via regular http/port 80 of the server the service is running on?

**Comment by riab-tam** [comment]
Hi.

After more debugging, it looks like the issue is caused by the firewall in our office.

So everything else is working fine. Feel free to close this issue.

Thanks for the help in troubleshooting, and for a great product.

**Comment by hunrai** [comment]
How can I install gophish on centos7?
