### ISSUE TITLE
Only Allow Admins to Create Accounts

### ISSUE THREAD

**Issue by jordan-wright** [gophish/gophish#137]
This is an RFC to see what everyone thinks.

I've gotten multiple requests via email with concern that anyone can create an account and start phishing. Instead, the request is to only allow registered users to create new accounts.

I'm personally good with this - I just wanted to see what y'all think before making the change.

**Comment by colemic** [comment]
I'd agree w/ that...

**Comment by JoeySec** [comment]
As soon as I saw that anyone could create an account I stopped looking at gophish to preform phishing campaigns. I would definitely implement the change for only admin(s) to create accounts.

**Comment by jordan-wright** [comment]
Works for me. I'll make it happen.
