### ISSUE TITLE
Unable reach landing page by domain name

### ISSUE THREAD

**Issue by dakotech** [gophish/gophish#1377]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.7.1
Brief description of the issue: 
Gophish is being run on a windows server, I have an A record pointing to my public ip address and a port forwarding rule allowing traffic to my gophish server. When setting up a campaign using the public IP as the landing page everything works as expected, but if I setup a landing page using the domain name I am unable to reach the landing page, any ideas?

What are you expecting to see happen? :
Reach the landing page using a domain name
What are you seeing happen?
This site cant be reached
ERR_CONNECTION_TIMED_OUT
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi @dakotech,

I would revisit DNS as being the possible issue. If you're able to reach Gophish using the public IP, that suggests the networking is set up correctly. Gophish doesn't do any kind of domain filtering, so as long as the domain resolves to the correct IP address, things _should_ work.

**Comment by dakotech** [comment]
You are correct, i fat fingered the external in the A record, thanks!
