### ISSUE TITLE
Local files accessible through admin server instead of phishing server

### ISSUE THREAD

**Issue by hatermind** [gophish/gophish#1379]
Hi,

I am using version 0.7.1 and have created some files under `gophish-0.7.1/static/endpoint/` path

```
ubuntu:~$ cat gophish-0.7.1/static/endpoint/asd
sample text
```
According to the documentation and #220 #164 i should be able to access to that file through the phishing server `http://localhost/endpoint/asd`. But instead of that, i can only access through the admin server  `https://localhost:3333/endpoint/asd`

```
ubuntu@:~/gophish-0.7.1$ curl -k https://localhost:3333/endpoint/asd
sample text
```
```
ubuntu@:~/gophish-0.7.1$ curl -k http://localhost/endpoint/asd
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /endpoint/asd was not found on this server.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at localhost Port 80</address>
</body></html>

```

As i understood, the expected behaviour is to access to that kind of files through the phishing server, so the victims wont have access to the 3333 port (admin server). Am I right? hope you can help me ;)

**Comment by jordan-wright** [comment]
A couple of things:

First, it looks like Apache is listening on port 80 - you shouldn't have Apache running with Gophish unless you're explicitly using it to proxy requests to Gophish. Otherwise, it will receive the connections instead of Gophish.

Second, you'll need to reference the files using `/static/<filepath>`, not `/endpoint/<filepath>`. You'll see an example of this in [the documentation](https://docs.getgophish.com/user-guide/documentation/landing-pages#static-assets).

I hope this helps!

**Comment by hatermind** [comment]
> 
> First, it looks like Apache is listening on port 80 - you shouldn't have Apache running with Gophish unless you're explicitly using it to proxy requests to Gophish. Otherwise, it will receive the connections instead of Gophish.
> 

You are right, i am using a random AWS instance and didnt realize there was an Apache. It´s working now, thx!

**Comment by xpelican** [comment]
Hello, I'm not sure if I'm doing something wrong, but I can't seem to be able to access my static content.

Uploaded the static resources I want to use on the landing page to <gophish root folder>/static/endpoint.

In the page source, I refer to them like this:
`<link href="https://<IP>:3333/static/bootstrap.css" rel="stylesheet" />`
`<img src="https://<IP>:3333/static/phishing_01.jpg"/>`

(My Gophish panel is hosted on port 3333 and HTTPS is on)

But none of them show up in the page preview. Nothing changes.
Am I doing something wrong?

Thanks in advance!
