### ISSUE TITLE
Way to hide the URL token in the path

### ISSUE THREAD

**Issue by flabr03** [gophish/gophish#1380]
What version of Gophish are you using?: 0.7.1

Brief description of the issue: Hide the ?rid=preview-TrbXw5u token in the URL redirect

What are you expecting to see happen? :hide the string to make it cleaner

What are you seeing happen?  http:/<URL>/?rid=preview-TrbXw5u

**Comment by jordan-wright** [comment]
Hi @flabr03,

I'm afraid there isn't a native way to do this within Gophish. The `rid` parameter must be included, since this tells Gophish which recipient is opening the email, clicking the link etc. That determines what campaign this is for and, by extension, what landing page should be loaded.
