### ISSUE TITLE
Easy HTTP to HTTPS redirect for phishing server?

### ISSUE THREAD

**Issue by riab-tam** [gophish/gophish#1382]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.7.1

Brief description of the issue: Currently the phishing server only supports either HTTP or HTTPS connections. There is no easy or built-in way to redirect one to the other. If we have an SSL certificate set up for the phishing server domain, we'd like to be able to automatically redirect HTTP traffic to the HTTPS URL. Related to issue https://github.com/gophish/gophish/issues/489. Is there an option in GoPhish to do this? Or an easy way via mod_rewrite or an .htaccess file so we don't have to set up an NGIX or other service on top of GoPhish? Thanks.

What are you expecting to see happen? : When web browsers go to "http://www.phishing_server.com", automatically redirect to "https://www.phishing_server.com", which would show either the "404 page not found" error or custom HTML we set up.

What are you seeing happen? Currently, if the phishing server is set to listen to the HTTPS URL, simply going to the HTTP URL will result in a network connection error.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by riab-tam** [comment]
OK, so there's no built-in way to do this in gophish, but for anyone else looking to do the same, we accomplished this by installing apache alongside gophish and configured it to permanently redirect all plain http domain traffic (from port 80) to the https domain (port 443), which the phishing server is listening on.

Hope this helps others.

**Comment by TheGroundZero** [comment]
Do you mind sharing the config you used for setting up the webserver on port 80?
I guess you used mod_rewrite to rewrite the url from HTTP to HTTPS, keeping the unique URL that is used for tracking purposes?

**Comment by riab-tam** [comment]
@TheGroundZero Sure. We are using virtual hosts on our server, so we simply set up an apache/httpd .conf file with a permanent redirect set up for the httpd port 80:

"<VirtualHost *:80>
	ServerName your_gophish_domain.com
	ServerAlias www.your_gophish_domain.com
	Redirect permanent / https://www.your_gophish_domain.com/ 
</VirtualHost>"

So the above apache service is listening on port 80 for all traffic directed at the phishing domain and will redirect to the https enabled domain, including any GET parameters contained in the original URL.

I'm sure this can also be done via mod_rewrite or an .htaccess file, but this works for us and minimizes the steps necessary for the redirect.

Of course, the above requires the proper DNS entries to route the domain name to the IP address of the server running apache before it will work.

**Comment by H4xl0r** [comment]
Easy ,

1. setup apache webserver for your domain
2. get certs for ypur domain (certbot letsencrypt)
3. stop apache server / deactivate 
4.change gophish settings:
 Phishing listen url : 0.0.0.0:443
 set cert to /letsencrypt/live/fullchain (path to your cert )
set privkey to /letsencrypt/live/privkey (path to your keyfile)

should listen on port 443 (ssl) now.
when sending mails set url to Https://yourdomain
thats it

**Comment by razermouse** [comment]
I purchased a wildcard, multi-domain cert so that we could have emails sent from one domain but use landing pages from other domains and not trigger a certificate warning to Phish email recipients. Big tip off if they get a warning from Safari! 

I compiled from source and configured GoPhish to listen on port 443. I then installed Apache2 and configured it to listen on port 80 with the following in 000-default.conf:

<VirtualHost *:80>

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}

</VirtualHost>

You need to install the rewrite module to get this working. 

$ sudo a2enmod rewrite

**Comment by jordan-wright** [comment]
Hi everyone,

Sorry for dropping into this issue late. Y'all are correct that there is no builtin way to do this with Gophish. For now, it's recommended set up something like nginx in front of Gophish to handle this, if needed.

**Comment by TheGroundZero** [comment]
For those who prefer a copy-pasteable manual

Install certbot and get SSL cert.

```bash
cd /opt/gophish # or your gophish directory
sudo apt install certbot
sudo kill $(pidof gohpish)
sudo certbot certonly -d <YOUR_DOMAIN> --standalone
ln -s /etc/letsencrypt/live/<YOUR_DOMAIN>/privkey.pem  <YOUR_DOMAIN>.key
ln -s /etc/letsencrypt/live/<YOUR_DOMAIN>/fullchain.pem  <YOUR_DOMAIN>.crt
nano config.json
```

/opt/gohpish/config.json

```
{
        "admin_server": {
                "listen_url": "127.0.0.1:3333",
                "use_tls": true,
                "cert_path": "gophish_admin.crt",
                "key_path": "gophish_admin.key"
        },
        "phish_server": {
                "listen_url": "0.0.0.0:443",
                "use_tls": true,
                "cert_path": "<YOUR_DOMAIN>.crt",
                "key_path": "<YOUR_DOMAIN>.key"
        },
        "db_name": "sqlite3",
        "db_path": "gophish.db",
        "migrations_prefix": "db/db_",
        "contact_address": "",
        "logging": {
                "filename": "/var/log/gophish/gophish.log",
                "level": ""
        }
}
```

```bash
sudo a2dissite 000-default
sudo a2dissite default-ssl
```

```bash
sudo nano /etc/apache2/sites-available/redirect_http_https.conf
```

```
<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        RewriteEngine On
        RewriteCond %{HTTPS} off
        RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}
</VirtualHost>
```

```bash
sudo a2enmod rewrite
sudo a2ensite redirect_http_https
systemctl reload apache2
```

Confirm gophish is listening on port 443

```
./gophish
ss -palen | grep :443
```
