### ISSUE TITLE
cannot generate landing pages

### ISSUE THREAD

**Issue by jepunband** [gophish/gophish#1384]
What version of Gophish are you using?: 0.7.1

Brief description of the issue: does not seem to generate landing pages ..

What are you expecting to see happen? : should be able to view the generated landing page

What are you seeing happen? blank

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

example page to generate for the landing page is .. https://www.instagram.com/accounts/password/reset/?hl=en

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi @jepunband,

If the import site function isn't working, you'll need to manually create the HTML. Importing a site is a best-effort approach.

I do want to point out that I've seen you create issues asking about cloning various social media providers. It's hard for me to think of any instance where needing to use these pretexts would be appropriate for an authorized phishing simulation. Please note that we only support using Gophish for phishing simulations in which you've obtained prior authorization.
