### ISSUE TITLE
Gmail's Image Caching causes campaign emails to get instantly flagged as open

### ISSUE THREAD

**Issue by aczietlow** [gophish/gophish#1390]
A continuation of the issue from #1248  with more information.

**What version of Gophish are you using?:** 
0.7.1

**Brief description of the issue:** Campaign emails sent to gmail, either public gmail or email managed by google enterprise get instantly flagged as open.

**What are you expecting to see happen? :** 

I expected emails sent to email addresses managed by gmail to not get flagged as open until the user opens them in their email client. 

**What are you seeing happen?** 
WIthin seconds of the email getting sent to gmail, the email gets marked as opened. I believe this is because google will attempt to scan the email and pre-fetch emails for caching purposes, which obviously completely breaks the tracking image logic. After some testing by I'm seeing the following HTTP headers when google makes this request for images. 

```
{
  "host": [
    "ec2-127-0-0-1.compute-1.amazonaws.com"
  ],
  "connection": [
    "keep-alive"
  ],
  "user-agent": [
    "Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy)"
  ],
  "accept-encoding": [
    "gzip,deflate,br"
  ]
}
```

And gophish sends the following in it's http response 
```

{
  "Accept-Ranges": [
    "bytes"
  ],
  "connection": [
    "keep-alive"
  ],
  "Content-Type": [
    "image/png"
  ],
  "Date": [
    "Fri, 14 Dec 2018 18:13:26 GMT"
  ],
  "Last-Modified": [
    "Fri, 14 Dec 2018 18:13:26 GMT"
  ],
  "user-agent": [
    "Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy)"
  ],
  "vary": [
    "Accept-Encoding"
  ],
}
```
I purpose gophish updates to return a `Cache-Control` header with the value of `private, max-age=0, no-cache`. If not possible for all requests for the tracking image, at least target the requests from GoogleImageProxy.

**Comment by tagelthebagel** [comment]
How are you able to even get your emails through to gmail addresses?  Mine keep getting flagged simply for having the {{.URL}} tag in them.  Got any tips for a new guy using gophish?

**Comment by rgrunsten** [comment]
Also having this issue as of June. Emails are going through fine, but nearly 100% of them are being opened automatically by Google on our campaign tracking page. Any fixes for this?

**Comment by nickje10** [comment]
Same problem here, any fixes someone?

**Comment by glennzw** [comment]
There are two problems here, one with email providers loading images (the image tracker that we use to determine if a user has 'opened' an email) and the another with the email provider loading and examining any links in an email (marking our {{.URL}} as 'clicked').

To resolve emails being marked as opened the only solution I can think of is to include some middleware to block the email provider by IP or User Agent, or to whitelist your client. I haven't tested this, but a quick Google suggests this is possible with nginx or Caddy.

As for emails being 'opened' (email provider inspecting links) the above plan would work, or what I've had success with is hosting a separate webserver that 'proxies' pages via a JavaScript method. The point here is that if the email provider 'poking around' isn't rendering the pages with a JS engine, there will be no hit. Her's my solution: https://github.com/gophish/gophish/issues/1559#issuecomment-526602895

**Comment by glennzw** [comment]
Closing out as haven't heard back.

**Comment by emreekmekcioglu1** [comment]
@glennzw  Can you find a solution abt "opened" issue that is caused bcs of email providers examin and open the email before rendering it to client? Thank you
