### ISSUE TITLE
Cant send mails via postfix

### ISSUE THREAD

**Issue by vipul-nair** [gophish/gophish#1392]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.71
Brief description of the issue: 
i cant send emails via postfix
What are you expecting to see happen? :
mail being sent
What are you seeing happen?
the loading icon keeps rotating on "send test mail"
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:
```
# See /usr/share/postfix/main.cf.dist for a commented, more complete version


# Debian specific:  Specifying a file name will cause the first
# line of that file to be used as the name.  The Debian default
# is /etc/mailname.
#myorigin = /etc/mailname

smtpd_banner = $myhostname ESMTP $mail_name (Ubuntu)
biff = no

# appending .domain is the MUA's job.
append_dot_mydomain = no

# Uncomment the next line to generate "delayed mail" warnings
#delay_warning_time = 4h

readme_directory = no

# See http://www.postfix.org/COMPATIBILITY_README.html -- default to 2 on
# fresh installs.
compatibility_level = 2

# TLS parameters
smtpd_tls_cert_file = /etc/letsencrypt/live/mail.localshopowner.tk/fullchain.pem
smtpd_tls_key_file = /etc/letsencrypt/live/mail.localshopowner.tk/privkey.pem
smtpd_use_tls=yes
smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache
smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache

# See /usr/share/doc/postfix/TLS_README.gz in the postfix-doc package for
# information on enabling SSL in the smtp client.

smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated defer_unauth_destination
myhostname = localshopowner.tk
alias_maps = hash:/etc/aliases
alias_database = hash:/etc/aliases
myorigin = /etc/mailname
mydestination = $myhostname, localshopowner.tk, localhost.tk,localhost
relayhost =  
mynetworks =localshopowner.tk,139.59.70.0/24 ,127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
mailbox_size_limit = 0
recipient_delimiter = +
inet_interfaces = loopback-only
inet_protocols = all
smtpd_sasl_type =
smtpd_sasl_local_domain = 
smtpd_sasl_auth_enable = yes
smtpd_recipient_restrictions = permit_sasl_authenticated,permit_mynetworks,reject_unauth_destination
smtp_tls_security_level = may
smtpd_tls_security_level = may
smtpd_tls_loglevel = 1
smtpd_tls_received_header = yes
milter_protocol = 2
milter_default_action = accept
smtpd_milters = inet:localhost:8891
non_smtpd_milters = inet:localhost:8891
mynetworks_style=subnet
```
```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 1.I have configured my postfix on digital ocean to send only smtp.I can successfully send emails via linux gnu mail.The command for that is echo "anything" | mail -s "subject" anything@gmail.com.This command is succesfull in sending emails.
2.How do i configure the gophish to send the emails via postfix.
3.I am also attaching the output from postfix config file and sending profile of gophish.

THANK YOU IN ADVANCE.I APPOLOGISE IF THIS IS NOT THE PLACE TO ASK THIS QUESTION
![Screenshot from 2019-03-10 11-06-04](https://user-images.githubusercontent.com/43108515/54086934-8b82ce80-4324-11e9-9ff1-9aa63cdb2ded.png)

**Comment by jordan-wright** [comment]
Hi @vipul-nair,

Thanks for reaching out. Do you have any Postfix logs that may indicate what the problem might be?

**Comment by vipul-nair** [comment]
If the postfix logs are located at /var/log/mail.err

here  it is.if not please tell me where the logs are.
Mar 10 15:15:00 localshopowner postfix/smtpd[2030]: fatal: bad string length 0 < 1: smtpd_sasl_type =
Mar 10 15:16:01 localshopowner postfix/smtpd[2033]: fatal: bad string length 0 < 1: smtpd_sasl_type =
Mar 10 15:17:02 localshopowner postfix/smtpd[2050]: fatal: bad string length 0 < 1: smtpd_sasl_type =
Mar 10 15:18:03 localshopowner postfix/smtpd[2138]: fatal: bad string length 0 < 1: smtpd_sasl_type =
Mar 10 15:19:04 localshopowner postfix/smtpd[2146]: fatal: bad string length 0 < 1: smtpd_sasl_type =
Mar 10 15:20:05 localshopowner postfix/smtpd[2147]: fatal: bad string length 0 < 1: smtpd_sasl_type =

also if you look at my screenshot.what do i write at the username and password field?

**Comment by S0larflare** [comment]
You shouldn't need to do localhost:25, localhost should suffice (I've never put a port in that part).

Could the problem be that you have a cert for localshopowner.tk but are then sending to localhost, so the cert has a mismatch? I'd expect a better error if that is the case though to be fair, but it might be worth trying mail.localshopowner.tk instead.

**Comment by vipul-nair** [comment]
even if there is a certificate mismatch.the mail should still reach my inbox.shouldnt it?

**Comment by gfrancqu** [comment]
Hi,

your postfix `main.cf` show you specified 
```
smtpd_sasl_type = 
```
and your logs are explicilty complaining at this specific parameters. 
Here is the postconf documentation about this parameters

```
smtpd_sasl_type (default: cyrus)
The SASL plug-in type that the Postfix SMTP server should use for authentication. The available types are listed with the "postconf -a" command.

This feature is available in Postfix 2.3 and later.
```
Also, you setup SASL authentication but you didn't provided any username/password on your sending. 
I'm not sure testing your configuration with a simple `mail` command is the good solution, try it with telnet to be sure of your postfix configuration

**Comment by razermouse** [comment]
You should comment out smtpd_sasl_type if you're not concerned about changing it from the default (Cyrus) to Dovecot. Regarding the username and password, it depends on how you've got Postfix configured. I struggled to get SASL working on my email server and finally just disabled SASL and it worked. My email server only accepts connections from the GoPhish application server so it's not open to the world.  

http://www.postfix.org/SASL_README.html#server_sasl

**Comment by jordan-wright** [comment]
Closing this since there haven't been any updates in a few months.
