### ISSUE TITLE
Installing via 'go get github.com/gophish/gosphish' error

### ISSUE THREAD

**Issue by jelshani** [gophish/gophish#1394]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
- Gophish 0.7.1

Brief description of the issue: 
- Installing (on CentOS) is running into an error message

What are you expecting to see happen? :
- When running 'go get github.com/gophish/gophish' to succesfully download.

What are you seeing happen?

- When running 'go get github.com/gophish/gophish' the error message below pops up. 

Please provide any terminal output that may be relevant below:

```
[root@server opt]# go get github.com/gophish/gophish
# runtime
/usr/local/go/src/runtime/map.go:65:2: bucketCntBits redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:64:18
/usr/local/go/src/runtime/map.go:66:2: bucketCnt redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:65:23
/usr/local/go/src/runtime/map.go:77:2: maxKeySize redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:74:17
/usr/local/go/src/runtime/map.go:78:2: maxValueSize redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:75:17
/usr/local/go/src/runtime/map.go:83:2: dataOffset redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:83:4
/usr/local/go/src/runtime/map.go:94:2: evacuatedX redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:91:19
/usr/local/go/src/runtime/map.go:95:2: evacuatedY redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:92:19
/usr/local/go/src/runtime/map.go:96:2: evacuatedEmpty redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:90:19
/usr/local/go/src/runtime/map.go:97:2: minTopHash redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:93:19
/usr/local/go/src/runtime/map.go:100:2: iterator redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:96:17
/usr/local/go/src/runtime/map.go:100:2: too many errors
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - go get github.com/gophish/gophish

**Comment by ta1bbty** [comment]
How did you solve this ?
