### ISSUE TITLE
Feature : SMTP/OWA validation

### ISSUE THREAD

**Issue by matosha** [gophish/gophish#1399]
I know the "Reporting" feature is relatively new, but may i propose a validation module for credentials which are submitted. For example, in corporate social engineering exercises; it would be great to have a "Valid" check for credentials which are submitted.

1. User submits creds.
2. If set, the credentials are checked against the companies SMTP or OWA instance
3. The submitted credentials are flagged as valid given that point in time. 

{"user","clicked","opened","submitted","reported","valid"}

**Comment by jordan-wright** [comment]
Hi @matosha,

Thanks for sending in this feature request! At this time, I'm not interested in having Gophish do any kind of validation on submitted data for a couple of reasons:

* It would be unreliable. When credentials are received, to me they aren't expected to be valid as SMTP credentials. Rather, they would be expected to be valid for the service spoofed by the landing page. Sometimes this would be the same (e.g. for domain credentials) but not always.

* We'd have to figure out which SMTP server to submit credentials to. It's often the case that the SMTP server used by Gophish is a local relay, so we'd have to look this up which is extra logic to consider.

That said, I still appreciate you reaching out. Please keep the ideas coming!
