### ISSUE TITLE
mysql migrations bug fix not included into latest release

### ISSUE THREAD

**Issue by gfrancqu** [gophish/gophish#1401]
What version of Gophish are you using?: 0.7.1

Brief description of the issue: mysql migrations bug fix not included into latest release

What are you expecting to see happen? : A sucessfull initialisation of the database

What are you seeing happen? : a crash :(  
```
Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - download the 0.7.1 release .tar.gz
 * Step 2 -  configure gophish to use mysql
 * Step 3 - watch the world burn

Hi ! Recently build a distroless container image of gophish (btw let me know if you are interested in a pull request to integrate the dockerfile within your repo) where I get the source from your latest release, unfortunately while trying to connect gophish to a mysql instance I noticed a syntax error in the migration script. This bug has already been fixed, but wasn't included into the latest 0.7.1. release, maybe time for a 0.7.2 ? see commit https://github.com/gophish/gophish/commit/ba967a724413245dc58df843568a77e3cd8bd956#diff-a107dc3daef47cd5cf73ecfc58c0aa99

**Comment by jordan-wright** [comment]
Yep! I apologize for the inconvenience there. I'll be releasing new binaries soon, though there are still some outstanding things I want to get taken care of before I do that.

Since this isn't a new issue, I'm going to go ahead and close it out. Thanks again for the heads up!
