### ISSUE TITLE
Keystroke logging

### ISSUE THREAD

**Issue by Macb3th** [gophish/gophish#1405]
Hi, 

Trying this tool for the first time. Works great, but I need keystroke logging because if a user fills from but not press button I don't see anything. Is some kind opt to add keystroke log in real time so maybe somebody did that with some extra tools?

**Comment by jordan-wright** [comment]
Hi there!

Keystroke logging isn't supported at this time, and I don't have any plans to add it. While this sounds interesting, this would require quite a bit of development time and effort to support a bit of an edge case.

If you wind up adding this in Gophish yourself, please reach out and let us know how you got it working!
