### ISSUE TITLE
go get github.com/gophish/gophish error

### ISSUE THREAD

**Issue by robertturknj** [gophish/gophish#1408]
Hello, when I type this command in kali linux, after running it, it gives me this error:

root@kali:/tmp# go get github.com/gophish/gophish
**# github.com/jinzhu/gorm
/root/go/src/github.com/jinzhu/gorm/main.go:25: undefined: sync.Map**

then when I try to run this:

cd SGOPATH/src/github.com/gophish/gophish

gives me this:

SGOPATH/src/github.com/gophish.gophish: No such file or directory

Can you guys help me please?

**Comment by jordan-wright** [comment]
Hi there!

One of the dependencies we use (Gorm) recently added a feature that requires Go v1.9 and above. This means that, by extension, Gophish currently requires Go v1.9 or above.

If you run `go version`, see that it's above version 1.9, and still run into this issue, please let me know and I'll re-open this.
