### ISSUE TITLE
landing page can't import the site

### ISSUE THREAD

**Issue by greed5566** [gophish/gophish#1409]
What version of Gophish are you using?: 
0.7.1
Brief description of the issue: 
I could get  to the webpage through browser by using proxy. 
Take facebook for example, it responds as below:
Get https://zh-tw.facebook.com/: dial tcp 31.13.87.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by jordan-wright** [comment]
Hi @greed5566,

I'm afraid that importing sites or templates is a best effort approach and not guaranteed to always work perfectly. In this case, it appears that the server running Gophish was unable to reach the host at `31.13.87.1`, which seems to be a network/firewall issue. You mentioned that you are able to reach the site via a proxy which I don't believe Gophish supports at this time.

Sorry we couldn't be of more help!
