### ISSUE TITLE
Attachments are Not Being Sent in Emails

### ISSUE THREAD

**Issue by dckidd452** [gophish/gophish#141]
I add files in the email template and run the Campaign.
No any attachments in my email

![image](https://cloud.githubusercontent.com/assets/12841587/12985450/b0c89bfa-d12d-11e5-8e80-8a0c1bc04b04.png)
![image](https://cloud.githubusercontent.com/assets/12841587/12985513/0a1a05ae-d12e-11e5-8424-6b2089149997.png)

**Comment by jordan-wright** [comment]
Thanks for the report! I'll see if I can reproduce and will update with the results.

**Comment by jordan-wright** [comment]
Huh... that's crazy. I could have sworn that worked in the past but, sure enough, I could reproduce the issue. I see that we are saving the attachments but not actually attaching them (doh!)

I'll get this fixed ASAP. Sorry for the inconvenience!

**Comment by dckidd452** [comment]
Hi Jordan,

Thank you!!
Glad to have been of help.

Karzs
