### ISSUE TITLE
Updated Python scripts to schedule blueteam campaigns

### ISSUE THREAD

**Issue by snori74** [gophish/gophish#1413]
I've just updated the command-line Python scripts we use. (https://github.com/CommArc/phishbuckets). These 'sprinkle' 10 different test emails over a target group of users over a two week period. Feel free to fork and use.

**Comment by jordan-wright** [comment]
This is awesome, thanks @snori74! I've added it to our [Additional References](https://docs.getgophish.com/user-guide/additional-references) page. If you'd like the details or attribution changed, please don't hesitate to [make a pull request](https://github.com/gophish/user-guide/blob/6a995d6ec0372f979a4c298c1fdea0cae4a3c3e7/additional-references.md) with the changes.

Thanks again for sending this over. Great work!

**Comment by snori74** [comment]
Looks good.
