### ISSUE TITLE
Email Import doesn't work

### ISSUE THREAD

**Issue by alecisec** [gophish/gophish#1418]
What version of Gophish are you using?: 
Have tried both 7.1 as well as building from source

Brief description of the issue: 

What are you expecting to see happen? :
Email should import into the template when hitting the green "import" button after the red "import email" button

What are you seeing happen?
The email template remains blank, switching to source shows only 

<html>
<head>
	<title></title>
</head>
<body></body>
</html>

The console reports a malformed MIME header

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
have tried many, many different emails, all the same result "malformed MIME header"
```

Please provide any terminal output that may be relevant below:

```

test-server | time="2019-04-02T05:48:04Z" level=info msg="10.216.10.191 - - [02/Apr/2019:05:48:04 +0000] \"GET /js/src/vendor/ckeditor/plugins/scayt/dialogs/dialog.css HTTP/1.1\" 200 419 \"http://52.65.112.170:3333/templates\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36\""
test-server | time="2019-04-02T05:49:09Z" level=error msg="malformed MIME header line: </style><![endif]--><style><!--"
test-server | time="2019-04-02T05:49:09Z" level=info msg="10.216.10.191 - - [02/Apr/2019:05:49:09 +0000] \"POST /api/import/email?api_key=165ad69f34f10965b91bde51bd690d8718369f627a4f1bbd755ec861e11701d6 HTTP/1.1\" 200 146 \"http://52.65.112.170:3333/templates\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36\""
test-server | time="2019-04-02T05:49:10Z" level=info msg="10.216.10.191 - - [02/Apr/2019:05:49:10 +0000] \"GET /js/src/vendor/ckeditor/skins/moono-lisa/icons.png?t=c264cac HTTP/1.1\" 200 6045 \"http://52.65.112.170:3333/js/src/vendor/ckeditor/skins/moono-lisa/editor.css?t=IA8F\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36\""


```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - take source of any email
 * Step 2 - paste into import box
 * Step 3 - press import

**Comment by jordan-wright** [comment]
Hi @alecisec, can you provide a (sanitized if needed) email that’s not importing correctly? This will help me troubleshoot on my end.

**Comment by alecisec** [comment]
As stated this occurs with any sample, I've tried several dozen. Perhaps if you have a known-good sample I could submit it and provide logs

**Comment by jordan-wright** [comment]
With any issue, it would be far easier for me to troubleshoot the issue on my end as opposed to waiting for logs and hoping they give more information beyond the malformed mime header.

If you could, please provide the exact content (with redactions as needed) for something that isn't working. I'll give that a shot locally and, if there's an issue, I can track it down and fix it as I also wrote the library used to parse and import these emails.

**Comment by jordan-wright** [comment]
Closing this since there haven't been any updates in over a week. @alecisec if you're still running into issues, please provide the exact content (with redactions as needed) for something that isn't working. I'll give that a shot locally and, if there's an issue, I can track it down and fix it as I also wrote the library used to parse and import these emails.

**Comment by alecisec** [comment]
Here is an example



<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns:m="http://schemas.microsoft.com/office/2004/12/omml" xmlns="http://www.w3.org/TR/REC-html40"><head><meta name=Generator content="Microsoft Word 15 (filtered medium)"><style></style></head><body lang=EN-AU link="#0563C1" vlink="#954F72"><p class=msipheader5dd7071b align="Center" style="margin:0"><span style='font-size:12.0pt;font-family:Arial;color:#000000'>Public</span></p><br /><div class=WordSection1><p class=MsoNormal>This is a plain email<o:p></o:p></p></div></body></html>

**Comment by alecisec** [comment]
This issue is still existing in version 10.1 - does this work in a different way to the website importer?

**Comment by itsashnow** [comment]
Currently working on this version 10.1 now.... email importer itsn't working!
