### ISSUE TITLE
Add Indexes to Database Tables for Improved Performance?

### ISSUE THREAD

**Issue by riab-tam** [gophish/gophish#1419]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.7.1

Brief description of the issue: Looking through the database tables that GoPhish uses, we noticed that only the default "id" field are indexed. For example, in the results table, neither the campaign_id or r_id fields are indexed, although we would guess that they are filtered upon in the "where" clause of the query for a specific result or set of results. Same for the group_targets table: does it make sense to have the group_id and target_id as a unique composite key, or at the very least, have the group_id indexed? If these tables get to become large in size, wouldn't having these additional indexes improve the performance of the queries? And if we add the indexes ourselves, will it break anything?

What are you expecting to see happen? : Other fields in the tables that are commonly filtered by in the queries would be indexed as well.

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi @riab-tam,

I'd be open to adding indexes to the database. I'm not a DBA, so any pull requests would be appreciated.

**Comment by jordan-wright** [comment]
Closing since there haven't been any updates to this in a while.
