### ISSUE TITLE
Gmail picks up {{.Tracker}} automatically as phishing

### ISSUE THREAD

**Issue by tagelthebagel** [gophish/gophish#1420]
What version of Gophish are you using?:  0.7.1

Brief description of the issue:  If the word {{.Tracker}} is in my email gmail address automatically are flagging it as phishing.  Is that just the end of me being able to test since my company is on gmail addresses?  Has anyone else dealt with this before?  I even whitelisted the email address I'm sending from in my G Suite settings.

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - I use to have a full email and it worked for a bit to my one work email address whilst I was testing.  All of a sudden it marked it as a phishing email.
 * Step 2 - Next I tried to remove literally EVERYTHING from the email.  And just put their {{.Email}}.  That works.  Then the second I add {{.Tracker}} it Flags.

Help!

**Comment by tagelthebagel** [comment]
Just tried it again and apparently the {{.URL}} gets flagged to. Even without a tracker.

**Comment by jordan-wright** [comment]
Hi @tagelthebagel
