### ISSUE TITLE
Unable to launch gophish from source

### ISSUE THREAD

**Issue by smahewar** [gophish/gophish#1421]
Hello,
         I have installed the Go version go1.12.1 windows/amd64 and gcc mingw-w64.
I'm able to build the gophish project successfully but when i open the url's https://127.0.0.1:3333  or http://0.0.0.0:80 in browser i get "This site can’t be reached 127.0.0.1 took too long to respond."
The ports 80 & 3333 are open i have verified using telnet.
![image](https://user-images.githubusercontent.com/44671730/55590468-a84fcd80-573b-11e9-8fec-a209e5493f39.png)

Thanks

**Comment by jordan-wright** [comment]
Hi there!

Are you launching Gophish from the same machine that you’re using your browser on? What do you see if you go to http://127.0.0.1?

**Comment by smahewar** [comment]
Yes, i'm launching in the same machine.
When i go to"http://127.0.0.1" , I get below:
![image](https://user-images.githubusercontent.com/44671730/55671521-7eacb880-5899-11e9-80b6-7292317e97ac.png)

And
![image](https://user-images.githubusercontent.com/44671730/55671544-d0edd980-5899-11e9-939f-271e505dc125.png)

**Comment by jordan-wright** [comment]
So the first issue is that there is another web server apparently listening on port 80 (maybe Apache?). That's not Gophish's 404 page. You'll want to shut that down.

Then try relaunching Gophish and let me know what you see when going to http://127.0.0.1.

**Comment by smahewar** [comment]
No, I do n't have any webservers installed on my machine. Also the ports are open I have verified using telnet,so there is no firewall issue as well.

**Comment by jordan-wright** [comment]
I can almost promise you that there's a webserver running on port 80. The 404 response you see is generated by a webserver, and that's not Gophish's 404 page. Do you see a log line appear when you browse to http://127.0.0.1? If not, then that indicates that the request is almost certainly being processed by a different webserver.

What have you verified with telnet? I would encourage you to try and make a manual HTTP request to localhost on port 80 with Telnet to see what the response looks like.

The only other thing to consider would be to make sure there aren't any browser proxies set up that would interfere with the connection. Unlikely, but worth double-checking.

**Comment by jordan-wright** [comment]
Going ahead and closing this out since there haven't been any updates in roughly a week. @smahewar if you're still running into issues, take a look at the notes above and let me know if any of those help.

**Comment by shewhohacks** [comment]
I'm having the same issue and I'm hosting the server out of an EC2 and trying to navigate to the <Public IP>:3333 and getting the same "took too long error". I ran ufw and it's not running, I'm not on a VPN so there should be no firewall issues. I also ra na netstat and have nothing running on 80, 8080, or 443. So I'm legitimately not sure why this isn't working.

**Comment by Dompavi** [comment]
@shewhohacks I was having the same issue on EC2, however i noticed it was actually a firewall issue. At first In EC2 dashboard i created a Security group in which i allowed access to port 3333, however the server ignored the rules I've set there. Setting up the rules in the "launch-wizard-1" security group inbound rules as such:
![Screenshot 2021-04-07 130440](https://user-images.githubusercontent.com/82096000/113864243-94178e80-97a2-11eb-9f47-5373ac84cded.png)

**Comment by glennzw** [comment]
This is outside the scope of what we're able to help with. A useful approach to test if inbound collections are allowed is to use netcat or socat to listen on a port (when gophish is not running) to see if inbound connections are allowed. e.g:

On your EC2:
```user@ec2 $ nc -v -l 3333```

On your laptop:
```user@home $ nc -v myserver.com 3333```

...and you should see this output if the connection was allowed:

```
Connection to myserver.com  port 3333 [tcp/dec-notes] succeeded!
```
