### ISSUE TITLE
gophish 7.1

### ISSUE THREAD

**Issue by nanarosana** [gophish/gophish#1422]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 7.1

Brief description of the issue: 
Adding new feature with its model,html and js. But saving data to database not working
What are you expecting to see happen? :
saving my feature data into database
What are you seeing happen?
nothing
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi there!

I’m afraid theres not nearly enough information for us to begin troubleshooting.

Please open a new issue and provide as many details as possible - what it is that you’re trying to add, what code you’ve added, what you expect to see happen, what’s happening instead, and where you think the issue may be occurring. That will help is narrow down how to best help you troubleshoot.
