### ISSUE TITLE
Go-phish with new feature

### ISSUE THREAD

**Issue by nanarosana** [gophish/gophish#1423]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 7.1

Brief description of the issue: 
I am trying to add new feature to go-phish. I creates for my feature new HTML, JS and model also add its part to API and route. Besides, i creates new table in the database for it. The problem when i trays to save the setup for my feature for example the name, the saving button not working. I do not know where the problem ? is it from model, API or JS.??
What are you expecting to see happen? :
my feature data saved successfully on its table in the database.
What are you seeing happen?
no action.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
I’m afraid there still isn’t enough information to begin troubleshooting. All we know at this point is:

* You’re trying to add a feature to Gophish
* It’s not working

That’s not enough information to help you out. What feature are you trying to add? What code can you provide to show what you’ve tried?

I’m afraid that if you can’t provide the code you’re working on, there will be very little we can do to help you out.

**Comment by nanarosana** [comment]
can i contact with you via email?please

**Comment by jordan-wright** [comment]
I’m afraid we don’t offer email support and instead provide all support via Github Issues. It’s quite possible that someone in the future will run into a similar issue you’re encountering, so by working through the issue here the whole community will benefit.

**Comment by nanarosana** [comment]
One of my team member clarify saving problem and upload the code to you...

**Comment by jordan-wright** [comment]
Ok, in that case I'm going to close this out in favor of #1424.
