### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by alecisec** [gophish/gophish#1425]
What version of Gophish are you using?: Built from source on 8/4/2019

Brief description of the issue: Logging in with a newly created account does not working/page doesn't load

What are you expecting to see happen? : Existing accounts work OK 

What are you seeing happen? gateway errors/502 (gophish sits behind nginx)

Logs from the process as follows:

06:50:20
2019/04/08 06:50:20 http: panic serving 172.17.0.4:54862: runtime error: invalid memory address or nil pointer dereference

06:50:20
goroutine 1481 [running]:

06:50:20
net/http.(*conn).serve.func1(0xc4201be3c0)

06:50:20
/usr/lib/go-1.10/src/net/http/server.go:1726 +0xd0

06:50:20
panic(0xa509a0, 0x103b2f0)

06:50:20
/usr/lib/go-1.10/src/runtime/panic.go:502 +0x229

06:50:20
github.com/jinzhu/gorm.(*Scope).related(0x0, 0x9fd880, 0xc4206c4ba0, 0xc4206bd280, 0x1, 0x1, 0xc4206cda20)

06:50:20
/root/go/src/github.com/jinzhu/gorm/scope.go:1058 +0x3a

06:50:20
github.com/jinzhu/gorm.(*Association).Find(0xc4206c36e0, 0x9fd880, 0xc4206c4ba0, 0xc4206c36e0)

06:50:20
/root/go/src/github.com/jinzhu/gorm/association.go:19 +0x90

06:50:20
github.com/gophish/gophish/models.(*User).HasPermission(0xc42051cf20, 0xafa9fe, 0xd, 0xaac420, 0xc4201e9cb0, 0x0)

06:50:20
/root/go/src/github.com/gophish/gophish/models/rbac.go:78 +0x1ed

06:50:20
github.com/gophish/gophish/controllers.newTemplateParams(0xc4206bef00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)

06:50:20
/root/go/src/github.com/gophish/gophish/controllers/route.go:154 +0x117

06:50:20
github.com/gophish/gophish/controllers.(*AdminServer).Base(0xc4200881e0, 0xb70080, 0xc42016a5b0, 0xc4206bef00)

06:50:20
/root/go/src/github.com/gophish/gophish/controllers/route.go:201 +0x43

06:50:20
github.com/gophish/gophish/controllers.(*AdminServer).Base-fm(0xb70080, 0xc42016a5b0, 0xc4206bef00)

06:50:20
/root/go/src/github.com/gophish/gophish/controllers/route.go:98 +0x48

06:50:20
net/http.HandlerFunc.ServeHTTP(0xc42001fec0, 0xb70080, 0xc42016a5b0, 0xc4206bef00)

06:50:20
/usr/lib/go-1.10/src/net/http/server.go:1947 +0x44

06:50:20
github.com/gophish/gophish/middleware.RequireLogin.func1(0xb70080, 0xc42016a5b0, 0xc4206bef00)

06:50:20
/root/go/src/github.com/gophish/gophish/middleware/middleware.go:109 +0xaf

06:50:20
net/http.HandlerFunc.ServeHTTP(0xc420112b40, 0xb70080, 0xc42016a5b0, 0xc4206bef00)

06:50:20
/usr/lib/go-1.10/src/net/http/server.go:1947 +0x44

06:50:20
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4200ca0c0, 0xb70080, 0xc42016a5b0, 0xc4206bed00)

06:50:20
/root/go/src/github.com/gorilla/mux/mux.go:212 +0xcd

06:50:20
github.com/gorilla/csrf.(*csrf).ServeHTTP(0xc42017cb40, 0xb70080, 0xc42016a5b0, 0xc4206bec00)

06:50:20
/root/go/src/github.com/gorilla/csrf/csrf.go:267 +0x323

06:50:20
net/http.(Handler).ServeHTTP-fm(0xb70080, 0xc42016a5b0, 0xc4206beb00)

06:50:20
/root/go/src/github.com/gophish/gophish/controllers/route.go:121 +0x4d

06:50:20
net/http.HandlerFunc.ServeHTTP(0xc42015a600, 0xb70080, 0xc42016a5b0, 0xc4206beb00)

06:50:20
/usr/lib/go-1.10/src/net/http/server.go:1947 +0x44

06:50:20
github.com/gophish/gophish/middleware.CSRFExceptions.func1(0xb70080, 0xc42016a5b0, 0xc4206beb00)

06:50:20
/root/go/src/github.com/gophish/gophish/middleware/middleware.go:30 +0xba

06:50:20
net/http.HandlerFunc.ServeHTTP(0xc42015a640, 0xb70080, 0xc42016a5b0, 0xc4206beb00)

06:50:20
/usr/lib/go-1.10/src/net/http/server.go:1947 +0x44

06:50:20
github.com/gophish/gophish/middleware.GetContext.func1(0xb70080, 0xc42016a5b0, 0xc4206bea00)

06:50:20
/root/go/src/github.com/gophish/gophish/middleware/middleware.go:60 +0x251

06:50:20
net/http.HandlerFunc.ServeHTTP(0xc42015a680, 0xb70080, 0xc42016a5b0, 0xc4206be800)

06:50:20
/usr/lib/go-1.10/src/net/http/server.go:1947 +0x44

06:50:20
github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x7f6cfd2face0, 0xc4206c2ab0, 0xc4206be800)

06:50:20
/root/go/src/github.com/NYTimes/gziphandler/gzip.go:336 +0x1ae

06:50:20
net/http.HandlerFunc.ServeHTTP(0xc420161b00, 0x7f6cfd2face0, 0xc4206c2ab0, 0xc4206be800)

06:50:20
/usr/lib/go-1.10/src/net/http/server.go:1947 +0x44

06:50:20
github.com/gorilla/handlers.loggingHandler.ServeHTTP(0xb6b1a0, 0xc42000e790, 0xb6c0e0, 0xc420161b00, 0xb1f980, 0xb6ff80, 0xc42068ae00, 0xc4206be800)

06:50:20
/root/go/src/github.com/gorilla/handlers/logging.go:45 +0x133

06:50:20
net/http.serverHandler.ServeHTTP(0xc420084d00, 0xb6ff80, 0xc42068ae00, 0xc4206be800)

06:50:20
/usr/lib/go-1.10/src/net/http/server.go:2697 +0xbc

06:50:20
net/http.(*conn).serve(0xc4201be3c0, 0xb70540, 0xc4208d8e40)

06:50:20
/usr/lib/go-1.10/src/net/http/server.go:1830 +0x651

06:50:20
created by net/http.(*Server).Serve

06:50:20
/usr/lib/go-1.10/src/net/http/server.go:2798 +0x27b

**Comment by alecisec** [comment]
Worked out this was due to the 'role_id' value in the db being set to '0' for new accounts, setting it manually to 2 resolves the issue.

**Comment by jordan-wright** [comment]
Hi @alecisec,

I apologize that you ran into this! This stemmed from the recent addition of RBAC support. I'm working right now to move registration to a full user-management API which should be done soon. This should resolve the issue.

I'm tracking this issue through #1375. Since this appears to be a duplicate, I'm going to close this one out in favor of working through that one.

Thanks again for the heads up!
