### ISSUE TITLE
404 Error in API Documentation Link

### ISSUE THREAD

**Issue by riab-tam** [gophish/gophish#1429]
Not really an Gophish issue, but just wanted to bring up that the API documentation link in the https://docs.getgophish.com/user-guide/documentation/using-the-api page is resulting in a 404 page not found error.

Just FYI. Thanks for a great product.

![gophish_link_404](https://user-images.githubusercontent.com/5065132/56152888-e098ac80-5f82-11e9-8b98-fd6d0ca2afa0.png)

**Comment by jordan-wright** [comment]
Thanks for the heads up! Got it fixed.
