### ISSUE TITLE
"New Template" has pre-populated values

### ISSUE THREAD

**Issue by snori74** [gophish/gophish#143]
Clean "admin" login and choose _Email Templates, +New Template_ - and get a form that's not the blank one that I'd expect - but instead is pre-populated: "Name" field has the name of a previously deleted template; "Text" is populated with the raw email content of a previous email import.

If I do a few new templates in a row, I see each new one having the "Subject": pre-populated with that of the previous - _that_ might be by design, but it doesn't seem necessary.

**Comment by jordan-wright** [comment]
Thanks for the report! I thought we got all these "artifact" bugs out but I guess not :smile: 

I'll get this taken care of for you.

**Comment by jordan-wright** [comment]
@snori74 can you check if this is fixed for you? We think we fixed this as of a2ee229.

**Comment by jordan-wright** [comment]
I'm going to go ahead and close this out for now. @snori74 if you still run into issues with this, let me know and I can re-open.
