### ISSUE TITLE
Made a change in the query page.go and the change is not reflected

### ISSUE THREAD

**Issue by smahewar** [gophish/gophish#1430]
Hi,
   I have a change in the .\gophish\gophish\controllers\api\page.go after the change i have built the code using "go build" and started the "gophish". The web pgae lauanched but the query changes are not reflected.
Is this the way to change the code and rebuild the gophish project ? Please do let me know if i'm missing anything.

Thanks,
Srikanth M

**Comment by jordan-wright** [comment]
Hi @smahewar,

I'm afraid there isn't enough information here to help troubleshoot. Rebuilding using `go build` and running the new executable should be enough to make things work so my best recommendation would be to first add a simple change like a print statement somewhere in the code to make _sure_ that the code isn't running, then begin to troubleshoot your installation of Golang.

Helping with local Golang issues is, I'm afraid, out of scope for the support we can provide here.

Sorry we couldn't be of more help!

**Comment by aukhan288** [comment]
I am also facing the same issue and also go build command return nothing
