### ISSUE TITLE
Can not start gophish

### ISSUE THREAD

**Issue by bubaiwantong** [gophish/gophish#1431]
Hello:
    when i use command ./gophish, show below:

time="2019-04-17T14:36:42+08:00" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
time="2019-04-17T14:36:42+08:00" level=warning msg="No contact address has been configured."
time="2019-04-17T14:36:42+08:00" level=warning msg="Please consider adding a contact_address entry in your config.json"
time="2019-04-17T14:36:42+08:00" level=error msg="no valid version found"
time="2019-04-17T14:36:42+08:00" level=fatal msg="no valid version found"

please help me, thank you very much

**Comment by bubaiwantong** [comment]
i edit config.json,show below

        "db_name": "mysql",
        "db_path": "root:xxxxxx@(:3306)/gophish?charset=utf8&parseTime=True&loc=UTC",
        "migrations_prefix": "db/db_",
        "contact_address": "china"

xxxxxx is mysql password

then restart gophish, show below:

time="2019-04-17T15:16:34+08:00" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
goose: migrating db environment 'production', current version: 0, target: 20180830215615
2019/04/17 15:16:34 FAIL 20160118194630_init.sql (Error 1071: Specified key was too long; max key length is 767 bytes), quitting migration.

**Comment by Seronsecurity** [comment]
Are you using SQLite?
Also - "contact_address":   I thought this was for an email adress, like "info@domain.cn"

**Comment by bubaiwantong** [comment]
> 
> 
> Are you using SQLite?
> Also - "contact_address": I thought this was for an email adress, like "[info@domain.cn](mailto:info@domain.cn)"

No, i use mysql

but if i use sqllite, that's ok

**Comment by jordan-wright** [comment]
Hi @bubaiwantong,

I'm not quite sure what would cause this issue. It looks like some configurations of MySQL may cause a key size issue, but I won't have time anytime soon to dig into it.

For now, I'm glad to hear you had success using SQLite. Since you have a workaround, I'm going to close this one out.

**Comment by glasn0st** [comment]
Hi @jordan-wright and @bubaiwantong, I had the same issue about mysql. 

The docs(https://docs.getgophish.com/user-guide/installation#create-the-database) of gophish told me to create database with utf8mb4_unicode_ci encoding and in file 20160118194630_init.sql it creates tables with type VARCHAR(255) UNIQUE.
The utf8mb4 encoding can use up to 4 bytes per character, so 
255*4 = 1020 bytes, which is higher than maximum key length(767 bytes).

The solution could be deleting the UNIQUE constraint from the SQL query. I'm not sure if the whole system is going to run correctly, I'm going to give it a shot, though.

**Comment by Seronsecurity** [comment]
IIRC,  varchar(255) ‘reserves’ that space, but doesn’t actually use it all until/unless the table actually needs it. It is ‘variable’ , with the maximum storage size being 255.  Since you won’t have a table full of 255 characters for every value, this shouldn’t be an issue.  Or am I misreading the issue?

aaron

**Comment by glasn0st** [comment]
> IIRC,  varchar(255) ‘reserves’ that space, but doesn’t actually use it all until/unless the table actually needs it. It is ‘variable’ , with the maximum storage size being 255.  Since you won’t have a table full of 255 characters for every value, this shouldn’t be an issue.  Or am I misreading the issue? aaron
> […](#)
> On May 29, 2019, 3:14 AM -0400, glasn0st ***@***.***>, wrote: Hi @jordan-wright and @bubaiwantong, I had the same issue about mysql. The docs(https://docs.getgophish.com/user-guide/installation#create-the-database) of gophish told me to create database with utf8mb4_unicode_ci encoding and in file 20160118194630_init.sql it creates tables with type VARCHAR(255) UNIQUE. The utf8mb4 encoding can use up to 4 bytes per character, so 255*4 = 1020 bytes, which is higher than maximum key length(767 bytes). The solution could be deleting the UNIQUE constraint from the SQL query. I'm not sure if the whole system is going to run correctly, I'm going to give it a shot, though. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

Yeah, but it can't 'reserve' more than 767 bytes. It's request for @jordan-wright to verify that it actually needs 255 bytes or/and unique constraint.

**Comment by Seronsecurity** [comment]
AHA!  
Sorry then. I was just trying to be helpful.

Aaron S. Birnbaum
Chief Security Officer
Seron Security, LLC
O: 866-666-4235
C: 781-363-2085
https://www.SeronSecurity.com
Our business is keeping others out of your business!™

Linkedin.com/company/seron-security
Facebook.com/Seron-Security-676440066078370/
Twitter.com/seronsecurity

Listen Thursday mornings at 8 am on 107.7 FM WTPL - https://www.radio.net/s/wtpl

----------------------------------------
