### ISSUE TITLE
URL Link to incorrect web page

### ISSUE THREAD

**Issue by zombian** [gophish/gophish#1442]
On the Community Guides page the link to practical phishing links to the USB one underneath it. https://docs.getgophish.com/user-guide/additional-references

It should link to https://medium.com/airwalk/practical-phishing-with-gophish-7dd384ad1840

**Comment by jordan-wright** [comment]
Thank you for the heads up! I could have sworn I had those correct, but that must have somehow slipped past me.

I've fixed it and we should be good to go now. Great catch!
