### ISSUE TITLE
Credential Capture and Redirect Issue

### ISSUE THREAD

**Issue by jmorin124** [gophish/gophish#1443]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  0.7.1

Brief description of the issue: I am attempting to create a simple html page to do a basic phishing test for my users. However, when I test the landing page, the "sign-in" button does not redirect me to the correct page, and the credentials do not capture in gophish (although my browser recognizes the submitted credentials just fine). When I try to edit the <form action=""> line, whatever I enter does not save. The only way I have found to redirect the user when the sign-in button is clicked is to create a URL link over the button in the HTML editor. I assume this is why the credentials are not saving, however I cannot figure out how to edit the <form action=""> line and have it save my input. I have tried looking through the related issue tickets, but I cannot figure out a solution that works for me. It probably does not help that I have 0 experience with HTML, so I apologize.

What are you expecting to see happen? : The <form action=""> line save my input, and the user's credentials to be saved in the administrative console upon entry.

What are you seeing happen? The <form action=""> line does not save my input, and no credentials are saved.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
<html><head>
	<title>Login Page</title>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
</head>
<body background="http://atgbcentral.com/data/out/188/5649077-blue-background-images.jpg">
<p>​</p>

<p align="center" style="color:white;font-size:250%">Summer Picnic Survey</p>

<div align="center"><img src="original.png"/></div>

<div align="center">
<p class="c" style="color:white;font-size:150%">Please enter your Office 365 credentials here so that we know who responded to the survey</p>

<form action="">
<table align="center" style="margin: 0px auto;">
</table>

<table class="c">
	<tbody>
		<tr>
			<td style="color:white;font-size:125%">Username or email address</td>
		</tr>
		<tr>
			<td><input size="27" type="text"/></td>
		</tr>
		<tr>
			<td style="color:white;font-size:125%">Password</td>
		</tr>
		<tr>
			<td><input size="27" type="password"/></td>
		</tr>
		<tr>
		</tr>
		<tr>
		</tr>
		<tr>
			<td align="center"><a href="http://www.strawpoll.me/17865420"><input type="submit" value="Sign in"/></a></td>
		</tr>
	</tbody>
</table>
</form>
</div>

<p>​</p>


</body></html>
```

**Comment by Spacekoekje** [comment]
Hello,

Not sure if this issue has been resolved, but have you tried the following?

- adding post method to the form
- adding a "name" to the input field
- [x] Capture Passwords in the Landing page template

```
<form action="" method="post" name="form">

<input name="username" placeholder="email@test.com" type="email"/>
<input name="password" placeholder="Password" type="password"/>

<button class="color-button" type="submit" value="Submit">Sign in</button>
</form>
```
Regards

**Comment by jordan-wright** [comment]
Hi @jmorin124,

Thanks for reaching out. @Spacekoekje is correct - your form needs to have the method set to `post`, and you need `name` attributes for every parameter you want to record in Gophish.

Setting both of these up should make things work for you.

Thanks again for getting in touch!
