### ISSUE TITLE
Campaign URL

### ISSUE THREAD

**Issue by Graz1991** [gophish/gophish#1446]
Hi,

I am trying to send my first Gophish campaign.

Server was configure as follows:
{
	"admin_server" : {
		"listen_url" : "127.0.0.1:3333",
		"use_tls" : true,
		"cert_path" : "gophish_admin.crt",
		"key_path" : "gophish_admin.key"
	},
	"phish_server" : {
		"listen_url" : "0.0.0.0:80",
		"use_tls" : false,
		"cert_path" : "example.crt",
		"key_path": "example.key"
	},
	"db_name" : "sqlite3",
	"db_path" : "gophish.db",
	"migrations_prefix" : "db/db_"
}

and campaign URL was set to http://127.0.0.1. The email is sent however cannot capture the statistics even through the users clicked on the link.

Can you please help? Thank you.

**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue: 

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by Spacekoekje** [comment]
Hello,

the campaign URL (The one you fill in when creating your campaign) has to be reachable for your targets.
So it depends where you are hosting your gophish server. 
for example, if you were to host it at a cloud provider with server ip: 123.45.67.91, the campaign URL would be: 

- http://123.45.67.91

now you would like to point your phishy domain (A record) to 123.45.67.91 , making the campaign URL:

- http://phishy.domain

once you get this working i suggest implementing https (https://www.n00py.io/2017/09/phishing-with-gophish-and-letsencrypt/)

**Comment by jordan-wright** [comment]
Hi @Graz1991,

@Spacekoekje is correct - the URL needs to be reachable by the recipient. The URL you used points to localhost, which is only available on the local machine.

You can find more information about this in our [FAQ](https://docs.getgophish.com/user-guide/faq) under the "Check the Campaign URL" section.

I hope this helps!
