### ISSUE TITLE
Security hardening of releases

### ISSUE THREAD

**Issue by eickeh** [gophish/gophish#1449]
What version of Gophish are you using?: 0.7.1

Brief description of the issue: 
Thanks again for all your work!
When unzipping a release under Linux the config.json file is world readable by default. As this contains the database password, it is desirable to have it only user, maximum group readable. The zip command keeps permissions when zipped and unzipped on Linux machines. Therefore, one could ```chmod 640``` the config.json before zipping and releasing it. 
Same problem also occurs when cloning the git repo. To also catch those cases, one could add a note to the "Install" section of the readme like:
  "Note: As the config.json file contains the database password, make sure that it is not world readable. For Linux users, a simple ```chmod 640``` does it."
Also, please use at least SHA256 for the hashes of the release zips as SHA1 is already considered insecure.

What are you expecting to see happen? :
config.json is not world readable by default or something tells me to set the permissions manually. SHA256 hashes are used for the release zip files.

What are you seeing happen?
config.json is world readable by default. SHA1 hashes are used for release zip files.

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Download GoPhish via zip file or clone the repo with git.
 * Step 2 - In case of zip file: unzip it
 * Step 3 - check permissions of config.json

**Comment by jordan-wright** [comment]
Hi @eickeh,

Thanks for reaching out! I'll update the release process to update the permissions for the `config.json` file. Additionally, I'll use SHA256 for the release hashes, as requested.

In the meantime, I've [updated the documentation](https://docs.getgophish.com/user-guide/installation#understanding-the-config-json) to give a heads up about restricting the file permissions.

Thanks again for getting in touch!
