### ISSUE TITLE
Cannot create custom Content-Type header to send multipart email

### ISSUE THREAD

**Issue by Synkrone** [gophish/gophish#1450]
**What version of Gophish are you using?:**
0.7.1

**Brief description of the issue:** 
The Content-Type header in the sending profile defaults to _Content-Type: text/html; charset="UTF-8"_ and cannot be overwritten

**What are you expecting to see happen? :**
I want to be able to overwrite the header in order to send a multipart email
for instance by specifying the following header:

Content-Type: multipart/alternative; boundary="abcdefg"

**What are you seeing happen?**
The header is always: 
Content-Type: text/html; charset="UTF-8"

**Comment by jordan-wright** [comment]
Hi @Synkrone,

I'm afraid that there isn't a way to change the Content Type header. The only headers we support are for changing email-wide headers, not individual MIME part headers. In Gophish, we manually add the Content-Types for the HTML and Text part of the email templates.

Sorry there isn't more we can do to help here!
