### ISSUE TITLE
Passwords and other campaign results not consistently deleted from database

### ISSUE THREAD

**Issue by blincoln-dd** [gophish/gophish#1452]
What version of Gophish are you using?: 

0.7.1

Brief description of the issue: 

When a campaign is deleted, the result data for that campaign (in particular, passwords submitted by recipients) are not consistently deleted from gophish.db.

What are you expecting to see happen? :

When I delete a campaign, I expect all data related to that campaign (but especially captured credentials) to be deleted from the GoPhish database.

What are you seeing happen?

I deleted approximately 20 campaigns today, and about 16 sets of captured credentials remain in gophish.db. Some of these credentials are from the same campaigns. There isn't a pattern I can see as to which campaigns were removed entirely from the database and which weren't.

I created a new campaign afterwards and made sure the file timestamp was updated to ensure it wasn't a disk write that hadn't been flushed yet.

You're more familiar with the code than I am, but perhaps consider something like looping through the table and setting any submitted value to 'XXXXXXXXXXXXXXXXXXXXXXXXXXX' or some other placeholder before deleting the campaign.

Please provide as many steps as you can to reproduce the problem:

 * Step 1 - Create some campaigns
 * Step 2 - Submit passwords for those campaigns
 * Step 3 - Submit passwords for those campaigns
 * Step 4 - Run the grep command below (requires GNU grep) to verify that the passwords are in the database.
 * Step 5 - Delete the campaigns
 * Step 6 - Run the same grep command again and see if any of the passwords are still present.

Grep command I used:

grep -P -i -o -a '"password":\["[^"]+"\]' gophish.db
 
Somewhat related: https://github.com/gophish/gophish/issues/1445

Thanks,

Ben

**Comment by jordan-wright** [comment]
Hi @blincoln-dd,

Thanks for reaching out! This is definitely unexpected behavior. The code that handles deleting a campaign can be found [here](https://github.com/gophish/gophish/blob/27553ccc1fd271bad71bef8dd08795daf9dfec8a/models/campaign.go#L555), and it appears we're deleting the `Events` associated with the campaign but it sounds like you're seeing that not happening consistently.

I'll see if I can reproduce this on my end and will report back. Thanks again for getting in touch!

**Comment by cschwartz** [comment]
Hi,

I'm not sure If you had time to dig into this already, but you might want to look at sqlite's `secure_delete` pragma.
If this is not enabled (which is the default, for performance reasons), rows will only be marked as deleted and not zeroed.
If you enable the `secure_delete` pragma, rows to be deleted are zeroed out. The good news is, go-sqlite3 allows to pass pragmas via the connection string, i.e. `"db_path": "gophish.db?_secure_delete=1"` will enable `secure_delete` for the `gophish.db` sqlite database.

I did a quick verification by running a `strings gophish.db | grep <myexamplepassword>` while deleting a campaign with captured (example) passwords with and without `secure_delete` enabled.
The grep did return the password when deleting campaigns without `secure_delete` and did not return the password when deleting with `secure_delete`.

While this addresses the initial issue, I'd guess that using `secure_delete` is probably not an obstacle for an attacker or forensic investigator.

Best,
  Christian

**Comment by moleeon** [comment]
hello there ,I am launching campaigns and the results show only email captured even after ticking the "capture password " box

**Comment by moleeon** [comment]
kindly give possible causes and possible solutions

**Comment by glennzw** [comment]
@moleeon if you're still experiencing this please open a new issue.
