### ISSUE TITLE
Max connections - unencrypted connection OR - x509: certificate is valid for *.123-reg.co.uk, 123-reg.co.uk, not smtp.123-reg.co.uk:465

### ISSUE THREAD

**Issue by timjwardster0** [gophish/gophish#1453]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.7.1

Brief description of the issue: 
Can't sent up a sending profile either on smtp port 25 or 465 with reg123 email account. Used gophish about a a year ago and it worked with same account

What are you expecting to see happen? :
Send test email

What are you seeing happen?
Try smtp and port 25 and get "unencrypted connection" error or if use port 465 get error - "x509: certificate is valid for *.123-reg.co.uk, 123-reg.co.uk, not smtp.123-reg.co.uk:465"

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
time="2019-05-13T16:53:07+01:00" level=info msg="127.0.0.1 - - [13/May/2019:16:53:07 +0100] \"GET /api/smtp/?api_key=962953a73f60b3f7b6f26c6313d765a3d38c456b27603d5374b395833833b17d&{} HTTP/2.0\" 200 687 \"https://127.0.0.1:3333/sending_profiles\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36\""
time="2019-05-13T16:53:12+01:00" level=warning msg="Max connection attempts exceeded - unencrypted connection"
time="2019-05-13T16:53:12+01:00" level=error msg="Max connection attempts exceeded - unencrypted connection"
time="2019-05-13T16:53:12+01:00" level=info msg="127.0.0.1 - - [13/May/2019:16:53:11 +0100] \"POST /api/util/send_test_email?api_key=962953a73f60b3f7b6f26c6313d765a3d38c456b27603d5374b395833833b17d HTTP/2.0\" 500 112 \"https://127.0.0.1:3333/sending_profiles\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36\"" 
```
Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Create send profile with account user name and password
  
 Is there a way to turn off trying to use a secure connection? If i set up outlook as a client to this email address settings are port 25 and "my outgoing server requires authentication". So should work on port 25. The account should allow SSL so I have tried port 465 but with error above.

Hope you can help. I know this is similar to #963 but seems slightly different as not using gmail.

**Comment by jordan-wright** [comment]
Hi @timjwardster0,

Have you tried checking the "Ignore Certificate Errors" checkbox in the sending profile? You can find a (possibly older) screenshot of this [in our documentation](https://docs.getgophish.com/user-guide/documentation/sending-profiles).

**Comment by jordan-wright** [comment]
Closing this since there hasn't been any updates in over a week.
