### ISSUE TITLE
Support for encrypted connections to a mysql db

### ISSUE THREAD

**Issue by cschwartz** [gophish/gophish#1456]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
master

Brief description of the issue: 
Currently no configurations exist to specify the ssl ca (i.e. PEM file) for connections to a mysql db. A configuration via the data source name (`db_path`) string is not possible.

Introducing a new config string which registers the referenced PEM file via `mysql.RegisterTLSConfig` is not terribly complex, and if you're interested I'd love to provide a pull request.

What are you expecting to see happen? :
The config file contains an option which would allow me to specify the path to a PEM file, which in turn would allow me to use the `tls=<custom>` option in the data source name string.

What are you seeing happen?
No such configuration option exist, preventing the use of encrypted mysql connections where the use of a ssl ca is required (i.e. AWS RDS).

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi @cschwartz,

Thanks for reaching out! This sounds great. If you want to take a first pass at it and send up a pull request, I'll help you get things merged in.

Thanks for offering to get this implemented!

**Comment by jordan-wright** [comment]
Closed via 26d99b5a653da4fc5c59d04b262d59aab35c32c9. Thanks again for sending this in!
