### ISSUE TITLE
Landing page images not displaying.

### ISSUE THREAD

**Issue by ppdoyle** [gophish/gophish#1457]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:   0.4 Linux 64bit

Brief description of the issue:   local images are display in preview of landing page but not in campagin

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
<html>
<head>
	<title></title>
</head>
<body>
<p><img alt="" src="/images/logo.png" style="width: 175px; height: 200px;" /></p>

<p>&nbsp;</p>

<p>this is my test page</p>
</body>
</html>

```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
I have tried with link to {{.URL}} and {{.BaseURL}} but it des not work.

**Comment by jordan-wright** [comment]
Hi @ppdoyle,

After putting images in the `static/endpoint/images/` directory, you can reference them using `/static/images/<filename>`. You can find more information [in our documentation](https://docs.getgophish.com/user-guide/documentation/landing-pages#static-assets).

Hope this helps!
