### ISSUE TITLE
Possible to add WWW-Authenticate to Header on landing page?

### ISSUE THREAD

**Issue by ApexAlpha** [gophish/gophish#1458]
What version of Gophish are you using?: latest

Brief description of the issue: 
We want to create a landing page that sends out the WWW-Authenticate header using Basic auth. This is since the page we are trying to simulate also uses this, and our targets use different browsers that make the pop-up unique to each browser. But since GoPhish has its own build in web-server I don't know how to change the equivalent of .htaccess.

Is it possible to change the headers GoPhish send out?

**Comment by jordan-wright** [comment]
Hi @ApexAlpha,

I'm afraid this isn't possible with Gophish right now. We currently don't have the ability to send custom headers when serving the landing pages.

Sorry we couldn't be of more help!
