### ISSUE TITLE
record not found, mail: no angle-addr (same as to #1340 but restarting did not solve issue)

### ISSUE THREAD

**Issue by philberndt** [gophish/gophish#1462]
What version of Gophish are you using?: 
Gophish v0.7.1

Brief description of the issue: 
Can't save Sending Profiles or test email because of error

This is being done in a remote machine

```
level=error msg="record not found"
level=error msg="mail: no angle-addr"

```
What are you expecting to see happen? :
Be able to save and send test email

What are you seeing happen?

I get a console error
```
level=error msg="record not found"
level=error msg="mail: no angle-addr"

```

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
time="2019-05-20T10:16:41Z" level=error msg="record not found"
time="2019-05-20T10:16:41Z" level=error msg="mail: no angle-addr"
time="2019-05-20T10:16:41Z" level=info msg="84.213.51.63 - - [20/May/2019:10:16:41 +0000] \"POST /api/smtp/?api_key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx HTTP/2.0\" 500 74 \"https://myip:3333/sending_profiles\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36\""

```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - enter info
 * Step 2 - save info
 * Step 3 - Send test mail

**Comment by philberndt** [comment]
ok, managed to fix it with Name<email@email.com> in the From field

**Comment by Enachikako** [comment]
Thanks very very much it works

**Comment by adarshvs** [comment]
> ok, managed to fix it with `Name<email@email.com>` in the From field

It is not working for me
