### ISSUE TITLE
python API does not work v2

### ISSUE THREAD

**Issue by misomrk1** [gophish/gophish#1467]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.7.1

Brief description of the issue: Trying to create new profile or campaign from within python, does not seem to work.

What are you expecting to see happen? :to get a new campaign created

What are you seeing happen?
a bunch of JSon errors and crap -see terminal output

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Traceback (most recent call last):
  File "/PycharmProjects/PenTester2.0/phishing.py", line 39, in <module>
    newCampaign()
  File "/PycharmProjects/PenTester2.0/phishing.py", line 38, in newCampaign
    campaign = api.campaigns.post(campaign)
  File "/usr/local/lib/python3.7/dist-packages/gophish/api/campaigns.py", line 20, in post
    return super(API, self).post(campaign)
  File "/usr/local/lib/python3.7/dist-packages/gophish/api/api.py", line 92, in post
    raise Error.parse(response.json())
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Looked up documentation on gophish python API
 * Step 2 - FIlled with my actual testing profiles, pages and usergroups
* Step 3 - tried running, got all that crap mentioned above

**Comment by jordan-wright** [comment]
Hi @misomrk1,

Thanks for getting in touch. Do you see any output in your Gophish terminal that may indicate where the issue could be?

**Comment by misomrk1** [comment]
Hi @jordan-wright,

As I am trying to create python program to implement gophish, the only output I get (running my py script) is as statet above. That is what I got for just using the code from documentation 
`def newCampaign():
    groups = [Group(name='testgroup')]
    page = Page(name='Linkedin')
    template = Template(name='Linkedin')
    smtp = SMTP(name='LinkedIN')
    url = 'http://192.168.1.20'
    campaign = Campaign(
        name='Example Campaign', groups=groups, page=page,
        template=template, smtp=smtp)
    campaign = api.campaigns.post(campaign)

`

**Comment by jordan-wright** [comment]
@misomrk1 What I meant was do you see any logs in the terminal of the server where Gophish is running? The server, not the client.

**Comment by misomrk1** [comment]
@jordan-wright  
All that I get in terminal is 

> root@kali:~/gophish-v0.7.1-linux-64bit# ./gophish
time="2019-05-29T16:16:44+02:00" level=warning msg="No contact address has been configured."
time="2019-05-29T16:16:44+02:00" level=warning msg="Please consider adding a contact_address entry in your config.json"
time="2019-05-29T16:16:44+02:00" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
goose: no migrations to run. current version: 20180830215615
time="2019-05-29T16:16:44+02:00" level=info msg="Starting phishing server at http://0.0.0.0:80"
time="2019-05-29T16:16:44+02:00" level=fatal msg="listen tcp 0.0.0.0:80: bind: address already in use"

just running it on my localhost kali machine

**Comment by jordan-wright** [comment]
> time="2019-05-29T16:16:44+02:00" level=fatal msg="listen tcp 0.0.0.0:80: bind: address already in use"

This suggests that Gophish may not be fully starting since something is already listening on TCP port 80. It's possible the admin server is still starting, so that may be a red herring, but worth looking into.

The next thing to double-check is to ensure that you've made all the objects you're using. For example, is there a group already created named `testgroup`, a landing page already created named `Linkedin`, etc.?

**Comment by misomrk1** [comment]
@jordan-wright 
it was already running process of gophish, just did not have the terminal open (thus could not get the terminal output). Killed and rerun, and servers both started fine. Upon posting the create new campaign request, it said it could not find campaign? Obviously it could not find it if I am trying to create it 

> root@kali:~/gophish-v0.7.1-linux-64bit# ./gophish
time="2019-05-29T19:58:59+02:00" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
time="2019-05-29T19:58:59+02:00" level=warning msg="No contact address has been configured."
time="2019-05-29T19:58:59+02:00" level=warning msg="Please consider adding a contact_address entry in your config.json"
goose: no migrations to run. current version: 20180830215615
time="2019-05-29T19:58:59+02:00" level=info msg="Starting phishing server at http://0.0.0.0:80"
time="2019-05-29T19:58:59+02:00" level=info msg="Starting admin server at https://127.0.0.1:3333"
time="2019-05-29T19:59:42+02:00" level=info msg="127.0.0.1 - - [29/May/2019:19:59:42 +0200] \"GET //api/campaigns/ HTTP/1.1\" 301 0 \"\" \"python-requests/2.21.0\""
time="2019-05-29T19:59:42+02:00" level=info msg="127.0.0.1 - - [29/May/2019:19:59:42 +0200] \"GET /api/campaigns/ HTTP/1.1\" 200 54930 \"\" \"python-requests/2.21.0\""
time="2019-05-29T19:59:42+02:00" level=info msg="127.0.0.1 - - [29/May/2019:19:59:42 +0200] \"GET //api/groups/ HTTP/1.1\" 301 0 \"\" \"python-requests/2.21.0\""
time="2019-05-29T19:59:42+02:00" level=info msg="127.0.0.1 - - [29/May/2019:19:59:42 +0200] \"GET /api/groups/ HTTP/1.1\" 200 403 \"\" \"python-requests/2.21.0\""
time="2019-05-29T19:59:45+02:00" level=info msg="127.0.0.1 - - [29/May/2019:19:59:45 +0200] \"POST //api/campaigns/ HTTP/1.1\" 403 31 \"\" \"python-requests/2.21.0\""
time="2019-05-29T19:59:59+02:00" level=error msg="record not found: campaign not found"
time="2019-05-29T19:59:59+02:00" level=error msg="record not found"
time="2019-05-29T19:59:59+02:00" level=warning msg="record not found"
time="2019-05-29T19:59:59+02:00" level=warning msg="record not found"

**Comment by jordan-wright** [comment]
One thing to note is that it appears my example is incorrect, in that there should be a `url` parameter passed when creating the `Campaign` object, though I don't think that's what's breaking things here.

I'm afraid this appears to be a case where logging on the Gophish side should be improved. From what I can tell, the error you're getting back from Python suggests that you're sending a campaign and receiving a non-200 response (from the Gophish output, I see reference to a `403`, but it's not really clear why you'd be getting that since I'm assuming the API key is being sent correctly). Then, when it's trying to parse the JSON, it's failing since the response being returned - for some reason - isn't JSON.

To further troubleshoot, my recommendation would be to find the folder where the Gophish Python API is stored (appears to be `/usr/local/lib/python3.7/dist-packages/gophish/api/`, and add something like `print(response.text)` above line 92 (which should say `raise Error.parse(response.json())`) in `api.py`. This will dump out the raw response you're getting back from Gophish which might help give more information.

**Comment by misomrk1** [comment]
@jordan-wright 
Hi Jordan, does not seem to print anything at all, what have I noticed today is, when I try to add the campaign and print it (as shown the function above) it prints one thing : 


>  /usr/bin/python3.7 /PycharmProjects/PenTester2.0/phishing.py
> /usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning)
> /usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning)
> Linkedin
> LinkedinTRY2
> Copy of Linkedin
> Copy of Copy of Linkedin
> /usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning)
> /usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning)
> testgroup has 2 users
> /usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning)
> Forbidden - CSRF token invalid
> 
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
>     return self.func(*args)
>   File "/PycharmProjects/PenTester2.0/phishing.py", line 40, in newCampaign
>     campaign = api.campaigns.post(campaign)
>   File "/usr/local/lib/python3.7/dist-packages/gophish/api/campaigns.py", line 20, in post
>     return super(API, self).post(campaign)
>   File "/usr/local/lib/python3.7/dist-packages/gophish/api/api.py", line 93, in post
>     raise Error.parse(response.json())
>   File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
>

**Comment by jordan-wright** [comment]
Hmmm... It's odd that you'd be seeing that message, since the `/api` routes are exempt from the CSRF protections.

My only guess at this point is that there is a bug in the API client in how the endpoints are built. You'll see that the request is being made for `//api/campaigns` which isn't correct (should be `/api/campaigns`). I'll see if I can validate that on my end and will push up a fix.

**Comment by misomrk1** [comment]
Thanks Jordan, I did not notice this, indeed seems it has been the issue, as removing a slash in line 7 of campaigns.py in front of api seems to have done the trick - I believe this will be the same for all the rest of issues of the same nature (adding groups and so on) 

Solution - Open the file giving you the issue, edit the line

> class API(APIEndpoint):
>     def __init__(self, api, endpoint='/api/campaigns/'):
>         """ Creates a new instance of the campaigns API """

and remove the '/' in front of api to make it look like

>     def __init__(self, api, endpoint='api/campaigns/'):

I believe this solves the issue and we can close it now?
