### ISSUE TITLE
Customizing Events and Results CSV

### ISSUE THREAD

**Issue by hahnsolo13** [gophish/gophish#1471]
What version of Gophish are you using?: 0.6.0

Brief description of the issue: Not really an issue, more of an enhancement. Is it possible to customize what would be exported in results.csv or events.csv? For example, add a position column in the events.csv.

What are you expecting to see happen? : Customize-able reports. 

***Everything below NA***

What are you seeing happen? 

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by H4xl0r** [comment]
there is a tool for working with gophish outputs !

**Comment by jordan-wright** [comment]
Yep! As @H4xl0r mentioned, [GoReport](https://github.com/chrismaddalena/Goreport) is a good candidate for this. Really the event export is just a wrapper around the existing API, so if you have custom needs, I'd recommend using the API directly.
