### ISSUE TITLE
Unable to pass JSON Body through Powershell

### ISSUE THREAD

**Issue by Gummidali** [gophish/gophish#1474]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.7.1

Brief description of the issue: 
Using Invoke-RestMethod in powershell to pass JSON packages to the GoPhish server appears to not be working, It's giving an "Invalid JSON structure" error.
In this case when trying to create a new Group.

What are you expecting to see happen? :
A success message and a new group created on the server.

What are you seeing happen?
"message": "Invalid JSON structure",
"success": false,
"data": null

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Invoke-RestMethod -Method Post -Uri "https://<redacted>:3333/api/groups/" -Body (ConvertTo-Json $GPhishGroupBody) -Headers $ApiKey

The converted Body:
}
    "name":  "totallyuniquename",
    "targets":  [
                    {
                        "first_name":  "test",
                        "last_name":  "testesen",
                        "email":  "test@testesen.com",
                        "position":  ""
                    },
                    {
                        "first_name":  "rolf",
                        "last_name":  "rolfberg",
                        "email":  "rolf@rolfberg.org",
                        "position":  ""
                    }
                ]
}
```

Please provide any terminal output that may be relevant below:

```
  "message": "Invalid JSON structure",
  "success": false,
  "data": null
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Just ran the command above, after creating the body

**Comment by jordan-wright** [comment]
Hi @Gummidali,

Thanks for reaching out! Your JSON looks right, so my guess is that Gophish isn't seeing this as a JSON HTTP request. Do you see different results using `-ContentType 'application/json'`?

**Comment by Gummidali** [comment]
> Hi @Gummidali,
> 
> Thanks for reaching out! Your JSON looks right, so my guess is that Gophish isn't seeing this as a JSON HTTP request. Do you see different results using `-ContentType 'application/json'`?

Yes, that looks to have got the issue sorted.
Thanks!
