### ISSUE TITLE
Group email check

### ISSUE THREAD

**Issue by Seronsecurity** [gophish/gophish#1475]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.7.1

Brief description of the issue: 
When you create a new user in a group, there is no validation checks for email address - and maybe others?

What are you expecting to see happen? :
error - this is not a valid email address

What are you seeing happen?
Nothing

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Create New Group
 * Step 2 - Add user (manually)
 * Step 3 - Fill out name and email address
 * Step 4 - Click Add+
 * Step 5 - No error generated  (and no apparent way to edit user?)

**Comment by jordan-wright** [comment]
All fixed! Thanks for the heads up.
