### ISSUE TITLE
Idea of improvement for credentials analyzing

### ISSUE THREAD

**Issue by ZigzagSecurity** [gophish/gophish#1478]
Hi there, 
Firstly I would greatly thank you for that tool, it's amazing to use ! 

I've been confronted to a little problem though, it's the lack of encryption for the passwords storage. 
But i've came out with something that some other people would may like too (if they've not already done it).

I really wanted to have some statistics on the password but I was not willing to store them in plain text. So i used a little bit of HTML and JS to get it out. 
I was spoofing the Outlook connection page and it uses Javascript to submit the credentials. 

## HTML modifications
![html_code](https://user-images.githubusercontent.com/40743997/58864176-8d0a2b80-86b4-11e9-964f-df503071efc0.PNG)

Here are some hidden input that will be passed to the post request and intercepted by GoPhish since it captures everything that has a name attribute in the form. 
It's completely transparent for the user and the value is added by some lines of Javascript.

## Javascript modifications
So I added some lines to the submition method. 
Here they are : 

![js_code](https://user-images.githubusercontent.com/40743997/58864654-68fb1a00-86b5-11e9-9b5b-249ec39ab679.PNG)

They are getting the value of the password, and passing it through some regex to have intels on the password complexity. I also replace each characters by a * to be sure it's not put in the database but it's possible to keep it clear or obfuscate it or whatever you can imagine. 

Then everything is put in the differents hidden inputs and the request is send to the server. 

## The captured datas

Back in the campaign results when someone submit their credentials every thing is captured and display in the normal array. With those datas we can almost be sure if the password is legit or if the user were just trolling us. 

![results](https://user-images.githubusercontent.com/40743997/58865061-238b1c80-86b6-11e9-8926-82ee1df47e09.PNG)

That's it, if you see any kind of ways this would be useful for you or anyone else, I let you do whatever you want with the idea and the code. 

Cheers !
Zigzag

**Comment by jordan-wright** [comment]
Hi @ZigzagSecurity,

Thanks for letting the community know about this approach- great work!

While I don't anticipate adding this natively to Gophish, I am always open and appreciative to this community for sharing how they're using Gophish to meet their needs when running phishing simulations.

Regarding storing encrypted credentials, the good news is that there is an open PR at #1314 that I plan to finishing reviewing and merging when I get a chance.

Thanks again for sending this over!
