### ISSUE TITLE
Feature Request - Reporting

### ISSUE THREAD

**Issue by quintingsnj** [gophish/gophish#1479]
Hi there. I note that there is a column for "reported", but it doesn't have any use at the moment (that I can see - if I am wrong, please correct me). What I am wondering is, until it is fully implemented, maybe make a checkbox that we can check off when an end user contacts IT to report this spam. We have a spam reporting system in our office, I get all of them, and then I submit them to our spam vendor for analysis, so I see the ones that get reported that are part of a GoPhish campaign, so it would be easy for me to just check off in the web interface that Bill reported the spam. Right now I keep a separate record of it, but would be nice if it had this capability, then I would have that data in the same place as the rest of the campaign.

Thanks!

**Comment by quintingsnj** [comment]
Actually, just realized that there is a way to get the reported count into the GoPhish database. 

http://server/report?rid=123456

Where server is your server, and the rid is the unique ID that each use gets for that campaign - I use my email log to get that info...a little tedious, but we are not a large organization, so this works for now :)

Something more automated would be nice :)

**Comment by antonio-bcn** [comment]
Hi, I'm trying to use the user-reporting feature. The action "report this mail" is properly counted and visualized in the statistics, but once the use clicks on the link he goes to a blank page. Would it be possible to create a specific landing page or at least to send the user to the landing page of the campaign?

Thanks. If I had to open a new issue, please let me know.

**Comment by jordan-wright** [comment]
Hi there!

A short term solution to this was merged in #1772. It will be included in the next release.

Thanks for sending this in!
