### ISSUE TITLE
difference between raw and final cvs

### ISSUE THREAD

**Issue by cka1906** [gophish/gophish#1480]
What version of Gophish are you using?: 
0.7.1
Brief description of the issue: 
We see a diffrence in clicked and open results in the cvs files raw and final
What are you expecting to see happen? :
in raw there is 74 rows with clicked on link but in final.cvs there is only 47? and there is no duplicates
in the dashboard it shows 74, what is correct

**Comment by jordan-wright** [comment]
What is "final.cvs"?

**Comment by cka1906** [comment]
it is the on of the cvs files, that you can get from the system, also called results and raw events.

**Comment by jordan-wright** [comment]
So `results.csv` only has the final status of each recipient (e.g. "Clicked Link"), whereas `events.csv` is every event recorded by Gophish (e.g. "Email Opened" and "Clicked Link"). This is why it makes sense that there would be more records in events.csv.
