### ISSUE TITLE
Idea for Improvement for Spear Phishing and Campaigns

### ISSUE THREAD

**Issue by newbcore** [gophish/gophish#1481]
First off, I wanted to say that I found this and love it, it is truly an amazing tool. It is better then any service I have used, thank you for all your hard work on this!

What version of Gophish are you using?: 
0.7.1

Brief description of the improvement: 
When adding individuals into Users & Groups, there are fields for First/Last/Email/Position. However, I do like to perform spear phishing attacks, simulating emails coming from employees managers. In order to do this, I must create an email template per each manager. Since we have 10 departments, that is 10 separate templates. If I could upload the managers name with the employee, this could be greatly streamlined. I know I could use the position field, but I already use that as well.

Also, is there anyway to randomize templates being sent? So that I do not need to manually segregate groups to send several templates, but load the templates to send into the campaign and for randomized sending? For example, if I have 3 templates I wish to send to a group of people, I must first create the separate groups, then create 3 campaigns. It would be a lot simpler if a campaign could hold several email templates to send.

**Comment by jordan-wright** [comment]
Hi @newbcore,

Thanks for reaching out!

I'm afraid there isn't a way to randomize the templates being sent. Perhaps in the future I'll consider adding this when revamping the way campaigns are built, but I'm afraid I don't have a timeline if/when this would be done.

For now, I'd recommend launching multiple campaigns and aggregating the results together as needed. The API can be used to make this quite a bit easier.

Sorry I couldn't be of more help!

**Comment by newbcore** [comment]
Hello,




I completely understand! I just thought I'd throw a suggestion. I have a little development background, though nothing major. If you'd like, I also have someone much better than I who absolutely love GoPhish. We used vendors, and ditched those because of this. We'd be more then happy to help in any way with this project!




Get Outlook for Android







On Mon, Jun 10, 2019 at 7:28 PM -0500, "Jordan Wright" <notifications@github.com> wrote:












Closed #1481.
