### ISSUE TITLE
Notifications on realtime events

### ISSUE THREAD

**Issue by nahojster** [gophish/gophish#1483]
Hello!

First of all thank you for an excellent tool, I really appreciate your hard work. Is there a way to contribute in any other ways besides what is mentioned in the contributing guidelines? Such as donations?

To the real question at hand, in my organization our goal is to totally automate GoPhish. Meaning we just want to let the application run and randomly generate campaigns based off of a user pool. A great feature for our purpose would be receiving notification upon campaign events, so if a user submits data a notification is sent to us. I searched the repo and found no mentions of this earlies, perhaps others would also benifit from this feature? Thanks again for your time!

**Comment by jordan-wright** [comment]
Hi there!

Eventually I might create some kind of campaign orchestration within Gophish, but for now this is 100% a use case for [the API](https://docs.getgophish.com/api-documentation/), since it allows you to automate all aspects of Gophish however you'd like.
