### ISSUE TITLE
Gophish Campagin

### ISSUE THREAD

**Issue by Graz1991** [gophish/gophish#1487]
Hi,
#
I have installed gophish on the VPS (using Digital Ocean). I can successfully log in using my ip address following change to my config file.

{
        "admin_server" : {
                "listen_url" : "0.0.0.0:3333",
                "use_tls" : false,
                "cert_path" : "example.crt",
                "key_path" : "example.key"
        },
        "phish_server" : {
                "listen_url" : "0.0.0.0:80",
                "use_tls" : false,
                "cert_path" : "example.crt",
                "key_path": "example.key"
        },
        "smtp" : {
                "host" : "smtp.example.com:25",
                "user" : "username",
                "pass" : "password"
        },
        "db_path" : "gophish.db",

I set up all the necessary details and my URL is set to my server IP address. I can successfully send a campaign however the server is not logging the statistics. The campaign status is still Email sent even though several users are clicking on the e-mail link.

Can you please advise?

Thank you.

BR,
Graziella

**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue: 

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi there!

You can find information on how to troubleshoot this type of scenario [in our documentation](https://docs.getgophish.com/user-guide/faq#events-arent-showing-up-on-the-dashboard).

If things still don’t work after following those steps, let us know what errors you’re seeing and we can reopen this issue and continue troubleshooting.

Hope this helps!
