### ISSUE TITLE
Link Opend = Mail Opend 

### ISSUE THREAD

**Issue by H4xl0r** [gophish/gophish#1489]
What version of Gophish are you using?: 
newest

Brief description of the issue: 

When sending mails with tracking image, some "targets" not allow pictures (tracking of mail open is not working then) , but they click the link.

now the details page shows up : Mail send ----> link clicked ---> Useragent.

What are you expecting to see happen? : 

When the "target" clicks the link , the system should recognize the click as mail opend and link clicked ! there is no other way for the "target" to get the link! .

**Comment by jordan-wright** [comment]
Hi there,

In the UI we do exactly that via Javascript, but we purposefully don't create artificial events in the database. This is because I want the database to reflect what Gophish recorded to maintain accuracy of the data.

I hope this helps!
