### ISSUE TITLE
Admin password change leads to empty password

### ISSUE THREAD

**Issue by Daxda** [gophish/gophish#149]
I fiddled around with your awesome framework and encountered a bug(?).
When logging in with the default credentials and then attempting to change the password of the admin account you are able to leave the new password value blank. When logging out and attempting to logg back into the account you are unable to do so because the password value has been changed to an empty password.

You are able to circumvent this by removing the `required` tag inside the login form - which allows you then to login without a password.

**Comment by jordan-wright** [comment]
Interesting. We probably don't want the password to be blank. I will look into the error handling in that regard.

Thanks for the report!
