### ISSUE TITLE
How Can Gophish  Blocked users by IP address?

### ISSUE THREAD

**Issue by greyredfox** [gophish/gophish#1490]
Hello
Thx for it is wonderful tools as GoPhish it works very good!
But I have one problem
When I started my Gophish company, send messages to users, service mail-bot, for example Google Bot or Yahoo Bot go to my landing page via link, which I input into my messages, and add website to BlackListed!!!
How I can disallow access by some IP-address? That Bot cann't go to my landing-gophish page and don't block it.
Thx!

**Comment by jordan-wright** [comment]
Hi there,

This isn't possible within Gophish. I recommend using your firewall to block incoming hosts by IP address.
