### ISSUE TITLE
gophish error

### ISSUE THREAD

**Issue by vasanth9** [gophish/gophish#1491]
when i run ./gophish command it gives following and terminates

time="2019-06-20T18:07:31+05:30" level=warning msg="No contact address has been configured."
time="2019-06-20T18:07:31+05:30" level=warning msg="Please consider adding a contact_address entry in your config.json"
time="2019-06-20T18:07:31+05:30" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
goose: no migrations to run. current version: 20180830215615
time="2019-06-20T18:07:31+05:30" level=info msg="Starting phishing server at http://0.0.0.0:80"
time="2019-06-20T18:07:31+05:30" level=info msg="Creating new self-signed certificates for administration interface"
time="2019-06-20T18:07:31+05:30" level=fatal msg="listen tcp 0.0.0.0:80: bind: permission denied"

**Comment by jordan-wright** [comment]
Hi there,

This means that the user running Gophish doesn't have permission to bind to a privileged port. This has been asked multiple times in the past, so you can find more information [here](https://github.com/gophish/gophish/search?q=permission+denied&type=Issues).
