### ISSUE TITLE
Not seeing GoPhish stats once campaign is launched

### ISSUE THREAD

**Issue by brcced** [gophish/gophish#1492]
Hi

I am new to this blog so bear with me if I am screwing up.  Some History...my Boss read about GoPhish being a viable method to teach users to spot spams or scams.  Been working on this for over two months and the only thing stopping me is getting a campaign to work with stats on email sent, email open, link clicked etc etc..

Here's a snapshot screen running GoPhish

![Gophish console](https://user-images.githubusercontent.com/52040669/59854712-6c430680-9341-11e9-9136-bce5725ebc6c.JPG)

Some background info...
Running GoPhish on Windows 10 (we cannot afford server licenses as we are a non-profit org).  Searching for info is geared to Unix, Linux, Ubuntu, Windows Server but only scant info on Windows 10 Pro.  Currently in DMZ and running Exchange Server 2010 with strict controls regarding downloading pictures (must click to open).

Any tips or advice would help as I am currently stuck.

Thanks Basil

**Comment by jordan-wright** [comment]
Hi there,

We'll need more information about how you have things set up in order to help you troubleshoot. For example, what URL are you using when building a campaign? Is that reachable by the people receiving the email?

You can find more information on how to troubleshoot this issue [in our documentation](https://docs.getgophish.com/user-guide/faq#events-arent-showing-up-on-the-dashboard).

**Comment by brcced** [comment]
For the URL I am using laptop's IP address where GoPhish resides.  Using 192.168.0.228.  As for it being reachable that is a good question and do not have an answer.

**Comment by brcced** [comment]
Just did a campaign using What's my IP address 199.243.73.62 for the URL and no stats are showing up.  Here's the email tracker info...
mg alt="" src="http://199.243.73.62/track?rid=n65cXSM" style=""> </div>

**Comment by S0larflare** [comment]
If you click the link in the email you’ve created, do you go to http://199.243.73.62/?rid=n65cXSM? Do you see your landing page?

Sent from my iPhone

On 25 Jun 2019, at 19:16, brcced <notifications@github.com<mailto:notifications@github.com>> wrote:


Just did a campaign using What's my IP address 199.243.73.62 for the URL and no stats are showing up. Here's the email tracker info...
mg alt="" src="http://199.243.73.62/track?rid=n65cXSM" style="">

**Comment by brcced** [comment]
Thanks Solarflare.  Unfortunately I am done and closing down right now.  Will do this on Thursday as I only work Tue and Thurs (part time).

Will respond back…Basil

**Comment by brcced** [comment]
Hi...tried both http and https.  Http gives me a 404 page not found.  Https gives me "Hmmm can't reach page".

Here's a portion of the email sent for testing purpose to me...
![Test Campaign Email](https://user-images.githubusercontent.com/52040669/60271107-bd15aa80-98bf-11e9-98e9-021ce6e4183b.JPG)
You will notice at the bottom there is a funny looking box.  That box contains the address http://199.243.73.62/?rid=n65cXSM

Is the email correct?

**Comment by S0larflare** [comment]
The funny looking box is the tracking pixel. It isn’t being rendered as it is being blocked by your email client.

The url you are using, how are you putting that in? Are you putting {{.URL}} in the email template and specifying http://199.243.73.62 as the campaign url when you set up the campaign?

Sent from my iPhone

On 27 Jun 2019, at 14:44, brcced <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi...tried both http and https. Http gives me a 404 page not found. Https gives me "Hmmm can't reach page".

Here's a portion of the email sent for testing purpose to me...
[Test Campaign Email]<https://user-images.githubusercontent.com/52040669/60271107-bd15aa80-98bf-11e9-98e9-021ce6e4183b.JPG>
You will notice at the bottom there is a funny looking box. That box contains the address http://199.243.73.62/?rid=n65cXSM

Is the email correct?

**Comment by brcced** [comment]
Yes both http and https using 199.243.73.62 in campaign URL section.  As for email the link for T4Slip is pointing to www.bobrumball.org/phish/clickitbait.html

I take it that I must create email HTML link inside GoPhish and not actually on the Website.  Used website to stash html as I could not even get it to display.  Will revert back if the answer you give me is to stash HTML inside GoPhish.  Now that I can see the IP address showing up as it was showing up blank.

As for the box not rendering properly what can I do so that it is getting render properly?

**Comment by brcced** [comment]
Did a test using http://199.243.73.62/?rid=n65cXSM it does not show up in gophish cmd prompt.  However if I use http://192.168.0.228/?rid=n65cXSM this shows up in gophish cmd prompt saying 404 19.  When I ping 199.243.73.62 it is reachable but when I ping 192.168.0.228 it says Request timed out.  Hence for having trouble getting this to work.

**Comment by brcced** [comment]
Interesting...did a test and notice that if I use http://199.243.73.62 as my campaign URL it is now showing 1 Email open but not showing stats on clicking the link.  I need pointers on how to have my links working.

**Comment by jordan-wright** [comment]
You need to use the `{{.URL}}` template tag in your email template. When you create your campaign, the URL you use needs to both be reachable by the recipients and point to the Gophish server.

**Comment by brcced** [comment]
I changed ip address and used {{.URL}} and it is working however it is coming back with a 404 page not found.  Making great progress and hopefully have this thing working soon.  I am using Windows 10 Pro.  Any ideas on how I can get the page to display?
Here's what it is showing in address bar
http://199.243.73.62/?rid=1mVrHED/static/clickbaitit.html  which comes back as "404 page not found"

**Comment by brcced** [comment]
Sorry typed in wrong address should be http://199.243.73.62/?rid=1mVrHED/gophish/static/clickbaitit.html

**Comment by brcced** [comment]
Hi...figured out what to do.  In the Link dialogue, pick http and what goes inside the box is {{.URL}}.  Got the Clicked Link stat to work.  Thanks Guys

**Comment by mrpaddy35** [comment]
> Hi...figured out what to do. In the Link dialogue, pick http and what goes inside the box is {{.URL}}. Got the Clicked Link stat to work. Thanks Guys

Hi @brcced what exactly you did ? i am having the same issue
