### ISSUE TITLE
Feature Request: Move Landing Page Redirection to Campaign Creation

### ISSUE THREAD

**Issue by pat-inthe-hat** [gophish/gophish#1493]
Currently 'redirects' are specific to each Landing Page. By moving the 'redirect' configuration to the 'New Campaign' creation, it would allow landing pages to be reused/re-purposed, i.e. using the same landing page for multiple campaigns over disparate recipients.

**Comment by jordan-wright** [comment]
Hi there,

I can see your point, but at the same time some people might say that when they want to use a landing page, they always want it to redirect to the same URL so they don't want to input that every time they create a campaign.

With this in mind, I don't think I'm going to change this at this time. I appreciate you bringing this up, and please keep the ideas coming!

**Comment by S0larflare** [comment]
Just wondering, how about doing both? Have the default redirect set in the landing page, but give the ability to override that upon campaign creation? Not sure how easy this would be as I can’t remember where it’s handled in the code, but if the campaign creator had another field added with the redirect url in it, which is auto-populated by the default value from the landing page, then you could perhaps make things a bit more flexible for everyone?

Sent from my iPhone

On 21 Jun 2019, at 02:01, Jordan Wright <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi there,

I can see your point, but at the same time some people might say that when they want to use a landing page, they always want it to redirect to the same URL so they don't want to input that every time they create a campaign.

With this in mind, I don't think I'm going to change this at this time. I appreciate you bringing this up, and please keep the ideas coming!
