### ISSUE TITLE
[Feature] Prevent the "popup" to close on missclick

### ISSUE THREAD

**Issue by maxlehot1234** [gophish/gophish#1494]
Is it possible to prevent the pipup when we create a template, campaings, etc to close if we missclick outside the popup?

It could be really cool ;)

**Comment by jordan-wright** [comment]
Hi there,

This was fixed back in ebc099b it just hasn't made it into a release yet.

**Comment by maxlehot1234** [comment]
Thats why :P

Hope it will become available in releases ;)

Thanks
