### ISSUE TITLE
GoPhish campaigns

### ISSUE THREAD

**Issue by simbamatema** [gophish/gophish#1496]
Got a campaign running until end of July for a set of users. It has scheduled the campaigns for each user account, evenly over the period. 

I want emails to be sent out daily for the users, instead of once over a period.

How do i go about doing that?

**Comment by jordan-wright** [comment]
Hi there!

All we support right now is evenly sending out emails between the start date and finish date. We don’t currently have the ability to send emails at one particular time each day.

Sorry we couldn’t be of more help! If I interpreted your question wrong, please let me know.
