### ISSUE TITLE
Cannot change the "admin" user name

### ISSUE THREAD

**Issue by eitancaspi** [gophish/gophish#1499]
Hi,

I use version 0.7.1 64 bit under windows 10 64 bit.

The GUI allows to change the name of the default "admin" user and submitting this change (with a password change) result in a success message, but navigating away from the user settings page and back to it shows the user stayed "admin".

Also, it is not possible to change only the user name - user is forced to change the password as well. Not so friendly - please enable to change only the user's name, without forcing a password change.

Thanks!

Eitan

**Comment by jordan-wright** [comment]
Hi there,

This is available in the current source, but hasn’t made it isn’t a release yet.

Thanks for getting in touch!
