### ISSUE TITLE
Import Email From IMAP

### ISSUE THREAD

**Issue by jordan-wright** [gophish/gophish#15]
It would be a neat feature to be able to connect to a users email (given credentials) to automatically import a template from their mailbox.

That would make it easier then "View Source" from the email.

**Comment by ethack** [comment]
What about creating a new email account specifically for gophish?  When you want to create a template you could just forward an email to that account, gophish will see the incoming email, and automatically import the email as a template.

Spam could be an issue.  Or not.  If you received any, then all of a sudden you've got some realistic phishing templates.

**Comment by jordan-wright** [comment]
This would be a **great** idea for a hosted solution. I considered offering something like this, but I think it falls under the same idea as having some domains people could use to do their phishing.

My assumption is that this, like most security tools, will inevitably be a  double-edged sword. If I host domains or email addresses bad guys use to do some of this stuff, it comes back on me. Instead, if I leave domain management, email management, etc. up to the user - it's on them.

However, that being said, I am still considering a hosted solution (might as well try to monetize this somehow without making it closed-source), and a gophish-specific email would be a great addition to that toolset.

**Comment by jordan-wright** [comment]
Going ahead and closing this, since I don't see us having the time to implement it. This would require a full UI to choose the email you want, which would basically require us to implement an entire imap browser.
