### ISSUE TITLE
Many issues

### ISSUE THREAD

**Issue by olivier2557** [gophish/gophish#150]
I have so many issues that I don't know where to start.

- If I have a tag {{.From}} in a mail template, the rendered mail will end-up at the position of the tag.

- I am seeing two different email when send by testing email server and by launching the campain:

  Test: 
</head>
<body>
<p>Dear o n,</p>

<p>Position l</p>
...

  Real campain:
<html>
<head>
	<title></title>
</head>
<body>
<p>Dear Olivier Nicole,</p>

<p>Position
and nothing more.

- Whatever landing page I created, I don't manage to access them through a webbrowser. I don't really get the logic between the name of the landing page and the URL to use.

Thank you.

**Comment by jordan-wright** [comment]
Hi Oliver,

When you send a test email, you put whatever you want into the "To" fields (first name, etc.). My guess is that in your group you have a member named "Olivier Nicole", but in your test email you just sent it to "o n", which explains the discrepancy in the output.

When you say "If I have a tag {{.From}} in a mail template, the rendered mail will end-up at the position of the tag.", what do you mean? Are you saying the address you provide is also in the output?

**Comment by olivier2557** [comment]
Hi Jordan,

I apologize for being confusing.

> When you send a test email, you put whatever you want into the "To" fields (first name, etc.). My guess is that in your group you have a member named "Olivier Nicole", but in your test email you just sent it to "o n", which explains the discrepancy in the output.

I meant that the difference was not on the name of the recipient, but on the fact that for some reason the {{.Popsition}} tag aborted the email (in the real campain it should read "Position lab sup"). See another example below.

> When you say "If I have a tag {{.From}} in a mail template, the rendered mail will end-up at the position of  the tag.", what do you mean? Are you saying the address you provide is also in the output?

The email template is of the sort: 
`Dear {{.FirstName}} {{.LastName}},`
` `
`Send by {{.From}}`
` `
`Position {{.Position}}`
` `
`{{.URL}}`

On the test email I get:

`...`
`<p>Dear Olivier Nicole,</p>`
` `
`<p>Send by` and nothing more, this is the end of the mail.

On the real campain I get:

`...`
`<p>Dear Olivier Nicole,</p>`
` `
`<p>Send by Pierre KJir</p>`
` `
`<p>Position` and nothing more.

Both being quite incomplete.

I will try to install the pre-compiled binaries.

**Comment by jordan-wright** [comment]
I'll take a look at the ```{{.From}}``` issue - we might be missing it in our test emails.

Does your group members have Position attributes? If this isn't provided and you specify the ```{{.Position}}``` template variable, the email will likely be cut short. You should see some kind of error message in the console output.

**Comment by olivier2557** [comment]
> I'll take a look at the {{.From}} issue - we might be missing it in our test emails.

I get the error:
`2016/02/16 10:56:02 worker.go:185: Creating email using template`
`2016/02/16 10:56:02 worker.go:196: template: html_template:8:13: executing "html_template" at <.From>: From is not a field of struct type *models.SendTestEmailRequest`

> Does your group members have Position attributes? If this isn't provided and you specify the {{.Position}} template variable, the email will likely be cut short. You should see some kind of error message in the console output.

Yes, I made sure to fill in all the attributes.

`2016/02/16 10:56:38 worker.go:94: template: html_template:10:14: executing "html_template" at <.Position>: Position is not a field of struct type struct { models.Result; URL string; TrackingURL string; Tracker string; From string }`

I could not use the binary distribution because of the certificate on email server (issue #146)

**Comment by jordan-wright** [comment]
Sure enough.. Looking at the code I think these are all valid bugs. How odd! I could have sworn I tested with a position...

I'll see what I can do to reproduce and will file bugs as needed.

Thanks for the report!

**Comment by jordan-wright** [comment]
I've created two separate issues for these. We'll work out of those for resolution, and will close this question down for now.

Thanks for the report!
