### ISSUE TITLE
Sender Profile Error and email error

### ISSUE THREAD

**Issue by bmpentesting** [gophish/gophish#1502]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
V 0.7.1 on Kali Linux using Digital Ocean VPS and hosted on my domain
Brief description of the issue: 
When creating "Sending Profiles", I always faced an error like maximum something and I guess it's because of using "@gmail.com." So, i used some other smtp servers like from smtp2go and sendgrid and it works. However, in the campaign page, the status for the mail always said error, it never sends successfully.
What are you expecting to see happen? :
I want to see my mail sent successfully
What are you seeing happen?
My mail is error
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Without seeing the exact error, I'm afraid there isn't anything we can do to help. "maximum something" doesn't give us information to go off of. Then not knowing the error message you see when you say "the status for the mail always said error" also makes it difficult to troubleshoot.

I'm afraid that unless you can provide more information on what you're seeing, there isn't a way to troubleshoot the issue.
