### ISSUE TITLE
how to exclude the ability to view captured data ?

### ISSUE THREAD

**Issue by GGfallin** [gophish/gophish#1503]
Good afternoon. I need to exclude the possibility of viewing the captured data of the employee who entered them on the Landing Page, but on the Dashboard should still be information that the employee still entered their data. How can I do that ?

**Comment by jordan-wright** [comment]
I'm afraid this isn't possible with Gophish after the data has been collected. When you created the landing page, there was the option to capture submitted data. It sounds like you had that enabled, which cause the submitted data to be captured.

The only way to get around this would be to manually remove the data out of the database.

Sorry I couldn't be of more help!

**Comment by GGfallin** [comment]
Oh, that's right. I completely forgot about the "do not capture password" feature in the Landing Page. Thanks a lot.
