### ISSUE TITLE
Not able to create new email template (template.go:84: record not found)

### ISSUE THREAD

**Issue by noelvang** [gophish/gophish#151]
With latest github code i am not able to create a new email template.

It just fails. Terminal gives "template.go:84: record not found" no matter what name i put in.

![capture](https://cloud.githubusercontent.com/assets/6898042/13051330/f5f50e16-d3f8-11e5-9616-8fd02d50b212.PNG)

**Comment by jordan-wright** [comment]
Thanks for the report!

That's not good... Is this only with the latest code, or is this with any code?

**Comment by noelvang** [comment]
Its works using the precompiled binary... but when i dl'ed the code and compiled myself, i cant create a template.

**Comment by jordan-wright** [comment]
Sorry about this, everyone! This was a result of me fixing the issue where attachments weren't getting sent.

Should be good to go now.

**Comment by noelvang** [comment]
Great it works! :)
