### ISSUE TITLE
landing page

### ISSUE THREAD

**Issue by domesticdom** [gophish/gophish#1511]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
v0.71
Brief description of the issue: 
hosting landing page 
What are you expecting to see happen? :
when clicking on the email page link it doesn't foward to the landing page.
But if i test it on my local network it works fine. 
how do i set up the landing page  outside of my network?
rid extension can it be use as a sms text to a mobile number ?
and when clicked on email page goes to the landing page and shows the outcome on gophish status page
What are you seeing happen?
why doesnt my email page work outside of my local network
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```New Sending Profile

From:Paymentisduetoday@tech-center.com
Host:smtp.mail.com
Username:Paymentisduetoday@tech-center.com



New Campaign
url:http.noip.ddns.net


Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi there!

> how do i set up the landing page outside of my network?

You need to ensure that the IP address or domain name that points to your Gophish server is reachable by any recipient. This is a networking issue, and not something we can fix in Gophish or in this forum. You can find more information on how to troubleshoot this [in our documentation.](https://docs.getgophish.com/user-guide/faq#events-arent-showing-up-on-the-dashboard)

Sorry there isn't more we can do to help!
