### ISSUE TITLE
Max connection attempts exceeded - unencrypted connection

### ISSUE THREAD

**Issue by bubaiwantong** [gophish/gophish#1512]
Hello：
        when i send test mail , have an error show below:
`time="2019-07-19T17:35:53+08:00" level=info msg="192.168.13.155 - - [19/Jul/2019:17:35:53 +0800] \"GET /api/smtp/?api_key=8b3eadd71bf9877870480d54cf7d09ea9d0d734d89459dbd1ddb3210cd5d05b8&{} HTTP/2.0\" 200 2 \"https://192.168.30.87:3333/sending_profiles\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36\""
time="2019-07-19T17:36:25+08:00" level=warning msg="Max connection attempts exceeded - unencrypted connection"
time="2019-07-19T17:36:25+08:00" level=error msg="Max connection attempts exceeded - unencrypted connection"`
       now i am use gophish0.7.1, please help me, thank you!

**Comment by LucasGaleano** [comment]
I resolve the problem when i delete the sending profile and create another.
i don't know why but that fix it

**Comment by giraffeCjl** [comment]
I encountered the same problem, which seems to be related to SSL/TLS. If it is solved, can you share the solution?

**Comment by glennzw** [comment]
The problem here is that the SMTP server you'd selected cannot be connected to from gophish. Either the IP and/or port is wrong, or it's unreachable from the host.
