### ISSUE TITLE
Duplicate Mails Sent Still Occurs

### ISSUE THREAD

**Issue by CG-root** [gophish/gophish#1515]
What version of Gophish are you using?:
gophish-v0.7.1-linux-64bit

Brief description of the issue:
Duplicates emails are being sent

What are you expecting to see happen? :
No duplicate emails

What are you seeing happen?
Duplicate emails

Please provide as many steps as you can to reproduce the problem:

Step 1 - Create a list of 600 email addresses as described below
Step 2 - Duplicate emails will be sent

It seems that the issue stated in [#1242](https://github.com/gophish/gophish/issues/1242) still occurs.
Is there a possibility to create a workaround (an if statement) that will check if an email was already sent to a specific email address in a campaign in order to avoid duplicate email to be sent to the same email address.

In order to reproduce the issue, I have used free account of sendgrid and send 600 emails to 600 email addresses in mailinator.com. For example,
testing1@mailnator.com, testing2@mailnator.com, testing3@mailnator.com, and so on.

I could notice that duplicate emails still occurs and also GoPhish log shows that.

Thanks

**Comment by mcvic1rj** [comment]
@CG-root please fill out the following and include log/configs where possible.
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue: 

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by franckyz0r** [comment]
I can confirm this.
5% of my targets got the email twice.
FYI: in version 0.6.x this was not happening.

**Comment by KiransHub** [comment]
I can confirm this two I've raised another ticket with some suggestions based on it. v0.8.0

**Comment by jordan-wright** [comment]
Hey there! We've made significant fixes in recent releases that I imagine have resolved this issue. You can find one such example in https://github.com/gophish/gophish/issues/1726.

Please do let me know if you encounter this in the latest release and we can continue troubleshooting. Apologies again for the inconvenience here! I always try to have Gophish work exactly as expected- _especially_ when it comes to the emails being sent, so bugs like this are always something I try to avoid.
