### ISSUE TITLE
In Version 0.7.1, gmail is not allowing use of gophish

### ISSUE THREAD

**Issue by kburke15** [gophish/gophish#1520]
I did a test email from my account in gophish and gmail will not allow emails sent from external sites. Is there another email that you recommend? I know you talked about being transparent about all that stuff with the email provider, but there should be an email that allows you to do this without contacting them or you should have an internal email attached to it. Otherwise, this tool simply does not work.

**Comment by jordan-wright** [comment]
Hi @kburke15,

Thanks for reaching out! I’m afraid there isn’t anything we can do about various email providers flagging emails that originate from what they believe to be a Gophish server.

As mentioned in the original announcement on our work improving transparency, you have the ability to use the “Custom Headers” feature of sending profiles to override any headers we set by default if that’s required. That said, there are likely many things Gmail and other providers consider when choosing to flag a particular email as spam.

Sorry we can’t be of more help! My recommendation would be to first whitelist the Gophish server where possible, then focus on setting up proper SPF, DKIM, and DMARC.
