### ISSUE TITLE
Tracker image is not loaded

### ISSUE THREAD

**Issue by brijeshchheda** [gophish/gophish#1521]
Hello Team, 

I am using the Gophish 0.7.1 version. While creating the email template and used below html code
<html>
<head>
	<title></title>
</head>
<body>
<p>Dear {{.FirstName}} {{.LastName}}</p>

 
<p style="caret-color: rgb(0, 0, 0); font-family: Helvetica; font-size: 12px; text-size-adjust: auto;">Click here <a href="{{.URL}}">link</a> </p>

<p>{{.Tracker}}</p>
</body>
</html>

However in email i only receive the phishing link and not any tracker image.. Also when I open the email, the count of "Email Opened" is not incremented, it works only when i click on the link, thereby increment in Email Opened and Clicked Link.

I am unable to get the count of those users who only opened the email

**Comment by jordan-wright** [comment]
Hi there!

When you say:

> in email I only receive the phishing link and not any tracker image

Do you mean that when you look at the HTML of the email you receive you don’t see a tracking image at the bottom?

**Comment by jordan-wright** [comment]
Closing since there haven't been any updates in a week.
