### ISSUE TITLE
POST command for API Help

### ISSUE THREAD

**Issue by tlinesTXT** [gophish/gophish#1522]
Hi, currently i'm attempting to setup GoPhish to launch campaigns through a Windows PowerShell script. The issue that i'm running into that is i'm getting the error.
```html
Invoke-WebRequest : { "message": "Invalid JSON structure", "success": false, "data": null }
```
The thing is I have triple checked my JSON structure and it doesn't show any errors in JSON formatting checkers. So my question is if there are any errors in the code I have below for actually pushing these campaigns via PowerShell.

```
$jsonString = @"
{
   "name":"Test6",
   "template":{
      "name":"Test"
   },
   "url":"http://redacted",
   "page":{
      "name":"Test"
   },
   "smtp":{
      "name":"Test SMTP"
   },
   "launch_date":"2019-25-07T08:20:00+00:00",
   "send_by_date":null,
   "groups":{
      "name":"Test Group"
   }
}
"@

Invoke-WebRequest -Uri https://redacted/api/campaigns/?api_key=redacted -Method POST -Body $jsonString
```

I saw other posts on the github about this, and none of them seemed to help me, so I hope you don't mind me making another one.

**Comment by jordan-wright** [comment]
Hi there!

You might double-check that the Content-Type header in the request is being set to “application/json”.

**Comment by jordan-wright** [comment]
Hi @tlinesTXT,

Just checking in - did this help resolve the issue you were encountering?

**Comment by jordan-wright** [comment]
Closing since there haven't been any updates in a while. @tlinesTXT if you're still running into issues, let me know if changing the Content-Type helps or not.

Thanks for reaching out!
