### ISSUE TITLE
Export campaign results not working in Firefox

### ISSUE THREAD

**Issue by noelvang** [gophish/gophish#153]
Using the precompiled binary, i was not able to export any results.

The button is not working properly, it just loads http://......:3333/campaigns/12/#

I am not able to test the latest github-code, since because of another reported bug.

**Comment by jordan-wright** [comment]
Interesting - what browser are you using? Are there any error messages in your browser dev console?

**Comment by noelvang** [comment]
Firefox 44.0.2.

No messsages as far as i can see. Although i have limited experience debugging webapplications.

**Comment by noelvang** [comment]
Works in IE11.

Strange

**Comment by jordan-wright** [comment]
Good to know. I only tested in chrome/IE.

I'll figure out what the deal is with FF.

**Comment by jcamil** [comment]
Any chance it could be an extension or plugin causing the issue in FF?




Thanks

John Camille
Senior Engineer
jcamille@pervasivesolutions.net
Pervasive Solutions
M: 585-880-9714
D:  585-300-0440 x108
[cid:image001.png@01D167E4.65CFB2D0]

**Comment by noelvang** [comment]
Hi John,

No i dont think so. I have no extensions installed, and very limited plugins.

I think i have some msoffice plugin (std office) and some nvidia plugins, thats all.

No flash, no java, no anything else.

**Comment by jcamil** [comment]
I’ll double check FF this afternoon.




Thanks

John Camille
Senior Engineer
jcamille@pervasivesolutions.net
Pervasive Solutions
M: 585-880-9714
D:  585-300-0440 x108
[cid:image001.png@01D167E9.7757F8F0]

**Comment by jordan-wright** [comment]
Ok, should be fixed now. Mind giving it a shot?

**Comment by noelvang** [comment]
Yes, will do. Reporting back asap.

**Comment by noelvang** [comment]
It works! Thank you!

**Comment by noelvang** [comment]
But maybe i should add, exporting results gives weird unicode output for special chars. Should this be added as a new issue?

**Comment by jordan-wright** [comment]
Probably... I'll have to look into all the unicode support across the
board. That one in particular is probably more of an issue with the
PapaParse library, though go ahead and file in in gophish. I'll transfer it
if needed.

**Comment by jcamil** [comment]
Might be related to #152 / Unicode bug on CSV bulk import?

Depending on how the .CSV is built, perhaps not all fonts have all Unicode characters supported?




Thanks

John Camille
Senior Engineer
jcamille@pervasivesolutions.net
Pervasive Solutions
M: 585-880-9714
D:  585-300-0440 x108
[cid:image002.png@01D167F6.C0553380]

**Comment by noelvang** [comment]
Not sure.

#152 is when importing using bulk CSV. Then the application its self have trouble with the chars. (i think it bugs out when importing them and saving them to DB) The exact same chars can be manually added, and then it works! (when sending mails, and viewing in the application). 

But when exporting those correct values (manually added), it acts up in the results CSV file.
