### ISSUE TITLE
webpage icon loading problem(s)

### ISSUE THREAD

**Issue by SirOussama** [gophish/gophish#1532]
Hey there, i'm using the latest version of gophish. My problem is that the adminserver page dosn't interact when I change some values. I had to delete fx. a profile from "Sending Profiles" and create a new one before it takes effect with the new values. Another thing I have noticed is when I add a profile and afterwards click on save profile then the circle loading animation is constantly loading so you can't do any thing

Maybe gophish are not so internetexplore friendly?
or is it a mainproblem?

**Comment by S0larflare** [comment]
If memory serves, parts of GoPhish use Promises, which aren't well supported in IE. You're best off using Chrome or Firefox.
________________________________

**Comment by jordan-wright** [comment]
@S0larflare is spot on. I personally develop using Chrome, so I recommend using either Chrome or Firefox to use Gophish. I'm afraid I don't have the time right now to work on browser compatibility with all the other things I'm trying to get done.

**Comment by SirOussama** [comment]
Thank you for your quick respons.
Another think im wondering about.
What should I do when you maybe some day update the gophish version, 
I mean I want to keep the open source software up to date, and keep all my templates. So how can I update in the furture without losing my templates?

Thank you in advance

**Comment by S0larflare** [comment]
Make a backup of your database, delete everything else then redownload and copy the database back

Sent from my iPhone

On 30 Aug 2019, at 13:04, SirOussama <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you for your quick respons.
Another think im wondering about.
What should I do when you maybe some day update the gophish version,
I mean I want to keep the open source software up to date, and keep all my templates. So how can I update in the furture without losing my templates?

Thank you in advance

**Comment by SirOussama** [comment]
Thank You!

**Comment by S0larflare** [comment]
Actually, backup your config.json too, so you don’t have to reconfigure anything

Sent from my iPhone

On 30 Aug 2019, at 13:35, SirOussama <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank You!
