### ISSUE TITLE
Gophish instance closed itself after a few minutes

### ISSUE THREAD

**Issue by fungfung0727** [gophish/gophish#1533]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: v0.7.1

Brief description of the issue: I launched a Amazon EC2 and started using Gophish on it. It works fine for 1.5 days. However, it started to shut down the Gophish instance by itself this afternoon. I tried to open the instance by typing './gophish' and the same thing happened

What are you expecting to see happen? : Gophish instance constantly run until i exit.

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
time="2019-08-08T09:10:50Z" level=warning msg="No contact address has been configured."
time="2019-08-08T09:10:50Z" level=warning msg="Please consider adding a contact_address entry in your config.json"
goose: no migrations to run. current version: 20180830215615
time="2019-08-08T09:10:50Z" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
time="2019-08-08T09:10:50Z" level=info msg="Starting admin server at https://0.0.0.0:3333"
time="2019-08-08T09:10:50Z" level=info msg="Starting phishing server at http://0.0.0.0:80"
time="2019-08-08T09:11:50Z" level=info msg="Sending emails to mailer for processing" num_emails=2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x8b5dfc]

goroutine 32 [running]:
github.com/gophish/gophish/models.NewPhishingTemplateContext(0xb56dc0, 0xc42014d600, 0xc4201adbc0, 0x1a, 0xc42056c4b7, 0x5, 0xc42056c4c0, 0x6, 0xc42056c4e0, 0xa, ...)
        /go/src/github.com/gophish/gophish/models/template_context.go:49 +0x18c
github.com/gophish/gophish/models.(*MailLog).Generate(0xc42021e370, 0xc4204d42a0, 0x0, 0xc4204d42a0)
        /go/src/github.com/gophish/gophish/models/maillog.go:156 +0x340
github.com/gophish/gophish/mailer.sendMail(0xb5a180, 0xc42021a140, 0xb54bc0, 0xc42000f788, 0xc4201c8ac0, 0x2, 0x2)
        /go/src/github.com/gophish/gophish/mailer/mailer.go:154 +0x2a3
github.com/gophish/gophish/mailer.(*MailWorker).Start.func1(0xb5a180, 0xc42021a140, 0xc4201c8ac0, 0x2, 0x2)
        /go/src/github.com/gophish/gophish/mailer/mailer.go:91 +0xd4
created by github.com/gophish/gophish/mailer.(*MailWorker).Start
        /go/src/github.com/gophish/gophish/mailer/mailer.go:85 +0x81

```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - ./gophish
 * Step 2 - use for a few minutes

**Comment by jordan-wright** [comment]
Hi there!

Can you give information about your campaign? For example, what are you using as the URL in the campaign?

What does your email template look like?

**Comment by fungfung0727** [comment]
It was solved! Its because of me running too many campaign at the same time. The server cannot handle it. Therefore, it shut down the Gophish instance by itself.

Thanks!

**Comment by jordan-wright** [comment]
Glad to hear you were able to get it solved!
