### ISSUE TITLE
Site Becomes Unresponsive When Attempting Large (10k) Campaign

### ISSUE THREAD

**Issue by JoaoBernardoo** [gophish/gophish#1534]
Gophish ver. 7.1

We are attempting to run a large campaign of about 10k users at once, but when we attempt this the front-end of the website locks up and is unusable. Is there a recommended spec for the machine we run Gophish on, for campaigns of this size? I have checked previous posts with similar subject matter but, they are from 2017 and I would like to know if anything has changed since then. Thanks for any help!

**Comment by jordan-wright** [comment]
Hi @JoaoBernardoo,

Thanks for reaching out! I have it as a "todo" to better handle server-side pagination for API requests and performance in general. The problem you're running into is that Gophish is setting up the campaign details in the database, loading the campaign JSON response, and trying to send that back to the browser. With such a large campaign, this has the potential to lock up the browser as you're seeing.

I'm always open to pull requests, but in the meantime you may consider leveraging our API for to manage large campaigns. We have a [Python API client](https://docs.getgophish.com/python-api-client/) that should make this pretty easy to get up and running.

Sorry I couldn't be of more help!
