### ISSUE TITLE
complete working of IP tracker

### ISSUE THREAD

**Issue by amar-bug** [gophish/gophish#1535]
Can anybody please provide the details that  how the IP tracker works and how it's capturing and fetching the details of the targeted machine and how it stores the data ?( its urgent)

**Comment by S0larflare** [comment]
When you connect to the gophish server, your IP address is captured as part of the request. So depending on how you have things set up, the IP address could be anything from an internal private IP of your machine to a public facing IP of a proxy/firewall.

Sent from my iPhone

On 9 Aug 2019, at 09:25, amar-bug <notifications@github.com<mailto:notifications@github.com>> wrote:


Can anybody please provide the details that how the IP tracker works and how it's capturing and fetching the details of the targeted machine and how it stores the data ?( its urgent)

**Comment by jordan-wright** [comment]
Hi there,

@S0larflare is correct, Gophish collects the IP address as part of the request it receives.
