### ISSUE TITLE
Update Docker Image

### ISSUE THREAD

**Issue by qraimbault** [gophish/gophish#1536]
What version of Gophish are you using?: N/A

Brief description of the issue: The docker image is not up-to-date.

What are you expecting to see happen? : The docker image is up-to-date.

What are you seeing happen? The docker image is not up-to-date.

Hello sir,

I know the image is not official, so I'm of course not asking you to update it, I just noticed that it looks abandoned and does not have version 0.7.

I created a github repository and a docker repository to add the new version, you can find it here : https://github.com/qraimbault/gophish-docker https://hub.docker.com/r/qraimbault/gophish

If you want to update the README, feel free to do it, it is more an information than an action request, it is my very small contribution to this project.

Thank you for your work.

**Comment by jordan-wright** [comment]
Hi @qraimbault,

Thanks for getting in touch! For a while now, we've had an official [Dockerfile](https://github.com/gophish/gophish/blob/master/Dockerfile). I just need to get a chance to push the image at `gophish/gophish`.

When I have that image pushed, I'll update the README to point to the official image.
