### ISSUE TITLE
Max Connection exceeded

### ISSUE THREAD

**Issue by michealcorvin** [gophish/gophish#1537]
![Screenshot from 2019-08-15 00-23-22](https://user-images.githubusercontent.com/42247920/63047943-0d3de000-bef3-11e9-8631-a4a1590a337b.png)
![Screenshot from 2019-08-15 00-20-53](https://user-images.githubusercontent.com/42247920/63047944-0d3de000-bef3-11e9-96a8-64d7f2b378a6.png)
![Screenshot from 2019-08-15 00-17-29](https://user-images.githubusercontent.com/42247920/63047945-0dd67680-bef3-11e9-9f13-9ef1aad64a3d.png)

I get this issue and i hope i am not the only one stuck up with this kinda issues i downloaded the latest 0.8 version as i was getting the same error n 0.7 but the issue is not fixed plz check

I am not using gmails smtp but i use smtp2go 
I get differet errors when i use different port numbers 
i get the same result on test email as well as live one,

**Comment by jordan-wright** [comment]
Hi there,

I'm afraid there isn't anything we can do in Gophish to prevent this. This error is saying that Gophish - for whatever reason - isn't able to authenticate to your SMTP server. I recommend troubleshooting your credentials and connection to your SMTP provider to determine the root cause.
