### ISSUE TITLE
Gophish not accepting post request for a new campaign

### ISSUE THREAD

**Issue by JoaoBernardoo** [gophish/gophish#1539]
What version of Gophish are you using?: 
7.1
Brief description of the issue: 
I am using the Python api client and attempting to create/launch a new campaign but get the error: super() takes at least 1 argument (0 given). The GET statement works just fine, it is only when I try to post that it doesn't work. I have tried running the script in python 2 and 3, in 3 I get formatting errors . I am using the sample code from the python api documentation about creating a new campaign. Any help would be much appreciated.

![image](https://user-images.githubusercontent.com/19581988/63114097-fa162900-bf61-11e9-9293-e0aff25abeb7.png)
![image](https://user-images.githubusercontent.com/19581988/63114153-1619ca80-bf62-11e9-82cf-9e0cdfc7db4b.png)

**Comment by jordan-wright** [comment]
Hi there!

Can you give an example of the code you're using to create the campaign? And can you please also ensure you're using the latest version of the api client: `pip install -U gophish`.

Thanks!

**Comment by jordan-wright** [comment]
Closing this since there haven't been any updates in a few months.
