### ISSUE TITLE
Where we need to insert {{.URL}} tag? do we need to put it put its manually or not?

### ISSUE THREAD

**Issue by Allen-Paul** [gophish/gophish#1540]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.7.1

Brief description of the issue: I am able to send mails but not able to track it. It is just showing that email sent then when I read lot of discussions regarding this issue, I came across {{.URL}} but I am not sure should I mention it manually or not.  

What are you expecting to see happen? : Just to know how to use {{.URL}}

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi @Allen-Paul,

Yes, the `{{.URL}}` needs to be inserted in the email template anywhere you want links that point to Gophish. This either can be done manually in the [template HTML editor](https://docs.getgophish.com/user-guide/documentation/templates#using-the-html-editor), or automatically if you're importing an email.

I hope this helps!

**Comment by Allen-Paul** [comment]
Thanks for the information.

Suppose if we not importing any mail and we are manually entering the mail content which has some URL then where we need to add this tag?
