### ISSUE TITLE
How URLs are assigned to every landing page?

### ISSUE THREAD

**Issue by Allen-Paul** [gophish/gophish#1542]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:0.7.1

Brief description of the issue: 
I need to know how are URLs assigned to every landing page? Please can someone help me out in understanding the mechanism behind URL assignment for every landing page.

Thanks in advance.

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi @Allen-Paul,

This seems similar to #1543. Essentially, when you create a campaign, you give it a URL. It's assumed that this URL points to your Gophish server.

When the campaign is created, Gophish creates a unique ID, called the `rid` for each recipient and adds it to the URL. Gophish stores a mapping in the database that can be thought of as `URL -> Landing Page + Campaign + Recipient` so, when the link is clicked, it knows who clicked it, what campaign it was a part of, and what landing page to return.

I hope this helps!

**Comment by Allen-Paul** [comment]
Thanks for the information and quick reply.
