### ISSUE TITLE
Why do we need to give URL in campaign page? (newbie)

### ISSUE THREAD

**Issue by Allen-Paul** [gophish/gophish#1543]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  0.7.1

Brief description of the issue: 
I didn't get why we need to give URL Explicitly in campaign section when we've already selected the template. Those templates will be in the same server then why should we give URL? I might me lagging behind somewhere in connecting the dots, so please help me out in this.
Thanks in advance.

What are you expecting to see happen? : 
Need to why  we should mention URL explicitly

What are you seeing happen?
When I give any random URL in campaign section, When I click on the link I am redirecting to that page instead of landing page.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by edermi** [comment]
This way you can point arbitrary domain names to your phishing server, so for example users from different regions may be sent a different URL. Also, this allows to decouple stuff because GoPhish actually doesn't have to care about domains and you can easily create local/test setups.

These are the reasons I see, maybe there are more.

**Comment by Allen-Paul** [comment]
Thanks for the quick reply.
Arbitrary domain means - other domain which we have hosted or any random (other's) domain?

To point to a domain first we need to register right or can we randomly give any domain?

Thanks.

**Comment by jordan-wright** [comment]
Hi @Allen-Paul,

The URL must point to the Gophish server. Gophish takes this URL you provide, adds a random ID f or every recipient, and uses that as the value for the `{{.URL}}` template tag in an email.

This means that reach recipient will receive their own URL that points to Gophish that, when clicked, can be reflected in the dashboard.

I hope this helps! You can find more information in our documentation about [campaigns](https://docs.getgophish.com/user-guide/documentation/campaigns) or our [FAQ](https://docs.getgophish.com/user-guide/faq#events-arent-showing-up-on-the-dashboard)
