### ISSUE TITLE
How mail delivery and mail operning are tracked?

### ISSUE THREAD

**Issue by Allen-Paul** [gophish/gophish#1545]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  0.7.1

Brief description of the issue: 
I want to know how the email delivery, Email opening are tracked? The status of link opening can be tracked by rid but how emails are tracked?

Thanks in advance

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi @Allen-Paul,

Email opens are tracked using a 1-pixel image (the "tracker") that can be added to emails when creating an email template. This image points to the Gophish server with the unique `rid` - very similar to the way clicked links are tracked, just with an image that's loaded in the email.

I hope this helps!
