### ISSUE TITLE
Which part of code is handling the links?

### ISSUE THREAD

**Issue by Allen-Paul** [gophish/gophish#1546]
What version of Gophish are you using?:  0.7.1

Brief description of the issue: 
May I please get to know which code is generating the rid for every link?
Which code is linking this URL with the template?

Thanks in advance.

**Comment by edermi** [comment]
As far as I can see these:

https://github.com/gophish/gophish/blob/f95e9554c7cefd8bd0e772af8a19436090311e8c/models/result.go#L177
https://github.com/gophish/gophish/blob/f95e9554c7cefd8bd0e772af8a19436090311e8c/models/result.go#L210

**Comment by Allen-Paul** [comment]
Thank you so much for the support and this awesome tool.
