### ISSUE TITLE
Feature Request: Different forms of address in template

### ISSUE THREAD

**Issue by Quixus** [gophish/gophish#1550]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.7.1
Brief description of the issue: 
I would like to see different forms of address as a template option. Maybe certain employees/bosses are addressed differently e.g. Hello {{.FirstName}} for some but Dear {{.Mr/Ms/Mrs}}  {{.LastName}}. Another use case would be gnder specific addressing. This isn't an issue for English mails but in other Languages this would be very helpful e.g. in German Sehr Geehrte Frau Schmidt for females and  Sehr Geehrter Herr Schmidt for males

**Comment by jordan-wright** [comment]
Hi there!

Thanks for reaching out. Eventually, I'd like to support custom template tags, which this would fall under, but I don't have a timeline for when I'll have a chance to implement that.

Since we're tracking this at #27, I'm going to close this one out. Thanks again for getting in touch.
