### ISSUE TITLE
Unable to remove : X-Mailer: gophish

### ISSUE THREAD

**Issue by ignitionlab** [gophish/gophish#1553]
What version of Gophish are you using?: 
v.07

Brief description of the issue: 
During testing I noticed that a X-Mailer header displays gophish.  I would like to remove this when I put my phishing sim into production, however I can find where to disable this option.

I would like to remove the following:
X-Mailer: gophish 

Cheers
Chris

**Comment by glennzw** [comment]
I think you'd need to manually comment out [this line](https://github.com/gophish/gophish/blob/master/models/maillog.go#L164) from maillog.go:

`msg.SetHeader("X-Mailer", config.ServerName)`

...and recompile.

**Comment by ignitionlab** [comment]
Thanks for the reply.  Found the line you mentioned. Unfortunately couldn't get it to recompile however thats more of an issue at my end rather than gophish. Cheers.

**Comment by dmaciejak** [comment]
Wondering why you would want to remove the header flag ? usually it's an indicator showing that the email should not be considered as malicious as it's an approved test.

**Comment by thryb** [comment]
You can also overwrite the header by adding a custom X-Mailer.

**Comment by jvgassel** [comment]
> You can also overwrite the header by adding a custom X-Mailer.

I tried that but doens't seem to work:

X-Mailer: someValue

**Comment by jordan-wright** [comment]
Closing this since there were answers provided here and in #1596.

**Comment by jasen-b** [comment]
Do not deceive yourself, criminals are using gophish.

**Comment by ashishkhairnar** [comment]
Found a line where you can add your custom header and let your client know so that they are aware of an authorized Phishing Simulation.

Line 45 - `config/config.go`

"""
// ServerName is the server type that is returned in the transparency response.
const ServerName = "gophish"
"""

**Comment by ITgeevoSOC** [comment]
Hi everyone,

By removing the header, does it enable phishing emails to go to others inbox instead of the spam?

I have been searching for an answer because all emails seem to go to spam/junk when launching a campaign.

**Comment by ashishkhairnar** [comment]
Whitelisting mail header on your email gateway will allow emails to reach the inbox. Without headers, any odd looking email will be quarantined or marked spam.

The criteria depends on domain reputation etc.

Having a header is easier solution.

**Comment by ITgeevoSOC** [comment]
Hi there,

Thank you for your response.

So in other words the header must not be removed if sending phishing campaigns?

Is that correct?

We tried whitelisting domains and IPs but they seem to go to spam.

**Comment by ashishkhairnar** [comment]
It depends how your email infrastructure is configured. But experimenting with header whitelisting may lead you success.

**Comment by ITgeevoSOC** [comment]
Thank you for your help.

**Comment by nikaro** [comment]
Would you accept a PR that add a flag allowing to disable the inclusion of this header?

Our security team use gophish to run internal phishing campaign test, but some smart users have a sieve filter that flag these emails (^_^')
