### ISSUE TITLE
Clicked Link Event Seems to be Auto-Creating for Certain Emails Using IE 8

### ISSUE THREAD

**Issue by riab-tam** [gophish/gophish#1555]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.7.1

Brief description of the issue: "Clicked Link" event being automatically created for some phishing testing emails a few seconds after email sent.

What are you expecting to see happen? : No clicked link event being auto-created.

What are you seeing happen?
    - On at least one of our campaigns, a "Clicked Link" event seems to be auto-created a few seconds after the phishing testing emails are sent. The events are created anywhere from one to three seconds after the emails are sent, and they all have the same details: OS of "Windows (OS Version: 7)" and application of "IE (Version: 8.0)"
    - In the same campaign, there are other click events that seem to be genuine (a human being actually going into the email and clicking on the link). These genuine clicks have different details: same OS but application of "IE (Version: 11.0)".

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi @riab-tam,

While I can't say for sure, this is likely due to an anti-spam appliance checking the content in the links to determine if it's malicious.

Either way, _something_ is clicking the links sent in the emails. These events aren't generated by Gophish itself. To that end, I'm afraid there isn't anything we can do to prevent this behavior on our side.

Thanks for getting in touch!

**Comment by glennzw** [comment]
I think this might be the same thing as is happening here: [https://github.com/gophish/gophish/issues/1559](https://github.com/gophish/gophish/issues/1559)
