### ISSUE TITLE
Users & Groups link selects wrong category

### ISSUE THREAD

**Issue by rc4** [gophish/gophish#1558]
What version of Gophish are you using?: 0.8.0

Brief description of the issue: when clicking Users & Groups at the top of the page, it opens the User Management section of the console, instead of the Users & Groups (email targets) section. 

What are you expecting to see happen? : Go to the Users & Groups section 

What are you seeing happen? Going to the User Management section

**Comment by jordan-wright** [comment]
Closed via https://github.com/gophish/gophish/commit/20295bd96a1a9231c5badc1cdbe290b03f4f0cb0
