### ISSUE TITLE
Unable to minify users.js with gulp due to ES6

### ISSUE THREAD

**Issue by glennzw** [gophish/gophish#1561]
What version of Gophish are you using?: 
0.8.0

What version of node are you using?: 
v10.10.0

Brief description of the issue: 
Unable to minify `users.js`

What are you expecting to see happen? :
Minify `users.js` when running gulp

What are you seeing happen?
After running `npm install && gulp` the `users.js` file is not minimised

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - `git clone git@github.com:gophish/gophish.git && cd gophish`
 * Step 2 - `rm static/js/dist/app/*`
 * Step 3 - `npm install`
 * Step 4 - `gulp`

After the above steps all the files in `static/js/src/app/` are minified into `static/js/dist/app/` *except* for `users.js`.

I think this is because `users.js` uses the `let` [keyword](https://www.greycampus.com/blog/programming/java-script-versions). GoPhish's [gulpfile.js ](https://github.com/gophish/gophish/blob/master/gulpfile.js#L52) references non-ES6. The `users.js` and `users.min.js` in the repo don't appear to be the same either.

Looks like some people have [had success](https://stackoverflow.com/questions/31444350/is-it-possible-write-a-gulpfile-in-es6) with using Babel. I am able to minify `users.js` with [this online tool](https://skalman.github.io/UglifyJS-online/).

Or maybe something is wrong with my local setup. Could someone else try replicate, or help me out?

**Comment by jordan-wright** [comment]
Hey @glennzw,

The Users API was my first attempt at the long process of bringing the Gophish frontend to modern development practices. In the longterm, I'd love to move to something like React, but for now it was just trying to use more modern ES6 where possible.

The other change was starting to use Webpack instead of Gulp. Right now, `users.js` is the only file that's managed with Webpack.

You can execute it using `yarn run webpack` or `npx webpack`. The output will look something like this:

```
yarn run webpack
yarn run v1.13.0
$ src/go/src/github.com/gophish/gophish/node_modules/.bin/webpack
Hash: df8889515ee9338c0d39
Version: webpack 4.32.2
Time: 886ms
Built at: 2019-08-28 20:14:36
       Asset      Size  Chunks             Chunk Names
users.min.js  4.09 KiB       0  [emitted]  users
Entrypoint users = users.min.js
[0] ./users.js 4.7 KiB {0} [built]
```

I hope this helps!

**Comment by glennzw** [comment]
Thanks @jordan-wright that worked! I notice the 'let' keyword isn't present in the minified file, maybe yarn is translating to <ES6. 

Looking forward to the React future of GoPhish 💪
