### ISSUE TITLE
Campaign URL not linking to Landing Page

### ISSUE THREAD

**Issue by LegendaryPancake** [gophish/gophish#1562]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue: 

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

{
        "admin_server": {
                "listen_url": "myip:3333",
                "use_tls": true,
                "cert_path": "gophish_admin.crt",
                "key_path": "gophish_admin.key"
        },
        "phish_server": {
                "listen_url": "0.0.0.0:80",
                "use_tls": true,
                "cert_path": "example.crt",
                "key_path": "example.key"
        },
        "db_name": "sqlite3",
        "db_path": "gophish.db",
        "migrations_prefix": "db/db_",
        "contact_address": "",
        "logging": {
                "filename": ""
        }
}

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
Step 1 - When providing the campaign a url of my gophish server, after sending a test email the link doesnt send to my landing page. It just tells me there was no response

**Comment by S0larflare** [comment]
Can you provide an example of an email? Are you using a {{.URL}} tag in it? What have you set as the campaign url when you set the campaign up? Are you using a machine within your network to test this, or is the email going externally?

Sent from my iPhone

On 28 Aug 2019, at 20:33, LegendaryPancake <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for reaching out! We're happy to help resolve issues as quickly as possible.

Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our documentation<https://getgophish.com/documentation/>, which covers how to use Gophish.

What version of Gophish are you using?:

Brief description of the issue:

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

{
"admin_server": {
"listen_url": "10.251.19.24:3333",
"use_tls": true,
"cert_path": "gophish_admin.crt",
"key_path": "gophish_admin.key"
},
"phish_server": {
"listen_url": "0.0.0.0:80",
"use_tls": true,
"cert_path": "example.crt",
"key_path": "example.key"
},
"db_name": "sqlite3",
"db_path": "gophish.db",
"migrations_prefix": "db/db_",
"contact_address": "",
"logging": {
"filename": ""
}
}

Please provide any terminal output that may be relevant below:

Insert output here


Please provide as many steps as you can to reproduce the problem:
Step 1 - When providing the campaign a url of my gophish server, after sending a test email the link doesnt send to my landing page. It just tells me there was no response

**Comment by LegendaryPancake** [comment]
"<center><a href="{{.URL}}" style="border-radius: 3px; font-size: 15px; color: white; border: 1px #1373b5 solid; box-shadow: inset 0 1px 0 #6db3e6, inset 1px 0 0 #48a1e2; text-decoration: none; padding: 14px 7px 14px 7px; width: 150px; max-width: 150px; font-family: proxima_nova, 'Open Sans', 'lucida grande', 'Segoe UI', arial, verdana, 'lucida sans unicode', tahoma, sans-serif; margin: 6px auto; display: block; background-color: #007ee6; text-align: center;">View file</a></center>"

Here is an example of part of the html code of the email and it does have a {{.URL}} on the link I am using. Basically I am spoofing an email from dropbox.com to get my employees to click on the "View File" link which is supposed to take them to my landing page, the landing page being a fake dropbox login website where they would then enter their credentials.

From what I have read you are supposed to set the URL as your gophish machines external ip address. I have done that as well as a few others to see if that works. The machine I'm using is a VM that is running on my computer within the network.

I hope this info helps and if it doesnt let me know if I can provide any more information that could be useful in helping me solve this problem

**Comment by jordan-wright** [comment]
The most important thing to know is whether the URL in your email matches the URL you configure when creating your campaign. Right now, I'm afraid it's not quite clear to me if the issue you're reporting is that the URL in the email is wrong (ie not what you configured) or that the URL you're entering isn't showing the landing page you expect.

**Comment by abhi1038** [comment]
I am having same problme 

I have just hosted the gophish on digital ocean server is running follower same configuration as documented. 

1. Mails are going in spam that's because i am using Cpanel SMTP with any configuration. 
2. I have open the email but the report dashboard doen't show that i have open or click on the link. 
3. Getting Unknown certificate in logs 
![image](https://user-images.githubusercontent.com/5114412/153545514-21d5f0d4-7a33-44b9-ae60-b69368800b7f.png)
4. This is my email template when i click on the link the landing page doesn;t shows up it says site can;t be reached. 
`<html>
<head>
	<title></title>
</head>
<body data-gr-ext-installed="" data-new-gr-c-s-check-loaded="14.1049.0">
<p>Hi {{.Email}}</p>

<p>Your Facebook account is temporarily disabled due to suspicious activities&nbsp;in your account.&nbsp;</p>

<p>To review the details please&nbsp;<a href="{{.URL}}">click here</a></p>

<p>Facebook Team</p>
{{.Tracker}}</body>
</html>
`
5. Below is the campaign setup in place of URL i have used same Static IP where the gophish is hosted. 
![image](https://user-images.githubusercontent.com/5114412/153545814-384f1321-7f75-4f91-9516-426b49860695.png)

Need some quick help.
