### ISSUE TITLE
JFYI: downloads for GoPhish 0.8 VERSION file says 0.7.1

### ISSUE THREAD

**Issue by ldunzweiler** [gophish/gophish#1563]
I checked all 32/64 bit for linux, osx and windows.  They all say 0.7.1

**Comment by jordan-wright** [comment]
Hi @ldunzweiler,

Thanks for the heads up! I've added a note on the release to indicate the mishap. As mentioned in #1551, this was just a minor oversight during the release process.

Thanks again for getting in touch!
