### ISSUE TITLE
Can I access the static page with the phish server address?

### ISSUE THREAD

**Issue by m00-k** [gophish/gophish#1564]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.7.1

Brief description of the issue: Can I access the static page with the phish server address?
my config here
```json
"phish_server": {
                "listen_url": "0.0.0.0:8081",
                "use_tls": false,
                "cert_path": "example.crt",
                "key_path": "example.key"
        },
```

i try this
```
http://phish_server:8081/static/images/logo.png
```
but 404 Error

I've already seen the document, but it doesn't work the same way.
https://docs.getgophish.com/user-guide/documentation/landing-pages#static-assets

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
I'm not too sure why that's inaccessible, but you can access resources in the `gophish/static/endpoint` folder. If you place your images in there you'll be golden.

**Comment by m00-k** [comment]
@glennzw Thank you for your reply.
Successfully achieved through the setup of nginx.
