### ISSUE TITLE
Never shows emails opened

### ISSUE THREAD

**Issue by flacko12** [gophish/gophish#1567]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: latest

Brief description of the issue: When email is opened results in gophish does not change

What are you expecting to see happen? : emails opened

What are you seeing happen?: stuck in  emails sent

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
<html>
<head>
	<title></title>
</head>
<body>
<p>Hi, Please support our IT project by clicking <a href="{{.URL}}">here</a>.<br />
<br />
<br />
<br />
<br />
Thanks,<br />
<br />
IT department</p>

<p>{{.Tracker}}</p>
</body>
</html>

This is my current code, When i run tests and open it on my email it does not show in gophish results even if i clicked the link in the email. what should i do?

**Comment by rfdevere** [comment]
The simplest reason this is happening is that your mail client isn't loading remote content. The 'Email Open' doesn't appear until you have retrieved the {{.Tracker}} which is 1x1 image. So you'd make sure to click 'load remote content' or whatever in your email client.

Failing that your phishing server isn't publicly accessible and you should check out some basics: https://www.professormesser.com/network-plus/n10-007/network-address-translation-3/ simply hosting it on a VPS would be the easiest route to get a public IP with few hassles.

**Comment by jordan-wright** [comment]
Closing this since @rfdevere answered the question with the (as always!) spot on advice.

**Comment by SarahCary** [comment]
it doesn't work I get this when I do http://192.168.1.112:8080 in the browser

![image](https://user-images.githubusercontent.com/63299560/162701206-7e073bac-be89-40d5-8c5e-adbe62ba0658.png)

**Comment by hackerPPi** [comment]
I have a problem with the dashboard, when I lunch the campaign and the mail was sent to the recipient and he opened the mail, clicked the link, submitted the data, and the email reported did not appear in the dashboard.
![gophish](https://user-images.githubusercontent.com/88426500/192457786-eb17d040-9ae0-49d2-8098-ca1ba184abfc.png)
![gophish2](https://user-images.githubusercontent.com/88426500/192457796-2d1ee957-05f7-4d80-a5c2-7b72e6c60806.png)
![gophish33](https://user-images.githubusercontent.com/88426500/192457800-78480878-fc25-437d-9619-ae99f714d91f.png)
![gophish,json](https://user-images.githubusercontent.com/88426500/192457806-d1bc7906-aae0-4a26-a102-20fbf3c74edf.png)

**Comment by Thiati** [comment]
I have the same problem until today
