### ISSUE TITLE
Creating a new group via the API

### ISSUE THREAD

**Issue by Dextroz** [gophish/gophish#1568]
What version of Gophish are you using?: 
Latest

Brief description of the issue: 
When attempting to use the API endpoint to make a POST request to create a new group, it doesn't behave as expected. 

The API endpoint in question -->`https://localhost:3333/api/groups/`

What are you expecting to see happen? :
A new group with users is created successfully.

What are you seeing happen?
I am seeing the endpoint behave the same as it would when making a GET request, which returns data about current users and groups.

Please provide as many steps as you can to reproduce the problem:
 * Make a POST request to `https://localhost:3333/api/import/group`
 * Returns a valid structure to create a new group.
 * Format the request as per the API documentation (unpack my data structure for the request): 
  ```
{
    "name": f"TestGroup{uuid4()}",
    "targets": [*group_members]
}
```
 * Make the POST request to the endpoint [`https://localhost:3333/api/groups/`](https://docs.getgophish.com/api-documentation/users-and-groups#create-group)

 * Returns data about the current groups and doesn't create a new one.

**Comment by jordan-wright** [comment]
Hi there,

Can you please provide sample code you’re using, as well as the logs from the Gophish terminal?

**Comment by jordan-wright** [comment]
@Dextroz,

Just checking in, are you still having trouble with this? If so, could you please provide sample code you’re using, as well as the logs from the Gophish terminal?
