### ISSUE TITLE
Gophish group member users got same multiple phishing emails

### ISSUE THREAD

**Issue by michaellp0307** [gophish/gophish#1569]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.6.0 
Brief description of the issue: 
1.Gophish is working fine if i send phishing email to groups which contains 1-10 outlook users
2.If i trigger four phishing email to four groups, each groups which contains hundred of outlook member users, All of outlook users got 2-3 same phishing emails, the outlook users are angry!

What are you expecting to see happen? :
I want to see how many users open email and clink the phishing link 

What are you seeing happen?
yes i can see the result，but what bad is outlook users got multiple same GOphish phishing emails, they get angry！

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

No,Email templates or landing pages was working as expected,

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
I believe i can reproduce the problem if  i send the Phishing emails to same old group which contain  hundred of outlook members,but i don't dare to do that cause i will lost my job!
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi there!

I’m sorry to hear you’re seeing unexpected results. I’m afraid it will be difficult to troubleshoot this based on just the information you’ve provided. All I know at this point is that multiple emails were sent to the same people.

But I don’t know how many campaigns were run (I’m guessing one?), what the Gophish logs say, etc. at this point, I’m assuming there was one campaign that was launched including multiple groups and somehow the same email from the campaign arrived to the same person more than once.

But from here, there just isn’t enough information to move forward- especially without logs to help track down the problem. I’m afraid if there isn’t any more information that can be provided, then there isn’t anything I can do to help.
