### ISSUE TITLE
gophish getting crashed automatically

### ISSUE THREAD

**Issue by Allen-Paul** [gophish/gophish#1570]
What version of Gophish are you using?: 
0.7.1

Brief description of the issue: 
getting crashed automatically. 

What are you expecting to see happen? 
Work without getting crash, launch and track campaigns.

What are you seeing happen?
When I run GoPhish, after 1 minute it is getting crashed. I started facing this issue from today.
When I went through all the issues related to this, I found that the issue was mostly related to errors in SMTP name, FROM address, and {{.URL}}.
I've made sure it's not caused because of anything mentioned above.

Please provide any terminal output that may be relevant below:

time="2019-09-03T10:25:29Z" level=warning msg="No contact address has been configured."
time="2019-09-03T10:25:29Z" level=warning msg="Please consider adding a contact_address entry in your config.json"
goose: no migrations to run. current version: 20190105192341
time="2019-09-03T10:25:29Z" level=info msg="Starting admin server at https://XXX.XXX.XXX.XXX:3333"
time="2019-09-03T10:25:29Z" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
time="2019-09-03T10:25:29Z" level=info msg="Starting phishing server at http://XXX.XXX.XXX.XXX:4444"
time="2019-09-03T10:26:29Z" level=warning msg="record not found: template not found for campaign"
time="2019-09-03T10:26:29Z" level=warning msg="record not found: template not found for campaign"
time="2019-09-03T10:26:29Z" level=info msg="Sending emails to mailer for processing" num_emails=2
time="2019-09-03T10:26:29Z" level=warning msg="record not found: template not found for campaign"
time="2019-09-03T10:26:29Z" level=info msg="Sending emails to mailer for processing" num_emails=3
time="2019-09-03T10:26:29Z" level=warning msg="record not found: template not found for campaign"
time="2019-09-03T10:26:30Z" level=warning msg="record not found: template not found for campaign"
time="2019-09-03T10:26:30Z" level=warning msg="record not found: template not found for campaign"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x93d74c]

goroutine 28 [running]:
github.com/gophish/gophish/models.NewPhishingTemplateContext(0xc69460, 0xc0001e8580, 0xc000277be0, 0x1d, 0xc000429487, 0x5, 0xc00042948c, 0x1, 0xc000429498, 0x4, ...)
	/go/src/github.com/gophish/gophish/models/template_context.go:49 +0x1dc
github.com/gophish/gophish/models.(*MailLog).Generate(0xc00020f810, 0xc00008bf40, 0x0, 0xc00008bf40)
	/go/src/github.com/gophish/gophish/models/maillog.go:158 +0x3f6
github.com/gophish/gophish/mailer.sendMail(0xc70aa0, 0xc000028098, 0xc620a0, 0xc000011610, 0xc00019fb40, 0x3, 0x4)
	/go/src/github.com/gophish/gophish/mailer/mailer.go:157 +0x277
github.com/gophish/gophish/mailer.(*MailWorker).Start.func1(0xc70aa0, 0xc000028098, 0xc00019fb40, 0x3, 0x4)
	/go/src/github.com/gophish/gophish/mailer/mailer.go:89 +0xd4
created by github.com/gophish/gophish/mailer.(*MailWorker).Start
	/go/src/github.com/gophish/gophish/mailer/mailer.go:83 +0x81

**Comment by Allen-Paul** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x93d74c]

goroutine 679 [running]:
github.com/gophish/gophish/models.NewPhishingTemplateContext(0xc69460, 0xc000740b00, 0xc000333620, 0x1d, 0xc00076e147, 0x5, 0xc00076e14c, 0x1, 0xc00076e158, 0x4, ...)
	/go/src/github.com/gophish/gophish/models/template_context.go:49 +0x1dc
github.com/gophish/gophish/models.(*MailLog).Generate(0xc0000a0280, 0xc0001180a0, 0x0, 0xc0001180a0)
	/go/src/github.com/gophish/gophish/models/maillog.go:158 +0x3f6
github.com/gophish/gophish/mailer.sendMail(0xc70aa0, 0xc0000280a8, 0xc620a0, 0xc000362da0, 0xc00005edc0, 0x3, 0x4)
	/go/src/github.com/gophish/gophish/mailer/mailer.go:157 +0x277
github.com/gophish/gophish/mailer.(*MailWorker).Start.func1(0xc70aa0, 0xc0000280a8, 0xc00005edc0, 0x3, 0x4)
	/go/src/github.com/gophish/gophish/mailer/mailer.go:89 +0xd4
created by github.com/gophish/gophish/mailer.(*MailWorker).Start
	/go/src/github.com/gophish/gophish/mailer/mailer.go:83 +0x81

**Comment by jordan-wright** [comment]
Hi there!

Did you by chance delete the template you used in the campaign? This would likely cause issues, since Gophish wouldn't be able to generate the emails to send out.

**Comment by prikk1** [comment]
Hi. 
I m facing similar issue, when we run the GitHub admin page it crashes post login. We are assuming there was some error in the campaign, possibly in the {{URL}} field. Now can we resolve this issue? Should we force stop the campaign? Mine is GoPhish-v0.8.0
