### ISSUE TITLE
Failed : start Gophish service running on AWS EC2

### ISSUE THREAD

**Issue by momaydopod** [gophish/gophish#1573]
I would like to setup Gophish alway on AWS EC2(ubuntu) . I try to create bash but did not work.  Please help to advise me

`ubuntu@ip:~$ sudo service gophish start
Job for gophish.service failed because the control process exited with error code.
See "systemctl status gophish.service" and "journalctl -xe" for details.
`

`ubuntu@:~$ systemctl status gophish.service
● gophish.service - SYSV: stops/starts gophish application server
   Loaded: loaded (/etc/init.d/gophish; generated)
   Active: failed (Result: exit-code) since Thu 2019-09-05 05:03:09 UTC; 35s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 16542 ExecStart=/etc/init.d/gophish start (code=exited, status=127)

Sep 05 05:03:09 ip- systemd[1]: Starting SYSV: stops/starts gophish ap
Sep 05 05:03:09 ip- gophish[16542]: /etc/init.d/gophish: line 36: “sta
Sep 05 05:03:09 ip- systemd[1]: gophish.service: Control process exite
Sep 05 05:03:09 ip- systemd[1]: gophish.service: Failed with result 'e
Sep 05 05:03:09 ip- systemd[1]: Failed to start SYSV: stops/starts gop
lines 1-11/11 (END)
`
Bash script gophish

`#!/bin/bash
# /etc/init.d/gophish
# initialization file for stop/start of gophish application server
#
# chkconfig: — 64 36
# description: stops/starts gophish application server
# processname:gophish
# config:/opt/goapps/src/github.com/gophish/gophish/config.json
# define script variables
processName=Gophish
process=gophish
appDirectory=/root/gophish/gophish
logfile=/var/log/gophish/gophish.log
errfile=/var/log/gophish/gophish.erro
start() {
 echo ‘Starting ‘${processName}’…’
 cd ${appDirectory}
 nohup ./$process >>$logfile 2>>$errfile &
 sleep 1
}
stop() {
 echo ‘Stopping ‘${processName}’…’
 pid=$(/usr/sbin/pidof ${process})
 kill ${pid}
 sleep 1
}
status() {
 pid=$(/usr/sbin/pidof ${process})
 if [[ “$pid” != “” ]]; then
 echo ${processName}’ is running…’
 else
 echo ${processName}’ is not running…’
 fi
}
case $1 in
 start|stop|status) “$1” ;;
esac
exit
`

**Comment by jordan-wright** [comment]
I’m admittedly not the most familiar with service configurations on Linux distros, but we can try to help.

Let’s start with the basics: what do you see in the terminal when you run gophish manually?

**Comment by momaydopod** [comment]
I use ubuntu 18 on aws . I can run normally i found http connection

**Comment by jordan-wright** [comment]
Ok, what happens when you run that bash script manually using “start” as the argument? What logs do you see in your log file?

**Comment by momaydopod** [comment]
This is error

ubuntu@:~$ systemctl status gophish.service
● gophish.service - SYSV: stops/starts gophish application server
Loaded: loaded (/etc/init.d/gophish; generated)
Active: failed (Result: exit-code) since Thu 2019-09-05 05:03:09 UTC; 35s ago
Docs: man:systemd-sysv-generator(8)
Process: 16542 ExecStart=/etc/init.d/gophish start (code=exited, status=127)

Sep 05 05:03:09 ip- systemd[1]: Starting SYSV: stops/starts gophish ap
Sep 05 05:03:09 ip- gophish[16542]: /etc/init.d/gophish: line 36: “sta
Sep 05 05:03:09 ip- systemd[1]: gophish.service: Control process exite
Sep 05 05:03:09 ip- systemd[1]: gophish.service: Failed with result 'e
Sep 05 05:03:09 ip- systemd[1]: Failed to start SYSV: stops/starts gop
lines 1-11/11 (END)

**Comment by jordan-wright** [comment]
That doesn’t give us any logs though. It only indicates that Gophish failed to start, not the output from Gophish indicating why that happened.

Without more information, there won’t be anything we can do to help.

**Comment by momaydopod** [comment]
How can i ger the log from gophish ?
You mean log in /var/gophigh/ ?

**Comment by jordan-wright** [comment]
Looking at your bash script it looks like it’d be in var/log/gophish.

**Comment by momaydopod** [comment]
No log , what happen ?

`root@:~# sudo service gophish start
Job for gophish.service failed because the control process exited with error code.
See "systemctl status gophish.service" and "journalctl -xe" for details.
root@:~# systemctl status gophish.service
● gophish.service - SYSV: stops/starts gophish application server
   Loaded: loaded (/etc/init.d/gophish; generated)
   Active: failed (Result: exit-code) since Mon 2019-09-09 03:55:37 UTC; 7s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 5630 ExecStart=/etc/init.d/gophish start (code=exited, status=127)

Sep 09 03:55:37  systemd[1]: Starting SYSV: stops/starts gophish ap
Sep 09 03:55:37  systemd[1]: gophish.service: Control process exite
Sep 09 03:55:37  systemd[1]: gophish.service: Failed with result 'e
Sep 09 03:55:37  gophish[5630]: /etc/init.d/gophish: line 36: “star
Sep 09 03:55:37  systemd[1]: Failed to start SYSV: stops/starts gop
lines 1-11/11 (END)
root@:~# cat /var/log/gophish/
cat: /var/log/gophish/: Is a directory
root@:~# cd /var/log/gophish/
root@:/var/log/gophish# ls
root@:/var/log/gophish# cd ..
root@:/var/log# ls
alternatives.log       cloud-init.log  landscape    syslog.3.gz
amazon                 dist-upgrade    lastlog      syslog.4.gz
apt                    dpkg.log        letsencrypt  tallylog
auth.log               gophish         lxd          unattended-upgrades
auth.log.1             journal         syslog       wtmp
btmp                   kern.log        syslog.1
cloud-init-output.log  kern.log.1      syslog.2.gz
root@:/var/log# cd gophish/
root@:/var/log/gophish# ls

`

**Comment by jordan-wright** [comment]
I'm afraid without Gophish logs, we aren't able to help. In general, troubleshooting non-official service scripts is outside the scope of the support we can provide.

If you are able to track down logs from Gophish showing why it's unable to start, then we can continue troubleshooting. Other than that, there isn't anything more we can do to help since the possible root cause could be any number of things depending on your setup.

**Comment by momaydopod** [comment]
> I'm afraid without Gophish logs, we aren't able to help. In general, troubleshooting non-official service scripts is outside the scope of the support we can provide.
> 
> If you are able to track down logs from Gophish showing why it's unable to start, then we can continue troubleshooting. Other than that, there isn't anything more we can do to help since the possible root cause could be any number of things depending on your setup.

I try to access the Gophish log but it's show web access log but show error of didn't start service. Because I can run normal service Gophish.

**Comment by nin-ack** [comment]
**Just wanted to leave this here incase it assists anyone else as I've noticed a few other instances of people having this error but no clear resolution (due to the lack of logs).**

1. **Manually execute the gophish binary to get a good idea of why it's failing** - most people are likely following tutorials that are instructing them to set gophish up as a service, and subsequently have a hard time hunting down _descriptive_ logs when something goes wrong. 

**Results from the default `/var/log || syslog`:**
```
22:07:13 gofish systemd[1]: gophish.service: Main process exited, code=exited, status=1/FAILURE 22:07:13 gofish systemd[1]: gophish.service: Failed with result 'exit-code'.
22:07:14 gofish systemd[1]: gophish.service: Service hold-off time over, scheduling restart.
22:07:14 gofish systemd[1]: gophish.service: Scheduled restart job, restart counter is at 5.
```

**Whereas executing the binary manually you will see exactly (read usually) what the issue is:**
```
time="*:10:49Z" level=warning msg="No contact address has been configured."
time="*:10:49Z" level=warning msg="Please consider adding a contact_address entry in your config.json"
goose: no migrations to run. current version: 20191104103306
time="*:10:49Z" level=info msg="Starting admin server at https://0.0.0.0:1080"
time="*:10:49Z" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
time="*:10:49Z" level=info msg="Creating new self-signed certificates for administration interface"
time="*:10:49Z" level=fatal msg="TLS Certificate Generation: Failed to open gophish99.crt for writing: open gophish99.crt: no such file or directory"
```

**In my particular case, the issue was that I had symlinked to the wrong certificate location(s) after switching over to letsencrypt.** I would suspect that this is the issue that others would have if they copy and pasted directly from a tutorial without taking time to modify the commands provided to match their environment.
