### ISSUE TITLE
0.7. Version number shown in 0.8

### ISSUE THREAD

**Issue by rfdevere** [gophish/gophish#1574]
Just a quick one, not worth the reporting form.

<img width="638" alt="Screenshot 2019-09-05 at 11 25 45" src="https://user-images.githubusercontent.com/10911683/64334287-1f7ddc00-cfd0-11e9-8f0a-9f36aecf0c1b.png">

Love the features, thanks as always Jordan and co.

**Comment by dmaciejak** [comment]
Seems it's a known issue ;)

**Comment by jordan-wright** [comment]
Hey @rfdevere!

Great to here from you, I hope you’re doing well! This is indeed a known issue. I added a little note on the release to make people aware.

I’ll probably drop a 0.8.1 release soon with some minor changes including a version number bump 🙂

Have a good one!
