### ISSUE TITLE
Installation Windows

### ISSUE THREAD

**Issue by styleicons** [gophish/gophish#1575]
Hi trying to install Gophish version 8 to my Windows 7. And I downloaded and extracted it but when I try to run the .exe file it keeps freezing on this screen and never completes. I turned off firewalls as well
 
![Gophish screenshot](https://user-images.githubusercontent.com/54966437/64398649-73adae00-d01a-11e9-8adc-e23b0419ccfc.jpg)

**Comment by jordan-wright** [comment]
It looks like things are starting up just fine. What happens when you open your browser to https://127.0.0.1:3333?

**Comment by jordan-wright** [comment]
Closing since there haven't been any updates in 5 days. If you're still encountering issues, please address my comment above and we can continue troubleshooting.
