### ISSUE TITLE
Weirdness with 3D in SMTP

### ISSUE THREAD

**Issue by glennzw** [gophish/gophish#1577]
**EDIT**: It seems I didn't [Google](https://stackoverflow.com/questions/4016067/whats-a-3d-doing-in-this-html) hard enough before posting this. It's to do with an email encoding system called "quoted-printable", which allows non-ASCII characters to be represented as ASCII for email transportation.

In quoted-printable, any non-standard email octets are represented as an = sign followed by two hex digits representing the octet's value. Of course, to represent a plain = in email, it needs to be represented using quoted-printable encoding too: 3D are the hex digits corresponding to ='s ASCII value (61).

So I think this is a Mailslurp issue rather than GoPhish. Left this post up in case anyone else runs into this so they don't waste a couple of hours like I did.

<hr>
**What version of Gophish are you using?:** 0.8

**Brief description of the issue:** 
Creating an email template with the equals character results in '3D' (hex for equals) being appended to equals signs.

**What are you expecting to see happen? :**
No '3D' appended to equals signs.

**What are you seeing happen?**
'3D' being appended to equals signs.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

Email template:
```
<!doctype html>
<html>
<head>
	<title></title>
</head>
<body>
This is a test email. <a href="http://example.com">Link</a>

{{.Tracker}}</body>
</html>
```

Checking the GoPhish database for the template:

```
sqlite> SELECT * FROM templates ORDER BY ID DESC limit 1;
6|1|MLTest01|MLTest01||<!doctype html>
<html>
<head>
	<title></title>
</head>
<body>
This is a test email. <a href="http://example.com">Link</a>

{{.Tracker}}</body>
</html>
```

Sticking a socat relay between GoPhish and the email server to monitor the SMTP conversation we get the output below. Every time there's a `=` character `3D` gets appended. e.g: `<a href=3D"http://example.com">Link</a>`

```
➜ socat -v TCP-LISTEN:2501,fork,reuseaddr TCP:localhost:2500
220 Welcome to MailSlurper!\r
EHLO localhost\r
250 Hello. How very nice to meet you!\r
MAIL FROM:<test@test.com>\r
250 Ok\r
RCPT TO:<test@test.com>\r
250 Ok\r
DATA\r
354 End data with <CR><LF>.<CR><LF>\r
Mime-Version: 1.0\r
Date: Fri, 06 Sep 2019 12:47:07 +0100\r
Message-Id: <1567770427392666000.4685.4156668335605406494@localhost>\r
Subject: MLTest01\r
To: "Dummy Derp" <test@test.com>\r
From: test@test.com\r
X-Mailer: gophish\r
Content-Type: text/html; charset=UTF-8\r
Content-Transfer-Encoding: quoted-printable\r
\r
<!doctype html>\r
<html>\r
<head>\r
	<title></title>\r
</head>\r
<body>\r
This is a test email. <a href=3D"http://example.com">Link</a>\r
\r
<img alt=3D'' style=3D'display: none' src=3D'http://localhost/track?rid=3D0=\r
RtyL3a'/></body>\r
</html>\r
.\r
250 Ok\r
```

In Mailslurp the email renders as:

<img width="299" alt="mailslurp" src="https://user-images.githubusercontent.com/3966613/64429894-eff1d100-d0ae-11e9-9757-80482192e343.png">

**Comment by glennzw** [comment]
If you're also using Mailslurper (excellent tool for debugging with GoPhish) you can follow the issue I raised here: https://github.com/mailslurper/mailslurper/issues/126

**Comment by jordan-wright** [comment]
You might also consider using MailHog. I use it for development and it works great.

https://github.com/mailhog/MailHog

**Comment by glennzw** [comment]
Oh awesome, thanks!
