### ISSUE TITLE
Landing page issue

### ISSUE THREAD

**Issue by y0d4a** [gophish/gophish#1580]
hello,
i am spinning with last step of flow, and it is landing page form.
When user get email, he get url for landing page, he click on it and he go to land page, that is all correct, i see that in status, but last step, when he enter username/password and click submit, he got 404 page with prefix in url "http://x.x.x.x/?username=admin&password=123"
i put redirect page to other address, but he always get same url. is it submit form problem?

in log i get:
time="2019-09-10T07:20:12-04:00" level=info msg="x.x.x.x - - [10/Sep/2019:07:20:12 -0400] \"GET /?username=admin&password=123 HTTP/1.1\" 404 19 \"\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36\""

thank you

**Comment by jordan-wright** [comment]
Try changing the “method” form attribute to “post”.

**Comment by y0d4a** [comment]
flawless! :)
thank you!

if anyone get in same issue, i use this simple form:
`<form action="" method="post">
		Username<input type="text" name="user"/><br/>
		Password<input type="password" name="password"/><br/>
		<input type="submit" value="Refresh credentials"/>
	</form>`
