### ISSUE TITLE
Unable to hit landing pages from external - AWS hosted instance

### ISSUE THREAD

**Issue by mjs101995** [gophish/gophish#1581]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.7.1
Brief description of the issue: 
I have an AWS EC2 instance running Ubuntu and have installed GoPhish on this. I am sending campaigns and am not able to get the landing pages to load with the correct material.

Current Campaign url is set to the Public IPv4 address of the instance (http://x.x.x.x). 

When trying to access on the "Phished user" i get:
 "This site can't be reached", x.x.x.x (AWS instance IP) refused to connect. "ERR_Connection_Refused".

This has been tested on different browsers and still no landing page. I have tested by enabling ICMP, i can ping the instance fine from the computers i am using and testing the landing page from. You can also see in below logs from my putty session that the machine is hitting the instance but failing on TLS handshake. 

What are you expecting to see happen? :
Landing page configured to be shown on user click. 

What are you seeing happen?
As described above.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```
**** Providing AWS Instance inbound forwarding:
Ports, Protocol, Source
80,         tcp,       0.0.0.0/0
443,         tcp,       0.0.0.0/0

Please provide any terminal output that may be relevant below:

```
Insert output here
```
root@ip-*AWS Private IP Address*:/home/ubuntu# ./gophish
time="2019-09-10T16:13:01Z" level=warning msg="No contact address has been configured."
time="2019-09-10T16:13:01Z" level=warning msg="Please consider adding a contact_address entry in your config.json"
goose: no migrations to run. current version: 20180830215615
time="2019-09-10T16:13:01Z" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
time="2019-09-10T16:13:01Z" level=info msg="Starting phishing server at https://0.0.0.0:443"
time="2019-09-10T16:13:01Z" level=info msg="Starting admin server at https://0.0.0.0:3333"
time="2019-09-10T16:14:01Z" level=error msg="record not found: campaign not found"
time="2019-09-10T16:14:01Z" level=error msg="record not found"
time="2019-09-10T16:14:01Z" level=warning msg="record not found"
n    ^C
root@ip-*AWS Private IP Address*:/home/ubuntu# nano config.json
root@ip-*AWS Private IP Address*:/home/ubuntu# ./gophish
time="2019-09-10T16:26:46Z" level=warning msg="No contact address has been configured."
time="2019-09-10T16:26:46Z" level=warning msg="Please consider adding a contact_address entry in your config.json"
time="2019-09-10T16:26:46Z" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
goose: no migrations to run. current version: 20180830215615
time="2019-09-10T16:26:46Z" level=info msg="Starting phishing server at https://0.0.0.0:80"
time="2019-09-10T16:26:46Z" level=info msg="Starting admin server at https://0.0.0.0:3333"
2019/09/10 16:26:58 http: TLS handshake error from 192.x.x.x:55243: tls: first record does not look like a TLS handshake
2019/09/10 16:27:04 http: TLS handshake error from 192.x.x.x:55244: tls: first record does not look like a TLS handshake
2019/09/10 16:27:04 http: TLS handshake error from 192.x.x.x:55247: tls: first record does not look like a TLS handshake
2019/09/10 16:27:04 http: TLS handshake error from 192.x.x.x:55248: tls: first record does not look like a TLS handshake
time="2019-09-10T16:27:46Z" level=error msg="record not found: campaign not found"
time="2019-09-10T16:27:46Z" level=error msg="record not found"
time="2019-09-10T16:27:46Z" level=warning msg="record not found"
2019/09/10 16:27:56 http: TLS handshake error from 192.x.x.x:55250: tls: first record does not look like a TLS handshake
2019/09/10 16:27:56 http: TLS handshake error from 192.x.x.x:55252: tls: first record does not look like a TLS handshake
2019/09/10 16:28:01 http: TLS handshake error from 192.x.x.x:55251: tls: first record does not look like a TLS handshake
2019/09/10 16:28:02 http: TLS handshake error from 192.x.x.x:55254: tls: first record does not look like a TLS handshake
2019/09/10 16:28:02 http: TLS handshake error from 192.x.x.x:55255: tls: first record does not look like a TLS handshake
2019/09/10 16:28:32 http: TLS handshake error from 192.x.x.x:55256: tls: first record does not look like a TLS handshake
2019/09/10 16:29:32 http: TLS handshake error from 192.x.x.x:55257: EOF
2019/09/10 16:29:32 http: TLS handshake error from 192.x.x.x:55261: tls: first record does not look like a TLS handshake
2019/09/10 16:31:03 http: TLS handshake error from 192.x.x.x:55260: EOF
2019/09/10 16:34:32 http: TLS handshake error from 192.x.x.x:55267: tls: first record does not look like a TLS handshake
2019/09/10 16:36:04 http: TLS handshake error from 192.x.x.x:55268: EOF
2019/09/10 16:36:08 http: TLS handshake error from 192.x.x.x:55273: tls: first record does not look like a TLS handshake
2019/09/10 16:36:23 http: TLS handshake error from 192.x.x.x:55274: EOF
2019/09/10 16:38:28 http: TLS handshake error from 192.x.x.x:56152: tls: first record does not look like a TLS handshake
2019/09/10 16:38:28 http: TLS handshake error from 192.x.x.x:55352: tls: first record does not look like a TLS handshake
2019/09/10 16:38:28 http: TLS handshake error from 192.x.x.x:55353: tls: first record does not look like a TLS handshake
2019/09/10 16:38:28 http: TLS handshake error from 192.x.x.x:55354: tls: first record does not look like a TLS handshake
2019/09/10 16:38:29 http: TLS handshake error from 192.x.x.x:55355: tls: first record does not look like a TLS handshake
2019/09/10 16:38:29 http: TLS handshake error from 192.x.x.x:55356: tls: first record does not look like a TLS handshake
2019/09/10 16:38:29 http: TLS handshake error from 192.x.x.x:55357: tls: first record does not look like a TLS handshake
2019/09/10 16:38:40 http: TLS handshake error from 192.x.x.x:3189: EOF

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi there!

I recommend checking out the notes [in our FAQ](https://docs.getgophish.com/user-guide/faq#events-arent-showing-up-on-the-dashboard) under "Check the Campaign URL", since it gives some hints on how you might be able to troubleshoot this issue.

Let me know if you are still encountering issues after having read through that, and please let us know what you see at each step in that FAQ, such as confirming that you're able to reach the Gophish web server which should return a 404 error.

**Comment by S0larflare** [comment]
"Starting phishing server at https://0.0.0.0:80<https://0.0.0.0:80/>"


You seem to be trying to serve TLS over port 80 and then gophish is complaining as youre connecting to port 80 via plain http (quite naturally) try removing tls for the phish server or changing the port to 443 and then using https for the campaign url

Sent from my iPhone

On 11 Sep 2019, at 04:55, Jordan Wright <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi there!

I recommend checking out the notes in our FAQ<https://docs.getgophish.com/user-guide/faq#events-arent-showing-up-on-the-dashboard> under "Check the Campaign URL", since it gives some hints on how you might be able to troubleshoot this issue.

Let me know if you are still encountering issues after having read through that, and please let us know what you see at each step in that FAQ, such as confirming that you're able to reach the Gophish web server which should return a 404 error.

**Comment by mjs101995** [comment]
I changed the config.json file to update the port to 443 as advised, i was then able to hit the test page as informed on the FAQ section and get the 404 error. 

From there i sent a new campaign and the landing page was working as expected. The only issue now being the Safe Browsing from Google hitch not liking the page i have. I am hoping to be able to handle this for my internal testing need with some whitelisting. From reading about the Google Safe browsing issue it doesn't seem much can be done to allow the page.

**Comment by jordan-wright** [comment]
Glad you were able to get it up and running! I’m afraid there isn’t anything we can do about the SafeBrowsing issue since that’s outside of our control.

Since you managed to get things running, I’m going to go ahead and close this one out.
