### ISSUE TITLE
Custom index.html file not populating with all its dependencies

### ISSUE THREAD

**Issue by jon-o1** [gophish/gophish#1586]
Currently using version 0.7.1. Running into an issue where i've created a custom index.html file with its dependencies which include css files etc. once i create a campaign the page is only populating with raw html and not including the styling. I must be missing a step somewhere or not linking something properly. I'm using the {{.URL}} parameter inside my email template which points to the index page (which it does) but still only displays the raw html. 

Email Template code:
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body><meta http-equiv="Content-Type" content="text/html; charset=Windows-1252">
<p style="FONT-SIZE: 10pt; FONT-FAMILY: ARIAL"><br />
Your password will expire in 2&nbsp;days.<br />
To change your password, open the Password Manager <strong><a href="{{.URL}}"><u><font color="#0066cc">Self-Service site home page</font></u>(<u><font color="#0066cc">https://mysite.com</font></u></a>)</strong>, then click Manage My Passwords, and follow the wizard&#39;s instructions. {{.Tracker}}</p>
</body>
</html>

Landing Page Code (custom index.html file code):
Pretty lengthy but can provide if needed..

**Comment by jon-o1** [comment]
Update: I was also having an issue where my landing page (using custom .html code) was displaying just the raw content and no styling. I was able to resolve this by moving all my styling folders under "/static/". The landing page now displays properly by itself. Issue still remains where when i run a campaign, the styling does not apply. I've tried moving these files into "/static/endpoint/" along with changing reference links and still no luck. 
Wonder if it could be something with how i'm creating the link in an email. 
Workflow: 
- User receives an email.
- A link embedded i have it pointing to http://{{.URL}}  (landing page/.html)
- Landing page

**Comment by glennzw** [comment]
Id' say go View Source on the phishing landing page and try open the CSS files from there to make sure your links are correct.

**Comment by jon-o1** [comment]
I receive a "404 page not found" message. My file and folder structure is as follows. 
Custom index.html and styling folders are housed in \\server\c$\gophish\static\.
I've also previously tried adding these into \\server\c$\gophish\static\endpoint\ but this wouldn't display the css when creating my landing page properly.

**Comment by jon-o1** [comment]
> Id' say go View Source on the phishing landing page and try open the CSS files from there to make sure your links are correct.

I receive a "404 page not found" message. My file and folder structure is as follows.
Custom index.html and styling folders are housed in \server\c$\gophish\static.
I've also previously tried adding these into \server\c$\gophish\static\endpoint\ but this wouldn't display the css when creating my landing page properly.

**Comment by jon-o1** [comment]
Update: I was able to figure out and change my reference links to point to the correct URL's.
