### ISSUE TITLE
Tracking Pixel is missing the alt="" header

### ISSUE THREAD

**Issue by new-gen23** [gophish/gophish#1590]
What version of Gophish are you using?: 
0.6.0 from https://hub.docker.com/r/matteoggl/gophish/, but commits for 0.8.0 do not indicate the problem is fixed.

Brief description of the issue: 
Spam protection solutions flag gophish mails as spam because the URL for the tracking pixel is missing an alt="" . As the pixel is included via the {{.tracking}} variable, there is no way to add the string manually.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

The problem can be replicated by creating an new template with random content. 

Please provide any terminal output that may be relevant below:

```
Insert output here
```
![image](https://user-images.githubusercontent.com/1741662/64956073-11f70a80-d88a-11e9-953e-5677125ac512.png)

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - create a new email template with random content.
 * Step 2 - set the checkbox for the tracking pixel
 * Step 3 - create a campaign
 * Step 4 - Launch the campain and check the email
 * Step 5 - The email is includes the tracking pixel URL, where the alt="" is missing.

**Comment by jordan-wright** [comment]
Hi there!

Thanks for reaching out. It looks like this was fixed at some point as you can see in https://github.com/gophish/gophish/blob/6222c5e180a97d0aa3ec345d0c7af06c380f3db5/models/template_context.go#L66

Let me know if you encounter the same behavior with the latest version of Gophish!

**Comment by new-gen23** [comment]
My fault. Looks good. Thanks.
