### ISSUE TITLE
Help with the red x box in phishing campaign emails

### ISSUE THREAD

**Issue by mbasilecgtc** [gophish/gophish#1591]
When I add {{.Tracker}} in the bottom of the email to track if the email was opened, I keep getting a red x box on the bottom. Is there a solution to this? I googled around and tried adding the sender to outlook's safe sender list to see if it would just go away but it doesn't. 

Outlook 2016 is what our company uses.

Any help with this would be a tremendous help! Thank you in advance.

**Comment by jordan-wright** [comment]
It sounds like perhaps it’s either a broken image meaning the URL you’re putting in your campaign doesn’t point to your Gophish instance, or it’s  a security setting which I’m afraid we won’t be able to help with.

**Comment by jordan-wright** [comment]
Closing this since there haven't been any updates in a couple of months.
