### ISSUE TITLE
Feature: Provide release builder through Dockerfile

### ISSUE THREAD

**Issue by quelsan** [gophish/gophish#1593]
In order to produce a "release" archive of Gophish, a build environment for Golang and the client side assets is required.

This build environment is however (hopefully soon, #1579) already providing these tools.

In my fork of Gophish I've been experimenting with [adding a feature to produce a release ZIP inside the Docker image](https://github.com/quelsan/gophish/blob/master/docker/run.sh).
The workflow looks like this:

```
$ docker build --tag "gophish:0.8.1"
$ docker run --rm "gophish:0.8.1" --build-release > local/releases/gophish-v0.8.1-linux-64bit.zip
```

It's quite neat, but this method is not perfect.
It works for Linux (32 and 64 bit, I presume), but the Windows binaries needs to be cross-compiled if one desires a full release workflow.

Feel free to borrow the code/concept if you think it's a good fit.

**Comment by jordan-wright** [comment]
Hey @quelsan!

You would likely be interested in our release scripts, which you can find [here](https://github.com/gophish/release-scripts). I've also talked a bit about how they work [here](https://jordan-wright.com/blog/post/2018-02-04-automating-gophish-releases/).

I think you would most likely be interested in [this section](https://github.com/gophish/release-scripts/blob/154f33f625031a35e948dcfc088ab5d47e816e1a/ansible/roles/release/tasks/main.yml#L67) of the script. Right now, I use the [`karalabe/xgo-latest`](https://github.com/karalabe/xgo) Docker image to handle cross compilation, and then build the releases for each system.

This works fine for now, but I'm very excited to try and move this workflow (and others) into Github Actions. I just recently got access for the Gophish organization, so I'm hoping to start playing around with it soon.

I hope this helps give you some inspiration for what you're working on!

**Comment by quelsan** [comment]
Thats cool - I've missed that repo. Will check it out, but it seems like the issue is already solved!
