### ISSUE TITLE
VML Tracking Image

### ISSUE THREAD

**Issue by bhaizlett123** [gophish/gophish#1595]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.7.1
Brief description of the issue: 
I am trying to insert the tracking image into VML for outlook users to automatically download the image, so i can track opened emails. But for some reason i can't get it to work.
What are you expecting to see happen? :
When an outlook user opens the email for the tracking image to trigger and show they opened the email.
What are you seeing happen?
Nothing
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:
I tried to insert this into the email template but it doesn't seem to work
```html
<v:background xmlns:v="urn:schemas-microsoft-com:vml" fill="t">
<v:fill type="tile" src="{{.Tracker}}"></v:fill> </v:background>

```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hey @bhaizlett123,

I haven't personally worked with VML files before, but I'm presuming the `src` attribute is asking for a URL to the image. In that case, you can use the `{{.TrackingURL}}` tag.

I hope this helps! Let me know if that doesn't give you the VML you expect.
