### ISSUE TITLE
Feature Request: Bypass Spam Filter: Allow sending HTML+Text phishing mail

### ISSUE THREAD

**Issue by new-gen23** [gophish/gophish#1599]
Brief description of the issue: 
I am doing a little research in bypassing spam filters that block most of the gophish mails. One point I cannot change are these scoring flags:
MIME_MA_MISSING_TEXT(2.00)[];
MIME_HTML_ONLY(0.20)[];
Reason:
I am using an HTML mail provided by the customer. However, the mail lacks a text version, normally separated by a dynamic boundary variable. This separator allows mail clients like outlook/thunderbird to display a text-only version of the mail. 
As a result, the spam filter flags the mail already with a bad reputation. 

There is currently no visible possibility to create a mail in Gophish with the structure:

```
From: foo <foo@bar.com> 
To:  bar <bar@lain.com> 
Subject: Sample message 
MIME-Version: 1.0 
Content-type: multipart/mixed; boundary="simple  boundary"

     This is the preamble.  It is to be ignored, though it 
     is a handy place for mail composers to include an 
     explanatory note to non-MIME compliant readers. 
     --simple boundary 
     Content-Type: text/html; charset="utf-8"

     HTML version text
     phishing-link 
     optional:tracking pixel
     It does NOT end with a linebreak. 
     --simple boundary 
     Content-type: text/plain; charset=us-ascii 

     This is explicitly typed plain ASCII text. 
     phishing-link
     It DOES end with a linebreak. 

     --simple boundary-- 
     This is the epilogue.  It is also to be ignored.
```
I can imagine it is not easy to implement this feature. But without this feature, the likelihood that current spam filters simply block all Gophish mails is present. And the result is that the campaigns fail, even if you but great effort in the phishing landing page. 

I will try to build a workaround with the postfix after-queue filter to add the mail header and the boundary line. My current approach would be to add the text version of the mail after the HTML part and separate it by a placeholder line. In the after-queue, add the multipart mail header and replace the placeholder with the correct boundary variable. That way, it should be possible to have the phishing link in the HTML and Text version. 
Furthermore, it is easier to make the Text version look similar to the HTML version, as spam filters also score, how much the two versions differ.

If you encounter spam filter blocks, I suggest to send the testmail to https://www.mail-tester.com/. It will give you a pretty good indication, why your gophish mail might get blocked at the target.
 
RFC, how to format multipart/mixed mails:
https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html

**Comment by zazathomas** [comment]
There is a "Text" tab on the gophish email template interface which you can toggle. Simply copy the text over to that tab and you should be alright. Cheers

**Comment by jordan-wright** [comment]
Hi there,

@zazathomas is correct, you can specify the text part of the email using the "Text" tab in the "Email Template" builder. By doing so, we create a multipart email that looks like this:

```
Content-Type: multipart/alternative; boundary=ada6eb3cf2d438c31325b7521f718c8fc8380c11b495e4d37afdfba329d8
Date: Sun, 22 Sep 2019 21:35:11 -0500
From: "test test" <test@test.com>
Mime-Version: 1.0
Return-Path: <test@test.com>
Subject: test
To: "test test" <test@test.com>
X-Mailer: gophish

--ada6eb3cf2d438c31325b7521f718c8fc8380c11b495e4d37afdfba329d8
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset=UTF-8

This is the text part
--ada6eb3cf2d438c31325b7521f718c8fc8380c11b495e4d37afdfba329d8
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html; charset=UTF-8

<html>
<head>
	<title></title>
</head>
<body>
<p>This is the HTML</p>
<img alt=3D'' style=3D'display: none' src=3D'/track?rid=3Dpreview-QM6S8Hi'/=
></body>
</html>

--ada6eb3cf2d438c31325b7521f718c8fc8380c11b495e4d37afdfba329d8--
```
