### ISSUE TITLE
Add Ability to Clone Campaign

### ISSUE THREAD

**Issue by jordan-wright** [gophish/gophish#160]
We have the ability to clone landing pages and templates, but we also need the ability to clone campaigns.

**Comment by jcamil** [comment]
Thanks Jordan!




Thanks

John Camille
Senior Engineer
jcamille@pervasivesolutions.net
Pervasive Solutions
M: 585-880-9714
D:  585-300-0440 x108
[cid:image001.png@01D1697C.85DB2D90]

**Comment by jordan-wright** [comment]
You bet! It looks like there's some issues with doing this right away.

First, I'll need to implement #78 so that we can fill in the SMTP server info on load. Then, I'll need to adjust the "send a test email" to use that data instead.

Unfortunately, the one thing I won't be able to copy over is the groups, since when we receive a campaign, we automatically grab all the members of each group specified and create ```models.Result``` objects for them. So, the original groups won't be available.

But, that should be ok since, ideally, you'll want to target other groups anyway. It's at the very least a solid start!

**Comment by jordan-wright** [comment]
With this taking quite a bit of dependency work, I'm going to go ahead and move this to 0.2. It will be one of the first items taken care of for that release.

**Comment by jordan-wright** [comment]
This was completed with https://github.com/gophish/gophish/commit/af91483cd432d7e69059bc13de2e6ddb8a21ffad.
