### ISSUE TITLE
Outlook SMTP

### ISSUE THREAD

**Issue by abdelakp** [gophish/gophish#1600]
Hi guys,
I have a problem when I use Outlook to send test mail with, I have this error message: 550 5.7.60 SMTP; Client does not have permissions to send as this sender. How can I resolve this problem?
I'm beginners and sorry for my english??
Thank you

**Comment by jordan-wright** [comment]
Hi there,

This is an error provided by the upstream mail server. You will need to ensure your credentials are correct, if applicable, and that the sending address you're using is allowed per the credentials you provide.

Beyond that, this is a mail server configuration issue, not something in Gophish. With that being the case, there isn't anything we can do to resolve this issue on our end, so I'm going to close it out.

Thanks for getting in touch!
