### ISSUE TITLE
TLS Handshake Error: unknown certificate

### ISSUE THREAD

**Issue by hahnsolo13** [gophish/gophish#1601]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: v 0.8

Brief description of the issue: We scheduled a campaign, and it froze when scheduled. Only 1/4 of the emails sent, and now gophish is showing TLS errors.

What are you expecting to see happen? : Successful campaign

What are you seeing happen? Gophish is sending errors during a scheduled campaign. The emails aren't being reported back into gophish.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

![image](https://user-images.githubusercontent.com/37385187/65352128-73cbb300-dbaf-11e9-8564-0c007c544fb9.png)

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
TLS handshake is a normal message to see in your logs if you're using a self signed cert (the default). e.g here's a snippet from my logs:

```
2019/09/19 16:10:58 http: TLS handshake error from 127.0.0.1:52833: remote error: tls: unknown certificate
time="2019-09-19T16:10:58+01:00" level=info msg="127.0.0.1 - - [19/Sep/2019:16:10:58 +0100] \"GET /api/campaigns/79/results?{} HTTP/2.0\" 200 749 \"https://gophish.local:3333/campaigns/79\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36\""
2019/09/19 16:11:58 http: TLS handshake error from 127.0.0.1:53075: remote error: tls: unknown certificate
time="2019-09-19T16:11:58+01:00" level=info msg="127.0.0.1 - - [19/Sep/2019:16:11:58 +0100] \"GET /api/campaigns/79/results?{} HTTP/2.0\" 200 749 \"https://gophish.local:3333/campaigns/79\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36\""
2019/09/19 16:12:59 http: TLS handshake error from 127.0.0.1:53284: remote error: tls: unknown certificate
time="2019-09-19T16:13:02+01:00" level=info msg="127.0.0.1 - - [19/Sep/2019:16:13:02 +0100] \"GET /api/campaigns/79/results?{} HTTP/2.0\" 200 749 \"https://gophish.local:3333/campaigns/79\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36\""
2019/09/19 17:22:38 http: TLS handshake error from 127.0.0.1:53588: remote error: tls: unknown certificate
2019/09/19 17:23:36 http: TLS handshake error from 127.0.0.1:53900: remote error: tls: unknown certificate
2019/09/19 17:24:37 http: TLS handshake error from 127.0.0.1:54158: remote error: tls: unknown certificate
2019/09/19 17:25:38 http: TLS handshake error from 127.0.0.1:54404: remote error: tls: unknown certificate
2019/09/19 17:26:39 http: TLS handshake error from 127.0.0.1:54675: remote error: tls: unknown certificate
2019/09/19 17:27:40 http: TLS handshake error from 127.0.0.1:54934: remote error: tls: unknown certificate
2019/09/19 17:28:41 http: TLS handshake error from 127.0.0.1:55181: remote error: tls: unknown certificate
2019/09/19 17:29:42 http: TLS handshake error from 127.0.0.1:55431: remote error: tls: unknown certificate
2019/09/19 17:30:43 http: TLS handshake error from 127.0.0.1:55680: remote error: tls: unknown certificate
2019/09/19 17:31:44 http: TLS handshake error from 127.0.0.1:55936: remote error: tls: unknown certificate
```

**Comment by hahnsolo13** [comment]
Ahhh if that's the case then there is a different issue. The campaign was scheduled to send around 7000 emails. The gophish interface reports 1498 sent, but I see about 4000 sent in our mail server. Any idea?

**Comment by glennzw** [comment]
Tricky. If I was in your position I'd fire up [MailHog](https://github.com/mailhog/MailHog), create a new send profile for MailHog, copy the failed campaign and send it again. This would help isolate if it's your mail server or Gophish misbehaving.

**Comment by MLK06** [comment]
Sorry but i have the same Problem with version 0.10.1 on windows

**Comment by glennzw** [comment]
Closing this out as we haven't heard any updates. If you're still having the problem try upgrading to the latest gophish, as a lot of improvements were recently made with the dispatch routines.
