### ISSUE TITLE
Gophish not reporting Email Opened/Clicked Link/Captured Data

### ISSUE THREAD

**Issue by jlj0304** [gophish/gophish#1603]
What version of Gophish are you using?: 0.7.1

Brief description of the issue: Campaign reports one opened an email and then nothing following that. 

What are you expecting to see happen? : The Expected outcome is to capture data submitted by the user (only username, no password). The campaigns are thoroughly tested against company testers prior to phishing employees. 

What are you seeing happen? It appears that once the first person opens the email, no other data is being captured, not even clicking the link. 

Mail Relay: SendGrid.com

**Comment by jordan-wright** [comment]
Hi there,

There's a lot here, without much info on what you've tried. Unless you can provide more information, like the email template and landing page you're using, I recommend taking a look at the FAQ [here](https://docs.getgophish.com/user-guide/faq#events-arent-showing-up-on-the-dashboard) which discuss how to troubleshoot issues similar to this.
