### ISSUE TITLE
Email send error

### ISSUE THREAD

**Issue by GerryOldMan** [gophish/gophish#1604]
What version of Gophish are you using?: 0.7.1

Brief description of the issue: 
Scheduled emails not sent due to reaching daily limit on GMail account. Dashboard shows the below error for email that has not been sent:
550 5.4.5 Daily user sending quota exceeded

Does GoPhish continue to try sending these emails, or should I create a new campaign when the limit has cleared?

**Comment by jordan-wright** [comment]
Hi there,

This response is a 5xx response indicating a permanent error. Gophish only retries 4xx temporary errors, and the maximum backoff period is around 4 hours (https://github.com/gophish/gophish/blob/master/models/maillog.go#L22).

Sorry there isn't more we can do to help on this one!

**Comment by GerryOldMan** [comment]
Thats great. Thanks. Just wanted to check.

**Comment by namanagrawal94** [comment]
> What version of Gophish are you using?: 0.7.1
> 
> Brief description of the issue:
> Scheduled emails not sent due to reaching daily limit on GMail account. Dashboard shows the below error for email that has not been sent:
> 550 5.4.5 Daily user sending quota exceeded
> 
> Does GoPhish continue to try sending these emails, or should I create a new campaign when the limit has cleared?

Hi,

Do you know how can i send email to 10,000 users at a time in a single day?
