### ISSUE TITLE
Share step run Gophish as a service

### ISSUE THREAD

**Issue by momaydopod** [gophish/gophish#1608]
I try to find many manual on the internet to configure Gophish as a service.

My the Gophish run on ubuntu 18.0  Please following this step for running Gophish as a service

Refer.
https://kifarunix.com/install-gophish-on-ubuntu-18-04-debian-9-8/

**Comment by jordan-wright** [comment]
It’s not clear what the issue is here, if there is one. If you are encountering issues running Gophish, please create a new issue and follow the provided issue template.

Thank you!
