### ISSUE TITLE
false positive on email open status

### ISSUE THREAD

**Issue by r4w4t** [gophish/gophish#1611]
Version of Gophish I am using.: 
0.7.1

Brief description of the issue: 
False-positive on email opened.

What are you expecting to see happen? :
I am using aws SES and SNS(for tracking notifications on delivery, read, etc), I tried sending mail from my domain, everything is fine except that I never opened any of the emails I received but it's still showing email opened in status on the dashboard

What are you seeing happen?
Amazon SNS is working like a charm for tracking if the mail has been opened or not, but then I have to cross-check for every email I sent.

cause of the issue(maybe):
I am not sure but maybe it's happening because of all the protection mechanisms used inside a corporate network(firewall etc) and something is triggering the event and leading to false positives.

Solution (maybe):
If that's the cause of the issue then email tracking can be implemented in a way so that it only triggers when it is being kept open for a few seconds.

**Comment by glennzw** [comment]
If you're using SES and SNS to track delivery it's probably tracking links in the email and 'clicking' on them in the background. Remember a 'click' is just a HTTP GET of the URL. I know I had this problem with SendGrid and had to turn off link tracking.

Watch your Gophish logs, you should see the GET requests coming through with an rid parameter and your Gophish server. The source IP and user agent will help you track down what's 'clicking' the links.

**Comment by jordan-wright** [comment]
Hi there!

As mentioned by @glennzw, some mail providers (in some cases both senders and receivers) may visit URLs found in emails to prevent spam and abuse. I'm afraid there isn't anything we can do about this in Gophish.

Sorry we can't do more to help!

**Comment by r4w4t** [comment]
> If you're using SES and SNS to track delivery it's probably tracking links in the email and 'clicking' on them in the background. Remember a 'click' is just a HTTP GET of the URL. I know I had this problem with SendGrid and had to turn off link tracking.
> 
> Watch your Gophish logs, you should see the GET requests coming through with a rid parameter and your Gophish server. The source IP and user agent will help you track down what's 'clicking' the links.

Facing the same issue with my own POSTFIX, I also tried GoDaddy relay, and sometimes it's showing email opened even before the email reaches to inbox. What do you think the problem is?

**Comment by ironc0in** [comment]
**Long Solution**: access the backend database (if that's possible) do a search of all the IP entries of the mail filter and remove them. GoPhish dashboard should now only have human clicks.
**Short and Dirty Solution**: Do an _Export CVS > Results_ of the campaign. Remove all rows with the offending IP address, create a formula or chart in excel with the new cleaned up data to get the real count of user clicks.
