### ISSUE TITLE
Move LoggingConfig into logger package

### ISSUE THREAD

**Issue by jordan-wright** [gophish/gophish#1613]
I'd like to use the `github.com/gophish/gophish/logger` package in other Gophish projects, but right now that's not very easy since the `LoggingConfig` is located in the `github.com/gophish/gophish/config` package.

The fix for this would be to move the `LoggingConfig` struct into the `logger` package, update the `log.Setup()` function to use that local struct, and update the `config.Config` to import from the correct place.

This is a great first issue to dive into the Gophish codebase!

**Comment by glennzw** [comment]
Having a go at this.

I've moved the `LoggingConfig` struct to `logger.go`, and updated the `Config` struct in `config.go` to import from the correct place:

```
Logging        logger.LoggingConfig `json:"logging"`
```

This of course needs to import `"github.com/gophish/gophish/logger"` which results in an import cycle (as `logger.go` imports "github.com/gophish/gophish/config").

And now I'm stuck 🙃

**Comment by glennzw** [comment]
Also, as a point of clarification, we want to use the `logger` package in other projects, but the `logger:Setup(conf *config.Config)` function is very specific for Gophish. Or would we have different `config.Config` structs for each project?

**Comment by jordan-wright** [comment]
So I would have the `Setup` function take a `LoggingConfig` object as the argument. After all, we only ever access `config.Logging` objects anyway so this should make it much cleaner 😄

**Comment by jordan-wright** [comment]
Closed via caede2e
