### ISSUE TITLE
WebService is not being created. & (wrong version in the settings)

### ISSUE THREAD

**Issue by kolet** [gophish/gophish#1615]
What version of Gophish are you using?: 
LATEST

Brief description of the issue: 
doesn't open a web service

What are you expecting to see happen? :
before a Campaign is made u should receive a 404 that a page is not found.
at least u know when u receive a 404 that the webservice do run

What are you seeing happen?

nothing.
no web service is being created.

for the tests, im using kali linux.

the gophish dashboard do works on the https , not the phishing url.
i tried to change the port from 80 to a different one, and that still does not work.

nothing is listening on port 80 

![image](https://user-images.githubusercontent.com/17353839/66582767-f7633900-eb8a-11e9-9cdf-b6debd4e5e9e.png)

second visual bug.

on the account settings (settings)
it shows Gophish version0.7.1 when i am on the lastest one. (Gophish v0.8.0 showed in user guide )  
![image](https://user-images.githubusercontent.com/17353839/66582368-52e0f700-eb8a-11e9-8dda-1d5d1daf4977.png)

**Comment by S0larflare** [comment]
What does the console show when you start GoPhish?

Sent from my iPhone

On 10 Oct 2019, at 16:18, kolet <notifications@github.com> wrote:

﻿

What version of Gophish are you using?:
LATEST

Brief description of the issue:
doesn't open a web service

What are you expecting to see happen? :
before a Campaign is made u should receive a 404 that a page is not found.
at least u know when u receive a 404 that the webservice do run

What are you seeing happen?

nothing.
no web service is being created.

for the tests, im using kali linux.

the gophish dashboard do works on the https , not the phishing url.
i tried to change the port from 80 to a different one, and that still does not work.

second visual bug.

on the account settings (settings)
it shows Gophish version0.7.1 when i am on the lastest one. (Gophish v0.8.0 showed in user guide )
[image]<https://user-images.githubusercontent.com/17353839/66582368-52e0f700-eb8a-11e9-8dda-1d5d1daf4977.png>

**Comment by kolet** [comment]
everything starts normaly no errors.

![image](https://user-images.githubusercontent.com/17353839/66588694-aefd4880-eb95-11e9-97cd-acd1163d36f4.png)

**Comment by glennzw** [comment]
Looks like you're running the command as 'user'. Try slap a sudo in front.

**Comment by kolet** [comment]
> Looks like you're running the command as 'user'. Try slap a sudo in front.

works like a charm ;)
thanks.

worth writing it in the documentation :)

**Comment by glennzw** [comment]
@jordan-wright Maybe a note to add to the documentation 👆

**Comment by jordan-wright** [comment]
Added a note to the documentation - thanks!
