### ISSUE TITLE
Does not fetch the whole page (which cause an auto redirect to the real domain) & X-Server (header) gives u away!

### ISSUE THREAD

**Issue by kolet** [gophish/gophish#1616]
hey there,
not sure if its a bug or its intentionaly.

1.  when trying to create a landing campaing it will fetch the html page but all js and pictures are still being taken from the real domain .

problem that accures is that, since all the "js links" are from the real domain it will auto redirect u to the real domain even before seeing the phishing page.

2, when trying to do a pentest there is something that gives right away ur campaing if u/they have an IDS /IPS inplace.

the X-Server in the header is gophish

![image](https://user-images.githubusercontent.com/17353839/66589305-eae4dd80-eb96-11e9-9ffb-1989d09a10d7.png)

this is basically will give u away immediately

**Comment by glennzw** [comment]
For 2. you can comment out [this line](https://github.com/gophish/gophish/blob/master/controllers/phish.go#L207) and recompile:

`w.Header().Set("X-Server", config.ServerName)`

**Comment by kolet** [comment]
> 1. A hacky solution is to create a single HTML file from the target website, inlining CSS, JS, and representing images in Base64. There are various tools to do this, e.g https://github.com/remy/inliner. e.g:
>    `inliner http://foobar2000.com > out.html` results in [this single file](https://pste.eu/p/gcan.html)
> 2. You can comment out [this line](https://github.com/gophish/gophish/blob/master/controllers/phish.go#L207) and recompile:
>    `w.Header().Set("X-Server", config.ServerName)`


1. how do u implement that into gophish "landing campain page" if u'd like to get the post data

2, thanks!,
but that kinda sucks u gota recompile everything ..

**Comment by jordan-wright** [comment]
>>> when trying to create a landing campaing it will fetch the html page but all js and pictures are still being taken from the real domain .
problem that accures is that, since all the "js links" are from the real domain it will auto redirect u to the real domain even before seeing the phishing page.

The landing page importing feature of Gophish takes a best-effort approach. We don't recursively clone down assets as this gets complicated quickly. Instead, making sure that any included JS on the landing page doesn't cause issues is left to the user of Gophish.

> but that kinda sucks u gota recompile everything ..

I understand that this can be frustrating, but this header exists as part of our efforts to [be transparent where possible](https://github.com/gophish/gophish/issues/1057). I'd be interested to hear more about why you feel this would compromise the integrity if your testing, though in the meantime since there isn't anything to fix in Gophish I'm going to go ahead and close this one out.

Thanks for getting in touch!

**Comment by kolet** [comment]
> > > > when trying to create a landing campaing it will fetch the html page but all js and pictures are still being taken from the real domain .
> > > > problem that accures is that, since all the "js links" are from the real domain it will auto redirect u to the real domain even before seeing the phishing page.
> 
> The landing page importing feature of Gophish takes a best-effort approach. We don't recursively clone down assets as this gets complicated quickly. Instead, making sure that any included JS on the landing page doesn't cause issues is left to the user of Gophish.
> 
> > but that kinda sucks u gota recompile everything ..
> 
> I understand that this can be frustrating, but this header exists as part of our efforts to [be transparent where possible](https://github.com/gophish/gophish/issues/1057). I'd be interested to hear more about why you feel this would compromise the integrity if your testing, though in the meantime since there isn't anything to fix in Gophish I'm going to go ahead and close this one out.
> 
> Thanks for getting in touch!

HI!
well u can keep this feature on, but i think it would be nice for the user to have an option to decide if he want this header to be on/off , like a togle flag. in the gophish dashboard , that way he (user) can check if everything works properly, and if it does it will togle it off.
as u know to have a successful campaing in a pentest environment everything should be near perfect with out stuff that gives u away.
in this matter tho , where gophish is clearly noticable thats giving u away by any ips/ids/firewall etc..
yes u can recompile the whole thing, but a togle option would be nicer instead of recompiling the whole project.

2nd thing
in my case i tried to clone a regulare page from an unknow site, just for the sake of the test.
when doing so i was automaticly redirected to port 443 (https) on my domain.
