### ISSUE TITLE
I want to build gophish using the branch attachment-support

### ISSUE THREAD

**Issue by daniyaltahir84** [gophish/gophish#1617]
I have manually edited the 9 files indicated in #260 and then trying ot build the branch attachment-support but getting the following errors.
![image](https://user-images.githubusercontent.com/54836022/66834568-4e944f80-ef77-11e9-84b9-d9d91cbf77b2.png)

**Comment by jordan-wright** [comment]
Note that this branch isn’t officially supported, so there’s limited help we’ll be able to provide.

But, for this particular error, try running “go get ./...” from the Gophish directory to install the needed dependencies.

**Comment by daniyaltahir84** [comment]
I have cloned gophish master and able to build it properly but i want to use this branch.

**Comment by jordan-wright** [comment]
I'm afraid that using anything except the `master` branch is very experimental and not something we provide broad support for.
