### ISSUE TITLE
Phishing server isn't listening

### ISSUE THREAD

**Issue by lucianocaba** [gophish/gophish#1622]
Dear All, I installed Gophish server, I can access to the admin server and I configured a campaign, but the phishing server isn't listening. It is not a firewall problem, even the phishing server cannot be accessed from the local host.
Any help will be appreciated.

Gophish current version: 20190105192341
Starting log:
time="2019-10-17T12:33:23Z" level=info msg="Starting admin server at https://0.0.0.0:3333"
time="2019-10-17T12:33:23Z" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
time="2019-10-17T12:33:23Z" level=info msg="Starting phishing server at http://0.0.0.0:80"

JSON Config:
{
        "admin_server": {
                "listen_url": "0.0.0.0:3333",
                "use_tls": true,
                "cert_path": "gophish_admin.crt",
                "key_path": "gophish_admin.key"
        },
        "phish_server": {
                "listen_url": "0.0.0.0:80",
                "use_tls": false,
                "cert_path": "gophish.crt",
                "key_path": "gophish.key"
        },
        "db_name": "sqlite3",
        "db_path": "gophish.db",
        "migrations_prefix": "db/db_",
        "contact_address": "",
        "logging": {
                "filename": ""
        }
}

ubuntu@ip-xx-xx-xx-xx:~/w3m$ w3m localhost
w3m: Can't load localhost.

ubuntu@ip-xx-xx-xx-xx:~/w3m$ nmap localhost

Starting Nmap 7.60 ( https://nmap.org ) at 2019-10-17 12:44 UTC
Nmap scan report for localhost (127.0.0.1)
Host is up (0.000088s latency).
Not shown: 998 closed ports
PORT     STATE SERVICE
22/tcp   open  ssh
3333/tcp open  dec-notes

Nmap done: 1 IP address (1 host up) scanned in 0.06 seconds
ubuntu@ip-172-30-0-117:~/w3m$

I changed the address of the phishing server (config.json) to the local IP of the server.... same result

**Comment by zieba88** [comment]
I have the same issue. Looks like its a bug.

**Comment by jordan-wright** [comment]
This is likely due to to Gophish being run without the appropriate permissions to bind to port 80. Try running it with `sudo`.

The bug in this case is that we should catch the fact that Gophish wasn't able to bind to the port, log the error, and exit. I'll fix this when I get a chance.

**Comment by zieba88** [comment]
Hi Jordan!

I should've caught that and ports lower than 1000 require root access. That solved my problem. Thank you!

**Comment by glennzw** [comment]
> This is likely due to to Gophish being run without the appropriate permissions to bind to port 80. Try running it with `sudo`.
> 
> The bug in this case is that we should catch the fact that Gophish wasn't able to bind to the port, log the error, and exit. I'll fix this when I get a chance.

I fixed this here https://github.com/gophish/gophish/pull/1635

**Comment by jordan-wright** [comment]
This has been fixed as of 28252bcb560b44251aa53b97680b5e664a6d7c2c. Thanks @glennzw!
