### ISSUE TITLE
API: Creating user should return initial API key

### ISSUE THREAD

**Issue by edermi** [gophish/gophish#1624]
What version of Gophish are you using?: 

0.8

Brief description of the issue: 

I'm building scripts to setup Gophish instances for multiple users.
When creating a user [via API](https://docs.getgophish.com/api-documentation/user-management), it is not possible to interact with the API using the created user. This makes it impossible to use Gophish without manual interaction (getting the API key once via Browser and web interface). 

What are you expecting to see happen? :

Since the user creating another user is in possession of the initial password, there would be no harm in just returning the API key for the created user in the JSON response. 

What are you seeing happen?

The only way to interact with the new user is to fetch the API key by browsing the web interface.

**Comment by jordan-wright** [comment]
This seems reasonable, I bet we can make that happen.
