### ISSUE TITLE
How many users we can target in a single campaign without slowing down the server?

### ISSUE THREAD

**Issue by bhagoria** [gophish/gophish#1625]
I have just instaled a V0.8.0 and tested it and it works fine. I am planning to have a company-wide campaign but before starting the same want to know the email sending limit.  How many users we can target in a single campaign without slowing down the server?

Thanks!

**Comment by jordan-wright** [comment]
Hi there!

The emailing shouldn’t be a problem- as long as your mail server handles the outgoing emails then you’ll be all set.

The only possible performance issue would be in the web UI. The way it loads results has been known to slow down the browser for campaigns with > a few thousand recipients. If you encounter that behavior, then I encourage you to consider using the API for reporting.

I hope this helps!
