### ISSUE TITLE
Can we spoof the sender?

### ISSUE THREAD

**Issue by alme5** [gophish/gophish#1628]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.8.0
Brief description of the issue: 
I would like to send spoofed emails.
What are you expecting to see happen? :
Spoofed emails to reach users mailbox.
What are you seeing happen?
Email coming from my fake domain instead.
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 - 
 
 
Greetings,
I am performing a phishing campaign against my organization but I have not been able to spoof our domain so far. 
My scenario is the following:
Our real domain: realdomain.com
Domain used for phishing: fakedomain.com

I have setup my own smpt relay with postfix and all is working fine and I am able to receive emails however the sender looks like hr@fakedomain.com  and instead I want it to look like: hr@realdomain.com

If I put HR <hr@realdomain.com>  under From: field I receive the following error:
 **553 5.7.1 : Sender address rejected: not owned by user hr@realdomain.com**
Which makes sense since I do not own that domain. 
Some two years ago when I first tried gophish I used to achieve this by playing with headers (X-Custom-Header). By putting this in there: From: "HR" <hr@realdomain.com> I was able to spoof the sender. 
Somehow this doesnt work anymore and when I try to do this the sender which appears on my mailbox is again the one in the From field:  HR <hr@fakedomain.com>

Any help?

**Comment by jordan-wright** [comment]
I'm afraid whether or not you can spoof a sender is dependent on a number of variables, all outside of Gophish's control, so there isn't any support we can provide there.

As long as you're putting the spoofed sender in the "From" field, then Gophish will attempt to send the email that reflects that. Doing some [searching](https://serverfault.com/questions/870888/sender-address-rejected-not-owned-by-user) it appears this is likely Postfix related.

Sorry there isn't more we can do to help!

**Comment by Ju777** [comment]
@alme5 @jordan-wright  Hello, did you find any solution ? It s nos about 4 years ago from your post ... I am hoping you're still working with Gophish ...
