### ISSUE TITLE
Display name issue for emails

### ISSUE THREAD

**Issue by mbasilecgtc** [gophish/gophish#1629]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: v0.8.0

Brief description of the issue: 
Display name for email address doesn't work when sending out of goPhish

What are you expecting to see happen? :
The display name to appear as it should in outlook as opposed to just the email address.
For an example of what I want to see:
Mike Tyson <MikeTyson@gmail.com>

What are you seeing happen?
The email address appears instead of the full name.

For example:
MikeTyson@gmail.com instead of the display name with email in parenthesis.
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
If you are specifying the email address as `Mike Tyson <miketyson@gmail.com>` in the "From" field in the sending profile, then you should be set as far as Gophish is concerned.

It's possible that some email clients are set up to display the email address regardless of whether or not a display name is set. My only advice would be to check the raw email transaction to make sure that what you're putting in the From field is what's reflected in that transaction.

Sorry there isn't more we can do to help here!
