### ISSUE TITLE
Cannot get gophish to track when users are opening emails.

### ISSUE THREAD

**Issue by buchheit-it** [gophish/gophish#1632]
I'm new to Gophish and perhaps I'm missing something. When creating a campaign I want to be able to see when the end-users are even just reading the email. We use Outlook, if that helps. In the Email template I have "add tracking image" selected and it still will not show whenever the end-user even reads the email. Any help is appreciated, thanks.

**Comment by jordan-wright** [comment]
Hi @buchheit-it,

Whether or not the tracking image works is dependent on the email client. Some, like Outlook in many cases, block these tracking pixels due to privacy concerns. I'm afraid there isn't anything we can do in Gophish to prevent this from happening.

Sorry we couldn't be of more help!

**Comment by buchheit-it** [comment]
Are there ways we can disable Outlook from blocking this?
