### ISSUE TITLE
Failure to capturing submitted data and redirection 

### ISSUE THREAD

**Issue by alme5** [gophish/gophish#1636]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.8.0

Brief description of the issue: 
On the landing page I have a simple login form and I cap ticked the option to capture submitted data but not passwords as I dont want that. After submitting the data I want my users to be redirected at: http://secret.domain.com/static/index.html  where I have put a small phishing description and is accessible form outside.  The gophish is running under http://secret.domain.com.
Unfortunately after user logs in the page is redirected to the following http://secret.domain.com/?email=name%40domain.com&password=test123 with the classic 404 error.

What are you expecting to see happen? :
Username to be captured and the user to be redirected to the correct page.

What are you seeing happen?
Username not captured and user is redirected to an error 404 page.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
<!DOCTYPE html><html><head>
	<title>CSSO</title>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet"/><script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
<form action="" class="form"><label for="email">Email: </label><input autofocus="" class="form-control" id="email" name="email" required=""/> <label for="password">Password: </label><input class="form-control" id="password" name="password" required=""/><br/>
<input class="form-control btn btn-lg btn-primary" type="submit"/> </form>
</div>


</body></html>```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

**Comment by jordan-wright** [comment]
Try adding a `method=“POST”` to your form. That should fix it :)

**Comment by jordan-wright** [comment]
Going ahead and closing this out since the advice above should fix your issue. Let us know if you continue to run into issues!
