### ISSUE TITLE
Stuck at gophish admin server starting. Admin dashboard will not load..

### ISSUE THREAD

**Issue by grayskyze** [gophish/gophish#1637]
I am using the latest version (v8.0) of gophish. I pulled down the zipped file from here: https://github.com/gophish/gophish/releases/

Brief description of the issue: 
When trying to run the gophish service, it just hangs at the starting admin service line:
 
> time="2019-10-28T21:03:09-04:00" level=warning msg="No contact address has been configured."
> time="2019-10-28T21:03:09-04:00" level=warning msg="Please consider adding a contact_address entry in your config.json"
> goose: no migrations to run. current version: 20190105192341
> time="2019-10-28T21:03:09-04:00" level=info msg="Starting admin server at https://127.0.0.1:3333"
> time="2019-10-28T21:03:09-04:00" level=info msg="Starting phishing server at http://0.0.0.0:80"
> time="2019-10-28T21:03:09-04:00" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"`

Not sure why it's just hanging on this step and won't load. I cannot visit the phishing server or admin page at all. When I attempt to browse to it, the browser just hangs.

Just in case, here's my config.json:

> `{
> 	"admin_server": {
> 		"listen_url": "127.0.0.1:3333",
> 		"use_tls": true,
> 		"cert_path": "gophish_admin.crt",
> 		"key_path": "gophish_admin.key"
> 	},
> 	"phish_server": {
> 		"listen_url": "0.0.0.0:80",
> 		"use_tls": false,
> 		"cert_path": "example.crt",
> 		"key_path": "example.key"
> 	},
> 	"db_name": "sqlite3",
> 	"db_path": "gophish.db",
> 	"migrations_prefix": "db/db_",
> 	"contact_address": "",
> 	"logging": {
> 		"filename": ""
> 	}

`
FYI. I'm on Kali Linux and I have a fresh install of Go configured.
****
Just want to point out, that when I first ran the ./gophish command I was able to load the admin page just fine. I faced the issue once I tried to relaunch and browse to the same localhost and port. This has happened on two separate VMs now. Am I missing something?

**Comment by jordan-wright** [comment]
Try running with sudo or checking your firewall rules. It’s likely to be one of those things.

**Comment by grayskyze** [comment]
Closing this issue. I was running as sudo and the firewall config I checked. Turned out that I was not closing the gophish service correctly. I was using CTRL + Z instead of CTRL + C. After I CTRL + C and killed all gophish services. I rebooted and was able to get it up and running w/ no problem. Thanks for your assistance.

**Comment by RickkeeC** [comment]
I was a N00b.  Run the setup in regular CMD prompt.  It hangs if you try to run CMD as admin.  Dooh!

**Comment by wingriddenangelxxx** [comment]
same is happening to me but mine never opened 
i got this problem from the jump

**Comment by traveltek-jnewall** [comment]
Hey guys, im currently working on this and seem to be getting blocked by bit defender. No matter what I do, im not getting the access. Ive tried adding the URL as an exception with bit defender and still having no luck. Any advice would be much appreciated.
