### ISSUE TITLE
Document Ability to Have Static Content Hosted on Phishing Server

### ISSUE THREAD

**Issue by jordan-wright** [gophish/gophish#164]
We allow static content to be hosted on the phishing server. Need to document this capability.

**Comment by jcamil** [comment]
I should be able to work on the documentation over the next few days.

**Comment by jordan-wright** [comment]
Awesome! If you'd like to leave the docs here in markdown, I'll drop them in the pdf user guide.

**Comment by jordan-wright** [comment]
Hey @jcamil - any luck with this? I have some time over the next couple days so I can knock it out if needed.

**Comment by scottg88** [comment]
I was curious how to do this and I worked it out. Is it intentional for files to have to be under e.g.:

static/endpoint/static/example.png

to be reachable by http://phishserver/static/example.png ?

If not, looks like http.StripPrefix can be used to allow the files to be dropped in just 'static/endpoint/'.

**Comment by jordan-wright** [comment]
Oh man, *that's* it?! No joke, when I originally dropped that static path in, I completely forgot about it for the longest time until someone needed to use it.

Then, I couldn't get it to work! I never tried endpoint/static/something.

That makes perfect sense. I'll see if I can strip out that prefix to make it easier for everyone. 

Great find!

**Comment by jordan-wright** [comment]
I've fixed this so that files are reference as follows:

```
http://phishserver/static/image.png
```

**Comment by adrigondite7** [comment]
can you document this in the gophish guide?

"Static Assets
There may be times that you want to store assets such as HTML pages, CSS/JS resources or other static files. To use these in Gophish, just move them under the static/endpoint directory. You can then reference them using the URL http[s]://phishing_server/static/filename. For more background, see this issue."
