### ISSUE TITLE
Installing guide doc from august 2019?

### ISSUE THREAD

**Issue by SirOussama** [gophish/gophish#1645]
Hello,
I already know that you have this documentation: docs.getgophish.com/user-guide/installation
But I'm looking for the "old" documentation for how to install gophish.
Can you please show me the dir or maybe a link.

Thank you in advance.

**Comment by jordan-wright** [comment]
I’m not sure what you mean- all the documentation for the user guide is in this repo so maybe you’re just looking for an older commit there?

https://github.com/gophish/user-guide

Alternatively, if you’re looking for the original PDF, you can probably find it in old commits of the Gophish repo.
