### ISSUE TITLE
Gophish not working with HTTPS

### ISSUE THREAD

**Issue by Leenders-IT** [gophish/gophish#1646]
How do you do?

I have the problem that my Gophish server doesn't work under HTTPS but the admin page is reachable via HTTPS without problems only the phishing site doesn't work 

this is the config

{
        "admin_server": {
                "listen_url": "0.0.0.0:3333",
                "use_tls": true,
                "cert_path": "phish.crt",
                "key_path": "phish.key"
        },
        "phish_server": {
                "listen_url": "0.0.0.0:443",
                "use_tls": true,
                "cert_path": "phish.crt",
                "key_path": "phish.key"
        },
        "db_name": "sqlite3",
        "db_path": "gophish.db",
        "migrations_prefix": "db/db_",
        "contact_address": """
}

The server is hosted via Azure

**Comment by jordan-wright** [comment]
Without knowing more details of what you mean by “doesn’t work”, I’m afraid there isn’t anything we can do to help you out.

Please tell us what you tried, what you see, if you see any logs, if you have azure setup to allow the connection, etc. Any details will help.

**Comment by glennzw** [comment]
I'm going to hazard a guess and say you're not running as root, so it can't bind to 443. Try running `sudo ./gophish` (if you're not already).
