### ISSUE TITLE
issues instaling gophish

### ISSUE THREAD

**Issue by DSUN01** [gophish/gophish#1647]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue: 

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by DSUN01** [comment]
when ever i type go get github.com/gophish/gophish  command i find below pls i need help

package github.com/gophish/gophish: cannot download, /root/go is a GOROOT, not a GOPATH. For more details see: 'go help gopath'

**Comment by glennzw** [comment]
Looks like your GOPATH isn't set. See https://github.com/golang/go/wiki/SettingGOPATH

Alternatively you could download the compiled binary from https://github.com/gophish/gophish/releases
