### ISSUE TITLE
Can't send test email

### ISSUE THREAD

**Issue by kehlanrutan** [gophish/gophish#1649]
What version of Gophish are you using?: 0.7.1

Brief description of the issue: Trying to create a sending profile using Gmail and it fails sending the test email.  

What are you expecting to see happen? : for the test email to complete

What are you seeing happen?  Max connection attempts exceeded - dial tcp 172.253.112.108:425: i/o timeout

Logs: `2019/11/05 19:34:06 http: TLS handshake error from 127.0.0.1:50476: remote error: tls: unknown certificate
time="2019-11-05T19:35:46-05:00" level=warning msg="Max connection attempts exceeded - dial tcp 172.253.112.108:425: i/o timeout"
time="2019-11-05T19:35:46-05:00" level=error msg="Max connection attempts exceeded - dial tcp 172.253.112.108:425: i/o timeout"
time="2019-11-05T19:35:46-05:00" level=info msg="127.0.0.1 - - [05/Nov/2019:19:34:06 -0500] \"POST /api/util/send_test_email HTTP/2.0\" 500 131 \"https://127.0.0.1:3333/sending_profiles\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36\""`

On the google side to make sure, 2fa is off and I enabled the use of less secure apps, if that makes a difference.

**Comment by jordan-wright** [comment]
Seeing an I/O timeout indicates a likely network issue. It sounds like whichever device is hosting Gophish isn’t able to reach 172.253.112.108 on port 425.

If you’re running Gophish on a hosted server, it’s possible that outbound SMTP connections are blocked by the provider to combat spam.

**Comment by kehlanrutan** [comment]
I am hosting Gophish on my laptop.  So would it be a router or firewall setting?

**Comment by jordan-wright** [comment]
Could be either, but likely a firewall setting implemented by your ISP.

**Comment by kehlanrutan** [comment]
I have gophish hosted on my laptop, so I changed networks and tried again.  I get the same error. 
`2019/11/06 10:47:04 http: TLS handshake error from 127.0.0.1:55668: remote error: tls: unknown certificate
time="2019-11-06T10:48:44-05:00" level=warning msg="Max connection attempts exceeded - dial tcp 108.177.122.108:425: i/o timeout"
time="2019-11-06T10:48:44-05:00" level=error msg="Max connection attempts exceeded - dial tcp 108.177.122.108:425: i/o timeout"
time="2019-11-06T10:48:44-05:00" level=info msg="127.0.0.1 - - [06/Nov/2019:10:47:04 -0500] \"POST /api/util/send_test_email HTTP/2.0\" 500 131 \"https://127.0.0.1:3333/sending_profiles\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36\""`

**Comment by jordan-wright** [comment]
﻿
On further reading of the Gmail docs, I think port 465 or 587 is what you’re looking for, not port 425.

I’d recommend taking a look at the Gmail SMTP docs to determine which port and host name is right for your use case.

I hope this helps!

**Comment by kehlanrutan** [comment]
omg, sorry about that.  Thank you, this worked.

**Comment by rivapari** [comment]
Max connection attempts exceeded - dial tcp: lookup smtb.gmail.com465: no such host ....what ican do

**Comment by nonamebaby23** [comment]
> On further reading of the Gmail docs, I think port 465 or 587 is what you’re looking for, not port 425. I’d recommend taking a look at the Gmail SMTP docs to determine which port and host name is right for your use case. I hope this helps!
> […](#)
> > On Nov 6, 2019, at 9:55 AM, kehlanrutan ***@***.***> wrote: ﻿ I have gophish hosted on my laptop, so I changed networks and tried again. I get the same error. 2019/11/06 10:47:04 http: TLS handshake error from 127.0.0.1:55668: remote error: tls: unknown certificate time="2019-11-06T10:48:44-05:00" level=warning msg="Max connection attempts exceeded - dial tcp 108.177.122.108:425: i/o timeout" time="2019-11-06T10:48:44-05:00" level=error msg="Max connection attempts exceeded - dial tcp 108.177.122.108:425: i/o timeout" time="2019-11-06T10:48:44-05:00" level=info msg="127.0.0.1 - - [06/Nov/2019:10:47:04 -0500] \"POST /api/util/send_test_email HTTP/2.0\" 500 131 \"https://127.0.0.1:3333/sending_profiles\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36\"" — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

I do not understand you mean to say that in Host section along  with smtp.gmail.com we should write port number like this smtp.gmail.com<portnumber> or something else to do

**Comment by Anonstroboscope** [comment]
> Max connection attempts exceeded - dial tcp: lookup smtb.gmail.com465: no such host ....what ican do

its smtp.gmail.com:465 you miss spell the smtp
