### ISSUE TITLE
Custom CSS and Image

### ISSUE THREAD

**Issue by stoksoz1** [gophish/gophish#1651]
How can we create CSS on gophish? Also can we change the some of the image that used on the gophish admin panel?

**Comment by jordan-wright** [comment]
I’m not sure what you’re asking - custom CSS on the admin panel, or CSS for a landing page?

All images used by the admin panel are in the static folder.

**Comment by stoksoz1** [comment]
I want to change (css, image) the admin login page, and admin panel page.

**Comment by jordan-wright** [comment]
You will need to modify `static/css/main.css`, then run `gulp` to recompile the CSS/JS.
