### ISSUE TITLE
Exposing gophish to the internet. 

### ISSUE THREAD

**Issue by Azuredragon-eazy** [gophish/gophish#1659]
How do i expose gophish to the internet from kali linux, i dont have any vps, so i intend on using my kali linux and the server host, but i don't know how to make it public on the internet. 

I dont Know if ssh tunneling will fix it for me, but any help will be appreciated.

**Comment by ntoenis** [comment]
This is a better question on how to set up a webserver/open ports as this is not something restricted by gophish. If this is something you're building out in a home lab I'd start with searching how to get yourself a static IP and hardening of your kali instance before attempting to open it to the world

**Comment by Azuredragon-eazy** [comment]
But i thought gophish is running on it own server and doesn't work on apache, in general terms, how do i make it public from my kali linux, most especially the landing pages.

**Comment by jordan-wright** [comment]
As @ntoenis mentioning, this is a networking problem, not a Gophish problem. You will need to do something like port forwarding, or giving your host a public IP address. I'm afraid that how you do this is beyond the scope of the support we provide.
