### ISSUE TITLE
535 Authentication credentials invalid

### ISSUE THREAD

**Issue by Sleimboyy** [gophish/gophish#1665]
Help when I try to send a test email it says Max connection attempts exceeded - 535 Authentication credentials invalid

**Comment by jordan-wright** [comment]
It sounds like you are using invalid credentials for your mail server. I’m afraid without more information, it won’t be possible for us to troubleshoot further.

While this doesn’t sound like an issue with Gophish, if you continue to run into issues please create a new issue and provide all of the information requested in our template. The more info, the more we’ll be able to help identify the cause.
