### ISSUE TITLE
Open File Tracking

### ISSUE THREAD

**Issue by bhaizlett123** [gophish/gophish#1667]
Hello,

I wanted to see if there is a way to track open files. Like if i include a word document in the email, i would like to see how many people actually opened the word doc. I know i could probably inject some DDE to open a url, but is there a way to configure gophish to track that?

**Comment by bhaizlett123** [comment]
Just to add even if there is a way to append the rid parameter to something so when they open the file it tries to connect to that url and i can track that they opened the file?

**Comment by jordan-wright** [comment]
Hi there!

I'm afraid that Gophish doesn't support attachment tracking at this time, and I don't have an ETA on when this support would be added.

Sorry we couldn't be of more help!
