### ISSUE TITLE
Mail Crash! HELP! 

### ISSUE THREAD

**Issue by KiransHub** [gophish/gophish#1670]
UPDATES:

Initially I thought it was something to do with base64. Now I see it has something to do with the mailer.

I've narrowed this down to the use of the domain https://www.blackfridaydeals4u.co.uk. It only seems to fall over when this domain is used?!

**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: **0.7.1**

Brief description of the issue: 

I used base64 to encode images in the email template. This was to prevent the mail client blocking the images. I've read in your issues that this is a tried and tested approach. 

Since doing that goPhish keeps crashing when emails are sent. I'm getting all sorts of issues where it just keeps crashing out. I tried to recreate the template just using images again and it crashed out. 

What are you expecting to see happen? :
I'm hoping it wouldn't crash
What are you seeing happen?
Crashes frequently especially when sending emails.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

I'm afraid I couldn't paste it all here as it was too big for github or paste bin! 

but you can see & download it here: https://gofile.io/?c=cGA24R

Please provide any terminal output that may be relevant below:

``` bash
time="2019-11-19T22:25:10Z" level=warning msg="record not found"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x8b5dfc]

goroutine 405 [running]:
github.com/gophish/gophish/models.NewPhishingTemplateContext(0xb56dc0, 0xc42016d080, 0xc4209127e0, 0x25, 0xc420139bb0, 0x5, 0xc420139bb8, 0x8, 0xc420139c10, 0xf, ...)
        /go/src/github.com/gophish/gophish/models/template_context.go:49 +0x18c
github.com/gophish/gophish/models.(*MailLog).Generate(0xc4200a3450, 0xc4201500e0, 0x0, 0xc4201500e0)
        /go/src/github.com/gophish/gophish/models/maillog.go:156 +0x340
github.com/gophish/gophish/mailer.sendMail(0xb5a180, 0xc4201e7ec0, 0xb54bc0, 0xc4202819d8, 0xc420156510, 0x1, 0x1)
        /go/src/github.com/gophish/gophish/mailer/mailer.go:154 +0x2a3
github.com/gophish/gophish/mailer.(*MailWorker).Start.func1(0xb5a180, 0xc4201e7ec0, 0xc420156510, 0x1, 0x1)
        /go/src/github.com/gophish/gophish/mailer/mailer.go:91 +0xd4
created by github.com/gophish/gophish/mailer.(*MailWorker).Start
        /go/src/github.com/gophish/gophish/mailer/mailer.go:85 +0x81

```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Import an email with a lot of images
 * Step 2 - Encode those images in base 64
 * Step 3 - try and email it out a few times

**Comment by KiransHub** [comment]
UPDATE: I restored the database to a last known working version. The template is there without base64 images.

Unfortunately the mail server is still crashing when trying to send any template. It's simply a mailer issue.

**Comment by KiransHub** [comment]
I've narrowed this down to the use of the domain https://blackfridaydeals4u.co.uk. It only seems to fall over when this domain is used?!

**Comment by S0larflare** [comment]
So it is crashing when it tries to insert the URL into the template, as far as I can tell. How have you set up the email? As going by the file you've linked to there are several cases of this:

`<a href="?rid=preview-92uM8ii">`

Have you removed or changed that when you pasted it, or is that how you have set it up on the console?

If GoPhish is crashing every time you try to run it, you should be able to delete the mails in the database. I would have thought clearing the mail_logs table in the database would sort this (but I would either wait for Jordan to confirm and/or back up the DB before doing this though).

**Comment by KiransHub** [comment]
Hey I found the issue to be a hidden character being present in the url for the landing page. Note if the url begins with a space then the crash will happen. I think you could possibly trim the url. 

My browser kept suggesting a url with hidden characters in it.
