### ISSUE TITLE
From First name and Last name not showing

### ISSUE THREAD

**Issue by bhaizlett123** [gophish/gophish#1672]
I keep testing out a campaign, and have configured the profile to use firstname lastname<email@domain.com> But for some reason every time i get the email, i only see the email address, without first last  name.

Gophish Version = 0.7.1

**Comment by jordan-wright** [comment]
Hi there!

> have configured the profile to use firstname lastnameemail@domain.com

I'm guessing you mean the sender address? In that case, make sure you're using this syntax:

```
First Last <email@domain.com>
```

If that doesn't work, then it's possible that you're running into a configuration on the receiving mail server which is forcing it to display only the email address.

I hope this helps!

**Comment by TheMime** [comment]
I am not sure if you figured this out or not, but I had a the same issue and it turns out it was because I saved the file in the wrong CSV format from excel. You have to use CSV (Comma delimited) it wont work if you use CSV (Macintosh) or CSV (MS-DOS) 

I hope this helps :)

**Comment by TheGroundZero** [comment]
@TheMime I assume @bhaizlett123 is talking about the "From" field in the Sending Profile configuration, you're talking about the targets under "Users & Groups".

**Comment by moolakarapaiyan** [comment]
@jordan-wright I am getting this error
how did you solved this
