### ISSUE TITLE
Expand reporting features in Admin Console

### ISSUE THREAD

**Issue by CyberM070** [gophish/gophish#1674]
What version of Gophish are you using?: 
Latest version
Brief description of the issue: 
@jordan-wright Chris Maddalena has created a great reporting tool for Gophish. See https://github.com/chrismaddalena/Goreport 
What are you expecting to see happen? :
An integration of his tool for reporting in the Admin Console would be awesome and makes it easier for users to download the reports straight from the dashboard.

**Comment by jordan-wright** [comment]
Hey there!

I appreciate you reaching out. Indeed, GoReport from @chrismaddalena is a stellar tool which I highly recommend.

I understand the desire to have that same capability in Gophish, though I don’t currently have plans to implement this. That said, if there are specific ways you’d like to see reporting in Gophish improved, please let me know!

GoReport is a perfect example of the ecosystem we create when we expose a useful API. I always encourage people who want custom or expanded features to leverage the API to fill those use cases.

Thanks again for getting in touch!
