### ISSUE TITLE
Landing Page not working. IIS page displays

### ISSUE THREAD

**Issue by tyitguy** [gophish/gophish#1675]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

0.7.1

Brief description of the issue: 

After creating an email Template with links and changeing the Link in the HTML code to {{.URL}} they never open the the landing page created in the Landing page section of gophish

What are you expecting to see happen? :

im expecting when selecting the links in the email sent for the landing page to open but all ive gotten so far is a default IIS Page.

What are you seeing happen?

When clicking on the links a Default IIS page opens

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

Please provide any terminal output that may be relevant below:

```
Insert output here


Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
It sounds like you have IIS running on TCP port 80. Gophish runs its own web server, so you’ll need to stop IIS.

Once you do that, you can restart Gophish and things should work correctly.

I hope this helps!
