### ISSUE TITLE
Change landing page to my custom URL in another server

### ISSUE THREAD

**Issue by yakir2b** [gophish/gophish#1676]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.8.0

Brief description of the issue: Change Landing page to custom URL on another server

What are you expecting to see happen? : If it available 

Hi,
There is an option to add a custom URL that is on another web server that i have made their all my modification and i want to use it?

Thanks for this great framework!

**Comment by jordan-wright** [comment]
Hi there!

I’m afraid it’s not quite clear what you’re trying to accomplish. Are you saying that when the user clicks the link in an email, you want them to go to a webpage not hosted by Gophish?

If so, you can do that by putting whatever you want in the campaigns URL field when setting it up. However, you won’t be able to track clicks, since the users won’t be going to Gophish.

**Comment by yakir2b** [comment]
Are you saying that when the user clicks the link in an email, you want them to go to a webpage not hosted by Gophish?
Yes.

So, i can run campaign without choosing landing page and URL fields? 
Or i can add my URL in the URL field (without landing page)?

By the tracking image option in the email template i will not get clicks tracking?

Thanks

So, i can run campaign without choosing landing page and URL fields? 
Or i can add my URL in the URL field (without landing page)?

By the tracking image option in the email template i will not get clicks tracking?

Thanks

**Comment by yakir2b** [comment]
I close it by mistake..

**Comment by jordan-wright** [comment]
You have to select a landing page, but the URL sent in emails is whatever you put in the campaign settings. It doesn’t _have_ to point to Gophish. You can set it to whatever URL you want, but you would lose click tracking.

The tracking image tracks email opens, not clicks. Clicks are tracked when the user hits your landing page. If you set the URL to something other than Gophish, then you can’t track clicks.

**Comment by yakir2b** [comment]
OK, i will try that.
For now i will stay with the "email open", maybe later i will do redirect at landing page to my web page to be able track clicks.

Thanks a lot Jordan

**Comment by yakir2b** [comment]
Hi, 
In the campaign i wrote my custom URL, but the users received the mail with the suffix "?rid" parameter.

There is a way to remove it? or choose not to add it?

Thanks

**Comment by edermi** [comment]
How is GoPhish supposed to track which users clicked the link or submitted data without the rid?

**Comment by yakir2b** [comment]
As said, By the tracking image option in the email template you can get the "email open" tracking.

**Comment by yakir2b** [comment]
> Hi,
> In the campaign i wrote my custom URL, but the users received the mail with the suffix "?rid" parameter.
> 
> There is a way to remove it? or choose not to add it?
> 
> Thanks

I manage to do it by not using template reference in the email template, i edit the link to have my custom URL.

Thanks
