### ISSUE TITLE
Duplicate emails being sent.

### ISSUE THREAD

**Issue by ISimplifyComplexity** [gophish/gophish#1677]
Hi,

We're using the latest version of gophish (v0.8.0).

I know that there's another ticket for this but it has been closed and I can't see a way to re-open it. 

We are sending to 3324 users, we found that the email is being sent out twice to some of them. 
I'm also seeing captures going down. People who have clicked the link and we're losing the results.

This is not great as we're running a live test at the moment.

I have a hunch that this might be caused by the race condition detailed in other messages. I know that you get around this by applying a lock but it's possible that the two threads are getting to the email simultaneously before one thread has an opportunity to lock the record. If this is the case then one way to get around this is to perhaps use an odd/even approach where you have two threads. One will only touch the even numbers the other will only touch the odd ones. Or just have a single thread that sends the emails out one at a time.

**Comment by KiransHub** [comment]
Went through the raw data CSV file and this confirmed that the emails were indeed sent to almost all of the users twice. 

One way to test this may be to replace the functions that write out the emails with ones that write to a log and perform a do work loop followed by some logging. You could then generate a list of fake email addresses and try to see if the problem occurs. 

I'm not a Go developer but I think this would allow you to possibly replicate the issue.

**Comment by jordan-wright** [comment]
Hey @KiransHub,

Sorry to hear that you're seeing duplicate emails being sent! I'd like to dig into the problem, but the issue is always reproducing the error.

Could you do me a favor and send me a copy of your raw events CSV to hi@getgophish.com? Feel free to anonymize as needed. All I need is to make sure that I can tell unique addresses apart. I'd like to see how quickly the duplicates get sent, what other activity is happening at the same time, etc.

If you by chance have the Gophish logs handy from that time as well, that would help immensely.

**Comment by KiransHub** [comment]
Hi Jordan, 

I will look into getting you those logs. I've got the raw data but need to process it to tokenize the email addesses. 

I wondered, would it be possible to just put a stub doWork function in the threads? Then you could simulate a workload whilst they wait for the mail server to respond? Would that possibly help to reproduce the problem?

**Comment by jordan-wright** [comment]
Hey there! We've made significant fixes in recent releases that I imagine have resolved this issue. You can find one such example in https://github.com/gophish/gophish/issues/1726.

Please do let me know if you encounter this in the latest release and we can continue troubleshooting. Apologies again for the inconvenience here! I always try to have Gophish work exactly as expected- _especially_ when it comes to the emails being sent, so bugs like this are always something I try to avoid.
