### ISSUE TITLE
Static images for email template

### ISSUE THREAD

**Issue by DKhalaf** [gophish/gophish#1678]
Hello

I'm using GoPhish version 0.8.0 on a Ubuntu Server
When sending an email with GoPhish, the recipient doesn't see the images.

The images are uploaded here, e.g: .../static/endpoint/image1.png - I can access the images via http://phishingserver/static/image1.png and there seems to be no issue.

But when the recipient receives the email, the content is blocked. Hitting "Show content" just loads and nothing really happens. I've tried sending it to different mail clients (Office365, outlook and gmail)

Does anyone know a fix for this? :-)

**Comment by H4xl0r** [comment]
please provide html layout of the mail

**Comment by 2013kaa** [comment]
> Привет
> 
> Я использую GoPhish версии 0.8.0 на сервере Ubuntu.
> При отправке электронного письма с GoPhish получатель не видит изображения.
> 
> Изображения загружаются здесь, например: ... / static / endpoint / image1.png - я могу получить доступ к изображениям через [http: //phishingserver/static/image1.png,](http://phishingserver/static/image1.png) и, похоже, проблем нет.
> 
> Но когда получатель получает электронное письмо, контент блокируется. Нажатие «Показать контент» просто загружается и ничего не происходит. Я пытался отправить его на разные почтовые клиенты (Office365, Outlook и Gmail)
> 
> Кто-нибудь знает решение для этого? :-)




Did you have a solution to the problem?

**Comment by Miesvanderlippe** [comment]
Hey,

It's better to use attached images and insert an image tag manually. If you add logo.png you'd insert `<img src="cid:logo.png">`. This sends the image with the original e-mail and displays it correctly.
