### ISSUE TITLE
Gophish not reporting email opened and link clicked

### ISSUE THREAD

**Issue by edrojas69** [gophish/gophish#1679]
What version of Gophish are you using?: 
- I'm using v0.8.0 

Brief description of the issue: 
- What I’m trying to do is to track when the email is open by the other person in order to be notified, not only when the mail has being sent, but also when the email has being opened and when the link has being clicked. I have integrated the TLS certificate and domain name in order to mitigate this issue, however the problem remain the same.

The emails template i have to use for the testing is this:

```html
<html>
<head>
	<title></title>
</head>
<body>
<p style="margin-left:13.5pt;">Hello {{.FirstName}},</p>

<p style="margin-left:13.5pt;">Please refer to the vital info I&#39;ve shared with you using Google Drive.&nbsp;</p>

<p style="margin-left:13.5pt;">Click <a href="{{.URL}}">https://google.com/drive/docs/file012345</a> and sign in to view details..</p>

<p style="margin-left:13.5pt;">&nbsp;</p>

<p style="margin-left:13.5pt;">Regards.</p>

<p style="margin-left:13.5pt;">&nbsp;</p>

<p style="margin-left:13.5pt;">CONFIDENTIALITY NOTICE:&nbsp; This e-mail and any transmitted files are private and confidential and are solely for the use of the recipient(s)&nbsp;to whom it is addressed.&nbsp; Any unauthorized review, use, disclosure, distribution or copying of this communication is strictly forbidden.&nbsp; If you have received this communication in error, please delete and immediately notify the sender via the e-mail return address.&nbsp; Thank you for your compliance.</p>

<p style="margin-left:13.5pt;">Please consider the environment before printing this e-mail.</p>

<p style="margin-left:13.5pt;">&nbsp;</p>

<p style="margin-left:13.7pt;">{{.Tracker}}</p>
</body>
</html>

```

**Comment by MECHcsd** [comment]
Experiencing the same issue using Google Suite. I think my issue is GoPhish and Google Suite are not connected with each other, meaning Google isn't saying to GoPhish, "Hey, John Doe opened the email". How is GoPhish suppose to know when someone opens an email or clicks on a link? They have to communicate with each other somehow, no? 

There is no documentation on setting this up with any email provider. So I am hoping someone answers you or you figure it out and respond with your findings.

Not sure how anyone is using this with such lack of documentation. Seems like a great application and I would really like to use it, but.... I don't know

**Comment by edrojas69** [comment]
I already fixed my problem, in the campaigns section when I placed the URL, I was doing it wrong, once I put the correct URL that was https: //your_domain.com, I could capture when the victim they open the email and when they click on a link 
![email](https://user-images.githubusercontent.com/40746404/69758671-e7091c80-113e-11ea-9187-dff954a0824b.png)
![tracking](https://user-images.githubusercontent.com/40746404/69758670-e7091c80-113e-11ea-8786-f6ec0e1ac891.png)

**Comment by jordan-wright** [comment]
Glad to hear you were able to resolve the issue!

**Comment by sidh104** [comment]
@edrojas69 could you help me here did you host a domain to perform the same or did you performed this on a locally hosted network. Could you provide the steps ? Thanks in advance
