### ISSUE TITLE
Collect additional data from browser / e-mail in events

### ISSUE THREAD

**Issue by grutz** [gophish/gophish#168]
It would be nice to gather the following information in the events database:

* Source IP
* User Agent
* Referer
* RID
* User Title

This would allow statistics to cover geolocation (using a geoip-db), browser type (phone, tablet, computer, etc), possible sharing of links, etc.

Right now I gather this from the raw HTTP log and have to correlate back to the user.

**Comment by jordan-wright** [comment]
Hey @grutz - thanks for the report!

I have good news and bad news:

* **Good** - We currently do check for geo ip info on tracking links. You can access this via the campaign ```results``` objects, which represent each user targeted in the campaign. They have the following structure:

```
"results": [
    {
      "id": "4408fd5bc60901c35e7352f0205282d26b27a9fc80bdd6ee4db4a6f87c1954bb",
      "email": "bjenius@morningcatch.ph",
      "first_name": "Boyd",
      "last_name": "Jenius",
      "position": "",
      "status": "Success",
      "ip": "x.x.x.x",
      "latitude": 0,
      "longitude": 0
    },
```

This also answers your questions about the RID, User Title, and Source IP.

* **Bad** - We don't seem to update the geo info on clicking the link or submitting data. That will be fixed.

* **Good** - We do [have a place](https://github.com/gophish/gophish/blob/master/controllers/route.go#L167) to capture browser information (user-agent, plugins, etc.)
* **Bad** - This isn't currently being done (watch #96 for this)

Hopefully this helps give a bit more info. I can try to add this information to the events. Things like browser info, lat, and lon I can see being helpful on a per-event basis as well as giving the last known information via the ```result``` objects.

**Comment by jordan-wright** [comment]
Hey @grutz, just wanted to check in - did this answer your question? We have a few ideas moving forward that I mentioned in the previous post. We'll probably open separate issues for getting those implemented to help with tracking.

**Comment by grutz** [comment]
@jordan-wright looks good, I wasn't seeing much in the results.csv file but when I dived into the sqlite database there certainly was more information. Thanks!

**Comment by choikappa** [comment]
Hi Grutz, 

Can I ask you which table did you query to get the user agents for the campaign?
