### ISSUE TITLE
Can I use Gophish multiple domains for several campaigns?

### ISSUE THREAD

**Issue by manuellobodescalzo** [gophish/gophish#1680]
**What version of Gophish are you using?:**
0.8.0
**Brief description of the issue:**
I want to use several domains that will use SSL for several campaigns.
**What are you expecting to see happen? :**
Multiple landing pages which show the domain instead of an IP and have the green ssl lock sign.
**What are you seeing happen?**
I can only use one landingpage that will actually "listen"

**Comment by jordan-wright** [comment]
As long as the domain points to your Gophish server, you should be fine. And make sure that you’re config.json has 0.0.0.0 as the IP address for the phishing server.

In the not too distant future, domains will be an actual object within Gophish, which will allow some nice features, like automatic certs via Lets Encrypt.

**Comment by manuellobodescalzo** [comment]
Thank you so much jordan-wright

**Comment by websecnl** [comment]
Is there any gophish fork which already has domains as actual objects, with automatic LetsEncrypt config?
