### ISSUE TITLE
No redirection to landing page  and no data recorded

### ISSUE THREAD

**Issue by bhamudha04** [gophish/gophish#1682]
What version of Gophish are you using?: 
Gophish v0.7.1; 

Brief description of the issue: 
No Data /User activity tracked in the campaign, when the received phishing email opened and clicked on the link, landing page is not getting opened. 

What are you expecting to see happen? :
Once user opened email and clicked the link. it should redirect to landing page and the results should get recorded in go-phish.

What are you seeing happen?
No log or No data get tracked.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
<html>
<head>
	<title></title>
</head>
<body>
<p>Please update your profile <a href="{{.URL}}">here</a>.</p>
{{.Tracker}}</body>
</html>
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 – Installed go-phish in Win 2008R2 using the Installer: gophish-v0.8.0-windows-64bit
 * Step 2 – Reset the Admin credential
* Step 3 – Created a sending profile. Office 365 SMTP address used and tested. Working fine. 
* Step 4 – landing Page – imported from dropbox, enabled Capture Submitted Data and Capture Passwords options. Redirection set with internal site.
* Step 5 – Simple email template created, as per the given html code above.
* Step 2 – Created a user groups.
* Step 2 – New campaign has been created. Note: URL set as Phishing server alias record name. ( Alias record: dropbox.protected.com.)
Output:
#. Mail has not reached user mail box – Fixed by whitelisting the sender address and phishing server in O365 Antispam policy. Now users are receiving the phishing email in their inbox.
#. When the received phishing email opened and clicked on the link, landing page is not getting opened. It is getting redirect to https://dropbox.protected.com/?rid=77xB76n URL that is defined while creating a campaign with rid value. Error: This site can’t be reached
#. Expected was, link should redirect to landing page – it is not happening
#. Mail open – No data recorded
#. Phishing link clicked – No data recorded.

**Comment by jordan-wright** [comment]
Hi there!

It sounds like the issue is that the URL you're using in your campaign isn't pointing to your Gophish phishing server. Otherwise, the user would see the landing page when they click the link. You can find some tips on troubleshooting this [here](https://docs.getgophish.com/user-guide/faq#events-arent-showing-up-on-the-dashboard).

I hope this helps! Let me know if you continue to run into issues.

**Comment by bhamudha04** [comment]
Thank you for your quick response. Issue Fixed.  Note: Observed, default IIS was running in the server, once I stopped that, it was pointing back to Phishing server.

**Comment by Elliotagbons** [comment]
> Hi there!
> 
> 
> 
> It sounds like the issue is that the URL you're using in your campaign isn't pointing to your Gophish phishing server. Otherwise, the user would see the landing page when they click the link. You can find some tips on troubleshooting this [here](https://docs.getgophish.com/user-guide/faq#events-arent-showing-up-on-the-dashboard).
> 
> 
> 
> I hope this helps! Let me know if you continue to run into issues. 

My domain is pointing, but not data is being recorded neither is the phishing page opening
