### ISSUE TITLE
Version file not matching current release

### ISSUE THREAD

**Issue by usernotification** [gophish/gophish#1683]
What version of Gophish are you using?: 0.8 (source build)

Brief description of the issue: Version file shows 0.7.1

What are you expecting to see happen? : A version file reflecting the current release
Got confused while finding out why I got the `msg="Max connection attempts exceeded - dial tcp xxxxxxxxxx:25: i/o timeout" ` (still have to find the cause) and re-installed 3 times before looking into the version file.

Please bump version. Thanks!

**Comment by jordan-wright** [comment]
This is a known issue (see #1551, #1615, and #1563) as well as this note in the [release itself](https://github.com/gophish/gophish/releases/tag/v0.8.0):

> Note: The VERSION file for these releases still says 0.7.1. This was an oversight during the release process. After upgrading, even if you see 0.7.1, you're certainly running the 0.8.0 codebase. I apologize for the inconvenience!
