### ISSUE TITLE
[Feature] Monitoring pressing a link

### ISSUE THREAD

**Issue by CG-root** [gophish/gophish#1684]
Is it possible to add an option that in addition to capturing a data from the user, it will be possible to add a link to the landing page and once a user clicks on it, it will send an update to the GoPhish server and add it in the statistics ?
Thanks!

**Comment by glennzw** [comment]
I've been thinking about this for a while too. My idea is to have arbitrary callbacks, for example:

```
/callback {"name": "Secondary Link", "rid": "DgZKuT7", "data": "User clicked second link"}

/callback {"name": "Opened Word Document", "rid": "DgZKuT7", "data": "Office Version: 2003"}

/callback {"name": "Watched Training Video", "rid": "DgZKuT7", "data": "Watched 'How to Spot a Phish'"}

/callback {"name": "Ran executable file", "rid": "DgZKuT7", "data": "OfficeUpdate.exe'"}

/callback {"name": "Signed Agreement", "rid": "DgZKuT7", "data": "'"}

```

Then in the UI we could this data to the timeline:

![Screen Shot 2020-01-28 at 16 30 06](https://user-images.githubusercontent.com/3966613/73283776-843e0b00-41eb-11ea-98d8-c1140b641995.png)

Obviously my simplified JSON above would need to include the extra info around which icons to use and how to lay out heading and main text, but you get the idea.

Thoughts @jordan-wright  ? I think we could add loads of cool functionality with this small modification.

**Comment by ChrisASE** [comment]
I love this idea. Post click educational phishing training is a key feature of a service I help to provide to clients. Breaking down exactly what a user clicks on the landing page and whether they watch the training video would be amazing.

Has there been any further discussion on this in the last 6 Months?


> I've been thinking about this for a while too. My idea is to have arbitrary callbacks, for example:
> 
> ```
> /callback {"name": "Secondary Link", "rid": "DgZKuT7", "data": "User clicked second link"}
> 
> /callback {"name": "Opened Word Document", "rid": "DgZKuT7", "data": "Office Version: 2003"}
> 
> /callback {"name": "Watched Training Video", "rid": "DgZKuT7", "data": "Watched 'How to Spot a Phish'"}
> 
> /callback {"name": "Ran executable file", "rid": "DgZKuT7", "data": "OfficeUpdate.exe'"}
> 
> /callback {"name": "Signed Agreement", "rid": "DgZKuT7", "data": "'"}
> ```
> 
> Then in the UI we could this data to the timeline:
> 
> ![Screen Shot 2020-01-28 at 16 30 06](https://user-images.githubusercontent.com/3966613/73283776-843e0b00-41eb-11ea-98d8-c1140b641995.png)
> 
> Obviously my simplified JSON above would need to include the extra info around which icons to use and how to lay out heading and main text, but you get the idea.
> 
> Thoughts @jordan-wright ? I think we could add loads of cool functionality with this small modification.

**Comment by glennzw** [comment]
I've opened a pull request for this feature, at last!

https://github.com/gophish/gophish/pull/1929
