### ISSUE TITLE
Changing the testing email context

### ISSUE THREAD

**Issue by kan1207** [gophish/gophish#1687]
Is there a way to change the email context in the testing email?

I have managed to change in the gophish program but not successful.

**Comment by jordan-wright** [comment]
There's no way to change it from within Gophish. If you're looking to modify Gophish itself, then you'd want to look [here](https://github.com/gophish/gophish/blob/master/controllers/api/util.go#L16) or [here](https://github.com/gophish/gophish/blob/44f88401bbd84994212c13a69987e2e6985d8a4a/models/email_request.go#L112).

I hope this helps!
