### ISSUE TITLE
Not getting data back to Gophish server

### ISSUE THREAD

**Issue by tarzan538** [gophish/gophish#1688]
Hi,

Some history: If I do this local within my subnet everything seems to work fine! Now once I am sending a campaign outside my small office network I send email without any problems but not getting data if somebody opens or click on link.

I am not a big technical person and would like your input in my setup;
**Here is my setup:**
    

1. LAN PC running Gophish "1.1.1.1"
2. Hosting account with new domain and DNS A record pointing to my public facing gateway IP (this     is the gateway for 1.1.1.1)
3. Campaign URL is: newdomainname.com
3. Firewall rule to redirect traffic from Public facing IP gateway to 1.1.1.1
4. Then config.json;
    {
    "admin_server": {
    "listen_url": "127.0.0.1:3333",
    "use_tls": true,
    "cert_path": "gophish_admin.crt",
    "key_path": "gophish_admin.key"
    },
    "phish_server": {
    "listen_url": "http://domainname.com:80",
    "use_tls": false,
    "cert_path": "example.crt",
    "key_path": "example.key"
    },
    "db_name": "sqlite3",
    "db_path": "gophish.db",
    "migrations_prefix": "db/db_",
    "contact_address": "",
    "logging": {
    "filename": ""
    }
    }

Question: Is there is something I am missing as I cannot make this work?

**Comment by tarzan538** [comment]
Anybody?

**Comment by jordan-wright** [comment]
Hi there!

Please understand that we're all volunteers here, so getting an answer on a support ticket might take a bit 😉 

As to your issue, this seems to be 100% a networking problem, not a Gophish problem. To that end, the only support we're able to provide is with Gophish itself.

Your setup seems reasonable- though my guess is that traffic isn't actually making it to your machine from the firewall. The simplest way to test would be to visit the domain name directly and make sure you:

* Get a boring 404 Not Found error
* See a log appear in the Gophish terminal

If those don't happen, it's a networking problem. The only thing to potentially adjust in your Gophish config would be to change `http://domainname.com:80"` to `http://0.0.0.0:80`. In this case, the domain should still work just fine.

I'm sorry we can't be of more help! The fact that things work fine in the subnet indicates that it's a routing problem, not an issue we can control here.

**Comment by tarzan538** [comment]
Thank you Jordan as I do appreciate your support.
