### ISSUE TITLE
Can't disable TLS 1.0 through Windows registry

### ISSUE THREAD

**Issue by timjwardster0** [gophish/gophish#1691]
What version of Gophish are you using?: 0.7.1

Brief description of the issue: Can't disable TLS 1.0 and ciphers - is there a gophish config way to do this?

What are you expecting to see happen? : Vulnerability scan on gophish server not show TLS 1.0 vulnerabilities / GoPhish use Windows registry setting disabling TLS 1.0 and weak ciphers

What are you seeing happen? Windows settings ignored, TLS 1.0 vulnerabilities when scan server

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Closing as a duplicate of #1689

**Comment by timjwardster0** [comment]
Hi, sorry for potential duplicate - I did search and didn't see this one - BUT I'm not using nginx. Just GoPhish on a Windows Server configured not to allow TLS 1.0 but GoPhish allows it anyway - so how can i make gophish not accept TLS 1.0?

**Comment by jordan-wright** [comment]
It’s not possible within Gophish to change the supported TLS protocols. This is something you’d have to modify and rebuild Gophish.

Though, an easier solution would be to put a proxy like nginx in front of Gophish and adjust the TLS settings there.

**Comment by timjwardster0** [comment]
Thanks for clarifying Jordan!
Tim

**Comment by S0larflare** [comment]
Hi Jordan,

I know you’re usually pretty loathe to add extra bloat to the config.json file, but couldn’t we add supported TLS versions/min TLS version in there which gets passed to the tls.Config struct? If we have the default as say TLS1 then it would be simple for people to change it to TLS1.2 if they wanted to improve the security/compliance?

Sent from my iPhone

On 11 Dec 2019, at 13:33, timjwardster0 <notifications@github.com> wrote:

﻿Thanks for clarifying Jordan!
Tim

**Comment by jordan-wright** [comment]
After thinking on this a bit more, I think this isn't a case for adjusting the `config.json`, but rather a case for improving the defaults.

I didn't realize TLS 1.2 support was so broad, but it appears that [Microsoft, Apple, and Google plan to deprecate TLS 1.0 and TLS 1.1 in early 2020](https://arstechnica.com/gadgets/2018/10/browser-vendors-unite-to-end-support-for-20-year-old-tls-1-0/):

> The impact of removing the old protocols shouldn't be too substantial. All four companies cite usage figures for the old versions; Firefox sees the most TLS 1.0 and 1.1 usage (1.4 percent of all secure connections) while the other three vendors claim a figure below 1.0 percent.

To that end, I think for our population it's safe to say that we can set TLS 1.2 as the default minimum TLS version supported by Gophish. If folks need legacy support, that should be the exception, not the norm.

I'll put out a change in the next day or two to make this happen when I can do some testing. Thanks for bringing this to my attention @timjwardster0, @S0larflare, and @plaverty9-r7!

**Comment by timjwardster0** [comment]
That's great Jordan. Sounds like a good way forward.


Don't suppose there is anyway to also address cipher vulnerabilities? Qualys scan suggested disabling  RC4 128/128, RC4 40/128, RC4 56/128, and Triple DES 168 when we pointed at server running GoPhish.



Regards


________________________________

**Comment by plaverty9-r7** [comment]
Good call, Tim. The SSLScan tool had a similar suggestion.

**Comment by jordan-wright** [comment]
Sure, it looks like there is similar distributions of adoption for more modern cipher suites so I can make that happen.
