### ISSUE TITLE
TLS handshake error during Install

### ISSUE THREAD

**Issue by Gaz2600** [gophish/gophish#1692]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.8.0

Brief description of the issue: I ran the installer for Windows 64bit on 2019 server.  I am getting an error: "http: TLS handshake error from 127.0.0.1:51862: read tcp 127.0.0.1:33330>127.0.0.1:51862: i.o timeout" 

What are you expecting to see happen? : I am expecting a clean install with no errors

What are you seeing happen? Error

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
What URL are you going to in your browser? What does your config.json look like? What are you seeing in your browser?

**Comment by Gaz2600** [comment]
This is during the installation process in the terminal window.  The
install instructions did not say anything about configuring the json file.

**Comment by jordan-wright** [comment]
I understand it was during the installation process, but I'm afraid that doesn't help me troubleshoot the issue.

The questions I asked above were to elicit information that can help me track down the problem. The error you provided tells me what happened, but not why it happened.

**Comment by S0larflare** [comment]
Have you gone to http://your.server or https://your.server? I suspect you're trying to connect over http.

**Comment by Gaz2600** [comment]
This was during install before I even tried to go to the page.. I
relaunched it the following day and did not get the error message, its
working now.
