### ISSUE TITLE
Test mail is showing my email address instead of the one I setup in the profile

### ISSUE THREAD

**Issue by 007me** [gophish/gophish#1693]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:   0.7.1 

Brief description of the issue: Test mail is showing my email address instead of the one I setup in the profile

What are you expecting to see happen? : 
I expect that the email that arrives will show the fake email address I typed in.

What are you seeing happen?
I see the fake name I placed but with my real email address

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - I setup a sending profile and placed a fake email address on the "from" field.
 * Step 2 - I setup Google as my SMTP server.
 * Step 3 - I sent a test email to another mail account I have and saw that the fake name is showing along with my real email and not the fake one.
What am I missing?

**Comment by jordan-wright** [comment]
If you’re using Gmail credentials to send emails through Google, then this is a feature of Gmail which isn’t something we can control within Gophish.

Sorry there isn’t more we can do to help!

**Comment by 007me** [comment]
What's my other options for SMTP?

Are there any free ones?

 

Regards,

 

 

__________________________________________________________________

 

Udi Burg 

e udi@udiburg.com <mailto:udi@udiburg.com>   m +972-54-4249440 

Ramat Gan, Israel w https://blog.udiburg.com

 <https://www.linkedin.com/in/udiburg/> 

 

P Think before you print

**Comment by jordan-wright** [comment]
I’m afraid the support we provide is limited to operating Gophish itself, not choosing and setting up an SMTP provider.

Fwiw, many people choose to run a local mail relay - there are many open source options to help with this.

**Comment by 007me** [comment]
Thanks Jordan.

 

 

__________________________________________________________________

 

Udi Burg 

e udi@udiburg.com <mailto:udi@udiburg.com>   m +972-54-4249440 

Ramat Gan, Israel w https://blog.udiburg.com

 <https://www.linkedin.com/in/udiburg/> 

 

P Think before you print
