### ISSUE TITLE
Implement Better User Management

### ISSUE THREAD

**Issue by snori74** [gophish/gophish#170]
The User Guide advises to change the password for "Admin" - but then gophish seems to allow further accounts to be added from the login screen without any controls. It's not clear what power 'admin' has that these additional accounts don't have - and the 'admin' user doesn't seem to have a way to view or delete these 'extra' accounts.

**Comment by jordan-wright** [comment]
Thanks for the report!

I'm working on implementing full account control from the admin panel. For now, in the master branch (building from source) you can no longer register an account without an existing account.

Let me get a couple of ideas together. I'll keep this issue open for reference.

**Comment by jordan-wright** [comment]
Closing since we have basic RBAC support as of v0.8.0. It's not the full user management that I'd like, but it's a start 😄
