### ISSUE TITLE
MAILGUN - Max connection attempts exceeded (x509)

### ISSUE THREAD

**Issue by austinsonger** [gophish/gophish#1709]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.7.1

Brief description of the issue: 
```
Max connection attempts exceeded - x509: certificate is valid for *.mailgun.org, mailgun.org, not smtp.mailgun.org:587
```
![](https://i.imgur.com/mUCnnkO.png)
What are you expecting to see happen? :

What are you seeing happen?
> I'm no longer seeing the logs of the these message attempts in my mailgun account.

**Comment by austinsonger** [comment]
After some research on my own of mailgun. I came cross this.

```
require tls: If set to True this requires the message only be sent over a TLS connection. If a TLS connection can not be established, Mailgun will not deliver the message. If set to False, we will still try and upgrade the connection, but if we can not, we will downgrade and deliver over a plaintext SMTP connection. The default is False.

skip verification: If set to True, the certificate and hostname will not be verified when trying to establish a TLS connection and Mailgun will accept any certificate during delivery. If set to False, Mailgun will verify the certificate and if it can not, a TLS connection will not be established. The default is False.
```

**Comment by jordan-wright** [comment]
What does your sending profile look like? The error suggests that the cert _should_ be valid since smtp.mailgun.com is a subset of *.mailgun.com, but for some reason the port number is being included in that validation.

**Comment by austinsonger** [comment]
![image](https://user-images.githubusercontent.com/26654315/72477036-4d600200-37b4-11ea-808d-2880427f33e9.png)

**Comment by jordan-wright** [comment]
I was able to reproduce this issue on my end - it looks like a bug to me. I'll see what I can do to track this down.

Thanks for sending this over!
