### ISSUE TITLE
SSL issue connecting to open relay with postfix

### ISSUE THREAD

**Issue by absane** [gophish/gophish#171]
When i try to use an open relay on the same server as GoPhish, I get the following Postfix error that prevents me from sending e-mails:

```
Feb 22 20:58:40 mail postfix/submission/smtpd[5544]: connect from xxx.yyy.com[127.0.0.1]
Feb 22 20:58:40 mail postfix/submission/smtpd[5544]: SSL_accept error from xxx.yyy.com[127.0.0.1]: 0
Feb 22 20:58:40 mail postfix/submission/smtpd[5544]: warning: TLS library problem: error:14094412:SSL routines:SSL3_READ_BYTES:sslv3 alert bad certificate:s3_pkt.c:1294:SSL alert number 42:
Feb 22 20:58:40 mail postfix/submission/smtpd[5544]: lost connection after STARTTLS from xxx.yyy.com[127.0.0.1]
Feb 22 20:58:40 mail postfix/submission/smtpd[5544]: disconnect from xxx.yyy.com[127.0.0.1]
```

In the gopisher log I see this:

```
 2016/02/22 21:05:46 template.go:84: record not found
 2016/02/22 21:05:46 api.go:449: Error - Template  does not exist
 2016/02/22 21:05:46 worker.go:157: Creating email using template
 2016/02/22 21:05:46 worker.go:190: Sending Email to xxxx@gmail.com
 2016/02/22 21:05:47 worker.go:193: x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs
```

No auth is needed and when I use KingPhisher or my local mail client I have no issues. This only happens with GoPhish.

**Comment by jordan-wright** [comment]
Are you using the pre built binary? If so, do you see any errors in gophish when sending a test email?

**Comment by absane** [comment]
I am using the prebuilt library. Those errors you see above are what I see what I send a test e-mail.

**Comment by absane** [comment]
Update: I was able to solve this problem by compiling from the latest source. I think the issue has to do with the mail server using a self-signed certificate. Not 100% sure but the newer version of GoPhish has the option of ignoring certificate errors.

**Comment by absane** [comment]
Update #2: it seems that when I compile from the latest source, I can send test e-mails just fine. However, now I cannot send campaigns. When I click "Launch Campaign" I see this error at the top: **table smtp has no column named ignore_cert_errors**. And, I cannot see the open for ignoring certificate errors anymore. I do not know what has happened.

**Comment by jordan-wright** [comment]
I would recommend doing a fresh compile from the latest sources. It sounds like something got messed up in your static files.

I would recommend wiping out the gophish directory and doing a fresh go get.

The option to ignore cert errors is in the launch campaign modal. By checking that, you should be able to ignore self signed certs. I agree this seems to be the case here.

**Comment by jordan-wright** [comment]
Closing this for now. Please don't hesitate to open another issue if you experience crashes when creating a campaign with the latest code.
