### ISSUE TITLE
Docker: Showing wrong gophish version number 0.7.1 / 0.8.0

### ISSUE THREAD

**Issue by radys** [gophish/gophish#1710]
There is probably wrong gophish number in web settings:
> Gophish version 0.7.1

I tried three ways:
- 1. source from base git repo (settings show wrong number)
- 2. git checkout tags/v0.8.0 (settings show wrong number)
- 3. docker pull gophish/gophish (settings show wrong number)

Create docker image from gophish source:
- docker build -t gophish/gophish .

There is wrong number also in source, but change has no effect:
```
# cat VERSION
0.7.1

# cat config/config.go | grep Version
// Version contains the current gophish version
var Version = ""
```

<img width="1211" alt="Snímek obrazovky 2020-01-08 v 12 28 17" src="https://user-images.githubusercontent.com/5844637/71975243-b32c1700-3213-11ea-998e-18a3f91d69c2.png">

**Comment by usernotification** [comment]
Fell for the same.
Dev forgot to tag release and points to documentation see #1683.
Creates a lot of issues and should be set straight by a new release, but probably has more reasons why it is not done until now.

**Comment by jordan-wright** [comment]
@usernotification is correct, this was a simple mistake where I forgot to update the `VERSION` file. It will be fixed in the next release, which will likely come out in the next week or so.
