### ISSUE TITLE
GoPhish unable to collect Data

### ISSUE THREAD

**Issue by GreatScotch** [gophish/gophish#1711]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.7.1

Brief description of the issue: Email template sent but gophish doesn't collect the data

What are you expecting to see happen? : once user opens email gophish should record events

What are you seeing happen?

I can only see the email being sent in the campaign results.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
<html>
<head>
	<title></title>
</head>
<body>
<p align="LEFT" dir="LTR">Dear Staff,</p>

<p align="LEFT" dir="LTR">We are pleased to introduce the company new LinkedIN page.</p>

<p align="LEFT" dir="LTR"><font face="Calibri">Please click on&nbsp;link to register and jion the company in LinkedIN. </font></p>

<p align="LEFT" dir="LTR"><font face="Calibri">Enter <strong>your email address and&nbsp;date of joining and your login password</strong> after clicking this </font><a href="{{.URL}}"><font face="Calibri">link</font></a><font face="Calibri">.</font></p>

<p align="LEFT" dir="LTR"><font face="Calibri">Regards,</font></p>

<p align="LEFT" dir="LTR"><font face="Calibri"><font size="3"><font face="Calibri"><font size="3"> company name</font></font></font></font></p>

<p align="LEFT" dir="LTR">&nbsp;</p>

<p>{{.Tracker}}</p>
</body>
</html>

```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
1. Config.Json file has been left as default. Admin_server listen url 127.0.0.1:3333 and Phish_server listen url is 0.0.0.0:80
2. Landing page was imported from LinkedIN website so it has the login credential boxes and links intact (for testing purposes). The page is set to redirect to https://www.bbc.co.uk (for testing purposes). Capture Submitted data and Capture Passwords is ticked.
3. Email template is simple and for the link I am using {{.url}} as documented, tracking image is ticked
4. Sending profile is working as I am receiving the email
5. I have installed on server 2016 and IIS is configured so users can reach the server with the IP Address of the server.
6. When I setup the campaign, the URL I enter is the Phish server IP Address http://192.*.*.*. So this means {{.URL}} is http://192.*.*.*?rid=****
7. When i receive the email and hover my mouse over the link indeed it is http://192.*.*.*?rid=****. IIS is enabled so when I click on the link it takes me to the the default IIS page and not the landing page.

If I disable IIS Default Web Site it will take me to a 404 page - resource not found, and not to the landing page.

Now as another test, I created a static webpage in IIS that's imported from LinkedIN login page, so when I click on the link in the email now I will get the LinkedIN page as expected.

However, I am still not getting any events recorded. Is there anything I am misunderstanding something here? 

I can see in the emails the tracking image is there but in Outlook it requires the user to click to download the pictures in the email. I suppose this could explain why opening emails might not be tracked, however click on the link should be recorded right?

If I disable IIS web sites I can't get to the landing page at all as expected the server ip address is not reachable as a http address.

Thanks

**Comment by GreatScotch** [comment]
Ok I sorted out the reporting now.

the json file instead of the default 0.0.0.0:80 I changed to the server ip and gave it a new port so... 
192.*.*.*:8081

then in the campaign url i added the same http://192.*.*.*:8081.

So now the tracking image works and clicking the link works. The only thing is trying to figure out Submitted Data and Email Reported events. 

I'm still thinking of using the LinkedIN landing page but i think the source code behind the website is preventing the other events from being recorded.

**Comment by GreatScotch** [comment]
Had to create a landing page without jscript, I managed to create something that looked similar to the Linkedin webpage, obviously not quite as snazzy and polished but I think it's good that it isn't as you also want people to spot a webpage that doesn't quite look authentic too.

**Comment by Tempsathi** [comment]
Hi 
I am trying to import linkedin page for my landing page... I can run the campaign and  I can even go to the landing page and click the URLs , but once I entered the username and password I suppose to capture submitted data. Which I can't see. 
I can only see up to email click event. 

I understand it may not be simple as just providing a URL to phish but then what the point of having import site?
