### ISSUE TITLE
Spoof Sender

### ISSUE THREAD

**Issue by labkali** [gophish/gophish#1712]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue: 

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 - 
 
 I read all the various posts related to the topic, at the moment what is the best way to spoof the sender?

**Comment by jordan-wright** [comment]
You can put any email address you want in the "From" field in a Gophish "Sending Profile" and Gophish will attempt to send as that address. You can find more information in [our documentation](https://docs.getgophish.com/user-guide/documentation/sending-profiles).

Whether or not the receiving mail server delivers your message will depend on the configuration of that mail server, and how your own mail server is setup. I'm afraid that both of these things are out of scope for the support we provide here.

Sorry we couldn't be of more help!
