### ISSUE TITLE
subfolder to landing page

### ISSUE THREAD

**Issue by irussak** [gophish/gophish#1713]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.3

Brief description of the issue: 

I couldn't find a description for how to create a subfolder for the landing page redirect

What are you expecting to see happen? :

I want to direct the people who open the LINK to a dedicated URL with subfolder such as www.xyz.com/printersrv/XXX.pdf

What are you seeing happen?
 
I couldn't find the method for organizing the subfolder within the server

*The landing page works proper.
I have bound the landing page to a proper domain

Please help me understand how I can do this.

Thanks

**Comment by glennzw** [comment]
The folder is `gophish/static/endpoint`. If you drop your `XXX.pdf` into a printers folder inside that directory, you can then access it via: http://www.xyz.com/static/printersrv/XXX.pdf
