### ISSUE TITLE
GoPhish Installation on Windows Server 2012 or 2016

### ISSUE THREAD

**Issue by onanugaola** [gophish/gophish#1715]
What version of Gophish are you using?: 
Gophish v0.8.0

Brief description of the issue: 
I will like to know whether it is possible to install GoPhish on Windows Servers or it works only on Windows 10. The documentation I find online is for Linux servers' installation.
1. If yes, what additional installation is needed?
2. Do I have to install SQLite
3. What files do I have to modify to able to run the GoPhish in the Cloud environment?
4. Which fill/folder does the landing page(s) located

Thanks

**Comment by jordan-wright** [comment]
In the future, when submitting issues I'd encourage you to first try things out. Then, you can let us know what you tried and what unexpected behavior you saw instead.

For now, here are the answers to your questions:

1) Yes, it's possible- just use the Windows release and it should work.
2) I'm not sure. Probably not? You can try and see what happens.
3) Probably just config.json
4) Those are stored in the database, not the filesystem
