### ISSUE TITLE
Api GetCampaignSummary

### ISSUE THREAD

**Issue by JoseW3b** [gophish/gophish#1717]
What version of Gophish are you using?: 0.8

Brief description of the issue: when you request a campaign summary doesn't retrieve send by date field with the right value set in database.

What are you expecting to see happen? : I expect send by date field was retrieve

What are you seeing happen?
When I made the request to `http://{myserver}:3333/api/campaigns/{campaignId}/summary` (from postman) the response value is `....., "send_by_date": "0001-01-01T00:00:00Z", .....`, although in database has a date value.

Thanks in advance,

**Comment by jordan-wright** [comment]
Great catch! This is a bug. It looks like we're missing `send_by_date` in the queries [here](https://github.com/gophish/gophish/blob/master/models/campaign.go#L350) and [here](https://github.com/gophish/gophish/blob/master/models/campaign.go#L327).

I can get a patch out for this later this week, unless you'd like to send up a PR.

**Comment by JoseW3b** [comment]
I have make a pull request. I hope it will be ok.
Thanks a lot.

**Comment by jordan-wright** [comment]
Closed via 91d7983. Thanks again for sending in the fix!
