### ISSUE TITLE
Is there a way to set a sending email sleep time to avoid flooding/spam issues?

### ISSUE THREAD

**Issue by laravelhelp2** [gophish/gophish#1718]
I was wondering if GoPhish has an inbuilt option to set a sleep/pause between each email sent.
For example I have 100 recipients and I want to set 1 second of delay for every email sent:

Email 1
sleep(1)
Email 2
sleep(1)
Email 3
...

Thank you

**Comment by glennzw** [comment]
You can, have a look at the 'Send Emails By' option in the campaign launcher. You'll have to do the mental maths to calculate when the campaign needs to end to match your desired sleep.

Alternatively check out my pull request to add a sleep between emails: https://github.com/gophish/gophish/pull/1557
