### ISSUE TITLE
Forward proxy with apache

### ISSUE THREAD

**Issue by Eviepayne** [gophish/gophish#1719]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.7.1

Brief description of the issue: 
When I use forward proxy with apache I get an error 500

What are you expecting to see happen? :
loading the landing page of the campaign

What are you seeing happen?
Internal error 500

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
web page is fine, it works in other configurations
However:

config.json phish server:
...
        "phish_server": {
                "listen_url": "127.0.0.1:443",
                "use_tls": true,
                "cert_path": "/etc/letsencrypt/live/domain.com/cert.pem",
                "key_path": "/etc/letsencrypt/live/domain.com/privkey.pem"
...

apache config:
...
<VirtualHost *:80>
        ServerName domain.com
        ProxyRequests off
        ProxyPass / "https://localhost:443/"
        ProxyPassReverse / "https://localhost:443/"
</VirtualHost>

!note - apache only listens on public IP, not localhost
...

```

Please provide any terminal output that may be relevant below:

```
2020/01/14 15:44:16 http: TLS handshake error from 127.0.0.1:46664: EOF
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - With the preceding configurations
 * Step 2 - Create a campaign with listener at http://domain.com

**Comment by jordan-wright** [comment]
Hi there!

I'm afraid our ability to help troubleshoot problematic Apache configs will be pretty limited. If you have Apache logs available, that might help. For now, all we see is that some kind of TLS handshake is occurring.

And what do you mean by "web page is fine, it works in other configurations". Are you saying that Gophish works without Apache? If so, then this would be out of scope for this forum, since our goal is to focus on troubleshooting issues with the Gophish project.

**Comment by Eviepayne** [comment]
I understand. I did eventually find a different way to do it. Instead of having gophish handle TLS, apache is handling it.
