### ISSUE TITLE
DSO missing from command line

### ISSUE THREAD

**Issue by klifer** [gophish/gophish#1721]
Hey
trying to install and compile gopfish on the fresh installation of Ubuntu srv. 
```
root@srv01:/home/r/gophish# uname -a
Linux srv01 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
after go build it's return:

```
root@srv01:/home/r/gophish# go build
# _/home/r/gophish
/usr/bin/ld: $WORK/b001/_pkg1_.a(_x011.o): undefined reference to symbol 'pthread_mutexattr_settype@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
 any ideas? thx

**Comment by jordan-wright** [comment]
This is the first I've heard about this happening, and I'm afraid I'm not sure what the cause would be.

At this point, it'd probably be easier to use one of our [binary releases](https://github.com/gophish/gophish/releases).

Sorry we couldn't be of more help!

**Comment by sadreck** [comment]
Had this exact issue on Ubuntu 18.04, turns out it was the `gccgo-go` at fault. I installed `golang-go` instead and that worked fine.
