### ISSUE TITLE
Sending profile always returns 

### ISSUE THREAD

**Issue by rogovtravka** [gophish/gophish#1725]
**What version of Gophish are you using?:** 
v0.9.0

**Brief description of the issue:** 
When sending a test e-mail for a Gmail, Hotmail or Office365 account it always returns the same error message. I have tried :465 and :587 for 3 accounts: a gmail account, a hotmail account and a business office 365 account.

**What are you expecting to see happen? :**
E-mail being sent

**What are you seeing happen? :**
Max connection attempts exceeded - dial tcp: lookup smtp.google.com: Temporary failure in name resolution

Max connection attempts exceeded - dial tcp: lookup smtp.office365.com: Temporary failure in name resolution

**Please provide as many steps as you can to reproduce the problem:**
 * Step 1 - Enter name, from, host (smtp.google.com:465 and :587, smtp.outlook365.com:587), username, password in new profile
 * Step 2 - Send test email
 * Step 3 - Temporary failure in name resolution
 
The passwords are double checked, have rebooted the gophish machine, tried different e-mail providers/accounts and ports. What is going wrong?

 Thank in advance.

**Comment by jordan-wright** [comment]
This is related to DNS, not Gophish. In this case, your system can't resolve smtp.google.com or smtp.office365.com.

With the first one, it's worth noting that you're likely looking for smtp.gmail.com as noted in the [Gmail SMTP documentation](https://support.google.com/a/answer/176600?hl=en). If you continue to see this error, then I'd encourage you to review your system DNS settings.

Sorry we couldn't be of more help!

**Comment by rogovtravka** [comment]
DNS wasn't configured properly. Thanks for the help.
