### ISSUE TITLE
Integrate gophish in PHP application

### ISSUE THREAD

**Issue by sexD** [gophish/gophish#1728]
Hi we have an intranet in our university for information security. This was created in PHP. I got asked if there is a possibility to integrate gophish into the application? Is there any "easier" way of doing this? Maybe making use of the APIs? Or can we directly use the source code? Any pointing towards in the right direction would be huge!

Thanks

**Comment by halaalajlan** [comment]
Call APIs directly from your application 

$curl = curl_init();
curl_setopt_array($curl, array(
  CURLOPT_URL => "https://127.0.0.1:3333/api/smtp",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "GET",
  CURLOPT_POSTFIELDS => "username=admin&password=gophish",
  CURLOPT_HTTPHEADER => array(
    "Content-Type: application/x-www-form-urlencoded",
    "Authorization: {{key}}",
    "Authorization: Bearer YourApiKeyxxxxxxx"
  ),
));

$response = curl_exec($curl);

curl_close($curl);
echo $response;

**Comment by jordan-wright** [comment]
@halaalajlan is spot on- you can use the [REST API](https://docs.getgophish.com/api-documentation/) built into Gophish to automate Gophish from a PHP application.
