### ISSUE TITLE
Create Markdown Version of User Guide

### ISSUE THREAD

**Issue by jordan-wright** [gophish/gophish#173]
Need to create a markdown version of the User Guide so that contributors can make changes that can be then ported to the PDF documentation.

**Comment by poerhiza** [comment]
http://pandoc.org/ _Should_ be able to help with this

**Comment by jordan-wright** [comment]
Absolutely! That's the route I'm likely going to go. Thanks for the suggestion!

**Comment by PaulSec** [comment]
Are you still looking to do this? 
Wouldn't it be better to add it in the [wiki](https://github.com/gophish/gophish/wiki)?

**Comment by jordan-wright** [comment]
Closing this one out. Currently, docs can be found on the [wiki](https://github.com/gophish/gophish/wiki). Unfortunately, Github doesn't make outside wiki contributions easy. 😒 

To make it easier to contribute to documentation, my longer term plans are to move everything to GitBook.io with a local copy stored on Github. You can find the currently copies [here](https://www.gitbook.com/@gophish). They are works in progress.
