### ISSUE TITLE
Old password not required to change password

### ISSUE THREAD

**Issue by glennzw** [gophish/gophish#1730]
What version of Gophish are you using?: 0.9.0

I just noticed that a user isn't required to enter their old password when setting a new password. The risk here is that if a session is compromised (e.g cookie is stolen) then the attacker can gain more permanent access by changing the password.

Best practise is to require the old password, as per OWASP guidelines:

"The most insecure scenario here is if the application permits the change of the password without requesting the current password. Indeed if an attacker is able to take control of a valid session they could easily change the victim's password."

https://wiki.owasp.org/index.php/Testing_for_weak_password_change_or_reset_functionalities_(OTG-AUTHN-009)

I can work on a fix for this if you'd agree it'd be useful @jordan-wright . Otherwise happy to leave it as is if you prefer :)

**Comment by glennzw** [comment]
Eh, I don't know if I was looking at an old version by mistake, or I hallucinated the whole incident, but the old password is indeed required to change to a new password.

**Comment by glennzw** [comment]
Ah, no, I see what it was - you are able to change your admin password from the user management section without the old password.

So the original risk stands.

**Comment by jordan-wright** [comment]
You’re right - admin users are able to change the password of any user. This is needed as a password reset of sorts.

In this case, we can’t assume the admin or original user remembers their old password right?

And regarding the threat model, it’s important to remember that Gophish is 100% api driven. So to me the most damaging thing an attacker can use a users cookie for is to copy the API key. Then they can do everything with that without needing to reset the users password.

I’m open to any approaches that make the current state of things better without adding considerable friction. For example, I’m not sure I want to ask for the users password again before showing them their api key. But please send any ideas my way!

**Comment by glennzw** [comment]
I think admin being able to change passwords for other users is OK, but admin being able to change their own password without the old one is the security risk.

Normally we'd reset this from the command line. We could have a flag on the gophish binary to reset the admin password, e.g:

 `./gophish --reset`

But yeah gotcha on the API model - this risk is probably not as significant on Gophish compared to other software.

I think we can park this for now, and roll it into https://github.com/gophish/gophish/issues/1538 at some point in the future.

**Comment by jordan-wright** [comment]
Sounds good! I'll go ahead and close it out. I have ongoing work in #1538, just haven't had time to finish it up.

> I think admin being able to change passwords for other users is OK, but admin being able to change their own password without the old one is the security risk.

The problem here is that a compromised admin could use the API access they have to create a new admin user, then use that user to reset the password of the admin they care about 🙁

**Comment by glennzw** [comment]
True, good point.

I guess a possible solution is to require the admin password to be included in the API requests when either changing the admin password or creating an admin account (and then require that input in the UI).

But yeah I think the risk is quite narrow here and we can accept it. Thanks for the back-and-forth!
