### ISSUE TITLE
I now have a newer version of GoPhish

### ISSUE THREAD

**Issue by mailnatalie** [gophish/gophish#1733]
I can see User Management and can change roles as admin but my back-up person cannot see the campaigns and templates that I have created.  I added him as Admin from the Admin profile and also as Admin from my personal (Admin) profile.  Am I missing something here?

Please.  Thanks

**Comment by glennzw** [comment]
Accounts are isolated and can only see their own data.

I too have been pondering this recently - the idea being to mark landing pages / etc as sharable.

I suspect we'll address this in the upcoming Store/Hub https://github.com/gophish/gophish/issues/1589

**Comment by jordan-wright** [comment]
@glennzw is correct. Currently all of the objects in Gophish are isolated per account. It’s possible that the Hub work will help with this until we can figure out some kind of team sharing in the future.
