### ISSUE TITLE
Gophish instillation and MySQL configuration error

### ISSUE THREAD

**Issue by channadsc** [gophish/gophish#1734]
What version of Gophish are you using?: 
Gophish v0.9.0
Brief description of the issue: 
gophish is not installing properly and after following the steps from the  documentation
```
$ go build
$ ./gophish 
```
Still getting this error
Gophish is not installed properly or please advice proper steps to mitigate this problem.

Terminal output
```
time="2020-01-29T12:48:19+05:30" level=fatal msg="invalid character 'z' looking for beginning of value"
```

**Comment by jordan-wright** [comment]
Hi there,

Can you provide the relevant parts of your config.json (redacting credentials to MySQL as necessary)

**Comment by channadsc** [comment]
Hey thank you for replying
I have attached the file to this email.

**Comment by channadsc** [comment]
Hey thank for replying,
Below is the code snippet of config.json file.
This issue was with GoPhish v0.9.
```
{
	"admin_server": {
		"listen_url": "127.0.0.1:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "gophish_admin.key"
	},
	"phish_server": {
		"listen_url": "0.0.0.0:80",
		"use_tls": false,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name" : "mysql",
	"db_path" : "botnet:@(:3307)/gophish?charset=utf8&parseTime=True&loc=UTC",
	"migrations_prefix": "db/db_",
	"contact_address": "",
	"logging": {
		"filename": "",
		"level": ""
	}
}

```

**Comment by channadsc** [comment]
I tried the Gophish v0.8, it works perfectly fine.

And later i tried the installation method from the documentation.
``` $ go get github.com/gophish/gophish ```
But when i proceed further for installation
``` 
$ cd $HOME/go/src/github.com/gophish/gophish/
$ go build 
$ ./gophish
time="2020-01-30T11:56:19+05:30" level=warning msg="No contact address has been configured."
time="2020-01-30T11:56:19+05:30" level=warning msg="Please consider adding a contact_address entry in your config.json"
time="2020-01-30T11:56:19+05:30" level=warning msg="waiting for database to be up..."
```
i get this error

**Comment by glennzw** [comment]
Those are just warnings, unless there are errors following them everything should be fine. Can you hit https://localhost:3333 and http://localhost ?

**Comment by channadsc** [comment]
Its working.
Thanks man.

Now i have one more issue.
while login into the admin account I'm getting 
```
Forbidden - CSRF token invalid
```

**Comment by jordan-wright** [comment]
This may happen if you had the admin login page open, restarted Gophish, then tried to login. Additionally, you'll need to make sure you have JS enabled.

Let me know if that doesn't help!

**Comment by channadsc** [comment]
It's working now. 
Thanks man.

Actually I'm developing application along with GoPhish with  few additional features to GoPhish and i just started and the interface and functionality of GoPhish is great, Thanks for developing this amazing application.
I will reach out to you if i find any issues while developing it further or any ideas to developed it further.
Thank you

**Comment by madhu535** [comment]
> This may happen if you had the admin login page open, restarted Gophish, then tried to login. Additionally, you'll need to make sure you have JS enabled.
> 
> Let me know if that doesn't help!

hi, can you help me out im getting the same problem of CSRF token invalid and i dont get what you mean by restart Gophish and have JS enabled

**Comment by madhu535** [comment]
ok i enabled javascript but im yet getting the same problem

**Comment by madhu535** [comment]
> It's working now.
> Thanks man.
> 
> Actually I'm developing application along with GoPhish ( with few additional features to GoPhish ) and i just started and the interface and functionality of GoPhish is great, Thanks for developing this amazing application.
> I will reach out to you if i find any issues while developing it further or any ideas to developed it further.
> Thank you

how did you fix it?

**Comment by wesdjwdj** [comment]
same problem
time="2023-11-28T11:38:59+08:00" level=fatal msg="invalid character ':' looking for beginning of value"

**Comment by wesdjwdj** [comment]
{
        "admin_server": {
                "listen_url": "127.0.0.1:3333",
                "use_tls": true,
                "cert_path": "gophish_admin.crt",
                "key_path": "gophish_admin.key",
                "trusted_origins": []
        },
        "phish_server": {
                "listen_url": "0.0.0.0:80",
                "use_tls": false,
                "cert_path": "example.crt",
                "key_path": "example.key"
        },
        "db_name": "sqlite3",
        "db_path": "gophish.db",
        "migrations_prefix": "db/db_",
        "contact_address": "",
        "logging": {
                "filename": "",
                "level": ""
        }
}
~                                                                                                                                                                                          
~
