### ISSUE TITLE
Gophishing Integrating with PHP

### ISSUE THREAD

**Issue by prashant199128** [gophish/gophish#1737]
Hi,
I want to retrieve  data from api actually in postman my url is displaying all json data, when i am applying into php code returning empty value, please check my code and  let me know ..
How to integrate in php code please suggest me. 
Thanks.  

```php
<?php
$url = 'https://xxxxxx/api/templates/?api_key=API_KEY';
$ch = curl_init();
curl_setopt($ch, CURLOPT_AUTOREFERER, TRUE);
curl_setopt($ch, CURLOPT_HEADER,0);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, TRUE);
$data = curl_exec($ch);
curl_close($ch);
$obj = json_decode($data);
print_r($obj);
```

**Comment by jordan-wright** [comment]
Hi there,

I'm afraid I don't use PHP often so my ability to help will be limited. One thing that will help is knowing what logs you see in Gophish, and seeing the actual response provided. As in, you say empty but is that "" or "[]"?

You could also find a way to dump out the request being sent from PHP and compare that with the request being send from Postman.

**Comment by prashant199128** [comment]
How to check gophising log?

**Comment by jordan-wright** [comment]
The output from the terminal running Gophish.

**Comment by prashant199128** [comment]
Hi,
Can you suggest me? How to post data in go phishing url. I am trying to post my data while creating template in post url, I am getting bad response, So please suggest me what is the exact format to post data in url.
Below my sample code is. 
$insert = new stdClass();
$insert->id = 55;
$insert->name = 'ssss';
$insert->subject = 'my new';
$insert->text = 'wwww';
$insert->html = '';
$insert->modified_date = '03/FEB/2020';
$insert->attachments = '';

$arr = json_encode($insert, true);
//print_r($arr);

$curl = curl_init();
// Set some options - we are passing in a useragent too here
curl_setopt_array($curl, [
    CURLOPT_RETURNTRANSFER => 1,
    //CURLOPT_POST => 1,
    CURLOPT_URL => 'https://xxxxxxx/api/templates/?api_key=sssssss',
    CURLOPT_USERAGENT => 'Codular Sample cURL Request',
    'Payload'=>$arr
]);
// Send the request & save response to $resp
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
$resp = curl_exec($curl);
if (!curl_exec($curl)) {
    die('Error: "' . curl_error($curl) . '" - Code: ' . curl_errno($curl));
}

// Close request to clear up some resources
print_r(json_decode($resp));

**Comment by prashant199128** [comment]
https://sssss:3333/api/templates/?api_key=xxxx&&id=110
HI,
i want to retrieve single template record,in gophish server,if i hit url in postman i m getting all template records soo please suggest me how to select single record in gophishing server .

**Comment by S0larflare** [comment]
I think it’s /api/templates/template_id/?api_key=

Sent from my iPhone

On 10 Feb 2020, at 08:44, prashant199128 <notifications@github.com> wrote:

﻿

https://sssss:3333/api/templates/?api_key=xxxx&&id=110
HI,
i want to retrieve single template record,in gophish server,if i hit url in postman i m getting all template records soo please suggest me how to select single record in gophishing server .

**Comment by prashant199128** [comment]
Thank you its working fine .

**Comment by prashant199128** [comment]
HI.
I need to collect campaign details. while printing json object as $campaign->timeline i am receiving all message expect Email Opened object, Please tell me how to collect email opened data in campaign.
array is given below .
Array
(
    [0] => stdClass Object
        (
            [email] => 
            [time] => 2020-02-04T12:33:11.45933011Z
            [message] => Campaign Created
            [details] => 
        )

    [1] => stdClass Object
        (
            [email] => a@gmail.com
            [time] => 2020-02-04T12:33:11.564306206Z
            [message] => Email Sent
            [details] => 
        )

    [2] => stdClass Object
        (
            [email] => a@gmail.com
            [time] => 2020-02-04T12:33:47.061265442Z
            [message] => Clicked Link
            [details] => {"payload":{"rid":["WgGFEyE"]},"browser":{"address":"5.194.255.78","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36"}}
        )

    [3] => stdClass Object
        (
            [email] => a@gmail.com
            [time] => 2020-02-04T12:34:03.607833853Z
            [message] => Submitted Data
            [details] => {"payload":{"email":["amar@info.com"],"pass":["info.com"],"rid":["WgGFEyE"]},"browser":{"address":"5.194.255.78","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36"}}
        )
)
Thanks .
