### ISSUE TITLE
Gmail does not receive emails when sent in bulk (I think)

### ISSUE THREAD

**Issue by BeeSting12** [gophish/gophish#1738]
What version of Gophish are you using?: v0.9.0

Brief description of the issue: 

First my setup. I am running GoPhish as a service on an AWS instance. The phishing account is a new gmail account I created two days ago. I have tested the landing page and tracking with my personal gmail account, my personal yahoo account, and a friend on a separate internet connection confirmed with his gmail account that it worked. I did my testing on a campaign with 6 people. 

Now the issue: I made the real campaign for an experiment I'm doing (don't worry, I have permission). It has 81 people, the majority of them use gmail. I started the campaign at 6:30am and all the emails were sent by 7:00am. Since then (it is 6:00pm now), I've only had two people open it. Both of them use icloud accounts. So I know tracking is still working. I'm wondering if gmail noticed the vast quantity of emails I was sending out and sent them to spam for those people with gmail accounts. I find it highly improbable that only 2 out of 81 people clicked on the email in the 11 hours the campaign has been live. 

I understand this isn't likely to be an issue with GoPhish itself, but I'd appreciate any help I can get with this.

What are you expecting to see happen? : More clicks on the email than I have.

What are you seeing happen? Only two, and those are from people with icloud accounts.

**Comment by glennzw** [comment]
In my experience GMail has sent a lot of my campaign emails to spam. Whitelisiting might help you:

https://support.google.com/a/answer/60751?hl=en

**Comment by jordan-wright** [comment]
@glennzw is correct- Gmail is likely sending your emails to spam. Since you have permission to run this campaign, I'd encourage you to reach out to the administrator in charge of the GSuite instance and ask them to whitelist your sending IP.

I hope this helps!
