### ISSUE TITLE
Landing Page 404

### ISSUE THREAD

**Issue by Gaz2600** [gophish/gophish#1742]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
V0.8.0

Brief description of the issue: 
I am getting a 404 message on my landing page.  I've read the Documentation but it's not clear on how you should configure everything.  I've tried http and https, I'm not sure what the url to my landing page actually is as its not shown anywhere on the landing page config.
What are you expecting to see happen? :

What are you seeing happen?
When my test user clicks the link in the phishing email it takes them to a 404 error page, http://10.11.12.13/?firstname=&lastname=&staffid=

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
<html><head>
	<title>Public Records Request - Exemption Request</title>
</head>
<body>
<p><b>Public Records Request - Exemption Request</b></p>
<p>&lt;html&gt;</p>

<form action="">First name:<br/>
<input name="firstname" type="text"/><br/>
Last name:<br/>
<input name="lastname" type="text"/><br/>
Staff ID:<br/>
<input name="staffid" type="text"/><br/>
<br/>
<input type="submit" value="Submit"/> </form>

</body></html>
```

Please provide any terminal output that may be relevant below:

```
time="2020-02-03T07:26:01-08:00" level=info msg="10.15.1.16 - - [03/Feb/2020:07:26:00 -0800] \"GET /api/pages/?{} HTTP/1.1\" 200 13025 \"http://10.11.12.13:3333/landing_pages\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36\""
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
It looks like your link is incorrect. It should of the form:

http://10.11.12.13/?rid=vVRsVB0

Make sure in your email template you're using the {{.URL}} variable.

See: https://docs.getgophish.com/user-guide/template-reference

Perhaps paste your email template here too.

**Comment by jordan-wright** [comment]
Closing since @glennzw gave (as always!) the correct advice to try and resolve the issue. I hope this helps!
