### ISSUE TITLE
VPS disconnected from network - How to prevent

### ISSUE THREAD

**Issue by empty0n3** [gophish/gophish#1743]
What version of Gophish are you using?:  The latest at the moment.

Brief description of the issue: Everything was working just fine and i've only sent about 5 emails to test the dashboard statistics. Then, I received an email from Digital Ocean saying that my VPS was disconnected from the network because it could be being used for malicious activities such as spam emails and DDOS.

Does this have anything to do with Gophish? Are there any configurations that could prevent this from happen again?

Thanks in advance! :)

**Comment by jordan-wright** [comment]
This is an issue with DigitalOcean, not Gophish. To that end, I encourage you to reach out with your use case and question to see what they can do to help.
