### ISSUE TITLE
Captured Credentials

### ISSUE THREAD

**Issue by empty0n3** [gophish/gophish#1744]
Hi! What happens when we capture the credentials using Gophish?
Does the application stores them? What should we do to make it more safe? 
In case we are using it in for employee awareness.

**Comment by jordan-wright** [comment]
For questions like this, I encourage you to check out our [documentation.](https://docs.getgophish.com/user-guide/documentation/landing-pages#capturing-credentials)

To "make it more safe", I recommend not capturing credentials at all if you're just testing for employee awareness.
