### ISSUE TITLE
Would restarting a Gophish service impact the running campaign?

### ISSUE THREAD

**Issue by bhagoria** [gophish/gophish#1745]
Hi Team,

If I restart a Gophish service, would it impact the running campaign?
I am targetting 33K recipients and all of sudden the phishing link (used for the landing page stopped working - it says page can not be displayed) and I am halfway through sending out the emails. 

Would a restart help? And, would it impact the emails that are about to be delivered and campaign?

Appreciate all your help and support!

**Comment by kevy73** [comment]
Likely not.  I have restarted the service multiple times while a campaign is running but the volume is low.
What OS are you running this on? You should be able to check the listeners and ensure they are listening on 80 or 443 depending on your config.

**Comment by jordan-wright** [comment]
Closing this since the question has been answered. @kevy73 is correct in saying that it would likely not impact your campaign, though of course everything is in the details so it's hard to say for sure.
