### ISSUE TITLE
imap: command not allowed in the current state

### ISSUE THREAD

**Issue by channadsc** [gophish/gophish#1746]
What version of Gophish are you using?: 
Gophish-v0.9
Brief description of the issue: 
not able to setup the imap account detials for report settings.

Have the following error at the terminal when setting the imap account.
```
imap: command not allowed in the current state
```
for the below imap setting:
````
Host          : imap.mail.yahoo.com
port           : 993
username  :  ******@yahoo.com
password  : *****
````
And when i change the email-id whithout the "@yahoomail.com"
````
username  : ****
````
I get the following error.
```
imap: unexpected completion status ("NRXHC3 BAD [CLIENTBUG] SELECT Command is not valid in this state")
```

**Comment by glennzw** [comment]
Hi there, the IMAP support is brand new so thanks for taking it for a spin. That error is coming straight from the IMAP server, not from Gophish. A quick Google search suggests you might have to configure your Yahoo account to allow less secure apps:

http://kb.mozillazine.org/Yahoo

**Comment by channadsc** [comment]
Thanks for responding.
Yes I did configure it earlier and it was working fine, I even got the statistics of email reported from the previous campaigns.
But I recently reinstalled the Gophish in my AWS EC2 instance and that's when I got this error, so I thought of reaching out to you guys. about the issue.

**Comment by glennzw** [comment]
Hmm to be honest I'm sure if there's much we can do, as it's an error coming from the IMAP server, not from Gophish. My only other advice would be to contact Yahoo support or ask on their forums.

I presume you get the same error when selecting the 'Test' button to test the settings?

**Comment by channadsc** [comment]
yes i get the same error.

**Comment by glennzw** [comment]
It seems Yahoo isn't so keen for us to be using IMAP

https://help.yahoo.com/kb/SLN27791.html

If at all possible I'd recommend switching to GMail as that works fine.
