### ISSUE TITLE
Hover over URL change.

### ISSUE THREAD

**Issue by BeanHubbleday** [gophish/gophish#1747]
This is more of a question than an issue, but is there a way to make the {{.URL}} tag say something different when hovered over in an email client?

i.e when it's hovered over, instead of saying "http://mygophishserver/....." could we have it say "http://alegitwebsite.com/......"? The RID can stay, that's not an issue.

I thought about a DNS redirect but we have remote users who's phones etc won't grab the DNS redirect...

**Comment by kevy73** [comment]
This is covered in the documentation. To have it display "http://alegitwebsite.com/.." when setting up the campaign, set the http url field to the value "http://alegitwebsite.com". 

Of course you will need to ensure among other things , purchase the domain and set up DNS for that if you want it accessible externally.

**Comment by BeanHubbleday** [comment]
We have set this and it works fine we want to try and remove the URL when hovered over. Any ideas?  Kind Regards, Jack Hubbledayjack@hubbleday.co.uk07986140318   10.02.2020, 05:06, "kevy73" <notifications@github.com>:This is covered in the documentation. To have it display "http://alegitwebsite.com/.." when setting up the campaign, set the http url field to the value "http://alegitwebsite.com".Of course you will need to ensure among other things , purchase the domain and set up DNS for that if you want it accessible externally.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by kevy73** [comment]
This is likely not possible from within Gophish due to "ethical security" reasons I believe.

**Comment by jordan-wright** [comment]
No, you can't change the URL the browser shows when you hover over it. This isn't an ethical security reason, it's just a security reason. You can imagine the implications if this were possible!

This is enforced by the browser, and there isn't anything we can do to change it. When you hover over a link, the browser will always show you what the link actually points to.
