### ISSUE TITLE
SSLtest indicated SSL 3 support from server

### ISSUE THREAD

**Issue by kevy73** [gophish/gophish#1750]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.80 running on Windows 2016

Brief description of the issue: Scan of https site from https://www.ssllabs.com/ssltest indicated SSL v3 support. Alert from scan "This server is vulnerable to the POODLE attack. If possible, disable SSL 3 to mitigate. "  I have followed all advisories for Windows to disable SSL 3 support. The server is a fresh install with no other extra roles/features installed. Only Gophish v0.8 is installed. SSL certificate is purchased from GoDaddy and works fine. How can I disable SSL v3 so it doesn't pop up in the scan again?

What are you expecting to see happen? : 

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Scan the external https site from https://www.ssllabs.com/ssltest
 * Step 2 - Report produced indicated "This server is vulnerable to the POODLE attack. If possible, disable SSL 3 to mitigate. "

**Comment by ldunzweiler** [comment]
Run IISCrypto and see if that changes ssllabs test.

**Comment by kevy73** [comment]
@ldunzweiler The server does't have IIS role installed. Would this work for Gophish as well?

**Comment by jordan-wright** [comment]
I'm not sure how you got this result (is Gophish running behind a proxy?) but I'm almost 100% positive Gophish doesn't support SSLv3 and isn't vulnerable to Poodle.

As of https://github.com/gophish/gophish/commit/79e680e67587848da20964b2173e95e12c4d0a7f we only support TLS 1.1 and 1.2. But even before that, SSLv3 has been disabled in Go's TLS implementation for a long time (always?) - you can see https://github.com/golang/go/issues/32716 for more info.

Without more troubleshooting information, I'm afraid there isn't anything I can do to replicate this issue.
