### ISSUE TITLE
Email sent twice to some of the recipients and landing page stopped working for some time

### ISSUE THREAD

**Issue by bhagoria** [gophish/gophish#1751]
What version of Gophish are you using?: 
0.7.1 (This would probably be 0.8)

Brief description of the issue: 
I noticed a few issues, not just one and mentioned below. The target list contained 33K email IDs and the campaign landing page had a login page to check who submitted the data.
- Campaign Stopped sending emails after sending 12K emails out of 33K but the campaign continued running. I had to create another campaign to deliver the rest of the emails. 
- Landing Page did not open in the browser for a long period of time, probably due to high load but it continued the tracking. Gophish service was running between 100 to 200% CPU. When load reduced then only landing page opened in the browser.
- The campaign sent emails twice to some of the recipients, not to the entire target list.
- Few Misc issues such as - Gophish service stopped once and landing page configuration page pointed to the old domain used in the past campaign.

What are you expecting to see happen? :
- The campaign must deliver emails to the uploaded list of targets, should not stop after sending a few emails.
- Landing page should open in the browser despite the high cpu load, not sure if this caused it though)
- The campaign should not send an email twice. The email sent twice to 5% of people out of total people. 

What are you seeing happen?
Same as mentioned in the brief description.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
I'd hazard this might be related to https://github.com/gophish/gophish/issues/1726

If your server runs out of resources, things might get weird (e.g. can't serve up landing pages, send additional emails).

**Comment by jordan-wright** [comment]
Hi there!

As @glennzw mentioned, I'm almost certain this is related to #1726. The good news is that I've created the PR at #1753 which should address these problems, improving sending performance significantly.

Since this appears to be a duplicate, I'm going to go ahead and close this one out. Thanks for sending this in!
