### ISSUE TITLE
Specific Template Not Sending

### ISSUE THREAD

**Issue by srajaram93** [gophish/gophish#1755]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.7.1

Brief description of the issue: 
I am trying to launch a campaign with a specific template which have worked in the past but the email is not even sending. All other templates work fine except for the one in question. 

What are you expecting to see happen? :
Emails from template being sent 

What are you seeing happen?
Nothing is happening. I tried sending a test email using the sending profile but even that wouldn't send. 

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```
<html>
<head>
	<title></title>
</head>
<body>
<div>&nbsp;</div>

<div>
<div class="msg-quote" data-mce-style="padding: 0; margin: 0; background: #f2f2f2;" style="padding: 0; margin: 0; background: #f2f2f2;">
<div data-mce-style="display: none !important; color: #fff; font-size: 1pt;" style="display: none !important; color: #fff; font-size: 1pt;">Jun 10, 2019 17:56:15 PDT Transaction ID: 0SH324375R6933342&nbsp; <a data-mce-href="https://www.paypal.com/myaccount/tra" href="{{.URL}}">https://www.paypal.com/myaccount/tra</a>..</div>

<table border="0" cellpadding="0" cellspacing="0" class="marginFix mce-item-table" width="100%">
	<tbody>
		<tr>
			<td bgcolor="#f2f2f2" class="mobMargin" data-mce-style="font-size: 0px;" style="font-size: 0px;">&nbsp;</td>
			<td align="center" bgcolor="#ffffff" class="mobContent" width="660">
			<table border="0" cellpadding="0" cellspacing="0" class="mce-item-table" width="100%">
				<tbody>
					<tr>
						<td align="center" valign="top" width="600">
						<table border="0" cellpadding="0" cellspacing="0" class="mce-item-table" width="100%">
							<tbody>
								<tr class="no_mobile_phone">
									<td bgcolor="#f2f2f2" data-mce-style="padding-top: 10px;" style="padding-top: 10px;">&nbsp;</td>
								</tr>
								<tr>
									<td bgcolor="#f2f2f2" data-mce-style="padding-top: 10px;" style="padding-top: 10px;">&nbsp;</td>
								</tr>
								<tr>
									<td align="center" bgcolor="#ffffff" valign="top">
									<table border="0" cellpadding="0" cellspacing="0" class="mce-item-table" data-mce-style="margin-bottom: 10px;" style="margin-bottom: 10px;" width="100%">
										<tbody>
											<tr valign="bottom">
												<td align="center" valign="top" width="20">&nbsp;</td>
												<td align="left" height="64"><img alt="paypal" border="0" data-mce-src="https://www.paypalobjects.com/en_US/i/logo/logo_emailheader_113wx46h.gif" data-mce-style="width: 113px; height: 46px;" height="46" src="https://www.paypalobjects.com/en_US/i/logo/logo_emailheader_113wx46h.gif" style="width: 113px; height: 46px;" width="113" /></td>
												<td align="center" valign="top" width="40">&nbsp;</td>
												<td align="right"><span data-mce-style="padding-top: 15px; padding-bottom: 10px; font: italic 12px; calibri, trebuchet, arial, sans serif; color: #757575; line-height: 15px;" style="padding-top: 15px; padding-bottom: 10px; font: italic 12px; calibri, trebuchet, arial, sans serif; color: #757575; line-height: 15px;"><span data-mce-style="display: inline;" style="display: inline;"><span data-mce-style="display: inline;" style="display: inline;"><a data-mce-href="https://www.paypal.com/myaccount/transaction/details/0SH324375R6933342?utm_source=unp&amp;utm_medium=email&amp;utm_campaign=PPX001066&amp;utm_unptid=c40d00a6-8be3-11e9-a0e7-d48564547810&amp;ppid=PPX001066&amp;cnac=US&amp;rsta=en_US&amp;cust=2EN66866LX759721M&amp;unptid=c40d00a6-8be3-11e9-a0e7-d48564547810&amp;calc=803ef8a9aedcb&amp;unp_tpcid=email-receipt-xclick-payment&amp;page=main:email:PPX001066:::&amp;pgrp=main:email&amp;e=cl&amp;mchn=em&amp;s=ci&amp;mail=sys" data-mce-style="text-decoration: none;" href="{{.URL}}" style="text-decoration: none;">&nbsp;</a> </span> </span> </span></td>
												<td align="center" valign="top" width="20">&nbsp;</td>
											</tr>
										</tbody>
									</table>

									<table border="0" cellpadding="0" cellspacing="0" class="mce-item-table" data-mce-style="margin-bottom: 10px;" style="margin-bottom: 10px;" width="100%">
										<tbody>
											<tr valign="bottom">
												<td align="center" valign="top" width="20">&nbsp;</td>
												<td class="ppsans" data-mce-style="font-family: Calibri, Trebuchet, Arial, sans serif; font-size: 15px; line-height: 22px; color: #333333;" style="font-family: Calibri, Trebuchet, Arial, sans serif; font-size: 15px; line-height: 22px; color: #333333;" valign="top">
												<div data-mce-style="color: #333 !important; font-family: arial,helvetica,sans-serif; font-size: 12px;" style="color: #333 !important; font-family: arial,helvetica,sans-serif; font-size: 12px;"><span data-mce-style="color: #333333 !important; font-weight: bold; font-family: arial,helvetica,sans-serif;" style="color: #333333 !important; font-weight: bold; font-family: arial,helvetica,sans-serif;">Hello,</span>
												<p data-mce-style="font-size: 14px; color: #c88039; font-weight: bold; text-decoration: none;" style="font-size: 14px; color: #c88039; font-weight: bold; text-decoration: none;">You authorized a transaction to Spotify USA Inc. Money won&#39;t leave your account until Spotify USA Inc processes your order.</p>

												<table cellpadding="5" class="mce-item-table">
													<tbody>
														<tr>
															<td valign="top">Thanks for using PayPal. To see the full transaction details, log in to your PayPal account. Keep in mind, it may take a few moments for this transaction to appear.</td>
															<td>&nbsp;</td>
														</tr>
													</tbody>
												</table>
												<span data-mce-style="display: inline;" style="display: inline;"><span data-mce-style="display: inline;" style="display: inline;"> </span></span>

												<table align="left" border="0" cellpadding="0" cellspacing="0" class="mce-item-table" data-mce-style="color: #666666 !important; font-family: arial,helvetica,sans-serif; font-size: 11px; margin-bottom: 20px; clear: both;" style="color: #666666 !important; font-family: arial,helvetica,sans-serif; font-size: 11px; margin-bottom: 20px; clear: both;" width="100%">
													<tbody>
														<tr>
															<td data-mce-style="padding-top: 15px; padding-right: 10px;" style="padding-top: 15px; padding-right: 10px;" valign="top" width="50%"><span data-mce-style="display: inline;" style="display: inline;"><span data-mce-style="color: #333333; font-weight: bold;" style="color: #333333; font-weight: bold;">Merchant </span><br />
															<span data-mce-style="display: inline;" style="display: inline;">Spotify USA Inc </span><br />
															<a data-mce-href="mailto:support@spotify.com" href="{{.URL}}">support@spotify.com</a> </span></td>
															<td data-mce-style="padding-top: 15px;" style="padding-top: 15px;" valign="top" width="50%"><span data-mce-style="display: inline;" style="display: inline;"><span data-mce-style="color: #333333; font-weight: bold;" style="color: #333333; font-weight: bold;">Instructions to merchant </span><br />
															<span data-mce-style="display: inline;" style="display: inline;">You haven&#39;t entered any instructions. </span></span></td>
														</tr>
														<tr>
															<td data-mce-style="padding-top: 15px; padding-right: 10px;" style="padding-top: 15px; padding-right: 10px;" valign="top" width="50%">&nbsp;</td>
															<td data-mce-style="padding-top: 15px;" style="padding-top: 15px;" valign="top" width="50%">&nbsp;</td>
														</tr>
													</tbody>
												</table>

												<div class="mpi_image"><span data-mce-style="display: inline;" style="display: inline;"><a data-mce-href="https://www.paypal.com/webapps/mch/cmd/?v=3.0&amp;t=1560214594&amp;fdata=OBcGAzRHBBYcHAQeSEgZGBswbx8sNVNwR3h7Vm1xUl5fV3VvbAt9ZEdRc1s4DHZQZ11eXncCVVJLQ19GH0BUXFhnbwUzOAp.QH9wWWF8U1xYXnNhYAB8Y0JUYB4-AS9bZ1JRUHsDVFNMSVlJFUdZXFhmfEwmbCEMJQAdKn84BAgAAnoICAN6ZVIXOVE1VRs2YFZYOXYEXR5BQDIjVAYZDwMQJAssPUghHih0IBcbIz0oQSQ5KA95cxEJMVwlVXpTZ1ZdUHQDXVZfEwwZSUgkMwAwBSUOPD1kAjklBj11XFxUUXdobQBwbEZeZAxpUHxTZkIeW3AZXUANA1BBGENdWF9hfFNxdycRKQoFJhoDPiE.Mno-OV47MFIXJ10iDSUHJQ0HCBxDFBYcTVtFFENdWl5mcV92aVh1Q3h.V2xuHg4fDiNlbgRxY0xTYwpnXXJQZFJQXnsEWEAUGxkXXxAcAwpofV51aFh3R314WTt4C1BfX3ZgbgIqbBVUM15nXHxSNVFOCyhDChQcFgQUEEFZWldjfFtxYFggRihwXWF5Ul9dBX45a1QuY0BQYVxkTioFJQ0MW3MRDAUNHhgdEEVLHx0wOzUiJAcmSyc8AzVuHxoIFRgrPUE7PBsJCl8kAS9bPxEECmVFCAAQFFBGG0xbUlpsfF98ZVd6RH1.WWp9TAwZWgQUEXEDcwAAIQU5HD8WIkFbJ2YFK0NLNhoHWlsVBQE4ZwkqPEtwMC4mSmsOGggUFyY0dVsmIQYIMU0yDThLKQsHC2YEKzkLBEhDaQUUGkMyLAQgIwchWz0xASstCQwEFzN1NUZlPwEJMBUwDyUJIhABBW5bDAgdGQMXXRQKD0MwJ093ZwIjGC48Dj4tKQYJAmJrHFcm&amp;cks=ZTgwZGYxYzFhYWI4MGMxNTRlZTJkMTNiNmJkZDYwNzg&amp;e=1.0&amp;e=1.0" href="{{.URL}}"><img alt="Send money abroad as fast as a lightning bolt. Send Money Abroad. Restrictions apply." border="0" class="mpi_image" data-mce-src="https://www.paypalobjects.com/digitalassets/c/NA/banner_ad/2019/imgUS_NA08421_XOOM_0601_530x80.png" data-mce-style="width: 100%;" dir="ltr" src="https://www.paypalobjects.com/digitalassets/c/NA/banner_ad/2019/imgUS_NA08421_XOOM_0601_530x80.png" style="width: 100%;" /></a></span></div>

												<table align="center" border="0" cellpadding="0" cellspacing="0" class="CartTable mce-item-table" data-mce-style="clear: both; color: #666666 !important; font-family: arial,helvetica,sans-serif; font-size: 11px;" style="clear: both; color: #666666 !important; font-family: arial,helvetica,sans-serif; font-size: 11px;" width="100%">
													<tbody>
														<tr>
															<td data-mce-style="border: 1px solid #ccc; border-right: none; border-left: none; padding: 5px 10px 5px 10px !important; color: #333333 !important;" style="border: 1px solid #ccc; border-right: none; border-left: none; padding: 5px 10px 5px 10px !important; color: #333333 !important;" width="40%"><span data-mce-style="display: inline;" style="display: inline;"><span data-mce-style="display: inline;" style="display: inline;">Description</span></span></td>
															<td align="right" data-mce-style="border: 1px solid #ccc; border-right: none; border-left: none; padding: 5px 10px 5px 10px !important; color: #333333 !important;" style="border: 1px solid #ccc; border-right: none; border-left: none; padding: 5px 10px 5px 10px !important; color: #333333 !important;" width="20%"><span data-mce-style="display: inline;" style="display: inline;"><span data-mce-style="display: inline;" style="display: inline;">Unit price</span></span></td>
															<td align="right" data-mce-style="border: 1px solid #ccc; border-right: none; border-left: none; padding: 5px 10px 5px 10px !important; color: #333333 !important;" style="border: 1px solid #ccc; border-right: none; border-left: none; padding: 5px 10px 5px 10px !important; color: #333333 !important;" width="15%"><span data-mce-style="display: inline;" style="display: inline;"><span data-mce-style="display: inline;" style="display: inline;">Qty</span></span></td>
															<td align="right" data-mce-style="border: 1px solid #ccc; border-right: none; border-left: none; padding: 5px 10px 5px 10px !important; color: #333333 !important;" style="border: 1px solid #ccc; border-right: none; border-left: none; padding: 5px 10px 5px 10px !important; color: #333333 !important;" width="25%"><span data-mce-style="display: inline;" style="display: inline;"><span data-mce-style="display: inline;" style="display: inline;">Amount</span></span></td>
														</tr>
														<tr>
															<td data-mce-style="padding: 10px;" style="padding: 10px;" width="40%">&nbsp;</td>
															<td align="right" data-mce-style="padding: 10px;" style="padding: 10px;" width="20%"><span data-mce-style="display: inline;" style="display: inline;"><span data-mce-style="display: inline;" style="display: inline;"><span data-mce-style="display: inline;" style="display: inline;">$34.99 USD </span></span></span></td>
															<td align="right" data-mce-style="padding: 10px;" style="padding: 10px;" width="15%"><span data-mce-style="display: inline;" style="display: inline;"><span data-mce-style="display: inline;" style="display: inline;">1</span></span></td>
															<td align="right" data-mce-style="padding: 10px;" style="padding: 10px;" width="25%"><span data-mce-style="display: inline;" style="display: inline;"><span data-mce-style="display: inline;" style="display: inline;"><span data-mce-style="display: inline;" style="display: inline;">$34.99 USD </span></span></span></td>
														</tr>
													</tbody>
												</table>
												<span data-mce-style="display: inline;" style="display: inline;"> <span data-mce-style="display: inline;" style="display: inline;"> </span></span>

												<table border="0" cellpadding="0" cellspacing="0" class="mce-item-table" data-mce-style="border-top: 1px solid #ccc; border-bottom: 1px solid #ccc; clear: both; color: #666666 !important; font-family: arial,helvetica,sans-serif; font-size: 11px;" style="border-top: 1px solid #ccc; border-bottom: 1px solid #ccc; clear: both; color: #666666 !important; font-family: arial,helvetica,sans-serif; font-size: 11px;" width="100%">
													<tbody>
														<tr>
															<td>
															<table align="right" border="0" cellpadding="0" cellspacing="0" class="mce-item-table" data-mce-style="color: #666666 !important; font-family: arial,helvetica,sans-serif; font-size: 11px; margin-top: 20px; clear: both; width: 100%;" style="color: #666666 !important; font-family: arial,helvetica,sans-serif; font-size: 11px; margin-top: 20px; clear: both; width: 100%;">
																<tbody>
																	<tr>
																		<td data-mce-style="width: 75%; text-align: right; padding: 0 10px 0 0;" style="width: 75%; text-align: right; padding: 0 10px 0 0;"><span data-mce-style="display: inline;" style="display: inline;"><strong>Subtotal </strong></span></td>
																		<td data-mce-style="width: 25%; text-align: right; padding: 0 10px 0 0;" style="width: 25%; text-align: right; padding: 0 10px 0 0;"><span data-mce-style="display: inline;" style="display: inline;"><span data-mce-style="display: inline;" style="display: inline;">$34.99 USD </span></span></td>
																	</tr>
																	<tr>
																		<td data-mce-style="width: 75%; text-align: right; padding: 0 10px 0 0;" style="width: 75%; text-align: right; padding: 0 10px 0 0;"><span data-mce-style="display: inline;" style="display: inline;"><span data-mce-style="color: #333333 !important; font-weight: bold;" style="color: #333333 !important; font-weight: bold;">Total </span></span></td>
																		<td data-mce-style="width: 25%; text-align: right; padding: 0 10px 0 0;" style="width: 25%; text-align: right; padding: 0 10px 0 0;"><span data-mce-style="display: inline;" style="display: inline;"><span data-mce-style="display: inline;" style="display: inline;">$34.99 USD </span></span></td>
																	</tr>
																	<tr>
																		<td data-mce-style="width: 75%; text-align: right; padding: 20px 10px 0 0;" style="width: 75%; text-align: right; padding: 20px 10px 0 0;"><span data-mce-style="display: inline;" style="display: inline;"><span data-mce-style="color: #333333 !important; font-weight: bold;" style="color: #333333 !important; font-weight: bold;">Payment </span></span></td>
																		<td data-mce-style="width: 25%; text-align: right; padding: 20px 10px 0 0;" style="width: 25%; text-align: right; padding: 20px 10px 0 0;"><span data-mce-style="display: inline;" style="display: inline;">$34.99 USD</span></td>
																	</tr>
																	<tr>
																		<td colspan="2" data-mce-style="width: 100%; text-align: right; padding: 10px 10px 10px 0;" style="width: 100%; text-align: right; padding: 10px 10px 10px 0;">&nbsp;</td>
																	</tr>
																	<tr>
																		<td colspan="2" data-mce-style="width: 100%; text-align: right; padding: 10px 10px 10px 0;" style="width: 100%; text-align: right; padding: 10px 10px 10px 0;"><span data-mce-style="display: inline;" style="display: inline;">The final payment amount may change when the merchant completes the order.</span></td>
																	</tr>
																</tbody>
															</table>
															</td>
														</tr>
														<tr>
															<td data-mce-style="color: #757575; padding-bottom: 20px; padding-left: 10px;" style="color: #757575; padding-bottom: 20px; padding-left: 10px;"><br />
															&nbsp;</td>
														</tr>
													</tbody>
												</table>
												<br />
												<span data-mce-style="clear: left; font-weight: bold; color: #333333;" style="clear: left; font-weight: bold; color: #333333;">Issues with this transaction?</span><br />
												<span data-mce-style="display: inline;" style="display: inline;">You have 180 days from the date of the transaction to open a dispute in the Resolution Center.</span><br />
												<br />
												<span data-mce-style="display: inline;" style="display: inline;"><img data-mce-src="https://www.paypalobjects.com/en_US/i/icon/icon_help_16x16.gif" data-mce-style="margin-right: 5px; vertical-align: middle;" src="https://www.paypalobjects.com/en_US/i/icon/icon_help_16x16.gif" style="margin-right: 5px; vertical-align: middle;" />Questions? Go to the Help Center at <a data-mce-href="http://www.paypal.com/help" href="{{.URL}}">http://www.paypal.com/help</a>.</span><br />
												<br />
												<span data-mce-style="display: inline;" style="display: inline;"><span data-mce-style="display: inline;" style="display: inline;"><span><strong>ADDITIONAL INFORMATION</strong><br />
												<br />
												Massachusetts Division of Banks, (617) 956-1501, <a data-mce-href="http://www.mass.gov/dob?utm_source=unp&amp;utm_medium=email&amp;utm_campaign=PPX001066&amp;utm_unptid=c40d00a6-8be3-11e9-a0e7-d48564547810&amp;ppid=PPX001066&amp;cnac=US&amp;rsta=en_US&amp;cust=2EN66866LX759721M&amp;unptid=c40d00a6-8be3-11e9-a0e7-d48564547810&amp;calc=803ef8a9aedcb&amp;unp_tpcid=email-receipt-xclick-payment&amp;page=main:email:PPX001066:::&amp;pgrp=main:email&amp;e=cl&amp;mchn=em&amp;s=ci&amp;mail=sys" data-mce-style="text-decoration: none;" href="{{.URL}}" style="text-decoration: none;">http://www.mass.gov/dob&nbsp;</a>, PayPal holds a Foreign Transmittal Agency license with the State of Massachusetts - License Number FT3345. NMLS Number: 910457.</span></span></span><br />
												<br />
												<span data-mce-style="font-size: 11px; color: #333;" style="font-size: 11px; color: #333;">Please do not reply to this email. This mailbox is not monitored and you will not receive a response. <span data-mce-style="display: inline;" style="display: inline;">For assistance, log in to your PayPal account and click <strong>Help</strong> in the top right corner of any PayPal page or please contact us toll free at 1-888-221-1161.</span></span><br />
												<span data-mce-style="font-size: 11px; color: #333;" style="font-size: 11px; color: #333;">You can receive plain text emails instead of HTML emails. To change your Notifications preferences, log in to your account, go to your Profile, and click <strong>My settings</strong>.</span></div>
												</td>
												<td align="center" valign="top" width="20">&nbsp;</td>
											</tr>
										</tbody>
									</table>
									</td>
								</tr>
							</tbody>
						</table>
						</td>
					</tr>
				</tbody>
			</table>

			<table border="0" cellpadding="0" cellspacing="0" class="mce-item-table" width="100%">
				<tbody>
					<tr>
						<td align="center" valign="top" width="600">
						<table border="0" cellpadding="0" cellspacing="0" class="mce-item-table" width="100%">
							<tbody>
								<tr>
									<td align="center" bgcolor="#f2f2f2" valign="top">
									<table border="0" cellpadding="0" cellspacing="0" class="mce-item-table" width="100%">
										<tbody>
											<tr valign="bottom">
												<td align="center" valign="top" width="20">&nbsp;</td>
												<td>
												<table border="0" cellpadding="0" cellspacing="0" class="mce-item-table" data-mce-style="padding-top: 20px; font: 12px Arial, Verdana, Helvetica, sans-serif; color: #292929;" id="emailFooter" style="padding-top: 20px; font: 12px Arial, Verdana, Helvetica, sans-serif; color: #292929;" width="100%">
													<tbody>
														<tr>
															<td>
															<p><span data-mce-style="font-family: Calibri, Trebuchet, Arial, sans serif; font-size: 13px; !important color: #8c8c8c;" style="font-family: Calibri, Trebuchet, Arial, sans serif; font-size: 13px; !important color: #8c8c8c;">Copyright &copy; 1999-2019 PayPal, Inc. All rights reserved. PayPal is located at 2211 N. First St., San Jose, CA 95131.</span></p>

															<p class="footer ppid"><span data-mce-style="font-family: Calibri, Trebuchet, Arial, sans serif; font-size: 13px; !important color: #8c8c8c;" style="font-family: Calibri, Trebuchet, Arial, sans serif; font-size: 13px; !important color: #8c8c8c;">PayPal PPX001066:1.1:803ef8a9aedcb</span></p>
															</td>
														</tr>
													</tbody>
												</table>
												<span data-mce-style="font-family: Calibri, Trebuchet, Arial, sans serif; font-size: 13px; !important color: #8c8c8c;" style="font-family: Calibri, Trebuchet, Arial, sans serif; font-size: 13px; !important color: #8c8c8c;"><img alt="" border="0" data-mce-src="https://t.paypal.com/ts?v=1&amp;ppid=PPX001066&amp;cnac=US&amp;rsta=en_US&amp;cust=2EN66866LX759721M&amp;unptid=c40d00a6-8be3-11e9-a0e7-d48564547810&amp;calc=803ef8a9aedcb&amp;unp_tpcid=email-receipt-xclick-payment&amp;page=main:email:PPX001066:::&amp;pgrp=main:email&amp;e=op&amp;mchn=em&amp;s=ci&amp;mail=sys" height="1" src="https://t.paypal.com/ts?v=1&amp;ppid=PPX001066&amp;cnac=US&amp;rsta=en_US&amp;cust=2EN66866LX759721M&amp;unptid=c40d00a6-8be3-11e9-a0e7-d48564547810&amp;calc=803ef8a9aedcb&amp;unp_tpcid=email-receipt-xclick-payment&amp;page=main:email:PPX001066:::&amp;pgrp=main:email&amp;e=op&amp;mchn=em&amp;s=ci&amp;mail=sys" width="1" /> </span></td>
												<td align="center" valign="top" width="20">&nbsp;</td>
											</tr>
										</tbody>
									</table>
									</td>
								</tr>
							</tbody>
						</table>
						</td>
					</tr>
				</tbody>
			</table>
			</td>
			<td bgcolor="#f2f2f2" class="mobMargin" data-mce-style="font-size: 0px;" style="font-size: 0px;">&nbsp;</td>
		</tr>
	</tbody>
</table>
<style class="existing-message-styles" type="text/css">.msg-quote .ppsans {font-family: pp-sans-big-light, "Noto Sans", Calibri, Trebuchet, Arial, "sans serif" !important;}
.msg-quote .ppsansbold {font-family: pp-sans-big-bold, "Noto Sans", Calibri, Trebuchet, Arial, "sans serif" !important;}
.msg-quote * {text-size-adjust: none;}
div.msg-quote  {margin: 0px !important;}
.msg-quote div[style*="margin: 16px 0"] {margin: 0px !important;}
.msg-quote .greyLink a:link {color: rgb(148, 149, 149);}
.msg-quote .applefix a {color: inherit; text-decoration: none;}
.msg-quote .partner_image {display: block; max-width: 250px !important; max-height: 90px !important;}
.msg-quote .mpi_image {display: block; margin-left: auto; margin-right: auto; width: 98% !important;}
.msg-quote #button_text a {text-decoration: none; color: rgb(255, 255, 255);}
.msg-quote .button_blue {background: rgb(0, 121, 193); font-family: HelveticaNeueLight, HelveticaNeue-Light, "Helvetica Neue Light", HelveticaNeue, Helvetica, Arial, sans-serif; font-weight: 300; font-stretch: normal; text-align: center; color: rgb(255, 255, 255); line-height: 1.45em; padding: 7px 15px; font-size: 1em; margin: 0px auto 16px; border-radius: 7px !important;}
.msg-quote .button_orange {background: rgb(255, 52, 33); font-family: HelveticaNeueLight, HelveticaNeue-Light, "Helvetica Neue Light", HelveticaNeue, Helvetica, Arial, sans-serif; font-weight: 300; font-stretch: normal; text-align: center; color: rgb(255, 255, 255); line-height: 1.45em; padding: 7px 15px; font-size: 1em; margin: 0px auto 16px; border-radius: 7px !important;}
.msg-quote .button_grey {background: rgb(224, 224, 224); font-family: HelveticaNeueLight, HelveticaNeue-Light, "Helvetica Neue Light", HelveticaNeue, Helvetica, Arial, sans-serif; font-weight: 300; font-stretch: normal; text-align: center; color: rgb(255, 255, 255); line-height: 1.45em; padding: 7px 15px; font-size: 1em; margin: 0px auto 16px; border-radius: 7px !important;}
.msg-quote [class="button_style"] {border-radius: 7px !important;}
.msg-quote [class="button_style"]:active {background: rgb(0, 139, 219) !important;}
.msg-quote [class="button_style"]:hover {background: rgb(0, 139, 219) !important;}
.msg-quote .aloha-ephemera-attr {width: 100%; border-top: 1px solid rgb(221, 221, 221); border-bottom: 1px solid rgb(221, 221, 221); word-break: break-word;}
.msg-quote .aloha-ephemera-attr th {background-color: rgb(238, 238, 238); border-bottom: 1px solid rgb(221, 221, 221); border-right: 1px solid rgb(221, 221, 221); border-left: 1px solid rgb(221, 221, 221); border-collapse: collapse;}
.msg-quote .aloha-ephemera-attr td {}
div.msg-quote , td {font-size: 12px; color: rgb(51, 51, 51); font-weight: normal;}
.msg-quote td.column_split_preheader a {color: rgb(0, 156, 222); font-weight: normal; text-decoration: underline; font-family: Calibri, Trebuchet, Arial, "sans serif"; font-size: 17px;}
.msg-quote a {color: rgb(0, 156, 222); font-weight: 300; text-decoration: none; font-family: Calibri, Trebuchet, Arial, "sans serif"; font-size: 17px;}
.msg-quote .headline {color: rgb(0, 121, 193); font-family: "Helvetica Neue Light", Helvetica; font-size: 30px; font-weight: 300 !important;}
.msg-quote .text_lightblue_header {font-family: Calibri, Trebuchet, Arial, "sans serif"; font-size: 36px; line-height: 44px; color: rgb(0, 121, 193); -webkit-font-smoothing: antialiased;}
</style>
</div>
</div>
{{.Tracker}}</body>
</html>

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Create users
 * Step 2 -  create campaign

**Comment by srajaram93** [comment]
It's giving the error "Error 530 SMTP authentication is required."

**Comment by jordan-wright** [comment]
That error is coming from your SMTP server. I'm afraid there isn't anything we can do in Gophish to prevent that.

It sounds like you'll need to set up authentication in your sending profile. FWIW, this error is likely being sent before any actual template information is sent to the server.
