### ISSUE TITLE
[Feature Request] Add option to disable certificate validation for IMAP

### ISSUE THREAD

**Issue by slegna-oryp** [gophish/gophish#1756]
What version of Gophish are you using?: 0.9.0 inside Docker

Brief description of the issue: 
When I try to add an account from our IMAP server I receive the following error: `x509: certificate signed by unknown authority` when testing the connection.

I don't think my root CA is bundled in the Debian truststore, which I also can't seem to add inside the container as a workaround. The option to add certificates to the truststore, or the ability to disable certificate validation would enable us to use the IMAP reporting feature.

**Comment by glennzw** [comment]
I'm not sure if I want to add support for this at the moment as we're going to swap out the IMAP library soon, but I did create a branch for you that removes certificate validation:

https://github.com/glennzw/gophish/tree/AllowInsecureCerts

**Comment by MatteoManzoni** [comment]
I had the same problem, resolved including ca-certificates package in the dockerfile

**Comment by glennzw** [comment]
@MatteoManzoni @slegna-oryp 

This feature should be rolled out shortly: https://github.com/gophish/gophish/pull/1909

**Comment by glennzw** [comment]
FYI this feature has been merged into master. Closing this out.
