### ISSUE TITLE
Unable to view the Statics of the campaing

### ISSUE THREAD

**Issue by chris134pravin** [gophish/gophish#1759]
What version of Gophish are you using?: 
0.9.0

Brief description of the issue: 
I am running this campaign on a purchased domain and this domain is reachable to all public users and I am running this on a cloud server (CentOS 7) with docker.

What are you expecting to see happen? :
So I initially tested this with my team and I request them that few click on the link and few visit the site and a few of them to report it but i am unable to get any kind of stats when I run the campaign I am able to see that the emails have been sent but after that, I have no other statics that I am able to view
![image](https://user-images.githubusercontent.com/12962838/75344075-cbd5b680-58bf-11ea-8a57-3531e5ab439d.png)

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Landing Page
![image](https://user-images.githubusercontent.com/12962838/75344207-23742200-58c0-11ea-9af7-162f0a472016.png)

 * Step 2 - Email Template
![image](https://user-images.githubusercontent.com/12962838/75344266-4e5e7600-58c0-11ea-9b2e-e886f1feebc1.png)

**Comment by jordan-wright** [comment]
Hey there!

Take a look through [this section](https://docs.getgophish.com/user-guide/faq#events-arent-showing-up-on-the-dashboard) of our FAQ and let me know if you continue to run into issues.

Thanks for reaching out!

**Comment by chris134pravin** [comment]
Hi so I did go through the FAQ and the Guide and followed the step as procedures but yet I don't receive any static of the campaign that I run for further clarification I have attached the screenshots.

![Capture](https://user-images.githubusercontent.com/12962838/75666682-3dd14580-5c9c-11ea-8427-2d8796e731aa.JPG)
![static error](https://user-images.githubusercontent.com/12962838/75666691-40339f80-5c9c-11ea-8ec5-d435e2dc50a9.JPG)

**Comment by chris134pravin** [comment]
> Is that rid generated by Gophish, or by you?

The rid i is generated by gophish

>What do you see on that page?

I am able to see the website login page developed by me (ScreenShot Below)
![gophish error](https://user-images.githubusercontent.com/12962838/75850080-68daa700-5e0c-11ea-9567-47982e011fe7.png)

>What URL did you use when building the campaign?

The URL used during the campaign is a purchased domain. where gophish is using the purchased URL to be accessed through port 3333 and the login page is using the same Domain on port 80. 
(Screenshot Below)
![gophish error 1](https://user-images.githubusercontent.com/12962838/75851201-0cc55200-5e0f-11ea-882d-48a920e18f50.png)

![gophish error 2](https://user-images.githubusercontent.com/12962838/75851200-0cc55200-5e0f-11ea-959a-843ad18b7215.png)

>Have you confirmed it's reachable?

Yes, I confirmed that it is reachable.
