### ISSUE TITLE
customize phishing site

### ISSUE THREAD

**Issue by axl6ab0** [gophish/gophish#1761]
What version of Gophish are you using?: 
0.9

Brief description of the issue: 
Good morning with everyone, so far I have worked very well with gophish, without a doubt the best tool for phishing shipments, I have a doubt, for the landing page and the phishing site I use no-ip to create the temporary domain, now I want to do something more complete, I bought a domain and a hosting to host my site there, with ssl certificate to make it look safe, can you work this way? since the site created is https://mail.example.com

**Comment by jordan-wright** [comment]
You have to host the site using Gophish. Normal hosting providers who give you either static site hosting or, say, PHP hosting won’t work.

You’ll need to use a VPS from a provider like DigitalOcean where you can install and use Gophish.

Beyond that, you can absolutely use the domain name and SSL certificate you’ve created. The SSL certificate should be specified in the config.json file.

I hope this helps!
