### ISSUE TITLE
LATEST GOPHISH ISSUE

### ISSUE THREAD

**Issue by rfalk347** [gophish/gophish#1764]
How do i go into the database of a particuliar campaign and search to verify in the actual data base if someone actually did click a link and submit actual credentials - is it possible that the user didnt click and submit data and the tool registered it as clicked and submitted?

**Comment by kpomeroy1979** [comment]
You can use the SQLite database program to directly interact with the data
that GoPhish collects. Sometimes, security software will open the email and
inspect the links and data before sending it to the end users inbox so it
is possible that a click has been registered, but not by the end user.
Please correct me if I'm wrong. I have never seen a false submitted data
report however.

**Comment by jordan-wright** [comment]
@kpomeroy1979 is correct. It’s technically possible that security software visited the link in the email, which would register as a click in Gophish.

All of the data it sounds like you care about will be in the “results” or “events” tables.

I hope this helps!

**Comment by rfalk347** [comment]
Do you know if mimecast is capable of doing this.?

Thanks

Sent via the Samsung Galaxy S® 6 edge, an AT&T 4G LTE smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jordan-wright** [comment]
Probably? Maybe? I’m not sure. Most security appliances would likely have some capability like this.
