### ISSUE TITLE
Launching Loop

### ISSUE THREAD

**Issue by Ignaros** [gophish/gophish#1766]
Hello Guys,

when I want to launch a new campaign it just won´t start and has got a loop...

![image](https://user-images.githubusercontent.com/61731549/75757939-90aa0c00-5d33-11ea-9d0a-c7ae22ce9966.png)

![image](https://user-images.githubusercontent.com/61731549/75757980-a28baf00-5d33-11ea-93f1-68d52d609d12.png)

anybody any idea?

**Comment by jordan-wright** [comment]
Take a look at the error message in the campaign screen- you didn’t specify a sending profile (or groups, or an email template). All of those are needed for a campaign.

My guess is that the modal just didn’t close out when an error is detecting so you should probably hit cancel and address the errors.

Hope this helps!
