### ISSUE TITLE
Landing Pages noch reachable

### ISSUE THREAD

**Issue by Ignaros** [gophish/gophish#1767]
Hello, I want to use gophish for educational usage and no I´m wondering, because nobody can reach my Landing Page.

config:
{
	"admin_server": {
		"listen_url": "127.0.0.1:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "gophish_admin.key"
	},
	"phish_server": {
		"listen_url": "192.168.1.9:80",
		"use_tls": false,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": "",
	"logging": {
		"filename": "",
		"level": ""
	}
}

campaign:
![image](https://user-images.githubusercontent.com/61731549/75803628-05eefe80-5d7f-11ea-8ada-c90ac1a7bd98.png)

what is wrong? :/

**Comment by jordan-wright** [comment]
The IP address of your listen URL is different than the IP address you’re using in your campaign.

**Comment by Ignaros** [comment]
ah i see, do they have to be the same IP?

**Comment by Ignaros** [comment]
{
	"admin_server": {
		"listen_url": "127.0.0.1:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "gophish_admin.key"
	},
	"phish_server": {
		"listen_url": "192.168.1.9:80",
		"use_tls": false,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": "",
	"logging": {
		"filename": "",
		"level": ""
	}
}

![image](https://user-images.githubusercontent.com/61731549/75880039-cf67c100-5e1c-11ea-9326-9947627f9b75.png)


![image](https://user-images.githubusercontent.com/61731549/75879996-c0810e80-5e1c-11ea-9c22-53d46961dbd2.png)

still not working :/
