### ISSUE TITLE
How to import email content in form 

### ISSUE THREAD

**Issue by prashant199128** [gophish/gophish#1769]
How to import email content in HTML form field while creating email template.

**Comment by TheGroundZero** [comment]
1. Make sure you have the source of the email
2. Create a new e-mail template
3. Click the Import Email button
4. Copy/paste the source of the source email into the dialog that appears
5. Click OK

To edit:

1. Click on the HTML tab
2. Use the "Source" button to switch between source and rendered view

PS: The import requires both the email headers as the content.  
In Outlook, right-click in an email and choose "view source" to copy the content.  
To copy the headers, open the email in a separate window, go to File > Properties, copy the internet headers.  
Paste the headers above the email content in the import dialog.

**Comment by jordan-wright** [comment]
@TheGroundZero is correct. Thank you for sending in this answer!

I've updated the documentation to say "Importing an Email".
