### ISSUE TITLE
Starting Whitespace Not Trimmed When Importing Emails

### ISSUE THREAD

**Issue by snori74** [gophish/gophish#177]
The input box prompts for "Raw Email Source" - yet feeding it something like the text from "Show original" in GMail doesn't seem to do the trick - it justs end up in the TEXT version of the email. 

Is there something I'm doing wrong, or is this simply not yet working as intended?

((a) - I *thought* I'd seen this work initially, but in testing I've had no luck at all, so can only think I'm remebering the Import option in "Landing pages". (b) - Clearly it's also possible to cut and paste bits of HTML from the "show original" raw text into the HTML tab of the email setup - but then why have an "Import Email" option?).

**Comment by jordan-wright** [comment]
Hey there!

Just a couple things to check:

1) Is the HTML base64 encoded? Unfortunately, that's not currently supported but is on the way.

2) This might sound crazy, but is there a blank line at the start of the "View Original" text? If so, try highlighting all text *after* that blank line and paste that into the import email.

**Comment by snori74** [comment]
Indeed, blank line at the top of the raw text kills the functionality. Still an issue, but...

* Should be renamed to something like "Poor handling of email import text". 

Trimming any whitespace from the beginning of the import will probably do the trick, and save a lot of hassle for users. (GMail always puts such blank line at the top of their "Show original" text -  so a Cntrl-A to select all such text will grab that line too).

**Comment by jordan-wright** [comment]
I agree completely. It goes into how the mail parsing is handled. I
remember looking at it a while back and, IIRC, it wasn't quite as simple on
the backend to handle it, but I'll look again and see what I can do.

Thanks for the report!

**Comment by jordan-wright** [comment]
Good news! This should be fixed in the email library as of https://github.com/jordan-wright/email/commit/a62870b0c368c3c29de27027be67d855e308cc37. 

If you're building from source, try a ```go get -u```, followed by a ```go build```. That should clear it up just fine.

Let me know if you run into issues!
