### ISSUE TITLE
GoPhish emails always end up in spam (due to X-Mailer header?)

### ISSUE THREAD

**Issue by TheGroundZero** [gophish/gophish#1771]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  0.9.0

Brief description of the issue: Testing Email Campaigns with a variety of target email providers, emails always end up in Spam/Unwanted.

What are you expecting to see happen? : Get emails to end up in the Inbox.

What are you seeing happen?

I noticed in Gmail that the email is explicitly marked as being sent by GoPhish.  
I assume that this is triggering the email filters, causing none of the mails to end up in the Inbox.  
This is caused by the X-Mailer header.

Note that I made an effort in setting up SPF, DMARC and DKIM.

![image](https://user-images.githubusercontent.com/2406013/75867884-89ecc900-5e07-11ea-8e89-056a7b9ed888.png)
![image](https://user-images.githubusercontent.com/2406013/75868039-c9b3b080-5e07-11ea-84bc-2af0e134f249.png)

**Comment by jordan-wright** [comment]
There are many reasons why an email may end up in spam. The X-Mailer is a possibility, and you have the ability to remove that if you want.

But I recommend instead to whitelist your sending IP address to ensure that emails get delivered.

Sorry we couldn’t be of more help!

**Comment by knvpk** [comment]
How to remove the `X-Mailer`? @jordan-wright
