### ISSUE TITLE
Gophish Ports

### ISSUE THREAD

**Issue by IamAdi9** [gophish/gophish#1775]
Greetings everyone

I want to install gophish  in my server but I don't want to open extra ports on it. So I just have port 80 and 443. Please help me knowing should I change my config.json to achieve?

Also if someone suggest this then I have another problem 
I tried this everything worked smoothly expect two thing - 

1. When I clicked link I was getting to the real website rather than my cloned Landing Page.
2. My Dashboard was not getting update  whenever I clicked on any of the link and even when I entered credentials I was getting logged on to real website.

Thanks in advance. Apologies  if explanation  was not up to the mark.

This is config.json
"admin_server" : {
                "listen_url" : "127.0.0.1:80",
                "use_tls" : true,
                "cert_path" : "gophish_admin.crt",
                "key_path" : "gophish_admin.key"
        },
        "phish_server" : {
                "listen_url" : "0.0.0.0:443",
                "use_tls" : false,
                "cert_path" : "example.crt",
                "key_path": "example.key"
        },
        "db_name" : "sqlite3",
        "db_path" : "gophish.db",
        "migrations_prefix" : "db/db_"

**Comment by jordan-wright** [comment]
Let’s please keep issues focused to a single problem.

In your current config, you’re only really exposing port 443, since the admin panel is bound to 127.0.0.1.

I believe both of your other questions can be answered via our FAQ https://docs.getgophish.com/user-guide/faq#events-arent-showing-up-on-the-dashboard

**Comment by IamAdi9** [comment]
Thank you @jordan-wright for you response.
Can you please also assist me with more thing.
I want to install gophish on apache server and want to access that over public ip. If it is possible what should I do?

**Comment by edermi** [comment]
You want Apache to be your reverse proxy: https://httpd.apache.org/docs/2.4/howto/reverse_proxy.html

**Comment by IamAdi9** [comment]
Yes idea is like that, mainly I want web portal of gophish to be available over internet for admins.

**Comment by bjb28** [comment]
@IamAdi9, you might try using GoPhish inside a docker.  You can then link the GoPhish ports to a different port to be exposed by docker.  

Using a docker also seems like a fix that will allow you to reach the admin page external from the machine.  I just successfully tested this on my local network

**Comment by IamAdi9** [comment]
@bjb28  ok I will try that and may I also ask Is it possible to use port 80 for both admin as well as phishing server. 
I am trying to achieve that but I get reply as "listen tcp 0.0.0.0:80: bind: address already in use" 
none of the other service is turned on for port 80. Rather than phishing server .

**Comment by jordan-wright** [comment]
This error is suggesting that there is some other web server listening on TCP port 80. You will need to shut down that web server so that Gophish can bind to the port.
