### ISSUE TITLE
Segmentation Violation on 0.9.0 upgrade

### ISSUE THREAD

**Issue by aPatinthehat** [gophish/gophish#1778]
What version of Gophish are you using?:
0.9.0

Brief description of the issue: 
gophish-v0.9.0-linux-64bit.zip checksum matches. Unzipped to a folder and attempts to run ./gophish results in the following error. Version 0.8.0 still works as expected. Ubuntu 16.04.6 LTS
 
```
time="2020-03-09T14:08:47Z" level=warning msg="No contact address has been configured."
time="2020-03-09T14:08:47Z" level=warning msg="Please consider adding a contact_address entry in your config.json"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x628f16]

goroutine 1 [running]:
github.com/gophish/gophish/logger.Setup(0x0, 0xc0001fc000, 0x5)
	/go/src/github.com/gophish/gophish/logger/logger.go:34 +0x26
main.main()
	/go/src/github.com/gophish/gophish/gophish.go:73 +0x23a
```

**Comment by S0larflare** [comment]
Can you post your config.json? I suspect you’re using an older format which doesn’t have the logger part at the end, which is causing it to throw its toys out of the pram

Sent from my iPhone

On 9 Mar 2020, at 14:16, aPatinthehat <notifications@github.com> wrote:

﻿

What version of Gophish are you using?:
0.9.0

Brief description of the issue:
gophish-v0.9.0-linux-64bit.zip checksum matches. Unzipped to a folder and attempts to run ./gophish results in the following error. Version 0.8.0 still works as expected. Ubuntu 16.04.6 LTS

time="2020-03-09T14:08:47Z" level=warning msg="No contact address has been configured."
time="2020-03-09T14:08:47Z" level=warning msg="Please consider adding a contact_address entry in your config.json"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x628f16]

goroutine 1 [running]:
github.com/gophish/gophish/logger.Setup(0x0, 0xc0001fc000, 0x5)
        /go/src/github.com/gophish/gophish/logger/logger.go:34 +0x26
main.main()
        /go/src/github.com/gophish/gophish/gophish.go:73 +0x23a

**Comment by aPatinthehat** [comment]
Yup it appears that was the issue. After modifying the appropriate config.json for v.09, everything works as expected without errors. Thanks!
