### ISSUE TITLE
I have the following error

### ISSUE THREAD

**Issue by lgcambero** [gophish/gophish#178]
![screenshot from 2016-02-27 17-59-33](https://cloud.githubusercontent.com/assets/11602705/13380029/1b9df7aa-de16-11e5-84a7-83ad40c33da3.png)

**Comment by wjwoodson** [comment]
Hi, if building from source you will need to set your $GOPATH to store dependencies [(see go installation)](https://golang.org/doc/install)

This should get you up and running:
`mkdir $HOME/gocode`
`echo 'export GOPATH=$HOME/gocode' >> $HOME/.profile`
`source $HOME/.profile`
`go get github.com/gophish/gophish`
`cd $HOME/gocode/src/github.com/gophish/gophish`
`go build`

There are also binary gophish releases available **[here](https://github.com/gophish/gophish/releases)**.

**Comment by lgcambero** [comment]
Thank you very much for the help, you can fix it. You should use some example, video, etc.?

**Comment by jordan-wright** [comment]
Hi @lgcambero, thanks for the report! @wjwoodson gave correct information on how to fix this.

My recommendation would be to follow the tutorials on Go's project website to get up and running with the Go language. From there, installing gophish is a straightforward process identical to installing any Go package. It is considered out of our scope to provide full instructions on how to get up and running with Go itself.

If you are having difficulty with installing from source, we recommend downloading the binary version of gophish for your platform. After downloading this binary, you can just run it and be good to go as shown in our User Guide.

Hope this helps!

**Comment by lgcambero** [comment]
Of course, thanks!

**Comment by lgcambero** [comment]
Sorry, When I launch the test campaign closes automatically gophish me, console is all I see. You can help me? Sorry but the English is not mine, I am from Argentina:

 2016/02/27 22:29:08 main_private.go:23: sql/root/projects/src/github.com/gophish/gophish/models/campaign.go:1001.146223msINSERT INTO "events" ("campaign_id","email","time","message") VALUES (?,?,?,?) [1  2016-02-27 22:29:08.129963336 -0300 ART Campaign Created]
 2016/02/27 22:29:08 worker.go:42: Worker received: prueba
127.0.0.1 - - [27/Feb/2016:22:29:07 -0300] "POST /api/campaigns/?api_key=96d586956b8c6251a596a79a9883ef6de32a361759a47fb27b2581e11ba17fc4 HTTP/1.1" 201 110234 "http://127.0.0.1:3333/campaigns" "Mozilla/5.0 (X11; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0 Iceweasel/44.0.2"
 2016/02/27 22:29:08 worker.go:57: mail: no address
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x647c32]

goroutine 8 [running]:
github.com/gophish/gophish/worker.processCampaign(0xc820ada1e0)
	/root/projects/src/github.com/gophish/gophish/worker/worker.go:59 +0x26a2
github.com/gophish/gophish/worker.(*Worker).Start(0xc820028b90)
	/root/projects/src/github.com/gophish/gophish/worker/worker.go:37 +0x119
created by github.com/gophish/gophish/controllers.init.1
	/root/projects/src/github.com/gophish/gophish/controllers/api.go:28 +0x9f

goroutine 1 [semacquire, 4 minutes]:
sync.runtime_Semacquire(0xc82019e87c)
	/root/go/src/runtime/sema.go:43 +0x26
sync.(*WaitGroup).Wait(0xc82019e870)
	/root/go/src/sync/waitgroup.go:126 +0xb4
main.main()
	/root/projects/src/github.com/gophish/gophish/gophish.go:75 +0x17b

goroutine 17 [syscall, 4 minutes, locked to thread]:
runtime.goexit()
	/root/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 18 [syscall, locked to thread]:
github.com/mattn/go-sqlite3._Cfunc_sqlite3_step(0x7ff7ec001878, 0xc800000000)
	github.com/mattn/go-sqlite3/_obj/_cgo_gotypes.go:787 +0x35
github.com/mattn/go-sqlite3.(*SQLiteRows).Next(0xc82071a690, 0xc820360fc0, 0x4, 0x4, 0x0, 0x0)
	/root/projects/src/github.com/mattn/go-sqlite3/sqlite3.go:897 +0x4c
database/sql.(*Rows).Next(0xc8206a2720, 0xc820360f80)
	/root/go/src/database/sql/sql.go:1639 +0x12b
github.com/jinzhu/gorm.Query(0xc8202da700)
	/root/projects/src/github.com/jinzhu/gorm/callback_query.go:56 +0x921
github.com/jinzhu/gorm.(*Scope).callCallbacks(0xc8202da700, 0xc8201982e0, 0x3, 0x4, 0xc8202da700)
	/root/projects/src/github.com/jinzhu/gorm/scope_private.go:331 +0x68
github.com/jinzhu/gorm.(*DB).First(0xc8201106e0, 0x943000, 0xc820360740, 0x0, 0x0, 0x0, 0xc8201106e0)
	/root/projects/src/github.com/jinzhu/gorm/main.go:204 +0x236
github.com/gophish/gophish/models.GetUser(0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/projects/src/github.com/gophish/gophish/models/user.go:17 +0x1ed
github.com/gophish/gophish/middleware.GetContext.func1(0x7ff7f2e71368, 0xc820816930, 0xc82066a2a0)
	/root/projects/src/github.com/gophish/gophish/middleware/middleware.go:29 +0x27d
net/http.HandlerFunc.ServeHTTP(0xc82021bce0, 0x7ff7f2e71368, 0xc820816930, 0xc82066a2a0)
	/root/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/handlers.combinedLoggingHandler.ServeHTTP(0x7ff7f2e6b1c0, 0xc820028010, 0x7ff7f2e70000, 0xc82021bce0, 0x7ff7f2e711c8, 0xc8206de370, 0xc82066a2a0)
	/root/projects/src/github.com/gorilla/handlers/handlers.go:77 +0x11f
github.com/gorilla/handlers.(*combinedLoggingHandler).ServeHTTP(0xc82021bd00, 0x7ff7f2e711c8, 0xc8206de370, 0xc82066a2a0)
	<autogenerated>:12 +0xb4
net/http.serverHandler.ServeHTTP(0xc820219d40, 0x7ff7f2e711c8, 0xc8206de370, 0xc82066a2a0)
	/root/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc82027c000)
	/root/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/root/go/src/net/http/server.go:1910 +0x3f6

goroutine 9 [chan receive, 4 minutes]:
database/sql.(*DB).connectionOpener(0xc8201bd400)
	/root/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
	/root/go/src/database/sql/sql.go:481 +0x336

goroutine 10 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7ff7f2e70f90, 0x72, 0xc82000a200)
	/root/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82027a290, 0x72, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82027a290, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82027a230, 0x0, 0x7ff7f2e71148, 0xc820333920)
	/root/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820228150, 0x458ee0, 0x0, 0x0)
	/root/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc820228150, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/net/http/server.go:2135 +0x41
net/http.(*Server).Serve(0xc820219d40, 0x7ff7f2e71110, 0xc820228150, 0x0, 0x0)
	/root/go/src/net/http/server.go:1887 +0xb3
net/http.(*Server).ListenAndServe(0xc820219d40, 0x0, 0x0)
	/root/go/src/net/http/server.go:1877 +0x136
net/http.ListenAndServe(0xc82000af40, 0xe, 0x7ff7f2e70078, 0xc82021bd00, 0x0, 0x0)
	/root/go/src/net/http/server.go:1967 +0x8f
main.main.func1(0xc82019e870)
	/root/projects/src/github.com/gophish/gophish/gophish.go:60 +0x671
created by main.main
	/root/projects/src/github.com/gophish/gophish/gophish.go:62 +0x134

goroutine 11 [IO wait]:
net.runtime_pollWait(0x7ff7f2e71050, 0x72, 0xc82000a200)
	/root/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82021e990, 0x72, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82021e990, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82021e930, 0x0, 0x7ff7f2e71148, 0xc8200a4060)
	/root/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820028c08, 0x458ee0, 0x0, 0x0)
	/root/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc820028c08, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/net/http/server.go:2135 +0x41
net/http.(*Server).Serve(0xc82016fb00, 0x7ff7f2e71110, 0xc820028c08, 0x0, 0x0)
	/root/go/src/net/http/server.go:1887 +0xb3
net/http.(*Server).ListenAndServe(0xc82016fb00, 0x0, 0x0)
	/root/go/src/net/http/server.go:1877 +0x136
net/http.ListenAndServe(0xc82000b030, 0xa, 0x7ff7f2e70078, 0xc820198ec0, 0x0, 0x0)
	/root/go/src/net/http/server.go:1967 +0x8f
main.main.func2(0xc82019e870)
	/root/projects/src/github.com/gophish/gophish/gophish.go:72 +0x67d
created by main.main
	/root/projects/src/github.com/gophish/gophish/gophish.go:74 +0x16d

goroutine 72 [IO wait]:
net.runtime_pollWait(0x7ff7f2e708d0, 0x72, 0xc82000a200)
	/root/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82027a060, 0x72, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82027a060, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82027a000, 0xc82078e000, 0x1000, 0x1000, 0x0, 0x7ff7f2e67050, 0xc82000a200)
	/root/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820028000, 0xc82078e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/root/go/src/net/net.go:172 +0xe4
net/http.(*liveSwitchReader).Read(0xc8206de048, 0xc82078e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/root/go/src/net/http/server.go:219 +0xa4
io.(*LimitedReader).Read(0xc8200a4040, 0xc82078e000, 0x1000, 0x1000, 0x11, 0x0, 0x0)
	/root/go/src/io/io.go:427 +0xbd
bufio.(*Reader).fill(0xc820218d20)
	/root/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc820218d20, 0xc81ffcca0a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadLine(0xc820218d20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/bufio/bufio.go:357 +0x53
net/textproto.(*Reader).readLineSlice(0xc820816060, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/net/textproto/reader.go:55 +0x81
net/textproto.(*Reader).ReadLine(0xc820816060, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/net/textproto/reader.go:36 +0x40
net/http.ReadRequest(0xc820218d20, 0xc82066a1c0, 0x0, 0x0)
	/root/go/src/net/http/request.go:653 +0xb6
net/http.(*conn).readRequest(0xc8206de000, 0x0, 0x0, 0x0)
	/root/go/src/net/http/server.go:633 +0x32f
net/http.(*conn).serve(0xc8206de000)
	/root/go/src/net/http/server.go:1319 +0x727
created by net/http.(*Server).Serve
	/root/go/src/net/http/server.go:1910 +0x3f6

**Comment by jordan-wright** [comment]
What "from" address are you using?

**Comment by jordan-wright** [comment]
Just checking in - are you still experiencing this issue? Happy to help any way I can.

**Comment by lgcambero** [comment]
Yes, even I have the problem, I'm using localhost (127.0.0.1:3333) by
entering the IP where the page "Cloned" is generated've put localhost and I
have also tried local ip (192.168.0.103). I want to do a tutorial tool to
upload it to my youtube channel and promote the same
https://www.youtube.com/c/luiscambero. I await your response to operate
Gophish and promote it. Greetings.

2016-02-29 22:01 GMT-03:00 Jordan Wright <notifications@github.com>:

**Comment by jordan-wright** [comment]
Hey @lgcambero thanks for getting back to us. I guess I'm a bit confused... The previous error was showing that there wasn't a "From" address specified in your campaign. Is this still the same issue you encounter? If so, what is the "From" address you are using?

Any information on how you are configuring campaigns that you can share will help us track this down quicker.

Thanks!

**Comment by jordan-wright** [comment]
Hi @lgcambero - any luck tracking this down?

**Comment by lgcambero** [comment]
No brother, :( I need your help, TeamViewer please!!

2016-03-02 21:03 GMT-03:00 Jordan Wright <notifications@github.com>:

**Comment by jordan-wright** [comment]
@lgcambero - I'm afraid I won't be able to perform troubleshooting over TeamViewer.

To troubleshoot this problem, I need the information I've requested multiple times:

> The previous error was showing that there wasn't a "From" address specified in your campaign. Is this still the same issue you encounter? If so, what is the "From" address you are using?

What is the From address you are using when creating a new campaign? This is in the SMTP settings.

**Comment by lgcambero** [comment]
Hello, I could correct the problem, basically I had errors in SMTP. All goes well until I click on the button to redirect me to the phishing URL (127.0.0.1:80) says "404 page not found". Any ideas?? Thank you.

**Comment by jordan-wright** [comment]
@lgcambero - please see the following exchange: https://github.com/gophish/gophish/issues/32#issuecomment-181533760

I think this should answer your questions.

**Comment by lgcambero** [comment]
SOLVED. First I want to thank you for all the help received, I am very grateful indeed, many attentions on your part. I will share with the Latin American community its fantastic tool, always educational and ethical purposes. Thank you very much for everything!! Gophish is the best framework
