### ISSUE TITLE
How to change the config.json in docker version

### ISSUE THREAD

**Issue by JxClur** [gophish/gophish#1780]
Greetings,

#### What version of Gophish are you using?: 
the latest version for docker
#### Brief description of the issue: 
With the gophish docker pulled and run, I found that the config.json of this version cannot be edited through some normal editor, such as nano, vi/vim(it doesn't have these installed and also doesn't have sudo permission by default). how can I do some changes on the config.json, like change the default gophishing port? 
#### What are you expecting to see happen? :
I would like to change the default gophishing port to a non-80 port number, how can I do that?
#### What are you seeing happen?
When I get into the shell of the container, I found it didn't have the normal editors and didn't have sudo permission to install these tools

**Any other methods that could be used to edit the config.json in docker container?**

 Looking forward to your reply, thanks!

**Comment by bjb28** [comment]
If you are looking to change the port, you could use [expose ports](https://docs.docker.com/engine/reference/run/#expose-incoming-ports) to match what you would like to reach. Exposing a non-standard port into the standard port does not make any changes to the config but may meet the intent. Possible example: 

`docker run -it  -p 1234:80  gophish`

Alternatively, you could use [volumes](https://docs.docker.com/engine/reference/run/#volume-shared-filesystems) to share the config file over the default file within the docker. Possible example:  

`docker run -it --rm --volume $PWD/config.json:/opt/gophish/config.json -p 1234:1234  gophish`

**Comment by JxClur** [comment]
Hi bjb28,
Thank you so much, you give a great solution for it!
