### ISSUE TITLE
Problem with track the mail

### ISSUE THREAD

**Issue by llucsito** [gophish/gophish#1781]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  I'm use 0.9.0 

Brief description of the issue: When send a campaing, the mail is send properly, but the track is not running properly, in the statics campaign i don't see statics "Email Openend" and "Clicked Link"

What are you expecting to see happen? : It should show if the recipient has opened the email and has clicked on the link

What are you seeing happen? 
It does not show if the users have opened the email and if they clicked on the link

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

<html>
<head>
	<title>HELLO</title>
</head>
<body>
<p>{{.FirstName}}, The password for {{.Email}} has expired. Please reset your password <a href="https://facebook.com}}">here</a>. Thanks, Morning Catch IT Team</p>
{{.Tracker}}</body>
</html>

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - I have created the Email Template as shown in the previous section
 * Step 2 - I create the campaign as follows
![imagen](https://user-images.githubusercontent.com/47555652/76308501-37aa1d00-62cb-11ea-8570-c052a4fd6e29.png)

**Comment by jordan-wright** [comment]
Hi there,

This FAQ article should address what you’re looking for https://docs.getgophish.com/user-guide/faq#events-arent-showing-up-on-the-dashboard
