### ISSUE TITLE
[Feature Request] Browser Fingerprint

### ISSUE THREAD

**Issue by vay3t** [gophish/gophish#1783]
Is it possible to add a module to obtain the victim's browser fingerprint?

### Refer 
* https://arxiv.org/pdf/1905.01051.pdf

### Projects
* https://github.com/Valve/fingerprintjs2
* https://github.com/jackspirou/clientjs

**Comment by jordan-wright** [comment]
Hi there!

Thanks for taking the time to reach out!

This isn’t something that I’m interested in adding to Gophish directly. Rather, you can always add Javascript on the landing page to generate any fingerprint you want.

Thanks again for getting in touch!
