### ISSUE TITLE
Problem with getting to Landing page

### ISSUE THREAD

**Issue by IamAdi9** [gophish/gophish#1784]
What version of Gophish are you using?: 0.5.0

Brief description of the issue: 
I have installed gophish on server which is accessed by SSH.
I created Landing page and Email Template. When I ran a test campaign I was not able to go to Landing Page.
I was confused with one thing that is what to put in url 
I know that "This should be a URL or IP address that points to the Gophish phishing server and is reachable by the recipient."
I want to know do I need to upload my website to internet by purchasing a domain name and host? and then it will go to landing page

What are you expecting to see happen? : I want to see user clicking on links and getting redirected to landing page

What are you seeing happen? I am going to legit sites and if I put a made up name than it say site is unreachable.

**Comment by asriznet** [comment]
> What are you seeing happen? I am going to legit sites and if I put a made up name than it say site is unreachable.

You would follow the listen_url of the phish_server on your config.json file.

if you have used port 80 and ip address of your gophish server is 10.1.10.20 with hostname of login.contoso.com then you can use either http://10.1.10.20 or http://login.contoso.com for the URL field.

Your target need to be able to access this so ensure your firewall allows it.

If your target are accessing from a remote location, you need to expose your gophish server in your internet firewall and create a DNS record for your hostname using a public IP address. As such, the URL will be accessible from anywhere as long as user has internet connectivity.

**Comment by jordan-wright** [comment]
@asriznet is correct. For the "URL" field when creating a campaign, you should put in the IP address (and port if needed) that points to the server running Gophish. If you purchase a domain name and create a DNS record that points to the server's IP address, you could use the domain name instead.

**Comment by IamAdi9** [comment]
Thank you very much @asriznet  and @jordan-wright . I understood that now completely.
