### ISSUE TITLE
there should be an api to get the user api key

### ISSUE THREAD

**Issue by wasihaider** [gophish/gophish#1787]
What is the point of providing default admin username and password but not an api for getting the default api key. There is no point going to the settings page to get the api key and then hard code it in the scripts. At least there is way to get default api key and then after changing the password the new api key should be returned.

**Comment by edermi** [comment]
When changing credentials, the new API key should already be returned. IMO gophish should not use default credentials at all, but that is tracked in a different ticket. That the key needs to be obtained from the web interface the first time is fairly common I think.

**Comment by jordan-wright** [comment]
@edermi is correct - we are removing default credentials very soon. And it is a common pattern to login first to get your API key, so while I’m always open to reconsidering new flows that keep the same security properties, I don’t have plans to change this now.

And it’s worth noting that the users API does return the API key, though of course if you’re getting the values for your own account you’ll need your API key to actually access that.

Thanks for getting in touch!
