### ISSUE TITLE
Url + "Max connection attempts exceeded - unencrypted connection" issues

### ISSUE THREAD

**Issue by aure44** [gophish/gophish#1788]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

The last one, I downloaded it today

Brief description of the issue: 
When I want to send a test mail, i have the error "Max connection attempts exceeded - unencrypted connection"
And I don't understand how do I choose an url for my campaign
(I know there are already solved issues about these but I simply don't understand, thanks a lot for help !

What are you expecting to see happen? :

Sending the mails

What are you seeing happen?

error "Max connection attempts exceeded - unencrypted connection"

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
Hi @aure44, this is the generic error that indicates there's something wrong with your SMTP setup. You might find more info here: https://github.com/gophish/gophish/issues/1013

**Comment by aure44** [comment]
Thanks a lot, sorry to ask the same question again then.
Have a nice week-end

**Comment by aure44** [comment]
Thanks but I am sorry to tell you that I am not really good at computer, I know basis, that's all. So I don't understand the solutions, this is too vague like check your set up, and every threats lead to another one without an answer. If you could clarify and tell me simply what should I do, this would be really nice of you, please.
Have a nice week-end though

**Comment by glennzw** [comment]
It's hard to help on such a generic error message, but it sounds like your SMTP settings are the problem. You might want to try another mail provider, e.g you can signup to sendgrid.com and send 100 free emails a day.

**Comment by aure44** [comment]
Thanks, I am going to try that, I'll tell you what happen then
Have a nice evening

**Comment by aure44** [comment]
I am sorry to tell you that there are not all functionnalities I was expecting of. Gophish is exactly what I want. But don't worry, if you don't want to help me, just don't, I'll try to fix that by myself and if you just don't have time, don't worry as well, I am not in a hurry

**Comment by jordan-wright** [comment]
As @glennzw mentioned, this is almost certainly an error with how you have SMTP configured. I encourage you to review what settings your SMTP provider requests (as in, do they require TLS connections? Do they require authentication? etc.) and configure Gophish with those settings.

Since this does not appear to be a bug with Gophish itself, I'm going to go ahead and close this one out.

Thanks for reaching out!
