### ISSUE TITLE
Reach landing page w external ip (or NoIP Domain)

### ISSUE THREAD

**Issue by LevBradley** [gophish/gophish#1789]
What version of Gophish are you using?: 
- The newest Version
Brief description of the issue: 
- I want my landing page to be reachable by my external ip adress or noip domain.
 (sry for bad english)
What are you expecting to see happen? :
- Im expecting to reach my landing page with my external ip. If you know noip it would be helpful to explain the problem to me so that in the end I can reach my landing page via a domain from noip
What are you seeing happen?
- The page is endless loading

**Comment by jordan-wright** [comment]
There isn't enough information in this issue for us to begin troubleshooting. All I can say at this point is that you need to ensure that Gophish is running on the server that external IP address or domain name, and the URL you use in a campaign should point to that IP/domain name.

More information can be found in our documentation. Specifically, our [FAQ](https://docs.getgophish.com/user-guide/faq). If you continue to run into issues, please post what exactly you're doing, how you're building your campaign, what you're trying, what you're expecting to see, what you're seeing instead, etc. etc. the more information the better!
