### ISSUE TITLE
gophish inside vagrant not reachable

### ISSUE THREAD

**Issue by kontez** [gophish/gophish#179]
Hi,

I'm using the latest gophish binary on a vagrant box with ubuntu 14.04.
When I launch the gophish binary I receive the following output:
```
vagrant@node1-ubuntu14:~/gophish_linux_amd64$ ./gophish
goose: no migrations to run. current version: 20160118194630
 2016/02/29 14:08:54 worker.go:35: Background Worker Started Successfully - Waiting for Campaigns
 2016/02/29 14:08:54 gophish.go:71: Starting phishing server at http://0.0.0.0:80
 2016/02/29 14:08:54 gophish.go:72: listen tcp 0.0.0.0:80: bind: permission denied
```

Launching it with sudo apparently fixes the error:
```
vagrant@node1-ubuntu14:~/gophish_linux_amd64$ sudo ./gophish
goose: no migrations to run. current version: 20160118194630
 2016/02/29 14:10:15 worker.go:35: Background Worker Started Successfully - Waiting for Campaigns
 2016/02/29 14:10:15 gophish.go:71: Starting phishing server at http://0.0.0.0:80
 2016/02/29 14:10:15 gophish.go:59: Starting admin server at http://127.0.0.1:3333

```

The ip address of the vagrant machine is 192.168.177.19, so with my browser I tried to go to 192.168.177.19:3333 but it receives no response, however 192.168.177.19:80 returns "404 page not found".

Netstat says that the service is running on both ports 80 / 3333.

Thanks. :)

**Comment by jordan-wright** [comment]
Hi @kontez - thanks for the report! We do indeed by default start a phish collection web server on port. This requires root access, since it is a reserved port. If you wish to run gophish as a lower privilege user, you can put a reverse proxy (such as nginx) in front of it and change the ```phish_server``` config setting in ```config.json``` to a different port.

For the 404 - [this comment thread](https://github.com/gophish/gophish/issues/32#issuecomment-181533760) should answer your question.

Let me know if you run into any issues!

**Comment by jordan-wright** [comment]
Closing this for now. Let me know if you run into any other issues.

Thanks!

**Comment by kontez** [comment]
Thank you for your reply, however the issue is that I am unable to reach the web panel even though I can reach the 404 page on port 80.  
If I try to connect to the web panel this is what I get:     
<img width="638" alt="screen shot 2016-03-01 at 11 48 40" src="https://cloud.githubusercontent.com/assets/7038941/13424915/db9c22f0-dfa3-11e5-904f-7d8ec135de87.png">

**Comment by jordan-wright** [comment]
Awesome! I was going to mention port forwarding, but it looks like you got it knocked out.

Thanks for the update!
