### ISSUE TITLE
building from source fails on "github.com/mattn/go-sqlite3"

### ISSUE THREAD

**Issue by tabbyreyez** [gophish/gophish#1790]
What version of Gophish are you using?: 
Latest 

Brief description of the issue: 
I receive the following command during the first step. 

go get github.com/gophish/gophish
# github.com/mattn/go-sqlite3
gcc: error: spawn: No such file or directory

However if I manually try and access the other repos referenced in go.mod, I don't get an error.
For example:
go get github.com/NYTimes/gziphandler
I don't receive any error!

What are you expecting to see happen? :
For the command to work and build GoPhish.

My setup is:
OS: Windows 10
Go: version go1.14.1 windows/amd64
gcc: version gcc (GCC) 5.4.0

I have tried to build using both Cygwin and MinGW

What do I need to do to fix this issue?

**Comment by jordan-wright** [comment]
You will need to have `gcc` downloaded and available on your path. You should be able to get that via Cygwin and MinGW. The reason for this is that the go-sqlite3 package uses C bindings to talk to the underlying database.
