### ISSUE TITLE
Setting delay when send campaings

### ISSUE THREAD

**Issue by edrojas69** [gophish/gophish#1792]
What version of Gophish are you using?: 
-v0.9.0

Is there a way to setting a delay when i send a campaign ?.
because when you send a multiple emails with gophish, gsuite generate an error and close it the connection temporarily

Gsuite error:
```
421 4.7.0 Try again later, closing connection. (MAIL) bt19sm3062483pjb.3 - gsmtp
```
![error](https://user-images.githubusercontent.com/40746404/77478947-a32cd800-6dfd-11ea-9abe-242f5235a7f5.png)

**Comment by glennzw** [comment]
Yes, when you create a new campaign set the 'Send by' parameter:

![Screenshot 2020-03-25 at 11 11 58](https://user-images.githubusercontent.com/3966613/77530632-9229a880-6e89-11ea-89c4-80398c05a2d7.png)

You'll have to do the mental maths to figure out the spacing you want. e.g:

_A campaign has 1,000 emails, and I want them sent at 5 second intervals. I want it to start now (say 11am). Therefore, 11h00 + (1000 * 5) = 5,000 seconds, so I'd need to set a 'Send Emails By' of 12h23._

See my pull request for adding a feature to specify delay between emails: https://github.com/gophish/gophish/pull/1557

**Comment by edrojas69** [comment]
okay, I going to try this settings for my next campaigns,
Thanks you! :)
