### ISSUE TITLE
Trying to get the banner to change to an apple logo, local file

### ISSUE THREAD

**Issue by mbasilecgtc** [gophish/gophish#1794]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 8.0

Brief description of the issue: Changing the banner to apple background

What are you expecting to see happen? : i want the logon box to stay the same but the background to change to a jpeg file i have.

What are you seeing happen? Landing page

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
	<base href="https://www.citrix.com/login" /><script type="text/javascript">
			var webAppObj = {
				website:'conlogin'
			};
		</script><script language="Javascript" src="//www.citrix.com/static/prod/tagmanagement/conlogin/tagManagement.js"></script>
	<title>Chr0m4ll0y Login</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/><meta name="description" content="Citrix Consolidated Login"/><meta name="forSiteMonitoring" content="SEARCHSTR_CONSOLIDATEDLOGIN"/><meta content="width=device-width" name="viewport"/>
	<link href="https://www.citrix.com/etc/designs/citrix/icon-favicon.png" rel="icon" type="image/vnd.microsoft.icon" />
	<link href="https://www.citrix.com/etc/designs/citrix/icon-favicon.png" rel="shortcut icon" type="image/vnd.microsoft.icon" />
	<link href="//www.citrix.com/static/conlogin/prod/css/fonts.css" rel="stylesheet" type="text/css" />
	<link href="//www.citrix.com/static/conlogin/prod/base.css?ver=140513" media="screen" rel="stylesheet" type="text/css" />
	<link href="//www.citrix.com/static/conlogin/mobile/prod/base.css?ver=140513" media="handheld,only screen and (max-device-width:480px)" rel="stylesheet" type="text/css" />
</head>
<body class="standard" onload="document.loginForm.username.focus()">
<div id="container">
<div id="containerBanner">
<div id="containerBannerBackground">
<div id="containerLogin" style="width: 935px">
<div id="textLogin">Enter Apple ID and Password</div>

<div id="containerForm" style="width: 930px">
<form action="" method="post" name="loginForm"><input type="hidden" value="https://identity.citrix.com/Utility/STS/Sign-In" /> <input type="hidden" value="https://www.citrix.com/login/bridge?url=http%3A%2F%2Fsupport.citrix.com%2F" /> <input type="hidden" value="https://www.citrix.com/login?url=http%3A%2F%2Fsupport.citrix.com%2F&amp;err=y" /> <input type="hidden" value="1" />
<div id="containerUserName">
<div id="labelUserName">User name</div>

<div id="labelNeedAnAccount"><a href="" onclick="window.open('https://www.citrix.com/welcome/create-account.html','mywindow','width=760,height=600,toolbar=no,location=yes,status=no,menubar=no,scrollbars=yes,resizable=no'); return false;">&nbsp; </a></div>

<div><input class="inputText" id="username" type="text" value="" /></div>
</div>

<div class="clearBoth">&nbsp;</div>

<div id="containerPassword">
<div id="labelPassword">Password</div>

<div><input class="inputText" id="password" type="password" value="" /></div>
</div>

<div class="clearBoth">&nbsp;</div>

<div id="containerLoginButton"><input alt="Log In" id="loginbtn" type="submit" value="" />
<div id="labelCantAccessAccount">&nbsp;</div>
</div>
</form>

<div class="clearBoth">&nbsp;</div>
</div>
</div>
</div>
</div>

<div class="hLine">&nbsp;</div>

<div id="containerFooter">
<div class="hLine">&nbsp;</div>

<div class="hLine">&nbsp;</div>

<div class="hLine"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFIAAABGCAYAAABfa8MWAAACdElEQVR4nO3bvZHqQBAEYP0ANiSAg00GeBjkgkcIpIBDHGSBRQwkQBUFDiCt+llHASd07KpXs+hNV42JZuerlXQnRAQNJZH0AnynKApEUXQvX2k1ZJIkT4gKaZk8z38BKqRD3iH2ej1/Pb0dWSjvEH3uRqBlkHEcKyQjVYiHw8Fvb69HbzBViGma+u/vvUNDkTql7/0b6dJAJBGBFkNmWdZs/0a7ecxutxPtHyxknucYDodP/+Z1u12sViur41RdO4uioK03OMjr9Vo5/GPt9/tfnzfGfPx55nU0KEhbgJ/qdDqlDyhsKkmSemsnGdROHQRmOa+faOEcaTwGpjikNNpr2d7M7nOQXawyHo/F4RinNSAMKQ3HQgQEIZfLpTheKyCl4ZiIgEJiMplw5qEcxaVxAIis3QgIQW42G3HAVkD+9d2KQn7aNABAhVTIh6YBALYCcj6fiwO2AhIIZ1eWPRx2modyFMtUveT0rbvyv9+RURThfD7Xn4dg4tY4AEDmrhSDHAwG4nivlee58zxikFmWicOV1Xa7dZpHH+yWVBzHMMbYzeLJ6KP0+31xtHd1u92sZtEvv96U9RwebKySpqk42mvNZjPrOcQhQ7zpuEQcEij/PYxUjUYjpxmCgATCuVY6r59oUSuLxUIc0fZO/ZhgIAH5XVlr7SQDWr4REQgQUuIuzkhwkABwuVwaQ2S9tB8kJAAcj8c/EZIkwel0enoX3BiD9XrdKCIQMORPyv7GnE6nH3329Ufv7NP5McFDfksUkhSFJEUhSVFIUhSSFIUkRSFJUUhSFJIUhSRFIUlRSFIUkhSFJEUhSVFIUhSSFIUk5R/0oAdwZMpW3QAAAABJRU5ErkJggg==" /></div>
</div>
</div>
<script type="text/javascript">
			if (typeof _satellite != "undefined") {
    			_satellite.pageBottom();
			}
		</script><script type="text/javascript">
			const SAVO_LINK = "https://citrix.savolab6.com";

			function readCookie(name) {
				var nameEQ = name + "=";
				var ca = document.cookie.split(';');
				for (var i = 0; i < ca.length; i++) {
					var c = ca[i];
					while (c.charAt(0) == ' ') c = c.substring(1, c.length);
					if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length, c.length);
				}
				return null;
			}
			parent.postMessage(readCookie('MyCitrixHash'), SAVO_LINK);
		</script></body>
</html>

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 - 

If you unzip both items in the zip file below to the same location, and open up the code1.html in internet explorer or something, that is how we would like it to work. The code above is something i've been using and modifying to try and get apple logo in the background instead of the blue banner, but preferred logon page would be in the zip file below if you can be of any assistance. I greatly appreciate it! 

[Code1.zip](https://github.com/gophish/gophish/files/4381418/Code1.zip)

**Comment by jordan-wright** [comment]
This sounds like an issue with the landing page you’re trying to modify, not an issue with GitHub itself. I’m afraid we don’t offer support building the actual HTML of a landing page unless it directly impacts the behavior of Gophish.

Sorry we can’t be of more help!
