### ISSUE TITLE
some settings in cloning site and x-mailer

### ISSUE THREAD

**Issue by edrojas69** [gophish/gophish#1795]
**What version of Gophish are you using?:** 
 v0.9.0

**Issue Description:**
I use gophish in a Red Team Training to send a massive campaigns, in a controlled environment, and i see the next things in the process to clone a website and when i send a mail

**Cloning website:**
Some website have a configuration they not permit to clone site or not allow to access the site when the User Agent is different the common user-agent of typical browsers, in this case, is some way to do a random-agent options for cloning sites?...
![photo_2020-03-26_14-18-51](https://user-images.githubusercontent.com/40746404/77676199-bf02bc00-6f6c-11ea-80c2-66fb96a8b633.jpg)

**Sending mail:**
When i send a campaigns, some ANTI-SPAM IP or IDS filters, they block me.., because the X-MAILER say gophish and the filter send the mail to SPAM, my ask is… can I configure by myself the X-MAILER or eliminate de X-MAILER?
![photo_2020-03-26_14-18-55](https://user-images.githubusercontent.com/40746404/77676253-d641a980-6f6c-11ea-8d38-2b739132fc2d.jpg)

![photo_2020-03-26_14-18-56](https://user-images.githubusercontent.com/40746404/77676262-d9d53080-6f6c-11ea-938a-81103e4312f5.jpg)

I hope you can help me with this, ty!

:)

**Comment by jordan-wright** [comment]
Hi there!

You can override the `X-Mailer` settings in your Sending Profile with a custom header. Changing the outbound user agent is something we don't support via configuration so you'll need to modify Gophish and build from source.
