### ISSUE TITLE
error read tcp 127.0.0.1:3333 -> 127.0.0.1:50073: i/o timeout

### ISSUE THREAD

**Issue by JunPham** [gophish/gophish#1800]

**Comment by JunPham** [comment]
I'm use Windows 8.1 64bit.
I have not changed any settings yet.
![image](https://user-images.githubusercontent.com/42670522/77838106-ab0eb400-713e-11ea-8c5c-1ad00fdd7ba9.png)
![image](https://user-images.githubusercontent.com/42670522/77838109-b235c200-713e-11ea-9460-623832e08aed.png)

**Comment by S0larflare** [comment]
You’re accessing a https site over http. Go to. Https://127.0.0.1:3333
