### ISSUE TITLE
Feature Request: Manually mark e-mails as reported

### ISSUE THREAD

**Issue by TheGroundZero** [gophish/gophish#1802]
I noticed there are a few topics/issues open here re. the ability to have a user flag/report a phishing e-mail.  
This seems to work by using a `/report?rid=xxx` url or by linking a support mailbox to GoPhish.  
cfr. #1479 

However, I was wondering whether it'd be possible to add a button to the Campaign Dashboard next to each entry to manually mark that someone did report the phishing e-mail?
This could perhaps be a toggle switch next to or instead of the `x` to maybe even _unflag_ an entry as reported?

![image](https://user-images.githubusercontent.com/2406013/78138894-ee5f7000-7427-11ea-9a48-0d2476029171.png)

**Comment by jordan-wright** [comment]
Hi there!

A short term solution to this was merged back in #1772. It will be included in the next release.
