### ISSUE TITLE
Chrome flagging URL as phishing 

### ISSUE THREAD

**Issue by ghost** [gophish/gophish#1803]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.9.0
Brief description of the issue: 

Google has flagged the gophish endpoint as phishing, this means when users click the link in the mail they are meet with a warning page in all red. Haven't seen anyone with a similar issue, so I was wondering if anyone else had any experience with this or any tips? I am a afraid the only option is to turn off safe browsing across all clients using chrome. 
https://transparencyreport.google.com/safe-browsing/.

What are you expecting to see happen? :

User click link and are redirected to landing page.

What are you seeing happen?

Google warning page "This is a phishing URL"

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by horllste** [comment]
this is not an issue

**Comment by jordan-wright** [comment]
There are many reasons why Chrome would flag a URL as phishing, especially if you're copying a pre-existing landing page (this is a good thing! Chrome is doing its job well).

I'm afraid there is nothing we can do in Gophish to change what Google does.
