### ISSUE TITLE
Webhook not returning the campaign id

### ISSUE THREAD

**Issue by shahin-raza** [gophish/gophish#1805]
**Webhook data issue ** 
I have upgraded the gophish 0.7 to 0.9. I have setup the webhook, getting the events data but campaign_id is missing in the alert data. Can anyone help me for this.

I am getting the below data in alert:
{"email":"xyz@mail.com","time":"2020-04-06T06:32:46.929643003Z","message":"Email Sent","details":""}

**Comment by jordan-wright** [comment]
This was fixed in 3d525525ea4ff9fc99d42b077653b09e4e6a43d8 but hasn't been included in a release. I don't have an ETA on a new release other than to say it'll come out soon.
