### ISSUE TITLE
Utility for copying templates, pages, sending profiles

### ISSUE THREAD

**Issue by glennzw** [gophish/gophish#1806]
(This isn't an issue, maybe I should put this somewhere else?)
<hr>

I know there are plans for advanced RBAC features in the future, such as templates etc that are 'global', but in the meantime I built a tiny utility to copy templates, pages, and sending profiles between different user accounts. You can find it here: https://github.com/glennzw/phishPaste

Example usage:
```
$ ./phishpaste --list-users
[+] Connecting to gophish.db (set $DATABASE_URL to use MySQL)
[+] Available users: 
	admin
	bobby
```
 
Let's copy all items from `admin` to `bobby`:

```
$ ./phishpaste --source admin --destination bobby --sending-profiles --email-templates --landing-pages 
[+] Connecting to gophish.db (set $DATABASE_URL to use MySQL)
[+] Copying 8 Landing Pages from 'admin' to 'bobby'
	✅ SimpleCreds 
	✅ HMRC 
	✅ Update Email Password 
	✅ Facebook 
	✅ Employee Evaluation 
	❌ Dropbox (destination user already has page of the same name) 
	✅ Antivirus Update 
	✅ Copy of Update Email Password 
[+] Copying 9 Email Templates from 'admin' to 'bobby'...
	✅ Template01 
	✅ HMRC 
	✅ Update Email Password 
	✅ MLTest01 
	✅ Facebook 
	✅ Employee Evaluation 
	❌ Dropbox (destination user already has template of the same name) 
	✅ Antivirus Update 
	✅ asriznet-test 
[+] Copying 9 Sending Profiles from 'admin' to 'bobby'...
	✅ SendGrid 
	✅ Mailslurp 
	✅ HMRC 
	✅ Update Email Password 
	✅ Facebook 
	✅ Employee Evaluation 
	❌ Dropbox (destination user already has sending profile of the same name) 
	✅ Antivirus Update 
	✅ Mailhog 

```

Note: If a destination item exists with the same name it's skipped (as you can see in the above output).

In the future I'll add the ability to do this between different databases too.

**Comment by jordan-wright** [comment]
Thanks for sending this over @glennzw! I've added it to our docs here https://docs.getgophish.com/user-guide/additional-references#tools.

(Note: It might take a few mins for it to show up.)
