### ISSUE TITLE
Proofpoint Automatically Flags Emails Based on the X-Mailer Header

### ISSUE THREAD

**Issue by gobiasinfosec** [gophish/gophish#1807]
As noted in the title Proofpoint is flagging emails from GoPhish based on the X-Mailer Header. This has happened on multiple client engagements even with the domain being whitelisted. 

Please add a feature that allows this to be changed for the entire software suite (not just adding a blank header to each individual campaign) without re-compiling the binary.

**Comment by jordan-wright** [comment]
You can set your own `X-Mailer` attribute in the Sending Profile settings, which will overwrite the built in one.
