### ISSUE TITLE
Office365 blocks the variables {{.URL}} and {{.Trackers}}.

### ISSUE THREAD

**Issue by gdelasaux** [gophish/gophish#1809]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

What version of Gophish are you using?:  v0.9.0

Brief description of the issue: 
Hi everybody,
I am currently running a phishing campaign on Office365 and I have a problem with receiving emails, when someone receives an email, this email is directly placed in the junk folder with an unwanted tag.

At first I thought it was coming from my SMTP server or from my gmail address used as SMTP relay, however after analysis it seems that the problem comes from the variables {{.URL}} and {{.tracker} since when I delete them from the content of the mail, the same mail arrives in the inbox. I think Office365 or the company I'm working for on this campaign is either blocking this kind of content or listing it directly as undesirable.

I would like to know if anyone here has ever encountered this problem and if so, have you found a solution? Can you explain it to me?

If someone has a solution other than changing the name of the variables in order not to be undesirable, I am willing to take it.

Thank you all in advance.

**Comment by glennzw** [comment]
Those variables are replaced before the mail hits the SMTP or receiving server, so they're being blocked because of the URL in use. You may need to increase the 'reputation' of the URL you're using, e.g:

- Don't use an IP, use a domain
- Set up TLS
- Host content that's not 'obviously' a phishing campaign (e.g. clone of FB would get  more easily blocked)
