### ISSUE TITLE
Landing Page HTML Not Structured Well

### ISSUE THREAD

**Issue by zoben10** [gophish/gophish#1810]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

**What version of Gophish are you using?:** Latest version

**Brief description of the issue:** Landing page malform when I copy my HTML code in the built-in HTML form in Gophish. But when I host my HTML code on my own server, the site is structured in a good way. 

**What are you expecting to see happen? :** Structure in my landing page

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by zoben10** [comment]
I cant post my HTML code here for privacy purpose. Thank you !

**Comment by glennzw** [comment]
If you can't share the HTML here we can't really help you.

**Comment by jordan-wright** [comment]
Agreed, without more information about the HTML that’s not structured correctly, there isn’t anything we can do to help.

**Comment by zoben10** [comment]
I found it, that I did a error. Everything is working perfectly now guys. GoPhish is awesome !
