### ISSUE TITLE
Error when running script:	Illegal Instruction. 

### ISSUE THREAD

**Issue by ListenHereDev** [gophish/gophish#1811]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.90.0

Brief description of the issue: Getting illegal instruction when running script. 

What are you expecting to see happen? : The ngrok link should output into the console. 

What are you seeing happen? An error: 
shellphish.sh: line 343: 16431 Illegal instruction     ./ngrok
http 127.0.0.1:3333 > /dev/null 2>&1
[*] Send this link to the Target:

[*] Or using tinyurl: http://tinyurl.com/yx7zk3hc (The tinyurl leads to a dead link) 
 

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
shellphish.sh: line 343: 16431 Illegal instruction     ./ngrok
http 127.0.0.1:3333 > /dev/null 2>&1
[*] Send this link to the Target:

[*] Or using tinyurl: http://tinyurl.com/yx7zk3hc

```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Install the latest ngrok
 * Step 2 -  Run the program and select Google.

**Comment by glennzw** [comment]
You've come to the wrong project, this is Gophish not Shellphish. Try here:

https://github.com/thelinuxchoice/shellphish
