### ISSUE TITLE
Not able to get to the landing page

### ISSUE THREAD

**Issue by nickdtong** [gophish/gophish#1814]
(https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.9

Brief description of the issue: Able to run the campaign and send emails, but can't seem to connect to anything except for the admin panel.

What are you expecting to see happen? : To be able to access the landing page

What are you seeing happen? I get the error 
This site can’t be reached (I'm using the netflix page as testing, but I plan to create a different page later)

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html

```

I'm using the default configuration listed below

```
{
	"admin_server": {
		"listen_url": "127.0.0.1:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "gophish_admin.key"
	},
	"phish_server": {
		"listen_url": "0.0.0.0:80",
		"use_tls": false,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": "",
	"logging": {
		"filename": "",
		"level": ""
	}
}

```

Please provide as many steps as you can to reproduce the problem:
  Step 1 - Set up a VPS on DigitalOcean and had it pull from gophish/gophish. I then ran it.
  Step 2 - Changed the settings on the firewall to allow HTTP, HTTPS, and 3333 ports
 Step 3 - Built everything, and got the email to send fine but wasn't able to get the listener or page working

**Comment by jordan-wright** [comment]
Hi there!

This is likely either a firewall issue or, more likely, a permissions issue. You'll want to make sure your user has the ability to run Gophish and have it bind to the privileged port. This can be done with `sudo` or [setcap](https://superuser.com/questions/710253/allow-non-root-process-to-bind-to-port-80-and-443).

I hope this helps! Let us know if you continue to run into issues and we can re-open to continue troubleshooting.
