### ISSUE TITLE
Error with gophish: Max connection attempts exceeded - 454 4.7.0 auth service unavailable

### ISSUE THREAD

**Issue by fkay9000** [gophish/gophish#1815]
I just tried out gophish for the first time and got max connection attempts exceeded - 454 4.7.0 auth service unavailable.
I am using the latest version of gophish 0.9.0 and less secure apps are turned on.

**Comment by jordan-wright** [comment]
This is an error received by the smtp server. You’ll need to review the logs there and determine why authentication is failing.

Im afraid there isn’t anything in Gophish we can do to address this.

**Comment by fkay9000** [comment]
How do I review the logs?

**Comment by fkay9000** [comment]
Okay I will review the logs. I will show on here if I see anything that I need help with
