### ISSUE TITLE
Microsoft 365 Default SMTP Behavior Change

### ISSUE THREAD

**Issue by staxmood** [gophish/gophish#1818]
What version of Gophish are you using?: 0.9.0

Brief description of the issue: Request for update of documentation - no issues

What are you expecting to see happen? : a successful SMTP test

What are you seeing happen? : An error related to authentication

Dusted off my azure instance of gophish today to setup a new campaign. Went through my normal process of acquiring a target domain and setting up an email account under that domain.
My issue came when i tried a test email inside of gophish, errors started coming out even though my sending profile was copied from a personal template.
Spent a few hours trying to diagnose the situation and even updated gophish versions from 7 to 9.
It wasn't till i learned that now by default, Microsoft O365 has enabled "Security Defaults" for new domains. This in turn disabled the ability for Simple AUTH of SMTP.

Just wanted to leave this page for people that may find the same issue with these two Microsoft links. They helped me get back up and sending emails without errors. Also didn't know if this SMTP AUTH work around needed to be inside of any documentation for gophish.

Thanks for the great tool!

Connect to Exchange Online PowerShell: https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell?view=exchange-ps

Enable or disable authenticated client SMTP submission (SMTP AUTH) in Exchange Online: https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission

**Comment by jordan-wright** [comment]
Thank you for taking the time to send this in! Glad to see you were able to find a workaround.

**Comment by KINGSABRI** [comment]
For the quick start, 
1. go to your office 365 admin panel 
2. click Azure Active Directory
![image](https://user-images.githubusercontent.com/1071827/120113401-02654580-c183-11eb-89f4-bc99e86b80e6.png)

3. Once Azure AD opens, under _Manage_, click **Properties**,
4. To to the bottom of the page and click **Manage Security defaults**

![image](https://user-images.githubusercontent.com/1071827/120113525-8cada980-c183-11eb-8228-4bfbd7259f06.png)
