### ISSUE TITLE
From header not working properly

### ISSUE THREAD

**Issue by kontez** [gophish/gophish#182]
I apologize for opening lots of issues in the past few days.
These are my SMTP options:
<img width="774" alt="screen shot 2016-03-01 at 13 39 47" src="https://cloud.githubusercontent.com/assets/7038941/13427315/7381b4f4-dfb3-11e5-8941-77b930247afd.png">

However the From header doesn't seem to work properly as shown here:
<img width="321" alt="screen shot 2016-03-01 at 13 32 08" src="https://cloud.githubusercontent.com/assets/7038941/13427325/8b1e1dd2-dfb3-11e5-89b8-ad272e0696d9.png">

I checked the source and the From header is not modified, only the X-Google-Original-From is. 
I think this is a problem from Google trying to avoid spam mails.
Here the header:
```
From: Spider Man <totallyprivatemail@gmail.com>
X-Google-Original-From: Spider Man <spiderman@spiderman.com>
```

**Comment by kontez** [comment]
Found the workaround, if you use this as host you don't need to authenticate :)
`aspmx.l.google.com:25`

**Comment by jordan-wright** [comment]
Correct. You'll notice that you authenticate to google with your gmail account. It uses that as the From address to avoid spoofing from its addresses.

Glad to hear you were able to get around the issue! Thanks for the update!

**Comment by sylcvqnr** [comment]
Is this SMTP Options page the same page for Sending Profile?

**Comment by jordan-wright** [comment]
What do you mean the "SMTP Options page"? What setting are you looking to configure?

**Comment by sylcvqnr** [comment]
I did find this popup https://cloud.githubusercontent.com/assets/7038941/13427315/7381b4f4-dfb3-11e5-8941-77b930247afd.png
The closiest I finded was "Sending Profile"

**Comment by jordan-wright** [comment]
What is it you're trying to do? What version of gophish are you on?

Old versions of gophish had you configure SMTP options when making a campaign. New versions let you save SMTP information in SMTP profiles.

**Comment by ankitbhatia32** [comment]
Hi I tried using the workaround. Without authentication I am able to spoof the email address but the emails are going in the Spam folder (which is not what I or anyone desire to be the outcome). Any solution to this?
Btw, nice tool to work on. It has been fun working on it.

**Comment by voilaviola** [comment]
Hi, thanks a lot for the walk around solution. However I think my ISP is blocking the port 25 so both gmail-smtp-in.l.google.com:25 and aspmx.l.google.com:25 don't work for me. I get "Host unreachable" if I telnet to them. 
With "From" field set to "Test Account <test.account@xxx.com>" <test.account@xxx.com>, google detects the spoof and blocked my gmail X(
