### ISSUE TITLE
Send Test Email

### ISSUE THREAD

**Issue by BRMunro** [gophish/gophish#1822]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue: 

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by BRMunro** [comment]
Hi there, I'm attempting to set up my sending profile and keep getting: Max connection attempts exceeded - 535 5.7.3 Authentication unsuccessful [SG2PR04CA0150.apcprd04.prod.outlook.com]

Is there any help or advice you could give at all? 

TYIA

**Comment by RevolutionUK** [comment]
Hi there, unfortuantely I dont have a solutio but..

Brief description of the issue: I'm receiving the same error whilst attempting to send an email via outlook/o365. Max connection attempts exceeded - 535 5.7.3 Authentication unsuccessful [DB8PR09CA0033.eurprd09.prod.outlook.com]

What are you expecting to see happen? : I get a test email from the o365 account to my account

What are you seeing happen?: Seems like it tries to connect to o365 and then just gives too many connections and auth error. double check creds and they're working fine.

What version of Gophish are you using?: The latest Ubuntu release gophish-v0.9.0-linux-64bit.zip

**Comment by smackqc** [comment]
We ran into the same issue recently when creating a new Office 365 account.

The problem: SMTP AUTH is now **disabled** by default on new Office 365 accounts.

The workaround (not a fix as not necessarily secure): Enable SMTP AUTH for the Office 365 account.

Background Information: [Enable or disable authenticated client SMTP submission (SMTP AUTH) in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission)

Steps:

- Open powershell as admin (** make sure your connection (wifi/cable) is set to private (not public))

```
Set-ExecutionPolicy RemoteSigned
winrm quickconfig
winrm get winrm/config/client/auth
```

- Connect to office 365

```
$UserCredential = Get-Credential
#this opens a box, fill in the login details
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $UserCredential -Authentication Basic -AllowRedirection
# start the sesssion
Import-PSSession $Session -DisableNameChecking
```

- Enable SMTP AUTH
```
Set-CASMailbox -Identity sean@contoso.com -SmtpClientAuthenticationDisabled $false
# Check it worked
Get-CASMailbox -Identity <MailboxIdentity>  | Format-List SmtpClientAuthenticationDisabled
# Close the session before leaving!!
Remove-PSSession $Session
 ```

**Comment by jordan-wright** [comment]
Excellent, thanks @smackqc! I had seen around that folks besides just Gophish users were encountering issues using SMTP so this makes sense.

Since there is a workaround, I’m going to go ahead and close this out.

**Comment by mrpaddy35** [comment]
i made all of these settings, but i am still not able to send email from gophish, is closing the session necessary command here ?
