### ISSUE TITLE
Max connection attempts exceeded - x509: certificate is valid for localhost.localdomain, not xxxdomain.com:25

### ISSUE THREAD

**Issue by mbroekema61** [gophish/gophish#1823]
What version of Gophish are you using?: 0.9

Brief description of the issue: X509 certificate error on sending test-email and running campaigns

What are you expecting to see happen? :results without errors

What are you seeing happen? message not sent due to these errors

Error on GUI while sending testmail:
Max connection attempts exceeded - x509: certificate is valid for localhost.localdomain, not xxxdomain.com:25

Please provide any terminal output that may be relevant below:
On Ubuntu 18 with tail -f /var/log/maillog:
 warning: TLS library problem: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:../ssl/record/rec_layer_s3.c:1528:SSL a

Errors with starting campaigns: aller mails gave this error:
Max connection attempts exceeded - x509: certificate is valid for localhost.localdomain, not xxxdomain.com:25

I have changed these lines in main.cf of my postfix config and the problems are gone but mail is sent unencrypted:

#smtpd_tls_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
smtpd_tls_cert_file=none
#smtpd_tls_security_level = may
smtpd_tls_security_level = none
#smtp_tls_security_level = may
smtp_tls_security_level = none

I'me using a 18 Ubuntu server wiht Plesk 18.x

**Comment by mbroekema61** [comment]
BTW, i'me using the Lets Encrypt addon on plesk to get my certificates...

**Comment by glennzw** [comment]
The error is fairly straight forward; your cert does not match the domain. Guess you could generate an appropriate cert, or tick the option to allow insecure certs.

![Screenshot 2020-05-05 at 11 10 38](https://user-images.githubusercontent.com/3966613/81055686-1af02700-8ec1-11ea-824d-93b57842c0d4.png)
