### ISSUE TITLE
No response when creating Email Templates, landing pages, and Campaigns

### ISSUE THREAD

**Issue by atheriqbal** [gophish/gophish#1826]
What version of Gophish are you using?
 0.80

Brief description of the issue:  
I have gophish running on Ubuntu 18.04. This was working fine a few days back, but today I am getting this issue. Whenever I click on New Email Template, enter all the information, and click submit, the browser just hangs. This happens when creating new landing pages and campaigns too. 
There is nothing much in the log, but the browser shows the errors which are attached. I have used Chrome and Firefox, and have already restarted the server. Wierd, that I can make user groups like before. 

 Any help in this regard would be helpful. 
Thanks
![image](https://user-images.githubusercontent.com/23431134/80648109-0529ce80-8a89-11ea-873f-3d0cf846972e.png)

**Comment by jordan-wright** [comment]
What do you see in the network tab when you attempt to make the request? What does the request/response look like?

**Comment by atheriqbal** [comment]
There was nothing useful in the network tab. I am making a connection to another server from gophish, and in the log I saw some lines related to connectivity. 
Once I fixed the connectivity, this was also resolved. 
Though, creating templates and landing pages had no relation to my connectivity. 

Thank you @jordan-wright anyways!
