### ISSUE TITLE
No option to Create Sending Profile

### ISSUE THREAD

**Issue by dambuster43** [gophish/gophish#183]
I have tried following the docs, page 17,but there doesn't seem to be an option for creating the Sending Profile.
![screen shot 2016-03-01 at 18 10 33](https://cloud.githubusercontent.com/assets/2886978/13436819/f82ef8f4-dfd8-11e5-84d5-040f39b00701.png)

**Comment by jordan-wright** [comment]
Hey there! Thanks for the report!

You actually caught us right when we're transitioning to the new release, which contains the sending profiles. We are finishing up documentation and building the binaries. It should be released around Thursday.

For now, you can build from source, or you can still configure your SMTP settings when building a campaign.

Hope this helps! Get hyped for the next release- it's awesome.

**Comment by dambuster43** [comment]
Awesome! Great job so far guys. Thanks for letting me know.  
 
  On Tue, 1 Mar, 2016 at 18:19, Jordan Wright<notifications@github.com> wrote:   Hey there! Thanks for the report!

You actually caught us right when we're transitioning to the new release, which contains the sending profiles. We are finishing up documentation and building the binaries. It should be released around Thursday.

For now, you can build from source, or you can still configure your SMTP settings when building a campaign.

Hope this helps! Get hyped for the next release- it's awesome.
