### ISSUE TITLE
How to host landing page externally using wamp ?

### ISSUE THREAD

**Issue by sparrowmp5** [gophish/gophish#1832]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: latest

Brief description of the issue: i want to host a gopish landing page and be accessible from the outside of the local host 

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by horllste** [comment]
get a vps

**Comment by jordan-wright** [comment]
You need to ensure that networking is set up so that users receiving emails can reach your server. Many people purchase a VPS to host Gophish.
