### ISSUE TITLE
Upgrade File Custom Code Overwrite Question

### ISSUE THREAD

**Issue by riab-tam** [gophish/gophish#1837]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.7.1

Brief description of the issue: Hi. I would like to upgrade to the latest version (0.9.0) via the directions from https://github.com/gophish/gophish/releases to get the latest updates, more specifically, to take advantage of the disabling of TLS 1.0 and 1.1 from update https://github.com/gophish/gophish/commit/79e680e67587848da20964b2173e95e12c4d0a7f

Before doing that, we have modified the default phishing server landing page to be a custom HTML page via the PhishHandler function in the controllers/phish.go file, as well as normal custom changes to the config.json file and additions to the static directory. If we follow the directions from the release page, will any custom changes we made to the controllers/phish.go file be overwritten?

Thanks.

What are you expecting to see happen? : Hopefully, all custom settings in the config.json file, files added to the static directory, and custom changes to the controllers/phish.go file remain.

What are you seeing happen? N/A

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi there,

It’s quite possible that phish.go was modified in the latest release so you might have merge conflicts you’ll need to resolve. That said, I’m afraid the support we can offer in this case is awfully limited, since these are custom code changes outside of the main Gophish release.

My recommendation would be to make backups of everything before attempting to update so that you can handle merge conflicts as needed, but can always roll back if things go wrong.
