### ISSUE TITLE
Use more consistent verbiage for sending interfaces

### ISSUE THREAD

**Issue by wjwoodson** [gophish/gophish#184]
A good portion of API and internal functions are implemented as 'SMTP', but gui calls this sending interface. Standardize to something both flexible enough to handle future mail senders + be intuitive for API users and maintainers.

**Comment by jordan-wright** [comment]
Yep! I imagine a button on the timeline that allows you to resend to a specific user. It can be a special API endpoint, like /campaign/:id/resend that takes in a campaign result object.

**Comment by jordan-wright** [comment]
I personally like SMTP better. It's shorter and will cover a majority of the cases. But, I'm open to a better term if we find one!

**Comment by jordan-wright** [comment]
I think we're good to close this for now @wjwoodson - SMTP will work for our purposes, even when we add API providers. 

The hardest part will be to create the actual programmatic interfaces needed to handle other senders, which is something I'm putting on the back burner for more high priority items. That's future gophish maintainers' problem :smile:
