### ISSUE TITLE
Python Script to integrate gophish with LDAP 

### ISSUE THREAD

**Issue by md-howsa** [gophish/gophish#1840]
What version of Gophish are you using?:   v0.9.0
Brief description of the issue: 

This is a python script I made to import users directly from Active directory via LDAP. It can retrieve as many users as you want. 

Script is available here: https://github.com/md-howsa/GoLDAP

I wish if the framework author Mr. jordan wright can embed it in future versions and make it easy to configure in the front end of gophish.

I will be more than happy to contribute more. 

Thanks for the great framework.

**Comment by jordan-wright** [comment]
Hi @md-howsa,

Thanks for sending this in! I don't plan to embed external tools into Gophish at this time, but I've added a link to the script in the ["Additional References"](https://docs.getgophish.com/user-guide/additional-references#tools) section of our documentation.

Keep up the great work! 🎊

**Comment by adonix-dev** [comment]
Same with batch script ;)
[https://github.com/gophish/gophish/issues/1173#issuecomment-717297476](url)
