### ISSUE TITLE
Error fetching IMAP settings

### ISSUE THREAD

**Issue by samf63** [gophish/gophish#1841]
What version of Gophish are you using?: 
v0.9.0
MySQL: 5.7.30
Windows server 12

Hi, 

We're having trouble saving IMAP settings within account settings >> reporting settings. The error "error fetching IMAP settings" is displayed. Also unable to save any new settings in there - same error appears and anything entered is wiped. 

Any suggestions for what to try? 

I can provide any further details if needed.

**Comment by glennzw** [comment]
Hi @samf63,

What browser are you using? Could you try Chrome if you're not already. Also, when you get these error messages are there any messages in the Gophish console?

I haven't tried deploying on Win server 12 + MSSQL, so it might be you've uncovered an edge case bug.

Also, could you try use sqlite and see if that works? That'll help narrow things down.

Glenn

**Comment by glennzw** [comment]
I haven't heard back so I'm going to close this. Feel free to re-open if the problem persists and you have some more info.
