### ISSUE TITLE
Unable to Start Gophish v0.9

### ISSUE THREAD

**Issue by cyberocean** [gophish/gophish#1842]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: v0.9

Brief description of the issue: I just downloaded Gophish for Linux but unsuccessful when trying to run it. I'm not able to access the admin server

What are you expecting to see happen? : Have Gophish execute successfully

What are you seeing happen? "This site cannot be reached"

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
root@localhost:~/Phishing Trip# ./gophish
time="2020-05-20T13:38:26Z" level=warning msg="No contact address has been configured."
time="2020-05-20T13:38:26Z" level=warning msg="Please consider adding a contact_address entry in your config.json"
goose: no migrations to run. current version: 20200116000000
time="2020-05-20T13:38:26Z" level=info msg="Starting admin server at https://127.0.0.1:3333"
time="2020-05-20T13:38:26Z" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
time="2020-05-20T13:38:26Z" level=info msg="Starting phishing server at http://0.0.0.0:80"
time="2020-05-20T13:38:26Z" level=info msg="Starting IMAP monitor manager"
time="2020-05-20T13:38:26Z" level=info msg="Starting new IMAP monitor for user admin"
```

Please provide as many steps as you can to reproduce the problem:
Step 1 - Download/Unzipped Gophish
Step 2 - Tried to start Gophish by typing "./gophish"
Step 3 - I receive "This site cannot be reached" error message when trying to connect to https://127.0.0.1:3333

**Comment by glennzw** [comment]
Try running `netstat -pant` on the Linux box, and paste the output here. That'll tell you what's listening on what ports.

From the logs it looks like it started up fine.

**Comment by cyberocean** [comment]
> Try running `netstat -pant` on the Linux box, and paste the output here. That'll tell you what's listening on what ports.
> 
> From the logs it looks like it started up fine.

Thank you for the comment @glennzw this is the output:


```
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:3333          0.0.0.0:*               LISTEN      917/./gophish
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      478/systemd-resolve
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      633/sshd
tcp        0    464 45.56.112.42:22         207.81.242.20:53302     ESTABLISHED 727/sshd: root@pts/
tcp6       0      0 :::80                   :::*                    LISTEN      917/./gophish
tcp6       0      0 :::22                   :::*                    LISTEN      633/sshd


```

**Comment by glennzw** [comment]
It's definitely listening on `127.0.0.1:3333`

Try hit it from the command line:

`curl -k https://127.0.0.1:3333`

You should get:

```
<a href="/login?next=%2F">Temporary Redirect</a>.
```

**Comment by cyberocean** [comment]
> It's definitely listening on `127.0.0.1:3333`
> 
> Try hit it from the command line:
> 
> `curl -k https://127.0.0.1:3333`
> 
> You should get:
> 
> ```
> <a href="/login?next=%2F">Temporary Redirect</a>.
> ```

I just tried the command and received the same output. However, I'm still getting a timeout error.

**Comment by glennzw** [comment]
Is this machine hosted or local? ie are you opening the browser on the same machine you're running Gophish on?

**Comment by cyberocean** [comment]
Seems like I fixed my issue. I just reinstalled gophish and it works perfectly now.

**Comment by glennzw** [comment]
Code for "it was running on a remote server" ;-)

Glad it's up and running.
