### ISSUE TITLE
Error 1292: Incorrect datetime value: '0000-00-00' for column 'send_by_date' at row 1 

### ISSUE THREAD

**Issue by UBPClaw** [gophish/gophish#1845]
What version of Gophish are you using?: 0.9

Brief description of the issue: On a new CentOS 8 box with mysql 8 Im getting Error 1292: Incorrect datetime value: '0000-00-00' for column 'send_by_date' at row 1 when creating a new campaign. I have followed the documentation and edited the my.cnf file to remove the NO_ZERO_IN_DATE and NO_ZERO_DATE modes then restarted both mysql and gophish but am still getting the error

**Comment by mitprasoon** [comment]
First get the sql mode by `SELECT @@sql_mode;`

remove  NO_ZERO_IN_DATE and NO_ZERO_DATE and then reset the GLOBAL sql_mode
`set GLOBAL sql_mode='SOMETHING'`;  //remove NO_ZERO_IN_DATE and NO_ZERO_DATE

**Comment by UBPClaw** [comment]
> First get the sql mode by `SELECT @@sql_mode;`
> 
> remove NO_ZERO_IN_DATE and NO_ZERO_DATE and then reset the GLOBAL sql_mode
> `set GLOBAL sql_mode='SOMETHING'`; //remove NO_ZERO_IN_DATE and NO_ZERO_DATE

That worked, thank you
