### ISSUE TITLE
help to update gophish

### ISSUE THREAD

**Issue by Cre4t1v3-h4ck3r** [gophish/gophish#1849]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue:  i need a how to update video.. 

What are you expecting to see happen? :

What are you seeing happen? no campaign results r reflecting in gophish

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi there!

All our documentation can be found at https://getgophish.com/documentation/.

Additionally, we have upgrade instructions at the bottom of our release notes for every release. The high level process is:

* Make a backup of your database
* Download the new release
* Copy your config.json
* Run the new binary

We don’t have plans to make a video at this time. If you run into errors during an upgrade, please file an issue with all the details and we can help troubleshoot.
