### ISSUE TITLE
Attachment send multiple times

### ISSUE THREAD

**Issue by toonswyzen** [gophish/gophish#185]
When I have 3 users in my users list the:
* first users gets 1x the attachment (as it should be)
* second user gets 2x the attachment
* third user gets 3x the attachment

Any thoughts ?

**Comment by jordan-wright** [comment]
Interesting... That's definitely not supposed to happen. Let me check our implementation and see if I can reproduce the issue. If so, I'll track it down.

Thanks for the report!

**Comment by jordan-wright** [comment]
Alright, should be good to go. Mind validating on your end?

**Comment by toonswyzen** [comment]
It is indeed fixed, thanks!
