### ISSUE TITLE
 Intentos de conexión máxima excedidos - marque tcp 40.97.154.82:587: tiempo de espera de E / S

### ISSUE THREAD

**Issue by rber96** [gophish/gophish#1850]
Saludos cordiales , anteriomente la herramienta no me presentaba este problema ,ay alguna solucion para  esto , su ayuda por favor .

**Comment by jordan-wright** [comment]
Lo siento, mi español es limitado, así que estoy usando Google Translate.

Un tiempo de espera de E / S sugiere que hay un firewall que bloquea la conexión o algún otro bloqueo de red / servidor.

Algunos servidores de correo bloquean las conexiones para evitar el spam. De lo contrario, podría ser un problema de red.

De cualquier manera, me temo que no hay nada que podamos hacer en Gophish para ayudar a prevenir este problema.

**Comment by jordan-wright** [comment]
Cerrando esto ya que no ha habido actualizaciones en una semana.

¡Gracias por ponerte en contacto!
