### ISSUE TITLE
Sender Mask

### ISSUE THREAD

**Issue by mdkzera** [gophish/gophish#1854]
What version of Gophish are you using?: 
v0.9.0
Brief description of the issue: 
I'm managing to create the campaigns, I can mask the outgoing email? example subject@linkedin.com

What are you expecting to see happen? :
Use my personal e-mail and and receive from another email

What are you seeing happen?
I can't find this option on the platform.

Thank you so much

**Comment by jordan-wright** [comment]
Hi there,

I believe what you're asking isn't possible. In the sending profile, we do have the "From" option, which is the "From:" header used to send emails. If that's not getting you the desired results, then I'm afraid there isn't much else we can do to help.
