### ISSUE TITLE
stucked at clicked link

### ISSUE THREAD

**Issue by siang92** [gophish/gophish#1856]
hi all, i just setup new gophish for testing. It went well for email sent and open, but seems stuck at clicked link. It doesn't detect the link opened as the email sent.
I can see email sent, and opened successfully , but no idea on the link clicked, even though both testing user already clicked.

Anyone can guide and idea on what happen ?

**Comment by jordan-wright** [comment]
Hi there,

I'd recommend you refer to our [FAQ](https://docs.getgophish.com/user-guide/faq#events-arent-showing-up-on-the-dashboard) which aims to cover this exact scenario. It will walk through troubleshooting steps to help track down the issue.

If these don't work, let us know exactly which part was failing and we can reopen this issue to continue troubleshooting. Please don't upload error reports as documents- instead, please just add the text and images to the issue.

Thank you!
