### ISSUE TITLE
Unable to login to outlook.office365.com

### ISSUE THREAD

**Issue by Shreyasinha1995** [gophish/gophish#1857]
Hi,

I am facing the issue in Gophish for Monitor an IMAP account for emails reported by users 

Accounting setting<Reporting setting. 

When i enter the detail of IMAP host: outlook.office365.com and port 993 it is giving me the error 'Unable to login to outlook.office365.com' and in more info 'imap: unexpected completion status ("EKXCH2 NO LOGIN failed.")'

Can some one help me to resolve the query

**Comment by Shreyasinha1995** [comment]
> Hi,
> 
> I am facing the issue in Gophish for Monitor an IMAP account for emails reported by users
> 
> Accounting setting<Reporting setting.
> 
> When i enter the detail of IMAP host: outlook.office365.com and port 993 it is giving me the error 'Unable to login to outlook.office365.com' and in more info 'imap: unexpected completion status ("EKXCH2 NO LOGIN failed.")'
> 
> Can some one help me to resolve the query

**Comment by glennzw** [comment]
Hi @Shreyasinha1995 - sorry you're having trouble with the IMAP login. I can confirm I get the same error when trying to login to `outlook.office365.com` on the current master branch.

The good news is that this issue doesn't seem to manifest in the new updated IMAP incarnation (https://github.com/gophish/gophish/pull/1791), which is currently in PR. If you can't wait for the merge, you can build it yourself: 

https://github.com/glennzw/gophish/tree/imap-update

![Screenshot 2020-06-08 at 12 02 47](https://user-images.githubusercontent.com/3966613/84023788-a3f6f400-a980-11ea-84da-92d1ca365c4d.png)

**Comment by suriyagk** [comment]
I am facing the same Issue any solutions for that, Please ping me

**Comment by glennzw** [comment]
@suriyagk You'll need to build from source with my `imap-update` branch:

```
git clone https://github.com/glennzw/gophish/tree/imap-update
cd gophish
go build
sudo ./gophish
```

**Comment by suriyagk** [comment]
I already have the same version of gophish but still I got this error

**Comment by glennzw** [comment]
Anyone in this thread still having issues please try and build from the new master.

**Comment by kush-1277** [comment]
Could you recommend a safe way where I could update my current installation, I have saved a lot of data and configuration in my current setup. I just installed it couple of weeks back, and I am facing the same issues.

**Comment by kush-1277** [comment]
> Could you recommend a safe way where I could update my current installation, I have saved a lot of data and configuration in my current setup. I just installed it couple of weeks back, and I am facing the same issues.
> 
> Thanks in advance @glennzw

Hey, got it Working! Just downloaded the master folder from here, and copied all of my certs, config files and DB files in the new folder which made it work!

Thanks a lot again!!!!

**Comment by glennzw** [comment]
Great stuff, nice work @kush-1277

**Comment by jordan-wright** [comment]
Closing since the changes from @glennzw have been live in the `master` branch for some time. If y'all are still running into IMAP issues after a new release is created, please don't hesitate to let us know.
