### ISSUE TITLE
Clicked link not reflecting in dashboard

### ISSUE THREAD

**Issue by sathishkumarrajendran-integra** [gophish/gophish#1859]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.9.0
Brief description of the issue: 
I have successfully created landing page, email template, and campaigns , but when sending phish mail I am not able to get clicked link in my dashboard.
What are you expecting to see happen? :
I want to get report for clicked link 
What are you seeing happen?
Nothing error receiving it shows mail delivered and read successfully.
[Go_Phish_Error.docx](https://github.com/gophish/gophish/files/4730107/Go_Phish_Error.docx)

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:
No
```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi there,

I'd recommend you refer to our [FAQ](https://docs.getgophish.com/user-guide/faq#events-arent-showing-up-on-the-dashboard) which aims to cover this exact scenario. It will walk through troubleshooting steps to help track down the issue.

If these don't work, let us know exactly which part was failing and we can reopen this issue to continue troubleshooting. Please don't upload error reports as documents- instead, please just add the text and images to the issue.

Thank you!
