### ISSUE TITLE
gophish: ELF: not found

### ISSUE THREAD

**Issue by SumiGaeshi** [gophish/gophish#1861]
I'm new to Gophish and fairly new to linux. The gophish installation instructions say to extract the files then execute Gophish. It just results in errors (see below).

What version of Gophish are you using?: 0.10.1

Brief description of the issue: execute Gophish just results in errors (see below).

What are you expecting to see happen? : My expectations are fairly minimal

What are you seeing happen?see below

Please provide any terminal output that may be relevant below:
gophish: 1: gophish: ELF: not found
gophish: 1: gophish: ~�: not found
gophish: 2: gophish: ����ۆߚ�԰b: not found
gophish: 2: gophish: @21@@@@@0pp@p@@@�e��e�: not found
gophish: 4: gophish: �@: not found
gophish: 1: gophish: Syntax error: Unterminated quoted string

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - extract gophish from zip
 * Step 2 - Open terminal
 * Step 3 - sudo sh gophish

**Comment by jordan-wright** [comment]
Try ./gophish instead of “sh gophish”. Right now, you’re trying to execute it as a shell script, which won’t work.

**Comment by SumiGaeshi** [comment]
That proved effective. Thank you.
