### ISSUE TITLE
Error 404 While running the exe - GET /wpad.dat HTTP/1.1\" 404 19 \"\" \"WinHttp-Autoproxy-Service/5.1\"

### ISSUE THREAD

**Issue by Fdarya** [gophish/gophish#1863]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: last version
Brief description of the issue: 

What are you expecting to see happen? : run exe file to start working with the tool

What are you seeing happen? the exe is running the database seems to be created, but then in the last line in the cmd seems like the server returning an error.
also, I didn't find information about where the user stored  (cloud maybe?) after sending the test emails.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
Could you share the error you mention

> the last line in the cmd seems like the server returning an error.

Perhaps a screenshot of the output from running the exe too.

> I didn't find information about where the user stored (cloud maybe?) after sending the test emails.

All data is stored in the gophish database, which is by default gophish.db (sqlite file) in the gophish directory.

**Comment by jordan-wright** [comment]
Closing this since it's been over a week with no response.

@glennzw is correct- all data is stored locally in the Gophish database.
