### ISSUE TITLE
Strange Tracker URL behaviour in Gmail

### ISSUE THREAD

**Issue by emtunc** [gophish/gophish#1864]
What version of Gophish are you using?: 
0.10.1, 0.9.0

Brief description of the issue: 
Tracking link does not seem to work in all but one use case for Gmail.

What are you expecting to see happen? :
Tracking link should work in most cases if it is loaded as an img.

What are you seeing happen?

- If I set the GoPhish listener URL to http://ip.address.he.re, the tracking link works 👍 
- If I set the GoPhish listener URL to https://ip.address.he.re, the tracking link does NOT work 👎 
- If I set the GoPhish listener URL to http://FQDN, the tracking link does NOT work 👎 
- If I set the GoPhish listener URL to https://FQDN, the tracking link does NOT work 👎 

I only get the correct, expected behaviour if I set the listener URL to an IP address and ONLY on HTTP and not HTTPS.

What happens is this:

- As soon as I open the email, a GoogleImageProxy bot calls out to the tracker link, NOT my browser/client.

An example of the request as per the GoPhish console logs:

```
Google time="2020-06-10T22:51:41Z" level=info msg="66.249.93.79 - - [10/Jun/2020:22:51:41 +0000]  \"GET /track?rid=JRvCs9v HTTP/1.1\" 200 95 \"\" \"Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com )\""
```

It may be a red-herring but I'm not sure if this has anything to do with the tracking link being quoted-printable in Gmail. This is what the link looks like when I view the email source:

```
<img alt=3D'' style=3D'display: none' src=3D'http://ip.address.he.re/track?r=
id=3DWHbasp0'/></body>
```

No idea at this point.

There is one dirty hack for this though:

- Set GoPhish to listen on both port 80 and 443
- Make the 'tracker URL' {{.TrackingURL}} configurable separately from {{.URL}

If the above was supported, I would set the URL to be https://FQDN (to make the phish more believable when I need it to be) and the TrackingURL to http://IP of the listener.

Hope this all makes sense.

Would be awesome if someone else could try this to see if they experience the same behaviour. on **Gmail**.. I'd be surprised if I was the only one.

**Comment by glennzw** [comment]
Hello,

The tracker image will reside on the server specified by `"phish_server"` in your `config.json` file. By default this is on port 80. If you want it to listen on 80 and 443 you'd need to use some additional proxying software in front of gophish (e.g. nginx, caddy).

For the tracking image to work, your client needs to allow remote loading of content. AFAIK GMail will load remote images, and it does for me:

![Screenshot 2020-06-11 at 11 39 47](https://user-images.githubusercontent.com/3966613/84376054-5bd20e80-abd8-11ea-890c-4c11f10dab9e.png)

**Comment by emtunc** [comment]
@glennzw does it work for you if you try setting your listener to https/443?

**Comment by glennzw** [comment]
Yes, I have my listener running on 443 by default.

**Comment by emtunc** [comment]
Does your tracker URL look like the below when you check the source? I'm wondering if it's an encoding issue or not.

Notice the `=` in the track?r=id=
Also note the `3D` prefixed in the ID.

```
<img alt=3D'' style=3D'display: none' src=3D'https://host/track?r=
id=3DWHbasp0'/></body>
```

**Comment by jordan-wright** [comment]
Are you using a valid certificate? It’s possible that the image proxy won’t load self signed certs.

**Comment by emtunc** [comment]
Yup it has a valid cert. Same behaviour with http://domain too so I don't _think_ it's a cert issue.

**Comment by glennzw** [comment]
> Does your tracker URL look like the below when you check the source? I'm wondering if it's an encoding issue or not.

Yes in GMail source it's quoted-printable for me:

```
<p><img alt=3D'' style=3D'display: none' src=3D'https://some.domain.com/track?rid=3DTnvNKkm'/></p>
```

Can you manually hit the tracking URL that's not working for you? i.e open a browser tab and browse to the tracker that GMail isn't hitting.

Also in Chrome open up the developer console, and see if there are any errors in fetching the image - might be something about not loading insecure content.

**Comment by glennzw** [comment]
Also: https://support.google.com/mail/answer/145919

**Comment by emtunc** [comment]
> > Does your tracker URL look like the below when you check the source? I'm wondering if it's an encoding issue or not.
> 
> Yes in GMail source it's quoted-printable for me:
> 
> ```
> <p><img alt=3D'' style=3D'display: none' src=3D'https://some.domain.com/track?rid=3DTnvNKkm'/></p>
> ```
> 
> Can you manually hit the tracking URL that's not working for you? i.e open a browser tab and browse to the tracker that GMail isn't hitting.
> 
> Also in Chrome open up the developer console, and see if there are any errors in fetching the image - might be something about not loading insecure content.

Yup I can hit the tracking URL when I hit it directly.

Any other troubleshooting steps I can take?

Is there any appetite to natively allow multiple listening ports on the listening server? If not, I'll start looking in to middle-layers/proxies.

**Comment by glennzw** [comment]
No we wouldn't have benefit in having multiple listening ports - but I use Caddy and/or nginx when proxying connections to gophish and it works quite well.
