### ISSUE TITLE
Gophish and docker 

### ISSUE THREAD

**Issue by littlejob** [gophish/gophish#1866]
Has anyone had success with the official docker build? Admin console is accessible, landing page is not.. port 80 is not even listening. 

**What version of Gophish are you using?:** 
Latest release - https://hub.docker.com/r/gophish/gophish

**Brief description of the issue:** 
Admin page accessible - landing page is not - port 80 is not even listening. 

What are you expecting to see happen? :
Various landing pages to load 

**What are you seeing happen?**
Connection refused - port not listening by default

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - docker run -dit --ip 172.17.0.2 -p 3333:3333 --name gophish_prod gophish/gophish
 * Step 2 - admin page is accessible - config.json shows ssl false for 0.0.0.0:80

**Comment by NotoriousRebel** [comment]
With step 1 what if you try adding -p80:80 in the docker run command?

**Comment by littlejob** [comment]
> With step 1 what if you try adding -p80:80 in the docker run command?

well that is embarrassing.. that did the trick. my prior build had a nginx reverse proxy sitting in front doing the redirect... rolled back to test other issues... 

thank you..
