### ISSUE TITLE
Issue upgrading to v0.10.1 from v0.9

### ISSUE THREAD

**Issue by tonynyamu** [gophish/gophish#1868]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: v0.9.0

Brief description of the issue: I have extracted and copied the upgrade files to /opt/gophish and run #sudo ./gophish  with the output below.

time="2020-06-20T09:48:41-05:00" level=info msg="Starting IMAP monitor manager"
time="2020-06-20T09:48:41-05:00" level=info msg="Starting phishing server at http://127.0.0.1:8080"
time="2020-06-20T09:48:41-05:00" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
time="2020-06-20T09:48:41-05:00" level=info msg="TLS Certificate Generation complete"
time="2020-06-20T09:48:41-05:00" level=info msg="Starting admin server at https://127.0.0.1:3333"
time="2020-06-20T09:48:41-05:00" level=info msg="Starting new IMAP monitor for user admin"

What are you expecting to see happen? I am expecting the admin page to launch. 

What are you seeing happen? when I navigate to the URL https://server/settings I get 
_Client sent an HTTP request to an HTTPS server._

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

I am using the latest config.json file from version 0.10.1
```html
{
	"admin_server": {
		"listen_url": "127.0.0.1:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "gophish_admin.key"
	},
	"phish_server": {
		"listen_url": "127.0.0.1:8080",
		"use_tls": false,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": "",
	"logging": {
		"filename": "/var/log/gophish/gophish.log",
		"level": ""
	}
}
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Are you specifying the port? Eg https://server:3333/?

**Comment by tonynyamu** [comment]
no and if I add the port it reverts to https://server with same message

**Comment by tonynyamu** [comment]
I found the issue I appreciate your time looking at this. I disabled tls and its working as expected.

**Comment by abhirf** [comment]
```
time="2022-02-09T13:05:42+01:00" level=info msg="Starting IMAP monitor manager"
time="2022-02-09T13:05:42+01:00" level=info msg="Starting new IMAP monitor for user admin"
time="2022-02-09T13:05:42+01:00" level=fatal msg="listen tcp 0.0.0.0:80: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."
```

When i am running the gophish command in windows (CMD) it is showing Starting IMAP Monitor manager instead of starting the Admin server
