### ISSUE TITLE
Datatables Styling Messed Up

### ISSUE THREAD

**Issue by jordan-wright** [gophish/gophish#187]
It seems like after some recent changes, our datatables styling is messed up on modal tables. Here's what I see on the edit template modal:

![image](https://cloud.githubusercontent.com/assets/1317288/13462339/8986606c-e04c-11e5-9d60-cabea2c28cbf.png)

@StrangeUSB - any ideas?

**Comment by StrangeUSB** [comment]
Hmm...strange. I'll take a look at this later today.

**Comment by StrangeUSB** [comment]
It looks like this is relating to DataTables trying to set it's width to 0px.  I believe this occurs because there is nothing in the table at the time of building it.

**Comment by jordan-wright** [comment]
Agreed. It seemed to start when I upgraded data tables to allow updates on polling.

I wonder if we just need to re draw or something?

**Comment by jordan-wright** [comment]
Looks like this might be related: http://datatables.net/forums/discussion/3417/table-gets-width-0px-when-bvisible-false-is-used

**Comment by StrangeUSB** [comment]
Yeah I saw that. I was able to fix it on one of the tables using that
method, I need to try and narrow down why it didn't work on the other
tables. The other issue with turning off autowidth is that the empty table
message gets squashed into the first tiny column.

There is another solution where we can force the width on all datatables to
100%, but I feel that's a little hacky.

**Comment by StrangeUSB** [comment]
Ok I added a hot fix for it if we want to push that out, but I think there could be a better way to do it.
