### ISSUE TITLE
level=fatal msg="unexpected end of JSON input"

### ISSUE THREAD

**Issue by huangyuan666** [gophish/gophish#1870]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue
The following error occurred when I started
![image](https://user-images.githubusercontent.com/24352334/85247049-22728c00-b47f-11ea-8018-02059b14b0a0.png)
I hope it will start
![image](https://user-images.githubusercontent.com/24352334/85247099-4fbf3a00-b47f-11ea-8ed7-3fc4b40d81c9.png)

**Comment by glennzw** [comment]
You're missing a closing brace `}` at the bottom of your file.

**Comment by jordan-wright** [comment]
Yep! What @glennzw said.
