### ISSUE TITLE
Issue: Sorting of Campaign Status is lost once page is refreshed.

### ISSUE THREAD

**Issue by kpomeroy1979** [gophish/gophish#1879]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.9.0

Brief description of the issue: 
When you are on the campaign page and you sort by clicking on the "Status" entry to have the "Submitted Data" entries at the top (to see the latest users who have submitted data), when the page refreshes the sorting reverts and the status are not in the correct order.

What are you expecting to see happen? :
When I refresh the page, I would want the Sorting of status to stay the way I want it, and not have to re-sort after every refresh.

What are you seeing happen?
When you refresh the Campaign page after sorting the status, the sorting changes and reverts back to a mix of status. 

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
Step 1. Sort the Campaign status
![image](https://user-images.githubusercontent.com/33209502/85793163-d54a2080-b6f1-11ea-8538-0c84ff67f080.png)

Step 2. Refresh. You will notice the sorting is lost.
![image](https://user-images.githubusercontent.com/33209502/85793220-e7c45a00-b6f1-11ea-8ea3-e94e22d95b8c.png)

**Comment by glennzw** [comment]
Does the same happen if you don't manually press the browser refresh button, but the gophish refresh button at the top of the page? This thread might help you in the meantime:

https://github.com/gophish/gophish/issues/1878

**Comment by glennzw** [comment]
I can't reproduce this - when I click the gophish refresh button the data maintains its sort. Perhaps the browser refresh button was being pressed.

Closing out as haven't heard back.
