### ISSUE TITLE
Unable to connect to localhost:3333 using Qubes-VM

### ISSUE THREAD

**Issue by ch4m30** [gophish/gophish#1881]
Hi team,

Gophish version: v0-10.1

Brief description: I am attempting to run Gophish in the QubesOS environment and after installing and executing the binary, i am unable to connect to https://localhost:3333 I get the following error:
![gophish](https://user-images.githubusercontent.com/63590773/86122664-ca84f680-bb0a-11ea-822e-bf8e5b0600ef.png)

I have altered the config file for the admin.server listen to be both 0.0.0.0:3333; and the default 127.0.0.1:3333 (but the issue is the same)

I have attempted to disable the firewall in Qubes, and tested various other OS specific settings but keep coming back to this issue.

Not sure if it can be resolved, but thought I'd reach out.

Thanks.

What are you expecting to see happen? : The Gophish log in page should appear on the browser.

What are you seeing happen? I am seeing the error message above.

Please provide as many steps as you can to reproduce the problem:
 * cd /opt/gophish
 * sudo ./gophish
 * sudo firefox
 * url = https://localhost:3333

**Comment by jordan-wright** [comment]
Looking at the Gophish start message, it appears that there is already a web server listening on TCP port 80. You'll need to shut that down and restart Gophish.

**Comment by ch4m30** [comment]
Hi Jordan, thanks mate, that is exactly what it was. The service ´lighttpd´ (lighty) was running on that port (checked via netstat).

Running the command `service lighttpd stop` and then launching the Gophish has allowed access to the log in page.

I´ll test the remaining features now. Thanks for your time to help!
