### ISSUE TITLE
Change RID in URL of email

### ISSUE THREAD

**Issue by binary0x1** [gophish/gophish#1882]
I have installed the latest version of gophish but when I'm trying to change the RID parameter in URL it doesn't work. After recompile, it uses the same parameter.

**Comment by edermi** [comment]
The RID is stored in the database. What are you trying to accomplish?

**Comment by binary0x1** [comment]
to modify the rid parameter into something else...like https://example.com?parameter=ID..

**Comment by edermi** [comment]
The RID is unique per user and generated when starting a campaign. The only thing you can do is hardcode the RID in the mail and edit the entry in the database manually, but this will only work when you are targeting a single user per campaign.

**Comment by jordan-wright** [comment]
Hi there! You should just need to change [this](https://github.com/gophish/gophish/blob/master/models/campaign.go#L129) parameter to something else, then recompile. If that doesn't work, we'll need more information on what you're doing to be able to help troubleshoot.
