### ISSUE TITLE
Users information is being stored on Gophish servers

### ISSUE THREAD

**Issue by roee360** [gophish/gophish#1884]
Does GoPhish extract any information from the instance that I crate to their own servers?

**Comment by glennzw** [comment]
Could you try explain your question again, I don't quite understand what you're asking.

Gophish is deployed on your server, and sends no information back here or anywhere else.
User information is collected when people open emails or submit data (User agent, OS version, etc)

**Comment by roee360** [comment]
that's what I meant,

Does the information that is being entered by the people I "Phish" or the information I supply about them is being stored or sent anywhere but my own server?

Is this software is safe to use?

**Comment by glennzw** [comment]
No that information is only stored on the gophish server you deploy - in a sqlite or mysql database.

It's as safe as any other piece of open source software 🙃

**Comment by roee360** [comment]
Thank you so much!
