### ISSUE TITLE
Default Credentials do not work when building from source

### ISSUE THREAD

**Issue by Sikkis** [gophish/gophish#1887]
What version of Gophish are you using?:  v.0.10.1

Brief description of the issue:  When building gophish from source, the default password (admin:gophish) does not work.

What are you expecting to see happen? : Login to the admin panel

What are you seeing happen? An authentication error.

Please provide any terminal output that may be relevant below:

```
time="2020-07-02T13:29:06Z" level=error msg="crypto/bcrypt: hashedPassword is not the hash of the given password"
```

Please provide as many steps as you can to reproduce the problem:
```
#Install Gophish
go get github.com/gophish/gophish
cd /opt/goapps/src/github.com/gophish/gophish
go build
sed -i 's/127.0.0.1/0.0.0.0/g' config.json
./gophish
```

**Comment by glennzw** [comment]
See https://github.com/gophish/gophish/issues/1876

> Removes the default password (gophish) for admin users to instead have the password randomly generated when Gophish first starts up

**Comment by Sikkis** [comment]
sorry for the inconvenience. I checked the open issues only
