### ISSUE TITLE
Unable to use PostFix with Gophish.

### ISSUE THREAD

**Issue by Yashvendra** [gophish/gophish#1891]
Q. What version of Gophish are you using?: 
A. **0.10.1**

Q. Brief description of the issue: 
A. I am trying to use PostFix with gophish. Gophish and PostFix servers are running on the same machine. After configuring the _sending profile_ when I try to send _testmail_, the notification says _Email Sent_, however, when I open the inbox of my gmail or any other account, I see no test email from gophish, both in inbox and in spam as well.

Q. What are you expecting to see happen? :
A. I expect to use PostFix as my mailing server for the phishing campaigns. 

Q. What are you seeing happen?
A. Test Email show that email has been sent successfully, but I see no email in my inbox or spam folder.

Q. Please provide any terminal output that may be relevant below:
A. These are the logs of gophish when email is sent -
```
time="2020-07-10T07:53:45Z" level=info msg="Email sent" email="\"Yash Kashyap\" <yashkashyp00720@gmail.com>"
time="2020-07-10T07:53:45Z" level=info msg="xxx.xxx.xxx.xxx - - [10/Jul/2020:07:53:45 +0000] \"POST /api/util/send_test_email HTTP/2.0\" 200 64 \"https://xxx.xxx.xxx.xxx.bc.googleusercontent.com:3333/sending_profiles\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18363\""
```
##### **NOTE**: IP's have been redacted intentionally.

Q. Please provide as many steps as you can to reproduce the problem:
##### NOTE: Both PostFix and Gophish are installed on the same machine.
 * Step 1 - On a fresh installation of ubuntu, install postfix by `sudo apt install postfix`. Leave the configs as default.
 * Step 2 - Copy your internal IPv4 (type `ifconfig` in console) and your hostname (type `hostname` in console). Open `/etc/hosts`, append a new line and map your IP to hostname.
 * Step 3 - Open `/etc/postfix/main.cf`, search for _mynetworks_ variable, and add your `/24` subnet in it.
                 For E.g. If your internal IP is `192.168.1.17`, then you should add `192.168.1.0/24` in _mynetworks_, separated by comma.
![image](https://user-images.githubusercontent.com/23001311/87132370-6523c900-c2b3-11ea-93be-fa25567bad99.png)
 * Step 4 - Restart yout postfix by typing `sudo systemctl restart postfix`
 * Step 5 - Launch gophish, go to sending profile, enter `hostname:25` (make sure to replace hostname with your hostname), try to send a testmail, you will see a notification which says email sent. Open your inbox to which you sent the test mail, you won't find that test email.

GoPhish notification:
<img width="404" alt="gophish" src="https://user-images.githubusercontent.com/23001311/87134026-bf258e00-c2b5-11ea-85a0-540b68a287f1.PNG">

**Comment by jordan-wright** [comment]
Hi there! We try to keep issues focused on Gophish itself. For information on how to configure Postfix, you might refer to [these instructions](https://www.trustedsec.com/blog/take-employees-phishing/).

In this case, Gophish is saying that whatever mail server you configured accepted the email to be sent. What happens from there is fully up to the mail server configuration and out of Gophish's hands.

Sorry we couldn't be of more help! You may also find some of the [community blogs](https://docs.getgophish.com/user-guide/additional-references#community-guides) helpful.
