### ISSUE TITLE
Campaigns are not archiving upon completion

### ISSUE THREAD

**Issue by ChrisASE** [gophish/gophish#1892]
What version of Gophish are you using?:
0.10.1

Brief description of the issue: 
On some user accounts, 'Completed' campaigns are auto moved into the Archived Campaigns tab under Campaigns, however for other users, all campaigns regardless of status remain under Active Campaigns.

*EDIT 14/07/2020*
This issue seems to affect users who have campaigns 'In Progress' or 'Queued'. If one campaign is 'In Progress' or 'Queued' then ALL campaigns for that user, regardless of whether they have been marked Complete or not, stay within the Active Campaigns tab.
If that one 'In Progress' or 'Queued' campaign is either deleted or marked as Complete, then everything marked as Complete moves into Archived Campaigns.
Completed campaigns move back into Active Campaigns when a new campaign is created.

What are you expecting to see happen? :
Completed campaigns are moved to Archived Campaigns. *EDIT* All other campaigns remain under Active Campaigns.

What are you seeing happen?
'Completed' campaigns remain in Active Campaigns when at least one other campaign is 'In Progress' or 'Queued'.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:
N/A

Please provide any terminal output that may be relevant below:
N/A

Please provide as many steps as you can to reproduce the problem:
* User has an active campaign that is either 'In Progress' or 'Queued'. All campaigns regardless of status 
stay in Active Campaigns.
* Mark the active campaign as 'Complete'. All campaigns automatically move into Archived Campaigns.
* Create a new campaign, set to either send straight away or some time in the future. Status of new campaign set to 'In Progress' or 'Queued' depending on scheduling. All 'Completed' campaigns move out of Archived Campaigns tab into Active Campaigns tab.

**Comment by jordan-wright** [comment]
Sorry for the delay- should be all fixed now! Thanks for sending this in!
