### ISSUE TITLE
How can Test Landing Page

### ISSUE THREAD

**Issue by momaydopod** [gophish/gophish#1893]
I use latest vetrsion of the Gophish

I not yet setting sending profile for mail server but I need to test the landing page before  send to user. Please advise

**Comment by glennzw** [comment]
Best is to send a campaign email to yourself :)

**Comment by momaydopod** [comment]
who can share sending profile ?

**Comment by jordan-wright** [comment]
Sending profiles are something that you control. It's either a personal SMTP server or a third party mail sending provider. You can find recommendations by searching through previous issues.

Since the original question was answered I'm going to close this out.
