### ISSUE TITLE
Error using brackets [ ] in sending profile from field

### ISSUE THREAD

**Issue by ldunzweiler** [gophish/gophish#1896]
CentOS 8, GoPhish 0.10.1, on-prem Exchange 2016

In our org, we use "[ext]" to denote external emails. 

When making a sender profile, in the from address I get the error "mail: no angle-addr" from using the [ ].  

Our fix for this atm is to make a transport rule on the exchange server to append the [ext].

**Comment by jordan-wright** [comment]
It's hard for me to imagine that would be a valid email address per RFC 5322, but even if it is, Gophish uses Golang's [`mail.ParseAddress`](https://golang.org/pkg/net/mail/#ParseAddress) function so we only support what it supports.

Sorry we cant be of more help here!
