### ISSUE TITLE
Gophish not accessible after adding WAF above the server machine

### ISSUE THREAD

**Issue by kush-1277** [gophish/gophish#1897]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

**What version of Gophish are you using?:** Version 10

Brief description of the issue: I have installed Gophish on a Kali Linux EC2-Instance, and I am testing a around with some stuff with the Cloudflare WAF. After I deployed my Cloudflare WAF on top of that instance using it's IP address and DNS settings, I cannot access the Gophish Admin login page.

The request times out with the Gophish server, which for me is the 1277 port, but when I access the same url with the 443 port I can see 404 not found which means it can access the machine with that port but not with the 1277 port. Is there something I can do from Gophish side or do I have to do some settings modification in Cloudflare DNS settings?

Any help will be appreciated! thanks a lot in advance!!

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

**Comment by jordan-wright** [comment]
I'm afraid there isn't enough information for us to determine what's going on here. It sounds like there's some Cloudflare related networking issue they needs to get resolved. There's almost certainly nothing custom that Gophish has to prevent this networking issue from occurring.

Sorry there isn't more we could do to help!
