### ISSUE TITLE
gophish can not start

### ISSUE THREAD

**Issue by topsekadmin** [gophish/gophish#1899]
i use gophishv0.10.1 version

config,json show below:
{
	"admin_server": {
		"listen_url": "0.0.0.0:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "gophish_admin.key"
	},
	"phish_server": {
		"listen_url": "0.0.0.0:80",
		"use_tls": false,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "mysql",
	"db_path": "root:XXXXXX@(localhost:3306)/gophish?charset=utf8&parseTime=True&loc=UTC",
	"migrations_prefix": "db/db_",
}

when i use ./gohish start server,show below:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x628f16]

goroutine 1 [running]:
github.com/gophish/gophish/logger.Setup(0x0, 0xc00024e000, 0x5)
	/go/src/github.com/gophish/gophish/logger/logger.go:34 +0x26
main.main()
	/go/src/github.com/gophish/gophish/gophish.go:73 +0x23a

same config use gophish0.8.0,that's ok

please help me,thank you

**Comment by jordan-wright** [comment]
You'll need to add a section that looks like this:

```json
"logging": {
		"filename": "",
		"level": ""
	}
```

In the meantime, I've added a little check to make this more resilient in case the logging section isn't provided.
