### ISSUE TITLE
Marking as reported is not registering

### ISSUE THREAD

**Issue by beaug** [gophish/gophish#1900]
In Campaigns clicking the "Reported" button gives the message to say this will mark as reported but does not actually update to say that the email was reported.

**Comment by jordan-wright** [comment]
Hey there!

I'm afraid there isn't enough info here to really troubleshoot what's going on. Do you see any logs show up in the Gophish console when you click that button? I'm guessing if you refresh the page you don't see the reported status?

And if you open your browser's developer tools, do you see the request get sent to Gophish? What does the response look like?

**Comment by jordan-wright** [comment]
Closing this since there haven't been any updates in a week. @beaug if you're still running into trouble, please provide the information I ask for above and we can continue troubleshooting.
