### ISSUE TITLE
Cross Site Scripting (XSS) via Webhooks

### ISSUE THREAD

**Issue by dunderhay** [gophish/gophish#1901]
### What version of Gophish are you using?: 
Gophish v0.10.1

### Brief description of the issue: 
When using the ping functionality to test a webhook, the response received from the webhook is reflected into the page without being properly escaped.

More on xss [here](https://owasp.org/www-community/attacks/xss/).

### What are you expecting to see happen? :
Execute arbitrary JavaScript

### What are you seeing happen?
Execute arbitrary JavaScript

### Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Create a php file containing our JavaScript payload (in my case test2.php):

   ```php
    <?php header("HTTP/1.0 404 <script>alert(1)</script>"); ?>
    ```

    Run the php web server: `php -S localhost:8443 -t .`
 
 * Step 2 - Create a new webhook in Gophish and point this to the previously created php file:

![Create-webhook](https://user-images.githubusercontent.com/27876907/87900731-914ffe80-ca98-11ea-9032-4af537869566.png)

* Step 3 - Click the "Ping" button to test the new webhook and notice execution of arbitrary JavaScript:

<img width="1126" alt="xss" src="https://user-images.githubusercontent.com/27876907/87900981-2c48d880-ca99-11ea-949b-c5356e8d1e3c.png">

<img width="1099" alt="dom" src="https://user-images.githubusercontent.com/27876907/87901005-379c0400-ca99-11ea-9aa0-e97bbc4d314c.png">

**Comment by dunderhay** [comment]
Quick update:

### What are you expecting to see happen? :
Special characters are escaped and the JavaScript payload is not executed.

### What are you seeing happen?
JavaScript payload is executed


I had a quick look for where this issue might be occurring and think it is the following:
https://github.com/gophish/gophish/blob/ec8b17238ee725e84f0d2cff4c20c2b8bbb362f5/static/js/src/app/webhooks.js


```js
const pingUrl = (btn, whId) => {
    dismiss();
    btn.disabled = true;
    api.webhookId.ping(whId)
        .success(function(wh) {
            btn.disabled = false;
            successFlash(`Ping of "${escapeHtml(wh.name)}" webhook succeeded.`);
        })
        .error(function(data) {
            btn.disabled = false;
            var wh = webhooks.find(x => x.id == whId);
            if (!wh) {
                return
            }
            errorFlash(`Ping of "${escapeHtml(wh.name)}" webhook failed: "${data.responseJSON.message}"`) 🔥
        });
};
```

**Comment by jordan-wright** [comment]
Should be all fixed. Thanks for sending this in! In the long term, I'd still love to move to something like React so that I'm not left catching every one of these instances, but these days it's hard to find the blocks of time needed for big migrations like that.

**Comment by dunderhay** [comment]
Yeah, using a modern framework like that would definitely stop you having to catch each individual case... but, that would be a major bit of work 😣
