### ISSUE TITLE
Add HTTP Security Headers to Phishing Server

### ISSUE THREAD

**Issue by riab-tam** [gophish/gophish#1904]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.10.1

Brief description of the issue: Looking to see if there is a way to add HTTP security headers (i.e. Strict-Transport-Security, Content-Security-Policy, X-Frame-Options, etc) to the domain served by the gophish phishing testing server.

What are you expecting to see happen? : HTTP security headers set when running a scan on the site via securityheaders.com

What are you seeing happen? No HTTP security headers set when running a scan on the site via securityheaders.com, and no clear ability to set them.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
No, there is currently no way to add custom headers to Gophish unless you either recompile the source yourself or front it with a reverse proxy.
