### ISSUE TITLE
Gophish won't launch on my Mac after using sudo ./gophish

### ISSUE THREAD

**Issue by moleeon** [gophish/gophish#1906]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue: 

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by moleeon** [comment]
its says command not found ..heres step by step of my installation method
cd Downloads
ls
cd gophish-v0
ls
ls -l
sudo ./gophish

then it asks for password .after putting my password it says "command  not found'
kindly point where I went wrong

**Comment by jordan-wright** [comment]
Without the output to your commands, it's hard to tell what's going on. What does the output of `ls -l` in that folder show?

**Comment by demicoli00** [comment]
Hi I'm having the same issue exactly as @moleeon 

What version of Gophish are you using?: V.0.10.0 osx 64 bit

Brief description of the issue: sudo ./gophish leads to sudo: ./gophish: command not found

Installation steps: 
cd Downloads
ls
cd gophish-v0
ls
ls -l
sudo ./gophish

Output: sudo: ./gophish: command not found

ls -

Output:
-rw-r--r--@  1 xxxxxxxxxxxxxxx  staff      1115 May 25 03:08 LICENSE
-rw-r--r--@  1 xxxxxxxxxxxxxxx  staff      3038 May 25 03:08 README.md
-rw-r--r--@  1 xxxxxxxxxxxxxxx  staff         7 May 25 03:08 VERSION
-rw-r--r--@  1 xxxxxxxxxxxxxxx  staff       437 Jul 25 17:35 config.json
drwxr-xr-x@  4 xxxxxxxxxxxxxxx  staff       128 May 25 03:08 db
-rw-r--r--@  1 xxxxxxxxxxxxxxx  staff  23407488 May 25 03:09 gophish
drwxr-xr-x@  7 xxxxxxxxxxxxxxx  staff       224 Jul 25 17:21 static
drwxr-xr-x@ 16 xxxxxxxxxxxxxxx  staff       512 May 25 03:08 templates

Cannot understand what I did wrong. Thanks.

**Comment by glennzw** [comment]
You need to set the gophish binary to be executable:

```
chmod +x gophish
sudo ./gophish
```

**Comment by moleeon** [comment]
Okay thanks , I will try that and give feedback

**Comment by jordan-wright** [comment]
Closing since it's been a few days. @moleeon if that didn't work, let us know and we can re-open.

**Comment by moleeon** [comment]
i am using the older version vo.9.0  now and it works perfectly .thank you

**Comment by moleeon** [comment]
i also wanna ask if its possible to use yahoo mail as smtp server
