### ISSUE TITLE
e.sendwithtls error

### ISSUE THREAD

**Issue by TheWalterWhite** [gophish/gophish#191]
When compiling the newest release on Ubuntu server 15.10 this error happens:
`worker/worker.go:127: e.SendWithTLS undefined (type email.Email has no field or method SendWithTLS)
worker/worker.go:228: e.SendWithTLS undefined (type email.Email has no field or method SendWithTLS)`

**Comment by jordan-wright** [comment]
Try a go get -u. Should fix the issue.

**Comment by TheWalterWhite** [comment]
That fixed it. Thanks!
