### ISSUE TITLE
i dont know why but i cant run gophish on my mac the terminal doesn’t recognise my command ./gophish 

### ISSUE THREAD

**Issue by BHrithik** [gophish/gophish#1910]
i dont know why but i cant run gophish on my mac the terminal doesn’t recognise my command 
<img width="1440" alt="Screenshot 2020-07-26 at 9 56 34 PM" src="https://user-images.githubusercontent.com/31255192/88484260-e0ab9880-cf8a-11ea-8054-f2b862ed4b73.png">

**Comment by jordan-wright** [comment]
Hi there! Check out #1906 and let me know if the chmod works to solve the issue.
