### ISSUE TITLE
Invalid Username/Password Error When Using Default Login Crendential

### ISSUE THREAD

**Issue by leiherman** [gophish/gophish#1911]
Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: the latest version in Dockerhub

Brief description of the issue: Invalid Username/Password when the first login using the default credential: admin/gophish

Please provide me the default credential for this version.

Thank you very much!

**Comment by jordan-wright** [comment]
Hi there! Please refer to our [documentation](https://docs.getgophish.com/user-guide/getting-started#logging-in)

> For versions of Gophish > 0.10.1, the temporary administrator credentials are printed in the logs when you first execute the Gophish binary.

**Comment by KhandyKane** [comment]
I am getting the error message of invalid username/password after running the binary.
![Capture](https://user-images.githubusercontent.com/104869277/166829412-5799960e-42bd-48e1-ab1c-80d16910cb5b.JPG)
![CMD](https://user-images.githubusercontent.com/104869277/166829449-772fc0fb-d352-418d-8516-928cbcee9fbb.JPG)

**Comment by webtool14** [comment]
im get this error massage 

 Invalid Username/Password

time="2022-10-21T13:12:08+01:00" level=warning msg="No contact address has been configured."
time="2022-10-21T13:12:08+01:00" level=warning msg="Please consider adding a contact_address entry in your config.json"
goose: migrating db environment 'production', current version: 0, target: 20220321133237
OK    20160118194630_init.sql
OK    20160131153104_0.1.2_add_event_details.sql
OK    20160211211220_0.1.2_add_ignore_cert_errors.sql
OK    20160217211342_0.1.2_create_from_col_results.sql
OK    20160225173824_0.1.2_capture_credentials.sql
OK    20160227180335_0.1.2_store-smtp-settings.sql
OK    20160317214457_0.2_redirect_url.sql
OK    20160605210903_0.2_campaign_scheduling.sql
OK    20170104220731_0.2_result_statuses.sql
OK    20170219122503_0.2.1_email_headers.sql
OK    20170827141312_0.4_utc_dates.sql
OK    20171027213457_0.4.1_maillogs.sql
OK    20171208201932_0.4.1_next_send_date.sql
OK    20180223101813_0.5.1_user_reporting.sql
OK    20180524203752_0.7.0_result_last_modified.sql
OK    20180527213648_0.7.0_store_email_request.sql
OK    20180830215615_0.7.0_send_by_date.sql
OK    20190105192341_0.8.0_rbac.sql
OK    20191104103306_0.9.0_create_webhooks.sql
OK    20200116000000_0.9.0_imap.sql
OK    20200619000000_0.11.0_password_policy.sql
OK    20200730000000_0.11.0_imap_ignore_cert_errors.sql
OK    20200914000000_0.11.0_last_login.sql
OK    20201201000000_0.11.0_account_locked.sql
OK    20220321133237_0.4.1_envelope_sender.sql
time="2022-10-21T13:12:11+01:00" level=info msg="Please login with the username admin and the password 03bcf2ef8141a25f"
time="2022-10-21T13:12:11+01:00" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
time="2022-10-21T13:12:11+01:00" level=info msg="Starting IMAP monitor manager"
time="2022-10-21T13:12:11+01:00" level=info msg="Starting phishing server at http://0.0.0.0:80"
time="2022-10-21T13:12:11+01:00" level=info msg="Creating new self-signed certificates for administration interface"
time="2022-10-21T13:12:11+01:00" level=info msg="Starting new IMAP monitor for user admin"
time="2022-10-21T13:12:11+01:00" level=info msg="TLS Certificate Generation complete"
time="2022-10-21T13:12:11+01:00" level=info msg="Starting admin server at https://127.0.0.1:3333"
2022/10/21 13:12:58 http: TLS handshake error from 127.0.0.1:64611: remote error: tls: unknown certificate
2022/10/21 13:13:00 http: TLS handshake error from 127.0.0.1:64612: remote error: tls: unknown certificate
2022/10/21 13:13:00 http: TLS handshake error from 127.0.0.1:64613: remote error: tls: unknown certificate
2022/10/21 13:13:05 http: TLS handshake error from 127.0.0.1:64615: remote error: tls: unknown certificate
2022/10/21 13:13:05 http: TLS handshake error from 127.0.0.1:64616: remote error: tls: unknown certificate
time="2022-10-21T13:13:05+01:00" level=info msg="127.0.0.1 - - [21/Oct/2022:13:13:05 +0100] \"GET / HTTP/2.0\" 307 51 \"\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36\""
time="2022-10-21T13:13:05+01:00" level=info msg="127.0.0.1 - - [21/Oct/2022:13:13:05 +0100] \"GET /login?next=%2F HTTP/2.0\" 200 1037 \"\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36\""
time="2022-10-21T13:13:05+01:00" level=info msg="127.0.0.1 - - [21/Oct/2022:13:13:05 +0100] \"GET /images/logo_inv_small.png HTTP/2.0\" 200 1118 \"https://127.0.0.1:3333/login?next=%2F\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36\""
time="2022-10-21T13:13:05+01:00" level=info msg="127.0.0.1 - - [21/Oct/2022:13:13:05 +0100] \"GET /images/logo_purple.png HTTP/2.0\" 200 4735 \"https://127.0.0.1:3333/login?next=%2F\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36\""
time="2022-10-21T13:13:05+01:00" level=info msg="127.0.0.1 - - [21/Oct/2022:13:13:05 +0100] \"GET /css/dist/gophish.css HTTP/2.0\" 200 52514 \"https://127.0.0.1:3333/login?next=%2F\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36\""
time="2022-10-21T13:13:06+01:00" level=info msg="127.0.0.1 - - [21/Oct/2022:13:13:05 +0100] \"GET /js/dist/vendor.min.js HTTP/2.0\" 200 324943 \"https://127.0.0.1:3333/login?next=%2F\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36\""
time="2022-10-21T13:13:06+01:00" level=info msg="127.0.0.1 - - [21/Oct/2022:13:13:06 +0100] \"GET /images/favicon.ico HTTP/2.0\" 200 1150 \"https://127.0.0.1:3333/login?next=%2F\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36\""
2022/10/21 13:13:13 http: TLS handshake error from 127.0.0.1:64620: remote error: tls: unknown certificate
2022/10/21 13:13:13 http: TLS handshake error from 127.0.0.1:64621: remote error: tls: unknown certificate
time="2022-10-21T13:13:13+01:00" level=error msg="crypto/bcrypt: hashedPassword is not the hash of the given password"
time="2022-10-21T13:13:13+01:00" level=info msg="127.0.0.1 - - [21/Oct/2022:13:13:13 +0100] \"POST /login?next=%2F HTTP/2.0\" 401 1118 \"https://127.0.0.1:3333/login?next=%2F\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36\""
time="2022-10-21T13:13:13+01:00" level=info msg="127.0.0.1 - - [21/Oct/2022:13:13:13 +0100] \"GET /font/fontawesome-webfont.woff2?v=4.7.0 HTTP/2.0\" 200 77177 \"https://127.0.0.1:3333/css/dist/gophish.css\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36\""
2022/10/21 13:13:24 http: TLS handshake error from 127.0.0.1:64623: remote error: tls: unknown certificate
2022/10/21 13:13:24 http: TLS handshake error from 127.0.0.1:64624: remote error: tls: unknown certificate
time="2022-10-21T13:13:24+01:00" level=error msg="crypto/bcrypt: hashedPassword is not the hash of the given password"
time="2022-10-21T13:13:24+01:00" level=info msg="127.0.0.1 - - [21/Oct/2022:13:13:24 +0100] \"POST /login?next=%2F HTTP/2.0\" 401 1123 \"https://127.0.0.1:3333/login?next=%2F\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36\""
