### ISSUE TITLE
Unable to run gophish on RHEL sudo ./gophish

### ISSUE THREAD

**Issue by jshorrock** [gophish/gophish#1912]
What version of Gophish are you using?: 

gophish-v0.10.1-linux-64bit

Brief description of the issue: Unable to run ./gophish

What are you expecting to see happen? :

Expecting to see file execute with log of IP, port, etc

What are you seeing happen?
without sudo, I get permission denied

./gophish
-sh: ./gophish: Permission denied

 sudo ./gophish
sudo: ./gophish: command not found

**Comment by jshorrock** [comment]
I've also tried building from source:
go get github.com/gophish/gophish
go build
After building, I get the same errors as above. I've also tried chmod -x gophish

**Comment by S0larflare** [comment]
The command you need is chmod +x gophish

Sent from my iPhone

On 29 Jul 2020, at 13:13, jshorrock <notifications@github.com> wrote:

﻿

I've also tried building from source:
go get github.com/gophish/gophish
go build
After building, I get the same errors as above. I've also tried chmod -x gophish

**Comment by jordan-wright** [comment]
Yep! chmod +x

**Comment by jordan-wright** [comment]
(If that's still not working, let us know and we can reopen the issue. Just include the exact commands and output you're seeing)

**Comment by jshorrock** [comment]
That worked, thanks for the help.

**Comment by masterloka** [comment]
any problem

goose: no migrations to run. current version: 20200730000000

time="2021-03-22T04:15:48Z" level=info msg="Starting IMAP monitor manager"
time="2021-03-22T04:15:48Z" level=info msg="Starting admin server at https://0.0.0.0:1724"
time="2021-03-22T04:15:48Z" level=fatal msg="open gophish_admin.key: permission denied"
