### ISSUE TITLE
Trouble identifying the people being phished

### ISSUE THREAD

**Issue by sreekanth99850** [gophish/gophish#1916]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
Gophish 9.0
Brief description of the issue: 

We are facing some issues in the Gophish application.
We send phishing mails to employees.We are facing trouble in identifying the employees who have been phished if they forward it to some other people(managers)
Could you please suggest a solution for this issue.

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
There's not a solution to that which Gophish currently offers. And to be honest, I don't really know how I'd handle that in general. If people are forwarding phishing emails around then that sounds like an opportunity to help guide folks to the right place where phishing emails should go - namely their friendly security team 😄
