### ISSUE TITLE
Submit Data in Gophish Not Working

### ISSUE THREAD

**Issue by gabrielbecks** [gophish/gophish#1921]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: I’m installed both v0.10.1 and v0.9.0 to my windows

Brief description of the issue: everything on my Gophish works well, but the submit data doesn’t I’ve Tried everything to make it work for weeks now even read every #issue relating still no success

What are you expecting to see happen? : I’m expecting to see the Campaign finish and give Brie credentials(submitted data)

What are you seeing happen? Everything working perfectly fine but the submit data, view credentials aspect

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:I’m not sure because I’ve checked and done everything and I’m open for any suggestions right now to help solve this issue

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - I log into Gophish 
 * Step 2 - create a normal campaign 
* step 3- when I test the campaign on my email and enter it shows email opened, clicked link and all that and just stops at that
*step 4- doesn’t show any thing on submit data
*step5- me *figurately going crazy and brainstorming what the problem could be.

**Comment by jordan-wright** [comment]
We'll need a copy of the `<form>` that you have in your landing page HTML. Chances are, there's something wrong there.

**Comment by gabrielbecks** [comment]
THIS IS THE COPY OF THE FORM BELOW:


<form action="" id="login_form" method="post" novalidate="1" onsubmit=""><input name="__original_url" type="hidden" value="https://www.facebook.com/login/device-based/regular/login/?login_attempt=1&amp;lwv=110" /><input autocomplete="off" name="jazoest" type="hidden" value="2646" /><input autocomplete="off" name="lsd" type="hidden" value="AVq_m78C" />
<table cellspacing="0" role="presentation">
	<tbody>
		<tr>
			<td class="html7magic"><label for="email">Email or phone</label></td>
			<td class="html7magic"><label for="pass">Password</label></td>
		</tr>
		<tr>
			<td><input class="inputtext login_form_input_box" data-testid="royal_email" id="email" name="email" type="email" /></td>
			<td><input class="inputtext login_form_input_box" data-testid="royal_pass" id="pass" name="password" type="password" /></td>
			<td><label class="login_form_login_button uiButton uiButtonConfirm" for="u_0_b" id="loginbutton"><input aria-label="Log In" data-testid="royal_login_button" id="u_0_b" type="submit" value="Log In" /></label></td>
		</tr>
		<tr>
			<td class="login_form_label_field">&nbsp;</td>
			<td class="login_form_label_field">
			<div><a href="https://www.facebook.com/recover/initiate?lwv=110&amp;ars=royal_blue_bar">Forgotten account?</a></div>
			</td>
		</tr>
	</tbody>
</table>
<input autocomplete="off" id="u_0_c" name="timezone" type="hidden" value="" /><input autocomplete="off" id="u_0_d" name="lgndim" type="hidden" value="" /><input name="lgnrnd" type="hidden" value="002908_Binz" /><input id="lgnjs" name="lgnjs" type="hidden" value="n" /><input autocomplete="off" name="ab_test_data" type="hidden" value="" /><input autocomplete="off" id="locale" name="locale" type="hidden" value="en_GB" /><input autocomplete="off" name="next" type="hidden" value="https://www.facebook.com/" /><input autocomplete="off" name="login_source" type="hidden" value="login_bluebar" /><input autocomplete="off" name="guid" type="hidden" value="" /><input autocomplete="off" id="prefill_contact_point" name="prefill_contact_point" type="hidden" /><input autocomplete="off" id="prefill_source" name="prefill_source" type="hidden" /><input autocomplete="off" id="prefill_type" name="prefill_type" type="hidden" />&nbsp;</form>

**Comment by gabrielbecks** [comment]
This is a copy of the <form> below:

<form action="" method="post" name="signIn" novalidate="">
<h1>Sign in</h1>
<div><label for="ap_email">Email </label></div>
<input name="email_address" type="email" />
<div><label for="ap_password">Password </label></div>
<input type="password" name="password"/>
<input type="submit" name="submit" value="Sign In"/>
<div><input tabindex="4" type="checkbox" value="true" /> Keep me signed in</div>
</form>

**Comment by gabrielbecks** [comment]
copy of the form

**Comment by gabrielbecks** [comment]
I'm Finding It Difficult ti post the form on here without it running So I Took A Picture Instead; 

![image](https://user-images.githubusercontent.com/69060650/89097190-a3a13500-d3d4-11ea-81fb-a0386824e28f.jpeg)

**Comment by gabrielbecks** [comment]
I really hope you can see it.

**Comment by glennzw** [comment]
When you hit Submit what happens? Is there an error, or nothing happens? Also, does anything appear in your gophish logs when submitting the form?

Perhaps simplify your `<form ...` element to:

`<form action="" method="post" name="form">`

I don't think that `onsubmit` would affect it, but it might.

Here's a very simple form you can try, that definitely works:

```
<html><head>
	<title></title>
</head>
<body>
<form action="" method="post" name="form"><label>Username:</label> <input name="username" type="text"/><br/>
<label>Password:</label> <input name="password" type="password"/><br/>
<input id="login" name="login" type="submit" value="Login"/> </form>


</body></html>
```

**Comment by gabrielbecks** [comment]
@glennzw nothing happens when i hit submit, every other thing works fine but submitted data and email reported is always on 0 no credentials are recorded, i just changed the form to yours and it still doesn't get data , just stops on clicked link refreshed like over and over again

**Comment by glennzw** [comment]
I assume you've tried a different browser? Try Chrome if you haven't already, with all plugins disabled.

Otherwise, I'm really not sure.

**Comment by jordan-wright** [comment]
@glennzw's form is the right way to write a form that submits data in a way that Gophish can record it. If that's not working, it'd imply a browser issue.

But there's still no information about what you're seeing. In order for us to troubleshoot what's going on, we need to know things like:

* When you say you tried @glennzw's form, did you completely replace the form?
* When you submit the form, do you see a request being made from your browser using your browser's developer tools?
* If you see a request being made, what does the request contents look like?
* If you see a request being made, do you see the log in the Gophish terminal?
* If you see the log in the Gophish terminal, what does it say?

These are all questions that we need answered in order to figure out what's going on.

**Comment by gabrielbecks** [comment]
- when i tired @glennzw's form, yes i completely replaced the form
when i submitted the form no request was made by the developer tools

and yes i just installed google chrome and disabled all plugins, but the problem still persists.

**Comment by jordan-wright** [comment]
We won't be able to proceed troubleshooting until we have the answers to the questions I listed earlier.

**Comment by jordan-wright** [comment]
Ah, I noticed that you did say you didn't see a request sent via dev tools. That's suggesting that JavaScript is catching the form submission. You'll need to remove the relevant JS to ensure the form is submitted just via the standard browser + HTML.

**Comment by gabrielbecks** [comment]
I've removed the JavaScripts, replaced the codes, changed browser everything you've asked, it's just not working out. Still the same thing.

**Comment by glennzw** [comment]
It's hard to figure out what's not working from the information provided. Perhaps you could share a video of everything you've done, step by step. - showing the browser and gophish terminal.

**Comment by glennzw** [comment]
Closing out as we haven't heard back, feel free to re-open.
