### ISSUE TITLE
Not able to connect mysql db with gophish code set up using binary

### ISSUE THREAD

**Issue by mansichauhan27** [gophish/gophish#1925]
hi i am no able to connect mysql db with gophish, getting this error:

time="2020-08-03T18:45:37+05:30" level=warning msg="waiting for database to be up..."
time="2020-08-03T18:45:42+05:30" level=warning msg="waiting for database to be up..."
time="2020-08-03T18:45:47+05:30" level=warning msg="waiting for database to be up..."
time="2020-08-03T18:45:52+05:30" level=warning msg="waiting for database to be up..."
time="2020-08-03T18:45:57+05:30" level=warning msg="waiting for database to be up..."
time="2020-08-03T18:46:02+05:30" level=warning msg="waiting for database to be up..."
time="2020-08-03T18:46:07+05:30" level=warning msg="waiting for database to be up..."
time="2020-08-03T18:46:12+05:30" level=warning msg="waiting for database to be up..."

Here is config.json:
{
	"admin_server": {
		"listen_url": "127.0.0.1:3333",
		"use_tls": true,
		"cert_path": "gophish.crt",
		"key_path": "gophish.key"
	},
	"phish_server": {
		"listen_url": "0.0.0.0:80",
		"use_tls": false,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "mysql",
	"db_path":"root:admin!@12(localhost:3306)/gophish?charset=utf8&parseTime=True&loc=Local",
	"migrations_prefix": "db/db_",
	"contact_address": "",
	"logging": {
		"filename": "log.log",
		"level": ""
	}
}

Please look into this as soon as possible.Thanks

**Comment by glennzw** [comment]
My only thought is the "12" after the "@" symbol. Unless that has some meaning I'm unaware of, but here's my working connection string:
```
        "db_path": "user:password@(:3306)/gophish?charset=utf8&parseTime=True&loc=UTC",
```

Perhaps increasing your debugging would help too (`"level": "debug"`).

**Comment by mansichauhan27** [comment]
Hi thanks for your help. I am now able to connect !!!
