### ISSUE TITLE
No groups found!

### ISSUE THREAD

**Issue by mehervez** [gophish/gophish#1927]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.9.0

Brief description of the issue: No groups found! error appears when I am creating a campaign. I have already created 2 groups.

What are you expecting to see happen? : Campaign to be created.

What are you seeing happen?No groups found! error while creating the campaign

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
There's not enough information here to troubleshoot. Please list everything you've tried up until this point, screenshots, etc. The more information the better.

**Comment by glennzw** [comment]
Closing out as we haven't heard back, feel free to re-open.
