### ISSUE TITLE
Error While Executing Gophish Ver 0.10.0

### ISSUE THREAD

**Issue by mehervez** [gophish/gophish#1928]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.10.0

Brief description of the issue: I am able to run the gophish ver 0.10.0 on my local machine, however while trying to execute the same on one of my VM I get the following error "D:\gophish-v0.10.1-windows-64bit>gophish
D:\gophish-v0.10.1-windows-64bit\db\db_sqlite3
goose: no migrations to run. current version: 20200116000000
runtime: bad pointer in frame github.com/konsorten/go-windows-terminal-sequences.EnableVirtualTerminalProcessing at 0xc0000596b0: 0x64 fatal error: invalid pointer found on stack"

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
A quick Google search led me to an article suggesting downgrading to Go 1.13 (as this appears to be a 1.14 problem).

**Comment by glennzw** [comment]
Closing out as we haven't heard back, feel free to re-open.

**Comment by kenwmc** [comment]
Where do I get version 1.13 of the software?  To see if this will work.  Can I copy my my current database back or am I going to loose all the information that was entered today.

**Comment by glennzw** [comment]
Keep a copy of gophish.db, and put that in any new gophish folder you create and you'll keep your work.

I don't use Windows so cant advise on how to downgrade, other than asking Google. I suspect remove the current version then install 1.13:


https://golang.org/doc/install#install

**Comment by kenwmc** [comment]
I know how to downgrade Windows but that really isn't what I was asking.  I was asking where do I find gophish version 1.13.

**Comment by edermi** [comment]
There is no gophish 1.13. You have to build the latest gophish from source using Go version 1.13.

**Comment by kenwmc** [comment]
Thanks for clarifying.  
    On Thursday, December 17, 2020, 04:11:38 AM CST, Michael Eder <notifications@github.com> wrote:  
 
 


There is no gophish 1.13. You have to build the latest gophish from source using Go version 1.13.

**Comment by glennzw** [comment]
Very sorry, yes I meant **go** 1.13
