### ISSUE TITLE
Email template worker crash with tag substitution

### ISSUE THREAD

**Issue by scottg88** [gophish/gophish#193]
On version 0.1.2:

Worker.go crash when an email template contains text wrapped in {{ and }} without a '.' at the beginning.

Reproduce:
- Create email template and in either text or HTML enter:
{{Something}}
- Launch campaign with email
- Worker.go crashes with error

Crash log:

```
 2016/03/08 05:45:42 worker.go:99: template: text_template:1: function "Something" not defined
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0x61a4a5]

goroutine 8 [running]:
text/template.errRecover(0xc8202e5528)
        /root/go/src/text/template/exec.go:100 +0xbb
text/template.(*Template).Execute(0x0, 0x7fcf86d31f18, 0xc8204833b0, 0xa92760, 0xc8202a6620, 0x0, 0x0)
        /root/go/src/text/template/exec.go:140 +0x235
github.com/gophish/gophish/worker.processCampaign(0xc820372000)
        /root/projects/src/github.com/gophish/gophish/worker/worker.go:101 +0x12b9
github.com/gophish/gophish/worker.(*Worker).Start(0xc820022b88)
        /root/projects/src/github.com/gophish/gophish/worker/worker.go:40 +0x119
created by github.com/gophish/gophish/controllers.init.1
        /root/projects/src/github.com/gophish/gophish/controllers/api.go:28 +0x9f

goroutine 1 [semacquire, 4 minutes]:
sync.runtime_Semacquire(0xc8201ba81c)
        /root/go/src/runtime/sema.go:43 +0x26
sync.(*WaitGroup).Wait(0xc8201ba810)
        /root/go/src/sync/waitgroup.go:126 +0xb4
main.main()
        /root/projects/src/github.com/gophish/gophish/gophish.go:75 +0x17b
<snip>
```

Full log: https://gist.github.com/scottg88/00946b6d67a5937525fe

Can confirm if you instead put a bogus tag like {{.Something}} (with the .), it does not crash.

**Comment by jordan-wright** [comment]
Ah, yes. This is unfortunately the difficulty with using go templates.

Eventually, I might consider just *not* using go's templates at all. They aren't forgiving to user errors, and don't really give me much more in this scenario than a simple find/replace. That should clear things up quite a bit but I'd like to run through all the options first.

Thanks for the report!

**Comment by scottg88** [comment]
Could we put a simple regex validation when updating the email template to make sure this doesn't occur, until a proper solution is decided upon? E.g. something as simple as:

\{[^.].*\}

Would match if there's something wrapped in curly braces with no '.' at the beginning anywhere in the text, then reject it with an error message.

**Comment by jordan-wright** [comment]
I'm planning on having where, on save, we validate the template by trying to parse it.

I'm expecting to have it knocked out in a couple days or so.

**Comment by jordan-wright** [comment]
I've added some validation to hopefully catch these things early. Let me know if that helps prevent this issue!

The error messages aren't perfect (just dumping out what Go provides), but it gives a hint to the issue.
