### ISSUE TITLE
Landing Page and Email template Images are not visible to enduser

### ISSUE THREAD

**Issue by vshinde1992** [gophish/gophish#1930]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  v0.10.1

Brief description of the issue: We have successfully imported landing and email template in GoPhish also copied all images in static/images folder within GoPhish server. We can see all images in GoPhish application for landing page and email template, However enduser post receiving mail not able to see images for email and landing page. Rest everything working fine, we are getting all results as expected. 
Note: We have opened port 443 from all enduser machines towards GoPhish server.
Also, Need help on how to import SSL certificate in GoPhish as we are hosting landing as HTTPS port 443. 

What are you expecting to see happen? : Endusers should be able to see all images on email template and and landing page.
 
What are you seeing happen? Endusers are receiving email and able to access landing page without image.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
A few things to help:

 * Could you share the email template and landing page you're using
 * Do you see any errors in the Gophish logs?

It sounds like either you have the static directory set wrong, or it's a firewall issue. The above info will help diagnose.

**Comment by vshinde1992** [comment]
[LandingPage.txt](https://github.com/gophish/gophish/files/5051877/LandingPage.txt)
[EmailTemplate.txt](https://github.com/gophish/gophish/files/5051879/EmailTemplate.txt)

Thanks Glen for your response.

Please find attached email template and landing page.
There are no errors in gophish logs.

**Comment by glennzw** [comment]
For your **Landing Page** you need to prepend your directories with `/static/`. For example if you want to serve the the file `foo.png` you would need to copy the file to:

`gophish/static/endpoint/images/foo.png`

and then reference it in your landing page with:

`<img src="/static/images/foo.png">`

For your **Email Template** you need the full URL to the remote image, not just the relative path. i.e:

Bad: `<img src="/images/LandingPage1-SpearPhishing.png">`  
Good: `<img src="http://<gophishserver>/images/LandingPage1-SpearPhishing.png">`

You can also embed the images as Base64 in both cases.

**Comment by vshinde1992** [comment]
Thanks Glenn for your response.

I have tried with your suggestions, however unable to import images in both email template and landing page within GoPhish. However earlier with my approach I am able to import images in GoPhish, but end users are unable to see images post opening emails.
Please find attached snap of gophish application and enduser landing page for reference.
![GoPhish-LandingPage](https://user-images.githubusercontent.com/68010547/89875629-7e0deb80-db8b-11ea-8d8b-a732427ecd0c.PNG)
![Enduser-LandingPage](https://user-images.githubusercontent.com/68010547/89875649-8403cc80-db8b-11ea-9346-badfdffa1c0c.PNG)

**Comment by glennzw** [comment]
If you right click the non-rendering image and select 'open in new tab' - what URL does it give you?

**Comment by vshinde1992** [comment]
Hello Glenn,

Images in Landing page are non-interactive and there are no link maped against it. However I have tried to link below URL and it giving 404 error.
https://<phishing-server>/images/LandingPage1-SpearPhishing.png

**Comment by glennzw** [comment]
As mentioned above, you'll need to prepend the image URL with `/static/` :

`https://(phishing-server)/static/images/LandingPage1-SpearPhishing.png`

That is, after you've added the images to the `static/endpoint/images/` directory

See https://docs.getgophish.com/user-guide/documentation/landing-pages

Hope this helps!

**Comment by vshinde1992** [comment]
Thanks Glenn, I have used below format and its working fine now for Landing page. All images are visible to enduser :)
https://(phishing-server)/static/images/LandingPage1-SpearPhishing.png

However I have used same above format for email template but still images are not visible for enduser. I have also tried with below format but no luck :(

1. https://(phishing-server)/images/LandingPage1-SpearPhishing.png
2. https://(phishing-server)/static/LandingPage1-SpearPhishing.png

**Comment by glennzw** [comment]
> 1. https://(phishing-server)/images/LandingPage1-SpearPhishing.png
> 2. https://(phishing-server)/static/LandingPage1-SpearPhishing.png

These URLs don't have the '/static/images` component.

You need:

`https://(phishing-server)/static/images/LandingPage1-SpearPhishing.png`

Assuming your running over SSL, otherwise http://....

**Comment by vshinde1992** [comment]
Thanks Glenn for all your help :)

Email template and landing page related issues got sorted out and enduser are able to see all images now.

**Comment by glennzw** [comment]
Great! Happy phishing.
