### ISSUE TITLE
Site not being copied entirely

### ISSUE THREAD

**Issue by Oplaa7** [gophish/gophish#1933]
**What version of Gophish are you using?:** 
Gophish V0.10.1 on Windows 10 for testing purposes

**Brief description of the issue:** 
I try to copy a landing page from the following site ( https://mijn.hoppenbrouwerstechniek.nl/#/ ) But when i do it copies everything but the login box ( or the password reset one when you have the specified link for that). Im currently trying to use this page to test our internal personel for phishing.
So it copies everything from the blue line and up but not the boxes.
I think its becouse they arent actually on that site but just a redirection?

**What are you expecting to see happen? :**
Succesfully copy the site including the login boxes and buttons that go with that.

**What are you seeing happen?**
Everything from the blue line and up is copied the rest is not getting copied.

**If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:** https://mijn.hoppenbrouwerstechniek.nl/#/

**Please provide any terminal output that may be relevant below:**
Not relevant i think

**Insert output here**
Not relevant i think

**Please provide as many steps as you can to reproduce the problem:**
 * Step 1 - Copy the url
 * Step 2 - Paste it in the landing page copy tool
 * Step 3 - Not everything from the site being copied

**Additional :** 
Im not that experienced with making websites or html and am currently doing this as a internship assignment. I would love it if someone could help me out with this problem!

**Comment by Oplaa7** [comment]
**Update!**

I fixed a loginbox, its not perfect but it works!
Now it only doesnt save the username when you login.
It says data submitted but doesnt show what i put in like it does with the other tests i did.

Does anyone have any idea why? I hae ''capture submitted data'' enabled.

**Source Code :**

<!DOCTYPE html><html lang="nl"><head>
</head>
<body><meta http-equiv="Content-Type" content="text/html; charset=utf-8"/><meta name="copyright" content="Copyright 2020 triptic (http://www.triptic.nl). All Rights Reserved."/><meta name="generator" content="iris 3.16.38 (qdo 7.16.26)"/><meta name="creator" content="triptic bv"/><meta name="format-detection" content="telephone=no,date=no,address=no,email=no"/>

<base href="https://mijn.hoppenbrouwerstechniek.nl/"/>
<link href="content/builds/Xw4pLg/custom/triptic-projects/hoppenbrouwers/Maintemplate/Intranet/css/main-social.scss.css" rel="stylesheet" type="text/css"/>
<link href="content/builds/Xw4pLg/node_modules/nprogress/nprogress.css" rel="stylesheet" type="text/css"/>
<link href="content/builds/Xw4pLg/packages/iris/iris/Maintemplate/Iris_fixed/Templates/css/incompatible-browser-check.scss.faf1590a90fca07de23dd98e7a89beadb16aa2ef.css" rel="stylesheet" type="text/css"/>
<link href="content/builds/Xw4pLg/custom/triptic-projects/hoppenbrouwers/Maintemplate/Intranet/css/print.scss.css" media="print" rel="stylesheet" type="text/css"/><script type="text/javascript" data-qdo-original="node_modules/jquery/jquery.js" src="content/builds/Xw4pLg/node_modules/jquery/jquery.js"></script><script type="text/javascript" data-qdo-original="node_modules/raven-js/dist/raven.js" src="content/builds/Xw4pLg/node_modules/raven-js/dist/raven.js"></script><script type="text/javascript">
                var qdo_clientStartTime = new Date(); // this must be set as early as possible to calculate qdo.serverTime better
                (function() {
                    'use strict';
                    var sendError = true;
                    $(window).on('beforeunload unload', function() {
                        // note that safari mobile and maybe other browsers do not fire these events
                        sendError = false;
                    });
                    window.qdo = {}; // needed for ('qdo' in window) check below
                    Raven.config('https://dummy@localhost:9000/2', {
                        autoBreadcrumbs: {
                            console: false
                        },
                        transport: function (options) {
                            if (
                                sendError!==undefined
                                && sendError
                                && ('qdo' in window) // variables might have been unset after unload of safari
                                && ('jQuery' in window) // variables might have been unset after unload of safari
                                && (
                                    !('active' in qdo) // qdo not initialized yet
                                    || qdo.active // don't do this when qdo is deactivated
                                )
                            ) {
                                jQuery.ajax({
                                    url: '/packages/iris/iris/reportJavascriptError.php?cm_lg=nl',
                                    type: 'POST',
                                    data: JSON.stringify(options.data),
                                    contentType: 'application/json'
                                });
                                sendError = false; // do not send any following errors because the current error might be causing any following errors
                            }
                        }
                    }).install();
                })();
            </script>
<title>- iris</title>
<meta name="HandheldFriendly" content="True"/><meta name="MobileOptimized" content="320"/><meta name="viewport" content="width=device-width,minimum-scale=1.0,initial-scale=1.0"/><meta name="apple-mobile-web-app-capable" content="yes"/><meta name="mobile-web-app-capable" content="yes"/><meta name="referrer" content="never"/>
<link href="content/builds/Xw4pLg/custom/triptic-projects/hoppenbrouwers/Maintemplate/Intranet/images/favicons/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<link href="content/builds/Xw4pLg/custom/triptic-projects/hoppenbrouwers/Maintemplate/Intranet/images/favicons/favicon-152.png" rel="apple-touch-icon-precomposed"/>
<link href="content/builds/Xw4pLg/custom/triptic-projects/hoppenbrouwers/Maintemplate/Intranet/images/favicons/favicon-152.png" rel="apple-touch-icon-precomposed" sizes="152x152"/>
<link href="content/builds/Xw4pLg/custom/triptic-projects/hoppenbrouwers/Maintemplate/Intranet/images/favicons/favicon-144.png" rel="apple-touch-icon-precomposed" sizes="144x144"/>
<link href="content/builds/Xw4pLg/custom/triptic-projects/hoppenbrouwers/Maintemplate/Intranet/images/favicons/favicon-120.png" rel="apple-touch-icon-precomposed" sizes="120x120"/>
<link href="content/builds/Xw4pLg/custom/triptic-projects/hoppenbrouwers/Maintemplate/Intranet/images/favicons/favicon-114.png" rel="apple-touch-icon-precomposed" sizes="114x114"/>
<link href="content/builds/Xw4pLg/custom/triptic-projects/hoppenbrouwers/Maintemplate/Intranet/images/favicons/favicon-72.png" rel="apple-touch-icon-precomposed" sizes="72x72"/>
<link href="content/builds/Xw4pLg/custom/triptic-projects/hoppenbrouwers/Maintemplate/Intranet/images/favicons/favicon-57.png" rel="apple-touch-icon-precomposed"/>
<link href="content/builds/Xw4pLg/custom/triptic-projects/hoppenbrouwers/Maintemplate/Intranet/images/favicons/favicon-32.png" rel="icon" sizes="32x32"/><meta name="msapplication-TileColor" content="#00649A"/><meta name="msapplication-TileImage" content="content/builds/Xw4pLg/custom/triptic-projects/hoppenbrouwers/Maintemplate/Intranet/images/favicons/favicon-144.png"/><meta name="theme-color" content="#00649A"/>
<div class="browser-upgrade" id="oldbrowser_ie10">
<div class="browser-upgrade-info"><strong>Oeps, je gebruikt een verouderde browser.</strong>
<p>Helaas wordt deze browser niet meer ondersteund. Upgrade je browser voor meer veiligheid, comfort en de beste ervaring.</p>
</div>

<div class="browser-upgrade-browsers"><a class="chrome" href="https://www.google.com/chrome" rel="noopener noreferrer" target="_blank">Google Chrome</a> <a class="firefox" href="https://www.mozilla.com" rel="noopener noreferrer" target="_blank">Mozilla Firefox</a> <a class="edge" href="https://www.microsoft.com/nl-nl/windows/microsoft-edge" rel="noopener noreferrer" target="_blank">Microsoft Edge</a> <a class="safari" href="https://www.apple.com/safari" rel="noopener noreferrer" target="_blank">Apple Safari</a></div>
</div>
<script type="text/javascript">
            (function() {
                /*@cc_on
                    if (/^(10)/.test(@_jscript_version)) {
                        document.getElementById('oldbrowser_ie10').className += ' browser-upgrade-is-visible';
                    }
                @*/
            }());
        </script><noscript>
            <div class="browser-javascript">
                <p><strong>Oeps, om dit intranet optimaal te bekijken moet je browser JavaScript ondersteunen.</strong></p>
                <p>JavaScript staat momenteel uit in je browser. Schakel JavaScript in.</p>
            </div>
        </noscript>

<div class="sitewrap" data-test-id="sitewrap" id="iris_iris_sitewrap">
<div class="headerwrap">
<div class="system-notifications environment-state" id="iris-system-notifications">
<div id="environment-state"> </div>

<div class="environment-state-network-error" id="network-error">
<div class="system-notification system-notification-network-error" id="iris_iris_workflow_network_error" style="display: none;">
<div class="sitewidth">
<div class="system-notification-message"><svg aria-hidden="true" class="icon icon-system-notification"><use xlink:href="content/builds/Xw4pLg/packages/iris/iris/Maintemplate/Iris_fixed/images/sprite_icons.svg#internet-not-connected"></use></svg>Oeps, het lijkt erop dat je geen internetverbinding hebt! Controleer je verbinding.</div>
</div>
</div>
</div>
</div>

<div class="system-notifications" id="system-notifications"> </div>
<script type="text/javascript">
                //<![CDATA[
                    var isisSystemNotificationsPosition = function() {
                        var $irisSitewrap = $('#iris_iris_sitewrap');
                        var irisSystemNotifications = $('#iris-system-notifications');
                        var irisSystemNotificationsHeight = irisSystemNotifications.height();
                        var viewportHeight = $(window).height() / 2;
                        var irisSystemNotificationsStickyClass = 'system-notifications-sticky';
                        var irisSystemNotificationsStickyScrolledClass = 'system-notifications-sticky-is-scrolled';

                        if (irisSystemNotificationsHeight < viewportHeight) {
                            $irisSitewrap.css('margin-top', irisSystemNotificationsHeight);
                            irisSystemNotifications.addClass(irisSystemNotificationsStickyClass);
                            $(document).scroll(function() {
                                if ($(document).scrollTop() > 0) {
                                    irisSystemNotifications.addClass(irisSystemNotificationsStickyScrolledClass);
                                } else {
                                    irisSystemNotifications.removeClass(irisSystemNotificationsStickyScrolledClass);
                                }
                            });
                        } else {
                            $irisSitewrap.css('margin-top', '');
                            irisSystemNotifications.removeClass(irisSystemNotificationsStickyClass);
                        }
                    };

                    isisSystemNotificationsPosition();

                    $(window).resize(function() {
                        isisSystemNotificationsPosition();
                    });
                //]]>
                </script>

<div class="header sitewidth clear" role="banner">
<div class="placeholder"><a class="logo" href="/" title="Homepage"><img alt="Hoppenbrouwers" height="41" src="content/builds/Xw4pLg/custom/triptic-projects/hoppenbrouwers/Maintemplate/Intranet/images/hoppenbrouwers.svg" width="233"/></a></div>


<div class="headercontent">
<div class="appmenuwrap" data-test-id="servicemenus" id="servicemenus"> </div>
</div>
</div>
</div>


<div class="navwrap">
<div class="menuwrap">
<div class="nav sitewidth clear">
<div class="menu" id="menu" role="menubar"> </div>


<div class="toolboxouter" id="toolboxouter" style="display:none"> </div>
</div>
</div>
</div>


<div class="mainwrap">
<div class="main sitewidth clear">
<div aria-labelledby="breadCrumbsLabel" class="breadcrumbs clear" id="breadcrumbs"> </div>


<div class="clear" id="mainHeader"> </div>

<div class="sidebarwrap">
<div class="sidebar clear" id="sidebar" style="display:none">
<div data-test-id="sidebarcontent" id="sidebarcontent"> </div>
</div>
</div>

<div class="content" id="content" role="main" style="">
<div class="inner" data-test-id="inner" id="inner">
<div class="userlogin">
<form accept-charset="utf-8" action="" class="formview" id="loginForm" method="post"><input id="formdata_loginForm__form_xsrf_token" type="hidden" value="8f9be45636675ec378a42678a2"/>
<h1>Inloggen</h1>

<fieldset>
<div class="formrow">
<div class="colone"><label for="formdata_loginForm__username">Gebruikersnaam of e-mailadres <span class="required">*<em>Verplicht veld</em></span></label></div>

<div class="coltwo"><input class="text" id="formdata_loginForm__username" maxlength="255" style="width: 130px" type="text" value=""/></div>

<div class="clear"> </div>
</div>

<div class="formrow">
<div class="colone"><label for="formdata_loginForm__password">Wachtwoord <span class="required">*<em>Verplicht veld</em></span></label></div>

<div class="coltwo"><input autocomplete="current-password" class="text" id="formdata_loginForm__password" maxlength="255" style="width: 130px" type="password" value=""/></div>

<div class="clear"> </div>
</div>

<div class="formrow">
<div class="colone"><label for="formdata_loginForm__remember_login">Onthoud login</label></div>

<div class="coltwo">
<div class="switch"><input id="formdata_loginForm__remember_login" type="checkbox" value="1"/></div>
<span class="tooltipicon" id="showRememberLoginTooltip"><span>(?)</span></span></div>

<div class="clear"> </div>
</div>

<div class="formrow">
<div class="colone"> </div>

<div class="coltwo"><button class="button" type="submit"><svg class="icon icon-apply"><use xlink:href="content/builds/Xw4pLg/packages/iris/iris/Maintemplate/Iris_fixed/images/sprite_icons.svg#apply"></use></svg> Inloggen</button></div>

<div class="clear"> </div>
</div>
</fieldset>

<div class="textfoot"><a href="/wachtwoord-vergeten">Problemen met inloggen?</a></div>
</form>
<script type="text/javascript">
            //<![CDATA[
                $(function() {
                    $('#loginForm').find('button[type=submit]').attr('disabled', false);
                });
            //]]>
            </script></div>
</div>
</div>
</div>
</div>
</div>
</body></html>

**Comment by jordan-wright** [comment]
It's likely the case that Javascript is catching the form submission and trying to override how that's handled. You'll need to remove that relevant JS to make sure your form submits correctly.

**Comment by jordan-wright** [comment]
Here is a recently added FAQ that will likely help out: https://docs.getgophish.com/user-guide/faq#submitted-form-data-isnt-being-captured

**Comment by Oplaa7** [comment]
**Solution**

I changed the following lines of code for it to work : 
**Not working :** div class="coltwo"input class="text" id="formdata_loginFormusername" maxlength="255" style="width: 130px" type="text" value="" /></div
**Working :**div class="coltwo"input name="text" id="formdata_loginFormusername" maxlength="255" style="width: 130px" type="text" value="" /></div

So the class was changed to name and now it saw it as a user login field and recorded the credentials.
No java  scripts had to be removed
