### ISSUE TITLE
Active campaign shows up in archived campaigns tab instead of the active campaigns tab

### ISSUE THREAD

**Issue by gr4ssi** [gophish/gophish#1934]
What version of Gophish are you using?: 
0.10.1 

Brief description of the issue: 
I archived one campaign, and now another one which is still active is also shown in the archived section.

What are you expecting to see happen? :
I'd expect to see the active campaign in the active section instead of the archived section.

What are you seeing happen?
I see an active campaign in the archived section

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Archive an open campaign
 * Step 2 - See that suddenly, an active one is also in the archived section. 

![grafik](https://user-images.githubusercontent.com/19840345/90147362-677db500-dd82-11ea-8aba-200a025c45a0.png)

**Comment by jordan-wright** [comment]
This was fixed as part of https://github.com/gophish/gophish/commit/b684fb4ebd37c9f4c6e66a410d34c9cfa428ff5c, just hasn't made it into a release yet.

Thanks for getting in touch!
