### ISSUE TITLE
Sending limit reached

### ISSUE THREAD

**Issue by namanagrawal94** [gophish/gophish#1939]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: V 0.10.1

Brief description of the issue: I am unable to send emails to 10,000 users in my organization due to email quota exceed issue. I am using Gsuite email.

What are you expecting to see happen? : Emails to deliver to all 10,000 users.

What are you seeing happen? Error after 500 users.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
Unfortunately this is a GMail issue, not a gophish issue, so there's not much we can do to help.

I'd recommend you run your own mailserver.

**Comment by namanagrawal94** [comment]
Hi Glenn,

By any chance, Di you have a guide on how to setup our own mailserver?

Best regards,
Naman
