### ISSUE TITLE
Redirect Issue

### ISSUE THREAD

**Issue by Natep86** [gophish/gophish#1941]
What version of Gophish are you using?:  newsest Download

Brief description of the issue: I have set up everything. I have a domain with google, I have set up via Digitalocean, I have configured the DNS properly. BUT, the Email Template is not redirecting to the Landing page. I have done searches in here and have found multiple issue that you have resolved. But yet none seem to fix mine. 
When creating the campain, in the "URL" field, I am imputing the digitalocian IP, which is also configured in the DNS of my domain. I have even used the domain www itself. I am lost as to why its not redirecting to the landing page. All im getting is MyUrl/?rid=YrwBMln

What are you expecting to see happen? : I expected the links to trace back to the landing page

What are you seeing happen? A loading white screen that ends with "Unable to connect"

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```LANDING PAGE:
Im using a few downloaded from Gethub. I have checked the links and all refer back to {{.URL}}

**Comment by agrawalpt** [comment]
It would be very helpful if you could provide the below information to understand what's happening...
did you hosted the landing page on that domain? Can you the share screenshot of html code of the landing page and also the url field?

**Comment by glennzw** [comment]
Closing out as we haven't heard back, feel free to re-open.
