### ISSUE TITLE
Cant launch gophish 

### ISSUE THREAD

**Issue by Xun-876** [gophish/gophish#1943]
when ever I try to launch gophish by "sudo ./gophish" its saying command not found. I'm using kali linux 64bit

**Comment by jordan-wright** [comment]
Try `chmod +x gophish` and then running it again.

**Comment by Xun-876** [comment]
Okay, now when I try to launch it its giving me an error which state "too many colons in address"

**Comment by jordan-wright** [comment]
What does your config.json look like? My guess is that one of your IP address/port pairs has too many colons.

**Comment by Xun-876** [comment]
![20200910_211100.jpg](https://user-images.githubusercontent.com/62703917/92843242-280aae80-f3aa-11ea-965f-e79a851428ba.jpg)

**Comment by jordan-wright** [comment]
127.0.0.1, not 127.0.0:1

**Comment by Xun-876** [comment]
![Screenshot_20200914-214329_WhatsApp.jpg](https://user-images.githubusercontent.com/62703917/93159280-7b933a00-f6d3-11ea-9669-82dfa3471df1.jpg)

**Comment by Xun-876** [comment]
I'm getting this error now

**Comment by edermi** [comment]
According to the log, it seems your database is readonly.

**Comment by Xun-876** [comment]
How do I change it
