### ISSUE TITLE
SSL Certificate import for Landing Page in GoPhish

### ISSUE THREAD

**Issue by vshinde1992** [gophish/gophish#1944]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue: 
We have successfully configured GoPhish landing page over port 80 and its working fine. Now we want to configure landing page over port 443. All necessary changes are already done in config.jason file and its working with warning of certificate.
Please help me on how to import/use SSL certificate for landing page in GoPhish.

What are you expecting to see happen? : Enduser should able to access landing page over port 443 without certificate warning.

What are you seeing happen?Ensusers are getting certifiate warning while accessing landing page.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Creating an SSL certificate is out of the scope for the support we provide. You should go through your domain provider or use something like LetsEncrypt. Then, you just point the `cert_path` and `key_path` settings in `config.json` (under the `phish_server` section) to point to the certificate and corresponding key. In the future, we may support LetsEncrypt out of the box, but for now you'll need to create your certificate outside of Gophish.

You can find an example of how to use LetsEncrypt [here](https://www.n00py.io/2017/09/phishing-with-gophish-and-letsencrypt/).
