### ISSUE TITLE
Max attempts exceeded - No Such Host

### ISSUE THREAD

**Issue by Rosariodalima** [gophish/gophish#1945]
There is a message appearing when I try to do a test email that says "Max attempts exceeded.No such host". Despite, I have sent a test email from the same email from 2 days

**Comment by jordan-wright** [comment]
In this case, Gophish is saying that it is unable to resolve the hostname used in your `Host` field in the sending profile.

My recommendation would be to check if the domain resolves using something like `nslookup` or `dig`. Either way, this will be a DNS issue, not a Gophish issue.
