### ISSUE TITLE
create landing page: template error

### ISSUE THREAD

**Issue by julmaurepas** [gophish/gophish#1947]
Hi,

I created the landing page with http://google.com and it works.
So I created an another landing page with http://github.com/login and it doesn't work.
I've a message: template: template:55:function "className" not defined.
I don't understand it and can you help me, please ?

Best regards

**Comment by glennzw** [comment]
It works for me, are you on the latest version? Can you submit a screenshot of the error?

<img width="635" alt="Screenshot 2020-08-30 at 12 24 11" src="https://user-images.githubusercontent.com/3966613/91656788-6606f900-eab3-11ea-87ca-ab96e4ead2ab.png">

**Comment by glennzw** [comment]
Aha, when I try save the page I get the same error! This is happening because in the GitHub HTML source there are two places where the gophish template placeholder format is used:

```
<div class="flash flash-full  {{ className }}">
```

```
<div>{{ message }}</div>
```

If you edit the source before saving and remove these it works.

**Comment by julmaurepas** [comment]
Hi,

Thanks a lot. Can u say me these file to modify, please ?

Best regards

**Comment by jordan-wright** [comment]
After importing a site, you need to remove any instance of {{ or }}, as those are used by Gophish. It’s not a file you need to modify - it’s the HTML you see in the editor after importing a site.
