### ISSUE TITLE
The select2('data') method was called on an element that is not using Select2.

### ISSUE THREAD

**Issue by GildedHonour** [gophish/gophish#1949]
Gophish has been installed via go get, v 0.10.1

I'm creating, laucnhing a campaign and getting an error

<img width="1271" alt="Captura de pantalla 2020-08-28 a las 17 43 18" src="https://user-images.githubusercontent.com/2032888/91559782-38da0f80-e928-11ea-9c30-69a96d6e79d2.png">

**Comment by GildedHonour** [comment]
It ocurrs when no group has been selected

**Comment by jordan-wright** [comment]
<img width="693" alt="Screen Shot 2020-08-28 at 2 11 24 PM" src="https://user-images.githubusercontent.com/1317288/91606789-5d3de800-e938-11ea-9473-808c4909ab90.png">

This is the error I receive when I haven't set any groups in the current `master` branch. Can you try with the just release v0.11.0 and let me know if you still see the same issue?

**Comment by glennzw** [comment]
Closing out as haven't heard back, and I get the same result as Jordan with 0.11.0. Feel free to reopen if you're still having this issue on the current master.

**Comment by afreeland** [comment]
I just pulled the repo this evening, built docker, and have it running locally but having a similar issues with that error.  
<img width="1567" alt="image" src="https://user-images.githubusercontent.com/3135030/181159544-503c2bf8-1ead-4c37-b15b-09ce67317f5a.png">

<img width="1569" alt="image" src="https://user-images.githubusercontent.com/3135030/181159671-39d4c0c9-4c81-4e95-9b7e-21ddf1c3addc.png">


It will just spin indefinitely and never actually create the campaign.   The `select2` is a js library for dropdowns right, haven't used that guy in a looong time.  Can debug a little further to find out what exactly is going on, unless its known already?

**Comment by afreeland** [comment]
Ah I think I see
https://github.com/gophish/gophish/blob/master/static/js/src/app/campaigns.js#L205-L208

I need to create a landing page
https://github.com/gophish/gophish/blob/master/templates/landing_pages.html#L3-L19

First time using this tool, sorry for adding noise ;)
