### ISSUE TITLE
Feature: Internationalization

### ISSUE THREAD

**Issue by firebitsbr** [gophish/gophish#195]
Tip: It would be interesting to have options Internationalization as Feature.

**Comment by jordan-wright** [comment]
@firebitsbr - can you expand a bit on this? What do you mean by having "Internationalization as a feature"?

**Comment by jordan-wright** [comment]
Going ahead and closing this for now. @firebitsbr, if you can provide any more details on what you mean by having "Internationalization as a feature", we'll determine if we can re-open.
