### ISSUE TITLE
Sending a test email - it'll get stuck

### ISSUE THREAD

**Issue by GildedHonour** [gophish/gophish#1950]
Gophish has been installed via go get, v 0.10.1

No errors in the terminal, nor in the console of a browser. "Pending"

<img width="1104" alt="Captura de pantalla 2020-08-28 a las 17 49 46" src="https://user-images.githubusercontent.com/2032888/91560146-daf9f780-e928-11ea-9f48-79a4e192b67a.png">

**Comment by jordan-wright** [comment]
Hi @GildedHonour,

I've tested locally with the current `master` branch, and don't see any issues on my end. Do the logs in Gophish indicate what might be the cause? If it's a timeout, then I'm guessing there's probably something network related happening.

**Comment by GildedHonour** [comment]
@jordan-wright I've found out that the host should've contained a port as well.

**Comment by CalfCrusher** [comment]
Same exact problem here, also my timezone server is UTC
