### ISSUE TITLE
I've lost my Gophish account

### ISSUE THREAD

**Issue by Jean3795** [gophish/gophish#1951]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue: 

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by Jean3795** [comment]
When I logged out of Gophish I tried log again and it didn´t let me, even by using the default credentials.

**Comment by jordan-wright** [comment]
Hi there,

You can reset the password using the method found [here](https://github.com/gophish/gophish/issues/362#issuecomment-337859010).

**Comment by Jean3795** [comment]
How do I do 

> Hi there,
> 
> You can reset the password using the method found [here](https://github.com/gophish/gophish/issues/362#issuecomment-337859010).

How can I do that?, I have Windows 10 btw

**Comment by jordan-wright** [comment]
You need to update the database as shown in that comment. My guess is that you’re using SQLite, so you need a SQLite client. Windows has some available with a quick Google search.

**Comment by Jean3795** [comment]
I've downloaded a program called DB Browser for SQ Lite, do you know that program and if you know about that program could you show how can I restore my account?

I have the script but I don´t exactly know what to do with it, because I don´t understand very well the program. Could you please show me how to do it?

**Comment by jordan-wright** [comment]
How to use particular SQLite tools is beyond the scope of the support we provide here.

But the concept should be straightforward, just open the database and run the sql command provided in that issue comment. That should restore access to your account.

**Comment by Jean3795** [comment]
I've downloaded the Windows SQLite but when I try to execute the command line it doesn´t let me. Could you please explain me how can I run the command line on sqlite3? I have tried various ways and still keeps the same.

§ yum install -y sqlite ||apt-get install -y sqlite3 libsqlite3-dev
§ sqlite3 gophish.db 'update users set hash="$2a$10$IYkPp0.QsM81lYYPrQx6W.U6oQGw7wMpozrKhKAHUBVL4mkm/EvAS" where username="admin";'

**Comment by Jean3795** [comment]
Excuse me if you notice that I am bothering you a lot but this is part of some college work (experiment) that I am doing and I have not been able to progress because I cannot find a way to reset my account. I have tried several ways and none of them have any effect, it would be very helpful for you to collaborate in that part, really.

**Comment by jordan-wright** [comment]
I’m afraid the details of how to use SQLite are beyond the scope of the support we offer. This forum is solely focused on helping troubleshoot Gophish issues.

In general, the flow should be the same: you use your SQLite application to open the database- its a file in your Gophish directory. You then run the SQL command from the linked comment to update the database, resetting the password.

Beyond that, there isn’t much we can do to help resolve the issue. I’m afraid I don’t have the time to spin up a Windows virtual machine, install Gophish, install a SQLite client, and then show screenshots of the entire process. I’d encourage you to look through the documentation for your SQLite client on how to open a database and run a SQL command, since everything should be in that documentation.

**Comment by Jean3795** [comment]
If I reinstall the app, could I create a new account?

**Comment by jordan-wright** [comment]
If you don’t care about your data, just delete the gophish.db file and restart Gophish.

**Comment by Jean3795** [comment]
Done, thanks for the help

**Comment by jordan-wright** [comment]
You bet! Let us know if run into any Gophish issues moving forward.
