### ISSUE TITLE
My landingpage still asking to enter a password even after clicking submit

### ISSUE THREAD

**Issue by northgod123** [gophish/gophish#1954]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  I use gophish-v0.10.1-windows-64bit

Brief description of the issue:  I have been redirected to the landing page but when i fill in username and password and click submit it keeps asking me to enter password

What are you expecting to see happen? : I'm expecting to see it redirect me to the original website login page after clicking submit and accepting credentials

What are you seeing happen? It keeps asking me to enter password after clicking submit

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by LaggerP** [comment]
Hi! The new gophish version has new password requirements. 

If you see the message of [documentation](https://docs.getgophish.com/user-guide/getting-started) the new gophish version force you to change the admin password after initial login.

When you run gophish for the first time gophish generate a temporal password. You can see this password in gophish console

![image](https://user-images.githubusercontent.com/29312124/91726222-4553a780-eb76-11ea-8490-e5875dad44a2.png)

Use that password to login and gophish show the next view to change the password

![image](https://user-images.githubusercontent.com/29312124/91726367-8055db00-eb76-11ea-98d5-0b9b7eceb738.png)

After that you can login with the _admin username_ and your _new password_


You can see the code in this [commit](https://github.com/gophish/gophish/commit/bf76f86ea4bacb3ae2e92f89d42d1134beac802c)

**Comment by glennzw** [comment]
@LaggerP Sounds like this is a landing page issue, rather than a admin login issue.

@northgod123 Make sure you're using a POST request, with no form action. Here's a working example:

```html
<html>
 <body>
  <form action="" method="post" name="form">
    <label>Username:</label> <input name="username" type="text"/><br/>
    <label>Password:</label> <input name="password" type="password"/><br/>
   <input id="login" name="login" type="submit" value="Login"/>
  </form>
  </body>
</html>
```

**Comment by northgod123** [comment]
Yes I think it’s a landing page problem but, I didnt create the landing page myself. I just exported it into the Gophish landing page feature. So I supposed it’d be all set up already

**Comment by glennzw** [comment]
You'll need to share the code here if you'd like us to debug it.

**Comment by northgod123** [comment]
Okay I sure will in a bit

**Comment by glennzw** [comment]
Closing this issue as haven't heard back.
