### ISSUE TITLE
Email not receiving on other end.

### ISSUE THREAD

**Issue by D-k19** [gophish/gophish#1955]
i'm using amazon ec2 instances and gophish is configured on  one of the server and and a domain is configured with SES and Route53, All the records are good. And for smtp relay i'm using sendgrid in gophish configuration to send email using sedngrid relay. I have two domains one was configured 2 months back and that is working fine, but now i  configured another domain to send emails through, But when i send a test email using gophish it says "Email sent" same shown in the logs, but it is not recieved on my gmail address.

**Comment by glennzw** [comment]
If gophish is dispatching the email, and SendGrid is receiving it, there's not much more support we can offer, unfortunately.

**Comment by jordan-wright** [comment]
@glennzw is correct - from Gophish's end, it thinks the email was sent successfully. It's entirely possible there's a spam filter on the other end that's dropping the email. If you are encountering this issue, work with your sysadmin or with your client to ensure that the IP address from your Sendgrid account is allowlisted in their SMTP servers.
