### ISSUE TITLE
login v.0.11.0  - sorry I see the msg: - Thanks for help

### ISSUE THREAD

**Issue by cherrera0001** [gophish/gophish#1957]
Hi, my name is Cristóbal Herrera, I need help, please!
I'm install gophish in zeusOs (S.O debian equals kali linux) but want apply one login and my response is " Invalid Username/Password "

I put user: admin and pass: gophish - ¿Is correctly? - I proof v.08.0 but this version my return other error. 

![imagen](https://user-images.githubusercontent.com/19656010/91876571-d5632100-ec4a-11ea-90e6-2d6a59d603bf.png)

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by cherrera0001** [comment]
After running the Gophish binary, open an Internet browser to https://localhost:3333 and login with the default username and password listed in the log output. e.g.

time="2020-07-29T01:24:08Z" level=info msg="Please login with the username admin and the password 4304d5255378177

**Comment by jordan-wright** [comment]
Glad to hear you got this issue resolved!
