### ISSUE TITLE
I can't sign into gophish running on a  vps after reinstalling, PLEASE HELP....

### ISSUE THREAD

**Issue by MccoyTesting** [gophish/gophish#1959]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue: Gophish v0.10.1

What are you expecting to see happen? : TO LOG INTO MY GOPHISH DASHBOARD

What are you seeing happen? INVALID USERNAME/PASSWORD

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 - 
 
I can't log into gophish after reinstalling it on a vps, i have tried my password and the gophish default password but it's not working, It runs successfully but can't login... about the sqlite3 which i have installed but i can't find my way around editing the gophish.db files cos i don't know how to do that while it's running on a vps, Please help me out.... I would appreciate a simple code that would reset the password please...

**Comment by jordan-wright** [comment]
When you start up Gophish, do you see a temporary password printed to the terminal? If so, use that to login. We've removed the default password in later versions of Gophish as you can see [here.](https://docs.getgophish.com/user-guide/getting-started#running-gophish).

Otherwise, you'll need to reset your password using SQLite using the method found [here](https://github.com/gophish/gophish/issues/362#issuecomment-337859010).

**Comment by MccoyTesting** [comment]
> When you start up Gophish, do you see a temporary password printed to the terminal? If so, use that to login. We've removed the default password in later versions of Gophish as you can see [here.](https://docs.getgophish.com/user-guide/getting-started#running-gophish).
> 
> Otherwise, you'll need to reset your password using SQLite using the method found [here](https://github.com/gophish/gophish/issues/362#issuecomment-337859010).

Thank you very much! It's worked .. the password was staring at me on the terminal all this while.
