### ISSUE TITLE
Links {{.URL}}  shows faint strikethough in emails! What other code could be used for this please???

### ISSUE THREAD

**Issue by MccoyTesting** [gophish/gophish#1960]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  Newest

Brief description of the issue:  landing page link with {{.URL}} showing in emails with fainted strikethough on the link text... making it unclickable

What are you expecting to see happen? : the links should be live and  clickable!

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 - 

What method should I use to make this links live and clickable???

**Comment by jordan-wright** [comment]
This sounds like something happening on the email client side of things. Try sending a test email to an account you control outside of the target system (e.g. to a Gmail account or something). My guess is that the links will be clickable.

In this case, there is nothing that can be done in Gophish to prevent this- you'll need to allowlist the Gophish server from any sort of spam filtering or message modification happening in the receiving mail server.

**Comment by MccoyTesting** [comment]
> This sounds like something happening on the email client side of things. Try sending a test email to an account you control outside of the target system (e.g. to a Gmail account or something). My guess is that the links will be clickable.
> 
> In this case, there is nothing that can be done in Gophish to prevent this- you'll need to allowlist the Gophish server from any sort of spam filtering or message modification happening in the receiving mail server.

Thanks Jordan

But please what do you mean by 
"you'll need to allowlist the Gophish server from any sort of spam filtering or message modification happening in the receiving mail server." ???? Or rather how do I get around this? ??

**Comment by jordan-wright** [comment]
You need to add a spam filtering exception for the Gophish server in your email server so that emails from Gophish aren't susceptible to this kind of modification.

How you do that is entirely dependent on your mail server, and not something we can help with. Additionally, there's not a way around this, since this sounds almost certainly like an (interesting!) defense in place on the mail server side of things.
