### ISSUE TITLE
To Expert Programmers, Please how do I manipulate a heavy JS html code to display Fully in Gophish Landing Page ???

### ISSUE THREAD

**Issue by MccoyTesting** [gophish/gophish#1964]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: Newest

Brief description of the issue: most pages not displaying fully in gophish landing page...

What are you expecting to see happen? : Please how I do manipulate a heavy js html page to dispay fully and most pages displays just half of it content, what should i add/remove to the html code to make it display fully on gophish landing page please?????

What are you seeing happen? How to I make it to display fully??

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
You're going to have to supply the code if you want some help. 

Your browser will be rendering the HTML/JS page - gophish just serves it up.
