### ISSUE TITLE
Cannot login using default username and password

### ISSUE THREAD

**Issue by nellirism** [gophish/gophish#1965]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
V0.11.0-windows-64bit

Brief description of the issue: 
Still cannot login using default username: admin and password: ".... " from the log after running binary. 

$ ./gophish
time="2020-09-13T00:11:15-07:00" level=warning msg="No contact address has been configured."
time="2020-09-13T00:11:15-07:00" level=warning msg="Please consider adding a contact_address entry in your config.json"
goose: no migrations to run. current version: 20200730000000
time="2020-09-13T00:11:16-07:00" level=info msg="Please login with the username admin and the password 29ef3acbf946d314"
time="2020-09-13T00:11:16-07:00" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
time="2020-09-13T00:11:16-07:00" level=info msg="Starting IMAP monitor manager"
time="2020-09-13T00:11:16-07:00" level=info msg="Starting phishing server at http://0.0.0.0:80"
time="2020-09-13T00:11:16-07:00" level=info msg="Starting admin server at https://127.0.0.1:3333"
time="2020-09-13T00:11:16-07:00" level=info msg="Starting new IMAP monitor for user admin"

What are you expecting to see happen? 

Successful login

What are you seeing happen?

Invalid Username/password

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
In the latest version there is no default password- it's generated and printed in the terminal when Gophish starts. You'll see an example in the output you provided.

**Comment by nellirism** [comment]
Jordan,

Thank you I really appreciate your time. I used that password printed on
the terminal when i started gophish. That's my confusion, because the
password generated still didn't work.
I tried again this morning, but still failed log in.

**Comment by jordan-wright** [comment]
Everytime you restart Gophish, if you didn’t reset the password then Gophish will generate a new one and print it to the terminal.

If you could, please take a video showing you starting Gophish, copying the credentials into the login form, and showing it not working. Then we can review the logs to determine what happened.

**Comment by nellirism** [comment]
Jordan,

I tried installing gophish on my macbook and login worked following the same procedure. The same version V0.11.0
I don't know what I did using my PC that is not allowing me to do the same. I was hoping you could help identify the error. 

Also the user guide showed V0.10.1 as the current version on top of the page, you must be in the process of updating that. 

Thank you so much!

**Comment by jordan-wright** [comment]
I’d be happy to help, I just need the information I asked for in the previous comment. Namely, a video of you showing yourself trying to login, it not working, and the output from the Gophish logs.

**Comment by nellirism** [comment]
Ok I'll try sending the video again. Somehow it didn't go through.

**Comment by bakutomas44** [comment]
it did not work, its says invalid user name/ password

**Comment by martirspe** [comment]
When capturing the data it gives me an encrypted password, in the videos I have seen they are in plain text. How can i see it?

**Comment by wisely5** [comment]
Hello, guys, i have issues with Gophish Invalid Username/Password. Can anyone please help me login?
