### ISSUE TITLE
TLS error when connecting to admin interface

### ISSUE THREAD

**Issue by ronimosh** [gophish/gophish#1968]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
**current version: 20200730000000**
Brief description of the issue: 
I just completed setting up the gophish server, and created 2 new pairs of certs (for admin and for phish test). 
The setup is on Azure VM running linux.
When I connect to https://<my server>:3333 the connection fails, and the console says:
2020/09/15 06:08:45 http: TLS handshake error from XXXXX:58034: read tcp 10.0.0.4:3333->XXXXX:58034: read: connection reset by peer
The message repeats multiple times for each connection attempt. 
I AM connecting to HTTPS (not HTTP)
What are you expecting to see happen? :
for the admin interface to appear...
What are you seeing happen?
On the browser - connection failed with the following message:
"An error occurred during a connection to <MYSERVER>:3333. PR_CONNECT_RESET_ERROR"
On the VM console - I get the above error message.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:
config.json file contains the following:
{
        "admin_server": {
                "listen_url": "10.0.0.4:3333",
                "use_tls": true,
                "cert_path": "<...>gophish_admin.crt",
                "key_path": "<...>gophish_admin.key"
        },
        "phish_server": {
                "listen_url": "0.0.0.0:443",
                "use_tls": false,
                "cert_path": "<...>gophish.crt",
                "key_path": "<...>gophish.key"
        },
        "db_name": "sqlite3",
        "db_path": "gophish.db",
        "migrations_prefix": "db/db_",
        "contact_address": "<MY EMAIL>",
        "logging": {
                "filename": "<FILE>.log",
                "level": ""
        }
}

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
- Clean install of gophish from the official binaries
- generated new certs using the openssl commands : 
openssl req -newkey rsa:2048 -nodes -keyout gophish.key -x509 -days 365 -out gophish.crt
openssl req -newkey rsa:2048 -nodes -keyout gophish_admin.key -x509 -days 365 -out gophish_admin.crt

 * Step 2 - 
 
 Try to browse to the admin url HTTPS://<SERVER>:3333

**Comment by jordan-wright** [comment]
Everything looks ok from the configuration side. Doing some googling, it seems that particular error is most often thrown when you have some kind of middlebox or proxy in between you and your connection.

**Comment by jordan-wright** [comment]
Closing this since there haven't been any updates in over a week.
