### ISSUE TITLE
Deleted template causes existing campaign to fail to load.

### ISSUE THREAD

**Issue by StrangeUSB** [gophish/gophish#197]
I created a campaign with a specific template, then I deleted the template, trying to view the campaign again displays a "Campaign no found!" error.  This could probably also be caused by deleting one of the other campaign settings.
```
127.0.0.1 - - [08/Mar/2016:22:22:58 -0600] "GET /campaigns/1 HTTP/1.1" 200 8626 "http://localhost:3333/campaigns" "{User-Agent}"
 2016/03/08 22:22:59 campaign.go:174: record not found: template not found for campaign
 2016/03/08 22:22:59 api.go:95: record not found
127.0.0.1 - - [08/Mar/2016:22:22:59 -0600] "GET /api/campaigns/1?api_key={API_KEY}&{} HTTP/1.1" 404 73 "http://localhost:3333/campaigns/1" "{User-Agent}"
```

**Comment by jordan-wright** [comment]
This is pretty difficult to address *accurately*. Specifically, ```models.GetCampaign``` tries to fetch all the attributes (template, smtp, etc.) from the db and apply it to the JSON result.

Unfortunately, the question is how to proceed if the attribute is deleted. I suppose something I could do is to attempt a load. If it fails (deleted), then I could just set the name of the template or whatever that's returned to "Deleted". That would allow the user to at least be notified that it was deleted.

Thoughts?

**Comment by StrangeUSB** [comment]
Yeah, after looking over that part of the code I see why it gets a little
difficult to do this "correctly".

I'm thinking that as long as there are results of a campaign I think that
they should be returned. The only time the settings come back into play is
on copying the campaign or eventually resending the emails, right?

I think possibly returning the deleted settings somehow, and notifying the
user if they try to use them again, would probably be the right way to do
this.

**Comment by jcamil** [comment]
Just a thought:

models.GetCampaign – returns both settings and results
models.GetCampaignSettings – queries for and returns settings only
models.GetCampaignResults – queries for and returns results only
