### ISSUE TITLE
Will using gophish with mailchimp or the like trigger an alarm?

### ISSUE THREAD

**Issue by GildedHonour** [gophish/gophish#1970]
If I sign up with mailchimp or the like and use gophish with it, will they likely to ban me or will it trigger an alarm for them so that I'll end up under scrutiny? Is it recommend, in general, to use gophish with mailchimp or the services like it?

It's not me who needs it, because I have my own email server; someone else does, and I need to suggest him a service to use it with.

**Comment by glennzw** [comment]
Each service will have their own spam policy, but in my experience they really don't like you sending out phishing campaigns.

**Comment by jordan-wright** [comment]
@glennzw is correct- every company is different. As general guidelines:

* If it's a free account, you'll probably be blocked quickly. After all, it's their platform and they can protect it however they deem fit.
* If it's a paid account, I encourage you to talk with customer support about your use case. They can give guidance on what's acceptable and what's not.

Either way, the goal is transparency. Don't hide and hope to not get blocked. Be proactive and let them guide you towards their recommendations on running safe, friendly phishing simulations.
