### ISSUE TITLE
Using a newly bought domain.

### ISSUE THREAD

**Issue by ronbilski159** [gophish/gophish#1974]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.10.1

Brief description of the issue: Not an issue haha, need to add a gophish server on the domain I have. How do I create it? need some help with it . tnx. !

What are you seeing happen? using my domain - lets say x.com - as a dashboard (server) of gophish - gophish.x.com:3333 or something 

Thanks guys.

**Comment by edermi** [comment]
You need to point the DNS entry for gophish.x.com to the IP of your gophish server.
