### ISSUE TITLE
In what event "capture credentials" wouldn't be necessary?

### ISSUE THREAD

**Issue by naddika** [gophish/gophish#1977]
There's a checkbox next to "capture credentials" on a phishing page settings. I figure that capturing them is one of the main goals.  In what event the admin wouldn't want to capture them? 

And, where would they actually be seen afterwads, if "captured" was checked and a user entered them on a phishing page?

**Comment by jordan-wright** [comment]
It's not always the case that administrators would want to capture credentials. Often, they want to know only if the user tried to submit credentials. This gives an indication that credentials were likely submitted without storing them in Gophish which could be a privacy risk.

If you have the "capture credentials" option selected, you can view them in the campaign results screen. More information can be found in [our documentation](https://docs.getgophish.com/user-guide/documentation/campaigns#viewing-result-details)
