### ISSUE TITLE
Improvements to page titles

### ISSUE THREAD

**Issue by nmalcolm** [gophish/gophish#198]
I noticed all page titles are prefixed with "Gophish - ". With multiple tabs open, this can become confusing. I propose this is moved to become a suffix instead.

Campaign results pages could also do with some changes to include the campaign name in the title, instead of a generic "Campaign Results" title.

These changes would make managing multiple campaigns easier. :smiley:

**Comment by jordan-wright** [comment]
Agreed - fixed!
