### ISSUE TITLE
Capture Credentials Working

### ISSUE THREAD

**Issue by mansichauhan27** [gophish/gophish#1980]
Hi, can you please tell me whether landing page data is passed on to server but not saved in database while submitting even if captured data is set to false?

Thanks in advance.

**Comment by glennzw** [comment]
No data is submitted (or stored) if captured data is set to false. You will get a submission event though:

<img width="587" alt="Screenshot 2020-09-21 at 19 27 32" src="https://user-images.githubusercontent.com/3966613/93800357-bc91ce00-fc40-11ea-8697-e3c2d3f33573.png">

**Comment by mansichauhan27** [comment]
Is data is not captured in database or data is not even passed to the server when form is submitted?

**Comment by glennzw** [comment]
Data is not passed to the server (it does not leave the browser).

This is based on my test with an inline proxy (Burp). A POST request is submitted with no content.
