### ISSUE TITLE
GoPhish Health Check URL

### ISSUE THREAD

**Issue by gophish-test-user** [gophish/gophish#1982]
Are there any dedicated health check URL and port for GoPhish?

**Comment by glennzw** [comment]
I'm not sure what you mean by health check, but no. The console output will give you insight into what's going on, and output any errors there.

**Comment by S0larflare** [comment]
I would guess he means like a heartbeat, to monitor that things are running without an error.

I’d say just monitor the process or port 3333 for the admin interface being available

Sent from my iPhone

On 21 Sep 2020, at 18:23, Glenn Wilkinson <notifications@github.com> wrote:

﻿

Closed #1982<https://github.com/gophish/gophish/issues/1982>.

**Comment by glennzw** [comment]
@S0larflare Ah good point.

@gophish-test-user Feel free to re-open if neither of these answers are what you're looking for.

**Comment by gophish-test-user** [comment]
@S0larflare - Yes, I  need a dedicated path or port that I can use for a health check to monitor if it is running. In fact, I am trying to set up Gophin in a docker container behind an AWS load balancer. So, I need to know what will be the health check path and port. Tried to use path (/) and port 3333, but did not work. But it works if I set up the path to /images.favicon.ico

**Comment by jordan-wright** [comment]
I have plans to add one soon.

**Comment by H4xl0r** [comment]
Use the Api to call ?

**Comment by glennzw** [comment]
> I have plans to add one soon.

I think it'd also be useful to return information about the state of gophish in this query. e.g: are any campaigns scheduled, or currently running, are any users logged in and active at the moment, maybe version information about gophish, memory usage.

**Comment by edermi** [comment]
> > I have plans to add one soon.
> 
> I think it'd also be useful to return information about the state of gophish in this query. e.g: are any campaigns scheduled, or currently running, are any users logged in and active at the moment, maybe version information about gophish, memory usage.

I like the idea, but only when the request is authenticated. Otherwise gophish leaks data to strangers on the Internet. For an unauthenticated request, I'd just return the HTTP status code indicating that everything is OK or not.

**Comment by alex4108** [comment]
@gophish-test-user You can configure your load balancer health check parameters to accept the 307 code returned when querying on / as a valid health check.  By default ELBv2 target groups only accept codes 200-299 as a passing check.  I'm not sure of classic load balancer default behavior.

```C:\Users\alex4>curl --insecure https://127.0.0.1:3333 -I
HTTP/1.1 307 Temporary Redirect```

**Comment by skyfox675** [comment]
> @gophish-test-user You can configure your load balancer health check parameters to accept the 307 code returned when querying on / as a valid health check. By default ELBv2 target groups only accept codes 200-299 as a passing check. I'm not sure of classic load balancer default behavior.
> 
> ```
> C:\Users\alex4>curl --insecure https://127.0.0.1:3333 -I
> HTTP/1.1 307 Temporary Redirect
> ```

Appears the ALBs (ELBv2) does now support a 307 HTTP return code as valid for passing of health checks. I am deploying ALBs via the AWS Load Balancer Controller for EKS:
`alb.ingress.kubernetes.io/success-codes:  200,301,307`

More info here:
https://kubernetes-sigs.github.io/aws-load-balancer-controller/guide/ingress/annotations/#health-check

**Comment by gebailey** [comment]
@gophish-test-user one other option would be to use `/login` as a health check endpoint; I'm using that with a AWS loadbalancer and it works OK (returns a 200).

**Comment by gavinelder** [comment]
if you're have a separate ingress for Admin & Phishing landing /robots.txt is suitable for the phishing ingress also.
