### ISSUE TITLE
Deleted scheduled campaigns are automatically stopped?

### ISSUE THREAD

**Issue by OSINT-d** [gophish/gophish#1984]
Hi everyone! I have a doubt on the complete/delete campaigns commands...

I scheduled some campaigns to start in a few days but then realized I got wrong with the groups. Indeed, I copied all campaigns and relaunched them with the correct recipients...then I deleted all previously scheduled campaigns without stopping them.

Did they automatically stop when I deleted them?

Thank you :)

**Comment by glennzw** [comment]
I just tested this by:

 * Create campaign to start in two minutes
 * Delete queued campaign
 * Wait

No campaign or error was encountered, so I think it's safe to assume that deleted scheduled campaigns do not run.
