### ISSUE TITLE
Button "Reported" without function

### ISSUE THREAD

**Issue by derhelge** [gophish/gophish#1985]
current version: 20200730000000

Brief description of the issue: 

What are you expecting to see happen? :
In the statistics of a current campaign the button for manual "reported" does not work.

At first I thought it was due to a missing certificate for the backend interface but this does not solve the problem. After clicking "continue" in the admin-gui, the log says:
```
time="2020-09-23T14:14:24+02:00" level=info msg="127.0.0.1 - - [23/Sep/2020:14:14:24 +0200] \"GET /api/campaigns/1?{} HTTP/2.0\" 200 28760 \"https://127.0.0.1:3333/campaigns/1\" \"Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0\""
```
Same is valid for chromium.

Short addition:
Reporting works great with the direct URL call 'http://phish_server/report?rid=1234567'.

What are you seeing happen?
I thought that I could use the function to manually mark certain users (as email reported).

Please provide as many steps as you can to reproduce the problem:
 * click on campaigns
 * click on "view results"
 * click on the small x in one row
 * click "continue"

**Comment by jsvazic** [comment]
I actually came here to say the same thing, but mine is slightly different.  For me, I add fake query parameters to my target URLs, but this also messes up the manual reporting button.  I.e. the resulting URL that gets called by the JS code when I click the manual report button looks like:

https://example.com/confirm-account?utm=12093801298321-109283019232-198032482034&zid=09328409238423/report?rid=OFLDFNx

Notice how the /report?rid=<value> is appended at the end?  It messes up the URL and causes an error when I try to click the button to manually report the phish.

**Comment by jordan-wright** [comment]
@jsvazic sounds like a bug. I'll get that fixed.

**Comment by jordan-wright** [comment]
I modified the logic to be more flexible, which hopefully fixes this issue.
