### ISSUE TITLE
Password suggestions in Search box for Sending Profiles

### ISSUE THREAD

**Issue by glennzw** [gophish/gophish#1986]
Running latest gophish.

Whenever I go to the 'Sending Profiles' tab Chrome tries to autofill username suggestions into the Search box:

<img width="1193" alt="Screenshot 2020-09-23 at 20 26 57" src="https://user-images.githubusercontent.com/3966613/94054059-63aa6d00-fddb-11ea-9d1f-76df0096895d.png">

This is super annoying, as even when I delete the autofilled username it pops back in. It's only happening on the search box for 'Sending Profiles', and I can't see anything in the HTML element that would entice chrome to fill this particular field.

Doing some Googling I think this might be a Chrome bug: https://support.google.com/chrome/thread/6787468?hl=en

I wanted to check in here though and see if anyone else runs into this, or has any possible fixes.

**Comment by jordan-wright** [comment]
We had a similar fix pushed in for a different password field. It was a weird fix, but it was the recommended way.

I know that's vague since this is from memory. This is just me saying "I agree it's weird, and I'll fix it" 😄

**Comment by glennzw** [comment]
Hehe, thanks!

**Comment by glennzw** [comment]
I can't figure this one out, let me know if you have any points @jordan-wright

**Comment by marksteward** [comment]
I think it's because the field has no name.

**Comment by glennzw** [comment]
Hmm I can't seem to replicate this any longer. I wonder if it was a Chrome bug that's been fixed.

@marksteward Can you still replicate it?

**Comment by marksteward** [comment]
Yeah, if I save my login creds. I have to work around it by entering a space in the search box after loading the Sending Profiles page.

**Comment by glennzw** [comment]
@marksteward Which version of Chrome are you using? This has been an issue for me for the last two years, but now it's disappeared. I'm testing on Chrome 97.0.4692.99.

**Comment by marksteward** [comment]
@glennzw I imagine it's because gophish now uses a self-signed HTTPS cert by default, which isn't allowed to do autofill. I disable that and use SSH tunnelling instead.

**Comment by marksteward** [comment]
OK, playing around, it is because of the missing form. I've issued a PR ^

**Comment by glennzw** [comment]
@marksteward Could you do me a favour, and see if you're able to add Custom Headers in the sending profile? I know you said in your PR that you can't use 'Enter' to add them, but clicking the 'Add' button doesn't work for me now. Not sure if it's related to this PR, or something else. Would appreciate you double checking your side.

**Comment by glennzw** [comment]
I've found the issue, it was my fault - I didn't rebuild the minified sending_profiles.js

**Comment by marksteward** [comment]
Ahh whew, I only just saw this, sorry!
