### ISSUE TITLE
gophish 0.11 and MariaDB 10.1.44

### ISSUE THREAD

**Issue by mbroekema61** [gophish/gophish#1988]
Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  0.11

Brief description of the issue: Moving from standard sqllite database to MariaDB

What are you expecting to see happen? :

I'me using gophish 0.11 with a deafult installation for quite a while on my Ubuntu 18 server which runs MariaDB 10.1.44
I've used the included sqllite database without any problem, created and done several succesfull campaigns.

Now i will change from sqllite to my server's Maria DB. It's looks good when changing the config.json file.
According to these remarks in your docs:
"Gophish uses a datetime format that is incompatible with MySQL >= 5.7. To fix this, Add the following lines to the bottom of /etc/mysql/mysql.cnf:"  
[mysqld]
sql_mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

 Question: do i have to change this also in de MariaDb configuration?

**Comment by jordan-wright** [comment]
I'm honestly not sure. Probably? At this time, the only database engines we officially support are SQLite and MySQL, so if you're using MariaDB, it should work but I can't make any guarantees.

**Comment by mbroekema61** [comment]
Thx, but why closing so soon, leaves no room for others to react ..:-(

**Comment by jordan-wright** [comment]
I'm always happy to reopen issues if more help is required. I close them if I feel I provided a response that adequately answers the question, otherwise issues tend to stay open forever.

Additionally, if you have further questions, you are always more than welcome to file additional issues. 🙂
