### ISSUE TITLE
Feature request: Support non-targeted attacks

### ISSUE THREAD

**Issue by Silur** [gophish/gophish#199]
Support for untargeted attacks for eg. sniffing/dnspoofing attacks where I don't have a list of users/emails and a mail template would be nice.

**Comment by jordan-wright** [comment]
Hi @Silur - thanks for the suggestion! I've considered this in the past, but gathering emails through an osint process is an entire field of study, and would be a huge feature to implement.

For now, we're going to stick to scenarios where the email addresses have already been gathered. 

Thanks again for the report. Keep those ideas coming!

**Comment by Silur** [comment]
Sorry if I confused you I know that email gathering is a way too big feature to implement, my scenario with "untargeted" attacks covers when I don't have any emails or groups at all. Only a website to redirect my targets to. Fancy emails aren't the only way to lead victims to a phishing site (for eg dns-spoofing) but gophish does not allow me to start a campaign without a list of addresses.

**Comment by rfdevere** [comment]
If you didn't have any one in mind then it's probably not the right tool
for you. Have a look into OSINT techniques to gather email addresses.
Googling 'TheHarvester' and 'RandomStorm/Bluto' will help you. Then come
back to GoPhish.

On Saturday, 12 March 2016, Silur <notifications@github.com> wrote:

> Sorry if I confused you I know that email gathering is a way too big
> feature to implement, my scenario with "untargeted" attacks covers when I
> don't have any emails or groups at all. Only a website to redirect my
> targets to. Fancy emails aren't the only way to lead victims to a phishing
> site (for eg dns-spoofing) but gophish does not allow me to start a
> campaign without a list of addresses.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gophish/gophish/issues/199#issuecomment-195761366>.
>


-- 
*Richard De Vere*
*Principal Consultant*

*Tel:* +44 754 6655448
*Web:* TheAntiSocialEngineer.com
*Email:* FrontDesk@TheAntiSocialEngineer.com
*Twitter:* @AntiSocial_Eng


The AntiSocial Engineer Ltd is a limited company registered in England and
Wales. Company Registration No. 09367111 Registered Office: 4 Capel Street,
Huddersfield, HD6 3AJ This message contains confidential information and is
intended only for AntiSocial Engineer customers. E-mail transmission cannot
be guaranteed to be secure or error-free as information could be
intercepted, corrupted, lost, destroyed, arrive late or incomplete, or
contain viruses. The AntiSocial Engineer Ltd cannot accept liability for
any errors or omissions in the contents of this message, which may arise as
a result of e-mail transmission. Please note that The AntiSocial Engineer
Ltd may monitor, analyse and archive email traffic, data and the content of
email for the purposes of security, legal compliance and staff training.

**Comment by Silur** [comment]
I don't need ANY email addresses neither from gophish nor from osint techniques.
Imagine me sitting next to you at starbucks,  you are on the public wifi, I arp spoof you and redirect facebook.com to my custom phising page. I don't need any OSINT for this, I don't have to know your email address and send an invitation

**Comment by rfdevere** [comment]
In this situation you would just MiTM and Strip SSL traffic to get the passwords. Guiding people to a 'phishing' page from the same network seems clumsy. If this is your sole intention then I reckon you'd like https://github.com/sophron/wifiphisher/

Richard

**Comment by jordan-wright** [comment]
Agreed completely.

Gophish is built around the use case of sending phishing emails and monitoring the results. Any use case outside of that would be better implemented through another tool.

For the use case presented, gophish doesn't have any tooling to get the user to the actual page (the MiTM). Then, when users reach the page there will be no way to know who visited the page, so gophish's reporting would be useless.

It seems like you would have just as much luck using a MiTM framework and then grep'ing through the web server logs.

Hope this helps!
