### ISSUE TITLE
What landing page will be used at 0.0.0.0:80 if I create multiple ones?

### ISSUE THREAD

**Issue by naddika** [gophish/gophish#1990]
Say, I run Gophish at 1.1.1.1 or test1.com. In the config there's this:

```
	"phish_server": {
		"listen_url": "0.0.0.0:80",
		"use_tls": false,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},

```
I create multiple landing pages. 

**Q 1:** when a user visits 1.1.1.1 or test1.com, which landing will be shown to him?

**Q 2:** I tried it locally and at all 3 ones -  "0.0.0.0:80", localhost and 127.0.0.1 - I got error returned by Gophish "404 page not found". Why?

**Comment by glennzw** [comment]
Best to stick to one ticket, answered here:

https://github.com/gophish/gophish/issues/1979#issuecomment-698586674

**Comment by jordan-wright** [comment]
Yes, let's stick to that comment thread for now.
