### ISSUE TITLE
Can't start gophish 

### ISSUE THREAD

**Issue by Xun-876** [gophish/gophish#1992]
![20200927_110521.jpg](https://user-images.githubusercontent.com/62703917/94369790-71991000-00b1-11eb-8260-6368910f16cb.jpg)

**Comment by edermi** [comment]
As I wrote in #1943 your database is read-only, at least that is what the log says. 
Explaining fundamentals goes beyond the scope of this issue tracker, and personally I don't think that gophish is the right software for you if you are struggling with these kind of problems.

**Comment by jordan-wright** [comment]
Yes, @edermi is correct- this is because SQLite believes your database is locked by some other process. I can only recommend Googling around to determine ways to identify and resolve the issue.

**Comment by Xun-876** [comment]
Thanks
