### ISSUE TITLE
./gofish not executing

### ISSUE THREAD

**Issue by Curioo** [gophish/gophish#1993]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
v0.11.0-osx-64bit
Brief description of the issue: 
I cant run the binary file
What are you expecting to see happen? :
Run the binray file
What are you seeing happen?
<img width="488" alt="Screenshot 2020-10-02 at 11 02 59" src="https://user-images.githubusercontent.com/47332301/94906554-f95e9000-049e-11eb-98b9-6b03a984a0ab.png">

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Download it
 * Step 2 - cd into dir
* Step 3 - type sudo ./gophish

**Comment by jordan-wright** [comment]
Try `chmod +x gophish` then running it.
