### ISSUE TITLE
issue configuring imap reporting

### ISSUE THREAD

**Issue by Ernie-Hd** [gophish/gophish#1998]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.11.0 

Brief description of the issue: Was able to get almost all of gophish working, but I was wanting to setup and test the IMAP reporting feature. But I can't seem to get it to test or save the settings. Even when I click on "advanced settings" nothing shows up.

What are you expecting to see happen? : window to expand or pop open

What are you seeing happen? nothing

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - sign in as admin, click settings, reporting settings, then advanced settings.
 * Step 2 - 
 
 
![gophi](https://user-images.githubusercontent.com/72576257/95504073-d9810d80-0971-11eb-9913-14bd91749c15.jpg)

**Comment by glennzw** [comment]
Could you check browser console to see if anything is popping up in there? Right click, Inspect, Console.

Also, make sure you don't have any addons blocking Javascript.

**Comment by Ernie-Hd** [comment]
Had tried a few different browsers. console doesn't have much showing
![cons](https://user-images.githubusercontent.com/72576257/95596693-557f6200-0a13-11eb-94d3-1da1a9ea7715.jpg)
Yeah I verified javascript was enabled and addons disabled.

**Comment by Ernie-Hd** [comment]
Seems like I was able to get around the issue and get it working it by doing a complete new setup. then transfer the previous db file over.
