### ISSUE TITLE
Trying to get real client IP behind proxy

### ISSUE THREAD

**Issue by glennzw** [gophish/gophish#1999]
What version of Gophish are you using?:  0.11

I have gophish running behind a proxy with requests being forwarded to it. This results in web log output like:

```
time="2020-10-09T16:09:38Z" level=info msg="127.0.0.1 - - [09/Oct/2020:16:09:38 +0000] \"GET / HTTP/1.1\" 200 1872 \"\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36\""
```

As you see I'm getting a client IP of 127.0.0.1, since the actual connection hitting gophish comes from the proxy running on the same box.

In order to get the real client IP I tried overwriting the `Host:` header within my proxy replacing it with the originating IP, but this doesn't seem to help.

Below is what hits the gophish admin server, as you can see I've supplied by real public IP in three headers (Host, X-Forwarded-For, and X-Real-Ip):

```
GET / HTTP/1.1
Host: <my_public_IP>
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: _gorilla_csrf=MTYw___etc; gophish=MTYw__etc
Dnt: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Sec-Gpc: 1
Upgrade-Insecure-Requests: 1
X-Forwarded-For: <my_public_IP>
X-Real-Ip: <my_public_IP>
```

In order to debug this I'm trying to find where in the gophish code the above connection log requests originate - but my grep fu is weak. Perhaps you know off hand @jordan-wright  or someone else?

Thanks!

**Comment by jordan-wright** [comment]
The connection log is generated using the [`handlers.CombinedLoggingHandler`](https://godoc.org/github.com/gorilla/handlers#CombinedLoggingHandler) library function as can be seen [here.](https://github.com/gophish/gophish/blob/3c490dbadbe6f66cc9a29bea50a136e98bbe50f8/controllers/route.go#L165).

You're right that this currently doesn't respect `X-Forwarded-For` headers. I think an easy way to update this would be to wrap the handler `CombinedLoggingHandler` receives in a call to [`handlers.ProxyHeaders`](https://godoc.org/github.com/gorilla/handlers#ProxyHeaders). Something like this:

```go
...
adminHandler = gzipWrapper(adminHandler)

// Respect X-Forwarded-For and X-Real-IP headers in case we're behind a
// reverse proxy.
adminHandler = handlers.ProxyHeaders(adminHandler)

// Setup logging
adminHandler = handlers.CombinedLoggingHandler(log.Writer(), adminHandler)
...
```

Note that this would need to be done in both admin.go and phish.go (for now until I finally get around to pushing out my refactoring that combines some of this stuff!)

**Comment by jordan-wright** [comment]
I had some time so I went ahead and knocked it out. Let me know if that works for you!

**Comment by glennzw** [comment]
Hi @jordan-wright, thanks for the help!

This almost works, I'm getting the real IP, but as an unwanted bonus a 500 internal server error too:

```
time="2020-10-11T19:31:51Z" level=info msg="x.x.x.167 - - [11/Oct/2020:19:31:51 +0000] \"GET / HTTP/1.1\" 307 51 \"\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36\""
time="2020-10-11T19:31:51Z" level=error msg="Unable to determine client IP address: address x.x.x.167: missing port in address"```

**Comment by jordan-wright** [comment]
Hmm... ok. That’s unexpected. Can you send me some details of your setup and we can troubleshoot? I tried the request using curl to set the headers and things seemed to work ok, but clearly there’s something missing.

Sorry for the trouble!

**Comment by glennzw** [comment]
No worries at all! I'm also debugging on my side. Trying to replicate the error with some curl commands.

**Comment by glennzw** [comment]
This seems to cause the crash:

```
curl -i -H "X-Real-Ip: 1.2.3.167"  http://localhost:3333/login 

HTTP/1.1 500 Internal Server Error
Content-Security-Policy: frame-ancestors 'none';
Content-Type: text/plain; charset=utf-8
Set-Cookie: _gorilla_csrf=x-JxXsQ6AB3iWZwXpAlr; Expires=Mon, 12 Oct 2020 08:28:15 GMT; Max-Age=43200; HttpOnly; SameSite
Vary: Accept-Encoding
Vary: Cookie
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
Date: Sun, 11 Oct 2020 20:28:15 GMT
Content-Length: 22

Internal Server Error
```

gophish console:
```
time="2020-10-11T20:30:18Z" level=error msg="Unable to determine client IP address: address 1.2.3.167: missing port in address"
time="2020-10-11T20:30:18Z" level=info msg="1.2.3.167 - - [11/Oct/2020:20:30:18 +0000] \"GET /login HTTP/1.1\" 500 22 \"\" \"curl/7.58.0\""
```

This is running on a remote server, with tls disabled.

**Comment by glennzw** [comment]
Adding a port seems to result in no crash:

```curl -i -H "X-Real-Ip: 1.2.3.167:1234"  http://localhost:3333/login ```

**Comment by jordan-wright** [comment]
Perfect, thanks! I’ll track this down. Earlier I was testing with the X-Forwarded-For header which might explain the difference.

**Comment by jordan-wright** [comment]
Ok, should be fixed with 2315412. The ratelimiter was getting upset that the IP didn't have a port, so I just removed that check to handle things more gracefully.

Feel free to reopen if you still don't see this fixing the bug. Sorry again for the hassle!

**Comment by jordan-wright** [comment]
Also just a heads up, I'm looking into why those new dependences were added. It feels like it came in from a tangential project I'm working on that's AWS + Docker related, but for the life of me I can't seem to get Go to remove them (even with `go mod tidy`, `go clean -modcache`, completely wiping/rebuilding go.mod, etc.).

I should have made a branch for this 😳

**Comment by jordan-wright** [comment]
Ok, fixed it. I think VSCode had the Go language server running which kept thrashing over the go.mod and go.sum files since I had both projects open. Or something. Just weird tbh. But it should be fixed now 😄

**Comment by glennzw** [comment]
This works perfectly, thanks so much @jordan-wright !

I'm sure the gremlins knew you were working on master and that's why they snuck in 😉

**Comment by glennzw** [comment]
Hi @jordan-wright , it seems I didn't test this thoroughly enough. I'm now getting a 404 on all landing pages, with the error in my console of:

```time="2020-10-14T13:16:12Z" level=error msg="address 1.1.1.167: missing port in address"```

(where `1.1.1.167` is my public IP)

If I hit the host directly without my proxy it's OK. However, going through Caddy this error crops up. Throwing in some netcats I can see the difference in the two requests:

```
curl https://my.phshing.server.com/?rid=aqRJUyG

Connection from localhost 35494 received!
GET /?rid=aqRJUyG HTTP/1.1
Host: 127.0.0.1:8080
User-Agent: curl/7.54.0
Accept: */*
X-Forwarded-For: 1.1.1.167
Accept-Encoding: gzip
```

Result: 404

vs

```
curl http://localhost:8080/?rid=aqRJUyG

Connection from localhost 35492 received!
GET /?rid=aqRJUyG HTTP/1.1
Host: localhost:8080
User-Agent: curl/7.58.0
Accept: */*
```

Result: OK, landing page loads.

So it seems the proxy is throwing in the `X-Forwarded-For` header. I've never noticed it before, but I guess pages worked before. I haven't set this option in Caddy, so I guess it's a default header that gets added. The relevant portion of my Caddy file is simply:

```
my.phshing.server.com {
  proxy / 127.0.0.1:8080
}
```

To reproduce the error:

```curl -i -H "X-Forwarded-For: 1.1.1.167" http://localhost:8080/?rid=aqRJUyG```

**Comment by jordan-wright** [comment]
Thanks Glenn! That’s surprising since the rate limiter shouldn’t be in play here. I’ll take a look this evening and get this fixed.

**Comment by jordan-wright** [comment]
Ok, should be fixed in https://github.com/gophish/gophish/commit/8b8e88b0773956eeeb2202871ec2c2076e36f920. Let me know if you continue to run into issues!

**Comment by glennzw** [comment]
Yup that hit the spot, thanks so much @jordan-wright !
