### ISSUE TITLE
Issue with Import of landing pages. (Unknown Certificates Authority )

### ISSUE THREAD

**Issue by madmantm** [gophish/gophish#200]
Hello Gophish team, i'm currently trying out the Gophish framework and it's pretty awesome, you did a great job, but i'm having this issue where the certificate is signed, by entrust, and for some odd reason, the operating system doesn't recognize the certificate presented, which works fine in the browser, i was wondering if it would be complex to add an option to ignore certs errors? like the SMTP issue that was previously fixed.

Get https://website.com x509: certificate signed by unknown authority

Thanks a lot!

**Comment by scottg88** [comment]
If I'm understanding this correct, your certificate works with other web applications but not gophish?

Have you included the full certificate chain in the public key?

You will typically get a root and intermediate bundle from the CA, combine this with the public key by appending the public key to the end of the bundle and try again with this new file.

**Comment by scottg88** [comment]
Looks like I interpreted the problem incorrectly after re-reading the title.

Instead, check that your ca certificate bundle is up-to-date (e.g. on Ubuntu the "ca-certificates" package in apt-get).

Alternatively it could be a similar issue if the website is not providing the intermediate CA certificate. Your desktop could have the intermediate CA included in the OS CAs but the Linux OS you are using does not. If this is the case (and it's generally a good idea) the fix would be to include the entire chain on the web server, similar to my last comment.

**Comment by jordan-wright** [comment]
In this case, I don't see much risk in changing the http client we use to ignore server cert issues.

This operation has to be initiated by the user, so I don't really consider that intrusive of a possible MiTM to be in our threat model.

Thoughts?

**Comment by madmantm** [comment]
Well, i did update the certificates in ubuntu with ca-certificates and i still got the issue.

**Comment by scottg88** [comment]
@madmantm check the website with a tool like SSL Labs to see if it's a chain issue.

@jordan-wright I agree with it not being a threat having the option available at time of import.

**Comment by madmantm** [comment]
@scottg88 you are correct, the certificate chain is incomplete.

**Comment by jordan-wright** [comment]
Ok, this should be fixed. Let me know if it works for you!

**Comment by madmantm** [comment]
Works #1, thanks!!

**Comment by MindNinja** [comment]
I am having the same problem. I just upgraded to the latest, so I assume I would have this change. I am trying to import an intranet corporate site. It gives me the certificate authority issue like the original poster. This site is a sharepoint site (I believe) and it does require credentials. I logged in with the browser I was running gophish in, and it still had the same problem.

**Comment by madmantm** [comment]
Well, did you compile from the github repository or used the standalone package, because i used the git-hub repository, when i had the issue and it was fixed.

**Comment by jordan-wright** [comment]
Correct, I believe this is fixed in the upcoming release.

Thanks!
