### ISSUE TITLE
imap "Reported" confirmation

### ISSUE THREAD

**Issue by Ernie-Hd** [gophish/gophish#2002]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.11.0

Brief description of the issue: just a question about imap reporting feature. I have it setup and it seems to work. thanks! But it only reports as "reported" if the person hadn't  opened the phish email at all. Is there a way to include if they opened it and then forwarded it afterwards. Or a way to manually mark them as having reported it.

**Comment by glennzw** [comment]
Unfortunately not, as gophish only checks for unread emails in the designated IMAP inbox. Otherwise it would have to read every single email every time it checked in.

**Comment by Ernie-Hd** [comment]
maybe in the future... thanks.
