### ISSUE TITLE
CSRF protection causing problems with NGINX reverse proxying from a different host

### ISSUE THREAD

**Issue by nurgster** [gophish/gophish#2003]
What version of Gophish are you using?:  0.11.0

Brief description of the issue: I'm using an nginx reverse proxy to send traffic from "https://<domain>.com:443" to the server hosting GoPhish with a different internal FQDN. The GoPhish server is configured to listen on 0.0.0.0:3333 with TLS disabled

What are you expecting to see happen? : Admin console

What are you seeing happen? "Forbidden - referrer invalid" error appears

Please provide any terminal output that may be relevant below:

Output from GoPhish console is the following (showing that the error is within GoPhish itself - a grep for "referrer invalid" suggests it's Gorilla CSRF protection):
```
time="2020-10-13T17:08:03Z" level=info msg="77.99.11.141 - - [13/Oct/2020:17:08:03 +0000] \"POST /login?next=%2F HTTP/1.0\" 403 28 \"https://<domain>/login?next=%2F\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0\""
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Install GoPhish on one server
 * Step 2 - Configure NGINX on another server to handle SSL and reverse proxy the request to Gophish server on port 3333

**Comment by glennzw** [comment]
If I'm not mistaken you can now set the CSRF token, as discussed here:

https://github.com/gophish/gophish/issues/1820
https://github.com/gophish/gophish/commit/a0e8c4a36936c2d39a041f42bd78633d07598d59

**Comment by nurgster** [comment]
Adding a CSRF token doesn't resolve this. 

My current config.json is:
`{
        "admin_server": {
                "listen_url": "0.0.0.0:3333",
                "use_tls": false,
                "cert_path": "gophish.crt",
                "key_path": "gophish.key",
                "csrf_key": "bLZ3wxuz3jAbkXDRxCeXpm9SGBmCLUbb"
        },
        "phish_server": {
                "listen_url": "0.0.0.0:3334",
                "use_tls": false,
                "cert_path": "example.crt",
                "key_path": "example.key"
        },
        "db_name": "sqlite3",
        "db_path": "gophish.db",
        "migrations_prefix": "db/db_",
        "contact_address": "",
        "logging": {
                "filename": "",
                "level": ""
        }
}
`

I should also add that if I connect directly to the Gophish server, it works. It's only when going through the nginx reverse proxy that it has issues.

**Comment by nurgster** [comment]
I have removed the X-Forwarded-Proto header from the nginx config and now this is working

**Comment by glennzw** [comment]
Jordan just pushed a fix relating to X-Forwarded header issues, I wonder if that affected you: https://github.com/gophish/gophish/issues/1999

Perhaps make sure you're on the latest commit.

**Comment by glennzw** [comment]
Hi @nurgster just checking if using the latest version resolved this?

**Comment by Adrian-Voelker** [comment]
I had the same issue and did quite a lot of research and testing.

I solved it with this NGINX proxy-configuration:

```location / {
        proxy_pass https://<your_(local)_host:port>;
        proxy_ssl_verify              off;  # Accept (all) self-signed certificates. -> Might be security-risk
        proxy_set_header   X-Real-IP          $remote_addr;
        proxy_set_header   X-Forwarded-For    $proxy_add_x_forwarded_for;
    }
```

It's important not to add any more (Host/Referer) headers, e.g.:

```
        proxy_set_header   Host               $host;
        proxy_set_header   X-Forwarded-Proto  $scheme;
        proxy_set_header   Referer           "<host>";   
```

Otherwise, it will break.

It's working for now. Eventually there should be made further in-depth research .

**Comment by glennzw** [comment]
Thanks so much @Adrian-Voelker! I'll close this issue now.

**Comment by revsbech** [comment]
Hi all, I seem to have the same issue. I'm running the system behind an AWS Load balancer (inside a Kubernetes cluster), and X-Forwarded-Proto is always set by the load balancer (as it should according to specifications). Is there any plands to update the CSRF code to take the X-Forwarded-Proto into account?

**Comment by fonsecas72** [comment]
Hi, sorry to bother, but i'm having a hard time figuring out this on k8s with a nginx ingress in front. 

Has anyone here made it working that minds to share the solution ? 🙇

**Comment by cakkasec** [comment]
> I had the same issue and did quite a lot of research and testing.
> 
> I solved it with this NGINX proxy-configuration:
> 
> ```
> location / {
>         proxy_pass https://<your_(local)_host:port>;
>         proxy_ssl_verify              off;  # Accept (all) self-signed certificates. -> Might be security-risk
>         proxy_set_header   X-Real-IP          $remote_addr;
>         proxy_set_header   X-Forwarded-For    $proxy_add_x_forwarded_for;
>     }
> ```
> 
> It's important not to add any more (Host/Referer) headers, e.g.:
> 
> ```
>         proxy_set_header   Host               $host;
>         proxy_set_header   X-Forwarded-Proto  $scheme;
>         proxy_set_header   Referer           "<host>";   
> ```
> 
> Otherwise, it will break.
> 
> It's working for now. Eventually there should be made further in-depth research .

Thanks so much! [Adrian-Voelker](https://github.com/Adrian-Voelker) You saved my time.
