### ISSUE TITLE
Campaign URL

### ISSUE THREAD

**Issue by hiheythere** [gophish/gophish#2005]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  0.9

Brief description of the issue: While setting up the campaign I don't know what to insert in the URL field. I don't have the greatest knowledge of networks. I'm just trying to make a simulation for my final exam. I've watched and read tons off tutorials and blogs put I still don't know how to make it work.

What are you expecting to see happen? : When I open the link in the sendet email the landing page should open. 

What are you seeing happen?
I've tried the listing URL's for the admin and  Gophish server in my config.json file. I also tried my MacBooks IP address aswell as my routers IP address. I can't reach anything with these addresses. In all of the YouTube tutorials they just use normal URL's like amazon.com and it still works for them. I don't know what im doing wrong.
I'm sorry to bother y'all with my dumb question but I really need help with my problem.

**Comment by glennzw** [comment]
You need to enter the IP address of the computer that gophish is running on.

When a user clicks a link in your email, they'll be sent to the gophish server - so it needs to be accessible to them.

**Comment by hiheythere** [comment]
If im using my IP address my browser says the server is not reachable. I've opened the link with the same device I run Gophish on so I think this should usually work.
