### ISSUE TITLE
landing page link to awareness page

### ISSUE THREAD

**Issue by Nanditaravindran** [gophish/gophish#2007]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: gophish-v0.10.1-windows-64bit

Brief description of the issue: want to link my landing page to an awareness page (either a poster or a video)

What are you expecting to see happen? : when I click submit to submit my data on the landing page, it should take me to a next page, which is an awareness page.

What are you seeing happen? Not sure how to do this, I am currently only seeing the landing page.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
This is currently not something built into Gophish. However, landing pages are just HTML - they can have links go anywhere. If you want to capture submitted data, then you'd need to write some Javascript to submit the form, then you can redirect the user to wherever you'd like. This awareness page would need to be hosted outside of Gophish.

However, the specifics on how to write custom landing page logic is beyond the scope of the support we provide but you can probably find issues here that give some examples.
