### ISSUE TITLE
Missing api entry for api.groupId.summary(id)

### ISSUE THREAD

**Issue by glennzw** [gophish/gophish#2009]
If I'm not mistaken I noticed that the endpoint defined in [api/server.go](https://github.com/gophish/gophish/blob/master/controllers/api/server.go#L73
):

```go
router.HandleFunc("/groups/{id:[0-9]+}/summary", as.GroupSummary)
```

is not reflected in the Javascript API endpoints in [gophish.js](https://github.com/gophish/gophish/blob/master/static/js/src/app/gophish.js#L128):

```javascript
    // groupId contains the endpoints for /groups/:id
    groupId: {
        // get() - Queries the API for GET /groups/:id
        get: function (id) {
            return query("/groups/" + id, "GET", {}, false)
        },
        // put() - Puts a group to PUT /groups/:id
        put: function (group) {
            return query("/groups/" + group.id, "PUT", group, false)
        },
        // delete() - Deletes a group at DELETE /groups/:id
        delete: function (id) {
            return query("/groups/" + id, "DELETE", {}, false)
        }
    },
```

i.e we can't call :

```javascript
 api.groupId.summary(50)
```

To rectify this I simply added:

```javascript
        // summary() - Queries the API for GET /groups/:id/summary
        summary: function (id) {
            return query("/groups/" + id + "/summary", "GET", {}, true)
        },
```

I can now call the endpoint:

```javascript
 api.groupId.summary(50)

{
  "id": 50,
  "name": "Test group'",
  "modified_date": "2020-10-13T10:14:41.751596Z",
  "num_targets": 2
}
```

Before I make a pull request I just wanted to make sure I'm not missing something or am mistaken.

**Comment by jordan-wright** [comment]
I wouldn't be surprised if there's an API endpoint missing. Typically, I end up adding them as I need them to do UI stuff. I'd be just fine if you wanted to add this one in just to be comprehensive. 🙂

**Comment by glennzw** [comment]
Ah awesome thanks!
