### ISSUE TITLE
Automatically Convert <a> tags in emails to {{.URL}}

### ISSUE THREAD

**Issue by jordan-wright** [gophish/gophish#201]
Based on an awesome [reddit comment](https://www.reddit.com/r/sysadmin/comments/49par4/got_to_play_with_gophish_today_this_is_some_damn/), we should automatically replace the ```<a>``` tags with references to ```{{.URL}}```. This can be done when importing an email.

Making this high priority, since it should present a big user experience improvement.

**Comment by StrangeUSB** [comment]
This is an awesome idea, but I feel it should still be optional. Maybe a
checkbox on the import modal.

**Comment by jordan-wright** [comment]
Agreed completely!

**Comment by pxdnbluesoul** [comment]
Reddit commenter here, I agree it would be better to be optional. There are plenty of times where it wouldn't be the desired result.

**Comment by jordan-wright** [comment]
Hey @pxdnbluesoul - I think I have this working. If you're building from source, just run a ```go get -u``` to grab the updates.

It looks like this:

![image](https://cloud.githubusercontent.com/assets/1317288/13691715/96ec6372-e700-11e5-8a3c-db0f6d2f46ee.png)

Let me know if this works for you!
