### ISSUE TITLE
Domain name / IP address not working as landing page

### ISSUE THREAD

**Issue by Nanditaravindran** [gophish/gophish#2010]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  gophish-v0.10.1-windows-64bit

Brief description of the issue: I have hosted my gophish version on my remote desktop, and I have a public IP address for it.
However, both the public IP and the domain whose A records, I have pointed to the IP are not working as my landing page. When I click on the link in the message, it takes me back to the gophish home page, not the associated landing page.

What are you expecting to see happen? :
When I click the link in the email message, the domain should open up, with the landing page, however, it takes me back to the gophish login page.

What are you seeing happen?

Gophish login page.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Similar to #2011 there isn't much we can do without understanding what steps you're taking to reproduce the issue. All I can do is point you to [this entry in our FAQ](https://docs.getgophish.com/user-guide/faq#events-arent-showing-up-on-the-dashboard).

**Comment by Nanditaravindran** [comment]
So, the URL, I open, has - http://your_url/?rid=XXXXX. "http://14.142.175.41/?rid=Tr8lEM8"

however, this is taking me back to the gophish login page.

**Comment by Nanditaravindran** [comment]
So, the URL, I open, has - http://your_url/?rid=XXXXX. "http://14.142.175.41/?rid=Tr8lEM8"
however, this is taking me back to the gophish login page.


Best regards,
Nandita Ravindran
Senior GRC Consultant,
SecurEyes
India | UAE | Oman | US
website: www.secureyes.net<http://www.secureyes.net/>
Mob: +91-9845447776

Disclaimer:
This e-mail and any attachments herein may contain confidential information and/or information protected by intellectual property rights for the exclusive attention of the intended recipient(s) named above. If you have received this email by mistake, please immediately notify the sender by return e-mail and delete this message and its attachments. Unauthorized use, copying or further full or partial distribution of this e-mail or its contents is prohibited. Although this e-mail and any attachments are believed to be free of any malicious software, it is the responsibility of the recipient to ensure the same. SecurEyes is not liable for any loss or damage arising in any way from the use of this e-mail or its attachments
