### ISSUE TITLE
Tracking of opening of emails. 

### ISSUE THREAD

**Issue by Nanditaravindran** [gophish/gophish#2011]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: gophish-v0.10.1-windows-64bit

Brief description of the issue: gophish is not tracking the opening of emails from a campaign.

What are you expecting to see happen? : when emails are opened it should show in the campaign statistics.

What are you seeing happen?
I am opening the mails, both in gmail and my official mail box. but this is not reflecting in gophish.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Without more information, I'm afraid all I can do is point you to [this entry in our FAQ](https://docs.getgophish.com/user-guide/faq#events-arent-showing-up-on-the-dashboard).

If this FAQ doesn't help resolve the issue, please provide the exact steps you're trying and we can re-open this issue to continue troubleshooting.

**Comment by Nanditaravindran** [comment]
So, the URL, I open, has - http://your_url/?rid=XXXXX. "http://14.142.175.41/?rid=Tr8lEM8"

however, this is taking me back to the gophish login page.
