### ISSUE TITLE
HELP WITH THE PHISING LINK PLEASE

### ISSUE THREAD

**Issue by wyattdkool** [gophish/gophish#2012]
What version of Gophish are you using?: 

**Newest Version**

Brief description of the issue: 

**How do you find the link for your landing page, I can't seem to find it??**

Please Help :)

**Comment by jordan-wright** [comment]
https://docs.getgophish.com/user-guide/documentation/campaigns

> URL - This is the URL that populates the {{.URL}} template value, commonly used in email templates. This should be a URL or IP address that points to the Gophish phishing server and is reachable by the recipient.
