### ISSUE TITLE
Tracing "record not found" error

### ISSUE THREAD

**Issue by glennzw** [gophish/gophish#2013]
What version of Gophish are you using?: 0.11

I'm working on some gophish updates, and have this error popping up in the console:

```
time="2020-10-21T20:00:13+02:00" level=error msg="record not found"
```

Nothing breaks, and everything is working as expected, but I'd like to find out where this illusive message is being generated. Is there anyway to tweak the logger to be more verbose, and tell me where this originates?

I've seen a few posts recently with this same error. I guess it comes from segments where we log `err.Error()` without giving context.

Thanks!

**Comment by glennzw** [comment]
Ah, I managed to debug-statement my way to find it. Seems it's an expected error when creating a new group (as that group doesn't exist):

```go
		_, err = models.GetGroupByName(g.Name, ctx.Get(r, "user_id").(int64))
		if err != gorm.ErrRecordNotFound {
```
https://github.com/gophish/gophish/blob/master/controllers/api/group.go#L36

I'd still be interested to know if anyone knows how to get the logger to output where errors are generated.

**Comment by jordan-wright** [comment]
Ah, yeah, I've been noticing those. It's honestly on my todo list to improve the error messages in general. Unfortunately, there's not a great way to trace the root of the logging message other than trial/error 🙁
