### ISSUE TITLE
How can I expose gophish to the internet?

### ISSUE THREAD

**Issue by MimoiGaming** [gophish/gophish#2020]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
v0.11.0

Brief description of the issue: 
I would like to expose gophish to the internet but I don't know how? I set up an Ubuntu Virtual Machine Server in my local network. Now I would like to know how I can get that server public and install gophish on it?

What are you expecting to see happen? :
That the gophish server is reachable from everywhere.

What are you seeing happen?
Nothing

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
You'll need to either (i) open a port on the router on your local network to route traffic inbound or (ii) host gophish on an internet accessible server (e.g. on DigitalOcean.com on Amazon AWS).

**Comment by MimoiGaming** [comment]
Thank You very much!

**Comment by MimoiGaming** [comment]
I have a small question again, how can I change where gophish is hosted because I don't want it to be on localhost?

**Comment by ChillVibesMushroom** [comment]
> I have a small question again, how can I change where gophish is hosted because I don't want it to be on localhost?

That's what I'm saying. have you tried one of these [https://pythonrepo.com/repo/anderspitman-awesome-tunneling-python-networking-programming](url) I need to portforward GoPhish over wan as well, but I saw this on Google, so I decided to help someone else who came across this website. 

HOPEFULLY one of these works. These are localhost tunneling services that make your website available over wan.
If @dggo666 @glennzw have a better solution or one that works with no error will you guys please let me know as I'm new to this and I would really appreciate the help

**Comment by ChillVibesMushroom** [comment]
> > I have a small question again, how can I change where gophish is hosted because I don't want it to be on localhost?
> 
> That's what I'm saying. have you tried one of these [https://pythonrepo.com/repo/anderspitman-awesome-tunneling-python-networking-programming](url) I need to portforward GoPhish over wan as well, but I saw this on Google, so I decided to help someone else who came across this website.
> 
> HOPEFULLY one of these works. These are localhost tunneling services that make your website available over wan. If @dggo666 @glennzw have a better solution or one that works with no error will you guys please let me know as I'm new to this and I would really appreciate the help


SHOW ME LOVE BACK MAKE A TUT OR SOMETHING

**Comment by Vector1199** [comment]
> You'll need to either (i) open a port on the router on your local network to route traffic inbound or (ii) host gophish on an internet accessible server (e.g. on DigitalOcean.com on Amazon AWS).

HII i doing the same but it is costly for me i hosted it on my laptop i there any option to expose it using portforwarding or tunnling services eg. telebit,cloudflair or anyother if yes can you describe it how to do it 

i used telebit and opened http port 3333 but it wont work after that i change config.jason and changed 0.0.0.0 to telebit ecposed link in it but it didnt work
