### ISSUE TITLE
Not Able to create imap profile

### ISSUE THREAD

**Issue by mansichauhan27** [gophish/gophish#2023]
Hi, I was using api to create imap profile but I am not able to, please help:

API Used: https://localhost:3333/api/imap (POST)
BODY: 
{
  "host": "qasmtp.logmetric.com",
  "port": "993",
  "username": "xyz",
  "password": "xyz",
  "enabled": false,
  "tls": true,
  "folder": "",
  "imap_freq": "60",
  "restrict_domain": "",
  "ignore_cert_errors": false,
  "delete_reported_campaign_email": false
}

Thanks!

**Comment by glennzw** [comment]
Hi there! What response does the server return? Using your settings works for me:

<img width="1176" alt="Screenshot 2020-10-29 at 13 07 00" src="https://user-images.githubusercontent.com/3966613/97569903-ac130700-19e7-11eb-8748-92350f8bc7ea.png">

**Comment by mansichauhan27** [comment]
I am getting a blank array. Screenshot:
 
![postman](https://user-images.githubusercontent.com/67453810/97659017-d4f0d600-1a93-11eb-9cc7-abbbe6b57358.PNG)

**Comment by glennzw** [comment]
Could you share what headers are being sent too, please?

**Comment by mansichauhan27** [comment]
I use the same coonfiguration for creating sending profile, campaigns etc.
![postman1](https://user-images.githubusercontent.com/67453810/97667369-b8f63000-1aa5-11eb-868b-63c9f50e2446.PNG)
![postman2](https://user-images.githubusercontent.com/67453810/97667378-be537a80-1aa5-11eb-824c-67365c862a0d.PNG)

**Comment by mansichauhan27** [comment]
Thanks @glennzw , I figured out my mistake, I was missing '/' in my url. Thanks For your support.

**Comment by glennzw** [comment]
No worries, glad you figured it out!
