### ISSUE TITLE
Using Gophish for Smishing?

### ISSUE THREAD

**Issue by CyberSecMin** [gophish/gophish#2024]
Is there a way to use Gophish for smishing? The main part i need is just a landing page that can track user input, and maybe source.

Is there a way to start a campaign and use the url from that ? Or does it only work with the email user list?

**Comment by CyberSecMin** [comment]
I know this isnt an issue, but i couldnt find a forum to ask the question on :)

**Comment by glennzw** [comment]
Top result when searching for 'SMS' ;-) 

[https://github.com/gophish/gophish/issues/1917](https://github.com/gophish/gophish/issues/1917)

Hope that helps.

**Comment by CyberSecMin** [comment]
Beautiful, thank you
