### ISSUE TITLE
Change Gophish logo at all screens

### ISSUE THREAD

**Issue by namanagrawal94** [gophish/gophish#2025]
I want to change the gophish logo at the top left corner from all the screens. I am able to change at the other place but not at the top left corner.

What are you expecting to see happen? : Whitecollar Gophish
![gophish](https://user-images.githubusercontent.com/69856224/97593943-2d8a8980-1a28-11eb-9162-704009fdd5da.JPG)

**Comment by jordan-wright** [comment]
You'll find the relevant HTML you need to change in templates/base.html. Since this isn't a bug or issue with Gophish itself, I'm going to go ahead and close this out.
