### ISSUE TITLE
Feature Request: MFA for admin/user accounts

### ISSUE THREAD

**Issue by GregCFTS** [gophish/gophish#2027]
Is it possible to introduce MFA for admin/user accounts on the web portal? 

Cheers.

**Comment by yrjo** [comment]
> Is it possible to introduce MFA for admin/user accounts on the web portal?
> 
> Cheers.

advice - Cloudflare Access OR something similar (Azure app gw or so) based on eg azure AD or another provider - in front of the :3333 endpoint ;) it would be much safer (also from network access lvl) than "just" MFA to be accessible by any:any on network level

**Comment by glennzw** [comment]
That's good advice from @yrjo and let's us decouple gophish from any third party providers (which is one of our goals).
