### ISSUE TITLE
Can add the staff_id in Users & Groups screen

### ISSUE THREAD

**Issue by jinyiwoo** [gophish/gophish#2029]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  0.9

Brief description of the issue:  cannot import the staff id in the page of 'Users&Groups’

What are you expecting to see happen? : custom define the users%groups info( add more fields in this page)

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
The fields you're able to import, with a sample data row, are:

```
First Name, Last Name, Email, Position
Example, User, foobar@example.com, Systems Administrator
```

Unfortunately staff id isn't one of those.

**Comment by jordan-wright** [comment]
@glennzw is correct- there is no current "staff ID" variable, and there are already [multiple issues](https://github.com/gophish/gophish/issues?q=is%3Aissue+is%3Aopen+custom+) dedicated to implementing custom variables for templates as well as a PR (#1813) that was close but not finished out (it's on the TODO to try and get this cleaned up and merged) that attempts to address this.

To that end, I'm going to close this as a duplicate. Thanks for getting in touch!
