### ISSUE TITLE
Support for X-Forwarded-For

### ISSUE THREAD

**Issue by nmalcolm** [gophish/gophish#203]
If the Phish server is behind a proxy, any connections made to it will show as coming from the proxy's IP. This can be prevented with a setting to use the `X-Forwarded-For` header instead.

I'm not sure if there's anything else which is needed for full proxy support, but it's a good start.

**Comment by jordan-wright** [comment]
Great idea! I'll get this knocked out.

**Comment by jordan-wright** [comment]
Ok, I've gotten this knocked out. ```X-Forwarded-For``` is now respected on email tracking links.

Currently, we don't do ip tracking on click events. That'll be fixed soon, and I'll support ```X-Forwarded-For``` from the get-go.

Let me know if this doesn't work for you and we'll re-open.

**Comment by nmalcolm** [comment]
Looks good! However, I feel it should be a setting. The `X-Forwarded-For` header can be easily spoofed if the Phish server isn't behind a proxy. If we know the targets will only be connecting through the proxy it would be sane to enable the setting.

**Comment by jordan-wright** [comment]
That's true. It can be spoofed. It might be a bit more difficult to make this a setting (architecturally, anyways). Let me see what I can do. I'll probably open a separate issue for making it a setting.
