### ISSUE TITLE
Question on how to use SSL to connect to mysql databse

### ISSUE THREAD

**Issue by sebastianbeck** [gophish/gophish#2031]
What version of Gophish are you using?: 
gophish-v0.11.0-windows-64bit

Brief description of the issue: 
I have setup a mysql Databse on Azure (Paas). I can setup everything fine if I disable the "Enforce SSL" settings.
But if I enforce SSL I get the error at the bottom

**How can I make gophish use an encrypted conection?**

What are you expecting to see happen? :

establish a encrypted connection to mysql databse. 

What are you seeing happen?

time="2020-11-03T19:46:47Z" level=warning msg="waiting for database to be up..."
time="2020-11-03T19:46:52Z" level=error msg="Error 1193: Unknown system variable 'useSSL'"
time="2020-11-03T19:46:52Z" level=fatal msg="Error 1193: Unknown system variable 'useSSL'"

**Comment by jordan-wright** [comment]
Our database connection is managed by the `gorm` library which itself uses the `go-sql-driver` library for the underlying connection. Looking through [it's documentation](https://github.com/go-sql-driver/mysql#tls), it looks like the setting might be `tls=true`.

But beyond that, I'm afraid that's all I can do to help. I don't personally use a MySQL + TLS connection so I don't have a certain answer for you.

Hopefully this puts you on the right track!
