### ISSUE TITLE
mySQL results modification

### ISSUE THREAD

**Issue by ironc0in** [gophish/gophish#2033]
Gophish v0.11
I'm trying to remove all entries (_false positives_) from the results where a spam filter clicked on the link.

I can successfully remove those rows with the target IP addresses with:
`delete from events WHERE campaign_id=61 AND details LIKE '%12.34.56.78%';`

But when I see the **results** table, it's still there:
`select * from results WHERE campaign_id=61 AND ip LIKE '%12.34.56.78%';`

It seems the **events** table may be computed and only shows the last event, if the spam filter clicked a few times, but the user never did, that event is removed from the events table but remains in the **results** table.

If I remove that IP from the **results** table, then that user is also removed from the result.

It seems the results table is computed, but I'm not sure how to recompute that table once the events table has been updated/changed.

**Any help would be really appreciated. I'm not a db guy.**
I just want a quick and dirty want to fix the true results after the campaign so I get it cleaned up in the front-end.

Eventually this could be integrated as a _spam filter label_ feature where we can define a bunch of IPs in the settings and the campaign flags those in a new column in the results which you can then filter on/off to hide **false positives**.

**Comment by jordan-wright** [comment]
I'm afraid any custom database modification is outside the scope of the support we can provide.

In general, the results table is meant to indicate the _current status_ of a recipient in the campaign. The values like the IP address are set anytime a new event is recorded.

To that end, "recalculating" the values for a row in the results table isn't really something Gophish would do. It'd be up to you to say something like: "Find the latest event for a given email address and campaign ID, then find the matching result and update the result with the IP address and status from that event."

Sorry there isn't more we can do to help!
