### ISSUE TITLE
Landing page redirects to Forbidden - CSRF token invalid

### ISSUE THREAD

**Issue by CyberSecMin** [gophish/gophish#2034]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
newest
Brief description of the issue: 
Made a landing page but no matter what i redirect to when they click the button i get the error Forbidden - CSRF token invalid

![image](https://user-images.githubusercontent.com/71698468/98225400-f6026c80-1f54-11eb-8cb3-0762edcd9f9d.png)

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
2020/11/05 10:51:05 http: TLS handshake error from 127.0.0.1:50990: remote error: tls: unknown certificate
2020/11/05 10:51:06 http: TLS handshake error from 127.0.0.1:50992: remote error: tls: unknown certificate
time="2020-11-05T10:51:06+01:00" level=info msg="127.0.0.1 - - [05/Nov/2020:10:51:06 +0100] \"POST /landing_pages HTTP/2.0\" 403 31 \"https://localhost:3333/landing_pages\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36\""
2020/11/05 10:51:16 http2: server: error reading preface from client 127.0.0.1:50995: read tcp 127.0.0.1:3333->127.0.0.1:50995: i/o timeout
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by 3noki** [comment]
I have a similar issue, I cannot even login to gophish. I ensured deleted cookies, tried using http or https and removing tls from config.json, I cannot login unless I have tls set to true, but I only receive the "Forbidden - CSRF token invalid" if using tls and correct credentials. 

The log below is a successful login directed to the CRSF error, I navigated back to main login page, tried again, and it said invalid credentials

`r@d:~/go/src/github.com/gophish/gophish# ./gophish
time="2021-01-19T20:49:55Z" level=warning msg="No contact address has been configured."
time="2021-01-19T20:49:55Z" level=warning msg="Please consider adding a contact_address entry in your config.json"
goose: no migrations to run. current version: 20201201000000
time="2021-01-19T20:49:55Z" level=info msg="Please login with the username admin and the password 5169ab020332922e"
time="2021-01-19T20:49:55Z" level=info msg="Starting admin server at https://ipaddress:3333"
time="2021-01-19T20:49:55Z" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
time="2021-01-19T20:49:55Z" level=info msg="Starting IMAP monitor manager"
time="2021-01-19T20:49:55Z" level=info msg="Starting new IMAP monitor for user admin"
time="2021-01-19T20:49:55Z" level=info msg="Starting phishing server at http://0.0.0.0:80"
2021/01/19 20:50:14 http: TLS handshake error from localipaddress:49937: remote error: tls: unknown certificate
time="2021-01-19T20:50:15Z" level=info msg="localipaddress - - [19/Jan/2021:20:50:15 +0000] \"POST /login?next=%2F HTTP/2.0\" 403 31 \"https://gophishipaddress:3333/login?next=%2F\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36\""
`

After trying the second time to login;

`2021/01/19 20:55:57 http: TLS handshake error from localipaddress50179: remote error: tls: unknown certificate
time="2021-01-19T20:55:57Z" level=info msg="localipaddress - - [19/Jan/2021:20:55:57 +0000] \"GET / HTTP/2.0\" 307 51 \"\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36\""
time="2021-01-19T20:55:57Z" level=info msg="localipaddress - - [19/Jan/2021:20:55:57 +0000] \"GET /login?next=%2F HTTP/2.0\" 200 1039 \"\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36\""
time="2021-01-19T20:55:57Z" level=info msg="localipaddress - - [19/Jan/2021:20:55:57 +0000] \"GET /images/logo_inv_small.png HTTP/2.0\" 200 1118 \"https://gophishipaddress:3333/login?next=%2F\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36\""
time="2021-01-19T20:55:57Z" level=info msg="localipaddress - - [19/Jan/2021:20:55:57 +0000] \"GET /images/logo_purple.png HTTP/2.0\" 200 4735 \"https://gophishipaddress:3333/login?next=%2F\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36\""
time="2021-01-19T20:55:57Z" level=info msg="localipaddress - - [19/Jan/2021:20:55:57 +0000] \"GET /css/dist/gophish.css HTTP/2.0\" 200 52514 \"https://gophishipaddress:3333/login?next=%2F\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36\""
time="2021-01-19T20:55:57Z" level=info msg="localipaddress - - [19/Jan/2021:20:55:57 +0000] \"GET /js/dist/vendor.min.js HTTP/2.0\" 200 324943 \"https://gophishipaddress:3333/login?next=%2F\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36\""
time="2021-01-19T20:55:58Z" level=info msg="localipaddress - - [19/Jan/2021:20:55:58 +0000] \"GET /images/favicon.ico HTTP/2.0\" 200 1150 \"https://gophishipaddress:3333/login?next=%2F\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36\""
time="2021-01-19T20:56:05Z" 

**level=error msg="crypto/bcrypt: hashedPassword is not the hash of the given password"**

time="2021-01-19T20:56:05Z" level=info msg="localipaddress - - [19/Jan/2021:20:56:05 +0000] \"POST /login?next=%2F HTTP/2.0\" 401 1120 \"https://gophishipaddress:3333/login?next=%2F\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36\""
time="2021-01-19T20:56:05Z" level=info msg="localipaddress- - [19/Jan/2021:20:56:05 +0000] \"GET /font/fontawesome-webfont.woff2?v=4.7.0 HTTP/2.0\" 200 77177 \"https://gophishipaddress:3333/css/dist/gophish.css\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36\""
time="2021-01-19T20:56:05Z" level=info msg="localipaddress - - [19/Jan/2021:20:56:05 +0000] \"GET /images/favicon.ico HTTP/2.0\" 200 1150 \"https://gophishipaddress:3333/login?next=%2F\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36\""
`

I'm not sure where you can access that page with the redirect options, unless it is a landing page for a phish

**Comment by goldenstandard1** [comment]
same issue as @3noki , this is my terminal output:

time="2021-01-31T19:34:27Z" level=warning msg="No contact address has been configured."
time="2021-01-31T19:34:27Z" level=warning msg="Please consider adding a contact_address e
ntry in your config.json"
goose: no migrations to run. current version: 20200730000000
time="2021-01-31T19:34:27Z" level=info msg="Please login with the username admin and the 
password 5925eae9da46ab6b"
time="2021-01-31T19:34:27Z" level=info msg="Starting admin server at https://0.0.0.0:3333
"
time="2021-01-31T19:34:27Z" level=info msg="Background Worker Started Successfully - Wait
ing for Campaigns"
time="2021-01-31T19:34:27Z" level=info msg="Starting IMAP monitor manager"
time="2021-01-31T19:34:27Z" level=info msg="Starting new IMAP monitor for user admin"
time="2021-01-31T19:34:27Z" level=info msg="Starting phishing server at http://0.0.0.0:80
"
2021/01/31 19:35:08 http: TLS handshake error from 69.143.129.141:56181: remote error: tl
s: unknown certificate
time="2021-01-31T19:35:08Z" level=info msg="<redacted> - - [31/Jan/2021:19:35:08 +000
0] \"POST /login?next=%2F HTTP/2.0\" 403 31 \"https://<redacted>:3333/login?next=%2F\" \
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/
88.0.4324.104 Safari/537.36\""
time="2021-01-31T19:35:09Z" level=info msg="<>- - [31/Jan/2021:19:35:09 +000
0] \"GET /favicon.ico HTTP/2.0\" 404 19 \"https://<>:3333/login?next=%2F\" \"Moz
illa/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0
.4324.104 Safari/537.36\""
time="2021-01-31T19:35:09Z" level=info msg="<>- - [31/Jan/2021:19:35:09 +000
0] \"GET /favicon.ico HTTP/2.0\" 404 19 \"https://<>/login?next=%2F\" \"Moz
illa/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0
.4324.104 Safari/537.36\""

with the same error: 
Forbidden - CSRF token invalid

**Comment by glennzw** [comment]
If your landing page is redirecting to "CSRF Forbidden" then it sounds like you're trying to redirect to the gophish admin server, rather then the gophish phish server. By default the former is on :3333 and the later on :80.

**Comment by glennzw** [comment]
Closing out as haven't heard back, feel free to reopen.
