### ISSUE TITLE
Phishing campaigns for O365, SCL problems

### ISSUE THREAD

**Issue by gdelasaux** [gophish/gophish#2038]
What version of Gophish are you using?: v0.11.0

Brief description of the issue: 
Hello everyone, I apologize in advance if this topic does not belong here and I fully understand that it will be deleted if it does.
I use GoPhish in my business to do phishing campaigns, I will be doing my first campaign soon.
I need to run this phishing campaign to email addresses under Office365.
I use Postfix to send my emails as well as a domain name that I have secured to the maximum, SPF, DKIM and DMARC in "pass".
The problem is the following, when I send emails to my target, they are directly listed as spam, when I analyze the header, I find that I have a SCL of 5 out so that my email is considered reliable it would take a SCL of 1 or 0.
I tried to secure my phishing emails as much as possible, no double URL, landing page with HTTPS, X-Mailer and List-Unsubscribe. Currently I have no choice but to ask my client to whitelist my domain however I would like to avoid that. 
If there are people running campaigns under O365 and have information that can help me I'm a taker.

What are you expecting to see happen? : Decrease my SCL

**Comment by GregCFTS** [comment]
Just to clarify, are you saying that when the emails are delivered they are being blocked by M365? Have you made sure to put whitelists in place for exchange?

**Comment by gdelasaux** [comment]
Hello,

Thank you for your answer, we have not yet asked our client to whitelist our domain name because we wanted to put ourselves in the shoes of an attacker who would not be whitelisted.

Despite the implementation of various registrations allowing the increase of my trust score, I am still blocked with a SCL of 5, here is the problem. 

So I created this topic in order to collect different opinions to be able to carry out my phishing campaign without whitelisting my domain, if necessary we will whitelist it.

Translated with www.DeepL.com/Translator (free version)

**Comment by gdelasaux** [comment]
> 
> 
> Just to clarify, are you saying that when the emails are delivered they are being blocked by M365? Have you made sure to put whitelists in place for exchange?

Hello,

Thank you for your answer, we have not yet asked our client to whitelist our domain name because we wanted to put ourselves in the shoes of an attacker who would not be whitelisted.

Despite the implementation of various registrations allowing the increase of my trust score, I am still blocked with a SCL of 5, here is the problem.

So I created this topic in order to collect different opinions to be able to carry out my phishing campaign without whitelisting my domain, if necessary we will whitelist it.

**Comment by IronFist009** [comment]
Hi, have you tried adding "Message-ID" header to the sending profile? I was having similar issue and got resolved by doing so.

**Comment by gdelasaux** [comment]
> 
> 
> Hi, have you tried adding "Message-ID" header to the sending profile? I was having similar issue and got resolved by doing so.

Hey,

I just tried to add the header Message-ID with the value "randomstring-{{{.RId}}@my.domain". When I send the test mail from GoPhish it's going inbox, but when I launch test campaign, it's the same as before, SCL is 5 and mail are tagged as junk :(

My client will whitelist my domain but it could be better if my domain wasn't whitelisted..

Thank's for help !

**Comment by IronFist009** [comment]
Hi, 

Don't forget angle brackets, also I noticed you got three curly brackets (randomstring**-{{{.**RId}}@my.domain) make sure there are not syntax error in value - <randomstring{{.RId}}@my.domain>

**Comment by IronFist009** [comment]
Hi,

Don't forget angle brackets "<>", also I noticed you got three curly brackets (randomstring**-{{{.**RId}}@my.domain) make sure there are not syntax error in value, it should look something like <randomstring{{.RId}}@my.domain>

Also try to send the same email directly from the email client check if that going to inbox, try to analysis email headers, https://mha.azurewebsites.net/  .. Compare it to the email that is reaching inbox.

Also you can try https://www.mail-tester.com/ to see if you missing something or the email content is triggering the spam filter.

Good luck!

**Comment by harrygeorge2893** [comment]
> Hi, have you tried adding "Message-ID" header to the sending profile? I was having similar issue and got resolved by doing so.

Please can you help me on how you did that I'm facing similar issues i really need your help thanks in advance
