### ISSUE TITLE
Admin website not available

### ISSUE THREAD

**Issue by Jozko001** [gophish/gophish#2039]
Hi, I would like to ask for help. I have installed gophish on my server (debian 10) and I am accessing to admin website from another hosts in my LAN. Everything works ok, but sometimes I have problem with accessing to gophish admin websites. However, directly from web browser on my server where is gophish installed, it works always without any problem. 

My solution for this problem is very strange and simple. If I have problem to acces it from my PC, always helps if I clicked somewhere in admin site, in web browser directly on server, where is gophish installed (e.g. campaigns, user & groups, etc.) After that website is again available from some host. Next solution is restarting gophish. 

My config file
```
{
	"admin_server": {
		"listen_url": "10.10.0.102:3333",
		"use_tls": false,
		"cert_path": "gophish_admin.crt",
		"key_path": "server.key"
	},
	"phish_server": {
		"listen_url": "10.10.0.102:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "server.key"
	},
	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": "",
	"logging": {
		"filename": "",
		"level": ""
	}
}
```
I had version 9, today I have updated on version 11, and still have same problem. Could someone help me, how to start debugging this  and find where is a problem? Thank you in advance.

**Comment by jordan-wright** [comment]
In this case, you're setting the `listen_url` for the `phish_server` and `admin_server` to the same value- they need to be different ports. Additionally, you might try changing from the `10.10.0.102` to just bind on all interfaces at `0.0.0.0`.

Give that a shot and let me if it helps.

**Comment by glennzw** [comment]
Closing out as haven't heard back.
