### ISSUE TITLE
Incredibly Slow Emailing

### ISSUE THREAD

**Issue by madmunich** [gophish/gophish#204]
Hello,
I have been running GoPhish almost since it was released, and I have had real issues with speed. The actual UI performance is fine, but the emails take forever to send. We are talking over an hour to send 25. At first I thought it was my SMTP relay but after spinning up an Amazon SES instance with a 50000 a day email allowance and 14 emails per second, I realize this can't be it. Thoughts?
Great product though

**Comment by jordan-wright** [comment]
Hey there!

Thanks for the report! Currently, there are absolutely issues with email speed.

To avoid rate limits, we are currently adding delays between each email. This isn't desired, so we're working out way to both:

* Streamline the emails to reuse connections
* Add exponential back off retry periods for failed emails.

I'm on mobile, but  I think we might have an issue laid out for this already. I'll double check. If so, I'll go ahead and point this one to it.

Thanks again for the report!

**Comment by vysec** [comment]
I found this to be an issue also.

**Comment by jordan-wright** [comment]
Just checking in on this - happy to report that I will be publishing changes soon that should increase emailing speed dramatically.

Stay tuned!

**Comment by jordan-wright** [comment]
This should be fixed as of https://github.com/gophish/gophish/commit/a8aac75f99612eb42be2c94700b55bad8fcee50a. If you could please verify by building from source (**you will need to ```go get -u``` to get the new email package**), I would appreciated it!

**Comment by madmunich** [comment]
Thank you! I will test ASAP. Likely tomorrow


________________________________

**Comment by jordan-wright** [comment]
Sounds good - after you go get -u, remember to "go build" to build the new binary.

**Comment by jordan-wright** [comment]
Going ahead and closing this for now. Let me know if upgrading the version from source doesn't fix the issue and we can take another look.

Thanks for reporting this!

**Comment by madmunich** [comment]
Apologies I meant to respond. This issue does indeed seem to be resolved. Thanks for all your hard work!


________________________________

**Comment by mtatran** [comment]
Hello, I am not building from source. Is there any way I can make my emails send faster?

**Comment by jordan-wright** [comment]
If you’re using the latest version of Gophish, emails should send pretty quickly as they are streamlined much more efficiently.

What kind of slow emailing are you seeing on your end (emails/second)?

**Comment by mtatran** [comment]
Yes I'm using the latest version. Although can say it was sending very fast until it reached 1870 out of 2500, now it's sending like 3 emails per hour.

**Comment by mtatran** [comment]
Hello I am using the latest version. Although I can say that the emails sent very quickly until it hit 1870 out of 2500. Now it's sending like 3 emails/hour.
@jordan-wright

**Comment by mtatran** [comment]
There was a couple incidents where our server crashed and it made the sending process a lot slower each time we turned it back on. There are no errors being thrown.

> That sounds like it might be some kind of issue with being rate limited by the receiving mail server. We also do an exponential backoff in the case of receiving errors when sending.
> 
> Without any log information it’s tough to say the actual cause. Do you see any errors being thrown?
