### ISSUE TITLE
Improved Upgrade Documentation

### ISSUE THREAD

**Issue by GnarTech** [gophish/gophish#2040]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  Linux

Brief description of the issue:  Poor upgrade documentation

What are you expecting to see happen? : Someone build out proper upgrade documentation. 

What are you seeing happen? A quick paragraph about how easy it is to upgrade, but many steps omitted which someone could run into.

P.S. - Documentation on all other aspects is great, just really lacking "Upgrade" documentation section on your website.

**Comment by jordan-wright** [comment]
Hey there!

Sorry to hear the documentation wasn't as comprehensive as you were looking for. It's worth noting that [we always accept pull requests.](https://github.com/gophish/user-guide/tree/a706aa441e635dbe7121c7dae032edd4641b966a)
