### ISSUE TITLE
SOMEONE PLEASE HELP

### ISSUE THREAD

**Issue by Matthewr7404** [gophish/gophish#2044]
Quick thing, I do not know if this is the app I want to be using for this but I want to send a "Password reset" email out to someone. Can a kind human please setup the phishing website for me I will just need acess to the credentials that come back from it!

The link I want the phishing website to replicate: https://www.minecraft.net/en-us/login

**Comment by jordan-wright** [comment]
No, what you're looking to do is likely illegal and not how Gophish is to be used.
