### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by AlenJeyu** [gophish/gophish#2047]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.5.1
Brief description of the issue: 
trying to connect to the localhost but the connection is being refused

What are you expecting to see happen? :
successful connection and printing the status code.
What are you seeing happen?

requests.exceptions.SSLError: HTTPSConnectionPool(host='127.0.0.1', port=3333): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)'),))

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

import requests

from gophish import Gophish
api_key = 'xxxxxxxxxxx'
api = Gophish(api_key)
from gophish import Gophish
api = Gophish(api_key, host='https://127.0.0.1:3333')
api = Gophish(api_key, host='https://127.0.0.1:3333', verify=False)

x = requests.get('https://127.0.0.1:3333')
print(x.status_code)

Please provide any terminal output that may be relevant below:

```
Insert output here:
```Traceback (most recent call last):
  File "trial.py", line 11, in <module>
    x = requests.get('https://127.0.0.1:3333')
  File "/Users/alenjeyu/Library/Python/2.7/lib/python/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/alenjeyu/Library/Python/2.7/lib/python/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/alenjeyu/Library/Python/2.7/lib/python/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/alenjeyu/Library/Python/2.7/lib/python/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Users/alenjeyu/Library/Python/2.7/lib/python/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='127.0.0.1', port=3333): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)'),))

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
Looks like the error is "CERTIFICATE_VERIFY_FAILED", meaning Python is connecting but doesn't like the self signed certificate. Try:

```
x = requests.get('https://127.0.0.1:3333', verify=False)
```

Obviously never do this in production, as you'd open yourself up to MiTM attacks.
