### ISSUE TITLE
Troubles working with templates HTML

### ISSUE THREAD

**Issue by OSINT-d** [gophish/gophish#2048]
Gophish version: 0.10.1 

Hi everyone,
I am a gophish user and I find troubles working with the HTML codes of both landing pages and email templates. Whenever I try to cancel a part of the code by selecting an entire string, Gophish takes me back to the homepage as the input was not directed to the code but to the browser. Everytime it happens, all the changes I made on the page are lost (unless I remember to save all of them before this issue comes out).
Is there a way to solve the issue?

Thank you!

**Comment by jordan-wright** [comment]
Can you provide more details? As in, a gif showing what you're seeing, what keys your pressing, etc. We'll need enough information to be able to locally reproduce the issue before we can attempt to fix it.

**Comment by OSINT-d** [comment]
Hi Jordan,
I try to explain me better through a screenshot.

Here I am writing on the HTML code and I am selecting a portion of text I want to remove from the code:
[cid:image002.jpg@01D6CC8E.C25E7180]

After selecting it, I press cancel but instead of removing the text I selected, gophish receives a different input and bounce me back to the “email templates” dashboard.
To be clearer, gophish gave me the same answer I receive with this command:
[cid:image004.jpg@01D6CC8E.C25E7180]

Indeed, to cancel a portion of HTML code I can’t proceed through the selection of text and that its removal, but I have to cancel it character by character.
Moreover, when this happens I lose all unsaved progresses I made in the code.

Unfortunately, I cannot made a video. I hope this is enough.

Best regards,

VALERIA MARIA D’ONGHIA
OSINT Analyst


[cid:image003.jpg@01D6CC8E.0CC72B50]

Da: Jordan Wright <notifications@github.com>
Inviato: domenica 6 dicembre 2020 20:47
A: gophish/gophish <gophish@noreply.github.com>
Cc: Valeria Maria D'Onghia <vd@intuity.it>; Author <author@noreply.github.com>
Oggetto: Re: [gophish/gophish] Troubles working with templates HTML (#2048)


Can you provide more details? As in, a gif showing what you're seeing, what keys your pressing, etc. We'll need enough information to be able to locally reproduce the issue before we can attempt to fix it.

**Comment by jordan-wright** [comment]
The images aren't loading - I think you'll need to upload them (you can drag/drop) in a comment in GitHub web interface.

But in general if you're clicking "Cancel" in the bottom right of the pop up, that means to cancel the entire editing process, not to remove a bit of text. Instead, to remove text highlight and hit the backspace key, just as you would in a text editor.

**Comment by glennzw** [comment]
Closing out as haven't heard back.
