### ISSUE TITLE
Input field type: Plain

### ISSUE THREAD

**Issue by rfdevere** [gophish/gophish#205]
On the tabs that stores the sending profiles consider using:
 <input type="password" class="form-control" placeholder="Password" id="password">

Minor one I admit but to be expected from all major software these days. Shoulder surfers and all.

**Comment by jordan-wright** [comment]
Hey @rfdevere! Looks like a picture or something isn't showing up. From the title, I'm guessing you're referring to the password not having the "password" input type?

If so, got it all fixed as of a couple minutes ago. Great catch!

https://github.com/gophish/gophish/commit/d5bf800961c4a65829286119f2beeaa29c59f421

**Comment by rfdevere** [comment]
Sorry inserting HTML into a HTML form wasn't my smartest move today! Yes I meant the input type:"Plain" option.

**Comment by jordan-wright** [comment]
Gonna go ahead and close this out, since it looks like it's fixed. @rfdevere if you run into any issues, let me know and we'll open it back up.

Thanks for letting us know about it!
