### ISSUE TITLE
Bulk import is adding a bunch of semicolons in the position field, and skipping some lines

### ISSUE THREAD

**Issue by CyberSecMin** [gophish/gophish#2054]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.11.0
Brief description of the issue: 
Using the bulk import feature is adding a bunch of semicolons to the position field like this
![image](https://user-images.githubusercontent.com/71698468/100592717-c6e2df00-32f7-11eb-97a0-f77fe038002a.png)

It also skipped 10 entries out of the 635 i attempted to add.
I have tried using different csv types, such as CSV UTF-8, CSV semicolon seperated, CSV MS-DOS and they all do the same =/
What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:
No errors in the terminal
```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
You'll need to include the file you're trying to upload for us to help.

**Comment by CyberSecMin** [comment]
I unfortunately wont be able to do that since there is a lot of sensitive data here =/

**Comment by CyberSecMin** [comment]
Hmm looking through the csv file, it "wraps" text on some of the fields for some reason 
This button:
![image](https://user-images.githubusercontent.com/71698468/100594827-75881f00-32fa-11eb-82d5-206c1db6c2dc.png)

The fields where it has done this are missing. The text in the fields looks like all the other fields though

**Comment by glennzw** [comment]
If you're using a rich editor (Excel or something else) it could be changing the file. Best to edit / view CSVs in notepad or vim or something plain to make sure the format matches:

```
First Name,Last Name,Email,Position
Example,User,foobar@example.com,Systems Administrator
```

**Comment by CyberSecMin** [comment]
That makes sense. Its the Excel formatting that adds the semicolons for some reason. But when i open the file with notepad++ i could find SOME clear formatting errors, with 4 users being in "" quotes. But i am still missing some users, where i simply cant see what the issue should be. For example here:
![image](https://user-images.githubusercontent.com/71698468/100602135-cbad9000-3303-11eb-814a-c06979d7cda6.png)
Nielsen isnt added for some reason.

**Comment by glennzw** [comment]
You could try running the file through a CSV validator.

Online: https://csvlint.io/
Local: https://github.com/Clever/csvlint
