### ISSUE TITLE
Avoiding google tagging landing page as malicious

### ISSUE THREAD

**Issue by CyberSecMin** [gophish/gophish#2056]
Do you guys know any way around this, or how google does this?

Is it because the companys employees report the site?
Or is it just random google AI that tags it?

Could it maybe be avoided with a robots.txt? If so, how?

Thank you :)

**Comment by jordan-wright** [comment]
This isn't something we'll be able to help you with. This forum is specifically to handle bug reports for the Gophish software itself. We don't have any insight into how Google detects and reports on phishing pages.
