### ISSUE TITLE
Can't create additional admin accounts

### ISSUE THREAD

**Issue by Estabanyo** [gophish/gophish#2061]
What version of Gophish are you using?: v.0.11.1

Brief description of the issue: When trying to create an admin account, I receive an error message of "table users has no column named last_login". I also receive this message when trying to change the password on the default admin account.

What are you expecting to see happen? : Create an account

What are you seeing happen? An error message, and no account being created. 
![image](https://user-images.githubusercontent.com/73993873/101362896-a0451b00-3898-11eb-9c34-288acd1b774c.png)

**Comment by glennzw** [comment]
Hi @Estabanyo, could you share your `config.json` file and also the output from the terminal when this happens? The `last_login` is a recent addition - that column should be added when gophish spins up.

**Comment by Estabanyo** [comment]
Hi @glennzw,

**Here is the config.json file here.**

	"admin_server": {
		"listen_url": "10.0.0.86:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "gophish_admin.key"
	},
	"phish_server": {
		"listen_url": "10.0.0.86:80",
		"use_tls": false,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": "",
	"logging": {
		"filename": "",
		"level": ""
	}
}

**Here is the output from the Terminal**

time="2020-12-08T14:40:12Z" level=info msg="10.0.1.29 - - [08/Dec/2020:14:40:12 +0000] \"POST /api/users/ HTTP/2.0\" 500 97 \"https://10.0.0.86:3333/users\" \"M ozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36 OPR/72.0.3815.400\""
2020/12/08 14:40:12 http: TLS handshake error from 10.0.1.29:58093: remote error : tls: unknown certificate
time="2020-12-08T14:40:12Z" level=info msg="10.0.1.29 - - [08/Dec/2020:14:40:12 +0000] \"POST /api/users/ HTTP/2.0\" 500 97 \"https://10.0.0.86:3333/users\" \"M ozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36 OPR/72.0.3815.400\""

We're running from Binary, and now running GoPhish as a service. We downloaded the file from Github and followed the install instructions. The only change we made was to remove the GoPhish xmailer tag.

Thanks,
Stephen

**Comment by glennzw** [comment]
Did you build from source on Windows? (ie. download the repo, go build, etc). I don't have a Windows environment at hand to test.

A quick fix would be to create the missing column, but I'm more concerned as to why it's not being auto-created. To add the column manually:

```
sqlite3 gophish.db
ALTER TABLE users ADD COLUMN last_login datetime;
```

My only thought as to why it's not working is that you have two different versions - an older version in which this column did not exist yet, but you're running a newer version. You could try rebuilding/redownloading.

**Comment by Estabanyo** [comment]
The source was downloaded and installed on an Ubuntu VM, didn't touch windows at all as far as I know.

I've tried that fix, however it's telling me the database is readonly - I wonder if that's why it's not working in the first place? 
![image](https://user-images.githubusercontent.com/73993873/101508998-34ce7c80-3970-11eb-9ff1-b3cefb8841ac.png)
GoPhish was installed on the Admin account, which is the owner, but is running on a seperate account called gophish which wouldn't have permission to edit it. Would this be why the column hasn't been created?

**Comment by glennzw** [comment]
So I spun up a fresh Ubuntu 18.04 box and I can't reproduce this. My successful outcome:

```
wget https://dl.google.com/go/go1.13.linux-amd64.tar.gz
tar -xvf go1.13.linux-amd64.tar.gz
sudo mv go /usr/local
mkdir ~/go
export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
go get github.com/gophish/gophish
cd ~/go/src/github.com/gophish/gophish/
go build
..............
./gophish
```

Then hitting the web UI I'm able to create new admin users:

<img width="1198" alt="Screenshot 2020-12-08 at 17 43 34" src="https://user-images.githubusercontent.com/3966613/101514371-7b76a380-397d-11eb-9870-310d79ee9577.png">

Perhaps try building again from the start?

**Comment by glennzw** [comment]
If `gophish.db` is read-only you will indeed have trouble. Whatever account executes gophish needs to be able to edit `gophish.db`

**Comment by Estabanyo** [comment]
I've set the file to read and write for all users. When trying to ALTER TABLE it returns that there is no table called users. Is it worth starting from scratch, or could we add this?

We're currently running a campaign, so we'd be waiting for 2 weeks or so before we were able to rebuild. if that's the best option, then that's what we'll do.

Thanks!

**Comment by glennzw** [comment]
If you're getting an error of "no user table" it might be the case that you're not actually opening the database file, but creating a new one. Make sure you're in the same folder as `gophish.db` or use its full path. Try `.tables` to show all tables:

```
$ sqlite3 gophish.db

sqlite> .tables
attachments           imap                  role_permissions    
campaigns             imap_old              roles               
email_requests        mail_logs             smtp                
events                pages                 targets             
goose_db_version      permissions           templates           
group_targets         reported              users               
groups                reported_attachments  webhooks            
headers               results             
```

Check the columns in `users` :
```
sqlite> PRAGMA table_info(users);
0|id|integer|0||1
1|username|varchar(255)|1||0
2|hash|varchar(255)|0||0
3|api_key|varchar(255)|1||0
4|role_id|INTEGER|0||0
5|password_change_required|BOOLEAN|0||0
6|last_login|datetime|0||0
7|account_locked|BOOLEAN|0||0
```

If you don't have the `last_login` column:

```
sqlite> ALTER TABLE users ADD COLUMN last_login datetime;
```

It's pretty weird behaviour though, so I'd recommend starting from scratch after the two week period. You could manually add additional users from sqlite as above if you really needed them.

**Comment by glennzw** [comment]
Closing out as haven't heard back.
