### ISSUE TITLE
How to add imported url to a new landing page using API

### ISSUE THREAD

**Issue by AlenJeyu** [gophish/gophish#2062]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.11.0

Brief description of the issue: 
I am currently working with the landing page API and want to import a site I have successfully got the code for the import URL part but I am not sure how to use that information in the creating landing page API.

code for importing a url:

url = 'http://www.jsontest.com/#mime'
response = requests.post('https://localhost:3333/api/import/site?api_key={}'.format(api_key), json={'url': url}, verify=False).json()

As far i know the creating landing page api should only have attributes mentioned below:
   id                  : int64
  name                : string
  html                : string
  capture_credentials : bool
  capture_passwords   : bool
  modified_date       : string(datetime)
  redirect_url        : string

so how to give response from the importing as an attribute to creating landing page. 

What are you expecting to see happen? : To import an url to a new landing page

What are you seeing happen?: dont know how to add imported url to the landing page.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
I haven't tried this before, but watching the process flow by intercepting via proxy, it looks like you need to do your above call to grab the HTML, and then a second call to save the page. e.g:

```
POST /api/import/site HTTP/1.1
Authorization: Bearer 8188eba0c91b68f17def50xxxe7ef64785b20663e73d

{
   "url":"http://example.org",
   "include_resources":false
}

```

Response:
```
{
  "html": "\u003c!DOCTYPE html\u003e\u003chtml\u003e\u003chead\u003e\u003cbase href=\"http://example.org\"/\u003e\n    \u003ctitle\u003eExample Domain\u003c/title\u003e\n\n    \u003cmeta charset=\"utf-8\"/\u003e\n    \u003cmeta http-equiv=\"Content-type\" content=\"text/html; charset=utf-8\"/\u003e\n    \u003cmeta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/\u003e\n    \u003cstyle type=\"text/css\"\u003e\n    body {\n        background-color: #f0f0f2;\n        margin: 0;\n        padding: 0;\n        font-family: -apple-system, system-ui, BlinkMacSystemFont, \"Segoe UI\", \"Open Sans\", \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n        \n    }\n    div {\n        width: 600px;\n        margin: 5em auto;\n        padding: 2em;\n        background-color: #fdfdff;\n        border-radius: 0.5em;\n        box-shadow: 2px 3px 7px 2px rgba(0,0,0,0.02);\n    }\n    a:link, a:visited {\n        color: #38488f;\n        text-decoration: none;\n    }\n    @media (max-width: 700px) {\n        div {\n            margin: 0 auto;\n            width: auto;\n        }\n    }\n    \u003c/style\u003e    \n\u003c/head\u003e\n\n\u003cbody\u003e\n\u003cdiv\u003e\n    \u003ch1\u003eExample Domain\u003c/h1\u003e\n    \u003cp\u003eThis domain is for use in illustrative examples in documents. You may use this\n    domain in literature without prior coordination or asking for permission.\u003c/p\u003e\n    \u003cp\u003e\u003ca href=\"https://www.iana.org/domains/example\"\u003eMore information...\u003c/a\u003e\u003c/p\u003e\n\u003c/div\u003e\n\n\n\u003c/body\u003e\u003c/html\u003e"
}
```

Step 2:

```
POST /api/pages/ HTTP/1.1
Authorization: Bearer 8188eba0c91b68f17def50xxxe7ef64785b20663e73d

{
  "name": "Test Landing Page",
  "html": "<!DOCTYPE html>\n<html>\n<head>\n\t<base href=\"http://example.org\" />\n\t<title>Example Domain</title>\n\t<meta charset=\"utf-8\"/><meta http-equiv=\"Content-type\" content=\"text/html; charset=utf-8\"/><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>\n\t<style type=\"text/css\">body {\n        background-color: #f0f0f2;\n        margin: 0;\n        padding: 0;\n        font-family: -apple-system, system-ui, BlinkMacSystemFont, \"Segoe UI\", \"Open Sans\", \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n        \n    }\n    div {\n        width: 600px;\n        margin: 5em auto;\n        padding: 2em;\n        background-color: #fdfdff;\n        border-radius: 0.5em;\n        box-shadow: 2px 3px 7px 2px rgba(0,0,0,0.02);\n    }\n    a:link, a:visited {\n        color: #38488f;\n        text-decoration: none;\n    }\n    @media (max-width: 700px) {\n        div {\n            margin: 0 auto;\n            width: auto;\n        }\n    }\n\t</style>\n</head>\n<body>\n<div>\n<h1>Example Domain</h1>\n\n<p>This domain is for use in illustrative examples in documents. You may use this domain in literature without prior coordination or asking for permission.</p>\n\n<p><a href=\"https://www.iana.org/domains/example\">More information...</a></p>\n</div>\n</body>\n</html>\n",
  "capture_credentials": false,
  "capture_passwords": false,
  "redirect_url": ""
}

```
