### ISSUE TITLE
Request for a new feature. Purge button

### ISSUE THREAD

**Issue by HugoLS** [gophish/gophish#2064]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

**What version of Gophish are you using?**:  0.11.0

**Brief description of the issue:**  I would like a efature to purge all campaigns easily/quicky. 
Actually, we have to doit one by one. It can take a lot of time because of the page reload, and the double swal box per item.

I already implemented this feature from my side, and i would like to create a pull request to propose you to review my code.
Please find below screenshot showing what i have done:

The purge Button:
![image](https://user-images.githubusercontent.com/9926857/101505295-7e20cb00-3974-11eb-8151-04a33b8906bc.png)

A confirmation swalbox to avoid unwanted purge:
![image](https://user-images.githubusercontent.com/9926857/101505416-9e508a00-3974-11eb-93b9-7b2d4aa3fc8b.png)

A swal box error if the passphrase is not right:
![image](https://user-images.githubusercontent.com/9926857/101505552-c50ec080-3974-11eb-960b-2cea45403812.png)

A swall box if the purge succeeded:
![image](https://user-images.githubusercontent.com/9926857/101505622-d788fa00-3974-11eb-8188-16096b89cc93.png)

**Comment by jordan-wright** [comment]
Thanks for reaching out! While I appreciate you taking the time to fill this out and offer to make a PR, at this time I don't think I want to merge this into the main version of Gophish.

Purging all campaigns is something I don't think will be applicable to most Gophish users, and keeping the UI very opinionated and simple to include only on the most core features is one of the things that makes Gophish so powerful.

But again I appreciate you getting in touch and encourage you to keep sending great ideas our way!
