### ISSUE TITLE
Why Do Always Get "Deceptive Site ahead"???

### ISSUE THREAD

**Issue by testinglab66** [gophish/gophish#2068]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: current

Brief description of the issue: I always get deceptive site ahead everything I run gophish even when I implement evilginx2 links too, what could be the problem cos my url is secure, but not showing the greenlock on the site! Please how do I fix????

What are you expecting to see happen? : I don't expect to see Deceptive Site Ahead, 

What are you seeing happen? The greenlock should show or appear on my site

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
Unfortunately this is not related to gophish itself so we can't really give you support.

https://www.malcare.com/blog/deceptive-site-ahead/

**Comment by testinglab66** [comment]
Please what I mean is even when I register another site same thing still happens after my last experience... Imy wondering how come even when I run Gophish with another domain same thing still happens... I have uninstalled and reinstall with a diff domain but same issues....I really need help.. I'm here wondering if they have flagged my browsers too or something..

**Comment by glennzw** [comment]
I understand what you mean, but this is out of the control of gophish. Either;

You're hosting on the same IP and Google has blacklisted it, or the content you're hosting has been blacklisted and is immediately detected as such by your browser.

As this problem is unrelated to gophish we can't really help other than to try approaches in the link posted above. Sorry.
