### ISSUE TITLE
Attachment Tracking

### ISSUE THREAD

**Issue by mansichauhan27** [gophish/gophish#2069]
Hi, I have been using your tool for quite a long time,thanks for it.

Is it possible to track attachments in gophish now?

**Comment by glennzw** [comment]
We're working on this at the moment: https://github.com/gophish/gophish/pull/1936

**Comment by jordan-wright** [comment]
Yep! PR is in progress. In the meantime, this has been asked a ton of times so I'm going to go ahead and close this out as a duplicate.
