### ISSUE TITLE
How to ensure captured credentials are stored encrypted?

### ISSUE THREAD

**Issue by legendOfZelda** [gophish/gophish#2070]
What version of Gophish are you using?: 0.11.0

Brief description of the issue: A client we're phishing requires us to store captured credentials encrypted. To this end, I set up Gophish with MySQL as the backend and wanted to enable encryption in MySQL, as described here: https://dev.mysql.com/doc/refman/8.0/en/innodb-data-encryption.html. Question: Is this sufficient to guarantee that captured credentials stored on persistent storage are only stored encrypted? (It's of course more difficult to have such a guarantee for memory too, but such a guarantee the client isn't after).

What are you expecting to see happen? : That the only place where credentials captured by Gophish are stored persistently is in MySQL (or SQLite if that's the configured backend) but nowhere else on persistent storage.

What are you seeing happen? I don't know, I have not checked the flow of captured data through Gophish all the way to the storage backends. I thought it would be easier to simply ask.

**Comment by jordan-wright** [comment]
In general, Gophish provides a clear warning that it stores data as cleartext in the database. If you implement some kind of encryption scheme or encryption-at-rest on top of that, that's up to you, and whether or not it's good enough for your client can only be decided by your client.

There's an open PR that supports encrypted data but I don't have a timeline on when it will be merged into master. You could try to give it a shot and see if it works for you.

**Comment by jordan-wright** [comment]
To elaborate a bit on your question- yes, I believe the only place credentials are ever stored is in the database.

**Comment by tuxvador** [comment]
Here is a quick workaround using the fish shell, you may need to adapt for bash : 

```bash
╭─user@hostname /home/user/junk ‹system›
╰─$ docker cp xxx33ba1fxxx:/opt/gophish/gophish.db .
╭─user@hostname /home/user/junk ‹system›
╰─$ sqlite3 gophish.db 'select * from events where details like \'%password%\';' > 1.txt
╭─user@hostname /home/user/junk ‹system›
╰─$ sed 's/rd":\["\(.\{0,4\}\).*\"]/rd":\["\1xxxx\"]/' 1.txt > 2.txt
╭─user@hostname /home/user/junk ‹system›
╰─$ for x in (cat 2.txt)
       #echo $x
       set id (echo $x | cut -d "|" -f 1)
       #sqlite3 gophish.db "select * from events where id=$id;"
       set a (echo $x | cut -d "|" -f 2)
       set b (echo $x | cut -d "|" -f 3)
       set c (echo $x | cut -d "|" -f 4)
       set d (echo $x | cut -d "|" -f 5)
       set e (echo $x | cut -d "|" -f 6)
       sqlite3 gophish.db "replace into events(id,campaign_id,email,time,message,details) values('$id','$a','$b','$c','$d','$e')"
       #echo "$id-$a-$b-$c-$d-$e"
    end
╭─user@hostname /home/user/junk ‹system›
╰─$ docker ./gophish.db cp xxx33ba1fxxx:/opt/gophish/gophish.db
```

result : 
```
"forcedownlevel":["0"],"isUtf8":["1"],"password":["Crisxxxx"]},"browser":{"
forcedownlevel":["0"],"isUtf8":["1"],"password":["Londxxxx"]},"browser":{
forcedownlevel":["0"],"isUtf8":["1"],"password":["Avocxxxx"]},"browser":{
```
