### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by testinglab66** [gophish/gophish#2072]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  current version

Brief description of the issue: deceptivery site ahead, Please what I mean is even when I register another site same thing still happens after my last experience... I'm wondering how come even when I run Gophish with another domain same thing still happens... I have uninstalled and reinstall with a diff domain but same issues....I really need help.. I'm here wondering if they have flagged my browsers too or something..

 

What are you expecting to see happen? : at least I should see a clean site after I've reintalled with a different domain, started all afresh but still experiencing issues...

What are you seeing happen? Same issues even after I started all anew...

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
Closed, duplicate: https://github.com/gophish/gophish/issues/2068

Please see the reply there.
