### ISSUE TITLE
Certificate Errors, please help

### ISSUE THREAD

**Issue by testinglab66** [gophish/gophish#2075]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: current version

Brief description of the issue: I bought a new vps server with a new domain, though I have not pointed the ip to my new domain, juSt installed gophish, started it and tried ooening the admin server through my ip address followed by the port I'm using on my gophish config.json but I'm getting "Warming, Potential Risk Ahead" and looking at it it says "MOZILLA PKIX ERROR SELF SIGNED CERT" 

What are you expecting to see happen? : I was expecting it to show the security exception not the potential risk ahead!

What are you seeing happen? Potential rissues ahead instead!

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by testinglab66** [comment]
TLS HANDSHAKE error, bad certificate, please how do I fix this???

**Comment by jordan-wright** [comment]
You need to retrieve a valid SSL certificate for your domain. How you do this is beyond the scope of our support since it depends on which certificate provider you use.

Then you update config.json to point to that certificate.
