### ISSUE TITLE
problems with the campaigns as it is not updated when they open the email or click the malicious url

### ISSUE THREAD

**Issue by pepino87** [gophish/gophish#2076]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

0.11.0

Brief description of the issue: 

campaigns are not updated when a user opens an email, or when he clicks on the malicious link

What are you expecting to see happen? :

I do not understand why the campaign is not updated when users do not open the mail

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:v="urn:schemas-microsoft-com:vml">
<head><meta content="text/html; charset=utf-8" http-equiv="Content-Type"/><meta content="width=device-width" name="viewport"/><meta content="IE=edge" http-equiv="X-UA-Compatible"/>
	<title></title>
	
	<style type="text/css">body {
			margin: 0;
			padding: 0;
		}

		table,
		td,
		tr {
			vertical-align: top;
			border-collapse: collapse;
		}

		* {
			line-height: inherit;
		}

		a[x-apple-data-detectors=true] {
			color: inherit !important;
			text-decoration: none !important;
		}
	</style>
	<style id="media-query" type="text/css">@media (max-width: 520px) {

			.block-grid,
			.col {
				min-width: 320px !important;
				max-width: 100% !important;
				display: block !important;
			}

			.block-grid {
				width: 100% !important;
			}

			.col {
				width: 100% !important;
			}

			.col>div {
				margin: 0 auto;
			}

			img.fullwidth,
			img.fullwidthOnMobile {
				max-width: 100% !important;
			}

			.no-stack .col {
				min-width: 0 !important;
				display: table-cell !important;
			}

			.no-stack.two-up .col {
				width: 50% !important;
			}

			.no-stack .col.num4 {
				width: 33% !important;
			}

			.no-stack .col.num8 {
				width: 66% !important;
			}

			.no-stack .col.num4 {
				width: 33% !important;
			}

			.no-stack .col.num3 {
				width: 25% !important;
			}

			.no-stack .col.num6 {
				width: 50% !important;
			}

			.no-stack .col.num9 {
				width: 75% !important;
			}

			.video-block {
				max-width: none !important;
			}

			.mobile_hide {
				min-height: 0px;
				max-height: 0px;
				max-width: 0px;
				display: none;
				overflow: hidden;
				font-size: 0px;
			}

			.desktop_hide {
				display: block !important;
				max-height: none !important;
			}
		}
	</style>
</head>
<body class="clean-body" style="margin: 0; padding: 0; -webkit-text-size-adjust: 100%; background-color: #FFFFFF;">
<table bgcolor="#FFFFFF" cellpadding="0" cellspacing="0" class="nl-container" role="presentation" style="table-layout: fixed; vertical-align: top; min-width: 320px; Margin: 0 auto; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #FFFFFF; width: 100%;" valign="top" width="100%">
	<tbody>
		<tr style="vertical-align: top;" valign="top">
			<td style="word-break: break-word; vertical-align: top;" valign="top">
			<div style="background-color:transparent;">
			<div class="block-grid" style="Margin: 0 auto; min-width: 320px; max-width: 500px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; background-color: #e50914;">
			<div style="border-collapse: collapse;display: table;width: 100%;background-color:#e50914;">
			<div class="col num12" style="min-width: 320px; max-width: 500px; display: table-cell; vertical-align: top; width: 500px;">
			<div style="width:100% !important;">
			<div style="border-top:0px solid transparent; border-left:0px solid transparent; border-bottom:0px solid transparent; border-right:0px solid transparent; padding-top:15px; padding-bottom:15px; padding-right: 0px; padding-left: 0px;">
			<div>&nbsp;</div>
			</div>
			</div>
			</div>
			</div>
			</div>
			</div>

			<div style="background-color:transparent;">
			<div class="block-grid" style="Margin: 0 auto; min-width: 320px; max-width: 500px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; background-color: transparent;">
			<div style="border-collapse: collapse;display: table;width: 100%;background-color:transparent;">
			<div class="col num12" style="min-width: 320px; max-width: 500px; display: table-cell; vertical-align: top; width: 500px;">
			<div style="width:100% !important;">
			<div style="border-top:0px solid transparent; border-left:0px solid transparent; border-bottom:0px solid transparent; border-right:0px solid transparent; padding-top:0px; padding-bottom:0px; padding-right: 0px; padding-left: 0px;">
			<div align="center" class="img-container center fixedwidth" style="padding-right: 0px;padding-left: 0px;"><img align="middle" alt="Image" border="0" class="center fixedwidth" src="https://assets.brand.microsites.netflix.io/assets/493f5bba-81a4-11e9-bf79-066b49664af6_cm_1440w.png?v=41" style="text-decoration: none; -ms-interpolation-mode: bicubic; border: 0; height: auto; width: 100%; max-width: 200px; display: block;" title="Image" width="200" /> </div>
			</div>
			</div>
			</div>
			</div>
			</div>
			</div>

			<div style="background-color:transparent;">
			<div class="block-grid" style="Margin: 0 auto; min-width: 320px; max-width: 500px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; background-color: transparent;">
			<div style="border-collapse: collapse;display: table;width: 100%;background-color:transparent;">
			<div class="col num12" style="min-width: 320px; max-width: 500px; display: table-cell; vertical-align: top; width: 500px;">
			<div style="width:100% !important;">
			<div style="border-top:0px solid transparent; border-left:0px solid transparent; border-bottom:0px solid transparent; border-right:0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;">
			<div style="color:#555555;font-family:Arial, 'Helvetica Neue', Helvetica, sans-serif;line-height:1.2;padding-top:10px;padding-right:10px;padding-bottom:10px;padding-left:10px;">
			<div style="font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 12px; line-height: 1.2; color: #555555; mso-line-height-alt: 14px;">
			<p style="font-size: 12px; line-height: 1.2; mso-line-height-alt: 14px; margin: 0;">Estimado(a)</p>

			<p style="font-size: 12px; line-height: 1.2; mso-line-height-alt: 14px; margin: 0;">&nbsp;</p>

			<p style="font-size: 12px; line-height: 1.2; mso-line-height-alt: 14px; margin: 0;">Como parte de las campa&ntilde;as de incentivos para nuestros empleados fuiste elejido como uno de los ganadores de una cuenta Netflis Premium, disfruta de las mejores pel&iacute;culas, documentales y series por 6 meses gratis, completando el siguiente formulario:&nbsp;<a href="{{.URL}}">Link</a>.</p>

			<p style="font-size: 12px; line-height: 1.2; mso-line-height-alt: 14px; margin: 0;">&nbsp;</p>

			<p style="font-size: 12px; line-height: 1.2; mso-line-height-alt: 14px; margin: 0;">Atentamente.<br />
			Equipo de promociones.</p>
			</div>
			</div>
			</div>
			</div>
			</div>
			</div>
			</div>
			</div>
			</td>
		</tr>
	</tbody>
</table>

<p>&nbsp;</p>

<p>{{.Tracker}}</p>
</body>
</html>

********************************************************************************************************************************

Landing page

<html><head>
	<title></title>
</head>
<body>
<p><iframe class="scribd_iframe_embed" data-aspect-ratio="1.7790927021696252" data-auto-height="true" frameborder="0" height="600" scrolling="no" src="https://www.scribd.com/embeds/487855843/content?start_page=1&amp;view_mode=scroll&amp;access_key=key-ohNzsS4VcZugPJpmeca5" title=" MaterialEducativo EjercicioPhishing v2.1" width="100%"></iframe></p>

<p style="   margin: 12px auto 6px auto;   font-family: Helvetica,Arial,Sans-serif;   font-style: normal;   font-variant: normal;   font-weight: normal;   font-size: 14px;   line-height: normal;   font-size-adjust: none;   font-stretch: normal;   -x-system-font: none;   display: block;"><a href="https://www.scribd.com/document/487855843/-MaterialEducativo-EjercicioPhishing-v2-1#from_embed" style="text-decoration: underline;" <="" body="">

</a></p></body></html>

**Comment by kajov** [comment]
Exactly same issue, tried it out yesterday on myself sending from specific email to my gmail and when opened the malicious email update of the action have not been returned to the gophish dashboard. 
As well I wan to point out that it might been because gmail tends to block images and detect gopsish phishing type emails relatively easy and in my opinion the hidden image file that is automatically blocked can't push an update to the dashboard in the end.

**Comment by glennzw** [comment]
If the email open event isn't being logged, it could be that the email client is blocking remote content.

When the user clicks the link, are they taken to the phishing landing page? If they are it's very strange that it's not being captured in the UI

**Comment by glennzw** [comment]
Closing out as haven't heard back.
