### ISSUE TITLE
New Feature : Add a preview of Landing pages

### ISSUE THREAD

**Issue by nsiicm** [gophish/gophish#2078]
Hi, 
If I'm not putting this in the right place please let me know.

After some research, i can't find the feature I miss. 
It could be nice to have a button like in picture to see and test (credentials capturing) landing pages without launching a test campaign to be able to do it ! This in order to keep clean campaigns without a bunch of test campaigns in the middle of real ones. 
 
![gophish](https://user-images.githubusercontent.com/17740842/102335862-bcc80e00-3f90-11eb-941d-93cf73caec86.PNG)

Gophish version : 0.11.0

**Comment by glennzw** [comment]
Whilst you won't be able to submit data and simulate an actual landing page, you can preview what the page looks like by toggling the `Source` button in the Edit view:

<img width="1193" alt="Screenshot 2020-12-16 at 13 11 04" src="https://user-images.githubusercontent.com/3966613/102347227-65ca3500-3fa0-11eb-9b2a-1efd9307c891.png">

**Comment by kajov** [comment]
And if you want to see the page in full browser window, on the right after the source there is a Paper with magnifying glass, when you press on it, the preview of whole page will be opened in new tab/window
