### ISSUE TITLE
Landing page filters URL

### ISSUE THREAD

**Issue by kontez** [gophish/gophish#208]
I create a landing page with a form in it like this:  
`<form action="https://example.com/page.php" method="post">`     
Then I click on "Save page" and then on "Edit Page" and somehow the URL is filtered like this:      
`<form action="" method="post">`     

Screenshots:
<img width="814" alt="screen shot 2016-03-11 at 14 41 36" src="https://cloud.githubusercontent.com/assets/7038941/13703613/a15e6502-e797-11e5-861e-4a3cda44438c.png">

<img width="815" alt="screen shot 2016-03-11 at 14 42 09" src="https://cloud.githubusercontent.com/assets/7038941/13703617/a715d624-e797-11e5-9edf-324a05865a1d.png">

**Comment by jordan-wright** [comment]
Hey Marvin,

Thanks for the report! This behavior is intentional, since you selected to "Capture submitted data". We change the form's ```action``` attribute so that we can capture any data submitted.

By "null"'ing it out, we effectively tell the browser to submit the data to the same page the user is on. This allows us to ensure that all creds are sent to our landing page, where we can collect them.

Hope this helps!

**Comment by kontez** [comment]
Hey Jordan, thank you for your quick reply.  

I tried again with "Capture submitted data" unticked and the "bug" is still there.

**Comment by jordan-wright** [comment]
Correct, if you try it again unchecking the "Capture submitted data" unchecked, it should replace the action with ```"#"```, which will prevent form data from being submitted anywhere.

I'm afraid this is the only sure-shot way to consistently capture creds (or not) without having to offer a bunch of different sub options (such as where you want the creds sent, etc.) that would make the UX worse.

**Comment by kontez** [comment]
So there is no way to redirect the data somewhere after the user submits the form?

**Comment by jordan-wright** [comment]
Of course there is! The code is open source :smile: 

Just comment out this line https://github.com/gophish/gophish/blob/master/models/page.go#L36

Then check both "Capture submitted data" as well as "Capture passwords".

**Comment by kontez** [comment]
Thank you very much :)

**Comment by faisalmuneer** [comment]
Hi,

I am trying gophish recently and testing some scenarios. however when I enable Capture Submitted Data and the capture password everything seems fine except I am unable to find the submitted data. 

could anyone explain where does it go and how we can see it?

**Comment by kontez** [comment]
You can see the submitted data in the Campaign Overview when you click on each user :)
