### ISSUE TITLE
[Feature request] Configure send days and hours

### ISSUE THREAD

**Issue by TriYop** [gophish/gophish#2081]
In order to improve the credibility and therefore the impact of the emails sent, it would be interesting to configure the ranges of days and hours during which the emails are sent. It would be unlikely that a business email would be sent outside of office hours.

**Comment by glennzw** [comment]
Hi there. Good idea! We'll keep that in mind, but the to do list is a little long. In the meantime, this pull request might interest you:

https://github.com/gophish/gophish/pull/1557
