### ISSUE TITLE
Custom URL(127.0.0.1/?rid=xxxxx)

### ISSUE THREAD

**Issue by Gu-f** [gophish/gophish#2083]
What version of Gophish are you using?: 
gophish-v0.11.0-linux-64bit

Brief description of the issue: 
Custom URL

What are you expecting to see happen? :
What are you seeing happen?
Can I customize the URL ,,,,,,,,The URL may be added to the malicious signature library.
If only it could be changed at will.
Features:
127.0.0.1/?rid=xxxxx
 For example,I want to change it to/////////
---------------------------or
127.0.0.1/?page=xxxxx
---------------------------or
127.0.0.1/admin/login
---------------------------or
127.0.0.1/login?rid=xxxxx&auth=xxxxx
-----------------------------------etc................
How to modify it,,,,,,,,,,or I hope gophish add this function module.

**Comment by glennzw** [comment]
You can have any number of arbitrary parameters and subfolders, as long as the `rid` parameter is present. e.g:

```
http://127.0.0.1/?rid=Fw8Pyja
http://127.0.0.1/?foo=123&rid=Fw8Pyja&bar=567
http://127.0.0.1/users/login/?foo=123&rid=Fw8Pyja&bar=567
```

AFAIK there isn't an option (without changing the code or having a fronting proxy) to change the rid parameter name.

**Comment by Gu-f** [comment]
Thanks!
