### ISSUE TITLE
Is it possible to send appointment via gophish?

### ISSUE THREAD

**Issue by TheMMcOfficial** [gophish/gophish#2085]
What version of Gophish are you using?: 0.11.0

Brief description of the issue: 
Is there a way to send appointments via Gophish? If yes how can I do it ?

**Comment by glennzw** [comment]
What do you mean by 'appointment'? As in a calendar file? (eg ics)

If so, yes just include the calendar contents in the email body.

You can't attach one at the moment (using template variables) but the upcoming attachment support would allow this and is a good use case!

**Comment by TheMMcOfficial** [comment]
By appointment I meens a TEAMS meeting that you need to accept or reject. Or something that is automatically add to the calendar.

**Comment by kajov** [comment]
In a lot of phishing emails if you check them in your spam folders, you might find that there is attachments of any sort. Corporate tend to have infected links to "pdf" files, or even infected pdf file attached that execute a script when opened in the computer and steal the shadow file/cookies/temp creds etc.
I've seen multiple cases of piggybacking of malicious auto-executable on outlook calendar/event invites too.

So I do agree calendar based invite attachments would be a very nice integration and use-case for phishing campaigns.

**Comment by glennzw** [comment]
Keep an eye on the attachment support; I've added `.ics` so you can send calendar invites with gophish variables inside.

https://github.com/gophish/gophish/pull/1936
