### ISSUE TITLE
Setup Apache / Postfix ?

### ISSUE THREAD

**Issue by chris4269** [gophish/gophish#2086]
I am looking for a documentation for the installation or at least the prerequisites
Ubuntu 20.04 ?
Apache 2 ?
Postfix  ?
SSL ?
Domain ?
...

**Comment by edermi** [comment]
Did you take a look at the documentation? https://docs.getgophish.com/user-guide/installation

**Comment by chris4269** [comment]
hello
your tool works with https://mailcow.email/ ?
Thank

----- Mail original -----
De: "Michael Eder" <notifications@github.com>
À: "gophish/gophish" <gophish@noreply.github.com>
Cc: "chris4269" <grenier.christophe@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Mardi 22 Décembre 2020 23:13:11
Objet: Re: [gophish/gophish] Setup Apache / Postfix ? (#2086)





Did you take a look at the documentation? https://docs.getgophish.com/user-guide/installation
