### ISSUE TITLE
Alternative GoPhish Reporting Options

### ISSUE THREAD

**Issue by mda1125** [gophish/gophish#2087]
What version of Gophish are you using?:  0.11.0

Brief description of the issue: IMAP Reporting works but what other options are there if your GSuite has IMAP disabled for the Org?

Looking for alternative methods for users to send off a Phishy email and somehow have it reported for that campaign other than IMAP.  Concept works and I've tested it outside our org.

But our current GSuite is setup for no POP3 and no IMAP access.

So I'm looking for alternative methods to check that user has reported a campaign email as a phish

**Comment by glennzw** [comment]
Hi there!

The alternative is to have a 'Report' button in the interface that scans the email for the RID gophish parameter and hits the gophish report endpoint. I built such a addon for GMail ages ago, but haven't maintained it. There might be other addons out there that are more generic, e.g a quick google gave me [this](https://workspace.google.com/marketplace/app/phishalarm/939483390031) (I haven't checked it out properly).

This was my version:

![CHROME03](https://user-images.githubusercontent.com/3966613/105495863-9b0b2680-5cb4-11eb-9141-1c87b63d38fe.png)
![CHROME01](https://user-images.githubusercontent.com/3966613/105495868-9c3c5380-5cb4-11eb-93fb-ab66e7eba1c6.png)
![CHROME02](https://user-images.githubusercontent.com/3966613/105495870-9cd4ea00-5cb4-11eb-8143-0a85d26dee88.png)
