### ISSUE TITLE
Support for changing of admin and landing pages URL base path

### ISSUE THREAD

**Issue by skyfox675** [gophish/gophish#2088]
What version of Gophish are you using?: `0.11.0` on docker

I would like to request support for a parameter in config.json to configure the base URL path for the admin listener and the landing page listener. This will help with K8s ingresses where gophish will not be at the URL root.

**Comment by glennzw** [comment]
Hi @skyfox675, thanks for reaching out. For the landing pages, you can have any additional url parameters and path parameters. e.g, all of these would work from the target's perspective:

```
http://127.0.0.1/?rid=Fw8Pyja
http://127.0.0.1/?foo=123&rid=Fw8Pyja&bar=567
http://127.0.0.1/users/login/?foo=123&rid=Fw8Pyja&bar=567
```

So, when you launch the campaign you'd set the landing page URL as any of the above, removing the rid parameters which would get automatically added.

As for custom path for the admin page, for my purposes I just slap a proxy in front (e.g nginx or Caddy).

The todo list is quite long so I don't know if we'd get to this any time soon TBH.

Hope that helps!
