### ISSUE TITLE
Fail to launch admin page port 3333

### ISSUE THREAD

**Issue by clement280397** [gophish/gophish#209]
Hello,

For me ( in MAC OSX) it's impossible to get the admin page (localhost:3333/login)
i just get a full blank page.

Any solutions ?

Update no other process on that port: 
  
<img width="1102" alt="capture d ecran 2016-03-11 a 21 06 14" src="https://cloud.githubusercontent.com/assets/7127000/13714155/3777e9f2-e7cd-11e5-98f0-b25e8fe8a2b8.png">

**Comment by jordan-wright** [comment]
Are you using the pre built binary or building from source? Is there any error messages in the terminal window?

**Comment by clement280397** [comment]
Hello,
I'm using  the pre built binary, there is error in terminal, just connexions infos

**Comment by jordan-wright** [comment]
So you don't see your connection in the terminal when you try to hit the admin page?

**Comment by clement280397** [comment]
On the terminal, i get the user agent and connexion when i go on the login page

**Comment by jordan-wright** [comment]
That's odd.. Is there any other data you can provide? Any other hints as to what might be going on?

What happens if you try another browser?

**Comment by clement280397** [comment]
Yep,
I got no specific informations except that the blank page contains a Shadow tag .
I don't remember exactly but there where nothing on screen but html file wasn't empty.
But there where no login form or anything like that

**Comment by jordan-wright** [comment]
Glad to hear building from source fixed it. I'll go ahead and close this specific issue out.
