### ISSUE TITLE
How to automagically reset inital admin password

### ISSUE THREAD

**Issue by skyfox675** [gophish/gophish#2090]
What version of Gophish are you using?: Docker, gophish/gophish:latest, 0.11.0

Brief description of the issue: Looking for information on a programic way to preform the initial admin password reset. I am currently supplying the `GOPHISH_INITIAL_ADMIN_PASSWORD` env variable to the container and is working as expected.

I am curious if there is a way to update the MySQL (in my case) database via a MySQL query or generate an admin API token via MySQL query and use that to reset the password?

Thanks in advance!

**Comment by skyfox675** [comment]
I've made some progress on this, and I'll be updating the password's hash in the DB.

Question though in `auth/auth.go` I see Bcrypt's DefaultCost being used but I don't see a salt specified and I also don't see it stored in the DB anywhere. I am assuming that a salt isn't used here since it's still possible to apply the bcrypt hash for `gophish` to recover from a lost admin password. 

If you have a moment @jordan-wright would you mind lending your thoughts on this?

Thanks!

**Comment by skyfox675** [comment]
Closing, completely overlooked using the API and pulling an API key from the DB, thanks!

**Comment by mumbaindians453363-create** [comment]
Instagram id password hack
