### ISSUE TITLE
Admins can't see other admins landing pages

### ISSUE THREAD

**Issue by HelterSkelter5** [gophish/gophish#2091]
What version of Gophish are you using?: 0.11.0

Brief description of the issue: When one admin creates a landing page, other admins can't see it.

What are you expecting to see happen? : One admin creates a landing page, other admins should be able to see it.

What are you seeing happen? Admins can't see each other's landing pages.

**Comment by HelterSkelter5** [comment]
Just seen this is covered under #2017 - not a great design as they point out. Are there any estimates on when this limitation might be removed?

**Comment by glennzw** [comment]
There aren't any plans at the moment to change this, as it'd be quite a large overhaul. Sorry about that.
