### ISSUE TITLE
Landing page redirect on data submission not working

### ISSUE THREAD

**Issue by lwild12** [gophish/gophish#2092]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
V10
Brief description of the issue: 
When submitting data to the form the redirect to doesn't work. GoPhish appears to be clearing the <form action=""> tag
What are you expecting to see happen? :
Redirect to our phishing training
What are you seeing happen?
Redirect to Gophish hostname/?
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
<!DOCTYPE html><html lang="en"><head>
	<meta http-equiv="x-ua-compatible" content="ie=edge"/><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
	<title>DfE Sign-in</title>
	<link href="https://cdn.signin.education.gov.uk/css/govuk/fonts.css?version=1" rel="stylesheet"/>
	<link href="https://cdn.signin.education.gov.uk/css/govuk/govuk-template.css?version=1" rel="stylesheet"/>
	<link href="https://cdn.signin.education.gov.uk/css/screen.css?version=1" rel="stylesheet"/>
	<link href="https://cdn.signin.education.gov.uk/images/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
	<link href="https://cdn.signin.education.gov.uk/images/apple-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/>
	<link href="https://cdn.signin.education.gov.uk/images/apple-icon-167x167.png" rel="apple-touch-icon" sizes="167x167"/>
	<link href="https://cdn.signin.education.gov.uk/images/apple-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>
	<link href="https://cdn.signin.education.gov.uk/images/apple-icon.png" rel="apple-touch-icon"/><meta property="og:image" content="https://cdn.signin.education.gov.uk/images/opengraph-image.png"/>
</head>
<body><script>document.body.className = ((document.body.className) ? document.body.className + ' js-enabled' : 'js-enabled');</script>
<div id="skiplink-container">
<div><a class="skiplink" href="#content">Skip to content</a></div>
</div>

<div class="wrapper">
<header id="global-header">
<div class="header-wrapper">
<div class="header-global">
<div class="header-logo"><a class="content" href="https://www.gov.uk" id="logo" title="Go to the GOV.UK homepage"><img alt="" height="32" src="https://cdn.signin.education.gov.uk/images/gov.uk_logotype_crown_invert_trans.png" width="36"/> GOV.UK </a></div>

<p class="header-title">Sign<span aria-hidden="true">-</span>in</p>
</div>
</div>
</header>

<div class="header-user">
<div class="header-inner">
<div class="service-info">
</div>
</div>
</div>

<main id="content" tabindex="-1">
<div class="grid-row">
<div class="col-8">
<h1 class="heading-xlarge">GOV.UK Sign-in</h1>
</div>
</div>

<div class="row">
<div class="col-6">
	<p>Don&#39;t already have an account?</p><p>
	You can now sign in with your Office 365 Account.
	Simply enter your Email address and password below.</p>


<fieldset><legend class="heading-medium">Sign-in</legend>

<div class="form-group "><label class="form-label" for="username">Email address</label> <input class="form-control full-width" id="username" name="username" type="text" value=""/></div>

<div class="form-group "><label class="form-label" for="password">Password</label>

<div class="show-password full-width"><input class="form-control" id="password" type="password"/></div>
</div>
</fieldset>


<div class="form-submit submit-buttons"><form action=""><button class="button" type="submit">Sign in <span class="loader spinner-inline vh"> </span></button></form><span></span></div>
</div>
</div>

<div class="row">
<div class="col-6">
</div>
</div>
</main>
</div>

<footer class="group js-footer" id="footer">
<div class="footer-wrapper">
<nav>

</nav>

<div class="footer-meta">
<div class="footer-meta-inner">
<div class="open-government-licence">
<p class="logo"><a href="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/" rel="license">Open Government Licence</a></p>

<p>All content is available under the <a href="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/" rel="license">Open Government Licence v3.0</a>, except where otherwise stated</p>
</div>
</div>

<div class="copyright"><a href="https://www.nationalarchives.gov.uk/information-management/re-using-public-sector-information/copyright-and-re-use/crown-copyright/">© Crown copyright</a></div>
</div>
</div>
</footer>


</body></html>
```
Please provide as many steps as you can to reproduce the problem:
 * Step 1 - User clicks on phishing email
 * Step 2 - User submits data

**Comment by glennzw** [comment]
Without wanting to dig too deeply into your code just yet, the 'secret recipe' to a successful redirection is to have a POST request with no action. Here's a sample working page:

```HTML
<html>
 <body>
  <form action="" method="post" name="form">
    <label>Username:</label> <input name="username" type="text"/><br/>
    <label>Password:</label> <input name="password" type="password"/><br/>
   <input id="login" name="login" type="submit" value="Login"/>
  </form>
  </body>
</html>
```

It looks like if you edit your:

```HTML
<form action=""><button class="button" type="submit">Sign in <span class="loader spinner-inline vh"> </span></button></form><span></span></div>
```

to include the action and POST you might have better luck:

```HTML
<form action=""><button class="button" type="submit" method="post" action="">Sign in <span class="loader spinner-inline vh"> </span></button></form><span></span></div>
```

**Comment by lwild12** [comment]
Hi @glennzw,
Have just tested this but it is still redirecting to host/? instead of host/static/notice.html

Any ideas?

**Comment by glennzw** [comment]
@lwild12 please could you share your `config.json` and a screenshot of your landing profile page, e.g.:

![Screenshot 2021-03-06 at 18 00 05](https://user-images.githubusercontent.com/3966613/110216226-d13be880-7ea5-11eb-930b-95fa8679cecc.png)

Specifically I'm interested in your 'Redirect to' option.

**Comment by lwild12** [comment]
Hi @glennzw
config.json:
`{
	"admin_server": {
		"listen_url": "0.0.0.0:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "gophish_admin.key"
	},
	"phish_server": {
		"listen_url": "0.0.0.0:80",
		"use_tls": false,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": "",
	"logging": {
		"filename": "",
		"level": ""
	}
}
`

![image](https://user-images.githubusercontent.com/6226324/110239211-bf0d8900-7f3d-11eb-9975-f51979b24df1.png)

**Comment by glennzw** [comment]
Hmm this all looks fine. I've tried to replicate your setup as follows:

## Landing Page
![Screenshot 2021-03-07 at 17 55 43](https://user-images.githubusercontent.com/3966613/110253911-99f03900-7f84-11eb-9228-9ab5d48ef6a6.png)

...and when the user submits data on the login page they're redirected to your page:


https://user-images.githubusercontent.com/3966613/110253938-bdb37f00-7f84-11eb-87af-b3604f8d609d.mov

I'm not sure if you can see anything different compared to your setup?
