### ISSUE TITLE
It is possible to see user passwords as hash(not as a plaintext)

### ISSUE THREAD

**Issue by hakanerensan** [gophish/gophish#2093]
I don't want to see users passwords as **clear text**. 

Is there a way to understand that, user send input without stored or captured his/her password.

Best regards,

**Comment by kajov** [comment]
Workaround for that in my opinion would be:

* Set up a MySQL salt/hash that every entry is salted/hashed or run periodical salt/hash checks via script to remove clear text credential information in the database.

I have not spotted any kind of option in config file or digging in the code that hashing is done in any way. If I am correct as well somewhere in Documentation it has been stated that passwords will be stored in plain text in db(please correct me if I am wrong)

We might need to wait for hashing function/algorithm to be integrated later in development.

**Comment by glennzw** [comment]
Your two best options are either to disable the capturing of passwords (the tickbox in the campaign creation dialog), or to encrypt the entire MySQL database:

https://mariadb.com/kb/en/data-at-rest-encryption-overview/

Alternatively, as @kajov points out you could create individual salts per user or per column but I don't know how trivial that is with MySQL.

I have a solution in the works that will be seamless, and store keys in the browser. I'll update this thread when I find time to finish it.

**Comment by kajov** [comment]
@glennzw The hashing and salting in mysql is quite complicated, it is possible to do it but it's doneusing SHA1, unless salt method has been updated to SHA256 or SHA512.

So you can generate 6 character (hex value only) random string
```MYSQL
SELECT SUBSTRING(SHA1(RAND()), 1, 6) AS salt
```
Remember to save it in either same column by prefixing the hash value with salt

Once you've save the salt simply hash the password with this query
```MYSQL
SELECT SHA1(CONCAT(salt, 'passwrd')) AS hash_value
```
As I said in above statement it might support better versions of SHA I haven't tested it yet so I can't say anything about it.

**Comment by jordan-wright** [comment]
Hi there!

There is an older PR in #1314 which attempts to allow encrypted passwords to be stored, but I'm not sure that's really what you're looking for.

So beyond that, I don't know that there's much you can do today with Gophish to solve this. In the future, it's possible we could do some trickery when password submission is disable in Gophish to still give a checkbox indicating if the password _would have been_ submitted, but this wouldn't be perfect.

**Comment by glennzw** [comment]
I'm going to close this out for now as the supplied solutions are the best we can offer at the moment.
