### ISSUE TITLE
SMTP QUESTION

### ISSUE THREAD

**Issue by Pyth18** [gophish/gophish#2094]
Hello, I am new in the field of informatics. I was testing this GoPhish tool and the question arose as to whether it is better to configure my own SMTP server or use Gmail's SMTP instead. Above all so that phishing is not marked as spam. Thank you for your answers.

**Comment by robertjager** [comment]
It really depends on your case @Pyth18. 

Let's asume your business is called contoso.com. And you want your phishing test send from the domain contoso.com, than use your own SMTP server. If you want the mail send from contooso.com (to see if it fools your end-users), register that domain-name and use a mailservice like Sendgrid (free for max. 100 mails per day).

If you want to use contoso@gmail.com, register this account at Gmail, and use Gmail as SMTP server. 

Don't use a public SMTP server and a random sending domain. 99% of the spamfilters will tell you it's spam. 
Every situation needs a different approach. Happy GoPhish!

**Comment by glennzw** [comment]
@robertjager is spot on. Good luck @Pyth18!

Closing this out.

**Comment by kodykat** [comment]
This was immensely helpful, thank you @robertjager
