### ISSUE TITLE
CORS policy

### ISSUE THREAD

**Issue by knayt** [gophish/gophish#2098]
_What version of Gophish are you using?:_   0.11.0

I am making an application that will make changes by API.
When you call `PUT` or `DELETE` it does not work. Since I get in response:

`Access to XMLHttpRequest at 'http://1.2.3.4:3333/api/templates/16?api_key=bfd7b4' from origin 'http://localhost:3000' has been blocked by CORS policy: Method DELETE is not allowed by Access-Control-Allow-Methods in preflight response.`

`Access to XMLHttpRequest at 'http://1.2.3.4:3333/api/templates/16?api_key=bfd7b4' from origin 'http://localhost:3000' has been blocked by CORS policy: Method PUT is not allowed by Access-Control-Allow-Methods in preflight response.`

I used some advice but it didn't help.

Is there any change that I can make on the server to allow this action?

**Comment by glennzw** [comment]
Before I did too deep into this, are other endpoints working for you? Is it just this one that fails?

**Comment by knayt** [comment]
`GET` and `POST` working. But if I want to delete the email template then I get an error.

**Comment by jordan-wright** [comment]
Yep, you're absolutely right. This is a bug since we were missing these methods in our CORS handling. Fixed in #2105.

**Comment by glennzw** [comment]
Thanks for your patience on this @knayt, I've merged this into master.
