### ISSUE TITLE
[Feature Request] Multi-Part MIME Email (HTML and Plain-Text)

### ISSUE THREAD

**Issue by websecnl** [gophish/gophish#2099]
SpamAssassin is really cracking down on HTML Only mails.
I was wondering if the GoPhish authors or any people in the community can either create a fork which supports this feature or/and eventually even commit the change to the official branche of gophish as this feature would be epic.

**Comment by glennzw** [comment]
Hi there, thanks for reaching out with this idea! We can already send both plain text and HTML emails in the same email AFAIK, but perhaps not multi-part MIME. Do you have any pointers on where to get started, or some discussions around why the MPM would help bypass spam filters? 

Without the above, I have a perfect score on mail-tester.com for my campaigns' "spaminess"

**Comment by jordan-wright** [comment]
I'm almost 100% certain that we send multipart emails - especially if both the text and HTML are filled out for a template since that's really the only way to send them...

Without a full test email showing what you're seeing, and commentary over that email suggesting what you'd like to see instead, I'm afraid there isn't much we can do here.

**Comment by websecnl** [comment]
No, even if you input text and html it will either do only text or only html but not both, the html only must be multi mime otherwise it will always return a high spam probability score

**Comment by jordan-wright** [comment]
I'm afraid my first comment stands- we'll need to see what you're doing in Gophish and the corresponding email to be able to effectively troubleshoot.

For example, I made an email template with both text and HTML, and this was the email that was sent- you can see it's a multipart email containing both the text and HTML parts:

```
Content-Type: multipart/alternative; boundary=93feeecd72470b4584f0028d65b06cd0e8c489f3b33c6e488ea7511ed1ff
Date: Sun, 24 Jan 2021 13:51:34 -0600
From: asdf@asdf.com
Message-ID: Ac_rJcEKtwv37i7D_xkpfn8JMr3zAP42wBLlhQKxAzg=@mailhog.example
Mime-Version: 1.0
Received: from mac.local by mailhog.example (MailHog)
          id Ac_rJcEKtwv37i7D_xkpfn8JMr3zAP42wBLlhQKxAzg=@mailhog.example; Sun, 24 Jan 2021 19:51:35 +0000
Return-Path: <asdf@asdf.com>
Subject: asdf
To: "J W" <j@w.com>
X-Mailer: gophish

--93feeecd72470b4584f0028d65b06cd0e8c489f3b33c6e488ea7511ed1ff
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset=UTF-8

This is sample text
--93feeecd72470b4584f0028d65b06cd0e8c489f3b33c6e488ea7511ed1ff
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html; charset=UTF-8

<html>
<head>
	<title></title>
</head>
<body>
<p>This is some sample HTML</p>
<img alt=3D'' style=3D'display: none' src=3D'http://localhost/track?rid=3Dp=
review-rCKYHCC'/></body>
</html>

--93feeecd72470b4584f0028d65b06cd0e8c489f3b33c6e488ea7511ed1ff--
```

**Comment by websecnl** [comment]
Hmm yea , this doesn't work for me

**Comment by glennzw** [comment]
My tests concur with @jordan-wright. @websecnl could you give us more details on how to reproduce what you're seeing? Perhaps it's an artefact of your mail server stripping out plaintext or HTML.

I'm testing with postfix on Linux.

**Comment by glennzw** [comment]
Closing out as haven't heard back.
