### ISSUE TITLE
Ability to Schedule Campaigns

### ISSUE THREAD

**Issue by jordan-wright** [gophish/gophish#21]
The ability to setup and schedule campaign in advance would add some pretty solid benefits automated campaign generation.

This might require a db schema update, so I'll probably put this at 0.2.

**Comment by richardontheinternet** [comment]
Oh you're one sneaky dude. I'd love to start my day with 500 emails all perfectly arranged and ready to go and prepared from the day before. Like an alarm clock for fun. Great Idea.

**Comment by edgarsblackanom** [comment]
The feature to schedule the campaigns is working?

**Comment by jordan-wright** [comment]
Yep! Sure is - just build from the latest source.

**Comment by AravindSreenivasa** [comment]
Hi Jordan,
I am facing issue in scheduling the campaigns. For range of some hours (2 hrs atleast), if the campaign is scheduled, emails are being sent instantly. I have tried changing the date and it did not send it right away. I am not sure why this is happening.
Here is the campaign created, scheduled at 5.20 PM MST
![campaign](https://cloud.githubusercontent.com/assets/14154524/17042043/6087e60e-4f5f-11e6-9800-e6764303ab7d.JPG)

It got sent out instantly after created, at 4.03 PM MST
![console](https://cloud.githubusercontent.com/assets/14154524/17042042/6084ad4a-4f5f-11e6-9073-2312d0dd55e3.JPG)

Let me know if I am missing something here.

**Comment by jordan-wright** [comment]
Are you using the most up to date version of both the front end (static assets) and backend code? Did you "go build" after getting the new code?

Thanks!

**Comment by AravindSreenivasa** [comment]
Yes. I downloaded it on June 20th, 2016 and have done "go build".

**Comment by AravindSreenivasa** [comment]
Hello Jordan,
I pulled the code yesterday(7/25/2016) and built it from source. I am still facing the issue in scheduling. I had set three Campaigns with 12,14, and 16 hour later and all of them were sent within next 2 minutes.

**Comment by yogesh-imorsetech** [comment]
Hey how do I schedule the campaign in gophish? can someone plz guide. Its urgent for me
