### ISSUE TITLE
Feature request: redirect after landing page submission

### ISSUE THREAD

**Issue by bleepnetworks** [gophish/gophish#210]
hey jordan,

first up well done, gophish is slick.

was wondering if there is a way to redirect users after they submit the landing page, e.g. to the actual site you are trying to fish creds for.

**Comment by rfdevere** [comment]
Jordan this is behaviour seen in SET and is great, people just thing the
page has crashed... by the time suspicion is high most are usually on the
real site checking for ssl certs ha

On Mon, Mar 14, 2016 at 11:38 AM, bleepdev <notifications@github.com> wrote:

> hey jordan,
>
> first up well done, gophish is slick.
>
> was wondering if there is a way to redirect users after they submit the
> landing page, e.g. to the actual site you are trying to fish creds for.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gophish/gophish/issues/210>.
>



-- 
*Richard De Vere*
*Principal Consultant*

*Tel:* +44 754 6655448
*Web:* TheAntiSocialEngineer.com
*Email:* FrontDesk@TheAntiSocialEngineer.com
*Twitter:* @AntiSocial_Eng


The AntiSocial Engineer Ltd is a limited company registered in England and
Wales. Company Registration No. 09367111 Registered Office: 4 Capel Street,
Huddersfield, HD6 3AJ This message contains confidential information and is
intended only for AntiSocial Engineer customers. E-mail transmission cannot
be guaranteed to be secure or error-free as information could be
intercepted, corrupted, lost, destroyed, arrive late or incomplete, or
contain viruses. The AntiSocial Engineer Ltd cannot accept liability for
any errors or omissions in the contents of this message, which may arise as
a result of e-mail transmission. Please note that The AntiSocial Engineer
Ltd may monitor, analyse and archive email traffic, data and the content of
email for the purposes of security, legal compliance and staff training.

**Comment by jordan-wright** [comment]
Yeah sure thing! This has actually been on my mind for a while. Glad we have an issue for it.

I'll get this implemented pronto.

**Comment by kontez** [comment]
I had this issue a while ago, see #208    
I modified route.go and added an http.Redirect in the POST case.    
Surely not the best way nor the most elegant, but it works ¯\_(ツ)_/¯

**Comment by jordan-wright** [comment]
Ok! This should be implemented. It looks like this:

![image](https://cloud.githubusercontent.com/assets/1317288/13895812/bff51d62-ed46-11e5-8724-0973971b49f1.png)

When creds are submitted, if a redirect url is configured it will send a 302 redirect to that url. You must have the "Capture creds" checkbox checked to set this, which makes sense as you only redirect after receiving creds.

Let me know what you think!

**Comment by rek3** [comment]
Hey Jordan. I was hoping there would be a feature like this but unfortunately it's doesn't seem to work in my environment. I have the field to input the redirect URL but it does nothing upon submission. I also tried implementing onclick events on the form itself, on the submit button, etc (I know action is cleared out) but still can't get it to stop simply refreshing the form page once the credentials are submitted. I also looked over the change logs for the files used to implement this and I have verified they're updated. Any suggestions?

**Comment by xkb77x** [comment]
Hi,

I am fairly new to GitHub and this sort of thing. I have implemented GoPhish here at work for our phishing training and we are really excited about it.  We really want to redirect after capturing the usernames.

I am wondering how I get the "redirect to" dialog box? I have been looking around and saw #208 and #314 but I am not sure how to get this working.

**Comment by alexlomas** [comment]
You'll need to build from source, the current binaries predate this.
Hoping Jordan will do a new release soon ^_^

**Comment by xkb77x** [comment]
Alex,

I am not super familiar with building and coding. Is there an ETA on a release time for the new release?

If not is there a good guide on how to implement this change on my own?

Thanks,

Kellon

**Comment by jordan-wright** [comment]
Hey everyone,

New release coming soonish - just adding some last minute things.

There are instructions on how to build from source in the User's Guide. If you run into any questions let me know.

Thanks!

**Comment by xkb77x** [comment]
Great. Thank you Jordan!

**Comment by jiimk** [comment]
Any word on the new build for this feature?  I used the latest 64-bit Windows build and I don't see that field option.  I began the build from source, but and just way too busy to keep consistent.  Love this product btw.  Nice work...

**Comment by pathetiq** [comment]
Hi all,

We've found that this feature was also require for our campaign so one of our dev (@hhaidar) create this gist to add to any campaign forms. 

In this code the form need to be named "login_form".

https://gist.github.com/hhaidar/bc907b7bc20897e0fe3a9759aee04c9d

Using this it capture the data with an ajax request and then forward the user to a remote site where data can also be push in the url (GET).

Hope it helps some of you while the next release.

Cheers
