### ISSUE TITLE
not able to login with gophish login default credencials

### ISSUE THREAD

**Issue by Phant0m58** [gophish/gophish#2101]
What version of Gophish are you using:-v0.11.0

Brief description of the issue:  i am not able to login with the default credentials provided README.md

What are you expecting to see happen? : notification of login fail

**Comment by glennzw** [comment]
There is no longer a default password, check the console output when you start gophish for the first time - the randomly generated password will be output there.

**Comment by Phant0m58** [comment]
Hello Team,

Can you be bit more specific?

Regards,
Shubham
