### ISSUE TITLE
Erro in open campaign

### ISSUE THREAD

**Issue by meetgyn** [gophish/gophish#2102]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

**What version of Gophish are you using?:** 
 0.11.0 
**Brief description of the issue:** 
I have a problem with Gophish sending a campaign, and I am unable to resolve it.
For example: I set everything up in my kali, when I send a campaign and the victim clicks the link instead of going straight to the client's cpanel he points to the kali's local ip. And with that I can't get it to work.
What are you expecting to see happen? :

What are you seeing happen?
I need that when clicking on the link the client is redirected to his cpanel for example:
Ip of kali linux 192.168.15.69
customer cpanel: webmail.hostgator.com.br
When clicking on the campaign email, it does not open the webmail, it is going straight to the kali ip.

**Comment by glennzw** [comment]
Could you paste the contents of your `config.json` file, and also the terminal output from when you run gophish.

**Comment by meetgyn** [comment]
![image](https://user-images.githubusercontent.com/3695608/105482813-af84fa00-5c87-11eb-92db-4e12d8102501.png)
The problem is occurring when I try to use it from wan> lan.
for it to work, I need to be inside the customer's environment, on the same network. Because clicking on the link that gophish sends does not redirect you to the real page.
for example: I send a gmail link to the victim ,. The victim opens the email and will enter his credentials, the gophish of the credentials error and not redirected to gmail.com. And another thing I noticed, and that I can't use my network's gophish, because it points to the ip of my local kali. I would have to solve this.

I thank you for your help.

**Comment by jordan-wright** [comment]
Hi there!

To start, I encourage you to check out [this section](https://docs.getgophish.com/user-guide/faq#events-arent-showing-up-on-the-dashboard) of our FAQ which generally gives some guidance on how to troubleshoot issues like this.

The tl;dr is that everything depends on what URL you use when creating the campaign. That URL is going to be put in the links in the email. So if the user is being taken somewhere you don't want them to go, either the URL in the campaign is wrong, or the email template isn't using the `{{.URL}}` template placeholder.

Hopefully this puts you on the right track to figuring out what's going here.

**Comment by meetgyn** [comment]
Thank you so much.
I will do further tests to remedy this problem. I believe that it is only a configuration error on my part.
I tried to put no-ip or DDNS to direct but without success too.
But and stirring that we will be able to solve rs. Hugs
> 
> 
> Hi there!
> 
> To start, I encourage you to check out [this section](https://docs.getgophish.com/user-guide/faq#events-arent-showing-up-on-the-dashboard) of our FAQ which generally gives some guidance on how to troubleshoot issues like this.
> 
> The tl;dr is that everything depends on what URL you use when creating the campaign. That URL is going to be put in the links in the email. So if the user is being taken somewhere you don't want them to go, either the URL in the campaign is wrong, or the email template isn't using the `{{.URL}}` template placeholder.
> 
> Hopefully this puts you on the right track to figuring out what's going here.

**Comment by glennzw** [comment]
Closing out as haven't heard back, feel free to reopen.
