### ISSUE TITLE
Gophish getting crashed automatically

### ISSUE THREAD

**Issue by prikk1** [gophish/gophish#2103]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.8.0
Brief description of the issue: 
Getting crashed automatically. Similar as issue #1570 
What are you expecting to see happen? :
Work without getting crash, open Gophish dashboard page post login.
What are you seeing happen?
When I run Gophish, it opens login page and allow me to enter user credentials, after that it immediately crashes and gives connection refused error. I read about similar issues and it seems this could be related to template and {{.URL}}.
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

time="2021-01-22T15:51:13+08:00" level=warning msg="No contact address has been configured."
time="2021-01-22T15:51:13+08:00" level=warning msg="Please consider adding a contact_address entry in your config.json"
goose: no migrations to run. current version: 20190105192341
time="2021-01-22T15:51:13+08:00" level=info msg="Starting phishing server at http://XXX.XXX.XXX.XXX:80"
time="2021-01-22T15:51:13+08:00" level=info msg="Starting admin server at http://XXX.XXX.XXX.XXX:3333"
time=""2021-01-22T15:51:13+08:00" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
time="2021-01-22T15:52:13+08:00" level=info msg="Sending emails to mailer for processing" num_emails=2

Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by prikk1** [comment]
Should we force stop the campaign which is running? If yes, then what will be the command?

**Comment by glennzw** [comment]
One test would be to use a new database connection, to see if the problem is in there. If you're using SQLite just rename gophish.db to gophish.old.db or something. If MySQL, create a new database. If it still crashes, then the data is not the problem, if it doesn't, then something is fishy in your datastore.

Did you delete anything (templates, etc) after dispatching the campaign?

You could try to 'force' stop by manually editing the database - I suspect marking the campaign as complete and/or purging the message queue.

**Comment by prikk1** [comment]
It is SQLite. No we didn’t deleted any template.
How can we manually edit the DB and force stop the campaign?

**Comment by prikk1** [comment]
Where can I find the steps to manually edit the DB and force stop the campaign?

**Comment by prikk1** [comment]
Hi. Can anyone advise on this issue. I am still getting the same error. How can I manually edit the DB and force stops the campaigns. After I login to teh portal, it tries to open the dashboard and then suddenly it crashes.

**Comment by prikk1** [comment]
I will close my issue here, not sure the exact issue but looks like DB was corrupted and GoPhish started working after we restored old backup.
