### ISSUE TITLE
is gophish still maintained?

### ISSUE THREAD

**Issue by asaqib27** [gophish/gophish#2104]
I am opening an issue that is not an issue actually but I am doing so because I found no way of communication "No Twitter", "No Gitter" & "No Discord"...

There are lots of open issues and PR since 2016 that are still open. 
Are they closed? or is gophish no more maintained?

**Comment by jordan-wright** [comment]
Hi there,

Gophish is still maintained. Maintenance has slowed down a bit as I’ve had other priorities to attend to, but I’m working to bring in more talented folks to help out moving forward.

I’ve intentionally chosen to put all communication here in GitHub issues to reduce the number of places I need to check frequently.

And it’s expected that some PRs and issues remain open for a long period of time. Chances are I just haven’t gotten around to reviewing them.

Hope this helps!

**Comment by glennzw** [comment]
@asaqib27 I'd say it's very actively maintained :) Feel free to open an issue (I responded to around 20 yesterday that were piling up).

**Comment by asaqib27** [comment]
Thanks...

You can close this one 😀
