### ISSUE TITLE
Gophish ability to capture credentials windows version

### ISSUE THREAD

**Issue by Hemza** [gophish/gophish#211]
Hello Jordan , i'm writing you  in order to know if the last version ( gophish windows version last release )  offer the  ability to capture credentials with just a click ( the availible  windows version),
i'm waiting for ur answer as soon as possible
Thank you

**Comment by jordan-wright** [comment]
Yes it does

**Comment by Hemza** [comment]
Thank you my freind ,
just  a question can you give me the best smtp config to send gophish phishing emails via gmail i mean with email account

**Comment by jordan-wright** [comment]
Hi Hemza,

You can find SMTP settings for gmail with a simple google search for "gmail SMTP settings".

Please understand there is only so much support bandwidth we can offer on open source projects. We try to keep these issues on gophish bugs and features, not as much on how to best configure gophish for your environment.

When you create an issue with questions like these, please indicate:

* What you've tried so far (specific settings)
* What happened when you tried it
* What you expected to happen when you tried it
* Any logs, errors you receive

Thanks!
Jordan
