### ISSUE TITLE
404 error page not found

### ISSUE THREAD

**Issue by mkannan22** [gophish/gophish#2111]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.11.0
Brief description of the issue: 
Landing page says 404 page not found 
What are you expecting to see happen? :
The imported site from Landing Page.
What are you seeing happen?
Landing page says 404 page not found 
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

import (example https://company.com)
displays perfectly in the Landing page HTML editor, click save and successful

Please provide any terminal output that may be relevant below:

time="2021-02-05T23:33:40Z" level=info msg="X.X.X.X - - [05/Feb/2021:23:33:40 +0000] \"GET /?rid=jP1SJlSjP1SJlS HTTP/1.1\" 404 19 \"\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36\""

Please provide as many steps as you can to reproduce the problem:
Filled in Email Template using correct URL variable. 
Filled in Landing Page by import site successfully.
Filled in Group successfully.
Filled in Sending Profile successfully. 
Filled in New Campaign with correct values and URL of the gophish server as the public domain name (tested with IP, http, https as well)
Email received successfully with correct link including the rid with number. 
Link is clicked on and goes to correct website, yet I see a 404 page not found error. 
The gophish server lives on EC2 with rules setup to allow all traffic on 80 and 443, but restrict access to 3333 to my IP only.

**Comment by glennzw** [comment]
This is a tricky one. If you manually view your campaign, and copy an rid parameter does that work? e.g:

![Screenshot 2021-02-10 at 18 09 05](https://user-images.githubusercontent.com/3966613/107552529-88a54e00-6bcb-11eb-8deb-fc834516db7b.png)

and then:

![Screenshot 2021-02-10 at 18 12 07](https://user-images.githubusercontent.com/3966613/107552587-9c50b480-6bcb-11eb-89a8-6dfebe96e416.png)


Also, make sure you haven't marked the campaign as completed, or you'll get 404s when trying to access the landing page.

**Comment by mkannan22** [comment]
I figured it out. I removed the {{.RId}} parameter from the email template (even though it came across perfectly in the email itself) and switched URL to IP along with http in the Campaign. From there I implemented letsencrypt and adjusted appropriate DNS settings. Thank you!
