### ISSUE TITLE
Phishing Event not Capturing, Running on Localhost 

### ISSUE THREAD

**Issue by khafitbimo** [gophish/gophish#2114]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
=> **gophish-0.11.0**

Brief description of the issue: 
=> I have trying  to running gophish in localhost, then started the campaign. Email already sent and successfully captured/ counted "email sent" in dashboard, but for other event : "Email open", "Clicked link" etc. there are not captured. 

What are you expecting to see happen? :
=> It's should be capture too, isn't it ?

What are you seeing happen?
=> There's no captured for event : email open, clicked link etc, Only captured for Email sent

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
<!DOCTYPE html><html lang="en"><head>
	<base href="https://127.0.0.1:3333/"/><meta charset="utf-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><meta name="description" content="Gophish - Open-Source Phishing Toolkit"/><meta name="author" content="Jordan Wright (http://github.com/jordan-wright)"/>
	<link href="/images/favicon.ico" rel="shortcut icon"/>
	<title>Gophish - Login</title>
	<link href="/css/dist/gophish.css" rel="stylesheet"/>
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,600,700" rel="stylesheet" type="text/css"/>
</head>
<body data-gr-ext-installed="" data-new-gr-c-s-check-loaded="14.992.0" data-new-gr-c-s-loaded="14.992.0">
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
<div class="container-fluid">
<div class="navbar-header"><button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse" type="button"><span class="sr-only">Toggle navigation</span></button><img class="navbar-logo" src="/images/logo_inv_small.png"/> <a class="navbar-brand" href="/"> gophish</a></div>

<div class="navbar-collapse collapse">
<ul class="nav navbar-nav navbar-right">
	<li><button class="btn btn-primary" type="button">Login</button></li>
</ul>
</div>
</div>
</div>

<div class="container">
<form action="" class="form-signin" method="POST"><input name="__original_url" type="hidden" value="https://127.0.0.1:3333/"/> <img id="logo" src="/images/logo_purple.png"/>
<h2 class="form-signin-heading">Please sign in</h2>
<input autofocus="" class="form-control top-input" name="username" placeholder="Username" required="" type="text"/> <input autocomplete="off" class="form-control bottom-input" name="password" placeholder="Password" required="" type="password"/> <input name="csrf_token" type="hidden" value="CPcucLkgxgs9uCAv/cqc5Qd5I3jMgj/7zG/3dsRyxp3KQpRVpPfDeF/oTrygsbxtlLiwU2LYXiwXraDK21NDrg=="/><button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button></form>
</div>
<script src="/js/dist/vendor.min.js"></script>

</body></html>
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
What happens when you a click a link? Does the campaign page load up? You should see the events in your gophish logs; once for email opened, one for link clicked.

Some email clients will block loading of remote images, so you wouldn't see the email opened notification. Also, I assume you're using a local email client/server if you're running off localhost.

**Comment by khafitbimo** [comment]
> What happens when you a click a link? Does the campaign page load up? You should see the events in your gophish logs; once for email opened, one for link clicked.
> 
> Some email clients will block loading of remote images, so you wouldn't see the email opened notification. Also, I assume you're using a local email client/server if you're running off localhost.

When I clicked the link, the campaign page doesn't load. Below this is my email template :

`<html>`
`<head>`
`	<title></title>`
`</head>`
`<body data-gr-ext-installed="" data-new-gr-c-s-check-loaded="14.992.0" data-new-gr-c-s-loaded="14.992.0">`
`<p>{{.FirstName}},</p>`

`<p>The password for {{.Email}} has expired. Please reset your password <a href="{{.URL}}">here</a>.</p>`

`<p>Thanks,<br />`
`Morning Catch IT Team</p>`
`{{.Tracker}}</body>`
`</html>`

Email has been sent successfully, but when I open the email, it doesn't count as "Email opened" in dashboard.
I have try with email company with .id and with gmail, both are same not captured as "Email opened". Gophish is running on localhost.

**Comment by glennzw** [comment]
What page do you get when clicking the link? Could you share a screenshot of what you see, and also the contents of your `config.json`

**Comment by glennzw** [comment]
Closing out as haven't heard back.
