### ISSUE TITLE
Solution suggestion SMTP server open Source or other solution

### ISSUE THREAD

**Issue by lcristovam** [gophish/gophish#2116]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

**What version of Gophish are you using?:** 
0.11.0

**Brief description of the issue:** 

Solution suggestion SMTP server open Source or other solution.

**What are you expecting to see happen? :**

Hi Guys. My name is Lucas and i'm starting on Information Security's World.

_In Gophish, i hope i can send emails with the changed header of the stmp account used to send emails.

I am putting together a phishing awareness tool using Gophish. For the quality of my system to be maximum to the point of testing company employees, I need to send emails with the modified header / address.
 
For example: The SMTP account is:  lucas@domainlucas.com and can send emails how support@nameofastore.com ( obviously the second address must be nonexistent, but I can choose any one)_

What are you seeing happen?

I was able to run campaigns that way, with a SaaS SMTP server called SMTP2G0. In it, I configured an SMTP username and password and registered it in a Gophish Send profile. However, with good reason, they blocked me because they suspected spam. I tried to search for other SMTP servers (I don't have a lot of technical knowledge about) but I couldn't find any that would give me that username and password. Even so, I believe that they will block me for identifying "spam". I would like to know if you could recommend any open source SMTP server that allows me to send these emails through gophish without this domain validation as they call it.

**Comment by glennzw** [comment]
Hi Lucas, and welcome to information security! This isn't really an area that we can support you in as it doesn't relate directly to gophish, but it's often best to use the SMTP server of the organisation you're running the campaign against. Alternatively, you can setup your own SMTP server (e.g Postfix).

Good luck!

**Comment by lcristovam** [comment]
Hi Glennzw!


sorry for deviating somewhat from the focus of the forum. Your answer has already prepared me a lot for my next steps.

Thank you!
