### ISSUE TITLE
How to decrypt the randomly password generate in the terminal 

### ISSUE THREAD

**Issue by SteveWicky** [gophish/gophish#2119]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  V0.11

Brief description of the issue: How can i get the clear text password for me to login?

What are you expecting to see happen? : 

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
"Please login with the username admin and the password ef08a1462cc531b0"

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
The password in the terminal isn't encrypted, it's plain test. Copy it, and paste it into the web login with the username 'admin'.

**Comment by SteveWicky** [comment]
Got it! Many thanks glennzw.
