### ISSUE TITLE
How Do I get a URL reachable to my gophish listeners 

### ISSUE THREAD

**Issue by UCSG123** [gophish/gophish#2120]
Hello I would like to get a URL public. I use my own URL of my gophish server. I read before issues like mine but I didn't understand where I can get this URL public. My actual url is http://127.0.0.1 but when I try to open that link on another device it doesn't open. It appears error 404.

**Comment by edermi** [comment]
You need a public routable IP address (usually already assigned to your VPS) and (optional, but recommended) a domain pointing there.

**Comment by UCSG123** [comment]
Thanks and do you have a blog or steps how can I put the domain pointing there. I already have the domain but I don't know how to configure it.

**Comment by edermi** [comment]
There are many resources on the internet. I'd recommend you to get a basic understanding of Layer 3/4 networking and DNS before connecting anything to the internet. This unfortunately goes far beyond the scope of this bug tracker.

**Comment by UCSG123** [comment]
I have my ip gophish but I don't know how to put it in a domain that I already have, do you have any tutorial?

**Comment by asaqib27** [comment]
It may help you..
https://www.hostinger.in/tutorials/dns/how-to-point-domain-to-vps

**Comment by UCSG123** [comment]
![Captura de pantalla (206)](https://user-images.githubusercontent.com/79067200/108211449-b3773100-70fa-11eb-9730-5d6be1049057.png)

**Comment by UCSG123** [comment]
Did I put the data correctly?

**Comment by glennzw** [comment]
Your A record needs to point to a public IP address, not your local IP (127.0.0.1 is your local computer, it can't be reached via the internet)

**Comment by ozanharun** [comment]
i have same issue, ip dan domain name already solved by internet access in cms actually, 
<img width="304" alt="image" src="https://user-images.githubusercontent.com/71914545/113814321-a80bc200-979b-11eb-8325-58047693358f.png">
but the link cannot redirect my landing page from internet.
i am currently using UAG to publish ip and domain name. I suspect this is because the gophish landing page url has random riders when sent to the user via email. Do you have any suggestions so that I can successfully access this landing page from outside using the UAG Unified Access Gateway.

**Comment by glennzw** [comment]
@ozanharun I don't have any experience with UAG, but the end result that you want is to be able to enter an IP + port from the target machine and through whatever TCP/IP plumbing have that socket end up on the phishing_server host + port in your `config.json`.

**Comment by adenix92** [comment]
Please 127.0.0.1:3333 and I even still yet change the port from config.json still yet not reachable on my browser; 
![image](https://github.com/user-attachments/assets/ec684b75-a711-44d9-a6eb-03fe6f6a4088)
![image](https://github.com/user-attachments/assets/9206b900-ca8e-4f7d-a9eb-f245e50685e9)
my dns configuration is been configure very well and am using namecheaper vps.
