### ISSUE TITLE
mysql can't start 

### ISSUE THREAD

**Issue by nickje10** [gophish/gophish#2121]
Hi,

My msql server won't start because of this rule in the documentation:

Gophish uses a datetime format that is incompatible with MySQL >= 5.7. To fix this, Add the following lines to the bottom of /etc/mysql/mysql.cnf:
[mysqld]
sql_mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

I ofcourse did that. But the problem is now that the mysql server won't start anymore. The first time there wasn't a problem. Everything was running and gophish dashboard runs also. But now (a day later) he don't want to start anymore.

Anyone know this problem? What can i do? :/

Screens:

![Screenshot_3](https://user-images.githubusercontent.com/30010182/108064868-8a549300-705d-11eb-9207-8c105b639166.png)
![Screenshot_2](https://user-images.githubusercontent.com/30010182/108064872-8aed2980-705d-11eb-99ea-a8ffdae71958.png)
![Screenshot_1](https://user-images.githubusercontent.com/30010182/108064873-8aed2980-705d-11eb-9805-3ab5cbb235af.png)

Version: v0.11.0
What i tried: Reboot server, restart mysql..

**Comment by jordan-wright** [comment]
Hi there!

I believe MySQL keeps logs somewhere- is there any useful information you can share from them to help track this down?

**Comment by nickje10** [comment]
That is all i have (i think).. :/

**Comment by cesar-rickinho** [comment]
The `/etc/mysql/mysql.cnf` file already has a section `[mysqld]`, so you can't add another one at the end, so need to search for that section and add the `sql_mode` line to the bottom (or top) of that section.

If you include two `[mysqld]` sections on the same configuration file it will fail to load.

Try to use this command to see the config file without the comments and identify the last line of the `[mysqld]` section, then add that line right below the last one.

`# grep -E -v '^#|^$' /etc/mysql/mysql.cnf`

Example from my MariaDB file:

[server]
[mysqld]
user                    = mysql
pid-file                = /run/mysqld/mysqld.pid
socket                  = /run/mysqld/mysqld.sock
basedir                 = /usr
datadir                 = /var/lib/mysql
tmpdir                  = /tmp
lc-messages-dir         = /usr/share/mysql
bind-address            = 127.0.0.1
query_cache_size        = 16M
log_error = /var/log/mysql/error.log
expire_logs_days        = 10
character-set-server  = utf8mb4
collation-server      = utf8mb4_general_ci
**sql_mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION**
[embedded]
[mariadb]
[mariadb-10.3]

**Comment by rschaal** [comment]
Had the same issue and it ended up being that MySQL 8 doesn't support NO_AUTO_CREATE_USER anymore. Once removed it looks like everything works.

From the release notes:

The following features related to account management have been removed:
Using GRANT to create users. Instead, use CREATE USER. Following this practice makes the NO_AUTO_CREATE_USER SQL mode immaterial for GRANT statements, so it too is removed.

**Comment by glennzw** [comment]
Great detective work. Closing this one out.
