### ISSUE TITLE
Phishing landing page on other server

### ISSUE THREAD

**Issue by RunFox** [gophish/gophish#2122]
What version of Gophish are you using?: 0.11.0

Hello!) I want to realise such scheme: 
One server with GoPhish, where I start company, collect statistic, etc.
Second server - phishing server, where I hosts phishing landing page. IP-address of this server I want to config in config.json. It will collect user's data. Then it must send data to GoPhish server. Some questions:
1)Is it possible? Will GoPhish send requests to remote server, where is not GopHish instance?
2)Even somebody realise such scheme)? There are some plugin/additional instruments for this maybe? If yes, please, give links
3)There are full list of POST and GET requests, which send to/from GoPhish Server? I see that reuqest for mark mail as opened is /track, for example.

As I understand it: I should config remote server in config.json, all requests will send to this server, I will process it and send requests to my GoPhish server.

**Comment by glennzw** [comment]
The gophish server runs two webservers, one for the admin login and one for the landing pages. These run within the same executable, and therefore on the same server. So the short answer is 'No'.

You could run your MySQL server on a different server.

If your goal is to have different IPs for admin and phishing, you can use proxies like nginx or Caddy to reroute traffic around.

Hope that helps!

**Comment by RunFox** [comment]
Hello, glennzw. I also decided use way with nginx and realized it=) It is looks like working scheme. Thank you for your answer anyway.
