### ISSUE TITLE
Phishing domain setup with cloudflare's ssl

### ISSUE THREAD

**Issue by white-gh0st** [gophish/gophish#2123]
What version of Gophish are you using?: v0.11.0

Brief description of the issue: I have a phishing domain created with cloudflare and using the free SSL option provided

What are you expecting to see happen? : I want to see phishing server hosting the phish_url which is also using the cloudflare ssl & after submitting the creds it needs to redirect to educational content which is running on port 80 in the server. 

What are you seeing happen? Landing page is not working. Since we are using clouflare's ssl running phish_server on port 443 -(true)- without certs not working. 

In the Dry run test:
I got the email
It has the link to static microsoft login page, link is hardcoded as "Import Email" option is not working. (phish_url : https://typo.squat.domain/login)
 when i click the link cloudflare is throwing error for server not reachable
Even i directly tried to access the url it is not working & by default cloudflare routes http to https

**Comment by glennzw** [comment]
This is hard to support, as it's a Cloudflare issue not a gophish issue. 

Can you share your email template HTML and also your `config.json`. My initial guess is that it sounds like you're hardcoding the phishing URL, when you should be using the `{{.URL}}` parameter.

**Comment by glennzw** [comment]
Haven't heard back so closing this out; feel free to reopen if you still need help.
