### ISSUE TITLE
GoPhish outlook tracker image

### ISSUE THREAD

**Issue by nathanduffy1995-dev** [gophish/gophish#2124]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.7.1

Brief description of the issue: Outlook blocking automatic download of image. When inserting tracker image into template and sending it to an outlook account, outlook by default wont download the image and we have no way of knowing if the user actually opened the email. 

What are you expecting to see happen? : When a user opens the email the tracker should update the stats on the gophish server.

What are you seeing happen? When we send a phishing template with the {{.Tracker}}, the 1pixel image is not being downloaded by the email client belonging to our client. This way they can read the email without the pictures downloading automatically and we have no way of knowing that they have read the email.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
	<title></title>
</head>
<body>
<p style="font-family:Segoe UI">Windows User Alert</p>

<p style="color:#2671ec; font-family:Segoe UI; font-size:36px">OneDrive Storage Subscription</p>

<p style="color:#000000; font-family:Segoe UI">The Mircosoft OneDrive storage space for the account {{.Email}} is close to reaching its maximim size quota.</p>

<p style="font-family:Segoe UI">Your organization has additonal avalable memory for your account. Please click be low to upgrade your subcription.</p>

<p style="font-family:Segoe UI"><a href="{{.URL}}" style="background-color:#0078d4;border-color:#0078d4;border-radius:2px;border-style:solid;color:#ffffff;display:inline-block;font-size:16px;text-decoration:none;text-align:center;line-height:40px;width:168px">Go To OneDrive</a></p>

<p style="font-family:Segoe UI">To opt out or change where you receive subscription notifications, click <a href="{{.URL}}">here</a>.</p>

<p style="font-family: &quot;Segoe UI&quot;;">&nbsp;</p>

<p style="font-family: &quot;Segoe UI&quot;;">Thanks,</p>

<p style="font-family: &quot;Segoe UI&quot;;">The IT Support team</p>

<p><img height="142" src="OneDrive-Logo.jpeg" width="300" /></p>


{{.Tracker}}</body>
</html>

```

Please provide any terminal output that may be relevant below:

The .URL in question is being pointed to our GoPhish server address for example: http://127.0.0.1:80

**Comment by glennzw** [comment]
Unfortunately there's nothing we can really do from the gophish side; you'd need to ask your client to enable loading of remote images.

Doing some Googling I can't find a way to whitelist images for certain emails, but perhaps someone else knows? You can add custom headers to identify gophish emails, or whitelist by domain (if possible).

**Comment by rfdevere** [comment]
You can add the sending email addresses to the safe senders list and go a step further with a registry edit, basically the opposite of this: https://www.stigviewer.com/stig/microsoft_outlook_2013/2015-06-19/finding/V-17739

Just be careful enabling remote content for an org just for phishing simulations.

**Comment by glennzw** [comment]
Great advice there from @rfdevere 

Closing this one out.
