### ISSUE TITLE
Case Insensitive Import collision.

### ISSUE THREAD

**Issue by 25zerotwo** [gophish/gophish#2128]
What version of Gophish are you using?: Version go1.15.8

Brief description of the issue: 
go/src/github.com/mailhog/MailHog/config/config.go:6:2: **case-insensitive import collision:** "github.com/mailhog/MailHog/vendor/github.com/ian-kent/envconf" and "github.com/mailhog/mailhog/vendor/github.com/ian-kent/envconf

What are you expecting to see happen? :
Get sourcing gophsih

What are you seeing happen?
Failure to source, due to a case insensitive mismatch.
Please provide any terminal output that may be relevant below:

$ go get github.com/mailhog/Mailhog
go/src/github.com/mailhog/MailHog/config/config.go:6:2: case-insensitive import collision: "github.com/mailhog/MailHog/vendor/github.com/ian-kent/envconf" and "github.com/mailhog/mailhog/vendor/github.com/ian-kent/envconf

Please provide as many steps as you can to reproduce the problem:
 * simply try to 'get' via go.

**Comment by glennzw** [comment]
It looks like you're trying to get mailhog rather than gophish. Could you give us the output from:

```
go get github.com/gophish/gophish
cd gophish
go build
```

**Comment by 25zerotwo** [comment]
Christ, I am sorry, was between the two githubs and raised it on entirely the wrong one.. Will close comment once I've just double check I've not gone utterly mad.

**Comment by glennzw** [comment]
No worries!
