### ISSUE TITLE
Link preview on-hover

### ISSUE THREAD

**Issue by lewOc** [gophish/gophish#2129]
We are sending a phishing email with a call to action via a 'sign-up' button.

When you mouse hover over the button it previews the link as 'fakepage.com' however we would like to have the hover preview to display the legitimate URL ie linkedin.com.

Is this possible?

**Comment by rfdevere** [comment]
On a landing page you could bring in JavaScript to handle the click but on an email this won’t be possible. 

Maybe you could snap up a similar typo domain or use a long subdomain (63 chars) to push it out of focus of the recipient.

Outside of that it’s diminishing returns for phishing simulations.

**Comment by glennzw** [comment]
@rfdevere is spot on here. Javascript on the landing page side, but that won't be possible on the email side.
