### ISSUE TITLE
Shut down issues?

### ISSUE THREAD

**Issue by johnnycannuk** [gophish/gophish#213]
I created a test campaign on my mac mini. OS X El Cap. Worked great (once I build from Source)

The only issue is I need to CTL-C to quit gophish and it shuts down but there is an errant process that locks port 80.

gophish can't restart because the port is in use and using sudo apachectl stop doesn't work because, obviously, because its not the built in apache.

I have to restart any way. Is there a clean way to restart or am I missing something

**Comment by rfdevere** [comment]
$sudo fuser -k 80/tcp

This will 'decommission' the port after the program terminates and avoid the 'port in use' error when it starts up.

As for a long term fix it does need a poke at.

Richard

**Comment by johnnycannuk** [comment]
Richard,

Thanks I'll note this.

**Comment by jordan-wright** [comment]
I guess I've been spoiled that Windows procs cleanly exit.

I bet I can fix this - let me see what I can do.

Thanks for the report!
