### ISSUE TITLE
Bug when copying Sending Profiles and adding an Email Header

### ISSUE THREAD

**Issue by r3medy** [gophish/gophish#2132]
What version of Gophish are you using?: 
v0.9.0-linux-64bit

Brief description of the issue: 
When copying a sending profile and changing the details, adding a new Email Header prevents the copy from taking place.

What are you expecting to see happen? :
Copying a sending profile and changing details, upon saving the changes should be saved. Not sure how to word this better.

What are you seeing happen?
When copying a sending profile and changing some details (regardless of what the details are, excluding email headers) upon hitting Save, the new profile is created.

However, when doing the same thing but adding an Email Header (as those aren't copied), upon hitting save the GoPhish URL changes to include headerKey=$KEY&headerValue=$VALUE.

It looks like the usual `POST /api/smtp/ HTTP/2.0\` request gets skipped if you try to add an Email Header when copying, and the `GET /api/smtp/?{} HTTP/2.0 ` is still processed, which is why we see the change in the URL.

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Copy any existing sending profile and add a new Email Header before hitting save.
 * Step 2 - Observe the mentioned behaviour both in terminal output and instance behaviour.
 
 
I'd like to note this is by no means gamebreaking, but seems to have been an issue since v0.8.0 and I thought it worth mentioning.

**Comment by glennzw** [comment]
Hi @r3medy, thanks for reaching out. I'm trying to reproduce by following your steps:

 * Step 1 - Copy any existing sending profile and add a new Email Header before hitting save.
 * Step 2 - Observe the mentioned behaviour both in terminal output and instance behaviour.

But the result is that the new copied sending profile saves fine:


https://user-images.githubusercontent.com/3966613/110212751-df353d80-7e94-11eb-9039-139627a433ae.mov

Does your output look different to this?

I did notice in the terminal the unhelpful message:

```
time="2021-03-06T15:59:53Z" level=error msg="record not found"
```

I'll try and track down the source of that error, but first up could you let me know if your result is different to my video above?

Also, might be worthing trying the latest version, 0.11.0.

**Comment by glennzw** [comment]
Closing out as haven't heard back.
