### ISSUE TITLE
How to create valid ip/domain that is accessible to recipient 

### ISSUE THREAD

**Issue by zzbaird** [gophish/gophish#2133]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
11
Brief description of the issue: 
I have no idea how to create a URL for hosting the phishing server. And anything involving the phishing server ip and domains
What are you expecting to see happen? :
I want to know how to create a URL that I can input in the campaign that will allow anyone on the receiving end to access the site 
What are you seeing happen?
The only URL that will work is when I put 192.168.56.1. I want to know how to create a different domain/ip that will allow anyone to access.
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - learn what to use to create a valid ip/domain 
 * Step 2 - what to input in the config for the phish server

**Comment by edermi** [comment]
You need a public routable IP address and a domain name that points to it. The first is usually part of your VPC while the latter can be bought. Gophish doesn't cover your infrastructure setup.
If this sounds all new to you, I'd recommend you to either get a provider that performs your awareness phishing test for you or you get a basic understanding of L3/L4 networking as well as DNS and how to secure your server and your user's data first. Unfortunately, this is something we cannot provide here.

**Comment by glennzw** [comment]
@edermi is spot on. You need to purchase a domain, and point it with DNS records to your public gophish server. Good luck!
