### ISSUE TITLE
Custom Headers usage

### ISSUE THREAD

**Issue by ermalg** [gophish/gophish#2135]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: gophish-v0.11.0-windows-64bit

Brief description of the issue: Is there any reference guide to learn how to properly use the custom headers?

What are you expecting to see happen? : To completely replace the From Header, with something that does not exist.

What are you seeing happen? The form header doesn't change.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
You can add custom headers in the Sending Profiles:

![Screenshot 2021-03-06 at 15 36 35](https://user-images.githubusercontent.com/3966613/110212122-ce36fd00-7e91-11eb-9a84-f1cb70b0b3f0.png)

I'm not sure what would happen if you replaced the from header, have you tried and found something unexpected happening?

**Comment by ermalg** [comment]
Hello, 
Thanks for your reply.

The first thing that I want to know, is how properly use the custom headers, how to write them.

This is why i firstly need a user manual of this custom headers.

What i have now, i.e, is like below:
Header: From
Value: {{.From}}-test@test.com.

But still in the test email, I receive the message from the real address, and not from the custom one.

Thanks

**Comment by glennzw** [comment]
Your header value would be invalid. If your gophish from field is, say, `bobby@internet.com` and your try set a header value of `{{.From}}-test@test.com` you'd get `bobby@internet.com-test@test.com`

<img width="705" alt="Screenshot 2021-03-10 at 13 02 51" src="https://user-images.githubusercontent.com/3966613/110633686-f891fe80-81a0-11eb-872a-e99ba4a65b92.png">

But more to the point I'm not sure why you don't just set the From field in the sending profile form?

<img width="701" alt="Screenshot 2021-03-10 at 13 04 18" src="https://user-images.githubusercontent.com/3966613/110633875-398a1300-81a1-11eb-9cd0-3ef8884540fe.png">

**Comment by glennzw** [comment]
One use case I can think of, is that if you want an email to appear as though it comes from the person it's being sent to. You could set a header value of `From` with value `{{.Email}}`:

<img width="701" alt="Screenshot 2021-03-10 at 13 09 51" src="https://user-images.githubusercontent.com/3966613/110634652-1f9d0000-81a2-11eb-8745-2660e0fa5c27.png">

Then the resultant email appears to come from myself:

![Screenshot 2021-03-10 at 13 10 05](https://user-images.githubusercontent.com/3966613/110634749-3ba0a180-81a2-11eb-8bb2-ce01da0355f6.png)

**Comment by ermalg** [comment]
Hello, 
Thanks again for your reply.

I have tried the last one to replace From header with {{.Email}} value, but i get an error message "Authentication rejected"

All that i want to do, is to be able to create a fake sender, so a fake From address, which does not exist at all but use my real credentials to log on into email server.

All i could do by now is to write on the From Field: Fake_Name<real_email_address@gmail.com>, which works.

**Comment by glennzw** [comment]
I think that if you're getting authentication rejected there's an issue on your mail-server side. One way to rule the mail-server out is to test with something like Mailhog. It's a dummy mail server that you can run on your local machine and point gophish to it. 

If you could give that a go, and let me know if you get the same error.

**Comment by ermalg** [comment]
Hello Glennzw,

Thanks for your help and recommendations! Next time I'll try to use dummy mail server.

For the moment I resolved the problem, with creating fake email addresses on my real mail server.

Best regards
