### ISSUE TITLE
Add ability to track score on NIST phish scale

### ISSUE THREAD

**Issue by PeterWhelan** [gophish/gophish#2139]
What version of Gophish are you using?: latest

Feature request:
Add ability to score each email and landing page on the NIST phish scale.
NIST has created a phish scale for scoring the number of cues and the context of a test message.
A phish that is well crafted and topical is more likely to succeed than a Nigerian prince trying to send me money if I just download his bank details.  Clicking on well crafted, tricky phish should not count against the user as much  as clicking on an obvious phish.
https://www.nist.gov/news-events/news/2020/09/phish-scale-nist-developed-method-helps-it-staff-see-why-users-click

**Comment by glennzw** [comment]
Hi @PeterWhelan, thanks for reaching out. The NIST phish scale looks very interesting.

How do you envisage this being incorporated into gophish?

**Comment by PeterWhelan** [comment]
Thank you for your prompt response Glenn,
I envision the NIST phish scale helping us track who was tricked by easily avoided attacks versus those who got tricked only by the hardest to spot ones.
We would adjust our training accordingly.

More cues means it is easier to detect, therefore higher score
Irrelevant context means it is easier to detect, therefore higher score

On the email template and landing pages, after the name field, add a numeric field for cues and a numeric field for context

The score for each landing page and email would be the sum of…
- The number of cues (typos, threats, urgency, odd formatting, etc)
- And the context, how relevant the message is to the recipient  (0  from your manager, 9 from a Nigerian prince wanting to send me millions)

For example, a hard one to detect...
Email identical to what you receive from microsoft, except it is from rnicrosoft Cue:1
You regularly get email from Microsoft Context:0
PHISH scale:1

An easy one to detect
Email from a personal address, full of typos claiming to be from HSBC Cue:9
You don’t have an account with HSBC Context:9
PHISH scale:18

Also, currently we pull the results of each campaign into a spreadsheet where we tally how many times each person has been phished.
It would be nice if that count was in GoPhish.

On the campaigns page, optionally allow inclusion of columns the phish scale total, sent, clicked, submitted, reported would be nice too.

**Comment by glennzw** [comment]
Hi Peter, great idea. I'm hoping to add some form of campaign library support in the future that would group phishing templates by social media, IT, internal, etc. This could be another field to include there. I don't have capacity to focus on this now but I'll keep it in mind when I get there!

In the meantime you might have some joy using our API to manually do some tagging, perhaps in a spreadsheet.

I've added the enhancement tag, and will close this out.
