### ISSUE TITLE
Ajax update issues

### ISSUE THREAD

**Issue by nmalcolm** [gophish/gophish#214]
It seems the ajax update feature on the campaign page is causing some major usability problems. I assume this is because the whole page is "refreshed" instead of individual nodes being updated.

Two examples I've come across:

1. If you're browsing through the pagination and the page is updated, you'll end up back at the first page.

2. "View Details" will auto-close after ~5 seconds if opened. You can imagine how frustrating it is clicking, trying to copy something from the details, and it suddenly closing, and having to repeat until you time it just right.

**Comment by jordan-wright** [comment]
Hey @nmalcolm - *completely* understood. I recall seeing something similar, and I think you summed it up nicely.

That needs to be fixed for sure.

In the meantime, if you want to avoid the ajax polling, you can comment out [this line](https://github.com/gophish/gophish/blob/master/static/js/app/campaign_results.js#L568) to avoid the updates.

I'll keep this issue open for reference until it's fixed. Thanks for the report!

**Comment by jordan-wright** [comment]
Ok, I think I addressed this in 16b225b1895b180ac98135b7c1aa0aedb64e6423.

Would you mind giving it a shot and letting me know if it helps fix the issue?

**Comment by jordan-wright** [comment]
Gonna go ahead and close this out for now. Give it a shot when you can and let me know if there are any issues!

**Comment by kontez** [comment]
I haven't had the chance to test the first issue but I still can reproduce. Built from source few moments ago!

**Comment by jordan-wright** [comment]
Interesting, thanks for the heads up!

To make sure you have the latest version, do you have any entries in ```static/js/app/campaign_results.js``` for ```escapeHtml(```?

And just to check, what behavior are you seeing specifically? If you have a row open, it closes when the ajax poll happens?

**Comment by kontez** [comment]
Yes I have! I grepped for ﻿﻿`escapeHtml(` and even compared the whole file just to be sure.
The behaviour is that when I click on "View Details" after some moments the box closes and I have to re-click "View Details" again.

**Comment by jordan-wright** [comment]
Oh... Yes, that is unfortunately still there. This specifically fixed the issue where the page is kept in place (if you're on page 5, you stay there), and the row itself, if expanded, will stay expanded.

The expanded details are a bit trickier and haven't yet been fixed.
