### ISSUE TITLE
using docker for both gophish and mailhog not working?

### ISSUE THREAD

**Issue by SijieZhuo** [gophish/gophish#2141]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
current version
Brief description of the issue: 
Hi, I am having issue with sending test emails when both gophish and mailhog was running via docker. when I tested gophish directly (without using docker) with mailhog (using docker), it works fine. but if I run both of them on docker, error message was displayed
What are you expecting to see happen? :
i will expect to see test email successfully send
What are you seeing happen?
error message : Max connection attempts exceeded - dial tcp 127.0.0.1:1025: connect: connection refused

Please provide any terminal output that may be relevant below:

```
time="2021-03-10T03:53:41Z" level=warning msg="Max connection attempts exceeded - dial tcp 127.0.0.1:1025: connect: connection refused"

time="2021-03-10T03:53:41Z" level=error msg="Max connection attempts exceeded - dial tcp 127.0.0.1:1025: connect: connection refused"

time="2021-03-10T03:53:41Z" level=info msg="172.17.0.1 - - [10/Mar/2021:03:53:41 +0000] \"POST /api/util/send_test_email HTTP/2.0\" 500 142 \"https://localhost:3333/sending_profiles\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18363\""
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - login
 * Step 2 - creating new sending profile with host: 127.0.0.1:1025

**Comment by glennzw** [comment]
That error of `dial tcp 127.0.0.1:1025: connect: connection refused` indicates the gophish container can't connect to the mailhog container. Perhaps you need to expose the mailhog port:

https://www.whitesourcesoftware.com/free-developer-tools/blog/docker-expose-port/

**Comment by SijieZhuo** [comment]
> I assume 127.0.0.1 is in the container's network namespace and you need to address the mailhog container using its IP address in docker's local network. `docker inspect <container_id_mailhog>` should give you the relevant information [1].
> 
> [1] https://stackoverflow.com/questions/43692961/how-to-get-ip-address-of-running-docker-container

If it is the problem of the mailhog, why it works fine with gophish that does not use docker container?

**Comment by SijieZhuo** [comment]
Update, I just got it working using 172.17.0.1:1025, Thank you for the quick response and helping me solve the problem.

**Comment by edermi** [comment]
> > I assume 127.0.0.1 is in the container's network namespace and you need to address the mailhog container using its IP address in docker's local network. `docker inspect <container_id_mailhog>` should give you the relevant information [1].
> 
> > 
> 
> > [1] https://stackoverflow.com/questions/43692961/how-to-get-ip-address-of-running-docker-container
> 
> 
> 
> If it is the problem of the mailhog, why it works fine with gophish that does not use docker container?

I assume because you exposed the mailhog port to your local system, so gophish is able to connect to it via 127.0.0.1. Once gophish runs in a container, it has its "own" 127.0.0.1.

If you're interested in how this works, take a look at network namespaces.

**Comment by SijieZhuo** [comment]
Cool, thanks for helping out.
