### ISSUE TITLE
Simulated Ethical Phishing campaign into Gmail G-Suite environment and SMTP providers questions

### ISSUE THREAD

**Issue by tscdridpath** [gophish/gophish#2143]
_What version of Gophish are you using?:_ 
0.11.0

_Brief description of the issue:_
Running a phishing campaign using GoPhish and looking for an SMTP hosting provider or someone with expertise to deliver emails to Gmail G-Suite.
Tried to use SMTP hosting providers previously and a requirement is using a Dedicated IP for the emails to be able to be whitelisted, this has been fine. However due to SMTP providers terms, phishing is in violation so we have had no luck finding a provider that is willing to provide this service to run simulated ethical phishing campaigns. These campaigns are run with communication to users that this is happening and in order to raise security awareness. No personal details entered on the landing pages are used or stored.
Setting up our own SMTP server has been thought about but the challenge or getting our own static IP and a reverse DNS record from a provider, then setting all the DKIM records etc... and finally forwarding the email messages from GoPhish on to the end destination looks very daunting. This is all in order to deliver the plausable ethical phishing into a Gmail G-Suite email environment.
Does anyone know anyone who has experience in this or can help? Even partner organisations that can provide any services in this area please?

_What are you expecting to see happen? :_
Simulated Ethical Phishing emails arriving in users Gmail G-Suite inbox and not spam.

_What are you seeing happen?_
Emails are arriving in users Gmail G-Suite spam folder. Unable to get a Dedicated IP email sender due to using it for ethical phishing.

_If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:_
N/A

**Comment by glennzw** [comment]
I've been through the same process; I've tried various SMTP providers but none of them allow phishing campaigns, and will terminate your account. Also it's fairly costly to get a fixed IP. Two options I can suggest:

 * Setup a postfix send only SMTP server on your own server (it's a little easier if it's send-only, see [this tutorial](https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-postfix-as-a-send-only-smtp-server-on-ubuntu-16-04))
 * Use your client's SMTP server (this also helps to ensure delivery)

I'll leave this open for a while to see if anyone else has some advice to add.

**Comment by TheBoss-9001** [comment]
I read an article [here](https://airwalkconsulting.com/techblog-phishing-with-gophish-on-aws/) where the author describes using Amazon's Simple Email Service to conduct their phishing. I don't know what their terms of service are though; hope it helps some.

https://airwalkconsulting.com/techblog-phishing-with-gophish-on-aws/

**Comment by tscdridpath** [comment]
Thanks for the feedback guys.
