### ISSUE TITLE
Issue sending emails from GoPhish for Spam or Virus Content

### ISSUE THREAD

**Issue by kkane2021** [gophish/gophish#2144]
I am receiving the following error when sending messages through GoDaddy.  I have narrowed the issue down to the contents that it is referring to being the tracker and the URL for the link.  Obviously, these are necessary items to send the phishing test.  When I remove both, the email sends successfully.  The second I add them back in, blocked!

ERROR MESSAGE:

Error 552 KMhwlSw2U83tO :: auth :: Message rejected for spam or virus content :: Please include this entire message when contacting support :: v=2.4 cv=ONniYQWB c=1 sm=1 tr=0 ts=604a2f2d p=zMki-jJqAAAA:8 a=RSen8zwGzMbhLNJUD2M5ew==:117 a=RSen8zwGzMbhLNJUD2M5ew==:17 a=IkcTkHD0fZMA:10 a=x7bEGLp0ZPQA:10 a=Cm-25PRvcicA:10 a=iro-ngXkuAeCFPCCK9wA:9 a=Re0INp8V8bS1jrmx:21 a=frz4AuCg-hUA:10 a=_W_S_7VecoQA:10 a=QEXdDO2ut3YA:10 a=qiWi7Edwir4A:10 a=8OY1mSCQZ4IA:10 a=NWVoK91CQyQA:10 a=CYYSbbFhz7qgkPy5e9Rl:22 a=MwpuUe3qDhG9mKJzj44U:22 a=BPzZvq435JnGatEyYwdK:22 a=jswh0VOYqTA5zEqyiMXg:22 a=p-dnK0njbqwfn1k4-x12:22 a=jjky5lfK57Ii_Ajn6BuG:22 :: 100.00

**Comment by glennzw** [comment]
Hi there. This is unfortunately outside the scope of the help we can offer as it's to do with Godaddy and your content. I suspect the IP and/or domain you're hosting gophish on has been marked as spam if this error only comes up once you include the tracker link and phishing URL. You can test this by sticking in a random other URL (www.google.com or something), and if that works I guess you need to get a new IP/domain for your gophish.
