### ISSUE TITLE
Add Tracking Image is failed

### ISSUE THREAD

**Issue by jooeji** [gophish/gophish#2145]
![image](https://user-images.githubusercontent.com/12831513/111095378-43808d00-8578-11eb-9d10-353314554760.png)

Save the settings, then open the checkbox to automatically cancel

**Comment by glennzw** [comment]
Hi there. Could you try elaborate on the problem you're facing?

If you toggle source you'll see the tracking img tag being added, if that helps.

**Comment by jooeji** [comment]
already been solved
