### ISSUE TITLE
[Request] Custom Phishing URI

### ISSUE THREAD

**Issue by websecnl** [gophish/gophish#2146]
So I was thinking, and it would be nice if we would make a custom phishing URI with a custom insertion point for the RID

example    https://{{.BaseURL}}/CookieAuth.dll?GetLogon?curl={{.RId}}&reason=0&formdir=6

This would be very convinient for Office phishing campagnes and other similar things.

If anyone can fork GoPhish and add this functionality I think this will be a great thing to merge into the final branche of GoPhish.

If this is already possible to use {{.RId}} instead of ?rid= in a custom URL than please explain me how.

**Comment by glennzw** [comment]
You have to have the rid parameter in the URL, but you can have as many other variables and paths as you want. e.g you can supply a URL like this when crafting your campaign:

`http://gophish.local/CookieAuth.dll?GetLogon&reason=0&formdir=6`

![Screenshot 2021-03-22 at 12 09 50](https://user-images.githubusercontent.com/3966613/111988006-d20c8580-8b07-11eb-9185-990a04db4b95.png)


which results in this link in the emails:

```
http://gophish.local/CookieAuth.dll?GetLogon=&formdir=6&reason=0&rid=FFdRy0u
```

![Screenshot 2021-03-22 at 12 12 50](https://user-images.githubusercontent.com/3966613/111988147-05e7ab00-8b08-11eb-96a4-a24554b8e3e8.png)
