### ISSUE TITLE
Can I use MySQL or SQLServer rather than SQLite?

### ISSUE THREAD

**Issue by hossam-brgoth** [gophish/gophish#2147]

**Comment by asaqib27** [comment]
This installation guide have a section that explained how you can configure MySQL.

https://docs.getgophish.com/user-guide/installation#:~:text=Using%20MySQL,couple%20extra%20steps%20are%20needed.

**Comment by asaqib27** [comment]
Hope it would help you..

https://docs.getgophish.com/user-guide/installation#:~:text=Using%20MySQL,couple%20extra%20steps%20are%20needed

**Comment by hossam-brgoth** [comment]
Thank you. And MS SQL SERVER?

**Comment by glennzw** [comment]
No, only sqlite and MySQL. Good luck!
