### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Blackghost01** [gophish/gophish#2149]
**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: The last version v0.11.0 from the oficial webside.

Brief description of the issue:  In the process of logging in with the windows app system i get everything correct except where is my password should come out.

What are you expecting to see happen? : Explain to me why the password does not come out and how to correct it.

What are you seeing happen?

Time="2021-03-25T17:23:36+01:00" level=info msg="Please login with the username admin and the password C:\\Users\\USER\\Desktop\\GoFish\\gophish_admin.key"

The app system says that, instead of providing the password between "........."

Please provide as many steps as you can to reproduce the problem:

 * Step 1 - I copy the address of the GoPhish folder to put in the system app.
 * Step 2 - I open the system app with administrator permission and follow  the steps in the video to generate the password.
 * Youtube link: https://www.youtube.com/watch?v=YywVLJi7KtU
   Minute: 4:30

![img2](https://user-images.githubusercontent.com/81332375/112516523-a9022400-8d97-11eb-87eb-05cf90b9079f.png)

**Comment by glennzw** [comment]
The error you're getting is at the bottom:

```solo se permite un uso de cada dirección de socket (protocolo/dirección de red/puerto)```

...which seems to translate to:

```only one use of each socket address (protocol / network address / port) is allowed```

This makes me think you have something already listening on port 3333

**Comment by Blackghost01** [comment]
thanks bro, how could i solve the problem?

**Comment by jordan-wright** [comment]
You'll need to find the process that is listening on that port, stop that process, then restart Gophish.

How to do that depends on your operating system, and there will be tons of resources online on how to find and stop listening processes.

**Comment by user2020-clon** [comment]
hello folks, please i need assistance here.. i cant seem to find  suitable smtp for gophsih. every gmail ive used seems to not work.
Please can someone come to my aid.

**Comment by glennzw** [comment]
> hello folks, please i need assistance here.. i cant seem to find suitable smtp for gophsih. every gmail ive used seems to not work.
> Please can someone come to my aid.

Please open new issues in a new ticket. As for SMTP servers, that's out the scope of support, but I'd recommend running your own SMTP server has most providers don't like handling phishing emails.
