### ISSUE TITLE
Feature - read recipts and DSN

### ISSUE THREAD

**Issue by nanoymaster** [gophish/gophish#215]
would it be possible to include "read recipts" or DSN as another method of checking weather the email has been delivered or read?

**Comment by jordan-wright** [comment]
To my knowledge, these require the ability to receive emails back from the targets, which involves having IMAP support #129. We'll keep this open, but it might be difficult.

In the meantime, we are planning on at least allowing custom headers, so you'll be able to send read receipt requests, just not receive them within gophish.
