### ISSUE TITLE
Client ID

### ISSUE THREAD

**Issue by PizzaPablo666** [gophish/gophish#2152]
What version of Gophish are you using?: 
I am using 0.11.0

Brief description of the issue: 
I am using GSuite (Google workspace), and for allowing third party application I need the Client ID of the web app.

What are you expecting to see happen? :
I need to know where is the Client ID because I couldn't find it in documentation or any other source.

What are you seeing happen?
Can't see client ID. So I can't allow GoPhish to use my GSuite user account (Editing, Sending ... mails).

Please provide as many steps as you can to reproduce the problem:
GSuite --> https://admin.google.com/ac/owl/domainwidedelegation
Needs client ID, for oAuth scopes.

Thanks in advance.

**Comment by glennzw** [comment]
I don't think there's anything on the gophish side to help you; gophish just needs the mail server settings.

https://support.google.com/mail/answer/7126229?hl=en-GB

**Comment by PizzaPablo666** [comment]
Yes it is true, I configured some settings in google side, and it worked. Thank you for response
