### ISSUE TITLE
Having trouble sending email with GoPhish v0.11.0

### ISSUE THREAD

**Issue by TheCyberian27** [gophish/gophish#2153]
I have successfully downloaded and installed GoPhish on my Windows computer and it up and running. I then went on to create a sending profile in which I placed the Host as (**smtp.tse@gmail.com:587**) as I was using my gmail account to test it. However, when I tried to send a test email to another email, I receive this error message:

"**Max connection attempts exceeded - dial tcp: lookup smtp.tse@gmail.com: getaddrinfow: A non-recoverable error occurred during a database lookup.**"

Can somebody help me with this issue? Thank you.

**Comment by glennzw** [comment]
Your host needs to be a hostname (without the user@ part). Here are the settings you need to send email via GMail:

https://support.google.com/mail/answer/7126229?hl=en-GB

**Comment by TheCyberian27** [comment]
> 
> 
> Your host needs to be a hostname (without the user@ part). Here are the settings you need to send email via GMail:
> 
> https://support.google.com/mail/answer/7126229?hl=en-GB

**Comment by TheCyberian27** [comment]
I followed the instructions and found that it IMAP was already enabled. Can you give me an example of what the host should look like?

**Comment by TheCyberian27** [comment]
> Your host needs to be a hostname (without the user@ part). Here are the settings you need to send email via GMail:
> 
> https://support.google.com/mail/answer/7126229?hl=en-GB

I followed the instructions and found that it IMAP was already enabled. Can you give me an example of what the host should look like?

**Comment by glennzw** [comment]
You want to enter SMTP, not IMAP details (IMAP is for receiving, not sending). For example:

![Screenshot 2021-03-29 at 14 02 25](https://user-images.githubusercontent.com/3966613/112840614-70b05d80-9097-11eb-8d41-1b6168151ce1.png)

**Comment by TheCyberian27** [comment]
> 
> 
> You want to enter SMTP, not IMAP details (IMAP is for receiving, not sending). For example:
> 
> ![Screenshot 2021-03-29 at 14 02 25](https://user-images.githubusercontent.com/3966613/112840614-70b05d80-9097-11eb-8d41-1b6168151ce1.png)

![show on github](https://user-images.githubusercontent.com/81562951/112844138-71a3b800-90b4-11eb-9a44-7498425007d7.JPG)
The interface type has already been set as SMTP. And when I followed that link you mentioned, IMAP and POP are both enabled. When I tried to send an email it got this error. Should I disable POP/IMAP?

**Comment by glennzw** [comment]
The link in the error (https://support.google.com/mail/?p=InvalidSecondFactor) tells you that you need to setup an 'app' password (a unique password, different to your regular login password). I suspect if you follow the steps on that page you'll get to a point where you can use gophish to send email.

G'luck!

**Comment by TheCyberian27** [comment]
> 
> 
>When I setup an app password, what do I put under 'select app' and 'select device' sections?

**Comment by TheCyberian27** [comment]
Hello there,
Im managed to resolve the issue I posted before hand, but now I have a new issue. I managed to successfully create a campaign and was able to have the emails sent to the designated groups. However, I do not know how to connect it with my gohpish local host. Do you know how to get the ip address of the localhost???

**Comment by glennzw** [comment]
You need to host your  gophish server on a publicly routable host, you can't run campaigns off of your local machine.

**Comment by TheCyberian27** [comment]
> You need to host your  gophish server on a publicly routable host, you can't run campaigns off of your local machine.

How can I do that?

**Comment by glennzw** [comment]
You'd need to rent a server, e.g from DigitalOcean or Amazon AWS. If you go with Digital Ocean you can get some free credits with my referral: https://m.do.co/c/92d344b69f50

Alternatively you could open up ports on your home router (but I wouldn't advise this).

**Comment by glennzw** [comment]
Closing out as haven't heard back.
