### ISSUE TITLE
BaseURL in admin listen_url for Admin Server not working

### ISSUE THREAD

**Issue by chrisnewmanuk** [gophish/gophish#2154]
What version of Gophish are you using?: Latest

Brief description of the issue: 
![image](https://user-images.githubusercontent.com/7243321/112972878-a7927c00-9148-11eb-9aef-4b807911dc9f.png)
"admin_server": {
                "listen_url": "0.0.0.0:8080/gophish",

Cannot use subresources - these are needed because the service sits behind a nginx proxy_pass'ing multiple services on port 8080

What are you expecting to see happen? :
Service is stood up against the URL with subdirectory specified and nginx can route to it.  Note, nginx is not on the same box as gophish

What are you seeing happen?
![image](https://user-images.githubusercontent.com/7243321/112972928-b37e3e00-9148-11eb-80ba-64cfb94d7e7b.png)

**Comment by glennzw** [comment]
Your `listen_url` needs to be of the form `host:port`, without the trailing path. You'd need to configure your nginx separately to route to the port . There are some threads in here discussing how to do that. I've also had good success with Caddy.

Hope that helps.

**Comment by glennzw** [comment]
Closing out as haven't heard back.
