### ISSUE TITLE
data not recorded

### ISSUE THREAD

**Issue by nanoymaster** [gophish/gophish#216]
not sure if I am doing something wrong, I simply imported owa login page.
however any data submitted to it doesn't seem to be recorded
yes I have checked the boxes to log everything including passwords, also tried without passwords...
but no luck

**Comment by jordan-wright** [comment]
Can you provide the <form> contents in your landing page?

That will help us determine why creds aren't being captured.

Thanks!

**Comment by nanoymaster** [comment]
nevermind, it was me being dumb...
can close this now
