### ISSUE TITLE
Not able to login with Default username and password

### ISSUE THREAD

**Issue by ryry190** [gophish/gophish#2160]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you running gophish-v0.10.0-windows-64bit

Brief description of the issue: I am not able to login with admin/gophish

What are you expecting to see happen? : I expect to be able to login

What are you seeing happen? error: invalid username/password

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by asaqib27** [comment]
admin/gophish is no more default credentials. You have to use admin as username and password that would be generated randomly when you start gophish. You can find this randomly generated password on the terminal screen.

**Comment by asaqib27** [comment]
For versions of Gophish > 0.10.1, the temporary administrator credentials are printed in the logs when you first execute the Gophish binary.

You can refer official docs [here](https://docs.getgophish.com/user-guide/getting-started#logging-in)

**Comment by ryry190** [comment]
So even if I installed gophish using nssm I can get my password

**Comment by asaqib27** [comment]
Yes, you can refer to this video that I have come across https://www.youtube.com/watch?v=YywVLJi7KtU

**Comment by fbihackertip2** [comment]
HELP...cant login with admin/gophish while running gophish on nssm
