### ISSUE TITLE
Left navigation bar/menu not showing on mobile

### ISSUE THREAD

**Issue by jepunband** [gophish/gophish#2164]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.11.0

Brief description of the issue: side navigation bar not showing when viewing from mobile

What are you expecting to see happen? : to see the left menu/navigation bar

What are you seeing happen? left menu navigation bar not showing

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - ./gophish
 * Step 2 - go to https://localhost:3333
 * Step 3 - login

**Comment by glennzw** [comment]
The mobile experience with gophish is a little clumsy; it's on our TODO list to overhaul the slightly outdated Bootstrap 3 front end. See https://github.com/gophish/gophish/pull/1565#issuecomment-526181253

Sorry about that.

**Comment by jepunband** [comment]
Ok.
