### ISSUE TITLE
Can’t get Gophish to unzip properly on D/O vps 

### ISSUE THREAD

**Issue by ryry190** [gophish/gophish#2165]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: gophish-v0.11.0-Linux-64bit.zip

Brief description of the issue: Every time I try to unzip the file I get db And none of the files from the gophish Download

What are you expecting to see happen? :To Get the file unzipped properly

What are you seeing happen? Nothing 

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
Please share some screenshots of the output you're getting, and the list of all commands you've run to reach the point you're at.

**Comment by ryry190** [comment]
![Uploading 15E33730-B113-4B3C-8649-834DC9FB9BB2.jpeg…]()

**Comment by ryry190** [comment]
![Uploading 43D33264-5265-4418-B512-D89609A0DAE7.jpeg…]()

**Comment by ryry190** [comment]
![Screenshot_2021-04-10_18_36_49](https://user-images.githubusercontent.com/82002651/114287910-14efb800-9a39-11eb-8a32-eeb3856e2b3e.png)
![Screenshot_2021-04-10_18_38_25](https://user-images.githubusercontent.com/82002651/114287913-19b46c00-9a39-11eb-865d-12ef53e295ce.png)

**Comment by ryry190** [comment]
an ive tried to re-download it over an over

**Comment by glennzw** [comment]
The `gophish` binary is there. Run it like so:

```
chmod +x gophish
./gophish
```

**Comment by ryry190** [comment]
could you explain a little more in detail cause i' basically using youtube videos to do this stuff lol

**Comment by ryry190** [comment]
i'm*

**Comment by ryry190** [comment]
and curious what the db means ? or if it has any relevance at all ?

**Comment by glennzw** [comment]
Where you typed the first `ls` command, type `chmod +x gophish` and press enter, and then type `./gophish` and press enter.

The db folder contains schema definitions for the gophish project, you don't need to worry about it.

**Comment by ryry190** [comment]
How do I get to the gophish Directory ? Because it’s not recognizing the
file
It’s just saying “ Not a directory “

**Comment by glennzw** [comment]
In your first screenshot, you typed `ls`. The file `gophish` was displayed. At this point type `chmod +x gophish` and press enter, and then type `./gophish` and press enter.

**Comment by glennzw** [comment]
Closing as haven't heard back. The documentation may help moving forward: https://docs.getgophish.com/user-guide/installation
