### ISSUE TITLE
Table data not being pulled from database

### ISSUE THREAD

**Issue by himynameiszak** [gophish/gophish#2168]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.11.0
Brief description of the issue: 
I have a working installation. It opens the database, it isn't corrupt. If I browser the database via sqllite data browser it's all there. The problem is when accessing the platform via the browser it doesn't show me any of my existing templates, groups, users, etc.
What are you expecting to see happen? :

What are you seeing happen?

![image](https://user-images.githubusercontent.com/2986028/115274786-070ff600-a10f-11eb-83d5-8374d6840da6.png)

![image](https://user-images.githubusercontent.com/2986028/115274815-142ce500-a10f-11eb-99ca-fc4479c27f63.png)

**Comment by himynameiszak** [comment]
Here it is:
{
	"admin_server": {
		"listen_url": "kmf-rds02:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "gophish_admin.key"
	},
	"phish_server": {
		"listen_url": "0.0.0.0:8840",
		"use_tls": false,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": "",
	"logging": {
		"filename": "log.txt",
		"level": ""
	}
}


The user's populate and i'm able to sign in successfully. The templates were in the UI previously. I started a campaign and it signed me out after, when I logged back in everything wouldn't appear in the UI.

![image](https://user-images.githubusercontent.com/2986028/115301989-eb691780-a12f-11eb-9f7c-0940a71550d9.png)

**Comment by glennzw** [comment]
Very strange. Let's try some debugging. I'd suggest making a copy of the `gophish.db` first.

Try add a new template, and see if it's reflected in the SQLite browser you're looking at. Also, in the 'User Management' tab in the UI are there any other users? Templates aren't shared between users.

**Comment by himynameiszak** [comment]
Interesting, everything repopulated with the admin creds. So nothing is shared between users including campaigns and sending profiles?

**Comment by glennzw** [comment]
Correct, every user has their own templates/etc that other users can't see.

**Comment by himynameiszak** [comment]
Thanks! I believe we can mark this solved.
