### ISSUE TITLE
No binary in zip file for macOS?

### ISSUE THREAD

**Issue by michaelreinhart** [gophish/gophish#2169]
I've downloaded the file gophish-v0.11.0-osx-64bit.zip, but when I unpack it on my Mac, there is no binary (i.e. application) inside. Am I doing something wrong?

**Comment by glennzw** [comment]
Looks like it's there for me:

```
➜  gophish-v0.11.0-osx-64bit $ ls    
LICENSE     README.md   VERSION     config.json db          gophish     static      templates

➜  gophish-v0.11.0-osx-64bit $ file gophish 
gophish: Mach-O 64-bit executable x86_64
```

**Comment by michaelreinhart** [comment]
Many thanks for the clarification. I guess I was expecting a macOS app.

**Comment by glennzw** [comment]
Nope just the regular binary. Hope that helps.
