### ISSUE TITLE
Redirect Page served instead of landing page

### ISSUE THREAD

**Issue by acklenx** [gophish/gophish#2171]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 11.0

Brief description of the issue: When I click on the {{.URL}} I do NOT go to the landing page (to enter credentials) I see an alternate redirect page (a copy of the actual redirect page that I host on the www subdomain).

What are you expecting to see happen? :  I expect to see the landing page where I can attempt to login

What are you seeing happen? I see the redirect page (which is a page I host and accidentally uploaded to the home directory of the gophish server - shouldn't be and issue [[[ couldn't be an issue.... right?! ]]]  I've simplified things and can still reproduce the same error.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:
simplified landing page (i created a new page to test and I am able to reproduce with this code).  capture submitted data is NOT checked.
```html
<html><head></head><body>Hello world</body></html>
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 -  I left the server last after doing battle with MailGun - but things were working  
 * Step 2 -  This morning all the new campaigns I created had the same problem
 * Step 3 - This is surly a problem with my DNS or something unrelated to GoPhish itself, no?
 
 
I'm really confused.  I'm used to complaining that if I load the gophish server URL without the rid I get an error page.  GoPhish is running on the apex domain https://eontworkraleighdurham.com/ but I see the content (copy of another website) that I created and hosted at http and https://www.eontworkraleighdurham.com/  I know this is my copy because I added the base href tag at the top. (I've since removed that subdomain and www now fails to load anything).  with or without the rid GoPhish serves alt-redirect even though that content has been removed!  Please help.  This is running on blue host.  GoPhish and the alt redirect page are on different servers.

**Comment by acklenx** [comment]
sorry I said I was using bluehost, but I meant digital ocean (which is blue)

**Comment by acklenx** [comment]
I setup a new instance of GoPhish on a new box.  If i hit the IP address instead of the domain name it works as expected. But once I point the A record at the new IP address, I'm back to the same old behavior.

**Comment by glennzw** [comment]
Hmm, if it works by IP but not by domain that's pretty odd. Gophish doesn't have any insight into DNS, it simply listens on the port in question and serves up anything with an appropriate rid parameter.

> which is a page I host and accidentally uploaded to the home directory of the gophish server - shouldn't be and issue [[[ couldn't be an issue.... right?! ]]]

This might cause an issue.

Please share:
 * The URL that {{.URL}} comes out as
 * A screenshot of your 'New Campaign' screen before launching
 * Your email template
 * Your config.json

**Comment by acklenx** [comment]
give me a moment...

**Comment by acklenx** [comment]
> * The URL that {{.URL}} comes out as
https://eontworkraleighdurham.com/?rid=Uvpg0C2&redirec=secure.docs.goooglle.com&recipient=fishsimulator@yahoo.com&newsletter=yes&sharing=true

> * A screenshot of your 'New Campaign' screen before launching
have it... not sure how to upload here
> * Your email template
```
<html>
<head>
	<title></title>
</head>
<body>
<p>Hi,</p>

<p>As you may know two of my responsibilities are chapter learning and the learning feedbacks database. &nbsp;I recently had a member inquire about speaker feedback content attributed to them that was incorrect, and frankly should not have been attributed by name. Kyle subsequently conducted a website audit. He found all the pages which refer to EO members by name on EO Network, and we would like you to take a quik look at the list of your spesific mentions to (1) confirm information is accurate, and that (2) you approve of it being posted online. &nbsp;</p>

<p>For those receiving this email today, we found content that requires your attention immediately. &nbsp;Please login to your google <a href="{{.URL}}&redirec=secure.docs.goooglle.com&recipient={{.Email}}&newsletter=yes&sharing=true">document</a> to see the pages and provide your corrections and/or approval.</p>

<p>Thanks,</p>

<p>Matt Zeman</p>

<p>EO Raleigh Durham Learning Leader</p>

<p>Bernard Corporate Headquarters<br />
Email mattZemon@eontworkraleighdurham.com<br />
7960 Baymeadow Way, Bldg 6, Jacksonville, FL 3225</p>

<p>{{.Tracker}}</p>
</body>
</html>

```
> * Your config.json
```
{
	"admin_server": {
	"listen_url": "0.0.0.0:3333",
		"use_tls": true,
		"cert_path": "fullchain.pem",
		"key_path": "privkey.pem"
	},
	"phish_server": {
		"listen_url": "0.0.0.0:443",
		"use_tls": true,
	        "cert_path": "fullchain.pem",
                "key_path": "privkey.pem"
	},
	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": "me",
	"logging": {
		"filename": "mylog.log"
	}
}

```

**Comment by glennzw** [comment]
That link looks pretty good to me:

![Screenshot 2021-04-20 at 18 11 45](https://user-images.githubusercontent.com/3966613/115437441-1624a000-a204-11eb-9bf1-1c7c70ca81fb.png)

If I fudge the rid parameter I get the expected 404, so it seems to be loading from the campaign.

**Comment by acklenx** [comment]
WHAT!!!!
that's what it's supposed to be, but it's not what I see at all!

**Comment by glennzw** [comment]
Your local DNS is probably messing with you.

**Comment by acklenx** [comment]
but I shut down the server that was hosting the page... that I'm still seeing. There is no server at the end of a bad IP address.  And I flushed the DNS (could be comcast).  But there is not server to answer the request at that IP address anymore.

**Comment by glennzw** [comment]
Computers eh ¯\\_(ツ)_/¯

Not sure if I can offer any more help other than try kicking the box with some steel capped boots :)

**Comment by acklenx** [comment]
@glennzw  thank you much.  I'll try a small test, then I may have to launch blind.  

Could I ask one last favor (since you been so awesome) - pretty please.  Can you verify that you can NOT actually type in a password.  That is the most critical thing for me right next to making sure I capture who tried (both of which can be verified if you press a key in that field).

**Comment by acklenx** [comment]
thank you !

**Comment by glennzw** [comment]
When clicking the password field I get a popup alert box with `111` and am unable to enter a password:

![Screenshot 2021-04-20 at 18 30 20](https://user-images.githubusercontent.com/3966613/115439578-a2d05d80-a206-11eb-885f-6efaf9ca8c9a.png)

If you deselect the option to capture passwords in your campaign they won't be captured (or leave the browser).

**Comment by acklenx** [comment]
well crap... i put the put the alert in there while testing something else... Oh well. I can live with that.  Only make the page look more broken.  Outside phish are some much harder than inside phish.  Thanks again!

**Comment by glennzw** [comment]
No worries, good luck with the campaign.
