### ISSUE TITLE
During a campaign, clicking on a link does not go to Landing Page

### ISSUE THREAD

**Issue by dconner5** [gophish/gophish#2172]
What version of Gophish are you using?: 0.11.0

Brief description of the issue: I am testing out GoPhish to potentially be used for simulated phishing at my company. I configured a campaign, but when clicking on the link in a phishing email, I am not seeing the landing page. 

What are you expecting to see happen? : I am expecting the landing page when clicking on the link

What are you seeing happen? I wasn't sure what value to place in the URL field when creating a campaign. If I place no value, I get a 404 error when clicking on the link in the phishing email.  If I use http://127.0.0.1 then I get the IIS welcome page when clicking on the link in the phishing email. I see the rid is being passed over as a parameter. This is an example of the url http://127.0.0.1/?rid=3ET3jIl

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - I created a landing page
 * Step 2 - I created an email template
 * Step 3 - I created a sending profile
 * Step 4 - I created a user group
 * Step 5 - I created the campaign using the URL http://127.0.0.1 and using all the dependent data from the above steps
 
 I am fairly certain I am missing something silly. Any help would be great.

**Comment by glennzw** [comment]
Hi there! No worries on it maybe being something silly, we were all new to gophish at some point.

In the URL field you need to enter a URL that's reachable by your intended recipient - an internet routable IP address (127.0.0.1 just points to your local computer, which is fine for testing).

If you're getting an IIS message then I'd guess you already have a webserver running on port 80 on that machine, and so the gophish webserver can't bind to that port. Could you paste a screenshot of gophish starting up please.

**Comment by glennzw** [comment]
Closing out as haven't heard back.
