### ISSUE TITLE
What kind of EC2 server do I need for a phishingcampaign with 12.000 recipients?

### ISSUE THREAD

**Issue by Tssjimp** [gophish/gophish#2173]
Hello,

I'm relatively new to GoPhish and want to create a campaing for our company. We have 12.000 employees. I want to run GoPhish on a EC2 server (Linux or Windows, doesn't matter). 

I really have no idea what the minumum specs shoud be. Could you point me in the right direction? Thank you very much!!

**Comment by glennzw** [comment]
This seems to give some guidance: https://github.com/gophish/gophish/issues/1144 (tl;dr: 4GM RAM).

gophish is fairly lightweight, but if your plan is to phish all 12,000 in one campaign your browser may struggle (see https://github.com/gophish/gophish/pull/2019, which I need to get around to finishing).

I'd recommend doing some dry runs with Mailhog to see how it holds up.

**Comment by edermi** [comment]
I'd recommend you to use MySQL instead of SQLite for that many users. In my experience, at some point this becomes the bottleneck when several hundreds of users try to access the phishing link at the same time.

**Comment by Tssjimp** [comment]
Thanks! This really helps! Very valuable tips. I'll set up mailhog and switch to MySQL.

**Comment by glennzw** [comment]
Good point @edermi.

I'm closing this out, feel free to reopen @Tssjimp if you get stuck.
