### ISSUE TITLE
Too many open files - Crashing gophish on large campaign.

### ISSUE THREAD

**Issue by ehotdc** [gophish/gophish#2178]
**What version of Gophish are you using?:** 
Gophish v0.11.0

**Brief description of the issue:** 
Running a very large campaign (~7000 users) made gophish completely irresponsive and crashed in a variety of different ways.

My setup:
I have gophish running on port 8000 internally, with nginx in the front, handling all tls. Nginx is utilizing geoIP module to restrict the incoming connections to only be from countries that are related to the business.

Here is my nginx.conf (may be relevant)
```
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;
events {
        worker_connections 1024;
}

http {
    geoip_country /usr/share/GeoIP/GeoIP.dat;
    map $geoip_country_code $allowed_country {
        default no;
        DK yes;
        UK yes;
        IN yes;
}

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
        gzip on;

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}
```
and for the nginx conf for the domain.
```
server {

        listen   443;
        listen   80;
        server_name EXAMPLE.COM;
        if ($allowed_country = no) {
            return 444;
        }
        location / {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_pass http://localhost:8000/;
        }

        ssl on;
        ssl_certificate /etc/letsencrypt/live/EXAMPLE.COM/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/EXAMPLE.COM/privkey.pem;
}
```

Before starting the campaign I set up gophish to run in my terminal and not as a service, so I could monitor it if it crashed.
After a couple of hundred of users started to visit the site, it became unresponsive. 
After a few minutes it failed with the following error:

```
2021/04/26 13:13:12 http: Accept error: accept tcp [::]:8000: accept4: too many open files; retrying in 5ms
2021/04/26 13:13:12 http: Accept error: accept tcp [::]:8000: accept4: too many open files; retrying in 10ms
2021/04/26 13:13:12 http: Accept error: accept tcp [::]:8000: accept4: too many open files; retrying in 20ms
2021/04/26 13:13:12 http: Accept error: accept tcp [::]:8000: accept4: too many open files; retrying in 40ms
2021/04/26 13:13:13 http: Accept error: accept tcp [::]:8000: accept4: too many open files; retrying in 80ms
2021/04/26 13:13:13 http: Accept error: accept tcp [::]:8000: accept4: too many open files; retrying in 160ms
time="2021-04-26T13:13:13+00:00" level=fatal msg="open static/db/geolite2-city.mmdb: too many open files"
```

I don't understand how this error appears in gophish, since NGINX should be responsible for filtering IP connections.

I have started moving the platform towards using mysql instead of sqlite, since I read that is better for performance.

**What are you expecting to see happen? :**
Gophish running smooth as an eel (see what I did there?)

**What are you seeing happen?**
Gophish crashing.

**Comment by glennzw** [comment]
Looking through the issue history this has come up before; https://github.com/gophish/gophish/issues/1633#issuecomment-547238654

The hypothesis in that thread was that it could be caused by a low user limit on the number of open sockets. A quick Google search suggests trying to up this limit: https://medium.com/@cubxi/nginx-too-many-open-files-error-solution-for-ubuntu-b2adaf155dc5

Maybe give that a go. You can run some tests without creating live campaigns by sending emails to Mailhog or something similar. Let us know how you get on.

**Comment by ehotdc** [comment]
This solved the issue, thanks!
