### ISSUE TITLE
Gophish on DMZ

### ISSUE THREAD

**Issue by MohamedNossirat** [gophish/gophish#2179]
Hi there, 

I'm planning to go for a campaign to test security awareness of our users. 
is it possible to put our server GoPhish to be accessible from another network ? Can we catch the statics either ? or this is just an interior test.

I configured Gophish to be accessible in our internal network and it works perfectly, but I want to reach out users who are in remot-working.

thanx

**Comment by glennzw** [comment]
Hi there! Yes absolutely you can bury gophish as deep as you like in a DMZ, as long as there is some routable IP that your users can hit that points to your gophish server (your "phish_server" as defined in your `config.json`).

**Comment by glennzw** [comment]
Closing, feel free to re-open if you still need help.
