### ISSUE TITLE
Tracking image

### ISSUE THREAD

**Issue by nanoymaster** [gophish/gophish#218]
whenever I use {{.Tracker}}
it puts the image in the email... however the src is: http://<my domain>/track?rid=<random UID>
but because it's not going to track.png or some similar transparent image it displays the broken image icon.

I think would be stealthier to display an invisible image

**update, just discovered the old issue and apparently been fixed /ignore this

**Comment by jordan-wright** [comment]
Are you building from source? This was recently fixed. You can see the progress in #202.

**Comment by nanoymaster** [comment]
no I was using the normal version... 
built from source now and saw that this is fixed and 302 redirect after post... so awesome :)
keep up the good work

**Comment by g9732** [comment]
Hi,
I have this same issue in last version 0.5.0 and question with this. Is there any option to add {{.Tracker}} to my linked image in email?

Thx for help.
