### ISSUE TITLE
New with gophish, have some questions 

### ISSUE THREAD

**Issue by mkarbian** [gophish/gophish#2180]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.11.0
Brief description of the issue: 
using  linux centos ,cant find the my email templates that i add to the system.
and do i need to include in the html file of the email a "href" for the landing page? or the system do the redirection automatically ?
What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
<html><head><title>Phish Template Preview</title></head><body><table style="border-collapse:collapse;padding:0;min-width:450px;" border="0" width="100%" align="center"><tbody><tr><td style="padding:6px;"><img style="float:left;height:auto;" src="xxx" alt="Microsoft"></td>
</tr><tr style="background-color:#ffffff;"><td style="padding:20px 6px 6px 6px;">
<p style="font-size:16px;line-height:21px;color:#707070;padding:0 0 20px 0;margin:0;font-family:'Segoe UI Semibold', 'Segoe UI Bold', 'Segoe UI', 'Helvetica Neue Medium', Arial, sans-serif;">Dear Joe,</p>
<p style="font-size:16px;line-height:21px;color:#707070;padding:0 0 20px 0;margin:0;font-family:'Segoe UI Semibold', 'Segoe UI Bold', 'Segoe UI', 'Helvetica Neue Medium', Arial, sans-serif;"><span style="font-weight:400;">The account information associated with joe.learner@mail.test has expired. Please log in to revalidate your information and retain access to your account.</span></p>
<a style="border:none;background:#2672ec;padding:10px 14px 11px 14px;border-collapse:collapse;text-decoration:none;font-weight:bold;color:#ffffff;font-family:'Segoe UI Semibold', 'Segoe UI Bold', 'Segoe UI', 'Helvetica Neue Medium', Arial, sans-serif;font-size:14px;display:inline-block;" title="View More" href="xxxx">Log In</a>
<p style="font-size:16px;line-height:21px;color:#707070;padding:20px 0 20px 0;margin:0;font-family:'Segoe UI Semibold', 'Segoe UI Bold', 'Segoe UI', 'Helvetica Neue Medium', Arial, sans-serif;font-style:italic;"><a style="color:#2672ec;" href="xxxx">Was this helpful? Send feedback.</a></p>
<p style="font-size:16px;line-height:21px;color:#707070;padding:10px 0 0 0;margin:0;font-family:'Segoe UI Semibold', 'Segoe UI Bold', 'Segoe UI', 'Helvetica Neue Medium', Arial, sans-serif;">This message was sent from an unmonitored email address. Please do not reply to this message.</p>
</td>
</tr><tr><td style="padding:6px 6px 6px 6px;">
<p style="font-size:12px;line-height:21px;color:#707070;padding:10px 0 0 0;margin:0;font-family:'Segoe UI Semibold', 'Segoe UI Bold', 'Segoe UI', 'Helvetica Neue Medium', Arial, sans-serif;"></p>
</td>
</tr></tbody></table></body></html>
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by atheriqbal** [comment]
Hi @mkarbian , 

Please copy paste the html for your email template here. 
Email templates are added separately, so are landing pages. 

You need to include {{.URL}} in href tag, like <a href="{{.URL}}">. Also read [this](https://docs.getgophish.com/user-guide/building-your-first-campaign/creating-the-template)

Regards

**Comment by mkarbian** [comment]
hi,

I am pasting both mail and landing page.
this is just an example..BTW I don't know why but i cant find the path \static\endpoint.

how do i word with the links in the html, do i need to tell gophish where to redirect with "href" for example? 

**that's the HTML of the email** :

<html><head><title>Phish Template Preview</title></head><body><table style="border-collapse:collapse;padding:0;min-width:450px;" border="0" width="100%" align="center"><tbody><tr><td style="padding:6px;"><img style="float:left;height:auto;" src="https://s3.us-east-2.amazonaws.com/cdn29/Outlook+365/logo-microsoft.png" alt="Microsoft"></td>
</tr><tr style="background-color:#ffffff;"><td style="padding:20px 6px 6px 6px;">
<p style="font-size:16px;line-height:21px;color:#707070;padding:0 0 20px 0;margin:0;font-family:'Segoe UI Semibold', 'Segoe UI Bold', 'Segoe UI', 'Helvetica Neue Medium', Arial, sans-serif;">Dear Joe,</p>
<p style="font-size:16px;line-height:21px;color:#707070;padding:0 0 20px 0;margin:0;font-family:'Segoe UI Semibold', 'Segoe UI Bold', 'Segoe UI', 'Helvetica Neue Medium', Arial, sans-serif;"><span style="font-weight:400;">The account information associated with joe.learner@mail.test has expired. Please log in to revalidate your information and retain access to your account.</span></p>
<a style="border:none;background:#2672ec;padding:10px 14px 11px 14px;border-collapse:collapse;text-decoration:none;font-weight:bold;color:#ffffff;font-family:'Segoe UI Semibold', 'Segoe UI Bold', 'Segoe UI', 'Helvetica Neue Medium', Arial, sans-serif;font-size:14px;display:inline-block;" title="View More" href="C:\Users\matanka\Desktop\login.html">Log In</a>
<p style="font-size:16px;line-height:21px;color:#707070;padding:20px 0 20px 0;margin:0;font-family:'Segoe UI Semibold', 'Segoe UI Bold', 'Segoe UI', 'Helvetica Neue Medium', Arial, sans-serif;font-style:italic;"><a style="color:#2672ec;" href="https://securityiq.infosecinstitute.com/formPreview/240?education=&amp;templateId=11429">Was this helpful? Send feedback.</a></p>
<p style="font-size:16px;line-height:21px;color:#707070;padding:10px 0 0 0;margin:0;font-family:'Segoe UI Semibold', 'Segoe UI Bold', 'Segoe UI', 'Helvetica Neue Medium', Arial, sans-serif;">This message was sent from an unmonitored email address. Please do not reply to this message.</p>
</td>
</tr><tr><td style="padding:6px 6px 6px 6px;">
<p style="font-size:12px;line-height:21px;color:#707070;padding:10px 0 0 0;margin:0;font-family:'Segoe UI Semibold', 'Segoe UI Bold', 'Segoe UI', 'Helvetica Neue Medium', Arial, sans-serif;"></p>
</td>
</tr></tbody></table></body></html>

**that's the HTML for the user to be re direct from the link in the email:**

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="/css/data-entry.28fd3fcdd108af61.css" />
    <style>
        #submit {
            cursor: pointer;
        }
    </style>
    <title></title>
</head>
<body style="margin:0;"><div style="position: absolute; top: 0; right: 0; bottom: 0; left: 0; background: url('https://s3.amazonaws.com/securityiq/phishing-templates/Outlook+365/background.jpg'); background-size: cover;">
<div style="position: absolute; top: 0; right: 0; bottom: 0; width: 500px; z-index: 500; background: white;">
<div style="margin: 0 50px; width: 400px; position: absolute; top: 0; bottom: 0; font-size: .9em; font-family: 'Segoe UI','Segoe','SegoeUI-Regular-final',Tahoma,Helvetica,Arial,sans-serif;"><img style="position: relative; top: 50px; display: block;" src="https://s3.amazonaws.com/securityiq/phishing-templates/Outlook+365/logo-outlook365.png" alt="" /> <span style="display: block; position: relative; top: 75px;">Work or school, or personal Microsoft account</span>
<div style="position: relative; top: 95px; width: 400px;"><input style="height: 28px; padding-left: 3px; margin: 0; border: 1px solid #b8b8b8; background: transparent; color: #000; width: 350px; box-sizing: border-box; font-size: .9em; outline: none;" type="text" placeholder="Email or phone" /> <input style="height: 28px; padding-left: 3px; margin: 0; border: 1px solid #b8b8b8; background: transparent; color: #000; width: 350px; box-sizing: border-box; font-size: .9em; margin-top: 10px; outline: none;" type="password" placeholder="Password" />
<div style="position: relative; margin: 20px 0;"><input style="position: absolute; left: -3px; float: left;" type="checkbox" /> <span style="display: block; position: absolute; left: 20px;">Keep me signed in</span></div>
<button id="submit" style="background: #2672ec; cursor: default; border: 1px solid #fff; padding: 6px 12px 6px 12px; color: #fff; width: auto; margin-right: 4px; font-size: 14px; position: absolute; top: 120px; outline: none;" type="submit">Sign in</button> <a style="position: absolute; top: 170px; text-decoration: none; color: #2872dd; font-size: 12px;">Can&rsquo;t access your account?</a></div>
<img style="position: absolute; bottom: 50px; right: 0;" src="https://s3.amazonaws.com/securityiq/phishing-templates/Outlook+365/logo-microsoft.png" alt="" /></div>
</div>
</div></body><script>
    document.getElementById('submit').addEventListener('click', function (event) {
        event.preventDefault();
                        window.location.href = 'https://securityiq.infosecinstitute.com/phished/preview?education=1&templateId=11429';
                    })
</script>
</html>

**Comment by mkarbian** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="/css/data-entry.28fd3fcdd108af61.css" />
    <style>
        #submit {
            cursor: pointer;
        }
    </style>
    <title></title>
</head>
<body style="margin:0;"><div style="position: absolute; top: 0; right: 0; bottom: 0; left: 0; background: url('https://s3.amazonaws.com/securityiq/phishing-templates/Outlook+365/background.jpg'); background-size: cover;">
<div style="position: absolute; top: 0; right: 0; bottom: 0; width: 500px; z-index: 500; background: white;">
<div style="margin: 0 50px; width: 400px; position: absolute; top: 0; bottom: 0; font-size: .9em; font-family: 'Segoe UI','Segoe','SegoeUI-Regular-final',Tahoma,Helvetica,Arial,sans-serif;"><img style="position: relative; top: 50px; display: block;" src="https://s3.amazonaws.com/securityiq/phishing-templates/Outlook+365/logo-outlook365.png" alt="" /> <span style="display: block; position: relative; top: 75px;">Work or school, or personal Microsoft account</span>
<div style="position: relative; top: 95px; width: 400px;"><input style="height: 28px; padding-left: 3px; margin: 0; border: 1px solid #b8b8b8; background: transparent; color: #000; width: 350px; box-sizing: border-box; font-size: .9em; outline: none;" type="text" placeholder="Email or phone" /> <input style="height: 28px; padding-left: 3px; margin: 0; border: 1px solid #b8b8b8; background: transparent; color: #000; width: 350px; box-sizing: border-box; font-size: .9em; margin-top: 10px; outline: none;" type="password" placeholder="Password" />
<div style="position: relative; margin: 20px 0;"><input style="position: absolute; left: -3px; float: left;" type="checkbox" /> <span style="display: block; position: absolute; left: 20px;">Keep me signed in</span></div>
<button id="submit" style="background: #2672ec; cursor: default; border: 1px solid #fff; padding: 6px 12px 6px 12px; color: #fff; width: auto; margin-right: 4px; font-size: 14px; position: absolute; top: 120px; outline: none;" type="submit">Sign in</button> <a style="position: absolute; top: 170px; text-decoration: none; color: #2872dd; font-size: 12px;">Can&rsquo;t access your account?</a></div>
<img style="position: absolute; bottom: 50px; right: 0;" src="https://s3.amazonaws.com/securityiq/phishing-templates/Outlook+365/logo-microsoft.png" alt="" /></div>
</div>
</div></body><script>
    document.getElementById('submit').addEventListener('click', function (event) {
        event.preventDefault();
                        window.location.href = 'https://securityiq.infosecinstitute.com/phished/preview?education=1&templateId=11429';
                    })
</script>
</html>

**Comment by mkarbian** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="/css/data-entry.28fd3fcdd108af61.css" />
    <style>
        #submit {
            cursor: pointer;
        }
    </style>
    <title></title>
</head>
<body style="margin:0;"><div style="position: absolute; top: 0; right: 0; bottom: 0; left: 0; background: url('https://s3.amazonaws.com/securityiq/phishing-templates/Outlook+365/background.jpg'); background-size: cover;">
<div style="position: absolute; top: 0; right: 0; bottom: 0; width: 500px; z-index: 500; background: white;">
<div style="margin: 0 50px; width: 400px; position: absolute; top: 0; bottom: 0; font-size: .9em; font-family: 'Segoe UI','Segoe','SegoeUI-Regular-final',Tahoma,Helvetica,Arial,sans-serif;"><img style="position: relative; top: 50px; display: block;" src="https://s3.amazonaws.com/securityiq/phishing-templates/Outlook+365/logo-outlook365.png" alt="" /> <span style="display: block; position: relative; top: 75px;">Work or school, or personal Microsoft account</span>
<div style="position: relative; top: 95px; width: 400px;"><input style="height: 28px; padding-left: 3px; margin: 0; border: 1px solid #b8b8b8; background: transparent; color: #000; width: 350px; box-sizing: border-box; font-size: .9em; outline: none;" type="text" placeholder="Email or phone" /> <input style="height: 28px; padding-left: 3px; margin: 0; border: 1px solid #b8b8b8; background: transparent; color: #000; width: 350px; box-sizing: border-box; font-size: .9em; margin-top: 10px; outline: none;" type="password" placeholder="Password" />
<div style="position: relative; margin: 20px 0;"><input style="position: absolute; left: -3px; float: left;" type="checkbox" /> <span style="display: block; position: absolute; left: 20px;">Keep me signed in</span></div>
<button id="submit" style="background: #2672ec; cursor: default; border: 1px solid #fff; padding: 6px 12px 6px 12px; color: #fff; width: auto; margin-right: 4px; font-size: 14px; position: absolute; top: 120px; outline: none;" type="submit">Sign in</button> <a style="position: absolute; top: 170px; text-decoration: none; color: #2872dd; font-size: 12px;">Can&rsquo;t access your account?</a></div>
<img style="position: absolute; bottom: 50px; right: 0;" src="https://s3.amazonaws.com/securityiq/phishing-templates/Outlook+365/logo-microsoft.png" alt="" /></div>
</div>
</div></body><script>
    document.getElementById('submit').addEventListener('click', function (event) {
        event.preventDefault();
                        window.location.href = 'https://securityiq.infosecinstitute.com/phished/preview?education=1&templateId=11429';
                    })
</script>
</html>

**Comment by mkarbian** [comment]
> hi,
> 
> I am pasting both mail and landing page.
> this is just an example..BTW I don't know why but i cant find the path \static\endpoint.
> 
> how do i word with the links in the html, do i need to tell gophish where to redirect with "href" for example?
> 
> **that's the HTML of the email** :
> 
> <title>Phish Template Preview</title>
> ![Microsoft](https://camo.githubusercontent.com/2af00b52838f2be315674f13a595bbefd5be57c09e1209040cc99bba61105ee4/68747470733a2f2f73332e75732d656173742d322e616d617a6f6e6177732e636f6d2f63646e32392f4f75746c6f6f6b2b3336352f6c6f676f2d6d6963726f736f66742e706e67)
> Dear Joe,
> 
> The account information associated with joe.learner@mail.test has expired. Please log in to revalidate your information and retain access to your account.
> 
> [Log In](xxxxx)
> [Was this helpful? Send feedback.](https://securityiq.infosecinstitute.com/formPreview/240?education=&templateId=11429)
> 
> This message was sent from an unmonitored email address. Please do not reply to this message.
> 
> **that's the HTML for the user to be re direct from the link in the email:**
> 
> <style> #submit { cursor: pointer; } </style> <title></title>
> ![](https://camo.githubusercontent.com/c4f9649de89aa6d4cc3be9d44ce3e9e4332716111e8118d382163f0fd45aaa17/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f736563757269747969712f7068697368696e672d74656d706c617465732f4f75746c6f6f6b2b3336352f6c6f676f2d6f75746c6f6f6b3336352e706e67) Work or school, or personal Microsoft account
> Keep me signed in
> Sign in Can’t access your account?
> ![](https://camo.githubusercontent.com/e40e73e6120b1d3e3b9c8e333fd2baa5f1928485984a0dc0b6706f933fa10dea/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f736563757269747969712f7068697368696e672d74656d706c617465732f4f75746c6f6f6b2b3336352f6c6f676f2d6d6963726f736f66742e706e67)
> <script> document.getElementById('submit').addEventListener('click', function (event) { event.preventDefault(); window.location.href = 'https://securityiq.infosecinstitute.com/phished/preview?education=1&templateId=11429'; }) </script>

sorry but the other HTML file doesn't work here, not sure why..

**Comment by glennzw** [comment]
You need to paste your HTML here between triple backticks. e.g:

\`\`\`
html goes here
\`\`\`

If you don't it tries to render and you get the weird output you see above. I edited your first post to fix this.

**Comment by mkarbian** [comment]
thanks for your help really appreciated .
I add add txt file thats the html if you need.
[login.txt](https://github.com/gophish/gophish/files/6392459/login.txt)


[login.txt](https://github.com/gophish/gophish/files/6392452/login.txt)


```

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="/css/data-entry.28fd3fcdd108af61.css" />
    <style>
        #submit {
            cursor: pointer;
        }
    </style>
    <title></title>
</head>
<body style="margin:0;"><div style="position: absolute; top: 0; right: 0; bottom: 0; left: 0; background: url('https://s3.amazonaws.com/securityiq/phishing-templates/Outlook+365/background.jpg'); background-size: cover;">
<div style="position: absolute; top: 0; right: 0; bottom: 0; width: 500px; z-index: 500; background: white;">
<div style="margin: 0 50px; width: 400px; position: absolute; top: 0; bottom: 0; font-size: .9em; font-family: 'Segoe UI','Segoe','SegoeUI-Regular-final',Tahoma,Helvetica,Arial,sans-serif;"><img style="position: relative; top: 50px; display: block;" src="https://s3.amazonaws.com/securityiq/phishing-templates/Outlook+365/logo-outlook365.png" alt="" /> <span style="display: block; position: relative; top: 75px;">Work or school, or personal Microsoft account</span>
<div style="position: relative; top: 95px; width: 400px;"><input style="height: 28px; padding-left: 3px; margin: 0; border: 1px solid #b8b8b8; background: transparent; color: #000; width: 350px; box-sizing: border-box; font-size: .9em; outline: none;" type="text" placeholder="Email or phone" /> <input style="height: 28px; padding-left: 3px; margin: 0; border: 1px solid #b8b8b8; background: transparent; color: #000; width: 350px; box-sizing: border-box; font-size: .9em; margin-top: 10px; outline: none;" type="password" placeholder="Password" />
<div style="position: relative; margin: 20px 0;"><input style="position: absolute; left: -3px; float: left;" type="checkbox" /> <span style="display: block; position: absolute; left: 20px;">Keep me signed in</span></div>
<button id="submit" style="background: #2672ec; cursor: default; border: 1px solid #fff; padding: 6px 12px 6px 12px; color: #fff; width: auto; margin-right: 4px; font-size: 14px; position: absolute; top: 120px; outline: none;" type="submit">Sign in</button> <a style="position: absolute; top: 170px; text-decoration: none; color: #2872dd; font-size: 12px;">Can&rsquo;t access your account?</a></div>
<img style="position: absolute; bottom: 50px; right: 0;" src="https://s3.amazonaws.com/securityiq/phishing-templates/Outlook+365/logo-microsoft.png" alt="" /></div>
</div>
</div></body><script>
    document.getElementById('submit').addEventListener('click', function (event) {
        event.preventDefault();
                        window.location.href = 'https://securityiq.infosecinstitute.com/phished/preview?education=1&templateId=11429';
                    })
</script>
</html>
```

**Comment by atheriqbal** [comment]
This is a little messy. But have a look at this email template. See how href tag is used. It will redirect you the landing page you have selected. 
```<html>
<head>
</head>
<body>
<p>&nbsp;</p>

<p><img alt="" src="https://www.underconsideration.com/brandnew/archives/dropbox_2017_logo.png" style="width: 120px; height: 27px;" /></p>
</body>
</html>
<title></title>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
<p>&nbsp;</p>

<p>Hi {{.FirstName}},</p>

<p>You have a new document/s shared to you via dropbox sharing.</p>

<p><a href="{{.URL}}">VIEW HERE</a></p>

<p>&nbsp;</p>

<p>&nbsp;</p>

<p>{{.Tracker}}</p>```


In your case, you can use this {{.URL}} in this way ->window.location.href = '{{.URL}}';. This will redirect to the landing page you have selected. Hope that helps. 

Regards

**Comment by mkarbian** [comment]
thanks for your help.
but i dont get it, how gophish making this re-direction from the email once the user click the link. to the landing page.

**Comment by atheriqbal** [comment]
You give the redirection URL when launching the campaign, that is your phishing server address and port. 
In an email, hover over the URL, and check how the URL is constructred with /rid. 

If you are asking in terms of code, thats a different thing. 

Regards

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to re-open if you're still haven't trouble.
