### ISSUE TITLE
Field 'From' on gophish to Phishing simulation

### ISSUE THREAD

**Issue by lcristovam** [gophish/gophish#2181]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

0.11.0
Brief description of the issue: 

authentication error for sending campaigns.

What are you expecting to see happen? :

I would like to send emails as a modified "FROM" header, in order to run phishing simulation campaigns for business customers, as part of a SecurityAwareness program.

Alternatives are welcome 

What are you seeing happen?

I'm having an authentication error when trying to send emails with a modified header (I imagine the problem is with the provider, I just want to confirm) 

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 -  configured sending profile with a smtp SaaS credentials
 * Step 2 -  started campaingn on gophish.
 
 
![image](https://user-images.githubusercontent.com/66442285/116568915-4b558000-a8df-11eb-9a7f-8220c596f87b.png)

**Comment by glennzw** [comment]
Hi there. Yeah you're right, any authentication issues are likely to be with the provider. A lot of SMTP SaaS products only let you send from a predetermined address. You can put whatever you want in the `From` section, it's just passed on to the SMTP server.

**Comment by lcristovam** [comment]
Ok, i will study the provider possibilities.  Thanks A lot Glenn

**Comment by glennzw** [comment]
No worries! Good luck.
