### ISSUE TITLE
Landing page content deleted when trying to save edits

### ISSUE THREAD

**Issue by PeterWhelan** [gophish/gophish#2186]
What version of Gophish are you using?: 
Latest

Brief description of the issue: 
Edited a landing page and clicked save.  Save button went gray but page remained on screen.  Came back to it a few hours later and it was still hung. Hit refresh and page appears in list with time of edit.  However, title and content do not appear.

What are you expecting to see happen? :
Landing page to be saved and retrieved.

**Comment by atheriqbal** [comment]
Hi @PeterWhelan , 

Was there any error in the log? 
Can you copy over the landing page here so we can check. 

Regards

**Comment by PeterWhelan** [comment]
No error in the log, I can send it if you like.
I can't copy the landing page over because goPhish deleted it instead of saving it.

**Comment by glennzw** [comment]
Hi Peter. Are you able to reproduce the issue, or it just happened once? It'll be hard for us to debug if you don't have the HTML that caused the issue. One thing you could do if it happens again is to check the browser console for errors.

**Comment by glennzw** [comment]
Closing out as haven't heard back.
