### ISSUE TITLE
level=fatal msg="tls: failed to find any PEM data in key input"

### ISSUE THREAD

**Issue by bartounet16** [gophish/gophish#2187]
Hello
i have generate certificate whith gandi

{
        "admin_server": {
                "listen_url": "0.0.0.0:3333",
                "use_tls": true,
                "cert_path": "gophish_admin.crt",
                "key_path": "gophish_admin.key"
        },
        "phish_server": {
                "listen_url": "0.0.0.0:443",
                "use_tls": true,
                "cert_path": "cesi.crt",
                "key_path": "cesi.key"
        },
        "db_name": "sqlite3",
        "db_path": "gophish.db",
        "migrations_prefix": "db/db_",
        "contact_address": "",
        "logging": {
                "filename": "",
                "level": ""
        }
}

but i have PEM error

time="2021-05-04T23:37:45+02:00" level=warning msg="No contact address has been configured."
time="2021-05-04T23:37:45+02:00" level=warning msg="Please consider adding a contact_address entry in your config.json"
goose: no migrations to run. current version: 20200730000000
time="2021-05-04T23:37:45+02:00" level=info msg="Starting IMAP monitor manager"
time="2021-05-04T23:37:45+02:00" level=info msg="Starting new IMAP monitor for user admin"
time="2021-05-04T23:37:45+02:00" level=info msg="Starting admin server at https://0.0.0.0:3333"
time="2021-05-04T23:37:45+02:00" level=info msg="Starting phishing server at https://0.0.0.0:443"
time="2021-05-04T23:37:45+02:00" level=fatal msg="tls: failed to find any PEM data in key input"

**Comment by glennzw** [comment]
Hi there. I'm not sure why you're getting that error but it's outside the scope of gophish support. Most people seem to favour using letsencrypt, e.g: https://www.n00py.io/2017/09/phishing-with-gophish-and-letsencrypt/

Alternatively you can generate your own cert for testing:

```
openssl req -newkey rsa:2048 -nodes -keyout gophish.key -x509 -days 365 -out gophish.crt
```

(see https://docs.getgophish.com/user-guide/installation#creating-ssl-certificate-and-private-keys)

**Comment by glennzw** [comment]
Closing out as haven't heard back.
