### ISSUE TITLE
Users and Admins can't see others creating things

### ISSUE THREAD

**Issue by emixam3** [gophish/gophish#2188]
**What version of Gophish are you using?:** 0.11

**Brief description of the issue:** In my GoPhish, I've got 5 users, admin{1-5}. When admin1 setup a new campaign, with a new landing page, a new email template etc.., he's the only one that can see all the work. He can't share with others.

**What are you expecting to see happen? :** To have the possibility to share campaigns, users & groups, email templates, landing pages and sending profiles with others gophish users.

Thanks for all the work on GoPhish!

**Comment by glennzw** [comment]
Unfortunately at this stage each user can only see their own data. There are plans for enhanced RBAC, but those are some ways down the line.

https://github.com/gophish/gophish/issues/2017

**Comment by emixam3** [comment]
Thanks for your reply, I didn't see #2017 issue.
For now, in my organization, we work like this:
- everyone has a named base admin account, and can log in Gophish with it,
- we created a service account, that every admin can switch on it when we need co-working.

**Comment by glennzw** [comment]
So at this stage unfortunately your admins would need to share credentials and login to the same account if they want to see each other's data. I wrote a utility script to copy templates/etc between accounts, which might help: https://github.com/glennzw/phishPaste
