### ISSUE TITLE
Error message after changing database to MySQL

### ISSUE THREAD

**Issue by Tssjimp** [gophish/gophish#2191]
Hello,

I'm using version 0.11.0 on Ubuntu 20.04.2 LTS 

I’ve installed mysql and replaced sqllite. Everything went well except that i get the error message “Error 1292: Incorrect datetime value: '0000-00-00' for column 'send_by_date' at row 1” in the final step to create a campaign.

So I know someting went wrong with updating my global settings as described in this article: https://docs.getgophish.com/user-guide/installation

I followed the instructions exactly, but after adding 
_[mysqld]
sql_mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
 to the /etc/mysql/mysql.cnf file i get the following message after restarting mysql._ 

**Job for mysql.service failed because the control process exited with error code.
See "systemctl status mysql.service" and "journalctl -xe" for details.**

I tried everything and also tried to edit other config files but it won’t work. After changing the config file back, mysql starts again. 

I hope you can help me!

**Comment by Tssjimp** [comment]
I think i found the solution here: https://www.knowledgebase-script.com/kb/article/how-do-i-disable-strict-mode-in-mysql-163.html

It seems like
[mysqld]
sql_mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION 

is not working anymore in newer versions. I've added:

**[mysqld]
sql-mode=""** 

to the config file **/etc/mysql/my.cnf** 

and now it works!

**Comment by emixam3** [comment]
Good to know! Thanks!

**Comment by glennzw** [comment]
I'll close this out, but hopefully others will find this useful. Good detective w2ork @Tssjimp .

**Comment by bbrendon** [comment]
Since this is more of an application setting, it might be better to move this to the connection string.

```
        "db_path": "x:x@(a:3306)/b?charset=utf8&parseTime=True&loc=UTC&sql_mode=''",

```
