### ISSUE TITLE
Dashbord Not Updating

### ISSUE THREAD

**Issue by hammi198** [gophish/gophish#2193]
Guys, Need assistance. Everything is working fine where emails can be sent out but Dashboard is not getting updated even though i click on the link embedded in the email. I am trying to open Go Phish Link just to verify if dashboard gets updated but no Luck. Below is the config file along with other details.

{
	"admin_server": {
		"listen_url": "127.0.0.1:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "gophish_admin.key"
	},
	"phish_server": {
		"listen_url": "0.0.0.0:80",
		"use_tls": true,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": "",
	"logging": {
		"filename": "",
		"level": ""
	}
}

Step No 1: Email Template is below
![Email Template](https://user-images.githubusercontent.com/83810598/117423244-f3032b80-af39-11eb-86ee-cdeb01d7674b.PNG)

Step No : 2 
Landing Page also have Go phish admin page added.

My assuumption is that locally (Laptop) it should work even though i uses local host... Kindly do confirm steps for resolving this issue as i have tried almost every option here.

**Comment by emixam3** [comment]
Hi,
I think your port numbre is wrong. Your admin server is set up on port 3333. But your phishing service, where phishings links and landing pages are set, is on port 80.
So try to change your port in your link.

**Comment by hammi198** [comment]
Thanks.. any Suggested port you want me to change?

**Comment by hammi198** [comment]
tried using 443 but it didnt work either. below is the updated settings for cinfig file

{
	"admin_server": {
		"listen_url": "127.0.0.1:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "gophish_admin.key"
	},
	"phish_server": {
		"listen_url": "0.0.0.0:443",
		"use_tls": true,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": "",
	"logging": {
		"filename": "",
		"level": ""
	}
}

Step No 1: Email template
Hello Hammad,
Please click on below to reset your password

https://localhost:443

FYI - When i change it to localhost : 443 page is not opening at all.

landing page is same as previous one

If possible.. if i get like step wise segregation what to do that would be great :)

**Comment by glennzw** [comment]
In your email body you should put {{.URL}} in place of the absolute URL you have entered.

**Comment by hammi198** [comment]
So it should be something like {{.localhost:443}}?

**Comment by emixam3** [comment]
Nope, just {{.URL}}. It is a variable that GoPhish recognize.

**Comment by glennzw** [comment]
Most likely, change your URL parameter in the campaign creation modal to `http://localhost`:

![Screenshot 2021-05-07 at 12 07 55](https://user-images.githubusercontent.com/3966613/117441186-eaf0bf00-af2c-11eb-8ce2-ba02e4a86695.png)

**Comment by glennzw** [comment]
(assuming that's where your gophish listener is as defined in your `config.json`)

**Comment by hammi198** [comment]
Tried using HTTP but dont get any page when click on the link.. Below are the details of config file along with other..

Conif File:
{
	"admin_server": {
		"listen_url": "127.0.0.1:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "gophish_admin.key"
	},
	"phish_server": {
		"listen_url": "0.0.0.0:80",
		"use_tls": false,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": "",
	"logging": {
		"filename": "",
		"level": ""
	}
}

Email Template:
Hello XYZ,
Please click on below to reset your password
{{.URL}}

Landing Page: Imported site
https://localhost:3333/login

**Comment by hammi198** [comment]
Campaign Model:
![Campaign_Details](https://user-images.githubusercontent.com/83810598/117443956-408b9280-af52-11eb-8558-ddb1434ed8e1.PNG)
Email Link:
Hello Hammad,
Please click on below to reset your password

https://localhost:3333/login?rid=zXqpxmQ

Click on the email:
![Email click](https://user-images.githubusercontent.com/83810598/117444188-8e07ff80-af52-11eb-946c-ee271eda168b.PNG)

**Comment by emixam3** [comment]
In your URL config in the campagne template, just try:
- https://127.0.0.1:80

After this, {{.URL}} should be like this:
- https://127.0.0.1:80?rid=abcdef

The URL must be the same that the listen_url field of the phish_server in your config.json.

Try this and let us know!

**Comment by hammi198** [comment]
Below are more details.. this may help. 

Campaign Creation details:
![Campaign_Details](https://user-images.githubusercontent.com/83810598/117440865-1041f500-af4e-11eb-8c35-ccf50024cd29.PNG)

Config File:
{
	"admin_server": {
		"listen_url": "127.0.0.1:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "gophish_admin.key"
	},
	"phish_server": {
		"listen_url": "0.0.0.0:80",
		"use_tls": false,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": "",
	"logging": {
		"filename": "",
		"level": ""
	}
}

Email Template:
Hello XXXX,
Please click on below to reset your password

{{.URL}}

Landing Page:

**Comment by gurudeep9** [comment]
> Thnaks Team, Finally dashbaord worked by changing giving IP address of the machine instead of localhost.

what did you do ?  faced same issue can u help me out for me also not working dasboard update
