### ISSUE TITLE
GoPhish Dashboard Not Updating "Email Opened" and "Clicked Links" values

### ISSUE THREAD

**Issue by HarisKhan-23** [gophish/gophish#2194]
Hi all,

I'm using GoPhish on localhost:3333 url to setup campaigns.  I'm using these campaigns to send out phishing emails to my own email address for testing purposes. As soon as the email gets sent out from GoPhish, the "Email Sent" counter on the dashboard is updated. 

However, the problem is, when I open my email on the same computer and even click on the link provided in the mail, nothing seems to update on the GoPhish Dashboard. I'm assuming that the "Email Opened" and "Clicked Links" values on the dashboard should be updated. 

While creating the campaign, I'm using my system's public IP address with "https", followed by the port number 83 in the following format:

https://Public_IP_Address_Here:83 

Below is my GoPhish JSON Configuration:

{
	"admin_server": {
		"listen_url": "127.0.0.1:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "gophish_admin.key"
	},
	"phish_server": {
		"listen_url": "0.0.0.0:83",
		"use_tls": false,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": "",
	"logging": {
		"filename": "",
		"level": ""
	}
}

Can someone please assist me in this so I can update my dashboard when emails are opened or clicked? Do I need to specify the URL in a specific format while creating the campaign?

Looking forward to any help. Thanks.

Regards,
Haris

**Comment by glennzw** [comment]
Hi there. Please share your email template and landing page template HTML.

When you say 'nothing happens' - does the landing page load, or you get an error? Please share a screenshot too.

**Comment by glennzw** [comment]
In your email body rather than the actual URL value you have there you need to put the template value `{{.URL}}`. See: https://docs.getgophish.com/user-guide/building-your-first-campaign/creating-the-template for more info.

For a first landing page it's best to use something simple, that has space for credentials:

```html
<html>
<head>
	<title></title>
</head>
<body>
<form action="" method="post" name="form"><label>Username:</label> <input name="username" type="text" /><br />
<label>Password:</label> <input name="password" type="password" /><br />
<input id="login" name="login" type="submit" value="Login" />&nbsp;</form>
</body>
</html>
```

**Comment by HarisKhan-23** [comment]
It's working fine now after I placed this URL template value and used the IPv4 address while setting up campaign. Turns out that I also had to disconnect my VPN in order to update the dashboard. Thanks a lot for the generous help!
