### ISSUE TITLE
GoPhish Deployment on IIS not working

### ISSUE THREAD

**Issue by HarisKhan-23** [gophish/gophish#2197]
Hi Team,

I have successfully tested out GoPhish on my local machine and it works like a charm, and now I want to deploy it on my network's server machine so that it can be accessible to everyone within the organization. I already have a security certificate that I'm using while deploying GoPhish using "Add a website" option in IIS. I'm giving the valid path of the GoPhish folder as well. 

The problem is, when I try to browse it after adding as a website in IIS, it doesn't work. I just get a "This site can't be reached" message on the browser. Can anyone please assist me in deploying GoPhish on IIS server, so that it can be tested out with other users within the same organization as well. Is there a step that I'm possibly missing?

Thanks in advance for the kind assistance.

Kind Regards,
Haris

**Comment by atheriqbal** [comment]
Hi @HarisKhan-23 ,

Is there anything available in your logs? Please share your config.json and logs.
Is the port reachable?

Regards

**Comment by hammi198** [comment]
@atheriqbal where we get these logs?

**Comment by glennzw** [comment]
@hammi198 You'd see the logs when you run the gophish binary - i.e the terminal output.

**Comment by atheriqbal** [comment]
Please check issue #1922. Do you get the same error ?

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen.
