### ISSUE TITLE
How to Test GoPhish on multiple users within same network

### ISSUE THREAD

**Issue by HarisKhan-23** [gophish/gophish#2198]
Hi Team,

We(Me and my team) need to test and run GoPhish within the organization for testing users who are on the same network. For that purpose, we have installed GoPhish on the network server machine. We previously tested GoPhish on a local machine and it worked fine locally. 

However, we don't have a clear idea of how to test it with multiple users on the same network. If we use the IP address of the server machine in the URL section while setting up a campaign, is that supposed to work fine? Or do we need to make any changes to the json config file as well?

Any insights into this will be highly appreciated.

Thanks.

Kind Regards:
Haris

**Comment by atheriqbal** [comment]
Hi @HarisKhan-23 ,
Yes it is supposed to work. You will use the server IP in campaign URL, and make sure its reachable for all the users. 
Use 0.0.0.0 is phishing server listen_url field.

Regards

**Comment by hammi198** [comment]
Hi @atheriqbal. Below is the config file currently we have. Now what would be setting here if let say our server address where we installed Go Phish is 10.X.X.X. Do we need to change anything in Config file? also when setting up the campaign we did gave IP address of the machine on which it is installed and that link is accessible over the VPN profile, link is accesssiable when we are connected over the VPN, gets opened but dahsbaord is not showing anything..

{
	"admin_server": {
		"listen_url": "127.0.0.1:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "gophish_admin.key"
	},
	"phish_server": {
		"listen_url": "0.0.0.0:83",
		"use_tls": false,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": "",
	"logging": {
		"filename": "",
		"level": ""
	}
}

**Comment by glennzw** [comment]
Hi @hammi198 - you don't need to make any changes to your config, your users just need to be able to hit the IP defined in your "phish_server", and you'd supply this IP in the phishing URL parameter when sending the campaign.

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen.
