### ISSUE TITLE
How to use Gophish with a Domain name?

### ISSUE THREAD

**Issue by Korto9** [gophish/gophish#2199]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  0.11.0

Brief description of the issue:  I want to use Gophish with a Domain name to caputure the password and create the landing page.

What are you expecting to see happen? : Creating of Landing page

What are you seeing happen? When I put my domain nothing happens and It just send me to my Domain.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - I putted my domain name
 * Step 2 - Nothing happens

Thank you in advance

**Comment by atheriqbal** [comment]
Hi @Korto9  ,

Please read the answer in issue #578 

Regards

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to re-open if you're still having trouble.
