### ISSUE TITLE
Force new password for new user doesn't work

### ISSUE THREAD

**Issue by emixam3** [gophish/gophish#2200]
**What version of Gophish are you using?:** 0.11.0

**Brief description of the issue:** When create new user, you can force the user to set a new password. But it doesn't work, the new user is not force to change it at first login.

**What are you expecting to see happen? :** At first login, force new user to change the password.

**What are you seeing happen?** First login doesn't ask to change the password.

**Comment by glennzw** [comment]
Are you building from source or the binary? This was an issue I fixed a little while ago, but I need to check if it's included in the binaries yet.

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen.
