### ISSUE TITLE
Howto install GoPhish on a microsoft 365 environment

### ISSUE THREAD

**Issue by Rood365** [gophish/gophish#2201]
Hi,

I have no version downloaded yet, but we like start using the phishing tool for our Microsoft 365 environment.
Please tell me if it is possible and if so where can i find the installation instructions to get this tool to work.

kind regards,
Jan
Netherlands

**Comment by atheriqbal** [comment]
Hi @Rood365 ,
Yes you can use it in Microsoft 365 environment. You will need to ask your exchange team to allow your server IP, and maintain safe sender list (email addresses from which you can send emails). 
Here are installation instructions https://docs.getgophish.com/user-guide/installation 

Hope it answers your question.

**Comment by Rood365** [comment]
Hi,
I read the article and still do need see how I can install GoPhish on a M365 tenant. Is there an App or just run a powershell script?
The installation script you are referring to is complicated and not clear to me.
Kind regards,
Jan

**Comment by atheriqbal** [comment]
Office 365 is your exchange(mail) server. 
One way to go about will be to install gophish on a server. You can install from binaries, or from source, and use Linux or a Windows server. 

Which step is not clear to you in the installation script?

Regards

**Comment by glennzw** [comment]
As usual @atheriqbal is spot on. As we haven't heard back I'm closing this issue out, feel free to reopen if you're still having trouble.
