### ISSUE TITLE
How set up a A record That points to external IP of the gophish server?

### ISSUE THREAD

**Issue by Korto9** [gophish/gophish#2202]
Hi,

I wanted to use my domain name in the url section but i dont know how

Thank in advance

**Comment by atheriqbal** [comment]
Hi @Korto9 , 
You will need to setup an A record that points to the external IP address of the Gophish server.

Regards

**Comment by Korto9** [comment]
How?

**Comment by Korto9** [comment]
How to check the gophisher server external ip? And how to setup a A record

**Comment by atheriqbal** [comment]
Its in config.json file. 
Please search for how to set up A record in Google. You will get many guides. 
@glennzw  please close the issue.

Regards

**Comment by Korto9** [comment]
![image](https://user-images.githubusercontent.com/78448424/118377733-1e6ec180-b59d-11eb-8e1c-d3893b910b66.png)

**Comment by Korto9** [comment]
Where is it I dont see it?

Thank you

**Comment by glennzw** [comment]
@atheriqbal is right, you need to setup records with your DNS provider. e.g with namecheap:

https://www.namecheap.com/support/knowledgebase/article.aspx/319/2237/how-can-i-set-up-an-a-address-record-for-my-domain/

There's nothing really to configure on the gophish side, you just setup the A record with your provider so `yourdomain.com` points to the IP that the gophish server is running on.
