### ISSUE TITLE
Phising URL Changes

### ISSUE THREAD

**Issue by hammi198** [gophish/gophish#2203]
We have installed Go Phish on one of the server. When campaign sends out email to participants links gets opened via (VPN) but dashboard is not getting updated. Do we have to update our config file with server IP (phish server / admin server)? If yes than do we have add port number 80 against that IP? For example 10.X.X.X:80?

"admin_server": {
		"listen_url": "127.0.0.1:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "gophish_admin.key"
	},
	"phish_server": {
		"listen_url": "0.0.0.0:83",
		"use_tls": false,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": "",
	"logging": {
		"filename": "",
		"level": ""
	}
}

**Comment by atheriqbal** [comment]
Hi,

In phishing server -> Listen_url, which is 83 in your case, this should be accessible for all the users who are being sent out the email. 0.0.0.0 is fine. 

Regards

**Comment by glennzw** [comment]
@atheriqbal is spot on here. Closing out as haven't heard back. Feel free to reopen with more info if you're still stuck.
