### ISSUE TITLE
Possible to Customize Homepage of Phishing Server?

### ISSUE THREAD

**Issue by nanoymaster** [gophish/gophish#221]
is there a way to easily customize the homepage?
I think I'm missing something
rather than 404 not found I'm wanting to put a generic 500 Internal Server Error
also being able to add a robots.txt with noindex would be good ;)

**Comment by jordan-wright** [comment]
Hey @nanoymaster - Yep! It's possible, since the code is open-source :smile: 

The easiest way to do it would probably be to change [this line](https://github.com/gophish/gophish/blob/master/controllers/route.go#L156) to say something like:

```
http.Error(w, "Internal Server Error", http.StatusInternalServerError)
```

**Comment by jordan-wright** [comment]
Since changing that line is probably the only way to get this knocked out with our current setup, I'm going to go ahead and close this out for now.

Let me know if you have any questions!

**Comment by nanoymaster** [comment]
I was kinda hoping for a custom error page, people are so used to seeing them that is someone stumbled across my domain they would just think "ahh it's broken" and leave.. could also obfuscate from potential hackers by cloning an IIS 500 error page or something.

hopefully in a future release?
