### ISSUE TITLE
invalid username and password for gophish 

### ISSUE THREAD

**Issue by davidtega01** [gophish/gophish#2210]
![gophi](https://user-images.githubusercontent.com/45460019/119000557-1fc83180-b983-11eb-9a4a-682f1d7d9fe0.JPG)
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: v.11.0

Brief description of the issue: invalid username and password
![gophi](https://user-images.githubusercontent.com/45460019/119000866-6453cd00-b983-11eb-81e0-6ea069013cd5.JPG)

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by atheriqbal** [comment]
Is this the first time you have started the instance? 
 An initial password is randomly generated and printed in the terminal when Gophish is launched for the first time. Check that and use here.

**Comment by codyangell** [comment]
How to I get the output with a windows environment install?

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen with more info if you're still stuck.
