### ISSUE TITLE
Need assistance with gophish

### ISSUE THREAD

**Issue by Fabian783** [gophish/gophish#2212]
Hello there, I have been trying to log into gophish for the first time and it's not letting me through. I use the admin as the username and gophish as the password. Can someone give me feed back of this?

Thank you
Sincerely,
Fabian Buchanan

**Comment by emixam3** [comment]
Hi,
Did you see [this ](https://github.com/gophish/gophish/issues/2210#issuecomment-845639496)?

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen with more info if you're still stuck.
