### ISSUE TITLE
Ubuntu 18.04 AWS - Landing Page and Email Template Endless Loop (0.11.0)

### ISSUE THREAD

**Issue by jstigerwalt** [gophish/gophish#2216]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  0.11.0

Brief description of the issue:  Landing Page and Email Templates are stuck in endless loading loop. Allows me to create a new page but does not allow me to save them. 

Installed using instructions found on Wiki. Ubuntu 18.04 Server AWS.

What are you expecting to see happen? : Version 0.10.0 is working fine for me, just tested I can create pages and templates as normal. I downloaded the binary from the releases this time instead of using go to install. 

What are you seeing happen? 

Landing page and Email templates not working correctly in 0.11.0 version installed with go, I have not tested downloading the binary already compiled.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Install on Ubuntu 18.04 AWS server (Go)
 * Step 2 - Install GCC as required and GoPhish
 * Step 3 - Run Gophish
 * Step 4 - Go to landing page or email template after logging in with admin account. Stuck in loop, will not let me save template or create landing page.

![Landing Pages - Gophish 2021-05-27 12-54-21](https://user-images.githubusercontent.com/29151777/119866836-3a525b80-beeb-11eb-8dbb-e6eb47b92e05.png)

**Comment by glennzw** [comment]
Please could you check the browser console, and also gophish's console log, and paste the results here?

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to re-open if you're still having trouble.
