### ISSUE TITLE
Change 404 page not found Function

### ISSUE THREAD

**Issue by H4xl0r** [gophish/gophish#2217]
What version of Gophish are you using?: 
recent 

Brief description of the issue: 
When running gophish server the main domain returns an 404 page not found when called.
Could someone please point me to the function, i would like to add a static template to distract the visitors.
(show simple html or so )

thanks

**Comment by H4xl0r** [comment]
got it check my changes

**Comment by puzzlewrj** [comment]
> got it check my changes

so where to add this static template?
