### ISSUE TITLE
Attempt to write to a read only database.

### ISSUE THREAD

**Issue by trevormac789** [gophish/gophish#2218]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.11.0

Brief description of the issue: 
When attempting to create a new group fails and gives up error:

"attempt to write a readonly database"

What are you expecting to see happen? :
The Group to be created. 

What are you seeing happen?
Group creation fails.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```html
time="2021-05-27T11:48:55-07:00" level=error msg="record not found"
time="2021-05-27T11:48:55-07:00" level=error msg="attempt to write a readonly database"
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Go to groups in Web UI Click create new group and enter valid information and try to submit.
 * Step 2 - 
 
 I've solved this problem myself but I thought I'd create this ticket as I don't think I saw the solution that worked for me in the other resolved issues.

I created a gophish user that starts the systemd service I created. I chown gophish: from the root directory on down.

The problem was that while gophish.db file had write permissions for the gophish user, Sqlight3 needs the parent folder to have write permissions as well. It was only read and execute. Adding write solved the issue. 

Thank you. You may go ahead and close this and maybe it'll help someone else in the future.

**Comment by glennzw** [comment]
Thanks for sharing your solution, I'm sure others will find it useful.
