### ISSUE TITLE
Few Queries / Suggestions

### ISSUE THREAD

**Issue by faisalmuneer** [gophish/gophish#222]
Hi, I am exploring gophish and checking the possibilities before actually using it in our environment to educate the users. Appreciate if someone can elaborate few questions/suggestions in my mind pertaining to gophish.

1. Export csv IP field is there but it is coming as empty without any value.
2. There is no date/time field in exported csv
3. Whether the email is opened or not is covered in csv. 
4. exported file name should be on the name of the campaign.
5. csv should tell if the user has entered any data on form or not (data itself may not be presented in the csv but only the indication alone).
6. There should be a feature to schedule to campaign to be executed at later stage.
7. There should be a configuration to provide redirected page / training page after user have entered the data.
8. Tracking image is does not get loaded even if you click to load the images.
9. Any information/report on the users who are repeatedly getting phished across all the campaigns would help a lot to focus on them.
10. In future release is there any plan to make the gophish RBAC oriented (at least 2-3 roles) and to integrated with active directory / LDAP.
11. The product guide does not cover how to migrate data to either newer version of gophish copying data from one user to another user. this is when you are creating a user in gophish at a later stage he/she should get all the previous data.
12. Dashboard does not give graph or figure for the ones who have only opened the email. It is only giving hints on successful and unsuccessful.

Regards,
Faisal

**Comment by jordan-wright** [comment]
Wow - a bunch of questions here.

For questions 1-5, have you tried exporting the raw results? It has far more data, and a lot of what you asked for.

For the remaining questions, please be sure to search through existing issues before creating new ones. For example:

6) Covered in #21 
7) Covered in #219 
8) This would be some kind of config issue and would require knowing exactly what you're setup is like to figure out why it's failing
9) This would be a feature request
10) Yes, but this will be an "enterprise version" feature and will not be in the open source version (coming soon!)
11) Not sure what you mean by this? What users? Everything is contained in ```gophish.db```, so backing up gophish, moving it, etc. can be done by moving the database
12) This would be a feature request

**Comment by faisalmuneer** [comment]
Hi, thanks for the immediate response. I have just tried raw events now and found the date/time stamp and few additional details like how many times an email is opened/clicked. For rest of points please see below more details.

1. IP address still could not be found even in the raw events.
4. Exported file names are not matching with the campaign names and a date/time can be appended to distinguished for the latest downloaded results. 
9. Feature request means I will have to post somewhere else or how it will be treated?
10. Enterprise version will have perpetual license? What extra features it will have on top of the community edition?
11. I created a new user but he did not get any data which was created by the user admin. gophish.db is now clear and can be used for migration/upgrades etc.
12. Feature request means I will have to post somewhere else or how it will be treated?

**Comment by faisalmuneer** [comment]
Hi, gophish.exe keep running in a DOS window in a verbose mode. Wondering if there could be an option to run it in the background as a service?

**Comment by jordan-wright** [comment]
Hey @faisalmuneer. A feature request is the same thing as an issue. Typically, we try to keep issues small and self-contained so they are easy to address and track. Large lists of questions like this are difficult to keep up with and things can fall through the cracks.

I'll answer the newest questions, but I'm also going to close out this issue. If there are questions that aren't answered, **definitely** let us know but please do so by creating separate issues. This will help us keep track of everything.

1) This would require a separate issue - it sounds like a bug.
2) This would require a separate issue - it sounds like a bug.
3) Feature requests are the same things as issues.
4) Yes, we are still working out the details, but enterprise licenses will be priced per year.
5) For now, there is no ability to share objects between users
6) See 3)

As far as running as a service, I've heard of people trying to use ```sc``` to do this. If that doesn't work, you can try [nssm](http://nssm.cc/)
