### ISSUE TITLE
Having some problems to send emails from a GMAIL Address

### ISSUE THREAD

**Issue by mar49raa** [gophish/gophish#2222]
What version of Gophish are you using?: 
v 0.11.0

Brief description of the issue: 
I am currently doing Gophish campaigns and everything is working well about the different pages, the admin page and the listener...
The problem is that I am using Gmail addresses to reach the victims. At the beginning, there was not any problems because the campaigns were not touching a lot of people.
Now, 2 problems are happening with the different Gmail adresses I am using :
- My emails are blocked directly from Gmail, with this message : "The text or the links seems suspects".
- After sending few emails, I receive this error message : "You have reached the sending limit", and with more researches I saw this :
![image](https://user-images.githubusercontent.com/85104069/120173101-fc637900-c203-11eb-8b8b-8f463eedf1fe.png)

What are you expecting? :
At first, I want to know if some of you already had this kind of problem and how you deal with it. I want to know if there is any solution to keep these google addresses for my campaigns.

To continue, I would like some advices about what types of addresses you are using for your own campaigns ? As I am using Gophish to sensitize people, using a Gmail address is a good way to add a clue for the victims to see the fraudulent email.

Thanks guys !

**Comment by mar49raa** [comment]
Ok I come back to give more infos about the problem.
I found this issue, (https://github.com/gophish/gophish/issues/788), so the objective would be to get the email address we use into the whitelist of the SMTP server of our victims. I will try this and see if it works.

**Comment by atheriqbal** [comment]
Did it work? Let me know if there are any issues

**Comment by glennzw** [comment]
It's quite tricky using GMail, as Google will always try to block what they see as spam. The best solution is to run your own mailserver.

This tutorial worked pretty well for me: https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-postfix-as-a-send-only-smtp-server-on-ubuntu-16-04
