### ISSUE TITLE
Unable to run GoPhish on MacOS

### ISSUE THREAD

**Issue by PatternedClothing** [gophish/gophish#2223]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: v0.11.0

Brief description of the issue: The terminal does not recognise ./gophish as a command. 

So I'm pretty new to this entire scene? And I've been trying to launch GoPhish but it seems I keep getting stuck. I haven't used the terminal on Mac before either so understanding the commands is pretty daunting. I downloaded the latest version through the website and tried following the instructions at - https://www.techrepublic.com/article/how-to-run-a-phishing-attack-simulation-with-gophish/ - moving the entire folder into a directory called gophish, and altering the code on config.json, but as soon as I get to the 'sudo ./gophish' the error 'command not found' pops up. 

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - mkdir gophish 
 * Step 2 - mv gophish-v0-4 gophish 
 * Step 3 - cd gophish 
 * Step 4 - chmod u+x gophish 
 * Step 5 - sudo ./gophish 
Output - " ./gophish: command not found"

**Comment by mitprasoon** [comment]
Can you confirm if you are using the correct binary for MacOS?
Can you run "file ./gophish" and check if it is from MacOS

**Comment by moivica** [comment]
I have the same issue - version v 0.11.0 

File: [gophish-v0.11.0-osx-64bit.zip ](https://github.com/gophish/gophish/releases/download/v0.11.0/gophish-v0.11.0-osx-64bit.zip)

After installation, command not found message is shown. 

@mitprasoon  - here is file info

```
MacBook-Pro:~/Desktop/gophish$ file ./gophish
./gophish: Mach-O 64-bit executable x86_64
```

Let me know if u need anything else.

**Comment by glennzw** [comment]
One thing to look out for is to check your `System Preferences` > `Security & Privacy` to make sure you've allowed the gophish binary to run. The first time I try run it I get the popup:

<img width="254" alt="a" src="https://user-images.githubusercontent.com/3966613/122676748-41f9dd00-d1d7-11eb-9aed-e775ec7b91af.png">

Allowing this in `Security & Privacy:

<img width="669" alt="b" src="https://user-images.githubusercontent.com/3966613/122676766-5938ca80-d1d7-11eb-9900-1c6def28b7e7.png">

..results in:

<img width="258" alt="c" src="https://user-images.githubusercontent.com/3966613/122676788-7077b800-d1d7-11eb-94e0-51c581c133a1.png">

Selecting 'Open' here and the binary runs:

```bash
gophish-v0.11.0-osx-64bit  ./gophish
time="2021-06-20T14:43:02+01:00" level=warning msg="No contact address has been configured."
time="2021-06-20T14:43:02+01:00" level=warning msg="Please consider adding a contact_address entry in your config.json"
goose: migrating db environment 'production', current version: 0, target: 20200730000000
OK    20160118194630_init.sql
OK    20160131153104_0.1.2_add_event_details.sql
.........
```

If this doesn't work please record the screen output you're seeing, or take some screenshots.

**Comment by PatternedClothing** [comment]
Hi @glennzw! 
I started the whole process from scratch and followed your instructions. However, when I got to the 'Open' bit, a text file was displayed instead of the binary running. 

<img width="1191" alt="Screenshot 2021-06-23 at 6 49 07 pm" src="https://user-images.githubusercontent.com/85125404/123121972-ab3b5380-d456-11eb-9e13-56a66080234b.png">

I'm not sure how to proceed from here? 
Thank you for replying!

**Comment by PatternedClothing** [comment]
Thanks for replying @mitprasoon! I'm fairly certain I downloaded the correct binary for MacOS. However when I ran "file ./gophish", the error "./gophish: cannot open `./gophish' (No such file or directory)" was displayed onto terminal.

**Comment by moivica** [comment]
Hi guys, 

It seems that this is a problem with permissions . 
Although i gave permission to app in security preferences (`run anyway button`), i could only read and write to file. Could not execute it. 
Just set  `chmod 766 gophish` in your gophish folder  and try to run app . 
It should work

**Comment by PatternedClothing** [comment]
Hi @moivica! 
I attempted to set the folder to the command you suggested, and ran the app. A window opened with what looks like another error... 

<img width="658" alt="Screenshot 2021-06-24 at 1 54 20 pm" src="https://user-images.githubusercontent.com/85125404/123294318-c9bc5000-d525-11eb-8d53-aedc79144de4.png">

Thank you for replying!

**Comment by glennzw** [comment]
@PatternedClothing Could you share more of that screenshot the full console output, including the command you ran). Also run the command 'ls -lh' so we can see the files and permissions.

**Comment by russtic** [comment]
Same issue
![image](https://user-images.githubusercontent.com/86748257/124036036-4bfcb680-d9f5-11eb-8094-f0b1bf9aa3da.png)

**Comment by glennzw** [comment]
@russtic try running it from inside the gophish directory

**Comment by russtic** [comment]
glennzw. I am. I have also tried renaming folder to no avail. Is there an issue with Big Sur? 
![image](https://user-images.githubusercontent.com/86748257/124074833-f697c800-da3b-11eb-8a17-9a7d4e1cd975.png)

**Comment by glennzw** [comment]
@russtic You're in your home directory (/home/russtic). Type 'pwd' to see your current working directory.

Type 'cd gophish' to enter the gophish directory, and then './gophish' to run the binary.

You're getting that error because gophish can't find the VERSION file, because it's looking in your home directory.

**Comment by PatternedClothing** [comment]
I was a little confused as to how I'm supposed to open the gophish directory since 'cd gophish' resulted in an error message, but opened a terminal file at the folder (as shown below). 

<img width="558" alt="Screenshot 2021-07-09 at 12 29 35 pm" src="https://user-images.githubusercontent.com/85125404/125048783-554ee880-e0b1-11eb-8625-d688390af728.png">

I ran './gophish' at the terminal window that opened and it worked! 
Thank you @glennzw for your help (and your patience). 

@russtic, I hope this helps you too!

**Comment by glennzw** [comment]
No worries @PatternedClothing, I'm glad it worked!

**Comment by topp07** [comment]
hello, i need help and assistance installing gophish on my macOS Big Sur

**Comment by topp07** [comment]
@glennzw need your help and guide to install gophish pls

**Comment by glennzw** [comment]
Please open a new issue and give a lot more info on what you've tried so far

**Comment by wlwilson82** [comment]
IT JUST DOES NOT WORK ON MY MAC. BOTH IMAC AND MACBOOK PRO

**Comment by MicheleCus** [comment]
Thanks moivica this works fine https://github.com/gophish/gophish/issues/2223#issuecomment-867401212
Using macbook pro M1

**Comment by hoangquandn97** [comment]
Hey all, I found the solution, I'm running Gophish v0.12.1 (the latest version at the time of writing) on my Macbook Air M2 and I couldn't run the binary file gophish after adding the execute permission and run it as a normal user:
Step 1: Extract the zip file downloaded from this site [Gophish download link](https://github.com/gophish/gophish/releases/)
Step 2: cd [gophish folder]
Step 3: Run "sudo chmod +x gophish" to assign execute permission
Step 4: Now, run gophish as a normal user without sudo "./gophish". Not sure why it didn't work with the sudo perm.
Step 5: Go to https://127.0.0.1:3333/, and voila

Note: In MacOS, it will prevent you from running the binary file, it that is the case, then:
Step 1: Go to Settings -> Privacy and Security -> Security session -> Allow "gophish" file to be run.
![Screenshot 2024-07-27 at 12 23 43 PM](https://github.com/user-attachments/assets/031137ff-eb41-4c43-8eaf-3b7f12d04ff5)
I circled where you should see it in the screenshot. You won't see it in my picture because I already allowed the file to be run.
Step 2: After all this, run "./gophish" again. Should be good to go!!
