### ISSUE TITLE
Dropbox Landing Page Import Issues

### ISSUE THREAD

**Issue by kwriley87** [gophish/gophish#2224]
What version of Gophish are you using?: 
0.11.0

Brief description of the issue: 
When importing a landing page using https://www.dropbox.com/login, the page itself looks fine but when you attempt to enter credentials, the following error is presented and the information is not captured in the go phish campaign and categorized as "submitted data" as it should be.

https://pasteboard.co/K4KDx1m.png

What are you expecting to see happen? :
Not to see this error and the attempt to submit information included in the campaign results.

What are you seeing happen?
See above.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

http://38.135.50.24/?rid=nsHUnqE

Please provide any terminal output that may be relevant below:

N/A

Please provide as many steps as you can to reproduce the problem:
Step 1: Create landing page
Step 2: Import Dropbox signin page.
Step 3: Create campaign and tie it to the created landing page.
Step 4: Run the campaign as a test to myself.

**Comment by atheriqbal** [comment]
Hi,
Did you manage to resolve the issue?

**Comment by kwriley87** [comment]
I have not, unfortunately.

**Comment by atheriqbal** [comment]
Okay I will try to reproduce on your version and get back to you.

**Comment by kwriley87** [comment]
Thank you -- let me know what you find.

**Comment by glennzw** [comment]
This is a tricky one as it's more of a webdev question than a gophish one. When replicating real services it's always useful to update the form code to be as simple as possible, and remove all javascript validation that might get in the way. I'd recommend trying to simplify the Dropbox post form to something along the lines of:

```html
<html>
<head>
	<title></title>
</head>
<body>
<form action="" method="post" name="form"><label>Username:</label> <input name="username" type="text" /><br />
<label>Password:</label> <input name="password" type="password" /><br />
<input id="login" name="login" type="submit" value="Login" />&nbsp;</form>
</body>
</html>
```

I don't have the spare cycles to dig through the messy dropbox code myself, but hopefull this gets you in the right direction

**Comment by atheriqbal** [comment]
Are you getting submitted results with a simple login page as suggested above? or any other simple page? Dont use dropbox for now. Check the functionaliy if its working or not. 
If its working on a simple form, it should on any other form with some tweaking in the HTML/JS code.

**Comment by glennzw** [comment]
Closing out as haven't heard back.

**Comment by Zaibali9999** [comment]
cross origin restriction
You need to remove validation and URL where form is trying to submit, Action attribute should be empty or remove from form tag

**Comment by Zaibali9999** [comment]
You can see error on console tab by click inspect element
