### ISSUE TITLE
Display of Google Chrome version different within one click

### ISSUE THREAD

**Issue by bassers** [gophish/gophish#2225]
What version of Gophish are you using?: 0.11.0

Brief description of the issue: Display of version of Google Chrome is different within same click. What is the correct one?

What are you expecting to see happen? : Only one version to be displayed.

What are you seeing happen? : Whitin one click different version of Google Chrome are displayed.

<img width="605" alt="chromem" src="https://user-images.githubusercontent.com/85297978/120657820-21b2ea00-c485-11eb-8ce4-ec2061696416.png">

**Comment by atheriqbal** [comment]
What is your Infrastructure? Is it an Enterprise environment where firewalls/Scanning engines may be checking emails for malicious links?

**Comment by bassers** [comment]
Microsoft 365, the link in the phishingmails is not checked by save link controls etc.
There is a firewall in place that checks https, but not expected to do something with useragents.
The scanning engines have whitelisting for this campaign.
Clients receive the mail on the device. Not in a Citrix or RDP like environment. 

It only occurs with Chrome.

**Comment by glennzw** [comment]
Very interesting. I'd agree with @atheriqbal that it's possibly some application inspecting URLs. You could check the IP addresses in the database, to see which one likely matches your client IP space (or one that's owned by Microsoft or some other AV vendor).

**Comment by atheriqbal** [comment]
This happens with me as well. We have Microsoft Exchange 365 environment with ATP services. Mostly the IPs are from Microsoft. I guess this is sandboxing from Microsoft, checking links. We opened a ticket with them, but they simply replied "we don't cater for third party services". Some emails go through properly, some have this problem. 

Somewhere @glennzw  you wsggested to make a rule in Exchange. That did not help either.

**Comment by glennzw** [comment]
@atheriqbal I saw this article recently:

https://m365admin.handsontek.net/microsoft-defender-for-office-365-introducing-advanced-delivery-for-phishing-simulations-and-secops-mailboxes/

_"We are introducing a new capability, Advanced Delivery, for the configuration of third-party phishing simulation campaigns and delivery of messages to security operations (SecOps) mailboxes"_

I haven't looked too deeply into how it all works, but I'd be interested to know if it helps in your environment?

**Comment by atheriqbal** [comment]
Hi,
Thanks for sharing. I have forwarded the link to relevant team. Defender service is different from ATP or not, I am not sure about it. Our Admins will answer for this, which I will share here with you. 
Also, just a personal opinion, the fact that Microsoft had to roll out this feature for third party softwares indicates this is an issue (not really an issue, but their flow does blocks some emails)  and maybe other clients had reported this too. Just perosnal opinion. 

Ill share any results I have here. Also, if @jordan-wright  can weigh in on this, it would be really helpful.
