### ISSUE TITLE
[QUESTION] Is it possible to setup DKIM on the server ?

### ISSUE THREAD

**Issue by Darktortue** [gophish/gophish#2226]
Hi,

I'd like to know if it is possible to setup DKIM with gopish. In order to bypass spam filter without whitelisting the ip address, it would be great to have a working DKIM.

**Comment by ehotdc** [comment]
DKIM is not really the responsibility of Gophish, but more the responsibility of the mailserver gophish is utilizing.

**Comment by Darktortue** [comment]
Yes I know that Gophish won't setup DKIM. Let me ask you my question differently.
I've been reading the documentation but it seems I can't find the part about the mailserver configuration. Did I miss it ?

**Comment by edermi** [comment]
No, this is something you have to configure in your mail server. Therefore, it is probably documented in your mailserver's documentation and unrelated to Gophish.

**Comment by thiagolmoraes** [comment]
actually, the libary used by Gophish provide no support for DKIM signing, maybe the alternative is to use DKIM-PROXY
