### ISSUE TITLE
Feature request: Ability to check captured password against HaveIbeenpwned's "pwned passwords"

### ISSUE THREAD

**Issue by Steltek** [gophish/gophish#2228]
This might be a bit too far off the "core business" of Gophish, but it would be nice if one could have submitted passwords checked against HaveIbeenpwned's "pwned password" database using their API. One would obviously have to designate a specific field name as the one containing the password, and then there could either be a manual operation like a "Check against HaveIbeenpwned" button, or even an automatic check that displays the result in the event. (e.g. Submitted data / OS / Browser / Found in HaveIbeenpwned: Yes/No)

**Comment by glennzw** [comment]
Great idea! I'm biased, because I've already implemented a solution to do this ;-)

https://github.com/glennzw/BreachCount


![pwnd](https://user-images.githubusercontent.com/3966613/122431847-b725a200-cf8c-11eb-91d4-41ff6bdf42ed.jpeg)

**Comment by mplattner** [comment]
This is a super-cool and useful script, thanks @glennzw! 🙌
