### ISSUE TITLE
gophish not sending test mail.

### ISSUE THREAD

**Issue by intelligentzombie1** [gophish/gophish#2229]
I'm trying to send a test email with gophish, after inputting every thing right, I keep getting the error.... Max connection attempts exceeded - 534 5.7.9 Application-specific password required. Learn more at 5.7.9 https://support.google.com/mail/?p=InvalidSecondFactor t11sm9819028qta.8 - gs
![Screenshot (22)](https://user-images.githubusercontent.com/50877510/121116075-f9f4b680-c7e3-11eb-92eb-cc2bde7dc227.png)
mtp. what could be the cause.

**Comment by alejandroiam** [comment]
you need to make an app password to send email with Google's smtp. See here [https://support.google.com/accounts/answer/185833?hl=en](https://support.google.com/accounts/answer/185833?hl=en)

**Comment by glennzw** [comment]
Yup @alejandroiam is correct. Check out that link and you should be fine. Feel free to re-open if you're still stuck.

**Comment by shimmy1981** [comment]
I created an app password and I'm still getting that error message. Are there any settings in gmail I need to change?
