### ISSUE TITLE
New feature : limit access to landing pages with IP addresses

### ISSUE THREAD

**Issue by emixam3** [gophish/gophish#2231]
**What version of Gophish are you using?:** 0.11.0

**Brief description of the new feature:** Limit side effects of transfer phishing emails to someone who is not target by a campaign.

**What are you expecting to see happen? :** If user A, in the users list targeted by a campaign, transfer an email to user B who is not targeted, nothing happened. User B cannot clic on the link in the email, because its IP address in not in the scope.

Seems like the htaccess files in web servers.

**Comment by edermi** [comment]
How is this supposed to work technically? You won't know the IP of your target, and if somebody forwards the E-Mail, there's nothing you can do to prevent the recipient clicking the link.

**Comment by emixam3** [comment]
> 
> 
> How is this supposed to work technically? You won't know the IP of your target, and if somebody forwards the E-Mail, there's nothing you can do to prevent the recipient clicking the link.

In a entreprise netword, you can get targets IPs. You can only target one office for example. But you don't want that someone in an other office can clic on your link. The goal is to limit side effects of a phishing campaign.

**Comment by edermi** [comment]
Well, letting the IP issue aside, there is no way to restrict who **clicks** the link. The best thing you could do is serving the phishing page only to your targets while visitors having a different IP get to see something else. 
You can configure this in your reverse proxy if you're using one (which I highly recommend).

**Comment by glennzw** [comment]
Gophish isn't really concerned with underlying networking, and I don't think it'd be a good place to implement these types of rules. It'd be best to enforce IP geo restriction using a proxy (nginx, Caddy, etc) or even firewall rules.
