### ISSUE TITLE
E mail Open Does Not show up in DashBoard

### ISSUE THREAD

**Issue by Biswadeep89** [gophish/gophish#2232]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
V 0.10.1
Brief description of the issue: 
I Can send mail to User but i am not getting how many mails are opened by the user . I am using the trackers as per the example in the Gophish document ,but i dont understand what is going wrong .

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:
<html>
<head>
	<title></title>
</head>
<body>
<p>&nbsp;</p>

<p>Hey You Can Check your password Linke here <a href="http://{{.URL}}">LInk </a></p>

<p>&nbsp;</p>

<p>&nbsp;</p>
</body>
</html>

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by atheriqbal** [comment]
Hi, can you copy paste the email template here?
Also, is the server accessible for the users? What are listen_url values in config.json?

**Comment by Biswadeep89** [comment]
Thank you for your response. I figured out the phising server listening port is not opened by Oracle cloud firewall thats why errors are coming. Now issue has been fixed and site is working fine.
