### ISSUE TITLE
Unable to access 

### ISSUE THREAD

**Issue by BDK97** [gophish/gophish#2234]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.4

Brief description of the issue: I can't access [https://127.0.0.1:3333](https://127.0.0.1:3333)

What are you expecting to see happen? : Have access of [https://127.0.0.1:3333](https://127.0.0.1:3333)

What are you seeing happen? Terminal says that the address is already in use  

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

Please provide any terminal output that may be relevant below:

```
bdk97@kali:~/Desktop/gophish$ ./gophish
2021/03/04 14:26:25 worker.go:37: Background Worker Started Successfully - Waiting for Campaigns
goose: no migrations to run. current version: 20170827141312
2021/03/04 14:26:26 gophish.go:87: Starting admin server at https://127.0.0.1:3333
2021/03/04 14:26:26 gophish.go:104: Starting phishing server at http://0.0.0.0:3333
2021/03/04 14:26:27 gophish.go:89: listen tcp 127.0.0.1:3333: bind: address already in use
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 -  Modify config.json
 * Step 2 - Try to have access to [https://127.0.0.1:3333](https://127.0.0.1:3333)

**Comment by glennzw** [comment]
The 'already in use' error means that another process is already listening on port 3333. You might have another instance of gophish running. You can run this command to see what's on that port:

```
netstat -ltnp | grep -w ':3333'
```
