### ISSUE TITLE
Certbot cannot be installed.

### ISSUE THREAD

**Issue by h1khak** [gophish/gophish#2235]
What version of Gophish are you using?: 
0.11.0

Brief description of the issue: 

when downloading certbot, and trying to run, an error is returned saying that the system does not support it.
I would like to know if there is any other option that might be effective to implement the SSL certificate in the gophish system

What are you expecting to see happen? :
complete installation

Skipping bootstrap because certbot-auto is deprecated on this system.
Your system is not supported by certbot-auto anymore.
Certbot cannot be installed.
Please visit https://certbot.eff.org/ to check for other alternatives.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

Skipping bootstrap because certbot-auto is deprecated on this system.
Your system is not supported by certbot-auto anymore.
Certbot cannot be installed.
Please visit https://certbot.eff.org/ to check for other alternatives.

```

**Comment by glennzw** [comment]
Tricky one to answer as it's not a gophish issue. What O/S and version are you using? Have you tried any alternatives via https://certbot.eff.org/ ?

**Comment by h1khak** [comment]
@glennzw 

[root@az-gophish-01 ~]$ uname -a
Linux az-gophish-01 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[root@az-gophish-01 ~]$ cat /etc/issue
\S
Kernel \r on an \m

in my work here, the guy who used this machine for gophish ended up leaving, without finishing the installation of it... now i'm a little lost about it... ;s

**Comment by glennzw** [comment]
Oh, bad luck being dropped in like that.

It's hard to tell from that output what the OS is. Any chance of starting again from a new machine? Ubuntu would be good.

**Comment by h1khak** [comment]
@glennzw 

I managed to discover the OS

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by glennzw** [comment]
Phew, so that's going to be a CentOS + certbot issue, and unfortunately outside the support for gophish. I'd recommend asking on the CentOS forums or IRC.
