### ISSUE TITLE
Attachment Open  Tracking

### ISSUE THREAD

**Issue by lcristovam** [gophish/gophish#2239]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue:
 **Track clicks on Attachments**

What are you expecting to see happen? :

**That Gophish shows if a user has opened an attachment on a email phishing**

What are you seeing happen?

**The Gophish Dashboard dont have this indicator, the near of this is  the"clicked link".  But, the system have the option to attach files on email templates. So, why dont create an same type indicator on Gophish Dashboard?** 

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - **Attached Files .XLSX .DOCX .PDF and launched campaigns**
 * Step 2 - **All Documents have been opened**
 * Step 3 - **Viewed that the Gophish Dashboard only reports that the email was opened.** 
 
![image](https://user-images.githubusercontent.com/66442285/122584107-551e7880-d030-11eb-88ba-ed6849d80c37.png)

**Comment by glennzw** [comment]
Thanks for the suggestion. This is a new feature that I'm going to get out Real Soon Now. See: https://github.com/gophish/gophish/pull/1936
