### ISSUE TITLE
mysql database - gophish not run

### ISSUE THREAD

**Issue by Micke2007** [gophish/gophish#2240]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
Gophish v0.11.0
Brief description of the issue: 
try to connect to mysql local database on xampp windows 10
What are you expecting to see happen? :
run gophish and create database
What are you seeing happen?
gophish not run, have the error
time="2021-06-18T20:37:55-03:00" level=warning msg="No contact address has been configured."
time="2021-06-18T20:37:55-03:00" level=warning msg="Please consider adding a contact_address entry in your config.json"
time="2021-06-18T20:37:55-03:00" level=error msg="no valid version found"
time="2021-06-18T20:37:55-03:00" level=fatal msg="no valid version found"

**Comment by glennzw** [comment]
Hi @Micke2007, sorry you're having trouble. Please could you share your `config.json` file. Does gophish run OK if you use the default sqlite database (just so we know it'd definitely a database problem)?

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to re-open if you're still having trouble.
