### ISSUE TITLE
Gophish not reporting email opened, but it only reports email opened and link clicked when the user clicks on the link. *It now works against protonmail users, not gmail users

### ISSUE THREAD

**Issue by jotunel** [gophish/gophish#2241]
What version of Gophish are you using?: latest (v 0.0.11)

I est the GoPhish application on my local end. Thus, URL in the new campaign tab is set to: http://127.0.0.1.

Some more info on my end:
```
time="2021-06-21T23:29:03+03:00" level=info msg="Starting admin server at https://127.0.0.1:3333"

time="2021-06-21T23:29:03+03:00" level=info msg="Starting phishing server at http://0.0.0.0:80"
```
-gmail account: Always display external images: On

Brief description of the issue: 
Regarding protonmail recipients: Works like a charm!
Regarding gmail recipients: Gophish not reporting email opened when it's about a gmail account, but it only reports email opened and link clicked when the user clicks on the link. In other words, if the user just opens the e-mail, nothing happens. If the user opens the e-mail and clicks on the link, then the email opened and link clicked both go up.

What are you expecting to see happen? : I expect the email opened counter go up +1, when a user just opens an email without clicking the link.

What are you seeing happen? Re: gmail accounts: Gophish only reports email opened and link clicked when the user clicks on the link. In other words, if the user just opens the e-mail, nothing happens. If the user opens the e-mail and clicks on the link, then the email opened and link clicked both go up.

![UsersReadTheEmailNotClickedOnTheLink](https://user-images.githubusercontent.com/86265268/122824014-bc665200-d2e8-11eb-9822-652b1e8816bc.png)
In the above case, both users read the phishing email but they never clicked on the link.

![UsersReadTheEmailsAndOpenedTheLinks](https://user-images.githubusercontent.com/86265268/122824049-cb4d0480-d2e8-11eb-866a-e1d97e93008f.png)
In the above case, both users read the phishing email and then they clicked on the link.

![Timeline](https://user-images.githubusercontent.com/86265268/122824207-051e0b00-d2e9-11eb-809e-652e5eaa4843.png)
As you can see in the above picture, the email opened is not even on the timeline.

![ItWorksOnProton](https://user-images.githubusercontent.com/86265268/122833114-0fde9d00-d2f5-11eb-9ab0-98a87211c194.png)
![ProtonWorks2](https://user-images.githubusercontent.com/86265268/122833310-6a77f900-d2f5-11eb-9c77-8cd93f742522.png)

Development: As you can see in the above picture(s) **it** **does** **work** on a user that is on **protonmail**. **Not working on gmail** though. What's been happening? 

Email Template:
```
<html>
<head>
	<title></title>
</head>
<body>
<p style="margin-left:13.5pt;">Hello {{.FirstName}},</p>

<p style="margin-left:13.5pt;">Your credit card credentials are in danger! &nbsp;</p>

<p style="margin-left:13.5pt;">Click <a href="{{.URL}}">HERE</a> and sign in to view details.</p>

<p style="margin-left:13.5pt;">&nbsp;</p>

<p style="margin-left:13.5pt;">Regards.</p>

<p style="margin-left:13.5pt;">&nbsp;</p>

<p style="margin-left:13.5pt;">CONFIDENTIALITY NOTICE:&nbsp; This e-mail and any transmitted files are private and confidential and are solely for the use of the recipient(s)&nbsp;to whom it is addressed.&nbsp; Any unauthorized review, use, disclosure, distribution or copying of this communication is strictly forbidden.&nbsp; If you have received this communication in error, please delete and immediately notify the sender via the e-mail return address.&nbsp; Thank you for your compliance.</p>

<p style="margin-left:13.5pt;">Please consider the environment before printing this e-mail.</p>

<p style="margin-left:13.5pt;">&nbsp;</p>

{{.Tracker}}

</body>
</html>
```
Is the `{{.Tracker}}` being used in a correct fashion?

config.json file:
```
{
	"admin_server": {
		"listen_url": "127.0.0.1:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "gophish_admin.key"
	},
	"phish_server": {
		"listen_url": "0.0.0.0:80",
		"use_tls": false,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": "",
	"logging": {
		"filename": "",
		"level": ""
	}
}
```
Development no.2 : When I click on http://127.0.0.1/track?rid=TAQKZtE, a black screen loads and then it counts the e-mail as opened. Also, see the image on below from the log output:
![200](https://user-images.githubusercontent.com/86265268/122838458-cd21c280-d2fe-11eb-93ba-182baa89f4b4.png)

What can we make off of this? Is this gmail's fault? Did anybody else solve this issue somehow about gmail recipients?

PS: I would appreciate any help, as I have a certain timeline for my company's needs to raise their security awareness. Thank you all people!

**Comment by glennzw** [comment]
GMail is likely blocking the remote loading of images (so the tracking pixel to see that an email has been 'read' doesn't load).

It's also likely scanning the URLs, which is why the links show up as clicked.

You can't do much about GMail not loading images, unless you can push some kind of group policy to remote load images. As for GMail scanning the URLs - you could block the IPs that are doing it, or allow-list your company IPs.

**Comment by glennzw** [comment]
Another solution I've used is to build out a 'proxy' landing page, that is Javascript dependent. If GMail isn't rendering Javascript when scanning the URL, this 'hack' could work: https://github.com/gophish/gophish/issues/1559#issuecomment-526602895

It's a little tricky though.

**Comment by jotunel** [comment]
Thank you a lot for your answers. That was what I was thinking, also. I just wanted to leave this here for future reference in case if others stumble upon this.
