### ISSUE TITLE
Doesn't start in Kali Linux

### ISSUE THREAD

**Issue by Strannik74** [gophish/gophish#2243]
Hello!
Downloaded binary won't start on Kali Linux
chmod +x gophish granted rights
![Снимок экрана от 2021-06-22 13-30-08](https://user-images.githubusercontent.com/31668854/122892209-a3988380-d35e-11eb-9a3b-35d69bb00dbd.png)
![Снимок экрана от 2021-06-22 13-31-27](https://user-images.githubusercontent.com/31668854/122892260-ac895500-d35e-11eb-833d-9b08cabcdcd5.png)

**Comment by glennzw** [comment]
You already have a webserver running on port 80 - see the last message in the output "0.0.0.0:80: bind: address already in use"

**Comment by Strannik74** [comment]
Thank you
On port 80, apache2 was running.
