### ISSUE TITLE
SSL Certificate Details

### ISSUE THREAD

**Issue by hammi198** [gophish/gophish#2244]
I got my SSL certificate from go daddy and now want to import that in go phish config file but not sure HOW i can do that..  

Lets assume my SSL Certificate is xyz.com, where i would have to copy that? should changing xyz.com.crt would work?or something else is to be done in go phsih web server

{
	"admin_server": {
		"listen_url": "127.0.0.1:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "gophish_admin.key"
	},
	"phish_server": {
		"listen_url": "10.90.10.154:443",
		"use_tls": true,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": "",
	"logging": {
		"filename": "",
		"level": ""
	}
}

**Comment by glennzw** [comment]
You need to replace example.crt and example.key in the above config.json file with your GoDaddy certs. The name of the file doesn't matter.

**Comment by hammi198** [comment]
Thanks Glennzw that was helpful. I am using window version of Go phish. so in order to do that do i have to create the file in the folder name let say xyz, put certificate details in it and than provide the name there? or i only have to provide the name of the certificate and Go phish will automatically going to pull this from the server?

**Comment by glennzw** [comment]
You need to place your .crt and .key files in the gophish directory. You'll see the gophish_admin.crt and gophish_admin.key files are already there for the admin console.

**Comment by hammi198** [comment]
Thanks.. just to be sure so will create two files in the directory and simple provide the name in config file right?
![Go Phish](https://user-images.githubusercontent.com/83810598/123088039-41d62900-d3f3-11eb-9280-e2788f0659e5.PNG)

**Comment by hammi198** [comment]
Thanks Glennzw it seems to be working fine now :)
