### ISSUE TITLE
How to send an email from Gophish using a custom domain & a private email

### ISSUE THREAD

**Issue by jotunel** [gophish/gophish#2248]
What version of Gophish are you using?: Latest 

Brief description of the issue:  Emails not being able to be sent out, with me using a custon domain and a private email. I have managed to get things done with me having a gmail account, but now I want to use my own email from a custom domain I bought to sent out mass emails to all employees at the company I am working on, so that we can raise their security awareness.
At New Sending profile, lies the error. I do know know of the proper STMP host I guess? I am using Namecheap and privateeemail so there is that. 
I am trying the following:
From: email@domain.shop
Host: mail.privateemail.com (or) smtp.privateemail.com
Username: email@domain.shop
password: The password of this email
Message not able to be sent.

Namecheap instructed me to use the following ones:
SMTP Host - mail.privateemail.com (or) smtp.privateemail.com;
Encryption - TLS or SSL;
SMTP Port - 465 (SSL) or 587 (TLS);
Authentication - On;
SMTP Username - full email address;
SMTP Password - password for that email address.

What are you expecting to see happen? : The email to be sent out successfully.

What are you seeing happen?  " Max connection attempts exceeded - dial tcp X.X.X.X:25: connectex: An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by atheriqbal** [comment]
Hi, have you managed to resolve the issue? If yes, please close it.

**Comment by jotunel** [comment]
Didn't solve the issue.
Used the gmail SMPT.
If someone else feels like having a better answer and/or reopening the question, they are welcome to do so.

**Comment by AbdulRafayShaikh** [comment]
@jotunel Hey buddy, I'm also using a NameCheap domain but due to an issue, it never loads the the landing page template when i click at it through the email template that i receive (test email), Kindly help me if read this message. Would he appreciated.

**Comment by sdinonno** [comment]
> 

@AbdulRafayShaikh have you checked the configs for your phish_server? and is the campaign still active?

**Comment by AbdulRafayShaikh** [comment]
> > 
> 
> @AbdulRafayShaikh have you checked the configs for your phish_server? and is the campaign still active?

Yes, Plus i have also enabled the tls: true

You can check more details here on my issue thread: https://github.com/gophish/gophish/issues/2909
