### ISSUE TITLE
GoPhish user campaign results not visible through admin user

### ISSUE THREAD

**Issue by HarisKhan-23** [gophish/gophish#2249]
Hi team,

I have created multiple number of users in GoPhish by logging into GoPhish with admin credentials and then using the "Add User" option from "User Management" tab. The problem is, when I login to GoPhish using any one of those users and create a campaign, and then logout and login again from admin credentials, those campaigns aren't visible at admin's view. 

Following this post: https://github.com/gophish/gophish/issues/2017 , I understand that GoPhish doesn't allow admin users to manage or view campaigns that are set up by other users. I just need to know if any such feature has been introduced in GoPhish recently or is there any workaround to view all user campaigns from admin dashboard?

The aim is to view all campaign results set up by different users under one admin user dashboard since that's what admin control should mean in the first place.

Any assistance would be highly appreciated.

Thanks.

**Comment by glennzw** [comment]
No unfortunately each user (admin or otherwise) has all their data segmented to them. There are no plans at this stage to change this, but it is on the backlog.
