### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by Hemza** [gophish/gophish#225]
Hello,

can you  tell me how to configure the landing page to be accessible by users,

regards

**Comment by jordan-wright** [comment]
Hey Hemza, we'll need some more info to troubleshoot the issue.

What have you tried so far that didn't work?

**Comment by m4dw0lf** [comment]
Hello Hemza,

So, you already created the campaign, right ?

When you create you have to specify the URL of the access, if your targets is in the same 
subnet that your phishing server you just have to point the internal IP of the server.
If the target is in the WAN network you have to poing the external IP of the server.

For me, this appear to me a normal question (But Gophish have a excellent documentation).

When you edit the file config.json you normally points two IP:

Server IP: x.x.x.x:3333
Phishing IP: x.x.x.x:80

When you create the campaign you have to point the Phishing IP to be accessible by the target. You also can point the Landing page that you want to use in your campaing.

If you have another doubt I would be glad to help.

Best regards.

**Comment by Itrustsecurity** [comment]
Thank you very much for explication,

**Comment by Hemza** [comment]
Thank you very much for explication

**Comment by blambson78** [comment]
So I have verified all these settings running on the Windows version and I cannot get a Landing Page to load. Everything else is working but the landing page does not seem to be running

**Comment by dardano** [comment]
Is this fixed ? I have the same issue on my side.
Thanks
