### ISSUE TITLE
How to spoof FROM field not showing the email and the rest of email headers??

### ISSUE THREAD

**Issue by jotunel** [gophish/gophish#2250]
What version of Gophish are you using?: Latest

Brief description of the issue: 
So, I am trying to raise security awareness at my company. I have successfully set up a phishing campaign with GoFish, but the problem is that 
1) **I can not spoof the From field**
2) if someone clicks at the email and selects "Show Original", so that he can see the real email headers, Message headers reveal my true identity. In other words, he will see something like this:

Return-Path: <my-real-email@gmail.com> 
Authentication-Results: XX; spf=pass smtp.mailfrom=my-real-email@gmail.com
Received-SPF: <my-real-email@gmail.com> 

What are you expecting to see happen? : I am expecting to totally erase my real email.

What are you seeing happen? Email headers revealing my true identity

I have set up an email from my custom domain and a custom email hosting provider.
In gmail, I have fetched(connected the two emails) the email using this: https://www.namecheap.com/support/knowledgebase/article.aspx/9188/2175/gmail-fetcher-setup-for-namecheap-private-email/
So, now, I am sending mails with my custom domain, but the STMP host is: smtp.gmail.com

Is there a way to send directly from the custom domain and not gmail, so that the headers are different? 
Because I am not sure about another solution, if there is any.

**Comment by glennzw** [comment]
If you're sending via GMail I don't think you can get around this. Best bet is to setup your own SMTP server (it's pretty [straight forward](https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-postfix-as-a-send-only-smtp-server-on-ubuntu-16-04)).

You can add/change email headers in your gophish sending profile, but if the mail server replaces or rejects theses I don't think there's too much we can do.

**Comment by jotunel** [comment]
Thank you very much for your response. 
The issue is not solved. **Gmail** is **not** **able** to **load remote content**, even if a gmail user has activated it. That being said, you can't tell if a gmail user opened his email. You can tell it if he also clicks that link though, as he moved onto the chain of actions.

If someone else finds a solution on this, it would be much appreciated if he can answer.

Leaving the topic open for a few days in the case of someone has to say something important on this.

**Comment by jotunel** [comment]
Also, if I setup my own SMTP server, is it 100% that this will work?

Regards,

**Comment by jotunel** [comment]
An old comment reads: "Most of the cheap webhosting sites offer a mailserver that does not check for mailspoofing. And most of the internet service providers offer a mailserver that can be (ab-)used for spoofing (as long you are sending it from an IP that's from themself)."

What's an examples of an Internet Service Provider that offers a mailserver that can be (ab-)used for spoofing?
Thanks!

**Comment by jotunel** [comment]
This was not possible via gmail. Used third party access and it got solved.
Closing this,

Thanks for the responses.

**Comment by mazayahamdallah** [comment]
Hi @jotunel, can you tell how was you solve this? thanks!
