### ISSUE TITLE
Feature request: Sending profile with IMAP

### ISSUE THREAD

**Issue by riramos** [gophish/gophish#2251]
Hi, I want to know if you are considering enabling IMAP support for sending profiles. 

Regards

**Comment by glennzw** [comment]
No, there are no plans for that. Are you facing problems with regular SMTP?

**Comment by Phexcom** [comment]
> No, there are no plans for that. Are you facing problems with regular SMTP?

Is there a way to get more custom Template Reference

**Comment by riramos** [comment]
> No, there are no plans for that. Are you facing problems with regular SMTP?

Yes, some email solutions (Microsoft 365, Google) do not accept emails that come from SMTP. In this case, the only way for the mail to reach the victim's mailbox is that the platform administrator add the fake domain to a white list.

**Comment by glennzw** [comment]
@riramos I might be mistaken, but I think IMAP is only for retrieving email (unless there's new functionality I'm unaware of).

I've used both Google and O365 to send via SMTP:

Google: https://support.google.com/mail/answer/7126229?hl=en-GB
Microsoft: https://support.microsoft.com/en-us/office/pop-imap-and-smtp-settings-8361e398-8af4-4e97-b147-6c6c4ac95353

**Comment by glennzw** [comment]
> > No, there are no plans for that. Are you facing problems with regular SMTP?
> 
> Is there a way to get more custom Template Reference

Hi @Phexcom - please open a new issue for questions unrelated to this issue

**Comment by riramos** [comment]
> @riramos I might be mistaken, but I think IMAP is only for retrieving email (unless there's new functionality I'm unaware of).
> 
> I've used both Google and O365 to send via SMTP:
> 
> Google: https://support.google.com/mail/answer/7126229?hl=en-GB
> Microsoft: https://support.microsoft.com/en-us/office/pop-imap-and-smtp-settings-8361e398-8af4-4e97-b147-6c6c4ac95353

Hi @glennzw, I'm talking about sending, not receiving. It is true that both Google and O365 can send emails via SMTP,  but I am asking that it be possible to send emails via IMAP. During the development of penetration tests, in a client that uses O365, it is necessary that the client configure an exception rule so that the emails arrive via SMTP, this impacts the criticality of the results.

**Comment by atheriqbal** [comment]
Yeah the administrator needs to add the sender address in safe sender list, and the IP needs to be whitelisted.

**Comment by glennzw** [comment]
@riramos My point is that I don't think IMAP can send email?

"IMAP is an Internet standard protocol used by email clients to retrieve email messages from a mail server over a TCP/IP connection." [[1](https://datatracker.ietf.org/doc/html/rfc3501)]

**Comment by glennzw** [comment]
Closing out as haven't heard back.
