### ISSUE TITLE
TLS Handshake error from X.X.X.X:52491: remote error: tls: unkown certificate 

### ISSUE THREAD

**Issue by eoinw** [gophish/gophish#2252]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: v0.11.0

Brief description of the issue: Sending profiles not working for multiple SMTP servers. The same SMTP servers were working last week so I am unsure why the issue has suddenly come about. 

What are you expecting to see happen? : The sending profiles to successfully send the emails

What are you seeing happen? Emails are not sending to any user. 

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

Please provide any terminal output that may be relevant below:
''time="2021-06-29T15:35:29Z" level=info msg="89.100.3.230 - - [29/Jun/2021:15:35:29 +0000] \"POST /api/util/send_test_email HTTP/2.0\" 400 74 \"https://54.75.181.196:3333/sending_profiles\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36\""
2021/06/29 15:35:46 http: TLS handshake error from 89.100.3.230:52491: remote error: tls: unknown certificate
time="2021-06-29T15:36:11Z" level=error msg="failed to create IMAP connection: dial tcp 212.227.15.154:993: i/o timeout"
time="2021-06-29T15:37:41Z" level=error msg="failed to create IMAP connection: dial tcp 212.227.15.154:993: i/o timeout"
time="2021-06-29T15:39:11Z" level=error msg="failed to create IMAP connection: dial tcp 212.227.15.154:993: i/o timeout"
time="2021-06-29T15:40:41Z" level=error msg="failed to create IMAP connection: dial tcp 212.227.15.154:993: i/o timeout"
time="2021-06-29T15:40:46Z" level=warning msg="Max connection attempts exceeded - dial tcp 185.107.232.248:587: i/o timeout"
time="2021-06-29T15:40:46Z" level=error msg="Max connection attempts exceeded - dial tcp 185.107.232.248:587: i/o timeout"
time="2021-06-29T15:40:46Z" level=info msg="89.100.3.230 - - [29/Jun/2021:15:35:46 +0000] \"POST /api/util/send_test_email HTTP/2.0\" 500 131 \"https://54.75.181.196:3333/sending_profiles\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36\""
time="2021-06-29T15:42:11Z" level=error msg="failed to create IMAP connection: dial tcp 212.227.15.138:993: i/o timeout"
time="2021-06-29T15:43:41Z" level=error msg="failed to create IMAP connection: dial tcp 212.227.15.138:993: i/o timeout"
time="2021-06-29T15:45:11Z" level=error msg="failed to create IMAP connection: dial tcp 212.227.15.138:993: i/o timeout"''

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Set up sending profile 
 * Step 2 - Get log from above

**Comment by eoinw** [comment]
Hi,
I am using GoPhish for a demonstration this Friday for a masters demonstration and would appreciate if I could be helped ASAP! But if not that's fair enough too. Thank you so much!

**Comment by glennzw** [comment]
Hello - thanks for reaching out. The error in the logs we're interested in is:

```
time="2021-06-29T15:40:46Z" level=error msg="Max connection attempts exceeded - dial tcp 185.107.232.248:587: i/o timeout"
```

That is saying the gophish server is unable to connect to `185.107.232.248:587`, which is presumably your SMTP server.

I am able to connect to that IP/port:

```
➜  ~ nc -v 185.107.232.248 587
Connection to 185.107.232.248 port 587 [tcp/submission] succeeded!
220 smtp-relay.sendinblue.com ESMTP Sendinblue SMTP 2.0
EHLO foobar
250-smtp-relay.sendinblue.com Nice to meet you, [82.37.11.112]
250-PIPELINING
250-8BITMIME
250-AUTH LOGIN PLAIN CRAM-MD5
250 STARTTLS
```

So, presumably there is some firewall or other networking issue preventing the server where gophish is residing to connecting. Try test from the command line to see if you're able to (`nc -v 185.107.232.248 587`, as above).

The TLS warnings can be ignored - those are just warning you're using a self signed cert to access the web admin console.

IT also looks like your server is failing to connect to the IMAP server - so something must be fishy (phishy?) on your networking layer.

Hope that helps get your masters demo sorted.

**Comment by eoinw** [comment]
Hi Glenn,
Thank you for your help I would have never figured that out unfortunately! 
I think was issue was that I had to add the IP address and port number to the security group for port 578 and port 993 as I am hosting this on AWS. 
Thank you so much again you don't know how much stress you've relieved for our group with your help haha!

**Comment by glennzw** [comment]
No worries, good luck with the Masters!
