### ISSUE TITLE
Feature request: More template reference

### ISSUE THREAD

**Issue by Phexcom** [gophish/gophish#2253]
How possible is it to be able to add more templates  just like the once listed on 
https://docs.getgophish.com/user-guide/template-reference

Example Templates :

{{.Date_current}}
{{.Time_current}}
{{.Random_num(len)}}
{{.Random_string(len)}}

Maybe more so the randomness of message been sent can bypass spam filters.

It will also be good if  templates can also work in the SUBJECT field and also the FROM field

**Comment by glennzw** [comment]
There aren't any additional template variables, but it is something we're working on supporting.
