### ISSUE TITLE
email not receiving at victim end 

### ISSUE THREAD

**Issue by rahultalekar** [gophish/gophish#2254]
hello community,

we have setup go phish and we are trying to send mails but in dashboard and also on console screen we can see mail are sent but at the receiver end we are not receiving any mail not in junk or spam folder also. kindly help us to solve this issue because there is no error showing. 
we are using outlook smtp server for sending mails.

Note:  test email are successfully received at victim end but campaign mail are not receiving

**Comment by glennzw** [comment]
Are you sending via Microsoft's SMTP servers? If your email isn't well formed it's likely being consumed by a spam engine.

Try send a campaign email to this site in order to gauge how "spammy" it is:

https://www.mail-tester.com

**Comment by atheriqbal** [comment]
If you are in an enterprise envornment, try white listing the phishing server IP. Also, keep the address in safe sender list

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to re-open if you're still having trouble.
