### ISSUE TITLE
Não estou recebendo o rastreio de email no painel help!!! (  I'm not receiving the email tracking on the help panel!!!) 

### ISSUE THREAD

**Issue by belinhadantas** [gophish/gophish#2255]
Ja testei de tudo para receber os movimentos no painel é apenas fica dessa forma: https://imgur.com/a/L2Xh4HC

I've tried everything to get the moves in the plan and it just stays that way:  https://imgur.com/a/L2Xh4HC

**Comment by glennzw** [comment]
Did you enable email tracking with your campaign? You need to select that option when making a template.

If so, then it's probably the email client that's blocking remote images (that's how the tracking works).

Can you share the email source, as received by the email client?

**Comment by belinhadantas** [comment]
I can share yes before you get me 2 doubts ( Ps: I'm a newbie I'm studying the platform for work use, I'm sorry for the doubts )

1: Confirm me if you are talking about this tracking option: https://imgur.com/a/vV5V3nx

If this option is always on

2 doubts: it's about installing gophish, I had a lot of difficulty because I don't speak very English and there is no tutorial teaching in Portuguese.

I downloaded the 64bits zip folder for windows opened the folder and ran it through the application inside it ( https://imgur.com/a/xSM1Bkd ) > then the CMD prompt opens ( https://imgur.com/a/ovMF1K6 ) 

I open nevagor and insert the ip provided along with the password to access the platform is this correct means of access?
Could this be what is causing the tracking problem?

3: doubts: am I in the correct place to get the source of the email? : https://imgur.com/a/XaGVg8q

If yes, confirm that I send it :)

Sorry for the basic doubts thank you for taking your time to help me

**Comment by glennzw** [comment]
Hi @belinhadantas - no problem, we were all newbies at some point!

1.
You need to enable tracking in the "Email Template" section:

![Screenshot 2021-07-06 at 09 54 34](https://user-images.githubusercontent.com/3966613/124572778-d5224c00-de40-11eb-8fad-bfcab045255e.png)

2.
Your installation looks OK.

3.
Yes that is the email source. If you share that I can see if you have enabled the 'Tracking Image'.

**Comment by belinhadantas** [comment]
Ok thank you I will test it is return with the result

**Comment by belinhadantas** [comment]
Here is the source of the email I did a new quick test enabling the way you asked but the result is the same as before do not capture anything

**Comment by belinhadantas** [comment]
Above is the source file in zip folder

**Comment by belinhadantas** [comment]
Source of email received is in zip file: 
[original_msg.zip](https://github.com/gophish/gophish/files/6804786/original_msg.zip)

**Comment by glennzw** [comment]
I can't find the tracking parameter in that email, so I don't think you included it. You can manually add it to your email template HTML with `{{.Tracker}}` (typically add this before your closing `</body>`.

It might be best to start with a very simple email template.

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen.
