### ISSUE TITLE
Gophish 0.11 won’t start while on a vps

### ISSUE THREAD

**Issue by Chosenbrain** [gophish/gophish#2256]
I installed the latest version of Gophish started it normally and it works fine not until I tried on a Vultr Vps, I installed Gophish unzip it then but I can’t start my Gophish instead I get error shown below 
![image](https://user-images.githubusercontent.com/32149973/124393800-23760480-dcf4-11eb-9339-df1f9956dadf.jpg)

**Comment by glennzw** [comment]
You're trying to run the Windows version on Linux. You'll need to download the Linux version of gophish.

**Comment by glennzw** [comment]
Closing out as haven't heard back.
