### ISSUE TITLE
Can't send emails from gmail while I have a VPN open

### ISSUE THREAD

**Issue by jotunel** [gophish/gophish#2257]
What version of Gophish are you using?: Latest

Brief description of the issue: I can send find from my personal computer when using my normal ISP IP address. But the second I switch on my VPN I get MAX Connections error when trying to send test emails. As there is a similar issue, jordan-wright is saying "Gophish is unable to reach the SMTP server you entered. If this is only occurring on a VPN, then that suggests a networking/routing issue outside of Gophish."
What could I do to solve this?

What are you expecting to see happen? : An email to send

What are you seeing happen? Not able to send if I have VPN on.

Has anyone else ran into this issue?

**Comment by atheriqbal** [comment]
Hi, 
Yeah this is outside the scope, but maybe Gmail is blocking you? Try allowing third party access to Gmail while still connected to VPN.

**Comment by jotunel** [comment]
Gmail was indeed blocking me. I used a different SMTP, outside of google and nearly everything is solved.

Thank you very much for your response.

Closing this.
