### ISSUE TITLE
Windows 10 is it possible to use gophish?

### ISSUE THREAD

**Issue by belinhadantas** [gophish/gophish#2258]
it is possible to use the gophish platform on windows or just linux :?

**Comment by edermi** [comment]
Have you read the [install documentation](https://docs.getgophish.com/user-guide/installation)? There is a windows download in the [releases](https://github.com/gophish/gophish/releases/tag/v0.11.0) section.

**Comment by glennzw** [comment]
As @edermi says, yes it's possible to run on Windows. Have a look through the documentation and download the Windows release. Good luck!
