### ISSUE TITLE
Slow Performance due to exisiting campaigns

### ISSUE THREAD

**Issue by iHasanYK** [gophish/gophish#226]
Hi,

thank you very much for the incredible tool, i really loved it.

i have one issue, i have created 6 campaigns for testing, all of them contain up to 2 emails, the performance became to be not good, it wasn't opening the home page of gophish, once i tried to delete any campaign, it was taking much time. 

and what's the recommended hardware specs if the issue related to hardware ?!

many thanks in advance.

best regards

**Comment by jordan-wright** [comment]
It should be just fine performance wise... what browser are you using?

**Comment by iHasanYK** [comment]
i have used Google chrome and firefox

when i have removed 3 campaigns out of 7, it started to be faster, but not fast as when it's fresh

**Comment by iHasanYK** [comment]
i have installed it on ubuntu 32 bit VM guest

**Comment by jordan-wright** [comment]
Hmm... I can't imagine that the fact it's a VM would be the performance. The required specs should be small.

I'm afraid without more information, I wouldn't be able to determine the underlying issue. One thing that you could try would be to:

* Open the page that's "slow"
* Watch the terminal window.. what line in the terminal output appears before/after the slowness occurs? That would be indicative of the issue. If it's an API call, etc.

**Comment by iHasanYK** [comment]
sorry Jordan for disturbing you, it was an internet issue, my browser was trying to connect to fonts.googleapis.com and there was a problem like blocking or something, it's working smoothly now, thanks a ton :D

**Comment by jordan-wright** [comment]
Ah, yeah, that's to download the Source Sans Pro font. I've been meaning to make that local.

Good catch! Glad to see it's resolved.
