### ISSUE TITLE
Cannot execute binary file

### ISSUE THREAD

**Issue by leogastelum9** [gophish/gophish#2260]
<img width="473" alt="8 cannot execute binary" src="https://user-images.githubusercontent.com/87397545/125533950-7dff4368-da70-4c74-97d4-3f1a87596f73.png">

**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: v0.11.0

Brief description of the issue: Cant execute gophish file. Using Ubuntu 20.04 on Oracle Always Free Tier Cloud

What are you expecting to see happen? : Install and run gophish on my vm server

What are you seeing happen? error "-bash: ./gophish: cannot execute binary file: Exec format error"

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html

```

Please provide any terminal output that may be relevant below:

```
$ ls -l gophish
-rwxr-xr-x 1 ubuntu ubuntu 20945544 Aug 28  2020 gophish

$ file gophish
gophish: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, Go BuildID=1Cx8MtvJ2ol9MtUiYSt0/AJMHZRU1IGS0TA-nd6_5/GNdG0oTnkPm0aC3p00xd/z0WEW3Lv4r69QDuwmjIh, BuildID[sha1]=7850f3325326b8645fb15a490c60f9500ebd1eae, not stripped

$ uname -a
Linux ubunto-server-vm 5.8.0-1034-oracle #35~20.04.2-Ubuntu SMP Mon Jun 28 08:52:07 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

$ ./gophish
-bash: ./gophish: cannot execute binary file: Exec format error
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Download Wget Linux 64 Gophish --> Complete.
 * Step 2 - In new dir, Unzip Gophish --> Complete.
 * Sept 3 - Nano config.json for listen_url 0.0.0.0:3333 --> Complete.
 * Sept 4 - chmod u+x gophish --> Complete.
 * Sept 5 - ./gophish --> Fail.
 
 I´m really new to command. From what I read, it may be the architecture, but dont kown what I can do. Thanks in advance.

**Comment by atheriqbal** [comment]
Do you have a windows server? Because I see Power shell running

**Comment by edermi** [comment]
The reason is probably that you're trying to run a 64bit Intel binary under a 64bit ARM architecture. You need to build Gophish for ARM, there are currently no official builds for it. This should not be a problem, but I'm not sure if the sqlite dependencies require modifications for building on ARM.

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen.
