### ISSUE TITLE
Hide RID in URL possible ?

### ISSUE THREAD

**Issue by antonbek89** [gophish/gophish#2263]
Did it passable changed the rid parameter ?
http://example.com/?rid=7UNpWt7

I tried go to models/campaign.go (line 130) and changed the "rid"parmter
const RecipientParameter = "rid" 

I stop the gophish service and start it again 

It's not work for me 
Someone maybe knows why?

**Comment by glennzw** [comment]
You can add as many directories and extra parameters as you like to your endpoint URL. e.g:

`https://example.com/foo/bar/blah?some=thing&up=down`

**Comment by antonbek89** [comment]
> You can add as many directories and extra parameters as you like to your endpoint URL. e.g:
> 
> `https://example.com/foo/bar/blah?some=thing&up=down`
> 
> Gophish will append the rid parameter. There's no easy way to change that actual value that I know of, though.

Exactly, my question how to do it?
Which parter in the code I need to change?

**Comment by edermi** [comment]
In general, I think it may be interesting to have this as a feature or at least documented for advanced users. I'd bet there are mail gateways blocking mails just because of the existence of a rid parameter in one of the links. 

I may take a closer look at it if I find some time in the next week.

**Comment by glennzw** [comment]
Sorry you can't change the `rid` name at this stage, but I'll keep it in mind for future updates.
