### ISSUE TITLE
Unable to copy images to templates

### ISSUE THREAD

**Issue by Mytre** [gophish/gophish#2265]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: Gophish Linux

Brief description of the issue: Unable to copy images to template to be used in campaigns

What are you expecting to see happen? : Copy image to template on the UI and image shows up

What are you seeing happen? Image is not copied.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:
It applies to every template, I used to be able to do this on gophish installed on windows, now I have it installed on Linux and I am unable to copy and paste pictures. Is this an issue related to permissions of gophish?

**Comment by glennzw** [comment]
Hi, thanks for reaching out. I suspect this is probably a browser or host OS issue, if it worked in one scenario but not another. I'm unable to paste images into templates on my Mac, but I don't have a Windows box handy to test if that works. We use CKEditor (https://ckeditor.com/) for template editing; you might have luck doing some research in that direction?

Sorry to not be of more help!

**Comment by glennzw** [comment]
So, I managed to spin up a Windows box, and I can't paste images in there either.

**Comment by KennethKali2020** [comment]
I have found use images already hosted on the web. Go to an image on the internet, copy the URL and then past that into a new window to make sure you are getting only the image. past an image onto the email, open the html view, go to where it says src= and past your new URL from the internet
