### ISSUE TITLE
Gophish redirect doesn't seem to be working (Not sure if i'm at fault)

### ISSUE THREAD

**Issue by joehilton** [gophish/gophish#2267]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: **gophish-v0.11.0**

Brief description of the issue: I've created my own landing page with a form for users to enter their email address and password, but when they click "Confirm" on the form, instead of redirecting them to the site that I want them to. It displays a 404 error saying page not found

What are you expecting to see happen? : When users hit the confirm button, I'm expecting credentials to be captured and then they are redirected to a different site that I have provided

What are you seeing happen?: When they click on "Confirm" all I see is a 404 page not found message. It also outputs the following in the address bar `?fullname=test%40test.com&email=test123`

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:
```
<html>
<head>
  <style>
    div {
      background-color: #DCDCDC;
      height: 31%;
      width: 15%;
      margin: auto;
      margin-top: 200px;
      padding: 20px 15px 60px 20px;
      border-radius: 10px;
      box-shadow: -1px 5px 10px 2px rgba(0,0,0,0.45)
    }
    p {
      font-weight: bold;
    }
    .capnet_logo {
      margin-left: 860px;
    }
    .office365logo{
      margin: auto;
      height: 200px;
      object-fit: cover;
    }
    .email_field{
      height: 30px;
      width: 100%;
      border-radius: 5px;
    }
    .password_field{
      height: 30px;
      width: 100%;
      border-radius: 5px;
    }
    .confirm_button{
      background-color: #286090;
      border-radius: 5px;
      color: #ffffff;
      padding: 10px 10px 10px 10px;
      font-size: 15px;
      font-weight: normal;
    }
  </style>
</head>
<body>
  <img src="C:\Users\Joe\Documents\Cybersecurity\Gophish\capnet logo.jpg" class="capnet_logo" alt="">
  <div>
    <img src="C:\Users\Joe\Documents\Cybersecurity\gophish\office365logo.png" class="office365logo" alt="">
    <form action="" target="_blank">

      <p><input type="text" class="email_field" name="fullname" placeholder="Email Address" label="Email Address"/></p>

      <p><input type="text" name="email" class="password_field" placeholder="Password" label="Password"/></p>

    <input type="submit" class="confirm_button" value="Confirm"/>

    </form>
  </div>
</body>
</html>
```

Please provide any terminal output that may be relevant below:
```
4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36\""
time="2021-07-23T09:40:03Z" level=info msg="157.231.7.32 - - [23/Jul/2021:09:40:03 +0000] \"GET /favicon.ico HTTP/2.0\" 404 19 \"https://captnet.co.uk/?rid=3F1v3Mb\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36\""
2021/07/23 09:40:12 http2: server: error reading preface from client 157.231.7.32:53320: read tcp 172.31.38.152:443->157.231.7.32:53320: i/o timeout
2021/07/23 09:40:12 http2: server: error reading preface from client 157.231.7.32:58753: read tcp 172.31.38.152:3333->157.231.7.32:58753: i/o timeout
time="2021-07-23T09:40:25Z" level=info msg="157.231.7.32 - - [23/Jul/2021:09:40:25 +0000] \"GET /?fullname=test%40test.com&email=test123 HTTP/2.0\" 404 19 \"https://captnet.co.uk/?rid=3F1v3Mb\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36\""
time="2021-07-23T09:40:31Z" level=info msg="157.231.7.32 - - [23/Jul/2021:09:40:31 +0000] \"GET /api/campaigns/30/results?{} HTTP/2.0\" 200 605 \"https://captnet.co.uk:3333/campaigns/30\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36\""
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
Try adding a POST parameter in your `<form>` spec. ie:

`<form action="" method="post">`

**Comment by joehilton** [comment]
Hi Glenn,

Just tried that but it still didn't record the submitted details unfortunately.

Thanks for the suggestion though, much appreciated
