### ISSUE TITLE
email template erro

### ISSUE THREAD

**Issue by m4m4t492** [gophish/gophish#2269]
What version of Gophish are you using?: 0.11.0

Brief description of the issue: Email error

What are you expecting to see happen? : link

What are you seeing happen? the link is in bracket ---> [link]. Example:
The password for email@email.com has expired. Please reset your password [10.10.10.1?rid=lheY7fY]here.

SAMPLE: 

![Untitled_censored](https://user-images.githubusercontent.com/66710286/127469170-d180c982-f57a-49b5-8c6f-e987e0470338.jpg)

**Comment by atheriqbal** [comment]
Hi, can you send your email template here? The HTML part

**Comment by glennzw** [comment]
Closing out as we haven't heard back, feel free to re-open the issue and share the email template @m4m4t492
