### ISSUE TITLE
Sending a test mail does not work 

### ISSUE THREAD

**Issue by OcusBpl** [gophish/gophish#2270]
What version of Gophish are you using?:  0.11

Brief description of the issue: Sending a test mail does not work  it loads continuously without sending itself, the same for the campaigns

What are you expecting to see happen? : mail send

What are you seeing happen? loading wheel and nothing is happening

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

When I create a profile, I want to send a test email and nothing happens, it's a load but the test does not send.
I put Gophish on a vps

**Comment by glennzw** [comment]
Hi there. Could you supply output from the gophish logs, and the details of the mailserver you're using.

**Comment by OcusBpl** [comment]
Hi, 
I use a microsoft exchange server
I have no error in my console
Where is the gophish log ?
Thanks

**Comment by atheriqbal** [comment]
Hi, 
The email address which you are using, is  it allowed to send emails from third party apps? You may need to talk to your Exchange Admin.

**Comment by KennethKali2020** [comment]
Exact same issue, following for solution. Email is set up for third party apps and I have tried it on several different virtual machines. Even spun it up on Azure

**Comment by glennzw** [comment]
Hard to debug this. I'd suggest two things:

(i) Set up Mailhog, it's a dummy SMTP server. You can run it on the same box as gophish, or a separate one. If you can successfully send emails through this server, then we know gophish is fine and it's a mail server / Microsoft issue.

(ii) Next, try manually sending a test email from the command line with telnet. e.g:

```
telnet youremailserver.com 25
ehlo youremailserver.com
mail from: someone@youremailserver.com
rcpt to: friend@youremailserver.com
data
Subject: Testing my smtp server

Hello,

This is a test.

Goodbye.

.
```

(substituting appropriate variables to match the ones you're using for gophish)

This will hopefully throw up any errors that your mail server is sending, that gophish isn't picking up on.

Also, try checking the browser console in gophish, there might be some errors popping up there.

If all the above fails, we might have to do some traffic interception (socat tunnels), but hopefully we won't have to go that far.

**Comment by glennzw** [comment]
One problem could be that your Azure instances is not allowing outbound connections? 

Did you succeed with the telnet example above to connect to your mail server?

**Comment by KennethKali2020** [comment]
so I ran the command on the FTP server, I was able to connect using port
587, but the connection was refused on port 25. I did confirm that the
azure is allowing all outbound connections

**Comment by glennzw** [comment]
From your gophish server if you're unable to connect to your mailserver via telnet then there's a networking problem.

Can you share the mail server IP + port here, and the result from the telnet command you tried please.

**Comment by KennethKali2020** [comment]
Is there a more secure way I can send you this info instead od posting it
in the forum??

**Comment by glennzw** [comment]
@KennethKali2020 Sure, drop me an email (see profile page).

**Comment by KennethKali2020** [comment]
OcusBpl... I am pretty embarrassed that I am posting this on here.. but I hope I am not the only one who made this mistake.... if you are using gmail, they dont accept prot 25... mine kept spinning over and over like yours, but you have to specify port 587

so smtp.gmail.com:587
thanks glenn for all your help, and I cant believe I got so careless.

**Comment by glennzw** [comment]
> thanks glenn for all your help, and I cant believe I got so careless.

We're all learning here, and have all made silly mistakes :) I'll close this out for now as haven't heard back from @OcusBpl

**Comment by nocomp** [comment]
hi,
i am using OVH email adresse, but no mail are sended :(
