### ISSUE TITLE
SMTP to Gophish

### ISSUE THREAD

**Issue by TairaNoMasakado** [gophish/gophish#2271]
I have a server with gophish and would like to know what is the best SMTP service to use with gophish. I don't want emails to fall into the spam box. Can help me?

**Comment by atheriqbal** [comment]
Hi, check issue #2116.

**Comment by glennzw** [comment]
@atheriqbal is spot on as usual. This is the guide I've used in the past: https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-postfix-as-a-send-only-smtp-server-on-ubuntu-16-04

**Comment by aafi19** [comment]
can someone guide me how to config SMTP server in Gophish , i'm filling all correct details, but still getting error =incorrect username or password , too many attempt excced

**Comment by glennzw** [comment]
Please open a new issue and share some screenshots

**Comment by thib-d** [comment]
You can use free smtp server made for it, like [https://smtpgophish.gottaphish.com/](https://smtpgophish.gottaphish.com/)
