### ISSUE TITLE
Content popups titled 'New' even when editing existing content

### ISSUE THREAD

**Issue by ChrisASE** [gophish/gophish#2275]
_What version of Gophish are you using?:_ 
0.11.0

_Brief description of the issue:_ 
When editing existing templates/sending profiles/landing pages etc, the title of the popup boxes all begin with 'New'.

What are you expecting to see happen? :
When creating new (or copying) templates/sending profiles/landing pages they are titled 'New xxxxxx'. When editing existing templates/sending profiles/landing pages they are titled 'Edit xxxxxx'

What are you seeing happen?
The title of popups begins 'New' regardless of whether the content is new or editing existing content.

_If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:_
N/A

_Please provide any terminal output that may be relevant below:_
N/A

Please provide as many steps as you can to reproduce the problem:
EG for Landing Pages.
 * Step 1 - Click Edit Page icon.
 * Step 2 - Existing page popup has all existing information (title, HTML, capture submitted opt-in/out, redirect URLs etc), but the popup is titled 'New Landing Page'.

I think I'm just being overly 'special' about this because there's been a few occasions when I've been working on autopilot/braindead mode, and when seeing 'New' it's thrown me off. This really isn't a major issue or bug, just an enhancement to make editing of existing content clearer. Screeny below what is seen when clicking 'Edit Page' on an existing landing page.
 

![](https://i.imgur.com/9WAsOmM.png)

**Comment by ChrisASE** [comment]
`<img src="https://i.imgur.com/9WAsOmM.png" width="400" style="400px;" />`

**Comment by glennzw** [comment]
I've bumped into this a few times too, it can be annoying. Will add to the list. Thanks for reaching out!

**Comment by jake-walker** [comment]
I'd like to have a look at this one 🙂

**Comment by Lakshyaraj00** [comment]
Insert code here

**Comment by Lakshyaraj00** [comment]
What you know about crack insta password?

**Comment by glennzw** [comment]
Hi @ChrisASE - thanks to @jake-walker we've now fixed this. Thanks for your patience!
