### ISSUE TITLE
Campaign URL

### ISSUE THREAD

**Issue by MrJeffyw** [gophish/gophish#2278]
Hi guys, what if i set the "campaign URL" as "http://mydomain.com/xxx/xxx.jsp" not just "http://mydomain.com" to make my phishing website more realistic.
Can you please help? Thank you.

**Comment by atheriqbal** [comment]
Hi, 
Campaign URL is the URL where your phishing server is listening. That is, <domain>:<4444> (default case). 
What do you mean by making phishing website more realistic? The Admin URL or Landing pages?

**Comment by MrJeffyw** [comment]
> Hi,
> Campaign URL is the URL where your phishing server is listening. That is, :<4444> (default case).
> What do you mean by making phishing website more realistic? The Admin URL or Landing pages?

Hi, i mean:
Email Templates->use {{.URL}} 
New Campaign->set URL http://mydomain.com
When clicking on the link in the email,what I see in the browser is "http://mydomain.com?rid=xxxxxx".

I want to make it look like “http://mydomain.com/account/login.jspx?rid=xxxxx” in the browser, which is more more deceptive! How should i set in Email Templates and New Campaign url?

**Comment by atheriqbal** [comment]
Maybe make an alias of domain "http://accounts.domain.login.com" point it towards the phishing server. Use this as campaign URL then.

**Comment by glennzw** [comment]
@MrJeffyw You can add any number of directories or variables to your campaign URL. e.g:

https://myserver.com
https://myserver.com/foo/bar/rar
https://myserver.com/foo?msg=hello&weather=ok

Gophish will append the rid parameter to the end when sending the campaign.

**Comment by MrJeffyw** [comment]
> @MrJeffyw You can add any number of directories or variables to your campaign URL. e.g:
> 
> https://myserver.com
> https://myserver.com/foo/bar/rar
> https://myserver.com/foo?msg=hello&weather=ok
> 
> Gophish will append the rid parameter to the end when sending the campaign.

Good！！
