### ISSUE TITLE
can't seem to install the gophish on my kali linux please i need help on mac

### ISSUE THREAD

**Issue by garycotler** [gophish/gophish#2279]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue: 

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by garycotler** [comment]
on my mac

**Comment by garycotler** [comment]
it's not granting me permission to to wrtie on the directory

**Comment by lagrav** [comment]
cmoon gary from divine ... more info

**Comment by garycotler** [comment]
hello sorry i didn't get a notification via email that i was replied

**Comment by garycotler** [comment]
here is the error zsh: no such file or directory: ./gophish

**Comment by garycotler** [comment]
![Screenshot 2021-08-18 at 9 01 29 PM](https://user-images.githubusercontent.com/87995743/129992162-16f08b8b-6b1a-44c3-81b1-7b9faa67cff6.png)
![Uploading Screenshot 2021-08-18 at 9.13.38 PM.png…]()

**Comment by garycotler** [comment]
![Screenshot 2021-08-18 at 9 13 38 PM](https://user-images.githubusercontent.com/87995743/129992198-7fcb38e4-1d19-463f-b157-5b430f33baf8.png)

**Comment by garycotler** [comment]
please help out

**Comment by lagrav** [comment]
bruh this is chris. lol i saw your message and knew you were the one.

**Comment by garycotler** [comment]
yeah bro mans got to it this fixed

**Comment by glennzw** [comment]
Please run the `ls` command in the gophish folder and put the output here.

Try `chmod +x gophish` too if you haven't run that already (make the file executable).

**Comment by garycotler** [comment]
ir says " ─(captainmarvel㉿kali)-[~/gophish]
└─$ chmod +x gophish
chmod: cannot access 'gophish': No such file or director"

**Comment by garycotler** [comment]
![Uploading Screenshot 2021-08-20 at 7.16.36 PM.png…]()

**Comment by garycotler** [comment]
http://prnt.sc/1qdhi7l

**Comment by edermi** [comment]
You cloned the repository instead of downloading the release binary. Either you use the provided release builds or build gophish on your own.

**Comment by garycotler** [comment]
how do i go about that thanks

**Comment by edermi** [comment]
These topics are covered in the documentation: https://docs.getgophish.com/user-guide/installation

**Comment by garycotler** [comment]
gophish working fine thanks i have solved it
