### ISSUE TITLE
Multiple Active Campaigns

### ISSUE THREAD

**Issue by iHasanYK** [gophish/gophish#228]
Hi Jordan,

does GoPhish support visiting multiple landing pages at the same time ?! if not, i would like to suggest such a thing if doable :) 

regards
hasan

**Comment by jordan-wright** [comment]
Hasan,

How would that work? Typically, links can only point to a single web page.

Thanks!

**Comment by iHasanYK** [comment]
i do apologize, my language is bad and i didnt know how to describe it
my question is, can we have multiple active campaigns ?!

**Comment by jordan-wright** [comment]
Absolutely! Technically speaking, since all data is loaded dynamically from the database, all campaigns are always "active".

Eventually, we'll put in the functionality to "complete" or "close" a campaign, but as of right now all campaigns are always available to have new results.

**Comment by jordan-wright** [comment]
I'm going to go ahead and close this for now. @iHasanYK - let us know if you have any other questions pertaining to this issue.

Thanks!

**Comment by iHasanYK** [comment]
Thanks Jordan, i have tested it today and it's working perfectly

many thanks again and again :)
