### ISSUE TITLE
This site can't be reached!

### ISSUE THREAD

**Issue by United2021** [gophish/gophish#2281]
Hi, im using gophish on upcloud server ubuntu os.
I deployed gophish on my website with listining port of 0.0.0.0:3333 but when i enter my server ip address xxx.xx.xxx.xxx:3333 in my browser it says this site cant be reached

**Comment by atheriqbal** [comment]
Is the port 3333 open to all?  
Send contents of config.json please.

**Comment by KennethKali2020** [comment]
go to the gophish website, scroll down and click on the link on their page. and click on the link. Typing in local host:3333 has stopped working for some reason. Click on their page, scroll down to setup and click their link that says https://localhost:3333/ it will take you to https://localhost:3333/login?next=%2F There is a youtube video about it.

**Comment by snowleoparddd17** [comment]
still, it was working a couple of days ago but now it cant be reached for me
