### ISSUE TITLE
Implemented USB Drive Test in Gophish

### ISSUE THREAD

**Issue by atheriqbal** [gophish/gophish#2283]
Hi, 
I have enhanced v0.11 to include USB drive test. 
I have kept in mind @jordan-wright's philosophy of running it without any exernal dependencies. 
@glennzw I have emailed you too. Anyways, this forum is open for suggestions. I can share my flow if the feature is deemed interesting by the community.

**Comment by atheriqbal** [comment]
I will...Just wanted to have a discussion first on features.

**Comment by glennzw** [comment]
Hi @atheriqbal - thanks so much for putting some thought into this and kicking off a discussion. I did see your email, apologies for not replying.

I'd be happy to hear what you have in mind! I've been pondering this for a while too.

**Comment by atheriqbal** [comment]
Okay I was a little busy, will post the description with screenshots tonight.

**Comment by atheriqbal** [comment]
Okay, so we launch a USB type campaign. All active and archived usb campaigns can be seen in this interface, with the same flow/logic as in phishing.

 

Give all the below details. I don’t think any other field is required here. (If someone has any ideas, please pitch in). On launching the campaign, it will give you can option to download an MS Word file with Macro. (We are working on using Excel too). User will download these files and copy it to the USBs. 
 


 

Campaign is in progress. You can download the file again anytime (First icon from the left)
 

Now there are 2 events we are tracking:
•	File open (Through a VSTO plugin, which can be pushed to all users for MS Office products, for example through SCSM – some extra effort).
•	Macros Enabled (This is already included in the file which is downloaded). No setup required.




Dashboard is populated. If anyone has suggestion for KPIs, do let me know.
 


And this is the timeline (never mind the icons, I just used the same ones for email and click). We are fetching hostname, mac address and IP. Can be anything else too.
 


So, this is the whole flow. Keep the suggestions coming.

**Comment by glennzw** [comment]
Hi @atheriqbal - thanks for walking us through your idea. It'd be pretty cool to track USB devices.

I'm a little concerned that this would take quite a big step away from the core email phishing that is gophish. That said, I'd definitely encourage you to build this out and maintain your own repo (I have various forks of my own with various elaborate gophish modifications that I use for specific engagements, e.g. WiFi tracking, haveibeenpwnd monitoring, etc). Perhaps if it gets enough traction we can reconsider adding it into the core.

I do appreciate you taking the time to put all this together and include us in the discussions! I'd love to take it for a spin once you've hosted it.

**Comment by atheriqbal** [comment]
Hi @glennzw , thank you for the feedback. I will make my own repo as you suggested. Lets see then. 
Closing it now.

**Comment by glennzw** [comment]
Great! Let us know how you get on.
