### ISSUE TITLE
Cannot get the Windows Service to start for GoPhish

### ISSUE THREAD

**Issue by mnITguy** [gophish/gophish#2285]
What version of Gophish are you using?:  gophish-v0.11.0-windows-64

Brief description of the issue: I cannot get the Windows Service to start for GoPhish after using NSSM to create the service

What are you expecting to see happen?: I'm expecting to see it work lol! 

What are you seeing happen?: I'm not seeing it work

Steps taken:
https://www.youtube.com/watch?v=lI6rCBYGNF8

**Comment by K-at** [comment]
I had the same problem. It was for an older version. Can you try this instruction: https://www.youtube.com/watch?v=YywVLJi7KtU&t=0s This helped me.

**Comment by mnITguy** [comment]
> I had the same problem. It was for an older version. Can you try this instruction: https://www.youtube.com/watch?v=YywVLJi7KtU&t=0s This helped me.

That is literally the same video I posted above, so yes, I did exactly as that video said to do on a 64bit OS, both Windows 2012 R2 Server and on a Windows 10 computer. Both would not allow the service to start. I receive an error this error:

![image](https://user-images.githubusercontent.com/89117407/129908526-6df41aaa-3fd5-4fef-9c7b-35c8b7d12d89.png)

**Comment by mnITguy** [comment]
I've tried changing the msconfig to load all drivers and services, that didn't work. 
I've tried changing the timeout threshold in the registry, also didn't work. 

I even tried using sc.exe to create the service instead of nssm, also received an error. I'm convinced v0.11.0 doesn't work for Windows, unless you have to have a specific build prior to 1909.

**Comment by glennzw** [comment]
It's hard to offer support on this as it's not a gophish specific problem. I assume gophish runs fine on the system without trying to start it asa service?

**Comment by KennethKali2020** [comment]
I have the same issue, it randomly stopped working for me too. Just launch it via cmd and leave it running. Since its a server, you shouldnt be restarting it anyways.

**Comment by mnITguy** [comment]
> I have the same issue, it randomly stopped working for me too. Just launch it via cmd and leave it running. Since its a server, you shouldnt be restarting it anyways.

Kenneth, what command are you using to launch it via cmd?

**Comment by KennethKali2020** [comment]
so if you are following the nssm method, then  gophish should already be unpacked in the C directory

cd \
cd gophish-v0.11.0-windows-64bit
gophish.exe

then it will start the service and it will tell you the temp password if not already set

**Comment by mnITguy** [comment]
> so if you are following the nssm method, then gophish should already be unpacked in the C directory
> 
> open admin command prompt
> 
> cd
> cd gophish-v0.11.0-windows-64bit
> gophish.exe
> 
> then it will start the service and it will tell you the temp password if not already set
> 
> then go to the gophish site, scroll down to getting started and click https://localhost:3333 from their page. Typing that into a URL does not work for me. Then bookmark that tab and you are good to go

 I've done all of that, doesn't matter what I do, the service doesn't fully start without an error. Instead it's in a paused state.

**Comment by KennethKali2020** [comment]
Are you saying that it doesn't start at all? If that is the case then you need to delete it and redownload it. Can you take a picture of what happens after you execute the command in the command prompt? And where is the server being hosted?

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to re-open.

**Comment by topherchris420** [comment]
i'm in the same position OP was in (it's in a paused state). how was this solved?
