### ISSUE TITLE
Phishing log timings was not in a order

### ISSUE THREAD

**Issue by sreekanth99850** [gophish/gophish#2286]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  11.0

Brief description of the issue: Phishing log timings was not in a order for some users. Sometimes submitted data time log Was coming first after that clicked link time is coming second . People was questioning about the timings  whether the logs is accurate or not . Could you please tell us why the timings are not in a order 
What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here


Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by atheriqbal** [comment]
Hi, can you give a screenshot of the timing? And are you using it in an enterprise environment?

**Comment by sreekanth99850** [comment]
Hi Atheriqbal,

In the below screenshot **Clicked link** time has came first  after **Email opened** time came. Without opening email how can a person click the link. Could you please help us to resolve the issue 

![image](https://user-images.githubusercontent.com/44702953/130060021-cd329610-47ec-431a-b4e9-cf911dbc974b.png)

**Comment by glennzw** [comment]
@sreekanth99850 What's probably happening is that some security application is scanning links in emails - thereby "clicking" the link. You can check what IP addresses are hitting the links to figure out the source.

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to re-open.
