### ISSUE TITLE
Session broke

### ISSUE THREAD

**Issue by TairaNoMasakado** [gophish/gophish#2288]
Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: **0.11.0**

Brief description of the issue: **Broke session**

What are you expecting to see happen? : **Nothing**

What are you seeing happen?  **When I give the command ./gophish it runs normally, but after a while the connection drops. I wanted gophish to be online all the time**

**Could someone help me solve**

**Comment by atheriqbal** [comment]
Hi,

Can you copy paste the log before it shuts down. Is there any error?

**Comment by TairaNoMasakado** [comment]
does not show any error, the process simply dies and I need to start again.

**Comment by atheriqbal** [comment]
Check logs.txt file. Does it contain any error?

**Comment by TairaNoMasakado** [comment]
No
