### ISSUE TITLE
Cannot send Test Email - connection reset by peer

### ISSUE THREAD

**Issue by lnenkov** [gophish/gophish#2289]
What version of Gophish are you using?: 
0.11.0 

Brief description of the issue: 
I am not able to send a test email. When I try to send a test email, I am receiving the following error message: Max connection attempts exceeded - read tcp xx.xx.xx.xx:33160->xx.xx.xx.xx:25: read: connection reset by peer

What are you expecting to see happen? :
To successfully send a test email.

What are you seeing happen?
A sent email

**Comment by atheriqbal** [comment]
Hi, which smtp are you using?

**Comment by lnenkov** [comment]
Hi,

I'm using my own smtp server.

**Comment by lnenkov** [comment]
A 2 weeks ago I was able to send emails through Gophish, and also the spoofing was working fine. And today when I tried to create a new campaign, I've received that error message. I already double-checked all of the settings - hostname, port, username, password, etc, and everything is fine. 
I don't know from where I need to start troubleshooting it.

**Comment by glennzw** [comment]
The message `error message: Max connection attempts exceeded` means that gophish is unable to connect to the host:port pair you entered for the SMTP server.

I'd suggest trying to connect manually (e.g with telnet) from the gophish server to make sure networking is OK.

**Comment by lnenkov** [comment]
I just tried with telnet and I'm not sure, but I think it's working. Here is the output from the terminal: 
220 mail.xxxxxxxxxxxx.ng ESMTP Postal/RALJIP

**Comment by glennzw** [comment]
Yes that means you're able to connect. Are you running the telnet command from the same computer that gophish is running on? If so, it should be able to connect.

**Comment by lnenkov** [comment]
Yes, I'm able to connect from Gophish server to email server.
I also checked the logs from the email server side and found the following:
root@mail:/opt/postal/log# tail smtp_server.log
[smtp.1:1662] [2021-08-24T12:23:25.144] ERROR -- : [MIW4CE] /opt/postal/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block in top_level'
[smtp.1:1662] [2021-08-24T12:23:25.144] ERROR -- : [MIW4CE] /opt/postal/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:125:in `run_with_threads'
[smtp.1:1662] [2021-08-24T12:23:25.144] ERROR -- : [MIW4CE] /opt/postal/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:110:in `top_level'
[smtp.1:1662] [2021-08-24T12:23:25.144] ERROR -- : [MIW4CE] /opt/postal/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:83:in `block in run'
[smtp.1:1662] [2021-08-24T12:23:25.144] ERROR -- : [MIW4CE] /opt/postal/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'
[smtp.1:1662] [2021-08-24T12:23:25.144] ERROR -- : [MIW4CE] /opt/postal/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:80:in `run'
[smtp.1:1662] [2021-08-24T12:23:25.144] ERROR -- : [MIW4CE] /opt/postal/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
[smtp.1:1662] [2021-08-24T12:23:25.144] ERROR -- : [MIW4CE] /opt/postal/vendor/bundle/ruby/2.6.0/bin/rake:23:in `load'
[smtp.1:1662] [2021-08-24T12:23:25.144] ERROR -- : [MIW4CE] /opt/postal/vendor/bundle/ruby/2.6.0/bin/rake:23:in `<main>'
[smtp.1:1662] [2021-08-24T12:23:33.410] DEBUG -- : [RALJIP]    Connection closed

I'm trying to find more information about those logs outputs, but currently, there isn't some relevant information. 
Do you have some idea or suggest next steps?

**Comment by glennzw** [comment]
Hmmm. Let's try rule out one variable at a time. It'd be useful if you could try some other SMTP server, e.g GMail (or even the dummy service MailHog). This would let us rule out gophish as the culprit.

But from your logs it does look like the mail server panics when gophish connects. The next step would be to stick a proxy in between gophish and the mailserver (or wireshark/tcpdump if cleartext) to have a look at the communications going back and forth. You could do this with socat:

`socat -v TCP-LISTEN:2501,fork,reuseaddr TCP:localhost:25`

In the above your real mailserver runs on port 25, and your socat listener is on 2501. Now point gophish to 2501 and you should be able to monitor gophish speaking to your mail server.

**Comment by lnenkov** [comment]
What do you mean with that "point to 2501"? - I couldn't find how to send test email on that port.

**Comment by glennzw** [comment]
If you're unfamiliar with socat and TCP/IP networking this might be tricky, but essentially socat can listen on a port, and send all network traffic to another host/port pair. So, your current setup:

`gophish =====> mail.server.com:25`

with the above socat command:

`gophish ====> socat:2501 ====> mail.server.com:25`

So you'd change your gophish config to point to mail.server.com:2501


Perhaps, before you start all that just verify that you can send emails through your mail server using telnet again:

```
telnet youremailserver.com 25
ehlo youremailserver.com
mail from: someone@youremailserver.com
rcpt to: friend@youremailserver.com
data
Subject: Testing my smtp server

Hello,

This is a test.

Goodbye.

.

```

**Comment by lnenkov** [comment]
Hi, I would like to thank you for the support so far. 
I tried to send email through telnet. Here is the output:
root@GoPhish:~# telnet xx.xx.xx.xx 25
Trying xx.xx.xx.xx...
Connected to xx.xx.xx.xx.
Escape character is '^]'.
220 mail.xxxxxxx ESMTP Postal/JGZCHJ
ehlo mail.xxxxxxxxx
250-My capabilities are
250-STARTTLS
250 AUTH CRAM-MD5 PLAIN LOGIN
mail from: test@xxxxx
250 OK
rcpt to: nenkov@xxxxxx
530 Authentication required

And I stuck on the authentication...

**Comment by glennzw** [comment]
OK cool so to authenticate you'd need to request `AUTH LOGIN`, and encode your username and password as base64. After your `ehlo`:

```
AUTH LOGIN
eW91clVzZXJuYW1l
eW91clBhc3N3b3Jk
```

where those two base64 values are your username and password. See https://www.ndchost.com/wiki/mail/test-smtp-auth-telnet

**Comment by lnenkov** [comment]
Hi, thank you for your patience and assistance.
I've completely reinstalled the SMTP server and currently, everything is working fine.

You can close the issue.

**Comment by glennzw** [comment]
Great glad to hear it!
