### ISSUE TITLE
Error Import Landing Page

### ISSUE THREAD

**Issue by TairaNoMasakado** [gophish/gophish#2294]
Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our documentation, which covers how to use Gophish.

What version of Gophish are you using?: **0.11.0**

Brief description of the issue: **Error when I need to import some website on landing page**

What are you expecting to see happen? : **Nothing**

What are you seeing happen? **template: template:85: function "searchMaxDuration" not defined**

Could someone help me solve

**Comment by atheriqbal** [comment]
hi, is the page accessible to the gophish instance?

**Comment by TairaNoMasakado** [comment]
I created a new email template and when I needed to save I found this error

**Comment by atheriqbal** [comment]
In the question you mentioned landing page. In comment, you mentioned new email template. Which one is it?
