### ISSUE TITLE
Authentication error with MFA

### ISSUE THREAD

**Issue by rickyrowing** [gophish/gophish#2295]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.10.1

Brief description of the issue: August 26th I had successfully launched a campaign with a customized template. When I came to work on August 31st 2021 I tried to launch a second campaign and I keep getting this error. "2021/08/31 14:54:18 http: TLS handshake error from 127.0.0.1:52883: remote error: tls: unknown certificate" Along with another error from outlook saying there is an authentication error. I understand the issue there is a MFA issue conflicting with my email. After doing some research I found how to use app password and tried to use that as my password to bypass the MFA but I am still getting the same error. 

What are you expecting to see happen? : I was expecting to send a phishing email to one person in my company. 

What are you seeing happen? Errors out when I attempt to send the email or even a test email to myself. 

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Create an office email, use the MFA (that Microsoft is starting to enforce as soon as you create your account.)
 * Step 2 - Send an email to your employees and watch it error out.

**Comment by atheriqbal** [comment]
Hey, are you able to send test email? What kind of environment are you using it in?

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to re-open.
