### ISSUE TITLE
URL Redirection - Track file

### ISSUE THREAD

**Issue by KevinUTNFRBA** [gophish/gophish#2297]
Hi, good Morning
We are using a campaign which uses an **external URL** in the phishing email, which downloads a file.
We have information about the opening of the email and the download of the file, **but the problem is that we do not have information about whether the user clicked on the link.**

Is there a way to redirect or encapsulate an EXTERNAL URL by tracking an internal gophish URL?

What version of Gophish are you using?:  0.10.1

**Comment by KevinUTNFRBA** [comment]
I hope my query is understood, any help would be appreciated!

**Comment by glennzw** [comment]
Hello - unfortunately there's no way for gophish to tell that an external link has been clicked. You *could* add some javascript to that external page to make a call back to the gophish server and 'click' the link, but that's the only solution I can think of.

Good luck!

**Comment by stepbysec** [comment]
Hello,
I am working on a similar use case scenario:
  - Gophish sends e-mails to users with a {{.URL}} placeholder, including a {{.Tracker}} to trace who read the e-mail.
  - When users click the link, they access landing page on Gophish server, so we can track who clicked.
  - Landing page is configured to redirect straight away to an external link that downloads the file

The landing page is configured with the below HTML code to do so:
```<html>
<head>
  <meta http-equiv="refresh" content="0; URL=https://www.whatever-target-you-want.com/file.ext"/>
</head>
<body>
File download in progress
</body>
</html>
```

I hope this helps answer your need.

My only issue here is to track who opens the file and enable macros.
Indeed, the file is static and cannot be configured per user with {{.URL}} placeholder.
