### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by TairaNoMasakado** [gophish/gophish#2298]
What version of Gophish are you using?: **0.11.0**

Brief description of the issue: **https://certbot.eff.org/cert-auto**
What are you expecting to see happen? : Nothing

I need to add an ssl certificate so that when the person clicks on the link they will be redirected to the gophish landing page with SSL certificate but the website https://certbot.eff.org/cert-auto is no longer available. Could you give me other options?

**Comment by atheriqbal** [comment]
Please follow [this](https://docs.getgophish.com/user-guide/installation) guide for SSL help. You can also use self signed certificates.

**Comment by glennzw** [comment]
@atheriqbal is spot on as usual.

I use Caddy, which works great.
