### ISSUE TITLE
invalid character 

### ISSUE THREAD

**Issue by TairaNoMasakado** [gophish/gophish#2300]
What version of Gophish are you using?: 0.11.0

Brief description of the issue: Error when I need execute ./gophish

What are you expecting to see happen? : invalid character 'g' looking for beginning of value

What are you seeing happen? was working normally, I suddenly went to start the service and the following error happened

**Comment by asaqib27** [comment]
Could you please share the config.json file and paste the logs. That would be helpful.

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to re-open if you're still having trouble.
