### ISSUE TITLE
mac build linux error

### ISSUE THREAD

**Issue by vonjk** [gophish/gophish#2302]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

0.11.0
Brief description of the issue: 

What are you expecting to see happen? :

What are you seeing happen?

# bitbucket.org/liamstask/goose/lib/goose
../../../Go/pkg/mod/bitbucket.org/liamstask/goose@v0.0.0-20150115234039-8488cc47d90c/lib/goose/dialect.go:119:7: undefined: sqlite3.Error

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 - 
 I tried to modify the parameter compilation and still reported an error
![image](https://user-images.githubusercontent.com/30076142/132360009-01cdd0b0-0f46-45f3-ac64-219093ec25f4.png)
![image](https://user-images.githubusercontent.com/30076142/132360052-c70e098f-f052-4541-8880-ae459e50d077.png)

As long as you cross build, there will be an error
 
![image](https://user-images.githubusercontent.com/30076142/132362885-f12ee8ff-6dbf-4dd1-aa33-a3cc5cf0bd7e.png)

**Comment by asaqib27** [comment]
It seems a problem with CGO and Cross Compiling. Because SQLite is developed using C language. when using cross-compiling it may happen some of the features don't work as expected. To overcome this issue you can xgo2 for cross-compiling. 

**Here, is an example:**
`xgo2 --targets=darwin/amd64 gophish`

**Links:**
xgo --> https://github.com/karalabe/xgo
I have used another version which is --> https://github.com/youchainhq/xgo2
