### ISSUE TITLE
Installing Gophish

### ISSUE THREAD

**Issue by matthewlyonsazpiral** [gophish/gophish#2303]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.11.0

Brief description of the issue: I've run the gophish.exe on the server but it hasn't installed

What are you expecting to see happen? : Some sort of installation process

What are you seeing happen? A command window appears and disappears

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by asaqib27** [comment]
The Gophish binary is not installable it is something that runs the program creates an initial admin and starts the server. You can have a look at installation doc here https://docs.getgophish.com/user-guide/installation

**Comment by matthewlyonsazpiral** [comment]
Thanks Adbul but that doesn’t make much sense to me.

I think I’ll just look again at a paid service.

Regards,

Matthew.
DD: +353 61 517 222
Mob: +353 87 0908485
www.azpiral.com
[azpiral_signature-logo-small]

**Comment by asaqib27** [comment]
that's purely your choice just wanted to let you know if you are very fresher user of GoPhish that Gophish is web application and not standalone / desktop application thus it's binary is not installable. Because it doen't make sense to create installable binary for web application.

**Comment by asaqib27** [comment]
that's purely your choice I just wanted to let you know (if you are a very fresher user of GoPhish) that Gophish is a web application and not a standalone/desktop application thus its binary is not installable. Because it doesn't make sense to create an installable binary for a web application.

**Comment by matthewlyonsazpiral** [comment]
But it should show something running right?
I’ve run the application gophish.exe and when I browse to https://localhost:3333 nothing happens?
***@***.***

Regards,

Matthew.
DD: +353 61 517 222
Mob: +353 87 0908485
www.azpiral.com
[azpiral_signature-logo-small]

**Comment by asaqib27** [comment]
yes definitely, and it actually shows logs and if you run it for the very first time you can also see the temporary password for the admin user too.  Consider the below logs as example. It generated when I run gophish first time. 

I first build gophish application then execute it.

`go build gophish.go`

`./gophish 
time="2021-09-15T13:18:19+05:30" level=warning msg="No contact address has been configured."
time="2021-09-15T13:18:19+05:30" level=warning msg="Please consider adding a contact_address entry in your config.json"
goose: migrating db environment 'production', current version: 0, target: 20201201000000
OK    20160118194630_init.sql
OK    20160131153104_0.1.2_add_event_details.sql
OK    20160211211220_0.1.2_add_ignore_cert_errors.sql
OK    20160217211342_0.1.2_create_from_col_results.sql
OK    20160225173824_0.1.2_capture_credentials.sql
OK    20160227180335_0.1.2_store-smtp-settings.sql
OK    20160317214457_0.2_redirect_url.sql
OK    20160605210903_0.2_campaign_scheduling.sql
OK    20170104220731_0.2_result_statuses.sql
OK    20170219122503_0.2.1_email_headers.sql
OK    20170827141312_0.4_utc_dates.sql
OK    20171027213457_0.4.1_maillogs.sql
OK    20171208201932_0.4.1_next_send_date.sql
OK    20180223101813_0.5.1_user_reporting.sql
OK    20180524203752_0.7.0_result_last_modified.sql
OK    20180527213648_0.7.0_store_email_request.sql
OK    20180830215615_0.7.0_send_by_date.sql
OK    20190105192341_0.8.0_rbac.sql
OK    20191104103306_0.9.0_create_webhooks.sql
OK    20200116000000_0.9.0_imap.sql
OK    20200619000000_0.11.0_password_policy.sql
OK    20200730000000_0.11.0_imap_ignore_cert_errors.sql
OK    20200914000000_0.11.0_last_login.sql
OK    20201201000000_0.11.0_account_locked.sql
time="2021-09-15T13:20:10+05:30" level=info msg="Please login with the username admin and the password bd1e083de2f1dd54"
time="2021-09-15T13:20:10+05:30" level=info msg="Creating new self-signed certificates for administration interface"
time="2021-09-15T13:20:10+05:30" level=info msg="Starting IMAP monitor manager"
time="2021-09-15T13:20:10+05:30" level=info msg="Starting phishing server at http://127.0.0.1:8080"
time="2021-09-15T13:20:10+05:30" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
time="2021-09-15T13:20:10+05:30" level=info msg="Starting new IMAP monitor for user admin"
time="2021-09-15T13:20:10+05:30" level=info msg="TLS Certificate Generation complete"
time="2021-09-15T13:20:10+05:30" level=info msg="Starting admin server at https://127.0.0.1:3333"`

**Comment by asaqib27** [comment]
yes definitely, and it actually shows logs and if you run it for the very first time you can also see the temporary password for the admin user too. Consider the below logs as example. It generated when I run gophish first time.

I first build gophish application then execute it.

go build gophish.go

./gophish
goose: migrating db environment 'production', current version: 0, target: 20201201000000  
OK    20160118194630_init.sql
OK    20160131153104_0.1.2_add_event_details.sql  
OK    20160211211220_0.1.2_add_ignore_cert_errors.sql  
OK    20160217211342_0.1.2_create_from_col_results.sql  
OK    20160225173824_0.1.2_capture_credentials.sql  
OK    20160227180335_0.1.2_store-smtp-settings.sql
OK    20160317214457_0.2_redirect_url.sql  
OK    20160605210903_0.2_campaign_scheduling.sql  
OK    20170104220731_0.2_result_statuses.sql  
OK    20170219122503_0.2.1_email_headers.sql  
OK    20170827141312_0.4_utc_dates.sql  
OK    20171027213457_0.4.1_maillogs.sql  
OK    20171208201932_0.4.1_next_send_date.sql  
OK    20180223101813_0.5.1_user_reporting.sql  
OK    20180524203752_0.7.0_result_last_modified.sql  
OK    20180527213648_0.7.0_store_email_request.sql  
OK    20180830215615_0.7.0_send_by_date.sql  
OK    20190105192341_0.8.0_rbac.sql  
OK    20191104103306_0.9.0_create_webhooks.sql  
OK    20200116000000_0.9.0_imap.sql  
OK    20200619000000_0.11.0_password_policy.sql  
OK    20200730000000_0.11.0_imap_ignore_cert_errors.sql  
OK    20200914000000_0.11.0_last_login.sql  
OK    20201201000000_0.11.0_account_locked.sql  
time="2021-09-15T13:22:51+05:30" level=info msg="Please login with the username admin and the password ace5d9e31506ecdb"  
time="2021-09-15T13:22:51+05:30" level=info msg="Starting admin server at https://127.0.0.1:3333"  
time="2021-09-15T13:22:51+05:30" level=info msg="Starting phishing server at http://127.0.0.1:8080"  
time="2021-09-15T13:22:51+05:30" level=info msg="Starting IMAP monitor manager"  
time="2021-09-15T13:22:51+05:30" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"  
time="2021-09-15T13:22:51+05:30" level=info msg="Starting new IMAP monitor for user admin"

**Comment by glennzw** [comment]
@asaqib27 is spot on here. @matthewlyonsazpiral; you need to run the gophish.exe from a command prompt (not double click it).

**Comment by glennzw** [comment]
@matthewlyonsazpiral Feel free to email me if you're looking for commercial or pre-setup gophish options.

**Comment by toddwaldorf** [comment]
unable to get windows service to run error code 3
