### ISSUE TITLE
Static Assets Problem

### ISSUE THREAD

**Issue by josprou** [gophish/gophish#2305]
What version of Gophish are you using ?:
v0.11.0

Brief description of the issue:
I'm using the precompiled Windows version of Gophish and there is no static / endpont folder to add dependencies to target pages. Is this version compatible with dynamic assets?

What are you expecting to see happen? :
I would like to be able to use dynamic assets.

What are you seeing happen?
I have created the static / endpoint folder manually and added the website dependencies, but it doesn't load the content.

Provide landing page below:

html
** Thanks for reaching out! We're happy to help resolve issues as quickly as possible. **

** Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment. **

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation] (https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using ?:

Brief description of the issue:

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
<! DOCTYPE html> <html> <head> <meta charset = "utf-8" /> <meta http-equiv = "X-UA-Compatible" content = "IE = edge" /> <meta content = "width = device-width, initial-scale = 1, maximum-scale = 1, user-scalable = no "name =" viewport "/>
<link href = "http://192.168.0.100/static/bootstrap.min.css" rel = "stylesheet" />
<link href = "http://192.168.0.100/static/animate.min.css" rel = "stylesheet" />
<link href = "http://192.168.0.100/static/reset.min.css" rel = "stylesheet" />
<link href = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" rel = "stylesheet prefetch" />
<link href = "app-esp.css" rel = "stylesheet" />
<title> Welcome, User Access | Datadec Online </title>
</head>
<body class = "hold-transition skin-blue sidebar-mini">
<nav class = "navbar navbar-default esp-navbar"> <! - <div class = "container-fluid"> ->
<div class = "navbar-header"> <a class="navbar-brand esp-navbar-brand" href="http://www.datadec.es"> <img class = "img-responsive" src = " http://192.168.0.100/static/logo_datadec.png "/> </a> </div>

<div id = "navbarUserInfoId" style = "display: none;">
<ul class = "nav navbar-nav">
<li class = "dropdown" style = "margin-top: 10px;"> </li>
</ul>

<ul class = "nav navbar-nav navbar-right" style = "margin-right: 0px;">
<li class = "dropdown" style = "margin-top: 10px;"> <a class="dropdown-toggle profile-image-cn" data-toggle="dropdown" href="#"> <img class = " profile-image "src =" ./ img / avatar.png "style =" vertical-align: bottom; "/> </a>

<ul class = "dropdown-menu">
<li> <a href="javascript:Main.changePassword()"> <span> Change password </span> </a> </li>
<li> <a href="javascript:Main.logOut();"> <span> Logout </span> </a> </li>
</ul>
</li>
</ul>
</div>
<! - </div> -> </nav>

<div class = "text-right pt-0 mt-0">
<p> <small> 1.23 </small> </p>
</div>
<! - Router view ->

<div id = "content"> </div>

<p> <input id = "version" type = "hidden" value = "1.23" /> <input id = "hiddenUser" type = "hidden" value = "" /> <input id = "hiddenDomain" type = " hidden "value =" "/> <script src =" http://192.168.0.100/static/jquery.min.js "> </script> <script src =" http://192.168.0.100/static/bootstrap .min.js "> </script> <script src =" lib / vue / vue.min.js "> </script> <script src =" lib / vue / vue-resource.min.js "> </ script> <! - Noty jquery plugin -> <script type = "text / javascript" src = "http://192.168.0.100/static/jquery.noty.packaged.min.js"> </script> < script type = "text / javascript" src = "http://192.168.0.100/static/noty-datadec.js"> </script> <! - app-js -> <script src = "http: / /192.168.0.100/static/app-esp.js?v=1.0.0 "> </script> </p>


</body> </html>
```

Thanks

**Comment by mcab** [comment]
> I'm using the precompiled Windows version of Gophish

If you bundle the files within the `/static/` folder before building gophish, they should theoretically be available. No guarantee that this works, though.

Alternatively, creating and importing a [landing page](https://docs.getgophish.com/user-guide/documentation/landing-pages) will point the dependencies in the right place.

**Comment by glennzw** [comment]
You can place static assets inside the `/static/endpoint` folder. e.g:

```bash
$ echo helloWorld > static/endpoint/foo.txt
```
<img width="427" alt="Screenshot 2021-09-24 at 16 05 26" src="https://user-images.githubusercontent.com/3966613/134697688-03be6d2f-3deb-47eb-be3d-2ed2cf232337.png">
