### ISSUE TITLE
Cannot send to a custom domain- varying error messages

### ISSUE THREAD

**Issue by carteraspear** [gophish/gophish#2306]
What version of Gophish are you using?: 8.0. I wanted to use the latest version but I was having some sign-in credential issues that other forums said was resolved by using 8.0.
edit: I've now tried and replicated the issue across all versions post 8. so, 8,9,10,11

Brief description of the issue: Gophish doesn't seem to like sending to custom domains. I created a sender and it sent just fine, no issues to my personal gmail address, but it does not send to my company email address. I get a few different errors depending on what sending port I specify. 

What are you expecting to see happen? : I'm expecting a test email in my work email inbox. It's important that my workplace domain will work- that's where the phishing test is going, lol

What are you seeing happen?

554 5.7.1 : Recipient address rejected: Access denied 
error message when using smtp.google.com:587

"550 5.1.1 The email account that you tried to reach does not exist. Please try 5.1.1 double-checking the recipient's email address for typos or 5.1.1 unnecessary spaces. "
error message when using smtp.google.com:25

" 530 5.7.0 Authentication Required."
error message when using smtp.gmail.com:25 or :587

"554 Email rejected"
error message when using smtp.mail.yahoo.com:587

It might also be relevant to say that I am absolutley certain I spelled my work email address correctly :)

Please provide any terminal output that may be relevant below: (I edited this a little bit to censor my work email address) 

```
time="2021-09-17T15:32:20-07:00" level=error msg="530 5.7.0 Authentication Required. Learn more at\n5.7.0  https://support.google.com/mail/?p=WantAuthError d22sm7228084pgi.73 - gsmtp"
time="2021-09-17T15:32:20-07:00" level=info msg="127.0.0.1 - - [17/Sep/2021:15:32:20 -0700] \"POST /api/util/send_test_email HTTP/2.0\" 500 187 \"https://127.0.0.1:3333/sending_profiles\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36\""
2021/09/17 15:33:12 http: TLS handshake error from 127.0.0.1:51166: remote error: tls: unknown certificate
time="2021-09-17T15:33:12-07:00" level=warning msg="530 5.7.0 Authentication Required. Learn more at\n5.7.0  https://support.google.com/mail/?p=WantAuthError 9sm5287777pjs.14 - gsmtp" code=530 email="\"MY FULL NAME\" <carter@WORKEMAIL.net>"
time="2021-09-17T15:33:12-07:00" level=error msg="530 5.7.0 Authentication Required. Learn more at\n5.7.0  https://support.google.com/mail/?p=WantAuthError 9sm5287777pjs.14 - gsmtp"
time="2021-09-17T15:33:12-07:00" level=info msg="127.0.0.1 - - [17/Sep/2021:15:33:12 -0700] \"POST /api/util/send_test_email HTTP/2.0\" 500 185 \"https://127.0.0.1:3333/sending_profiles\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36\""
2021/09/17 15:34:01 http: TLS handshake error from 127.0.0.1:60295: remote error: tls: unknown certificate
time="2021-09-17T15:34:02-07:00" level=warning msg="554 Email rejected" code=554 email="\"MY NAME\" <carter@WORKEMAIL.net>"
time="2021-09-17T15:34:02-07:00" level=error msg="554 Email rejected"
time="2021-09-17T15:34:02-07:00" level=info msg="127.0.0.1 - - [17/Sep/2021:15:34:01 -0700] \"POST /api/util/send_test_email HTTP/2.0\" 500 73 \"https://127.0.0.1:3333/sending_profiles\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36\""
2021/09/17 15:34:37 http: TLS handshake error from 127.0.0.1:60566: remote error: tls: unknown certificate
time="2021-09-17T15:34:37-07:00" level=warning msg="554 Email rejected" code=554 email="\"MY FULL NAME\" <carter@WORKEMAIL.net>"
time="2021-09-17T15:34:37-07:00" level=error msg="554 Email rejected"
time="2021-09-17T15:34:37-07:00" level=info msg="127.0.0.1 - - [17/Sep/2021:15:34:37 -0700] \"POST /api/util/send_test_email HTTP/2.0\" 500 73 \"https://127.0.0.1:3333/sending_profiles\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36\""
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Create a new sender profile- add a name, fill in the "from" field.
 * Step 2 - Fill in the host field with a smtp.something.something:AportNumber
 * Step 3 - click "send a test email" 
 * Step 4- enter my tester email. If I test using my personal google address, it sends with no problem. If I use my work email address, it comes back with an error that changes based on what port I use as described above. 

Thanks yall, I appreciate you :)

**Comment by mcab** [comment]
> but it does not send to my company email address. I get a few different errors depending on what sending port I specify.

It seems like you're trying to send this through a Google Workspace-backed account. If you wish to do such, your organization will have to allow [routing outbound mail using SMTP relay](https://support.google.com/a/answer/2956491?hl=en).

On top of that, you may have to either allow [less secure apps](https://support.google.com/accounts/answer/6010255?hl=en) or generate an [App Password](https://support.google.com/accounts/answer/185833) if MFA is enabled on the Google account.

**Comment by carteraspear** [comment]
Thanks for the reply- what about this makes you think this is a google workspace issue? 

The only reason I’m asking is because our company doesn’t use google workspace at all. We’re an independent IT company and one of our primary tasks for our clients is email hosting so we have our own setup that’s totally separate from any web based email- does that help clarify?

**Comment by mcab** [comment]
> what about this makes you think this is a google workspace issue?

Apologies, I assumed that the sending out via a custom domain via Gmail's relay would exclusively be solo account or Google Workspace. A little trickier with the setup presented.

> email hosting so we have our own setup that’s totally separate from any web based email

Authenticating against that email setup might be the case here, but the limit of my knowledge stops here without any more information. 😅

**Comment by glennzw** [comment]
This is difficult to debug as gophish is just reporting the errors received from the mail server. Can you try manually sending an email with the same host/ip/credentials? (e.g. https://michlstechblog.info/blog/mail-connect-tls-encrypted-to-a-smtp-server-by-telnet/)

Also, try sending an email to https://www.mail-tester.com/. It's likely Google/Yahoo are dropping your emails due to bad SPF/DKIM/etc.

Hope that helps.

**Comment by glennzw** [comment]
Closing as haven't heard back, feel free to re-open.
