### ISSUE TITLE
cannot access gophish admin server using ionos ip address

### ISSUE THREAD

**Issue by mahamzaidi6** [gophish/gophish#2308]
hi. Afterwards When I tried to access the admin server using the localhost and without ssh i accessed the page easily. I am trying to access gophish admin server using ssh from my kali linux system and the ip address of the vps server provided by ionos but firefox gives me the error 
`Firefox can’t establish a connection to the server at ip_address:port_number. `

I dont understand what's the issue because according to the terminal I am able to successfully start both the phishing and the admin server. But as the browser fails to the load the page the terminal shows the following log entry:

> [19/Sep/2021:19:15:19 +0000] \"GET / HTTP/1.1\" 404 19 \"\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36\"

I performed all the steps according to this [tutorial](https://www.youtube.com/watch?v=S6S5JF6Gou0&t=1246s) and am using the latest version of gophish.

**Comment by atheriqbal** [comment]
Hi, 

What does your config.json looks like? Is the IP accessible?

**Comment by glennzw** [comment]
Closing as haven't heard back, feel free to re-open.
