### ISSUE TITLE
GoPhish crashing

### ISSUE THREAD

**Issue by iteam-Technology** [gophish/gophish#231]
GoPhish crashes when creating a new campaign. I am using the localhost:3333 as listener to test functionality. 

Also, when testing email - I cant mask with the "from" email address. Shows up as the authenticated users email when I receive the test email. Wondering if something wrong im doing. Using gmail smtp server to authenticate.

**Comment by jordan-wright** [comment]
Hey there!

Thanks for the report. Can you see what the error message is in the output on your terminal when you launch a campaign? My "3-point jump shot" guess is that this is related to #193. You might try building from source and attempting to save your template to see if this is the issue.

Also, Gmail is special in that it will (to my knowledge) always show your authenticated user as the "From" sender. It sets a "X-Gmail-Sender" header or something like that with your spoofed addr. You might try using their unauthenticated smtp gateway and see if that helps at all (if you're sending to gmail addresses).

**Comment by jordan-wright** [comment]
Hey @iteam-Technology - did this answer your question? I'll keep the issue open for another day or so until we hear back.

**Comment by jordan-wright** [comment]
Hey @iteam-Technology - since we haven't heard back, I'm going to go ahead and close this out.

Let us know if you have any questions.
