### ISSUE TITLE
Import errror python

### ISSUE THREAD

**Issue by mrrobotnl** [gophish/gophish#2311]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.11.0

Brief description of the issue: 
With python I get the following error when tyring to make a connection: 

What are you expecting to see happen? :
I get a import error when I use the python api (most likely due to a circular import) 

What are you seeing happen?
ImportError: cannot import name 'Gophish' from partially initialized module 'gophish' (most likely due to a circular import) (C:\Users\gophish.py)

I am currently using this script: 

from gophish import Gophish
api_key = ""
api = Gophish(API_KEY, host='https://secret-website:3333', verify=False)

**Comment by edermi** [comment]
I assume this is because your script is also named `gophish`. Renaming your script will probably resolve the issue.

**Comment by glennzw** [comment]
Sounds like @edermi has the right idea here.

Closing as haven't heard back, feel free to re-open.
