### ISSUE TITLE
Mailgun & gophish error codes

### ISSUE THREAD

**Issue by th3-hatt3r** [gophish/gophish#2312]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: Latest version

Brief description of the issue: When trying to send a test email after importing all settings from mailgun I keep getting Max connection attempts exceeded - 535 Authentication failed

What are you expecting to see happen? : a test email to go through

What are you seeing happen? Max connection attempts exceeded - 535 Authentication failed

**Comment by nejec** [comment]
How did you configure your sending profile?

**Comment by glennzw** [comment]
Closing as haven't heard back, feel free to re-open.
