### ISSUE TITLE
i can't get back in my account and SQL lite is not working on my pc and i am using v0.7.1

### ISSUE THREAD

**Issue by obitojnr** [gophish/gophish#2314]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue: 

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by atheriqbal** [comment]
Hey, 
Your issue is not clear. Have you forgotten your password?

**Comment by obitojnr** [comment]
The default password isn't working so i can get in and seems like i forgot
the password but the default password is not working i haven't changed the
password yet.

**Comment by glennzw** [comment]
You can delete the gophish.db database file if you want a fresh empty db. If there's data in there that you need, then you can do a password reset like so:

```
§ yum install -y sqlite ||apt-get install -y sqlite3 libsqlite3-dev
§ sqlite3 gophish.db 'update users set hash="$2a$10$IYkPp0.QsM81lYYPrQx6W.U6oQGw7wMpozrKhKAHUBVL4mkm/EvAS" where username="admin";'
```
(reset admin password to 'gophish').
