### ISSUE TITLE
Gophish landing page not capturing credentials

### ISSUE THREAD

**Issue by yazramadan** [gophish/gophish#2316]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

0.11.0

Brief description of the issue: 

I have created a landing page but when I launch a campaign the credentials are not captured. I have tried resolving it by following this link (https://github.com/gophish/gophish/issues/1443 and https://github.com/gophish/gophish/issues/1105) but nothing. I would really appreciate some help asap as I am under time constraint to fix this.

Thank you

What are you expecting to see happen? :

Campaign captures creds

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

[Outlook password change - broken (copy 1).txt](https://github.com/gophish/gophish/files/7245846/Outlook.password.change.-.broken.copy.1.txt)

**Comment by atheriqbal** [comment]
Hi, can you use a simple landing page with only bare minimum code? 
```
<form action="" method="post" name="form">

<input name="username" placeholder="email@test.com" type="email"/>
<input name="password" placeholder="Password" type="password"/>

<button class="color-button" type="submit" value="Submit">Sign in</button>
</form>

```
See if this is capturing the credentials.

**Comment by yazramadan** [comment]
> Hi, can you use a simple landing page with only bare minimum code?
> 
> ```
> <form action="" method="post" name="form">
> 
> <input name="username" placeholder="email@test.com" type="email"/>
> <input name="password" placeholder="Password" type="password"/>
> 
> <button class="color-button" type="submit" value="Submit">Sign in</button>
> </form>
> ```
> 
> See if this is capturing the credentials.

Hello, the landing page is mimicking outlook so it has to look similar to it. The code you've included wouldn't fit the campaign, is it possible to keep the design of the form but still capture credentials? It has been done before but I lost the code for it. I understand that I may need to remove javascript but i'm not too familiar with it. Any help would be much appreciated.

thanks!

**Comment by atheriqbal** [comment]
Are you sure it was the same page with 3 text fields?

I am asking to use the bare minimum for testing only, just to check if the feature is working. Then we can work our way towards designing the page and eliminating and JS related issues.

**Comment by yazramadan** [comment]
> Are you sure it was the same page with 3 text fields?
> 
> I am asking to use the bare minimum for testing only, just to check if the feature is working. Then we can work our way towards designing the page and eliminating and JS related issues.

Hi Yes, I've tested that landing page before and it works. Creds are captured.

**Comment by atheriqbal** [comment]
Okay so that means there is some problem with the scripting in that page. Ill try over the weekend with my instance, and let you know if it works.

**Comment by yazramadan** [comment]
Thank you very much, this would help me a lot. I really appreciate it.

**Comment by glennzw** [comment]
The problem was that giant blob of JavaScript, there's code in there to override the POST functionality. Also, your button on the form submission wasn't a submit button. I removed the JS, and changed the button, and it works for me now:

Landing page:
<img width="812" alt="Screenshot 2021-12-15 at 16 53 10" src="https://user-images.githubusercontent.com/3966613/146219456-bdcdc569-b7a8-47df-bf04-324f5675af8c.png">

Data submitted:
<img width="906" alt="Screenshot 2021-12-15 at 16 52 26" src="https://user-images.githubusercontent.com/3966613/146219326-5d9ea82a-5e4d-4149-b024-9fa16c231c5e.png">

Here's the code: [Outlook.password.change_fixed.html.txt](https://github.com/gophish/gophish/files/7720854/Outlook.password.change_fixed.html.txt)
