### ISSUE TITLE
How do I set the email sending interval?

### ISSUE THREAD

**Issue by leiqichn** [gophish/gophish#2317]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.11

Brief description of the issue: 
My email address has a limit on the number of emails that can be sent per hour(100 per hour). I want to set the interval for sending emails to 40 seconds.

What are you expecting to see happen? :
Send no more than 100 emails per hour

What are you seeing happen?
So many messages were sent quickly that subsequent messages failed to be sent

 This is very urgent to me, I hope you can answer me as soon as possible, thank you very much!

**Comment by horllste** [comment]
Why not get 2 to 3 or more email addresses as sender for your sending profiles enough to send to your numbers of targeted email address and send them once

**Comment by vonjk** [comment]
https://github.com/gophish/gophish/pull/1557

**Comment by glennzw** [comment]
Thanks for reaching out. Sp @vonjk is right - there's a pull request and discussion to add the sending rate in https://github.com/gophish/gophish/pull/1557. In the meantime you can just populate the 'send by' field and do some mental maths to spread out the sending.
