### ISSUE TITLE
Unable to create new landing pages on fresh install - Built from Source (Ubuntu 20.04)

### ISSUE THREAD

**Issue by jstigerwalt** [gophish/gophish#2319]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

0.11

Brief description of the issue: 

When trying to create a landing page, getting 404's. This is captured from the logs:
```
\"GET /js/src/vendor/ckeditor/ckeditor.js HTTP/2.0\" 404 
\"GET /js/src/vendor/ckeditor/adapters/jquery.js HTTP/2.0\" 404
```
What are you expecting to see happen? :

Trying to create a landing page on a fresh install. Built from source code.

What are you seeing happen?

Multiple things here:

The page will load but it will always spin.

![image](https://user-images.githubusercontent.com/29151777/135691105-b5d13630-7171-4dcf-ae84-cf27210fc296.png)

 I am able to click on create page and then presented with this screen which is broken. You can not submit data or do anything.

![image](https://user-images.githubusercontent.com/29151777/135691213-a915862c-d5e5-4da6-b98e-45608de4724f.png)

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
time="2021-10-01T22:02:33Z" level=info msg="IP - - [01/Oct/2021:22:02:33 +0000] \"GET /landing_pages HTTP/2.0\" 200 2566 \"https://IP:6874/templates\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36\""
time="2021-10-01T22:02:33Z" level=info msg="IP - - [01/Oct/2021:22:02:33 +0000] \"GET /js/src/vendor/ckeditor/ckeditor.js HTTP/2.0\" 404 19 \"https://IP:6874/landing_pages\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36\""
time="2021-10-01T22:02:33Z" level=info msg="IP- - [01/Oct/2021:22:02:33 +0000] \"GET /js/src/vendor/ckeditor/adapters/jquery.js HTTP/2.0\" 404 19 \"https://IP:6874/landing_pages\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36\""
time="2021-10-01T22:02:33Z" level=info msg="IP- - [01/Oct/2021:22:02:33 +0000] \"GET /js/dist/app/landing_pages.min.js HTTP/2.0\" 200 1853 \"https://IP:6874/landing_pages\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36\""
```
Looking at the file location, my other Gophish server installed on Ubuntu 18.04 experienced the same issue but was closed. Checking to see if the files are in the right dir turned this up:

![image](https://user-images.githubusercontent.com/29151777/135691654-5ebafe8b-01de-4dd0-a964-d480fb494cc2.png)

I cant find the following files anywhere building with source code:
```
/js/src/vendor/ckeditor/ckeditor.js
/js/src/vendor/ckeditor/adapters/jquery.js 
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Install GO
 * Step 2 - Install GCC
 * Step 3 - go get github.com/gophish/gophish
 * Step 4 - cd go/pkg/mod/github.com/gophish/gophish@v0.11.0/
 * Step 5 - go build
 * Step 6 - ./gophish
 * Step 7 - Setup Admin account and try to create a landing page - issue
 
 I built from source code yesterday. I have multiple servers running Gophish, this is the 2nd time out of 5 servers I have experienced this.

**Comment by jstigerwalt** [comment]
By adding in the vendor folder from downloading the source code fixed the issue. 

![image](https://user-images.githubusercontent.com/29151777/135692808-c65c1c68-6c1a-4d6f-8d9a-021bee42551a.png)

The only thing I did funny on this server was tried to install gophish without GCC and then remove the "go" folder. Here is my command history:

```
    3  wget https://golang.org/dl/go1.17.1.linux-amd64.tar.gz
    4  rm -rf /usr/local/go && tar -C /usr/local -xzf go1.17.1.linux-amd64.tar.gz
    5  nano ~/.profile
    6  export PATH=$PATH:/usr/local/go/bin
    7  go version
    8  go get github.com/gophish/gophish
    9  apt update
   10  apt install build-essential
   11  go get github.com/gophish/gophish
   12  cd go
   13  ls
   18  rm go
   19  rm go -r
   20  ls
   21  go get github.com/gophish/gophish
   22  ls
   23  cd go/pkg/mod/github.com/gophish/gophish@v0.11.0/
   24  ls
   25  go build
   26  ls
   27  cat config.json
   
   screen -S gophish            <- (Started Gophish in Screen)
   
```

**Comment by gudbes** [comment]
Hello @jstigerwalt 
I have the same problem as you on my debian.
I can't fix the problem.
Can you please give me the path where you get the vendor folder and the path where you copy it.
I tried to copy the vendor folder from ~/go/pkg/mod/github.com/gophish/gophish@v0.11.0/static/js/src but I only have the app folder in it and my destination folder seems to be /opt/goapps/pkg/mod/github.com/gophish/gophish\@v0.11.0/

I thank you in advance for your help.

Gudbes

**Comment by Speedbuilder** [comment]
I had the same issue described as here above but I was able to locate the issue and fix it:

For context: I also had to build the binary from source and moved the `gophish` binary to the following location: `~/gophish/bin`.

The `vendor` directory is not included when you `go get github.com/gophish/gophish` for some reason. So in order to have the vendor directory and its files, I cloned the [Gophish repository](https://github.com/gophish/gophish) locally and `mv`'ed the `vendor` directory to my `~/gophish/pkg/mod/github.com/gophish/gophish@v0.11.0/static/js/src`.

Please not that it is **not** required to rebuild the `gophish` ELF, just `Ctrl + C` the `gophish` process and rerun it with `./gophish`. This is what solved the issue for me, no more infinite loading of the Landing Pages and no more errors in the JS console.

**Comment by gudbes** [comment]
Hello @Speedbuilder,

Thank you for your answer.
To get around the problem I switched to the windows version because I needed gophish occasionally.
Thanks for taking the time to share this solution.

Have a Nice day.
