### ISSUE TITLE
Website Importing

### ISSUE THREAD

**Issue by iHasanYK** [gophish/gophish#232]
Hi Jordan,

when you clone a website, it will add the source code of the webpage as it's, i would like to ask if you are planning to include a site cloner to download the page and change the reference links inside it.

it will be much faster to load the page from GoPhish server (if you have internal GoPhish Server in your company) rather than going to internet to get some contents from there, in spite of it will look more real.

best regards
hasan

**Comment by rfdevere** [comment]
Just my opinion but this level of customisation would be narrowing a use down quite a lot.

I do feel the pain though, Old OWA login is a classic example of a page that I've always had problems with reference links and the images displaying correctly. It would be handy to have this feature but it wouldn't be used much. I've learnt to minimise this task with wget -mk.... You should really check that out! Downloads the whole site with local reference links ;-) 

Richard

**Comment by jordan-wright** [comment]
Agreed with @rfdevere. For now, this type of cloning is out of the scope for gophish.

Perhaps in the future, we'll take a look at implementing this, but it's not currently on the roadmap.

Thanks for the suggestion, though!

**Comment by iHasanYK** [comment]
Thanks for response gents.
i got the point

**Comment by securitygeneration** [comment]
fwiw, I too would love to see a full page clone (included static content) from within GoPhish
