### ISSUE TITLE
Landing Page saying not authorized

### ISSUE THREAD

**Issue by francescouk** [gophish/gophish#2320]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: Latest

Brief description of the issue: Landing page resulting in not authorized. Follow the message that the browser returns:

```
{"message": "You are not authorized to view this page."}

```

What are you expecting to see happen? : The actual page which has been cloned using gophish

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
http2: server: error reading preface from client XXX.XXX.XXX.XXX:6970: read tcp 10.0.0.1:443->XXX.XXX.XXX.XXX:6970: i/o timeout

goose: no migrations to run. current version: 20201201000000
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
Hi there! It's not too obvious at what point you're getting stuck. Do you get that message when you try clone the site, or once you've cloned it and browsed to it that's what you see?

If you have successfully cloned it please share the HTML here.

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen.
