### ISSUE TITLE
How to capture only first two and last two characters of the password written?

### ISSUE THREAD

**Issue by dsin-casa** [gophish/gophish#2322]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
**Gophish v0.11.0**
Brief description of the issue: 
**Not an issue but would like partial password capture settings.**
What are you expecting to see happen? :
**Would Like to capture only the first two and last two characters of the password written. like : "2p........3!"**
What are you seeing happen?
Full password in plaintext.

**Comment by glennzw** [comment]
Interesting question - I've done some work around this, and it's fairly straight forward with client side javascript. Here's my solution: https://github.com/glennzw/BreachCount

If you just want the first to chars to be sent back you'd need to modify the code, but I don't think it should be too hard (https://github.com/glennzw/BreachCount/blob/master/breachcount.js).
