### ISSUE TITLE
Can we collect data via the Google Form

### ISSUE THREAD

**Issue by sadeegr** [gophish/gophish#2323]
Hey,
Can we import a Google form to our landing page and collect the submitted data directly?

**Comment by atheriqbal** [comment]
I dont think so. It takes certain parameters, username and password. Google form has its now set of fields and names.

**Comment by nejec** [comment]
I guess you can create a redirect landing page and use a pre-filled google forms link. This would open Google Forms page, however `gophish` would no longer be included in the flow.

**Comment by glennzw** [comment]
I'm not sure what your end objective is @sadeegr, but you could just put your Google form URL in the landing page parameter of the campaign. Or load it inside an iframe of your landing page, but I don't see the benefit of this.
