### ISSUE TITLE
Gmail shows open even when the email is not opened on gmail

### ISSUE THREAD

**Issue by intotheblues** [gophish/gophish#2325]
hi i have setuped gophish on windows server with a domain, i am having 2 issues 
1) when i send campaign, campaign sent to gmail shows opened even when its not opened ye
2) Clicks on link doesn't work, i have a email template with download now button any ideas how can i integrate links click with that download button in my email template

**Comment by atheriqbal** [comment]
Hi,

Are you in an Enterprise environment?
Please send your email template for testing.

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to re-open if you're still having trouble.
