### ISSUE TITLE
550 domain listen in dbl.samphaus.org 

### ISSUE THREAD

**Issue by g4sp4ch0** [gophish/gophish#2326]
**What version of Gophish are you using?:** 

0.11.0

**Brief description of the issue:** 

error 550 for blacklisting in spamhaus but it is checked and it does not exist in this list. On the poste.io mail server I can send mail without any problem.

**What are you expecting to see happen? :**

campaigns to be sent

**What are you seeing happen?**

no mail is sent from gophish

Thanks

**Comment by nejec** [comment]
Did you check your IP/from domain on the [blacklists](https://mxtoolbox.com/blacklists.aspx) as well?

How did you configure your sending profile?
