### ISSUE TITLE
Feature request: Deactivate URL after X submits

### ISSUE THREAD

**Issue by ElleshaHackett** [gophish/gophish#2331]
I think it would be beneficial if there is an option that deactivates a personal URL when one or a set number of submits has been succeeded. For example in the scenario that you want to inform one person but with the risk of him or her showing it to everyone else or forwarding it. I think personally I would like to deactivate it after two or three submits. For the case that someone forgets it, or retries later.

**Comment by glennzw** [comment]
Thanks for the idea @ElleshaHackett! I don't think this is a feature that would be widely used enough to warrant its implementation, but you could probably implement it via the API for your particular use cases.
