### ISSUE TITLE
Documentation Text is Screwed up

### ISSUE THREAD

**Issue by SpyderZ** [gophish/gophish#2335]
The documentation site has all its text messed and corrupted, it's impossible to make anything out when viewing it on Brave (Chrome) browser on Big Sur.

![Screen Shot 2021-10-20 at 6 18 57 PM](https://user-images.githubusercontent.com/1954540/138185718-a5312213-006c-42cc-b906-01a51fb2213a.png)

Safari, however, works fine.

**Comment by nejec** [comment]
works for me as well: macOS + Safari

**Comment by glennzw** [comment]
@SpyderZ The documentation looks fine, might be your browser doing something weird?
