### ISSUE TITLE
Translate the project (EN --> FR)

### ISSUE THREAD

**Issue by SwitHak** [gophish/gophish#234]
Hi,

I'm french student interested by your project and want to help you. I would like to translate your project in FRench language. I think many enterprises or SOC can be interested by your project.

How i can, do you have namming tables or others ?

I have already installed the latest release yesterday. So i can try my work immediatly.

Have an Nice Day !

@SwitHak

**Comment by SwitHak** [comment]
EDIT: I try to work on documentation PDF but if you have the docx file, i take it 
To translate, it's be more easy.

**Comment by jordan-wright** [comment]
Hey @SwitHak - Thanks for the offer to translate! I'm eventually going to get around to putting a markdown version of the docs on here, just haven't had the time yet. You can keep track of #173 for the status.

That would be the the place to add a translation.

**Comment by SwitHak** [comment]
Hi, I agree with this proposal, when do you release the next version of Gophish?

**Comment by jordan-wright** [comment]
Good question. I'm working through a pretty big feature right now with #223, but hopefully once that's done it'll just be a few minor things to knock out before the next release.
