### ISSUE TITLE
Maximum number of users per campaign

### ISSUE THREAD

**Issue by lnenkov** [gophish/gophish#2340]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  0.10.1

Brief description of the issue: I would like to know what is the maximum number of users that I can run in one campaign. 
I have around 5000 users

What are you expecting to see happen? : To work correctly.

**Comment by edermi** [comment]
We've done campaigns with 5000 users and Gophish. You may want to use MySQL as DB backend and a reverse proxy for static content hosting.

**Comment by glennzw** [comment]
I've done a campaign with 20k users. The backend has no problem with this, but you'll bump into trouble in the browser when you try view a campaign that large (see https://github.com/gophish/gophish/pull/2019)

**Comment by lnenkov** [comment]
Thanks for the answers guys. I just tried with 500 users and it worked fine. My worries are about the DB backend, because I'm using SQLite.

**Comment by glennzw** [comment]
I'd recommend using MySQL, but SQLite performs pretty well:

"I have SQLite database 3.3 GB in size with 25million rows of stored numeric logs and doing calculations on them, it is working fast and well."

https://stackoverflow.com/questions/1546947/maximum-number-of-rows-in-a-sqlite-table
