### ISSUE TITLE
External IP's logged for link clicked do not always populate

### ISSUE THREAD

**Issue by littlejob** [gophish/gophish#2344]
**What version of Gophish are you using?:** 
Current Version: 0.10.1

**Brief description of the issue:** 
When campaign links are clicked, source IP's are not logged and recorded in all cases. 

**What are you expecting to see happen? :**
I expect to see public IP's listed for all clicks logged. 

What are you seeing happen?
![image](https://user-images.githubusercontent.com/3580651/140333367-49f2f8c2-776b-4bcc-ae6f-537c75aaae4e.png)

Regardless of template used, landing page, user targets, issue occurs for every campaign.

**Comment by littlejob** [comment]
has anyone else experienced this same behavior?

**Comment by atheriqbal** [comment]
Not really, can you explain with more details. Have you made any changes to the code?

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen.
