### ISSUE TITLE
issues opening the landing page from the phishing email

### ISSUE THREAD

**Issue by mkarbian** [gophish/gophish#2347]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
I downloaded it 3 month ago so i think its 0.11.0
Brief description of the issue: 
cant reach the landing page
What are you expecting to see happen? :
open a static PNG image or open a html file that has src in it with the png file.
What are you seeing happen?
after 1000 attempts browser cant reach this page
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Ill make it short
<html>
<title></title>
<body>
<p><img alt="" src="http://server/static/capture2.png"
style=...............</p>

</body>
</html>

option 2
<html>
<title></title>
<body>
<p><img alt="" src="http://server/static/test.html"
style=...............</p>

</body>
</html>
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - tried to move the files to /static path
 * Step 2 - tried any manipulation on the src on the landing page and on the email template.
 * Step 3 - tried different variation in the URL section when i start new campaign
   
 I don't know what to do here, pls help.
all targets can reach the server with http\https do i need more permissions for other services?
last thing is everything has to be stored locally,

**Comment by glennzw** [comment]
Hello! I'm not entirely sure I understand your question. Are you saying you're unable to load static images on your landing page?

For static assets to be accessible add them to the `gophish/static/endpoint/` folder, and then in the browser hit your `gophishserver.com/static/file.png`

e.g: 

`echo helloWorld > gophish/static/endpoint/foo.txt`

<img width="433" alt="Screenshot 2021-12-15 at 15 03 21" src="https://user-images.githubusercontent.com/3966613/146200618-bac0ecd7-1f90-420c-ba92-403a3edeb23d.png">

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen.
