### ISSUE TITLE
issues with istalling gophish on vps server

### ISSUE THREAD

**Issue by garycotler** [gophish/gophish#2349]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue: 

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by garycotler** [comment]
![Screenshot 2021-11-08 at 6 30 23 PM](https://user-images.githubusercontent.com/87995743/140925075-20394292-693b-4b75-812f-4dfc5a22d1bb.png)

**Comment by garycotler** [comment]
i have had trouble with this for days

**Comment by edermi** [comment]
Please read the [documentation](https://docs.getgophish.com/user-guide/), it covers these steps.

**Comment by garycotler** [comment]
thank you  i just got it solved my network was slow not making it work all good now
