### ISSUE TITLE
Does Gophish need a new maintainer?

### ISSUE THREAD

**Issue by eickeh** [gophish/gophish#2350]
Hi there,

I've noticed that development of gophish basically stopped early this year. The last commit is from march and the last release from 2020. Even pull request do not get merged. That is really sad but I hope it's not the end of this great tool. I really like gophish and would be very happy to see the commit history fill again. 

@jordan-wright @glennzw , can you tell me the current status of gophish? Does it need a new maintainer to restart the devolopment?

**Comment by eickeh** [comment]
ping

**Comment by mrrobotnl** [comment]
> ping

pong

**Comment by atheriqbal** [comment]
I guess they are busy elsewhere. They will respond soon.

**Comment by glennzw** [comment]
Hi there. Thanks for reaching out. I do need to get on top of the outstanding pull requests etc, hoping to make some time now that I'm off from $DAYJOB for the holidays.
