### ISSUE TITLE
add external information within the dashboard or campaign 

### ISSUE THREAD

**Issue by mrrobotnl** [gophish/gophish#2352]
Hey Developers I have a question. Can I edit the main dashboard? I want to add an extra source of information within the dashboard for a better overview. 
Is it perhaps possible to post information from a webhook within the dashboard? I made a solution for the attachment problem and I want to make better dashboard overview from a: the results from the phising campaign and b: the external webhook that tells me when somebody opened the attachments. 
If this is not possible, could I extract the information from the gophish server and place it in an external dashboard. And if this is possible what (opensource) dashboard would you guys as developers recommend? 
I currently make use of the latest version of gophish. Thanks in advance for reading the question.

**Comment by glennzw** [comment]
Hello! Yeah feel free to edit the main dashboard :) It's all API driven, and pulled into the dashboard via JavaScript calls. I'd recommend cracking open Developer Tools, a webproxy, and browsing the non-minified .js files.
