### ISSUE TITLE
Images not showing in emails

### ISSUE THREAD

**Issue by Awaces** [gophish/gophish#2353]
What version of Gophish are you using?: 
0.11.0

Brief description of the issue: 
Hi,
I'm setting up a gophish campaign where I inject images from my phishing domain:
https://phishing-domain/static/image.jpg
They show up in the HTML editor, but they are not available when sending out the emails

What are you expecting to see happen? :
Images inside emails

What are you seeing happen?
No images

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
<img alt="Atlassian" src="https://phishing-domain.com/static/b64R5YLsB.png" style="border-style: none; vertical-align: top; width: 193px; height: 24px;" />
```

**Comment by abid28june** [comment]
most of the email services provider such as (outlook) will automatically disable the images tag unless user click on it and trust to view the image, focus on your template and make it more attractive so that users can click without viewing the images.

**Comment by Awaces** [comment]
> u

Hi Abid

Thanks for your reaction.
I do realize that part. 
However, there's no option to allow or enable the images.

Kind regards

**Comment by VaishaEYE** [comment]
Hi, happy GoPhish user here. Images encoded in base64 are showing perfectly fine in Outlook without user interaction. See https://www.w3docs.com/snippets/html/how-to-display-base64-images-in-html.html for an explanation on how to encode images inline in img tags.

**Comment by Awaces** [comment]
> Hi, happy GoPhish user here. Images encoded in base64 are showing perfectly fine in Outlook without user interaction. See https://www.w3docs.com/snippets/html/how-to-display-base64-images-in-html.html for an explanation on how to encode images inline in img tags.

Works like a charm!
Thanks!

**Comment by mrrobotnl** [comment]
What i've heard is that if you translate the image to base64 it also helps with outlook especially
