### ISSUE TITLE
invalid Json structure 

### ISSUE THREAD

**Issue by abid28june** [gophish/gophish#2355]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

version v0.11.0

Brief description of the issue: 

all were working perfectly, but today morning when i starting a new campaign with gophish, suddenly it gives an error at the time of lunching campaign, plz see attached error.

 
![image](https://user-images.githubusercontent.com/57210170/143182427-2d999f1d-ed72-4584-a618-927a88684ddc.png)

**Comment by abid28june** [comment]
resolution found,  stopped the services from services manger in windows and then execute the gophish.exe file from cmd, it works fine now.

**Comment by abid28june** [comment]
have the same issue again.

**Comment by atheriqbal** [comment]
Can you help us to reproduce this? Share email template and landing page

**Comment by abid28june** [comment]
resolved, never cut the execution start date, let it be as is.. if you do so you will face such error.
