### ISSUE TITLE
unable to start Gophish afer few days :(

### ISSUE THREAD

**Issue by starbase073** [gophish/gophish#2356]
I have running a Gophish server on ubuntu after a few days it stop withstarting :(

**Log:**
time="2021-11-25T09:30:31Z" level=info msg="92.66.190.47 - - [25/Nov/2021:09:30:31 +0000] \"GET /static/adobe/login.html HTTP/1.1\" 304 0 \"\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edg/96.0.1054.34\""
time="2021-11-25T09:30:31Z" level=info msg="92.66.190.47 - - [25/Nov/2021:09:30:31 +0000] \"GET /dialog/res/css/common/double-click-prevention.css HTTP/1.1\" 404 19 \"http://gophish.it-pg.nl/static/adobe/login.html\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edg/96.0.1054.34\""
time="2021-11-25T09:30:31Z" level=info msg="92.66.190.47 - - [25/Nov/2021:09:30:31 +0000] \"GET /dialog/res/js/common/double-click-prevention.js HTTP/1.1\" 404 19 \"http://gophish.it-pg.nl/static/adobe/login.html\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edg/96.0.1054.34\""
goose: no migrations to run. current version: 20200730000000
time="2021-11-25T09:32:47Z" level=error msg="record not found"
time="2021-11-25T09:32:47Z" level=fatal msg="record not found"

**What version of Gophish are you using?:** 
 current version: 20200730000000
 
**Brief description of the issue:** 
Stop starting after 9 days 

**What are you expecting to see happen? :**
service start up

**What are you seeing happen?**
**Please provide any terminal output that may be relevant below:**
goose: no migrations to run. current version: 20200730000000
time="2021-11-25T09:32:47Z" level=error msg="record not found"
time="2021-11-25T09:32:47Z" level=fatal msg="record not found"

**Please provide as many steps as you can to reproduce the problem:**
Option 1:  sudo service start gophish
Option 2:  sudo ./opt/gophish/gophish

I am lost wht he not want to start up any more, can some help me?

**Comment by atheriqbal** [comment]
Have you been able to start?

**Comment by glennzw** [comment]
This is a tricky one, as you say it was working and then stopped. I'd recommend trying to start with a fresh database file (rename gophish.db to gophish_backup.db and restart).

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen.
