### ISSUE TITLE
Clicked Link False Positives

### ISSUE THREAD

**Issue by ac205** [gophish/gophish#2357]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: v0.11.0

Brief description of the issue: Getting Clicked Link results when users did NOT click the link.

What I have noticed is everyone that is getting the false positive shows an older version of Chrome was used to click the link which is NOT the actual version they have installed on their computers.

[https://i.imgur.com/FFrxgYe.png](https://i.imgur.com/FFrxgYe.png)
[https://i.imgur.com/L8H0UtM.png](https://i.imgur.com/L8H0UtM.png)
[https://i.imgur.com/yg1AZTg.png](https://i.imgur.com/yg1AZTg.png)
 
It also shows the email was opened multiple times which is a bit odd, and in the last screenshot shows it was randomly opened later in the evening on a Windows 8 computer again with a random outdated version of Chrome?

Any idea what would cause this or how to resolve as the software is useless if it is giving random false positives :(

**Comment by ac205** [comment]
Ok I think I have discovered the issue. We use Office 365 and have the Report Message button enabled. It appears when someone clicks the Report Message button is must be then triggering Microsoft to do a scan of the email and links which in turn is opening the link and giving the user the 'Clicked Link' result and most likely is run in a sandbox vm which could have an outdated/random version of Chrome on it.

**Comment by atheriqbal** [comment]
Hi @ac205 , yes that is the case. Microsoft scans and opens the links in Sandbox environment.

**Comment by Sethu-code** [comment]
Hi @ac205 do you know a way to stop Microsoft from scanning the links? I'm also having the same issue and getting false positives and I can't exclude all people who reported email since we have users who clicks on links and then report it

**Comment by glennzw** [comment]
Yup that's exactly the issue, Microsoft is 'clicking' the links. I know others have mentioned disabling this on the 365 side, so you may need to search through old issues. Other options are:

 * Implement firewall rules to only allow IPs from your org to access the phish site
 * Deploy some JavaScript to discern between a browser click and a command line tool (although MS may be running these links in a browser). (see https://github.com/gophish/gophish/issues/1559#issuecomment-526602895)
