### ISSUE TITLE
my gophish user and groups doesn't accept .csv files it says i am attempting to  write a readonly database

### ISSUE THREAD

**Issue by garycotler** [gophish/gophish#2358]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue: 

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by garycotler** [comment]
![Screen Shot 2021-11-26 at 11 07 01 AM](https://user-images.githubusercontent.com/87995743/143607585-c1546faa-4e82-4551-9304-f72834914341.png)

what do i do

**Comment by atheriqbal** [comment]
Hi, where are you bringing your users from? Any database ?

**Comment by glennzw** [comment]
Thanks for reaching out. Are you able to add users one at a time (not via the CSV upload) ? My guess is not, as the gophish.db file is read only. You may need to change its permissions, or run gophish as the same user you installed as (or run with sudo).

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen.
