### ISSUE TITLE
email templates

### ISSUE THREAD

**Issue by netwestconsulting** [gophish/gophish#236]
if the email template has a URL (ex.) www.company.com/passwd-change  and that is your landing page all goes well , but if proof point or URL defense intercepts the message for running a scan or proof

it pre-pends the following 
https://urldefense.proofpoint.com/v2/url?u=https- (then the website)

Is this something that is fixed in the API ?

**Comment by jordan-wright** [comment]
Can you expand a bit on what you're seeing? It sounds like this is something that Proofpoint is catching, such as the url displayed not being the same that is actually pointed to (a common phishing technique).

**Comment by jordan-wright** [comment]
Hey @netwestconsulting - I haven't heard back in a while, so I'm going to go ahead and close this out.

Let us know if you have any questions! It sounds like there is something about the email template that is tipping off Proofpoint that it might be a forgery.
