### ISSUE TITLE
Gophish 0.11.0 version windows default password

### ISSUE THREAD

**Issue by danish31** [gophish/gophish#2360]
I have installed Gophish v.0.11.0 in windows 10 using nssm . It is installed as a service. So while running the service I am unable to see the binary output to get default username and password.

Hence I am unable to login to Gophish.

Please advice how to proceed?

**Comment by glennzw** [comment]
Good question. I'd recommend running gophish from the command prompt first to see the username and password, and then running it as a service. I hope that helps!

**Comment by wolxler** [comment]
you can tell exactly how to run

**Comment by glennzw** [comment]
@danish31 Closing this out as haven't heard back.

@wolxler Please open a new issue for the trouble you're having. Thanks!
