### ISSUE TITLE
SMTP configuration using cloud based mailbox

### ISSUE THREAD

**Issue by MrSMTP** [gophish/gophish#2361]
Hi,

i discovered Gophish last week and i could be usefull on the entreprise that i am working for. Howerver, we mitigated the our mailbox to the cloud a few months ago and the SMTP+ port are "hidden".

Is there a way to set up the program using an API graph?

Thank you for reading my question

**Comment by glennzw** [comment]
Hello! Unfortunately SMTP is our only sending mechanism. You can setup your own SMTP server, which might help: https://www.atlantic.net/vps-hosting/how-to-configure-postfix-as-a-send-only-smtp-server-on-ubuntu-20-04/

Good luck!
