### ISSUE TITLE
Phishing Event not get counts, Running on Localhost

### ISSUE THREAD

**Issue by aukhan288** [gophish/gophish#2363]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
=> Gophish v0.11.0

Brief description of the issue: 
I have trying to running gophish in localhost, then started the campaign. Email already sent and successfully captured/ counted "email sent" in dashboard, but for other event : "Email open", "Clicked link" etc. there are not captured.
What are you expecting to see happen? :

What are you expecting to see happen? :
It's should be capture too, isn't it ?

What are you seeing happen?
There's no captured for event : email open, clicked link etc, Only captured for Email sent

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Email Template:

<html>
<head>
	<title></title>
</head>
<body>
<p>Dear User;</p>

<p>I hope you will fine.</p>

<p>we are contacting from facebook team. in last couple days we raised a problem with your account wich is login from multiple unsecured IP&#39;s.</p>

<p>So kindly varify your account&nbsp;for safety.</p>

<p><a href="{{.URL}}">Click Here</a></p>

<p>{{.Tracker}}</p>
</body>
</html>








Landing Page:


<html><head>
	<title></title>
	<base href="http://localhost/test/"/>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet"/><script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script><script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
<form action=""><input name="__original_url" type="hidden" value="http://localhost/test//action_page.php"/>
<div class="form-group"><label for="email">Email address:</label> <input class="form-control" id="email" placeholder="Enter email" type="email"/></div>

<div class="form-group"><label for="pwd">Password:</label> <input class="form-control" id="pwd" placeholder="Enter password" type="password" name="password"/></div>

<div class="form-group form-check"><label class="form-check-label"><input class="form-check-input" type="checkbox"/> Remember me </label></div>
<button class="btn btn-primary" type="submit">Submit</button>

<p>{{.Tracker}}</p>
</form>
</div>


</body></html>

Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
> "Email open", "Clicked link" etc. there are not captured.

Are the emails being delivered to the inbox? Are you able to click the links and see the landing page?

What SMTP server are you using? If you're hosting all of this on your localhost, and it's not internet accessible, this maybe part of the problem.

**Comment by aukhan288** [comment]
Yes i received the email and also able to open link and see the landing page.
but not get the response of email open, click link and fill form data.

Yes i m using on localhost

**Comment by aukhan288** [comment]
I am closing this issue because i resolve my issue.
Thanks
