### ISSUE TITLE
putting admin interface behind reverse proxy which does authentication

### ISSUE THREAD

**Issue by rful011** [gophish/gophish#2364]
Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
v 0.11.0

Brief description of the issue: 
we want to use our sso system to authenticate and authorise connections to the admin interface.  i.e the app is firewalled so the only way to get to it is via the proxy that does the authentication.  

The question is does gophish look for any of the standard Authentication headers and skip the login prompt.  If so which?

Is there a recommended way of doing this?

**Comment by glennzw** [comment]
> The question is does gophish look for any of the standard Authentication headers and skip the login prompt. If so which?

No we don't have this capability. I'm not sure of a way to implement SSO, but I'll leave this open in case anyone else has some ideas.
