### ISSUE TITLE
page can not access

### ISSUE THREAD

**Issue by topsekadmin** [gophish/gophish#2365]
root run command ./gophish , display error:
![856e5d4be8d124cb8ea2c73143126b2](https://user-images.githubusercontent.com/59950798/145318805-669cbb42-640e-486c-9617-56c3ea5a4426.png)

page can not access, other page can access
![ef5a474583851833f73913655635284](https://user-images.githubusercontent.com/59950798/145318728-6477e6dd-de43-4990-9c60-1e84c24d1794.png)

please help me, thank you

**Comment by atheriqbal** [comment]
What does ps aux | grep gophish show?

**Comment by glennzw** [comment]
You don't have permission to bind to port 80, you need to run the command as root:

```
sudo ./gophish
```
