### ISSUE TITLE
Gophish will not install

### ISSUE THREAD

**Issue by eeore39648** [gophish/gophish#2368]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 11

Brief description of the issue: I have downloaded the Gophis file, I have extracted. My issue is when I double click gophish.exe, a CMD window popsup but then immediately goes away.
What do I do to install gophish?

What are you expecting to see happen? : a window showing that gophish is installing

What are you seeing happen? A window breifly popsup, then immediately goes away.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by atheriqbal** [comment]
Please check the logs file. Is there anything it it? And are you downloading the binary?

**Comment by eeore39648** [comment]
No log file. Where is the Binary? 
See attachment. This is where I am downloading the zip file.I have downloaded several times. Extracted several times. When attempting to open. A CMD window breifly popsup, thenm immediately goes away.
    On Sunday, December 12, 2021, 10:55:52 PM CST, atheriqbal ***@***.***> wrote:  
 
 


Please check the logs file. Is there anything it it? And are you downloading the binary?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by glennzw** [comment]
Your attachment didn't come through. But try running the binary from a command prompt, not double clicking it. ie open up cmd.exe, navigate to the directory, and then run gophish.exe. Hope that helps.

**Comment by smcStevesmc** [comment]
I can not get it to do anything, I tried both the source and the zip file. I have the gophish.go but it won't open, what am I not doing correctly?

**Comment by glennzw** [comment]
@smcStevesmc Please open a new issue, with more details of the exact commands you've run and problem you're facing.

**Comment by glennzw** [comment]
Closing out as haven't heard back from the original author, feel free to re-open if you're still having trouble and can supply those logs.
