### ISSUE TITLE
Can't reach the login page and Unix Executable File not working in terminal (Mac)?

### ISSUE THREAD

**Issue by Joefly1** [gophish/gophish#2369]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: v0.11.1

Brief description of the issue: 
Forgive any lack of knowledge--I'm rather a noobie when it comes to all of this.
I was able to reach to successfully run GoPhish and reach the login page https://127.0.0.1:3333 

Now when I go to the login page it says "Site can't be reached." Also noticed I can't properly run the Unix Executable File.

What are you expecting to see happen? :
To be able to successfully reach the login page 

What are you seeing happen?
Below is what happens when I attempt to reach the login page
![image](https://user-images.githubusercontent.com/95936363/145632932-91b72e85-821a-4cd6-9152-141f6f2ae7a2.png)

This is the terminal text when I run the gophish executable file:

Last login: Fri Dec 10 10:59:00 on ttys000
/Users/josephfeely/Desktop/gophish-v0.11.0-osx-64bit\ \(1\)/gophish ; exit;     
josephfeely@Josephs-MacBook-Air ~ % /Users/josephfeely/Desktop/gophish-v0.11.0-osx-64bit\ \(1\)/gophish ; exit;
time="2021-12-10T13:03:43-05:00" level=fatal msg="open ./VERSION: no such file or directory"
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by glennzw** [comment]
Could you try running the executable from the directory itself. i.e:

```
cd /Users/josephfeely/Desktop/gophish-v0.11.0-osx-64bit\
./gophish
```

**Comment by glennzw** [comment]
Closing out as haven't heard back, feel free to reopen.
