### ISSUE TITLE
API Integration - PHP Script error

### ISSUE THREAD

**Issue by m4dw0lf** [gophish/gophish#237]
Hello Guys,

I'm creating a script in PHP to make some communications with the gophish API, I'm following the documentation but I'm also having some problems. I'm about 7 hours trying to solve this but I don't have any idea of what is going on.

Can you guys help me ? I modified my script to show to you guys.

```
<?php

$url = 'http://x.x.x.x:3333/api/campaigns/?api_key=123ec63dc9f8cf5c802ec17c8f7b6d7cd639ca4237064ee55ca5edf421d7c41b';

$ch = curl_init($url);

$url1 = 'http://x.x.x.x:3333';

$attachments = array(
    'id' => 1,
    'name' => 'Example',
    'content' => 'Hello, world!',
    "type" => 'text/plain',

);
$templatevalues = array(
  'id' => 5,
  'name' => 'Banco - x',
  'subject' => '{{.FirstName}}, blablabla  - blablabla',
  'text' => '',
  'html' => '<html><head></head><body>This is a test message!</body></html>',
  'attachments' => array($attachments),
  'modified_date' => '2016-04-08T19:00:00.000000Z',
);


$resultsvalues = array(
    'id' => 1,
    'email' => "123123@gmail.com",
    'first_name' => 'Igor',
    'last_name' => 'Rincon',
    'status' => 'Email Sent',
    'ip' => '8.8.8.8',
    "latitude" => 0,
    'longitude' => 0,

);

$timeline = array(
    'id' => 1,
    'email' => '123123@gmail.com',
    'time' => '2016-04-08T19:00:00.000000Z',
    'message' => 'Campaign Created',
);

$page = array(
  'id' => 4,
  'name' => 'Bank - x',
  'html' => '<html><head></head><body>This is a test message!</body></html>',
  'modified_date' => '2016-04-01T00:52:26.938735538-03:00',
);


$smtp = array(
  'id' => 1,
  'host' => 'smtp.test.ws:587',
  'username' => 'contact@test.ws',
  'password' => 'gophish',
  'from_address' => 'Contact <contact@test.ws>',
);

$campanha = array(
    'id' => 19,
    'name' => 'Test - X',
    'created_date' => '2016-04-08T19:00:00.000000Z',
    'completed_date' => '2016-04-08T19:00:00.000000Z',
    'template' => $templatevalues,
    'page' => $page,
    'status' => 'Emails Sent',
    'results' => array($resultsvalues),
    'timeline' => array($timeline),
    'smtp' => $smtp,
    'url' => $url1,
);



$jsonDataEncoded = json_encode(array($campanha));

echo $jsonDataEncoded;

curl_setopt($ch, CURLOPT_POST, 1);

curl_setopt($ch, CURLOPT_POSTFIELDS, $jsonDataEncoded);

curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json'));

$result = curl_exec($ch);

```

The result is:

`[{"id":19,"name":"Test - X","created_date":"2016-04-08T19:00:00.000000Z","completed_date":"2016-04-08T19:00:00.000000Z","template":{"id":5,"name":"Banco - x","subject":"{{.FirstName}}, blablabla - blablabla","text":"","html":"<\/head>This is a test message!<\/body><\/html>","attachments":[{"id":1,"name":"Example","content":"Hello, world!","type":"text\/plain"}],"modified_date":"2016-04-08T19:00:00.000000Z"},"page":{"id":4,"name":"Bank - x","html":"<\/head>This is a test message!<\/body><\/html>","modified_date":"2016-04-01T00:52:26.938735538-03:00"},"status":"Emails Sent","results":[{"id":1,"email":"123123@gmail.com","first_name":"Igor","last_name":"Rincon","status":"Email Sent","ip":"8.8.8.8","latitude":0,"longitude":0}],"timeline":[{"id":1,"email":"123123@gmail.com","time":"2016-04-08T19:00:00.000000Z","message":"Campaign Created"}],"smtp":{"id":1,"host":"smtp.test.ws:587","username":"contact@test.ws","password":"gophish","from_address":"Contact "},"url":"http:\/\/x.x.x.x:3333"}]
`

I test in this site: http://jsonlint.com/

And the message is: Valid JSON

I'm receving this message from Gophish:
```
{
  "message": "Invalid JSON structure",
  "success": false,
  "data": null
}
```

**Comment by m4dw0lf** [comment]
For better visualization:

```
[
    {
        "id": 19,
        "name": "Test - X",
        "created_date": "2016-04-08T19:00:00.000000Z",
        "completed_date": "2016-04-08T19:00:00.000000Z",
        "template": {
            "id": 5,
            "name": "Banco - x",
            "subject": "{{.FirstName}}, blablabla  - blablabla",
            "text": "",
            "html": "<\/head>This is a test message!<\/body><\/html>",
            "attachments": [
                {
                    "id": 1,
                    "name": "Example",
                    "content": "Hello, world!",
                    "type": "text\/plain"
                }
            ],
            "modified_date": "2016-04-08T19:00:00.000000Z"
        },
        "page": {
            "id": 4,
            "name": "Bank - x",
            "html": "<\/head>This is a test message!<\/body><\/html>",
            "modified_date": "2016-04-01T00:52:26.938735538-03:00"
        },
        "status": "Emails Sent",
        "results": [
            {
                "id": 1,
                "email": "123123@gmail.com",
                "first_name": "Igor",
                "last_name": "Rincon",
                "status": "Email Sent",
                "ip": "8.8.8.8",
                "latitude": 0,
                "longitude": 0
            }
        ],
        "timeline": [
            {
                "id": 1,
                "email": "123123@gmail.com",
                "time": "2016-04-08T19:00:00.000000Z",
                "message": "Campaign Created"
            }
        ],
        "smtp": {
            "id": 1,
            "host": "smtp.test.ws:587",
            "username": "contact@test.ws",
            "password": "gophish",
            "from_address": "Contact "
        },
        "url": "http:\/\/x.x.x.x:3333"
    }
]
```

**Comment by jordan-wright** [comment]
Hey @m4dw0lf, do all of the campaign items (smtp, landing page, etc.) exist before using them in the campaign?

You need to create each of those items before trying to use them, otherwise it will complain. Searching the code, I see that error being thrown on ```models.PostCampaign()```, so my guess is that the function is seeing that the items don't exist and is complaining.

I would agree that's not the best error message :smile: 

Let me know if that helps. Glad to see you using the API!

**Comment by m4dw0lf** [comment]
@jordan-wright Do you agree with me that I can just see what is in:

http://x.x.x.x:3333/api/campaigns/18?api_key=123ec63dc9f8cf5c802ec17c8f7b6d7cd639ca4237064ee55ca5edf421d7c41b

and use this information to generate my code ? I'm asking this because some fields that I have accessing the URL don't have in docummentation.

Another example,

In docummentation (https://getgophish.com/documentation/api/#campaigns-campaigns-post)  we don't have the field: 

"capture_credentials": true,

So I don't have to point this in my code, right ?

Thank you!

**Comment by jordan-wright** [comment]
We can definitely be more clear in the docs.

When creating objects such as a Template, all the required fields should be documented. Everything else, if excluded will take their default values. In this case, ```capture_credentials``` will be set to ```false``` if not included.

The code to create a campaign works by looking up all the objects by name and using those values. So really all you need when creating a campaign is the name attribute of the template, landing page, smtp profile, etc. Don't bother filling in the text, html, etc. We look all that up anyways :smile:

**Comment by m4dw0lf** [comment]
Ok...

Just one more question:

If I don't want to use attachment, can I just put:

attachment: null, ?

Thank you!

**Comment by jordan-wright** [comment]
You can leave it out altogether, I believe.

**Comment by m4dw0lf** [comment]
Ok...

I will try null or the way that is in the docummentation.

In the doc I see:

```
"results": [
      {
        "id": 1,
        "email": "foo@example.com",
        "first_name": "John",
        "last_name": "Doe",
        "status": "Email Sent",
        "ip": "1.2.3.4",
        "latitude": 0,
        "longitude": 0
      }
```

The ID is different when I look at the campaign already created:

```
 "status": "In progress",
  "results": [
    {
      "id": "4fc03983683a63591af5b4ee5edaa0d2dc02a0e15bfa613500cd5768db98eecf",
      "email": "m4d123123@gmail.com",
      "first_name": "Igor",
      "last_name": "Rincon",
      "position": "CTO",
      "status": "Sent",
      "ip": "",
      "latitude": 0,
      "longitude": 0
    },
```

I think that the content of the id doesn't make difference, right ?

**Comment by jordan-wright** [comment]
That's the "rid" that is generated randomly for every target in a campaign. It's what you'll see at the end of your tracking and landing page links.

**Comment by m4dw0lf** [comment]
Ok... Can I have your e-mail ? Maybe we can make some business for you help my team.

**Comment by jordan-wright** [comment]
You bet - you can always reach me at hi@getgophish.com.

**Comment by jordan-wright** [comment]
Hey @m4dw0lf, I'm going to go ahead and close this for now. Feel free to reach out in issues or via email if you have any other questions.

Thanks!
