### ISSUE TITLE
Getting All campaign from admin user

### ISSUE THREAD

**Issue by asad-eteam** [gophish/gophish#2371]
What version of Gophish are you using?:
I am using Gophish v0.11.0.

Brief description of the issue:
I created multiple users in Gophish in which one is admin user. So i want to see from admin all campaigns, Email Templates, landing pages etc created by any user.
Is that possible?
What are you expecting to see happen? :

What are you seeing happen?
nothing.

**Comment by glennzw** [comment]
Thanks for reaching out. Unfortunately at this stage users can only see their own campaigns, etc (even admin users). There are plans in the pipeline to add more fine grained access control, but for now it's not possible.
