### ISSUE TITLE
Set Campaign URL to secondary external Server 

### ISSUE THREAD

**Issue by bokkabonga** [gophish/gophish#2372]
What version of Gophish are you using?:  0.11

Hey everyone,

i wondered if it is somehow possible to configure the Campaign URL in a way, that allows the Link to point to a completely different website and still fetch the campaign results. For example:

I start a Campaign via our gophish server (https://gophish.domain.com) but set the Campaign-URL to point towards https://some-other-domain.com so that the user wont immediately (or after closer inspecting the link) be able to tell, that the link points to one of our own servers.

I figure i could simply set up a new gophish Server each time i want to start a new campaign, but i wanted to avoid that if possible.

I hope you can understand what i´m trying to explain, if not i´d be happy to explain further.

**Comment by edermi** [comment]
What prevents you from setting a CNAME record for some-other-domain.com pointing to gophish.domain.com?

**Comment by bokkabonga** [comment]
Hey @edermi  i already thought about that. Correct me if i´m wrong here, but i can only really do that for my own DNS-Server if i want to be quiet flexible right? So the CNAME would only work if the Client on which the user clicks the link is using our DNS-Server to resolve the name.

Opening the link from some other device or in some foreign network would not work in that case.

**Comment by edermi** [comment]
If you own some-other-domain.com and set your CNAME in the DNS server responsible for the zone, it will also work on your client's network.

**Comment by glennzw** [comment]
You don't even need a CNAME, just another A record. One for your 'legit' domain, another for your phishing domain. e.g: 

```gophish.domain.com --> 1.2.3.4
somethingphishy.serverupdate.com --> 1.2.3.4```

Then just make sure the admin server and phishing server run on different ports.

**Comment by glennzw** [comment]
Closing out as haven't heard back, feel free to reopen.
