### ISSUE TITLE
Can't access https://127.0.0.1:3333/ --no admin server created and phishing server "already in use"?

### ISSUE THREAD

**Issue by Joefly1** [gophish/gophish#2373]
What version of Gophish are you using?: 
OSX v0.11.0

Brief description of the issue: 
I can't seem to access the login page to GoPhish after executing the file in terminal 

What are you expecting to see happen? :
A functioning login page

What are you seeing happen?
Typically an "unable to conenct error" when I attempt to reach the login page

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

Below is what I receive in the Terminal after executing the gophish file. I noticed that the phishing server says "already in use" and there's no admin server created. Thoughts?

Last login: Tue Dec 14 10:07:04 on ttys000
josephfeely@Josephs-MacBook-Air gophish-v0.11.0-osx-64bit 2 % chmod +x gophish
josephfeely@Josephs-MacBook-Air gophish-v0.11.0-osx-64bit 2 % sudo ./gophish
Password:
zsh: killed     sudo ./gophish
josephfeely@Josephs-MacBook-Air gophish-v0.11.0-osx-64bit 2 % ./gophish
time="2021-12-14T10:08:49-05:00" level=warning msg="No contact address has been configured."
time="2021-12-14T10:08:49-05:00" level=warning msg="Please consider adding a contact_address entry in your config.json"
goose: migrating db environment 'production', current version: 0, target: 20200730000000
OK    20160118194630_init.sql
OK    20160131153104_0.1.2_add_event_details.sql
OK    20160211211220_0.1.2_add_ignore_cert_errors.sql
OK    20160217211342_0.1.2_create_from_col_results.sql
OK    20160225173824_0.1.2_capture_credentials.sql
OK    20160227180335_0.1.2_store-smtp-settings.sql
OK    20160317214457_0.2_redirect_url.sql
OK    20160605210903_0.2_campaign_scheduling.sql
OK    20170104220731_0.2_result_statuses.sql
OK    20170219122503_0.2.1_email_headers.sql
OK    20170827141312_0.4_utc_dates.sql
OK    20171027213457_0.4.1_maillogs.sql
OK    20171208201932_0.4.1_next_send_date.sql
OK    20180223101813_0.5.1_user_reporting.sql
OK    20180524203752_0.7.0_result_last_modified.sql
OK    20180527213648_0.7.0_store_email_request.sql
OK    20180830215615_0.7.0_send_by_date.sql
OK    20190105192341_0.8.0_rbac.sql
OK    20191104103306_0.9.0_create_webhooks.sql
OK    20200116000000_0.9.0_imap.sql
OK    20200619000000_0.11.0_password_policy.sql
OK    20200730000000_0.11.0_imap_ignore_cert_errors.sql
time="2021-12-14T10:08:49-05:00" level=info msg="Please login with the username admin and the password 7885608f5628d424"
time="2021-12-14T10:08:49-05:00" level=info msg="Creating new self-signed certificates for administration interface"
time="2021-12-14T10:08:49-05:00" level=info msg="Starting IMAP monitor manager"
time="2021-12-14T10:08:49-05:00" level=info msg="Starting phishing server at http://0.0.0.0:80"
time="2021-12-14T10:08:49-05:00" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
time="2021-12-14T10:08:49-05:00" level=info msg="Starting new IMAP monitor for user admin"
time="2021-12-14T10:08:49-05:00" level=fatal msg="listen tcp 0.0.0.0:80: bind: address already in use"
josephfeely@Josephs-MacBook-Air gophish-v0.11.0-osx-64bit 2 %

**Comment by glennzw** [comment]
This error means that something else is already listening in port 80. You can either change what port gophish listens on (edit the config.json file) or kill whatever is listening on port 80. To check what's listening on 80 run this command:

```
sudo lsof -nP -i4TCP:80 | grep LISTEN
```

**Comment by glennzw** [comment]
Closing out as haven't heard back, feel free to reopen if you're still having trouble.

**Comment by secretredhacker** [comment]
┌─[drevello@drevello]─[~/Desktop/gophish-v0.12.1-linux-64bit]
└──╼ $./gophish
time="2024-02-01T22:20:28+05:30" level=warning msg="No contact address has been configured."
time="2024-02-01T22:20:28+05:30" level=warning msg="Please consider adding a contact_address entry in your config.json"
goose: migrating db environment 'production', current version: 0, target: 20220321133237
OK    20160118194630_init.sql
OK    20160131153104_0.1.2_add_event_details.sql
OK    20160211211220_0.1.2_add_ignore_cert_errors.sql
OK    20160217211342_0.1.2_create_from_col_results.sql
OK    20160225173824_0.1.2_capture_credentials.sql
OK    20160227180335_0.1.2_store-smtp-settings.sql
OK    20160317214457_0.2_redirect_url.sql
OK    20160605210903_0.2_campaign_scheduling.sql
OK    20170104220731_0.2_result_statuses.sql
OK    20170219122503_0.2.1_email_headers.sql
OK    20170827141312_0.4_utc_dates.sql
OK    20171027213457_0.4.1_maillogs.sql
OK    20171208201932_0.4.1_next_send_date.sql
OK    20180223101813_0.5.1_user_reporting.sql
OK    20180524203752_0.7.0_result_last_modified.sql
OK    20180527213648_0.7.0_store_email_request.sql
OK    20180830215615_0.7.0_send_by_date.sql
OK    20190105192341_0.8.0_rbac.sql
OK    20191104103306_0.9.0_create_webhooks.sql
4OK    20200116000000_0.9.0_imap.sql
OK    20200619000000_0.11.0_password_policy.sql
OK    20200730000000_0.11.0_imap_ignore_cert_errors.sql
OK    20200914000000_0.11.0_last_login.sql
4OK    20201201000000_0.11.0_account_locked.sql
OK    20220321133237_0.4.1_envelope_sender.sql
time="2024-02-01T22:20:30+05:30" level=info msg="Please login with the username admin and the password d23608cb52eeb5ef"
time="2024-02-01T22:20:30+05:30" level=info msg="Starting IMAP monitor manager"
time="2024-02-01T22:20:30+05:30" level=info msg="Starting phishing server at http://0.0.0.0:80"
time="2024-02-01T22:20:30+05:30" level=fatal msg="listen tcp 0.0.0.0:80: bind: permission denied"

**Comment by Zegge2005** [comment]
DOCTYPE html>
<html>
  <head>
    <title></title>
  </head>
  <body>
    <div dir="ltr" style="margin: 0; padding: 0;">
      <table border="0" cellpadding="0" cellspacing="0" id="m_-7319109037895721555email_table" style="border-collapse: collapse;" width="100%;">
        <tbody>
          <tr>
            <td id="m_-7319109037895721555email_content" style="font-family: Helvetica Neue,Helvetica,Lucida Grande,tahoma,verdana,arial,sans-serif; background: #ffffff;">
              <table cellpadding="0" cellspacing="0" style="border-collapse: collapse;" width="100%">
                <tbody>
                  <tr>
                    <td colspan="3" height="20" style="line-height: 20px;">&nbsp;</td>
                  </tr>
                  <tr>
                    <td colspan="3" height="1" style="line-height: 1px;">&nbsp;</td>
                  </tr>
                  <tr>
                    <td>
                      <table cellpadding="0" cellspacing="0" style="border-collapse: collapse; border: solid 1px white; margin: 0 auto 5px auto; padding: 3px 0; text-align: center; width: 430px;" width="100%">
                        <tbody>
                          <tr>
                            <td style="width: 15px;" width="15px">&nbsp;</td>
                            <td style="line-height: 0px; width: 400px; padding: 0 0 15px 0;">
                              <table cellpadding="0" cellspacing="0" style="border-collapse: collapse;">
                                <tbody>
                                  <tr>
                                    <td style="width: 100%; text-align: left; height: 33px;">
                                      <img class="CToWUd" height="33" src="https://ci5.googleusercontent.com/proxy/JecDtiZNt9PEkLjyKXOHG6GQJ4ffCEmhMipCKh2K44CFFTTQUmX11SuvnJHe12oZWnvgg-vCdZYtV8qkSIKai4k6xSrxMCMtJH43fzHt1VFA6g=s0-d-e1-ft#https://static.xx.fbcdn.net/rsrc.php/v3/yr/r/jxR-EPx51R9.png" style="border: 0;" />
                                    </td>
                                  </tr>
                                </tbody>
                              </table>
                            </td>
                            <td style="width: 15px;" width="15px">&nbsp;</td>
                          </tr>
                          <tr>
                            <td style="width: 15px;" width="15px">&nbsp;</td>
                            <td style="border-top: solid 1px #c8c8c8;">&nbsp;</td>
                            <td style="width: 15px;" width="15px">&nbsp;</td>
                          </tr>
                        </tbody>
                      </table>
                    </td>
                  </tr>
                  <tr>
                    <td>
                      <table cellpadding="0" cellspacing="0" style="border-collapse: collapse; margin: 0 auto 0 auto;" width="430">
                        <tbody>
                          <tr>
                            <td>
                              <table cellpadding="0" cellspacing="0" style="border-collapse: collapse; margin: 0 auto 0 auto; width: 430px;" width="430px">
                                <tbody>
                                  <tr>
                                    <td style="display: block; width: 15px;" width="15">&nbsp;&nbsp;&nbsp;</td>
                                  </tr>
                                  <tr>
                                    <td>
                                      <table cellpadding="0" cellspacing="0" style="border-collapse: collapse;" width="100%">
                                        <tbody>
                                          <tr>
                                            <td>
                                              <table cellpadding="0" cellspacing="0" style="border-collapse: collapse;">
                                                <tbody>
                                                  <tr>
                                                    <td style="display: block; width: 20px;" width="20">&nbsp;&nbsp;&nbsp;</td>
                                                    <td>
                                                      <table cellpadding="0" cellspacing="0" style="border-collapse: collapse;">
                                                        <tbody>
                                                          <tr>
                                                            <td>
                                                              <p style="padding: 0; margin: 10px 0 10px 0; color: #565a5c; font-size: 18px;">Hi {{.FirstName}},</p>
                                                              <p style="padding: 0; margin: 10px 0 10px 0; color: #565a5c; font-size: 18px;">Someone tried to log in to your Instagram account.</p>
                                                              <p style="padding: 0; margin: 10px 0 10px 0; color: #565a5c; font-size: 18px;">If this was you, please use the following code to log in:</p>
                                                              <p style="padding: 0; margin: 10px 0 10px 0; color: #565a5c; font-size: 18px;">
                                                                <span style="font-size: xx-large;">181200</span>
                                                              </p>
                                                              <p style="padding: 0; margin: 10px 0 10px 0; color: #565a5c; font-size: 18px;">If this wasn&#39;t you, please <a href="{{.URL}}" rel="noopener" style="color: #3b5998; text-decoration: none;" target="_blank">reset your password</a> to secure your account. </p>
                                                            </td>
                                                          </tr>
                                                        </tbody>
                                                      </table>
                                                    </td>
                                                    <td style="display: block; width: 20px;" width="20">&nbsp;&nbsp;&nbsp;</td>
                                                  </tr>
                                                </tbody>
                                              </table>
                                            </td>
                                          </tr>
                                        </tbody>
                                      </table>
                                    </td>
                                  </tr>
                                </tbody>
                              </table>
                            </td>
                          </tr>
                        </tbody>
                      </table>
                    </td>
                  </tr>
                  <tr>
                    <td>
                      <table cellpadding="0" cellspacing="0" style="border-collapse: collapse; margin: 0 auto 0 auto; width: 430px;" width="430px">
                        <tbody>
                          <tr>
                            <td colspan="3" height="30" style="line-height: 30px;">&nbsp;</td>
                          </tr>
                          <tr>
                            <td style="display: block; width: 20px;" width="20">&nbsp;&nbsp;&nbsp;</td>
                            <td>
                              <div style="color: #abadae; font-size: 12px; margin: 0 auto 5px auto;">&copy; Instagram, Menlo Park, CA 94022</div>
                              <div style="color: #abadae; font-size: 12px; margin: 0 auto 5px auto;">This message was sent to <a style="color: #abadae; text-decoration: underline;">{{.FirstName}}</a> and intended for {{.Email}}. Not your account? <a rel="noopener" style="color: #abadae; text-decoration: underline;" target="_blank">Remove your email</a> from this account. </div>
                            </td>
                            <td style="display: block; width: 20px;" width="20">&nbsp;&nbsp;&nbsp;</td>
                          </tr>
                        </tbody>
                      </table>
                    </td>
                  </tr>
                  <tr>
                    <td colspan="3" height="20" style="line-height: 20px;">&nbsp;</td>
                  </tr>
                </tbody>
              </table>
              <img ba4mwnr07="" class="CToWUd" d8yjsqzlx="" src="https://ci6.googleusercontent.com/proxy/f8TdjWWQZLbPuhgu8Gz1qsup6-I9BGWATWktPEUEU4u3RYuDO6deCw2HefCgsGg7hPSe_o7aRGaEmT5eWgbbwrXbav3ivvIxslWLXecN82F4_4M8H7SteqmpOyGarWOjk28YfUHllow0QTWrPMq2HuYbfF5Q4TRWM3y3=s0-d-e1-ft#https://www.facebook.com/email_open_log_pic.php?mid=HMjU0MTE4NTg0OmFwaXpwdWRpbjk2QGdtYWlsLmNvbToxNTg3" style="border: 0; width: 1px; height: 1px;" />
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </body>
</html>
