### ISSUE TITLE
Email templates Gophish, URL points to server home Page authentification Gophish

### ISSUE THREAD

**Issue by Olvers974** [gophish/gophish#2375]
**_Hello :)_**

_What version of Gophish are you using?:_ 
**v. 0.11.0**

Brief description of the issue: 
The url of my email templates does not redirect to the right place. However, I made the DNS registration of the domain to the IP address of my server. (Record A)

_What are you expecting to see happen? :_
I want to get to the wrong email template

_What are you seeing happen?_
I go to the gophish authentication home page instead.

**Why ?**
My prestatary tells me that it is an internal config of gophish. **_My server is in Centos, on a VM, with the Apache service._**

I don't have control over the DNS host, but want to know if this comes from the configuration of the server, or from the DNS host

Please provide as many steps as you can to reproduce the problem:
Step 1 - Campaign Test

Thanks everyone for the help ;)

Olvers974

**Comment by glennzw** [comment]
Hi there, thanks for reaching out. It sounds like you have the gophish endpoint and admin server on the same IP (presumably different ports). I'm guessing when you create a campaign you need to supply the landing page as http://.... rather than https://.... but you'd need to share at the least your `config.json` (and your DNS record info etc too if possible).

**Comment by Olvers974** [comment]
> Hi there, thanks for reaching out. It sounds like you have the gophish endpoint and admin server on the same IP (presumably different ports). I'm guessing when you create a campaign you need to supply the landing page as http://.... rather than https://.... but you'd need to share at the least your (and your DNS record info etc too if possible).`config.json`

Hi @glennzw 

Thanks for the anwser.
I don't have a certificate, and my server is in HTTP.

My config.json :

        "admin_server": {
                "listen_url": "0.0.0.0:3333",
                "use_tls": false
        },
        "phish_server": {
                "listen_url": "0.0.0.0:80",
                "use_tls": false
        },
        "db_name": "sqlite3",
        "db_path": "gophish.db",
        "migrations_prefix": "db/db_",
        "contact_address": "",
        "logging": {
                "filename": "",
                "level": ""
        }
}

For my DNS record, it's my IP > Domain Name. (My instruction for the config)

Before recording, it worked. It was showing the IP address on my {URL} link.

I will see with my prestataire if they can give me the config

**Comment by Olvers974** [comment]
Yes ... :/

**Comment by glennzw** [comment]
It would seem it's a DNS issue and not a gophish issue then, making it hard to debug from my end. You could email me some more details to keep them off the public forum and I could try help (glennzw AT ProtonMail DOT com).
