### ISSUE TITLE
Multi-Admin view for campaigns

### ISSUE THREAD

**Issue by herrJJ** [gophish/gophish#2376]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.11.0
Brief description of the issue: 
multiple admins confiugured, can't see every campaign created
What are you expecting to see happen? :
all admins see all campaigns created (privileged rights management to use named admin accounts in one instance)
What are you seeing happen?
nothing: only the user/admin created can see its campaign, no multi user support seen
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
Hi there, thanks for reaching out. Unfortunately what you're looking to do isn't possible. Each user (admin or otherwise) can only see their own data. It is on our roadmap to add more fine-grained user access control.
