### ISSUE TITLE
Error Message in place of the Landing Page

### ISSUE THREAD

**Issue by PatternedClothing** [gophish/gophish#2378]
What version of Gophish are you using?: v0.11.0

Brief description of the issue: 
While the GoPhish campaign sends emails to the target audience, within the phishing email sent, all the links are redirected to the a page with a message on it (as shown in the screenshot below).

<img width="1439" alt="Screenshot 2022-01-01 at 6 56 17 pm" src="https://user-images.githubusercontent.com/85125404/147853859-08d98460-a215-4b49-9 410-cf1755597f69.png">

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

Landing Page: 

<img width="525" alt="Screenshot 2022-01-01 at 7 20 28 pm" src="https://user-images.githubusercontent.com/85125404/147853877-8ec9da99-a40b-46a6-bd18-8c5b1aa33244.png">

**Comment by glennzw** [comment]
Hi there. The first screenshot isn't loading, could you send it again please?

Also, please include the HTML for the landing page.

**Comment by glennzw** [comment]
Closing out as haven't heard back, feel free to reopen.
