### ISSUE TITLE
Logrotate on Gophish log file results in no output after rotation of the file

### ISSUE THREAD

**Issue by RESP-hub** [gophish/gophish#2379]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

**What version of Gophish are you using?:** 
0.11.0

**Brief description of the issue:** 
Logrotate on Gophish log file results in no output in the new file created after the log rotation.

**What are you expecting to see happen? :**
Log rotates and creates new file, Gophish reports new log entries to this newly created file.

**What are you seeing happen?**
After setting up logrotate on the logfile configured in the Gophish configuration, the newly created file after rotation does not see any new logs. Logrotate was setup because the file was getting to large to open on our server.

Only a Gophish service restart will get the log going again. I could add a `postrotate` script to restart the gophish service after file rotation, but I would rather not do this as it could disrupt ongoing campaigns.

Is there any way (with a parameter in the config file for example) that the logrotation process does not break the Gophish logging?

Thanks in advance!

**Comment by glennzw** [comment]
We're you able to find a solution? I had a quick look but am unfamiliar with log rotate

**Comment by Buchtic** [comment]
Simply just use option ```copytruncate``` rather then ```create```.
My logrotate config:

```
/home/gophish/gophish.log {
	weekly
	rotate 5
	copytruncate
	dateext
	compress
}
```
