### ISSUE TITLE
Target page does not load

### ISSUE THREAD

**Issue by faisalmuneer** [gophish/gophish#238]
Hi,

I am facing an issue where the target page does not open on remote host when any user clicks on it goes to the URL of my computer (where gophish is running) but the page does not load and timeout.

However when I get the email as victim and I click on the same computer where gophish is also running as a server then the page loads fine.

**Comment by jordan-wright** [comment]
Sounds like a possible firewall issue.. Can you give us more info on the setup? Are you and the victim on the same lan? Can they reach the phish server ip and get a 404?

What does your config.json file look like?

**Comment by faisalmuneer** [comment]
Yes the victim and myself are on the same LAN. phish server IP they are unable to reach so that means most probably could be Windows Firewall?

{
	"admin_server" : {
		"listen_url" : "mct-ict-94.oamc.com:3333",
		"use_tls" : true,
		"cert_path" : "gophish.crt",
		"key_path" : "gophish.key"
	},
	"phish_server" : {
		"listen_url" : "10.0.6.5:81",
		"use_tls" : false,
		"cert_path" : "example.crt",
		"key_path": "example.key"
	},
	"smtp" : {
		"host" : "smtp.example.com:25",
		"user" : "username",
		"pass" : "password"
	},
	"db_path" : "gophish.db",
	"migrations_path" : "db/migrations/"
}

**Comment by SwitHak** [comment]
Hi, I have the same thing when I don't set my firewall rules 

You need to setup :

Incoming /outgoing TCP 3333
Incoming /outgoing TCP 81 

Tell me if it's works !

**Comment by faisalmuneer** [comment]
Can we make the landing page https as well? because currently only the admin page is on https not the landing page.

**Comment by jordan-wright** [comment]
You can make either of the servers operate over HTTPS by changing the ```config.json``` file.
