### ISSUE TITLE
login and password

### ISSUE THREAD

**Issue by wolxler** [gophish/gophish#2382]
initial login and password are not correct
login admin
password gophish

**Comment by asaqib27** [comment]
default password is not gophish. 
Default password would be printed on terminal once you execute gophish and it started successfully.

**Comment by wolxler** [comment]
I did it as stated in the documents. Stopped the service gophish started via cmd gophish. will start the service gophish copied the received password but still an error

**Comment by wolxler** [comment]
blew it all away:
Running Gophish
Now that you have gophish installed, you’re ready to run the software. To launch gophish, open a command shell and navigate to the directory the gophish binary is located.
Then, execute the gophish binary. You will see some informational output showing both the admin and phishing web servers starting up, as well as the database being created. This output will tell you the port numbers you can use to connect to the web interfaces.
If you're running a version of Gophish after v0.10.1, then temporary admin credentials are printed in these logs which you can use to login.
got parameters
time="2020-06-30T08:04:33-05:00" level=warning msg="No contact address has been configured."
 time="2020-06-30T08:04:33-05:00" level=warning msg="Please consider adding a contact_address entry in your config.json"
 time="2020-06-30T08:04:33-05:00" level=info msg=_**"Please login with the username admin and the password 1178f855283d03d3"**_
 time="2020-06-30T08:04:33-05:00" level=info msg="Starting phishing server at http://0.0.0.0:80"
 time="2020-06-30T08:04:33-05:00" level=info msg="Starting IMAP monitor manager"
 time="2020-06-30T08:04:33-05:00" level=info msg="Starting admin server at https://127.0.0.1:3333"
 time="2020-06-30T08:04:33-05:00" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
 time="2020-06-30T08:04:33-05:00" level=info msg="Starting new IMAP monitor for user admin"

copied the password but still login or password error

**Comment by wolxler** [comment]
does this error affect the username and password?
log4cplus:ERROR No appenders could be found for logger.
log4cplus:ERROR Please initialize the log4cplus system properly.
