### ISSUE TITLE
Create custom variable in gopish 

### ISSUE THREAD

**Issue by aukhan288** [gophish/gophish#2384]
What version of Gophish are you using?:
I am using Gophish v0.11.0.

Brief description of the issue:
Is this possible to create own variable in gophish for tracking extra phishing events?
eg: in gophish we can track count of email open, clink links and capture credential. But in my scenario i want to create more variables to capture events.    

What are you expecting to see happen? :

What are you seeing happen?
nothing.

**Comment by glennzw** [comment]
It's not at the moment, but it will be: https://github.com/gophish/gophish/pull/1929
