### ISSUE TITLE
Automation tools and a owa / outlook gophish reporter tool

### ISSUE THREAD

**Issue by lerra** [gophish/gophish#2385]
What version of Gophish are you using?: 
0.11.0

Brief description of the issue:

We at Daniel Wellington have built automation tools we would like to share with the community and have it listed if possible on the documentation page https://docs.getgophish.com/user-guide/additional-references or somewhere else that is appropriated.

The tools we have built is,
The first tool is a GoPhish reporter plugin for Outlook/OWA that can be deployed in Office365 and pushed out to all email users (including mobile).  Users reporting a GoPhish email will automatically flag in GoPhish that it is reported, if it is not a GoPhish email it will copy the headers and send it to our support mail for investigation, it can be found here https://github.com/dwtechnologies/gophish-owa-phishing-reporter/

The second tool we have built is the  automation to creating campaigns and spread out users evenly and dynamic load balancers in AWS to not get blocked in google safe browsing. When the campaign is over it will tear down the load balancers (so you get new ip/dns+cert next time). The code can be found here https://github.com/dwtechnologies/dw-gophish-automation

The third one is for Office365 and Microsoft Teams users, we have put out a detailed article on how to build a power automate flow to handle and verify the incoming webhook from GoPhish. We use two events, one when a user have sent there credentials and the other one is when they use the phishing reporter plugin and report our Phishing mail. For users that spots the phishing mail we send a high five over teams. For users that did fail and put in there credentials, we assign them to complete a quiz in Microsoft forms within X amount of weeks, if they don't do that we send reminders to the user and there manager in azure ad. If they still have not completed that within X amount of weeks we will then add a second CC to the manager manager. The next step after X amount of weeks is to send a mail to our support team to disable the account. The flow details can be found here https://github.com/dwtechnologies/dw-gophish-automation/blob/master/power-automate/Office365-Power-Automate.md

We have a article explaining how we built this and put it together, it can be found here https://medium.com/daniel-wellington-tech-stories/how-we-brought-security-awareness-through-the-company-with-automation-of-open-source-tools-and-a-b8dcf0234c69

**Comment by glennzw** [comment]
Hi @lerra! Thanks so much for reaching out and giving back to the community! These are some really great additions and I'm sure a lot of people will find them useful. I'll very happily add them to the documentation 🥳

I've been working on a reporter plugin for Outlook too, using Yeoman. Did you use that as your boilerplate too?

**Comment by glennzw** [comment]
Just so I can credit you properly, would you like me to reference the author in the documentation as "Daniel Wellington Technologies " or "Lezgin Bakircioglu" ?

**Comment by lerra** [comment]
@glennzw Big sorry mate, been on vacation and can't get hold of the developer, what I remember we used some ready made examples from microsoft as a boilerplate so most likely yes but I can not confirm that.

You can write Daniel Wellington as the author, big thanks and big sorry for the delay
