### ISSUE TITLE
Gophish Deploy on Heroku vps

### ISSUE THREAD

**Issue by aukhan288** [gophish/gophish#2386]
What version of Gophish are you using?:
I am using Gophish v0.11.0.

Brief description of the issue:
I am deploying gopish on heroku vps. after deployment the build created successfully but due to port my app is crashed after starting
This is the output:
![image](https://user-images.githubusercontent.com/33312651/151124301-9f536a81-c380-4e10-9027-9d9560cf7590.png)

What are you expecting to see happen? :

What are you seeing happen?
nothing.

**Comment by glennzw** [comment]
Hmm I do use Heroku for other projects but I've never tried to get Gophish running. The one gotcha is going to be that it's tricky to expose multiple ports with Heroku (as you'll need one for campaigns, one for admin). I *think* you might be able to do something with multiple subdomains.

To start off you'd need to supply a little more info on how you're deploying.

**Comment by aukhan288** [comment]
I got one port from heroku which is used in admin server.
how i can use another port for phishing server?
![image](https://user-images.githubusercontent.com/33312651/151788945-603e69a8-c14e-4ed4-8c8a-a94798a6a7dd.png)

**Comment by aukhan288** [comment]
This is tha config file which we are deploying on heroku
{
  "admin_server": {
    "listen_url": "https://gentle-basin-33147.herokuapp.com/",
    "use_tls": true,
    "cert_path": "gophish_admin.crt",
    "key_path": "gophish_admin.key"
  },
  "phish_server": {
    "listen_url": "gentle-basin-33147.herokuapp.com",
    "use_tls": false,
    "cert_path": "example.crt",
    "key_path": "example.key"
  },
  "db_name": "sqlite3",
  "db_path": "gophish.db",
  "migrations_prefix": "db/db_",
  "contact_address": "aukhan288@gmail.com",
  "logging": {
    "filename": "",
    "level": ""
  }
}

**Comment by aukhan288** [comment]
It will also be helpful if you put tell us which free/paid hosting can we use in your experience which does not have above issuse. Thanks

**Comment by aukhan288** [comment]
Which framework of golang used in gophish? i think gin framework is used in gophish is that right?
@glennzw

**Comment by glennzw** [comment]
@aukhan288 gorilla is used to handle HTTP traffic: https://github.com/gophish/gophish/blob/master/controllers/route.go

**Comment by aukhan288** [comment]
gorilla is just a web toolkit which is used for url routing.
i am talking about programming language framework.
Following are the golang frameworks:
1) gin
2) beego
3) echo
4) kit
5) fasthttp

**Comment by edermi** [comment]
You can find a list of used dependencies in https://github.com/gophish/gophish/blob/master/go.mod
Gophish uses gorilla, as @glennzw said.

**Comment by aukhan288** [comment]
@edermi here i cheeked no no framework. it means gophish is created on simple/core golang

**Comment by glennzw** [comment]
OK. I'll close this out.

Feel free to reopen or open a new issue if you have other problems.
