### ISSUE TITLE
Email Reported Function not working

### ISSUE THREAD

**Issue by Sethu-code** [gophish/gophish#2387]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.11.0

Brief description of the issue:  I just set up email reporting and no data gets submitted. When I try to test the settings I get an unable to login error.

What are you expecting to see happen? : When someone reports the email, it gets counted and I can see how many people reported on the dashboard

What are you seeing happen? The reporting tab is showing on the dashboard but the number is zero. When I test the settings after saving, I get an unable to login error

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
<img width="461" alt="new error imap" src="https://user-images.githubusercontent.com/82969714/151162952-46d7629d-28e5-4d73-bb78-c20fcb3e8460.PNG">
<img width="415" alt="Imap error" src="https://user-images.githubusercontent.com/82969714/151162999-61e77355-09ed-44ff-8619-21cc78d479c5.PNG">
<img width="391" alt="Imap" src="https://user-images.githubusercontent.com/82969714/151163027-13b709a3-d5fd-4a86-83fd-3d413f5a5bbf.PNG">

```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
Hi there. How are your users reporting the emails, via IMAP, or a URL click?

**Comment by Sethu-code** [comment]
Hi, via IMAP. We use the Microsoft phishing button which sends to the same mailbox as the one I was setting up for email reporting on Gophish

**Comment by Sethu-code** [comment]
- No, that's where I get the Failed- unable to login error
- Yes, they do arrive
- No, it's unable to login to the IMAP server

**Comment by glennzw** [comment]
OK great that gives us a good starting point to debug. When you get the login failure, there should be a 'more info' button. Could you screenshot that and post it here please. Also, when you do the login test there should be some output in the gophish terminal, could you paste that here too.

**Comment by Sethu-code** [comment]
<img width="461" alt="new error imap" src="https://user-images.githubusercontent.com/82969714/155075529-e5806e8b-2033-4643-81b8-ec34b54a12ac.PNG">
Hi Glennzw, I have attached the error I get when I click on more info. I access gophish using an IP address and it takes me straight to the tool, I'm not sure how to to get to the termunal. We also use okta for MFA, could it be the reason gophish is unable to login to the IMAP server.

**Comment by glennzw** [comment]
Hi @Sethu-code; that error looks like your gophish server isn't able to access the IMAP server. It's probably a firewall issue.

You could verify this by trying to connect from the command line on your gophish server, with something like:

```
nc -v 52.98.16.226 993
```

You should see `Connection to 52.98.16.226 port 993 [tcp/imaps] succeeded!` Although I did notice you said you don't have terminal access. The MFA may indeed be the problem.

You could also setup a Gmail or Yahoo account and try connect with those just to rule out gophish being the problem.

I hope this helps.

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen.
