### ISSUE TITLE
GoPhish + Ngrok - Can't Access Admin Panel 

### ISSUE THREAD

**Issue by RJSOG** [gophish/gophish#2388]
System Info: Raspbian on Raspberry Pi 4
Ngrok version: 2.3.40
GoPhish version: 0.11.0

Command Ngrok : `./ngrok http https://127.0.0.1:3333`
Command GoPhish: `sudo ./gophish`

Url : https://0a23-184-82-106-7.ngrok.io/login?next=%2F
Issue: After accessing the login page and submitting the login and the password i have this error:

-  with https: `Forbidden - referer invalid`
-  with http: `CSRF - Invalid Token`

**Comment by glennzw** [comment]
Hi there. It's a little hard to debug without more information. You're probably seeing that message as you're bouncing through ngrok.

Have you tried hitting the URL directly via the Pi's accessible IP?

**Comment by RJSOG** [comment]
Hi there, 
By using ngrok i can access the login page, but without i can't access anything..

**Comment by glennzw** [comment]
When you say "i can't access anything.." do you mean you get an error when connecting to gophish? Is it running? Could you share your `config.json`. You'll need to expose the admin URL to 0.0.0.0 if you want to access it from your LAN.

**Comment by glennzw** [comment]
This is now resolved in v0.12.1 with the addition of adding Trusted Origins to config.json.
