### ISSUE TITLE
Phish with no users

### ISSUE THREAD

**Issue by tux-mind** [gophish/gophish#239]
Hello there!

I'm playing a little with this powerful project, and I have a question.

What if I want to phish without knowing my users ?

Take this scenario:

> I'm setting up gophish on my home router, listening on port 8080.
> I setup a simple program that redirect certain requests to my router ( http://example.com/ -> http://192.168.1.1:8080/ ).
> Now I want to known how many of my home guests fall in my trap.

In this scenario I don't known my guests email addresses, I just redirect them from the correct website to the gophish one and collect credentials from who fall in my phishing trap.

As developer I bet that users are a keypoint of your infrastructure, but will you able to achieve this ?

Thank you for your time and this project, which looks like to have a great power! :wink:

**Comment by jordan-wright** [comment]
Hey there!

I'm afraid that gophish is trying to stay focused as a core product. Right now, this means that we will require prior email addresses and will only focus on tracking events that occur from those emails.

If you are simply looking to capture who hits a website, I would recommend setting something simple up like nginx and watching the access logs.

**Comment by rfdevere** [comment]
Put your router on a different IP, set up SEToolKit running a credential
harvester attack on 192.168.1.1, a cloned copy of your routers login page
and sit back and just tail -f the log file. Leave this closed and speak to
@rfdevere on Twitter if you need a run through.

On Tuesday, 12 April 2016, Jordan Wright <notifications@github.com> wrote:

> Closed #239 <https://github.com/gophish/gophish/issues/239>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/gophish/gophish/issues/239#event-624894341>
>


-- 
*Richard De Vere*
*Principal Consultant*

*Tel:* +44 754 6655448
*Web:* TheAntiSocialEngineer.com
*Email:* FrontDesk@TheAntiSocialEngineer.com
*Twitter:* @AntiSocial_Eng


The AntiSocial Engineer Ltd is a limited company registered in England and
Wales. Company Registration No. 09367111 Registered Office: 4 Capel Street,
Huddersfield, HD6 3AJ This message contains confidential information and is
intended only for AntiSocial Engineer customers. E-mail transmission cannot
be guaranteed to be secure or error-free as information could be
intercepted, corrupted, lost, destroyed, arrive late or incomplete, or
contain viruses. The AntiSocial Engineer Ltd cannot accept liability for
any errors or omissions in the contents of this message, which may arise as
a result of e-mail transmission. Please note that The AntiSocial Engineer
Ltd may monitor, analyse and archive email traffic, data and the content of
email for the purposes of security, legal compliance and staff training.
