### ISSUE TITLE
Can´t login in Gophish

### ISSUE THREAD

**Issue by blueadias** [gophish/gophish#2391]
What version of Gophish are you using?:  
0.11.0

Brief description of the issue: 
I install gophish but default credentials (admin/gophish) don't work, as we can see in the image below.
![image](https://user-images.githubusercontent.com/98945045/152312071-5787a323-8246-4cf4-8337-9596682421ac.png)

What are you expecting to see happen? :
I expect to log in to the web application,
What are you seeing happen?

I can´t authenticate with default credentials.

**Comment by glennzw** [comment]
The default credentials of "gophish/admin" were replaced with random password generation:

- - -

### Setup
After running the Gophish binary, open an Internet browser to https://localhost:3333 and login with the default username and password listed in the log output.
e.g.
```
time="2020-07-29T01:24:08Z" level=info msg="Please login with the username admin and the password 4304d5255378177d"
```

Releases of Gophish prior to v0.10.1 have a default username of `admin` and password of `gophish`.
- - -

(from the README.md file https://github.com/gophish/gophish/blob/master/README.md)

**Comment by blueadias** [comment]
Thank you for your help. I was able to login now :)
