### ISSUE TITLE
Invalid Username/Password

### ISSUE THREAD

**Issue by jacmatmar** [gophish/gophish#2393]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: gophish-v0.11.0-windows-64bit

Brief description of the issue: When I use the admin username and the generated password from my terminal it says "Invalid Username/Password"

What are you expecting to see happen? : I am expecting the credentials to work correctly and to see a reset password screen.

What are you seeing happen? When I use the admin username and the generated password from my terminal it says "Invalid Username/Password"

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below: N/A

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Start Gophish via NSSM 
 * Step 2 - Start a command prompt terminal to generate a password so I can log in & make my own password.

**Comment by glennzw** [comment]
Hmm this definitely shouldn't be happening. Are you copying and pasting, making sure not to pick up any whitespace characters? I'd suggest pasting it into notepad to double check.

**Comment by jacmatmar** [comment]
> Hmm this definitely shouldn't be happening. Are you copying and pasting, making sure not to pick up any whitespace characters? I'd suggest pasting it into notepad to double check.

Yes, I've tried both methods if entering the password.

**Comment by glennzw** [comment]
As a last resort you could try to manually set the password:

```
§ yum install -y sqlite ||apt-get install -y sqlite3 libsqlite3-dev
§ sqlite3 gophish.db 'update users set hash="$2a$10$IYkPp0.QsM81lYYPrQx6W.U6oQGw7wMpozrKhKAHUBVL4mkm/EvAS" where username="admin";'
```

This will reset the admin password to 'gophish'

**Comment by Amnasiddique** [comment]
Unable to login with default credentials!
using version gophish-v0.11.0-windows-64bit
(Username: admin & Password: gophish).
showing invalid.
![invalid credentials Gophish](https://user-images.githubusercontent.com/51027102/163013886-1df028f7-2f1c-4016-a3bb-ca1257bcff6c.PNG)

**Comment by glennzw** [comment]
@Amnasiddique There are no longer default credentials, the random admin password will be printed out to the console when you start gophish.

**Comment by Amnasiddique** [comment]
how can we go on start gophish without login? where is an other option to go on dashboard and random password will be printed out. I don't have find about this in user guide.

**Comment by glennzw** [comment]
@Amnasiddique Please could you paste the output from the console when you run gophish (or take a screenshot)

**Comment by Amnasiddique** [comment]
kindly guide from where should I go to start gophish, if unable to login from this page

**Comment by glennzw** [comment]
I need to see the output from running gophish.exe (it looks like you're on Windows). How are you starting gophish?

**Comment by Amnasiddique** [comment]
I have installed gophish by this method which is mentioned below and now I just want to login **https://127.0.01:3333**

https://youtu.be/lI6rCBYGNF8

**Comment by Amnasiddique** [comment]
Thanks for guide! Issue has been resolved.

**Comment by Amnasiddique** [comment]
now I have finding this error
![image](https://user-images.githubusercontent.com/51027102/163039170-d2e30999-c701-4059-8d9e-6e59316aeb8e.png)

**Comment by glennzw** [comment]
There's no error that I can see there. It's just gophish starting up.

**Comment by glennzw** [comment]
The TLS error is more of a warning that you're using a self signed certificate, but this is fine.

**Comment by Kasudo** [comment]
> As a last resort you could try to manually set the password:
> 
> ```
> § yum install -y sqlite ||apt-get install -y sqlite3 libsqlite3-dev
> § sqlite3 gophish.db 'update users set hash="$2a$10$IYkPp0.QsM81lYYPrQx6W.U6oQGw7wMpozrKhKAHUBVL4mkm/EvAS" where username="admin";'
> ```
> 
> This will reset the admin password to 'gophish'

how do i do that please

**Comment by cagaoloz** [comment]
![222](https://user-images.githubusercontent.com/19945397/176416792-1355d783-f463-49ec-bdee-0c487dd840d8.png)
I donot enter

**Comment by snowleoparddd17** [comment]
> > As a last resort you could try to manually set the password:
> > ```
> > § yum install -y sqlite ||apt-get install -y sqlite3 libsqlite3-dev
> > § sqlite3 gophish.db 'update users set hash="$2a$10$IYkPp0.QsM81lYYPrQx6W.U6oQGw7wMpozrKhKAHUBVL4mkm/EvAS" where username="admin";'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This will reset the admin password to 'gophish'
> 
> how do i do that please

anyone have an answer?

**Comment by kiakill16** [comment]
I have the same exact problem on the windows version, It does not matter what password is generated. It keeps saying invalid password and username.

**Comment by Amnasiddique** [comment]
From where will we find start gophish?? how can I go on dashboard without
login?

**Comment by glennzw** [comment]
@snowleoparddd17 This command is to be run from within your gophish folder. You'll need the sqlite3 program installed

@kiakill16 Could you please record a video if you running gophish, copying the password, pasting it into notepad, then pasting it into the login prompt?

@Amnasiddique After running gophish the console will be accessible on https://127.0.0.1:3333 - if you have further trouble please open a new issue.

**Comment by ltp59** [comment]
hello im new to github and gophish, i follow everything but when i go to the gophish login page it say website cant be reach.. how to solve it , im on windows, thanks

**Comment by Dahmmy225** [comment]
![gophish error](https://user-images.githubusercontent.com/120079812/209213008-5148255c-f957-49be-9994-ffce334a8951.png)

I tried using admin as its default password and gophish as it default password but it keeps giving me this type of error

**Comment by iremnurylmz** [comment]
Solution: 
![gophish](https://github.com/user-attachments/assets/9950cf7a-9e98-4418-b856-2155c9838050)

**Comment by rajkshk2** [comment]
In Gophish in kali, the password for the admin account isn't stored in the config.json file. Instead, it is stored in the database file, typically gophish.db, in a hashed format.
Install SQLite: If you don't have SQLite installed, install it with:
#sudo apt update
#sudo apt install sqlite3
Open the Gophish Database: Use SQLite to open the gophish.db file, which is usually located in /var/lib/gophish/ as seen in the config:
#sqlite3 /var/lib/gophish/gophish.db
sqlite>SELECT * FROM users;
Update the Password: Use a hashed password to update the admin password. Here is an example SQL command that sets the password to "gophish":
>UPDATE users SET hash='2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824' WHERE username='admin';

Restart Gophish
#sudo systemctl start gophish

**Comment by jkrushna449-cmd** [comment]
> Unable to login with default credentials! using version gophish-v0.11.0-windows-64bit (Username: admin & Password: gophish). showing invalid. ![invalid credentials Gophish](https://user-images.githubusercontent.com/51027102/163013886-1df028f7-2f1c-4016-a3bb-ca1257bcff6c.PNG)
