### ISSUE TITLE
 template cannot upload documents in docx format

### ISSUE THREAD

**Issue by vonjk** [gophish/gophish#2394]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue: 

What are you expecting to see happen? :
After pulling the latest version of gophish, try the template attachment function, but cannot upload documents in docx format

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:

This is an error in editing template
![image](https://user-images.githubusercontent.com/30076142/153531658-f75c6d35-b441-4c9f-a514-0d7217fdd1e5.png)
<img width="718" alt="image" src="https://user-images.githubusercontent.com/30076142/153548317-48a84e34-b5f2-4652-bbfe-14810785bff5.png">

 This is a new template error
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/30076142/153532493-1c188eb4-bbf9-4845-8db6-b4daeef6deaf.png">
<img width="821" alt="image" src="https://user-images.githubusercontent.com/30076142/153548279-af7c079a-d6fa-4463-a596-b3ba4ffd4507.png">

Is it possible to distinguish between clicking a link and opening an attachment? and add related icons
like this https://github.com/gophish/gophish/pull/1929

<img width="794" alt="image" src="https://user-images.githubusercontent.com/30076142/153545424-7323aab8-fb56-4bb3-924d-7a02cf80950f.png">

<img width="788" alt="image" src="https://user-images.githubusercontent.com/30076142/153545392-d3a3ce7b-b3f8-4f89-b28a-7463a68a3ddb.png">

With this, it can be more intuitive to count the number

**Comment by vonjk** [comment]
Hi @glennzw ,thanks for your reminder, it should be the problem of my docx attachment, I changed a new file successfully, I suspect it is an error when inserting the template =. =

**Comment by Richard-Tang** [comment]
> Hi @glennzw ,thanks for your reminder, it should be the problem of my docx attachment, I changed a new file successfully, I suspect it is an error when inserting the template =. =

Hey, could you please provide me with the .docx? The .docx generated by me cannot be used! :)
