### ISSUE TITLE
Unable to add Custom headers in sending profile

### ISSUE THREAD

**Issue by su1s** [gophish/gophish#2396]
What version of Gophish are you using?: 

Current Master branch (14/2/2022)

Brief description of the issue: 

Unable to add custom Headers in sending profiles 

What are you expecting to see happen? :

Add Custom Header Button to Add headers to the list below 

What are you seeing happen?

Nothing happens on mouse click on the button or if you tab to the control and hit enter / space 

Please provide as many steps as you can to reproduce the problem:
 * Step 1 -  Create Sending profile 
 * Step 2 -  Add values to the two custom header boxes 
 * Step 3 - Click on Add custom header button 
 * Step 4 - Observe nothing happens 

May be related to this recent merge request as it looks to affect the same area 

https://github.com/gophish/gophish/pull/2389

**Comment by glennzw** [comment]
Hi @su1s - you're exactly right I think this crept in as a result of #2389. I'll address this as a top priority.

**Comment by glennzw** [comment]
Thanks again for raising this @su1s. It's now been fixed: https://github.com/gophish/gophish/commit/741201b7f09a0a0fd8ed778da057adc371b4b92b

**Comment by su1s** [comment]
Impressive, thanks very much !
