### ISSUE TITLE
Attachment Tracking not working

### ISSUE THREAD

**Issue by BlindChowder** [gophish/gophish#2397]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.11.0

Brief description of the issue:  I'm trying to send an attachment with a phishing email but the variables ({{.FirstName}} {{.LastName}}) aren't being filled in when the Word document comes through to the target.  It also isn't tracking that the attachment is being opened.

What are you expecting to see happen? :I expect Variables to be filled in and tracking to work.

What are you seeing happen?  I've created a Word document on my GoPhish server based on the "Attachment Tracking" section of the user guide to test attachment tracking and get it working before sending out phishing emails.  The phishing email comes through but the variables in the attached Word document are still listed as {{.FirstName}}, {{.LastName}}, {{.Email}}.  GoPhish is also not tracking that anything is being opened.  I'm only send a phishing email with the word doc attached to myself to test.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
Hi @BlindChowder, thanks for reaching out. Please could you share the Word document and I'll try figure out why it's not working.

There's only attachment support from source at the moment, so if you're running a binary it won't work.

**Comment by glennzw** [comment]
No worries. What I mean by my question is, how did you download and run gophish?

**Comment by glennzw** [comment]
I can see the template variables inside the XML of your Word doc, so that seems fine. You need to build gophish from source:

------

### Building From Source
**If you are building from source, please note that Gophish requires Go v1.10 or above!**

To build Gophish from source, simply run ```go get github.com/gophish/gophish``` and ```cd``` into the project source directory. Then, run ```go build```. After this, you should have a binary called ```gophish``` in the current directory.

------
(from the README.md file)


I'll rebuild all the binaries soon so you can just download and run them.

**Comment by BlindChowder** [comment]
It was already downloaded when I started working with it.  I know I have to open Gophish.exe which brings up a command prompt

**Comment by glennzw** [comment]
Unfortunately if you download the gophish binary attachment tracking won't (yet) work. You'll need to compile the code yourself.

I'll shortly be releasing new compiled binaries so you can use attachment tracking with the binaries (the .exe you downloaded).

Thanks for your patience.

**Comment by abhirf** [comment]
I had copied the link of gophish and pasted it in my linux to download it and unzipped it later 

will the attachment work ?

**Comment by glennzw** [comment]
No it won't work (yet).

**Comment by CyberM070** [comment]
@glennzw  I have build from source and the variables in the documents are working, but opening the documents does not result in 'e-mail opened' in the dashboard. What could cause that if the rest is working properly?

**Comment by glennzw** [comment]
@CyberM070 Please open a new issue for this and I'll try help you

**Comment by gakshay47** [comment]
Tried the same steps it's not working,
https://docs.getgophish.com/user-guide/documentation/attachments
