### ISSUE TITLE
Unable to configure GoPhish

### ISSUE THREAD

**Issue by simphiwemayisela** [gophish/gophish#240]
Good Day

I have installed GoPhish toolkit on my 64-bit laptop, however, I cannot  log into http://localhost:3333. I get the error message: "localhost refused to connect"

I tried using Internet Explorer as well as Chrome.

Please help

**Comment by jordan-wright** [comment]
Can you copy/paste the output from your terminal when gophish is started?

**Comment by simphiwemayisela** [comment]
Herewith the ooutput from the terminal:

C:\Users\simphiwe.mayisela\Documents\Security Awareness\GoPhish\gophish_windows_
64bit>gophish.exe
2016/04/14 14:51:40 worker.go:38: Background Worker Started Successfully - Wait
ing for Campaigns
goose: no migrations to run. current version: 20160227180335
2016/04/14 14:51:40 gophish.go:71: Starting phishing server at http://0.0.0.0:8
0
2016/04/14 14:51:40 gophish.go:72: listen tcp 0.0.0.0:80: bind: An attempt was
made to access a socket in a way forbidden by its access permissions.

Simphiwe Mayisela | Group Information Security Officer
Internet Solutions


[cid:image001.jpg@01D1965D.53FB2D30]


T      +27 11 575 8621

M     +27 82 805 1949

F       +27 11 576 8621

**Comment by jordan-wright** [comment]
@simphiwemayisela - if you are still having difficulty, you can change the "phishing_server" port in ```config.json``` to be something > 1024, such as 8080 or 8888. Then, just make sure to specify that port when setting the "URL" for the campaign.

**Comment by simphiwemayisela** [comment]
I have changed the port to 8080 and the web server can start. Thank you

Simphiwe Mayisela | Group Information Security Officer
Internet Solutions


[cid:image001.jpg@01D19680.FDAC8FE0]


T      +27 11 575 8621

M     +27 82 805 1949

F       +27 11 576 8621

**Comment by simphiwemayisela** [comment]
Good Day

The sending profile is currently configured as follows:

[cid:image001.jpg@01D19713.C68542D0]

However, I am not sure if I have configured the email settings correctly as I keep getting the following error message when I try to send a Test Email:

[cid:image002.jpg@01D19713.C68542D0]

Please help


Simphiwe Mayisela | Group Information Security Officer
Internet Solutions


[cid:image003.jpg@01D19713.C68542D0]


T      +27 11 575 8621

M     +27 82 805 1949

F       +27 11 576 8621

**Comment by simphiwemayisela** [comment]
Good Day

Could you kindly send me landing page templates with HTML source code that I can use for my campaign. This is what I have currently:

<html><head>
               <title>Simulated Phishing Scenario</title>
</head>
<body>
<p>You have fallen victim to a simulated phishing attack that has been initiated by the Information Security Officer. Please exercise precaution when viewing attachments or clicking on links that originate from unsolicited senders</p>


</body></html>

Simphiwe Mayisela | Group Information Security Officer
Internet Solutions


[cid:image004.jpg@01D19714.187CB0A0]


T      +27 11 575 8621

M     +27 82 805 1949

F       +27 11 576 8621

**Comment by jordan-wright** [comment]
That looks like it should work just fine. At this time, we do not have any landing page or email templates pre defined.

**Comment by jordan-wright** [comment]
Also, please open new issues for errors, as this one is already closed. We try to keep track of each issue individually.

Thanks,
Jordan

**Comment by simphiwemayisela** [comment]
New issue opened

Simphiwe Mayisela | Group Information Security Officer
Internet Solutions


[cid:image001.jpg@01D19718.262519F0]


T      +27 11 575 8621

M     +27 82 805 1949

F       +27 11 576 8621

**Comment by playjett** [comment]
hello guys,
i hope everyone is good?
please my gophish system is not sending test mails and it keep giving me ERROR SENDING EMAIL after i launch the campaign please help. please recommend to me smtp servers that works, but not Gmail,yahoo and some few.  please reply me here or send mail to  me on burnettelcolimited@gmail.com. mostly i don't see replied issues on my account on github.  THANKS.
