### ISSUE TITLE
Can’t run goohish 

### ISSUE THREAD

**Issue by DB2121** [gophish/gophish#2400]
This is what I get when I try to run gophish I’m not sure what I’m doing wrong 😫
![E6BD4A0E-D8D9-490F-BC7D-FF54FDC6ED89](https://user-images.githubusercontent.com/98005741/154307705-5114423b-10a3-4f5a-8bd9-4e358efc186e.jpeg)

**Comment by glennzw** [comment]
Hi @DB2121. Hmm, strange. It looks like your O/S isn't recognising the gophish binary as an ELF executable, and is trying to run it a shell script. Doing some Googling it looks like you might be running a 64-bit program on a 32-bit machine.

Perhaps try the 32bit version: https://github.com/gophish/gophish/releases/download/v0.11.0/gophish-v0.11.0-linux-32bit.zip

**Comment by DB2121** [comment]
I’m still getting the same error message

**Comment by DB2121** [comment]
I downloaded the file you sent and the error message is still the same I don't know what else to do ![image](https://user-images.githubusercontent.com/98005741/154321707-75438fa5-14e7-4613-bf9f-dd44e1e6bb21.jpeg)

**Comment by DB2121** [comment]
> I downloaded the file you sent and the error message is still the same I don't know what else to do ![image](https://user-images.githubusercontent.com/98005741/154321707-75438fa5-14e7-4613-bf9f-dd44e1e6bb21.jpeg)

Can anyone help please

**Comment by edermi** [comment]
What shell are you using? Is `sudo` aliased to something? Can you run the executable without `sudo`?

**Comment by DB2121** [comment]
Ok thank you for your response I sincerely appreciate. though I’m still a
newbie however I think the shell I use is /use/bin/zsh
Just as shown below. I look forward to hearing from you.

**Comment by edermi** [comment]
As @glennzw said, your shell seems to interpret the ELF-file as a script. Can you try a different shell?

Unless you provide full information about your environment it is difficult to find out what's wrong and nobody will be able to help you. 
Are you working on a clean Kali installation or did you change anything?

**Comment by DB2121** [comment]
No I didn’t change anything at all. After installing kali on my VMware work
station. I installed tor, proxychains, htop neofetch gdebi, I’m not sure
what kind of change must have cause the file to not work
I really need help on this bro 🙏

**Comment by vonjk** [comment]
Maybe you can try to run directly from the source code,if you have golang environment `go run gophish.go`

**Comment by DB2121** [comment]
Ok thanks I really appreciate bro. Have you tried installing angrily
recently
I think there’s something wrong with the platform

**Comment by Maroaluka** [comment]
I am having issues running gophish 
Please can someone help

**Comment by glennzw** [comment]
> I am having issues running gophish 
> 
> Please can someone help

Please open a new issue, with details as to the trouble you're having.

**Comment by glennzw** [comment]
Closing out, feel free to reopen if you're still having trouble.
