### ISSUE TITLE
Hello developers

### ISSUE THREAD

**Issue by digitalboi0** [gophish/gophish#2403]
I am having having issues running my gophish admin server on my Amazon Ec2 instance, I have tried multiple Instance, I add the new rules to allow me access it yet when I start my gophish sever and I go to this url https://Amazon ip:3333 nothing happens I have tried all resources on the internet yet nothing happens I would be happy if you assist me 
Thank you

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to re-open.
