### ISSUE TITLE
Attachment problem and e-mail report problem

### ISSUE THREAD

**Issue by adricustodio** [gophish/gophish#2404]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  0.11.0

Brief description of the issue: Trying to track the attachment and it's not working, im using the model of the gophish webpage to test and still not working, and the "report" button does nothing.. i click and it asks "the RID will be flagged as reported" but it does not compute as reported.

What are you expecting to see happen? : the tracking fields filled with information.

What are you seeing happen? no field on the attachments are filled

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
Hi @adricustodio, sorry to hear you're having trouble with attachment support. Are you building from source, or downloading the binary? The attachment tracking will only work (for now) if you build from source.

Also, when you say the 'reporting link is not working', do you mean when you push the report button on the gophish ui? Perhaps check the browser console; if you're serving the admin page off SSL and the phishing page off plaintext you might see an error like this:

![Screenshot 2021-04-06 at 17 09 36](https://user-images.githubusercontent.com/3966613/113742862-f321c880-96fa-11eb-995f-57dbad559499.png)

The solution here would be to either server both off the same protocol, or allow mixed content in your browser (with caution).

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen.
