### ISSUE TITLE
Differentiating Mail-From and Header-From

### ISSUE THREAD

**Issue by stepbysec** [gophish/gophish#2406]
_What version of Gophish are you using?:_ 0.11.0 (built from latest sources to be able to use the attachment tracking feature)

_Brief description of the issue:_ Gophish currently does not allow to set a **Mail-From** different from the **Header-From**.
This scenario is frequently used in phishing attempts when DMARC is not enabled on the spoofed domain.
This allows to lure users in believing that the e-mail comes from domainXYZ.com when you actually do not own that domain and send from domainABC.biz for instance.

_What are you expecting to see happen? :_ Be able to set a Header-From different from the Mail-From.

_What are you seeing happen?_ Currently, both match.

In the meantime, I circumvented the issue by setting up Postfix on my gophish server, poiting my e-mail profile to that local instance and configuring Postfix as follows:
 * Append the following lines to **/etc/postfix/main.cf**:
```
sender_canonical_classes = envelope_sender
sender_canonical_maps =  regexp:/etc/postfix/sender_canonical_maps
```
 * Append the following lines to **/etc/postfix/sender_canonical_maps**: 
```
/.+/    security@groupeactual.eu  
 ```
 * Then run:
```
sudo postmap /etc/postfix/sender_canonical_maps
sudo service postmap reload
```

**Comment by glennzw** [comment]
Does this PR address your issue? https://github.com/gophish/gophish/pull/2334

I'll get it merged in soon.

**Comment by glennzw** [comment]
De rein!
