### ISSUE TITLE
How to setup malicious files via email templates with gophish (confused)

### ISSUE THREAD

**Issue by wilsonr88** [gophish/gophish#2407]
Is there a write up on how to setup malicious files in gophish. I want to set one up but its not as straight forward as I thought it was going to be. Any help or write up or instructions or something would be appreciated. I tried attaching a blank word document and test sending to myself to see if it show up in the email but it didnt. thanks.

**Comment by glennzw** [comment]
Hi @wilsonr88, here's the documentation on attachment tracking:

https://docs.getgophish.com/user-guide/documentation/attachments

It does require a bit of work at the moment, and you'll need to compile from source as opposed to just download the binary. I'll be releasing compiled binaries soon.

In the future I'd like to make it a little easier to track too. Hope that helps.

**Comment by wilsonr88** [comment]
Hi Glenn,

Would someone be able to walk me through this by any chance?

**Comment by wilsonr88** [comment]
> Hi @wilsonr88, here's the documentation on attachment tracking:
> 
> https://docs.getgophish.com/user-guide/documentation/attachments
> 
> It does require a bit of work at the moment, and you'll need to compile from source as opposed to just download the binary. I'll be releasing compiled binaries soon.
> 
> In the future I'd like to make it a little easier to track too. Hope that helps.

@glennzw I have uploaded the word document template and have ran a campaign but when i open it in my email it doesnt show that the email has been open. Any advice on this issue?

**Comment by glennzw** [comment]
Did you use one of the sample word documents?

Also, just to confirm, you're compiling from source right?

**Comment by wilsonr88** [comment]
Yes I used the word document template and it uploaded but when I opened the
doc it didn't register to the server as opened.

**Comment by glennzw** [comment]
OK - and could you detail how you installed / setup gophish please

**Comment by wilsonr88** [comment]
I wouldn't be able to as I use it for my work snd my technical manager set
it up long before I was there

**Comment by glennzw** [comment]
Ah unfortunately if it's an old installation you won't have attachment support as that's a new feature
