### ISSUE TITLE
Resetting Gophish password

### ISSUE THREAD

**Issue by ryanc511** [gophish/gophish#2408]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.11.0
Brief description of the issue: 
Installed Gophish as a service using nssm and cant login.  I need assistance to reset the password.
What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
Hi @ryanc511; to reset the password you'll need to edit the password field in the database. On a Linux based system you can do it like so:

```
§ yum install -y sqlite ||apt-get install -y sqlite3 libsqlite3-dev
§ sqlite3 gophish.db 'update users set hash="$2a$10$IYkPp0.QsM81lYYPrQx6W.U6oQGw7wMpozrKhKAHUBVL4mkm/EvAS" where username="admin";'
```

This will reset the admin password to 'gophish'

**Comment by ryanc511** [comment]
Hi Glenn,
Thanks I was able to get it resolved.

Ryan Connelly
Network Administrator
412-737-9698  ***@***.******@***.***>
***@***.***

**Comment by highrider0602** [comment]
tried the above suggestion and edited the where username parameter to the usernamer i changed it to and i get the following output, 


![gophish](https://user-images.githubusercontent.com/62209183/195446939-983dd93c-d5d8-409a-ba23-8555981dbedb.png)

!


Any advice is appreciated. Thank you

**Comment by glennzw** [comment]
@highrider0602 Can you do a sanity check and make sure the gophish.db file is in your current folder with the 'ls -lh' command.

**Comment by highrider0602** [comment]
sorry for the late followe up 

![gophishissue](https://user-images.githubusercontent.com/62209183/196342963-84ab7296-f8fa-4e6c-99cb-48c081f616ab.png)

Here is what i get when i check

**Comment by glennzw** [comment]
OK so the `gophish.db` file is there, but it's complaining there's no user table. Try running the `.tables` command from inside the sqlite prompt:

```
$ sqlite3 gophish.db
SQLite version 3
Enter ".help" for usage hints.
sqlite> .tables
attachments           imap                  role_permissions    
campaigns             imap_old              roles               
email_requests        mail_logs             smtp                
events                pages                 targets             
goose_db_version      permissions           templates           
group_targets         reported              users               
groups                reported_attachments  webhooks            
headers               results             
sqlite> 
```
