### ISSUE TITLE
Error creating sending profile

### ISSUE THREAD

**Issue by simphiwemayisela** [gophish/gophish#241]
Good Day

I managed to resolve the initial error about port by appending ":25" at the end of the mail server hostname.

However, I am now getting a new error when trying to send a Test email:

 2016/04/15 12:49:26 worker.go:186: Creating email using template
 2016/04/15 12:49:26 worker.go:227: Sending Email to simphiwe.mayisela@is.co.za
 2016/04/15 12:50:57 worker.go:230: 550 **Rejected because 196.14.169.11 is in a b
lack list at cbl.abuseat.org**
127.0.0.1 - - [15/Apr/2016:12:49:26 +0200] "POST /api/util/send_test_email?api_k
ey=26ddad66b0ef2a3b4359f2857c98e47fa2413b575f140825e0c28e26de3a1f1e HTTP/1.1" 50
0 128 "http://localhost:3333/sending_profiles" "Mozilla/5.0 (Windows NT 6.3; WOW
64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36"

I am not sure where it is picking up 196.14.169.11 from.

**Comment by simphiwemayisela** [comment]
Any feedback on this issue?

**Comment by jordan-wright** [comment]
Looks like your IP is blacklisted and the email was rejected by the receiver. Nothing to do except send from a different IP address.

**Comment by seguridad-vnzl** [comment]
hello I have a problem today with the gophish application.

when I send the email template, it does not show me the email address I need, but if it shows me the email address of hosting, can you help me solve this problem please
