### ISSUE TITLE
email template and landing pages loads endlessly

### ISSUE THREAD

**Issue by BueriAugustin** [gophish/gophish#2411]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
Gophish v0.11.0 as service on debian 11

Brief description of the issue: 

email template and landing pages loads endlessly after installation of gophish, I can't create a new template

What are you expecting to see happen? :

What are you seeing happen?
![image](https://user-images.githubusercontent.com/96128842/156789557-3faef353-3f60-4196-85f4-1903207604d0.png)

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by todonnal2-r7** [comment]
Having this same problem on fresh Ubuntu server. Fresh clone of Github repository doesn't fix it. Tried multiple browsers.

The template creation form opens if I click "New Template" but it won't save after I fill out the form. Same behavior on Landing Pages.

**Comment by BueriAugustin** [comment]
> I solved this problem by switching versions of GoLang. The version that worked for me was go 1.16.14.
> 
> You may need to switch versions a couple times to find the right one for your specific GoPhish installation.

This solution doesn't work for me. I have tried many version of go but the problem still persists

**Comment by BueriAugustin** [comment]
I solved the problem by using the executable* for linux and configuring it as a service

*https://github.com/gophish/gophish/releases/download/v0.11.0/gophish-v0.11.0-linux-64bit.zip
