### ISSUE TITLE
gophish/macos

### ISSUE THREAD

**Issue by Guiyome8** [gophish/gophish#2412]

**Comment by Guiyome8** [comment]
Hello,
I work on a macos terminal and I can't configure gophish.
I first tried the  `/go build` but without success.
Then I saw a related problem and I tried `./gophish` and `sudo ./gophish `but without success either.



<img width="570" alt="Capture d’écran 2022-03-04 à 18 23 31" src="https://user-images.githubusercontent.com/100539319/156812550-46c8745c-0341-4a21-a6ee-04b0ca81c295.png">

I don't see any other solutions so I'm asking for your help.
thank you :)

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to re-open.
