### ISSUE TITLE
Only email sent is tracked, no link clicked or email opened whatsoever

### ISSUE THREAD

**Issue by Studentz322** [gophish/gophish#2418]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: v.0.11.0

Brief description of the issue: My gophish is unable to track any email being opened, link being clicks and etc. The only thing that my gophish manage to track is email send

What are you expecting to see happen? : Hoping the dashboard to all the data (email opened, link clicks and etc)

What are you seeing happen? Only email send is shown as submitted in the gophish dashboard

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
Hi there. You'll need to share a bit more information for us to help you. e.g:

 * Your email template
 * What happens when a user clicks an email after receiving a campaign email

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to re-open.
