### ISSUE TITLE
Tracker not working correctly.

### ISSUE THREAD

**Issue by timlearyy** [gophish/gophish#242]
I sent out a test campaign to several of my users today.  When the email is opened the {{.Tracker}} is registering as link clinked instead of email opened.  I have included the html below.
```
<html>
<head>
	<title></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
<center><img src="http://205.186.139.88/tslogo_sig.png" /></center>

<table cellpadding="0" cellspacing="0" width="100%">
	<tbody>
		<tr>
			<td>
			<table cellpadding="0" cellspacing="0" width="100%">
				<tbody>
					<tr>
						<td style="font-weight: bold; font-size: 12px; font-family: Helvetica, Arial, sans-serif;
              color: #ffffff; width: 100%; text-align: left; background: #daae28; padding: 10px;">
						<style type="text/css">.caption-link { color: #ffffff; }
                a.caption-link, a.caption-link:active, a.caption-link:link, a.caption-link:visited { color: #ffffff; }
						</style>
						TeamSupport Password Reset Notification</td>
					</tr>
				</tbody>
			</table>
			</td>
		</tr>
		<tr>
			<td style="text-align: center; padding-left: 0; border-left: solid 1px #eeeeee; border-right: solid 1px #eeeeee; background:#ffffff;">
			<table width="100%">
				<tbody>
					<tr>
						<td style="font-size: 12px; font-weight: normal; font-family: Arial; padding: 7px; 
              text-align: left; color: #555555;">Your password was reset for your TeamSupport.com account.<br />
						<br />
						Click <a href="{{.URL}}">here</a> to login and change your password.<br />
						<br />
						This email was generated automatically, please do not reply.<br />
						&nbsp;</td>
					</tr>
				</tbody>
			</table>
			</td>
		</tr>
		<tr>
			<td>
			<table cellpadding="0" cellspacing="0" width="100%">
				<tbody>
					<tr>
						<td style="font-weight: bold; font-size: 12px; font-family: Helvetica, Arial, sans-serif;
              color: #ffffff; line-height: 1em; width: 100%; text-align: left; background: #d27528;
              padding: 10px; margin: 5px">
						<style type="text/css">.caption-link { color: #ffffff; }
						</style>
						TeamSupport</td>
					</tr>
				</tbody>
			</table>
			</td>
		</tr>
	</tbody>
</table>
{{.Tracker}}</body>
</html>
```

**Comment by jordan-wright** [comment]
Hey @timlearyy - thanks for the report!

Any way you can give us the HTML of an actual email that was delivered? I'm curious what it looks like when the user receives the email.

You can just x.x.x.x out the urls, we'll just need to see the path. So, if your url is 1.2.3.4/track?rid=1234, you can make it x.x.x.x/track?rid=1234.

Thanks!

**Comment by jordan-wright** [comment]
Hey @timlearyy - just checking in. Are you able to grab the HTML of an actual email that was delivered?

**Comment by timlearyy** [comment]
Here you go Jordan:

<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"><title></title>

</head>
<body>
<center><img src="http://***.***.***.***/tslogo_sig.png"></center>

<table cellpadding="0" cellspacing="0" width="100%">
                <tbody>
                                <tr>
                                                <td>
                                                <table cellpadding="0" cellspacing="0" width="100%">
                                                                <tbody>
                                                                                <tr>
                                                                                                <td style="font-weight: bold; font-size: 12px; font-family: Helvetica, Arial, sans-serif;

              color: #ffffff; width: 100%; text-align: left; background: #daae28; padding: 10px;">
                                                                                                <style type="text/css">.caption-link { color: #ffffff; }

                a.caption-link, a.caption-link:active, a.caption-link:link, a.caption-link:visited { color: #ffffff; }
                                                                                                </style>
                                                                                                TeamSupport Password Reset Notification</td>
                                                                                </tr>
                                                                </tbody>
                                                </table>
                                                </td>
                                </tr>
                                <tr>
                                                <td style="text-align: center; padding-left: 0; border-left: solid 1px #eeeeee; border-right: solid 1px #eeeeee; background:#ffffff;">
                                                <table width="100%">
                                                                <tbody>
                                                                                <tr>
                                                                                                <td style="font-size: 12px; font-weight: normal; font-family: Arial; padding: 7px;

              text-align: left; color: #555555;">Your password was reset for your TeamSupport.com account.<br>
                                                                                                <br>
                                                                                                Click <a href "***.***.***.***/ouch:443?rid=adeecd6554da1b6e5c26301964ebe90954590b23700251a81e0d7d82bb03e6ea" >here</a> to login and change your password.<br>
                                                                                                <br>
                                                                                                This email was generated automatically, please do not reply.<br>
                                                                                                &nbsp;</td>
                                                                                </tr>
                                                                </tbody>
                                                </table>
                                                </td>
                                </tr>
                                <tr>
                                                <td>
                                                <table cellpadding="0" cellspacing="0" width="100%">
                                                                <tbody>
                                                                                <tr>
                                                                                                <td style="font-weight: bold; font-size: 12px; font-family: Helvetica, Arial, sans-serif;

              color: #ffffff; line-height: 1em; width: 100%; text-align: left; background: #d27528;

              padding: 10px; margin: 5px">
                                                                                                <style type="text/css">.caption-link { color: #ffffff; }
                                                                                                </style>
                                                                                                TeamSupport</td>
                                                                                </tr>
                                                                </tbody>
                                                </table>
                                                </td>
                                </tr>
                </tbody>
</table>

<p><img src="https://***.***.***.***:***/track?rid=eb7594e087177d4fdb21102b4d1154dd12c161c661b631a6caeac1670e4aeac7"></p>

<img style="display: none" src="***.***.***.***/ouch:***/track?rid=adeecd6554da1b6e5c26301964ebe90954590b23700251a81e0d7d82bb03e6ea">
<img src="https://u2722366.ct.sendgrid.net/wf/open?upn=1USBPjr-2FD5hZvgyJhuwtbr7afht9cj3yqTDb9l-2FhL9BxaGQQVHAcjdf8T36MQqPLMWrQKwRUuHQRgePTfBWl-2FdwpV5aO6gvgCTCHgmZGBvtL-2Fg4Zgc8gQMngSXmx4I6BaAnPIADnuI6XEdtGDxlO1wvCxQtJGCe67zGh6BtSnuO-2BetRLZFp-2FXx0k9wM7D6pCL8gvFAQOneirr3RM4QYzRp5AM64qvX08LgVMslB67MA-3D" alt="" width="1" height="1" border="0" style="height:1px !important;width:1px !important;border-width:0 !important;margin-top:0 !important;margin-bottom:0 !important;margin-right:0 !important;margin-left:0 !important;padding-top:0 !important;padding-bottom:0 !important;padding-right:0 !important;padding-left:0 !important;">
</body> </html>

[cid:image001.jpg@01D1581D.B7311C80]<http://www.ezlynx.com/?utm_source=signature&utm_medium=email&utm_content=general&utm_campaign=ezlynx>

Mark Lozano

office 877-932-2382x376

email<mailto:mark.lozano@ezlynx.com> |

website<http://www.ezlynx.com/?utm_source=signature&utm_medium=email&utm_content=general&utm_campaign=ezlynx>

[cid:image002.gif@01D1581D.B7311C80]<http://www.facebook.com/ezlynx>[cid:image003.gif@01D1581D.B7311C80]<http://www.twitter.com/ezlynx>[cid:image004.gif@01D1581D.B7311C80]<http://www.linkedin.com/company/ezlynx>[cid:image005.gif@01D1581D.B7311C80]<http://www.youtube.com/ezlynxsolutions>




Visit ezlynx.com<http://www.ezlynx.com/?utm_source=signature&utm_medium=email&utm_content=general&utm_campaign=ezlynx> today to find out how to streamline your agency's workflow!

**Comment by jordan-wright** [comment]
I think this might be related to https://github.com/gophish/gophish/issues/246 - can you confirm if that workaround works for you?

**Comment by timlearyy** [comment]
When I get back in the offices on Monday I will give it a try and let you know.

[cid:image001.jpg@01D1581D.B7311C80]<http://www.ezlynx.com/?utm_source=signature&utm_medium=email&utm_content=general&utm_campaign=ezlynx>

Mark Lozano

office 877-932-2382x376

email<mailto:mark.lozano@ezlynx.com> |

website<http://www.ezlynx.com/?utm_source=signature&utm_medium=email&utm_content=general&utm_campaign=ezlynx>

[cid:image002.gif@01D1581D.B7311C80]<http://www.facebook.com/ezlynx>[cid:image003.gif@01D1581D.B7311C80]<http://www.twitter.com/ezlynx>[cid:image004.gif@01D1581D.B7311C80]<http://www.linkedin.com/company/ezlynx>[cid:image005.gif@01D1581D.B7311C80]<http://www.youtube.com/ezlynxsolutions>




Visit ezlynx.com<http://www.ezlynx.com/?utm_source=signature&utm_medium=email&utm_content=general&utm_campaign=ezlynx> today to find out how to streamline your agency's workflow!

**Comment by jordan-wright** [comment]
Hey @timlearyy any luck giving this a shot?

**Comment by jordan-wright** [comment]
Hey @timlearyy, did that fix work out for you?

**Comment by timlearyy** [comment]
I’ve been extremely busy at work and haven’t had a chance to test.  Sorry.

[cid:image001.jpg@01D1581D.B7311C80]<http://www.ezlynx.com/?utm_source=signature&utm_medium=email&utm_content=general&utm_campaign=ezlynx>

Mark Lozano

office 877-932-2382x376

email<mailto:mark.lozano@ezlynx.com> |

website<http://www.ezlynx.com/?utm_source=signature&utm_medium=email&utm_content=general&utm_campaign=ezlynx>

[cid:image002.gif@01D1581D.B7311C80]<http://www.facebook.com/ezlynx>[cid:image003.gif@01D1581D.B7311C80]<http://www.twitter.com/ezlynx>[cid:image004.gif@01D1581D.B7311C80]<http://www.linkedin.com/company/ezlynx>[cid:image005.gif@01D1581D.B7311C80]<http://www.youtube.com/ezlynxsolutions>




Visit ezlynx.com<http://www.ezlynx.com/?utm_source=signature&utm_medium=email&utm_content=general&utm_campaign=ezlynx> today to find out how to streamline your agency's workflow!

**Comment by jordan-wright** [comment]
Going to go ahead and close this out for now. @timlearyy - let me know if this still doesn't work and we can re-open :smile:
