### ISSUE TITLE
Hello quick questions to developpers

### ISSUE THREAD

**Issue by jnthnm** [gophish/gophish#2420]
Hello, this is not really an issue more like some questions

I'm using the last update version of gophish on a windows server it seems working fine so far

Does gophish can support large scale of campaign? Like 1000 mails sent to 1000 users ?
I'm using public SMTP of office, I guess I have to differ the mails sent to not be blocked ?

Thanks a lot for your responses

**Comment by gear0** [comment]
Hi jnthnm,
from my experience gophish can handle even lager campaigns especially if you don't send them at the same time. I guess 1000 will be fine though. The limiting factor will be your mail server which is used for delivery and the receiving mail server which might block your mail server if you send to many mails in a short period. If you use a public SMTP server of office (I guess you mean Microsoft Office), then they will probably won't allow you to send large amounts of mails within a short period.

**Comment by glennzw** [comment]
Hi @jnthnm, @gear0 is absolutely correct. 1000 emails is quite a small campaign. The only thing that might start tripping you up is viewing the gophish data in the browser if you send a very large campaign (as its currently all displayed within the browser). To get around this you could (a) make sure your browser has a LOT of RAM available, or (b) take my PR enabling pagination https://github.com/gophish/gophish/pull/2019 for a spin (I tested this with 20,000 email campaigns with no problems).
