### ISSUE TITLE
Admin page not loading

### ISSUE THREAD

**Issue by apimant** [gophish/gophish#2421]
I am using Gophish 0.11.0
I am running Gophish on a virtual private server, I have configured and changed my listen  address to 0.0.0.0, I have tried Gophish with apache on and off and also nginx off and on, whenever I run Gophish it runs well on the terminal but when I try to access my admin page with my servers IP address and port number the page keeps loading and eventually shows unable to connect, I have tried both HTTP and HTTPS,my server works perfectly as I have tried hosting some webpages on it and it works perfectly, I have also rebooted my VPS and tried, my firewall is also turned off.

<img width="971" alt="Screen Shot 1400-12-28 at 09 05 09" src="https://user-images.githubusercontent.com/101924589/159115321-2c561c83-55fa-49da-bee0-de986ed045a5.png">

**Comment by glennzw** [comment]
Hi there. This sounds like there are firewall rules blocking port 3333. 

You could confirm this by doing the following:

On your server stop gophish and run this command:
`ncat -v -e /bin/cat -k -l 3333`

(this will listen on port 3333)


On your laptop run the command `nc -v x.x.x.x 3333`. You should see a 'Connection succeeded' message, and then anything you type should be echo'd back to you (after hitting return):
```
➜  ~ nc -v x.x.x.x 3333
Connection to x.x.x.x port 3333 [tcp/dec-notes] succeeded!
hello
hello
test
test
```

If the above FAILS, then you know its a firewall or other routing issue.

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to re-open.
