### ISSUE TITLE
Admin Server not loading

### ISSUE THREAD

**Issue by abhirf** [gophish/gophish#2422]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: v0.11.0

Brief description of the issue: I changed my certificate and key in the admin_server inside config.json file. My website that i am using is working perfectly. I can load the website page. But the moment i load the admin server page with the port 1724 or 3333 it is showing me error and not loading. I have used the port 443 for phishing_server port and 3333 for admin_server. I was using a server IP address before and right now if i load on that the admin server page works but not on the website link. 

What are you expecting to see happen? : the admin_server to run on the website i specified. 

What are you seeing happen? the admin server loading on the server ip address and not on the website port. 

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by abhirf** [comment]
Here is the config.json file
![Config_file](https://user-images.githubusercontent.com/96383129/159310646-d2a0577e-631e-429d-a466-365bf2eb1d86.PNG)

**Comment by abhirf** [comment]
![Connection error](https://user-images.githubusercontent.com/96383129/159310863-24046d3b-f7b7-4321-8bd6-3a06b8d99852.PNG)
![console](https://user-images.githubusercontent.com/96383129/159310886-98c0a213-619d-44de-be76-3af1a27373fb.PNG)

**Comment by abhirf** [comment]
If i access the phish server port on 80 it doesnt load but if i load it on 443 it works. But somehow i cannot access the admin server on my website. It is only accessable on the server i am using

**Comment by glennzw** [comment]
The admin server will be running on 3333, not 443. So anything you're seeing on 443 is something else (maybe apache or something).

That error looks like a bad certificate. One thing you could try is to serve the admin page over cleartext, just so you know you're actually reaching the gophish admin server. Change your `config.json` to:

```"use_tls": false```

If you're then able to access the admin portal on `http://yourserver.com:3333` then it's probably a certificate issue.

**Comment by abhirf** [comment]
I ran the admin server on port 3333 but it showed connection time out. So what is happening is that if i run on the IP address using the same port it is working but instead if i use the website name along with the port to use the admin server it shows error

**Comment by abhirf** [comment]
Yes exactly. with domain it isnt loading and with IP address it works fine

**Comment by glennzw** [comment]
OK so that's a DNS issue by the sounds of it, and unfortunately there's not much we can help you with on that front.

**Comment by glennzw** [comment]
It's hard to tell if it's actually connecting, but it might be the cert. What happens if you use the standard gophish cert?

**Comment by abhirf** [comment]
If i use the standard gophish certificate, it is the same thing. I can only
use the gophish admin server through the Ip address ( 1.1.1.1:3333) and not
through the domain that i have.

**Comment by glennzw** [comment]
The domain, does it definitely have an A record to the IP? i.e:

```bash
$ host my.phish.domain.com
my.phish.domain.com has address 1.2.3.4
```

**Comment by abhirf** [comment]
Sorry but i didn’t understand what you meant. Could please elaborate?

**Comment by glennzw** [comment]
What is the IP address associated to your domain? You could check with this tool: https://mxtoolbox.com/DNSLookup.aspx

It should match the IP address that is working.

**Comment by abhirf** [comment]
no the two are different. The IP address that i use is the one of the server i am using and the address associated to the domain is different

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to re-open.
