### ISSUE TITLE
[Open question] Custom sender per recipient

### ISSUE THREAD

**Issue by stepbysec** [gophish/gophish#2423]
Would it be possible to use Gophish for the following scenario?
- For each recipient to target, I would first identify a contact they have already shared e-mails with.
- I would then load those data somewhere (Gophish, Postfix, anything else?) so that e-mails are customized for each recipient with their previously identified contact as sender. (I only need the header-from field to be customized, the mail-from will be the same for all e-mails sent, so that they do not fail SPF)
- I would set up an e-mail template looking like "Your contact shared a file with you" e-mails we see so often in real phishing attempts.

Doing so would allow to test users behaviors when they receive such e-mails from known contacts that have had their own mailbox compromised.

**Comment by stepbysec** [comment]
Maybe the quickest solved issue ever ;).
It could actually be acceptable to use a generic sender's address, but just customize the e-mail template with the contact details.
I guess I could use the First name and Last name fields to matche the sender's details instead of the recipient's, and that would do the trick

**Comment by glennzw** [comment]
I'm not sure I 100% understand your question, but the short story is that all users in a single campaign will receive the same email from the same sending profile. You can customise your sending profile to be from whoever you want it to be from.

**Comment by jesseedwards1** [comment]
hey @stepbysec did you manage to achieve it ?
Im looking for the same thing , to set custom sender-envelope name for each user in users group and send email to everyone with same sender email but different custom sender-name which i set before .
