### ISSUE TITLE
Please comprehensive Guide on Creating Mysql Data for Gophish

### ISSUE THREAD

**Issue by uchenna2k2** [gophish/gophish#2425]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  0.11.0

Brief description of the issue:  I am a bit confused on how to install mysql database. 

**For this command.**
"db_name" : "mysql",
"db_path" : "root:@(:3306)/gophish?charset=utf8&parseTime=True&loc=UTC",

**I know that I will go into my config.json file and change db_name to mysql
For the second command, will I input my kali root username or password or will I create a random name and password for the mysql database?**

**For this command**
[mysqld]
sql_mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
I know that I will locate this path  **/etc/mysql/mysql.cnf** and input the above code at the end. 
I cannot find mysql.cnf in the specified path but found it inside **/etc/mysql/conf.d/mysql.cnf**
I want to ask if this is ok.

**For the last confusing path**
CREATE DATABASE gophish CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;.

I am supposed to log into mysql. Please how do I log into mysql, am I supposed run this on gophish terminal. I searched for mysql on my kali linux and nothing came up. Please I need help urgently. 

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
Hi @uchenna2k2, you need to do two broad things:

1. Setup MySQL on your computer/server
2. Configure gophish to connect to that mysql server


You'll need to check a guide for installing MySQL on Kali, but you'll want to create user and password for the mysql account. Once you've done that, from your mysql prompt create a gophish database with the command:

```
CREATE DATABASE gophish CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```

Then your config.json should look something like this:

```json
{
	"admin_server": {
		"listen_url": "127.0.0.1:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "gophish_admin.key"
	},
	"phish_server": {
		"listen_url": "0.0.0.0:80",
		"use_tls": false,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "mysql",
	"db_path": "YOURMYSQLUSER:YOURMYSQLPASSWORD@(:3306)/gophish?charset=utf8&parseTime=True&loc=UTC",
	"migrations_prefix": "db/db_",
	"contact_address": "",
	"logging": {
		"filename": "",
		"level": ""
	}
}
```

...substituting YOURMYSQLUSER and YOURMYSQLPASSWORD.

Hope that helps.

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to re-open.

**Comment by LoreMenyatso** [comment]
Hey should i  edit any config file in @ etc/mysql/... ?
