### ISSUE TITLE
Gophish url only working on my pc

### ISSUE THREAD

**Issue by Cesarsilva000** [gophish/gophish#2426]
pls guys i need help i have done everything as required on gophish so when i set up campaign i use 127.0.0.1 as url i send the emails when i check it on my pc it works on my pc but on other devices it doesnt work

**Comment by jordan-wright** [comment]
127.0.0.1 is the localhost address. Networking rules dictate that this address is only reachable on the same machine Gophish is running.

You need to update your Gophish configuration to have it listen on all interfaces, e.g. "0.0.0.0:<port>".

Then you need to use the Gophish instance's IP address (not localhost) to reach it.

**Comment by rafaelribeirong** [comment]
> 127.0.0.1 é o endereço do host local. As regras de rede determinam que esse endereço só pode ser acessado na mesma máquina em que o Gophish está sendo executado.
> 
> Você precisa atualizar sua configuração Gophish para que ele ouça em todas as interfaces, por exemplo, "0.0.0.0:".
> 
> Então você precisa usar o endereço IP da instância Gophish (não localhost) para alcançá-lo.

é possivel você explicar com mais detalhes?
Eu também consigo fazer tudo porém não consigo que outras pessoas acessem para o teste
