### ISSUE TITLE
Client sent an HTTP request to an HTTPS server

### ISSUE THREAD

**Issue by northernligh** [gophish/gophish#2427]
Am getting an error that **Client sent an HTTP request to an HTTPS server**

![image](https://user-images.githubusercontent.com/102486579/160298916-f1f70028-4fcd-47aa-ba11-28fef2dab96b.png)

**Comment by jordan-wright** [comment]
This means Gophish is configured to use TLS. Add "https://" to the front of your URL and you should be good to go.
