### ISSUE TITLE
Extra help concerning gophish url

### ISSUE THREAD

**Issue by Cesarsilva000** [gophish/gophish#2428]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.11

Brief description of the issue: thanks alot Jordan Wright but pls I need extra help so how do I know/locate my gophish instance ip or is that my normal ip address pls help me 

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
Hi @Cesarsilva000, I'm not sure I understand your question. You need to host gophish on an IP that is publicly accessible. e.g on DigitalOcean or Amazon AWS.

**Comment by Cesarsilva000** [comment]
Oh so that's the only way
But I thought someone said you can point your domain to your gophish server
won't that work if it will what is my gophish server/ip
Pls help me out

**Comment by Cesarsilva000** [comment]
Oh and is there any other  GPS I can use

**Comment by glennzw** [comment]
Gophish needs to be installed on a publicly accessible IP. You can have a domain that points to that IP.

I'm not sure what you mean by GPS.

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to re-open.

**Comment by Cesarsilva000** [comment]
Thanks for the reply
Pls what ip should I point my domain to
Should I point it to my ip address or ipv4 address or 127.0.0.1 or
0.0.0.0:80
Pls help me out
