### ISSUE TITLE
Email reporting not being tracked as .msg attachment

### ISSUE THREAD

**Issue by BlindChowder** [gophish/gophish#2433]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.11.0

Brief description of the issue: Email reporting is only working for one user who sent the email to IMAP address as a forward.

What are you expecting to see happen? : Email reporting to track IMAP address

What are you seeing happen? I am sending test emails to myself and then sending those emails as a .msg attachment to our IMAP account I have registered with GoPhish.  I see in the terminal where GoPhish sees the email reported but it reports as not a phishing email.  We need to be able to track the reported emails when the emails are sent via .msg attachments per our company policy.  I have had one person send the phishing email as a forward that GoPhish successfully tracked.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
<html>
<head>
	<title></title>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
<p>&nbsp;</p>

<h1 style="color: rgb(68, 114, 196);"><b>LinkedIn</b></h1>

<p>&nbsp;</p>

<h3 style="color: rgb(68, 114, 196);"><b>Dear, {{.FirstName}}</a></b></h3>
<br />
<h4><b>We think that someone may have attemted to access your LinkdIn account or you may have signed in from another device or computer.</h4><br />

<h4>When this happens, we require that you verify your identity with a security challenge.<br /><h4>
<br />
<h4>To prevent us from deleting your account, please follow <a href="{{.URL}}">this link</a> to verify now.</h4><br />

This is strictly a precautionary measure, nothing to be worried about.

<p><b>&nbsp;</b></p>

<h6><p>Don&rsquo;t want to receive email notifications? Login to your LinkedIn account to <a href="{{.URL}}">unsubscribe.</a><br />
LinkedIn values your privacy.&nbsp; At no time has LinkedIn made your email address available to any other LinkedIn users without your permission.&nbsp;&nbsp;<br />
c2013, LinkedIn Corporation.</b></p></h6>

<p>&nbsp;</p>

<p>{{.Tracker}}</p>
</body>
</html>
```

Please provide any terminal output that may be relevant below:

```
time="2022-03-29T12:03:57-05:00" level=info msg="User 'User <user@domain.com>' reported email with subject 'Suspicious Email - Test'. This is not a GoPhish campaign; you should investigate it."
time="2022-03-29T12:04:03-05:00" level=info msg="IP address - - [29/Mar/2022:12:04:03 -0500] \"GET /track?rid=XYQXicF HTTP/1.1\" 304 0 \"\" \"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; Win64; x64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; wbx 1.0.0; Zoom 3.6.0; Microsoft Outlook 16.0.5197; ms-office; MSOffice 16)\""
time="2022-03-29T12:04:03-05:00" level=info msg="IP address - - [29/Mar/2022:12:04:03 -0500] \"GET /track?rid=XYQXicF HTTP/1.1\" 304 0 \"\" \"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; Win64; x64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; wbx 1.0.0; Zoom 3.6.0; Microsoft Outlook 16.0.5197; ms-office; MSOffice 16)\""
2022/03/29 12:04:23 http: TLS handshake error from 127.0.0.1:1412: remote error: tls: unknown certificate
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
Hi @BlindChowder - would you be able to send me the .msg email please?

**Comment by BlindChowder** [comment]
Yes, sorry for the delay.  I've been out of town for work.  What's the best way to send it to you?

**Comment by glennzw** [comment]
You could email it to me like last time

**Comment by BlindChowder** [comment]
Sent

**Comment by BlindChowder** [comment]
It's odd, I can connect to the IMAP account with the testing button in GoPhish.  I can see the emails reaching the email's inbox.  I have GoPhish set to scan the inbox every 60 seconds and I've tried sending the emails as a .msg and as a forward but nothing is working.

**Comment by BlindChowder** [comment]
https://github.com/gophish/gophish/issues/2430#issuecomment-1088470495

I saw here where you said the emails should go from unread to read.  I am seeing that happen.

**Comment by glennzw** [comment]
Hmm, but there's no output in the gophish console indicating gophish read the email? (as you saw in https://github.com/gophish/gophish/issues/2430#issuecomment-1088470495)

**Comment by BlindChowder** [comment]
I do see the output in the console for any email that is sent to our reporting email.  It shows all emails sent (even GoPhish phishing emails) as not GoPhish emails.  We're using Outlook and sending the phishing emails to our IMAP account as an attachment inside another Outlook email.  I believe this creates the email attachment as a .msg format.  I saw in a sperate post where you said the attachments had to be in .eml format. Does GoPhish work with Outlook in a Windows environment as far as this issue may be concerned?

**Comment by glennzw** [comment]
@BlindChowder Very strange. Could you paste the console output you see when gophish checks those emails.

The .msg email you sent me worked fine when I checked it. Could you do me a favour and forward the email exactly as you do to your Outlook to my dummy account that I have IMAP running against:  safety.check.9001@gmail.com

**Comment by glennzw** [comment]
(also if you could let me know once you've sent it so I can go test it with that mailbox)

**Comment by BlindChowder** [comment]
time="2022-04-15T09:24:34-05:00" level=info msg="User 'User <User@domain.com>' reported email with subject 'Suspicious Email'. This is not a GoPhish campaign; you should investigate it."

This is what I'm getting when I send the email to my IMAP account as an attachment.  GoPhish is seeing the email, it just can't read the rid number.

I've sent you the email to the safety check address you mentioned before.

**Comment by glennzw** [comment]
Very odd, it works fine for me. Here's the result of the email you forwarded to that address:

```
time="2022-04-15T15:52:32+01:00" level=info msg="User 'xx xx <xx@xxx.com>' reported email with rid wi75Ngm"
time="2022-04-15T15:52:32+01:00" level=error msg="Error reporting GoPhish email with rid wi75Ngm: record not found"
```

I wonder if it's an Outlook thing. I do have an Outlook dummy account somewhere, I'll try test with that. Also, you could try test with a GMail account just so we can try figure out if it's a provider problem or a gophish problem.

**Comment by glennzw** [comment]
Hi @BlindChowder - I just tested this with Outlook.com and it works for me there too:

```
time="2022-04-27T13:21:00+01:00" level=info msg="User 'x x <x.check.x@gmail.com>' reported email with rid wi75Ngm"
time="2022-04-27T13:21:00+01:00" level=error msg="Error reporting GoPhish email with rid wi75Ngm: record not found"
```

**Comment by jmccarthy6** [comment]
Need a solution for this. I'm in the same boat. It doesn't detect the report. Did anyone figure this out?

**Comment by jmccarthy6** [comment]
@glennzw I wonder if there are some settings in outlook that has it working for you. It doesn't work for me but if I change to a gmail address it does show it as reported. @BlindChowder Did you find out anything on your side?

**Comment by glennzw** [comment]
Closing out as haven't heard back; feel free to reopen.

**Comment by TheGuardianLight** [comment]
I have the same problem.
