### ISSUE TITLE
Unable to send email

### ISSUE THREAD

**Issue by belgianik** [gophish/gophish#2435]
What version of Gophish are you using?: v0.11.0

Brief description of the issue: unable to send email or testing emails.

What are you expecting to see happen? : send mails. 
------

Hi everyone!
Looking for some help here.
I just configured GoPhish and use the latest stable version (aka v.0.11.0).
Everything works fine except when I try to send emails...

I created sending profile.
All settings are correct and SMTP server is reachable. 

However, when I try to send test email I got the following error:
"501 Invalid command or cannot parse from address"

Here are the few lines of logs:
time="2022-03-30T18:36:11+02:00" level=warning msg="501 Invalid command or cannot parse from address" code=501 email=xxxxxxx@hotmail.com
time="2022-03-30T18:36:11+02:00" level=error msg="501 Invalid command or cannot parse from address"
time="2022-03-30T18:36:11+02:00" level=info msg="IP - - [30/Mar/2022:18:36:11 +0200] \"POST /api/util/send_test_email HTTP/2.0\" 500 103 \"https://IP:3333/sending_profiles\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X XX; rv:98.0) Gecko/20100101 Firefox/98.0\""

Am I missing something? 

Thanks for your help!

**Comment by glennzw** [comment]
The error is coming from your SMTP server, and it is:

`501 Invalid command or cannot parse from address`

This means the SMTP server is rejecting the From address you specified in your sending profile. What is the sending address you supplied?

**Comment by belgianik** [comment]
Indeed, thanks for your help!
I defined in the SMTP From field: Mister X <misterx@mydomain.local>
By removing "Mister X" it seems that SMTP servers understand the communication!

**Comment by y0d4a** [comment]
hi, i am unable to add host with online tld?

**Comment by y0d4a** [comment]
nvm, i manual change in database:
```
UPDATE smtp
SET from_address = REPLACE(from_address, 'domain.tld', 'newdomain.tld')
WHERE id = 1;
```
