### ISSUE TITLE
Tracking attachments not working

### ISSUE THREAD

**Issue by CyberM070** [gophish/gophish#2437]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: latest build form source

Brief description of the issue: the provided templates for tracking attachments do not appear as 'e-mail opened' in the dashboard, but the template variables are working properly.

What are you expecting to see happen? : opening the templates results in 'email opened' in the dashboard

What are you seeing happen? nothing :).

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below: the templates from the Gophish user guide

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 - 
 
 Reproducing the creation of templates does not make a difference.

**Comment by glennzw** [comment]
Hi @CyberM070, thanks for reaching out. Are you using the exact template from the documentation, or have you made any changes? It *might* be a problem with Office blocking remote images, depending on your setup.

Either way if you could share one of the documents here so I can double check on my side.

**Comment by CyberM070** [comment]
Hi @glennzw, I used the provided Office templates without editing them. I also reproduced the steps to create my own documents, but I had the same results eacht time. https://github.com/gophish/user-guide/blob/master/documentation/example-attachments/gophish_word.docx this is the document I used. The HTML file does work, so it seems that Office is the issue?

**Comment by glennzw** [comment]
Hmm thanks for the info. Which version of Office are you using, and what O/S? I'll try reproduce on my side.

**Comment by glennzw** [comment]
Also, could you create a new blank document and try insert a remote image, and see if that loads?

It could also be a security issue - Office blocking remote images because the Word file was downloaded from an untrusted source.

**Comment by CyberM070** [comment]
Loading a random image from the internet is also not working, so I guess you are right about the blocking part.

**Comment by glennzw** [comment]
I just tested on the same OSX version of Offie as you, and it worked for me:

<img width="1432" alt="Screenshot 2022-04-01 at 14 24 05" src="https://user-images.githubusercontent.com/3966613/161272570-6545ebf6-30d7-4342-a362-5c9006a933a2.png">

So yeah it's possible your Word is configured to block remote content. Maybe following the opposite of these instructions will help:

https://answers.microsoft.com/en-us/msoffice/forum/all/how-to-block-online-image-in-word-document/eb4a6816-3819-4c86-ba12-8eb0dab41dab

**Comment by glennzw** [comment]
Closing out as haven't heard back, feel free to re-open.

**Comment by kavanaas** [comment]
Hello Glennzw, I am also conducting phishing attack inside our organization. I also have the same issue of attachment. It would be really greatfull if you help me out please?

**Comment by kavanaas** [comment]
Hello @glennzw, I am also conducting phishing attack inside our organization. I also have the same issue of attachment. It would be really greatfull if you help me out please?

**Comment by sliferboy** [comment]
Hello for anyone having this problem with {{.TrackingURL}}, the main reason it is because of the domain certificat  you need to verify domain certificat for your gopish listener cause microsoft blocks suspicious domains and to test it you just go Quickparts -> field -> includetext --> and then put your domain URL and click ok , a box will pop up if your certificat is not valid

**Comment by glennzw** [comment]
Great tip thanks @sliferboy
