### ISSUE TITLE
gophish service paused and will not start Windows 10 pro

### ISSUE THREAD

**Issue by tdn001** [gophish/gophish#2438]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  

v0.11.0 windows 64

Brief description of the issue: 

Hello installed the gophish on a winodws 10 pro 64 bit
installed nssm 2.24
gophish service in a paused state will not start and run
https://localhost:3333 errors out

What are you expecting to see happen? :

access the program to start my email testing

What are you seeing happen?

will not connect to url or services wont run

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - removed and re installed nssm and gophish 
 * 
 * Step 2 - checked boot order,

**Comment by glennzw** [comment]
Hi @tdn001, does it run correctly when not run as a service? Are you able to see the gophish logs from the service running?
