### ISSUE TITLE
SMTP using TLS error "504 5.7.4 Unrecognized authentication type"

### ISSUE THREAD

**Issue by lockandski** [gophish/gophish#244]
When I try to setup a mail server that is using Office 365 hosted exchange (SMTP/TLS on default port 587), I get the following error:

> 504 5.7.4 Unrecognized authentication type

The server I am trying to connect to is: smtp.office365.com:587

**Comment by jordan-wright** [comment]
Can you show me a screenshot of the Sending Profile you are using? You can redact the username (just making sure you are authing! I doubt it will work without an account).

**Comment by lockandski** [comment]
Hey Jordan, please see attached- thanks
[image: Inline image 1]

**Comment by jordan-wright** [comment]
This looks similar to the [same issue](https://github.com/go-gomail/gomail/issues/16) the gomail library encountered a while back.

I'll see if I can get this implemented in https://github.com/jordan-wright/email ASAP.

**Comment by lockandski** [comment]
Perfect, thanks Jordan

**Comment by MindNinja** [comment]
Has this been fixed... I have tried gmail, office365, att smtp, and several others and have been completely unsuccessful with any smtp email outbound activity.

In the gmail case I get the attached email from gmail:

<img width="556" alt="screen shot 2016-05-17 at 9 43 49 am" src="https://cloud.githubusercontent.com/assets/8138291/15324270/cc6b92be-1c13-11e6-9d8c-2d2a1febf08c.png">

For a lot of the others I get the EOF (nothing else in the logs) response. Having a hard time using gophish with these issues.

**Comment by jordan-wright** [comment]
Just checking in on this - Happy to report that I'm finalizing some changes that should get this resolved.

I should be able to get something pushed out by tomorrow or the next day.

**Comment by jordan-wright** [comment]
This should be fixed as of https://github.com/gophish/gophish/commit/a8aac75f99612eb42be2c94700b55bad8fcee50a. If you could please verify by building from source (**you will need to ```go get -u``` to get the new email package**), I would appreciated it!

**Comment by jordan-wright** [comment]
Going ahead and closing this for now. Let me know if upgrading the version from source doesn't fix the issue and we can take another look.

Thanks for reporting this!

**Comment by lockandski** [comment]
I can confirm I can authenticate and send email with Office 365, using TLS to smtp.office365.com:587

Thanks!

**Comment by jordan-wright** [comment]
Excellent - thanks for the follow-up, @lockandski!

**Comment by mmonroe86** [comment]
Which auth type should be user here. I am using SendWithTLS and passing in plainAuth struct and tls.Config with InsecureSkipVerify set to true as I am testing this locally? This setup is not working

**Comment by MonicaIrvine** [comment]
Did you get this figured out?  I am trying to validate my office365 account on click funnels and getting the same code :504 5.7.4 Unrecognized authentication type.  Do you mind me asking what you did to fix?
