### ISSUE TITLE
not show the email and link open

### ISSUE THREAD

**Issue by SarahCary** [gophish/gophish#2440]
Thanks for reaching out! We're happy to help resolve issues as quickly as possible.

Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.
What version of Gophish are you using?: 0.11.0

Brief description of the issue: when I send the phishing email when I open the email or click on the link in the email to redirect me to a form. It sends me directly to the Gophish dashboard there is no unique rid that is generated.

![image](https://user-images.githubusercontent.com/63299560/161731325-fdb07e0b-9f3d-4cbd-a4f1-257d9a2a82da.png)

What are you expecting to see happen? : I want that when I open the email, it is marked in the person's information for the campaign and same when I click on link. And when I click on the link it should go to the simple form that I put.

Campaign:
![image](https://user-images.githubusercontent.com/63299560/161728403-d5214022-d34d-46ae-8282-a8697251fb12.png)

Email Templates
![image](https://user-images.githubusercontent.com/63299560/161731613-557a1d21-d294-4e45-ac4b-717b34ddf029.png)

![image](https://user-images.githubusercontent.com/63299560/161731748-f7a519df-694f-4dfd-8084-54baabf2d094.png)

Landing Pages

![image](https://user-images.githubusercontent.com/63299560/161731895-262188d3-c675-41c5-b515-ba65bb8ca573.png)

can you help me on what is not working?
Thanks

**Comment by glennzw** [comment]
Hi @SarahCary, thanks for reaching out. You need to specify the URL in your campaign on port 80, ie for your case it would be `http://192.168.1.112`. If that doesn't work please share your `config.json` too.

**Comment by SarahCary** [comment]
in fact on the ip address 192.168.1.112 I have a mail server and 192.168.1.112:3333 is the gophish server

**Comment by glennzw** [comment]
The gophish admin server and campaign server run on different ports. In your `config.json` this is specified. If you haven't edited it then it's running on port 80 and that's what you want to supply in the URL parameter of the campaign URL.

**Comment by glennzw** [comment]
You've defined your phish_server listen_url as `"0.0.0.0:8080"`, so you need to set your URL in your Campaign as `http://192.168.1.112:8080`

**Comment by SarahCary** [comment]
That's what I did but it doesn't work, it always sends me back to the Dashboard page
![image](https://user-images.githubusercontent.com/63299560/162146485-12aee789-f995-4b2e-8edd-e57e74e59603.png)

**Comment by glennzw** [comment]
If you put the `http://` at the front you may have more success.

```http://192.168.1.112:8080```

**Comment by glennzw** [comment]
You entered an "s" after "http". You need to enter exactly this: `http://192.168.1.112:8080`

**Comment by SarahCary** [comment]
So I put http://192.168.1.112:8080 but it doesn't change anything and when I click on the link in the email it goes to https://192.168.1.112:3333

**Comment by glennzw** [comment]
If you just browse to `http://192.168.1.112:8080` (ignoring the email) what do you get?

Also, try browse to `http://127.0.0.1:8080`

**Comment by BlindChowder** [comment]
Not sure if this will help, but I had a similar problem where my email opened wasn't being tracked.  Setting the URL to the ip of the GoPhish server without the port fixed my problem.  So for you it'd be http://192.168.1.112.  I'm also using 127.0.0.1:3333 in my config.json file.

**Comment by glennzw** [comment]
@BlindChowder Sarah has her listener port set to 8080, so she needs to include it. If you leave off the port the browser/email client will assume port 80 and translate http://192.168.1.112/ to http://192.168.1.112:80/

**Comment by SarahCary** [comment]
it doesn't work I get this when I do http://192.168.1.112:8080/ in the browser
![image](https://user-images.githubusercontent.com/63299560/162703359-9b6efdc0-3b7c-4d9a-8371-0723c52b7baa.png)

**Comment by glennzw** [comment]
Sarah that 404 is exactly what you should see, that means you're hitting the phish listener.

Now in your campaign set the URL to http://192.168.1.112:8080/

**Comment by glennzw** [comment]
The link in the email needs to be `{{.URL}}`. When the campaign is sent this value is changed for each user to something like `http://192.168.1.112:8080/?rid=abc1234`

See: https://docs.getgophish.com/user-guide/template-reference

**Comment by SarahCary** [comment]
ok it works well thanks. Last question, I import a site with a form but when I enter data and do submit, I do not see submitted data

**Comment by glennzw** [comment]
I'd recommend starting with a very simple landing page:

```HTML
<html>
 <body>
  <form action="" method="post" name="form">
    <label>Username:</label> <input name="username" type="text"/><br/>
    <label>Password:</label> <input name="password" type="password"/><br/>
   <input id="login" name="login" type="submit" value="Login"/>
  </form>
  </body>
</html>
```

Understanding this, you can then edit imported sites appropriately. ie you need a form with a POST method and blank action.

**Comment by glennzw** [comment]
That's a bit beyond the scope of help we can offer here, as it's more of a web dev question. I'd recommend you try remove the "Next" button and replace it with something along the lines of 

```html
<input id="login" name="login" type="submit" value="Next"/>
```
