### ISSUE TITLE
Simplest form(s) not capturing credential parameter values supplied to the GoPhish application

### ISSUE THREAD

**Issue by glitchdigger** [gophish/gophish#2444]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

**What version of Gophish are you using?:** 
0.11.0
**Brief description of the issue:** 
Using the most basic form provided does not actually capture credentials. There is zero javascript here. Simply what was listed in https://github.com/gophish/gophish/issues/1705 by lead dev.

**What are you expecting to see happen? :**
I would expect to see credentials of user supplied values of the parameters captured in POST request sent to the GoPhish application

**What are you seeing happen?**
I only see a 'detection' of a form submission, but that is all.

**If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:**
```
<form action="" method="post" name="form">

<input name="username" placeholder="email@test.com" type="email"/>
<input name="password" placeholder="Password" type="password"/>

<button class="color-button" type="submit" value="Submit">Sign in</button>
</form>
```

```html
There is no HTML code other than what is mentioned above. 
```

**Please provide any terminal output that may be relevant below:**

```
None
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Just load up the basic form supplied and submit some values. 
 
### 
Thanks everyone for your help and contributions

**Comment by glennzw** [comment]
Hi @glitchdigger - thanks for reaching out and sorry to hear you're having trouble grabbing submitted data. Could you do me a favour and screenshot your landing page template. Just to double check you've enabled capturing of input:

<img width="563" alt="Screenshot 2022-04-15 at 15 08 53" src="https://user-images.githubusercontent.com/3966613/163580974-659660dd-2bd8-472a-94b2-fa2cddf5f698.png">

**Comment by Tempsathi** [comment]
Hi
I am trying to import linkedin page for my landing page... I can run the campaign and I can even go to the landing page and click the URLs , but once I entered the username and password I suppose to capture submitted data. Which I can't see.
I can only see up to email click event.

I understand it may not be simple as just providing a URL to phish but then what the point of having import site?

**Comment by gear0** [comment]
Hi @Tempsathi,
you have to make sure that the form you want to use to capture follows the structure as mentioned here https://docs.getgophish.com/user-guide/faq#submitted-form-data-isnt-being-captured. Also you need to make sure to enable "Capture Submitted Data" on your landing page configuration as pointed out by glennzw.

**Comment by glitchdigger** [comment]
Just a heads up to everyone here, I ended up modifying the form to properly include the "name" tag and it ended up working as intended. Thank you. I thought I had already included that tag when I made this post, but I had actually reloaded an older example of the form. Cheers to everyone and @glennzw @gear0  you've all done a great job with this project. Thank you for your hard work.

**Comment by glennzw** [comment]
Great news @glitchdigger, happy phishing! 🐟
