### ISSUE TITLE
Interactions from private IPv4 addresses

### ISSUE THREAD

**Issue by ChrisASE** [gophish/gophish#2445]
What version of Gophish are you using?:
0.11.0

Brief description of the issue:
Seeing interactions from private IPv4 addresses in the 10.0.0.0/8 range.

What are you expecting to see happen? :
Interactions are from publically routed IP addresses.

What are you seeing happen?
In several assessments with different external clients, every now and then (1 in ~500 emails sent) I'm seeing click and report interactions from IP addresses in the 10.0.0.0/8 range. This is a regular occurrence lately, but it is not a massive problem, however it is peculiar to see so many interactions from private space. Not exactly sure where the problem is, this issue log is more of a query as to whether others have come across this issue, potential resolves, advice etc.

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Send campaign
 * Step 2 - Export raw events
 * Step 3 - Check Clicked Link and Email Reported interactions
 * Step 4 - Observe interactions from 10.0.0.0/8 range.

**Comment by glennzw** [comment]
Hi @ChrisASE, that's quite odd behaviour. It could be similar to https://github.com/gophish/gophish/issues/2344, where the theory was that some reverse proxy or similar device was ferrying the requests inbound. You could check the gophish logs for the User-Agent which might help narrow down the source. Also I assume you've tried interacting with the 10.0.0.0/8 from the point-of-view of the gophish server to see what's at the other end? If you know the rid of the offender you can dig through the gophish database like so:

```sh
sqlite3 gophish.db "SELECT details FROM events where message='Clicked Link' AND details like '%shlgyL7%'LIMIT 2"| jq 
```

```json

{
  "payload": {
    "rid": [
      "shlgyL7"
    ]
  },
  "browser": {
    "address": "::1",
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit (KHTML, like Gecko) Chrome Safari"
  }
}
{
  "payload": {
    "rid": [
      "shlgyL7"
    ]
  },
  "browser": {
    "address": "127.0.0.1",
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit (KHTML, like Gecko) Chrome Safari"
  }
}
```

**Comment by ChrisASE** [comment]
Thanks for a speedy response @glennzw.

Connected to the Gophish server via SSH I've tried a traceroute to the 10.67.**.** IP and also run an nmap scan.
Neither reveal anything useful.

UA:
Mozilla/5.0 (Linux; Android 10; SAMSUNG SM-G965F) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/16.2 Chrome/92.0.4515.166 Mobile Safari/537.36

**Comment by glennzw** [comment]
Hi @ChrisASE. That looks a lot like a Samsung mobile phone clicking the link. If this is a corporate environment I'd guess that a staff member is connected to your corp WiFi which is on that internal range and clicked the link. I'd check who via the rID and go ask them?

**Comment by ChrisASE** [comment]
Hi @glennzw.

These are external clients based globally. We have clients with staff in the UK who are showing as having clicked from a 10.x.x.x IP, but we also have clients in India showing as having clicked from a 10.x.x.x IP.
No targets are connected to our business WiFi, they will be connected either to their own organisation's WiFi, their residential WiFi, or using their phone carrier's mobile data.

The only common trend seen in clicks from the 10/8 range is that they're all from mobile phones (Samsung & iPhones mainly).

I see interactions from this private range in assessments sent to several clients so it isn't localised to one company, and they are definitely not connected to our network. I'm just completely lost with this one :/

**Comment by glennzw** [comment]
Pretty strange indeed. My only thought is that there is some load balancer, reverse proxy, or other device on your 10.x range that is proxying the requests. I had this issue before in an older version of gophish (https://github.com/gophish/gophish/issues/1999).

Gophish is pretty dumb, if something hits its endpoint it'll log it. The two further debugging options I can suggest are:

 * Put a proxy in front of gophish so you can monitor and log every web request in detail (e.g. mitmproxy). In the headers you might get a clue as to the origin (e.g a header telling you it's a load balancer).
 * Do some further investigation into what is at the end of the 10.x.x.x IPs. If the user agent comes back as a mobile phone I'm guessing it's a proxy or load balancer preserving the original user agents. You could try a deeper nmap (e.g. sudo nmap -O -sS 1-65535) or speak to the network admin. If it's on the same local network as your gophish server you should be able to see its MAC address, which would also give you a clue as to what it is.

Feel free to drop nmap results here.

**Comment by glennzw** [comment]
The more I think about this, the more I think it's a similar issue to https://github.com/gophish/gophish/issues/1999. I suspect gophish might not be parsing the headers properly which include the originating IP address for what I suspect is some kind of reverse proxy. Basically we'll need more verbose logs, which might be a pain for you in a production environment, but if you know the 'culprits' you could get their help by asking them to click the link again. 

Then, how do we log more verbose web traffic... It will depend on your gophish setup for the landing pages. Something like:

```
mitmdump -p443 --certs full.pem --mode reverse:http://localhost:80 --flow-detail 2 >> logs.txt
```

Then in the logs.txt you'll get full HTTP logs and be able to see all the headers etc, e.g from my logs.txt:

```
Proxy server listening at http://*:443
[::1]:58991: clientconnect
[::1]:58991: Client Handshake failed. The client may not trust the proxy's certificate for localhost.
[::1]:58991: clientdisconnect
[::1]:58992: clientconnect
[::1]:58992: Client Handshake failed. The client may not trust the proxy's certificate for localhost.
[::1]:58992: clientdisconnect
[::1]:58993: clientconnect
[::1]:58993: GET http://localhost/?rid=a4kZJko
    Host: localhost
    Connection: keep-alive
    Cache-Control: max-age=0
    sec-ch-ua-mobile: ?0
    sec-ch-ua-platform: "macOS"
    Upgrade-Insecure-Requests: 1
    User-Agent: Mozilla/5.0
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
    Sec-Fetch-Site: none
    Sec-Fetch-Mode: navigate
    Sec-Fetch-User: ?1
    Sec-Fetch-Dest: document
    Accept-Encoding: gzip, deflate, br
    Accept-Language: en-US,en;q=0.9
 << 200 OK 11.38k
    Content-Encoding: gzip
    Content-Type: text/html; charset=utf-8
    Vary: Accept-Encoding
    X-Server: gophish
    Date: Wed, 27 Apr 2022 12:42:11 GMT
    Transfer-Encoding: chunked
```

Hopefully in there you'll see some header information giving us more clarity as to what is going on here.

HTH, it's a bit of a pain, but maybe you're running gophish behind nginx or something you could use that to get logs.

**Comment by glennzw** [comment]
Closing out as haven't heard back, feel free to re-open.
