### ISSUE TITLE
False positives 

### ISSUE THREAD

**Issue by not-hal-finney** [gophish/gophish#2446]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  0.11.0 

Brief description of the issue: When sending to office 365 environments, the emails seems be getting scanned and false clicks are being done before the users received the emails. 

What are you expecting to see happen? : Delivery but no click before the user receives it and opens it themselves 

What are you seeing happen? Windows 10 with seemingly random chrome browsers clicking the links before the email is even delivered into the users mailbox

Always windows 10 with these 3 versions of "chrome"  Chrome (Version: 80.0.3987.132),  Chrome (Version: 96.0.4664.110) and  Chrome (Version: 79.0.3945.136)

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - New campaign, email sent to myself. link is clicked before the email is received by me. 
 * Step 2 - Tested to non office email in same campaign and issue does not happen. 

Some output from tests:

Timeline for User 1
Email: test@example.com
Result ID: TfELCdT
Campaign Created April 21st 2022 2:50:01 pm
Email Sent April 21st 2022 2:50:03 pm
Clicked Link April 21st 2022 2:50:22 pm
Windows (OS Version: 10) - not me 
Chrome (Version: 79.0.3945.136)
Clicked Link April 21st 2022 2:55:06 pm
Windows (OS Version: 10) - not me 
Chrome (Version: 80.0.3987.132)

Timeline forUser 2 
Email: test2@example.com
Result ID: SwdwetS
Campaign Created April 21st 2022 2:34:09 pm
Email Sent April 21st 2022 2:34:11 pm
Clicked Link April 21st 2022 2:35:43 pm
Linux (OS Version: x86_64) - Legit click by me*
Firefox (Version: 91.0)
Clicked Link April 21st 2022 2:35:58 pm
Windows (OS Version: 10) - not me 
Chrome (Version: 79.0.3945.130)
Clicked Link April 21st 2022 2:43:35 pm
Windows (OS Version: 10) - not me 
Chrome (Version: 80.0.3987.132)
 
Timeline for User 3  (non office 365)
Email: user3@example.com
Result ID: V3uqyoJ
Campaign Created April 21st 2022 2:50:01 pm
Email Sent April 21st 2022 2:50:04 pm - Not auto clicks or opens.

**Comment by not-hal-finney** [comment]
Apologies this can be closed using this https://github.com/gophish/gophish/issues/2115 

"
    Create a new mail flow rule in your Exchange/Office Admin center.
    Give the rule a name such as "Bypass ATP Links".
    Click More options....
    From the Apply this rule if…. drop-down menu, select The senders then select IP address is in any of these ranges or exactly matches.
    Enter gophish SMTP server IP
    From the Do the following… drop-down menu, select Modify the message properties... and then set a message header.
        Click the first *Enter text... link and set the message header to: X-MS-Exchange-Organization-SkipSafeLinksProcessing
        Click the second *Enter text... link and set the value to: 1
    Click Save.
"

**Comment by glennzw** [comment]
Great I'm glad that worked for you!
