### ISSUE TITLE
I am having issues running gophish

### ISSUE THREAD

**Issue by Maroaluka** [gophish/gophish#2447]
I am having issues running gophish 
Please can someone help

_Originally posted by @Maroaluka in https://github.com/gophish/gophish/issues/2400#issuecomment-1106221566_

**Comment by glennzw** [comment]
Hi @Maroaluka - please could you give us some more info. Have you followed the documentation? https://docs.getgophish.com/user-guide/

**Comment by glennzw** [comment]
Closing out as haven't heard back.
