### ISSUE TITLE
Can't run.

### ISSUE THREAD

**Issue by 0x1401** [gophish/gophish#245]
Chmod 777. changed port in config

`[root@DS843302 gophish_linux_64bit]# sudo ./gophish
goose: no migrations to run. current version: 20160227180335
 2016/04/18 20:07:23 gophish.go:71: Starting phishing server at http://0.0.0.0:80
 2016/04/18 20:07:23 worker.go:38: Background Worker Started Successfully - Waiting for Campaigns
 2016/04/18 20:07:23 gophish.go:59: Starting admin server at http://127.0.0.1:1488
`

Can't run...

Clear Centos 7

**Comment by jordan-wright** [comment]
Hey there! What error are you getting? The startup logs look ok.

**Comment by 0x1401** [comment]
No any error:( 
I only see 
`[root@DS843302 gophish_linux_64bit]# sudo ./gophish goose: no migrations to run. current version: 20160227180335 
2016/04/18 20:07:23 gophish.go:71: Starting phishing server at http://0.0.0.0:80 
2016/04/18 20:07:23 worker.go:38: Background Worker Started Successfully - Waiting for Campaigns 
2016/04/18 20:07:23 gophish.go:59: Starting admin server at http://127.0.0.1:1488 `

And panel not work. I have no messege what it start.
I need apache? or can start on clear centos 7?

**Comment by jordan-wright** [comment]
What do you see in both your browser and the terminal when you go to http://127.0.0.1:1488?

**Comment by 0x1401** [comment]
as i wrote when i use wget it get:
 wget http://127.0.0.1:1488 --2016-04-19 07:44:48-- http://127.0.0.1:1488/ Connecting to 127.0.0.1:1488... failed: Connection refused.

**Comment by jordan-wright** [comment]
Sorry - the original email didn't have the wget update. When gophish is running, what do you see when you type "netstat -tulpn"?

Also, do you have any local firewall configs that might be causing the issue? Iptables and the like?

**Comment by 0x1401** [comment]
`root@DS843302:/usr/gophish_linux_64bit#` ./gophish
 2016/04/19 15:52:44 worker.go:38: Background Worker Started Successfully - Waiting for Campaigns
goose: no migrations to run. current version: 20160227180335
 2016/04/19 15:52:44 gophish.go:71: Starting phishing server at http://0.0.0.0:80
 2016/04/19 15:52:44 gophish.go:59: Starting admin server at http://127.0.0.1:3333
^Croot@DS843302:/usr/gophish_linux_64bit# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1884/sshd
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      1125/master
tcp        0      0 0.0.0.0:222             0.0.0.0:*               LISTEN      1884/sshd
tcp6       0      0 :::22                   :::*                    LISTEN      1884/sshd
tcp6       0      0 :::25                   :::*                    LISTEN      1125/master
tcp6       0      0 :::222                  :::*                    LISTEN      `1884/sshd`

New clear ubuntu server now)) 


Than as u say i trying to turn off firewall: 
`
root@DS843302:/usr/gophish_linux_64bit# sudo ufw disable
Firewall stopped and disabled on system startup
root@DS843302:/usr/gophish_linux_64bit# ./gophish
 2016/04/19 15:56:30 worker.go:38: Background Worker Started Successfully - Waiting for Campaigns
goose: no migrations to run. current version: 20160227180335
 2016/04/19 15:56:30 gophish.go:71: Starting phishing server at http://0.0.0.0:80
 2016/04/19 15:56:30 gophish.go:59: Starting admin server at http://127.0.0.1:3333

---

root@DS843302:/usr/gophish_linux_64bit# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1884/sshd
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      1125/master
tcp        0      0 0.0.0.0:222             0.0.0.0:*               LISTEN      1884/sshd
tcp6       0      0 :::22                   :::*                    LISTEN      1884/sshd
tcp6       0      0 :::25                   :::*                    LISTEN      1125/master
tcp6       0      0 :::222                  :::*                    LISTEN      1884/sshd
root@DS843302:/usr/gophish_linux_64bit#

`
No changes(

**Comment by 0x1401** [comment]
UPDATE: 
sorry i was cancel...
i run and see ports:
```


Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:3333          0.0.0.0:*               LISTEN      8600/gophish
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1884/sshd
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      1125/master
tcp        0      0 0.0.0.0:222             0.0.0.0:*               LISTEN      1884/sshd
tcp6       0      0 :::80                   :::*                    LISTEN      8600/gophish
tcp6       0      0 :::22                   :::*                    LISTEN      1884/sshd
tcp6       0      0 :::25                   :::*                    LISTEN      1125/master
tcp6       0      0 :::222                  :::*                    LISTEN      1884/sshd
```
3333 i have.

**Comment by 0x1401** [comment]
I am idiot.... Thank you for help man!
