### ISSUE TITLE
How to get rid ID of landing page

### ISSUE THREAD

**Issue by rexeor** [gophish/gophish#2450]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.11.0

Brief description of the issue: I am trying to create a phishing campaign on localhost with Kali Linux. I have created a landing page but I don't know how to get the "rid" ID that corresponds to my landing page. I know that the "rid" ID is a unique identifier for each landing page but I don't know where or how I can check this ID.

What are you expecting to see happen? : I need to get the "rid" ID of my landing page to insert the link of the landing page in my "email template"

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by gear0** [comment]
Hi @rexeor,

please have a look at https://docs.getgophish.com/user-guide/template-reference. If I understand you correctly than you have to include the variable {{.URL}} to get the whole tracking URL and {{.RId}} to just get the RID.

**Comment by rexeor** [comment]
> Hi @rexeor,
> 
> please have a look at https://docs.getgophish.com/user-guide/template-reference. If I understand you correctly than you have to include the variable {{.URL}} to get the whole tracking URL and {{.RId}} to just get the RID.

Hello @gear0, 

I got it. Thank you very much for the help.
