### ISSUE TITLE
gophish does not send to domain emails

### ISSUE THREAD

**Issue by Keynotey** [gophish/gophish#2454]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: Current Version: 0.10.1

Brief description of the issue: 
I am trying to send emails to domain emails for example abc@coolkid.com but its not going through however if I try to send to a gmail address for example xyz@gmailcom it works and the email gets delivered.

What are you expecting to see happen? :
I am expecting the emails to get delivered for the domain account just as it was delivered for the gmail ones

What are you seeing happen?
I am getting the following errror
Error 550 5.1.1 The email account that you tried to reach does not exist. Please try 5.1.1 double-checking the recipient's email address for typos or 5.1.1 unnecessary spaces. Learn more at 5.1.1 https://support.google.com/mail/?p=NoSuchUser b6-20020a056402350600b00425d8c9efd2si1462007edd.152 - gsmtp

Thank you in advance

**Comment by mk12-dhensel** [comment]
The error message is telling you exactly what is wrong. 

> [550 5.1.1 means that the recipient email server considers that the email address doesn't exist at the destination domain, and therefore has no way to deliver it. Unless you made an error typing out in the email address, this is not something for you to correct and needs to be corrected on the receiving end](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiXmaK2iMn3AhUKADQIHcQWAUEQFnoECAsQAw&url=https%3A%2F%2Fsupport.google.com%2Fmail%2Fthread%2F8013209%2Ferror-550-5-1-1-recipient-address-rejected-user-unknown-is-being-shown%3Fhl%3Den%23%3A~%3Atext%3DReport%2520abuse-%2C550%25205.1.%2Ccorrected%2520on%2520the%2520receiving%2520end.&usg=AOvVaw25POp7ErJvfjOyrAEtsGyd)

**Comment by glennzw** [comment]
Closing out as @mk12-dhensel's answer is spot on.
