### ISSUE TITLE
Cannot reach phishing server at port 443 with tls enabled

### ISSUE THREAD

**Issue by mk12-dhensel** [gophish/gophish#2455]
What version of Gophish are you using?: 
20201201000000

Brief description of the issue: 
I am unable to access the phishing server via public IP or domain name with TLS enabled on port 443 and get a ERR_CONNECTION_RESET. I am able to access the admin panel with TLS via domain name without any issues.

What are you expecting to see happen? :
I expect to be able to access the phishing server for an active campaign over an encrypted connection on port 443 when it is accessed via domain name (e.g https://mydomain.com/?rid=xxxxxxxx).

What are you seeing happen?
I am starting up gophish via Docker, seeing in the docker gophish logs that gophish is running the phishing server on 0.0.0.0:443, but when navigating to the page via it's public IP as well as domain name, I get an ERR_CONNECTION_RESET error and am unable to access the phishing landing page for any campaign(s) I've tried to host. 
I have ensured that my campaign phishing server URL is assigned to the proper URL with https (https://mydomain.com and https://my.ip.here) with no resolution of the problem.

Here are the docker logs output for the application immediately after startup:
```
Runtime configuration:
{
        "admin_server": {
                "listen_url": "0.0.0.0:3333",
                "use_tls": true,
                "cert_path": "gophish_admin.crt",
                "key_path": "gophish_admin.key"
        },
        "phish_server": {
                "listen_url": "0.0.0.0:443",
                "use_tls": true,
                "cert_path": "gophish_admin.crt",
                "key_path": "gophish_admin.key"
        },
        "db_name": "sqlite3",
        "db_path": "gophish.db",
        "migrations_prefix": "db/db_",
        "contact_address": "",
        "logging": {
                "filename": "",
                "level": ""
        }
}

time="2022-05-05T17:18:23Z" level=warning msg="No contact address has been configured."
time="2022-05-05T17:18:23Z" level=warning msg="Please consider adding a contact_address entry in your config.json"
goose: no migrations to run. current version: 20201201000000
time="2022-05-05T17:18:23Z" level=info msg="Starting admin server at https://0.0.0.0:3333"
time="2022-05-05T17:18:23Z" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
time="2022-05-05T17:18:23Z" level=info msg="Starting IMAP monitor manager"
time="2022-05-05T17:18:23Z" level=info msg="Starting new IMAP monitor for user admin"
time="2022-05-05T17:18:23Z" level=info msg="Starting phishing server at https://0.0.0.0:443"

```

I am running gophish on Ubuntu 20.04 (LTS) x64 in a DigitialOcean droplet. I installed and run gophish via Docker using the gophish/gophish image.

Running the docker container via sudo does not resolve or change the issue. **Switching the phishing server port to listen on port 80 and setting use_tls to false allows me to access the phishing server.**

I have looked at other issues filed in this repo where others seem to have a similar problem, but none of the solutions listed in them have resolved my issue. I have tried restarting my droplet instance multiple times. I do not have ufw enabled or any DigitalOcean firewalls set up for this server.

Thank you all for your hard work you put into gophish. It has helped me immensely and is a great tool.

**Comment by glennzw** [comment]
Hi @mk12-dhensel, thanks for reaching out and sorry to hear you're having trouble with gophish. Could you please share the output when trying to reach the page with curl?

`curl --verbose --insecure https://mydomain.com/?rid=xxxxxxxx`

and

`curl --verbose --insecure https://1.2.3.4/?rid=xxxxxxxx`

This might help us with some extra debugging info.

**Comment by mk12-dhensel** [comment]
Here's the outputs  (Note that I have modified my domain and ip info in the output, but used the real ones for the actual curl requests)

```
$ curl --verbose --insecure https://subdomain.mydomain.com/?rid=tYFi63E
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 150.231.196.87:443...
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0* connect to 150.231.196.87 port 443 failed: Connection refused
* Failed to connect to subdomain.mydomain.com port 443: Connection refused
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
* Closing connection 0
curl: (7) Failed to connect to subdomain.mydomain.com  port 443: Connection refused
```

```
$ curl --verbose --insecure https://150.231.196.87/?rid=tYFi63E
*   Trying 150.231.196.87:443...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0* connect to 150.231.196.87 port 443 failed: Connection refused
* Failed to connect to 150.231.196.87 port 443: Connection refused
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
* Closing connection 0
curl: (7) Failed to connect to 150.231.196.87 port 443: Connection refused
```

**Comment by gear0** [comment]
Hi @mk12-dhensel,
looks like your server isn't listening. Can you confirm that your server is actually listening on port 443?

You can do this with `ss -tpln` for example.

Furthermore, can you confirm that there is no firewall running on your server or in front of it that might block incoming requests?

Kind regards,
gear0

**Comment by glennzw** [comment]
@gear0 is spot on here - it looks like either 443 isn't listening or it's being denied by something (e.g. a firewall). Two other tests:

From a remote box (e.g your laptop):

`nc -z -v 1.2.3.4 443`

from the server:

`nc -z -v localhost 443`

Also from the server:
`netstat -pant | grep LISTEN`

**Comment by mk12-dhensel** [comment]
I was hoping this wasn't a me problem, but it was a silly mistake. 

I'm not familiar with using docker without docker-compose, and this was my first time creating a container via cli and not a compose file. 

The problem that caused this was me forgetting to map the gophish internal 443 port to the hosts 443 port during creation of the container (e.g docker run -d --name gophish **-p 443:443** -p8080:8080 -p 80:80 -p 3333:3333)

Removing the container and mapping the port explicitly allowed me to access the phishing server.

Thank you for giving me a new angle to look at the problem and helping me solve it :). I hope I can give back to the project in the future in some way.

**Comment by glennzw** [comment]
Great I'm glad you managed to get it working! The best thing about 'silly' mistakes is we learn tips and tricks for the next sticky situation.

Happy phishing!
