### ISSUE TITLE
Deceptive site ahead! What to do?

### ISSUE THREAD

**Issue by rzmpzgeviii** [gophish/gophish#2458]
![warning](https://user-images.githubusercontent.com/101715188/167470623-bc34bca9-9c71-4aa2-a03f-8ee23122d015.png)

I just added the ssl certificate and launched a test campaign with myself as a target  and immediately got restricted
I haven´t sent out any email except to my self but "google safe" already blocked my entire domain?!
Even without clicking on the link, just by  opening  the mail the entire site turns red with the warning? 

Any ideas what exactly triggers that event? I guess my domain contains restricted keywords. 
Thats pretty unfortunate  because a good phishing training should be as similar as possible to the original one.

Unfortunately there is less known about blacklisted words. 

Imma just change the vps IP and try out another domain.

**Comment by glennzw** [comment]
Hi @rzmpzgeviii - bad luck on getting onto the naughty list. If your test campaign was imitating a real world service (GMail, LinkedIn, etc) and you sent it to a GMail account the automatic systems could have picked it up. Quite strange for it to happen so fast though.

You could try adding firewall rules on your campaign server to limit access to your target org, or try blacklisting Google IPs.

HTH

**Comment by rzmpzgeviii** [comment]
@glennzw thanks mate, 
yeah i´ve done research and testing to figure out there are a bunch of restricted words. And that counts for Domains & Emails.

- Company names 
- Obviously illicit stuff such as "drugs" "rap4ping" etc.
And to my surprise even words like
- verification (in every language not just english)

Although i.e. https://paypal-login-741947.com is theoretically available and can be registered, (which most registrars will already block)  
google itself has "paypal" blacklisted and will 100% put a warning in front.

And good to know: as soon as ur vps gets blacklisted once, assigned ips that you add will be partly blacklisted right away as well. 

Fortunately, I already found a pretty good workaround which would make for example https://paypal-login-741947.com  work with full access, ssl,  no warning, no blacklist. But gotta keep my secret secret. 🙏🤫

**Comment by simodangio01** [comment]
Have same problem here... I need your help!
Please text me: simodangio01@gmail.com
