### ISSUE TITLE
Email tracker status issue

### ISSUE THREAD

**Issue by welts** [gophish/gophish#246]
Hi!

Never ending respect and thanks for such an awsome solution!

There may be an issue with email tracker status:

Use case 1: landing page URL is entered like http://www.example.com (phishing URL is displayed http://example.com/?rid=[random_string]) and phishing mail is opened (but no click on phish link has been done), email tracker status on Campain's timeline page is displayed correctly “Email Opened”.

Use case 2: landing page URL is entered like http://www.example.com/subdir (phishing URL is displayed http://example.com/subdir?rid=[random_string]) and phishing mail is opened (but no click on phish link has been done), email tracker status on Campain's timeline page is displayed uncorrectly “Clicked Link”.

Can you reproduce and confirm this bug?

Keep up the good work!

**Comment by jordan-wright** [comment]
This appears to be an issue with how the phishing router is created.

Here's the function:

``` go
// CreatePhishingRouter creates the router that handles phishing connections.
func CreatePhishingRouter() http.Handler {
	router := mux.NewRouter()
	router.PathPrefix("/static/").Handler(http.StripPrefix("/static/", http.FileServer(http.Dir("./static/endpoint/"))))
	router.HandleFunc("/track", PhishTracker)
	router.HandleFunc("/{path:.*}", PhishHandler)
	return router
}
```

You'll notice that the tracker is looking for the prefix ```/track```. I'll see if I can change this to be ```/anything/else/track``` instead.

**Comment by zyxtarmo** [comment]
Created quick fix that worked for us:

---

diff --git a/worker/worker.go b/worker/worker.go
index 981740d..4400729 100644
--- a/worker/worker.go
+++ b/worker/worker.go
@@ -12,6 +12,7 @@ import (
        "os"
        "strings"
        "text/template"
+       "regexp"
 
        "github.com/gophish/gophish/models"
        "github.com/jordan-wright/email"
@@ -68,6 +69,10 @@ func processCampaign(c *models.Campaign) {
                ft = f.Address
        }
        for _, t := range c.Results {
+               
+               y, _ := regexp.Compile("^(?:http://|www.|https://)([^/]+)")
+               tURL := y.FindString(c.URL)
+
                td := struct {
                        models.Result
                        URL         string
@@ -78,7 +83,8 @@ func processCampaign(c *models.Campaign) {
                        t,
                        c.URL + "?rid=" + t.RId,
                        c.URL + "/track?rid=" + t.RId,
-                       "<img style='display: none' src='" + c.URL + "/track?rid=" + t.RId + "'/>",
+                       // "<img style='display: none' src='" + c.URL + "/track?rid=" + t.RId + "'/>",
+                       "<img style='display: none' src='" + tURL + "/track?rid=" + t.RId + "'/>",
                        ft,
                }
                // Parse the templates

**Comment by zyxtarmo** [comment]
Quick fix, that worked for us
[fix_tracker.diff.txt](https://github.com/gophish/gophish/files/227963/fix_tracker.diff.txt)

, is attached.

**Comment by welts** [comment]
I confirm, it works!

Thank you zyxtarmo!

**Comment by jordan-wright** [comment]
I'm going to go ahead and close this since there is a workaround, however I'll be adding in a permanent fix into the codebase soon.

Thanks @zyxtarmo!

**Comment by bartenge** [comment]
> Quick fix, that worked for us
> [fix_tracker.diff.txt](https://github.com/gophish/gophish/files/227963/fix_tracker.diff.txt)
> 
> , is attached.

hello having the same problem i am unable to track opened mails and clicked links, where ama i suppose to edit with attached file?
