### ISSUE TITLE
Post custom Html file to http://<IP>/xxx.html and not to http://<IP>/static/xxx.html (Marked by Google: phishing and deceptive site) 

### ISSUE THREAD

**Issue by Desiqvel** [gophish/gophish#2461]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
v1.10
Brief description of the issue: 
Have been flagged by Google, and to verify I'm the owner, I have to upload a .html file to the main page (Google didn't allow to put the file in /static/endpoint/ , it has to be directly from the main page http://<IP>/xxx.html). 

What are you expecting to see happen? :
I was hoping to upload a .html file that's accessible from the main page

What are you seeing happen?
Been searching in docs/google/folders but cant find where to place the .html file so its accessible for Google Search Console

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Post a campaign with email and landing site
 * Step 2 - Panic when the landing site has a big red screen

**Comment by glennzw** [comment]
Hi @Desiqvel - hmm tricky question. I don't think you'd be able to add a page to the root directory without modifying the code. I think the simplest solution would be to stop gophish and spin up a temporary webserver. The easiest solution would be with python:

```bash
mkdir foo
cd foo
echo "blahblah" > index.xxx.html
sudo python -m SimpleHTTPServer 80
```

That would start a webserver, serving up content from the foo directory (including your xxx.html for Google).

**Comment by Desiqvel** [comment]
> Hi @Desiqvel - hmm tricky question. I don't think you'd be able to add a page to the root directory without modifying the code. I think the simplest solution would be to stop gophish and spin up a temporary webserver. The easiest solution would be with python:
> 
> ```shell
> mkdir foo
> cd foo
> echo "blahblah" > index.xxx.html
> sudo python -m SimpleHTTPServer 80
> ```
> 
> That would start a webserver, serving up content from the foo directory (including your xxx.html for Google).

Thank you, that worked (almost) perfectly, just had to change some code:

```python3 -m pip install http.server
mkdir web
cd web
*copied the .html file into 'web' folder*
sudo python3 -m http.server 80
```
