### ISSUE TITLE
does not see the images in the email

### ISSUE THREAD

**Issue by SarahCary** [gophish/gophish#2462]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  0.11.0

Brief description of the issue: 
When I launch a campaign from an existing email, the email is sent but the images that appeared in the original email are not visible.

What are you expecting to see happen? :
I want the images to be visible when the email is received.

What are you seeing happen?
this is what I see:
![image](https://user-images.githubusercontent.com/63299560/168044648-cef67f65-b8bc-4615-b1ca-d4496bb54a6d.png)

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```
`<html xmlns="http://www.w3.org/TR/REC-html40" xmlns:m="http://schemas.microsoft.com/office/2004/12/omml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word">
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"/><meta name="Generator" content="Microsoft Word 15 (filtered medium)"/>
	<title>New article;</title>
	<style type="text/css">
	</style>
	
</head>
<body lang="FR" link="#C86E6E" vlink="#C86E6E">
<div class="WordSection1">
<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<div align="center">
<table border="0" cellpadding="0" cellspacing="0" class="MsoNormalTable" style="width:100.0%;background:#ECECEC" width="100%">
	<tbody>
		<tr style="height:30.0pt">
			<td style="padding:0cm 0cm 0cm 0cm;height:30.0pt">&nbsp;</td>
		</tr>
		<tr>
			<td style="padding:0cm 0cm 0cm 0cm">
			<div align="center">
			<table border="0" cellpadding="0" cellspacing="0" class="MsoNormalTable" style="width:412.5pt" width="550">
				<tbody>
					<tr>
						<td style="padding:0cm 0cm 0cm 0cm">
						<div align="center">
						<table border="0" cellpadding="0" cellspacing="0" class="MsoNormalTable" style="width:412.5pt;background:white" width="550">
							<tbody>
								<tr style="height:24.0pt">
									<td style="padding:0cm 0cm 0cm 0cm;height:24.0pt">&nbsp;</td>
								</tr>
								<tr>
									<td style="padding:0cm 0cm 0cm 0cm">
									<p align="center" class="MsoNormal" style="text-align:center;mso-line-height-alt:0pt"><img alt="img" id="_x0000_i1025" src="https://test.com/assets/images/messenger/logo.png" style="width:1.4583in" width="140" /><o:p></o:p></p>
									</td>
								</tr>
								<tr style="height:18.0pt">
									<td style="padding:0cm 0cm 0cm 0cm;height:18.0pt">&nbsp;</td>
								</tr>
								<tr>
									<td style="padding:0cm 0cm 0cm 0cm">
									<p align="center" class="MsoNormal" style="text-align:center;mso-line-height-alt:0pt"><img alt="img" id="_x0000_i1026" src="https://test.com/assets/images/messenger/news-poster.jpeg" style="width:5.7333in" width="550" /><o:p></o:p></p>
									</td>
								</tr>
								<tr style="height:21.0pt">
									<td style="padding:0cm 0cm 0cm 0cm;height:21.0pt">&nbsp;</td>
								</tr>
								<tr>
									<td style="padding:0cm 0cm 0cm 0cm">
									<div align="center">
									<table border="0" cellpadding="0" cellspacing="0" class="MsoNormalTable" style="width:375.0pt" width="500">
										<tbody>
											<tr>
												<td style="padding:0cm 0cm 0cm 0cm">
												<p align="center" class="MsoNormal" style="text-align:center"><b><span style="font-size:21.0pt;font-family:&quot;Century Gothic&quot;,sans-serif;color:#414A51;letter-spacing:2.25pt">new article create; <o:p></o:p></span></b></p>
												</td>
											</tr>
											<tr>
												<td style="padding:0cm 0cm 0cm 0cm">
												<div align="center">
												<table border="0" cellpadding="0" cellspacing="0" class="MsoNormalTable" style="width:37.5pt" width="50">
													<tbody>
														<tr style="height:9.0pt">
															<td style="border:none;border-bottom:solid #942FD3 2.25pt;padding:0cm 0cm 0cm 0cm;height:9.0pt">&nbsp;</td>
														</tr>
													</tbody>
												</table>
												</div>
												</td>
											</tr>
											<tr style="height:12.0pt">
												<td style="padding:0cm 0cm 0cm 0cm;height:12.0pt">&nbsp;</td>
											</tr>
											<tr>
												<td style="padding:0cm 0cm 0cm 0cm">
												<p class="MsoNormal" style="line-height:21.0pt"><span style="font-size:10.5pt;font-family:&quot;Arial&quot;,sans-serif;color:#7F8C8D">Hello,<br />
												Test, new article. <o:p></o:p></span></p>

												<h4 style="mso-margin-top-alt:2.25pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;margin-bottom:.0001pt;line-height:21.0pt"><span style="font-family:&quot;Arial&quot;,sans-serif;color:#7F8C8D">HOMEOFFICE<o:p></o:p></span></h4>
												</td>
											</tr>
											<tr>
												<td style="padding:0cm 0cm 0cm 0cm">
												<div align="center">
												<table border="1" cellpadding="0" cellspacing="0" class="MsoNormalTable" style="border:solid #281573 1.5pt">
													<tbody>
														<tr style="height:24.0pt">
															<td style="border:none;padding:0cm 11.25pt 0cm 11.25pt;height:24.0pt">
															<p align="center" class="MsoNormal" style="text-align:center"><span style="font-size:10.5pt;font-family:&quot;Arial&quot;,sans-serif;color:#361675"><a href="{{.URL}}"><span style="color:#422890">read the story</span></a><o:p></o:p></span></p>
															</td>
														</tr>
													</tbody>
												</table>
												</div>
												</td>
											</tr>
											<tr style="height:15.0pt">
												<td style="padding:0cm 0cm 0cm 0cm;height:15.0pt">&nbsp;</td>
											</tr>
											<tr>
												<td style="padding:0cm 0cm 0cm 0cm">
												<div align="center">
												<table border="0" cellpadding="0" cellspacing="0" class="MsoNormalTable" style="width:37.5pt" width="50">
													<tbody>
														<tr style="height:9.0pt">
															<td style="border:none;border-bottom:solid #942FD3 2.25pt;padding:0cm 0cm 0cm 0cm;height:9.0pt">&nbsp;</td>
														</tr>
													</tbody>
												</table>
												</div>
												</td>
											</tr>
											<tr>
												<td style="padding:0cm 0cm 0cm 0cm">
												<div align="center">
												<table border="0" cellpadding="0" cellspacing="3" class="MsoNormalTable">
													<tbody>
														<tr>
															<td style="padding:.75pt .75pt .75pt .75pt">
															<p class="MsoNormal"><img border="0" id="_x0000_i1027" src="https://test.com/assets/images/messenger/rocket.png" style="width:.525in" width="50" /><o:p></o:p></p>
															</td>
														</tr>
													</tbody>
												</table>
												</div>
												</td>
											</tr>
										</tbody>
									</table>
									</div>
									</td>
								</tr>
								<tr style="height:24.0pt">
									<td style="padding:0cm 0cm 0cm 0cm;height:24.0pt">&nbsp;</td>
								</tr>
							</tbody>
						</table>
						</div>

						<p align="center" class="MsoNormal" style="text-align:center"><o:p>&nbsp;</o:p></p>

						<div align="center">
						<table border="0" cellpadding="0" cellspacing="0" class="MsoNormalTable" style="width:412.5pt;background:white" width="550">
							<tbody>
								<tr>
									<td style="padding:0cm 0cm 0cm 0cm">
									<div align="center">
									<table border="0" cellpadding="0" cellspacing="0" class="MsoNormalTable" style="width:412.5pt" width="550">
										<tbody>
											<tr style="height:15.0pt">
												<td style="padding:0cm 0cm 0cm 0cm;height:15.0pt">&nbsp;</td>
											</tr>
											<tr>
												<td style="padding:0cm 0cm 0cm 0cm" valign="top">
												<div align="center">
												<table border="0" cellpadding="0" cellspacing="0" class="MsoNormalTable" style="width:412.5pt" width="550">
													<tbody>
														<tr>
															<td style="width:.3pt;padding:0cm 0cm 0cm 0cm" width="0">
															<div align="center">
															<table border="0" cellpadding="0" cellspacing="0" class="MsoNormalTable" style="width:90.0%" width="90%">
																<tbody>
																	<tr>
																		<td style="padding:0cm 0cm 0cm 0cm">
																		<p class="MsoNormal"><b><span style="font-size:12.0pt;font-family:&quot;Arial&quot;,sans-serif;color:#634B4B">Note <o:p></o:p></span></b></p>
																		</td>
																	</tr>
																	<tr style="height:3.0pt">
																		<td style="padding:0cm 0cm 0cm 0cm;height:3.0pt">&nbsp;</td>
																	</tr>
																	<tr>
																		<td style="padding:0cm 0cm 0cm 0cm">
																		<div>
																		<p class="MsoNormal" style="line-height:21.0pt"><span style="font-size:10.5pt;font-family:&quot;Arial&quot;,sans-serif;color:#9B9B9B">if you have any problems, please contact the support. <o:p></o:p></span></p>
																		</div>
																		</td>
																	</tr>
																	<tr style="height:12.0pt">
																		<td style="padding:0cm 0cm 0cm 0cm;height:12.0pt">&nbsp;</td>
																	</tr>
																</tbody>
															</table>
															</div>
															</td>
														</tr>
													</tbody>
												</table>
												</div>
												</td>
												<td style="padding:0cm 0cm 0cm 0cm" valign="top">&nbsp;</td>
											</tr>
										</tbody>
									</table>
									</div>
									</td>
								</tr>
							</tbody>
						</table>
						</div>

						<p align="center" class="MsoNormal" style="text-align:center"><span style="display:none"><o:p>&nbsp;</o:p></span></p>

						<div align="center">
						<table border="0" cellpadding="0" cellspacing="0" class="MsoNormalTable" style="width:412.5pt;background:white" width="550">
							<tbody>
								<tr>
									<td style="background:#287FF4;padding:0cm 0cm 0cm 0cm">&nbsp;</td>
								</tr>
							</tbody>
						</table>
						</div>

						<p align="center" class="MsoNormal" style="text-align:center"><o:p>&nbsp;</o:p></p>

						<div align="center">
						<table border="0" cellpadding="0" cellspacing="0" class="MsoNormalTable" style="width:412.5pt;background:#333742" width="550">
							<tbody>
								<tr>
									<td style="padding:0cm 0cm 0cm 0cm">
									<div align="center">
									<table border="0" cellpadding="0" cellspacing="0" class="MsoNormalTable" style="width:412.5pt" width="550">
										<tbody>
											<tr>
												<td style="width:.3pt;padding:0cm 0cm 0cm 0cm" width="0">
												<div align="center">
												<table border="0" cellpadding="0" cellspacing="0" class="MsoNormalTable" style="width:412.5pt" width="550">
													<tbody>
														<tr style="height:9.0pt">
															<td style="padding:0cm 0cm 0cm 0cm;height:9.0pt">&nbsp;</td>
														</tr>
														<tr>
															<td style="padding:0cm 0cm 0cm 0cm" valign="top">
															<div align="center">
															<table border="0" cellpadding="0" cellspacing="0" class="MsoNormalTable" style="width:412.5pt" width="550">
																<tbody>
																	<tr>
																		<td style="width:.3pt;padding:0cm 0cm 0cm 0cm" width="0">
																		<div align="center">
																		<table border="0" cellpadding="0" cellspacing="0" class="MsoNormalTable" style="width:412.5pt" width="550">
																			<tbody>
																				<tr>
																					<td style="padding:0cm 0cm 0cm 0cm">
																					<div>
																					<p align="center" class="MsoNormal" style="text-align:center"><span style="font-size:10.0pt;font-family:&quot;Arial&quot;,sans-serif;color:#9B9B9B">Thanks,<br />
																					Team test <o:p></o:p></span></p>
																					</div>

																					<div>
																					<div align="center" class="MsoNormal" style="text-align:center">
																					<hr align="center" size="3" width="100%" /></div>

																					<p align="center" class="MsoNormal" style="text-align:center"><span style="font-size:7.5pt;font-family:&quot;Arial&quot;,sans-serif;color:#9B9B9B">This message is generated automatically. Please do not reply. You are receiving this message because you have an account on Test. Subscription is not possible. <o:p></o:p></span></p>
																					</div>
																					</td>
																				</tr>
																				<tr style="height:6.0pt">
																					<td style="padding:0cm 0cm 0cm 0cm;height:6.0pt">&nbsp;</td>
																				</tr>
																			</tbody>
																		</table>
																		</div>
																		</td>
																	</tr>
																</tbody>
															</table>
															</div>
															</td>
															<td style="padding:0cm 0cm 0cm 0cm" valign="top">
															<div>
															<div align="center">
															<table border="0" cellpadding="0" cellspacing="0" class="MsoNormalTable">
																<tbody>
																	<tr>
																		<td style="width:375.0pt;padding:0cm 0cm 0cm 0cm" width="500">&nbsp;</td>
																	</tr>
																</tbody>
															</table>
															</div>
															</div>
															</td>
														</tr>
													</tbody>
												</table>
												</div>
												</td>
											</tr>
										</tbody>
									</table>
									</div>
									</td>
								</tr>
							</tbody>
						</table>
						</div>
						</td>
					</tr>
				</tbody>
			</table>
			</div>
			</td>
		</tr>
	</tbody>
</table>
</div>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>
</div>
</body>
</html>
`

Do I have to access the images directly from a website or can I import them from my documents directly into gophish?

**Comment by glennzw** [comment]
My French isn't great, but it looks like it's asking you to click a button to allow your mail client to load remote images. This is a mail client specific option (whether or not to load remote images).

Two alternatives are:
 i. Attach images and reference them by cid
ii. Encode images as Base64 and embed them

This article will help: https://sendgrid.com/blog/embedding-images-emails-facts/

**Comment by 03163074** [comment]
客户端加载会记录，网页版好像自动屏蔽远程图片

**Comment by glennzw** [comment]
Closing out as haven't heard back, feel free to re-open.
