### ISSUE TITLE
GoPhish Reported Button Not Working

### ISSUE THREAD

**Issue by frodeaux** [gophish/gophish#2464]
What version of Gophish are you using?: 
 0.11.0

Brief description of the issue:  
When using the admin console and trying to select the "Reported" button on the report, it does not work.  A popup appears to confirm but fails to report. 

What are you expecting to see happen? :  
I expect the it to show as reported and it does not report

What are you seeing happen? 
Nothing it does not register as reported.  The web inspector presents the following error upon trying to confirm the report: 

 XMLHttpRequest cannot load http://gophish.mydomain.com/report?rid=xjR75HV due to access control checks. (Mydomain.com is not the actual domain, I changed it for this post)

**Comment by glennzw** [comment]
Could you check your browser console when you click the button? See https://github.com/gophish/gophish/issues/2161#issuecomment-814245626

Perhaps it's this.

**Comment by frodeaux** [comment]
I have checked but that doesn't appear to be the same issue.  My console gives me:

XMLHttpRequest cannot load http://gophish.mydomain.com/report?rid=xjR75HV due to access control checks.

**Comment by glennzw** [comment]
Closing out as haven't heard back, feel free to re-open.
