### ISSUE TITLE
add rid parameter after @ if url contains @-sign

### ISSUE THREAD

**Issue by JoeDevler** [gophish/gophish#2465]
What version of Gophish are you using?: 
current version

Brief description of the issue: 
A @-Sign could be used to fuscate the Phishing URL
If i create a Campaign i have to set a url.
The rid parameter will automatic add to the choosen url.

What are you expecting to see happen? :
http://example.com-dep88z32g@phishingdomain.com/?rid=123
rid parameter should be part of real phishing url

What are you seeing happen?
http://example.com-dep88z32g?rid=123@phishingdomain.com/
rid parameter is part of fuscate url

**Comment by glennzw** [comment]
Hi @JoeDevler - thanks for reaching out. It seems to work fine for me:

Campaign:
![Screenshot 2022-05-13 at 12 48 49](https://user-images.githubusercontent.com/3966613/168277311-46b4bc05-aa98-4ee6-b60c-9c989132bb9f.png)

Resultant URL:
![Screenshot 2022-05-13 at 12 52 21](https://user-images.githubusercontent.com/3966613/168277828-94ccb7d2-1794-4436-b97b-c29c6e637137.png)


Could you share a screenshot of your Campaign modal please

**Comment by JoeDevler** [comment]
Hi @glennzw thank you.
I examined it, the behavior only appears when there is a # in the fuscating url
i.e.
http://example.com-laekgd#@phishydomain.com

so it just a little thing, which isnt really necessary for the url.
but is this intended?

Im glad that this "fuscating method" is already working!

**Comment by glennzw** [comment]
The behaviour is correct - by including the `#` the base of the URL is now `example.com-laekgd`, so the rid parameter gets appended there. You can test this in your browser by clicking your link (http://example.com-laekgd/#@phishydomain.com):

![Screenshot 2022-05-13 at 16 24 04](https://user-images.githubusercontent.com/3966613/168315987-c930add0-27c3-43b4-8fe5-1c5dff8c3053.png)

Compared to your first URL (http://example.com-dep88z32g@phishingdomainxxxx.com/?rid=123):


![Screenshot 2022-05-13 at 16 25 14](https://user-images.githubusercontent.com/3966613/168316181-f8447891-2f96-47a0-bbf7-88f1a41334f9.png)

You can also test this with Javascript:

```javascript
url = new URL("http://example.com-dep88z32g@phishingdomain.com")
url2 = new URL("http://example.com-laekgd/#@phishydomain.com")

console.log(url.origin)
http://phishingdomain.com

console.log(url2.origin)
http://example.com-laekgd
```
