### ISSUE TITLE
./gophish ????

### ISSUE THREAD

**Issue by bitstraveler** [gophish/gophish#2467]
hi, i'm not a new user of Gophish, but now i cannot start gophish like before last time i used it it was last december.

```bash
ubuntu@test:/opt/gophish/gophish$ ls
CONTRIBUTING.md    config       go.sum        static
Dockerfile         config.json  gophish.go    templates
ISSUE_TEMPLATE.md  context      gulpfile.js   util
LICENSE            controllers  imap          webhook
README.md          db           logger        webpack.config.js
SECURITY.md        dialer       mailer        worker
VERSION            doc          middleware    yarn.lock
ansible-playbook   docker       models
auth               go.mod       package.json
ubuntu@test:/opt/gophish/gophish$ ./gophish
-bash: ./gophish: No such file or directory
```

 why i cannot start gophish with the command ./gophish

i have done : chmod u+x gophish

**Comment by glennzw** [comment]
In your `ls` listing there is no file called `gophish` so that's why `./gophish` fails.

Type `go build` to compile `gophish.go` into `gophish`

**Comment by bitstraveler** [comment]
ok that's new, i never done go build in the previous version, thanks

**Comment by glennzw** [comment]
You can download a prebuilt version if you don't want to compile from source:

https://github.com/gophish/gophish/releases
