### ISSUE TITLE
password not working 

### ISSUE THREAD

**Issue by MuhammadBaig22** [gophish/gophish#2468]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue: 

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by MuhammadBaig22** [comment]
hello username and password is not working

**Comment by EhouarnBeriotOConnell** [comment]
Hello,

I am no Github or forums expert, but your message lacks information.
- What version of Gophish are you using ?
- Are you talking about Gophish login or sending profile SMTP authentification ?
- What is the exact error message ?
- What credentials did you try ? I believe default credentials are login : **admin** and password : **gophish**

Regards,

**Comment by DrW3b** [comment]
![2022_05_21_05_24_04_C_Users_Ahmad_Desktop_gophish_v0 11 0_windows_64bit_gophish](https://user-images.githubusercontent.com/94005355/169633611-84734d35-56b0-4cc2-8fb6-21c275f9fb18.gif)

**Comment by glennzw** [comment]
@DrW3b is spot on, you need to use the password from the console. I'll close this out but feel to re-open if you're still stuck.

**Comment by snowleoparddd17** [comment]
> you have to use the password thats showing in your console ![2022_05_21_05_24_04_C_Users_Ahmad_Desktop_gophish_v0 11 0_windows_64bit_gophish](https://user-images.githubusercontent.com/94005355/169633611-84734d35-56b0-4cc2-8fb6-21c275f9fb18.gif) [ ](https://user-images.githubusercontent.com/94005355/169633611-84734d35-56b0-4cc2-8fb6-21c275f9fb18.gif) ![2022_05_21_05_24_04_C_Users_Ahmad_Desktop_gophish_v0 11 0_windows_64bit_gophish](https://user-images.githubusercontent.com/94005355/169633611-84734d35-56b0-4cc2-8fb6-21c275f9fb18.gif) [ ](https://user-images.githubusercontent.com/94005355/169633611-84734d35-56b0-4cc2-8fb6-21c275f9fb18.gif)

even when I input the password on my console it doesnt work what can I do ?
