### ISSUE TITLE
Mac Zip File - Templates directory contains blank html files

### ISSUE THREAD

**Issue by pm190618** [gophish/gophish#247]
All the html files are filled with zeros. I copied the template directory from the Linux 64 bit zip file, and it will now load the html pages. I can login using the login.html page, but can't do anything else yet
[templates.zip](https://github.com/gophish/gophish/files/226976/templates.zip)

**Comment by jordan-wright** [comment]
Wow! I can't believe this hasn't been caught yet. Thanks for the report!

I've updated the release with my own backup of the files. Let me know if that fixes the issue for you.

**Comment by pm190618** [comment]
Glad to help! However, it didn't totally fix the problem. There were also some blank .js files in the static/js directory. I copied the static/js directory from the Linux 64 bit zip file as well, and now the console is showing no errors and I can navigate/create campaigns and everything like normal.

**Comment by jordan-wright** [comment]
Another good catch! I've updated the release, so we should be good to go. If you can confirm, then we can close out this issue.

Thanks again!

**Comment by jordan-wright** [comment]
I've gotten confirmation on another thread that this appears to be fixed.

Thanks again!
