### ISSUE TITLE
"sent to : " field empty in sending profile test email

### ISSUE THREAD

**Issue by EhouarnBeriotOConnell** [gophish/gophish#2472]
**What version of Gophish are you using?:** 
0.11.0, Windows executable

**Brief description of the issue:** 
"Who you sent to:" field empty in test email.

**What are you expecting to see happen? :**
Correct recipient email displayed.

**What are you seeing happen?**
field is empty

**Reproduce the problem:**
 * open sending profiles
 * click new profile
 * setup new profile
 * send test email
 * open test email

![image](https://user-images.githubusercontent.com/70465902/169040440-99c08239-7b16-4f58-a237-ff92a1d9c3ee.png)

I encountered this using 365 SMTP, Google SMTP, Mailhog SMTP, Outlook client and MailHog Client.
In both mail clients, the "to:" field is filled with correct email.
In "Source" tab in MailHog, field value is "=20"
![image](https://user-images.githubusercontent.com/70465902/169042888-f69bb43a-6c99-42e6-919b-728d094b838a.png)

Not a major inconvenience but I did not see any other issue about it and thought I might as well bring it up.
 
Love this tool, cheers !

**Comment by glennzw** [comment]
Hi @EhouarnBeriotOConnell, that's very odd. I don't have a Windows box handy at the moment, but on *nix this works for me:

<img width="688" alt="Screenshot 2022-06-03 at 12 29 52" src="https://user-images.githubusercontent.com/3966613/171845505-47666797-1ff8-44b7-a7e3-fb0f25429cb5.png">



<img width="476" alt="Screenshot 2022-06-03 at 12 28 11" src="https://user-images.githubusercontent.com/3966613/171845268-055323cd-1ed8-47c8-ac55-f2d1e91f6afc.png">

I'll have to spin up a Windows box and try replicate.

**Comment by EhouarnBeriotOConnell** [comment]
Everything is working now, without updating Gophish.

It was some time ago, but maybe I simply forgot to fill the First Name and Last Name fields ?
I'll close the issue for now, and reopen it if encounter the problem again.

Apologies and thank you for your time.
