### ISSUE TITLE
Error during campaign phishing

### ISSUE THREAD

**Issue by flabos82** [gophish/gophish#2475]
Hello 
i'm a new user of GoPhish.
I'm settuping it for a test following this guide (https://www.youtube.com/watch?v=fxAbhYrlYxs)
When i've set up Sending Profile i've run successfully a test on my personal email.
I've setup all and run a Campaign but GoPhish can't send email, on the dashboard i see "Error" on detailss of dashboard.
I cannot understand reason of this.
Could someone support me?
<img width="80" alt="Capture" src="https://user-images.githubusercontent.com/105927203/169548778-8bf37f18-7d75-4d7a-951e-f96ea1035d65.PNG">

Thanks
Flavio

**Comment by zer01sec** [comment]
Hi,

what does the output in the gophish server show once you start the campaign? Can you send a screenshot of that?

**Comment by flabos82** [comment]
Hi, there is no error message, this is my problem 
Just i see 2 moments when i run campaign.
1) sending icon near every mail addresso on dashboard
2) error icon ( as i put inside ticket ) near every mail addresso on dashboard .
![errore_gp](https://user-images.githubusercontent.com/105927203/169800017-74799c77-a4d5-4390-beee-b8de3bedfa34.jpg)
In order to provide a complete information i'm running GoPhish inside a Win 10 Pro 64 bit client on a notebook.
GoPhish is the last version available on download page.
Notebook is online using my mobile hotspot connection.
On notebook i've uninstall antivirus and disable windows firewall.
On the same address i've run successfully a test on sending profile tab.
Thanks
Flavio

**Comment by zer01sec** [comment]
Hi Flavio,

what I wanted from you is this output actually (the one you get on the machine from where you run gophish):
<img width="796" alt="gophishscrnsht" src="https://user-images.githubusercontent.com/97805141/169818235-1755e290-338d-4fb7-a16c-3eb9445927bf.png">

The one you provided doesn't say much what could be the issue here. So, when you launch your campaign, go through these lines and see what kind of messages you receive and those that are relevant paste here.

**Comment by flabos82** [comment]
i cannot understand reason but now i'm able to send out email.....:-)
I have Email Sent count set 1.
From my mobile i've opened email ( i've add a tracking image )  and click on link buy "Email Opened" and "Clicked Link" are still at 0. 
Do you know a good how to or course that i can follow to know better how to setup?
Thanks
Flavio

**Comment by glennzw** [comment]
Hi @flabos82. You'll need to expand that row to see the reason for the error. e.g:


<img width="1187" alt="Screenshot 2022-06-03 at 11 35 12" src="https://user-images.githubusercontent.com/3966613/171838276-0df90d27-82a9-4f67-8d90-a367500a842f.png">

**Comment by flabos82** [comment]
Thanks for clarification! 
I didn’t note this! 
Really thanks

Inviato da iPhone

**Comment by glennzw** [comment]
Sure!

**Comment by kingsxcell** [comment]
What could be the solution the error shown above as i am currently experiencing same.
