### ISSUE TITLE
Change variables (URL/IP) under a ongoing campaign 

### ISSUE THREAD

**Issue by Desiqvel** [gophish/gophish#2476]
Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
1.10 

Brief description of the issue: 
Is it possible to change the ladning page URL while a campaign is ongoing?
Google flagged my domain name and i need to change the landing page to somthing that isnt flagged as a phishing site

What are you expecting to see happen? :
Change a config file that stores info about the campaign 

What are you seeing happen?
A big red screen

**Comment by glennzw** [comment]
Hi @Desiqvel - thanks for reaching out. Hmm that's a tricky situation. If the emails have already left then there's nothing you can do as they're already headed for the users inboxes, and you can't edit that.

If it's a scheduled campaign, you could cancel it. But if you really wanted to you could edit the database :

```sql
UPDATE campaigns SET url='http://some-other-url.com/' WHERE name='Some Campaign';
```

**Comment by Desiqvel** [comment]
> Hi @Desiqvel - thanks for reaching out. Hmm that's a tricky situation. If the emails have already left then there's nothing you can do as they're already headed for the users inboxes, and you can't edit that.
> 
> If it's a scheduled campaign, you could cancel it. But if you really wanted to you could edit the database :
> 
> ```sql
> UPDATE campaigns SET url='http://some-other-url.com/' WHERE name='Some Campaign';
> ```

Thanks for the reply, when I think about it now it doesn't make sense to be able to change IP/URL after the mail is sent, it was just a last second hope after the site was flagged.

I think the only solution for this is better preparation, launch the site during testing and go to [https://search.google.com/search-console](Google search console) and claim the web url/ip of the landing page. 

There's a easy integration with GoDaddy if you're using that or you can set up a temporary simple http server in python (when Gophish is off, wasn't able to do this while Gophish was using the ports) and add the Google HTML-file in the folder you started the server.
