### ISSUE TITLE
Updated page for Google phishing

### ISSUE THREAD

**Issue by D4RKH0R1Z0N** [gophish/gophish#2484]
Hello I made the latest version of Google login page, available at [https://GitHub.com/D4RKH0R1Z0N/gphish](https://GitHub.com/D4RKH0R1Z0N/gphish), so can you try and add that page to this project?

**Comment by glennzw** [comment]
We don't store templates, users are create their own, but thanks for sharing!

**Comment by D4RKH0R1Z0N** [comment]
Oh ok!
