### ISSUE TITLE
Compile from source on Windows using Cygwin

### ISSUE THREAD

**Issue by EhouarnBeriotOConnell** [gophish/gophish#2491]
Hello !

I am trying to install Gophish from source on Windows 10 in order to use attachement tracking (by the way, does someone know when this will be available on the not-from-source binary ?).

I first tried : `go get github.com/gophish/gophish`
I had an error telling me to use `go install` instead because `go get` is deprecated.
So I did : `go install github.com/gophish/gophish@latest`

I had en error because I did not have gcc installed. I searched and found [this issue](https://github.com/gophish/gophish/issues/1790). SO I went on, installed Cygwin, added `C:\cygwin64\bin` to Path. GCC works : 

```
gcc --version
gcc (GCC) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
```

Then I retried `go install github.com/gophish/gophish@latest` and had this error : 
```
# github.com/mattn/go-sqlite3
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingwex: No such file or directory
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingw32: No such file or directory
collect2: error: ld returned 1 exit status
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function 'sqlite3SelectNew':
sqlite3-binding.c:128049:10: warning: function may return address of local variable [-Wreturn-local-addr]
128049 |   return pNew;
       |          ^~~~
sqlite3-binding.c:128009:10: note: declared here
128009 |   Select standin;
       |          ^~~~~~~
```

I searched more and found [this issue](https://github.com/gophish/gophish/issues/450). So I copied the gcc.exe file from `C:\cygwin64\bin` to `C:\Program Files\Go\bin`.

Tried go install again, and now I have this : 
```
# github.com/mattn/go-sqlite3
gcc: fatal error: cannot execute 'cc1': spawn: No such file or directory
compilation terminated.
```

Any help is appreciated.
If I ever get this to work, I'll try making a complete guide on how to compile Gophish from source on Windows that could maybe be added to the documentation, since this has been very time-consuming for me so far.

**Comment by Miesvanderlippe** [comment]
It's easier to use the supplied Dockerfile. This provides a consistent environment for everyone.

Another option is using Windows Subsystem for Linux. 

I recommend looking trough some Go on Windows tutorial if you still want to build from source on native windows.
