### ISSUE TITLE
Campaign Stats (Links clicked on, emails opened, information entered, reported emails) not updating 

### ISSUE THREAD

**Issue by nv0019** [gophish/gophish#2492]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: [Gophish v0.11.0]

Brief description of the issue: Whenever I run a campaign on  GoPhish,  The stats are not updating for some reason (emails opened, clicked links, emails reported. information entered). In other words, it just stays at 0.

What are you expecting to see happen? : I am expecting to see actual stats on the information listed above when running the campaign.  I am using my IP Address for the Listen_Url on the config.json file and on the campaign ending it with .80.

I am not using a VPS. If that is needed, I would greatly appreciate it if you can show me how to install it and connect it with gophish. I am also using Kali Linux

What are you seeing happen?

I am unfortunately unable to provide  a screenshot but its basically Amount of emails sent: 2 and the other categories as 0 in the campaign 

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by mthenmo** [comment]
hello im using Gophish v0.11.0

Brief description of the issue: Whenever I run a campaign on GoPhish, The stats are not updating for some reason (emails opened, clicked links, emails reported. information entered). In other words, it just stays at 0.

What are you expecting to see happen? : I am expecting to see actual stats on the information listed above when running the campaign. I am using my IP Address for the Listen_Url on the config.json file and on the campaign ending it with .80.

I am not using a VPS. If that is needed, I would greatly appreciate it if you can show me how to install it and connect it with gophish. I am also using Kali Linux

What are you seeing happen?

![image](https://user-images.githubusercontent.com/107203493/172895169-b25a323b-cb65-47c8-9e71-70ce2996dc70.png)

![image](https://user-images.githubusercontent.com/107203493/172895426-6d54d472-b2f1-47ca-9830-04f7e05469dd.png)

![image](https://user-images.githubusercontent.com/107203493/172895725-42d79ac6-d594-4e50-beac-9a6543ff8147.png)

![image](https://user-images.githubusercontent.com/107203493/172895817-57e31288-2381-4568-bb48-0df99779790f.png)


im using microsoft's SMTP server 
is there somthing else that will help you to understand my case better?

thanks 

Insert output here
Please provide as many steps as you can to reproduce the problem:

Step 1 -
Step 2 -

**Comment by mthenmo** [comment]
hey thaks for your answer
for the first quastion: if i'll change the port to port 80 it wiil work? or i would also will need to allow the access via local FW and on my router on my privete LAN ? (i'm using oracle VB VM for the platform) i will create VPS if nedded   
i've tried to use to SMTP suppliers one havent activatied the account and the second is microsoft SMTP.
should it work microsoft SMTP ?

**Comment by gear0** [comment]
Hi @mthenmo,
to make your gophish instance running on a virtual machine inside your private LAN you would need multiple things.
1. A static public IP or a respective dynamic DNS entry.
2. Rules on your Firewall allowing incoming traffic to your virtual machine.
3. The virtual machine needs a network which is bridged to the Host network. Otherwise you would need port forwardings configured in virtual box.

The easier way to run gophish is definitely on a vps.

Regarding SMTP, it could work with Microsoft, but I guess they might block you rather quickly if you run large campaigns. A better way would be running a dedicated SMTP server yourself.

Kind regards,
gear0

**Comment by mthenmo** [comment]
thak you so much 

i'm planing to install a VPS soon i just want to make sure that all the configuration will work properly.
i have approved traffic to my VM and i've configured port forwarding as well
the VM network adpter is attaced to bridgeg adapter 
im using port 3335 and its not working :|

**Comment by gear0** [comment]
Without knowing the exact configuration of all components it will be very difficult to debug the current setup in virtualbox. To exclude as many sources of error as possible you can try to open one of the phishing mails locally on the machine on which gophish is running and try access your phishing landing page from this machine as well.

Additionally, it would also help if you could provide a screenshot of the campaign you try to launch.

Kind regards,
gear0

**Comment by nvasquez22** [comment]
@gear0. Could you possibly help me as well?

**Comment by gear0** [comment]
Hi @nvasquez22,
I can try but therefore you need to describe your problem.

Kind regards, 
gear0

**Comment by nvasquez22** [comment]
@gear0 

Sure. 
Whenever I run a campaign on GoPhish, the stats such as emails opened, links opened, Reported emails still remain at 0.  For the link used, I'm using my IP Address. 80 along for the Json.config settings . I am currently using Kali Linux and I dont have a VPS. If a VPS is required, please let me know and possibly explain how to download/ incoporate it to GoPhish

**Comment by gear0** [comment]
This sounds a lot like the problem mthenmo had. Can you please share your config.json. 

A VPS is not strictly required but it makes things easier since you won't need to configure NAT/Port Forwarding and possibly no dynamic DNS.

Could you please also start a campaign for testing purposes and share the configuration of the campaign as well as the output of the command

`curl -v http://<YOUR_PHISHINGSERVER_IP_OR_DOMAIN>/?rid=<RID_OF_TESTUSER>`

**Comment by nvasquez22** [comment]
![InkedScreenshot from 2022-06-13 08-07-18_LI](https://user-images.githubusercontent.com/80422709/173362832-bf6d4089-f42f-4274-9a50-f4c2fe6d9410.jpg)

**Comment by nvasquez22** [comment]
@gear0 
I left the Listen URL as it is on Phish_server, I don't know if it has to be changed

**Comment by mthenmo** [comment]
hello again 

iv'e installed GoPish on a VPS and im having problems with finding a SMTP service that allows to make Phishing awernesse traning on his platform. 
I would like to use an open source SMTP server that i will manage.
for that i have 3 questions.
1. can i use this SMTP server to send mails over the internet?
2. do you have a recommend about easy solution to implement?
3. will i need to buy a domain name for this and configure DNS Records or somthing like that ?
thanks so much ! 

Moshe

**Comment by gear0** [comment]
> Sorry could you elaborate on the output of the command? I see you provided an example but where do you get access to that command? The linux terminal?
> 
> 
> 
> Also, here is the screenshot of the config.file
> 
> 
> 
> 
> 
> ![InkedScreenshot from 2022-06-13 08-32-13_LI](https://user-images.githubusercontent.com/80422709/173362482-984e4dee-0910-4cc2-b507-2a7bedddcef4.jpg)
> 
> 09/173362452-7204a57f-849b-41c2-9b88-e6fc5aca2905.jpg)
> 
> 

Yes you have to enter the command in the linux terminal with the values appropriate to your campaign. For example if you used `phish.mydomain.com` as URL when creating your campaign and the RID for one of your target is `x5aj7v` then the command would be as follows

`curl -v http://phish.mydomain.com/?rid=x5aj7v`

You can find the RID of a target when you navigate to the campaign details and expand the info for a target. The RID is shown right under the firstname and lastname.

**Comment by gear0** [comment]
> hello again 
> 
> 
> 
> iv'e installed GoPish on a VPS and im having problems with finding a SMTP service that allows to make Phishing awernesse traning on his platform. 
> 
> I would like to use an open source SMTP server that i will manage.
> 
> for that i have 3 questions.
> 
> 1. can i use this SMTP server to send mails over the internet?
> 
> 2. do you have a recommend about easy solution to implement?
> 
> 3. will i need to buy a domain name for this and configure DNS Records or somthing like that ?
> 
> thanks so much ! 
> 
> 
> 
> Moshe
> 
> 

Hi @mthenmo,
Please find the answers below.
1. You will probably be able to send mails with your self-hosted mail server over the internet, but this also depends on the VPS provider. For example Amazon is actively blocking outgoing traffic to port 25 and you must go through a process with Amazon Security Team to get port 25 unlocked.
2. If you run docker you might want to take a look at [docker-mailserver](https://docker-mailserver.github.io/docker-mailserver/edge/)
3. Yes a domain would be required as well as setting respective DNS records.

**Comment by glennzw** [comment]
This conversation is quite old now so I'm going to close it out. Feel free to reopen with fresh information or open a new issue.
