### ISSUE TITLE
Tracking attachments not working

### ISSUE THREAD

**Issue by kavanaas** [gophish/gophish#2494]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
Gophish v0.11.0

Brief description of the issue: 
Any attachments are working

What are you expecting to see happen? :
When i click the link the gophish dashboard shows email is clicked, opened etc,,. But I want when the attachment is opened.

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 - 
 

I a, also confused that when i add attachment what exactly i need to fill in the EMail template and Landing page?. Could please someone help me.

**Comment by EhouarnBeriotOConnell** [comment]
Hello !

I believe attachment tracking is not implemented in 0.11.0.
To get this feature to work, you will have to [compile Gophish from source](https://github.com/gophish/gophish#building-from-source) to get the latest version.

More info on this [here](https://github.com/gophish/gophish/issues/2397) and [here](https://github.com/gophish/gophish/issues?q=is%3Aissue+attachment++tracking).

To setup a campaign with attachement tracking, your email template can be something like : 
![attachement_exemple_1](https://user-images.githubusercontent.com/70465902/173527690-569f514e-3b35-4829-bd78-d0277962d227.png)

(The attachement will have to be setup like described [here](https://docs.getgophish.com/user-guide/documentation/attachments))

If you don't have a link in your email, your landing page can be anything, this won't affect attachement tracking.

So your campaign:
![attachement_exemple_2](https://user-images.githubusercontent.com/70465902/173528990-61b4e703-98db-490e-ab83-9954748a2aea.png)


Hope his helps,

**Comment by kavanaas** [comment]
Hello @EhouarnBeriotOConnell,

Thank you so much for your response. I have already tried with the given version and the steps you mentioned. Unfortunately, when the user open an attachment, in the Gophish dashboard the number of counts are not showing. It would be really great if you could answer me.

**Comment by pwnmagus** [comment]
Hi @EhouarnBeriotOConnell , I also have same issue here,

Here's  mine

What version of Gophish are you using?: 0.11.0

Brief description of the issue:  I tried to run phishing campaign with an attachment based on this article. [user-guide/attachments.md at fe136bcb4927f1fd2caed899adf5d4fe4195ef77 · gophish/user-guide · GitHub](https://github.com/gophish/user-guide/blob/fe136bcb4927f1fd2caed899adf5d4fe4195ef77/documentation/attachments.md) . the variable in the attachment didn't converted at all.

What are you expecting to see happen?: I'd like to see the variables in the attachment converted to appropriate value based on every target

What are you seeing happen?: The variables in every attachment didn't get converted, and the tracker didn't work

Here's the evidence for this issue :
![evidence gophish](https://user-images.githubusercontent.com/38983134/178923320-3ba011f9-e477-4563-a4b5-3b71d7a57839.png)

Please kindly check for any solution for this issue :)

**Comment by Miesvanderlippe** [comment]
Hey,

I'm pretty sure attachment tracking has been added in 0.12.0. All those tags should've been replaced, not just the image one.

**Comment by glennzw** [comment]
Yup as @Miesvanderlippe pointed out attachment tracking has been rolled into the latest version

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen.

**Comment by MorielHarush** [comment]
i am using v0.12.1 , i have similar issue. im trying to track a docx file with office 2013 installed.
i used the tag : {{.TrackingURL}} into Word > Insert > field > includeimage . 
the system does not show me that the file is opened. 
** if im using the {{.TrackingURL}} as text inside the word file , it shows me the tracking link. just in case it helps to identify the problem.

**Comment by jr-catalyst** [comment]
Can report the same behaviour on 0.12.1

Following the official documentation and using the default .docx file, no metrics other than "Email sent" are reported in the dashboard. The {{.TrackingURL}} is resolving successfully in the document, as is {{.FirstName}}.

Despite including a {{.Tracker}} tag in the email, no reports of the email being opened. And no reports of the document being opened either. 

Campaigns using a link work as expected, it is just the attachments that fail.

What other debugging information can I provide?

**Comment by Miesvanderlippe** [comment]
At this point you should consider this project dead and a bad idea to run. Everything is outdated.

Anyways, you can do a bit of debugging by renaming the e-mail attachment to .docx.zip and checking the document rels for your tracking pixel. Manually curl that url and checks whether it works.
