### ISSUE TITLE
Email Template - Design with loading of images 

### ISSUE THREAD

**Issue by ecgkleung** [gophish/gophish#2498]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.11.0

Brief description of the issue: 
Any ideas how to make use of the gophish's web server as images for storing multimedia files when we designing email template? as the UI does not have an option that upload image into the email template.

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by ecgkleung** [comment]
I am trying to upload the images under the path /root/gophish/static/images/images.jpg

but when i want to browse the image from browser, it does not work as well.
https://ip/images/images.jpg

**Comment by gear0** [comment]
Hi @ecgkleung,
If you don't have any proxy running in front of gohish the URL for static resources should be https://ip/static/images/images.jpg in your case. If you don't want to place any images on the server you can include the images as base64 encoded version. See [stackoverflow](https://stackoverflow.com/questions/8499633/how-to-display-base64-images-in-html) for an example.

Kind regards,
gear0
