### ISSUE TITLE
Send Test Email

### ISSUE THREAD

**Issue by jordan-wright** [gophish/gophish#25]
Before launching a campaign, it would help if the admin could send a test email to himself/herself to ensure all looks good.

**Comment by jordan-wright** [comment]
Marked as high priority due to the increase in usability this provides.

**Comment by richardontheinternet** [comment]
You know them annoying pop up boxes? Put one in the final version when you press launch campaign. Tools that i've tried in the past that are trigger happy have to get uninstalled as they can't be trusted on the job.

**Comment by jordan-wright** [comment]
@rfdevere - I added the launch campaign confirmation a couple of days ago. Also, just a heads up, I just finished implementing the basic ability to send a test email in #97.
