### ISSUE TITLE
'go get' is no longer supported outside a module

### ISSUE THREAD

**Issue by ThatzOkay** [gophish/gophish#2502]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
latest
Brief description of the issue: 
tring to follow instruction of how to build gophish i get a error message on go get
What are you expecting to see happen? :
go get downloading to source to my go home folder
What are you seeing happen?
the error message
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:
go: go.mod file not found in current directory or any parent directory.
'go get' is no longer supported outside a module.
To build and install a command, use 'go install' with a version,
like 'go install example.com/cmd@latest'
For more information, see https://golang.org/doc/go-get-install-deprecation
or run 'go help get' or 'go help install'.
```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - go get github.com/gophish/gophish

**Comment by Aphelion09** [comment]
try "git clone https://github.com/gophish/gophish.git" and then move to the new gophish directory and run go build. Then just start the gophish binary
