### ISSUE TITLE
After installing from source: sending an e-mail gives this error: tls: server selected unsupported protocol version 301

### ISSUE THREAD

**Issue by Aphelion09** [gophish/gophish#2503]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:
build from source

Brief description of the issue: 
Sending E-Mails from the host of my company worked perfectly fine with gophish 1.10. After installing gophish from source and copying my DB, I get the following error once I wanna send an Mail " Max connection attempts exceeded - tls: server selected unsupported protocol version 301 ". Even with a new gophish.db I get the same message. So it is for sure a Problem with an updated file, sadly I can't find the error in the source code. 

What are you expecting to see happen? :
sending an e-mail without problems, like it used to do
What are you seeing happen?
 Max connection attempts exceeded - tls: server selected unsupported protocol version 301
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by Aphelion09** [comment]
The Host is using an old TLS Version which isnt support anymore I guess. Any way to bypass this?

**Comment by glennzw** [comment]
Hi @Aphelion09 - yeah it looks like you're right. A quick Google indicates:

```
"unsupported protocol version" 301 means an insecure TLS version (1.0), selected by the server. (and 301: permanently redirected)
```

I don't believe we've updated any of our SMTP logic between source and 1.10, but maybe an underlying library doesn't like using older protocols. Unfortunately I can't think of an easy way for you to solve this, other than updating your SMTP server.

You *might* be able to put a mitmproxy in between, but that could get messy.

**Comment by Aphelion09** [comment]
Yes we did update it, even though it had some complications. Still thanks, i'm gonna close the thread.
