### ISSUE TITLE
"Redirect To..." option missing on Windows 32/64 bit build

### ISSUE THREAD

**Issue by lockandski** [gophish/gophish#252]
The landing page configuration option "Redirect to..." is missing in the Windows 32/64 bit builds

![image](https://cloud.githubusercontent.com/assets/9500421/14716982/969b1cb6-07ac-11e6-8907-5ec8f43f2716.png)

**Comment by jordan-wright** [comment]
Hey there,

I believe that this feature is being introduced in 0.2, which is not yet released. If you build from source, this feature will be available.
