### ISSUE TITLE
Unable to get password "no contact address has been configured"

### ISSUE THREAD

**Issue by snowleoparddd17** [gophish/gophish#2525]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  v0.11.0 windows 64 bit

Brief description of the issue: When i try to cd gophish on my command script as administrator, it tells me to add a contact address in the config.json. Im not sure what to add there to make it work, or what a contact address even is.

What are you expecting to see happen? : The password for my gophish showing up for me to be able to sign in.

What are you seeing happen? "No contact address has been given, please consider adding a contact_address entry in your config.json"

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 - 
 
 
![Screenshot (1)](https://user-images.githubusercontent.com/108897162/177857529-d6b013af-31df-4e79-b5d8-c5fc061d889a.png)

**Comment by snowleoparddd17** [comment]
So I figured out that for contact address , you input the url for the gophish github page ( https://github.com/gophish/gophish )

works fine now and gave me my password , but the password wont work on the site even though i have admin as username and inputting the correct password from my command script

**Comment by glennzw** [comment]
Hi @snowleoparddd17 - so yes you can put the contact address, but that's optional. The password should just be copy/pasted from the terminal - careful of picking up extra characters like the double quote.
