### ISSUE TITLE
Max connection attempts exceeded - unencrypted connection

### ISSUE THREAD

**Issue by aaq1adqwe** [gophish/gophish#2530]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
gophish-v0.11.0-windows and linux

Brief description of the issue: 

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 - 
 
 Max connection attempts exceeded - unencrypted connection

I set up gophish in the LAN environment，and I can send and receive normally using the third-party email client。
I don't know why gophish will report this error when adding STMP to send the test email。

Is it the problem of gophish or SMTP server？

**Comment by aaq1adqwe** [comment]
> 

I can't operate the smtp server, so how can I fix this myself   :(

Help me，please！

**Comment by Mr3Jane** [comment]
Could you please check with your SMTP support if they have TLS config available? It should be there by default almost, just another port

**Comment by glennzw** [comment]
As @Mr3Jane points out this is a problem with your SMTP server, not gophish. Without more details, or the ability to modify your SMTP server, we can't help much.

I'd suggest setting up your own SMTP server: https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-postfix-as-a-send-only-smtp-server-on-ubuntu-20-04

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen.
