### ISSUE TITLE
Do admin and phish server support separate deployment?

### ISSUE THREAD

**Issue by Caratpine** [gophish/gophish#2531]
I want to deploy the admin server in the intranet environment and the phish server in the public network environment. Is this supported? thanks.

**Comment by Mr3Jane** [comment]
Not really, not OOTB. I was looking for the same solution for my setup as well, but there's no easy way to do that. I've settled with firewall rules and white-listing some IPs to admin panel, reducing the attack surface to public part of the app.

**Comment by Caratpine** [comment]
Thanks @Mr3Jane 
I think it's a strong requirement. Employee information is sensitive, and some companies do not allow this data to be stored in the cloud or on the public Internet.

**Comment by glennzw** [comment]
It'd be quite tricky to break those components apart. You can host your gophish server internally, and route traffic from an external VPS/cloud provider to your internal gophish host.

HTH.
