### ISSUE TITLE
Opened/Clicked-Link Status Not Being Tracked_MS Exchange

### ISSUE THREAD

**Issue by moses0404** [gophish/gophish#2538]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.11.0
Brief description of the issue: 
When launching a campaign, it only shows the sent status, no opened no link clicked status, knowing that our mail server is an MS ECHANGE 2019
What are you expecting to see happen? :
See the count of the opend mails and the clicked links
What are you seeing happen?
0 opened mails, 0 link clicked
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
<html>
<head>
	<title></title>
</head>
<body>
<p>Hi, Please support our IT project by clicking <a href="{{.URL}}">here</a>.<br />
<br />
<br />
<br />
<br />
Thanks,<br />
<br />
IT department</p>

<p>{{.Tracker}}</p>
</body>
</html>
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 - 
 
![image](https://user-images.githubusercontent.com/110186514/181592202-012151a1-cecc-4319-b975-645e75bf38bc.png)
![image](https://user-images.githubusercontent.com/110186514/181592491-58bf1ed4-84a9-4521-9f7a-79c3b7259f0c.png)

**Comment by glennzw** [comment]
Hi @moses0404 - thanks for reaching out. As you can see in your email photo at the bottom, the tracking image isn't being loaded:


![Screenshot 2022-07-30 at 12 18 09](https://user-images.githubusercontent.com/3966613/181908519-2c36cc79-9271-40f7-9fd9-6fc81f63d011.png)

You'd need to configure your email environment to allow remote image loading if you want the tracker to work.

As for the clicks not being registered; what happens when you click the link in your email?

**Comment by moses0404** [comment]
The main issue is that the port 80 wasn't open on my server, thank you for the support
