### ISSUE TITLE
Admin page is not working on my domain

### ISSUE THREAD

**Issue by mrymalali** [gophish/gophish#2539]
Brief description of the issue: 

dears, 
i'm trying to access gophish admin page with my domain --> XXX.com:3333
but it is not working 
although my domain is working fine and i have tried to insert an html code and it was working fine..
also it is not working with the IP that i use for my server !

What are you expecting to see happen? :
![sc1](https://user-images.githubusercontent.com/37781891/181792138-85ca2192-0f11-42ea-950d-c4132aa6de83.png)
![sc2](https://user-images.githubusercontent.com/37781891/181792174-a48c23e3-52ec-4b30-881f-2c396d578b81.png)

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
You'll need to provide a bit more information please:

 * Can you access the site via IP directly?
 * Please share your `config.json` file
 * Please share the output from the console when running gophish

**Comment by mrymalali** [comment]
> 
Can you access the site via IP directly?
unfortunately no !
![sc1](https://user-images.githubusercontent.com/37781891/181953096-eb528e25-018e-4418-87c5-2b9e462861df.png)

Please share your config.json file

      `  GNU nano 4.8                                  config.json                                             {
        "admin_server": {
                "listen_url": "0.0.0.0:3333",
                "use_tls": true,
                "cert_path": "gophish_admin.crt",
                "key_path": "gophish_admin.key"
        },
        "phish_server": {
                "listen_url": "0.0.0.0:443",
                "use_tls": false,
                "cert_path": "/etc/ssl/certificate.crt",
                "key_path": "/etc/ssl/private/private.key"
        },
        "db_name": "sqlite3",
        "db_path": "gophish.db",
        "migrations_prefix": "db/db_",
        "contact_address": "",
        "logging": {
                "filename": "",
                "level": ""
        }
}
`

Please share the output from the console when running gophish
root@Phishing:~# ./gophish
time="2022-07-30T19:24:54Z" level=warning msg="No contact address has been configured."
time="2022-07-30T19:24:54Z" level=warning msg="Please consider adding a contact_address entry in your config.json"
goose: no migrations to run. current version: 20200730000000
time="2022-07-30T19:24:54Z" level=info msg="Starting admin server at https://0.0.0.0:3333"
time="2022-07-30T19:24:54Z" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
time="2022-07-30T19:24:54Z" level=info msg="Starting IMAP monitor manager"
time="2022-07-30T19:24:54Z" level=info msg="Starting new IMAP monitor for user admin"
time="2022-07-30T19:24:54Z" level=info msg="Starting phishing server at http://0.0.0.0:443"
time="2022-07-30T19:24:54Z" level=fatal msg="listen tcp 0.0.0.0:443: bind: address already in use"


hope this can help, thanks in advance :)

**Comment by mrymalali** [comment]
I should inform you that im using digitalocean

**Comment by AJQBSC** [comment]
I met the same problem. Do you know why now? I wonder how to solve the problem.

**Comment by glennzw** [comment]
So the one problem is that port 443 is already in use, as you can see by the error on the final line:

```
time="2022-07-30T19:24:54Z" level=fatal msg="listen tcp 0.0.0.0:443: bind: address already in use"
```

You'll need to stop whatever webserver is running there. As for not being able to hit :3333 for the admin console, could you see if you can access it locally. e.g ssh in a second time and run:

```
wget https://127.0.0.1:3333
```

This should let you know if it's a firewall/acl issue, or if gopish isn't starting properply

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen.
