### ISSUE TITLE
Submitted Data Tracking

### ISSUE THREAD

**Issue by moses0404** [gophish/gophish#2540]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.11.0
Brief description of the issue: 
Submitted Data not bieng tracked for some template, for example template"1"  works fine but template"2" tracks only the openning and clicking status 
What are you expecting to see happen? :
Submitted data
What are you seeing happen?
It doesn't show always the submitted data
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:
template"1" is this one: https://github.com/FreeZeroDays/GoPhish-Templates/blob/master/Landing_Pages/O-Three-Sixty-Five_Landing_Page.html

Template"2" is in the attachement because maximum  is 65536 characters
![Stats](https://user-images.githubusercontent.com/110186514/182036889-a738523c-6f8e-47f2-96f6-6a8e6a0bf845.PNG)
![Mail](https://user-images.githubusercontent.com/110186514/182036890-d1b06403-50a2-4345-a905-cf09f02ebbd3.PNG)
![Landing Page](https://user-images.githubusercontent.com/110186514/182036892-81f4c7d4-47e7-4c6d-9886-ae60a72a007f.PNG)

```html
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by moses0404** [comment]
[template2.txt](https://github.com/gophish/gophish/files/9229798/template2.txt)

**Comment by glennzw** [comment]
Hi @moses0404 - that second template is a little too big for us to help debug here - just know that the requirements for a landing page are:

 * Data should be submitted in a form via a POST
 * Form action should be blank
 * Form variables should have names

Here's a base page that you can adapt and integrate into your own templates:

```html
<html><head></head><body>
  <form action="" method="post" name="form">
    <label>Username:</label> <input name="username" type="text"/><br/>
    <label>Password:</label> <input name="password" type="password"/><br/>
   <input id="login" name="login" type="submit" value="Login"/>
  </form>
  
</body></html>
```

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen.
