### ISSUE TITLE
GOPHISH x GOOGLE DATASTUDIO

### ISSUE THREAD

**Issue by renatodesouzabr** [gophish/gophish#2541]
Which version of Gophish are you using?:
0.10.1

Brief description of the problem:
I need to make campaign data available in Google data Studio, but I'm not having success, as an alternative I thought of making it available in google sheet, but I don't know if this is the best way.

What do you expect to see happen? :
Make campaigns available as a data source in Data Studio

What are you seeing happening?
I don't know how to do it, I tried via API or Webhooks, but I'm not having success.

**Comment by glennzw** [comment]
Hi @renatodesouzabr; your best bet would be to download the CSV data from the campaign page:

![Screenshot 2022-08-02 at 16 23 54](https://user-images.githubusercontent.com/3966613/182411997-e94b8dba-49b2-4b82-9a25-42a2190d03a2.png)

and then find a way to import it to your desired location.

**Comment by renatodesouzabr** [comment]
Hello @glennzw thanks for replying, this option I've been using, I need something that updates the data automatically.

**Comment by glennzw** [comment]
You'll need to use the API if you want real-time data https://docs.getgophish.com/api-documentation/
