### ISSUE TITLE
Using current time for email template

### ISSUE THREAD

**Issue by emersonku** [gophish/gophish#2543]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  v0.11.0

Brief description of the issue:  
I want to insert current time into my phishing email template for time sensitive campaign. I tried to use {{.NOW}} but template failed to compile. It does not recognise the {{.NOW}}

What are you expecting to see happen? : 
Showing current time of the system.

What are you seeing happen?
Template failed to compile.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
Additional template variables of this nature are on the radar, but no time soon I'm afraid. Good idea though and thanks for the suggestion.
