### ISSUE TITLE
Specifying an Envelope Sender doesn't work due to outdated templates.min.js

### ISSUE THREAD

**Issue by sylencecc** [gophish/gophish#2545]
When adding or editing an Email template, the field "Envelope Sender" is silently ignored during saving the template. Inspecting  the POST request made to save a template confirms that the field's contents are never sent to the server.
The reason is that the minified `templates.min.js` in `static/js/dist/app/` differs from its source `templates.js` in `static/js/src/app/`. Some of  the code for handling the "Envelope Sender" field is missing, the culprit seems to be the merge commit bb516ef7aba4e4f8026b8ad7a122dd5574492782, in which ` templates.min.js`  is only partially updated, missing some of the changes made to the original ` templates.js`.

Running `gulp`  to regenerate the minified JS files prior to executing `go build` fixes the issue.

To reproduce, do the following:
* Select "Email Templates" in the sidebar
* Click "New Template", fill out the form with dummy values and input any E-Mail address into "Envelope Sender"
* Click "Save Template"
* Navigate to a different section, e.g. by clicking on "Landing Pages" (to prevent form data to be cached)
* Navigate back to "Email Templates" 
* Edit the template you created previously
* The field "Envelope Sender" is empty

What are you expecting to see happen? :
Envelope Sender should be saved.

What version of Gophish are you using?: 
built from master branch, currently on commit 5ef2d75e72a0e1425aa18deacebbc4bf73b617a9

**Comment by glennzw** [comment]
Great catch thank you @sylencecc - let me do some investigations and get this fixed ASAP.

To confirm, with the current master the `templates.js` has the correct logic/code, but has been incorrectly minified?

**Comment by sylencecc** [comment]
Correct.
As an example, the `save(idx)` function in `templates.js` starts with
```
template.name = $("#name").val()
template.subject = $("#subject").val()
template.envelope_sender = $("#envelope-sender").val()
template.html = CKEDITOR.instances["html_editor"].getData();
```
while the same method in `templates.min.js` is missing `envelope_sender`-specific stuff:
```
e.name = $("#name").val(), 
e.subject = $("#subject").val(), 
e.html = CKEDITOR.instances.html_editor.getData(), 
```

**Comment by glennzw** [comment]
Perfect, thanks so much @sylencecc. I've re-minified the `template.js` file and pushed to master. Could you verify it all works as expected now?

I realise when testing I must've used an already saved Email Template, that had the Envelope saved.

**Comment by sylencecc** [comment]
Works as expected now, thank you! :+1:
