### ISSUE TITLE
I cannot access gophish

### ISSUE THREAD

**Issue by verosf98** [gophish/gophish#2547]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: **v0.11.0-windows-64bit**

Brief description of the issue:  **I installed the program and when I try to access it, I get this message**
![image](https://user-images.githubusercontent.com/97690120/183678872-0a25bbda-ebc7-4fe8-8f48-58b87e977a44.png)

What are you expecting to see happen? : **the program running**

What are you seeing happen? **The page gives an error "ERR_CONNECTION_REFUSED".**

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:
![image](https://user-images.githubusercontent.com/97690120/183679474-48b52917-2fc9-4e1b-9edf-7e272728b58a.png)

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Introducing https://127.0.0.1:3333 in url 
 * Step 2 -

**Comment by verosf98** [comment]
I have tried many of the solutions on the internet for this error and still have not been able to solve it.

**Comment by Aphelion09** [comment]
Tried binding to another port?

**Comment by verosf98** [comment]
I have tried with different ports and it still does not work.

**Comment by Aphelion09** [comment]
Looks like a permission problem, I had a similar problems back then. Do you have root privileges?

**Comment by verosf98** [comment]
I have root privileges and I have tried disconnecting the firewall temporarily, I also tried opening the port in question with a firewall rule.

**Comment by glennzw** [comment]
@Aphelion09 is spot on - it's a permission problem. You can see the error in your console output that gophish is unable to bind to port 80.

**Comment by verosf98** [comment]
and how i solve the problem?

**Comment by glennzw** [comment]
@verosf98 You need to run the tool with Administrative privileges. ie:

Press Start, type `cmd`, right click on cmd.exe and select 'Run as Administrator', then navigate to your gophish.exe file and run it.

**Comment by verosf98** [comment]
I already tried that and it didn't work either

**Comment by glennzw** [comment]
The error you're seeing indicates you're not running it with admin rights so I'd try again- feel free to share a video or screenshots
