### ISSUE TITLE
Dashboard Monitoring

### ISSUE THREAD

**Issue by kartikrajus** [gophish/gophish#255]
Hi,

I'm able to send email to targeted recipient. However, failing on the dashboard front. I'm not able to track action on the email possibly because of the wrong configuration.

Well, can you confirm if I need to configure any other application viz. web server or its inbuilt with GoPhish? Currently, I have given public IP of the server on which GoPhish is configured.

Please suggest.

**Comment by jordan-wright** [comment]
There is no other configuration needed. Just make sure that the "URL" you set when setting up a campaign is reachable from the machine that opens the email.
