### ISSUE TITLE
Feature - Add specific values related to the user in the trackings link

### ISSUE THREAD

**Issue by quentingosset** [gophish/gophish#2553]
Hello,
I would like to have the ability to add attributes on users and have this information reported if the user clicks on the phishing. 

Here is an example:
I work in a company that has several types of profiles (Developer / HR / Marketing / Accounting / Operator / ... ) we sometimes send a mass mailing to all profiles at the same time. I would like to have the possibility to add attributes on the Users for example: 

FIRSTNAME | LASTNAME | EMAIL | POSITION | TYPE
- Quentin | Gosset | email@email.com | 1 | Developer ICT
- Marie | Dupond | email@email.com | 2 | HR
- Jean | Marc | email@email.com | 3 | Operator

and when the user clicks on the link, I can know which profile has clicked on the email if it is a Developer, a Worker, a HR person. This will give me the possibility to report and to be able to target correctly the problems in my company and say "Yes the main problem is located at the HR level which often opens the phising emails".

Thanks ! :)

**Comment by glennzw** [comment]
I mean I think the easiest way to solve this is to send different campaigns to different departments? So create a campaign for HR, for Operators, for Developers. Then you can see stats per department.

If you want your sample output you could just send one big campaign, export the data to CSV, and do a cross correlation to a spreadsheet that includes Department.

HTH!

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to re-open.
