### ISSUE TITLE
Error Installing on Kali 2.0

### ISSUE THREAD

**Issue by mehranexpert** [gophish/gophish#256]
root@kali:/Desktop/git/src/github.com/gophish/gophish# go build
../../jordan-wright/email/email.go:18:2: cannot find package "mime/quotedprintable" in any of:
	/usr/lib/go/src/pkg/mime/quotedprintable (from $GOROOT)
	/Desktop/git/src/mime/quotedprintable (from $GOPATH)

**Comment by mehranexpert** [comment]
root@kali:/Desktop/git/src/github.com/gophish/gophish# go build
gophish.go:35:2: cannot find package "github.com/gophish/gophish/config" in any of:
	/usr/lib/go/src/pkg/github.com/gophish/gophish/config (from $GOROOT)
	($GOPATH not set)
gophish.go:36:2: cannot find package "github.com/gophish/gophish/controllers" in any of:
	/usr/lib/go/src/pkg/github.com/gophish/gophish/controllers (from $GOROOT)
	($GOPATH not set)
gophish.go:37:2: cannot find package "github.com/gophish/gophish/models" in any of:
	/usr/lib/go/src/pkg/github.com/gophish/gophish/models (from $GOROOT)
	($GOPATH not set)
gophish.go:38:2: cannot find package "github.com/gorilla/handlers" in any of:
	/usr/lib/go/src/pkg/github.com/gorilla/handlers (from $GOROOT)
	($GOPATH not set)

**Comment by jordan-wright** [comment]
Looks like you aren't using a version of Golang >= 1.5

**Comment by mehranexpert** [comment]
Yes Fixed  Now .
