### ISSUE TITLE
GoPhish to the outsides world

### ISSUE THREAD

**Issue by wisper1977** [gophish/gophish#2560]
So I have the server setup and have it working if it is local, meaning if the person opens it on our network. What I want is if they open it at home to be able to tell if they did. I am not sure what I need to do in the Config.JSON file.

here is my config.json

	"admin_server": {
		"listen_url": "127.0.0.1:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "gophish_admin.key"
	},
	"phish_server": {
		"listen_url": "0.0.0.0:80",
		"use_tls": false,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": "",
	"logging": {
		"filename": "",
		"level": ""
	}

Edit: So now this isn't even working. It sends the email, but the link clicked doesn't go to the landing page, or register in the campaign as being opened.

**Comment by glennzw** [comment]
Users will need to be able to access your phish_server IP. If you're running gophish internally then you may need some intermediate routers/firewalls to bounce a connection from the outside to the inside.
