### ISSUE TITLE
Questions / Issues - False Positive Clicks

### ISSUE THREAD

**Issue by jarvismgv** [gophish/gophish#2565]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.11.0

Brief description of the issue: 

After rolling out an internal phishing campaign, I found some interesting details surrounding the number of users that ended up in the "Clicked Link" results. A number of these users were recorded to have clicked on the link from a device that they do not own such as a Samsung SM-G998U and a Windows (OS Version: 10). After speaking with the users, we confirmed that they did not click on the link but instead forwarded the email with an emoji in the reply message. Testing this exact action (including the emoji in the reply message) registered a click in GoPhish. We also performed tests on what happens after a link is actually clicked and found that the click is being some times being registered multiple times from the same device. We would like to know if there are syslogs associated with how each click was recorded from the device. We would also like to know if these issues are resolved with the recent 0.12.0 release?

What are you expecting to see happen? :

We expect the number of reported "Clicked Link" results to represent the accurate location from where the click occurred (in this case the device that the user has). We are also expecting for clicks to only be registered after an actual user clicks on the link, not when the message is replied to or forwarded with an emoji. 

What are you seeing happen?

We are seeing results that indicate users clicked on the links when they in fact did not click on the link.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Deploy phishing campaign with obvious URL to click on
 * Step 2 - Review results after deployment and outline the users that clicked on the links. Outline the device type and browser versions that were recorded with the link.

**Comment by jarvismgv** [comment]
Thank you for this informatuon.

**Comment by jarvismgv** [comment]
Thank you for this information, are you able to confirm whether or not these issues exist with the latest updates from 0.12.0? Or can we expected to possibly see these issues even after we upgrade our current instance?

**Comment by glennzw** [comment]
I don't think there are any issues; this looks to be expected behaviour from a technology point of view.

But no there have been no backend changes between 0.11.0 and 0.12.0 that handle anything to do with the event handlers.

**Comment by jarvismgv** [comment]
Got it, thank you for this information.

**Comment by glennzw** [comment]
Sure no problem
