### ISSUE TITLE
IP from russia

### ISSUE THREAD

**Issue by cyberhax1** [gophish/gophish#2566]
Hello! This is not really issue related to technical support, but just curious. 
so here's the thing: I'm starting a phishing campaign for my employees, but I'm also looking at IP and geolocation. For the journalism department, one of the people showed up with an IP address from Russia, not Poland where we are located. We don't use any VPN, services from Russia or anything like that. Could it be a risk to our company that someone from Russia has infiltrated? I am also worried that the other 50 people are in Poland and the IP shows Poland, but for one person Russia (the person is in a managerial position and uses computer only in office).

**Comment by cyberhax1** [comment]
I also searched in google, found nothing useful. I think this isnt gophish bug or something, but real threat to our company

**Comment by glennzw** [comment]
Hi @cyberhax1 - that's pretty interesting, and a little worrying. Gophish is fairly simple - it will just log any hits to the endpoint (for email viewed via a tracking pixel, or user clicking a link). Sometimes it might be an appliances (e.g. email scanning software, antivirus, etc). However in your case if it's just the one user and just that one IP it is a little strange.

It *could* be the case that someone has gained access to that user's email account and clicked the link (or just viewed the email if it was a tracking pixel). Are you able to tell from your email setup where that user has been logged in from? i.e list all active and historical sessions (and you might see one in Russia). Have you analysed the IP to determine who owns it?

I guess you have a couple of options; either change that user's password (and maybe nuke and pave their devices) or send a couple more emails to try entice the Russian to click again.

I'd also suggest dropping some Canary Tokens around (https://canarytokens.org/generate), they're extremely useful for catching hackers in your network/inboxes - drop me an email if you'd like more info on these.

**Comment by cyberhax1** [comment]
> Hi @cyberhax1 - that's pretty interesting, and a little worrying. Gophish is fairly simple - it will just log any hits to the endpoint (for email viewed via a tracking pixel, or user clicking a link). Sometimes it might be an appliances (e.g. email scanning software, antivirus, etc). However in your case if it's just the one user and just that one IP it is a little strange.
> 
> It _could_ be the case that someone has gained access to that user's email account and clicked the link (or just viewed the email if it was a tracking pixel). Are you able to tell from your email setup where that user has been logged in from? i.e list all active and historical sessions (and you might see one in Russia). Have you analysed the IP to determine who owns it?
> 
> I guess you have a couple of options; either change that user's password (and maybe nuke and pave their devices) or send a couple more emails to try entice the Russian to click again.
> 
> I'd also suggest dropping some Canary Tokens around (https://canarytokens.org/generate), they're extremely useful for catching hackers in your network/inboxes - drop me an email if you'd like more info on these.

Hello! Thanks for reply!

We will check the activity, but its very, very strange, that the employee is on vacation. We use POSTFIX, and the employee has auto-reply, that he is on vacation and please contact he`s collegue collegue@mydomain.com.

The strange thing is that, in attachment tracking we saw that email was opened - 1.st from legit IP and second time (in 20 mins) from russia IP.

**Comment by cyberhax1** [comment]
> > Hi @cyberhax1 - that's pretty interesting, and a little worrying. Gophish is fairly simple - it will just log any hits to the endpoint (for email viewed via a tracking pixel, or user clicking a link). Sometimes it might be an appliances (e.g. email scanning software, antivirus, etc). However in your case if it's just the one user and just that one IP it is a little strange.
> > It _could_ be the case that someone has gained access to that user's email account and clicked the link (or just viewed the email if it was a tracking pixel). Are you able to tell from your email setup where that user has been logged in from? i.e list all active and historical sessions (and you might see one in Russia). Have you analysed the IP to determine who owns it?
> > I guess you have a couple of options; either change that user's password (and maybe nuke and pave their devices) or send a couple more emails to try entice the Russian to click again.
> > I'd also suggest dropping some Canary Tokens around (https://canarytokens.org/generate), they're extremely useful for catching hackers in your network/inboxes - drop me an email if you'd like more info on these.
> 
> Hello! Thanks for reply!
> 
> We will check the activity, but its very, very strange, that the employee is on vacation. We use POSTFIX, and the employee has auto-reply, that he is on vacation and please contact he`s collegue [collegue@mydomain.com](mailto:collegue@mydomain.com).
> 
> The strange thing is that, in attachment tracking we saw that email was opened - 1.st from legit IP and second time (in 20 mins) from russia IP.

We were thinking, that auto-reply use some Russia service, but its just not possible, because it uses POSTIFX services. And as we know, in todays war situation its impossible to travel to Russia :D So maybe, someone has infiltrated?

**Comment by cyberhax1** [comment]
> > > Hi @cyberhax1 - that's pretty interesting, and a little worrying. Gophish is fairly simple - it will just log any hits to the endpoint (for email viewed via a tracking pixel, or user clicking a link). Sometimes it might be an appliances (e.g. email scanning software, antivirus, etc). However in your case if it's just the one user and just that one IP it is a little strange.
> > > It _could_ be the case that someone has gained access to that user's email account and clicked the link (or just viewed the email if it was a tracking pixel). Are you able to tell from your email setup where that user has been logged in from? i.e list all active and historical sessions (and you might see one in Russia). Have you analysed the IP to determine who owns it?
> > > I guess you have a couple of options; either change that user's password (and maybe nuke and pave their devices) or send a couple more emails to try entice the Russian to click again.
> > > I'd also suggest dropping some Canary Tokens around (https://canarytokens.org/generate), they're extremely useful for catching hackers in your network/inboxes - drop me an email if you'd like more info on these.
> > 
> > 
> > Hello! Thanks for reply!
> > We will check the activity, but its very, very strange, that the employee is on vacation. We use POSTFIX, and the employee has auto-reply, that he is on vacation and please contact he`s collegue [collegue@mydomain.com](mailto:collegue@mydomain.com).
> > The strange thing is that, in attachment tracking we saw that email was opened - 1.st from legit IP and second time (in 20 mins) from russia IP.
> 
> We were thinking, that auto-reply use some Russia service, but its just not possible, because it uses POSTIFX services. And as we know, in todays war situation its impossible to travel to Russia :D So maybe, someone has infiltrated?

Also a little bit more info - the microsoft office versions are different

**Comment by glennzw** [comment]
Do you per chance use any Russian antivirus, that maybe scanned the attachment? e.g Kaspersky?

**Comment by cyberhax1** [comment]
> Do you per chance use any Russian antivirus, that maybe scanned the attachment? e.g Kaspersky?

No, we use avast

**Comment by cyberhax1** [comment]
Thats why its very, very strange.

**Comment by glennzw** [comment]
My only guess then is that either the user installed something on one of their devices (e.g Kaspersky), or that some third party has access to that user's device(s) or password for mailbox.

**Comment by cyberhax1** [comment]
> My only guess then is that either the user installed something on one of their devices (e.g Kaspersky), or that some third party has access to that user's device(s) or password for mailbox.

We will investigate and update you! :) Thanks for help!

**Comment by glennzw** [comment]
Closing this out - I hope your investigation yielded results!
