### ISSUE TITLE
Unable to send emails during the campaign

### ISSUE THREAD

**Issue by joseraeiro** [gophish/gophish#2568]
What version of Gophish are you using?:

0.12.0 

Brief description of the issue: 

I'm able to created a sending profile and am able to send the test email, but when using the same profile in a campaign I get an error message stating that there was an Event: Error Sending Email.
 
Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Create Sending profile
 * Step 2 - Teste Sending profile by clicking on Send Test Email
 * Step 3 - Create a Campaign using that Sending profile
 * Step 4 - Click on Launch Campaign

**Comment by glennzw** [comment]
That's very strange; and you're using the same sending profile? Could you share some more details to help us. e.g screenshots, console output.

**Comment by joseraeiro** [comment]
Never mind, I got it working using a different SMTP server. Still for further reference, could you please indicate where I can find the console output?

Thank you for your help!

**Comment by glennzw** [comment]
Console output it what you see when you run the gophish binary.

**Comment by joseraeiro** [comment]
I see! I've already checked that this stream is the log and how can I redirect it into a file (using config.json)!

Thank you very much for your help!
