### ISSUE TITLE
Missing dot in first path element

### ISSUE THREAD

**Issue by mundifitimit22** [gophish/gophish#2577]
Hello everyone,
I installed golang, also downloaded gophish, bu the problem is when i go to the directory where gophish.go is located, I type "go build" and it gives  me this error "build github.com/gophish/gophish: cannot load archive/zip: malformed module path "archive/zip": missing dot in first path element" 
Please someone help me with this.
Thanks in advance!

**Comment by glennzw** [comment]
If you're still having trouble please reopen.
