### ISSUE TITLE
Cant send a sending profile (test)

### ISSUE THREAD

**Issue by jelle500** [gophish/gophish#2579]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
v0.12.0
Brief description of the issue: 
I cant send a test mail. or the issue of: 501 5.1.7 Invalid address (with port 587) or Max connection attempts exceeded - dial tcp 52.97.211.86:25: i/o timeout
What are you expecting to see happen? :
Mail send
What are you seeing happen?
501 5.1.7 Invalid address  ---- or ---- Max connection attempts exceeded - dial tcp 52.97.211.86:25: i/o timeout
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:
time="2022-09-02T16:31:59+01:00" level=warning msg="501 5.1.7 Invalid address" code=501 email="\"Jelmer Noordam\" <jelmernoordam@live.nl>"
time="2022-09-02T16:31:59+01:00" level=error msg="501 5.1.7 Invalid address"
time="2022-09-02T16:31:59+01:00" level=info msg="127.0.0.1 - - [02/Sep/2022:16:31:58 +0100] \"POST /api/util/send_test_email HTTP/2.0\" 500 80 \"https://localhost:3333/sending_profiles\" \"Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0\""

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Login to gophish
 * Step 2 - Go to Landing page
 * Step 3 - fill in the necessary information
 * step 4 - send mail (wont work)
 
 
![illustration](https://user-images.githubusercontent.com/112715398/188188152-9f1040a3-a6ea-461b-84ea-ba34e3aa3946.png)

**Comment by glennzw** [comment]
Hi @jelle500 - could you do me a favour and try with version 0.11.0? This is the second time I've seen this issue pop up, and I wonder if it's got to do with changes between 0.11.0 and 0.12.0. (https://github.com/gophish/gophish/issues/2591)

**Comment by glennzw** [comment]
If it's still an issue with 0.11.0, you could try `userjelle@outlook.com`, without the name and angle brackets (as a test). In the Email Template you can then set the sender envelope.

However, your format should work fine. When I get some time I'll try with my Outlook account.

**Comment by MilThomas** [comment]
Hi, I have seen both issues and have it myself, I confirm that with a rollback to 0.11 the test succeded, so is related to 0.12, can I add some info to help debuging?

**Comment by glennzw** [comment]
Thanks @MilThomas - does it only fail with the Test email, but succeeds with Campaign emails?

Is it only with outlook that this happens?

**Comment by jelle500** [comment]
Sorry for the late reaction. You are completely true, version 0.11.0 works. Altough, now somehow a smtp server blocks it ;)

**Comment by Miesvanderlippe** [comment]
Probably related to this;

https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission

Please do not use your private email, please do not publish it in a Github issue lol. You'll get your 365 account banned if you use it with GoPhish.

**Comment by jelle500** [comment]
@Miesvanderlippe thanks for your advice. I will look into it.

Hahah no luckily it is just a test email ;)

**Comment by glennzw** [comment]
Hi @jelle500 - I've tested this with Outlook on my side and it works:

![Screenshot 2022-09-30 at 11 47 07](https://user-images.githubusercontent.com/3966613/193254205-940b6623-af11-433f-8c0e-762e26b828e4.png)

I see you're using port 25 - you should be using 587 AFAIK.

![Screenshot 2022-09-30 at 11 46 41](https://user-images.githubusercontent.com/3966613/193254290-be9a3396-ebc0-46be-8a63-112cc642f470.png)

Test email received:


![Screenshot 2022-09-30 at 11 47 26](https://user-images.githubusercontent.com/3966613/193254386-5dfa6df5-0f96-4695-a3c9-99e176a591c5.png)

**Comment by glennzw** [comment]
This should be fixed now with the latest code release. See https://github.com/gophish/gophish/pull/2669

**Comment by glennzw** [comment]
Haven't heard back so closing out. Feel free to reopen.
