### ISSUE TITLE
 Some Email is not been delivered to inbox or spam

### ISSUE THREAD

**Issue by mokkabca** [gophish/gophish#2582]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  0.12.0

Brief description of the issue: Some Email is not been delivered to inbox or spam

What are you expecting to see happen? : Gophish dashboard showing sent but i am not receiving any mail

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

![Untitled](https://user-images.githubusercontent.com/95523018/188382732-006ee00b-f6fa-4895-9e7b-9fae154f4a75.png)

**Comment by glennzw** [comment]
Hi @mokkabca - if the email is being marked as Send then it's being accepted by your SMTP server - there's not much more we can do from our end. You'd need to investigate your SMTP server logs.

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen.
