### ISSUE TITLE
Use PDF attachement on GoPhish

### ISSUE THREAD

**Issue by AeroVeza** [gophish/gophish#2584]
Hello all,

I just want to know if someone have alredy used PDF atachement with gophish and how you made it.

I don't find anything on web, so if you can help me, it will help me a lot.

Thanks.

**Comment by glennzw** [comment]
We don't support PDF yet, but it's on the roadmap. 

You can have a look at Canary Tokens for some PDF tracking: https://canarytokens.org/generate

(this only works for Adobe)

**Comment by AeroVeza** [comment]
Thank you for your answer.

**Comment by glennzw** [comment]
Unknown at this stage, sorry.

**Comment by glennzw** [comment]
I'll close this out - but keep an eye on releases for that PDF support!
