### ISSUE TITLE
template: template:2: function "dxLocalize

### ISSUE THREAD

**Issue by Smurfboi007** [gophish/gophish#2587]
Hi and thanks for this lovely tool! I am usingGophish v0.12.0. I'm getting this error while trying to import a page:  `template: template:2: function "dxLocalize" not defined`. The page I'm trying to import is `https://app.digiexam.com/`, I have also tried `https://app.digiexam.com/app#/login` (I have tried with and without the last `/`) this does not work and the error I said appears once I press the save page button. This is all that shows in the HTML tab:
![2022-09-06 18_20_55-Window](https://user-images.githubusercontent.com/68959201/188686365-b699f9fc-4071-43b1-831a-c49a126f6d38.png)

and this is the HTML source: https://pastebin.com/VXS24sy2

Have tried using other sites such as `https://digiexam.com/` which works like a charm. Do you know what the issue is, is there something I can do about it or any workaround? Hope you're having a good day and once again thanks so much for this amazing tool!

**Comment by glennzw** [comment]
Hi @Smurfboi007 - I'm fairly certain the problem is that there are lots of double braces (`{{` and `}}`) in that code. Gophish uses those for template variables, e.g `{{.FirstName}}`.

You'll need to go through the HTML and remove those.

**Comment by glennzw** [comment]
Hi @Smurfboi007 - the page clone tool is very much a "best effort" tool. You might have better luck using third party tools to try clone the site. We can't really offer much more help as this is now a webdev question - and that's a lot of HTML to scour.

**Comment by glennzw** [comment]
Closing out as haven't heard back, feel free to reopen.
