### ISSUE TITLE
VBScript for attachment tracking not working

### ISSUE THREAD

**Issue by grad1es** [gophish/gophish#2588]
What version of Gophish are you using?:  v 0.12.0

Brief description of the issue: when trying to run attachment tracking in a .docm file, the
"ActiveDocument.FollowHyperlink Address:=URL" in the vbscript brings a runtime error. 

What are you expecting to see happen? : being able to run macro and show that someone opened macro

What are you seeing happen? run time error

Please provide any terminal output that may be relevant below: opens the debugger and shows ActiveDocument.FollowHyperlink Address:=URL highlighted in yellow

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - created includepicture with trackingurl, textbox etc, everything exactly as it is in the attachment tracking guide in a .docm file
 * Step 2 - pasted the vba code into a macro in the document, gets runtime error and ActiveDocument.FollowHyperlink Address:=URL 
 * is highlighted in yellow

**Comment by glennzw** [comment]
Hi @grad1es - have you tried using the gophish test macro document? 

See https://docs.getgophish.com/user-guide/documentation/attachments

**Comment by glennzw** [comment]
Closing out as haven't heard back, feel free to reopen.
