### ISSUE TITLE
Forbidden - referer invalid

### ISSUE THREAD

**Issue by evanerwee** [gophish/gophish#2589]
Using the solution with AWS ALB on an EC2 instance. Is there any solution to the problem or is the solution only crafted for local desktop execution (very small scale)?

I looked at all the posting but nothing so far can take this issue away.

**Comment by glennzw** [comment]
Hi @evanerwee - we've just [rolled a fix ](https://github.com/gophish/gophish/pull/2301) for this into master, but if you're using the binaries it's not in there yet.

If you're able to download and compile the source you'll be good to go.

**Comment by evanerwee** [comment]
When I tru to build on Linux, Ubuntu 22.
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3SelectNew’:
sqlite3-binding.c:128049:10: warning: function may return address of local variable [-Wreturn-local-addr]
128049 |   return pNew;
       |          ^~~~
sqlite3-binding.c:128009:10: note: declared here
128009 |   Select standin;
       |          ^~~~~~~

**Comment by glennzw** [comment]
Which go version are you using?

**Comment by evanerwee** [comment]
(base) evanerwee@RWY740:/gophish/gophish$ go version
go version go1.18.1 linux/amd64

**Comment by evanerwee** [comment]
I build a new EC2 instance, Ubuntu.

Same Problem:

go: downloading github.com/emersion/go-textwrapper v0.0.0-20160606182133-d0e65e56babe
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3SelectNew’:
sqlite3-binding.c:128049:10: warning: function may return address of local variable [-Wreturn-local-addr]
128049 |   return pNew;
       |          ^~~~
sqlite3-binding.c:128009:10: note: declared here
128009 |   Select standin;
       |          ^~~~~~~
ubuntu@ip-############:/gpserver$ ls
ubuntu@ip-############:/gpserver$

**Comment by glennzw** [comment]
Can confirm I'm seeing the same on Ubuntu 22:

```
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function 'sqlite3SelectNew':
sqlite3-binding.c:128049:10: warning: function may return address of local variable [-Wreturn-local-addr]
128049 |   return pNew;
       |          ^~~~
sqlite3-binding.c:128009:10: note: declared here
128009 |   Select standin;
       |          ^~~~~~~
```

I'm investigating now. There were some changes with the upstream sqlite which have been causing problems.

**Comment by glennzw** [comment]
As per [this thread](https://github.com/mattn/go-sqlite3/issues/803) this appears to be a working solution:

`export CGO_CFLAGS="-g -O2 -Wno-return-local-addr"`

After doing that I'm able to `go install github.com/gophish/gophish@latest` and cd into the directory and `go build`

**Comment by Miesvanderlippe** [comment]
You need to add a couple of headers when running GoPhish behind a reverse proxy. Check out #2003

**Comment by Frekex** [comment]
> Hi @evanerwee - we've just [rolled a fix ](https://github.com/gophish/gophish/pull/2301) for this into master, but if you're using the binaries it's not in there yet.
> 
> 
> 
> If you're able to download and compile the source you'll be good to go.
I experienced the same issue just now trying to login into gophish
Forbidden - referer invalid

**Comment by Frekex** [comment]
I ran into the same problem just now

Forbidden - referer invalid. 

Any help? I am new here

**Comment by glennzw** [comment]
@Frekex Please open a new issue if you're still having trouble.
