### ISSUE TITLE
export of templates for the community

### ISSUE THREAD

**Issue by hheile** [gophish/gophish#259]
hello,
i've done a lot of templates and landing-pages for a lot of case-szenarios.
they completly work without contacting any external web-service, mans all the components are located at the local webserver. 

i cover the following szenarios: (completly build to the up-to-date messages from the platforms
Gmail
Facebook
Ebay
Paypal
LinkedIn
Twitter
Xing
Instagram
Office365
Dropbox
WeTransfer
different Webmail-Provider
different Webmail Logins (incl. OWA, Lotus Notes Traveller)
different Transfer-Services
different paket-distributors (DHL, UPS, whatever)
different ticket-systems (OTRS, ....)
different ssl-vpn systems (Fortinet, sonicwall, Checkpoint, Sophos)

i would like to contribute them to the project, including all grafics, icons and so on, but for now i have no comfortable possibility to export them

 i believe that regular awareness-programms will help the companys to get the people sensitive enough. 

A Word from my side: theese templates should be for awareness-programms only. they should not be used outside of educational purposes. 

if there is a way to distribute them to the project let me know. 
answer here, maybe leave an email-adress to contact you directly. 

best regards
hheile

**Comment by jszaszvari** [comment]
Just upload them to your own Git Repo and link too it.

Start a 'GoPhish Templates' repo and if they like it, They can pull it into the project.

**Comment by jordan-wright** [comment]
Agreed - for now, let's keep these in a separate repo.

I'm not a lawyer, but I can imagine issues with hosting these templates for community consumption (harming the brand, etc.). I'm not quite comfortable with accepting the risk of that until I do more research.

Thanks for the contribution though! If you do put these out on a repo, let me know!

**Comment by netstatmen** [comment]
Hi @DontFuckItUp , I'm a student seeking to explore this powerful tool, can you tell me where can I find your templates and landing-pages to experiment with? Thanks for your help
