### ISSUE TITLE
Gophish-sending profile: "not sending test email (501 5.1.7 Invalid address)"

### ISSUE THREAD

**Issue by VTH8** [gophish/gophish#2591]
What version of Gophish are you using?: gophish-v0.12.0-windows-64bit

Brief description of the issue: I have setup the sending profile properly, but when I try to have a test mail then I'm getting may errors

What are you expecting to see happen? : send test mail

What are you seeing happen? getting error "501 5.1.7 Invalid address" and not sending test mail

Please provide any terminal output that may be relevant below:
![Screenshot 2022-09-09 013023](https://user-images.githubusercontent.com/112782175/189217201-c7ecf44b-38fc-43b8-a46a-b1acf3f9f0b7.jpg)
![Screenshot 2022-09-09 013209](https://user-images.githubusercontent.com/112782175/189217256-2ef9c9f7-219d-4c5b-bc24-99dae4d2c131.jpg)

```
Insert output here
```

Plz, anyone provide solution for this....

**Comment by glennzw** [comment]
Hi @VTH8 - thanks for reaching out and sorry you're having trouble sending emails. Would you be able to try do the same test from one version back, `gophish-v0.11.0-windows-64bit` ? There were some changes between versions that may have broken things and this would help me debug this.

**Comment by VTH8** [comment]
> Hi @VTH8 - thanks for reaching out and sorry you're having trouble sending emails. Would you be able to try do the same test from one version back, `gophish-v0.11.0-windows-64bit` ? There were some changes between versions that may have broken things and this would help me debug this.

Thank for gueding, Let me try with  gophish-v0.11.0-windows-64bit , If there will be else, then i will get to put here

**Comment by glennzw** [comment]
So it turns out the problem is to do with our migration to support Sender Envelopes. Basically your 'SMTP From' needs to adhere to RFC 5321 and the allowed format. See https://github.com/gophish/gophish/issues/2624 for a discussion.

The solution is to change your 'SMTP From' field above to be `google.help@outlook.com` (and specify the Sender Envelope in the Email Template)
