### ISSUE TITLE
username and password of local host is showing invalid

### ISSUE THREAD

**Issue by pratik777777** [gophish/gophish#2594]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue: 
![Screenshot (226)](https://user-images.githubusercontent.com/113281603/189517697-c737ad8d-b7f7-43b8-aa33-37dc5b61df81.png)
Hello team i am entering your default username and password i.e admin and gophish,respectively but still it showing invalid username and password my version is v11 but i have tried to generate the id pass but it also showing invalid.
Hopefully this issue will solve early and i'm expecting that.
Thanks!

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
As per the [README.md ](https://github.com/gophish/gophish/blob/master/README.md)file:

------
After running the Gophish binary, open an Internet browser to https://localhost:3333 and login with the default username and password listed in the log output.
e.g.
```
time="2020-07-29T01:24:08Z" level=info msg="Please login with the username admin and the password 4304d5255378177d"
```

Releases of Gophish prior to v0.10.1 have a default username of `admin` and password of `gophish`.

**Comment by Narzard** [comment]
Need to run gophish.exe in command prompt. Cannot just click on the exe.

1. Open CMD.
2. CD to directory containing gophish.exe
3. Enter command:    .\gophish.exe
4. Press Enter. 

The your information will now show in the command prompt window.

**Comment by glennzw** [comment]
Closing out this issue as haven't heard back, feel free to re-open.
