### ISSUE TITLE
Customs Header not working

### ISSUE THREAD

**Issue by nickruth1** [gophish/gophish#2597]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
Current Version: v0.12

Brief description of the issue: 
When attempting to add custom headers nothing occurs when the "+ add customs header" button is pressed.

What are you expecting to see happen? :
I'm expecting them to be accepted and shown below

What are you seeing happen?
Nothing 

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - go to new sending profile
 * Step 2 - fill correct information
 * Step 3 - enter custom headers and press the red button
 * Step 4 - Nothing happens
 
![image](https://user-images.githubusercontent.com/90261358/189726102-9e5bf996-8b68-4544-a901-7dcd24487c9f.png)

**Comment by glennzw** [comment]
Hi there - this is a known issue - you'll need to build from source for now, or use v0.11.0. 

Apologies for the inconvenience.

**Comment by glennzw** [comment]
This is resolved in the latest v0.12.1, you can download it [here](https://github.com/gophish/gophish/releases/tag/v0.12.1)
