### ISSUE TITLE
Add ApplySecurityHeaders in Phishing Server

### ISSUE THREAD

**Issue by mahamb** [gophish/gophish#2598]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.12.0

Brief description of the issue: 
Good day and thank you in advance for help.
I am currently studying/looking into steps on how to add the ApplySecurityHeaders in Phishing Server (from middleware.go). I noticed that by default, ApplySecurityHeaders is enabled in Admin Server but not in Phishing Server.

[Code from Gophish.go]
        adminConfig := conf.AdminConf
        adminServer := controllers.NewAdminServer(adminConfig, adminOptions...)
        middleware.Store.Options.Secure = adminConfig.UseTLS

        phishConfig := conf.PhishConf
        phishServer := controllers.NewPhishingServer(phishConfig)
        _<Does adding the middleware code below will enable the SecurityHeaders same as Admin Server?>_
       **middleware.Store.Options.Secure = phishConfig.UseTLS**

[Code from Middleware.go]
// ApplySecurityHeaders applies various security headers according to best-
// practices.
func ApplySecurityHeaders(next http.Handler) http.HandlerFunc {
        return func(w http.ResponseWriter, r *http.Request) {
                csp := "frame-ancestors 'none';"
                w.Header().Set("Content-Security-Policy", csp)
                w.Header().Set("X-Frame-Options", "DENY")
                next.ServeHTTP(w, r)
        }
}

What are you expecting to see happen? : Enable the ApplySecurityHeaders in Phishing Server and Add other custom Security Header, if possible.

What are you seeing happen?
Result of Server Response from Phishing Server:
  HTTP/1.1 404 Not Found
  Content-Type: text/plain; charset=utf-8
  Vary: Accept-Encoding
  X-Content-Type-Options: nosniff
  Date: Wed, 14 Sep 2022 03:38:17 GMT
  Content-Length: 50

Result of Server Response from Admin Server:
  HTTP/1.1 307 Temporary Redirect
  Content-Security-Policy: frame-ancestors 'none';
  Content-Type: text/html; charset=utf-8
  Location: /login?next=%2F
  Set-Cookie: _gorilla_csrf=<...............................>; Expires=Wed, 14 Sep 2022 15:25:36 GMT; Max-Age=43200; HttpOnly; Secure
  Vary: Accept-Encoding
  Vary: Cookie
  X-Frame-Options: DENY
  Date: Wed, 14 Sep 2022 03:25:36 GMT
  Content-Length: 51
  HTTP/1.1 200 OK
  Content-Security-Policy: frame-ancestors 'none';
  Set-Cookie: gophish=<...............................>=; Path=/; Expires=Mon, 19 Sep 2022 03:25:36 GMT; Max-Age=432000; HttpOnly; Secure
  Vary: Accept-Encoding
  Vary: Cookie
  X-Frame-Options: DENY
  Date: Wed, 14 Sep 2022 03:25:36 GMT
  Content-Type: text/html; charset=utf-8
  Transfer-Encoding: chunked

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```


```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
Hi @mahamb - thanks for reaching out. I assume the original developers only applied this to the admin server as that's a sensitive point of logging in, and we don't want attackers loading it in an iFrame. I don't see this threat being present for the phish server pages. What do you imagine the benefit to be here?

**Comment by mahamb** [comment]
Hi @glennzw - thank you for reply & information. As our Phish Server Landing Page may include JS in future, I am thinking to implement the HTTP Security Headers in Phish Server Pages to add some degree of privacy and integrity of our landing page which is open to public internet.
Do you have any idea or steps on how to enable the middleware.go ApplySecurityHeaders in Phish Server?

Please correct me if I am wrong, Phish Server Code is in controllers/phish.go while AdminServer code is in controllers/route.go. Not sure if I enable the **CSRF protection** in Phish Server will open security hole instead of making it more secure as intended.

Btw, is there any available Gophish Code Layout/Structure I can refer to? If there is, appreciate if you can share me the link.
Thank you very much.

**Comment by glennzw** [comment]
Unfortunately there's no documentation @mahamb - the best way to learn is just to dive into the code as you're already doing. In terms of privacy @Miesvanderlippe has a good suggestion.

Best of luck!
