### ISSUE TITLE
Gophish doesn’t want to work on aarch64

### ISSUE THREAD

**Issue by Sushi-Mampfer** [gophish/gophish#2600]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
Latest
Brief description of the issue: 
I can’t compile gophishs code.
What are you expecting to see happen? :
Compiling
What are you seeing happen?
Errors
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```

sudo go install github.com/gophish/gophish@latest# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3SelectNew’:
sqlite3-binding.c:128049:10: warning: function may return address of local variable [-Wreturn-local-addr]
128049 |   return pNew;
       |          ^~~~
sqlite3-binding.c:128009:10: note: declared here
128009 |   Select standin;
       |          ^~~~~~~

```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 have an aarch64 linux system from oracle cloud that has problems with everything because there aren't any executables for it
 * Step 2 - try to compile gophish yourself.

**Comment by glennzw** [comment]
As per [this thread](https://github.com/mattn/go-sqlite3/issues/803) this appears to be a working solution:

`export CGO_CFLAGS="-g -O2 -Wno-return-local-addr"`

After doing that I'm able to `go install github.com/gophish/gophish@latest` and cd into the directory and `go build`
