### ISSUE TITLE
Does not automatically login to the legitimate website after landing page.

### ISSUE THREAD

**Issue by roxanne-tampus** [gophish/gophish#2601]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 12

Brief description of the issue: When I try to login using my legit credentials for example facebook. After click the login button, it will just redirect to legit facebook login page.

What are you expecting to see happen? : I was expecting that after filling out the login details in the phishing server, it will automatically redirecting to legitimate website and logged in like a normal process. 

What are you seeing happen? Though the credentials are being captured and can be seen in the campaign details, the landing page after logging in just redirecting to the legitimage login page and not logging in at all.

**Comment by Mr3Jane** [comment]
@roxanne-tampus this is expected behavior. It is almost impossible to achieve what you are for, at least with Facebook for sure - their security controls will not allow this, at least not in a straightforward way

**Comment by glennzw** [comment]
@Mr3Jane is spot on as usual, the tool does not do this @roxanne-tampus. You can simply capture credentials entered.

If you want to MiTM there are other tools for this (I'd rather not mention by name, as that's not what gophish is all about).
