### ISSUE TITLE
Hardware Requirement for around  one hundred thousand users  

### ISSUE THREAD

**Issue by D3MON1198** [gophish/gophish#2602]
I am trying to set up the go phish for the around a One Hundred Thousand. will it lead to specific hardware requirement ?

**Comment by Mr3Jane** [comment]
@D3MON1198 in my experience, there are 2 main kinda "bottlenecks": software-wise is [this issue](https://github.com/gophish/gophish/issues/2527) and hardware-wise it's CPU. So, in terms of hardware, Gophish isn't really that demanding, so it doesn't require much, but there a huge "but": unless the issue mentioned above is resolved, in my experience it's almost impossible to run a campaign of this size. To be exact, the campaign will run just fine, but the performance **for users** will degrade significantly with your users visiting the page and interacting with it (there's more info in the issue discussion). I guess, you can work around that if you don't expect lots of users to be active simultaneously.

**Comment by glennzw** [comment]
Another thing to be mindful of is loading very large records into the UI, as the current datatables implementation will load all users/events/etc into the browser.

More information here: https://github.com/gophish/gophish/pull/2019

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen.
