### ISSUE TITLE
Max connection attempts exceeded - dial tcp 52.98.16.198:587: i/o timeout

### ISSUE THREAD

**Issue by EdidiongA** [gophish/gophish#2603]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: gophish-v0.12.0

Brief description of the issue: When I send a test email from sending profiles, the error "Max connection attempts exceeded - dial tcp 52.98.16.198:587: i/o timeout" is shown. Correct SMTP host and port settings were entered (smtp-mail.outlook.com:587). Outlook email was entered as sender in Sending profile

What are you expecting to see happen? : Message sent

What are you seeing happen? Test message fails to send. 

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by Miesvanderlippe** [comment]
I'm pretty sure Outlook is not going to appreciate you sending phishing mail trough their system. It will be against their TOS, even if you have an agreement with the targets. 

Having said that, you need to enable insecure logins in order to have SMTP on Outlook/GMail. 

Be warned, you will be banned the moment you do something they detect. This may or may not include the headers GoPhish always sends with e-mails.

**Comment by glennzw** [comment]
@EdidiongA Your error makes me think that a firewall or other device is blocking access to port 587.

Please try connect from the command line, with a tool like netcat, e.g:

```bash
$ nc -v smtp-mail.outlook.com 587
Connection to outlook.office365.com port 587 [tcp/submission] succeeded!
220 LO4P265CA0143.outlook.office365.com Microsoft ESMTP MAIL Service ready at Fri, 30 Sep 2022 10:51:35 +0000
```

**Comment by glennzw** [comment]
This should be fixed now with the latest code release. See https://github.com/gophish/gophish/pull/2669
