### ISSUE TITLE
Gophish no longer launches: Sqlite database probably corrupted ?

### ISSUE THREAD

**Issue by BobbyDck** [gophish/gophish#2608]
Hello,

Since a few weeks, following a reboot of my server, my Gophish does not work anymore.
When I try to launch the application, I get the following result:

_[root@ip-10-68-20-126 gophish]# ./gophish
time="2022-09-21T08:53:58Z" level=warning msg="No contact address has been configured."
time="2022-09-21T08:53:58Z" level=warning msg="Please consider adding a contact_address entry in your config.json"
goose: no migrations to run. current version: 20200730000000
time="2022-09-21T08:53:58Z" level=error msg="record not found"
time="2022-09-21T08:53:58Z" level=fatal msg="record not found"_

After some research, it seems that my database has become corrupted since trying to launch Gophish with a new database works correctly.

I tried to run the following command:
_sqlite3 gophish.db .dump | sqlite3 gophish_recover.db_ 
but the problem persists.

When I do a _PRAGRA integrity_check_ of my .db file, the result is **OK**.

I also saw another closed issue where the problem was related to the removal of the admin user. Which is unfortunately not my case.

Do you have any idea where this problem might be occurring? Do you have any ideas on how to solve it to avoid losing data from my previous campaigns?

Thank you in advance for your help

**Comment by atheriqbal** [comment]
Hi,
Can you browse your .db data in DB Browser for SQLite?

**Comment by glennzw** [comment]
If you are able to browse gophish.db via command line tools such as `sqlite` you could try to dump the db contents and import it into a fresh `gophish.db`

**Comment by BobbyDck** [comment]
Thank you both for your answers!

I have transferred my .db file to my local machine, I tried to import it into DB Browser for SQlite but I get the error "Database disk image is malformed".

Also tried to dump the db content and import into a new gophish_refresh.db but same error when i start Gophish.

**Comment by atheriqbal** [comment]
Do you get a missing index error somewhere?

**Comment by BobbyDck** [comment]
From what I saw, no :/

**Comment by BobbyDck** [comment]
I just performed the process again, importing my corrupted .db file worked well in DB Browser SQLite ! 
What do you advise me from there?

Thanks you in advance!

**Comment by BobbyDck** [comment]
Problem solved!

I don't know why my first import of my db file didn't work in DBBrowser SQLite, but I was finally able to see that the "admin" user had been deleted after all.
As mentioned in another post, this was the cause of the problem, so I added the admin user to my database and then imported it to my gophish server and the problem was resolved.

Thank you for your help!
