### ISSUE TITLE
Emails Limitations !

### ISSUE THREAD

**Issue by iivm7** [gophish/gophish#2609]
Dears, 

all things are great, configure everything perfectly :) 
unfortunately i started my campaign which included nearly 8K emails !!

 i was using Titan Mail but I exceeded the limit by the first group of users.
they mentioned to me that i should try Mailchimp platform but my account got suspended during the testing time !

is there any way that i can send this huge amount of emails without limitation ?

**Comment by iivm7** [comment]
any suggestions ?

**Comment by edermi** [comment]
Use your own mailserver

**Comment by iivm7** [comment]
How to do that ?
Is there any instructions?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by edermi** [comment]
This is out of scope of GoPhish. You'll probably find enough information online.

**Comment by iivm7** [comment]
I know it's out of gophish scope
But I will appreciate if you could provide me any videos or articles that could help me

Thanks in advance

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Miesvanderlippe** [comment]
You're probably going to have to run your own mailserver. I'm not sure you're ready for that, because it's a nightmare. The easiest route to take is probably a Docker mailserver. Some of those include pretty good defaults etc.

**Comment by glennzw** [comment]
The easiest option is to setup a postfix send only SMTP server:

https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-postfix-as-a-send-only-smtp-server-on-ubuntu-22-04

**Comment by hongsolo9** [comment]
> The easiest option is to setup a postfix send only SMTP server:
> 
> https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-postfix-as-a-send-only-smtp-server-on-ubuntu-22-04

DO does not permit outgoing smtp (port 25). They only allow incoming.

**Comment by iivm7** [comment]
@hongsolo9 
Thanks for your efforts 
but unfortunately this did not work for me .. 
if you have any good tutorials about how to set my own smtp server, i would be grateful 
i tried many ways but it seems not working

**Comment by glennzw** [comment]
@iivm7 this tutorial is probably the most straight forward one you'll find

> https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-postfix-as-a-send-only-smtp-server-on-ubuntu-22-04

**Comment by iivm7** [comment]
I did all the steps but unfortunately I'm not receiving any emails
As mentioned before it might be because of port 25 ..
is there any other way?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hongsolo9** [comment]
> I did all the steps but unfortunately I'm not receiving any emails As mentioned before it might be because of port 25 .. is there any other way? Get Outlook for iOS<https://aka.ms/o0ukef>
> […](#)

You could use Mailgun or Sendgrid. They can blast your mail but you will need to get your targets to whitelist their sending mail server ip and/or domain names.

**Comment by iivm7** [comment]
I tried all the above but they blocked me 🤣
Unfortunately, that way I'm looking for a way to create my own mail server

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by glennzw** [comment]
This is beyond the support we can offer as gophish is working fine. Best of luck with the SMTP server!
