### ISSUE TITLE
Email Sent!

### ISSUE THREAD

**Issue by mehranexpert** [gophish/gophish#261]
But not sent , i change SMTP Servers , Same Result status say Email Sent , but not Deliver

**Comment by jordan-wright** [comment]
If gophish says that the email was sent, it received a successful status code from the SMTP server. It's very likely that the SMTP server dropped the message (eg a spam filter). 

You'll want to check the SMTP server logs for details. I'm afraid there isn't anything gophish can do to fix this one.
