### ISSUE TITLE
Sponsoring / tipping GoPhish

### ISSUE THREAD

**Issue by Miesvanderlippe** [gophish/gophish#2613]
Our company is considering GoPhish for awareness campaigns. As such, longevity of the project is important. We stayed away from the project until the recent resumption of development. Have you considered taking (financial) support in one shape or the other?

**Comment by glennzw** [comment]
Hi @Miesvanderlippe - feel free to drop me an email to discuss this. We have sponsored features in the past (e.g webooks).

**Comment by glennzw** [comment]
Hi @Miesvanderlippe - I set up a github sponsor page to support my maintenance of the project:

https://github.com/sponsors/glennzw

In the longer run I'll figure out a way to add a sponsor option to the project itself (tax plumbing and all that is the tricky bit).
