### ISSUE TITLE
{   "message": "API Key not set",   "success": false,   "data": null }

### ISSUE THREAD

**Issue by ShahidAkhterSec** [gophish/gophish#2617]
In Browser , Getting Error 500 - Request says {
  "message": "API Key not set",
  "success": false,
  "data": null
} 
for Testing Sending profile.
What's the issue as i am using latest version

**Comment by ShahidAkhterSec** [comment]
1 Firefox/102.0\""
time="2022-10-04T14:55:48+05:00" level=info msg="192.168.18.2 - - [04/Oct/2022:14:55:48 +0500] \"GET /css/dist/gophish.css HTTP/2.0\" 200 52514 \"\" \"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0\""
time="2022-10-04T14:55:48+05:00" level=info msg="192.168.18.2 - - [04/Oct/2022:14:55:48 +0500] \"GET /css/dist/gophish.css HTTP/2.0\" 200 20480 \"\" \"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0\""            
time="2022-10-04T14:55:49+05:00" level=info msg="192.168.18.2 - - [04/Oct/2022:14:55:49 +0500] \"GET /sending_profiles HTTP/2.0\" 307 67 \"\" \"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0\""                   
time="2022-10-04T14:55:49+05:00" level=info msg="192.168.18.2 - - [04/Oct/2022:14:55:49 +0500] \"GET /login?next=%2Fsending_profiles HTTP/2.0\" 200 1031 \"\" \"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0\""   
time="2022-10-04T14:56:59+05:00" level=info msg="192.168.18.2 - - [04/Oct/2022:14:56:59 +0500] \"POST /api/util/send_test_email HTTP/2.0\" 401 70 \"\" \"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0\""          
time="2022-10-04T15:00:25+05:00" level=warning msg="Max connection attempts exceeded - dial tcp myip:25: i/o timeout"                                                                                                             
time="2022-10-04T15:00:25+05:00" level=error msg="Max connection attempts exceeded - dial tcp (ip):25: i/o timeout"                                                                                                               
time="2022-10-04T15:00:25+05:00" level=info msg="192.168.18.2 - - [04/Oct/2022:14:55:55 +0500] \"POST /api/util/send_test_email HTTP/2.0\" 500 129 \"https://192.168.18.2:3333/sending_profiles\" \"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0\""                                                                                                                                                                                                           
time="2022-10-04T15:00:26+05:00" level=warning msg="Max connection attempts exceeded - dial tcp 172.105.97.154:25: i/o timeout"                                                                                                             
time="2022-10-04T15:00:26+05:00" level=error msg="Max connection attempts exceeded - dial tcp 172.105.97.154:25: i/o timeout"                                                                                                               
time="2022-10-04T15:00:26+05:00" level=info msg="192.168.18.2 - - [04/Oct/2022:14:55:26 +0500] \"POST /api/util/send_test_email HTTP/2.0\" 500 129 \"https://192.168.18.2:3333/sending_profiles\" \"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0\""                                                                                                                                                                                                           
time="2022-10-04T15:00:55+05:00" level=info msg="192.168.18.2 - - [04/Oct/2022:15:00:55 +0500] \"POST /api/util/send_test_email HTTP/2.0\" 401 70 \"\" \"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0\""

**Comment by ShahidAkhterSec** [comment]
[
![api broken](https://user-images.githubusercontent.com/102585129/193794743-c13d7293-7f2a-4c1d-bf48-64b11bc0c4f9.JPG)
](url)

**Comment by atheriqbal** [comment]
Hi, 

SMTP settings are correct?

**Comment by glennzw** [comment]
Yeah @atheriqbal is spot on - it looks like the SMTP host:port pair is unreachable.
