### ISSUE TITLE
domain name not working

### ISSUE THREAD

**Issue by Waiker** [gophish/gophish#2618]
What version of Gophish are you using?: 
0.11.0

Brief description of the issue:  
no response when setting domain name in url

What are you expecting to see happen? : 
loading landing page

What are you seeing happen?
in browser - "err_connection_closed"

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```
{

        "admin_server": {

                "listen_url": "0.0.0.0:3333",

                "use_tls": true,

                "cert_path": "gophish_admin.crt",

                "key_path": "gophish_admin.key"

        },

        "phish_server": {

                "listen_url": "0.0.0.0:8081",

                "use_tls": false,

                "cert_path": "example.crt",

                "key_path": "example.key"

        },

        "db_name": "sqlite3",

        "db_path": "gophish.db",

        "migrations_prefix": "db/db_",

        "contact_address": "",

        "logging": {

                "filename": "",

                "level": ""

        }

}
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - I purchased a domain
 * Step 2 - add an A record for it with the IP address of my server GoPhish
 * Step 3 - fixed the setting in the config phish_server ->listen_url. Set the domain name, ip server address, now the value is 0.0.0.0
 * Step 4 - тo check, I put apache on this server and tried to load the page by domain name - everything is ok. (then I removed apache)
 * Step 5 - when sending letters, the link with the domain name is not loaded, but if you put the server ip, the page is loaded successfully

Thanks

**Comment by glennzw** [comment]
I can't think why this would be the case - if you can access:

https://1.1.1.1:3333

then you should be able to access:

https://yourdomain.com:3333

IFF `host yourdomain.com` resolves to `1.1.1.1` (substitute for your IP).

Gophish doesn't care about domains - it just listens on the specified port. There's not much more I can suggest, but if you email me the IP / domain I can have a look an try figure it out.

**Comment by Waiker** [comment]
@glennzw This is strange. I can access the admin panel using a domain name like https://yourdomain.com:3333

But I can't open links from the mailing list, like:
https://yourdomain.com:8080/?rid=MelfmHb

Maybe I'm misconfiguring the company?

Do I need to have an ssl certificate?

What to specify in the URL when creating a company if I do not have a certificate?
http/https ?
you must additionally specify the port (if I specified 80 in the configuration file)?

**Comment by glennzw** [comment]
Your listen URL is defined as `"listen_url": "0.0.0.0:8081"` but you say you're trying to access the phish server on port `8080`. This is probably the problem. You'll need to use `http` too, as you've set `"use_tls": false`.

**Comment by Waiker** [comment]
wrong message. I check port 8081 as per config.
Now I noticed that my browser (chrome) automatically changes the domain to https and I get an error.
There is a certificate for the admin panel and the browser downloads it successfully via https

**Comment by atheriqbal** [comment]
Did you resolve your issue?

**Comment by glennzw** [comment]
@Waiker in your `config.json` you'll need to set `"use_tls": true` in your `phish_server` section if you want to use `https`
