### ISSUE TITLE
No Problem.  Offering .ico file for Windows Desktop shortcut to the GoPhish Console URL

### ISSUE THREAD

**Issue by toddalbers** [gophish/gophish#2620]
What version of Gophish are you using?: Gophish v0.12.1

Brief description of the issue: No problems.  Just offering a .ico file that can be used on a Windows shortcut to either https://127.0.0.1:3333/ or whatever location the shortcut needs to point to.

What are you expecting to see happen? :  If you guys like the .ico file, you can include it in the download file.  I copied it from the base html page of the console (initially at https://127.0.0.1:3333) and shrunk it down and made it a little clearer.

What are you seeing happen?  Either you like the .ico or you don't.  Simply offering it if liked.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:  Not Applicable

Please provide any terminal output that may be relevant below:  Not applicable

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - No problem experienced.  Offering this .ico file.  I had to add .png as the extension to upload it.  Just change the extension to .ico.  (Correct file name: GoPhish.ico)
![GoPhish ico](https://user-images.githubusercontent.com/52428561/194642618-a67a3769-4cc6-49c5-92d4-1f3f80c834e6.png)

 * Step 2 - Steps to make it the icon on a shortcut to https://127.0.0.1:3333.
 * A - Save the .ico file somewhere on your computer that is accessible to any users that need access.  Probably in same folder you run the gophish.exe from.  Save the file with the filename GoPhish.ico.
 * B - Right click on the Windows desktop.  Select New\Shortcut.
 * C - In "Type the location of the item:" enter:  https://127.0.0.1:3333.  Click Next
 * D - In "Type a name for this shortcut:" enter:  GoPhish   Click Finish
 * E - Find the newly created icon on the Windows desktop.
 * F - Right click on the newly created icon.  Select Properties
 * G - On the Web Document tab, click on "Change Icon"
 * H - On the Change Icon windows, click Browse
 * I - Browse to where you saved the GoPhish.ico file and select that file.  Click Open.
 * J - Hit OK.  Hit OK again.
 * K - The shortcut on your desktop should have the new icon.
 
Again, just offering as an option to make the link to the console's appearance specific to GoPhish.

**Comment by glennzw** [comment]
Great thanks so much @toddalbers - nice of you to take the time to offer this.
