### ISSUE TITLE
Unable to connect to gophish server

### ISSUE THREAD

**Issue by chiragnahata** [gophish/gophish#2621]
I have configurd gophish along with listening port to 0.0.0.0:3333 but still now not reachable at the ipaddress:3333. Please help.
![image](https://user-images.githubusercontent.com/63905783/194756799-150b8391-4505-49d1-a319-1a37dea9dd18.png)
Also I opened the port in OCI

**Comment by glennzw** [comment]
Can you share the output from the gophish console an your `config.json` file please

**Comment by glennzw** [comment]
Also it looks like you're running Apache on that host on port 80, which may be causing trouble

<img width="916" alt="Screenshot 2022-10-10 at 21 42 22" src="https://user-images.githubusercontent.com/3966613/194949400-90fdd0db-9552-4916-9c51-dd4204ac4085.png">

**Comment by chiragnahata** [comment]
> In your config.json
> 
> Change 127.0.0.1:3333
> to 0.0.0.0:3333 
> So you can visit link from outside the VPS localhost

Already done

**Comment by atheriqbal** [comment]
Can you please share contents of config.json file?

**Comment by TitouanTa** [comment]
Hello, same issue here.
Can i have some help please ?

**Comment by Raigakkun** [comment]
Hello same issues.

**Comment by getsniped** [comment]
Same problem, tried to start this on oracle vps. And YES, I opened port on oracle but still can't reach admin panel either the phishing site.

**Comment by chiragnahata** [comment]
Oracle banned my vps after installing gophish server

**Comment by glennzw** [comment]
A lot of different commenters here with similar problems, but the OP's question seems to have been resolved - Oracle banned the VPS.

If anyone else has the same issue still please open a new thread and supply your gophish console output, `config.json` file, and any errors you're seeing.
