### ISSUE TITLE
[Question] Track links clicked that are not directed to the landing page

### ISSUE THREAD

**Issue by Popi443** [gophish/gophish#2622]
Hello everyone,
Is there a way to track links that are not directed to the landing page? For example, I want to track how many people clicked on a google drive download link in the emails. From what I have observed it seems like {{.Tracker}} will only track for links that are converted into {{.URL}} which are redirection to the landing page.

**Comment by atheriqbal** [comment]
So you need to track some other URL which will be like "drive.google.com ***" ? Don't think so

**Comment by Popi443** [comment]
> So you need to track some other URL which will be like "drive.google.com ***" ? Don't think so

Yea, that's what I meant. For testing, I want to host a word document on google drive or onedrive and include the download link into the email then collect the data for link click rate. If it's not possible then I will look for alternative solutions, thank you for your help.

**Comment by glennzw** [comment]
Hi @Popi443 - you can only track one link from an email, the one specified by {{.URL}}.

If you wanted to track other links you'd need to setup a separate webserver and monitor those logs.

**Comment by Popi443** [comment]
Thank you for the answer.
