### ISSUE TITLE
Campaign doesn't show if email are opened

### ISSUE THREAD

**Issue by joseraeiro** [gophish/gophish#2625]
What version of Gophish are you using?: 

http://172.16.99.13/?rid=8tlr1j3

Brief description of the issue: 

Campaign doesn't show if email are opened, although it sends correctly the emails and detects when a link is clicked.

What are you expecting to see happen? :

I was expecting to see which emails were opened.

The console doesn't show any error, except this one (that I believe is not related):

`http tls handshake error from [ip address] remote error: tls: unknown certificate`

**Comment by atheriqbal** [comment]
What is your setting in config.json? is use tls true? Which url did you give while launching the campaign?

**Comment by joseraeiro** [comment]
This is my config.json file:

`{
        "admin_server": {
                "listen_url": "0.0.0.0:443",
                "use_tls": true,
                "cert_path": "gophish_admin.crt",
                "key_path": "gophish_admin.key"
        },
        "phish_server": {
                "listen_url": "0.0.0.0:80",
                "use_tls": false,
                "cert_path": "example.crt",
                "key_path": "example.key"
        },
        "db_name": "sqlite3",
        "db_path": "gophish.db",
        "migrations_prefix": "db/db_",
        "contact_address": "",
        "logging": {
                "filename": "",
                "level": ""
        }
}`

As for the URL, I gave the IP of the machine on http.

**Comment by atheriqbal** [comment]
Is there a firewall etc. ? 
When you open the email, do you click on "Download external image .... " message?

**Comment by glennzw** [comment]
Could you confirm that you've enabled the 'Tracking' option in your Email Template settings:

![Screenshot 2022-10-13 at 10 42 21](https://user-images.githubusercontent.com/3966613/195562944-99776cb0-2025-49b8-a288-4fb343ad2494.png)

If you're able to click links fine, then I'm sure you've entered the campaign detail fine, and my next guess is that your email client is blocking loading of remote images.

To further investigate view the email source in the email client. At the bottom you'd want to see something like this:

![Screenshot 2022-10-13 at 10 48 47](https://user-images.githubusercontent.com/3966613/195564582-11738032-e4fa-4318-9bda-4b27e85df56e.png)

You can see the tracking pixel in my example `http://gophish.local/track?rid=kOS5ZMV`. You can try load that directly in your browser. If it loads, and you see an 'Email opened' event in gophish then it's your email client that's blocking remote images.

**Comment by joseraeiro** [comment]
Strange. Now it's working, but only if I open the email on Outlook. On Gmail it doesn't work. Even when I try to open the tracking pixel on my browser, which replies with "404 page not found". Please look at the attached screenshots:
![2022-10-13 11_46_43-Original message](https://user-images.githubusercontent.com/8979838/195577341-7b3b2289-c893-4b31-94d7-b689fec6c19b.png)

![2022-10-13 11_48_49-@Sassy, the sasquatch - Discord](https://user-images.githubusercontent.com/8979838/195577602-dfa92f38-512b-4d77-95d3-9e4eb5f29ac2.png)

I've also tried to use just one "=" sign in the URL but the result is the same: GoPhish doesn't detect the email as opened.

**Comment by glennzw** [comment]
The format you're seeing in GMail is called "Quoted Printable" - you can decode it with a tool like:

https://www.webatic.com/quoted-printable-convertor

Your Gmail `src=3D'http://172.16.99.13/track?rid=3DxKDk90a'` will be decoded by GMail to `src='http://172.16.99.13/track?rid=xKDk90a'`

So I suspect your problem is that GMail is blocking remote images. To change this:

https://support.google.com/mail/answer/145919?hl=en-GB&co=GENIE.Platform%3DDesktop

**Comment by joseraeiro** [comment]
It is weird because I have Gmail opening all the images on emails:

![2022-10-13 12_42_56-Settings - zeraeiro@gmail com - Gmail](https://user-images.githubusercontent.com/8979838/195587628-81167385-b510-4209-9154-b42e2989c3d8.png)

And it also doesn't ask me if I want to load any image, while looking at the message.

Although it says in the help dialog that opens clicking on Learn More (above): 

> Sometimes, senders may know whether you've opened an email that has an image. Gmail scans every message for suspicious content. If Gmail thinks that a sender or message is suspicious, images aren’t shown and you’ll be asked if you want to see the images.

Perhaps Gmail is blocking the tracking pixel?

**Comment by joseraeiro** [comment]
Thank you very much for all your help!
