### ISSUE TITLE
Alternative for training

### ISSUE THREAD

**Issue by renatodesouzabr** [gophish/gophish#2627]
Hi guys, I'm in need of an alternative for security training, after the landing page, any suggestions ?

**Comment by ThiagoCruzBr** [comment]
Hi @renatodesouzabr I didn't fully understand your question and what kind of team you wish training, but here some suggestion:

You could prepare your users to detect a phishing attack, just after some user "Submmited Data" into your "Landing Page" at Gophish. Create a Quiz or some Form to informe and gather some stats from your audience.

**Comment by glennzw** [comment]
@renatodesouzabr I quite like https://phishingquiz.withgoogle.com
