### ISSUE TITLE
Location of Gophish listener clarification?

### ISSUE THREAD

**Issue by UnkeptBroom** [gophish/gophish#2629]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
v0.11.0

Brief description of the issue: 
Would like some assistance in understanding the URL section on the Campaign table page. Whatever URL is in this section, it directs the person who clicked on the link to it, not the landing page I set up. I used a basic HTML code to make a standard username and password. I am completely new to all of this and cannot seem to get a decent summary of what this section means.

What are you expecting to see happen? :

What are you seeing happen?
If I put in amazon's URL in it, the user who clicked on the link in my phishing email gets sent there instead of my landing page. I fully understand I am misinterpreting something here, but like I said, I'm very new to this and all the Youtube tutorials I have been finding have either skimmed this section over or explained it very vaguely.

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - I setup the email template, landing page and sending profiles, along with users /groups for which emails I want it sent to.
 * Step 2 - I come to the campaign page, in the 4th row. It's asking to put in a URL. Location of gophish listener. I don't understand what this means.

**Comment by UnkeptBroom** [comment]
I get this feeling that this URL section must be linked to my HTML that I made in the Landing Page section. I've done this all on a Windows laptop. I haven't used any virtual machines or Kali Linux.

**Comment by glennzw** [comment]
The URL section needs to point to the host gophish is running on, and to the port specified in your `config.json` file.

If I'm running gophish on a server with public IP `1.2.3.4` and hostname `myphishserver.com`, and in my `config.json` I have the default `phish_server` listener of `"listen_url": "0.0.0.0:80"` then the following are valid URLs to enter for the campaign:

```
http://1.2.3.4
https://myphishserver.com
```

**Comment by UnkeptBroom** [comment]
> The URL section needs to point to the host gophish is running on, and to the port specified in your `config.json` file.
> 
> If I'm running gophish on a server with public IP `1.2.3.4` and hostname `myphishserver.com`, and in my `config.json` I have the default `phish_server` listener of `"listen_url": "0.0.0.0:80"` then the following are valid URLs to enter for the campaign:
> 
> ```
> http://1.2.3.4
> https://myphishserver.com
> ```

Your explanation has helped alot! Greatly appreciated in helping me out!

**Comment by Thiati** [comment]
![HOJe](https://github.com/gophish/gophish/assets/160087442/9d091116-361e-4d77-8fb7-c6e320f78969)

Guys I'm having trouble configuring my gophish to visualise who has opened a particular email and other operations. what do I need?

**Comment by Matease** [comment]
> The URL section needs to point to the host gophish is running on, and to the port specified in your `config.json` file.
> 
> If I'm running gophish on a server with public IP `1.2.3.4` and hostname `myphishserver.com`, and in my `config.json` I have the default `phish_server` listener of `"listen_url": "0.0.0.0:80"` then the following are valid URLs to enter for the campaign:
> 
> ```
> http://1.2.3.4
> https://myphishserver.com
> ```

How do you run Gophish on a server with this public IP?
