### ISSUE TITLE
Email open tracking not working

### ISSUE THREAD

**Issue by dbachletu** [gophish/gophish#263]
Hello - Campaign tracking is working when user clicks on a link in a message but not when email is opened.  Email open tracking is not working in Outlook even if user opens the message and chooses to download images.  

HTML of email is below

<html>
<head>
	<title></title>
</head>
<body>
<p>Hello {{.FirstName}}</p>

<p>You have a pending health insurance claim for XYZ. Please log into your&nbsp;members&nbsp;account to review the claim&nbsp;with link below.</p>

<p><a href="{{.URL}}" target="_blank">XYZ Members Portal</a></p>

<p>Thank you for using XYZ Insurance</p>

<p>Regards,</p>

<p><a href="mailto:claims@xyzinsurance.com?subject=Claims%20Inquiry">XYZ Claims</a></p>

<p>{{.Tracker}}</p>
</body>
</html>

**Comment by jordan-wright** [comment]
The email looks good. My guess is that the users email client does not show images by default, and they chose not to show images when viewing the email.

Unfortunately, there isn't much gophish can do about this.

**Comment by dbachletu** [comment]
Thanks for the response. 

This may be an outlook client issue.  If I open message in Outlook it will not track on open even if I chose to manually download images.  It seems to work OK if I open the same message in Gmail.  Unfortunately, all of our corporate clients are Outlook so we just may not be able to get this level of tracking.

**Comment by jordan-wright** [comment]
I believe you are correct. I'm afraid in this case it appears to be an Outlook configuration issue.

Thanks for the report!
