### ISSUE TITLE
When ending a test email from sending profile shows an error

### ISSUE THREAD

**Issue by asumaitpsrc** [gophish/gophish#2630]
Hello
When trying to send a test email from a new sending profile couple of times it shows those errors
if you can solve this issue I'll appreciate it.
![Image (1)](https://user-images.githubusercontent.com/116165390/196674974-42e4efdf-2370-48ca-81dc-bf7b1d09f0c1.jpeg)
![Image](https://user-images.githubusercontent.com/116165390/196674990-08e34784-d617-4256-a2e7-594615b2b25b.jpeg)
Kind regards
Abdallah Sumait

**Note**: _I'm using it for testing employees for security Awareness_

**Comment by glennzw** [comment]
It looks like you're using an invalid email address - in your sending profile please set it to someone@somewhere.com

With the latest code release this value will be checked to make sure it's of this form.
