### ISSUE TITLE
Max connection attempts exceeded - 535 5.7.8 - GMAIL

### ISSUE THREAD

**Issue by mori1209** [gophish/gophish#2632]
What version of Gophish are you using?: 
gophish-v0.12.1-linux-64bit

Brief description of the issue: 
I get the following error:

```  
Max connection attempts exceeded - 535 5.7.8 Username and Password not accepted. Learn more at 5.7.8 https://support.google.com/mail/?p=BadCredentials a2-20020a056602148200b006bc3bf6e5b5sm2200194iow.55 - gsmtp
```
In the past, to fix this problem, the option: "less secure apps" had to be enabled in the Gmail account, today it is no longer available for use:
https://support.google.com/accounts/answer/6010255?hl=en

What are you expecting to see happen? :
I expect the email I'm trying to send via gmail smtp to be sent

What are you seeing happen?
Error sending the email

Please provide any terminal output that may be relevant below:

```
2022/10/19 13:56:25 http: TLS handshake error from ip:41248: remote error: tls: unknown certificate
time="2022-10-19T13:56:30Z" level=warning msg="Max connection attempts exceeded - 535 5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials x5-20020a026f05000000b0035b3e0a3243sm2141268jab.57 - gsmtp"
time="2022-10-19T13:56:30Z" level=error msg="Max connection attempts exceeded - 535 5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials x5-20020a026f05000000b0035b3e0a3243sm2141268jab.57 - gsmtp"
time="2022-10-19T13:56:30Z" level=info msg="ip - - [19/Oct/2022:13:56:25 +0000] \"POST /api/util/send_test_email HTTP/2.0\" 500 266 \"https://ip:8081/sending_profiles\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36\""

```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Setting up "New Sending Profile"
 * Step 2 - Enter a Gmail account
 * Step 3 - Use HOST: smtp.gmail.com:587
 
 
<img width="527" alt="Screenshot_2" src="https://user-images.githubusercontent.com/63657758/196713123-5c44e90d-4982-4fb8-8b6e-41b74d753648.png">

**Comment by glennzw** [comment]
From the message it looks like your username / password are incorrect?

**Comment by glennzw** [comment]
See https://support.google.com/accounts/answer/6010255?hl=en

**Comment by PetimatRa** [comment]
I'm using an e-mail address that i created for Gophish. So, it's not that I have a third-party app using this e-mail.

**Comment by glennzw** [comment]
But you're using GMail correct?

What did the URL in your screenshot reveal?

**Comment by PetimatRa** [comment]
Yes, that's right

**Comment by glennzw** [comment]
Have you allowed less secure apps:

> Allow less secure apps: If you don't use 2-Step Verification, you might need to allow less secure apps to access your account

Have you created a per app credential set:

> Use an App Password: If you use 2-Step Verification, try signing in with an App Password

**Comment by PetimatRa** [comment]
> Have you allowed less secure apps:
> 
> > Allow less secure apps: If you don't use 2-Step Verification, you might need to allow less secure apps to access your account
> 
> Have you created a per app credential set:
> 
> > Use an App Password: If you use 2-Step Verification, try signing in with an App Password

Nope, it doesn't work for me. I've tried everithing.

**Comment by glennzw** [comment]
And what credentials are you using for the SMTP settings in gophish?

**Comment by PetimatRa** [comment]
smtp.gmail.com:587

**Comment by glennzw** [comment]
That's a host and port. Are you using the same username and password in gophish that you use to login to your GMail account?

**Comment by PetimatRa** [comment]
![Screenshot 2023-01-05 034350](https://user-images.githubusercontent.com/101638512/210772823-f94b0a9f-0e17-43b8-bb68-171603aa67ba.png)
 
here I'm using the same credentials

**Comment by PetimatRa** [comment]
> OK so you're not using the per app credential recommendation:
> 
> > Use an App Password: If you use 2-Step Verification, try signing in with an [App Password](https://support.google.com/accounts/answer/185833).
> 
> GMail often won't let third party apps (anything but the GMail web interface) log you in.

And what about outlook? Maybe that one is easier to use?

**Comment by glennzw** [comment]
I've had success with GMail using the above third party app method. I've also had success with Outlook.

**Comment by PetimatRa** [comment]
> I've had success with GMail using the above third party app method. I've also had success with Outlook.

I don't know what I'm doing wrong, but it doesn't work for me.

**Comment by glennzw** [comment]
> I don't know what I'm doing wrong, but it doesn't work for me.

You need to use an App Password https://support.google.com/accounts/answer/185833

This will give you a different username and password to use with gophish for your GMail account.

**Comment by axncavalheiro** [comment]
After that and the https://admin.google.com, security and less secure stuff, there is another place where I change it: go to https://myaccount.google.com , Security tab and there is a "Less secure app access" where you must to turn to ON.

**Comment by fernandodiasti** [comment]
Bom dia todos, acabei de encontrar a solucão para o uso de apps menos seguro, estava eu sofrendo em confs do gophish, exatamente com este problems.

Passos: 
1 - Vc deve acessar sua conta google, esta conta que irá utilizar o envio de e-mail via smtp, nela vc deve ativar o segundo fator de autenticação, e na própria tela de ativação de 2FA vc já encontra logo abaixo a opção de criar uma senha de APPS
.

2 - Então no seu app, vc usa esta senha junto da sua conta gmail para o acesso ao app e envio de mensagens.

**Comment by KevinCARCA** [comment]
I have the same problem but with Outlook :C
