### ISSUE TITLE
upgrade to version 0.12.1 issue

### ISSUE THREAD

**Issue by ITgeevoSOC** [gophish/gophish#2633]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: v.0.11.0 linux 64 bit

Brief description of the issue: We need to upgrade to version 0.12.1, but from the instructions we have copied the db from v0.11.0 to 0.12.1 but  it doesn't migrate our configuration from config.json file. Do we need to copy also the config.json file except db?

What are you expecting to see happen? : to run the latest version with our configuration and our templates/landing pages.

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
Yes if you've modified your config.json you'll need to copy that over too. I'll update the documentation to make this more clear.

**Comment by ITgeevoSOC** [comment]
Thanks for your response.

We managed to upgrade Gophish to its latest version. However, the custom email templates and the landing pages that we had created from the previous version was not migrated to the new version.

Could you please advise what can be done about this?

**Comment by glennzw** [comment]
If your custom templates aren't present then it seems like you haven't migrated the gophish database over. Can you share your `config.json` please and list the steps you took to migrate over?
