### ISSUE TITLE
API Summary doesn't show 'Email Reported' stats

### ISSUE THREAD

**Issue by ThiagoCruzBr** [gophish/gophish#2634]
What version of Gophish are you using?: 
- 0.12.0

Brief description of the issue: 
- Using gophish API client I get campaigns summary (Total, Sent, Opened and Clicked, Submitted Data) but statistics from "Email Reported" doesn't show, although it shows on GUI.

What are you expecting to see happen? :
- It was expected to retrieve all statistics from a campaigns using API client.

What are you seeing happen?
- Here is an example, using python API to get stats, where "Email reported" stats doesn't show at output
```
summary = api.campaigns.summary(campaign_id=79)
s = summary.as_dict()
s
```

Output:
```json
{'id': 79,
 'name': 'example',
 'status': 'In progress',
 'created_date': '2022-10-19T18:45:31Z',
 'send_by_date': '0001-01-01T00:00:00Z',
 'launch_date': '2022-10-19T18:44:00Z',
 'completed_date': '0001-01-01T00:00:00Z',
 'stats': {'total': 1,
  'sent': 1,
  'opened': 1,
  'clicked': 1,
  'submitted_data': 1}}
```

**Comment by glennzw** [comment]
Hi @ThiagoCruzBr - thanks for your patience with our reply. I can confirm I see the same. It looks like `email_reported` hasn't been included in the [model](https://github.com/gophish/api-client-python/blob/master/gophish/models.py#L152):

```python
class Stat(Model):
    _valid_properties = {
        'total': None,
        'sent': None,
        'opened': None,
        'clicked': None,
        'submitted_data': None,
        'error': None
    }
```

I've updated the code and the [documentation](https://docs.getgophish.com/python-api-client/campaigns) and it should work as expected now:


```python
from pprint import pprint as pp
from gophish import Gophish
api = Gophish("8188eba0c91b68f0274f960b89d66b9c1217def50f492e7ef64785b20663e73d", host="https://gophish.local:3333", verify=False)
summary = api.campaigns.summary(campaign_id=206)
s = summary.as_dict()
pp(s)
```
```
{'completed_date': '0001-01-01T00:00:00Z',
 'created_date': '2020-08-14T18:45:42.932982Z',
 'id': 206,
 'launch_date': '2020-08-14T18:45:00Z',
 'name': 'Copy of All the attachments',
 'send_by_date': '0001-01-01T00:00:00Z',
 'stats': {'clicked': 4,
           'email_reported': 1,
           'opened': 5,
           'sent': 20,
           'submitted_data': 1,
           'total': 20},
 'status': 'In progress'}
```
