### ISSUE TITLE
Variables in text file are not updated

### ISSUE THREAD

**Issue by joannahsu11** [gophish/gophish#2635]
What version of Gophish are you using?: 
0.12.1

Brief description of the issue: 
Tried to send an email with .txt file attached. When the email is opened by the receiver, all the variables in the text file remain {{.RId}}, {{.Email}}, etc.

What are you expecting to see happen? : 
Variables are updated

What are you seeing happen? 
variables remain the same

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Create a new campaign
 * Step 2 - Send an email with a text file attached to it. 
 (I used the template provided here [https://docs.getgophish.com/user-guide/documentation/attachments](url))

When the receiver opens the attachment, this is what they see

![image](https://user-images.githubusercontent.com/72953248/197459162-04fe5c8c-a41f-4062-bfc9-b48ecde95327.png)

 
 My config.json
```
{
	"admin_server": {
		"listen_url": "127.0.0.1:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "gophish_admin.key",
		"trusted_origins": []
	},
	"phish_server": {
		"listen_url": "0.0.0.0:80",
		"use_tls": false,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": "",
	"logging": {
		"filename": "",
		"level": ""
	}
}
```

**Comment by glennzw** [comment]
Hi @joannahsu11 - I hate to say it but "it works for me". Perhaps you could detail step by step what you're doing, and/or attach some screenshots or videos. Also please make sure you're using the latest version.

<img width="1190" alt="Screenshot 2022-11-30 at 10 53 11" src="https://user-images.githubusercontent.com/3966613/204778298-d42b6c4c-11c6-4e38-95ba-37b5aafff79e.png">
