### ISSUE TITLE
CSS for Landingpages / Landingpage storage directory

### ISSUE THREAD

**Issue by Aphelion09** [gophish/gophish#2638]
Heyy, this sounds like a dumb question, but is there a way to use a custom css file for a landingpage? Basically I wanna use a custom landingpage, I do have the .html file together with a .css and some image files. But I can't find the directory of the landingpages. 

Thanks :)

**Comment by glennzw** [comment]
Sure you can!

Store any custom files (css, images, js, etc) inside:

`gophish/endpoint/`

and then you can access them in your browser via:

`http://phish_server/static/`

**Comment by Aphelion09** [comment]
Thanks for the answer!

Sadly it didn't work as expected. 
First I had no endpoint folder in my main directory, so I just created one and put the files inside the folder,
when opening my phish server, with a /static/ behind it, I just get the "404 page not found" Error. 

Alright, so I tried linking the file in the landing page with .../static/style.css and it didn't work either

**Comment by glennzw** [comment]
Which version of gophish are you using? It should be as simple as:

![Screenshot 2022-12-01 at 15 52 13](https://user-images.githubusercontent.com/3966613/205098539-25a79c9e-1f95-421a-b768-071326d36e62.png)

**Comment by Aphelion09** [comment]
Oh god, found the Issue. I had to remove the Port in the URL... 

Closing the thread, thanks for you help and have a nice weekend :)
