### ISSUE TITLE
Unable to add custom X-Whatever headers to sending profiles

### ISSUE THREAD

**Issue by kpomeroy1979** [gophish/gophish#2639]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
The latest version. 0.12
 

Brief description of the issue: 
I'm not able to add any custom X-whatever headers to sending profiles in version 0.12. If I create a new sending profile, or copy an existing one and want to edit it to add new custom headers, I'm not able to save the changes. A message appears that sys "no data in table".

What are you expecting to see happen? :
To add custom X-whatever headers to sending profiles

What are you seeing happen?
Normally, I just copy my pre-existing sending profiles (amazon SES, SendGrid etc) and then customize and add new X-whatever headers. When I copy a pre-existing (known good working) sending profile, I'm not able to add any new custom X-whatever security headers. I'm also not even able to add any to the existing sending profiles (not that I would want to as they are already setup). There is a message when I copy a sending profile that says "No data available in table". 

When I upgrade to the latest version, I simply copy the gophish.db file and the config file into the latest gophish version directory. This process has worked every time. 

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Log into go phish
 * Step 2 - Click on sending profiles
 * Step 3 - Copy a pre-existing sending profile
 * Step 4 - Try and edit it to add new custom X-whatever security headers

**Comment by glennzw** [comment]
Hi @kpomeroy1979 - thanks for reaching out and sorry about the trouble with custom headers. There was an issue with v0.12 that was rectified in v0.12.1 - could you try this version and let me know if it resolves your problem?

**Comment by kpomeroy1979** [comment]
Hi Glenn.

I'll give that a shot and let you know. Thanks for getting back to me. I
should have checked to see if there was a more recent version. My bad there.

Keep up the good work with GoPhish! It's a fantastic tool!

**Comment by kpomeroy1979** [comment]
Confirmed upgrading to v 0.12.1 fixed the issue.

**Comment by glennzw** [comment]
Great! Sorry about the trouble.

**Comment by SV-ZeroOne** [comment]
Can someone please point me to the exact commit this fix was implemented? It would be greatly appreciated as I'm running evilgophish that is still on version 0.12 and has this problem and we would like to try get it fixed specifically.

**Comment by harrygeorge2893** [comment]
> Can someone please point me to the exact commit this fix was implemented? It would be greatly appreciated as I'm running evilgophish that is still on version 0.12 and has this problem and we would like to try get it fixed specifically.

have you been able to resolve this issue also facinvg the same issue currently on my evilgophish setup

**Comment by SV-ZeroOne** [comment]
> > Can someone please point me to the exact commit this fix was implemented? It would be greatly appreciated as I'm running evilgophish that is still on version 0.12 and has this problem and we would like to try get it fixed specifically.
> 
> have you been able to resolve this issue also facinvg the same issue currently on my evilgophish setup

Unfortunatly not :(
You can go highlight the issue on the actual evilgophish repo so the author bumps up the version for us hopefully.
https://github.com/fin3ss3g0d/evilgophish/issues/74

**Comment by harrygeorge2893** [comment]
> > > Can someone please point me to the exact commit this fix was implemented? It would be greatly appreciated as I'm running evilgophish that is still on version 0.12 and has this problem and we would like to try get it fixed specifically.
> > 
> > 
> > have you been able to resolve this issue also facinvg the same issue currently on my evilgophish setup
> 
> Unfortunatly not :( You can go highlight the issue on the actual evilgophish repo so the author bumps up the version for us hopefully. [fin3ss3g0d/evilgophish#74](https://github.com/fin3ss3g0d/evilgophish/issues/74)

thanks for your reply, Please do you have any idea on how i go add unsubscribe link list on my header just as shown in the image below thanks in advance for your help
![Screenshot 2023-09-11 141224](https://github.com/gophish/gophish/assets/115331787/ad46024b-3204-4c95-9c46-cd85d83a6b22)
