### ISSUE TITLE
Tracking image should return transparant pixel instead of 404

### ISSUE THREAD

**Issue by TheDauntless** [gophish/gophish#264]
Currently, the tracking image returns a 404 error. Some clients (fe Gmail) display the "missing image" icon, which is very ugly.

If gophish would return either a transparant png or a customisable image, that would be much better.

**Comment by jordan-wright** [comment]
Gophish does returns transparent pixel. Please make sure that the targets are able to reach the URL you configured when setting up the campaign.

If this still doesn't work, we'll need more information about your configuration to try and find the issue.

Thanks!
Jordan

**Comment by TheDauntless** [comment]
I thought it was a 404 because the image looked that way.

The server actually returns the following:

    HTTP/1.1 200 OK
    Date: Wed, 11 May 2016 14:02:53 GMT
    Content-Length: 0
    Content-Type: text/plain; charset=utf-8
    Connection: close

Which is then interpreted by gmail as a missing image (which makes sense). Is this a configuration error on my part? Everything else is working as expected (landing page, tracking, etc)

**Comment by jordan-wright** [comment]
That's really weird.. What's the URL youre going to? What are the logs in the terminal when you load the image?

I wonder if gmail's image caching is intercepting the request.

**Comment by TheDauntless** [comment]
The url in gmail is 
`https://ci4.googleusercontent.com/proxy/fiGKDHzc5irGBFRYlVJd64qq0eGmRMTFkrz_r75RnzHNWpGahGk0UCdw-utKl0a04q4WgasteRhfhrzlzAk1xVSU8yOa3L7pJwe_iBql_r3c164ZRkbRvQPs-EdfbKmCQwtvUQ_hao95OXRdvdNhJslADVWjNFvWPm8Cqg=s0-d-e1-ft#http://mydomain.com/track?rid=9bf1fa5c060b55ee98116af6a834864c3807c39c844144b4987ede7bf6f32f91`

If I then visit the anchor part:
http://mydomain.com/track?rid=9bf1fa5c060b55ee98116af6a834864c3807c39c844144b4987ede7bf6f32f91

The server returns a 200 as indicated before:

    HTTP/1.1 200 OK
    Date: Wed, 11 May 2016 14:02:53 GMT
    Content-Length: 0
    Content-Type: text/plain; charset=utf-8
    Connection: close

There's no error on the terminal, just the normal feedback:

    2016/05/13 10:31:01 main_private.go:23: sql/home/username/go/src/github.com/gophish/gophish/models/campaign.go:108433.668µsINSERT INTO "events" ("campaign_id","email","time","message","details") VALUES (?,?,?,?,?) [44 email@domain.com 2016-05-13 10:31:01.703452676 +0200 CEST Email Opened ]

    xxx.xxx.xxx.xxx - - [13/May/2016:10:31:01 +0200] "GET /track?rid=9bf1fa5c060b55ee98116af6a834864c3807c39c844144b4987ede7bf6f32f91 HTTP/1.1" 200 0 "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"

(I removed some sensitive information from there)

**Comment by jordan-wright** [comment]
What version of gophish are you using?

**Comment by TheDauntless** [comment]
Unfortunately, I'm apparently using a pull from March third. (I had pulled the latest version, but forgot to compile it). 

I now see this is a duplicate of #202 .

Sorry for making an issue on an outdated version. I honestly thought I had the latest version.
