### ISSUE TITLE
Clicking {{.URL}} does not show the landing page

### ISSUE THREAD

**Issue by jhexdejesus1** [gophish/gophish#2641]
Hi,

I have added the URL which is setup as the public IP where my gophish server is hosted. When I clicked on the URL, it proceeds to the gophish console instead of the Landing Page. In the tutorials, they are proceeding to the Landing page, but when I follow the steps it's proceeding to the gophish console.

I would appreciate the help and response.

**Comment by aukhan288** [comment]
please add a phishing server url (dfine in config.json file) in url in create campaign page

**Comment by Ju777** [comment]
Hi,

we have a different but close to the issue previously post here.

Here is some information about our situation :

What version of Gophish are you using?: gophish-v0.12.1-linux-64bit

Brief description of the issue: when we click on the {{.URL}} link from the fake mail, we don't get the landing page, we get the default page of the domain name provider saying something like ``this website is ready to be built, create your first html files now !``.

What are you expecting to see happen? : we expect to see the landing page

What are you seeing happen? : the domain name provider default page

Please provide any terminal output that may be relevant below:

``config.json : ``
```{
        "admin_server": {
                "listen_url": "0.0.0.0:3333",
                "use_tls": true,
                "cert_path": "votre-compte.fr.crt",
                "key_path": "votre-compte.fr.key",
                "trusted_origins": []
        },
        "phish_server": {
                "listen_url": "0.0.0.0:443",
                "use_tls": true,
                "cert_path": "votre-compte.fr.crt",
                "key_path": "votre-compte.fr.key"
        },
        "db_name": "sqlite3",
        "db_path": "gophish.db",
        "migrations_prefix": "db/db_",
        "contact_address": "",
        "logging": {
                "filename": "",
                "level": ""
        }
}```

``Our domain-name : www.votre-compte.fr``
``The URL set up in the campaign : https://www.votre-compte.fr``
![image](https://user-images.githubusercontent.com/65866062/202278148-19e830db-718a-4434-b4d4-450680b3d066.png)

Do you need more details ?

Regards,

Julien

**Comment by Ju777** [comment]
It's resolved. The error was there -> The URL set up in the campaign was : ``https://votre-compte.fr`` and should be ``https://PHISH_SERVER_IP`` .

**Comment by glennzw** [comment]
@jhexdejesus1 - there are two different IP:Host pairs to keep in mind, as defined in your `config.json`: admin_server and phish_server

You'll hit `admin_server` to setup your campaigns etc, but you need to supply the IP/host and port pair when creating a campaign to your phish_server

**Comment by glennzw** [comment]
Haven't heard back so closing out. Feel free to reopen.
