### ISSUE TITLE
Problemas na visualização de resultados da campanhas

### ISSUE THREAD

**Issue by 96737-3982** [gophish/gophish#2643]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue: 

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 - 
 
 Não esta aparecendo o resultado da campanhas.

**Comment by 96737-3982** [comment]
Qual versão do Gophish você está usando?:
v0.12.1
Breve descrição do problema:
Não está aparecendo o resultado das campanhas.

**Comment by glennzw** [comment]
Hi there - you'll need to give us some more information to go on to help you. From Google Translate it seems you're having trouble seeing Campaign Results. Can you provide:

 * Your config.json
 * The output from your gophish console
 * Other info where things are not going as expected - e.g screenshots of the campaign
