### ISSUE TITLE
Sometimes add tracking image is invalid

### ISSUE THREAD

**Issue by lypacd** [gophish/gophish#2645]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.12.1

Brief description of the issue: 
When creating an email template, if add tracking image is selected and then the saved email template is opened, it is found that the tracking image is not selected. As a result, the email cannot be traced

What are you expecting to see happen? :
If add tracking image is selected, it is the same as opening the email template again after saving the tracking Image

What are you seeing happen?
If add tracking image is selected, the tracking image is not selected after it is saved and then opened again

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
hello
```

Please provide any terminal output that may be relevant below:

```

```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - When creating an email template, select add tracking image and save the Settings
 * Step 2 - Open the mail template again and check whether add tracking image is selected

**Comment by glennzw** [comment]
Hi @lypacd - thanks for reaching out. You're right the tracking image can be a bit tricky sometimes and the UX flow maybe needs updating. Make sure you're in HTML mode and not in Source view, then it should be added. If in doubt you can always manually add the {{.Tracker}} variable to a suitable location. 

Here's a video of it working for me:

https://user-images.githubusercontent.com/3966613/204632886-85798d80-bace-4721-b3c5-4da708baee95.mov

**Comment by glennzw** [comment]
Haven't heard back so closing out. Feel free to reopen.
