### ISSUE TITLE
Email Reporting Issue using imap

### ISSUE THREAD

**Issue by aukhan288** [gophish/gophish#2648]
Reported by email as shown in this image
![image](https://user-images.githubusercontent.com/33312651/199180522-a99c255c-e8ca-4013-b2da-d105ed900f8e.png)
This configured imap which is working fine
![image](https://user-images.githubusercontent.com/33312651/199181258-946522b6-1ffd-4a3b-b526-af041c400c4d.png)

The first image is show that email reported.
The second image is show the configuration of imap setting.

The main issue is that i am facing.
My imap server is configured successfully and also email is reporting fine but i am not get data in imap server of reported emails
thanks

**Comment by glennzw** [comment]
Hi @aukhan288 - so it looks like the IMAP reporting is working as per your first image. I'm not sure what the issue is that you're facing?

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to re-open if you're still having trouble.

**Comment by AChopra02** [comment]
Hi @aukhan288 could help me how email reported is working, i have setup all the imap config but still dashbooards not updating
