### ISSUE TITLE
ssl certificate not showing any change or progress in gophish

### ISSUE THREAD

**Issue by bossmunya** [gophish/gophish#2649]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue: 

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by bossmunya** [comment]
Gophish v0.11.0
I have installed gophish on my ubuntu 20.04 Azure VPS, hosted it on my domain <rrbz.cf:80> then got an ssl certificate from certbot and installed it but my domain is still saying unsecure, dangerous
       "admin_server": {
                "listen_url": "0.0.0.0:80",
                "use_tls": true,
                "cert_path": "gophish_admin.crt",
                "key_path": "gophish_admin.key"
        },
        "phish_server": {
                "listen_url": "0.0.0.0:443",
                "use_tls": true,
                "cert_path": "rrbz.cf.crt",
                "key_path": "rrbz.cf.key"
        },
        "db_name": "sqlite3",
        "db_path": "gophish.db",
        "migrations_prefix": "db/db_",
        "contact_address": "",
        "logging": {
                "filename": "log.txt",
                "level": ""
        }
}


![invalid](https://user-images.githubusercontent.com/96220260/199932962-5e19ecb5-ebca-4345-9291-59fefd60dcb7.png)
![invalid](https://user-images.githubusercontent.com/96220260/199933103-79d8fc9b-15f7-4680-a6e1-1ae28ff85e81.png)

**Comment by glennzw** [comment]
Could you share the steps you took to create the certificate please.

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen.
