### ISSUE TITLE
Fail to capture input field data

### ISSUE THREAD

**Issue by sexD** [gophish/gophish#265]
I must say that I completely love gophish. I stumbled up on some difficulties regarding capturing input field data from landing pages. For some pages it works perfectly fine where for others it says that a user has submitted data but the "Parameter" and "Value" are left empty.

Is this a bug in the current release? Any help on this?

**Comment by jordan-wright** [comment]
When you load the landing page, can you copy/paste the HTML source? Specifically the form element? I want to see how it's structured.

**Comment by sexD** [comment]
<html lang="en-us">
<head>
</head>
<body>&nbsp;</body>
</html>
<title></title>
<meta charset="utf-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/><meta name="viewport" content="width=device-width, initial-scale=1"/><meta name="msapplication-config" content="none"/><meta name="format-detection" content="telephone=no"/>
<title></title>
<meta name="description" content="List your hotel, apartment or B&amp;B on Boooooking.com. Join us and our truly global audience. Sign up your property for free and expand your business."/><meta name="keywords" content="Reservadaftion, List, Boodafking, Guest, Revedafnue, Padfartner, Advertiadfse, Onlinadfe"/><script>
            var PageLoadTimer = { start: (new Date()).getTime() };
            (function( win ) {

                win.performance = win.performance || win.mozPerformance || win.msPerformance || win.webkitPerformance || false;

                if ( ! win.performance ) {
                    win.performance = { timing: { domLoading: +new Date() }, legacy: true };
                }

            })( this );

        </script>
<link href="https://join.booking.com/static/bootstrap/css/bootstrap.min.va20e074ff274d9a8999d4f89cad0da9c4d3fa11cv.css" rel="stylesheet" />
<link href="https://join.booking.com/static/bootstrap/css/bootstrap-theme.va20e074ff274d9a8999d4f89cad0da9c4d3fa11cv.css" rel="stylesheet" />
<link href="https://join.booking.com/static/css/base.va20e074ff274d9a8999d4f89cad0da9c4d3fa11cv.css" rel="stylesheet" />
<link href="https://join.booking.com/static/css/booking_icon_font.va20e074ff274d9a8999d4f89cad0da9c4d3fa11cv.css" rel="stylesheet" />
<link href="forms.css" rel="stylesheet" />
<link href="https://join.booking.com/static/css/media.va20e074ff274d9a8999d4f89cad0da9c4d3fa11cv.css" rel="stylesheet" type="text/css" />
<link href="https://join.booking.com/static/images/favicon.va20e074ff274d9a8999d4f89cad0da9c4d3fa11cv.ico" rel="shortcut icon" />
<form action="./post.php" class="js-signup-scroll b-form long-form signup-access  " id="add_property" method="POST"><input name="action" type="hidden" value="get_started" /> <input id="create_only" name="create_only" type="hidden" value="0" /> <input id="is_proptype_lp" name="is_proptype_lp" type="hidden" value="" /> <input name="aid" type="hidden" value="" /> <input name="label" type="hidden" value="" /> <input name="started" type="hidden" value="2016-02-08 14:51:00" />
<div class="panel-default">
<div class="alert alert-danger hidden" id="error_header">&nbsp;</div>
</div>

<div id="acco-type-help" style="display:none;">&nbsp;</div>
<label class="property-name">Full Name </label> <label class="property-name-for-group" hidden="">Property name (1 of )</label> <input class="form-control" id="name" name="name" type="text" value="" /> <label for="email_address">Your Email Address</label> <input class="form-control" id="email" name="email" type="email" value="" /> <label for="phone_number">Your Phone Number</label> <input class="form-control" id="phone_number" name="phone_number" type="phone" value="" width="30" /> <label for="contact_email">Date of Birth</label> <input class="form-control" id="date_of_birth" name="date_of_birth" type="date" value="" />
<div class="get-started-button"><input class="btn btn-primary btn-block btn-lg sign_up_cta_spaced" id="save" name="save" type="submit" value="Submit" /></div>

<div class="legal_copy">By continuing, you agree to let Boooking.com email you regarding your property registration.</div>

<div class="loading">&nbsp;</div>

<div><a class="js-continue-registering continue-registration-link" data-track-ga="proceed_registration_bottom_e_clicked"> Already started registering? Continue here. </a></div>
</form>

**Comment by jordan-wright** [comment]
Interesting - I'm surprised the form action wasn't changed when you saved the page. Did you import this via the GUI with the capture creds option checked?

The root cause is that the action attribute of the form element is not set correctly, so gophish isn't seeing the credentials as they are submitted.

**Comment by sexD** [comment]
Interesting indeed, maybe something to look into for future updates. I ran into the same issue when I scraped office 365 login page. Nothing was captured. Could you please show me the fix, i.e. How the action attribute shall be set?

**Comment by strawgate** [comment]
Hello!

I am seeing the same issue with a Windows ADFS login page -- can you help us understand what the action should look like so we can manually change the form action?

**Comment by jordan-wright** [comment]
Hey there!

Sorry for the delay. Do you have the url you used to scrape? I'd like to replicate this on my end.

Thanks!

**Comment by sexD** [comment]
Hi Jordan,

I tried with the following link and same thing occured: https://login.microsoftonline.com/

I also wonder what the best way to update gophish is? I should replace all files except database?

**Comment by Nhoty** [comment]
The same is happening with Instagram login access ....

**Comment by Gitimesid** [comment]
Hello
Maybe script that is executed at the form validation . Try deleting it.

**Comment by Nhoty** [comment]
i try to deleted all the scripts but nothing happend . Is the login form
of view-source:https://login.live.com/

2016-06-17 4:24 GMT-03:00 Gitimesid <notifications@github.com>:

**Comment by smarti09** [comment]
Has anyone received an update for this.  I really want to use Office 365 subscription login page to perform phish testing.....

**Comment by jordan-wright** [comment]
I'll check in on the o365 login page tomorrow and see what the deal is.

Sorry for the delay!

**Comment by Nhoty** [comment]
The same thing is happening with Apple Cloud ID . 

Alberto Herrera Yañez




On Sun, Jul 10, 2016 at 12:49 AM -0300, "Jordan Wright" <notifications@github.com> wrote:












I'll check in on the o365 login page tomorrow and see what the deal is.



Sorry for the delay!

**Comment by anance25** [comment]
I am also experiencing issues capturing input from my landing page scraped from https://login.microsoftonline.com using the import tool.  Is there any update to this issue?

**Comment by hpscrappy** [comment]
i am having this same issue

**Comment by jordan-wright** [comment]
So I guess it's best to provide some input on the way gophish parses a page. I look for any `<form>` elements, changing their `action` attribute to point back to gophish. Then, I'll clear out `input type=password` elements, etc. for the case of credential capturing.

Some sites are really odd in how they load up resources and submit forms. They may do a bunch of javascript validation and stuff that might break how gophish handles the form submit, or they may just pass stuff completely via JS. This is what we're seeing happen with the sites listed here in this issue.

Unfortunately, this is not something that we can fix easily in gophish. I'll keep working on improving the form capture, but in the meantime I recommend for every site that isn't working to check out the HTML source, figure out how credentials are being sent by that page, and adjust to your needs. I'm afraid there's just not an easy answer :disappointed:

**Comment by nopslider** [comment]
I'm also seeing failure to capture submitted form data, even thought the values are being sent to gophish (indicating the re-written form is good):

`POST /?rid=yborTuZ HTTP/1.1
Host: <REMOVED>
Connection: keep-alive
Content-Length: 417
Cache-Control: max-age=0
Origin: <REMOVED>
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7ONj8SdEl7HxaKPz
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Referer: <REMOVED>
Accept-Encoding: gzip, deflate
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6

------WebKitFormBoundary7ONj8SdEl7HxaKPz
Content-Disposition: form-data; name="__original_url"

https://<REMOVED>/index.php?route=account/login
------WebKitFormBoundary7ONj8SdEl7HxaKPz
Content-Disposition: form-data; name="email"

aaaa
------WebKitFormBoundary7ONj8SdEl7HxaKPz
Content-Disposition: form-data; name="password"

sssdsdsdsddsdssd
------WebKitFormBoundary7ONj8SdEl7HxaKPz--
`

**Comment by nopslider** [comment]
I think I've worked it out. Gophish only accepts application/x-www-form-urlencoded, not multipart/form-data. Change the enctype attribute if you want to capture the form.

**Comment by Kaztar** [comment]
Jordan, 
Please keep this closed if it already is.  
My solution that I found was to move the HTML <Form> element up a few levels and voila it worked.  Make sure your Form clause has all of the inputs included, and it should work (including buttons).  For O365 the sign in button is outside of the form clause and I believe that this is causing the issue.

**Comment by stretch20** [comment]
@sexD https://phps.space/questions/concealing-a-field-when-the-php-post-is-devoid-of-content
