### ISSUE TITLE
Can not access the gophish admin page from IONOS VPS

### ISSUE THREAD

**Issue by Ju777** [gophish/gophish#2658]
Hello,

we saw a similar issue but closed without fully answering, that's why we re-open the issue.

What version of Gophish are you using?:  gophish-v0.12.1-linux-64bit

Brief description of the issue: when trying to open gophish admin page from the public IP address of our IONOS VPS, we obtain a timeout message.

What are you expecting to see happen? : we expect to see the gophish login page

What are you seeing happen? : a timeout message after we entered 'https://OUR_VPS_IP:3333'

Please provide any terminal output that may be relevant below:

```
cat config.json gives the following :

{
        "admin_server": {
                "listen_url": "0.0.0.0:3333",
                "use_tls": true,
                "cert_path": "gophish_admin.crt",
                "key_path": "gophish_admin.key",
                "trusted_origins": []
        },
        "phish_server": {
                "listen_url": "0.0.0.0:8080",
                "use_tls": false,
                "cert_path": "example.crt",
                "key_path": "example.key"
        },
        "db_name": "sqlite3",
        "db_path": "gophish.db",
        "migrations_prefix": "db/db_",
        "contact_address": "",
        "logging": {
                "filename": "",
                "level": ""
        }
}

./gophish gives the following  :

time="2022-11-16T08:31:50Z" level=warning msg="No contact address has been configured."
time="2022-11-16T08:31:50Z" level=warning msg="Please consider adding a contact_address entry in your config.json"
goose: no migrations to run. current version: 20220321133237
time="2022-11-16T08:31:50Z" level=info msg="Please login with the username admin and the password 0a97e4e9b11b7063"
time="2022-11-16T08:31:50Z" level=info msg="Starting IMAP monitor manager"
time="2022-11-16T08:31:50Z" level=info msg="Starting admin server at https://0.0.0.0:3333"
time="2022-11-16T08:31:50Z" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
time="2022-11-16T08:31:50Z" level=info msg="Starting phishing server at http://0.0.0.0:8080"
time="2022-11-16T08:31:50Z" level=info msg="Starting new IMAP monitor for user admin"
```
We set up the ``8080 port`` for the phishing server because the ``80 port`` is already in use by IONOS apache server.

What are we missing ?

Regards,

Julien

**Comment by edermi** [comment]
Have you opened your firewall?

**Comment by Ju777** [comment]
Yes we have.
Allowing tcp/3333 and tcp/8080.

**Comment by Ju777** [comment]
Thanks for showing your ``config.json`` .

If we set the ``443 port``, gophish outputs a message saying that it is already in use. But for you it's working fine.

Where did you get the name of your ``cert_path`` and ``key_path`` ? We don't have any.

**Comment by beckyboop123** [comment]
Can you check if your Linux firewall is on? What distro are you using?
For CentOS I run 'sudo systemctl status firewalld'

I purchased an SSL certificate from Ionos and uploaded it to my server for those paths. That shouldn't stop you from accessing the admin portal though.

**Comment by Ju777** [comment]
The distro is Ubuntu 22.04. The firewall is ``ufw`` and inactive (the command line is ``ufw status``).

**Comment by glennzw** [comment]
The easiest way to test if your firewall is allowing traffic through (and rule out gophish) is to run another simple program on port 3333 (after stopping gophish). e.g with netcat:

Server:
```
nc -v -l 9090
```

Client (your laptop):
```
echo HELLO | nc -v 1.2.3.4 3333
```

(where `1.2.3.4` is your server's public IP)

You should see "HELLO" popup in the server netcat console if the connection was allowed through.

You could also run a tiny Python webserver on port 3333: `python -m SimpleHTTPServer 3333 ` - and try access that from your browser (http://1.2.3.4:3333)

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen.
