### ISSUE TITLE
Test emails being blocked - but by what?

### ISSUE THREAD

**Issue by beckyboop123** [gophish/gophish#2659]
What version of Gophish are you using?: 0.11.0

Brief description of the issue: Unable to send test mail to self hosted mail relay

What are you expecting to see happen? : I am hoping for the test email to be sent to my test email address
What are you seeing happen? Max connection attempts exceeded - short response: This IP [77.68.x.x] is blocked

Please provide any terminal output that may be relevant below:

```
2022/11/16 08:56:20 http: TLS handshake error from 92.232.x.x:52017: remote error: tls: unknown certificate
time="2022-11-16T08:56:21Z" level=warning msg="Max connection attempts exceeded - short response: This IP [77.68.x.x] is blocked."
time="2022-11-16T08:56:21Z" level=error msg="Max connection attempts exceeded - short response: This IP [77.68.x.x] is blocked."
time="2022-11-16T08:56:21Z" level=info msg="92.232.x.x - - [16/Nov/2022:08:56:20 +0000] \"POST /api/util/send_test_email HTTP/2.0\" 500 140 \"https://mygophishserver:3333/sending_profiles\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36\""
```

So in short, my Gophish environment is hosted on Ionos (77.68.x.x) VPS using CentOS. All was working sweetly until my chosen mail relay blocked me and I hadn't even sent out a campaign, only test emails. 
To avoid any provider blocked my again I decided to fire up a mail relay (using port 587) on my Synolgy Disktation (92.232.x.x) at my home address as I am not going to be sending out masses of mail.

I know Gophish works as I've had it working before but I cannot seem to decide where its being blocked.
The diskstations firewall is off, CentOS has its firewall off. I have added port 587 to the Ionos Incoming firewall and my home firewall has also had a rule applied.

Can anyone suggest anything? What have I overlooked?

![tempsnip](https://user-images.githubusercontent.com/74063418/202137941-a388be8d-c00a-4839-bcb4-68c0a3bdb607.png)

**Comment by glennzw** [comment]
Phew tricky one to debug @beckyboop123 - and unfortunately beyond the support we can offer as it's not a gophish issues. All providers tend to take a different approach to allowing mail relays, and often won't care if it's a legitimate authorised phishing campaign.

Best advice in my experience is to run your own server on your own infrastructure. I've had good success with send only postfix servers:

https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-postfix-as-a-send-only-smtp-server-on-ubuntu-22-04

Sorry to not be of more use!

**Comment by medicobooks** [comment]
Gophish shows emails sent successfully but on the receiving end, it shows the sender as my gmail address not the one provided initially.

**Comment by glennzw** [comment]
@medicobooks Please open a new issue
