### ISSUE TITLE
Docker image : landing page not working

### ISSUE THREAD

**Issue by phocean** [gophish/gophish#266]
Hello,

First congrats and many thanks for sharing this great work.

However, I have an issue with the landing page not running.

After I launch a campaign with a landing page and URL like http://<my public IP>, nothing listens on port 80. Of course, as a consequence, phishing links don't work.

Note that I am running Gophish from within you Dockerfile, so the issue may be link to this environment.

**Comment by jordan-wright** [comment]
Can you give a few more details about your setup, the error you get, etc?

**Comment by phocean** [comment]
It is a simple, installed from scratch Debian Jessie, no firewall, Docker 1.9.1, no error at all.
I am using your Dockerfile, and run instructions, nothing else.
Note that I am now working on the host with your binary and it works as expected (besides a few other bugs that I will report later).
So the issue is related to the docker image only.

**Comment by jordan-wright** [comment]
You may check with the author of the Docker image. The image was created by someone in the community, so it's not officially supported by the gophish team - only listed as an option :)

I'll see if I can get a name later this evening.

Thanks!

**Comment by phocean** [comment]
Ok, I see. Thanks. Feel free to close this issue.
