### ISSUE TITLE
Webhooks for Microsoft Teams

### ISSUE THREAD

**Issue by JB-1173** [gophish/gophish#2660]
What version of Gophish are you using?: 
v12.1

Brief description of the issue: 
Trying to configure a webhook to send click event data to an internal Microsoft Teams channel. I have setup the webhook in the dashboard and it pings successfully, however, I am not seeing any event data. 

Does any additional configuration need to be done in the backend to specify which events need to be sent via the webhook?

Screenshot of the successful ping to Teams:
![image](https://user-images.githubusercontent.com/118353416/202161589-d6babd2c-b70d-487a-a879-9dc4be669773.png)

Any guidance on this would be much appreciated - I haven't found much documentation to help so far.

**Comment by glennzw** [comment]
Thanks for reaching out @JB-1173. You shouldn't need to configure anything else, once the webhook is specified it'll reach out with all events. It might be a firewall issue either on outbound from your phish server or inbound on your Teams server side.

I haven't tried setting up webhooks with Teams, but I've had good success with https://www.integromat.com/ - you could possibly try that out just to ascertain the the webooks are firing. See my writeup here where I created a Telegram bot:

https://github.com/glennzw/AddTelegramBotToGophish

Hope that helps!

**Comment by JB-1173** [comment]
Hi @glennzw, 

Thanks for the response - it was very helpful. I was able to setup integromat to fire gophish events into a Teams channel using your guide.

**Comment by glennzw** [comment]
That's great, nicely done! I'll close this out.
