### ISSUE TITLE
Gmail SMTP 555 5.5.2 error when sending test emails

### ISSUE THREAD

**Issue by Knowaaaa** [gophish/gophish#2662]
What version of Gophish are you using?: 0.10.1

Brief description of the issue: SMTP Syntax Error 555 5.5.2

What are you expecting to see happen? : Test Email succeeded

What are you seeing happen? When I type in a valid email address and set up an SMTP account using gmail smtp, it fails to send and throws a 555 error. 

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

Please provide any terminal output that may be relevant below:

```
time="2022-11-16T15:08:40-05:00" level=warning msg="555 5.5.2 Syntax error. j10-20020ac874ca000000b0035d432f5ba3sm9240143qtr.17 - gsmtp" code=555 email="\"NAME REDACTED\" <EMAILREDACTIED@ourdomain.org>"
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Click send test email
 * Step 2 - error

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen.

**Comment by Calvinceshamir** [comment]
am getting this error when i run a landing test email in gophish. an using a gophish version 12.1   can someone to help me how to solve the error

555 5.5.2 Syntax error, cannot decode response. For more information, go to 5.5.2 https://support.google.com/a/answer/3221692 and review RFC 5321 5.5.2 specifications. b5-20020ac247e5000000b005101b72b1ffsm1062897lfp.117 - gsmtp

**Comment by abdelwahab-maiza** [comment]
Subject: Assistance Needed: SMTP Syntax Error

Hi Ms. @Calvinceshamir ,

I'm facing the same SMTP syntax error you mentioned dealing with before: "555 5.5.2 Syntax error, cannot decode response." Have you found a solution? Your help would be greatly appreciated.

Thanks.

**Comment by leeway0507** [comment]
If you try to set sender name and get the 555 5.5.2. error, remove the brackets(<>).

from := "John Doe <john.doe@example.com>"
to
from := "John Doe john.doe@example.com"

It works.

**Comment by kalnode** [comment]
Similar error to OP, @leeway0507 's fix worked.
Context: Cloudflare, Nuxt & [worker-mailer](https://github.com/zou-yu/worker-mailer) library

Side note: On localhost, Nuxt and [nodemailer](https://github.com/nodemailer/nodemailer) library, all else being equal (same form, gmail smtp settings & auth), this error did **_not_** occur; test mails with`from: "John Doe <email@domain.com>"` worked fine in my tests.
