### ISSUE TITLE
redirect may cause CORS issues

### ISSUE THREAD

**Issue by Caratpine** [gophish/gophish#2668]
https://github.com/gophish/gophish/blob/cec2da512890e4e5fe893aaf2a223a501408370d/controllers/phish.go#L282

If the redirect URL is not the same as the domain name of Phishing, it will cause CORS issues, so I think redirect should not be used here, and the front end should be redirected

**Comment by glennzw** [comment]
Haven't heard back so closing out. Feel free to reopen.
