### ISSUE TITLE
SMTP helo localhost

### ISSUE THREAD

**Issue by phocean** [gophish/gophish#267]
Hello,

Gophish uses this library to send e-mails:
https://github.com/jordan-wright/email

As a consequence (I quickly looked at the code), it opens SMTP connections with the hardcoded "localhost" string.

So Gophish is sending to the SMTP server:

```
helo localhost
```
Then, it shows in message sources:

```
Received: from localhost (xxx])
	by xxx
	for xxx
```

Which gets flagged by many anti-spam:

```
X-Spam-Status: No, score=4.53 ....
	...
	HELO_LOCALHOST=3.828, ...
```
See the high spam score, which is a big stopper for a real phishing campaign.
It hould be configurable or at least use os.Hostname() properly.

Note that I workaround this issue by monkey patching the binary (replacing with an hex editor all occurrences of localhost). It worked as expected, which confirms this issue.

**Comment by jordan-wright** [comment]
Hi there,

I maintain that email library. Can you open an issue there? I'll be happy to take a look and address it.

Thanks!

**Comment by phocean** [comment]
No problem, done!

**Comment by jordan-wright** [comment]
Ok, great! I'll track it there, and will close this one out.

**Comment by phocean** [comment]
Can you please fix this ?

I think it is quite major for a phishing tool...
