### ISSUE TITLE
Syntax error: Unterminated quoted string

### ISSUE THREAD

**Issue by alexUnbox** [gophish/gophish#2673]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: v0.12.1-64bit

Brief description of the issue: Not sure what's the problem, but the program is not working. I get errors when trying to execute the binary file. I'm running Ubuntu on Parallels Desktop VM, MacbookAir with M1 chip. Also tried with Kali Linux, I get the same errors.
Is the CPU architecture not compatible? I managed to run the previous version on VirtualBox (Kali Linux) from my Windows computer.

What are you expecting to see happen? : Process starting as expected

What are you seeing happen?: Error while executing the binary file.

Please provide any terminal output that may be relevant below:

```
parallels@ubuntu-linux-22-04-desktop:~/Desktop/gophish$ sudo chmod +x gophish
parallels@ubuntu-linux-22-04-desktop:~/Desktop/gophish$ ./gophish
bash: ./gophish: cannot execute binary file: Exec format error
parallels@ubuntu-linux-22-04-desktop:~/Desktop/gophish$ sudo ./gophish
./gophish: 3: Syntax error: Unterminated quoted string
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - I unzipped the archive
 * Step 2 - Executed chmod 744 on the folder
 * Step 3 - Executed chmod +x gophish
 * Step 4 - sudo ./gophish or ./gophish; they show different error messages. I couldn't find anything on the internet about fixing this.

**Comment by atheriqbal** [comment]
Did you manage to run? Let us try on Ubuntu VM...

**Comment by alexUnbox** [comment]
<img width="724" alt="Screenshot 2022-11-28 at 14 54 00" src="https://user-images.githubusercontent.com/99738256/204282738-b1f8c664-ae62-4f97-a790-287992f55d78.png">
No, is not working. 
On VirtualBox works well, just tried it today; but on Mac Parallels VM is not working.

**Comment by jordan-wright** [comment]
Out of curiosity, are you sure the "gophish" file you're executing is the binary? I'm seeing suggestions that one of two things is happening:

* You're using the binary for the wrong platform (e.g. using the Mac build for your Ubuntu VM)
* Somehow your Gophish binary isn't the binary and is something else, like a text file.

**Comment by jordan-wright** [comment]
What does `dpkg --print-architecture` show? My guess is that it's an ARM image, and the binary was built for x86 processors.

I'm not sure if we have an ARM build of Gophish yet.

**Comment by alexUnbox** [comment]
Indeed it is an ARM64 architecture, as I also specified in description that my Mac is equipped a M1 CPU :)
I was suspecting might be the compatibility issue, but wasn't sure as I didn't find anything about system requirements for gophish on the internet

**Comment by jordan-wright** [comment]
Yep! The M1 note was super helpful so I include you mentioning it.

My recommendation would be to see about using an x86 image through vbox until either we have arm builds or if you can get parallels working with an x86 image (I'm not sure it can on an M1?)

Sorry for the hassle here!

**Comment by alexUnbox** [comment]
No problem
Thanks for the support, the Virtual Box setup will do the job :)

**Comment by jordan-wright** [comment]
Whoops - typo on my end. I *appreciate* you mentioning the M1 note. Not sure why autocorrect thought I wanted to say "included". 😄 

Thanks again- we'll see about getting arm builds out soon.
