### ISSUE TITLE
gopish attachement size problem  when uploading a file above 500 ko !

### ISSUE THREAD

**Issue by sliferboy** [gophish/gophish#2678]
The size of the attachement can not be above 500 ko  ! is there a file size restriction ? or a way to modify the size if the source code and thank you !

**Comment by glennzw** [comment]
I've tested a one megabyte and ten megabyte attachment - both attach and send fine. You may need to provide us with some more information as to where you're seeing failure.

![Screenshot 2022-12-01 at 15 46 23](https://user-images.githubusercontent.com/3966613/205096928-160bdf5f-31fa-4ef8-8510-18b466919b2f.png)

**Comment by sliferboy** [comment]
the problem is not when uploading the files it works fine but if u try to save it it will not be saved !

**Comment by glennzw** [comment]
In my example above I did indeed save the template with a 10mb attachment and dispatch the campaign. Emails were received with attachments intact.

Could you please share the error you're getting.

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen.
