### ISSUE TITLE
How can I use settoolkit with gophish to add my page

### ISSUE THREAD

**Issue by livinglife33** [gophish/gophish#2685]
How can I use the set tool kit to make my websites then put it onto gophish because when I use settoolkit and ngrok my pages get flagged or have a warning sign how can I fix those two things or can I use another domain or hosting server to host my settoolkit pages ?

**Comment by glennzw** [comment]
That's unfortunately out of the scope of the support we can offer here.

Gophish will let you host templates within its framework, and you can redirect users to other sites, but there's no out of the box integration with other tools (like SET).
