### ISSUE TITLE
Adding active certificated https in all campaigns

### ISSUE THREAD

**Issue by EmilioAgger** [gophish/gophish#2686]
**What version of Gophish are you using?:** 
Version is 0.11.0

**Brief description of the issue:** 
At the moment I am using the same link (link999.com), to all my 6-8 campaigns. That means if the link "link999.com" get flagged as spam, all the other campaigns are gone, so I want to make a server that can handle 3 or more links and still be active/certificated with https, that means I can create 2-3 campaigns on one link at the same time, instead of 6-8 campaigns on one link and putting the risk down by a lot, If this is possible can you maybe help me get there

**What are you expecting to see happen? :**
That I can have several links in Gophish that can be certificated with https, when i have 3 domains active, in 3 different campaigns, at the moment I can only use the last added link in the config.json file to certificate one link and not the 3 links that are add in the config.json file, all the links have both been cerfiticated through Certbot and has been given a cert_path and key_path

**What are you seeing happen?**
Now I am only seeing one off the many links is get certificated with "https", the rest of the links are not getting certificated with https when I using them in a campaign. And all the links have been certificated through **Certbot** and **letsencrypt** 

**Please provide any terminal output that may be relevant below:**
 _"admin_server": {
                "listen_url": "0.0.0.0:3333",
                "use_tls": true,
                "cert_path": "gophish_admin.crt",
                "key_path": "gophish_admin.key"
        },
"phish_server": {
                "listen_url": "0.0.0.0:443",
                "use_tls": true,
                "cert_path": "domain1.crt",
                "key_path": "domain1.key",
                "cert_path": "domain2.crt",
                "key_path": "domain2.key",
                "cert_path": "domain3.crt",
                "key_path": "domain3.key",
        },_

**Please provide as many steps as you can to reproduce the problem:**
 **Step 1 **- Add one domain in DNS server with CNAME and with Certbot in ubuntu, 
 **Step 2 **- Rename the and relocate then in (/etc/letsencrypt/live/)
 **Step 3**- Add them in config fil, but only the last added link is certificated with https or the last on the list is getting the https in the campaigns the rest are still with http

**Comment by edermi** [comment]
This can easily be solved by using a reverse proxy.

**Comment by edermi** [comment]
I'm using nginx and it works fine. How to set this up is beyond the scope of this bug tracker though.

I've heard that caddy is quite easy to setup and use, others seem to prefer it. There have been other issues that ended in the same "use a reverse proxy" recommendation, maybe you can find something there.

**Comment by glennzw** [comment]
Caddy is super easy to setup multiple (sub)domains. Check out:

https://caddy.community/

Here's a quick sample Caddy file:

```
phishserver01.com, phishserver02.com, phishserver03.com {
        reverse_proxy localhost:8080 # Gophish listener
}
```
