### ISSUE TITLE
[OFF TOPIC / OPINION]  - Super phisy email coming through to my priority inbox

### ISSUE THREAD

**Issue by iec989** [gophish/gophish#2688]
I've just got the following email on my personal Hotmail account, and I was wondering, how it could make it through to my "priority" inbox.

Take a look:

![image](https://user-images.githubusercontent.com/11177560/205726004-ff96af41-279c-49e7-856c-c99a319b8104.png)

Can it not be more _phisy_?

Super odd email address, with words like "prime" or "account suspended", with an attachment, and even though all this, it made it through, and it is not an exception, I'm getting this kind of email on a daily basis.

Furthermore, I don't see any headers like X-mailer over there. 

What do you think was the reason for this email to make it through? Any header?

> `Received: from DB9PR01MB9464.eurprd01.prod.exchangelabs.com
>  (2603:10a6:10:360::15) by PAXPR01MB9218.eurprd01.prod.exchangelabs.com with
>  HTTPS; Mon, 5 Dec 2022 17:15:49 +0000
> Received: from AM5PR1001CA0039.EURPRD10.PROD.OUTLOOK.COM
>  (2603:10a6:206:15::16) by DB9PR01MB9464.eurprd01.prod.exchangelabs.com
>  (2603:10a6:10:360::15) with Microsoft SMTP Server (version=TLS1_2,
>  cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.5880.14; Mon, 5 Dec
>  2022 17:15:47 +0000
> Received: from VI1EUR06FT065.eop-eur06.prod.protection.outlook.com
>  (2603:10a6:206:15:cafe::d6) by AM5PR1001CA0039.outlook.office365.com
>  (2603:10a6:206:15::16) with Microsoft SMTP Server (version=TLS1_2,
>  cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.5880.14 via Frontend
>  Transport; Mon, 5 Dec 2022 17:15:47 +0000
> Authentication-Results: spf=none (sender IP is 209.85.128.176)
>  smtp.mailfrom=xoqnf.domain-price-wars.com; dkim=pass (signature was verified)
>  header.d=xoqnf-domain-price-wars-com.20210112.gappssmtp.com;dmarc=none
>  action=none header.from=xoqnf.domain-price-wars.com;
> Received-SPF: None (protection.outlook.com: xoqnf.domain-price-wars.com does
>  not designate permitted sender hosts)
> Received: from mail-yw1-f176.google.com (209.85.128.176) by
>  VI1EUR06FT065.mail.protection.outlook.com (10.13.6.76) with Microsoft SMTP
>  Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id
>  15.20.5880.14 via Frontend Transport; Mon, 5 Dec 2022 17:15:47 +0000
> X-IncomingTopHeaderMarker:
>  OriginalChecksum:1F37B11349A547306DBCC4EFFA496F9ED663C0029DE552A3429DA1206D334DA6;UpperCasedChecksum:2B9D38C25EF723215B94AF6AF889E46BBC15F66CECB117DD9DAB68350BC65FC8;SizeAsReceived:2405;Count:14
> Received: by mail-yw1-f176.google.com with SMTP id 00721157ae682-3e78d07ab4fso54796657b3.9
>         for <XXXXX@hotmail.com>; Mon, 05 Dec 2022 09:15:47 -0800 (PST)
> DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
>         d=xoqnf-domain-price-wars-com.20210112.gappssmtp.com; s=20210112;
>         h=to:subject:message-id:date:from:mime-version:from:to:cc:subject
>          :date:message-id:reply-to;
>         bh=z6w/qqRJN9tdIO1Tn0GjPAizuIdsAHEHGC5gS29TrKc=;
>         b=YPaRSwMmbxnyucoYz5XJF4pPEvkDB9dEmcCjiniVbP8oFW7HRDIUXu/u9a9Q02MdP5
>          i/fiLIENsy8aNOUs5wdfwIwFzatHDv6DKwkxcGa+fvtdt6/ROBYns35vZq0E8N6IoOil
>          cRP1zHRqCzcb97tpCBBJP+BaIs64aQybpi+vW/74nUOB5lBg8gMJEef5d9X9IPjL8s/D
>          t5YDBiWYXr7efTQ3MAgU9vVQEse5yIsrkN54wuEweqWDawD/OH89yigexKwBNuty6LH3
>          M6Tlz+1QCIwTUzYQWWv8vxSPN+Zmj3ikkvk3YYBp5xsqyAysc0BKFs6WMthNpA8x2xiv
>          +jdQ==
> X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
>         d=1e100.net; s=20210112;
>         h=to:subject:message-id:date:from:mime-version:x-gm-message-state
>          :from:to:cc:subject:date:message-id:reply-to;
>         bh=z6w/qqRJN9tdIO1Tn0GjPAizuIdsAHEHGC5gS29TrKc=;
>         b=Z8Ml860SNOV9KhbAtR7VkO9ZHPi+J21CZaye1+F9lpkRcaW0+bfBnWDbe+/FMWMoxS
>          Y+iFV1t6UqzJNixiZecrK9AR5g3ueBHFFn2O8iEuR5qWwk3sPG2sZS91EDcHt/Z1nzMK
>          8AOwcWhR3fwcmH+Jjc0NmDt+9Vsflf7ZOiQy/4LOdaoAcvbSeARlA+Bc+xX5N2HVKkOZ
>          FCEtAuRrqoIXgmHcl1jwXJ4NQQmiVwQumVDm+Zr+EZ9KUwMzkvbk9wsEqVs3y+Hr4NMa
>          uXVKN9ec5KLA6feNHRpewLcc7wEHmNABWVGv41khIuWelTLSpbla4xh6KlLctUSoDzhj
>          aOrQ==
> X-Gm-Message-State: ANoB5plOZrskup5gSzvy24+Z12cODYmsoMRVrHXCCeOO/NY/NkWeIEni
> 	BA/gseMuB/dxG7QnRZ6CgFz+bXkewG1lPewL/ZD6hQ==
> X-Google-Smtp-Source: AA0mqf4dTurbL68rGiX3MHxh887YsLQlukEb8TcFMZKAsPfcaEJXvou7lrQiFS7JT5rHSARq2LYGxaTOO/eAqVblVKg=
> X-Received: by 2002:a81:7056:0:b0:329:88ec:ba20 with SMTP id
>  l83-20020a817056000000b0032988ecba20mr13571629ywc.492.1670260546189; Mon, 05
>  Dec 2022 09:15:46 -0800 (PST)
> From: Prime Service <lwgtpkpnlp@xoqnf.domain-price-wars.com>
> Date: Mon, 5 Dec 2022 13:13:04 -0400
> Message-ID: <CA+dmQuXkFhm-TBSiYm8c6gimw2p5FwO+sdGois7cUZNOKTjraw@mail.gmail.com>
> Subject: Account Suspended #5286633 - Update needed to reactivate your account!
> To: undisclosed-recipients:;
> Content-Type: multipart/mixed; boundary="0000000000008a1a0505ef17d6d1"
> Bcc: XXXXX@hotmail.com
> X-IncomingHeaderCount: 14
> Return-Path: lwgtpkpnlp@xoqnf.domain-price-wars.com
> X-MS-Exchange-Organization-ExpirationStartTime: 05 Dec 2022 17:15:47.7139
>  (UTC)
> X-MS-Exchange-Organization-ExpirationStartTimeReason: OriginalSubmit
> X-MS-Exchange-Organization-ExpirationInterval: 1:00:00:00.0000000
> X-MS-Exchange-Organization-ExpirationIntervalReason: OriginalSubmit
> X-MS-Exchange-Organization-Network-Message-Id:
>  97235829-b22b-4409-5392-08dad6e459ff
> X-EOPAttributedMessage: 0
> X-EOPTenantAttributedMessage: 84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa:0
> X-MS-Exchange-Organization-MessageDirectionality: Incoming
> X-MS-PublicTrafficType: Email
> X-MS-TrafficTypeDiagnostic: VI1EUR06FT065:EE_|DB9PR01MB9464:EE_
> X-MS-Exchange-Organization-AuthSource:
>  VI1EUR06FT065.eop-eur06.prod.protection.outlook.com
> X-MS-Exchange-Organization-AuthAs: Anonymous
> X-MS-UserLastLogonTime: 12/5/2022 4:06:14 PM
> X-MS-Office365-Filtering-Correlation-Id: 97235829-b22b-4409-5392-08dad6e459ff
> X-MS-Exchange-EOPDirect: true
> X-Sender-IP: 209.85.128.176
> X-SID-PRA: LWGTPKPNLP@XOQNF.DOMAIN-PRICE-WARS.COM
> X-SID-Result: NONE
> X-MS-Exchange-Organization-PCL: 2
> X-MS-Exchange-Organization-SCL: 1
> X-Microsoft-Antispam: BCL:0;
> X-MS-Exchange-CrossTenant-OriginalArrivalTime: 05 Dec 2022 17:15:47.6670
>  (UTC)
> X-MS-Exchange-CrossTenant-Network-Message-Id: 97235829-b22b-4409-5392-08dad6e459ff
> X-MS-Exchange-CrossTenant-Id: 84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa
> X-MS-Exchange-CrossTenant-AuthSource:
>  VI1EUR06FT065.eop-eur06.prod.protection.outlook.com
> X-MS-Exchange-CrossTenant-AuthAs: Anonymous
> X-MS-Exchange-CrossTenant-FromEntityHeader: Internet
> X-MS-Exchange-CrossTenant-RMS-PersistedConsumerOrg:
>  00000000-0000-0000-0000-000000000000
> X-MS-Exchange-Transport-CrossTenantHeadersStamped: DB9PR01MB9464
> X-MS-Exchange-Transport-EndToEndLatency: 00:00:01.9164684
> X-MS-Exchange-Processed-By-BccFoldering: 15.20.5880.013
> X-Microsoft-Antispam-Mailbox-Delivery:
> 	abwl:0;wl:0;pcwl:0;kl:0;dwl:0;dkl:0;rwl:0;ucf:0;jmr:0;ex:0;psp:0;auth:0;dest:I;ENG:(5062000305)(90000117)(90005022)(91005020)(91035115)(5061607266)(5061608174)(9050020)(9100338)(2008001134)(2008121020)(4810004)(4910033)(8820095)(9575002)(10195002)(9320005);
> X-Message-Info:
> 	qZelhIiYnPkTIE6tPwZ57rG2DbqtB2lssGXcwuT810EAAjhSqIWzMdmvK+L4EwUqzZt0rJWeetJMm6FOWNhJP5dBR3fPeWNWeWURC9RB+JIHJN7+2rfcAgeunnr344gZBWEJAgdwjcjzKg4Ri/VmpzFbpoc2HseoBqENDat1HOHCoEAqdt38oOME3tIfIpizVYjR5QqNNzQxWouG+W2lYg==
> X-Message-Delivery: Vj0xLjE7dXM9MDtsPTA7YT0wO0Q9MTtHRD0yO1NDTD0z
> X-Microsoft-Antispam-Message-Info:
> 	=?utf-8?B?WXdPaXhSNUhkeGdEWDd2d1ArZ1JkT1RXTGVnT0YyakRxVlc5aGdOSHUzaGxT?=`

**Comment by glennzw** [comment]
Super phishy for sure. Spammers will tweak their emails until they bypass spam filters - either in reverse (starting with a spammy email and slowly removing/changing bits until it passes) or forward (start with a bland email and add spammy bits until it fails).

I suspect you were just unlucky enough to receive a "fresh" spammy email - the same one would likely go straight to your spam filter now.

But, I'm just theorising.

I'll close this out for now - best of luck fighting the spam.
