### ISSUE TITLE
Email templates and issues with attached files

### ISSUE THREAD

**Issue by phocean** [gophish/gophish#269]
After I create an e-mail template with an attached phishing file of my own, I get two sort of issues when the campaign is launched:

1. With text only content and my file attached, it sends blank emails: no text at all, only the enclosed file is there.
2. With HTML, if I check the "Add tracking image", it does not send any e-mail.

In fact, only the case of HTML + attached file without tracking image works as expected.
I don't get any error message of any kind.

**Comment by jordan-wright** [comment]
Interesting - I'll see if I can reproduce the issue.

Thanks for the report!

**Comment by jordan-wright** [comment]
Hey @phocean - I think this was fixed in a8aac75f99612eb42be2c94700b55bad8fcee50a. Can you give that a shot and let me know if it fixed the issue?
