### ISSUE TITLE
Glibc version 2.28 not found.

### ISSUE THREAD

**Issue by Frekex** [gophish/gophish#2690]
Please how can I solve the above error problem /lib/x86_64-linux-gnu/libc.so.6: version’GLIB _2.28’ not found. (Required by ./gophish)

**Comment by glennzw** [comment]
Which operating system and version are you using, and which version of gophish did you download?

You can check which version of glibc you have installed with `ldd --version ldd`

**Comment by Frekex** [comment]
I fixed it

**Comment by Frekex** [comment]
I just did an upgrade to Ubuntu 20 and it worked

**Comment by Nonymouslly-Pizzy** [comment]
Please how can I solve the above error problem /lib/x86_64-linux-gnu/libc.so.6: version’GLIB _2.28’ not found. (Required by ./gophish)
