### ISSUE TITLE
v 0.12 not installing,giving glibc error

### ISSUE THREAD

**Issue by anacarnet83** [gophish/gophish#2691]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: v 0.12

Brief description of the issue: ./gophish: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./gophish)

What are you expecting to see happen? : to install and run ./gophish

What are you seeing happen?: ERROR GLIBC 2.28 NOT FOUND

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```./gophish
Insert output here
```./gophish: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./gophish)

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
Which operating system and version are you using, and which version of gophish did you download?

You can check which version of glibc you have installed with `ldd --version ldd`

**Comment by anacarnet83** [comment]
Ubuntu 2.28--Sent from Yandex Mail for mobile06.12.2022, 10:02, "Glenn Wilkinson" ***@***.***>:
Which operating system and version are you using, and which version of gophish did you download?
You can check which version of glibc you have installed with ldd --version ldd

**Comment by anacarnet83** [comment]
Ubuntu 18--Sent from Yandex Mail for mobile06.12.2022, 10:02, "Glenn Wilkinson" ***@***.***>:
Which operating system and version are you using, and which version of gophish did you download?
You can check which version of glibc you have installed with ldd --version ldd

**Comment by atheriqbal** [comment]
Also, did you update your golang version? 
In your OS check "go version" and then "go version <path/to/the/binary>"

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen.
