### ISSUE TITLE
./gophish: 2: Syntax error: ")" unexpected

### ISSUE THREAD

**Issue by maknuspl** [gophish/gophish#2692]
Hi,

I unzip gophish, and when I run `./gophish` I have error

./gophish: 2: Syntax error: ")" unexpected

**Comment by maknuspl** [comment]
Download: gophish-v0.12.1-linux-64bit.zip

![image](https://user-images.githubusercontent.com/70414469/206148947-5d122a30-93c0-4eca-a493-c42130ffd0b1.png)

**Comment by edermi** [comment]
Your screenshot shows that you obviously downloaded the OSX build...

**Comment by maknuspl** [comment]
I don't know how I missed it. My mistake. Sorry.

**Comment by glennzw** [comment]
+1, @edermi is spot on. Closing out.
