### ISSUE TITLE
SMTP FROM domain name ".online" not working

### ISSUE THREAD

**Issue by yaryatchii** [gophish/gophish#2696]
Hi, 

when i try to create a sending profile with my domain name in .online it said : SMTP FROM invalid address mail...

Can you help me ? 

Version : LAST 0.12.1

**Comment by glennzw** [comment]
Hi @yaryatchii - thanks for reaching out for bringing this to our attention. I suspect this is related to the recent change here https://github.com/gophish/gophish/pull/2669

@troplolBE - could you weigh in please. We may need to rethink your regex and loosen it a bit. It looks like the longest TLD is 18 characters (NORTHWESTERNMUTUAL):

```bash
curl -s https://data.iana.org/TLD/tlds-alpha-by-domain.txt | awk '{ print length, $0 }' | sort -n -s -r | cut -d" " -f2- | grep -v "\-\-" | head -n 5
```

```
# Version 2022121600, Last Updated Fri Dec 16 07:07:01 2022 UTC
NORTHWESTERNMUTUAL
TRAVELERSINSURANCE
AMERICANEXPRESS
KERRYPROPERTIES
```

and your regex accepts TLDs between 2 and 5 characters.

`r, _ := regexp.Compile("^([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})$")`
https://github.com/gophish/gophish/pull/2669/files#diff-efa73697037cdfe2b9d4422172c95022d12bf608d9bfa98d24bb90e5e22243a1R107

**Comment by troplolBE** [comment]
Hey @glennzw,

We could definitely loosen up the regex. We modify it to not set any limitations at all for the TLDs.

**Comment by glennzw** [comment]
OK cool I [updated](https://github.com/gophish/gophish/commit/d2efb18ef1e35b7faa32eb97e191056f7157c4f6) the code to allow up to 18 for now.

@yaryatchii If you grab the latest codebase you won't have this problem again.

Thanks both!
