### ISSUE TITLE
Show version/build in the web interface

### ISSUE THREAD

**Issue by snori74** [gophish/gophish#270]
From the web interface I'd expect to be able to see what version of the code that I'm running on each - at the Dashboard or perhaps under "Settings".  If it's there somewhere then it's not as clear as it should be.

I'm only just getting my head around calling the API, but I don't see a call in that to get the version either

(I have two installations which I intend for "test" and "production", and it would be nice for it to be very obvious what they're running).

**Comment by jordan-wright** [comment]
Yeah, you bet. I can make that happen.

**Comment by jordan-wright** [comment]
Fixed via 33df3c38685d4419a9cba468663264dc3ca74069

**Comment by snori74** [comment]
cool!
