### ISSUE TITLE
forbidden - referer invalid

### ISSUE THREAD

**Issue by anacarnet83** [gophish/gophish#2700]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: v0.12

Brief description of the issue: Forbidden - referer invalid

What are you expecting to see happen? : dashboard page after entering my credentials

What are you seeing happen? Forbidden - referer invalid

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - sudo ./gophish
 * Step 2 - error while entering credential

**Comment by glennzw** [comment]
Please could you give some more details on your setup so we can reproduce. I'm guessing you're using a reverse proxy?

Please see https://github.com/gophish/gophish/issues/2003#issuecomment-801160614

**Comment by anacarnet83** [comment]
yes i am using a reverse proxy

**Comment by glennzw** [comment]
You'll need to give us more information to replicate your environment in order to help.
