### ISSUE TITLE
gophish: Send Test Email error -> Max connection attempts exceeded

### ISSUE THREAD

**Issue by xxxnpno** [gophish/gophish#2703]
Hey, I just downloaded gophish and I just encountered a problem ;
When I am trying to Send Test Email
![image](https://user-images.githubusercontent.com/120803617/208249881-905a860f-3885-4279-96ca-890a1d02c556.png)
![image](https://user-images.githubusercontent.com/120803617/208249902-b3a79855-d047-4077-89fe-6c528de2f5c3.png)
Here are some explainations.
Thank you

**Comment by glennzw** [comment]
From the error it looks like your username and password aren't being accepted by GMail.

Did you try follow the link in the error?

**Comment by mahmodjay** [comment]
have you fixed this>?
