### ISSUE TITLE
When setting up Sending Profile, stuck on Sending... 

### ISSUE THREAD

**Issue by artlemaks** [gophish/gophish#2704]
Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: gophish-v0.12.1-linux-64bit

Brief description of the issue: When configuring sending profile and trying to send out a test email, it gets stuck on Sending. I am using Sendgrid for SMTP relay with settings as below. Password is API key obtained from Sendgrid. Using DigitalOcean for VPS. 
![image](https://user-images.githubusercontent.com/25079150/208676705-40a15c01-5d64-44de-9202-98c26b4811bf.png)

What are you expecting to see happen? : The test email should be sent successfully. I tried setting this up on local environment and emails were sent using same settings. 

What are you seeing happen?: 
![image](https://user-images.githubusercontent.com/25079150/208676445-fe22ce7c-c0c2-44e3-8828-d926a037bc34.png)

Please provide any terminal output that may be relevant below:

time="2022-12-20T13:18:33Z" level=warning msg="Max connection attempts exceeded - dial tcp 54.228.39.88:25: i/o timeout"
time="2022-12-20T13:18:33Z" level=error msg="Max connection attempts exceeded - dial tcp 54.228.39.88:25: i/o timeout"

**Comment by glennzw** [comment]
The error `Max connection attempts exceeded - dial tcp 54.228.39.88:25: i/o timeout` tells me your gophish server is unable to communicate with your mailserver. Double check your IP and port : 54.228.39.88:25 (I'm unable to connect to this).

**Comment by glennzw** [comment]
(try port 587 - I can connect on that)
