### ISSUE TITLE
/

### ISSUE THREAD

**Issue by boouuumi** [gophish/gophish#2705]
/

**Comment by Dahmmy225** [comment]
Pls i have issues logging in as a new user what are you suggesting mate?

**Comment by glennzw** [comment]
You'll need to include a full HTML webpage - just a snippet of Javascript isn't going to render. Is the javascript above your entire page?

Editing `\static\js\src\vendor\ckeditor\plugins\preview` is not an advisable route to go down.

**Comment by Dahmmy225** [comment]
I'LL send you a 1 minute video

**Comment by boouuumi** [comment]
> You'll need to include a full HTML webpage - just a snippet of Javascript isn't going to render. Is the javascript above your entire page?
> 
> Editing `\static\js\src\vendor\ckeditor\plugins\preview` is not an advisable route to go down.

What do you mean by  "javascript above your entire page?"
Like putting the javascript in the same field witht the code for the Landing Page just above it?

**Comment by glennzw** [comment]
The code that you shared was only Javascript. You need to have HTML too.

**Comment by glennzw** [comment]
Closing out as haven't heard back, feel free to reopen.
