### ISSUE TITLE
CANT LOGIN AS NEW USER

### ISSUE THREAD

**Issue by Dahmmy225** [gophish/gophish#2706]
What version of Gophish are you using?: [gophish-v0.12.1-windows-64bit.zip](https://github.com/gophish/gophish/releases/download/v0.12.1/gophish-v0.12.1-windows-64bit.zip)

Brief description of the issue: i have my gophish installed and the service working fine but have got issues with looging in as a new user. pls can you help me out with the problem

What are you expecting to see happen? : i was expecting me to login with admin as my username and gophish as my password.

What are you seeing happen?: but whenever i login with those above credentials it keep telling me invcalid username and password pls can you help me with it needed urgently.

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - downloaded the exact gophish version zip file for my windows 
 * Step 2 - downloaded nssm and installed gophish with it using cmd prompt
 * Step 3 - started the service by running it on the "service" app on my system
 * Step 4 - went to my chrome and typed https://localhost:3333/

then it showed me this error
 
 
![gophish error](https://user-images.githubusercontent.com/120079812/209270759-a6ee1e9b-fa6b-40aa-bacb-d7dd14f7e1c8.png)

**Comment by glennzw** [comment]
After running the Gophish binary, open an Internet browser to https://localhost:3333 and login with the default username and password listed in the log output. e.g.

time="2020-07-29T01:24:08Z" level=info msg="Please login with the username admin and the password 4304d5255378177d"

(via README.md)

**Comment by Dahmmy225** [comment]
Good day Pls I don't understand what you mean by log output and I tried
l9ggig in with the datails you gave me still the same result

**Comment by glennzw** [comment]
Please share a screenshot of how you're starting gophish

**Comment by Dahmmy225** [comment]
https://user-images.githubusercontent.com/120079812/209508462-97233334-db5e-4783-9473-eb2235e2b13e.mp4

i am sending a one minute video of how i access gophish on my pc

**Comment by glennzw** [comment]
Run gophish.exe manually from the command prompt for the first time and you'll see the logs that output the password.

I'm not too familiar with Windows services, so I'm not sure where you'd see the log output there.

**Comment by Dahmmy225** [comment]
pls can you recommend anyone that can help me

**Comment by glennzw** [comment]
To see the console output from an executable file that is running as a service on Windows, you can use the following steps:

Open the Services app by typing "services.msc" into the Start menu search bar and pressing Enter.

In the Services app, locate the service that corresponds to the executable file that you want to see the output for.

Right-click on the service and select "Properties".
In the Properties window, go to the "Log On" tab.

Check the "Allow service to interact with desktop" checkbox.
Click "Apply" and then "OK".

Restart the service by right-clicking on the service and selecting "Restart".

After the service has been restarted, you should be able to see the console output when the executable file is run.

Source: ChatGPT

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen.

**Comment by Emdad05** [comment]
> What version of Gophish are you using?: [gophish-v0.12.1-windows-64bit.zip](https://github.com/gophish/gophish/releases/download/v0.12.1/gophish-v0.12.1-windows-64bit.zip)
> 
> 
> ![gophish error](https://user-images.githubusercontent.com/120079812/209270759-a6ee1e9b-fa6b-40aa-bacb-d7dd14f7e1c8.png)
root@localhost:~/gophish# sudo ./gophish                               time="2023-01-11T18:08:15Z" level=warning msg="No contact address has been configured."                                                       time="2023-01-11T18:08:15Z" level=warning msg="Please consider adding a contact_address entry in your config.json"                            goose: no migrations to run. current version: 20220321133237           time="2023-01-11T18:08:15Z" level=info msg="Please login with the 👉username admin and the password 649789bd63531faa" 👈                         time="2023-01-11T18:08:15Z" level=info msg="Starting admin server at https://127.0.0.1:3333"                                                  time="2023-01-11T18:08:15Z" level=info msg="Starting phishing server at http://0.0.0.0:4444"                                                  time="2023-01-11T18:08:15Z" level=info msg="Starting IMAP monitor manager"                                                                    time="2023-01-11T18:08:15Z" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
time="2023-01-11T18:08:15Z" level=info msg="Starting new IMAP monitor for user admin"

Password is in the terminal
