### ISSUE TITLE
Unable to Complete Install

### ISSUE THREAD

**Issue by pwelford** [gophish/gophish#2710]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
v0.12.1
Brief description of the issue: 
unable to complete install getting this **-bash: cd: go/src/github.com/gophish/gophish: No such file or directory** after running **go install github.com/gophish/gophish@latest**

What are you expecting to see happen? :
The contents of the GoPhish folder

What are you seeing happen?
Putty stating file or directory does not exist

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
To build Gophish from source, simply run 'git clone https://github.com/gophish/gophish.git' and cd into the project source directory. Then, run 'go build'. After this, you should have a binary called gophish in the current directory.

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen.
