### ISSUE TITLE
My own full website as my Landing Page

### ISSUE THREAD

**Issue by boouuumi** [gophish/gophish#2711]
Brief description of the issue: I would like to use my own page as the Landing Page. The issue is that my website is a full folder with a lot of separated files so If I choose one file for the Landing Page it comes out as plain text. So how would I go about it if I want to get my full page where would I put the rest of the folder...

What are you expecting to see happen? : My page fully showing

What are you seeing happen? The page not fully showing

**Comment by awei84** [comment]
I think you can try the Google plugin.
SingleFile is an extension that helps you to save a complete page (with CSS, images, fonts, frames, etc.) as a single HTML file.

**Comment by glennzw** [comment]
You have two options; embed all the files into one (as @awei84 says, SingleFile is great, I use it a lot) or you can save the files in the static directory on your gophish server:

`gophish/endpoint/`

and then you can access them in your browser via:

`http://phish_server/static/`

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen.
