### ISSUE TITLE
Send emails via address different from original and randomising the sender

### ISSUE THREAD

**Issue by josefhotcold** [gophish/gophish#2713]
Hey!
I'm using version 0.11.0 and I have some questions. 
The main idea is the sending emails not from original address. When you create a sending profile you have to fill the field "From" with address that matches your "Username" field. If you try to do this you will receive an error "554 5.7.1 <user@email.com>: Recipient address rejected: Sender is not same as SMTP authenticate username". 
And the next question arising from the previous one is the using regular expressions when you create a sending profile to randomise the sender (the field "From").
I'm using a custom SMTP.
Is it possible to implement these features to GoPhish?

**Comment by glennzw** [comment]
It will depend on what the SMTP server allows - but yes generally your username that you authenticate with will be the MAIL FROM value. If you upgrade to a later version of gophish you can set the Sender Envelope in your Email Templates.

Also if you run your own SMTP server (or use a different provider) you may be able to specify a different FROM.

**Comment by josefhotcold** [comment]
Thank you so much! I've updated GoPhish to the latest version and now it works! And also I've allowed the sending emails not from original address in the config file on my SMTP. I'm using iRedMail and here is an instruction how to do this https://docs.iredmail.org/errors.html#recipient-address-rejected-sender-is-not-same-as-smtp-authenticate-username .

**Comment by Ghostsarah0042** [comment]
I'm having issues please I need help

**Comment by glennzw** [comment]
@Ghostsarah0042 Please open a new issue and give a lot more detail.

**Comment by Ghostsarah0042** [comment]
i managed to set up but i'm having issues hosting pages please so one help i've trying to figure out how to run a phising attack i even had to turn on of my old laptop's into kali but i still can't figure it out how do i get results to my email or telegram

**Comment by glennzw** [comment]
@Ghostsarah0042 Please open a new issue (https://github.com/gophish/gophish/issues/new/choose) and give a lot more detail about your setup, what's not working, what you expect to be happening, etc. Please read the Documentation first: https://getgophish.com/documentation/

**Comment by Ghostsarah0042** [comment]
How can I contact you WhatsApp telegram??

**Comment by glennzw** [comment]
@Ghostsarah0042 You can't, but feel free to open a new issue to discuss the trouble you're having.
