### ISSUE TITLE
gophish

### ISSUE THREAD

**Issue by lakesideXY** [gophish/gophish#2714]
What version of Gophish are you using?: v0 .12 .1

Brief description of the issue:  Max connection attempts exceeded - dial tcp: lookup smtp@mail.com: getaddrinfow: A non-recoverable error occurred during a database lookup.

**Comment by glennzw** [comment]
This sounds like your gophish server is unable to communicate with your SMTP server.

**Comment by lakesideXY** [comment]
How can I go about this?, what’s the way out

**Comment by glennzw** [comment]
Ensure your gophish server is able to communicate with your smtp server- this may involve firewall rules, or at the least ensuring the SMTP details you are using are correct.

Please could you provide more details of your setup and what SMTP you're using.

**Comment by lakesideXY** [comment]
![0677FE5F-7903-4401-9FC3-06B1F1E363A5](https://user-images.githubusercontent.com/67004703/210585398-00054485-5664-4580-9432-90558071f4fa.jpeg)
SMTP:::: gmail

**Comment by lakesideXY** [comment]
What is my username and password on my sending profile?

**Comment by glennzw** [comment]
You'll need to share the Sending Profile details behind that Test Email screen

**Comment by lakesideXY** [comment]
![Uploading 170EB02A-D1EF-4239-9293-326541DB130C.jpeg…]()

**Comment by glennzw** [comment]
Unfortunately your screenshots didn't upload

**Comment by lakesideXY** [comment]
Name: TP
Interface Type: SMTP
SMTP From:: White Walker <gophishwalker@usa.com>
Host:  smtp.mail.com
Username: gophishwalker@usa.com
Password:: Cathode@01!

**Comment by glennzw** [comment]
You probably need to set your host to

smtp.mail.com:587

**Comment by lakesideXY** [comment]
I just did that and I got the same error message. 
![Uploading image.jpg…]()

**Comment by glennzw** [comment]
Unfortunately your screenshots are still not uploading

**Comment by lakesideXY** [comment]
This is the error message I always get anytime I send a test mail……

Max connection attempts exceeded - dial tp 142,250.138.109:25: connectex: A
connection
attempt failed because the connected party did not properly respond after a
period of time,
established connection failed because connected host has failed to respona.

**Comment by glennzw** [comment]
You're trying to connect on port 25 (see `250.138.109:25`). As mentioned above you need to connect on port 587. Change your host to `smtp.mail.com:587`

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen.

**Comment by lakesideXY** [comment]
Thanks a lot. Which version of gophish can I download to set a user account?

**Comment by lakesideXY** [comment]
This is the error message I got while trying to send a test email:::

Max connection attempts exceeded - 535 5.7.8 Username and Password not
accepted.
