### ISSUE TITLE
Login 

### ISSUE THREAD

**Issue by lakesideXY** [gophish/gophish#2716]
What version of Gophish are you using?: v0 .12 .1

Brief description of the issue: Anytime I shutdown my PC gophish won't recognize my login details if I attempt to login again. Thank you

**Comment by glennzw** [comment]
You'll need to give us a lot more information about your setup. e.g:

 * Operating system
 * Your `config.json` file
 * Your gophish setup (docker, source, binary)
 * Network setup

**Comment by lakesideXY** [comment]
I don’t know how to get those info except the OS which is win 10 and I
downloaded the gophish zip file from the github

You'll need to give us a lot more information about your setup. e.g:

**Comment by glennzw** [comment]
The `config.json` file is in the gophish folder.

It sounds to me like you might be running the gophish.exe file from inside the zip file, so the database doesn't get saved.

**Comment by lakesideXY** [comment]
Thanks, I'll check it out. Yes I’m running the gophish.exe file from inside
the zip file.
How can I get a saved database please.

**Comment by glennzw** [comment]
You need to extract the zip file into a folder.

**Comment by lakesideXY** [comment]
Thanks, I'll check it out.
