### ISSUE TITLE
How tracking "Submitted Data" works on landing page?

### ISSUE THREAD

**Issue by kubakriz** [gophish/gophish#2717]
Hi there, guys,

How is the "Submitted Data" tracked? The thing is I want to make landing page only with button that will be named "Download" and should download some empty document named "Invoice". I want to track that download button as "Submitted data" for the result analysis afterwards. I want it to double check if the "victim" would stop if they had to click some download button on weird site. 

Next problem is that I made the "report phishing" link like this:
`<p style="font-size: 9px; text-align: center;">This is a phishing test e-mail, if you noticed it report it<a href="{{.BaseURL}}/report?rid={{.RId}}">here</a>`

It was working when I was testing just by IP addres, now I have domain linked and the problem is that Outlook mails make it "reported" immediately after it is delivered. Is there some filter bots that clicking the link and is there some possibility how to evade it so I can see only the real reports from people? 

Thank you so much for your help, I'm really tired of it.

**Comment by glennzw** [comment]
Hi @kubakriz. Interesting idea. Here's my solution:

```html
<!DOCTYPE html><html><head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
  $("button").click(function(){
    $.post("/?rid={{.RId}}",
    function(data,status){
       window.open('https://slicedinvoices.com/pdf/wordpress-pdf-invoice-plugin-sample.pdf', '_blank');
      $("#phish").html("That was a phish, oops. If you did spot it, click <a href='{{.BaseURL}}/report?rid={{.RId}}'>here</a> to report it.");
    });
  });
});
</script>
</head>
<body>

<button>Download Invoice</button>
<p id="phish"></p>
</body></html>
```

Landing page:

![Screenshot 2023-01-06 at 10 02 31](https://user-images.githubusercontent.com/3966613/210977997-81c248e0-9fd4-4712-9c01-88bb917d0fd1.png)

Clicking the link downloads a PDF:

![Screenshot 2023-01-06 at 10 03 24](https://user-images.githubusercontent.com/3966613/210978118-66a7c1da-912d-4065-bc05-b9481e4dd985.png)

After clicking the link the user can report the phish with the new link:

![Screenshot 2023-01-06 at 10 02 26](https://user-images.githubusercontent.com/3966613/210978214-054cc635-7f45-4d2d-98d5-412e95d8796b.png)

And all results come through the dashboard:

![Screenshot 2023-01-06 at 10 00 11](https://user-images.githubusercontent.com/3966613/210978311-62ae75c3-cc30-4c80-a4e8-ed7f938930a7.png)

**Comment by kubakriz** [comment]
Wow, that's really awesome! :-) I see you are a pro! :-)

**Comment by glennzw** [comment]
Thanks! Happy phishing.
