### ISSUE TITLE
email spoofing

### ISSUE THREAD

**Issue by anonymous091223** [gophish/gophish#2718]
What version of Gophish are you using?: v0 .11 .1

Hi, I am a user of Gophish. I would like to ask if anyone here can teach or guide me how to spoof email in gophish? It is possible to spoof email in gophish? Any recommendations on how my phishing be more convincing to its victims? Thank you!

**Comment by glennzw** [comment]
It will depend on what your SMTP server accepts, but you can specify the sender address in the Sending Profile and the Sender Envelope in the Email Template.

**Comment by anonymous091223** [comment]
> 

Thanks, any recommendations on what will I use domain or email service provider that can spoof email? I currently using now a gmail but it only allows me to spoof the name but not the email address.

**Comment by glennzw** [comment]
GMail isn't a great option. There are providers like SendGrid etc but phishing emails are against their TOS.

I'd recommended running your own SMTP server, or using the SMTP of the customer you're doing the work for.

**Comment by anonymous091223** [comment]
> GMail isn't a great option. There are providers like SendGrid etc but phishing emails are against their TOS.
> 
> I'd recommended running your own SMTP server, or using the SMTP of the customer you're doing the work for.

Do you mean I will use the SMTP of the phish victims? They are currently using an open source tool email client. Do you think its possible to create a Sending profile using its SMTP? Thank you.

**Comment by glennzw** [comment]
Yes use the SMTP server that your target organisation uses (their IT admin can set up an account for you). I couldn't comment on whether or not their open source tool would help as I don't know their setup.

**Comment by glennzw** [comment]
Closing out as haven't heard back, feel free to reopen.
