### ISSUE TITLE
XSS

### ISSUE THREAD

**Issue by Mafieww** [gophish/gophish#272]
Hi,

I found a XSS on the page : Users & Groups.

![xss gophish](https://cloud.githubusercontent.com/assets/19486827/15421374/2f38df30-1e73-11e6-9b3b-7ef110f763f1.PNG)

**Comment by jordan-wright** [comment]
Thanks for the report! We'll get this fixed ASAP.

**Comment by jordan-wright** [comment]
Ok, this one should be fixed - can someone confirm?

**Comment by alou1** [comment]
Hi,
Those two pages are fixed (templates and users) , but these pages are still xss vulnerable : 
- landing_pages
![xss_landing](https://cloud.githubusercontent.com/assets/17706044/16111470/fd1b8b10-33b2-11e6-86f9-06058048a61b.png)

- sending_profiles
![xss_sending_profiles](https://cloud.githubusercontent.com/assets/17706044/16111485/0d8da71c-33b3-11e6-9df1-a6773424c2b2.png)

- campaigns : 
           via users-group name 
![xss_campaign_preparation](https://cloud.githubusercontent.com/assets/17706044/16111514/34a40328-33b3-11e6-88da-7d5de2351dd7.png)
![xss_campaign_through_group_name](https://cloud.githubusercontent.com/assets/17706044/16111526/3bae03a8-33b3-11e6-9337-2678bf028c7e.png)

          campaign name
![xss_campaigns_page](https://cloud.githubusercontent.com/assets/17706044/16111532/43dc7884-33b3-11e6-9b0e-cb51c0192c75.png)
