### ISSUE TITLE
I have faced "max connection attempts exceeded - 535 5.7.8 Username and Password not accepted" issue.

### ISSUE THREAD

**Issue by abdullah3102** [gophish/gophish#2721]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: I am using 0.12.1 version of GoPhish.

Brief description of the issue: I have completed my sending profile. At final when I tried to send a test mail to check the configuration. I showed me a error message. 

What are you expecting to see happen? : I would like to see that test mail is send properly.

What are you seeing happen? I got a error message.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
Please see:

https://github.com/gophish/gophish/issues/2703
https://github.com/gophish/gophish/issues/2632
https://github.com/gophish/gophish/issues/2603
