### ISSUE TITLE
trusted_origins key not working

### ISSUE THREAD

**Issue by afmart** [gophish/gophish#2722]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: Gophish v0.12.1

Brief description of the issue: 
admin_server.trusted_origins seems to do nothing, I put an IP address like 'admin_server.trusted_origins=["1.2.3.4"]' and access to admin side by other IPs is still possible.

What are you expecting to see happen? :
I expected some message like, access denied or 404 - page not found, changed log to debug to see if the was any issue, but didn't see any message related to blocking that.

What are you seeing happen?
IP's not in admin_server.trusted_origins aren't blocked while trying to access to admin side.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Open config.json
 * Step 2 - Add an IP value to admin_server.trusted_origins key 
 * Step 3 - Run Gophish
 * Step 4 - Access admin server from an IP not set in admin_server.trusted_origins

**Comment by glennzw** [comment]
Hi @afmart - thanks for reaching out. I think you've misunderstood the purpose of the trusted origins directive - it's to bypass CSRF restrictions when using a reverse proxy. If you want to restrict which IP addresses can access your admin panel you'll need to do so at the operating system level. e.g iptables, ufw, etc

**Comment by afmart** [comment]
Hello @glennzw, 
sorry for my confusion, it's not on the documentation page, and I didn't catch it in the release notes. 
I'm evaluating the software, and need to test and document all the setting and options.
Please close the Issue.

**Comment by glennzw** [comment]
Sorry the documentation wasn't clear:

https://docs.getgophish.com/user-guide/installation#understanding-the-config.json

> The phish_server.trusted_origins option allows you to add addresses that you expect incoming connections to come from. This is helpful in cases where TLS termination is handled by a load balancer upstream, rather than the application itself.

Or the release notes:

> Added Trusted Origins to CSRF Handler
We've added the ability to set trusted_origins in the config.json file. This allows you to add addresses that you expect incoming connections to come from, which is helpful in cases where TLS termination is handled by a load balancer upstream, rather than the application itself. This has been a long discussed and requested feature so it's great to have! Thanks to @mcab and everyone else in https://github.com/gophish/gophish/pull/2301.

https://github.com/gophish/gophish/releases/tag/v0.12.1
