### ISSUE TITLE
tcp 0.0.0.0:80: bind: permission denied" /here is the solution 

### ISSUE THREAD

**Issue by Emdad05** [gophish/gophish#2723]
If anyone getting this error , then go to root folder open gophish directory and find config.json file , and edit the code inside
{
	"admin_server": {
		"listen_url": "127.0.0.1:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "gophish_admin.key",
		"trusted_origins": []
	},
	"phish_server": {
		"listen_url": "0.0.0.0:4444",
		"use_tls": false,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": "",
	"logging": {
		"filename": "",
		"level": ""
	}
}

Copy this and paste and save then run😊

**Comment by glennzw** [comment]
Thanks @Emdad05!

Ideally if you want to bind to port 80 for your fish server you should run gophish with root/admin privileges, but if you're happy for it to be on port 4444 this works too.
