### ISSUE TITLE
email link {{.URL}} is not redirect to the landing page

### ISSUE THREAD

**Issue by HAZTAGS** [gophish/gophish#2724]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: Gophish v0.12.1

Brief description of the issue: 
1. link in the email is not redirect the user to the landing page, the link redirect to gophish admin page instead
2. opened email and cliked link is not detected

What are you expecting to see happen? : 
1. link redirect to landing page
2. opened email and cliked link is detected

I installed GoPhish on a VPS (ubuntu OS) and I using a domain. Here is my config.json

![image](https://user-images.githubusercontent.com/108968463/212231016-0bc3523a-12cc-4b3a-b98e-1d6b963739bf.png)

**Comment by glennzw** [comment]
Please share a screenshot of your Campaign before sending.

I'm guessing you've set the landing page to `https://yourserver.com` rather than `http://yourserver.com`

**Comment by HAZTAGS** [comment]
thanks for your solution @glennzw , it's work
but why use http instead of https?

**Comment by glennzw** [comment]
It's using http because that's what you've defined for your phish_server in your config.json (port 80, and use_tls = false).

**Comment by HAZTAGS** [comment]
Oh i see. oke thanks for your help.

can i ask for other assist from you glennzw?
i acces the VPS using PuTTY to run GoPhish on my server. but when i close PuTTY, GoPhish is also closed. 
i need the GoPhish to keep runing when i exit the PuTTY. i was try this -> https://buaq.net/go-217.html but it's not working. GoPhish service run but i can't acces it

**Comment by HAZTAGS** [comment]
oh i see... thanks for your help glennzw

**Comment by HAZTAGS** [comment]
Hi Glenn,

Can you tell me how to access gophish log file? Because someone create a
campaign and then delete it. Some user want to know who was deleted it.

My gophish version is c0.12.1 , installed on an ubuntu 22.04 LTS vm server.

Thanks alot

Pada tanggal Sel, 24 Jan 2023 21:14, Glenn Wilkinson <
***@***.***> menulis:

**Comment by glennzw** [comment]
How are you running gophish? By default the logs will just be output to the terminal (unless you've specified in your `config.json` for them to go to a file)

**Comment by HAZTAGS** [comment]
Hi Glenn

I run gophish in background using command: ./gophish &
I already set the config.json to get log output but the result is just like
this (attached file).

Is any other way to see the log detail ?

Thanks alot

Pada tanggal Rab, 15 Mar 2023 17:12, Glenn Wilkinson <
***@***.***> menulis:
