### ISSUE TITLE
How can I check attachments on the timeline?

### ISSUE THREAD

**Issue by bigsan2** [gophish/gophish#2729]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.12.1

Brief description of the issue: 
How can I check attachments on the timeline?
When the current attachment is opened, it is recorded as Email Opened in the timeline. Can I check it by opening the attached file separately?

What are you expecting to see happen? :
I want to check the record of opening attachments on the campaign results screen.

What are you seeing happen?
![image](https://user-images.githubusercontent.com/33522876/212838849-5572d142-94c9-46ae-bc27-98ebe1602984.png)

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
Great question @bigsan2. It's not super intuitive at this stage, but basically you can use any of these URL options in your attachment:

 * Email opened: `{{.TrackingURL}}`
 * Link clicked: `{{.URL}}`
 * Data submitted: `{{.URL}}` via a POST

You'd need to *not* use the above in any email/landing page though. So you'd want Word (or Excel etc) to hit those URLs when opened (as a remote image). The Data Submitted would require a macro to perform a POST.

When I get time I'll finish work on my custom events PR: https://github.com/gophish/gophish/pull/1929 (or take sponsorship on and dedicate work hours to it).

Hope that helps!

**Comment by glennzw** [comment]
Closing out as haven't heard back, feel free to reopen.
