### ISSUE TITLE
Weird GoPhish results 

### ISSUE THREAD

**Issue by nathanduffy1995-dev** [gophish/gophish#2730]
What are you seeing happen?

Running phishing campaigns externally with GoPhish and seeing that there are a few anomalies in the results csv. Results showing the IP address as internal addresses or loopback addresses, and I was wondering if anyone else had this issue? 

Thanks.

**Comment by glennzw** [comment]
I've seen this before, maybe these threads can help:

https://github.com/gophish/gophish/issues/2445
https://github.com/gophish/gophish/issues/2344

Gophish will just capture the inbound IP - which may be a private or local IP if you're using some middleware or reverse proxy.

I hope that helps.

**Comment by nathanduffy1995-dev** [comment]
Thanks Glenn, those threads are helpful, particularly this one: https://github.com/gophish/gophish/issues/2445 - Seems to be the exact same issue as I have.
