### ISSUE TITLE
Sender profile test email error 555 5.5.2 Syntax error.

### ISSUE THREAD

**Issue by zakaria250** [gophish/gophish#2733]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.12.1

Brief description of the issue: when attempting to create a sending profile and sending a test email im faced with the syntax error 555 5.5.2 

What are you expecting to see happen? :a succesful test email send.

What are you seeing happen? fail and syntax error.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Domain is hosted on digital ocean. SSL certificate by lets encrypt. 
 * Step 2 -  Config.json configured, connection is secure but failing to send email through my gmail.
 * Step 3 - Using domain from the company im working at which is google workspaces
 
 
![evidence 2](https://user-images.githubusercontent.com/43185705/213319176-9cacef14-7814-4c97-8004-5f2eea5dd827.jpg)
![Evidence1](https://user-images.githubusercontent.com/43185705/213319178-b3309c16-056e-4031-9432-36ad4133f2cc.jpg)

**Comment by mlazzje** [comment]
Same issue here!

**Comment by zakaria250** [comment]
Anyone have a solution for this?

**Comment by Sniper1470** [comment]
hello pls whats the latest version of gophish and how do i download it

**Comment by glennzw** [comment]
@zakaria250 and @mlazzje make sure you're using the latest version, and set your SMTP from to be an email address:
![Screenshot 2023-01-24 at 14 50 11](https://user-images.githubusercontent.com/3966613/214326519-2f562f93-a2bc-4e0e-99b2-99ebcf984f40.png)

You can set the Sender Envelope in the Email Template (to have the `Information Security` friendly name)

**Comment by Sniper1470** [comment]
please i got this error  "554 Message rejected: Email address is not verified. The following identities failed the check in region US-WEST-1" any solution please

**Comment by glennzw** [comment]
@Sniper1470 This sounds like an AWS error. See https://aws.amazon.com/premiumsupport/knowledge-center/ses-554-400-message-rejected-error/

**Comment by glennzw** [comment]
Closing out as haven't heard back, feel free to reopen.
