### ISSUE TITLE
Hide login page for target

### ISSUE THREAD

**Issue by rgnct** [gophish/gophish#2734]
What version of Gophish are you using?: 
0.12.1

Brief description of the issue: 
Is it possible to hide the login page so the person would not become suspicious of the URL?

For example, they would get this URL:
http://my.domain.xyz/?rid=1tVHRHO

But, if they erase the slash like this:
http://my.domain.xyz/

they would get the admin login page
![image](https://user-images.githubusercontent.com/123041193/213338838-66c92cdb-5380-44f6-9b70-02d9fd3253f1.png)

So, is it possible to hide it? or redirect to another URL?

Surely if I want to log in, I just have to use /login 
https://my.domain.xyz/login?next=%2F

Thank you.

**Comment by Luke-From-IT** [comment]
Actually, the login page, by default, is hosted on a different port (3333, by default). so going to http://my.domain.xyz would not show anything. When you set this up, have you changed the admin port to 80 or 443?

**Comment by glennzw** [comment]
@Luke-From-IT is spot on - you can host your login portal on a different port (3333 by default) so a user is unlikely to find it.

I use different subdomains too, e.g gophish.myserver.com for the admin login, and then different subdomains for campaigns - e.g notsuspicious.myserver.com

**Comment by glennzw** [comment]
Closing out as haven't heard back, feel free to reopen.
