### ISSUE TITLE
Is it possible to save files uploaded by users on the phishing page (landing page)?

### ISSUE THREAD

**Issue by nairpaa** [gophish/gophish#2737]
Is it possible to save files uploaded by users on the phishing page (landing page)?

I asked ChatGPT and he found that the configuration that can do this uses the following configuration:
```json
{
  "admin_server": {
    "listen_url": "0.0.0.0:3333",
    "use_tls": false,
    "cert_path": "",
    "key_path": ""
  },
  "phish_server": {
    "listen_url": "0.0.0.0:443",
    "use_tls": true,
    "cert_path": "",
    "key_path": "",
    "redirect_url": "",
    "redirect_path": ""
  },
  "db_name": "sqlite3",
  "db_path": "gophish.db",
  "migrations_path": "./db/migrations",
  "uploaded_file_path": "/var/gophish/uploaded_files" # <---- Like this
}
```

But it doesn't work. I can't find it in the Gophish documentation either. Is it possible to save user uploaded files?

**Comment by c0d3kid** [comment]
No it's not possible.

**Comment by glennzw** [comment]
@c0d3kid is right, there's no such "uploaded_file_path" option. ChatGPT was wrong.
