### ISSUE TITLE
Go Phish Not Opening - New Machine

### ISSUE THREAD

**Issue by hammi198** [gophish/gophish#2739]
Go Phish Community, We have a go phish working without any issue but once we moved our server to new DMZ environment, it started to sop, we are not able to open admin portal. We did change the config file and added new IP but still we are not able to open it.

Do we need to re-install Go Phish as server was moved to new DMZ? or what would be the best step moving forward.

Looking for your assistance.

**Comment by glennzw** [comment]
Hi @hammi198. Could you share the output from the gophish console when running it, as well as you `config.json`?

If you're unable to access the admin portal I's guess it's one of the following reasons:

- Gophish doesn't have permission to bind to the port or something else is running on that port
- There are networking constraints (e.g a firewall) preventing you from accessing the port
- You're binding the admin interface to the local interface

**Comment by glennzw** [comment]
Closing out as haven't heard back, feel free to reopen.
