### ISSUE TITLE
Gophish site not loading up things

### ISSUE THREAD

**Issue by Loner291999** [gophish/gophish#2740]
What version of Gophish are you using?: 0.12.1
Brief description of the issue: 
Information on the site is not loading, anytime I click to check something(campaigns, users landing pages etc.) on the screen after logging in, its stuck on the loading symbol(even though there is info to be shown), and upon checking the console in the browser inspector, shows that the "user is not defined".  I also can't make any new campaigns or landing pages etc

 
![image](https://user-images.githubusercontent.com/39133646/214528635-d4858150-121b-43c0-b9f4-ed4d766e60f6.png)
![image](https://user-images.githubusercontent.com/39133646/214557332-cbd071d4-2ecf-4551-9eec-1d09469b8c66.png)

![image](https://user-images.githubusercontent.com/39133646/214556720-8fadc498-5652-4c81-aba1-b1653e055bab.png)

config file below:
![image](https://user-images.githubusercontent.com/39133646/214529056-ba45cc19-1a57-4fe8-9189-476b0b77eeb8.png)

**Comment by glennzw** [comment]
Hi @Loner291999 - that's definitely not expected behaviour. Did you install from source or the binary, which OS, etc?

**Comment by Loner291999** [comment]
The OS was Ubuntu 22.04.1 LTS and I installed it from the binary. IIRC, I did something along the line of this [video](https://www.youtube.com/watch?v=lEX0OTrobn4)

**Comment by glennzw** [comment]
I just spun up a fresh Ubuntu 22.04 LTS:

```
root@gophish-test:~# cat /etc/issue
Ubuntu 22.04.1 LTS \n \l
root@gophish-test:~# wget -q https://github.com/gophish/gophish/releases/download/v0.12.1/gophish-v0.12.1-linux-64bit.zip
root@gophish-test:~# unzip gophish-v0.12.1-linux-64bit.zip -d gophish
root@gophish-test:~# cd gophish
root@gophish-test:~/gophish# sed -i 's/127.0.0.1/0.0.0.0' config.json 
root@gophish-test:~/gophish# chmod +x gophish
root@gophish-test:~/gophish# ./gophish
```

and logged in fine with no console issues:

![Screenshot 2023-01-27 at 12 20 29](https://user-images.githubusercontent.com/3966613/215085758-33026c5b-3198-4006-8bce-184f93900c33.png)

I suspect all the files weren't extracted properly, or you were trying to run gophish from inside the archive.

You'd need to give more information on your setup.

**Comment by Loner291999** [comment]
So I am doing this on a VM, all i did was download the zip, unzipped it in Downloads and moved it to the Home directory, "chmod +x gophish", and i hit "sudo ./gophish"

before all this i also installed the following as required:
apt-get install golang-go
apt-get install apache2
apt-get install sqlite3
apt-get install mysql-server
apt-get install gcc
apt-get install build-essential

**Comment by glennzw** [comment]
Could you share the the console output from the terminal when you run it. 

Also do a sanity check that all files exist, run `find . | wc -l` from inside your gophish folder:

```bash
$ find . | wc -l
   364
```

**Comment by Loner291999** [comment]
![image](https://user-images.githubusercontent.com/39133646/215475981-c5952a0e-05c5-41a1-865a-8dd313b673b3.png)
![image](https://user-images.githubusercontent.com/39133646/215475990-cb1cd924-720f-4b44-9cf4-810f858a450f.png)

console output after login

`
time="2023-01-30T16:19:09+04:00" level=warning msg="No contact address has been configured."
time="2023-01-30T16:19:09+04:00" level=warning msg="Please consider adding a contact_address entry in your config.json"
goose: no migrations to run. current version: 20220321133237
time="2023-01-30T16:19:09+04:00" level=info msg="Starting admin server at https://127.0.0.1:3333"
time="2023-01-30T16:19:09+04:00" level=info msg="Starting IMAP monitor manager"
time="2023-01-30T16:19:09+04:00" level=info msg="Starting phishing server at http://0.0.0.0:4444"
time="2023-01-30T16:19:09+04:00" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
time="2023-01-30T16:19:09+04:00" level=info msg="Starting new IMAP monitor for user admin"
time="2023-01-30T16:19:46+04:00" level=info msg="127.0.0.1 - - [30/Jan/2023:16:19:46 +0400] \"GET /campaigns HTTP/2.0\" 307 60 \"[https://127.0.0.1:3333/\"](https://127.0.0.1:3333//%22) \"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0\""
time="2023-01-30T16:19:46+04:00" level=info msg="127.0.0.1 - - [30/Jan/2023:16:19:46 +0400] \"GET /login?next=%2Fcampaigns HTTP/2.0\" 200 1057 \"[https://127.0.0.1:3333/\"](https://127.0.0.1:3333//%22) \"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0\""
time="2023-01-30T16:19:47+04:00" level=info msg="127.0.0.1 - - [30/Jan/2023:16:19:47 +0400] \"GET /images/elguards-white.png HTTP/2.0\" 200 49487 \"[https://127.0.0.1:3333/login?next=%2Fcampaigns\"](https://127.0.0.1:3333/login?next=%2Fcampaigns\%22) \"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0\""
time="2023-01-30T16:19:47+04:00" level=info msg="127.0.0.1 - - [30/Jan/2023:16:19:47 +0400] \"GET /images/elguards-black.png HTTP/2.0\" 200 45044 \"[https://127.0.0.1:3333/login?next=%2Fcampaigns\"](https://127.0.0.1:3333/login?next=%2Fcampaigns\%22) \"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0\""
time="2023-01-30T16:19:47+04:00" level=info msg="127.0.0.1 - - [30/Jan/2023:16:19:47 +0400] \"GET /css/dist/gophish.css HTTP/2.0\" 200 55479 \"[https://127.0.0.1:3333/login?next=%2Fcampaigns\"](https://127.0.0.1:3333/login?next=%2Fcampaigns\%22) \"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0\""
time="2023-01-30T16:19:47+04:00" level=info msg="127.0.0.1 - - [30/Jan/2023:16:19:47 +0400] \"GET /js/dist/vendor.min.js HTTP/2.0\" 200 324943 \"[https://127.0.0.1:3333/login?next=%2Fcampaigns\"](https://127.0.0.1:3333/login?next=%2Fcampaigns\%22) \"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0\""
time="2023-01-30T16:19:47+04:00" level=info msg="127.0.0.1 - - [30/Jan/2023:16:19:47 +0400] \"GET /images/favicon.ico HTTP/2.0\" 200 1150 \"[https://127.0.0.1:3333/login?next=%2Fcampaigns\"](https://127.0.0.1:3333/login?next=%2Fcampaigns\%22) \"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0\""
time="2023-01-30T16:19:49+04:00" level=info msg="127.0.0.1 - - [30/Jan/2023:16:19:49 +0400] \"POST /login?next=%2Fcampaigns HTTP/2.0\" 302 0 \"[https://127.0.0.1:3333/login?next=%2Fcampaigns\"](https://127.0.0.1:3333/login?next=%2Fcampaigns\%22) \"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0\""
time="2023-01-30T16:19:49+04:00" level=info msg="127.0.0.1 - - [30/Jan/2023:16:19:49 +0400] \"GET /campaigns HTTP/2.0\" 200 2792 \"[https://127.0.0.1:3333/login?next=%2Fcampaigns\"](https://127.0.0.1:3333/login?next=%2Fcampaigns\%22) \"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0\""
time="2023-01-30T16:19:49+04:00" level=info msg="127.0.0.1 - - [30/Jan/2023:16:19:49 +0400] \"GET /js/dist/app/gophish.min.js HTTP/2.0\" 200 1107 \"[https://127.0.0.1:3333/campaigns\"](https://127.0.0.1:3333/campaigns/%22) \"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0\""
time="2023-01-30T16:19:49+04:00" level=info msg="127.0.0.1 - - [30/Jan/2023:16:19:49 +0400] \"GET /js/dist/app/campaigns.min.js HTTP/2.0\" 200 2947 \"[https://127.0.0.1:3333/campaigns\"](https://127.0.0.1:3333/campaigns/%22) \"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0\""
time="2023-01-30T16:19:49+04:00" level=info msg="127.0.0.1 - - [30/Jan/2023:16:19:49 +0400] \"GET /js/dist/vendor.min.js HTTP/2.0\" 200 324943 \"[https://127.0.0.1:3333/campaigns\"](https://127.0.0.1:3333/campaigns/%22) \"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0\""
time="2023-01-30T16:19:49+04:00" level=info msg="127.0.0.1 - - [30/Jan/2023:16:19:49 +0400] \"GET /font/fontawesome-webfont.woff2?v=4.7.0 HTTP/2.0\" 200 77160 \"[https://127.0.0.1:3333/css/dist/gophish.css\"](https://127.0.0.1:3333/css/dist/gophish.css/%22) \"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0\""
time="2023-01-30T16:19:49+04:00" level=info msg="127.0.0.1 - - [30/Jan/2023:16:19:49 +0400] \"GET /images/favicon.ico HTTP/2.0\" 200 1150 \"[https://127.0.0.1:3333/campaigns\"](https://127.0.0.1:3333/campaigns/%22) \"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0\""
`

**Comment by glennzw** [comment]
It doesn't look like there are any errors. My next thought is that your browser is blocking the loading of some .js files. Could you try in a different browser?

**Comment by Loner291999** [comment]
apologies for not posting an update, turns out recreating the gophish instance helped
