### ISSUE TITLE
What to type in URL (Location of GoPhish listener, must be reachable by targets)

### ISSUE THREAD

**Issue by Hanzo96** [gophish/gophish#2741]
Hello, first I have a question about GoPhish, is it used for e-mail phishing only? or can I host a phishing link using it? 
second I want to know what to type in in URL when creating a campain, I want to host a phishing page that can be accessed by any victim who clicks the link, is it possible to do that with GoPhish? Thanks

**Comment by glennzw** [comment]
Hi @Hanzo96, welcome to gophish! You can send phishing emails and host the phishing site (landing page). You'll need to run it on a publicly accessible server, and you'd use that server's IP or hostname as the URL when creating a campaign.

Take a look at the documentation here: https://docs.getgophish.com/user-guide/

There are loads of tutorials on Youtube too.

Good luck!

**Comment by glennzw** [comment]
Closing out as haven't heard back, feel free to reopen.
