### ISSUE TITLE
 Invalid SMTP From address because it is not an email address

### ISSUE THREAD

**Issue by Sniper1470** [gophish/gophish#2745]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue: 

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by Sniper1470** [comment]
Invalid SMTP From address because it is not an email address.  please help out with this issue

**Comment by glennzw** [comment]
It sounds like you're not entering a valid email address.

Could you share a screenshot please.

**Comment by glennzw** [comment]
Closing out as haven't heard back, feel free to reopen.

**Comment by sarwar0980** [comment]
![image](https://user-images.githubusercontent.com/101712482/231713016-ef935b39-d4a5-422f-8b2b-f68d8e639b8d.png)
How can i solved this issue, please let me know.

**Comment by sarwar0980** [comment]
![image](https://user-images.githubusercontent.com/101712482/231713798-b6a17f55-7cfb-4063-bb85-0eb6fabfa236.png)
**Invalid SMTP From address because it is not an email address** Help Please

**Comment by directionforward** [comment]
+1

**Comment by phi-el** [comment]
+1, if you insert the sender with that format directly in the db, it still works

**Comment by glennzw** [comment]
SMTP from should be of the form `name@domain`.

You can specify the Sender Envelope in the Email Template.

**Comment by phi-el** [comment]
Thanks for replying :) Regarding to the first image provided @ https://docs.getgophish.com/user-guide/documentation/sending-profiles , the image states "First Last<test@example.com>" for the "From" field, so this could lead to some misconceptions :)
