### ISSUE TITLE
Forbidden - CSRF token invalid

### ISSUE THREAD

**Issue by Lebron226** [gophish/gophish#2746]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: gophish 0.12.1

Brief description of the issue: i cant reach the gophish page. whe, i submit the ID and password on login page its noticed that Forbidden - CSRF token invalid 

What are you expecting to see happen? : gophish framework page

What are you seeing happen?:Forbidden - CSRF token invalid 

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
Hi there. You're probably behind a reverse proxy?

You could try using the trusted_origins parameter:

https://docs.getgophish.com/user-guide/installation

**Comment by glennzw** [comment]
Closing out as haven't heard back, feel free to reopen.
