### ISSUE TITLE
Dashboard Results Incorrect

### ISSUE THREAD

**Issue by lily-dev** [gophish/gophish#2748]
I'm currently using Gophish V0.11.0

My dashboard results are: 
![image](https://user-images.githubusercontent.com/62301796/215339535-c8b67b54-ca58-47f9-bc72-02ef81a58d2b.png)
However, the emails have been opened. How do I set the gophish server to be publicly accessible for the results to reflect ?
I have tried:
1.  Changing the admin_server.listener_url L to 0.0.0.0 but its only accessible locally. 
I have also looked at the documentations FAQ and tried 
-  Ensuring the  email template has the {{.URL}} template tag 
![image](https://user-images.githubusercontent.com/62301796/215339789-ef2621b0-283a-4322-9d37-a7ea51c7d6e8.png)
- The campaign URL does point to the gophish server, but its still not reachable.

Code for config.json 
![image](https://user-images.githubusercontent.com/62301796/215343205-8fd5e339-50b5-425d-8179-7b6c0b7d6455.png)
The results when running http://PrivateIP on the web, the result is 404 page not found

PS: There is no firewall/vpn blocking the server from being accessed.

**Comment by glennzw** [comment]
You won't be able to access a private IP from the internet. Where are you running gophish?

You'll need to run it on a publicly accessible IP (or use tunnels or ngrok or something similar to achieve a publicly routable endpoint).

**Comment by lily-dev** [comment]
I'm running the gophish from a VM on a personal PC.

**Comment by glennzw** [comment]
If it's running locally then there's no way for another host on the internet to communicate with it (to load the tracker image for view the landing page).

**Comment by glennzw** [comment]
I'd recommend hosting on DigitalOcean, AWS, or Vultr. You can use my DigitalOcean referral code to get $200 credit:

https://www.digitalocean.com/?refcode=92d344b69f50

**Comment by lily-dev** [comment]
I've managed to set it up on a server, but how do I access it over the internet using the public IP ?

**Comment by lily-dev** [comment]
All ports were closed, had to enable port 3333.

**Comment by glennzw** [comment]
Great! Happy phishing 🐟

**Comment by lily-dev** [comment]
Emails are being sent but once opened, the results don't reflect. This is after I switched from using outlook as the sender to my own personal domain. How do I get the results to reflect. 
The only error I see in the logs is  "TLS handshake error from IP: remote error: tls: unknown certificate"
 since its self signed. My phish listener can be accessed over the internet.
