### ISSUE TITLE
配置文件中的 `Contact address` 是什么意思? 有什么功能

### ISSUE THREAD

**Issue by deTian0** [gophish/gophish#2754]
配置文件中的 `Contact address` 是什么意思? 有什么功能

**Comment by deTian0** [comment]
What does' Contact address 'mean in the configuration file? What function does it have?

**Comment by glennzw** [comment]
Contact address allows you to submit your email address - it's a safety measure when an admin comes across your phishing site and wants someone to contact. You can test this by adding a `+` character to the end of a landing page. e.g:

http://localhost/?rid=iRnxseC+

```
{
  "server": "gophish",
  "contact_address": "glenn@internet.com",
  "send_date": "2023-01-09T13:33:30.141934Z"
}
```
