### ISSUE TITLE
Gophish API : http: TLS handshake error

### ISSUE THREAD

**Issue by Ju777** [gophish/gophish#2755]
Hello,

I am trying a very simple http request on Gophish API, but it's blocked by a TLS error message displayed by Gophish server logs :

**What version of Gophish are you using?:**
Gophish version0.12.1

**Brief description of the issue:**
I am trying to execute an http request to get the sending_profiles in JSON format. The request is blocked unless I desactivate the SSL certificate verification. Note that the SSL certificate installed on my Gophish server is valid until november 2023.

**What are you expecting to see happen? :**
I am expecting to see a response including all the sending_profiles in JSON format.

**What are you seeing happen?**
- I am seeing this error message (in my http client POSTMAN) ``Error: unable to verify the first certificate``.

- And I am seeing this error message in the web browser console : ``Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://gophish.alliancecybertech.eu:3333/api/smtp. (Reason: header ‘authorization’ is not allowed according to header ‘Access-Control-Allow-Headers’ from CORS preflight response)``.

**If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:**
It's not.

**Please provide any terminal output that may be relevant below:**
No terminal ouput. But here is my ``config.json`` :
```
{
        "admin_server": {
                "listen_url": "0.0.0.0:3333",
                "use_tls": true,
                "cert_path": "my_certificate.crt",
                "key_path": "my_certificate.key",
                "trusted_origins": []
        },
        "phish_server": {
                "listen_url": "0.0.0.0:8080",
                "use_tls": true,
                "cert_path": "my_certificate.crt",
                "key_path": "my_certificate.key"
        },
        "db_name": "sqlite3",
        "db_path": "gophish.db",
        "migrations_prefix": "db/db_",
        "contact_address": "",
        "logging": {
                "filename": "",
                "level": ""
        }
}
```

**Please provide as many steps as you can to reproduce the problem:**
 * Step 1 : write an http request, mine is written in Javascript : 
 ```
  fetch(GOPHISH_ADMIN_URL, {
        method: "GET",
        headers: {
            Authorization : GOPHISH_API_KEY
        },
    })
 ```
 * Step 2 : execute the request from your interface
 * Step 3 : check the gophish server logs and see : ``2023/02/01 11:06:32 http: TLS handshake error from MY_IP_ADDRESS: EOF``

**Comment by glennzw** [comment]
I suspect the answer is the same as in https://github.com/gophish/gophish/issues/2756

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen.
