### ISSUE TITLE
Gophish API : the 'Authorization' header is not allowed by server. So I can't authenticate with my API KEY.

### ISSUE THREAD

**Issue by Ju777** [gophish/gophish#2756]
Hello,

**What version of Gophish are you using?:**
Gophish version 0.12.1

**Brief description of the issue:**
I am trying to make an http request towards my Gophish server. But the request is blocked by my browser, considering that the 'Authorization' header is forbidden for such a request :
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://MY_GOPHISH_SERVER:3333/api/smtp. (Reason: header ‘authorization’ is not allowed according to header ‘Access-Control-Allow-Headers’ from CORS preflight response).
```

Here is my request (written in Javascript) :
```
fetch(GOPHISH_SEVER_URL, {
        method: "GET",
        headers: {
            Authorization : API_KEY
        },
    })
```

**What are you expecting to see happen? :**
I am expecting to get the sending_profiles as a response in JSON format.

What are you seeing happen?
I see an error message in my browser console : 
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://MY_GOPHISH_SERVER:3333/api/smtp. (Reason: header ‘authorization’ is not allowed according to header ‘Access-Control-Allow-Headers’ from CORS preflight response).
```

**If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:**
It's not.

**Please provide any terminal output that may be relevant below:**
No terminal ouput.

**Please provide as many steps as you can to reproduce the problem:**
 * Step 1 - Write an http request to obtain the sending_profiles.
 * Step 2 - Execute it.
 * Step 3 - Check in your browser console wether you got the JSON response or not.

**Comment by edermi** [comment]
This is related to CORS: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by Ju777** [comment]
Thanks @edermi .

I have read the document you mentionned.
I was hoping there is a way to bypass this browser security. Maybe you know something about it ?

**Comment by edermi** [comment]
If the script is supposed to run in the browser, you'd have to modify the Gophish source to set an `Access-Control-Allow-Origin` header. This exposes the API to client side browser attacks (XSS etc.), so unless there's a specific reason to have your API code running in the browser I'd strongly consider running it outside the browser in a separate process.

**Comment by Ju777** [comment]
Hello @edermi ,

I am wondering if I formulated my issue correctly : what I see is that a simple GET request from my frontend towards my Gophish server is blocked (with a message in the console saying that the "Authorization header is not allowed").

I am ok with it but how can one make any HTTP request towards a server expecting an API_KEY identification without an 'Authorization header' ?

By the way, with a HTTP client like POSTMAN, the request is blocked as well ... unless I disable the SSL verification in POSTMAN.

So my issue is : how can I disable the SSL verification in my HTTP request coded (in Javascript) as it is done in POSTMAN ?

**Comment by glennzw** [comment]
@edermi is spot on, this is a CORS issue - it'd be dangerous if any webpage could make web requests to other domains. You could disable your browser security measures, but that's not super great.

If you're bumping into SSL trouble, you could run gophish over HTTP as a quick fix.

If you're building out an application you could make your API requests server side - e.g with the Python API library.

HTH, good luck!

**Comment by Ju777** [comment]
Thanks @glennzw .

I figured out something : I put the Gophish AIP KEY in the url : ```https://GOPHISH_URL/ressource/?api_key=MY_API_KEY``` (masked with environment an variable) . It works because my request is a GET one.

And the 'Authroization' header has to be used in POST, PUT, DELETE but not in GET ... my mistake !

**Comment by Ju777** [comment]
It can be closed.
