### ISSUE TITLE
Build From Source, But Attachment Tracking not working

### ISSUE THREAD

**Issue by Lllly101** [gophish/gophish#2757]
**similar issues**：https://github.com/gophish/gophish/issues/2397

What version of Gophish are you using?:  0.12.1
Go Version:  1.19.5

Brief description of the issue:  I'm trying to send an attachment with a phishing email but the image seems not being loaded when the Word document comes through to the target. The variables {{.FirstName}} and {{.LastName}} is filled in with the receivers informations.

What are you expecting to see happen? : I except the image tracking to work.

What are you seeing happen? I used the "gophish_word.docx" and do not changed any thing. GoPhish is not tracking that anything is being opened.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```

```
![image](https://user-images.githubusercontent.com/27736585/216568278-45d66870-0fa7-45f1-b988-61caec67cb39.png)
![image](https://user-images.githubusercontent.com/27736585/216567964-958cabd7-5c0c-49eb-8399-a1ab1d97265c.png)

The Word I used 
[gophish_word.docx](https://github.com/gophish/gophish/files/10577749/gophish_word.docx)

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
If you're seeing the result of 'Email Opened' that means the tracking image loaded. In Word you'd see an error in that red square if it wasn't working, e.g:

![Screenshot 2023-02-10 at 16 15 16](https://user-images.githubusercontent.com/3966613/218141296-626ddd7e-2a2c-4eed-8b29-1034ef0fbcbd.png)

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen.

**Comment by umeshkumar1209** [comment]
Hi glennzw,
I already done all variable to print as simple, but attachment tracking was not working. 

[gophish_attchement.docx](https://github.com/gophish/gophish/files/13811752/gophish_attchement.docx)
[gophish_text.txt](https://github.com/gophish/gophish/files/13811753/gophish_text.txt)
[gophish_word.docx](https://github.com/gophish/gophish/files/13811754/gophish_word.docx)

Could you please help me regarding same?

**Comment by umeshkumar1209** [comment]
@glennzw,
Could you please help me on above issue?
![Gophish_Reports](https://github.com/gophish/gophish/assets/97392761/c2d71d62-f991-46bc-b7f3-f7f2b5bebd45)
