### ISSUE TITLE
Update Gophish to latest fixes?

### ISSUE THREAD

**Issue by sexD** [gophish/gophish#276]
Hi all,,

I know that this is not an issue but I wonder how I can update Gophish with the latest files to include all recent fixes? I installed it from the binary file which I extracted on my server. Shall I just replace all files via sFTP with the files found here on Github? Would that work? Do I need to preserve any files?

Thousand thanks for an answer for this noob question.

**Comment by jordan-wright** [comment]
I would recommend setting up the Go environment and successfully building a new install from source (in a different folder than your current install). Then, when you run gophish it will make a new gophish.db.

Overwrite the gophish.db with your copy and you'll be good to go. :)

**Comment by jordan-wright** [comment]
Going to go ahead and close this for now - let me know if you run into issues!
