### ISSUE TITLE
I have changed the sender profile but the display name on the recipients keeps showing the same as the old one 

### ISSUE THREAD

**Issue by drravik** [gophish/gophish#2761]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue: 

I have changed the sender profile but the display name on the recipients keeps showing the same as the old one.
In the mean time on the headers of outlook the sender is the new one

What are you expecting to see happen? : Sender should be the new phishing email address that i have created

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
Hi @drravik - you'll need to give us a lot more information. e.g some screenshots of your Email Template, Sending Profile, what the email looked like in your inbox.

Mailhog can be a great tool for testing things like this.

**Comment by drravik** [comment]
Thank you for your reply. The issue was at the email template. I have not changed the name and email address of the sender there.
