### ISSUE TITLE
unable to access gophish from a VPS

### ISSUE THREAD

**Issue by justinboss123** [gophish/gophish#2763]
I have the same problem with my vps server when I do all the configuration I can't get the gophish administrator interface 
![go1](https://user-images.githubusercontent.com/125306679/218696290-e3d7e792-eacf-4682-a1fd-468df149855e.PNG)
![go2](https://user-images.githubusercontent.com/125306679/218696303-fca1612a-6159-4117-85ca-48d96add9a8a.PNG)

**Comment by edermi** [comment]
Your second log shows that the admin server runs on port 1723, so the config you placed here definitely doesn't match what you're using in production.
Also, there already seems to be another process listening on port 80.

**Comment by justinboss123** [comment]
I changed the configurations I forgot to take the capture of the new configurations here is the new configuration
![go3](https://user-images.githubusercontent.com/125306679/218699864-4b2d0e4a-ac94-46c8-8324-30f40d13b004.PNG)

**Comment by edermi** [comment]
Sorry, the information you provided is not sufficient to resolve your case. You changed settings without providing us the respective configuration and you didn't bother filling out the issue template, which leads to relevant information missing. You also didn't describe your problem well, from what I can see gophish is up and running and there is even a log line stating that a Firefox browser connected to the server.

Please refer to the documentation on how to set up Gophish: https://docs.getgophish.com/user-guide/installation 
If you have further problems, please give us **at least** (better fill out the [issue template](https://github.com/gophish/gophish/blob/master/ISSUE_TEMPLATE.md)):

1. Your gophish config file
2. The gophish output
3. A problem description that states what you are trying to do, what you expect to happen and what actually happens.

Unless you take some time to clarify the problem, nobody will be able to provide assistance in resolving it.

**Comment by justinboss123** [comment]
I made the necessary configuration but I can't access my server online and I see at the bottom when I try to connect via the web that it gives me the address 127.0.0.1
I attach to this the captures of my config.json configuration, the message obtained on the server and the message obtained during the web connection
![go1](https://user-images.githubusercontent.com/125306679/218777626-0aadf448-292c-426e-8b5a-90d218ac01e0.PNG)
![go3](https://user-images.githubusercontent.com/125306679/218777636-c48ae279-e33f-492d-8d71-3b7bff696130.PNG)
![go4](https://user-images.githubusercontent.com/125306679/218777641-b23ce1b8-2d12-40f7-8686-015e5e2fa63a.PNG)

**Comment by edermi** [comment]
Can you reach the server on port 80? Did you open the port in the firewall? Depending on your cloud provider, you need to open the port on the system and/or the cloud provider's console.

**Comment by justinboss123** [comment]
j'ai ouvert le port 80 sur mon serveur vps et quand je fait http://192.162.70.51:80 dans mon navigateur il me dis error 404 page no found. j'ai aussi remarqué que la reponse sur le serveur à changé sauf si je fais le https://192.162.70.51:3333 il resort toujours la 127 sur le serveur j'ai joint les captures d'écrans
![go6](https://user-images.githubusercontent.com/125306679/218789259-f264afaa-f1a7-4eb0-8d44-bd347ca28daf.PNG)
![go7](https://user-images.githubusercontent.com/125306679/218789267-8e453c18-012c-40f8-981d-77ced6a05cb0.PNG)

**Comment by edermi** [comment]
I don't know what ISPconfig monitor is and the whole issue sounds like there's something else blocking access to Gophish. Have you tried with a different VPS provider?

**Comment by justinboss123** [comment]
ok I think I'll try another vps which you advise me?

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen.
