### ISSUE TITLE
Creating SSL certificate and private keys

### ISSUE THREAD

**Issue by dminyard** [gophish/gophish#2769]
What version of Gophish are you using?: 0.7.1

Brief description of the issue: When using the instructions for generating a certificate with openssl, the command completes successfully, but the site is still flagged as insecure.

What are you expecting to see happen? : The site address shows as secure in the browser URL

What are you seeing happen? Refer to screenshot.

![image](https://user-images.githubusercontent.com/11983964/219416194-0fc47a97-5847-42be-bd38-c78b4d6b6104.png)

**Comment by edermi** [comment]
For the browser to accept the certificate, you need a domain name and a certificate issued by a trusted CA.

**Comment by glennzw** [comment]
@edermi is spot on. The instructions you're following are for generating a self signed cert. I'd recommend letsencrypt, e.g:

https://blog.agood.cloud/posts/2019/10/17/lets-go-phishing/
