### ISSUE TITLE
Test mail did not arrive mail box when try at Campaign

### ISSUE THREAD

**Issue by wkj719** [gophish/gophish#2774]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.12.1 linux 64

Brief description of the issue: The campaign is being tested. When I test in Sending Profiles, the mail arrives normally, but when I send a test mail in the campaign and when I start the campaign, the mail does not arrive. An email called Delivery Status Notification is sent to my email account connected via smtp, and the email is blocked.

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
If the email is being blocked it sounds like you need to do some whitelisting on your infrastructure side. If gophish marks the email as 'Sent' then it's out of gophish's hands if it gets delivered.

**Comment by glennzw** [comment]
Also, the test email is just some plain text, whilst the actual campaign is probably more "phishy" and being eaten by an appliance.
