### ISSUE TITLE
CERTIFICATE SSL

### ISSUE THREAD

**Issue by mateocrx** [gophish/gophish#2776]
What version of Gophish are you using? 

v0.12.1

Brief description of the problem: 

I can't add an ssl certificate to gophish and I've been on it for several weeks, anyone have a tutorial?

**Comment by troplolBE** [comment]
Hey,

There is a tutorial on the official website of GoPhish. Here is the link: https://docs.getgophish.com/user-guide/installation#creating-ssl-certificate-and-private-keys

Hope this helps.

**Comment by mateocrx** [comment]
Thank !!
