### ISSUE TITLE
[suggestion] port this phishing template project to GoPhish?

### ISSUE THREAD

**Issue by thesle3p** [gophish/gophish#278]
I recently came across this Project for creating Phishing templates in python https://github.com/killswitch-GUI/SimplyTemplate would it be feasible to port this to gophish? So far my only complaint with gophish is a lack of ready to go templates, porting this project to go/gophish shouldn't be too hard and would solve that issue.

**Comment by jordan-wright** [comment]
Hey there!

Thanks for the suggestion! The effort required to port this to gophish would be substantial, so I'm afraid we won't pursue this at this time.

However, creating new templates should be fairly trivial using the "Import site" and "import email" features.

Thanks again for the suggestions!
