### ISSUE TITLE
From and Mail From header should be different

### ISSUE THREAD

**Issue by secudna** [gophish/gophish#2781]
To follow  this issue [Bad sender address syntax #2624](https://github.com/gophish/gophish/issues/2624).
@troplolBE answered via https://github.com/gophish/gophish/issues/2624#issuecomment-1324986956 that the rfc oblige us to avoid the format Firstname Lastname <test@test.fr> in the Mail From Header.

[the rfc
](https://www.ietf.org/rfc/rfc5321.txt)

```
4.1.1.2.  MAIL (MAIL)

   This command is used to initiate a mail transaction in which the mail
   data is delivered to an SMTP server that may, in turn, deliver it to
   one or more mailboxes or pass it on to another system (possibly using
   SMTP).  The argument clause contains a reverse-path and may contain
   optional parameters.  In general, the MAIL command may be sent only
   when no mail transaction is in progress, see Section 4.1.4.

   The reverse-path consists of the sender mailbox.  Historically, that
   mailbox might optionally have been preceded by a list of hosts, but
   that behavior is now deprecated (see Appendix C).  In some types of
   reporting messages for which a reply is likely to cause a mail loop
   (for example, mail delivery and non-delivery notifications), the
   reverse-path may be null (see Section 3.6).

   This command clears the reverse-path buffer, the forward-path buffer,
   and the mail data buffer, and it inserts the reverse-path information
   from its argument clause into the reverse-path buffer.

   If service extensions were negotiated, the MAIL command may also
   carry parameters associated with a particular service extension.
```

This reverse-path (Return-path/ Mail From) should indeed not be set as Firstname Lastname <test@test.fr> but at test@test.fr.

But this still allow us to have Firstname Lastname <test@test.fr>  in the From headers of the Sending Profiles, so why force the user to use only the email ?  This is very restrictive for phishing purpose

Solution ->
    We could take as input the Firstname Lastname <test@test.fr> 
    The From: will be Firstname Lastname <test@test.fr> 
    The mail From: test@test.fr

**Comment by glennzw** [comment]
You set the email address in the Sending Profile (as per the RFC you mention) and then the `FirstName Surname <email>` in the Sender Envelope in the Email Template, which is the email header. Does this not solve your problem?

**Comment by mfran2002** [comment]
Hi glennzw,
I'm a very beginner but I should create a campaign for  my company. Never done before.
I have to say it's a great tool, easy to use. Only I'm not able to show the envelope sender.
It only shows me the real sender.

I tried different kind of strings:

1. name surname
2. name surname nsur@mail.me
3. name surname <nsur@mail.me>
4. nsur@mail.me
5. <nsur@mail.me>
6. name surname "nsur@mail.me"
7. "nsur@mail.me"

with no luck
is there a particular syntax or way to write it?

thank you

**Comment by mfran2002** [comment]
Please someone can help?

**Comment by glennzw** [comment]
@mfran2002 Not all providers will let you override the MAIL FROM with the Sender Envelope (e.g GMail won't let you).

@secudna Closing out as haven't heard back. Feel free to reopen.
