### ISSUE TITLE
Can i spoof any email that doesn't have DMARC policy enabled? and how?

### ISSUE THREAD

**Issue by MarcusSelev** [gophish/gophish#2782]
I used this method in this video:
https://www.youtube.com/watch?v=j6NJnFcyIhQ&ab_channel=ChrisPowell

it works fine, till last week all sent emails lands in spam, i don't know how to fix it neither why, anyone can explain why?

**Comment by glennzw** [comment]
Unfortunately this is beyond the scope of support we're able to offer. There are many reasons why emails may end up in spam.
