### ISSUE TITLE
Sender address rejected: Must not use TLS

### ISSUE THREAD

**Issue by gautamrohit** [gophish/gophish#2785]
Hello All,

I am new to Gophish. I have installed the latest version of Gophish which is [v0.12.1].

I have installed the same on ubuntu 22.04.

I am using smtp relay server for sending profiles over port 25. I have trusted my Gophish server IP in smtp to allow relaying. 

When I am testing the same, getting " 421 4.7.0 <abc@xyz.com>: Sender address rejected: Must not use TLS".

Please help.

**Comment by glennzw** [comment]
Unfortunately this is beyond the scope of support we can offer - I'd recommend contacting the SMTP provider.
