### ISSUE TITLE
Update gophish to the last repository version

### ISSUE THREAD

**Issue by m4dw0lf** [gophish/gophish#279]
Hey guys,

I update my gophish to the last version that is in the repository.

I'm receiving this error when I run the command "go build", could you guys help me ?

# github.com/mattn/go-sqlite3
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
# github.com/jinzhu/gorm
../../jinzhu/gorm/utils.go:137:7: error: expected operand
   for range primaryValue {
       ^
../../jinzhu/gorm/utils.go:137:7: error: expected ‘{’
../../jinzhu/gorm/utils.go:137:7: error: expected ‘;’ or ‘}’ or newline
../../jinzhu/gorm/utils.go:147:2: error: expected declaration
  return strings.Join(results, ",")
  ^
../../jinzhu/gorm/utils.go:148:1: error: expected declaration
 }
 ^
../../jinzhu/gorm/utils.go:146:2: error: missing return at end of function
  }
  ^
../../jinzhu/gorm/utils.go:141:10: error: reference to undefined name ‘marks’
   if len(marks) > 1 {
          ^
../../jinzhu/gorm/utils.go:142:63: error: reference to undefined name ‘marks’
    results = append(results, fmt.Sprintf("(%v)", strings.Join(marks, ",")))
                                                               ^
../../jinzhu/gorm/utils.go:144:43: error: reference to undefined name ‘marks’
    results = append(results, strings.Join(marks, ""))
                                           ^
# github.com/jordan-wright/email
../../jordan-wright/email/email.go:506:28: error: reference to undefined identifier ‘mime.QEncoding’
     buff.Write([]byte(mime.QEncoding.Encode("UTF-8", subval)))
                            ^

Thanks.

**Comment by DeveloppSoft** [comment]
Please, send 'go version' results so we are sure you are using a version >
go1.5

**Comment by jordan-wright** [comment]
@m4dw0lf - make sure you are using go version >= 1.5.

Also, when you upgrade be sure to run a "go get -u" to resolve any new dependencies (soon these will be bundled in gophish).

**Comment by m4dw0lf** [comment]
Hey guys,

The go version is = 1.6 but I already solve the problem making a new installation of the GO.

Thank!
