### ISSUE TITLE
uninstall / stop it running on windows

### ISSUE THREAD

**Issue by lexiola** [gophish/gophish#2794]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.12.1

Brief description of the issue: i want to delete it but i get an error becasue it is running how do istop it? ending task in task manfer does not work 

What are you expecting to see happen? : i want to delete it

What are you seeing happen? it is not deleting , it is running 

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
gophish is just a binary - so kill gophish.exe, and delete its folder.
