### ISSUE TITLE
如何支持自动生成二维码模式

### ISSUE THREAD

**Issue by Devil-QAQ** [gophish/gophish#2795]
被钓方署于内网环境，url格式无法出网，希望使用二维码模式，gophish内部根据每一个用户生成一个单独的二维码，有这类接口吗

**Comment by ymbzd** [comment]
no

**Comment by glennzw** [comment]
@Devil-QAQ Google Translate tells me you'd like to use QR codes in your campaign emails. Whilst there's no direct support, you can use a third party website that generates QR codes in realtime. See:

https://github.com/gophish/gophish/issues/1843#issuecomment-634730316

(unfortunately my heroku service got shut down, but there are probably other services other there)

Good luck!

**Comment by awei84** [comment]
> 被钓鱼方置于内网环境，url格式无法出网，希望使用二维码模式，gophish内部根据每个用户生成一个单独的二维码，有这块石头
You can try this address, or build it yourself, it is very simple and there is a ready-made docker
Here is a third party:
<p><img src="https://api.pwmqr.com/qrcode/create/?url={{.URL}}" /></p>
