### ISSUE TITLE
Provide visability to web info on clicks

### ISSUE THREAD

**Issue by snori74** [gophish/gophish#280]
If the web server run by 'gophish' keeps any logs, I can't see reference to them in the docs. What would be handy would be to:

1 - Produce logs as per other web servers, and document where to find these
2 - Add info to the "raw events" export, as shown below:

`email,time,message,details`
`2016-06-01T04:49:22.4758726Z,Campaign Created,`
`hcm@example.com,2016-06-01T04:49:22.9123732Z,Email Sent,`
`hcm@example.com,2016-06-01T04:54:04.005621Z,Clicked Link from: 122.182.121.123 requesting: /forms/PasswordChange.pdf with: Mozilla/5.0 (Windows; U; MSIE 9.0; WIndows NT 9.0; en-US))`

(Had a situation where the number of clicks implied that the recipient had forwarded on to other parties, but we had no visibility as to where the clicks were coming from)

**Comment by jordan-wright** [comment]
@snori74 thanks for the suggestion! Are you more concerned about the IP address or the path that was visited? Right now, there should only be two paths (/track and /) that are used to handle phishing campaigns.

I'll make sure we are including the IP address in the tracking and clicking logs. I agree those are important.

**Comment by snori74** [comment]
Path is presumably related to "opened" vs "clicked the link" - in which
case it effectivly already provided.

**Comment by snori74** [comment]
The IP will also allow us to differentiate "opened from a phone" vs opened
at work which is a big question now.

What woul probably also help re tha would be the browser Agent string -
again will allow to diff tween 'phone on home wifi' from lappie on home
wifi.
On 4/06/2016 5:37 pm, "Steve Brorens" <sbrorens@gmail.com> wrote:

Path is presumably related to "opened" vs "clicked the link" - in which
case it effectivly already provided.

**Comment by jordan-wright** [comment]
You'll find that IP and User Agent information are now included in both clicked links and data submit events.

**Comment by snori74** [comment]
cool, I must upgrade!
