### ISSUE TITLE
Feature-Request: Add the possibility to save a campaign

### ISSUE THREAD

**Issue by BlackPearl01** [gophish/gophish#281]
Hello,

First, thanks for your really useful tool :+1:

I would suggest adding a feature for campaigns : 

Indeed, at present it is not possible to record a campaign in anticipation. We are forced to throw .. it is a pity! Would it be possible to add a feature to record a campaign and put it "in draft"?

Thank you !

**Comment by jordan-wright** [comment]
This is absolutely on our radar. For now, I'm going to close this out since we are tracking the ability to schedule campaigns in #21.

Thanks for the suggestion!
