### ISSUE TITLE
Emails are not getting sent 

### ISSUE THREAD

**Issue by uncommonbreed475** [gophish/gophish#2812]
Hi i m using latest version of gophish, and only problem I m facing is my emails are not getting sent, even test mails, i m using sendinblue SMTP, and my vps is from cloudzy, i am not getting any errors but only problem I m facing is my  emails are not getting sent, please help Thank You

**Comment by urbaninorr** [comment]
Fishing for me.    yes , i can see the mail, thanks.   Video?   its diffucold  for mee to understand everything.

**Comment by uncommonbreed475** [comment]
Hi christia von Sydow Gophish/Gophish

Thanks for ur reply,

I Am Unable To Send Mails Even Test Mails....,

Here is the output m getting in terminal

....2023/03/29 22:30:27 http: TLS handshake error from 172.86.121.18:51608:
remote error: tls: bad certificate
time="2023-03-29T22:30:56Z" level=info msg="172.86.121.18 - -
[29/Mar/2023:22:30:56 +0000] \"GET / HTTP/2.0\" 307 51 \"\" \"Mozilla/5.0
(X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0\""
time="2023-03-29T22:30:56Z" level=info msg="172.86.121.18 - -
[29/Mar/2023:22:30:56 +0000] \"GET /login?next=%2F HTTP/2.0\" 200 1038 \"\"
\"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101
Firefox/111.0\""
time="2023-03-29T22:30:56Z" level=info msg="172.86.121.18 - -
[29/Mar/2023:22:30:56 +0000] \"GET /images/logo_inv_small.png HTTP/2.0\"
200 1118 \"https://172.86.121.18:3333/login?next=%2F\" \"Mozilla/5.0 (X11;
Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0\""
time="2023-03-29T22:30:56Z" level=info msg="172.86.121.18 - -
[29/Mar/2023:22:30:56 +0000] \"GET /images/logo_purple.png HTTP/2.0\" 200
4735 \"https://172.86.121.18:3333/login?next=%2F\" \"Mozilla/5.0 (X11;
Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0\""
time="2023-03-29T22:30:56Z" level=info msg="172.86.121.18 - -
[29/Mar/2023:22:30:56 +0000] \"GET /css/dist/gophish.css HTTP/2.0\" 200
52514 \"https://172.86.121.18:3333/login?next=%2F\" \"Mozilla/5.0 (X11;
Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0\""
time="2023-03-29T22:30:56Z" level=info msg="172.86.121.18 - -
[29/Mar/2023:22:30:56 +0000] \"GET /js/dist/vendor.min.js HTTP/2.0\" 200
324943 \"https://172.86.121.18:3333/login?next=%2F\" \"Mozilla/5.0 (X11;
Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0\""
time="2023-03-29T22:30:57Z" level=info msg="172.86.121.18 - -
[29/Mar/2023:22:30:57 +0000] \"GET /images/favicon.ico HTTP/2.0\" 200 1150
\"https://172.86.121.18:3333/login?next=%2F\" \"Mozilla/5.0 (X11; Ubuntu;
Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0\""
time="2023-03-29T22:31:11Z" level=info msg="172.86.121.18 - -
[29/Mar/2023:22:31:11 +0000] \"POST /login?next=%2F HTTP/2.0\" 302 0 \"
https://172.86.121.18:3333/login?next=%2F\" \"Mozilla/5.0 (X11; Ubuntu;
Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0\""
time="2023-03-29T22:31:11Z" level=info msg="172.86.121.18 - -
[29/Mar/2023:22:31:11 +0000] \"GET / HTTP/2.0\" 200 1766 \"
https://172.86.121.18:3333/login?next=%2F\" \"Mozilla/5.0 (X11; Ubuntu;
Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0\""
time="2023-03-29T22:31:11Z" level=info msg="172.86.121.18 - -
[29/Mar/2023:22:31:11 +0000] \"GET /js/dist/app/gophish.min.js HTTP/2.0\"
200 1107 \"https://172.86.121.18:3333/\" \"Mozilla/5.0 (X11; Ubuntu; Linux
x86_64; rv:109.0) Gecko/20100101 Firefox/111.0\""
time="2023-03-29T22:31:11Z" level=info msg="172.86.121.18 - -
[29/Mar/2023:22:31:11 +0000] \"GET /js/dist/app/dashboard.min.js HTTP/2.0\"
200 2268 \"https://172.86.121.18:3333/\" \"Mozilla/5.0 (X11; Ubuntu; Linux
x86_64; rv:109.0) Gecko/20100101 Firefox/111.0\""
time="2023-03-29T22:31:11Z" level=info msg="172.86.121.18 - -
[29/Mar/2023:22:31:11 +0000] \"GET /font/fontawesome-webfont.woff2?v=4.7.0
HTTP/2.0\" 200 77160 \"https://172.86.121.18:3333/css/dist/gophish.css\"
\"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101
Firefox/111.0\""
time="2023-03-29T22:31:11Z" level=info msg="172.86.121.18 - -
[29/Mar/2023:22:31:11 +0000] \"GET /js/dist/vendor.min.js HTTP/2.0\" 200
324943 \"https://172.86.121.18:3333/\" \"Mozilla/5.0 (X11; Ubuntu; Linux
x86_64; rv:109.0) Gecko/20100101 Firefox/111.0\""
time="2023-03-29T22:31:11Z" level=info msg="172.86.121.18 - -
[29/Mar/2023:22:31:11 +0000] \"GET /images/favicon.ico HTTP/2.0\" 200 1150
\"https://172.86.121.18:3333/\" \"Mozilla/5.0 (X11; Ubuntu; Linux x86_64;
rv:109.0) Gecko/20100101 Firefox/111.0\""
time="2023-03-29T22:31:11Z" level=info msg="172.86.121.18 - -
[29/Mar/2023:22:31:11 +0000] \"GET /api/campaigns/summary?{} HTTP/2.0\" 200
508 \"https://172.86.121.18:3333/\" \"Mozilla/5.0 (X11; Ubuntu; Linux
x86_64; rv:109.0) Gecko/20100101 Firefox/111.0\""
time="2023-03-29T22:31:19Z" level=info msg="172.86.121.18 - -
[29/Mar/2023:22:31:19 +0000] \"GET /sending_profiles HTTP/2.0\" 200 2777 \"
https://172.86.121.18:3333/\" \"Mozilla/5.0 (X11; Ubuntu; Linux x86_64;
rv:109.0) Gecko/20100101 Firefox/111.0\""
time="2023-03-29T22:31:20Z" level=info msg="172.86.121.18 - -
[29/Mar/2023:22:31:20 +0000] \"GET /js/dist/app/sending_profiles.min.js
HTTP/2.0\" 200 2420 \"https://172.86.121.18:3333/sending_profiles\"
\"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101
Firefox/111.0\""
time="2023-03-29T22:31:20Z" level=info msg="172.86.121.18 - -
[29/Mar/2023:22:31:20 +0000] \"GET /api/smtp/?{} HTTP/2.0\" 200 382 \"
https://172.86.121.18:3333/sending_profiles\" \"Mozilla/5.0 (X11; Ubuntu;
Linux x86_64; rv:109.0) Gecko/20100101 Fi

Thats My Vps ip add 172.86.121.18

Whats Else Do You Need To Understand My Problem ??

Please Help To Figure This Out,

Thank You

**Comment by uncommonbreed475** [comment]
Hello

I m waiting for ur reply, please help me to solve this issue, Or should i
use the earlier version of gophish ??? If that can solve the problem
Thank you

**Comment by glennzw** [comment]
Closing due to duplicate https://github.com/gophish/gophish/issues/2813
