### ISSUE TITLE
Result Page un-responsive for large-scale Campaigns

### ISSUE THREAD

**Issue by beyefendi** [gophish/gophish#282]
May I have your attention, please. I am experimenting on 6K+ users.

Results page executes AJAX calls in each 10 seconds to update campaign timeline and email status.
Its good.
However, each aforementioned AJAX call returns 2.8MB data (for this specific case).
Its bad.
Although the table uses paging, response has the all the records and fields.
I think the real reason is not just that. It is the cause of the json object (returned by the GET response) which have page element which have html attribute that actually holds the whole content of the landing page. Is it necessary to send that or at least the whole landing page?
Here is the screenshot. http://prntscr.com/bbqkqg
Secondly, after some hours sqlite gave panic
For example: route.go:110: database is locked
Its ugly.
If we solve the issue of html attribute inside the page element, it will be pretty.
Finally, at least mysql will be a good option.

**Comment by jordan-wright** [comment]
@beyefendi Thanks for the report!

I have considered making an endpoint for something like ```/campaign/results``` that only brings back the results. I might do something similar here so that we only poll for the results instead of the entire campaign. That should help.

We are also planning on supporting other databases (keep an eye on #53) - no timeline on that yet, though.

I'll keep this issue about creating a more lightweight polling endpoint.

**Comment by jordan-wright** [comment]
Hey @beyefendi - good news! I believe I fixed this in https://github.com/gophish/gophish/commit/c5d6792bbaf1dd0223cdf6180d1d7dabf857b1ca.

In a nutshell, I created an endpoint at ```/campaigns/:id/results``` that returns 

```
	Id      int64    `json:"id"`
	Name    string   `json:"name"`
	Status  string   `json:"status"`
	Results []Result `json:"results, omitempty"`
	Events  []Event  `json:"timeline,omitempty"`
```

This should make things much more snappy on the results page without sacrificing any functionality. Grab the updated source and let me know if it works for you!

**Comment by beyefendi** [comment]
Hi @jordan-wright 
Now response data seems better, thanks for your code and very quick response.

Unhappily, I need to open a new case.
Here is the screenshot: http://prntscr.com/bdrxp8
I think, browser fetches all data about in 1 second. That's good. 
But rendering time takes 5 minutes. That's bad.

For this issue, we can apply come workaround.
Rather than fetching all records to fill the details table, (let's say) we can fetch 500 by 500 (experiments will find most sensible value).

**Comment by jordan-wright** [comment]
That's going to be more tricky. Fortunately, we already have an issue to cover pagination through the API which is what this will tie back to. It'll be a bit before I can work that out, but I'll let you know when it's working.

Just curious, do you see this same behavior across all browsers?

**Comment by beyefendi** [comment]
Both Firefox and Chrome.
Since Firebug is more friendly, I took screenshot from them.

This is from Chrome. 
http://prntscr.com/bdt40g
http://prntscr.com/bdt5zs
Content download time is nearly same, 1.5 min.
