### ISSUE TITLE
Useless Tool I Have Ever Used,,Dont Waste Time

### ISSUE THREAD

**Issue by uncommonbreed475** [gophish/gophish#2820]
My Genuine Opinion for this tool Is,, its the worst tool i have ever used,, bakwas tool, never waste time using this tool, it does not work at all, no emails are sent, and no support from these people, i have wasted my week using this tool, where it dint work at all,, useless people useless tool,,,,,,

**Comment by tech62** [comment]
The tool works for me, can you provide more details of your problem ?

**Comment by edermi** [comment]
Seemingly he is annoyed that nobody replied to this issue: https://github.com/gophish/gophish/issues/2813

My 5 cents on this topic: Everybody here is helping others in their free, unpaid time. If you are not willing to invest some time to write a proper bug report and describe your problem properly, you may not expect others to spend their time helping you.

**Comment by mirfansulaiman** [comment]
You should learn more how SMTP work and How gophish work.

**Comment by glennzw** [comment]
@uncommonbreed475 The best way to ensure you don't get any help is to be rude to the maintainers and other volunteers who give up their free time to provide free support.
