### ISSUE TITLE
i hosted my Gophish server on my laptop but i want to portforward it through telebit.io cloud then what send i should do ?

### ISSUE THREAD

**Issue by Vector1199** [gophish/gophish#2824]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue: 

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by Vector1199** [comment]
i tried everything but it just opens in my laptop when started camphein the mail can't reach to the victim

**Comment by Vector1199** [comment]
i hosted it on my laptop i there any option to expose it using portforwarding or tunnling services eg. telebit,cloudflair or anyother if yes can you describe it how to do it

i used telebit and opened http port 3333 but it wont work after that i change config.jason and changed 0.0.0.0 to telebit ecposed link in it but it didnt work

**Comment by glennzw** [comment]
I wouldn't recommend hosting on your laptop, but if you're set on that ngrok is a useful option.

**Comment by Vector1199** [comment]
> I wouldn't recommend hosting on your laptop, but if you're set on that ngrok is a useful option.

i tried it and it worked but as always ngrok is not stable after some time it gets failed so i baught a cloud and hosted on it thanks for the help
