### ISSUE TITLE
Issue With the Campaign loding ?

### ISSUE THREAD

**Issue by vasanth0611** [gophish/gophish#2827]
hi when we try to open the campaign phishing URL in the Chrome browser it detects it as dangerous and phishing context is there an SSL certificate for my Domin, I have purchased the new doming also gives the same warning, Is that possible to change the URL value of ?rid=K1hGTdh in the URL (url)  `https://[cybersecon.cfd]`
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/2552339/230338657-ed77e560-fdaa-44f7-9076-15cef1307394.png)

**Comment by glennzw** [comment]
Duplicate, closed.
