### ISSUE TITLE
Phishing web page inaccessible 	

### ISSUE THREAD

**Issue by Gitimesid** [gophish/gophish#283]
Hello Jordan,
I setup gophish and configure mail server. I created my campaign, received the phishing mail but there are two problems. 
Firstly, the phishing link indicate the gophish server root web page. When I follow it, the server returns me "404 page not found".
Secondly, the tracker link to /track?rid=... but gophish server returns the same error.

Template mail:
&lt;html&gt;&lt;head&gt;&lt;title&gt;&lt;/title&gt;&lt;/head&gt;
  &lt;body&gt;
    &lt;p&gt;Hello {{.FirstName}}&lt;/p&gt;
    &lt;p&gt;... &lt;a href="{{.URL}}"&gt;link&lt;/a&gt;...&lt;/p&gt;
    &lt;p&gt;{{.From}}&lt;/p&gt;
    {{.Tracker}}
  &lt;/body&gt;
&lt;/html&gt;

The landing page is imported from external site. Only the capture data is selected.
For campaign configuration, I fill URL field with  gophish server IP address without path (http://x.x.x.x).
During the testing phase, I launch a campaign, and I opens the mails, but my mails status stay "Sent" instead of "Opened".

**Comment by jordan-wright** [comment]
@Gitimesid - can you copy/paste the output from the terminal after you open the email and click the links?

**Comment by Gitimesid** [comment]
Thank you to your reactivity.
I tried to capture the output but this time it works perfectly.
I don't understand what happened previous week.
