### ISSUE TITLE
Email Tracking Failed

### ISSUE THREAD

**Issue by nmbboy** [gophish/gophish#2847]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.12.1 

Brief description of the issue: 
Email Tracking Failed
In data statistics, statistics of opened emails are invalid, and functions such as clicked links are valid
After reading the previous solutions, I found that there is a problem with opening the email link, but I don't know how to solve it

looks like this
![image](https://user-images.githubusercontent.com/58100371/234453923-0bd8e071-0384-4573-a868-b8c453cbd4d3.png)
Hope to get a reply.
good luck

**Comment by nmbboy** [comment]
Hello, it may be that my test is not very rigorous, I seem to have found the problem, the reason is in the browser, just change the google browser or other browsers, but only my browser will automatically change to 'https '. The specific reason is still not found, thank you very much.

**Comment by glennzw** [comment]
OK strange! I'm glad you found the problem.
