### ISSUE TITLE
Implement "Data Submitted" status

### ISSUE THREAD

**Issue by beyefendi** [gophish/gophish#285]
"Success" email status is good, but it could be better.
 
It would be great to know how much people sent their credentials (or whatever).
We can fire an event when landing page posted with data for "Data submitted".
Then set the status of the campaign.Result object to Data Submitted.

Likewise "Clicked Link".
Then we can replace Success with those two.

**Comment by jordan-wright** [comment]
We currently have the "Submitted Data" event being logged in the raw logs that you can export as CSV.

It's possible that I might change what we see in the main dashboard, but until I do an overhaul of what that results pane looks like, I'm going to go ahead and leave it as "success" for now.

Thanks for the suggestion!
