### ISSUE TITLE
Failed to save edited landing page

### ISSUE THREAD

**Issue by HAZTAGS** [gophish/gophish#2865]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  v0.12.1 and installed it to vm

Brief description of the issue: can't save edited landing page

What are you expecting to see happen? : save ok

What are you seeing happen? 
![image](https://github.com/gophish/gophish/assets/108968463/1115b352-286a-44e4-91ce-d41cf84b3a76)

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 open landing page menu
 * Step 2 edited some landing page with html editor, and click save but failed to save. the landing is still with previous code

**Comment by atheriqbal** [comment]
What does the landing page looks like ? I mean the contents. Without the code we cant say much. 
Also, what was the error?

**Comment by HAZTAGS** [comment]
Hi there,

the page looks like this
![image](https://github.com/gophish/gophish/assets/108968463/8ad0cc6f-5f29-4cba-a3e7-ca463b5502a9)
a simple page with 1 image and little quiz. 

the error looks like this
![image](https://github.com/gophish/gophish/assets/108968463/cde648f0-4159-4974-be6c-5d0bc021c0e0)
the image is other example of similiar errors. i think the server blocked the jquery request or how?

**Comment by HAZTAGS** [comment]
cancel
