### ISSUE TITLE
XSS in captured data

### ISSUE THREAD

**Issue by Gitimesid** [gophish/gophish#287]
Hello Jordan !
I find XSS vulnerability in captured data (login and password).

![alert_xss](https://cloud.githubusercontent.com/assets/19729514/15827550/7ec67db2-2c03-11e6-898c-5554e5bbdbf5.PNG)
![code_xss](https://cloud.githubusercontent.com/assets/19729514/15827551/7ec6ceca-2c03-11e6-82aa-89c626322c9b.PNG)

**Comment by Gitimesid** [comment]
I downloaded compiled gophish v0.1.2.

**Comment by jordan-wright** [comment]
Ok, it looks like this is likely a duplicate that has been fixed in the source release.

I'm going to go ahead and close this out for now, but if you are able to reproduce this using the latest source build, please let me know.

Thank you so much for this report!
