### ISSUE TITLE
Links working only on certain addresses

### ISSUE THREAD

**Issue by Damakov** [gophish/gophish#2875]
**What version of Gophish are you using?:** 
0.12.1

**Brief description of the issue:** 
When I send an email with a link in it, I get an error when clicking on the link, but only when I send it to my 'client's' address. It works fine when I send it to my personal address. I have consulted with the company's IT director to configure all the security settings (on Office 365 and IONOS), but it still doesn't work. Sometimes the link is not clickable at all, and other times the link doesn't redirect to a valid page and shows an error.
I found some posts that looked similar in terms of the error, but it's probably not because of the same issue since my link works on certain addresses.

**What are you seeing happen?**
<img width="854" alt="image" src="https://github.com/gophish/gophish/assets/76222612/0c6eaefb-f438-4f21-ba0b-a12089ebe195">

**Config.json :**
<img width="674" alt="image" src="https://github.com/gophish/gophish/assets/76222612/2292c306-5f07-4cbe-a386-56996306075f">

If you need any further information, please don't hesitate to ask.
Thank you in advance for your future responses.

**Comment by glennzw** [comment]
Hi @Damakov - thanks for reaching out. Would you be able to share the email template too? I'm able to hit https://www.korriganed.net/ from here, so I suspect your client's infrastructure is blocking it for some reason. Could you ask the IT contact to just try clicking that link directly?

**Comment by Damakov** [comment]
Hi @glennzw thank you for your response.

**Here is the code for one of the basic emails templates we tried:**

_</head>
<body>
<p>Bonjour, {{.FirstName}} ,{{.URL}} : <a href="{{.URL}}">connectez vous</a></p>

<p>{{.Tracker}}</p>
</body>
</html>_

**And here is the link that I include when creating the campaigns:**
![image](https://github.com/gophish/gophish/assets/76222612/242c23ac-7d2d-4c23-9a72-a65ec76b0d4b)

**Here are the rules that the person I usually work with gives to clients :**

_Go to the link https://admin.exchange.microsoft.com/#/homepage.
Navigate to the Mail flow menu, then Connectors, and click on Add.
Select Your organization's email server, and click Next.
In the Name field, enter PHISHING CAMPAIGN, and select the options Enable and Keep the internal Exchange mail header options. Then, click Next.
Select By verifying that the sending server's IP address exclusively belongs to your organization, and add the following IP address to the list: MY_DOMAIN_IP.
Go to the menu https://security.microsoft.com/antispam, and select Connection Filter Policy (default value).
Click on Edit, add the IP MY_DOMAIN_IP to the Always allow messages from the following IP addresses or address range menu, and click Save.

Second Step:

    Go to the menu https://security.microsoft.com/advanceddelivery and click on Phishing simulation.
    Enter the sender's domain: to be determined with the client, if available, then save the domain name in IONOS.
    Enter the sender's IP address:  MY_DOMAIN_IP.
    Enter the simulation URLs: to be determined with the client, if available, then save the domain name in IONOS, corresponding to one of the following IP addresses that belong._


To add some informations, we tried clicking on the first link and it redirected to the error page that I mentioned above. Occasionally, the second link doesn't work either. However, when we copy and paste the entire URL, it does redirect to the website with the right page (not the error), but only once. When we try again, it doesn't work. I think you're right, it's related to the client's infrastructure, but I don't know how to fix it. Honestly I'm relatively new to the field of phishing campaigns.

**Comment by glennzw** [comment]
One thought I have is that you're entering the URL as `www.korriganed.net` (leaving off the `https://`) so it might be sending users to the http version. Try change the URL parameter in your campaign to `https://www.korriganed.net/`

**Comment by Damakov** [comment]
Thank you I think it worked. This was really a silly mistake, I thought gophish relied on the config.json to create the correct link.
