### ISSUE TITLE
PR_END_OF_FILE_ERROR Secure Connection Failed when clicking landing page.

### ISSUE THREAD

**Issue by exouster** [gophish/gophish#2906]
Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
![image](https://github.com/gophish/gophish/assets/108223583/d47bd34b-5f05-4686-b7f4-bf10e932acc8)

Brief description of the issue: 
PR_END_OF_FILE_ERROR Secure Connection Failed when clicking landing page

What are you expecting to see happen? :
See the landing page 

What are you seeing happen?
![image](https://github.com/gophish/gophish/assets/108223583/b0c2ebd8-cb9e-4a73-9df2-5ffc69823e71)

Please provide any terminal output that may be relevant below:

![image](https://github.com/gophish/gophish/assets/108223583/0bde6c77-79e7-4525-8a2b-10aa794f3c5a)

**Comment by atheriqbal** [comment]
Your phishing server url is 80 in the config file. While in address bar it shows 8083. Please use the right port
