### ISSUE TITLE
What Needs To Be My Campaign URL

### ISSUE THREAD

**Issue by AlmightyStrikeLord** [gophish/gophish#2918]
What’s Needs To Be In Campaign URL Field Rn I’m Running http://localhost. That’s Just All I Need Everything Else If Fine

**Comment by jordan-wright** [comment]
* https://docs.getgophish.com/user-guide/faq#events-arent-showing-up-on-the-dashboard
* https://docs.getgophish.com/user-guide/documentation/campaigns

> URL - This is the URL that populates the {{.URL}} template value, commonly used in email templates. This should be a URL or IP address that points to the Gophish phishing server and is reachable by the recipient.
