### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by mmjturner** [gophish/gophish#292]
I'm on Parrot Sec...my go version is: go version go1.6.1 linux/amd64
When i type go build in the gophish directory, i get this:

> gophish.go:35:2: cannot find package "github.com/gophish/gophish/config" in any of:
> 	/usr/lib/go/src/github.com/gophish/gophish/config (from $GOROOT)
> 	($GOPATH not set)
> gophish.go:36:2: cannot find package "github.com/gophish/gophish/controllers" in any of:
> 	/usr/lib/go/src/github.com/gophish/gophish/controllers (from $GOROOT)
> 	($GOPATH not set)
> gophish.go:37:2: cannot find package "github.com/gophish/gophish/models" in any of:
> 	/usr/lib/go/src/github.com/gophish/gophish/models (from $GOROOT)
> 	($GOPATH not set)
> gophish.go:38:2: cannot find package "github.com/gorilla/handlers" in any of:
> 	/usr/lib/go/src/github.com/gorilla/handlers (from $GOROOT)
> 	($GOPATH not set)

So where is my issue? Should $GOPATH be in my .bashrc file?
Thanks

**Comment by jordan-wright** [comment]
Yes, it appears as though the issue is that your gopath is not set correctly. Please refer to the instructions on the golang.org site for how to correctly set the GOPATH environment variable.

https://golang.org/doc/install#testing

**Comment by vivekbdh** [comment]
Even I have also the same problem...

pwd
/usr/local/src/gophish-master
[root@VIVEK-PC gophish-master]# go build
gophish.go:39:2: cannot find package "github.com/NYTimes/gziphandler" in any of:
        /home/backup/VivekBackup/software/go/src/github.com/NYTimes/gziphandler (from $GOROOT)
        /home/florinp/golang/src/github.com/NYTimes/gziphandler (from $GOPATH)
gophish.go:40:2: cannot find package "github.com/gophish/gophish/auth" in any of:
        /home/backup/VivekBackup/software/go/src/github.com/gophish/gophish/auth (from $GOROOT)
        /home/florinp/golang/src/github.com/gophish/gophish/auth (from $GOPATH)
gophish.go:41:2: cannot find package "github.com/gophish/gophish/config" in any of:
        /home/backup/VivekBackup/software/go/src/github.com/gophish/gophish/config (from $GOROOT)
        /home/florinp/golang/src/github.com/gophish/gophish/config (from $GOPATH)
gophish.go:42:2: cannot find package "github.com/gophish/gophish/controllers" in any of:
        /home/backup/VivekBackup/software/go/src/github.com/gophish/gophish/controllers (from $GOROOT)
        /home/florinp/golang/src/github.com/gophish/gophish/controllers (from $GOPATH)
gophish.go:43:2: cannot find package "github.com/gophish/gophish/mailer" in any of:
        /home/backup/VivekBackup/software/go/src/github.com/gophish/gophish/mailer (from $GOROOT)
        /home/florinp/golang/src/github.com/gophish/gophish/mailer (from $GOPATH)
gophish.go:44:2: cannot find package "github.com/gophish/gophish/models" in any of:
        /home/backup/VivekBackup/software/go/src/github.com/gophish/gophish/models (from $GOROOT)
        /home/florinp/golang/src/github.com/gophish/gophish/models (from $GOPATH)
gophish.go:45:2: cannot find package "github.com/gophish/gophish/util" in any of:
        /home/backup/VivekBackup/software/go/src/github.com/gophish/gophish/util (from $GOROOT)
        /home/florinp/golang/src/github.com/gophish/gophish/util (from $GOPATH)
gophish.go:46:2: cannot find package "github.com/gorilla/handlers" in any of:
        /home/backup/VivekBackup/software/go/src/github.com/gorilla/handlers (from $GOROOT)
        /home/florinp/golang/src/github.com/gorilla/handlers (from $GOPATH)
gophish.go:37:2: cannot find package "gopkg.in/alecthomas/kingpin.v2" in any of:
        /home/backup/VivekBackup/software/go/src/gopkg.in/alecthomas/kingpin.v2 (from $GOROOT)
        /home/florinp/golang/src/gopkg.in/alecthomas/kingpin.v2 (from $GOPATH)
