### ISSUE TITLE
ESET NOD32 blocks access to server

### ISSUE THREAD

**Issue by lemarakis** [gophish/gophish#2927]
What version of Gophish are you using?: 
v0.12.1 on debian

Brief description of the issue: 
ESET NOD32 flags every landing page as malicious.
Checked it with several PCs and all kind of browsers.

My landing page is very simple:

```html
<html><head></head><body>test</body></html>
```

The config is the following:
```html
{
        "admin_server": {
                "listen_url": "0.0.0.0:3333",
                "use_tls": true,
                "cert_path": "gophish_admin.crt",
                "key_path": "gophish_admin.key",
                "trusted_origins": []
        },
        "phish_server": {
                "listen_url": "0.0.0.0:80",
                "use_tls": false,
                "cert_path": "example.crt",
                "key_path": "example.key"
        },
        "db_name": "sqlite3",
        "db_path": "gophish.db",
        "migrations_prefix": "db/db_",
        "contact_address": "",
        "logging": {
                "filename": "",
                "level": ""
        }
}
```

What are you seeing happen?

![Snag_24134ef3](https://github.com/gophish/gophish/assets/17491845/67d92270-beb9-4bf7-b4f6-b1d6268c5439)

**Comment by jordan-wright** [comment]
This is not something we can help with. It sounds like your question is "how can I prevent ESET from flagging my fake phishing page as phishing" is this is not support that we offer here. This forum is to assist with triaging bugs and questions about Gophish specifically.

**Comment by BriefcaseJoee** [comment]
Hi @lemarakis,

I don't know if you are still dealing with this issue. I ran into the same problem today and managed to solve it by adding an exception in ESETs Management Console for the applicable IP of the VPS you are running GoPhish on.
You can define it via Web Access Control > IP exceptions
You are also able to create a custom policy to apply this exception across all clients.
