### ISSUE TITLE
Remove random parameters from "submitted data"

### ISSUE THREAD

**Issue by beyefendi** [gophish/gophish#293]
It could be better, not to show some certain parameters in submitted data while listing in the results page under details part.
The parameters, actually session or CSRF tokens, which are auto-generated random values.
It will also reduce fetch size.
By the way it may include rid.

I am experiencing this variables, for now.
__VIEWSTATE	POST
__VIEWSTATE	GET
__EVENTVALIDATION	POST
__EVENTVALIDATION	GET
__EVENTTARGET	POST
__EVENTTARGET	GET
__EVENTARGUMENT	POST
__EVENTARGUMENT	GET
__VIEWSTATEGENERATOR	POST
__VIEWSTATEGENERATOR	GET

**Comment by jordan-wright** [comment]
Hey @beyefendi - thanks for the suggestion!

Unfortunately, it gets to be pretty tricky for gophish to determine what to keep and when. For some users, the _VIEWSTATE param may be needed, etc.

For now, I'll probably keep things simple and capture everything (with the only exception being passwords). If I decide to change this out in the future (if there's a clean way to do it without getting too complicated), I'll reopen this back up.

Great ideas though - please keep them coming! Gophish is getting better as a result of your suggestions!

**Comment by beyefendi** [comment]
Although its OK, a clarification might be needed in here.

Those parameters are already exists in the csv files that are downloadable by exporting functionality.
However, showing them on the html, at the same time, does not make sense.

Lets wait, someone to meet with this issue (namely, carving the just 10 characters-parameter from tons of random characters) one day, then it causes to think once again.

I want to just keep the extended list.
__ASYNCPOST	POST
__VIEWSTATEENCRYPTED	GET and POST
__COMPRESSEDVIEWSTATE	GET and POST
__SCROLLPOSITIONX	GET and POST
__SCROLLPOSITIONY	GET and POST
__LASTFOCUS	GET and POST
__PREVIOUSPAGE	GET and POST
__ASYNCPOST	GET and POST
_javax.faces.ViewState	GET and POST
org.apache.struts.taglib.html.TOKEN	GET and POST
jsessionid	GET
PHPSESSID	GET
