### ISSUE TITLE
password issue

### ISSUE THREAD

**Issue by elchinsir** [gophish/gophish#2937]
default password and username for the localhost doesnt work.

**Comment by 0xmada** [comment]
**GET PASSED 2FA AND MORE WITH THE ADVANCE PHISHING TOOL IN THIS TELEGRAM CHANNEL https://t.me/dayztar**

**Comment by Prauudev** [comment]
Available for coding work 🪖  PM for custom pages, Java & PHP-based software for managing an organisation.  -Custom Pages/panels -Websites -Software for organisation management system.  Delivery:  Between 6 hours and 24 hours depending on what you need done  Features: Country Filter UserAgent Filter ﻿﻿Mobile Filter (Can't be bypassed with UA changer) ﻿﻿Mobile & PC Design ﻿﻿Priv8 Antibot ﻿﻿The files generates every time you load the page. Results via: telegram, email or file Residential IP Filter (Doesn't work with CDN) • Format can be changed  🐠PHISHINGHUB 1.0 🐠 ⚠️"Best livepanels based on Upanel framework without API" What u can expect: ▶️ Best of the best panels ▶️ Free updates on panels  Over 100 UK/USA/international Bank Panels available,list and demo videos available in channel    Contact https://t.me/prauu  Channel https://t.me/actionFs

**Comment by jordan-wright** [comment]
I've marked this as spam and reported the content.

@elchinsir there is not enough information here to assist in troubleshooting. Please follow our issue template and resubmit with more information.
