### ISSUE TITLE
Can i *clearly* understand how does credential submission work?

### ISSUE THREAD

**Issue by hollow1** [gophish/gophish#294]
Hey guys, two out of three forms i tried to import to capture creds didn't work.
So i want to have a way to manually adjust my forms so gophish would capture submitted data.
Is there any guide or doc on how the form must be set up?

**Comment by jordan-wright** [comment]
Of course you can - the code is open source 😄 

[Here](https://github.com/gophish/gophish/blob/master/models/page.go#L26) is the code that handles parsing the form. Basically, we parse the HTML looking for ```form``` elements. If we find one, we set the ```action``` tag to be a null string, which causes the form to post credentials to the same url the user is currently at.

We also do things like strip out any inputs that have ```type=password``` in the case users don't want to capture passwords..

I hope this helps! Let me know if you have any questions.

**Comment by hollow1** [comment]
Thanks a lot for a reply.
Now i get it!
Input must have a tag "name", otherwise gophish doesn't capture it.
Maybe you can add this to the user manual.
Cool tool you are doing here, love it.

**Comment by jordan-wright** [comment]
Sure thing - I'll see if I can get it added.

Thanks for the heads up! Glad you're liking gophish!
