### ISSUE TITLE
 cannot execute binary file

### ISSUE THREAD

**Issue by evasun12345** [gophish/gophish#2941]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

[gophish-v0.12.1-osx-64bit.zip](https://github.com/gophish/gophish/releases/download/v0.12.1/gophish-v0.12.1-osx-64bit.zip)

Brief description of the issue: 

I'm operating on a VPS from digital ocean and have downloaded Gophish in the server. I've unzipped digital ocean and used the commands: chmod +x gophish, and ./gophish. However, the error "cannot execute binary file: Exec format error" shows up. 

What are you expecting to see happen? :

Gophish running

What are you seeing happen?

cannot execute binary file: Exec format error

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

here is my config.json:

{
        "admin_server": {
                "listen_url": "0.0.0.0:3333",
                "use_tls": true,
                "cert_path": "gophish_admin.crt",
                "key_path": "gophish_admin.key",
                "trusted_origins": []
        },
        "phish_server": {
                "listen_url": "0.0.0.0:80",
                "use_tls": false,
                "cert_path": "example.crt",
                "key_path": "example.key"
        },
        "db_name": "sqlite3",
        "db_path": "gophish.db",
        "migrations_prefix": "db/db_",
        "contact_address": "",
        "logging": {
                "filename": "",

Here is my terminal output:

root@ubuntu-s-1vcpu-1gb-nyc1-01:~# ls
LICENSE    VERSION      db       gophish-v0.12.1-osx-64bit.zip  templates
README.md  config.json  gophish  static
root@ubuntu-s-1vcpu-1gb-nyc1-01:~# ./gophish
-bash: ./gophish: Permission denied
root@ubuntu-s-1vcpu-1gb-nyc1-01:~# chmod +x gophish
root@ubuntu-s-1vcpu-1gb-nyc1-01:~# ./gophish
-bash: ./gophish: cannot execute binary file: Exec format error

Why is this happening?

**Comment by evasun12345** [comment]
@glennzw

**Comment by edermi** [comment]
You need the Linux build to run on linux, not the OSX build

**Comment by glennzw** [comment]
@edermi is spot on, you need to use the [Linux package,](https://github.com/gophish/gophish/releases/download/v0.12.1/gophish-v0.12.1-linux-64bit.zip) not the OSX one.

Feel free to re-open if you're still stuck. Good luck!
