### ISSUE TITLE
发送钓鱼邮件在qq邮箱中无法正常显示

### ISSUE THREAD

**Issue by shen771** [gophish/gophish#2943]
发送的钓鱼邮件无法在qq邮箱中正常显示，而是出现了html源码，版本0.12.1

[root@xxxx gophish]# cat VERSION
0.12.1
[root@xxx gophish]# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009
Codename:       Core

![1692009261490](https://github.com/gophish/gophish/assets/46846049/2da88127-3c61-4af1-b9d6-3a3099b3b614)

**Comment by glennzw** [comment]
Hi there, could you explain the problem with a little more detail, and how I might reproduce it?

**Comment by glennzw** [comment]
Closed out as haven't heard back.
