### ISSUE TITLE
Suggestion: Show number of potential emails to send before starting campaign

### ISSUE THREAD

**Issue by FLX-0x00** [gophish/gophish#2946]
I think it would be nice to show the number of emails that will be send by the phishing campaign right before it starts.

Just right in this window. Maybe gophish can calculate the right number from the email groups.

![image](https://github.com/gophish/gophish/assets/26464774/fb28881a-360a-48be-ab1f-52c4cd290755)

**Comment by glennzw** [comment]
That's a nice idea, thanks @FLX-0x00 ! Even better if it's all done in Javascript.

**Comment by FLX-0x00** [comment]
There are so many times when you want to test the email with a few users and not double check the selected group and then hundreds of emails fly away :D

**Comment by WigzyDev** [comment]
Great idea! I have also launched campaigns to the wrong amount of people while testing before.  Submitted a PR to add this.

**Comment by FLX-0x00** [comment]
Hopefully the PR will merged. We have implemented a false positive button switcher to mark submissions as false positive, but no luck with merging since 2021 :/ 

no hard feelings - we use a custom compiled version and we will merge this PR in our internal version =) Thanks @WigzyDev  for your awesome contribution

**Comment by WigzyDev** [comment]
> Hopefully the PR will merged. We have implemented a false positive button switcher to mark submissions as false positive, but no luck with merging since 2021 :/
> 
> no hard feelings - we use a custom compiled version and we will merge this PR in our internal version =) Thanks @WigzyDev for your awesome contribution

All good. That's unfortunate that PR's aren't actively being merged. We also went the route of the custom compiled internal version with a bunch of updates.
