### ISSUE TITLE
Broken links in MS Office 365/Outlook

### ISSUE THREAD

**Issue by leonardo-martins** [gophish/gophish#2947]
What version of Gophish are you using?: 
Gophish v0.12.1

Brief description of the issue: 
Campaign URL not properly showing in MS Office365/Outllok. URL code specified in email template, but it appears broken in email received. Changed the style several times. Nothing changed.

CODE:

`<h3><a href="{{.URL}}" style="text-decoration:none; color:black";>Review</a></h3></div>`

IN EMAIL: (Just appears text, not the link)
`[IP?rid=kX0vtON]Review`

What are you expecting to see happen? :

The correct and normal link.

What are you seeing happen?

Link broken and in pure text.

Have double checked Office settings in admin, sender email has correct permissions.
Does anyone faced the same stituation?

**Comment by glennzw** [comment]
Please could you share a screenshot of your Campaign launch page.

I suspect you're leaving off the leading `http[s]://` parameter on your URL input.

**Comment by glennzw** [comment]
Closing out as haven't heard back, feel free to reopen.

**Comment by dlvfr** [comment]
yo, i have the same issue
how to solve?

**Comment by SnrMasara** [comment]
Having the same issue here - 

<img width="269" height="28" alt="Image" src="https://github.com/user-attachments/assets/ee558fdc-5245-4ec9-ab7b-c2019fa15d60" />
