### ISSUE TITLE
PR waiting for merge

### ISSUE THREAD

**Issue by viegelinsch** [gophish/gophish#2952]
Hi,

on behalf of my organisation a general update was created and pulled in https://github.com/gophish/gophish/pull/2882 by @qi-zh.
Unfortunately so far no reaction has been received.

Should we split the PR into small PR for each issue or how to get in contact with @jordan-wright to get into communication about this?

What version of Gophish are you using?: 
_master_

Brief description of the issue: 
_general update to address almost all current security issues - see https://github.com/hzi-braunschweig/gophish/actions for proof that all test pass_

What are you expecting to see happen? :
_communication and advice_

What are you seeing happen?
_busy silence 😉_

Any feedback welcome.

**Comment by jordan-wright** [comment]
Hi there!

"busy silence" indeed! Both @glennzw and I work on Gophish strictly in our spare time, of which there isn't much these days.

I left a comment [here.](https://github.com/gophish/gophish/pull/2882#issuecomment-1689125714) The short of it is that the PR is far too big to review so I would encourage making much smaller, more atomic changes. That way it can be easy to work through in chunks.

And apologies in advance if further reviews continue to take a while!

**Comment by viegelinsch** [comment]
Hi @jordan-wright @glennzw,
I reacted on @jordan-wright comment in #2882 - now I try my luck here.
Of course I understand your point about small PR, the review and how time consuming it is for a project in your spare time.

On the other hand, our philosophy is, that tests must not fail before handing in a PR and the problem with all this security updates is, that only after this mess of updates and changes the project was building properly again and no test failed.
Maybe something to take into account?!

Please feel free to contact me outside this issue to discuss adequate compensation. Maybe there is a way we can sponsor your efforts?!

I would be happy to discuss with you further efforts as we really would like to support this project.
