### ISSUE TITLE
its this project abandoned? more issues

### ISSUE THREAD

**Issue by git5loxosec** [gophish/gophish#2957]
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3SelectNew’:
sqlite3-binding.c:128049:10: warning: function may return address of local variable [-Wreturn-local-addr]
128049 |   return pNew;
       |          ^~~~
sqlite3-binding.c:128009:10: note: declared here
128009 |   Select standin;
       |          ^~~~~~~
       
       
       issue, not installing

**Comment by jordan-wright** [comment]
There's not enough information here to help troubleshoot this.

Please follow our issue template, describing exactly what you're doing, what you expect to see happen, and what is happening instead.

**Comment by glennzw** [comment]
@git5loxosec please try this solution:

https://github.com/gophish/gophish/issues/2589#issuecomment-1245379398
