### ISSUE TITLE
can't submit data on Gophish 

### ISSUE THREAD

**Issue by kimhongkhay** [gophish/gophish#2958]
![Screenshot 2023-08-29 103204](https://github.com/gophish/gophish/assets/116153306/2730b4a5-7bf2-4818-8a8e-7d8ece84973e)

**Comment by kimhongkhay** [comment]
I have follow on Landing Page by  this way, but still not working 

<html><head>
	<title></title>
</head>
<body>
<form action="" method="post" name="form"><label>Username:</label> <input name="username" type="text"/><br/>
<label>Password:</label> <input name="password" type="password"/><br/>
<input id="login" name="login" type="submit" value="Login"/> </form>


</body></html>

**Comment by kimhongkhay** [comment]
Hi @glennzw , thank for help answer to my problem. 
currently It's working back. because I misconfiguration my self.

**Comment by kimhongkhay** [comment]
Oh, Do you know why Submited Data not get full information?
![Screenshot 2023-09-06 091226](https://github.com/gophish/gophish/assets/116153306/e4d35b67-e53f-487b-8179-59f958d44bb9)

**Comment by jordan-wright** [comment]
This documentation is related to your use case: https://docs.getgophish.com/user-guide/faq#submitted-form-data-isnt-being-captured
