### ISSUE TITLE
Go Build Issue

### ISSUE THREAD

**Issue by hatface13** [gophish/gophish#2959]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
Most recent, pulled today.  0.12.1
Brief description of the issue: 
After issuing _go build_ the executable is not built as the script errors out along the way.
What are you expecting to see happen? :
Be provided an executable to run gophish with.
What are you seeing happen?
`# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3SelectNew’:
sqlite3-binding.c:128049:10: warning: function may return address of local variable [-Wreturn-local-addr]
128049 |   return pNew;
       |          ^~~~
sqlite3-binding.c:128009:10: note: declared here
128009 |   Select standin;
       |          ^~~~~~~`
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:
[ec2-user@xxxxxxxxxx gophish]$ sudo go build
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3SelectNew’:
sqlite3-binding.c:128049:10: warning: function may return address of local variable [-Wreturn-local-addr]
128049 |   return pNew;
       |          ^~~~
sqlite3-binding.c:128009:10: note: declared here
128009 |   Select standin;
       |          ^~~~~~~
```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - git clone https://github.com/gophish/gophish.git
 * Step 2 - go build

**Comment by glennzw** [comment]
Haven't heard back so closing out; feel free to reopen.
