### ISSUE TITLE
Kali purple install - password not showing on terminal

### ISSUE THREAD

**Issue by wizhardhacker1** [gophish/gophish#2960]
password not showing on terminal starting. i get this only

Starting gophish...
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ====
Authentication is required to start 'gophish.service'.
Authenticating as: kali,,, (kali)
Password:
==== AUTHENTICATION COMPLETE ====
Opening Web UI https://127.0.0.1:3333  

tried this ... and nothing ... GOPHISH_INITIAL_ADMIN_PASSWORD="password" gophish

tried this ... and nothing (adding to config.json)

"admin": {
    "email": "admin@example.com",
    "password": "password",
    ...
}

This is crazy ... please help

**Comment by glennzw** [comment]
I'm not too familiar with Kali Purple but it looks like you'll need to find the log output to see the password

**Comment by gear0** [comment]
Hej @wizhardhacker1,
looks like you are running gophish as a systemd service. 
After the initial start of the gophish service via

`sudo systemctl start gophish.service`

you should be able to get the logs via

`journalctl -u gophish.service`

At the very beginning of the output (you might need to scroll up), you should be able to find the password.

If you are unable to find the password, stop the gophish service, try deleting your database file, and restart the service. This will create a new database file and a new initial password.

Cheers,
gear0

**Comment by jordan-wright** [comment]
I'm going to go ahead and close this one out since @gear0 is correct- `journalctl` should help in this case and there haven't been any updates in 3 weeks.

Thanks y'all!

**Comment by bassel27** [comment]
Any idea on how to run gophish normally not as a systemd service? I wanna get the logs on the terminal without having to type this command
`sudo systemctl start gophish.service`

@gear0
