### ISSUE TITLE
Result with false positive ''link clicked''

### ISSUE THREAD

**Issue by Landou78** [gophish/gophish#2961]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
- 0.10.1

Brief description of the issue: 
- Phishing campaign is launch (email send to ask people to click on a link who redirect to a ''trap page'')
- Many result with ''link clicked'' even if the receiver didn't click

What are you expecting to see happen? :
- expected result is to have ''link clicked'' only if the target user really clicked on the link

What are you seeing happen?
- ''link clicked'' in the GOPHISH report result even if the person didn't click

After few analyse, below what could cause the issue : 
- when people open the email with Iphone 
- when Microsoft bot scan the page

**My main question is : how to ensure that ''link clicked'' really refere to a click from the target person and not fro ma bot or something else. If this issue is known, do we have a list of element that could affect the results ?**

**Comment by glennzw** [comment]
Hi @Landou78 - unfortunately this is beyond gophish's control. Your best bet is to disable link inspection with whatever appliances you're using, or at least whitelist your gophish domains. There are a lot of threads discussing this, e.g:

https://github.com/gophish/gophish/issues/2646#issuecomment-1330976891
