### ISSUE TITLE
GoPhish Listener URL is not working with IIS Website (Windows Server 2019 VM)

### ISSUE THREAD

**Issue by BriefcaseJoee** [gophish/gophish#2969]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.12.1

Brief description of the issue: 
User is being redirected to the standard IIS website, instead of to the defined landingpage. I used the {{.URL}} as described in the User manual, Link is working just fine but it refers the user to the wrong website

What are you expecting to see happen? :
Redirection to the predefined Landingpage

What are you seeing happen?
Redirection to the standard IIS website

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
<html><head>
</head>
<body bgcolor="#ffffff" text="#000000"><div class="OutlookMessageHeader" lang="en-us" dir="ltr" align="left">
  
  <br/>
  <br/>
  Hello, <br/>
  <br/>
  In an effort to continue bringing you the best available technology, our team has implemented the newest version of Microsoft&#39;s Office 365 Webmail.  
  <br/>
  Your existing emails, contacts. and calendar events will be seamlessly transfered to your new account. 
  <br/>
  <br/>
  Visit <a href="http://&lt;%= @url %&gt;">https://www.companyname.com</a>
  and login with your current username and password to confirm your new account.<br/> 
  <br/>
  Thank you,<br/>
  <br/>
  Company Name<br/>
  <br/>
  <br/>
  <br/>
  <br/>
  Please DO NOT REPLY to this email as this is not a monitored inbox. If
  you have questions/inquiries please visit 
  <a href="http://www.google.com">https://targetcompanysite.com</a>.<br/>
  <br/>
</div>

</body></html>

```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Normal GoPhish setup - works perfectly
 * Step 2 - Setup templates and profiles - works perfectly
 * Step 3 - JSON.config: 
 * {
	"admin_server": {
		"listen_url": "127.0.0.1:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "gophish_admin.key",
		"trusted_origins": []
	},
	"phish_server": {
		"listen_url": "0.0.0.0:80",
		"use_tls": false,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": "",
	"logging": {
		"filename": "",
		"level": ""
	}
}
* Step 4 - Campaign(Listener URL) = http://IIS Server IP (Windows Server 2019 VM)
* Step 5 - Click the phishing link in the URL --> Redirects to standard IIS landinpage instead of the predfined one in GoPhish

**Comment by gear0** [comment]
Hi @BriefcaseJoee 
Have you checked the firewall settings of your server?
It should not be necessary to join the server to your domain. Your users just net to be able to reach your phishing server on the port you bind your gophish landing page.

Cheers,
gear0

**Comment by BriefcaseJoee** [comment]
Hi @gear0 

Thanks for your response.
You are right, it has probably something to do with the firewall settings. I've tried to create a custom rule to allow outbound/inbound access to Port 80 in specific networks but I'm not able to bind the listener to this port, same applies for 8080.

time="2023-09-13T09:18:00+02:00" level=fatal msg="listen tcp 0.0.0.0:80: bind: An attempt was made to access a socket in a way forbidden by its access permissions."

I know that this error is quite common but haven't found a suitable solution in other tickets yet.

**Comment by gear0** [comment]
Ok the output of `netstat -atn` shows that ports 80 and 8080 are already occupied by another process. Is IIS still running? Could be that it is binding those ports. You could try stopping IIS and check the netstat command again. If the output does not contain ports 80 and 8080 you should be good to go.

Cheers,
gear0
