### ISSUE TITLE
How to add unsubscribe link list to the email header

### ISSUE THREAD

**Issue by harrygeorge2893** [gophish/gophish#2972]
Please how can i  add unsubscribe link list on my header just as shown in the image below thanks in advance for your help
 
 
![Screenshot 2023-09-11 141224](https://github.com/gophish/gophish/assets/115331787/871b8694-cdeb-4523-92fe-770a3217d917)

**Comment by kpomeroy1979** [comment]
You add a new custom header in GoPhish in your sending profile. Google for the exact name.

![image](https://github.com/gophish/gophish/assets/33209502/ee424fa9-1917-45be-b468-a3e1e90e3693)

**Comment by harrygeorge2893** [comment]
> You add a new custom header in GoPhish in your sending profile. Here are a few headers I add. Use Google for the exact name for your unsubscribe header.
> 
> ![image](https://user-images.githubusercontent.com/33209502/267776300-ee424fa9-1917-45be-b468-a3e1e90e3693.png)

Thank you for your reply. i have tried it but the email header doesn't come with the unsubscribe link see below if i am doing it wrongly thanks for your prompt response 
![nq](https://github.com/gophish/gophish/assets/115331787/5d96559f-714a-41b8-97a0-eaa4f12214fe)

**Comment by glennzw** [comment]
I think you're looking for the `List-Unsubscribe Header` ([RFC 2369](http://www.faqs.org/rfcs/rfc2369.html)):

```
3.2. List-Unsubscribe

   The List-Unsubscribe field describes the command (preferably using
   mail) to directly unsubscribe the user (removing them from the list).

   Examples:

     List-Unsubscribe: <mailto:list@host.com?subject=unsubscribe>
     List-Unsubscribe: (Use this command to get off the list)
         <mailto:list-manager@host.com?body=unsubscribe%20list>
     List-Unsubscribe: <mailto:list-off@host.com>

     List-Unsubscribe: <http://www.host.com/list.cgi?cmd=unsub&lst=list>,
         <mailto:list-request@host.com?subject=unsubscribe>
```

**Comment by kpomeroy1979** [comment]
Google for the proper format sir. Sent from my iPhoneOn Sep 13, 2023, at 4:43 PM, harrygeorge2893 ***@***.***> wrote:﻿

You add a new custom header in GoPhish in your sending profile. Here are a few headers I add. Use Google for the exact name for your unsubscribe header.


Thank you for your reply. i have tried it but the email header doesn't come with the unsubscribe link see below if i am doing it wrongly thanks for your prompt response

**Comment by glennzw** [comment]
Closing out as haven't heard back, and problem should be solved with above solution.
