### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by hastalamuerte** [gophish/gophish#2973]
...
Setting up gophish (0.12.1-0kali3) ...
gophish.service is a disabled or a static unit not running, not starting it.
Processing triggers for kali-menu (2023.4.5) ...

┌──(root㉿R9)-[~]
└─# gophish
Starting gophish...
Opening Web UI https://127.0.0.1:3333

No username, no password. Admin - gophish - not work
Nothing more. No output and log at first start. 
Maybe its time to change Log Pas function - there is so lot issues with kind of that?
How can i can i login can you tell plz? latest kali debian. gophish via apt install.

**Comment by hastalamuerte** [comment]
ONLY ONE COMMENT THROUGH ALL ISUES HELPFULL 

journalctl -u gophish.service

kali-gophish admin

**Comment by wand3rlust** [comment]
Since version 0.10.1, a randomly generated password is displayed on the terminal once Gophish is launched. 

Lookout for message starting with : **Please login with the username admin and the password ..........***

Login with this password and then change it when prompted.

**Comment by glennzw** [comment]
@wand3rlust is spot on, check your console @hastalamuerte

**Comment by bassel27** [comment]
How did you solve this? I have the same issue on Kali linux.

**Comment by wand3rlust** [comment]
> How did you solve this? I have the same issue on Kali linux.

@bassel27 what version are you using and if possible share bit more details like error messages, OS, etc.

**Comment by bassel27** [comment]
I'm using v0.12.1, the latest version.

I tried the command above and it shows me the logs, so I can log in.

However I'm looking for a way to show the log normally without needing to type this command.

Refer yo my issue #3107  for more details

**Comment by wand3rlust** [comment]
> I'm using v0.12.1, the latest version.
> 
> I tried the command above and it shows me the logs, so I can log in.
> 
> However I'm looking for a way to show the log normally without needing to type this command.
> 
> Refer yo my issue #3107 for more details

@bassel27 I just checked with the same version (x64 binary from v0.12.1) and am able to see the password (first-run) on the console itself (see image below). Moreover, this password is usually for the first run only and once you login with it, you can change it to one of your choosing and use that in future.

In #3107, if you don't want to use systemd, one way would be to disable the systemd service & remove the unit file (there are probably better solutions than this, but atm this is the only one that comes to my mind), and then run the binary manually/custom scripts/cron jobs, etc. That said, systemd is usually a good way to start services unless under specific circumstances.

![Image](https://github.com/gophish/gophish/assets/83376115/e56834ee-c486-4d34-ad00-d8c6180d64a6)
