### ISSUE TITLE
Marking phishing email as "Reported' does not update the GUI

### ISSUE THREAD

**Issue by kpomeroy1979** [gophish/gophish#2975]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.12.1 on Linux

Brief description of the issue: 
When I click on the "Reported" button to mark a phishing email as reported by end users, the GUI does not update.
![image](https://github.com/gophish/gophish/assets/33209502/6e6c0027-d278-4cc9-a046-9221ff0ed0e6)

What are you expecting to see happen? :
I would expect to see the blue number for "Reported" increment for each user that reported the email.

What are you seeing happen?
When I click the "Reported" x to indicate a user has reported the phishing email, nothing happens besides a pop-up saying are you sure.
![1](https://github.com/gophish/gophish/assets/33209502/bda96974-0086-446b-8d30-2f7aba1f1ab3)

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Complete a phishing campaign
 * Step 2 - Navigate to the Archived campaigns
 * Step 3 - Clicked on 'view results'
 * Step 4 - Clicked on the "reported X" button to indicate the user marked as phishing and nothing happens. The number did not go up from 0 to 1, 2, 3 etc.
 *

**Comment by kpomeroy1979** [comment]
The only way I can make the number from the Reported column to go up is to edit the database manually.

![image](https://github.com/gophish/gophish/assets/33209502/f9aa2b1f-697c-4cb2-8696-f4cedb6bd320)

**Comment by glennzw** [comment]
Please check the browser console and see if there's an error in there? I suspect it's this mixed content issue:

https://github.com/gophish/gophish/issues/2161#issuecomment-814245626

**Comment by glennzw** [comment]
I've [added some error handling](https://github.com/gophish/gophish/commit/8e79294413932fa302212d8e785b281fb0f8896d#diff-560651f98a35edbcf18ccd0bd96a4bc25a8f6956c01f6056704a42ac43a75d27) for this condition (when serving admin over SSL but campaigns over cleartext). You should now get an error when it fails:

![image](https://github.com/gophish/gophish/assets/3966613/61380d5d-0564-4759-85d0-46e2daf7d3d0)

**Comment by glennzw** [comment]
P.S I do need to make this an API call at some stage rather than this shorter term solution

**Comment by glennzw** [comment]
Haven't heard back so closing out; feel free to reopen.
