### ISSUE TITLE
API Endpoint for get all campaigns id's

### ISSUE THREAD

**Issue by RunFox** [gophish/gophish#2976]
What version of Gophish are you using?: 0.12.1

I don't find REST API Endpoint for get all campaigns id's
Is there such an endpoint? If not, could I request it to be added?

**Comment by franraknic** [comment]
You can get the campaigns data from `GET api/campaigns/`, the structure of the reply is described on the [API Documentation](https://docs.getgophish.com/api-documentation/campaigns).

**Comment by glennzw** [comment]
Thanks @franraknic

Closing out, let us know if you have any further questions @RunFox
