### ISSUE TITLE
Sending test emails

### ISSUE THREAD

**Issue by aldo1901** [gophish/gophish#298]
I still cannot use send a test email using smtp.gmail.com. I either get an EOF, or I'm told that the remote target actively refused the connection. My setting in the Sending Profiles are:

smtp.gmail.com
myusername blahblah@google.com
mypassword  xoxoxoxoxox

Am I missing something here, seeing how we  are authenticating to an external host I don't need to run postfix or sendmail locally.

I have also tried to add outlook.com smtp and nothing

**Comment by jordan-wright** [comment]
Try using port 587 for gmail and let me know if that fixes the issue: https://github.com/gophish/gophish/issues/253

**Comment by aldo1901** [comment]
sorry, yes I have tried using 587 and 465. No luck. I just cannot tell if it's a firewall issue or not.

**Comment by aldo1901** [comment]
As of now the only testing accounts I have are for outlook.com and gmail.com accounts. Would you be able to provide if there would work, I've tried a few setting and SMTP server/ports and still no luck. I get this message "No connection could be made because the target machine actively refused it." I'm trying to send myself an email to my corporate server. I'm hoping that whatever this is sending as a test email is not getting flagged by an internal measure. Otherwise I would not be able to use this.

**Comment by aldo1901** [comment]
So some update, I tried using the same settings with another phishing tool(Lucy) and I had no problems sending myself an email.

**Comment by jordan-wright** [comment]
What version of gophish are you using?

**Comment by jordan-wright** [comment]
Specifically, let me know if this still doesn't work when you're building from source. If so, we'll keep troubleshooting the issue.

Thanks for the updates!

**Comment by aldo1901** [comment]
I'm using v0.1.2

**Comment by aldo1901** [comment]
compiling from source still nothing. I noticed that although I'm trying to use port 465, I get an error regarding port 25

2016/06/14 15:23:13 worker.go:223: dial tcp :25: getsockopt: connection refused
2016/06/14 15:23:13 http: multiple response.WriteHeader calls
127.0.0.1 - - [14/Jun/2016:15:23:13 -0400] "POST /api/util/send_test_email?api_key=cebe794cd3190e1637d335bb71a36b97f90ffc0cc9b6f44a962a1b8e1d989387 HTTP/1.1" 500 179 "http://127.0.0.1:3333/sending_profiles" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
 2016/06/14 15:23:18 campaign.go:230: Found 0 Campaigns to run

**Comment by aldo1901** [comment]
Ok so I figured it out. You hard-coded port 25 in line 58 in smtp.go. I changed it to 465 and I was able to get mail. My suggestion is to include other ports or leave as an input variable.

**Comment by jordan-wright** [comment]
How are you formatting your connection string? The code you pointed to only sets port 25 if no port is specified. This is to have a sane default for cases where the user doesn't explicitly set it.

**Comment by aldo1901** [comment]
I tried:

smtp.gmail.com:587
smtp.gmail.com:465

While setting both of these, the traffic still reflected port 25. All I did was change port 25 to 465 on smtp.go and it worked. I'm not very well versed in GO so I really couldn't tell you why this is happening.

**Comment by AravindSreenivasa** [comment]
I am using the pre-compiled binaries. I am facing the similar issues.

smtp.gmail.com:587  -> An attempt was made to access a socket in a way forbidden by its access permissions.
smtp.gmail.com:465 -> EOF

I am using my personal email id and password for username and password. Am I wrong there? or is there anyway I can fix this issue?

**Comment by jordan-wright** [comment]
Try building from source and see if the issue persists.

Thanks!
Jordan

**Comment by AravindSreenivasa** [comment]
I will be trying that soon. But the traffic(dial) is reflecting 587 or 465 itself. It is not dialing 25 as it happened with aldo.

**Comment by AravindSreenivasa** [comment]
Thanks a lot Jordan. I built it from source and was able to send the emails after a little hassle with gmail settings. But couple of issues.
1. even though I opened the emails and clicked the links, It is not showing accordingly in dashboard.
2. Do I need to host a server at the URL i'm providing? I did host the page in github, I opened the page and entered values. Nothing is being captured or shown as Email opened.

Please help me out. Thanks,
Aravind

**Comment by jordan-wright** [comment]
Are these for test emails? If so, there are no notifications if links are clicked, etc. That functionality is only to tell if the emails are sent successfully.

If these are for full campaigns, then the only requirements are:

* The URL you use when making a campaign points to your gophish server
* That URL is reachable by the users clicking the links in the email

**Comment by AravindSreenivasa** [comment]
Initially I got it wrong. This is working fine for me. Thank you Jordan.

**Comment by jordan-wright** [comment]
Good to hear! I'll go ahead and close this out.

**Comment by ryan-es2** [comment]
I fixed this myself within the gophish ui specifically where it asks for the mailserver you must append with :465 or whichever port
