### ISSUE TITLE
Landing Page and Email Template Endless Loop (v0.12.1) Cent OS Linux 8

### ISSUE THREAD

**Issue by kazumimuraki** [gophish/gophish#2981]
Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our documentation, which covers how to use Gophish. (previous user "Desiqvel" had this ticket [#2338](https://github.com/gophish/gophish/issues/2338) but it was for Ubuntu, not the Cent OS.

What version of Gophish are you using?: 0.12.1

Brief description of the issue: Landing Page and Email Templates are stuck in endless loading loop. Allows me to create a new page but does not allow me to save them.

What are you expecting to see happen? : be able to save landing page and email template

What are you seeing happen?

Landing page and Email templates not working correctly in 0.12.1 version installed with go, I have not tested downloading the binary already compiled. I deployed gophish on a VPS, and its OS version is Cent OS Linux 8. I accessed the VPS via SSH connection from my mac terminal. I set up an SSH tunnel and connected to https://127.0.0.1:3333/ from chrome on my mac.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:
Not able to get that far

Insert code here
Please provide any terminal output that may be relevant below:
See added description below

Insert output here
Please provide as many steps as you can to reproduce the problem:

Step 1 - Run Gophish
Step 2 - Go to landing page or email template after logging in with admin account. Stuck in loop, will not let me save template or create landing page

Picture of loading loop:
Completely same as [#2338](https://github.com/gophish/gophish/issues/2338)

Picture of Chrome:
<img width="1440" alt="スクリーンショット 2023-09-21 23 24 27" src="https://github.com/gophish/gophish/assets/99329674/7dc952c6-aa50-468f-a9fb-95c542a6b6d9">

I followed the solution in #2338 and did the following:

> Seems to have fixed the problem.
> 
> When downloading the github folder it seems to be a missing folder "vendor".
> Location: "gophish/static/js/src/vendor/"
> 
> I downloaded svn ( sudo apt-get install subversion )
> 
> Then cd into /src/ and download the missing vendor folder
> 
> svn checkout https://github.com/gophish/gophish/trunk/static/js/src/vendor

**Comment by glennzw** [comment]
I'm guessing your vendor folder is missing, same as with the behaviour in the other thread. Could I ask how you're installing gophish? Please see this comment: https://github.com/gophish/gophish/issues/2610#issuecomment-1259969742

**Comment by kazumimuraki** [comment]
Problem solved! Thank you so much for your help! :)

**Comment by Swimatum** [comment]
Working ! Thanks !
