### ISSUE TITLE
User ID and Group ID in docker image

### ISSUE THREAD

**Issue by Bl00d-B0b** [gophish/gophish#2982]
Hello,

How I can change group ID and user ID in docker image? as i can see it's 1000 by default. but I would like to have them different.

Ed

**Comment by jordan-wright** [comment]
Hi there!

This is the level of customization I think I'm going to hold off from adding in the dockerfile unless we hear more requests for this feature. I generally hold off on adding customizable features unless it'll benefit the majority of the userbase to avoid overwhelming folks with customizability.

If you'd like to change this, my recommendation would be to fork and customize the [existing Dockerfile](https://github.com/gophish/gophish/blob/master/Dockerfile) to suit your needs.
