### ISSUE TITLE
Gophish Error while launching in Cloud enviornment in Ubuntu 

### ISSUE THREAD

**Issue by prashanth9911** [gophish/gophish#2984]
I am facing a issue while launching in Ubuntu environment, ubuntu running on AWS, kindly help me how to resolve this issue,

Error message
./gophish.go: line 1: package: command not found
./gophish.go: line 3: /bin: Is a directory
./gophish.go: line 4: gophish: command not found
./gophish.go: line 6: syntax error near unexpected token `('
./gophish.go: line 6: `The MIT License (MIT)'

Kindly help me to fix this issue

**Comment by glennzw** [comment]
Hi @prashanth9911 - you're trying to run go source file. You'll need to either download the binaries or compile the source. Check out the docs for more info.

Binaries: https://github.com/gophish/gophish/releases
Building from source: https://github.com/gophish/gophish

**Comment by prashanth9911** [comment]
kindly help me with how to download the binaries and where I need to put these binaries

**Comment by glennzw** [comment]
It's a bit beyond the scope of support we can offer, but there are lots of tutorials on YouTube, e.g:

https://www.youtube.com/watch?v=lEX0OTrobn4

Good luck!

**Comment by prashanth9911** [comment]
i am getting this error,

time="2023-09-27T10:18:33Z" level=fatal msg="listen tcp 0.0.0.0:80: bind: permission denied"

**Comment by wand3rlust** [comment]
> i am getting this error,
> 
> time="2023-09-27T10:18:33Z" level=fatal msg="listen tcp 0.0.0.0:80: bind: permission denied"

That is because running any service on port 80 requires admin privileges. Try with `sudo` or root account.

**Comment by jordan-wright** [comment]
At this point, I think we've provided the level of support expected for contributors in this repository.

To summarize:

* You'll need to either build Gophish from source or use one of the prebuilt binaries. You can find these on our [releases page](https://github.com/gophish/gophish/releases).
* You'll need to ensure that Gophish can bind to the port you have configured

For more information, please refer to our docs at https://docs.getgophish.com/user-guide/
