### ISSUE TITLE
Gophish v0.12.1 keep crashing on VPS

### ISSUE THREAD

**Issue by chunlam2** [gophish/gophish#2988]
Hi there ! I need some help !

What version of Gophish are you using?: 
Gophish v0.12.1

Brief description of the issue: 
Gophish crashes automatically after ~ 2 hours of launching

What are you expecting to see happen? :
I want Gophish to run without interruption

What are you seeing happen?
I have a test EC2 instance running a Linux 2023 server where I deployed my unmodified Gophish server from the gophish-v0.12.1-linux-64bit.zip package. The server runs for a few hours, about 2 hours, and then crashes.

I'm currently extracting the logs in the gophish.log file to see if there's any information, but there's nothing for the moment, I'm waiting for the next crash.

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - I go into the file and type `sudo ./gophish &`

**Comment by blkph0x** [comment]
install as a service if your terminal session dies so do any processes under that session. I had the same issue just installed as a servcie and start it with service gophish start

**Comment by chunlam2** [comment]
> install as a service if your terminal session dies so do any processes under that session. I had the same issue just installed as a servcie and start it with service gophish start

Thanks for your feedback! 
The server hasn't crashed since, so if it was related to my terminal session, it may be due to human error! If the server crashes again, I'll go ahead and implement the service solution, and I'll be sure to update you on the progress. 
Thanks a lot! :)
