### ISSUE TITLE
Collect data on Gophish

### ISSUE THREAD

**Issue by TairaNoMasakado** [gophish/gophish#2989]
**What version of Gophish are you using?:** 
v0.12.1

**Brief description of the issue:** 
I see that Gophish marks the email opened, clicks on the links and sends data on a recurring basis. For example, if the user clicked 6 times, it shows this. I would like to know in which file it stores this information so that I can collect these recurrences easily, because in the CSV it only shows the 1 status and does not count how many times each action was performed

**What are you expecting to see happen? :**
Collect how many times the user performs each action

thank you

**Comment by jordan-wright** [comment]
Hey there,

Thanks for reaching out!

Gophish tracks user actions like email opens, link clicks, etc., through the events API. The specific storage location for these details is in the SQLite database in the events table. You can query this table to collect recurrences for each user's actions. The events table will store every occurrence, so if a user clicked 6 times, there will be 6 different entries for that user's clicks.

You can run a SQL query like this to get the information:

```sql
SELECT email, message, COUNT(*) FROM events GROUP BY email, message;
```

I hope this helps!
