### ISSUE TITLE
[support] Issue building from repository

### ISSUE THREAD

**Issue by dhruvin917** [gophish/gophish#299]
Hey Jordan,

I'm trying to build from the repository but I keep running into the following error:

`gophish.go:35:2: cannot find package "github.com/gophish/gophish/tree/master/con
fig" in any of:
        C:\Go\src\github.com\gophish\gophish\tree\master\config (from $GOROOT)
        ($GOPATH not set)
gophish.go:36:2: cannot find package "github.com/gophish/gophish/tree/master/con
trollers" in any of:
        C:\Go\src\github.com\gophish\gophish\tree\master\controllers (from $GORO
OT)
        ($GOPATH not set)
gophish.go:37:2: cannot find package "github.com/gophish/gophish/tree/master/mod
els" in any of:
        C:\Go\src\github.com\gophish\gophish\tree\master\models (from $GOROOT)
        ($GOPATH not set)
gophish.go:38:2: cannot find package "github.com/gorilla/handlers" in any of:
        C:\Go\src\github.com\gorilla\handlers (from $GOROOT)
        ($GOPATH not set)`

Also, my Go version is 1.5. 

Thanks for all the help!

**Comment by jordan-wright** [comment]
You'll want to follow the instructions on the [golang website](https://golang.org/doc/install) to setup your gopath. I'm afraid that getting golang up and running is a problem that's considered out of scope for gophish support.
