### ISSUE TITLE
PROBLEMA GOPHISH USERNAME AND PASSWORD

### ISSUE THREAD

**Issue by chrisnigg9** [gophish/gophish#2996]
![Immagine 2023-10-10 192325](https://github.com/gophish/gophish/assets/134374400/82d6ee18-42b8-4bf1-a95c-65029fb05f54)

PASSWORD INVALID

**Comment by wand3rlust** [comment]
@chrisnigg9 From the image it looks like another service is already running on port 80.
Additionally, check this out: https://github.com/gophish/gophish/issues/2942#issuecomment-1678871738 [make sure sqlite3 is in your PATH]

**Comment by chrisnigg9** [comment]
@wand3rlust Please could you tell me how do I know the programs running on port :80 and how to check the sqlite

**Comment by wand3rlust** [comment]
@chrisnigg9 

1. For identifying program you can use this: `netstat -aon | findstr :80`
2. For checking sqlite, enter this in CMD: `sqlite3`
