### ISSUE TITLE
gophish logs

### ISSUE THREAD

**Issue by topazbor** [gophish/gophish#301]
where does gophish save his logs?
and what is the best way to see them

**Comment by jordan-wright** [comment]
We currently don't store web server logs anywhere. We do store events that occur in phishing campaigns in the database.

You can download these logs using the export button in the campaign results, or through the API.

**Comment by jordan-wright** [comment]
The other option to get raw terminal logs would be to start gophish piping the output to a file.

**Comment by topazbor** [comment]
thanks
