### ISSUE TITLE
Web Enhancement

### ISSUE THREAD

**Issue by aldo1901** [gophish/gophish#303]
If possible, I would like to see a way for me to access the web gui from a remote computer. So doing something with apache or something would be awesome.

**Comment by wjwoodson** [comment]
The admin server is configured for local access only by default. You can configure it to listen for remote traffic directly by changing admin server listen_url to 0.0.0.0 (or an IP already configured on your host) in config.json.

Ex: 
`	"admin_server" : {`
`		"listen_url" : "0.0.0.0:3333",`
`		"use_tls" : false,`
`		"cert_path" : "example.crt",`
`		"key_path" : "example.key"`
`	},`

For more advanced configurations you will need to look into forwarding traffic with apache mod_proxy or similar.

**Comment by aldo1901** [comment]
Ok cool. Thanks. Sorry I'm not the programming type and I'm still learning your file structure. Where does the tool save the templates I create or save in the gui? I'm trying to create some custom html code but I cannot figure out for the life of me where the source code resides hence I'm having issue with pointing my code to where the css sheets or images reside. 

-Aldo

**Comment by wjwoodson** [comment]
Aldo,

You should be able to access existing template html through the GUI at templates -> select existing -> edit -> HTML -> source
On the back-end the content of templates are stored in the database gophish.db in table templates column html.

I don't believe we currently support uploading additional files for templates through the GUI but per #164 you can add them directly to the directory `static/endpoint/` and reference at in your template HTML with a relative link to the resource in `static/`

Ex:
Add file `static/endpoint/image.png` on gophish server
Accessible at phish side via `http://phishserver/static/image.png`

Please let me know if this works for you.
Will

**Comment by aldo1901** [comment]
Awesome. Thanks for all the help. I really like your product. 

-Aldo

**Comment by jordan-wright** [comment]
Thanks @wjwoodson!
