### ISSUE TITLE
How can I verify Gophish?

### ISSUE THREAD

**Issue by gdrdrposteo** [gophish/gophish#304]
I haven't seen any signing keys,checksum, etc. How do I go about this? Help please?

Thanks!

**Comment by jordan-wright** [comment]
My apologies, I don't have the hashes published. I'll get those put up somewhere and will get back to you.

Thanks for the report!

**Comment by gdrdrposteo** [comment]
No problem! Looking forward to it.

**Comment by tonejito** [comment]
I uploaded the files to [VirusTotal](https://virustotal.com/) and they are all clean.

Cheers!

**Comment by tonejito** [comment]
Download URL:

https://github.com/gophish/gophish/releases

--------

**v0.1.2**

		https://github.com/gophish/gophish/releases/download/v0.1.2/gophish_linux_64bit.zip

+ https://virustotal.com/en/url/bc0b3f155789f4b936df35a18fcc809ca7e704244cd33ab1ee55de795a89da4b/analysis/


		gophish_linux_64bit.zip	v0.1.2

+ https://virustotal.com/en/file/692834c27f44b396b14e276bd8677a0a5664dbb865adbad98c4105a75378fbee/analysis/


		https://github.com/gophish/gophish/releases/download/v0.1.2/gophish_linux_32bit.zip

+ https://virustotal.com/en/url/489e9d5bf7d247cb2507c882896a3e3bb9ae1f3a861a08ebbf5eb4762ffd7cd8/analysis/


		gophish_linux_32bit.zip	v0.1.2

+ https://virustotal.com/en/file/4ab9d56ece53f59286bd1235c358026966df691d6ecc81b1fb66b5de9e951fc1/analysis/

--------

**v0.1.1**

		https://github.com/gophish/gophish/releases/download/v0.1.1/gophish_linux_32bit.tar.gz

+ https://virustotal.com/en/url/53d9ab4f4316de8093d8131eda02f19433522e2083d0fad274e2c7abde77b5f3/analysis/

		gophish_linux_32bit.tar.gz	v0.1.1

+ https://virustotal.com/en/file/ff366aa38c38379d158c83e49aaf52f709da6669d95192f5365291b2594bd0fc/analysis/

		https://github.com/gophish/gophish/releases/download/v0.1.1/gophish_linux_64bit.tar.gz

+ https://virustotal.com/en/url/6b21bfa31e171039c3fe546ee8d2ea84a28cc7a8cde564ab57f726e2a7c35141/analysis/

		gophish_linux_64bit.tar.gz	v0.1.1

+ https://virustotal.com/en/file/9ada8bb96070bcfee3ef13ee01df2da9fa08e7f1d1d2f07d182ce8ef3bc8bea0/analysis/

**Comment by jordan-wright** [comment]
All fixed in the latest release - I provided sha1 hashes for every binary. Hope this helps!
