### ISSUE TITLE
Max connection attempts exceeded -

### ISSUE THREAD

**Issue by pascalGodfa** [gophish/gophish#3042]
please how can i resolve this error in gophishL
 
Max connection attempts exceeded - dial tcp: lookup smpt.gmail.com on 192.168.1.1:53: no such host

My gophish is not sending test email

**Comment by gear0** [comment]
Hi @pascalGodfa 
You have a typo in your smtp domain.

Cheers,
gear0

**Comment by pascalGodfa** [comment]
> Hi @pascalGodfa You have a typo in your smtp domain.
> 
> Cheers, gear0

Thank so much, I didn’t notice that
But Everything is fine now.

**Comment by minochch669-hue** [comment]
@pascalGodfa please tell me how did you solve it

**Comment by viewpage0** [comment]
how can fix this Max connection attempts exceeded - dial tcp 172.397.62.108:465: i/o timeout on gophish
