### ISSUE TITLE
Add {{.email}} as a variable

### ISSUE THREAD

**Issue by betote** [gophish/gophish#306]
would be something useful add the variable "email" just like the existing variables ( url, firstname, etc.)
![screenshot 390](https://cloud.githubusercontent.com/assets/2721467/16286889/eedc9dae-38a4-11e6-9e2e-ad8d046228dd.jpg)

**Comment by jordan-wright** [comment]
My apologies for not having that documented (we'll fix that).

However, ```{{.Email}}``` is a valid template value that will give you what you're looking for.

Thanks for the report!
