### ISSUE TITLE
I'm a SPAM for Microsoft defender 

### ISSUE THREAD

**Issue by borisbecode** [gophish/gophish#3069]
Hello, I am doing an internship at a company and I plan to carry out a phishing campaign with gophish. Has anyone ever been faced with carrying out a campaign against Microsoft Defender?

I installed gophish on an Azure cloud VM, I was thinking of using mailjet as an SMTP server and I bought a shitty domain name from OVH.

None of my emails arrive in the mailbox of the company linked to Microsoft → they are directly considered by Microsoft as SPAM and do not even appear in the mailbox;

 They arrive in my gmail or outlook mailboxes, sometimes in spam, sometimes not.

We have added the domain, the IPs of the mailjet servers (too many but it was to see if the problem comes from there) as well as the url of the Azure server (`~example.com/*` for all subdomains and paths .")  **in the phishing simulation in Microsoft Defender**

btw I see a link https://example.mjt.lu, it is generated by {{.URL}} from gophish? I am not sure .

My SPF, DKIM, DMARC are correctly configured.

I see a lot of “domain reputation”, I am currently doing my tests with a .site, could this come from there? I will have a .fr later. also I have not added my domain in my Azure VM, I only use the domain as a mailbox (but my Azure url is HTTPS for example)

I'm going to try with a personal SMTP server, but no idea if that will solve the problem,

In the meantime, if any of you have an idea or have already been in a similar situation, what configuration did you have?

THANKS !!

![Analyse-image](https://github.com/gophish/gophish/assets/90902213/cfc4b5fe-854a-4559-8cc6-3396e87877c5)
![phishing-simulation-option](https://github.com/gophish/gophish/assets/90902213/8b68a3b0-c6de-405b-b6d8-24b3456982c4)
![sender-ip](https://github.com/gophish/gophish/assets/90902213/52e0a9bf-e2fe-45c5-9c8e-72d425a98fa8)

**Comment by mailo32** [comment]
hello , did you find any solution for this ? Thanks

**Comment by borisbecode** [comment]
Hello, in terms of config I use mailcow for the SMTP server and My SPF, DKIM, DMARC are correctly configured. I think it really comes from the domain reputation. 
The solution found was to whitelist the url and domain in Defender. and everything works perfectly !

**Comment by borisbecode** [comment]
it also appears that in the header of the email "gophish" is mentioned, I think that the defender AI reads this too and could be a cause of blocking if it is not whitelist. I have not tried to modify the header sent by gophish but from memory it is possible to do
