### ISSUE TITLE
Error: (i) table pages has no column named redirect_url

### ISSUE THREAD

**Issue by dhruvin917** [gophish/gophish#308]
Hey Guys,

I'm compiling from the source and I'm getting the error "(i) table pages has no column named redirect_url" whenever I try to create a new landing page and when I try to start a campaign. Any idea on how to fix it?

Thanks.

EDIT: The issue is with the gophish.db file. I'm replacing my binary install with the source. The issue goes away if I use the gophish.db from the source, but the downside to that is I would lose all my data. Is there a way to fix the .db file?

**Comment by jordan-wright** [comment]
Hmmm.... the db should have run migrations to add that column when you upgraded.

Did you move your existing gophish.db file to the new source installation folder?

**Comment by dhruvin917** [comment]
I did move the gophish.db file to the new source installation folder and the error still came up. I also tried to just replace the gophish.exe file in the original directory as well and the issue was the same.

**Comment by jordan-wright** [comment]
IIRC this was resolved in another issue. If you are still experiencing this issue, make sure you copy all the static assets (including database migration files) when upgrading gophish from source.
