### ISSUE TITLE
Post Redirect !

### ISSUE THREAD

**Issue by justuandme** [gophish/gophish#310]
is their is a way after victim login to our landing page it will redirect to any other url ?
like in normal php phish we use header ('Location:  http://abc.com');
and the user will redirect to abc.com after getting all the post variables.
if this feature is not yet added then please add this feature.
thanks

**Comment by justuandme** [comment]
i found the fix from earlier issues. # https://github.com/gophish/gophish/issues/219
thanks to : https://github.com/unsubtleguy

**Comment by jordan-wright** [comment]
Good deal! Glad you were able to get it resolved :)
