### ISSUE TITLE
reporting on "position" statistics

### ISSUE THREAD

**Issue by leonteale** [gophish/gophish#311]
You have a nice little reporting bit going on in gophish. and since you can import or use collums such as "positions" within a company. i know i have clients that wish to have a breakdown of what percentage of say the 'sales team' or the 'finance team' clicked the link or opened the email. rather than just as a whole.

Since we can export the raw results i was able to generate this information myself in a few lines of python code. i think this would be a great addition to the already great product you guys have. 

Please see the example screenshot below, the tool exports simply to csv and uses the exported 'results.csv' 

Now im not a coder so i dont think i can help really do a pull request for this sort of thing so im happy to just send you the code if you want or you can tell me how to do a request. as i would love to contribute to this software since i use it alot now. 

![gophish_possition_export](https://cloud.githubusercontent.com/assets/3170212/16376411/ff9db720-3c57-11e6-9a1c-1ebf73bdfabc.png)

**Comment by jordan-wright** [comment]
Thanks for this suggestion!

I'll probably add more modular and thorough reporting functionality later down the line, but since we can export as CSV, I'm not going to add this particular functionality for now. Anyone who needs to do custom reporting can work with the CSV results or the API as needed.

**Comment by Cycl0pe** [comment]
![screenshot-2018-5-3 test - gophish](https://user-images.githubusercontent.com/24911604/39584261-464aa846-4ef2-11e8-8a29-3139aba4153d.png)

I tried something just modifying the JS. I don't know if it can fit inside the project!
