### ISSUE TITLE
Unable to call up landing page / phishing server.

### ISSUE THREAD

**Issue by JanIT011** [gophish/gophish#3116]
What version of Gophish are you using?: 
cisagov/gophish:0.11.0-cisa.1 (https://github.com/cisagov/pca-gophish-composition/blob/develop/docker-compose.yml) on a Ubuntu

Brief description of the issue: 
Can't access the "phish-server" - accessing the Admin Inteface is not an issue. Any insights would be apreciated

I've registered a domain (lets call it gophish.mydomain.com) and pointed an A record to the IP of the server (Lets call it 5.67.890.000).
I can access the admin interface both with  5.67.890.000:3333 and gophish.mydomain.com:3333
Upon trying 5.67.890.000:3380 or gophish.mydomain:3380 I get "this site can't be reached"
In the "URL:" Field of the campaign I'm using : https://gophish.mydomain.com (Also tried: http://gophish.mydomain.com, https://5.67.890.000 and http://5.67.890.000:)
The link from a test-e-mail points to https://mydomain.gophish.com/?rid=02DNWKV (and the other permutations from http and IP tries) - however, this leads to a "Site cannot be reached" error.

Please provide any terminal output that may be relevant below:
Upon ss-tpln I get:
`LISTEN   0        4096              0.0.0.0:3380            0.0.0.0:*       users:(("docker-proxy",pid=11917,fd=4))
`
In the docker compose logs I see: 
`gophish-1        | time="2024-03-26T15:48:58Z" level=info msg="Starting phishing server at http://0.0.0.0:3380"
`
- however, thereafter there isn't a single reference to 3380 in the logs.

This is my config.json:
```
  GNU nano 4.8                                          config.json
{
        "admin_server": {
                "listen_url": "0.0.0.0:3333",
                "use_tls": true,
                "cert_path": "gophish_admin.crt",
                "key_path": "gophish_admin.key",
                "trusted_origins": []
        },
        "phish_server": {
                "listen_url": "0.0.0.0:3380",
                "use_tls": false,
                "cert_path": "gophish_admin.crt",
                "key_path": "gophish_admin.key"
        },
        "db_name": "sqlite3",
        "db_path": "gophish.db",
        "migrations_prefix": "db/db_",
        "contact_address": "",
        "logging": {
                "filename": "",
                "level": ""
        }
}
```

I've also made a change to the docker-compose.yml, that did not resolve the issue::
```
`      - target: 3333
        published: 3333
        protocol: tcp
        mode: host
      - target: 80
        published: 3380
        protocol: tcp
        mode: host
```
to:
```
`      - target: 3333
        published: 3333
        protocol: tcp
        mode: host
      - target: 3380
        published: 3380
        protocol: tcp
        mode: host
```

**Comment by JanIT011** [comment]
Ok, I just got further, but couldn't resolve this yet.

Turns out: the port is missing int he URL. 

The URL will point to gophish.mydomain/?rid=OK0DKN4 => doesnt work. However if I manually insert gophish.mydomain:3381/?rid=OK0DKN4 it does work

This is probably a really simple and stupid mistake I'm making here that I'm not aware of.

**Comment by glennzw** [comment]
Great detective work. Yeah essentially if you don't supply a port to your browser it assumes 80 or 443.
