### ISSUE TITLE
secure database user password in config.json

### ISSUE THREAD

**Issue by mac-mahon** [gophish/gophish#3119]
Hello,

I am here to seek information. I have a functional Gophish v0.12.1 infrastructure with a MariaDB database for the security of users' personal data. I am looking to "hide" the user password for the database. I tried using environment variables on Linux to test, but it is not recognized. Is there a known method for this? My config file looks like this:
```
{
	"admin_server": {
		"listen_url": "127.0.0.1:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "gophish_admin.key",
		"trusted_origins": []
	},
	"phish_server": {
		"listen_url": "0.0.0.0:80",
		"use_tls": false,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "mysql",
	"db_path": "username:password@(:port)/database?charset=utf8&parseTime=True&loc=UTC",
	"migrations_prefix": "db/db_",
	"contact_address": "",
	"logging": {
		"filename": "gophish.log",
		"level": ""
	}
}

```
 I am open to any method, script, encrypting the config.json file, etc. 
The objective is to prevent anyone accessing my system from seeing what is in the database.
Thanks in advance

**Comment by mac-mahon** [comment]
Hello, I still haven't had an answer to my question for a week. I guess there isn't one...
To answer my problem, I will use Docker with its secrets management. 
https://docs.docker.com/engine/swarm/secrets/
I'm posting this here so that the next person with the same problem can find the answer faster than me. 
Good day!

**Comment by glennzw** [comment]
That looks like a good solution. There have been other threads where people have used MySQL's standard encryption options. Please see: https://github.com/gophish/gophish/issues/2093#issuecomment-765325186
