### ISSUE TITLE
New Release Timeline?

### ISSUE THREAD

**Issue by faisalmuneer** [gophish/gophish#312]
Hi, If you could let me know if there is any timeline for the new release to come? 

Or otherwise, if you could list down the procedure to download and compile the code to incorporate all the changes so far.

Thanks.

**Comment by jordan-wright** [comment]
If you have been using a precompiled binary, the procedure to start using a version built from source is to:

* Build from source using instructions in the User Guide
* Copy your existing `gophish.db` file into the source directory
* Run `./gophish` to update your db with the migrations and start the servers. You'll be good to go from here!

As far as timeline, we'll probably be releasing a new version soon, I just don't have a firm date yet.

**Comment by faisalmuneer** [comment]
Hi, just gone through the User Guide but I think it requires *nix OS? 

Please let me know if it can be installed from source on Windows platform?

**Comment by jordan-wright** [comment]
Yes, it can absolutely be installed on Windows- just download the Go programming language and run "go get" exactly like what's shown for the nix install.

**Comment by alexlomas** [comment]
Good luck with building on Windows, it's an utter nightmare to get MinGW & gcc etc installed and working.

**Comment by faisalmuneer** [comment]
ohh then I better wait for the next release...

**Comment by Mafieww** [comment]
Hi, If you could let me know if there is any timeline for the new release to come?

Thanks
