### ISSUE TITLE
I would like to change the way {{.Tracker}}

### ISSUE THREAD

**Issue by doohyun1** [gophish/gophish#3127]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  0.12

Brief description of the issue:  
I would like to change the way `{{.Tracker}}` is transformed from `<img alt="" style="display: none" src="url">` to `<img src="url" width="3" height="3" border="0" style="border:1px solid white; display:block;">`. Could you let me know which file I need to modify to make this adjustment?"

What are you expecting to see happen? :Gophish Tracker working

What are you seeing happen?Gophish Tracker not working

**Comment by hackermade** [comment]
I have the same issue, i have created an email template but when i click a button to send me to the landing page, i get and error, which says that this page doesnt exist.

**Comment by glennzw** [comment]
The easiest way would be to include manual HTML in your template. e.g:

```
<img src="{{.TrackingURL}}" width="3" height="3" border="0" style="border:1px solid white; display:block;">
```
