### ISSUE TITLE
open attatchment event name change

### ISSUE THREAD

**Issue by leonteale** [gophish/gophish#313]
When opening an attachment, i was surprised that the portal detects this. this is good :) However, can the name be changed from Email opened. to "attachment opened". 

This creates false positives ATM especially if you have a tracking image and an attachment within the same email. im not sure if the client "accepted the image warning" or if they just opened the attachment. 

does this tracking work for all attachment types?

**Comment by jordan-wright** [comment]
What kind of attachment did you open? Chances are, gophish detected that the email was opened, since we do not currently implement attachment tracking.

**Comment by jordan-wright** [comment]
Going ahead and closing this for now. Attachment support isn't yet introduced into gophish. We're planning on making that functionality available in version 0.3.
