### ISSUE TITLE
Deleting multiple user groups, Campaigns, Landing Pages, Email Templates together with check-box 

### ISSUE THREAD

**Issue by satish23kumar** [gophish/gophish#3133]
What version of Gophish are you using?: gophish-v0.12.1

Brief description of the issue: 
Unable to delete multiple User groups, Archived campaigns, Mail Templates and Landing Pages together.

What are you expecting to see happen?
Maybe a checkbox against each item to select and delete (like in a mailbox).

**Comment by glennzw** [comment]
Hi there, thanks for reaching out. That's a good feature request. At this stage you'd need to manually do this via the database.
