### ISSUE TITLE
Redirect to Training Page or Other Site After POST Data

### ISSUE THREAD

**Issue by alexlomas** [gophish/gophish#314]
After "logging in" having fallen for the phish it would be great to be able to display a training page, or redirect to another site/page.

**Comment by jordan-wright** [comment]
If you want to host this site yourself, there is already the ability to have a "redirect url" setting when creating a landing page. See #210 for the implementation.

Let me know if this answers your question! Right now, training pages are not implemented, but are on the roadmap and being tracked separately.

**Comment by alexlomas** [comment]
Ah, ok, I don't see this in the pre-compiled version 0.1.2 as I guess that pre-dates your update.

**Comment by jordan-wright** [comment]
Yep! Right now it's in the source distro. It's about time I update binaries - I'll see if I can release a new version of the binaries this week or next :smiley: 

Thanks for the report!
