### ISSUE TITLE
When creation a user (User Management) account_block value is ignored

### ISSUE THREAD

**Issue by Caetan** [gophish/gophish#3147]
What version of Gophish are you using?: 0.12.1

Brief description of the issue: When creation a new user in User Management, the _account_block_ value is ignored, so checking it sends _account_block_: true in the POST request, but the backend sets it as false. Actually, the post response has the _account_block_: false

What are you expecting to see happen? : To keep the value and store it as it comes

What are you seeing happen? The value is always false when creating

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Go to User Management
 * Step 2 - Create a new user
 * Step 3 - Check Account Locked checkbox
 * Step 4 - Create
 * Step 5 - Edit the user. You will see the  Account Locked checkbox is unchecked

Thanks!

**Comment by ttinkywinky45** [comment]
**Hi 👽 ! If you are interested in ⚙️Advanced Phishing⚙️ and the ✨Evilginx3✨ tool then I offer you Google Gmail and Custom Phishlets (Paypal, Cryptos...) with a ✅Free Tutorial✅ which arrives if the 📈Telegram reaches 50 Subscribers📈
⏳ GOOGLE GMAIL PHISHLET 2024 WITH PROOF ⏳
 ->
⛔https://www.youtube.com/watch?v=nA47UknIE6A⛔
---
🔓 Ask your questions and a free tutorial from 50 subs on telegram !!!
->
📩https://t.me/Noremorse1011📩**

![evilginx_background](https://github.com/kgretzky/evilginx2/assets/144027798/0e448f68-ecdc-49a4-a4f4-23dbed7cb971)
