### ISSUE TITLE
Landing page unreachable with https

### ISSUE THREAD

**Issue by 2fray93** [gophish/gophish#3155]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

**What version of Gophish are you using?: **

0.12.1

**Brief description of the issue: **

After clicking on the link in the email, I'm redirected to a https page and eventually to an unreachable site error message. The landing page is reachable only if I change the URL to http://*.*.*.*/?rid=*******.

**What are you expecting to see happen? :**

The landing page, directly.

**What are you seeing happen?**

An error message.

**Please provide any terminal output that may be relevant below:**

My config.json file looks like this :

```

        "admin_server": {
                "listen_url": "0.0.0.0:3333",
                "use_tls": true,
                "cert_path": "gophish_admin.crt",
                "key_path": "gophish_admin.key",
                "trusted_origins": []
        },
        "phish_server": {
                "listen_url": "0.0.0.0:80",
                "use_tls": false,
                "cert_path": "example.crt",
                "key_path": "example.key"
        },


```

**Please provide as many steps as you can to reproduce the problem:**
 * Step 1 - I create my email template and insert {{.URL}}, choosing the http protocol. 
 * Step 2 - I launch a campaign;
 * Step 3 - I receive the email.
 * Step 4 - When clicking on the link, I get the unreachable page error.
 
 Thanks for your help.

**Comment by AndreasDickow** [comment]
you might change the url in config.json from "listen_url": "0.0.0.0:80", to "listen_url": "0.0.0.0:443", as 80 is reserved to non https Traffic only and install the required certificates.

As an alternative to get both ports working leave the config.json as is and add an Apache Server in front of it.
change apache ports.conf to only listen to port 443 
and put in place a proxy config, that also allows serving static assets over https like
<VirtualHost *:443>
...ssl certificate related settings ...

# part for proxy forwarding
<IfModule mod_proxy.c>
      ProxyPreserveHost On
      ProxyPass /static !
      ProxyPass / http://127.0.0.1:80/
      ProxyPassReverse / http://127.0.0.1:80/
   </IfModule>

# part for serving assets over https
    <Directory "/var/www/html/static">
        Options FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>
...

**Comment by 2fray93** [comment]
The first solution worked perfectly. Thanks a lot.
