### ISSUE TITLE
SMTP helo with hardcoded "localhost" flagged as spam

### ISSUE THREAD

**Issue by phocean** [gophish/gophish#317]
Hello,

I am reopening this issue as I found the root cause, which is in the NewDialer() function of the gomail
library.

See my bug report there:

https://github.com/go-gomail/gomail/issues/62

As a consequence (I quickly looked at the code), it opens SMTP connections with the hardcoded "localhost" string.

So Gophish is sending to the SMTP server:

```
helo localhost
```
Then, it shows in message sources:

```
Received: from localhost (xxx])
	by xxx
	for xxx
```

Which gets flagged by many anti-spam:

```
X-Spam-Status: No, score=4.53 ....
	...
	HELO_LOCALHOST=3.828, ...
```
See the high spam score, which is a big stopper for a real phishing campaign.

Note that I workaround this issue by monkey patching the binary (replacing with an hex editor all occurrences of localhost). It worked as expected, which confirms this issue.

I then fixed the gomail library, which also fixes the issue.

I think it is still a Gophish concern as an anti-spam solution: if it is not fixed upstream, please fork the library or use another one.

**Comment by jordan-wright** [comment]
Let me know if 5cdfcbf fixes the issue for you - should be good to go!

**Comment by phocean** [comment]
Yes, my tests confirm it is fixed. Good job, thanks :-)
