### ISSUE TITLE
Campaign not found message immediately after confirming a campaign

### ISSUE THREAD

**Issue by evanuz** [gophish/gophish#318]
Hello
Im using Mac OS X 10.11.2 (15C50) i downloaded the code from the webpage for mac. everything works ok except for campaigns, when i launch one i get a message saying campaign not found, the emails are sent and the phishing site works ok.

What can i do?

Thanks in advance

**Comment by jordan-wright** [comment]
Can you give the output that you see in the terminal when you execute and navigate to the campaign? Any information about campaign setup, etc. helps get this narrowed down.

Thanks for the report!

**Comment by evanuz** [comment]
Hey

Here is the log for the campaign and some screen captures



127.0.0.1 - - [07/Jul/2016:22:05:59 -0500] "POST /api/campaigns/?api_key=9ce1a15443128a8a984eb1651e7babda96ce865ca188976b2a47c7a6204e3aae HTTP/1.1" 201 36254 "http://127.0.0.1:3333/campaigns" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
 2016/07/07 22:05:59 worker.go:115: Creating email using template
 2016/07/07 22:05:59 worker.go:126: Sending Email to musicritif@thraml.com
127.0.0.1 - - [07/Jul/2016:22:05:59 -0500] "GET /campaigns/6 HTTP/1.1" 200 8700 "http://127.0.0.1:3333/campaigns" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
127.0.0.1 - - [07/Jul/2016:22:06:00 -0500] "GET /api/campaigns/6/results?api_key=9ce1a15443128a8a984eb1651e7babda96ce865ca188976b2a47c7a6204e3aae&{} HTTP/1.1" 404 19 "http://127.0.0.1:3333/campaigns/6" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
 2016/07/07 22:06:07 main_private.go:23: sql/Users/Justin/dev/go/src/github.com/gophish/gophish/models/campaign.go:108621.391µsINSERT INTO "events" ("campaign_id","email","time","message","details") VALUES (?,?,?,?,?) [6 musicritif@thraml.com 2016-07-07 22:06:07.475493768 -0500 CDT Email Sent ]
127.0.0.1 - - [07/Jul/2016:22:06:10 -0500] "GET /api/campaigns/6/results?api_key=9ce1a15443128a8a984eb1651e7babda96ce865ca188976b2a47c7a6204e3aae&{} HTTP/1.1" 404 19 "http://127.0.0.1:3333/campaigns/6" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
127.0.0.1 - - [07/Jul/2016:22:06:20 -0500] "GET /api/campaigns/6/results?api_key=9ce1a15443128a8a984eb1651e7babda96ce865ca188976b2a47c7a6204e3aae&{} HTTP/1.1" 404 19 "http://127.0.0.1:3333/campaigns/6" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
127.0.0.1 - - [07/Jul/2016:22:06:30 -0500] "GET /api/campaigns/6/results?api_key=9ce1a15443128a8a984eb1651e7babda96ce865ca188976b2a47c7a6204e3aae&{} HTTP/1.1" 404 19 "http://127.0.0.1:3333/campaigns/6" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
127.0.0.1 - - [07/Jul/2016:22:06:40 -0500] "GET /api/campaigns/6/results?api_key=9ce1a15443128a8a984eb1651e7babda96ce865ca188976b2a47c7a6204e3aae&{} HTTP/1.1" 404 19 "http://127.0.0.1:3333/campaigns/6" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"


Thanks!!! 
<img width="522" alt="screen shot 2016-07-07 at 10 09 56 pm" src="https://cloud.githubusercontent.com/assets/20330741/16676418/99cedf2e-448f-11e6-98c6-99108c243974.png">
<img width="780" alt="screen shot 2016-07-07 at 10 08 42 pm" src="https://cloud.githubusercontent.com/assets/20330741/16676417/99ccc6ee-448f-11e6-9510-c2823abae558.png">
<img width="1043" alt="screen shot 2016-07-07 at 10 07 47 pm" src="https://cloud.githubusercontent.com/assets/20330741/16676416/99cb8c3e-448f-11e6-8944-9c7fe7409716.png">

**Comment by jordan-wright** [comment]
What version of gophish are you running? Are you building from source?

**Comment by jordan-wright** [comment]
Hey @evanuz - just checking in, are you still experiencing this issue? If so, what version of gophish are you running? Are you building from source?

**Comment by jordan-wright** [comment]
Closing this issue as we haven't heard back in 27 days. If you continue to run into issues, please let us know the answer to our questions above and we can continue troubleshooting.

Thanks!
