### ISSUE TITLE
Mixed Content Error on Report Button in Gophish Running on Synology NAS

### ISSUE THREAD

**Issue by DDULDDUCK** [gophish/gophish#3182]
Thanks for reaching out! We're happy to help resolve issues as quickly as possible.

Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

---

**Issue: Mixed Content Error on Report Button in Gophish Running on Synology NAS**

Hello,

I have installed Gophish on a Synology NAS using Docker. Most functionalities like email opens and link clicks are working fine. However, I'm facing an issue with the "Report" button. When the "Report" button is clicked, the flag does not change, and the developer tools show a JavaScript error:

```
Mixed Content: The page at 'https://url' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://url'. This request has been blocked; the content must be served over HTTPS.
```

Here is my current `config.json` configuration:

```json
{
	"admin_server": {
		"listen_url": "0.0.0.0:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "gophish_admin.key",
		"trusted_origins": []
	},
	"phish_server": {
		"listen_url": "0.0.0.0:80",
		"use_tls": false,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": "",
	"logging": {
		"filename": "",
		"level": ""
	}
}
```

To resolve this, I added the following meta tag to the `base.html` file:

```html
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
```

However, this did not solve the issue since the phishing server does not support HTTPS. Consequently, while the report button is clickable, it does not function properly, and email links do not lead to the correct landing pages.

**Question:**

Is there a way to enable the "Report" button functionality without disrupting other features? Specifically, I need to ensure that the report button works while maintaining the functionality of email links directing to the correct landing pages.

Thank you for your assistance.

**Comment by glennzw** [comment]
Unfortunately without tweaking your browser the gophish server and admin server will need to reside on the same protocol.

If you know what you're doing you can modify your browser to allow Mixed Content for specific sites:

#### Chrome

1. **Open Developer Tools**:
   - Press `F12` or `Ctrl + Shift + I` (Windows/Linux) or `Cmd + Option + I` (Mac).

2. **Go to Security**:
   - Click on the `Security` tab in the Developer Tools panel.

3. **Temporarily Disable**:
   - You will see a message about blocked mixed content. Click on "Disable protection for now" to allow mixed content for that session.

For a more permanent solution:

1. **Access Flags**:
   - Go to `chrome://flags/#unsafely-treat-insecure-origin-as-secure`.

2. **Enable Flag**:
   - Find "Insecure origins treated as secure" and enable it.

3. **Add URL**:
   - In the text box, add the URL of the site you want to allow mixed content for, in the format `http://url`.

4. **Relaunch Browser**:
   - Restart Chrome to apply changes.

#### Firefox

1. **Open Preferences**:
   - Go to `about:config` in the address bar.

2. **Search Setting**:
   - Search for `security.mixed_content.block_display_content`.

3. **Toggle Setting**:
   - Double-click to set it to `false`.

For specific sites:

1. **Permissions**:
   - Go to the site, click the lock icon in the address bar, and open "Permissions".
   
2. **Disable Protection**:
   - Choose to disable protection for the specific site.

**Comment by DDULDDUCK** [comment]
It was perfectly resolved with your response. Thank you so much.
