### ISSUE TITLE
Users Control 

### ISSUE THREAD

**Issue by acassio22** [gophish/gophish#319]
Hello,

Very good framework!

I would like to make a suggestion, could add the function to control access and users viewing? and also create users groups?

So it would be closest to a SaaS platform.

Again, thank you for the great job!

**Comment by jordan-wright** [comment]
Hi @acassio22 - thanks for this suggestion! RBAC and "team" functionality is on our roadmap for a later release (since this is a big feature to implement) and is being tracked via #10.

I'm going to go ahead and close this one out as a duplicate. Keep the ideas coming!
