### ISSUE TITLE
Attempt to write a readonly database

### ISSUE THREAD

**Issue by nclaypool** [gophish/gophish#321]
Not entirely sure why this started all of a sudden, I haven't changed anything in the directory that GoPhish is installed in. I thought maybe this was a file permissions error, tried adding Everyone with full permissions to the SQL files but that didn't help either. This occurs when trying to saving new or editing existing items regardless of location.

Viewing the log output on gophish.exe I see the following entries.
TIMESTAMP smtp.go:73: record not found
TIMESTAMP smtp.go:88: attempt to write a readonly database

I'm perplexed.

**Comment by jordan-wright** [comment]
Hmmm... No idea why this is happening. You might check to see what processes have the database open. If it's only gophish, I would recommend restarting the server.

**Comment by nclaypool** [comment]
I'm such an idiot! 
Forgot to launch the GoPhish.exe as an administrator on the server. Did that and it works fine, its been a while since I've used so I forgot about that.
