### ISSUE TITLE
SSL Certificat 

### ISSUE THREAD

**Issue by Josh9657** [gophish/gophish#3211]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.12.1

Brief description of the issue: 
I use gophish on **Kali Linux**
I obtained an ssl certificate with zerossl, 
the files are in the same location as the original files /var/lib/gophish
file1.crt and file2.key
I also reconfigured the config.json but I cannot access the site 
port 443 is open on the router
content of the json file: 
{
        "admin_server": {
                "listen_url":"127.0.0.1:3333",
                "use_tls": true,
                "cert_path": "/var/lib/gophish/gophish_admin.crt",
                "key_path": "/var/lib/gophish/gophish_admin.key",
                "trusted_origins":[]
        },
        "phish_server": {
                "listen_url": "0.0.0.0:443",
                "use_tls": true,
                "cert_path": "/var/lib/gophish/domainame.crt",
                "key_path": "/var/lib/gophish/domainname.key"
        },
        "db_name": "sqlite3",
        "db_path": "/var/lib/gophish/gophish.db",
        "migrations_prefix": "db/db_",
        "contact_address": "",
        "logging": {
                "filename": "",
                "level": ""
        }
}

What are you expecting to see happen? : that the portal works

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by poooldo** [comment]
Please provide the messages in the log to see what's happening

**Comment by Josh9657** [comment]
> Veuillez fournir les messages dans le journal pour voir ce qui se passe

it's good for me :)
thank for your help
