### ISSUE TITLE
Gophish arrives to spam

### ISSUE THREAD

**Issue by Yusefwinstrol** [gophish/gophish#3212]
Hi, im trying to do a campaign, but all the emails arrives to spam. I tried to install postfix for use together, but i cant resolve that. What can i do for resolve this problem? 
I have Gophish and Postfix in a virtual machine on Azure. I don't know if there are other option to do this.
I decided install postfix for configure SPF, DMARC and  DKIM protocols.

**Comment by jordan-wright** [comment]
Hi there!

This FAQ entry is the only guidance we can provide on this topic: https://docs.getgophish.com/user-guide/faq#how-to-bypass-spam-filters
