### ISSUE TITLE
Máximo de tentativas de conexão excedido - 535 5.7.139

### ISSUE THREAD

**Issue by fabianotecnol** [gophish/gophish#3220]
Máximo de tentativas de conexão excedido - 535 5.7.139 Autenticação malsucedida, a solicitação não atendeu aos critérios para ser autenticada com sucesso. Entre em contato com seu administrador. [MN2PR07CA0004.namprd07.prod.outlook.com 2024-08-13T18:27:55.030Z 08DCBB430284475F]

**Comment by jordan-wright** [comment]
Isso indica um problema com a autenticação SMTP. Provavelmente as credenciais estão incorretas.

Sem mais informações, não poderemos ajudar a solucionar o problema, pois isso parece ser um problema com as credenciais que estão sendo usadas ou com seu serviço SMTP.

(Desculpas por quaisquer problemas de tradução - usei translate.google.com).
