### ISSUE TITLE
Maximum number of users

### ISSUE THREAD

**Issue by sexD** [gophish/gophish#323]
I wonder what the maximum number of users per campaign are? I sent to a campaign of 1000 users, it says that all emails have been sent but no clicks are registered. Is this due to the big amount?

Regards

**Comment by jordan-wright** [comment]
Hmm.... Can the users reach the gophish server? Sounds like either you have **super** good users, or there was a broken link somewhere :smile: 

There is no known maximum limit to the number of users in a gophish campaign.

Hope this helps! You might include yourself in the next campaign to make sure you can reach the gophish server. Let me know if you have any other questions - for now I'm going to go ahead and close this out.
