### ISSUE TITLE
error：gofish 501 mail from address must be same as authorization user.

### ISSUE THREAD

**Issue by KIKI-flower** [gophish/gophish#3243]
I would like to test phishing emails using GoPhish, but I encountered an error when sending the test email: "501 mail from address must be the same as the authorization user." Is this an issue because I am using a QQ email account? How can I resolve this?
![image](https://github.com/user-attachments/assets/455e170c-e257-4d77-8baa-10db3b670503)

**Comment by jordan-wright** [comment]
Hi! This is an error from your SMTP provider. I would reach out to your SMTP admin to help troubleshoot this, as I anticipate it's an error with how the outbound emails are being structured. This is likely a security setting explicitly to prevent phishing.

Since this does not appear to be an issue within Gophish I'm going to close this one out.

**Comment by KIKI-flower** [comment]
Thank you very much for your explanation. After a whole night of attempts, I figured out my issue. Some tutorials online suggested configuring the "SMTP From" in "New Profiles" in the format of xxxx<***@***.***> However, when sending a test email, I encountered a 501 error. The correct configuration requires changing it to ***@***.***, which prevents the error. Once again, thank you for your help!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gophish/gophish"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月23日(星期一) 中午11:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gophish/gophish] error：gofish 501 mail from address must be same as authorization user. (Issue #3243)





 
Hi! This is an error from your SMTP provider. I would reach out to your SMTP admin to help troubleshoot this, as I anticipate it's an error with how the outbound emails are being structured. This is likely a security setting explicitly to prevent phishing.
 
Since this does not appear to be an issue within Gophish I'm going to close this one out.
