### ISSUE TITLE
Certificate signed by unknown authority

### ISSUE THREAD

**Issue by rajvi7493** [gophish/gophish#325]
When i am testing SMTP option by giving SMTP server and test mail details, error will come " Certificate signed by unknown authority"

**Comment by jordan-wright** [comment]
What version of gophish are you using? I believe 0.1.2 is the version that started allowing you to ignore cert errors. If you don't see it, try building from source.

Hope this helps!

**Comment by rajvi7493** [comment]
Issue still persist, after using v0.1.2. Can you please help me out?

**Comment by jordan-wright** [comment]
Try building from source - I believe the feature you are requesting has not been released yet, but it in the developer branch.

**Comment by jordan-wright** [comment]
Can you send a screenshot of what you see when the error occurs? I'll need the screenshot of the entire window.

Thanks!

**Comment by rajvi7493** [comment]
Hi,
Please find the attached.

**Comment by jordan-wright** [comment]
It appears you may have forgotten to upload the screenshot.

**Comment by rajvi7493** [comment]
I uploaded the screenshot.

**Comment by jordan-wright** [comment]
I still don't see any screenshots in your comment.

Could you please try uploading it again?

**Comment by jordan-wright** [comment]
Hi @rajvi7493 - I still have not seen a screenshot of the issue. I'm going to go ahead and close this out for now, but can reopen if, after receiving a screenshot, can confirm there is an issue.

Thanks!

**Comment by jumarko** [comment]
@jordan-wright I'm getting a similar error now when trying to setup gophish with AWS SES:

![Image](https://github.com/user-attachments/assets/0130c92b-66c0-4b27-9cc1-808e137d2669)

This works just fine with openssl
```
openssl s_client -crlf -quiet -connect email-smtp.eu-central-1.amazonaws.com:465 < test-email.txt
Connecting to 3.126.224.62
depth=2 C=US, O=Amazon, CN=Amazon Root CA 1
verify return:1
depth=1 C=US, O=Amazon, CN=Amazon RSA 2048 M01
verify return:1
depth=0 CN=email-smtp.eu-central-1.amazonaws.com
verify return:1
220 email-smtp.amazonaws.com ESMTP SimpleEmailService-d-WR03JDBYC nGHcR7mucjAbXzvfgjTs
250-email-smtp.amazonaws.com
250-8BITMIME
250-AUTH PLAIN LOGIN
250 Ok
334 VXNlcm5hbWU6
334 UGFzc3dvcmQ6
235 Authentication successful.
250 Ok
250 Ok
354 End data with <CR><LF>.<CR><LF>
250 Ok 0107019735fce523-2f150ded-81d7-428e-8eb3-492a95b54f7a-000000
^C

```

Anything I'm missing? 

NOTE: If I enable `Ignore Certificate Errors` then the test email is sent properly.
