### ISSUE TITLE
How to catch users that open their email at home or from external

### ISSUE THREAD

**Issue by FebruarySilver** [gophish/gophish#326]
Hi Jordan,

I can catch the internal easily but external users cant seem to go back to my server. I tried making it public but there is only one listen_url to config.json for both admin and listening server. changing the value of IP making it to public does not allow by the system, error in bind as if it only accepts it local IP. Please help me.

**Comment by jordan-wright** [comment]
You'll need to make the `phish_server` listen_url IP either external or "0.0.0.0" and you'll need to setup port forwarding on your firewall to allow external connections.

The other option is to host gophish on a public VPS, which works for a bunch of folks.

Hope this helps!
