### ISSUE TITLE
Randomize who to send emails to

### ISSUE THREAD

**Issue by N-Engelmann** [gophish/gophish#3263]
Hey,

first of all great thing you built there.

I wanted to ask if it is possible to randomize the order in which the people get emails.
My list is in alphabetical order and I just realized that gophish will send to Person A but A has 2 mails and now that person will get basically the frst 2 emails 1pm and then 3 pm.
I want that people get an mail on every email they have.

If you have any question or i should specify something let me know ^^.

**Comment by guisithos** [comment]
Issue #3167 has the same request. Ive asked to get me this assigned so I could try to get a look into.
