### ISSUE TITLE
Chrome only marks the Gophishing link as a Dangerous Site.

### ISSUE THREAD

**Issue by atasoyhk** [gophish/gophish#3277]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  v 0.12.1 (windows)

Brief description of the issue: Chrome only marks the Gophishing link as a Dangerous Site.

What are you expecting to see happen? : I think Chrome caught it from the link after the last update. That's why the ? in the ?pid= section in the link. Changing or removing the sign or changing this part.

What are you seeing happen?

![image](https://github.com/user-attachments/assets/7e382ca9-e02f-49af-8132-1696bd8a76e1)
https://prnt.sc/HbTCwPNuy6Vp

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by wand3rlust** [comment]
@atasoyhk Chrome detects the patterns in URLs and other files (say JS or CSS) along with other metrics and then corelates them with Google's internal threat database. So if anyone is using the default configuration, it's bound to be detected sooner or later.

To prevent this sort of issues, customize your infrastructure and lure as much as possible with OpSec in mind.

**Comment by atasoyhk** [comment]
@wand3rlust Thanks for the reply. What do you mean by customization? Do you mean customization of the software? Or is it the customization of the scenario to be applied? It would be more understandable for me if you give an example on this subject.

**Comment by atasoyhk** [comment]
.

**Comment by wand3rlust** [comment]
@atasoyhk, customization means few things here.

1. Customization of the source code to remove the baked IoCs
2. Configuration of the deployed Gophish
3. Hardening of the infrarstructure where the Gophish is deployed
4. Setting the testing stage (browser, test email, etc) to prevent burning the domain

Hope these will give you some ideas for your next engagement.
