### ISSUE TITLE
Recover deleted campaign

### ISSUE THREAD

**Issue by Th4n0s** [gophish/gophish#328]
Hello,

As I was creating a new campaign, I accidentally deleted one of my campaigns... Is there a way to recover it?

Thanks in advance for any help/advice.

**Comment by jordan-wright** [comment]
I'm afraid there is no way to recover a deleted campaign. The wording on the prompt in the latest source version is more clear with this, saying that the action cannot be undone.

I apologize for the inconvenience! I recommend setting up an automated job to take backups of the gophish.db file if you are concerned this might happen again in the future.

**Comment by Th4n0s** [comment]
Thanks for the reply Jordan.
Likely previous versions did the trick and I was able to restore the db file. A lesson to be learned though.
