### ISSUE TITLE
Attachments will not send from a campaign

### ISSUE THREAD

**Issue by hpscrappy** [gophish/gophish#329]
Attachments are not being sent in the campaign e-mails, however they will attach when sent as a test email. This was built from source pulled today.

**Comment by ustayready** [comment]
Same prob here.. troubleshooting it now

**Comment by jordan-wright** [comment]
Thanks for this report! I'll fix this tonight.

**Comment by hpscrappy** [comment]
any luck in getting this resolved?

**Comment by jordan-wright** [comment]
Should be fixed now - if you could, please give it a shot and let me know if you run into any issues.

Thanks for the report!
