### ISSUE TITLE
How can i check logs of running campaigns

### ISSUE THREAD

**Issue by amol7111** [gophish/gophish#330]
Hi

i am able to send the mails through gophish, but as i click on the link provided in to the mail it says page can not be displayed. how can i check logs to get the exact issue

Thank you
Amol mhaske

**Comment by jordan-wright** [comment]
Hi there,

If you copy/paste the output from your terminal into the issue, then we can troubleshoot.

Also, what version of gophish are you using? Are you building from source?

**Comment by jordan-wright** [comment]
Just checking in on this, can you copy/paste the output from your terminal into the issue? If so, we can troubleshoot further.

Thanks!

**Comment by jordan-wright** [comment]
Closing this issue as we have not heard back in a week. If you continue to have trouble, please respond back with the terminal output reproducing the issue and we can continue troubleshooting.

Thanks!
