### ISSUE TITLE
Sqlite database locked

### ISSUE THREAD

**Issue by neumama5** [gophish/gophish#331]
About two month ago I launched a large testing phishing campaign for more than 6000 people (The campaign was hosted on a VM machine with 4 cores and 8GB RAM + 2GB swap). During the period which we sent the emails (around 30 mins), some users attempted to visit the phishing landing page.
In this time I was able to see in activity logs of gophish that some of the users were receiving 404 error page. This page was shown to users due to locked database. 
 ![screen shot 07-29-16 at 11 07 am](https://cloud.githubusercontent.com/assets/20705422/17243374/c1e8e614-557c-11e6-9238-3b538c6b3936.PNG)
On further investigation,  it seems that gophish is not able to handle multi-thread access to the underlying DB for queries.
R.g.:
`err = db.Table("pages").Where("id=?", c.PageId).Find(&c.Page).Error
if err != nil {
                if err != gorm.ErrRecordNotFound {
                        return err
                }
                c.Page = Page{Name: "[Deleted]"}
                Logger.Printf("%s: page not found for campaign\n", err)
}`
I carried out performance testing and created a  workaround which can be adding the following line in the file (models. go):
`db.DB().SetMaxOpenConns(1)`
Is it possible that gophish will support multiple access to DB in the future or is it planned to fix this by supporting different DB than SQLite (through germ library)?

Many thanks in advance for your response.
Martin

**Comment by jordan-wright** [comment]
Interesting - thanks for the heads up! I'll review this and will get back to you.

For now, gophish only supports the sqlite database. It is possible that we will support others in the future. You can track any progress through #53

**Comment by jordan-wright** [comment]
Everything I'm seeing shows this to be the fix as well, so I rolled it out. Let me know if that addresses the issue for you!

Thanks again for the thorough investigation - it's much appreciated. :smile:
