### ISSUE TITLE
Secure cookies

### ISSUE THREAD

**Issue by tonivanremortel** [gophish/gophish#333]
Hi,

One of my colleagues has set up a Gophish server (version 0.1.2) based on your documentation.
For security he configured a certificate to be used by the web UI.

When I scan the server for security issues, I get 1 high severity vulnerability:
_
> **Vulnerability Detection Result:**
> 
> **The cookies:**
> Set-Cookie: csrf_token=vuR4Fz5xxxxxxxxxxxxxxxxxxxxxxxxxr1WdFJlBI+qNo=; Max-Age=31536000 
> are missing the httpOnly attribute.
> 
> **Affected Software/OS:**
> Application with session handling in cookies.
> 
> **CVSS Base Vector:**
> AV:N/AC:L/Au:N/C:P/I:N/A:N
> 
> **Insight:**
> The flaw is due to a cookie is not using the 'httpOnly' attribute. This
> allows a cookie to be accessed by JavaScript which could lead to session hijacking attacks.
> 
> **Summary:**
> The application is missing the 'httpOnly' cookie attribute
> 
> **Solution:**
> Set the 'httpOnly' attribute for any session cookies.
> 
> **Vulnerability Detection Method:**
> Check all cookies sent by the application for a missing 'httpOnly' attribute
> 
> **Impact:**
> Application
> 
> **References:**
> https://www.owasp.org/index.php/HttpOnly
> https://www.owasp.org/index.php/Testing_for_cookies_attributes_(OTG-SESS-002)
> 
> **CVSS Base Score: 5.0**
_ 

I'm assuming that this can only be fixed in your code?
Best to have a look at it.

Thanks!

**Comment by jordan-wright** [comment]
Sure, why not. I've thought about doing this before but it always got put on the back burner. Should be fixed now :smile: 

Thanks for the report!
