### ISSUE TITLE
Add documentation on using CA signed SSL certs

### ISSUE THREAD

**Issue by Johnvvu** [gophish/gophish#334]
Can you add documentation on how to add CA signed certs and the steps to use the certificate chains and keys?

**Comment by jordan-wright** [comment]
Hi @Johnvvu,

I'm afraid we won't be adding specific documentation on how to setup CA signed certificates and keys, as this is out of the scope of gophish.

We already take the step of showing how to generate self signed certs in our User Guide, but anything beyond that, you will need to consult online documentation for the proper way to generate those certs.

At the end of the process, you will still have a cert and a key - both of which can be used with gophish the same way as we show with self-signed certs.

**Comment by Johnvvu** [comment]
Hi Jordan,

Please call me at 704-621-0639. I have a problem with GoPhish that I need to talk to you about. 

In the meantime, please click on this link to read more...just joking.   I do need to speak to you though when you have a few minutes.

John

**Comment by jordan-wright** [comment]
Hey John,

I'm afraid I don't provide phone support. My time is very limited and there simply isn't time to reach out to everyone personally.

Please add any issues to our Github issues and we will get back to you as soon as possible.

Thanks!
Jordan
