### ISSUE TITLE
Captured Data

### ISSUE THREAD

**Issue by hpscrappy** [gophish/gophish#335]
Data is not being captured on the landing pages. Also I do not see the User agent string.

![image](https://cloud.githubusercontent.com/assets/20582822/17520063/4d913f48-5e1c-11e6-9083-c2c56379c792.png)

**Comment by hpscrappy** [comment]
this was pulled today and built from source....thanks.

**Comment by jordan-wright** [comment]
Well that's interesting - the credential replay functionality shouldn't show up for "Click Link" events.

What URL did you clone?

Also, all the user agent and ip info are in the raw logs that you can export as CSV.

**Comment by hpscrappy** [comment]
Github.com gophosh gophish

**Comment by jordan-wright** [comment]
No, I meant what url for the landing page. What does your landing page html look like? 😄

**Comment by hpscrappy** [comment]
https://www.facebook.com/login/

i imported this page to test

**Comment by jordan-wright** [comment]
I'd be interested to hear more about your exact workflow. I just created a landing page from importing that url and everything worked fine. Creds were captured, and the dashboard showed what I would expect.

You might try clearing cache to make sure you have the latest JS files? Can you confirm that if you go to the "Settings" page you see "0.2alpha" as the version?

**Comment by hpscrappy** [comment]
i had the right version, so i rebuilt it and it started working fine I did notice however the tracker image checkbox doesn't work and password capture is not saving.

thanks

**Comment by jordan-wright** [comment]
The email tracking was fixed in #361. Let me know if you run into any issues!
