### ISSUE TITLE
Must execute gophish binary from install directory?

### ISSUE THREAD

**Issue by anance25** [gophish/gophish#337]
Hi, i have the latest pre-built binary installed in /usr/bin/gophish on an ubuntu 14.04 LTS box.

When i execute the gophish binary while my working directory is the gophish directory, it executes perfectly:
```
neo@ubuntu14:/usr/bin/gophish$ sudo ./gophish
 2016/08/10 09:50:28 worker.go:38: Background Worker Started Successfully - Waiting for Campaigns
goose: no migrations to run. current version: 20160227180335
 2016/08/10 09:50:28 gophish.go:59: Starting admin server at http://127.0.0.1:3333
 2016/08/10 09:50:28 gophish.go:71: Starting phishing server at http://0.0.0.0:80
```

However, when i try to execute the gophish binary while my working directory is anywhere else, it will not run:
```
neo@ubuntu14:~$ sudo /usr/bin/gophish/gophish
File error: open ./config.json: no such file or directory
 2016/08/10 09:50:45 models.go:84: no valid version found
no valid version found
 2016/08/10 09:50:45 gophish.go:71: Starting phishing server at http://
 2016/08/10 09:50:45 worker.go:38: Background Worker Started Successfully - Waiting for Campaigns
 2016/08/10 09:50:45 gophish.go:59: Starting admin server at http://
 2016/08/10 09:50:45 gophish.go:60: listen tcp :80: bind: address already in use
```

The "address already in use" error cant be correct because netsat output indicates that port 80 is not in use.  The file error seems to indicate that the process is trying to open config.json using a relative path, rather than an absolute path.

Is this intended functionality?  Im evaluating gophish for long-term usage, and we will want to daemon-ize gophish in some way.  Executing the binary in the context of the precise folder that it is installed in will be a bit cumbersome.  

Thanks

**Comment by jordan-wright** [comment]
Hi there!

Yes, gophish currently has two paths that are hardcoded - the path to `config.json` and the path to the `static/` directory. For now, gophish must be executed from it's current directory.

I've heard of people having luck daemonizing gophish on windows using nssm. Making this happen on linux distros should be even simpler.

Hope this helps!

**Comment by doktor1360** [comment]
This will get it done - not perfect by any means but it works like a champ...

Filename : /etc/init.d/gophish
==========
#!/bin/bash
# /etc/init.d/gophish
# initialization file for stop/start of gophish application server
#
# chkconfig: - 64 36
# description: stops/starts gophish application server
# processname:gophish
# config:/opt/goapps/src/github.com/gophish/gophish/config.json

# define script variables

processName=Gophish
process=gophish
appDirectory=/opt/goapps/src/github.com/gophish/gophish
logfile=/var/log/gophish/gophish.log
errfile=/var/log/gophish/gophish.error

start() {
    echo 'Starting '${processName}'...'
    cd ${appDirectory}
    nohup ./$process >>$logfile 2>>$errfile &
    sleep 1
}

stop() {
    echo 'Stopping '${processName}'...'
    pid=$(/usr/sbin/pidof ${process})
    kill ${pid}
    sleep 1 
}

status() {
    pid=$(/usr/sbin/pidof ${process})
    if [[ "$pid" != "" ]]; then
        echo ${processName}' is running...'
    else
        echo $processName' is not running...'
    fi
}

case $1 in
    start|stop|status) "$1" ;;
esac
==========

Have fun... peace

**Comment by aukhan288** [comment]
@jordan-wright
Hi,
I deployed gophish on vps. it working fine but when i close ssh then gophish also stop working.
how i can keep runing gophish after closing ssh

**Comment by catx0rr** [comment]
@aukhan288

Try using [nohup](https://www.digitalocean.com/community/tutorials/nohup-command-in-linux) command. this will make the executable run in background even you exit ssh. You can also redirect the stderr and stdout into a file.
