### ISSUE TITLE
Sending Attachments Quit Working

### ISSUE THREAD

**Issue by ustayready** [gophish/gophish#338]
Sending attachments originally worked before I pulled in https://github.com/gophish/gophish/pull/260 and merged. After trying to back out the merge I ended up just wiping the entire installation, removed the jli53 installation, and reinstalled GoPhish from scratch but now it seems even though Add Files attaches the files to the Email Templates and the content is making it into the database, it's not being attached to the sent emails. No clue what else could have changed on the server.

**Comment by ustayready** [comment]
Further testing shows the attachments are successfully sent when using "Send Test Email"

**Comment by jordan-wright** [comment]
Are you building from source? I fixed the attachment sending issue in campaigns a while back and confirmed it worked just fine in a recent test.

Could you confirm that you are building from source and that if you navigate to the settings page you see the version as "0.2alpha"?

**Comment by ustayready** [comment]
I am building from source.

Hmm.. settings page isn't listing the version but the readme.md is listing it as 0.1.2 along with git tags:
```
$ git tag
v0.1
v0.1.1
v0.1.2
```
Weird, I reinstalled straight from the repo. What is the best way for me to upgrade when building from source using go?

**Comment by jordan-wright** [comment]
If you don't see the version on the settings page, chances are you have an older version.

Try running "go get -u github.com/gophish/gophish"

That should update the software. Then you'll want to run "go build" to generate the new binary.

**Comment by ustayready** [comment]
Worked perfect! Thanks. Sorry for wasting your time.

**Comment by jordan-wright** [comment]
No such thing - all reports are good reports.

Thanks for getting in touch!
