### ISSUE TITLE
Export Results as CSV From UI

### ISSUE THREAD

**Issue by jordan-wright** [gophish/gophish#34]
It shouldn't take an API expert to grab the results into a usable CSV format.

![image](https://cloud.githubusercontent.com/assets/1317288/10265469/6de151f8-69f7-11e5-8ae6-197a2318585c.png)

Specifically, the "Export" option should allow for CSV exporting of campaign results.

**Comment by jordan-wright** [comment]
Related to #56, since the datatables buttons can help out with this.

**Comment by richardontheinternet** [comment]
Export options, possible selection of export format. Can you customise a basic report with options in the setting like company logo in paid version and then parse it to a PDF or HTML page? This will be a HIGHLY profitable idea as it will enable local Joe Bloggs IT company to issue phishing reports with hardly any effort.

**Comment by jordan-wright** [comment]
@rfdevere, you bet! I'm hoping to integrate a full reporting engine at some point, though you're correct - it will likely be an enterprise version :smile: 

For now, I've add the CSV export capability so once I merge, this particular issue will be closed. I'll be opening other issues in the future to handle things like branding and other file type exports.
