### ISSUE TITLE
 attempt to write a readonly database

### ISSUE THREAD

**Issue by jakfrost84** [gophish/gophish#340]
I have started the script using "sudo Sudo nohup ./gophish &" so I can close the session and keep it running. After doing that I recive the error "attempt to write a readonly database" when modifying the campaigns (email templates, users, landing page, etc.)

**Comment by jakfrost84** [comment]
* "sudo nohup ./gophish &"

**Comment by jakfrost84** [comment]
2016/08/15 08:39:26 main.go:690: log/home/user/go/src/github.com/gophish/gophish/models/campaign.go:117attempt to write a readonly database

**Comment by jordan-wright** [comment]
hmm... I'm not really sure what would cause that. You might try running gophish in something like `screen` and seeing if that will take care of your use case? I know it's not ideal, but it might work for now since I have a ton of stuff to fix in gophish and very limited time :smile:

**Comment by jakfrost84** [comment]
I will give that a shot and let you know. I understand its looking and
functioning great other than that! Im just starting getting into pentesting
and so far the best open sourced I have used. Keep up the good work and if
you need any testing or suggestions please let me know.

Thanks!

**Comment by ustayready** [comment]
@jakfrost84 congrats on getting involved into pentesting! It's always great to hear this kind of news. Regarding your background process, have you thought about using supervisord? It's pretty easy to get started with and all you have to do is create a config file, set the path to gophish, and launch it. :) It's what I use.

- Mike

**Comment by jakfrost84** [comment]
@ustayready Thank you for the suggestion! I will give that a shot.

**Comment by jakfrost84** [comment]
@ustayready I have installed supervisord created the config file but I am getting  errors regarding can't find command and no tty present.  I apologize that I am new to this.  I will continue researching but figured you may be able to explain what I am doing wrong. 

[program:GoPhish]
command=./gophish
directory=/home/user/go/src/github.com/gophish/gophish/
autostart=true
autorestart=true
startretries=3
stderr_logfile=/var/log/gophish/gophish.err.log
stdout_logfile=/var/log/gophish/gophish.out.log
user=user
enviroment=SECRET_PASSWORD= 'sudo password'

**Comment by ustayready** [comment]
@jakfrost84 So it can't find the gophish command probably because its not in the $PATH environment for the user that supervisord is executing as. A quick fix is to put the absolute path instead of just calling the command. so for the command use /home/user/go/src/github.com/gophish/gophish/gophish

After changing that, let me know if the tty present problem still exists.

Try this config:
```
[supervisord]
logfile=/tmp/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/tmp/supervisord.pid
nodaemon=false
minfds=1024
minprocs=200

supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:gophish]
command=/home/user/go/src/github.com/gophish/gophish/gophish
numprocs=1
autostart=true
autorestart=unexpected
user=user
```

**Comment by jakfrost84** [comment]
User@GoPhish:~$ sudo supervisorctl
gophish                          FATAL      Exited too quickly (process log may have details)


LOG:
File error: open ./config.json: no such file or directory
 2016/08/18 14:18:01 models.go:84: no valid version found
no valid version found
 2016/08/18 14:18:01 gophish.go:71: Starting phishing server at http://
 2016/08/18 14:18:01 gophish.go:72: listen tcp :80: bind: permission denied
File error: open ./config.json: no such file or directory
 2016/08/18 14:18:02 models.go:84: no valid version found
no valid version found
 2016/08/18 14:18:02 gophish.go:71: Starting phishing server at http://
 2016/08/18 14:18:02 gophish.go:72: listen tcp :80: bind: permission denied
File error: open ./config.json: no such file or directory
 2016/08/18 14:18:05 models.go:84: no valid version found
no valid version found
 2016/08/18 14:18:05 gophish.go:71: Starting phishing server at http://
 2016/08/18 14:18:05 gophish.go:72: listen tcp :80: bind: permission denied
File error: open ./config.json: no such file or directory
 2016/08/18 14:18:08 models.go:84: no valid version found
no valid version found
 2016/08/18 14:18:08 gophish.go:71: Starting phishing server at http://
 2016/08/18 14:18:08 gophish.go:72: listen tcp :80: bind: permission denied



[supervisord]
logfile=/tmp/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/tmp/supervisord.pid
nodaemon=false
minfds=1024
minprocs=200

supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:gophish]
command=/home/comstar/go/src/github.com/gophish/gophish/gophish
numprocs=1
autostart=true
autorestart=unexpected
startretries=3
stderr_logfile=/var/log/gophish/gophish.err.log
stdout_logfile=/var/log/gophish/gophish.out.log
user=User
enviroment=SECRET_PASSWORD= "Sudo Password"

**Comment by ustayready** [comment]
So.. looks like you are trying to bind to port 80 which is a privileged port that only root/sudo can do. Because you are launching gophish as a regular user, it won't be able to bind to that port by default. I'd encourage a higher port to avoid risks. Also, I just cd into the directory of supervisord.conf (which is in my gophish directory) and execute:

`sudo supervisord --configuration supervisord.conf`

Give that a shot!

**Comment by jakfrost84** [comment]
I am missing something here or just my luck.....I don't want to waste your time anymore so my apologies.  Just an update after running the suggest command using the specified config. 


Error: Another program is already listening on a port that one of our HTTP servers is configured to use.  Shut this program down first before starting supervisord.

**Comment by ustayready** [comment]
No problem at all! 

So, something is already binding to port 80 so gophish can't listen using that port. 

```
$ sudo netstat -tulpn | grep ':80'
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      915 apache2
$ sudo ls -la /proc/915/exe
lrwxrwxrwx 1 root root 0 Aug 18 01:39 /proc/915/exe -> /usr/sbin/apache2
```

You will either need to kill whatever process has port 80 bound open or set your admin_server and phish_server in config.json to a different port. 

Hope that helps! Let me know if you have any problems.

Mike

**Comment by jakfrost84** [comment]
I already looked at that and nothing is running.... I also changed the port to a higher number.  Everything works with no issue if just running the script from the directory.  

```
User@GoPhish:~$ sudo netstat -tulpn

Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      905/sshd
tcp6       0      0 :::22                   :::*                    LISTEN      905/sshd
```

Thank you,

Paul

**Comment by ustayready** [comment]
Are you in the same directory as the gophish binary and config.json when you execute supervisord?
Who owns the directory/files of the gophish directory and what are the rwx permissions of user/group?
Is the user that's set in the supervisord config the same user that owns the gophish files?
When switching to a higher port, are you using a port > 1024?
When running supervisord, does it background as normal (i.e. do you see a process running)?

**Comment by jakfrost84** [comment]
@ustayready FIXED! Thank you very much for all your help!

I removed the environment line and changed the user to root and everything started up properly. 

`user=user
enviroment=SECRET_PASSWORD= 'sudo password'`

**Comment by jordan-wright** [comment]
Awesome! Glad you got this worked out. I'll go ahead and close this issue out for now.

Great work @jakfrost84 and @ustayready!
