### ISSUE TITLE
Anonymize statistics

### ISSUE THREAD

**Issue by raymontag** [gophish/gophish#341]
Hi,

I would like to use gophish for a customer but I got the requirement that nobody (incl. myself) should be able to see who actually clicked on the phishing link (probably a very german thing as privacy and employee protection is really important to us).

I already wrote a small solution in Python to do this: I generated an UUID for each sended mail and only saved this one but not which mail belongs to which UUID.

Maybe you find this feature interesting and will implement it. I would really like to use gophish in future if I meet this requirements again (what will happen for sure) :)

**Comment by jordan-wright** [comment]
Great suggestion! We actually have an issue open for this in #258 so we'll track progress through that issue.
