### ISSUE TITLE
API GET /groups/ targets and /templates/ attachments don't have id

### ISSUE THREAD

**Issue by pkhxcp** [gophish/gophish#342]
The response I receive for groups is 

```
{
  "id":xxxx,
  "name": "xxxx",
  "modified_date": "xxxx",
  "targets": [
    {
      "first_name": "xxxx",
      "last_name": "xxxx",
      "email": "xxxx",
      "position": "xxxx"
    }
  ]
}
```

and for templates is 

```
{
    "id": xxxx,
    "name": "xxxx",
    "subject": "xxxx",
    "text": "xxxx",
    "html": "xxxx",
    "modified_date": "xxxx",
    "attachments": [
      {
        "content": "xxxx",
        "type": "xxxx",
        "name": "xxxx"
      }
    ]
  }
```

The [API documentation](https://github.com/gophish/gophish/blob/master/templates/gophish.apib) says that id is required, but it is not shown via API GET request.

**Comment by jordan-wright** [comment]
I guess I'm not sure what you're looking for. There are two options with the API:

`GET /groups/` - Get all groups
`GET /groups/:id` - Get specific group by ID.

Both endpoints should return the ID in the returned response.

**Comment by pkhxcp** [comment]
Sorry if I wasn't clear. This was in the API docs:

```
Each target contains the following attributes:
+ id: 1 (required, number) - Unique identifier
+ first_name: John - First name of Target
+ last_name: Doe - Last name of Target
+ email: john.doe@example.com - Email address of Target
+ position: System Administrator - Company position of the Target
```

The only way to get targets is to call GET /groups/ but the response doesn't give the targets' ids.
Same thing for attachments. The only way to get attachments is to call GET /templates/ but the response doesn't give the attachments ids.

**Comment by jordan-wright** [comment]
Oh, my apologies. I should update the docs. There is currently no use for having the IDs for targets and attachments, so they are not included in the JSON output. There's nothing you can really do with them in the API, making them only useful in the backend.

However, when getting the response from a campaign, the results _will_ have an ID, since this is the "result id" used in creating links.

**Comment by pkhxcp** [comment]
Thanks for the quick updates! I'll adjust as necessary.
