### ISSUE TITLE
Large campaigns using authenticated mail with Google fails to complete

### ISSUE THREAD

**Issue by ustayready** [gophish/gophish#343]
After creating and launching a campaign with 3100 targets, we get between 50 - 90 emails sent before the rest of the sending result in errors. First the errors start rolling in as **gomail: could not send email 1: 421 4.7.0 Try again later, closing connection.** which then lead to **gomail: could not send email 1: write tcp xxx.xxx.xxx.xxx:42624-\\u003e74.125.130.108:587: write: broken pipe**

## **Details about the campaign:**
- Authenticated sending profile using Google Apps for Work account and smtp.gmail.com:587
- Ignoring Certificate Errors in sending profile
- Within 1 minute, 73 errors (of first error) start pouring in
- About 2 minutes after the first error, the errors changed to broken pipes

## **Details about the sending:** (from sqlite)
```
sqlite> select min(time) from events where campaign_id = 46 and message = 'Email Sent';
2016-08-17 02:57:33.753218124-04:00

sqlite> select min(time) from events where campaign_id = 46 and details like '%Try%';
2016-08-17 02:58:51.952522056-04:00

sqlite> select max(time) from events where campaign_id = 46 and details like '%Try%';
2016-08-17 03:01:11.11641459-04:00

sqlite> select min(time) from events where campaign_id = 46 and details like '%broken pipe%';
2016-08-17 03:01:14.056168896-04:00

sqlite> select max(time) from events where campaign_id = 46 and details like '%broken pipe%';
2016-08-17 03:06:20.75842502-04:00

sqlite> select count(*) from events where campaign_id = 46 and details like '%Try%';
73
```

There is no way for me to restart the campaign or add a rate limit between emails, not sure what I should try. I may take a swat at manually adding a sleep in between emails, as well as, adding campaign restart functionality that sets the campaign to CAMPAIGN_QUEUED and loads results based on status (i.e. not in Email Opened, Email Sent, Success)

Anyone have a recommendation for the best way to overcome sending this amount of email without risk of landing in spam? I have an SPF entry on the host since its external to the organization but some emails were randomly landing in spam which creates inaccurate results. :(

- Mike

**Comment by ustayready** [comment]
We are also in touch with Google to see if this is a rate limiting / firewall blacklist on their part. If so, forgive me for reporting.

**Comment by ustayready** [comment]
Self resolved this by switching authentication to using an SMTP relay instead of Google SMTP.

**Comment by jordan-wright** [comment]
Yeah, the 4xx errors generally are to prevent users from sending too much email. A standard SMTP relay will handle the queueing and retrying. Gophish currently doesn't handle this manually.

I'll consider adding the queueing in the future, but for now you'll definitely want to point gophish to an SMTP relay.
