### ISSUE TITLE
RFC: Training Pages

### ISSUE THREAD

**Issue by jordan-wright** [gophish/gophish#345]
All,

I am working to finalize the ability to use Training Pages in gophish, and wanted some feedback before rolling it out.

Until #223 is built out in 0.3, I'm only adding basic support for Training Pages. This means that you will be able to select a single training page - much like you do with Landing Pages right now.

What I wanted feedback on was the flow that I was considering. It should make sense for most cases, but I wanted to make sure I wasn't missing anything.

Here is the flow I'm setting up now:

* IF no training page AND no landing page specified - error
* IF no training page specified, but landing page (with redirect url) specified - visitor receives landing page and redirected to landing page -> redirect URL
* IF training page AND landing page specified -> User presented with landing page, after credentials are submitted, user sees training page (ignoring redirect url)
* IF training page AND no landing page - User sees training page after clicking link in email

So this should be what I imagine most people would expect. Basically training page > redirect url if it's specified.

Thoughts?

**Comment by CoreyMcCown13** [comment]
I think that sounds great. I am currently using a training page hosted on a separate server and am using the redirect feature to simply redirect to the training page. Having it built in would be great. 

Would there be any sort of way to have a button, such as "I have read and understand the content of this page" on the training page, and GoPhish could report back with what users read training document?

**Comment by hheile** [comment]
sounds awesome for me, exactly what is needed

**Comment by hheile** [comment]
i can spare the code from my training-pages to this project. (Sorry-German, can be easy translated to english, maybe i do that later).

what would be nice is to track if customer reaches training-page, 
if he clicks trough all pages (something like a unique identifier for all pages)
when customer starts to "train" when customer finishes train (means reaching the last page)
or if he closes after 3rd page or something.
let me know where to drop the pages (html with a little scripting for the forward-reverse-buttons)

**Comment by Get-Sleep** [comment]
It would be amazing if you could have a Landing Page that after a user enters username+password and submits, you are taken to a Training Page.

**Comment by hheile** [comment]
hello,

something similar is allready working. When you enter a URL at the bootom field of the landing-page editor your users will be taken there after hitting submit.

best regards hheile

Von meinem iPhone gesendet

Am 09.09.2016 um 11:27 schrieb Get-Sleep <notifications@github.com<mailto:notifications@github.com>>:


It would be amazing if you could have a Landing Page that after a user enters username+password and submits, you are taken to a Training Page.

-

**Comment by Get-Sleep** [comment]
I dont have any field like that on the landing page editor :confused: 

I have Name, HTML, and two tickboxes for capturing data. Running latest version

**Comment by jordan-wright** [comment]
If you build from source you will see that field.

**Comment by jordan-wright** [comment]
Going ahead and closing this for now. It seems like we're all on the same page for the initial rollout of training pages. I've been working on these and they should be rolled out soonish.

Thanks everyone!
