### ISSUE TITLE
allow to host the app in a subfolder

### ISSUE THREAD

**Issue by mattoufoutu** [gophish/gophish#346]
Currently, it is only possible to deploy GoPhish at "/", with no support (at least none I found) for hosting in a subfolder.

Example: I have a server on which I have many web applications, all of them behind an nginx server. So I  tell nginx that "/gophish" and "/gophishadmin" should be proxy_pass'd respectively to the phishing site and to the admin interface. The problem here is that GoPhish has no way of knowing it is hosted under "/gophishadmin" instead of the usual "/", making every request to it fail because of erroneous URL paths.

It would be nice to be able to handle this with a "prefix" option (or whatever name you give it) for both the phishing site and the admin interface, so GoPhish would generate its links accordingly and would be able to work even if not hosted at a webserver's root.

**Comment by jordan-wright** [comment]
Could something like [nginx url rewriting](https://serverfault.com/questions/379675/nginx-reverse-proxy-url-rewrite) help with this? I don't know that it is in the current plan to support hosting out of a configurable subdirectory.

**Comment by mattoufoutu** [comment]
I'll have a look into nginx url rewriting thx.
On the other hand, if this isn't in your plans, would you still be willing
to accept a PR if I implement this by myself?

Le mer. 24 août 2016 06:23, Jordan Wright <notifications@github.com> a
écrit :

**Comment by jordan-wright** [comment]
Sorry for the delay - I would absolutely accept a pr that addresses this problem in an easy to use way.

**Comment by jordan-wright** [comment]
I'm going to go ahead and close this out for now, but if you open a PR, please reference this and we'll make sure it all gets taken care of.

Thanks again for this report!
