### ISSUE TITLE
Campaigns never move out of "queued" state

### ISSUE THREAD

**Issue by alexlomas** [gophish/gophish#348]
In the campaigns dashboard the state is "queued", log shows:

2016/08/23 14:58:06 campaign.go:235: Found 0 Campaigns to run

Fresh built from source just now, although I did have a previous build working ok and did

go get -u github.com/gophish/gophish
go build

And then copied a backup of gophish.db back on top.

**Comment by alexlomas** [comment]
Actually, the emails are sent exactly an hour on, so I guess some sort of time zone issue? I'm in GMT+1 (BST).

**Comment by santhoshmla** [comment]
yup, timezone differences on your server/client. Reconfigured timezone, works fine as expected.

**Comment by jordan-wright** [comment]
Ah, I thought this was taken care of with #316 - looks like I'll reopen it and we'll track it from there.

Thanks for the report!
