### ISSUE TITLE
How to send an tracking attachment?

### ISSUE THREAD

**Issue by santhoshmla** [gophish/gophish#352]
Trying the new attachment tracking functionality. 
Tested email with html and word .doc attachments (File names as a.html, b.doc for example).
Couldn't get the attachment tracking functionality right. 
Pointers on how to make this work would be of great help.

Built the binary from Source today early morning (GMT+5:30)

**Comment by jordan-wright** [comment]
Are you using the correct branch? The attachment tracking functionality is not in the main branch yet.

**Comment by jordan-wright** [comment]
Closing this out since attachment support is not currently in the master branch. Attachment support will be coming soon! :smile:

**Comment by mrbangus** [comment]
Jordan-wright - Do you know how close gophish is to implementing the attachment tracking?
