### ISSUE TITLE
gophish.go is not running on windows 8.1

### ISSUE THREAD

**Issue by yogesh-imorsetech** [gophish/gophish#353]
Hello,

I have downloaded the gophish code and trying to run gophish.go but its not running. When running it is throwing below error -
    (function (exports, require, module, __filename, __dirname) { package main
                                                                          ^^^^

    SyntaxError: Unexpected identifier
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:373:25)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Function.Module.runMain (module.js:441:10)
        at startup (node.js:139:18)
        at node.js:974:3

Can you please guide asap?

**Comment by jordan-wright** [comment]
This error seems really odd. How are you executing gophish? Are you using a prebuilt binary or building from source?

**Comment by yogesh-imorsetech** [comment]
I downloaded the source https://github.com/gophish/gophish/archive/v0.1.1.zip and trying to run gophish.go in node. Bcoz double clicking on it is asking for application. Plz help asap.

**Comment by jordan-wright** [comment]
Gophish is written in Golang, not Node.js. Those are completely different languages.

To build from source you need to compile gophish according to our user guide. We do not provide support for setting up a Golang environment.

If this is not possible, I suggest using the prebuilt binaries. You can find instructions on using them in our user guide as well.

**Comment by yogesh-imorsetech** [comment]
Which user guide are you referring to...plz share url and what all I need to install in order to run it?

**Comment by jordan-wright** [comment]
https://getgophish.com/documentation/

**Comment by yogesh-imorsetech** [comment]
I tried by building it from source but while running command 'go get github.com/ gophish/gophish' on my c:/GO/work folder (Windows), i am getting error - 
c:\Go\work>go get github.com/ gophish/gophish
package github.com: unrecognized import path "github.com" (parse https://github.com?go-get=1: no go-import meta tags)
package gophish/gophish: unrecognized import path "gophish/gophish" (import path does not begin with hostname)

Can I have guidance to set it up from source?

**Comment by jordan-wright** [comment]
Looks like you have a space in your path. Use github.com/gophish/gophish

**Comment by yogesh-imorsetech** [comment]
Sorry to update...I could get it installed from source. Now my next problem is when I ran gophish binary and browse http://127.0.01:3333/login, it throws error - " The connection was reset"

**Comment by yogesh-imorsetech** [comment]
![log](https://cloud.githubusercontent.com/assets/20571503/18273086/35aa7a2c-7459-11e6-83ab-3c1577194b6d.png)
Here is the log console.
