### ISSUE TITLE
page not found error

### ISSUE THREAD

**Issue by miked531** [gophish/gophish#355]
When configuring a campaign, the url must contain a path component or a 404 is returned. Without a path, /?rid=... does not work. This could be just an update to the documentation.

**Comment by CoreyMcCown13** [comment]
I believe that is by design so that you can track which user visits and when.

**Comment by jordan-wright** [comment]
That is correct. This is by design so that standard scanning or visiting the index page will not reveal the server is running gophish. The rid parameter is required which loads the content dynamically from the database.

**Comment by jordan-wright** [comment]
I will take it as an action item to update the docs :smile:

**Comment by miked531** [comment]
a little more playing with this today and here's what I hav found. both hits from the tracker and click work fine with the url of "http://foo.bar" and "http://foo.bar/" (trailing slash). when there is a path (http://foo.bar/path) hits on the tracker url are being reported as link click events
