### ISSUE TITLE
get in spam in gmail

### ISSUE THREAD

**Issue by AVI321123** [gophish/gophish#356]
Hi,
test mails without link get to INBOX right.
All test mails + links get spam in GMAIL
How to fix that ?

**Comment by CoreyMcCown13** [comment]
Mine land in my gmail inbox, it is probably the content of the message triggering a spam filter that Gmail has in place. If they're organizational email addresses, adding a whitelist may help?

**Comment by jordan-wright** [comment]
That's correct. I'm afraid the gmail spam filter is a black box to us. My recommendation would be to use an mta that does proper email authentication (spf/dkim/dmarc). Other than that, whitelisting would be the next best thing.

There is unfortunately nothing we can do on our end to fix this issue.
