### ISSUE TITLE
Scheduling campaign

### ISSUE THREAD

**Issue by yogesh-imorsetech** [gophish/gophish#357]
Hello,

I am new to gophish and I want to schedule a campaign. I am not getting a bit on how to do. Can I get some help plz asap?

**Comment by CoreyMcCown13** [comment]
If you built from source, it is just one of the options when you go to launch a campaign, you can't miss it. If you downloaded a binary, it won't be there - they haven't been updated yet.

**Comment by jordan-wright** [comment]
That is correct- if you build from source you will see the option presented. Thanks @CoreyMcown13!
