### ISSUE TITLE
Feature-Req.: Add the option to identify between "Mr." or "Mrs." in E-Mail templates

### ISSUE THREAD

**Issue by derWeihnachtsmann** [gophish/gophish#358]
Hi Jordan,

thank you for your time offered to make this project possible.

I have a Feature request, when we import email-adresses as csv, there should be a row if the user is male or female and based on that the email-Template should change to: "Dear Mr." oder "Dear Mrs." (in multiple languages?) 

Again, thank you for you time spended in this project!

**Comment by CoreyMcCown13** [comment]
You could always make two separate email templates, one for Mr. and one for Mrs., and then create two separate email groups for male and female users and select the respective templates for the campaign. This would be little extra work for you, without having to restructure the database and add email template variables to GoPhish.

**Comment by jordan-wright** [comment]
Hi @derWeihnachtsmann - I'm afraid this is a pretty specific use case. I think we'll just capture this under the feature to add custom variables #27 

Thanks for the suggestion!
