### ISSUE TITLE
Strange 404 on LandingPage

### ISSUE THREAD

**Issue by hheile** [gophish/gophish#359]
Hello Jordon,

i have strange issue on my landing-page (Version 0.2alpha).

Wenn i click my link in my email i should go to the landing-page. it works perfectly with the morning-catch file. 

i created my own landing page, and when i click the link i get:
404 page not found
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml"><head><meta charset="utf-8"/>
	<title>Passwort Reset</title>
</head>
<body>
<div class="mi-desktop" style="font-family: sans-serif; font-size: 14px; line-height: 24px;">
<table align="center" bgcolor="#FFFFFF" cellpadding="0" cellspacing

...allthecodesnippedaway....

see the 404 page not found thing at the beginning, the full html is shown in the output.

what happens in the console when i do this:
 2016/09/05 15:52:46 main.go:690: sql/home/mytestlablogin/go/src/github.com/gophish/gophish/models/campaign.go:117401.381µsINSERT INTO "events" ("campaign_id","email","time","message","details") VALUES (?,?,?,?,?)[25 sweety@home.com 2016-09-05 15:52:46.2390606 +0200 CEST Clicked Link {"payload":{"rid":["756e8073e566fc95f918d8d94f98384314b4c709fca90496bc6e03d2e1e6d7b6"]},"browser":{"address":"10.14.11.136","user-agent":"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; WOW64; Trident/8.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0)"}}]
 2016/09/05 15:52:46 route.go:238: template: html_template:59:64: executing "html_template" at <.URL>: URL is not a field of struct type models.Result
10.14.11.136 - - [05/Sep/2016:15:52:46 +0200] "GET /?rid=756e8073e566fc95f918d8d94f98384314b4c709fca90496bc6e03d2e1e6d7b6 HTTP/2.0" 404 699 "" "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; WOW64; Trident/8.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0)"
 2016/09/05 15:53:02 main.go:690: sql/home/mytestlablogin/go/src/github.com/gophish/gophish/models/campaign.go:117370.439µsINSERT INTO "events" ("campaign_id","email","time","message","details") VALUES (?,?,?,?,?)[25 hero@home.com 2016-09-05 15:53:02.008208983 +0200 CEST Clicked Link {"payload":{"rid":["7bebf87f844f0e1f5dc695a20adc4445c4a473b113a1e2d962f881d34a6fbb9b"]},"browser":{"address":"10.14.11.81","user-agent":"Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"}}]
 2016/09/05 15:53:02 route.go:238: template: html_template:59:64: executing "html_template" at <.URL>: URL is not a field of struct type models.Result

i have no idea whats wrong. 

best
hheile

**Comment by jordan-wright** [comment]
I don't know that the {{.URL}} template variable is valid on the landing page. At least, that's what the error shows.

Try removing it and see if that works. When I'm back at the computer I'll investigate more.

**Comment by hheile** [comment]
Hi jordan,

you’re right, works as expected.


Mit freundlichen Grüßen,

i.A. Heiko Heilemann
Team Security

--
MEKO-S GmbH
Lise-Meitner-Str. 6
28359 Bremen
Deutschland

Telefon:           +49 421 388 90 222
Telefax:           +49 421 388 90 19
E-Mail:            hheilemann@meko-s.de
Internet:           http://www.meko-s.de<http://www.meko-s.de/>
Internet:           http://www.flexx-m.de<http://www.flexx-m.de/>

AG Bremen, HRB 20031
Geschäftsführer: Peter Behrens, Luigi Argentato, Matthias Thom

Ein Unternehmen der Diersch & Schröder Gruppe, Bremen

Von: Jordan Wright [mailto:notifications@github.com]
Gesendet: Montag, 5. September 2016 16:59
An: gophish/gophish <gophish@noreply.github.com>
Cc: Heiko Heilemann <HHeilemann@meko-s.de>; Author <author@noreply.github.com>
Betreff: Re: [gophish/gophish] Strange 404 on LandingPage (#359)

I don't know that the {{.URL}} template variable is valid on the landing page. At least, that's what the error shows.

Try removing it and see if that works. When I'm back at the computer I'll investigate more.

**Comment by jordan-wright** [comment]
@hheile This should be fixed as of 7740bb3e95c58fc6795e32684a0d4321759276d0. Let me know if you continue to experience this issue.

Thanks!
