### ISSUE TITLE
gophish on a Ubuntu server?

### ISSUE THREAD

**Issue by nadvig** [gophish/gophish#360]
hi! i'm testing right now gophish on my laptop. very good, everything is ok with the admin/gui/127.0.0.1 etc....

but i have a ubuntu server on the cloud. I have to install gophish. everything is ok for the installation. but to have access to the GUI admin (in local is 127.0.0.1:3333), do i have to create a web host in the /www/ directory? like a website to have access ? i have open the port 3333.

can you help me? in the user guide nothing about it is there!

**Comment by jordan-wright** [comment]
You need to be able to reach the admin interface that, by default, listens on localhost only. So to keep it that way you can use ssh tunneling to access the panel.

Otherwise, if you're cool with exposing the admin interface to the Internet, you can do that by changing the admin_server line in config.json to "0.0.0.0:3333" and restarting gophish.

**Comment by nadvig** [comment]
what is the best practice for gophish? my goal is to phish our employees. so i have to install gophish where? on my laptop? on a cloud server? and to access the GUI to do the campaign ?

**Comment by hheile** [comment]
hello nadvig, i've deployed gophish on a separate vm running ubuntu 16 lts. 
my machine is really minimalistic, just ubuntu, email-setup to my internal emailsysetm (exchange) and a webserver (the ubuntuserver) reachable by all via DNS. thats it. 
in config.json you can change the admin-interface behavior (Port, SSL yes/no) listening-name or ip.

**Comment by nadvig** [comment]
ok thanks i will do some changes on my set up. i have my gophish in a ubuntu vm also. i thaught it was important to setup on a cloud server or something like that....

also, i have a vm in the cloud to host the phish website ... the url that the employees will click on that phishing message that they will received.... is that ok? the click on the link will go to the html page that i will host on that cloud vm.
