### ISSUE TITLE
Password forgotten

### ISSUE THREAD

**Issue by evanuz** [gophish/gophish#362]
Hey, i forgot the pass i set, is there a way to change it in order to use all the stuff i had already set up??

**Comment by jordan-wright** [comment]
You can edit the gophish.db file using a SQLite client and change the admin hash to the default hash found in models/models.go.

This changes the password to "gophish".

**Comment by evanuz** [comment]
Perfect :D worked like a charm

Thanks!

**Comment by jimmybarber** [comment]
worked out fine, thank you

**Comment by bhargavi-git** [comment]
I am not able to find the software
using SQL Lite pro, unable to recover 
can anyone help me with step by steps

**Comment by putsi** [comment]
Just as a reference for new users. This is how you can reset the admin password back to "gophish" in Centos and most Debian based distros such as Ubuntu:
```
yum install -y sqlite ||apt-get install -y sqlite3 libsqlite3-dev
sqlite3 gophish.db 'update users set hash="$2a$10$IYkPp0.QsM81lYYPrQx6W.U6oQGw7wMpozrKhKAHUBVL4mkm/EvAS" where username="admin";'
```

**Comment by Black-Zetsu** [comment]
hello guys,
I also forgot my gophish, i want to ask someone who can assist me on recover it

**Comment by Black-Zetsu** [comment]
hi @jordan-wright I tried to go through on what you said on top but i can't understand how do you do that.. i would love if you could make some steps please, I thank you in advance to anyone will answer me..
a

**Comment by th0r3i9** [comment]
this...
sudo apt --purge remove gophish 

then install it again if you have a rod and bait already :)

**Comment by martirspe** [comment]
When capturing the data it gives me an encrypted password, in the videos I have seen they are in plain text. How can i see it?
