### ISSUE TITLE
Integrate USB phishing campaigns

### ISSUE THREAD

**Issue by seanthegeek** [gophish/gophish#363]
Hi,

I wrote a USB phishing client a while back, but never got around to creating a server for it. It is written in Python, and packaged as a one-click EXE using pyinstaller.

I'm not sure if this is usable for a Go-based project, but if anything, it might be a good example to port!

https://github.com/seanthegeek/phishforall/

Note to self: learn Go!

**Comment by jordan-wright** [comment]
Hi @seanthegeek - thanks for the suggestion!

For now, I'm going to keep gophish targeted to sending phishing emails. If, however, you are able to get this working in Go, please send a pull request and we would be happy to consider merging it into the product.

Thanks again for the great suggestions!
