### ISSUE TITLE
Import Site Landing Page is Spotty

### ISSUE THREAD

**Issue by wauger** [gophish/gophish#369]
Hi Jordan et al,
For some reason the Import Site function doesn't always pull the entirety of a static HTML page (no active scripting). In some cases it does, and everything displays correctly. Other times it seems to miss a few CSS imports and the formatting is way off. 

Am I missing something or doing something wrong here?

Thanks,
-Paul

**Comment by jordan-wright** [comment]
Hey Paul,

The way the cloning works is by grabbing the HTML of the page, adding a `base` tag to have all relative assets point off the base url, and update any `form` tags on the page according to what data you choose to capture.

This is the most lightweight way to do site cloning, but it's unfortunately not perfect. You're likely doing things right but I still recommend double-checking the pages after they are cloned to ensure everything looks the way you expect it to.

**Comment by wauger** [comment]
Thanks much Jordan. Is the only way to test the landing page to launch a
campaign and click on a link?

**Comment by jordan-wright** [comment]
Unfortunately I've upgraded to Go 1.7 to diagnose #354 so I don't have a screenshot, but there's a "Source" button in the page editor that you can click which will show you a preview of the page as it will appear to the user. There is also a button in the editor that will make the preview full screen as needed.
