### ISSUE TITLE
glibc 2.14 dependency fails on Debian Wheezy

### ISSUE THREAD

**Issue by SEBreniac** [gophish/gophish#375]
Debian Wheezy comes with glibc 2.12 by default, and the compiled version of GoPhish requires glibc 2.14 or greater to run.

`./gophish: /lib64/libc.so.6: version 'GLIBC_2.14' not found (required by ./gophish)`

**Comment by jordan-wright** [comment]
You might try building from source or using a new version of glibc.

For the next release, I'll try to compile with 2.14 to fix this issue.

**Comment by SEBreniac** [comment]
Thanks - I did end up doing this, and it compiled fine.
