### ISSUE TITLE
Add Database Column(s) - Goose Migration Script?

### ISSUE THREAD

**Issue by doktor1360** [gophish/gophish#376]
Per the subject, client would like to add a column to a couple of tables in the gophish.db file. I haven't seen a whole lot on this forum or on the web addressing this specifically. Not to be playing the fool here, but is it safe to assume the following:

Use 'goose' to create a new sql migration file in the ~/db/migrations directory. Edit the contents of the file with the required sql and save. Simply rebuild gophish and the migrations code (setup) does the rest of the heavy lifting, and builds the DDL changes into the gophish.db. Would that be a correct statement? If not, what is the actual procedure or is there some document I've not unearthed...

Any/all feedback - input would greatly appreciated... 

Thanx in advance!

**Comment by jordan-wright** [comment]
You can find some information [here](https://getgophish.com/blog/post/database-migrations-in-go/), however you should just be able to add the columns to the database directly.

However, please note that I'm afraid we do not provide official support for custom changes like this one.

**Comment by doktor1360** [comment]
Kewlio... a 'goose' wrapper... thanx for the Heads-Up...

I did make the assumption I could modify the db file directly (like any other sqlite file), however I didn't want to charge in like a Bull in a China Shop without checking with the author/support/forum data available firstly. However, again, thanx for the input... much appreciated...
