### ISSUE TITLE
Gophish has problems loading css file ?

### ISSUE THREAD

**Issue by derWeihnachtsmann** [gophish/gophish#377]
Hi, 
I think I have encountered a Problem regarding GoPhish with css (or it's just me failing again), and I need someone to confirm this.

If I try to import the site, the css will not load and therefore break the layout of the site when you have clicked the Link in the eMail.
In the PreviewWindow of GoPhish it looks just fine.

I put the css and js into the GoPhish - static folder.

Let me know if I have left any Questions. 

Thank you very much and have a nice day!

http://pastebin.com/r4A8efWL

**Comment by jordan-wright** [comment]
What version of gophish are you using? Why are you putting the CSS/JS in the static folder of gophish? When importing a site from a URL, it should add a `base` tag that points all relative urls (like the CSS ones) to the appropriate imported url.

If you aren't importing by url and are just dropping the HTML into gophish, then you can refer to [this answer](https://github.com/gophish/gophish/issues/164) for information on where to host the files.

**Comment by jordan-wright** [comment]
@derWeihnachtsmann just checking in - could you take a look at my comment above and let me know if that helps solve your question?

**Comment by jordan-wright** [comment]
Hi @derWeihnachtsmann I'm going to go ahead and close this one out since I haven't heard back in about a month.

Let me know if the comments above don't help resolve the issue and we'll be happy to continue troubleshooting.

Thanks for reporting this to us!
