### ISSUE TITLE
gophish on a web server

### ISSUE THREAD

**Issue by nadvig** [gophish/gophish#379]
hi if i want to use goshish on my VPS, if i do these changes am i ok ?

 "admin_server" : {
		"listen_url" : "server_ip:3333",
		"use_tls" : true,
		"cert_path" : "gophish.crt",
		"key_path" : "gophish.key"
	},
	"phish_server" : {
		"listen_url" : "0.0.0.0:80",
		"use_tls" : true,
		"cert_path" : "gophish.crt",
                "key_path": "gophish.key"

i have done also 
ufw allow 3333
service apache2 stop
./gophish 
tcp : 80... bind address allready use

**Comment by nadvig** [comment]
i have made some changes and i get the usual message when running ./gophish:

root@ubuntu:/opt/gophish# ./gophish
 2016/09/24 14:55:11 worker.go:38: Background Worker Started Successfully - Waiting for Campaigns
goose: migrating db environment 'production', current version: 0, target: 20160227180335
OK    20160118194630_init.sql
OK    20160131153104_0.1.2_add_event_details.sql
OK    20160211211220_0.1.2_add_ignore_cert_errors.sql
OK    20160217211342_0.1.2_create_from_col_results.sql
OK    20160225173824_0.1.2_capture_credentials.sql
OK    20160227180335_0.1.2_store-smtp-settings.sql
 2016/09/24 14:55:11 gophish.go:67: Starting phishing server at https://0.0.0.0:80
 2016/09/24 14:55:11 gophish.go:55: Starting admin server at https://server_ip:3333

but when i do to https://server_ip:3333 the page isnt't loaded

**Comment by jordan-wright** [comment]
The first error was because something else was already running in tcp port 80. Looks like you got that resolved.

What is the terminal output when you hit the login page and it doesn't load? 

What version of gophish are you running?

**Comment by nadvig** [comment]
it's the last version of gophish

https://server_ip:3333 : the page is not loaded, that's it. 
the usual Apache page html is loaded if i go to : http://server_ip

my port 3333 is open

**Comment by nadvig** [comment]
am in!!!

"admin_server" : {
"listen_url" : "0.0.0.0:3333",
"use_tls" : true,
"cert_path" : "gophish.crt",
"key_path" : "gophish.key"
},

**Comment by jordan-wright** [comment]
Cool - sounds like you got it resolved.

**Comment by nadvig** [comment]
Yes thanks


Envoy? de mon iPhone

Le 24 sept. 2016 ? 12:34, Jordan Wright <notifications@github.com<mailto:notifications@github.com>> a ?crit :


Cool - sounds like you got it resolved.

-
