### ISSUE TITLE
Question: What database tools are people using for goPhish?

### ISSUE THREAD

**Issue by JGoLabs** [gophish/gophish#380]
Does anyone have a recommendation on an off the shelf tool for viewing the database contents for gophish?  Also, is the database msql, sqlite or something else?

**Comment by jordan-wright** [comment]
The database will be SQLite unless you are using the experimental MySQL support that isn't merged into mainline yet.

To access the database, you can use the standard sqlite3 cli client available on most nix distros, or you can use the popular [sqlite browser](http://sqlitebrowser.org/)

**Comment by jordan-wright** [comment]
@JGoLabs I don't see anyone else jumping in at this question, so I'll likely close out the issue tomorrow or the next day.

Did my answer give you what you were looking for?

**Comment by jordan-wright** [comment]
Going ahead and closing this one out. Let me know if you run into any issues!
