### ISSUE TITLE
Question : attachment, traking status 

### ISSUE THREAD

**Issue by aprilLast** [gophish/gophish#381]
Hello, I have a question. 
I want to track when people open the attachment file or click that. 

I saw the blow issue, but I can't find solutions.
https://github.com/gophish/gophish/issues/227
Is it not possible this function in current gophish? 

And I want to know track the status. 
When I was test outlook, IE, gophich can't get opening status. (chrome O) 
So do you know the reason? and How I to get the status? 

Last.. I want to know IP address but when I was export csv, there is not any Ip, latitude, longtidue information. 
Do I have to set another setting? 
If you have a time, please confirm my question. 
I am waiting for your answer.  Thank you very much!

**Comment by jordan-wright** [comment]
Hi @aprilLast, thanks for reaching out.

There are quite a few questions in this one issue. We try to keep issues isolated in scope to better track completion of things. Please break up future issues separately.

For this one, here are the answers:

* Attachment support is on the way but is not currently implemented into the main branch of gophish #227 is a good issue to track.
* There are multiple reasons email open events won't show up, the primary reason is that many mail clients and configurations block external images from loading. This is to prevent tracking. There is nothing gophish can do about this.
* Tmk, the latitude, longitude, etc. info is exported properly when you export via the "results" option from the campaign results page
