### ISSUE TITLE
RFE: Additional Variables

### ISSUE THREAD

**Issue by cclements** [gophish/gophish#383]
Would be useful to have additional variables supported.  A few that I would find helpful are:

{{.Address}}
{{.Date}} (possibly with offsets?  eg. current, +1, -1)
{{.Company}}
{{.FirstInitial}}
{{.LastInitial}}
{{.DomainName}}

Pie in the sky, random strings/lengths would also be great for simulating order/ticket numbers and such:

{{.RandNum6}}  e.g. -> 856130
{{.RandAlpha8}} e.g -> IFPZBWLB

**Comment by jordan-wright** [comment]
Hi @cclements - Thanks for the suggestion! I'm hoping to eventually find a way to expose custom template variables which should let you do all of this yourself.  We're tracking that via #27, so for now I'll go ahead and close this one out as a duplicate.

Let me know if you have any questions! Thanks again for the suggestion - keep them coming!
