### ISSUE TITLE
{{.URL}} with HTTPS landing page

### ISSUE THREAD

**Issue by ozheng** [gophish/gophish#384]
The landing page defined with {{.URL}} is always set to http://[name].
When the config.json is modified with use_tls=true, {{.URL}} should set the URL to https://[name].

**Comment by jordan-wright** [comment]
I'll investigate, but just to clarify - are you setting the "Url" parameter when building a campaign to "https://example.com"?

From a brief glance through the code, I don't see where I'm hard setting this anywhere.

**Comment by jordan-wright** [comment]
I've confirmed that with the latest source if you specify "https://x.x.x.x" as the url when building a campaign, that's what shows up as the link in the email.

If you meant something different then please let me know and I'll be happy to look into it. Otherwise, I think we're ok on this one.

**Comment by ozheng** [comment]
Oh... You are absolutely right.
I was not setting the right URL (I was not very clear about the "Url" parameter meaning).

Thank you.

**Comment by LidiaNg** [comment]
> I've confirmed that with the latest source if you specify "https://x.x.x.x" as the url when building a campaign, that's what shows up as the link in the email.
> 
> If you meant something different then please let me know and I'll be happy to look into it. Otherwise, I think we're ok on this one.

hi, i would like to know, how to mi ip address in the url (how to hide my url of listener)
