### ISSUE TITLE
Announcement: Freezing Development for 0.2

### ISSUE THREAD

**Issue by jordan-wright** [gophish/gophish#385]
All,

I have decided to freeze development for gophish to prepare for the 0.2 binary releases. This means cleaning up documentation, building and releasing the binaries.

It might take a bit to get all the binaries built, but bear with me and we'll make it happen.

Moving forward, here are some of the big ticket items I want to tackle in 0.3:
- Attachment Support (currently branched but not brought into mainline)
- UI Refresh (it's going to be awesome)
- Implementing the campaign builder (see #223)
- Better email queuing/retrying
- Mysql support (a pull request exists, but we'll need to do some testing before merging)

All this being said, 0.3 will be a _big_ feature release. There is a lot to do, and my free time is becoming much more few and far between. So, I would ask that everyone bear with me as I might be slower to answer issues in favor of rolling out the new features.

I hope everyone is getting good use out of gophish. I promise there's plenty to be excited about in the coming months!

Jordan

**Comment by snori74** [comment]
Great to hear that 0.2 is coming. Have had quite a burst of work using gophish lately, and have been working on some interesting scripts using the API, which I hope to be able to share soon.

**Comment by ss23** [comment]
@jordan-wright Will there be a branch for either 1.2 so development can continue in master, or perhaps a dev/next/something branch we can base pull requests against?

**Comment by jordan-wright** [comment]
Closing this as [0.2 has been released!](https://github.com/gophish/gophish/releases/tag/v0.2.0)
