### ISSUE TITLE
IP tracking

### ISSUE THREAD

**Issue by snori74** [gophish/gophish#387]
It seems to make sense to record IP on each "event" rather than just in the "status" - ie Campaign["timeline"] rather than in Campaign["status"]. No problem with a single value in "status" (the first or the most recent perhaps?) - but _adding_ a per-click entry under "timeline". 

Thoughts?

(This is particularly the case where we're seeing contention from staff about whether, and when, a link was clicked - and would like to be able to differentiate any potential "pre-clicks" by AV or mailfiltering software - and the occasional potential case of an email being forwarded off and clicked by someone other than the original target).

**Comment by jordan-wright** [comment]
Are you building from source? We are [adding the IP address and user-agent string](https://github.com/gophish/gophish/blob/master/controllers/route.go#L193) to each event in the payload field.

**Comment by snori74** [comment]
Not on my production setup. I'll shortly get a 'from source' server setup
for testing and see how that goes.

 - steve

**Comment by jordan-wright** [comment]
Sounds good, thanks @snori74! Let me know if that fixes the problem for you.

**Comment by jordan-wright** [comment]
Hey @snori74 - just checking in. Did building from source help to fix this issue?

Thanks!

**Comment by jordan-wright** [comment]
Going ahead and closing this for now. @snori74 - let me know if building from source didn't fix this issue and we can always re-open.
