### ISSUE TITLE
recording UserAgent string

### ISSUE THREAD

**Issue by snori74** [gophish/gophish#388]
As with #387, this seems most logical to record under Campaign["timeline"].

This would allow tracking of whether the link was opened from a phone, Outlook etc, - or possibly by mail-checking sandbox (either when the user clicks the link - or potentially when they simply _open_ the email.

**Comment by jordan-wright** [comment]
See my comment on #387 and let me know if that answers your question. 😄

**Comment by jordan-wright** [comment]
Going ahead and closing this for now. @snori74 - let me know if building from source didn't fix this issue and we can always re-open.
