### ISSUE TITLE
Gophish - cannot get results data

### ISSUE THREAD

**Issue by yellowroomlearning** [gophish/gophish#393]
Hi there

I have just installed gophish and have successfully run my first test campaign but I am getting no results data back. I have tried a variety of things to resolve the issue but am having no luck. A bit more info about what I have done:
I have created a template - it includes the tracker and the {{.URL}} 
I have created a landing page - for test purposes I just used a random webpage
I set the URL in the campaign to the phishing server as indicated when starting up - http://0.0.0.0:80
I have made sure the firewall is allowing traffic through port 80

The email sends and I receive it OK but nothing happens in the results when I open or click the link.

Any suggestions would be welcome as I have drawn a blank.

Thank you

**Comment by Amghost03** [comment]
I am having the same issue except my first few test campaigns were successful and now the emails are sending, but results are not being recorded.

**Comment by yellowroomlearning** [comment]
Did you set the campaign URL as 0.0.0.0:80 - this is only bit to my setup I am not sure about.

**Comment by yellowroomlearning** [comment]
OK, update. I have now set my URL to my IPv4 address on port 80 - when launching a campaign it sends ok, I receive the mail. The link is there to be clicked but when I click on it I just get a blank page - it does not seem to load the landing page. The link adress had the ?rid variable but nothing happens after that and still no update in the results - just shows as 'sent'

Any ideas would be welcome please?

**Comment by yellowroomlearning** [comment]
Further update. I have resolved my issue. I reconfigured the server to listen on a different port as it seems port 80 was conflicting somehow (although not clear on the firewall). Anyway, I set it to another port, opened it up on the firewall and success - emails now tracked and results data present.

**Comment by tarzan538** [comment]
Yellowroomlearning,

I am having the same issue as I can get data from a submitted campaign if I am in the same network, but once data comes from outside the network I cannot record data. We are a non-profits organization and we can use some help as we are not that technical.

Can you give me a quick step by step on how to config the system to receive data on my laptop. We have a fortinet firewall and the server we are running Gophish on only this PC. What options do we have to set this up and get data?

Thank you,

Felix

**Comment by Amitdassabtin** [comment]
are you here someone?
