### ISSUE TITLE
google smtp relay issues 

### ISSUE THREAD

**Issue by insomnia80** [gophish/gophish#397]
I haven't been able get my smtp relay through google servers to work.  I have tried using 25, 465, 587 smtp.google.com as well as smtp-relay.gmail.com.  I'm not sure if it's an issue with google or if I am just missing something.  When I use 465 it causes gophish to shutdown.  For the URL in the campaign should it be 127.0.0.1?
![google smtp](https://cloud.githubusercontent.com/assets/17791884/19334437/8f55bdfa-90c1-11e6-97f7-cd940cf16c2c.PNG)

![sending profile](https://cloud.githubusercontent.com/assets/17791884/19334589/8af9f00e-90c2-11e6-91d0-46ad8a5b3b72.PNG)

**Comment by jordan-wright** [comment]
No, the URL in the campaign should be an address of the gophish server that external targets can reach.

What logs do you see in the console when you send a test email? Are you using the pre built binaries or are you building from source?

**Comment by insomnia80** [comment]
I am using the pre built and with 587 I get this message  //support.google.com/mail/answer/78754 e192sm5345372oic.22 - gsmtp
25  A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
465 I get EOF in send test email and when I try it with a campaign it crashes the console

**Comment by frankenwino** [comment]
It may or may not be related but Google Compute Engine does not allow outbound connections on ports 25, 465, and 587: https://cloud.google.com/compute/docs/tutorials/sending-mail/

**Comment by insomnia80** [comment]
Thank you!!! That was what was wrong.  For anyone else who may have this issue:


    Take the step mentioned earlier. Log into your google email account and then go to this link: https://www.google.com/settings/security/lesssecureapps and set "Access for less secure apps" to ON. Test to see if your issue is resolved. If it isn't resolved, as it wasn't for me, continue to Step #2.

    Go to https://support.google.com/accounts/answer/6009563 (Titled: "Password incorrect error"). This page says "There are several reasons why you might see a “Password incorrect” error (aka 534-5.7.14) when signing in to Google using third-party apps. In some cases even if you type your password correctly." This page gives 4 suggestions of things to try.

**Comment by jordan-wright** [comment]
Good deal! It's possible the version in source "just works" so I recommend only doing this if needed.
