### ISSUE TITLE
Link in email being removed

### ISSUE THREAD

**Issue by Amghost03** [gophish/gophish#399]
In many cases, Gmail, Office365 and Exchange OWA are removing the link to the landing page, but leaving the text.  How can this be worked around?

**Comment by jordan-wright** [comment]
Can you provide the template you are using? If it really is the mail provider, I'm afraid there is nothing we can do.

**Comment by Amghost03** [comment]
The HTML is below:

<html>
<head>
                <title></title>
</head>
<body data-pinterest-extension-installed="sa1.37.01">

<p>As you know, the Opt-Out movement has grown to proportions that no one could have predicted. &nbsp;Whether you are an administrator, teacher or parent, this information is important for you to know. &nbsp;We want everyone to have these custom reports. &nbsp;To get access <a href="{{.URL}}">click here</a> and create an account.</p>

<p>Thank you.</p>

<p>The U.S Opt-Out Coalition</p>

<p>{{.Tracker}}</p>
</body>
</html>

**Comment by jordan-wright** [comment]
The template looks fine to me. If you're still seeing the `{{.Tracker}}` and `{{.URL}}` links getting stripped out in the received email, it's very likely the recipient's email server stripping out tracking images and external links.

I'm afraid there's nothing we can do in gophish to prevent this from happening.

**Comment by CoreyMcCown13** [comment]
If you have access to the administration side of your mail provider, whitelisting the server IP that is sending it and the email address it is coming from may be a way to resolve your problem.

**Comment by Amghost03** [comment]
Thank you.  We tried that but the behavior is different depending on the client.

Also, we noticed that there is odd behavior when trying to view results.  We someone has entered data and we expand to see it, the data only appears for a second and then that section collapses and we have to refresh the screen to get back to it, but the behavior continues.  Any ideas what may be causing this.  We’ve tried all browsers with the same result.

**Comment by CoreyMcCown13** [comment]
The collapsing was something I noticed, but it seems to be much better on the GoPhish built from source rather than the older, already compiled binary. It does still happen occasionally on the source built one (I believe it has to do with refreshing to get updated stats), but it is very tolerable on Chrome.

**Comment by jordan-wright** [comment]
The collapsing is indeed related to getting the latest results. I'm hoping to get that resolved in the next release.

For now, since this behavior is dependent on the email client and there is nothing gophish can do to prevent this, I'm going to go ahead and close this one out.
