### ISSUE TITLE
Unique Identifiers

### ISSUE THREAD

**Issue by ryan-es2** [gophish/gophish#400]
Hello, and thanks for an awesome tool!
I am a Jr Pentester learning the ropes so to speak. I am investing a lot of time in Soc Eng work. Before finding your tool I was manually running campaigns with the help of excel. 
I am having a little difficulty understanding how I do the following with your tool.

Presently I have the user follow a link ?id=randomstring that way when checking apache logs I see unique hits as <randomstring> is associated to that user in my excel list. 

How do I do this in GoPhish if I have a group list but need to uniquely Ident each email?
I have made a campaign and a user list, however the email template needs to create a unique id for each user if you will.. http://phishingsite.xzy/index.html?id=xyz0001   etc etc

Apologies for the explanation :s

**Comment by jordan-wright** [comment]
Gophish already does that for you. After you start sending out emails, you'll see each generated `{{.URL}}` have an `?rid=xxxx` parameter which is a unique ID for every target in the campaign.

**Comment by ryan-es2** [comment]
Thanks for the speedy response! I thought that might be the case, but was unsure, I will learn how to format a campaign correctly!

**Comment by jordan-wright** [comment]
Sounds good. Feel free to open issues if you run into bugs while using Gophish!
