### ISSUE TITLE
Error inserting template into database ?

### ISSUE THREAD

**Issue by ryan-es2** [gophish/gophish#401]
How might one fix this issue? I have sql configured and installed, everything else is working just fine except when making an email template?

Kind regards,

Ryan

**Comment by ryan-es2** [comment]
Nevermind, I ran go build again and this repaired I suppose the link

**Comment by rcarterv** [comment]
I've run into the same issue on v0.3.0. Rebuilding my docker image did not correct this issue. Would love suggestions. :)

**Comment by jordan-wright** [comment]
What errors do you see in the terminal when you try to save the template?

**Comment by rcarterv** [comment]
8/31/2017 2:06:32 PM 2017/08/31 20:06:32 api.go:321: template: html_template:1:2: executing "html_template" at <.Firstname>: can't evaluate field Firstname in type struct { models.Result; URL string; TrackingURL string; Tracker string; From string }

8/31/2017 2:06:32 PM10.42.230.199 - - [31/Aug/2017:20:06:32 +0000] "POST /api/templates/?api_key=48f5cfc995beed59381f627cd81b7b98289ca6ce1592fa0654fab6b3f118dd29 HTTP/1.1" 500 105 "https://gophish.apps.verisys.com:5052/templates" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"

This is what I have pasted into the HTML tab:
```
{{.Firstname}}, 

Our records indicate that you have PTO records that have not been approved in over 60 days. Please login here to update or retire old requests. 

ActionHRM Administrator

{{.Tracker}}
```

Any help is appreciated.

**Comment by rcarterv** [comment]
I see what the problem is now: **.Firstname** should be **.FirstName**. That didn't jump out at me before.

User error, whoops!

**Comment by jordan-wright** [comment]
Yep! You can always find the full template reference here: https://gophish.gitbooks.io/user-guide/content/template_reference.html

Thanks for reaching out!

**Comment by agentAA7** [comment]
when I try and use {{ .Now }} I get an error:

> Error inserting template into database

Do I need to install some sort of patch to get this to work?
This is a fresh install using the latest version, the server is only 1 week old.
