### ISSUE TITLE
Installation Steps for Ubuntu 16.10 on a VM

### ISSUE THREAD

**Issue by ryan-es2** [gophish/gophish#402]
Just sharing everything I had to figure out to get a 100% working install of GoPhish as a noob.
There is prob a better way but I was short on time and struggling as it was.
I experienced an SQL error after install when saving an email template, I am not sure if installing sqllite3 fixed this or mysql-server ?? Either way running go build after again got me up and running so I figured I would share.
# Configuration of GoPhish on Ubuntu Server
#New Password
passwd

# Set Timezone
rm /etc/localtime
ln -s /usr/share/zoneinfo/<your zone>/etc/localtime
date

# Required Dependencies
apt-get update && apt-get upgrade
apt-get install golang
apt-get install apache2
apt-get install sqlite3
apt-get install mysql-server
apt-get install gcc
apt-get install build-essential

# Install Steps for gophish
mkdir ~/.go
export GOPATH=~/.go
go get github.com/gophish/gophish
cd ~/.go/src/github.com/gophish/gophish
go build

**Comment by CoreyMcCown13** [comment]
For what it's worth, on CentOS7 minimal the following dependencies needed installed: golang, gcc, build-essentials . Then follow the exact same "Install Steps for gophish" and it will work.

**Comment by ryan-es2** [comment]
Thanks Cory will look into this aswell :) But I am reading into using a pi i have lying around with docker too :) such a great app this gophish

**Comment by jordan-wright** [comment]
You don't need apache2 or mysql-server to get gophish to work. It uses its own web servers and leverages sqlite by default to store data. Otherwise, these look good! I'll point to this in the wiki as a helpful resource.

In the meantime, I'm going to go ahead and close this one out since it's resolved. Thanks for writing this up!
