### ISSUE TITLE
need a template variable which is {{.Email}}

### ISSUE THREAD

**Issue by edwardyeung** [gophish/gophish#403]
Sometime you create templates need this...

Especially when you need to pass a variable through url. 

For example, 
1. http://www.google.com/q={{.Email}}
2. {{.Url}}{{.Email}}    ( {{.Url}} = http://www.google.com/q= )

**Comment by jordan-wright** [comment]
Hi @edwardyeung - my apologies for not having this document, but ```{{.Email}}``` should already work just fine.

You can find an updated template reference [on the wiki](https://github.com/gophish/gophish/wiki/Template-Reference) since I'm moving documentation to it.
