### ISSUE TITLE
I can't use Chinese filling the <from> field in the New Sending Profile

### ISSUE THREAD

**Issue by edwardyeung** [gophish/gophish#404]
The hint is `mail: missing word in phrase: mail: invalid string`

**Comment by jordan-wright** [comment]
Hey @edwardyeung - thanks for letting us know about this. Unfortunately, I think this is an issue with Golang, no gophish. I don't believe Golang supports non-ascii characters in email addresses.

**Comment by jordan-wright** [comment]
Closing this one out since it appears to be a duplicate of #135. We'll work from that issue to eventually track down the non-ascii characters in SMTP issue.

Thanks for this report!
