### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by hpscrappy** [gophish/gophish#405]
It would be nice if we could export all campaign's together with the metrics for each to show trends within an organization. showing campaign, total, success rates, (opened,clicked...etc)

**Comment by jordan-wright** [comment]
Hey @hpscrappy! Thanks for sending this our way.

This is a perfect use case for the API. All of this data is easily exportable from either the API or the sqlite database.

**Comment by jordan-wright** [comment]
Going ahead and closing this for now. I would definitely recommend going with the API or hitting the database directly to export all of this information.
