### ISSUE TITLE
Monitoring Gophish and DoS

### ISSUE THREAD

**Issue by ryan-es2** [gophish/gophish#410]
Hi there!

I noticed whilst on the dashboard, it seems to refresh regularly and if I am not mistaken issues a GET request to the API for campaign results. It does this almost 1second apart, I worry this might cause a crash, perhaps it could be set to refresh on 5, 15, 30 min intervals ?

**Comment by jordan-wright** [comment]
Gophish currently polls every 10 seconds for new results. You're correct that, when there are thousands of recipients, this can cause the dashboard to become unresponsive.

I am planning a complete UI refresh in the next release, which will aim to fix this issue.

**Comment by ryan-es2** [comment]
No rush mate! do your thing :)

**Comment by jordan-wright** [comment]
Thanks! I'm going to go ahead and close this out since we'll track this UI refresh through a separate task.

Keep the good ideas coming!
