### ISSUE TITLE
Template Panic "function "backgroundImage" not defined"

### ISSUE THREAD

**Issue by kjarrard** [gophish/gophish#412]
Hope someone can help - I'm brand new to Gophish, and am not a Linux guy fo rthe most part.  I was running the Windows binaries, but apparently a bug was fixed with O365 sending and that fix is not in the available compiled binaries.

So, I just spun-up a Ubuntu 16.04 vm, Had to manually install gomail.v2 as the gophish install failed saying it was not available.  Did the gophish install and all worked.  Tested an o365 Sending Profile and it worked this time around.  Created all the other pieces and launched several test campaigns.  

I'm using a Landing Page in my Email Template and what I'm seeing is that when the link is clicked in the email, gophish panics and the client shows a "page isn't working/ERR_EMPTY_RESPONSE" message.  Not sure what is going on.  Here is the output from the gophish terminal window.  Help would be greatly appreciated.  It errors out right away with the background image.  Could that really be causing the panic?  This is the webpage I'm using as a template:  https://online.adp.com/resource/login.html

 2016/10/24 11:06:01 main.go:702: sql/home/jblow/go/src/github.com/gophish/gophish/models/campaign.go:1171.064109msINSERT INTO "events" ("campaign_id","email","time","message","details") VALUES (?,?,?,?,?)[5 joe@blow.com 2016-10-24 11:06:01.126276651 -0700 PDT Email Opened ]
172.20.1.74 - - [24/Oct/2016:11:06:01 -0700] "GET /track?rid=f3ca8be7a90bfad860141fdf99c332c29af53458cee342c42cd98d359da98c84 HTTP/1.1" 200 106 "" "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; WOW64; Trident/8.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; InfoPath.3; Microsoft Outlook 15.0.4745; Microsoft Outlook 15.0.4745; ms-office; MSOffice 15)"
172.20.1.74 - - [24/Oct/2016:11:06:01 -0700] "GET /api/campaigns/4/results?api_key=de778bcb82c6c7dfbdd880904ba5fffd73476a019588c1b6b00a86ccc91e8643&{} HTTP/1.1" 200 614 "http://172.25.3.122:3333/campaigns/4" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
172.20.1.74 - - [24/Oct/2016:11:06:07 -0700] "GET /api/campaigns/5/results?api_key=de778bcb82c6c7dfbdd880904ba5fffd73476a019588c1b6b00a86ccc91e8643&{} HTTP/1.1" 200 391 "http://172.25.3.122:3333/campaigns/5" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
 2016/10/24 11:06:08 main.go:702: sql/home/jblow/go/src/github.com/gophish/gophish/models/campaign.go:117852.337µsINSERT INTO "events" ("campaign_id","email","time","message","details") VALUES (?,?,?,?,?)[5 joe@blow.com 2016-10-24 11:06:08.382882145 -0700 PDT Clicked Link {"payload":{"rid":["f3ca8be7a90bfad860141fdf99c332c29af53458cee342c42cd98d359da98c84"]},"browser":{"address":"172.20.1.74","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"}}]
 2016/10/24 11:06:08 route.go:223: template: html_template:23: function "backgroundImage" not defined
2016/10/24 11:06:08 http: panic serving 172.20.1.74:56760: runtime error: invalid memory address or nil pointer dereference
goroutine 71 [running]:
net/http.(_conn).serve.func1(0xc820818c00)
    /usr/lib/go/src/net/http/server.go:1389 +0xc1
panic(0xb05100, 0xc82000a100)
    /usr/lib/go/src/runtime/panic.go:443 +0x4e9
html/template.(_Template).escape(0x0, 0x0, 0x0)
    /usr/lib/go/src/html/template/template.go:79 +0x3c
html/template.(_Template).Execute(0x0, 0x7f695463d060, 0xc820166460, 0xb19760, 0xc8202d7a40, 0x0, 0x0)
    /usr/lib/go/src/html/template/template.go:101 +0x34
github.com/gophish/gophish/controllers.PhishHandler(0x7f695458d508, 0xc820860340, 0xc820272460)
    /home/jblow/go/src/github.com/gophish/gophish/controllers/route.go:243 +0x14fa
net/http.HandlerFunc.ServeHTTP(0xcf2880, 0x7f695458d508, 0xc820860340, 0xc820272460)
    /usr/lib/go/src/net/http/server.go:1618 +0x3a
github.com/gorilla/mux.(_Router).ServeHTTP(0xc8201b4460, 0x7f695458d508, 0xc820860340, 0xc820272460)
    /home/jblow/go/src/github.com/gorilla/mux/mux.go:114 +0x2a8
github.com/NYTimes/gziphandler.NewGzipLevelHandler.func1.1(0x7f695458d4d0, 0xc820ebb320, 0xc820272460)
    /home/jblow/go/src/github.com/NYTimes/gziphandler/gzip.go:167 +0x169
net/http.HandlerFunc.ServeHTTP(0xc820175240, 0x7f695458d4d0, 0xc820ebb320, 0xc820272460)
    /usr/lib/go/src/net/http/server.go:1618 +0x3a
github.com/gorilla/handlers.combinedLoggingHandler.ServeHTTP(0x7f69546381c0, 0xc820022010, 0x7f6954589000, 0xc820175240, 0x7f695458d330, 0xc82081a750, 0xc820272460)
    /home/jblow/go/src/github.com/gorilla/handlers/handlers.go:77 +0x121
github.com/gorilla/handlers.(_combinedLoggingHandler).ServeHTTP(0xc820175280, 0x7f695458d330, 0xc82081a750, 0xc820272460)
    <autogenerated>:15 +0xb4
net/http.serverHandler.ServeHTTP(0xc820173480, 0x7f695458d330, 0xc82081a750, 0xc820272460)
    /usr/lib/go/src/net/http/server.go:2081 +0x19e
net/http.(_conn).serve(0xc820818c00)
    /usr/lib/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(_Server).Serve
    /usr/lib/go/src/net/http/server.go:2137 +0x44e
 2016/10/24 11:06:08 main.go:702: sql/home/jblow/go/src/github.com/gophish/gophish/models/campaign.go:117833.54µsINSERT INTO "events" ("campaign_id","email","time","message","details") VALUES (?,?,?,?,?)[5 joe@blow.com 2016-10-24 11:06:08.467424207 -0700 PDT Clicked Link {"payload":{"rid":["f3ca8be7a90bfad860141fdf99c332c29af53458cee342c42cd98d359da98c84"]},"browser":{"address":"172.20.1.74","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"}}]
 2016/10/24 11:06:08 route.go:223: template: html_template:23: function "backgroundImage" not defined
2016/10/24 11:06:08 http: panic serving 172.20.1.74:56762: runtime error: invalid memory address or nil pointer dereference
goroutine 73 [running]:
net/http.(_conn).serve.func1(0xc82081d100)
    /usr/lib/go/src/net/http/server.go:1389 +0xc1
panic(0xb05100, 0xc82000a100)
    /usr/lib/go/src/runtime/panic.go:443 +0x4e9
html/template.(_Template).escape(0x0, 0x0, 0x0)
    /usr/lib/go/src/html/template/template.go:79 +0x3c
html/template.(_Template).Execute(0x0, 0x7f695463d060, 0xc820d16000, 0xb19760, 0xc8200c60c0, 0x0, 0x0)
    /usr/lib/go/src/html/template/template.go:101 +0x34
github.com/gophish/gophish/controllers.PhishHandler(0x7f695458d508, 0xc820bc0080, 0xc820272620)
    /home/jblow/go/src/github.com/gophish/gophish/controllers/route.go:243 +0x14fa
net/http.HandlerFunc.ServeHTTP(0xcf2880, 0x7f695458d508, 0xc820bc0080, 0xc820272620)
    /usr/lib/go/src/net/http/server.go:1618 +0x3a
github.com/gorilla/mux.(_Router).ServeHTTP(0xc8201b4460, 0x7f695458d508, 0xc820bc0080, 0xc820272620)
    /home/jblow/go/src/github.com/gorilla/mux/mux.go:114 +0x2a8
github.com/NYTimes/gziphandler.NewGzipLevelHandler.func1.1(0x7f695458d4d0, 0xc8200e0090, 0xc820272620)
    /home/jblow/go/src/github.com/NYTimes/gziphandler/gzip.go:167 +0x169
net/http.HandlerFunc.ServeHTTP(0xc820175240, 0x7f695458d4d0, 0xc8200e0090, 0xc820272620)
    /usr/lib/go/src/net/http/server.go:1618 +0x3a
github.com/gorilla/handlers.combinedLoggingHandler.ServeHTTP(0x7f69546381c0, 0xc820022010, 0x7f6954589000, 0xc820175240, 0x7f695458d330, 0xc820258000, 0xc820272620)
    /home/jblow/go/src/github.com/gorilla/handlers/handlers.go:77 +0x121
github.com/gorilla/handlers.(_combinedLoggingHandler).ServeHTTP(0xc820175280, 0x7f695458d330, 0xc820258000, 0xc820272620)
    <autogenerated>:15 +0xb4
net/http.serverHandler.ServeHTTP(0xc820173480, 0x7f695458d330, 0xc820258000, 0xc820272620)
    /usr/lib/go/src/net/http/server.go:2081 +0x19e
net/http.(_conn).serve(0xc82081d100)
    /usr/lib/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(_Server).Serve
    /usr/lib/go/src/net/http/server.go:2137 +0x44e
 2016/10/24 11:06:08 main.go:702: sql/home/jblow/go/src/github.com/gophish/gophish/models/campaign.go:117840.942µsINSERT INTO "events" ("campaign_id","email","time","message","details") VALUES (?,?,?,?,?)[5 joe@blow.com 2016-10-24 11:06:08.704211908 -0700 PDT Clicked Link {"payload":{"rid":["f3ca8be7a90bfad860141fdf99c332c29af53458cee342c42cd98d359da98c84"]},"browser":{"address":"172.20.1.74","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"}}]
 2016/10/24 11:06:08 route.go:223: template: html_template:23: function "backgroundImage" not defined
2016/10/24 11:06:08 http: panic serving 172.20.1.74:56764: runtime error: invalid memory address or nil pointer dereference
goroutine 75 [running]:
net/http.(_conn).serve.func1(0xc820818200)
    /usr/lib/go/src/net/http/server.go:1389 +0xc1
panic(0xb05100, 0xc82000a100)
    /usr/lib/go/src/runtime/panic.go:443 +0x4e9
html/template.(_Template).escape(0x0, 0x0, 0x0)
    /usr/lib/go/src/html/template/template.go:79 +0x3c
html/template.(_Template).Execute(0x0, 0x7f695463d060, 0xc8202868c0, 0xb19760, 0xc8200c69c0, 0x0, 0x0)
    /usr/lib/go/src/html/template/template.go:101 +0x34
github.com/gophish/gophish/controllers.PhishHandler(0x7f695458d508, 0xc820cf25c0, 0xc8202722a0)
    /home/jblow/go/src/github.com/gophish/gophish/controllers/route.go:243 +0x14fa
net/http.HandlerFunc.ServeHTTP(0xcf2880, 0x7f695458d508, 0xc820cf25c0, 0xc8202722a0)
    /usr/lib/go/src/net/http/server.go:1618 +0x3a
github.com/gorilla/mux.(_Router).ServeHTTP(0xc8201b4460, 0x7f695458d508, 0xc820cf25c0, 0xc8202722a0)
    /home/jblow/go/src/github.com/gorilla/mux/mux.go:114 +0x2a8
github.com/NYTimes/gziphandler.NewGzipLevelHandler.func1.1(0x7f695458d4d0, 0xc820ce83c0, 0xc8202722a0)
    /home/jblow/go/src/github.com/NYTimes/gziphandler/gzip.go:167 +0x169
net/http.HandlerFunc.ServeHTTP(0xc820175240, 0x7f695458d4d0, 0xc820ce83c0, 0xc8202722a0)
    /usr/lib/go/src/net/http/server.go:1618 +0x3a
github.com/gorilla/handlers.combinedLoggingHandler.ServeHTTP(0x7f69546381c0, 0xc820022010, 0x7f6954589000, 0xc820175240, 0x7f695458d330, 0xc8200641a0, 0xc8202722a0)
    /home/jblow/go/src/github.com/gorilla/handlers/handlers.go:77 +0x121
github.com/gorilla/handlers.(_combinedLoggingHandler).ServeHTTP(0xc820175280, 0x7f695458d330, 0xc8200641a0, 0xc8202722a0)
    <autogenerated>:15 +0xb4
net/http.serverHandler.ServeHTTP(0xc820173480, 0x7f695458d330, 0xc8200641a0, 0xc8202722a0)
    /usr/lib/go/src/net/http/server.go:2081 +0x19e
net/http.(_conn).serve(0xc820818200)
    /usr/lib/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(_Server).Serve
    /usr/lib/go/src/net/http/server.go:2137 +0x44e
172.20.1.74 - - [24/Oct/2016:11:06:12 -0700] "GET /api/campaigns/4/results?api_key=de778bcb82c6c7dfbdd880904ba5fffd73476a019588c1b6b00a86ccc91e8643&{} HTTP/1.1" 200 614 "http://172.25.3.122:3333/campaigns/4" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
 2016/10/24 11:06:13 main.go:702: sql/home/jblow/go/src/github.com/gophish/gophish/models/campaign.go:1171.066514msINSERT INTO "events" ("campaign_id","email","time","message","details") VALUES (?,?,?,?,?)[5 joe@blow.com 2016-10-24 11:06:13.809688806 -0700 PDT Clicked Link {"payload":{"rid":["f3ca8be7a90bfad860141fdf99c332c29af53458cee342c42cd98d359da98c84"]},"browser":{"address":"172.20.1.74","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"}}]
 2016/10/24 11:06:13 route.go:223: template: html_template:23: function "backgroundImage" not defined
2016/10/24 11:06:13 http: panic serving 172.20.1.74:56766: runtime error: invalid memory address or nil pointer dereference
goroutine 77 [running]:
net/http.(_conn).serve.func1(0xc8203a1e00)
    /usr/lib/go/src/net/http/server.go:1389 +0xc1
panic(0xb05100, 0xc82000a100)
    /usr/lib/go/src/runtime/panic.go:443 +0x4e9
html/template.(_Template).escape(0x0, 0x0, 0x0)
    /usr/lib/go/src/html/template/template.go:79 +0x3c
html/template.(_Template).Execute(0x0, 0x7f695463d060, 0xc820148e00, 0xb19760, 0xc8202d6fc0, 0x0, 0x0)
    /usr/lib/go/src/html/template/template.go:101 +0x34
github.com/gophish/gophish/controllers.PhishHandler(0x7f695458d508, 0xc820bfa080, 0xc8202737a0)
    /home/jblow/go/src/github.com/gophish/gophish/controllers/route.go:243 +0x14fa
net/http.HandlerFunc.ServeHTTP(0xcf2880, 0x7f695458d508, 0xc820bfa080, 0xc8202737a0)
    /usr/lib/go/src/net/http/server.go:1618 +0x3a
github.com/gorilla/mux.(_Router).ServeHTTP(0xc8201b4460, 0x7f695458d508, 0xc820bfa080, 0xc8202737a0)
    /home/jblow/go/src/github.com/gorilla/mux/mux.go:114 +0x2a8
github.com/NYTimes/gziphandler.NewGzipLevelHandler.func1.1(0x7f695458d4d0, 0xc820856060, 0xc8202737a0)
    /home/jblow/go/src/github.com/NYTimes/gziphandler/gzip.go:167 +0x169
net/http.HandlerFunc.ServeHTTP(0xc820175240, 0x7f695458d4d0, 0xc820856060, 0xc8202737a0)
    /usr/lib/go/src/net/http/server.go:1618 +0x3a
github.com/gorilla/handlers.combinedLoggingHandler.ServeHTTP(0x7f69546381c0, 0xc820022010, 0x7f6954589000, 0xc820175240, 0x7f695458d330, 0xc82081a000, 0xc8202737a0)
    /home/jblow/go/src/github.com/gorilla/handlers/handlers.go:77 +0x121
github.com/gorilla/handlers.(_combinedLoggingHandler).ServeHTTP(0xc820175280, 0x7f695458d330, 0xc82081a000, 0xc8202737a0)
    <autogenerated>:15 +0xb4
net/http.serverHandler.ServeHTTP(0xc820173480, 0x7f695458d330, 0xc82081a000, 0xc8202737a0)
    /usr/lib/go/src/net/http/server.go:2081 +0x19e
net/http.(_conn).serve(0xc8203a1e00)
    /usr/lib/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(_Server).Serve
    /usr/lib/go/src/net/http/server.go:2137 +0x44e

**Comment by jordan-wright** [comment]
Hi @kjarrard,

Thanks for including the full stack trace! This line is the smoking gun:

```
2016/10/24 11:06:08 route.go:223: template: html_template:23: function "backgroundImage" not defined
```

It looks like somewhere in your html, you have ```{{backgroundImage}}``` or similar. This matches the syntax of gophish's templating system, so it assumes you want to have that replaced but doesn't know what to replace it with.

I recommend trying to remove that bit in the html and see if it works better.

Thanks!

**Comment by kjarrard** [comment]
Thanks for the help.  I saw that but wasn't sure it was enough to cause a
full abort.  It's a bummer, they use quite a few tags in the form {{
tagname }}.  Looks like this site isn't a good option for import cloning.
