### ISSUE TITLE
503 Bad Command Sequence

### ISSUE THREAD

**Issue by CaptainBobby** [gophish/gophish#417]
I get the following errors after creating a campaign.

****
 2016/10/31 10:17:05 campaign.go:235: Found 1 Campaigns to run
 2016/10/31 10:17:05 worker.go:53: Worker received: IRS TG3 - 4Q2016 2nd
 2016/10/31 10:17:05 worker.go:141: Creating email using template
 2016/10/31 10:17:05 worker.go:181: Sending Email to APatten@domain.com
 2016/10/31 10:17:05 worker.go:184: gomail: could not send email 1: 551 Forwarding to remote hosts disabled
 2016/10/31 10:17:05 main.go:690: sql/home/administrator/go/src/github.com/gophish/gophish/models/campaign.go:117352.824µsINSERT INTO "events" ("campaign_id","email","time","message","details") VALUES (?,?,?,?,?)[44 APatten@domain.com 2016-10-31 10:17:05.792681897 -0600 MDT Error Sending Email {"error":"gomail: could not send email 1: 551 Forwarding to remote hosts disabled"}]
 2016/10/31 10:17:05 worker.go:141: Creating email using template
 2016/10/31 10:17:05 worker.go:181: Sending Email to AWadsworth@domain.com
 2016/10/31 10:17:05 worker.go:184: gomail: could not send email 1: 503 Bad command sequence
 2016/10/31 10:17:06 main.go:690: sql/home/administrator/go/src/github.com/gophish/gophish/models/campaign.go:1172.746225msINSERT INTO "events" ("campaign_id","email","time","message","details") VALUES (?,?,?,?,?)[44 AWadsworth@domain.com 2016-10-31 10:17:06.041100342 -0600 MDT Error Sending Email {"error":"gomail: could not send email 1: 503 Bad command sequence"}]
****

Any idea why this has started happening? It didn't happen when I sent my last campaign. Sending profile was copied from existing. When sending test emails or creating campaigns with one recipient, everything works fine. I am only trying to send to 32 recipients at a time.

No changes to the server. I am on version 0.2alpha. I changed the recipient email domain in the log for security reasons.

**Comment by jordan-wright** [comment]
Did anything change on your smtp server? It's looking like the smtp server isn't liking gophish trying to relay mail through it.

**Comment by CaptainBobby** [comment]
As far as I know, no, nothing has changed. In fact, there is nothing in the mail server logs coming from the gophish server. It's as if nothing is being sent. And like I said, we are able to create a campaign with a single recipient and the email is relayed.

We are currently testing to see if there is a recipient threshold, 10, 15, etc. We've tested a campaign with 5 recipients and the email relayed correctly. I will update as I continue to test and look through logs.

**Comment by CaptainBobby** [comment]
It looks like when we get to about 14 recipients the emails start to fail. Is there a permanent log that GoPhish writes to? If so where is it located?

Also, when there are errors after a campaign is created, would it be possible for a status of "Has Errors" to display on the campaign dashboard?

**Comment by CaptainBobby** [comment]
We did find that the gophish server wasn't listed as a trusted relay however after adding it we are still experiencing the same issue. I'm going to spin up a fresh VM and build from source again to see if something has gone wrong with the VM itself. I'll let you know if that resolves the issue.

**Comment by CaptainBobby** [comment]
After watching the logs, when the campaign emails start going out we've observed this "503 Bad Command Sequence" behavior happening if the previous email response is a "550 No such recipient."

So, if the 16th recipient doesn't exist recipients 17-20 will fail with the 503 error. Once the recipient who didn't exist was removed the other 19 emails relayed correctly.

This behavior continued to happen after creating a new GoPhish server and building from source.

**Comment by jordan-wright** [comment]
Thanks for the investigation! I'll take a look when I get a chance to see if there is something we can do on gophish's end to help catch errors and handle them more gracefully.

**Comment by infosecwriter** [comment]
I am having the same issue

**Comment by jordan-wright** [comment]
Just a heads up, this was fixed as part of https://github.com/gophish/gophish/pull/878.

Hope this helps! Let me know if you continue to run into issues.
