### ISSUE TITLE
Problems with database upgrade?

### ISSUE THREAD

**Issue by snori74** [gophish/gophish#418]
My understanding is that the format of the database changes from time to time, and that 'goose' is used 'auto-upgraded' the db as necessary. In my case however, when I put in a later executable (compiled), I found that although most things appeared to work, I was getting:
1 - 404's on targets clicking. 
2 - The "version number" did not appear on the "Settings" screen. 
3 - The log was showing;
2016/11/04 13:09:33 campaign.go:233: no such column: launch_date
2016/11/04 13:09:33 campaign.go:235: Found 0 Campaigns to run
2016/11/04 13:09:33 worker.go:41: no such column: launch_date
2016/11/04 13:10:00 campaign.go:305: no such column: redirect_url

Currently I've reverted to an older binary gophish binary for now which appears to work correctly. With this, the  system reports as it starts up:
 > goose: no migrations to run. current version: 20160605210903

Any advice on working through a fix when this occurs, or how to avoid it? (as I'll certainly want to upgrade at some point)

**Comment by SEBreniac** [comment]
@snori74 

When you compiled the new binary, did you make sure to copy over the new templates and static files too? It looks like most of your issues are due to using old templates (missing some fields).

**Comment by snori74** [comment]
Ah! That will be the problem then. 

I copied just the 'gophish' executable. Do I need to copy just 'templates' and static' directories, or everything (except gophish.db)?

**Comment by jordan-wright** [comment]
Yes, you'll need to update all the files and folders that currently come with the binary. That would include the `migrations/` folder, which holds all the database migration files.

If you update all of the files/folders, that should take care of your issue.
