### ISSUE TITLE
Localhost SMTP Relay Not Connecting

### ISSUE THREAD

**Issue by theabraxas** [gophish/gophish#420]
I have a simple Postfix server running on the same host gophish is installed on (from most recent Docker Image) - I am attempting to create a sending profile but am getting errors when pointing to: 
`localhost:25` or `public-ip:25` with and without authentication. Is this a supported configuration? I'm only seeing a 3rd party relay from your documentation user/setup guide.

**Comment by jordan-wright** [comment]
What errors are you getting?

**Comment by theabraxas** [comment]
I try the 'test' option and get an 'unable to connect' error,

**Comment by jordan-wright** [comment]
Can you show us a screenshot of what you're doing? Is there any output from the terminal that gives indications of what might be going on?

**Comment by jordan-wright** [comment]
Hey @theabraxas, just wanted to check in - could you send us a screenshot of what the sending profile configuration looks like?

**Comment by theabraxas** [comment]
I think I need to figure out how to properly set this up with postfix on my end - any chance there's a deployment guide for running your own mailserver on the same box? (ie. sample postfix config requirements?)

**Comment by jordan-wright** [comment]
I'm afraid I don't have any postfix instructions handy, although there should be quite a few resources like this available via some searching. If you come across any particularly good resources, or want to write up your experiences, I would be happy to include them in our docs.

**Comment by jordan-wright** [comment]
Going ahead and closing this for now, since this doesn't appear to be an issue with gophish. If I'm mistaken, please don't hesitate to let me know and we can re-open.

Thanks for reaching out!
