### ISSUE TITLE
Web server times out

### ISSUE THREAD

**Issue by congriholdplantains** [gophish/gophish#425]
I have gotten the gophish web server running fine, but it seems to time out at some point during the day. How can I prevent it from doing so, in order to make sure users hit a live site regardless on when they end up interacting with the [internal test] phishing email?

**Comment by jordan-wright** [comment]
We would need some more information to help troubleshoot this one. Are there any messages in the terminal that may indicate why it's "timing out"? Does this mean the server is completely crashed, or is it something different?

**Comment by congriholdplantains** [comment]
No messages, gophish just dies and it stops responding, both the admin interface and the external piece.

Recently, I did get this, but I don't think this is the one that usually triggers, since this one was while I was working with the admin dashboard and normally it happens out of the blue:
 2016/11/15 00:03:55 worker.go:45: Worker received: bait b test
 2016/11/15 00:03:55 worker.go:90: template: html_template:66: function "URL" not defined
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0x61a4a5]

goroutine 8 [running]:
text/template.errRecover(0xc8200e5528)
	/root/go/src/text/template/exec.go:100 +0xbb
text/template.(*Template).Execute(0x0, 0x7f74644b50d8, 0xc82023fc70, 0xa92760, 0xc820498460, 0x0, 0x0)
	/root/go/src/text/template/exec.go:140 +0x235
github.com/gophish/gophish/worker.processCampaign(0xc820334d80)
	/root/projects/src/github.com/gophish/gophish/worker/worker.go:92 +0xdab
github.com/gophish/gophish/worker.(*Worker).Start(0xc820022b90)
	/root/projects/src/github.com/gophish/gophish/worker/worker.go:40 +0x119
created by github.com/gophish/gophish/controllers.init.1
	/root/projects/src/github.com/gophish/gophish/controllers/api.go:28 +0x9f

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc8201ae83c)
	/root/go/src/runtime/sema.go:43 +0x26
sync.(*WaitGroup).Wait(0xc8201ae830)
	/root/go/src/sync/waitgroup.go:126 +0xb4
main.main()
	/root/projects/src/github.com/gophish/gophish/gophish.go:75 +0x17b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/root/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 16 [IO wait]:
net.runtime_pollWait(0x7f74644b5e00, 0x72, 0xc82000a190)
	/root/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82033adf0, 0x72, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82033adf0, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82033ad90, 0xc820321400, 0x400, 0x400, 0x0, 0x7f74644ac050, 0xc82000a190)
	/root/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820023048, 0xc820321400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/root/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8203581b0, 0x7f74644b65a8, 0xc820023048, 0x5, 0x0, 0x0)
	/root/go/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc82008d600, 0xc1ad17, 0x0, 0x0)
	/root/go/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc82008d600, 0xc82035c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/root/go/src/crypto/tls/conn.go:901 +0x167
net/http.(*liveSwitchReader).Read(0xc820325018, 0xc82035c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/root/go/src/net/http/server.go:219 +0xa4
io.(*LimitedReader).Read(0xc82035a020, 0xc82035c000, 0x1000, 0x1000, 0x50, 0x0, 0x0)
	/root/go/src/io/io.go:427 +0xbd
bufio.(*Reader).fill(0xc820356180)
	/root/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc820356180, 0xc81ffdb30a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadLine(0xc820356180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/bufio/bufio.go:357 +0x53
net/textproto.(*Reader).readLineSlice(0xc8203595f0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/net/textproto/reader.go:55 +0x81
net/textproto.(*Reader).ReadLine(0xc8203595f0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/net/textproto/reader.go:36 +0x40
net/http.ReadRequest(0xc820356180, 0xc820499dc0, 0x0, 0x0)
	/root/go/src/net/http/request.go:653 +0xb6
net/http.(*conn).readRequest(0xc820324fd0, 0x0, 0x0, 0x0)
	/root/go/src/net/http/server.go:633 +0x32f
net/http.(*conn).serve(0xc820324fd0)
	/root/go/src/net/http/server.go:1319 +0x727
created by net/http.(*Server).Serve
	/root/go/src/net/http/server.go:1910 +0x3f6

goroutine 15 [IO wait]:
net.runtime_pollWait(0x7f74644b5ec0, 0x72, 0xc82000a190)
	/root/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82033ad80, 0x72, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82033ad80, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82033ad20, 0xc820320c00, 0x400, 0x400, 0x0, 0x7f74644ac050, 0xc82000a190)
	/root/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820023040, 0xc820320c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/root/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820358000, 0x7f74644b65a8, 0xc820023040, 0x5, 0x0, 0x0)
	/root/go/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc82008d340, 0xc1ad17, 0x0, 0x0)
	/root/go/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc82008d340, 0xc820352000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/root/go/src/crypto/tls/conn.go:901 +0x167
net/http.(*liveSwitchReader).Read(0xc8203249e8, 0xc820352000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/root/go/src/net/http/server.go:219 +0xa4
io.(*LimitedReader).Read(0xc82031bd60, 0xc820352000, 0x1000, 0x1000, 0x50, 0x0, 0x0)
	/root/go/src/io/io.go:427 +0xbd
bufio.(*Reader).fill(0xc820311d40)
	/root/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc820311d40, 0xc81ffdb30a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadLine(0xc820311d40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/bufio/bufio.go:357 +0x53
net/textproto.(*Reader).readLineSlice(0xc820315980, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/net/textproto/reader.go:55 +0x81
net/textproto.(*Reader).ReadLine(0xc820315980, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/net/textproto/reader.go:36 +0x40
net/http.ReadRequest(0xc820311d40, 0xc820499c00, 0x0, 0x0)
	/root/go/src/net/http/request.go:653 +0xb6
net/http.(*conn).readRequest(0xc8203249a0, 0x0, 0x0, 0x0)
	/root/go/src/net/http/server.go:633 +0x32f
net/http.(*conn).serve(0xc8203249a0)
	/root/go/src/net/http/server.go:1319 +0x727
created by net/http.(*Server).Serve
	/root/go/src/net/http/server.go:1910 +0x3f6

goroutine 12 [runnable, locked to thread]:
github.com/mattn/go-sqlite3._Cfunc__sqlite3_open_v2(0x7f744c0008c0, 0xc820446bb0, 0x7f7400010006, 0x0, 0xc800000000)
	github.com/mattn/go-sqlite3/_obj/_cgo_gotypes.go:196 +0x39
github.com/mattn/go-sqlite3.(*SQLiteDriver).Open(0xc82018e6e0, 0xc82000b090, 0xa, 0x0, 0x0, 0x0, 0x0)
	/root/projects/src/github.com/mattn/go-sqlite3/sqlite3.go:672 +0x81e
database/sql.(*DB).conn(0xc8201b1540, 0x1, 0x447f7b, 0x0, 0x0)
	/root/go/src/database/sql/sql.go:710 +0x451
database/sql.(*DB).query(0xc8201b1540, 0xc8203733b0, 0x46, 0xc820323290, 0x1, 0x1, 0x976b01, 0xc8203232f0, 0x0, 0x0)
	/root/go/src/database/sql/sql.go:959 +0x46
database/sql.(*DB).Query(0xc8201b1540, 0xc8203733b0, 0x46, 0xc820323290, 0x1, 0x1, 0xc8200fd400, 0x0, 0x0)
	/root/go/src/database/sql/sql.go:947 +0xa3
github.com/jinzhu/gorm.Query(0xc820383e00)
	/root/projects/src/github.com/jinzhu/gorm/callback_query.go:47 +0x84a
github.com/jinzhu/gorm.(*Scope).callCallbacks(0xc820383e00, 0xc82018e140, 0x3, 0x4, 0xc820383e00)
	/root/projects/src/github.com/jinzhu/gorm/scope_private.go:333 +0x68
github.com/jinzhu/gorm.(*DB).First(0xc820241a40, 0x94e3a0, 0xc82043fe80, 0x0, 0x0, 0x0, 0xc820241a40)
	/root/projects/src/github.com/jinzhu/gorm/main.go:204 +0x236
github.com/gophish/gophish/models.GetUser(0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/projects/src/github.com/gophish/gophish/models/user.go:17 +0x1ed
github.com/gophish/gophish/middleware.GetContext.func1(0x7f74644bac48, 0xc8203b0180, 0xc8204982a0)
	/root/projects/src/github.com/gophish/gophish/middleware/middleware.go:29 +0x27d
net/http.HandlerFunc.ServeHTTP(0xc820232ec0, 0x7f74644bac48, 0xc8203b0180, 0xc8204982a0)
	/root/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/handlers.combinedLoggingHandler.ServeHTTP(0x7f74644b01c0, 0xc820022010, 0x7f74644b50b0, 0xc820232ec0, 0x7f74644baaa8, 0xc8204a5810, 0xc8204982a0)
	/root/projects/src/github.com/gorilla/handlers/handlers.go:77 +0x11f
github.com/gorilla/handlers.(*combinedLoggingHandler).ServeHTTP(0xc820232ee0, 0x7f74644baaa8, 0xc8204a5810, 0xc8204982a0)
	<autogenerated>:15 +0xb4
net/http.serverHandler.ServeHTTP(0xc820215c20, 0x7f74644baaa8, 0xc8204a5810, 0xc8204982a0)
	/root/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc820257130)
	/root/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/root/go/src/net/http/server.go:1910 +0x3f6

goroutine 9 [chan receive]:
database/sql.(*DB).connectionOpener(0xc8201b1540)
	/root/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
	/root/go/src/database/sql/sql.go:481 +0x336

goroutine 10 [IO wait]:
net.runtime_pollWait(0x7f74644b6040, 0x72, 0xc82000a190)
	/root/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8202733a0, 0x72, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8202733a0, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820273340, 0x0, 0x7f74644b61f8, 0xc82035a800)
	/root/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820022d98, 0xc820356660, 0x0, 0x0)
	/root/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc820022d98, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/net/http/server.go:2135 +0x41
crypto/tls.(*listener).Accept(0xc820283560, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/crypto/tls/tls.go:46 +0x60
net/http.(*Server).Serve(0xc820215c20, 0x7f74644b63e8, 0xc820283560, 0x0, 0x0)
	/root/go/src/net/http/server.go:1887 +0xb3
net/http.(*Server).ListenAndServeTLS(0xc820215c20, 0xc82000aee0, 0xb, 0xc82000aef0, 0xb, 0x0, 0x0)
	/root/go/src/net/http/server.go:2038 +0x32d
net/http.ListenAndServeTLS(0xc82000aed0, 0xe, 0xc82000aee0, 0xb, 0xc82000aef0, 0xb, 0x7f74644b5128, 0xc820232ee0, 0x0, 0x0)
	/root/go/src/net/http/server.go:2000 +0xc4
main.main.func1(0xc8201ae830)
	/root/projects/src/github.com/gophish/gophish/gophish.go:57 +0x2ee
created by main.main
	/root/projects/src/github.com/gophish/gophish/gophish.go:62 +0x134

goroutine 11 [IO wait]:
net.runtime_pollWait(0x7f74644b6100, 0x72, 0xc82000a190)
	/root/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8202046f0, 0x72, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8202046f0, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820204690, 0x0, 0x7f74644b61f8, 0xc82018ed20)
	/root/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820022c08, 0xc82004bc88, 0x0, 0x0)
	/root/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc820022c08, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/net/http/server.go:2135 +0x41
net/http.(*Server).Serve(0xc820165aa0, 0x7f74644b61c0, 0xc820022c08, 0x0, 0x0)
	/root/go/src/net/http/server.go:1887 +0xb3
net/http.(*Server).ListenAndServe(0xc820165aa0, 0x0, 0x0)
	/root/go/src/net/http/server.go:1877 +0x136
net/http.ListenAndServe(0xc82000afc0, 0xa, 0x7f74644b5128, 0xc82018ed00, 0x0, 0x0)
	/root/go/src/net/http/server.go:1967 +0x8f
main.main.func2(0xc8201ae830)
	/root/projects/src/github.com/gophish/gophish/gophish.go:72 +0x67d
created by main.main
	/root/projects/src/github.com/gophish/gophish/gophish.go:74 +0x16d

goroutine 18 [IO wait]:
net.runtime_pollWait(0x7f74644b5d40, 0x72, 0xc82000a190)
	/root/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82033ae60, 0x72, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82033ae60, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82033ae00, 0xc820321000, 0x400, 0x400, 0x0, 0x7f74644ac050, 0xc82000a190)
	/root/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820023050, 0xc820321000, 0x400, 0x400, 0x0, 0x0, 0x0)
	/root/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820358180, 0x7f74644b65a8, 0xc820023050, 0x5, 0x0, 0x0)
	/root/go/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc82008d8c0, 0xc1ad17, 0x0, 0x0)
	/root/go/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc82008d8c0, 0xc82035e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/root/go/src/crypto/tls/conn.go:901 +0x167
net/http.(*liveSwitchReader).Read(0xc8203250c8, 0xc82035e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/root/go/src/net/http/server.go:219 +0xa4
io.(*LimitedReader).Read(0xc82035a080, 0xc82035e000, 0x1000, 0x1000, 0x50, 0x0, 0x0)
	/root/go/src/io/io.go:427 +0xbd
bufio.(*Reader).fill(0xc8203561e0)
	/root/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc8203561e0, 0xc81ffdb30a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadLine(0xc8203561e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/bufio/bufio.go:357 +0x53
net/textproto.(*Reader).readLineSlice(0xc8203ef530, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/net/textproto/reader.go:55 +0x81
net/textproto.(*Reader).ReadLine(0xc8203ef530, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/net/textproto/reader.go:36 +0x40
net/http.ReadRequest(0xc8203561e0, 0xc820499ce0, 0x0, 0x0)
	/root/go/src/net/http/request.go:653 +0xb6
net/http.(*conn).readRequest(0xc820325080, 0x0, 0x0, 0x0)
	/root/go/src/net/http/server.go:633 +0x32f
net/http.(*conn).serve(0xc820325080)
	/root/go/src/net/http/server.go:1319 +0x727
created by net/http.(*Server).Serve
	/root/go/src/net/http/server.go:1910 +0x3f6

goroutine 19 [IO wait]:
net.runtime_pollWait(0x7f74644b5c80, 0x72, 0xc82000a190)
	/root/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82033b560, 0x72, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82033b560, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82033b500, 0xc82037d400, 0x400, 0x400, 0x0, 0x7f74644ac050, 0xc82000a190)
	/root/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820023168, 0xc82037d400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/root/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820359440, 0x7f74644b65a8, 0xc820023168, 0x5, 0x0, 0x0)
	/root/go/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc82008db80, 0xc1ad17, 0x0, 0x0)
	/root/go/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc82008db80, 0xc82036a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/root/go/src/crypto/tls/conn.go:901 +0x167
net/http.(*liveSwitchReader).Read(0xc820325388, 0xc82036a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/root/go/src/net/http/server.go:219 +0xa4
io.(*LimitedReader).Read(0xc82035a780, 0xc82036a000, 0x1000, 0x1000, 0x50, 0x0, 0x0)
	/root/go/src/io/io.go:427 +0xbd
bufio.(*Reader).fill(0xc820356600)
	/root/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc820356600, 0xc81ffdb30a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadLine(0xc820356600, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/bufio/bufio.go:357 +0x53
net/textproto.(*Reader).readLineSlice(0xc820359500, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/net/textproto/reader.go:55 +0x81
net/textproto.(*Reader).ReadLine(0xc820359500, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/net/textproto/reader.go:36 +0x40
net/http.ReadRequest(0xc820356600, 0xc820499ea0, 0x0, 0x0)
	/root/go/src/net/http/request.go:653 +0xb6
net/http.(*conn).readRequest(0xc820325340, 0x0, 0x0, 0x0)
	/root/go/src/net/http/server.go:633 +0x32f
net/http.(*conn).serve(0xc820325340)
	/root/go/src/net/http/server.go:1319 +0x727
created by net/http.(*Server).Serve
	/root/go/src/net/http/server.go:1910 +0x3f6

goroutine 20 [IO wait]:
net.runtime_pollWait(0x7f74644b5bc0, 0x72, 0xc82000a190)
	/root/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82033b5d0, 0x72, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82033b5d0, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82033b570, 0xc82037d000, 0x400, 0x400, 0x0, 0x7f74644ac050, 0xc82000a190)
	/root/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820023170, 0xc82037d000, 0x400, 0x400, 0x0, 0x0, 0x0)
	/root/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820359380, 0x7f74644b65a8, 0xc820023170, 0x5, 0x0, 0x0)
	/root/go/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc82036c000, 0xc1ad17, 0x0, 0x0)
	/root/go/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc82036c000, 0xc82036e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/root/go/src/crypto/tls/conn.go:901 +0x167
net/http.(*liveSwitchReader).Read(0xc820325438, 0xc82036e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/root/go/src/net/http/server.go:219 +0xa4
io.(*LimitedReader).Read(0xc82035a7e0, 0xc82036e000, 0x1000, 0x1000, 0x50, 0x0, 0x0)
	/root/go/src/io/io.go:427 +0xbd
bufio.(*Reader).fill(0xc820356660)
	/root/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc820356660, 0xc81ffdb30a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadLine(0xc820356660, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/bufio/bufio.go:357 +0x53
net/textproto.(*Reader).readLineSlice(0xc8203ef560, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/net/textproto/reader.go:55 +0x81
net/textproto.(*Reader).ReadLine(0xc8203ef560, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/net/textproto/reader.go:36 +0x40
net/http.ReadRequest(0xc820356660, 0xc820499960, 0x0, 0x0)
	/root/go/src/net/http/request.go:653 +0xb6
net/http.(*conn).readRequest(0xc8203253f0, 0x0, 0x0, 0x0)
	/root/go/src/net/http/server.go:633 +0x32f
net/http.(*conn).serve(0xc8203253f0)
	/root/go/src/net/http/server.go:1319 +0x727
created by net/http.(*Server).Serve
	/root/go/src/net/http/server.go:1910 +0x3f6

**Comment by jordan-wright** [comment]
That's likely the issue. It looks like in a template you have {{URL}} where it should be {{.URL}} (note the ".")

As it stands, Golangs templating is picky so the server crashes if there are invalid template values. Fixing this should resolve your issue.

**Comment by congriholdplantains** [comment]
Ok, that fixed that, but that was a recent issue. I am still having it crash randomly. Attached is what it looked like today, hours before that URL snafu. 

What data would help troubleshoot it next time it happens? I am hesitating on launching the campaign due to these gophish crashes.

**Comment by congriholdplantains** [comment]
Ah, ID10-T error. I was sshing into the box and not running gophish in the background, so it would eventually shut down when my terminal window shut down or the connection timed out. Has been running for 16 hours so far.

This app is great by the way. I wish there were a few more options for the landing page piece, for example, for those of us running it for internal purposes, allowing you to serve a "you have been phished page, here's what to do", to cut down on the panic and bandwidth needed to deal with end users that fell for it.
