### ISSUE TITLE
Change default list sorting

### ISSUE THREAD

**Issue by yonkavalow** [gophish/gophish#426]
Would like to configure to have lists sort descending by date instead of ascending by name.

**Comment by jordan-wright** [comment]
Which lists are you referring to specifically?

**Comment by yonkavalow** [comment]
The Dashboard and Campaign lists mainly but it could helpful on any of the lists.

**Comment by jordan-wright** [comment]
I've made the change for the campaign tables. For now, I'm leaving the other tables sorted by names since they are not as much time dependent.
