### ISSUE TITLE
Allow tracking of email clients

### ISSUE THREAD

**Issue by recrudesce** [gophish/gophish#427]
I've noticed that when a user clicks on a phishing link, GoPhish logs the browser used. That's great, but can we also do it for the /track/ requests too ?
This would allow us to provide metrics on both the platforms, the browser AND the email clients in use during an engagement.

As an example, this is logged to console when a user gets the tracker image in their email client (Outlook in this case):
`100.100.100.100 - - [11/Nov/2016:09:49:02 +0000] "GET /track?rid=1234567890abcdef HTTP/1.1" 200 106 "" "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E; Microsoft Outlook 14.0.7109; ms-office; MSOffice 14)"`

Thanks :)

**Comment by jordan-wright** [comment]
Yeah, sure, I can get this added.

**Comment by jordan-wright** [comment]
Ok, this should be good to go. If you could build from the latest source and let me know if that fixes the issue, it'd be much appreciated!

Thanks for reporting this!
