### ISSUE TITLE
Format version number

### ISSUE THREAD

**Issue by snori74** [gophish/gophish#429]
In latest v0.2.0:
Very minor thing...
Github download of v0.2.0 - but when run, the gophish GUI "Settings" says: 0.2alpha

**Comment by snori74** [comment]
Some sort of "build number" or build date might also be worth considering. e.g my "from source" test version (from source downloaded two weeks ago), reports itself as "0.2alpha", just as does the latest binary, yet they are presumably different.

**Comment by jordan-wright** [comment]
They are different, I just failed to update the version number for the 0.2 official build. I'll get that updated.

Thanks for the report!

**Comment by jordan-wright** [comment]
I've gone ahead and changed the latest version number to `0.3-dev` in source, as this will track us to the `0.3` milestone.

I'll try to remember to update it when I do the official release 😄 

Thanks for the heads up!
