### ISSUE TITLE
"Redirect to:" after Capture of Submitted Data

### ISSUE THREAD

**Issue by snori74** [gophish/gophish#430]
In latest v0.2.0...
This is a pointer to a "normal" web page - i.e. outside of the rest of the system. It seems to me that it would be preferable to redirect to a named "Landing page" (or similar), i.e. still within 'gophish'. As it is, we now need and extra web server/page.

**Comment by jordan-wright** [comment]
This is to be expected in Gophish's current form. The use case is mainly for red teams.

The idea is that, after receiving credentials for the cloned `foo.com`, the red team member may want to redirect the user to the actual `foo.com` to prevent suspicion.

However, that being said, it's *possible* to send the user to a static page you control via [this method](https://github.com/gophish/gophish/issues/164). Additionally, with the plans for the 0.3 release, I am hoping to [revamp the campaign builder](https://github.com/gophish/gophish/issues/223) which will provide a much more modular way to setup campaign flow.

Hope this helps! Thanks for the report!

**Comment by snori74** [comment]
Aha, makes sense.
