### ISSUE TITLE
"Campaign Timeline" oddness 

### ISSUE THREAD

**Issue by snori74** [gophish/gophish#431]
In latest v0.2.0...
For a queued campaign that has yet to start, the shown date range is: "January 1st 1970 12:00 pm -->> July 1st 2007 11:00 pm" - with (a) no (correct) indication of when the campaign was created, or when it will launch.

**Comment by jordan-wright** [comment]
This is likely the default timescale for chartist, which is the charting library we use. Though, if the campaign hasn't started yet, this shouldn't affect the accuracy of any results.

When the campaign starts, do you see a suitable date range?

**Comment by jordan-wright** [comment]
Going ahead and closing this out for now. @snori74, if you still see this date range after launching a campaign, let me know and we'll continue tracking it down.
