### ISSUE TITLE
What's the difference between the SMTP settings in config.json and the sending profiles?

### ISSUE THREAD

**Issue by parappsys** [gophish/gophish#434]
I've installed GoPhish on Server 2012 R2. I was thinking I'd use SMTP on the server and just allow the host to authenticate against it. This is not going well.

I'm wondering what the settings in the config do, and how they are different than the sending profile? When I try the test message, it just spins and I don't see any connection to the server on port 25.

Thanks for any help you can offer.

**Comment by parappsys** [comment]
It's strange. If I telnet into port 25 and send a test email, it works. I must have some settings incorrectly set within GoPhish.

**Comment by jordan-wright** [comment]
Sorry for the confusion. We handle SMTP settings via the Sending Profiles. The SMTP settings in the config.json were originally meant for handling the smtp server settings, but they aren't used at all.

I've removed the unused smtp settings in the config file.
