### ISSUE TITLE
Fix UI freezing when launching large campaigns

### ISSUE THREAD

**Issue by SEBreniac** [gophish/gophish#437]
This suggestion is to target the UI freezing when a campaign is launched. (I do realize this doesn't solve the campaign results screen).

The 'PostCampaign' function in models/campaigns.go has a for loop on line 313 that creates the `CampaignResult` model for each target in the list. For large target lists, this represents a VERY long time (one DB insert per target), and the UI freezes since it is waiting to get back the response from the POST request.

If the `CampaignResult` model creation loop were put into a different thread, this would allow the UI to get back its HTTP response without waiting/locking up. If there were an error in the `CampaignResult` creation, it could be flagged in the campaign via the `ERROR` const (or perhaps a new const with something more descriptive).

**Comment by jordan-wright** [comment]
I bet I could do something like that. Good suggestion!

**Comment by limp15000** [comment]
That would be great 👍 
I had to export as CSV to be able to look at the results. The interface was freezing constantly and chrome is pegged at 50%.
But I did manage to get my stats so all is good ;)

Thanks for the great tool :)

**Comment by jordan-wright** [comment]
I'm currently working on a UI and associated API overhaul to prevent us from loading unnecessary data.

This should help prevent the frontend from freezing when loading large datasets.

**Comment by suffestuffie** [comment]
I did some tests with current version (0.3dev, 24-2-2017) and found out that it is recommended to split large campaigns into multiple imports/campaings with no more then 500 users. If you use more, then the UI become unusable.

**Comment by S0larflare** [comment]
@suffestuffie You can go higher than that (the highest I've gone is about 790) though the UI is only really useable after you complete the campaign. That said, you can always use the api to get the data you want.

I would say that it might be worth changing the campaign page to either update less often or not make it realtime and include a 'refresh' button.

**Comment by SEBreniac** [comment]
@suffestuffie @S0larflare In our internal build, I modified the default refresh rate on the campaign results page to be much longer. I believe the default from the date of our build was set at 10 seconds which I changed to be 60 seconds. This relieved the UI stress on the browser while viewing campaign results significantly for our larger campaigns (2000+) while maintaining some level of "neartime" data.

File: `/static/js/dist/app/campaign_results.min.js`
![image](https://cloud.githubusercontent.com/assets/16544171/23805237/aa8f8dfe-0582-11e7-89b9-27a192357e46.png)

Side note - not sure if the import bit has been addressed yet. Haven't have a chance to adopt the newest releases since our latest campaign.

**Comment by S0larflare** [comment]
@SEBreniac Yeah that's what I ended up doing on my production server as a quick fix, worked quite well, great minds and all that :P. 

Personally I do think that a longer refresh time of 1 minute should be the standard and a refresh button to manually refresh should be added. I just haven't had a chance to have a go making it.

**Comment by jordan-wright** [comment]
This one appears to have been fixed in bddb9fdb283c3e3f5af44d46386468e4ca225ab3 so I'm going to close it out.
