### ISSUE TITLE
Issue Executing Bin

### ISSUE THREAD

**Issue by GitHubGuru007** [gophish/gophish#440]
When attempting to execute the pre-built binary for the Linux X64 platform the following error is generated. 

gophish: 1: gophish: Syntax error: "(" unexpected

Dash and Bash have both been used unsuccessfully.

![image](https://cloud.githubusercontent.com/assets/23526970/20394608/bcfbe5c2-aca5-11e6-80f2-ccd2fd70d827.png)

**Comment by jordan-wright** [comment]
How specifically are you executing the binary?

**Comment by GitHubGuru007** [comment]
I tried $ sudo sh gophish, bash gophish, dash gophish, sh gophish ./gophish. But the command that worked was sudo ./gophish 

Thank you
