### ISSUE TITLE
AWS and Gophish

### ISSUE THREAD

**Issue by LarryGrim** [gophish/gophish#444]
Trying to setup gophis on Amazon web server (t2.micro Ubuntu 12.04 LTS).  
It works fine from AWS to AWS instance.  As shown by this startup.
[GoPhish.txt](https://github.com/gophish/gophish/files/601819/GoPhish.txt)
When trying to use the public address, it works with port 80, but nothing on 1488.  Public IP is in the /etc/hosts, and custom.json is setup as discussed in different posts in GitHub.
[Gophish2.txt](https://github.com/gophish/gophish/files/601821/Gophish2.txt)
Already turned off any inadvetent firewall settings with
sudo ufw disable and sudo ufw status show Status: inactive.

So, question of the day is why I cannot get to the admin screen from the outside?
Any help is appreciated.
Thanks.

**Comment by LarryGrim** [comment]
While ot would be wonderful to connect with the public website, it works also well with a remote deskstop using Windows Remote Connection.
See AWS note at https://aws.amazon.com/premiumsupport/knowledge-center/connect-to-linux-desktop-from-windows/

**Comment by jordan-wright** [comment]
@LarryGrim it looks like this is definitely an AWS issue, not an issue with Gophish. I see gophish successfully reading the config file and binding to all interfaces on the port you specified.

If afraid providing aws support is out of the scope of our help, but you might be able to check something like [this](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/authorizing-access-to-an-instance.html) and see if that helps.

**Comment by jordan-wright** [comment]
Good deal! Glad you got it up and running!

**Comment by MyNam3IsR00T** [comment]
LarryGrim, could you make a little Tutorial for the install of gophish on AWS instance ? best regards, R00T.

**Comment by LarryGrim** [comment]
R00T,

Working on a full document, which is currently at around 80 pages. Doing a
presentation at a conference for CMS (Department of Health and Human
Services), where I will be talking about both Gophish and PhishingFrenzy
open source phishing campaign tools.  When finished with presentation and
document, will forward.

Thanks,
Larry

**Comment by jordan-wright** [comment]
How exciting!! I hope Gophish is holding its own :)

If you want to chat about any specifics offline, let me know at jordan-wright.com/contact. Happy to answer any questions you may have.

**Comment by MyNam3IsR00T** [comment]
Hi Larry,

It will be great THX Larry, do you know when the doc will be available ?
By the way, good luck for the presentation :)

R00T

**Comment by LarryGrim** [comment]
Current draft, but lots more to add.
Google drive at
https://drive.google.com/open?id=1SBNOvGG_5yDLrWFO336zYn0EozGBc345Zx9EN7_2
Regards,
Larry

**Comment by LarryGrim** [comment]
I hate google docs.
Forget the link.
Should not have tried something new tonight.
Larry

**Comment by LarryGrim** [comment]
Ok.

After twenty minutes with Google Drive, and all that goodness, here is the
link to the start of the build document.  It is in DRAFT.

Assumption was no experience with almost anything related, including Linux
commands, use of Amazon Web Services, or anything else.

https://drive.google.com/file/d/0B_tSZQg1Aov2ckdLSmw5N3F3UGc/view?usp=sharing

Larry

**Comment by jordan-wright** [comment]
That document is looking fantastic, @LarryGrim! I can't imagine the time it's taken you to put all that together. I'm excited to get more time so I can read it more closely.

If/when you're ready to share more broadly, let us know and we'll help make that happen. This is a great resource that so many people can benefit from. 😄

**Comment by MyNam3IsR00T** [comment]
@LarryGrim great draft thx.
