### ISSUE TITLE
Spam indicators

### ISSUE THREAD

**Issue by reynas** [gophish/gophish#447]
using the mail-tester.com website (based upon SpamAssassin) it indicates that we can get a lower spam score by adding alt attributes to images. Can the alt attribute be added to the tracking image as well ? (empty alt should suffice)

**Comment by reynas** [comment]
other indicators on that website can be used in gophish to avoid being tagged as spam

**Comment by jordan-wright** [comment]
I suppose we could do that. Though, a majority of spam indicators will be based on IP/domain reputation, setting up spf/dkim/dmarc properly, and proper email template formatting (which is out of Gophish's control).

If you have resources that people can use to test their templates, I can add it to the documentation.

**Comment by jordan-wright** [comment]
I've added the empty alt attribute. If there are other indicators that are not dependent on the custom HTML used by templates, let me know and I will consider adding them.

Thanks for this report!
