### ISSUE TITLE
Archiving past campaigns

### ISSUE THREAD

**Issue by S0larflare** [gophish/gophish#448]
Currently, after an appropriate time has passed I am closing campaigns and then finally deleting them in order to not clutter the interface (and to make it a bit easier to find the new/current campaigns). However this means that the historic data of a completed campaign is then lost to the aether. Would it be possible to archive old campaigns and place them in their own tab/section. This way they would be viewable in the future if they are needed and don't get in the way of live campaigns.

**Comment by jordan-wright** [comment]
I see an issue to simply order campaigns by the created date. Would that be sufficient?

**Comment by S0larflare** [comment]
Personally, I would say no. Ordering would be useful regardless, and would help when going through both active and archived campaigns. But the advantage of being able to archive campaigns when they aren't needed any more would be shown when you have a large amount of campaigns. As I am currently making one campaign out of multiple smaller campaigns (the only real way to do some kind of randomised/staggered sending at the moment) I am ending up with a large amount of campaigns at the end of it. If completing these campaigns put them into a different place, so that they aren't front and centre but under their own tag/tab on the campaigns area, it would make it a lot easier to track live campaigns whilst still having the historic data for older campaigns.

**Comment by tmgordon** [comment]
You can create a new user account when you want a fresh campaign list until this is implemented. I would like to see a way to transfer campaigns from one user to another though.

**Comment by S0larflare** [comment]
I built this in to my prod build so long ago I forget that it’s not a feature. I created a separate tab on the campaign screen for active and archived campaigns, makes it a lot cleaner. I’ll update and make a PR for it when reporting gets merged
