### ISSUE TITLE
Not able to Build: cgo.exe: exit  status 2

### ISSUE THREAD

**Issue by dalvirsaini** [gophish/gophish#451]
I am facing gone more issue to build that is
C:\Projects\Go\src\github.com\gophish\gophish>go build
go build github.com/mattn/go-sqlite3: C:\Go\pkg\tool\windows_amd64\cgo.exe: exit
status 2

so how to fix it

**Comment by jordan-wright** [comment]
You'll need to make sure you have a compiler in your path.

I think go build has a "-v" option for verbose logging. What do you see when you run it with "-v"?

**Comment by dalvirsaini** [comment]
its fixed by installing the correct version of  MIngw.
