### ISSUE TITLE
Request landing page

### ISSUE THREAD

**Issue by AgoraSecurity** [gophish/gophish#452]
I want to put a simple redirect on the main domain.

If the user only visits evil-domain.com I want to redirect them to the client's domain. Is that possible?

It would also be nice to put a simple landing page (maybe not a redirect), for example:
evil-domain.com/ --> Static page explaining that this is an engamenet
evil-domain.com/?XXX --> Normal GoPhish websites
evil-domain.com/static/... --> Normal GoPhish static websites

I know that a workarround would be to use Apache/Nginx as a proxy and redirect the traffic accordingly, but using only GoPhish is quite easier and faster.

Cheers

**Comment by jordan-wright** [comment]
The informational index page will need to be changed in the code itself. At this time, I'm going to keep the default to be a 404 page. You can change [this line](https://github.com/gophish/gophish/blob/master/controllers/route.go#L165) to be a 302 redirect, or whatever you want Gophish to do.

Hope this helps!
