### ISSUE TITLE
Phishing Success Overview Graph Error

### ISSUE THREAD

**Issue by S0larflare** [gophish/gophish#461]
This is a pretty small one, but occasionally the graph doesn't calibrate its y axis properly and can therefore miss a few points if you have multiple campaigns.

Example: https://s13.postimg.org/4w9a7p9tz/graph.png

**Comment by jordan-wright** [comment]
What browser are you using?

**Comment by S0larflare** [comment]
That's with Firefox 50.0.1, I have checked and it does seem to do it correctly in IE.

**Comment by jordan-wright** [comment]
Yeah, the charts are kinda messed up in FF. I'm going to be doing a UI overhaul soon, which should fix this.

**Comment by S0larflare** [comment]
Going through old issues I have open. Considering GoPhish uses entirely different graphs now this is no longer relevant:smile:
