### ISSUE TITLE
How to use damain in "listen_url" of admin_server

### ISSUE THREAD

**Issue by dalvirsaini** [gophish/gophish#463]
How to use damain in "listen_url" of admin_server?

suppose I have a domain like www.example.com . I want to run gophish on this domain. how I can do it? 

I tried to use this but it saying that port is required. 

I tried to use "www.example.com:80"

but following error comes to run binary 
**tcp myip:80: bind: The requested address is not valid in its context.**

Note: This is my azure server with reserved IP

**Comment by jordan-wright** [comment]
Just put the domain in the URL field when making campaigns. As long as the domain resolves to the IP gophish is listening on, it will work just fine.
