### ISSUE TITLE
Importing group via API

### ISSUE THREAD

**Issue by CarterMcKelvain** [gophish/gophish#465]
(please mark as question)
Hi all,
I'm fairly new to python/API's and I'm trying to help automate some of our tasks. Currently I have a powershell script that pulls user data from AD and puts it into a csv with the correct headers (I have tested uploading the generated file and it works). I now am trying to push that file to our gophish server through the api.

Here is what I have so far (again, very new to this, apologies!):

```
import requests

api_key = 'redacted'
url = 'http://redacted:3333/api/import/group'

headers = {
    'Content-Type': 'multipart/form-data; boundary=----BOUNDARY'
}

files = {'file': ('test.csv', open('test.csv', 'rb+'))}
res = requests.post(url + "?api_key=" + api_key, files=files, headers=headers)
print res.status_code
```

When I run this I get a the following error:

```
Traceback (most recent call last):
  File "C:/redacted/gophish_group_push.py", line 11, in <module>
    res = requests.post(url + "?api_key=" + api_key, files=files, headers=headers)
  File "C:\Python27\lib\site-packages\requests\api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

I assume this has to do with the my headers, although I'm not sure. In the API documentation it has a "body" section that I do not know what to do with. I've googled as best as I can and still have come up short. This is also my first time using requests for python. Please let me know if you need any more information. Thank you!

**Comment by CarterMcKelvain** [comment]
Ok so I think I am starting to figure more out. It looks like it is loading the file correctly. (I added res.text to see the text output.) Here is where I'm at now, I added the headers to the files= instead of having them separate.

`import requests

api_key = 'eb65a9f488ab432872ba065b39729eaa541b9db6e4033a2fb56ec026904e9ab6'
url = 'http://az-sec-01.cloudapp.net:3333/api/import/group'

files = {'file': ('test.csv', open(r'test.csv', 'rb+'), {'Content-Type': 'multipart/form-data; boundary=----BOUNDARY', 'Content-Disposition': 'form-data; name="files[]"; filename="test.csv"'})}
res = requests.post(url + "?api_key=" + api_key, files=files)
print res.status_code
print res.text`

**Comment by CarterMcKelvain** [comment]
alright so after sending that

**Comment by CarterMcKelvain** [comment]
I also wanted to ask this... Do you need to specify the api key in a POST? I'm still pretty confused on this. If anyone has an example of this it would help me greatly. Thank you!

**Comment by Vanhecke** [comment]
Hey @CarterMcKelvain ,
You have to supply the API key with every request (including POSTs).

I have my target lists in JSON format and import them using [httpie](https://github.com/jkbrzt/httpie)

`http post localhost:3333/api/groups/?api_key=API_KEY < targets.json`

With targets.json looking like this:

```json
{
  "id": 1,
  "name": "Target Group 1",
  "modified_date": "2015-01-01T01:02:03.000000Z",
  "targets":
	[
		{
		  "id": 1,
		  "first_name": "Christina",
		  "last_name": "Morrison",
		  "email": "Christina.Morrison@example.com",
		  "position": "Software Engineer"
		},
		{
		  "id": 2,
		  "first_name": "Judy",
		  "last_name": "Ellis",
		  "email": "Judy.Ellis@example.com",
		  "position": "Product Engineer"
		}
	]
}

```

**Comment by CarterMcKelvain** [comment]
@Vanhecke Thanks for the reply! I'm going to try this. I have a large list in .csv format so I'll try to get it into the .json like you have. I'm pulling from AD so I might try to just put it in that format with my powershell script. I appreciate you responding. I'll update when I figured it out/have a problem. Thanks!

**Comment by CarterMcKelvain** [comment]
Alright @Vanhecke , I made the following powershell script that puts it all in the right format. It makes it in the same structure that you have it in. Once I try to post it with httpie, it keeps saying "Invalid json structure. Below the code you can see a sample output that it did. I then tried to use your exact exact example and it said the same thing. Any ideas? Latest version? 

```
# We first need to specify which AD group we want to work with
$Groups = Get-ADGroup -filter {Name -like 'REDACTED' } | Select-Object Name

# Next we need to initialize our counter
$counter = 1

# Next we need to pull users from AD with their first name, last name, email, and department
$output = 
    ForEach ($Group in $Groups) {
        Get-ADGroupMember -identity $($group.name) -recursive | `
        Get-ADUser -Properties mail, Title, Department, GivenName, Surname | `
        Select-Object ('mail', 'GivenName', 'Surname', 'Department') | `
        Select `
        @{Name="first_name";Expression={$_."GivenName"}},
        @{Name="last_name";Expression={$_."Surname"}},
        @{Name="email";Expression={$_."mail"}},
        @{Name="position";Expression={$_."Department"}}
    }

# Next we need to put the output into a format that GoPhish can read. We use an array in an array to do this. The top array has the "headers" for GoPhish.
# The next array inside the targets has the users with data.
$body = @{
    id = 1
    name = "All Users - Updated Weekly"
    modified_date = "2015-01-01T01:02:03.000000Z"
    targets = $output | sort email -Unique | `
                Where-Object {$_."last_name" -ne $NULL} | `
                Where-Object {$_."email" -Match "@REDACTED" -or $_."email" -Match "@REDACTED" -or $_."email" -Match "@REDACTED"} | `
                Where-Object {$_."email" -NotMatch "REDACTED"` -and `
                    $_."email" -NotMatch "REDACTED" -and `
                    $_."email" -NotMatch "REDACTED" -and `
                    $_."email" -NotMatch "REDACTED" -and `
                    $_."email" -NotMatch "REDACTED" -and `
                    $_."email" -NotMatch "REDACTED" -and `
                    $_."email" -NotMatch "REDACTED" -and `
                    $_."email" -NotMatch "REDACTED" -and `
                    $_."email" -NotMatch "REDACTED" -and `
                    $_."email" -NotMatch "REDACTED" -and `
                    $_."email" -NotMatch "REDACTED" -and `
                    $_."email" -NotMatch "REDACTED" -and `
                    $_."email" -NotMatch "REDACTED" -and `
                    $_."email" -NotMatch "REDACTED" -and `
                    $_."email" -NotMatch "REDACTED" -and `
                    $_."email" -NotMatch "REDACTED"} | `
                    sort "email" -Unique | `
                    Select-Object @{ Name = "id" ; Expression= {$global:counter; $global:counter++} }, first_name, last_name, email, position

    }

# Finally we need to specify our command that this script will run, convert it to json
$body | ConvertTo-Json | Out-File "C:\REDACTED\Desktop\targets.json"
```


Sample output:
```
{
    "name":  "All Users - Updated Weekly",
    "id":  1,
    "modified_date":  "2015-01-01T01:02:03.000000Z",
    "targets":  [
                    {
                        "id":  1,
                        "first_name":  "test2",
                        "last_name":  "test2",
                        "email":  "test2@test.com",
                        "position":  "test2"
                    },
                    {
                        "id":  2,
                        "first_name":  "test",
                        "last_name":  "test",
                        "email":  "test@test.com",
                        "position":  "test"
                    }
                ]
}
```
So, I'm really not sure what's going wrong, any input?

**Comment by CarterMcKelvain** [comment]
Here is the exact command that I ran plus the result.

C:\REDACTED\Desktop>http post http://REDACTED:3333/api/groups/?api_key=REDACTED < targets.json
HTTP/1.1 400 Bad Request
Access-Control-Allow-Origin: *
Content-Encoding: gzip
Content-Length: 96
Content-Type: application/json
Date: Fri, 02 Dec 2016 15:12:04 GMT
Vary: Accept-Encoding

{
    "data": null,
    "message": "Invalid JSON structure",
    "success": false
}

**Comment by jordan-wright** [comment]
You might try removing the "id" attributes, since those are automatically filled in by Gophish.

Sorry I haven't gotten a chance to dive deeper into this yet!

**Comment by CarterMcKelvain** [comment]
Alright. I'm closing this as I solved it finally! I had to encode the json in Ascii (to make sure the it didn't encode with UTF8/BOM) and it works flawlessly. Thanks for steering me in the right direction @Vanhecke ! Here is my powershell script for anyone else that needs to do something like this!

```
# We first need to specify which AD group we want to work with
$Groups = Get-ADGroup -filter {Name -like 'REDACTED' } | Select-Object Name

# Next we need to initialize our counter
$counter = 1

# Next we need to pull users from AD with their first name, last name, email, and department
$output = 
    ForEach ($Group in $Groups) {
        Get-ADGroupMember -identity $($group.name) -recursive | `
        Get-ADUser -Properties mail, Title, Department, GivenName, Surname | `
        Select-Object ('mail', 'GivenName', 'Surname', 'Department') | `
        Select `
        @{Name="first_name";Expression={$_."GivenName"}},
        @{Name="last_name";Expression={$_."Surname"}},
        @{Name="email";Expression={$_."mail"}},
        @{Name="position";Expression={$_."Department"}}
    }

# Next we need to put the output into a format that GoPhish can read. We use an array in an array to do this. The top array has the "headers" for GoPhish.
# The next array inside the targets has the users with data.
$body = @{
    id = 1
    name = "All Users - Updated Weekly"
    modified_date = "2015-01-01T01:02:03.000000Z"
    targets = $output | sort email -Unique | `
                Where-Object {$_."first_name" -ne $NULL} | `
                Where-Object {$_."email" -Match "REDACTED" -or $_."email" -Match "REDACTED" -or $_."email" -Match "REDACTED"} | `
                Where-Object {$_."email" -NotMatch "REDACTED"` -and `
                    $_."email" -NotMatch "REDACTED" -and `
                    $_."email" -NotMatch "REDACTED" -and `
                    $_."email" -NotMatch "REDACTED" -and `
                    $_."email" -NotMatch "REDACTED" -and `
                    $_."email" -NotMatch "REDACTED" -and `
                    $_."email" -NotMatch "REDACTED" -and `
                    $_."email" -NotMatch "REDACTED" -and `
                    $_."email" -NotMatch "REDACTED" -and `
                    $_."email" -NotMatch "REDACTED" -and `
                    $_."email" -NotMatch "REDACTED" -and `
                    $_."email" -NotMatch "REDACTED" -and `
                    $_."email" -NotMatch "REDACTED" -and `
                    $_."email" -NotMatch "REDACTED" -and `
                    $_."email" -NotMatch "REDACTED" -and `
                    $_."email" -NotMatch "REDACTED"} | `
                    sort "email" -Unique | `
                    Select-Object @{ Name = "id" ; Expression= {$global:counter; $global:counter++} }, first_name, last_name, email, position

    }

# Lastly we need to convert it to ascii so that gophish can read it and send it via api.
$body = $body | ConvertTo-Json
$body | Out-File  -Encoding ascii "C:\REDACTED\targets.json"
$filecontent = Get-Content 'C:\REDACTED\targets.json'

Invoke-RestMethod -Uri "http://REDACTED:3333/api/groups/1?api_key=REDACTED" -Method Delete
Invoke-RestMethod -Uri "http://REDACTED:3333/api/groups/?api_key=REDACTED" -ContentType "application/json" -Method POST -body ([System.Text.Encoding]::ASCII.GetBytes($filecontent))

**Comment by aieeeeeeeee** [comment]
Hi all, 

I'm sorry but I have a similar issue. 

Here the content of my json file:
`{
        "name": "testAPI",
        "targets": [
            {
                "email": "benoit@gmail.com",
                "first_name": "benoit",
                "last_name": "lastname",
                "position": "here"
            }
        ]
}`

I'm using httpie as follows:
`http -f POST  http://SERVER_IP:3333/api/groups/\?api_key\=API_KEY < test.json`

And I get the following error message:

> HTTP/1.1 400 Bad Request
Access-Control-Allow-Origin: *
Content-Length: 77
Content-Type: application/json
Date: Tue, 17 Jan 2017 15:10:41 GMT
Set-Cookie: csrf_token=behObGGx5kTW9t1wseIygRR0RBWl14flORNjic2zzpE=; Max-Age=31536000
Vary: Cookie

{
    "data": null,
    "message": "Invalid JSON structure",
    "success": false
}

> 

Any clue?

Thanks in advance.

**Comment by jordan-wright** [comment]
Just as a heads up, I'm in the process of making an official Python API client which should hopefully make it much easier to do these kinds of things.

It's not done yet, but you can follow the progress here https://github.com/gophish/api-client-python

I'll make a formal announcement when version 0.1 is ready for alpha testing :)

**Comment by aieeeeeeeee** [comment]
Great news! Nevertheless I'm still stuck (until you release the official python API client ;-) ) and to be honest what I can't understand because even when I redirect the output of a GET in a .json file and use the same json file (after having modified the ID) as input I stil get the same error: "Invalid JSO structure". Any clue?

**Comment by jordan-wright** [comment]
Can you show the exact steps you do to reproduce the issue? I can try to troubleshoot from there.

**Comment by aieeeeeeeee** [comment]
`http http://SERVER_IP:3333/api/groups/\?api_key\=...> test.json`

Then I modify a little bit the test.json and then I do the following:
`http -f POST  http://SERVER_IP:3333/api/groups/\?api_key\=... < test.json
`

**Comment by Vanhecke** [comment]
@jordan-wright I applaud the cli client - I have a bunch of bash scripts but am too embarrassed to share.

@aieeeeeeeee If gophish says invalid JSON structure its because it couldn't parse your request.
Did you try sending with `http -j POST` in stead of `http -f POST`? That's what I'm doing.

**Comment by aieeeeeeeee** [comment]
Great, thanks Vanhecke!!!
