### ISSUE TITLE
Landing page is not available

### ISSUE THREAD

**Issue by dalvirsaini** [gophish/gophish#467]
Hi, 

I am creating a landing page like with name Test  
Adding some html there.

now when i am running the url http://localhost:3333/Test   then its saying that page not found

so how i can view my landing page and what should be the correct url so that i can use in email templates.

while creating campaign i am using the URL value as 
 **http://localhost:3333**

and now in email the link redirecting to like this 
http://localhost:3333/?rid=f4fcbd8fcc2d4add757685979aacdad5cb551e1e3a422dbe5af247d10d54acf6

Email template is : 

Dear {{.FirstName}},
Please access the following link:
{{.URL}}

Pls help me to get rid of this .. 

Which link will work for the landing pages associated with campaign. I need format for the landing page that I should use.

Thanks
Dalvir

**Comment by jordan-wright** [comment]
Please refer to the [user guide](https://www.gitbook.com/book/gophish/user-guide/details) for information on how this is setup. It explains step by step how to setup a campaign.

You cannot test landing pages outside of the HTML editor.

**Comment by dalvirsaini** [comment]
ok now issue fixed
