### ISSUE TITLE
Capture Submited data

### ISSUE THREAD

**Issue by dalvirsaini** [gophish/gophish#470]
I created a email template saying to reset user password and sending him on the link to reset password landing page. 

the landing page html is like this 
```

<html><head></head><body>
<form action="">
Email: <input type="text" name="email"/><br/>
password: <input type="password" name="pwd"/><br/>
<input type="submit" value="submit"/>
</form>

</body></html>

```

While creating my landing page the check box to capture submitted data and to capture password are checked. 

Now in landing page I want to capture this data. 

So how this capture data logic will work

as on submit i am redirecting to the listner url with the query string like 
http://192.168.170.1:88/?email=sdsad%40ss.com&pwd=dsadsa

I think there is something missing from my end. But not getting what is that.. could you let me know how to do it.

one more question:

For the landing page my url is generating like this after click on links in email 
http://192.168.170.1:88/?rid=64b36f70acc4284a7fbb07c5d25a94ccd5b059386042d2b3945955f418f624fe
can we customize this url like 

http://192.168.170.1:88/Landing/custom?rid=64b36f70acc4284a7fbb07c5d25a94ccd5b059386042d2b3945955f418f624fe

Note:
phish listen_url =http://192.168.170.1:88
admin_server listen_url =http://192.168.170.1:33

**Comment by S0larflare** [comment]
I don't quite get your meaning. Gophish changes this for you. Tick the box on the landing page for "Capture submitted data" and then put the redirect url in below it, in the "redirect to" field. You should have the user submitted to the page you specify and you should get the credentials they used in the console.

**Comment by dalvirsaini** [comment]
First of all I have 
phish listen_url =http://192.168.170.1:88
admin_server listen_url =http://192.168.170.1:33

Now I mean to say that if there is a reset password landing page  and on submit
What redirection url i need to use so that I can see  the submitted data in dashboard page. 
I am following the process: 
1) Created a landing page with reset password fields. 
2) Check box to capture submitted data are checked
3) In redirect url I used http://192.168.170.1:88 as redirect url .. 
Is this redirect url ok or I can use any other url like http://www.goggle.com etc.
Now when user will submit the form then where I should redirect to him? This is the main questions from my side.. so that submitted data can be captured automatically by gophish.

Thanks
