### ISSUE TITLE
Automatically splitting groups

### ISSUE THREAD

**Issue by reynas** [gophish/gophish#472]
Certain mailservers are limited to sending batches of e-mails.
e.g. eurodns supplies a free mailbox when purchasing a domain name. These are limited to sending 25 mails at once. When importing a user list, it can be useful to have an option to automatically split these users into groups of (in this case) 25 users. 

Can this be done?

**Comment by jordan-wright** [comment]
Hey @reynas! This is a perfect use case for the API. I would recommend leveraging the Gophish API to handle this for you.

I can't see us integrating this into the web UI at this time.
