### ISSUE TITLE
Docker gophish issue 0.2

### ISSUE THREAD

**Issue by amlwwalker** [gophish/gophish#474]
Hi, I was using matteoggl/gophish/ docker container for running gophish. It's an old version so I wanted to update to 0.2. The only thing i changed was the url to the zip to download to: `https://github.com/gophish/gophish/releases/download/v0.2.0/gophish-v0.2-linux-64bit.zip`

matteoggl/gophish is using: `https://github.com/gophish/gophish/releases/download/v0.1.2/gophish_linux_64bit.zip`

Now when I go to the url, I get: `400 Bad Request: too many Host headers`

Any ideas as to what must have changed in the update to result in this?

**Comment by jordan-wright** [comment]
Hi @amlwwalker, I'm afraid the Dockerfile is a community contribution and not officially supported by gophish.

I recommend contacting @matteoggl if you are having issues with the Dockerfile.

Sorry there isn't more we can do to help!
