### ISSUE TITLE
Extensions for file Upload?

### ISSUE THREAD

**Issue by dalvirsaini** [gophish/gophish#475]
What file extensions can be used to attach as a file>?

Can I use .exe? 
as if I am using .exe then I am not getting email.

**Comment by jordan-wright** [comment]
All file extensions are allowed for attachment upload. It's likely your email server is filtering emails with .exe attachments. There is nothing gophish can do to help with this.

Try using something like Mailhog as your testing smtp server and, if the emails still don't show up, let me know and we can re open.
