### ISSUE TITLE
How to Use Doman Instead of IP

### ISSUE THREAD

**Issue by dalvirsaini** [gophish/gophish#477]
Here are my phishing server setting 

"admin_server" : {
		"listen_url" : "IP:33",
		"use_tls" : false,
		"cert_path" : "gophish_admin.crt",
		"key_path" : "gophish_admin.key"
	},
	"phish_server" : {
		"listen_url" : "IP:88",
		"use_tls" : false,
		"cert_path" : "example.crt",
		"key_path": "example.key"
	},

*Ip: Pubic Ip of my server 
* My server already has 2-3 more sites deployed those are running on port 80 

the above is working as expected. 

Now instead of Ip I want to use doamin like this. these are sub doamins of mydomain.com

adminserver.mydomain.com

phishserver.mydomain.com

How I can use these here.

Is it posible to use? 

if yes then what are steps? 
I tried following: 
a) "adminserver.mydomain.com:80" -- Erro An attemp
t was made to access a socket in a way forbidden by its access permissions

b)  or "http://adminserver.mydomain.com" -- error too many colons are in address

c)  Or "www.myadminserver.com"-- missing port error

as I tried all these and facing issue 

Plz help to get rid of this.

**Comment by S0larflare** [comment]
Yes, you can. I have mine set up as a hostname with the default 3333 port.

"listen_url" : "hostname.tld:3333",

Should do it from gophish's side.

**Comment by dalvirsaini** [comment]
I want to get rid of this port.. and just want to use this tool like http://adminserver.mydomain.com..

Is it now possible without port??

**Comment by jordan-wright** [comment]
No, the port is needed in the gophish config. If you just specify the default ports (80 for http, 443 for https) then when you actually use the URLs in your browser you don't need to include them.

But they always have to be included in the config.
