### ISSUE TITLE
Launch Campaign Button does nothing

### ISSUE THREAD

**Issue by gjayne84** [gophish/gophish#479]
Hi, I've run into a strange issue and I'm not sure how to proceed.  I'd be grateful if anyone could give me some pointers so I can get my first campaign up and running.

I'm running Gophish from the pre-built 64-bit WIndows binary and have successfully setup a sending profile, user group, e-mail template and landing page.  However, when I now try creating a campaign I fill in all the details and then click Launch Campaign, but nothing happens?  I don't get any error in the terminal or in the browser.  The campaign screen just stays open.

Would anyone be able to help me with what could be causing the problem, or how I can find any more info?  Even to be able to find an error would be helpful because at the moment I've got nothing to go on to troubleshoot.

Thanks in advance for your help.

**Comment by CarterMcKelvain** [comment]
Hi! How large is your list of users?

**Comment by gjayne84** [comment]
Hi, at the moment there's just one user in the group.  I've tested sending to this user using the sending profile and the test e-mail was sent successfully.

**Comment by S0larflare** [comment]
I had this problem a while back and couldn't work out why for a while. Turns out that it was because I was using IE and Promises aren't properly supported in IE. If that's true for you, try a different browser? If it's not that, try opening up the developer tools to see if you can find where the error comes from.

**Comment by gjayne84** [comment]
Thanks so much for your help.  Just tried this in Chrome and it worked perfectly.  Thanks again!

**Comment by S0larflare** [comment]
No worries, glad I could help!
