### ISSUE TITLE
Profile setup New Campaign started - doesn't save

### ISSUE THREAD

**Issue by Sliinno1** [gophish/gophish#481]
Hi we have the Windows version running locally on a Windows 7 laptop, launched the gophish.exe and this launches okay. I can login to the console (http://localhost:3333) okay. I can create Users & Groups, Email templates, Landing Pages, Sending Profiles and configured the settings to point to our email server. I've managed to send a test email successfully. However when trying to run a campaign - I fill in all the fields - however I cannot save the campaign - and it fails to start. Am I missing anything. I've attached some screenshots that might help.

[Launch Campaign Nothing happens.docx](https://github.com/gophish/gophish/files/634197/Launch.Campaign.Nothing.happens.docx)

**Comment by S0larflare** [comment]
Looking at the screenshots, i can't see the error that you're getting. Is this the same as #479? Are you using IE?

**Comment by jordan-wright** [comment]
@Sliinno1 - any updates on this one? Are you using IE, as @S0larflare suggested?

**Comment by jordan-wright** [comment]
Closing this out as there hasn't been updates in over 2 weeks. @Sliinno1, if you're still having issues, please confirm that @S0larflare's advice did not address the issue and please provide us with any additional information you have so we can help troubleshoot.
