### ISSUE TITLE
I can Launch a campaign but no results in the DashBoard

### ISSUE THREAD

**Issue by Sliinno1** [gophish/gophish#483]
Hi 

I have created a number of campaigns - I have been able to successfully send out emails and these have been received by Recipients. However the dashboard does not update - it has a status of Emails Sent - even though the scheduled date has elapsed. Should I be expecting a list of users who has clicked on the link - as I don't. I've attached some screenshots to help describe the issue somewhat better. This is running on a Windows Laptop with a Chrome Browser.
![gophish results1](https://cloud.githubusercontent.com/assets/24413559/21094480/24bc4da2-c04f-11e6-949f-d11da71a3c5d.PNG)
![gophish results3](https://cloud.githubusercontent.com/assets/24413559/21094482/24cf7f26-c04f-11e6-8b26-7e16228a3708.PNG)
![gophish results2](https://cloud.githubusercontent.com/assets/24413559/21094481/24c24450-c04f-11e6-8fa7-b96febe15c1f.PNG)

I hope someone can help me.

Thanks

Simon

**Comment by snori74** [comment]
Can receipient's "see" your laptop? 

The URL that you provide when you create the campaign needs to point to where your Gophish server is (you laptop) - and recipients need to be able to browse directly to there. If you're sending to your co-workers who share a LAN segment with you, then probably *they* can directly access port 80 on your laptop - but it's unlikely that anyone else can.

**Comment by jordan-wright** [comment]
@snori74 hit the nail on the head. My guess is that the URL you used in your campaign is not reachable by the targets. 

Make sure that the URL used in the campaign points to gophish'a phish server and is reachable by all targets.

**Comment by Sliinno1** [comment]
Hi thanks for the feedback, the clients can ping my address as we are on the same LAN segment. However they cannot hit the URL - they get page cannot be displayed - I've attached some screenshots that might assist and help you point me in the right direction. No Firewall is enabled. The URL specified is just my IP address. Do I need to add anything else or enable any additional features to allow this to work?
![campaign test 2](https://cloud.githubusercontent.com/assets/24413559/21178906/84cb7ca4-c1e9-11e6-99b6-08f180c9f935.png)
![campaign test 1](https://cloud.githubusercontent.com/assets/24413559/21178907/84d47a3e-c1e9-11e6-88d6-be6113762a09.png)

**Comment by jordan-wright** [comment]
You're not actually using "10.1" as the IP address, are you? Because that's not an IP address. You'll need all four octets of your IP address for people to be able to connect to you.

**Comment by rayansami** [comment]
Hi , I'm facing the same kind of problem. My target users are from different networks. That's why I used my public ip on Campaign URL field . When I click the link on mail (from different network) it redirects me to router's admin page rather then my created landing page on gophish. What am I missing here?

**Comment by snori74** [comment]
As in my responce to Sliinno1, your targets need to be able to "see" the machine where gophish is hosting the page. If this is your laptop or PC on a LAN it won't be visible (normally) outside that LAN. Google for "router NAT" for one approach to resolving this - the other is to host gophish externally 'in the cloud'.

**Comment by Sliinno1** [comment]
Hi all

I am still facing the same issues. The recipients who receive the email are all on the same network in the same subnet. They can ping my machine no problem - however they cannot http:// on to my machine - I wonder if that is the issue - is there something I need to do to make this work. This is a windows 7 machine. Looking forward to your responses and hoping we can get this to work.

**Comment by jordan-wright** [comment]
It's possible that the Windows Firewall is blocking the connections. You'll need to make sure the gophish executable is allowed through the firewall.

Then, I would recommend you have one of your users manually try to connect to your machine. If it works (meaning they just hit http://your_ip), they should see a `404 Not found` text error.

**Comment by jordan-wright** [comment]
It looks like everything is actually working. The default Gophish page is a `404 - Page Not found` page. Gophish loads the actual phishing page content dynamically by looking at the `rid` parameter sent with the URL. This parameter is created for every target in a campaign.

How are you referencing the Gophish server in the email template itself? You'll want to make sure you setup the links to point to `{{.URL}}` like we show in the documentation, since that will add in the correct links for you.

**Comment by jordan-wright** [comment]
Closing this out, since things appear to be working. Just make sure you're using the `{{.URL}}` template variable when setting up your links so that the `rid` parameter is created the right way and you should be good to go!

**Comment by Sliinno1** [comment]
Jordan just before you close this - can you confirm are we expecting too much. I was expecting to see a report of not just the emails sent but the users who have opened the email and people who have actually clicked on the email as well. is this right - if so - can we leave this case open?

**Comment by Amitdassabtin** [comment]
hello someone here??

**Comment by Amitdassabtin** [comment]
![Screenshot 2024-05-22 212214](https://github.com/gophish/gophish/assets/87874623/8a2eb8c6-0c5c-45f0-af30-c965fd272d16)
what is this??
