### ISSUE TITLE
More statistics on campaign page

### ISSUE THREAD

**Issue by reynas** [gophish/gophish#484]
Could you add more statistics to the campaign page, such as the time needed to phish the first person, a list of unique user-agents and IP's , ... maybe some other statistics?

**Comment by jordan-wright** [comment]
I'll consider adding other statistics in the UI refresh, but I'm afraid it won't be any time soon, since there is a bunch of higher priority items to take care of.

In the meantime, all of these statistics can be gathered from the API if you need them for a given campaign.

**Comment by jordan-wright** [comment]
Going ahead and closing this out for now since there is a way to get the information you're asking for from the API and we already have tasks open for the upcoming UI redesign.
