### ISSUE TITLE
Some examples of API use from Python

### ISSUE THREAD

**Issue by snori74** [gophish/gophish#487]
I've just opened up some Python scripts which you can find at github.com/CommArc/phishbuckets. The scripts themselves reflect our own needs so may not be of much use to anyone else - but the examples of API calls could be a handy start. Comments welcome.

**Comment by jordan-wright** [comment]
Excellent! Thanks, @snori74!

I'm working on revamping the API docs to include code samples, but this is a great resource.

**Comment by jordan-wright** [comment]
@snori74 Just wanted to close the loop on this one. I've published a [Python API client](https://github.com/gophish/api-client-python) that should help make integrating with Gophish a bit easier.

Hope it helps! Thanks again for sharing your resources 😄
