### ISSUE TITLE
README.md (and hence landing page) documentation link..?

### ISSUE THREAD

**Issue by Antwebb** [gophish/gophish#488]
Going to https://github.com/gophish/gophish and scrolling down to read the README.md gives

Documentation
Documentation can be found on our site. Find something missing? Let us know by filing an issue!

Linking to https://getgophish.com/documentation/

Whereas on https://github.com/gophish/gophish/releases we have

Moving Documentation

You'll notice that this release no longer contains a PDF of our User Guide. I'm experimenting with different ways to open up documentation to changes from the community. Right now, I've moved nearly everything to our wiki, but will continue tracking down the right fit for the Gophish documentation.

Linking to https://github.com/gophish/gophish/wiki

**Comment by jordan-wright** [comment]
I've added an update to the release to point to the new documentation at our Gitbooks repo here: https://www.gitbook.com/@gophish

Always trust the link I have on the getgophish.com website - it will be authoritative.

Thanks for the report! Sorry for any confusion.
