### ISSUE TITLE
CSV Company Field

### ISSUE THREAD

**Issue by dragontologist** [gophish/gophish#492]
The CSV file requires a Company header, but the User Guide doesn't mention this except when showing an example of the CSV. The actual program doesn't appear to store this information, and {{.Company}} is an invalid command. It'd be nice to have this added as an optional field in each user.

Additionally, the CSV columns are in a different order than the Users & Groups displays it - it reverses Email and Position.

**Comment by S0larflare** [comment]
I didn't know what you meant, but looking at the guide I can see the problem you mention. Not sure why the Company header is there as it isn't something that is required at all. The CSV example is wrong as it has spaces in the headers anyway, the CSV should be something like:

FirstName,LastName,Email,Position
Joe,Bloggs,j.bloggs@example.com,CEO

**Comment by jordan-wright** [comment]
I've updated the User Guide to remove the reference to the Company field - sorry for the confusion!

That field shouldn't be required at all. If you're experiencing issues that indicate the field is missing, let me know and we'll track them down.
