### ISSUE TITLE
Credentials are not being captured

### ISSUE THREAD

**Issue by jey45** [gophish/gophish#494]
Hi all,
I am having trouble with the password capture feature of the Gophish program. I have been able to use it previously on a workstation under lab conditions but it does not seem to be capturing any submitted data when I use it in production over a server. I am using windows 10 on a OS 2012 R2 server. The email service I have been using is Microsoft Outlook. I have tried the last two versions of Gophish and both receive the same problem, it is telling me that someone has submitted credentials but it is not capturing the data which they have submitted.

**Comment by jordan-wright** [comment]
There are a bunch of reasons that input may not be captured. I recommend searching through other issues to find similar cases and see if they apply.

If you're still having issues, we'll need a copy of the landing page HTML (pasted between code blocks using ```) in order to help debug.

**Comment by jordan-wright** [comment]
Closing this as there hasn't been any added information in over a week.

@jey45, if you're still encountering issues, please provide a copy of the landing page HTML and we'll be happy to continue troubleshooting.
