### ISSUE TITLE
Default credentials wrong on page 9 of the .pdf user guide (very frustrating)  its admin/gophish not gophish/gophish

### ISSUE THREAD

**Issue by lonegray** [gophish/gophish#495]
The default credentials are wrong on page 9 of the .PDF users guide
(https://getgophish.com/documentation/   click on users guide, look on page 9)  

The manual reads the default credentials are:   gophish/gophish but it should be admin/gophish in gophish v2.0

**Comment by jordan-wright** [comment]
Sorry about that - my bad. It's been fixed in the Gitbook docs, which is what the website points to.

Good catch!
