### ISSUE TITLE
Tracker being counted as a "click"

### ISSUE THREAD

**Issue by snori74** [gophish/gophish#498]
[from-exchange.txt](https://github.com/gophish/gophish/files/662637/from-exchange.txt)
Have had no problems with clicking the .URL links giving a "Clicked" result, but have yet to see a .Tracker link generate a "Viewed" result as it should.

Doing some testing today, it seems clear that chosing to "Display images" in the mail client loads the tracker URL - but gives a "clicked" result in gophish. This is effectivly a "false positive", so a very bad thing.

Clearly this is working for some, so it's not clear to me what could be going on.   See attached files for more detail. (Running 0.2alpha, just loaded from source, on Linux).

![in-the-gui](https://cloud.githubusercontent.com/assets/2436188/21334538/42d1e850-c6bd-11e6-9716-3ba1af8ac6f0.png)
![in-gmail](https://cloud.githubusercontent.com/assets/2436188/21334545/4ac8cc0e-c6bd-11e6-96a7-8cd3b5c46110.png)
[in-the-log.txt](https://github.com/gophish/gophish/files/662545/in-the-log.txt)

At the server we see:

`/var/log/gophish.log:111.222.111.31 - - [20/Dec/2016:13:29:51 +1300] "GET /login.html/track?rid=7e2eb410862be1815e0a67009c77d31f3a24de54382ce5f8642114db51176fe1 HTTP/1.1" 200 1145 "" "Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy)"`

...and the main link (i.e. the .URL one) does not appear - because it has not been clicked.

But, when  the recipent later _does_ click on that main link, we get *almost* the same URL showing in the log: 

`/var/log/gophish.log:111.222.111.222 - - [20/Dec/2016:14:13:54 +1300] "GET /login.html?rid=7e2eb410862be1815e0a67009c77d31f3a24de54382ce5f8642114db51176fe1 HTTP/1.1" 200 2121 "" "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)"`

..the difference being that the first has "/track" in it.

Edit: See also now the tracker-event.csv file - which doesn't seem to differentiate between a click on the tracker (in this case from Gmail) and a click of the .URL - yet the /var/log/gophish.log file _did_.

PS: A further example, from MS Outlook running on a TS, is in the attached "from-exchange.txt" file.

BTW: This seems to be a dup of RyanGandrud's #422 
[tracker-events.txt](https://github.com/gophish/gophish/files/662611/tracker-events.txt)

**Comment by snori74** [comment]
[from-exchange.txt](https://github.com/gophish/gophish/files/662640/from-exchange.txt)

**Comment by snori74** [comment]
Here's the logging of an Apple Mail  user opening the .Tracker at 13:07 (default behaviour) - but this being recorded as "Clicked Link"). And then - at 13:09 - _actually_ clicking the link:

```
11.22.22.11 - - [21/Dec/2016:12:40:57 +1300] "GET /smug/gallery/hsg-330544/track?rid=1c7731b21c310ccbc24ab296f79e626773f4a28bdad84b1934404816e1c18f0c HTTP/1.1" 200 1131 "" "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0; Microsoft Outlook 15.0.4763; ms-office; MSOffice 15)"

 2016/12/21 13:05:32 main.go:687: sql/home/snori74/Coding/golang/gopath/src/github.com/gophish/gophish/models/campaign.go:117995.4µsINSERT INTO "events" ("campaign_id","email","time","message","details") VALUES (?,?,?,?,?)[1390 target@example.com 2016-12-21 13:05:32.1071223 +1300 NZDT Clicked Link {"payload":{"rid":["1c7731b21c310ccbc24ab296f79e626773f4a28bdad84b1934404816e1c18f0c"]},"browser":{"address":"11.22.22.11","user-agent":"Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0; Microsoft Outlook 16.0.6965; ms-office; MSOffice 16)"}}]

11.22.22.11 - - [21/Dec/2016:13:05:31 +1300] "GET /smug/gallery/hsg-330544/track?rid=1c7731b21c310ccbc24ab296f79e626773f4a28bdad84b1934404816e1c18f0c HTTP/1.1" 200 1131 "" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0; Microsoft Outlook 16.0.6965; ms-office; MSOffice 16)"

 2016/12/21 13:07:27 main.go:687: sql/home/snori74/Coding/golang/gopath/src/github.com/gophish/gophish/models/campaign.go:117995.8µsINSERT INTO "events" ("campaign_id","email","time","message","details") VALUES (?,?,?,?,?)[1390 target@example.com 2016-12-21 13:07:27.7269196 +1300 NZDT Clicked Link {"payload":{"rid":["1c7731b21c310ccbc24ab296f79e626773f4a28bdad84b1934404816e1c18f0c"]},"browser":{"address":"11.22.22.11","user-agent":"Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0; Microsoft Outlook 16.0.6965; ms-office; MSOffice 16)"}}]

11.22.22.11 - - [21/Dec/2016:13:07:27 +1300] "GET /smug/gallery/hsg-330544/track?rid=1c7731b21c310ccbc24ab296f79e626773f4a28bdad84b1934404816e1c18f0c HTTP/1.1" 200 1131 "" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0; Microsoft Outlook 16.0.6965; ms-office; MSOffice 16)"

 2016/12/21 13:09:11 main.go:687: sql/home/snori74/Coding/golang/gopath/src/github.com/gophish/gophish/models/campaign.go:117856.1µsINSERT INTO "events" ("campaign_id","email","time","message","details") VALUES (?,?,?,?,?)[1390 target@example.com 2016-12-21 13:09:11.3376997 +1300 NZDT Clicked Link {"payload":{"rid":["1c7731b21c310ccbc24ab296f79e626773f4a28bdad84b1934404816e1c18f0c"]},"browser":{"address":"11.22.22.11","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393"}}]

11.22.22.11 - - [21/Dec/2016:13:09:07 +1300] "GET /smug/gallery/hsg-330544/?rid=1c7731b21c310ccbc24ab296f79e626773f4a28bdad84b1934404816e1c18f0c HTTP/1.1" 200 1131 "" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393"

 2016/12/21 13:10:07 main.go:687: sql/home/snori74/Coding/golang/gopath/src/github.com/gophish/gophish/models/campaign.go:1171.1218msINSERT INTO "events" ("campaign_id","email","time","message","details" VALUES (?,?,?,?,?)[1390 target@example.com 2016-12-21 13:10:07.1526585 +1300 NZDT Clicked Link {"payload":{"rid":["1c7731b21c310ccbc24ab296f79e626773f4a28bdad84b1934404816e1c18f0c"]},"browser":{"address":"11.22.22.11","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0; Microsoft Outlook 15.0.4763; ms-office; MSOffice 15)"}}]

11.22.22.11 - - [21/Dec/2016:13:10:06 +1300] "GET /smug/gallery/hsg-330544/track?rid=1c7731b21c310ccbc24ab296f79e626773f4a28bdad84b1934404816e1c18f0c HTTP/1.1" 200 1131 "" "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0; Microsoft Outlook 15.0.4763; ms-office; MSOffice 15)"
ccladmin@Nessus3:~/tmp$ 
```

**Comment by jordan-wright** [comment]
Sorry for the delay - I think the issue is the custom path you're using. The pattern match in controllers/route.go only looks for "/track" at the root of the URL.

I might be able to get this fixed, I'll just need to test some things out.

Thanks for reporting this!

**Comment by snori74** [comment]
SOLVED. Looks like the "URL" field defined for a Campaign needs to actually be a simple hostname. So, entering "http://smug.mybox.com" is OK, but "http://mybox/smug" or "http://mybox/smug/pix.png" will lead to the problem that I saw. 

Seems that this could be fixed by either (a) Re-naming that field to HOSTNAME, or (b) By changing the logic to trim off the extra path information in front of the "?rid=". 

If neither of those appeals, then there could be text/documentation warning, or validation, to prevent an actual url from being entered rather than a hostname

**Comment by jordan-wright** [comment]
This should be fixed now. If you wouldn't mind, give it a shot and let me know if you run into any issues!
