### ISSUE TITLE
False positives from AppleMail

### ISSUE THREAD

**Issue by snori74** [gophish/gophish#499]
Just a quick note to say that Apple's Mail product by default allows the user to hover over web links to get a "preview". Currently 'gophish' will count this as a "click" - i.e. another way to record a "false positive" and make people grumpy. 

If you log the output of 'gophish' you can eliminate these based on the fact that they don't also do a corresponding "GET /favicon.ico" - which all browsers do. Not sure if that should be built in to gophish, but if it's not, then it will be necessary to double-check the results based on the logs. Not fun.   

A preview:
```
22.111.22.11 - - [21/Dec/2016:09:59:54 +1300] "GET /some/galleries/72157664540330544/s?rid=bf3146dd90fe3d260c448a58df950690114304ad4275487dcbef27c7b4d91033 HTTP/1.1" 200 1131 "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12"
```
An actual click from the same machine:
```
22.111.22.11 - - [21/Dec/2016:10:10:51 +1300] "GET /some/galleries/72157664540330544/s?rid=bf3146dd90fe3d260c448a58df950690114304ad4275487dcbef27c7b4d91033 HTTP/1.1" 200 1131 "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12"
22.111.22.11 - - [21/Dec/2016:10:10:51 +1300] "GET /favicon.ico HTTP/1.1" 404 43 "http://example.com/some/galleries/72157664540330544/s?rid=bf3146dd90fe3d260c448a58df950690114304ad4275487dcbef27c7b4d91033" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12"
```

**Comment by S0larflare** [comment]
Only problem being is that if you don't have a favicon for the site, then that call will never be made. Admittedly most sites nowadays will have a favicon and if you're cloning a site that should get picked up, but if someone spins up something simple and neglects to put a favicon on the site, they will get false negatives.

**Comment by snori74** [comment]
Yes, in this case we were indeed using "something simple", which didn't include a _link rel="icon"_ in the head - so defaulted to looking for the _/favicon.ico_ - which gophish is not providing - and hence we can differentiate between an AppleMail-preview and a user-clicked-launching-a-full-browser. If we have a  _link rel="icon"_ in our HTML, I'm not sure we could. Needs more testing.

**Comment by jordan-wright** [comment]
I don't know how I feel about testing for the follow up favico request. It seems complicated and possibly error prone depending on the browser.

The less magic we implement, the better. I'll be thinking about this, but for now you might be better off filtering out the apple mail click events from the API.

Thanks again for sending in this report!

**Comment by snori74** [comment]
Yup, in my case I work from the API, so I will simply filter out all the "Mac OS X" events - then have to run something separate against this detailed log to find any _real_ click events.

**Comment by jordan-wright** [comment]
Sounds good. Until we can work out something more long term, I'm going to go ahead and close this out since we have a (non-ideal) workaround.

Thanks again for reporting this!
