### ISSUE TITLE
Autocomplete on Template Variables

### ISSUE THREAD

**Issue by jordan-wright** [gophish/gophish#50]
When filling out a template, we shouldn't assume the user knows all the template variables that are possible.

It would be user friendly to have an "autocomplete" feature that can show what variables are available.

**Comment by TheGroundZero** [comment]
I'm very much in favor of adding this to the tool.  
The User Guide only mentions the variables at the very end, in an Appendix. It'd be nice to have either an autocomplete function triggered by typing `{{.` or a list to the side, where you can click to enter the variable at your cursor

**Comment by jordan-wright** [comment]
This was added back in https://github.com/gophish/gophish/commit/b4ff771b3a9e486a13574fdc1007e479cd5cf405
