### ISSUE TITLE
Cannot send email with an attached file

### ISSUE THREAD

**Issue by Wiss13** [gophish/gophish#503]
When I tried to send an email with an attached file, the email was sent without it.
I tried to send the email with an HTML and text format but neither one of them worked.

**Comment by jordan-wright** [comment]
I'm afraid we'll need more details to troubleshoot this.

What version of gophish are you using?
What type of file is being attached?
What email provider are you sending to?
Are there any relevant logs in the terminal that might give hints as to what's happening?

If you could send this info, we should be able to figure out what's going on.

Thanks!

**Comment by jordan-wright** [comment]
Hey @Wiss13,

Just wanted to check in on this - are you still having this issue? If so, could you please update the issue with the items listed above?

**Comment by jordan-wright** [comment]
Going ahead and closing this since there haven't been any updates in over 2 weeks. 

@Wiss13, if you're still encountering issues, please let us know as well as updating the issue with the items listed above and we'll be more than happy to continue troubleshooting!
