### ISSUE TITLE
How to set a default page or build other pages to run on the gophish server

### ISSUE THREAD

**Issue by chrisfosterexternal** [gophish/gophish#506]
Where is webroot located for the gophish server? I want to set an index.html page that the user will land on after submitting credentials.

**Comment by jordan-wright** [comment]
Hey there!

You can host static HTML files by putting them under `static/endpoint` and referencing them at `x.x.x.x/static/filename.html`.

[Here's](https://github.com/gophish/gophish/issues/220) an issue with more background on this.

Hope this helps! Let me know if you run into any issues.
