### ISSUE TITLE
Host files and folders for landing page

### ISSUE THREAD

**Issue by mkannan22** [gophish/gophish#507]
Is there a way to host an entire web page where additional files are called from another folder? For example, there are JavaScript and CSS located in separate files that the main index page needs to access for the page to be displayed properly.

**Comment by m4dw0lf** [comment]
I think that /endpoint/static will help you.

Em 06/01/2017 17:28, "dukesecurity" <notifications@github.com> escreveu:

**Comment by mkannan22** [comment]
Excellent. Problem solved. Thanks!

**Comment by jordan-wright** [comment]
Just a heads up, I've gone ahead and added information about this in [the documentation](https://gophish.gitbooks.io/user-guide/content/documentation/landing_pages.html#static-assets).

Sorry about the confusion!
