### ISSUE TITLE
Capture Credentials Not Working

### ISSUE THREAD

**Issue by mkannan22** [gophish/gophish#510]
I am having issues capturing credentials. I went back to the basics and made a simple HTML form, but can't seem to capture any data. Is there a basic template to work off of to capture credentials? Here is an example of one Landing Page I am just trying to test to get captured credentials to work. Once that is successful I can build out from there. Both "Capture Submitted Data" and "Capture Passwords" are checked in the Landing Page. I have reviewed issue numbers 265, 294, 494, and many more. Also, have tried adding a hardcoded URL in the action field. Any suggestions?

> 

```
<html><head>/<head><body>
<form action="" method="get">
First Name:<br/>
<input name="fname" type="text"/><br/>
Password:<br/>
<input name="password" type="password"/><br/>
<input type="submit" value="Submit"/> 
</form>
</body>
</html>
```

>

**Comment by jordan-wright** [comment]
What version of Gophish are you using? One thing that's important to note is that the form "action" needs to be "POST". Trying that on my instance that's built from source seems to work just fine:

![image](https://cloud.githubusercontent.com/assets/1317288/21792994/4491a152-d6b3-11e6-85fb-503b3d70be15.png)

**Comment by mkannan22** [comment]
Wow. Overthought that one. Thank you yet again. Keep the features coming. Using this tool more and more!!

**Comment by Haydz** [comment]
Hi,

I have this issue following the tutorial Morning Catch.

The below image shows that Capture credentials is marked correctly:

![image](https://cloud.githubusercontent.com/assets/2356349/21811675/8f83709e-d71e-11e6-851a-249cdfcebe99.png)





The HTML code is below for the landing page.  **The method is post.**
![image](https://cloud.githubusercontent.com/assets/2356349/21811609/4ae29190-d71e-11e6-84eb-648285df7cc2.png)


`
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head>
	<base href="http://192.168.56.101/mail/"/>
	<title>Morning Catch Corporate Mail :: Welcome to Morning Catch Corporate Mail</title>
	<meta name="Robots" content="noindex,nofollow"/>
	<link href="./?_task=mail" rel="index"/>
	<link href="skins/default/images/favicon.ico" rel="shortcut icon"/>
	<link href="skins/default/common.css?s=1268078233" rel="stylesheet" type="text/css"/><meta http-equiv="content-type" content="text/html; charset=UTF-8"/><script type="text/javascript" src="program/js/jquery-1.3.min.js?s=1235083105"></script><script type="text/javascript" src="program/js/common.js?s=1256995296"></script><script type="text/javascript" src="program/js/app.js?s=1256995295"></script><script type="text/javascript">
/* <![CDATA[ */

var rcmail = new rcube_webmail();
rcmail.set_env({"task":"login","request_token":"de9c9d261fd074c50c3dc9734e171962","keep_alive":60,"action":"","comm_path":".\/?_task=mail"});
rcmail.add_label("loading","Loading...");
rcmail.add_label("servererror","Server Error!");
rcmail.gui_object('message', 'message');
rcmail.gui_object('loginform', 'form');
/* ]]> */
</script>
</head>
<body>
<p><img alt="Morning Catch Corporate Mail" border="0" src="skins/default/images/roundcube_logo.png" style="margin:0 11px"/></p>

<div id="message"> </div>

<div id="login-form">
<div class="boxtitle">Welcome to Morning Catch Corporate Mail</div>

<div class="boxcontent">
<form action="" method="post" name="form"><input type="hidden" value="http://192.168.56.101/mail/./"/> <input type="hidden" value="de9c9d261fd074c50c3dc9734e171962"/> <input type="hidden" value="login"/><input id="rcmlogintz" type="hidden" value="_default_"/><input id="rcmloginurl" type="hidden" value=""/>
<table border="0" summary="">
	<tbody>
		<tr>
			<td class="title"><label for="rcmloginuser">Username</label></td>
			<td><input autocomplete="off" id="rcmloginuser" type="text"/></td>
		</tr>
		<tr>
			<td class="title"><label for="rcmloginpwd">Password</label></td>
			<td><input autocomplete="off" id="rcmloginpwd" type="password"/></td>
		</tr>
	</tbody>
</table>

<p style="text-align:center;"><input class="button mainaction" type="submit" value="Login"/></p>
</form>
</div>
</div>
<script type="text/javascript">
/* <![CDATA[ */

$(document).ready(function(){ rcmail.init(); });
/* ]]> */
</script>

</body></html>
`


Below image shows that credentials are not being captured:
![image](https://cloud.githubusercontent.com/assets/2356349/21811726/bfe3d206-d71e-11e6-8cf4-bb7efeac26bb.png)

I have cloned the VMX to OVA, perhaps this has affected the cloning of the landing page?

**Comment by DerekChia** [comment]
I have the problem of not seeing the Submitted Data as well. Any idea what I need to do? The redirection works fine after submitting the data though.

**Comment by S0larflare** [comment]
I find that GoPhish seems to like the 'name' property to be defined in a form.
```
<form action="" method="post" name="form">
<label>Username:</label>
<input name="username" type="text"/>
<label>Password:</label>
<input name="password" type="password"/>
</form>
```

**Comment by liamosaur** [comment]
@S0larflare's tip fixed the issue for me. Thanks!
