### ISSUE TITLE
Email open track not work

### ISSUE THREAD

**Issue by eyadgh** [gophish/gophish#511]
Hi ,
i'm using the last version , when trying to track email it's not work .

**Comment by S0larflare** [comment]
Can you give a little more detail about the problem? This could be anything from an obscure bug to the user not being able to hit the page/reach the server.

**Comment by eyadgh** [comment]
@S0larflare 
my friend im able to receive notificaton if the victim click the link or enter the password . but i cant receive notification if he open the email . 

i tried many times to send send email with track image enabled .

**Comment by jordan-wright** [comment]
It might be the case that the email client is blocking tracking images. This is common and I'm afraid there is nothing gophish can do about it.

**Comment by eyadgh** [comment]
but i worked on another phishing service & it was working fine .
