### ISSUE TITLE
Help with Sending Templates

### ISSUE THREAD

**Issue by xaime23** [gophish/gophish#515]
What is this error?
Config:
Host: localhost
From: google@localhost
Rest in white
Thacks!

<img width="960" alt="sin titulo" src="https://cloud.githubusercontent.com/assets/25134195/21963085/2540082c-db34-11e6-807d-ef417c908389.png">

**Comment by jordan-wright** [comment]
That error says that gophish was unable to connect to the host you have specified. You'll need to make sure you have an SMTP server listening on port 25 for gophish to connect to.

**Comment by jordan-wright** [comment]
Closing this out since there haven't been any updates in 2 weeks. @xaime23, if you're still having issues, let us know and we can continue investigating.

Thanks!
