### ISSUE TITLE
Shorter RIDs

### ISSUE THREAD

**Issue by Vanhecke** [gophish/gophish#518]
Hey all,

I would like to see gophish use smaller rids.
The URLs right now are quite long for anything that isn't email-based phishing (sms, voice, chat).

I haven't looked at the code yet but if others here find it to be a good idea I'll try to make a pull request.

Cheers

**Comment by jordan-wright** [comment]
I'd be fine with this. What kind of RID's are you thinking?

**Comment by Vanhecke** [comment]
I think numeric values [0-9] make the most sense.  
A number like "12963" can be passed as a one-time password,  support ticket, pincode, personnel number, application number, etc.
It's also much easier to communicate a number over voice comms.

It would be good if the "starting" point was something like 1337.
To avoid sending something like "1", "2", ..., "1234", etc

**Comment by S0larflare** [comment]
What about a 5 digit alphanumeric RID? That would allow for 36^5 (just over 60 million) unique RIDs and would still be easy to communicate  "B32YG" for example.

**Comment by Vanhecke** [comment]
>  not ennumerable
That's a good point.
[A-Z0-9] Would do the trick.

**Comment by jordan-wright** [comment]
@S0larflare is absolutely right. The rid parameter is basically a generated password that authenticates the target. This means that anyone with that parameter can falsify results.

I'll do some experimenting and may switch it to 5 or 6 characters. Some people run big campaigns, so if adding one more letter gives us some room, then it should be fine.

Good suggestions everyone! Thanks for the feedback.

**Comment by jordan-wright** [comment]
This should be fixed now. I opted to go 7 random alphanumeric characters in `a-zA-Z0-9`

Hope that helps!

**Comment by RogerBergling** [comment]
Hi Jordan, great work. Is there a way to change the rid to only a-z0-9. Uppercase get lowercase by our spam filer. Is the a setting to change the rid parameters to only get lowercase?

**Comment by jordan-wright** [comment]
Hi there!

You’ll need to modify this line and recompile: https://github.com/gophish/gophish/blob/1aab1a34ba84d5f0ae95b2d2020d0a3eec96fd12/models/result.go#L177

**Comment by RogerBergling** [comment]
Work perfectly! Thanx! Have a great day!

**Comment by Genesiss2** [comment]
@RogerBergling or Smbdy - Help please!

How do you make changes that take effect in an already installed gophish? After modifying these sources, they don't take effect on an already installed gophish. Please advise on how you make changes to be applied to an already installed gophish.

**Comment by RogerBergling** [comment]
Sorry to to say, I do not know! Sorry
