### ISSUE TITLE
Sending Profile via MS Exchange

### ISSUE THREAD

**Issue by Y0shiT0shi** [gophish/gophish#519]
Hi everyone! Sorry for my english.

I'm trying to configure gophish sending profile via exchange server inside our organization. But when I send test email I get error "535 5.7.3 Authentication unsuccessful". So I don't what to do. Can you help me?

**Comment by S0larflare** [comment]
Have you ticked the box to ignore certificate errors? If not, could you show how you have set it up?

**Comment by Y0shiT0shi** [comment]
Yes, I checked the box to ignore certificate errors.

**Comment by jordan-wright** [comment]
It sounds like the username and password you're using may be incorrect. Can you send us a screenshot of your setup? You can redact things as needed.

Also, do you see any logs on the Exchange server that may indicate the issue?

**Comment by Y0shiT0shi** [comment]
![goph](https://cloud.githubusercontent.com/assets/25222439/22105372/7418dcd8-de65-11e6-9cae-2615e39ce624.png)
![test_email](https://cloud.githubusercontent.com/assets/25222439/22105384/840dcd74-de65-11e6-974c-21212a95c136.png)

Unfortunately, our IT-department don't know which logs needed to be viewed.

username and password must be correct. I've checked them many times.

**Comment by S0larflare** [comment]
So is username@kubank.ru how you actually log in to exchange? Most places this is shortened to just the username part, so that could be causing the issue. I suppose there could be an issue with the host not being given as an FQDN, but if that was the problem I would have expected and error to say the host can't be found rather than an authentication error, so that's probably not it.

**Comment by jordan-wright** [comment]
@Y0shiT0shi have you made any progress on this? Is there anything we can do to help?

**Comment by Y0shiT0shi** [comment]
I've tried to use username instead of username@kubank.ru and host name in FQDN format. But result is unsuccessful.

I think problem is that exchange is using AD-authentication, so in fact there are no username/password to authenticate on exchange-server. But maybe I just do not understandt how it works.

But our IT-department doesn't now how to change authentication type.

**Comment by S0larflare** [comment]
I don't think the :25 is necessary, it should default to that, but I wouldn't have thought it would hurt. Have you tried doing this with the username and password blank?

**Comment by Y0shiT0shi** [comment]
> I don't think the :25 is necessary, it should default to that, but I wouldn't have thought it would hurt. Have you tried doing this with the username and password blank?

Yeah, with blank username and password it works! Thank's a lot!

Can you explain how is that? I don't understand how this exchange works and how it's possible to authenticate and send email without entering username and password.

**Comment by S0larflare** [comment]
Well most SMTP servers don't require authentication from the inside. SMTP is an old protocol and believes what you tell it, The username and password is more for services like gmail and things which you would need to log in using your account to use beforehand.

**Comment by jordan-wright** [comment]
Glad you got this figured out, @Y0shiT0shi! I'll go ahead and close this out.
