### ISSUE TITLE
When having a group in gophish and one email is invalid

### ISSUE THREAD

**Issue by mcb-phish** [gophish/gophish#520]
When having a group in gophish and one email is invalid  it creates an error 

gomail: could not send email 1: 550 unknown user ... 

and then the rest of the group is skipped ( as error )

is there any way to have it continue sending to the rest of the group and only error for the invalid email 

addresses ???

This is my first post / question and not sure if its alright in here ? I didn't get any responses yet ? :)

Thank you !

**Comment by jordan-wright** [comment]
Sorry for the delay in getting back to you. I will work to handle errors better in the sending process. I agree that smtp errors shouldn't stop the whole campaign, and I want to make sure we properly handle deferred emails by exponential backoffs

**Comment by mcb-phish** [comment]
Thank you very much. This would be greatly useful as we have several groups of users and at times some user have been "expired" and their email address becoming unreachable  and causes a "stop" in the groups campaign.   

Best Regards

**Comment by jordan-wright** [comment]
Out of curiosity, what version of Gophish are you using? Are you building from source or using a pre-built binary?

The reason I ask is that emails are sent in this function: https://github.com/gophish/gophish/blob/master/worker/worker.go#L182

If there is an error when the sending happens, it looks like we're just logging it, adding the error status, and moving on.

Is there any additional logs from the terminal you could provide to help track down the issue?

**Comment by jordan-wright** [comment]
Just curious - does this appear to have the same symptoms as https://github.com/gophish/gophish/issues/417? Just thinking out loud, I wonder if we need to reset the connection after an error occurs.

**Comment by S0larflare** [comment]
Jordan, is this something best addressed in gomail rather than gophish? When I was getting timeouts for the smtp connection I had to fudge it to simply start a new connection before that became a problem. Is there a way to add in a few more error cases for things like invalid emails and connection timeouts so that they can be (hopefully seemlessly) dealt with?

**Comment by mcb-phish** [comment]
Oooops i had "closed" this issue by mistake   (newbie)

this is what i have installed 


![screenshot from 2017-01-31 08-43-22](https://cloud.githubusercontent.com/assets/25224309/22465439/18e43ef8-e792-11e6-8f68-8a8a9405bc67.png)

**Comment by mcb-phish** [comment]
looking into things I must of got only a binary package  ...  I'll try to go from source and build and see how that goes ???  therefore the binary 64 bit must not be up to date ???

**Comment by mcb-phish** [comment]
I downloaded source , recompiled  ( with go ) copied the old .db and ran .

Now it continues after it finds an invalid email address ...    I assume then that the 64 bit binary is not up to date ... source is and it works for me now ... Thanks so much for your help 

Greatly appreciated !!!

Am I supposed to be the one closing this issue ?? :)

**Comment by mcb-phish** [comment]
Thanks for all your help. Great job!

Sent from my BlackBerry 10 smartphone on the Bell network.
From: Jordan Wright
Sent: Thursday, February 2, 2017 7:15 PM
To: gophish/gophish
Reply To: gophish/gophish
Cc: Bergeron, Michel (DPS/MSP); State change
Subject: Re: [gophish/gophish] When having a group in gophish and one email is invalid (#520)



Closed #520<https://github.com/gophish/gophish/issues/520>.
