### ISSUE TITLE
Error Sending email - "422 try again in XX seconds"

### ISSUE THREAD

**Issue by aieeeeeeeee** [gophish/gophish#521]
Hello guys, 

I'm trying to send an email to 152 persons and after 25 emails I receive for the 127 left the following error:

>  Error Sending Email - 422 try again in 15 seconds.

Do you guys have any clue? 

Thanks!

**Comment by S0larflare** [comment]
Off the top of my head I would assume this is a message from your SMTP server rate-limiting you to 25 emails in a specific time frame in order to prevent mail flooding. Is this an internal copany mail server or are you using an external service like gmail?

**Comment by aieeeeeeeee** [comment]
Indeed it was the problem so I had to groups of 25. Thanks!
