### ISSUE TITLE
Gopish webroot to craft a redirect after landing page

### ISSUE THREAD

**Issue by mantis-le-sin** [gophish/gophish#522]
Hi guys,
I've been googling without luck.
Can you please tell me the webroot for the Gophish web server? I need to redirect from the landing page to a page on my gophish server but I don't know where to place this page :)

thanks
mls

**Comment by S0larflare** [comment]
Put the page you want to redirect to in ./static/endpoint directory, then reference it using http://servername/static/filename

**Comment by mantis-le-sin** [comment]
thank you @S0larflare! Any idea how can I create a folder and than put the html page?
ex: server/newdir/index.html

**Comment by S0larflare** [comment]
You can create a folder in /static/endpoint, put the file in there and then reference that.

e.g.

<gophish>/static/endpoint/newdir/index.html

http://<gophish server>/static/newdir/index.html

**Comment by jordan-wright** [comment]
Closing this since @S0larflare did a great job of answering the question.

Thanks @S0larflare!
