### ISSUE TITLE
Phishing Campaign Guide

### ISSUE THREAD

**Issue by LarryGrim** [gophish/gophish#525]
Not necessarily an issue, but I have created a guide on conducting a phishing campaign with Gophish.   The guide is available at  http://tinyurl.com/PhishCampaign 
Major Chapters:

**Overview**
**Building the Tools** 

- -Workstation
- -AWS Virtual Ubuntu Server
- -Gophish install

**Test Gophish Campaign**
**Education**

- -Preliminaries
- -During/after Campaign

**Sample Authorization Form
Endnotes/References**

Hope it helps someone.
-Larry
-

**Comment by S0larflare** [comment]
I've only had a quick flick through with my phone, but this is pretty good. Helps with sone common pitfalls and explains the why as much as the how. I do think going as far as talking about easter eggs in notepad++ is going on a bit of a tangent though.

**Comment by LarryGrim** [comment]
Yes, I agree that Easter Eggs for Notepad++ was a little of the beaten
path.  However, writing it was such a pain that I had to inject a little
humor into an otherwise numbing 120+ pages.
Thanks for the quick feedback.

**Comment by jordan-wright** [comment]
Thank you for this, @LarryGrim! I hope you don't mind, I've added a reference to your doc in the official user guide: https://gophish.gitbooks.io/user-guide/content/additional-references.html

This is fantastic, and I really, really appreciate you sending this our way. 😄 

I'll leave this issue up for another week or so for any people passing by to see.
