### ISSUE TITLE
custom Smtp service not working?

### ISSUE THREAD

**Issue by vinnt2** [gophish/gophish#526]
Hey

ok so when i use my own smtp server on it , in some time it gives certificate error , or usually just have no response when sending.

Anyway to fix this issue? or i have to create some certificate for it?

-------------------------------------------------------------------------
this one is by far best open-source email toolkit out there.

**Comment by vinnt2** [comment]
I'm using it from own localhost. But i guess it really doesn't matter for these kind of issues.

**Comment by jordan-wright** [comment]
What SMTP server are you using? If you're getting certificate errors, you can ignore them in the Sending Profile dialog:

![image](https://cloud.githubusercontent.com/assets/1317288/22451848/8ce57c78-e737-11e6-99e8-a0b5321f8d4f.png)

Also, what errors do you see in the terminal when you attempt to send the emails?

**Comment by vinnt2** [comment]
oh seems you updated it? im using free smtps from tearcloud.com

by the way thanks for support and this one is indeed great app there.

**Comment by jordan-wright** [comment]
Yes, I recommend either using the latest binaries (version 0.2) or building from source.

Let me know if that fixes the issue you're encountering!

**Comment by vinnt2** [comment]
Thanks For you're Support , Indeed this one is working perfect.

All resolved by that 'Ignore Certifacate Errors'
