### ISSUE TITLE
Tracking Image/Url not working.

### ISSUE THREAD

**Issue by derpynirvash** [gophish/gophish#528]
I am having an issue where the tracking image in the email messages is not working. The url is being injected into the email body, which I have verified by looking at the email source. 

 `<img style=3D'display: none' src=3D'http://10.1.10.52/track?rid=3D6860f0a83
60991276c72e87d92dfb3e356fa92d508a1605065504de3be1506cc'/>`

I have also tried pasting the url into a normal browser and it comes back with a 404
http://10.1.10.52/track?rid=3D6860f0a8360991276c72e87d92dfb3e356fa92d508a1605065504de3be1506cc

This is the messaage that appears in the console when I try to access the above url
`10.1.4.37 - - [01/Feb/2017:08:10:50 -0800] "GET /track?rid=3D6860f0a8360991276c7
2e87d92dfb3e356fa92d508a1605065504de3be1506cc HTTP/1.1" 404 43 "" "Mozilla/5.0 (
Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2
883.87 Safari/537.36"`

The landing page for the campaign works as expected and will returns the Link clicked/info submitted statues. 

Is there anything I could be doing wrong?

I am using the latest binary version for Windows x64 (v0.2) I attempted to try building from source, but I am having issues with getting gcc to behave on Windows.

**Comment by S0larflare** [comment]
Is 10.1.10.52 your gophish server?

If you create an email with {{.Tracker}} and also {{.URL}}, are you able to reach the link generated?

**Comment by derpynirvash** [comment]
10.1.10.52 is the gophish server, 10.1.4.37 was the desktop I was testing with. 

I created a test email with just that, which shows this in the email source 
`<img style=3D'display: none' src=3D'http://10.1.10.52/track?rid=3D631d46fc5
f33810ef09efc6ad471064c5fc287ec8541f9c8fef8f5581c355cb2'/> and also http://
10.1.10.52?rid=3D631d46fc5f33810ef09efc6ad471064c5fc287ec8541f9c8fef8f5581c
355cb2`

This is the log from the server
` 2017/02/02 06:22:26 campaign.go:235: Found 1 Campaigns to run
 2017/02/02 06:22:26 worker.go:53: Worker received: Copy of testemail
 2017/02/02 06:22:26 worker.go:141: Creating email using template
 2017/02/02 06:22:26 worker.go:181: Sending Email to email@email.email
 2017/02/02 06:22:27 main.go:724: sql/go/src/github.com/gophish/gophish/models/campaign.go:117985.9µsINSERT INTO "events" ("campaign_id","email","time","message","details") VALUES (?,?,?,?,?)[11 email@email.email 2017-02-02 06:22:27.3084533 -0800 PST Email Sent ]
 
 2017/02/02 06:23:11 main.go:724: sql/go/src/github.com/gophish/gophish/models/campaign.go:117986.6µsINSERT INTO "events" ("campaign_id","email","time","message","details") VALUES (?,?,?,?,?)[11 email@email.email 2017-02-02 06:23:11.8290049 -0800 PST Clicked Link {"payload":{"rid":["631d46fc5f33810ef09efc6ad471064c5fc287ec8541f9c8fef8f5581c355cb2"]},"browser":{"address":"10.1.4.37","user-agent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"}}]

 10.1.4.37 - - [02/Feb/2017:06:23:11 -0800] "GET /?rid=631d46fc5f33810ef09efc6ad471064c5fc287ec8541f9c8fef8f5581c355cb2 HTTP/1.1" 200 6020 "" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
 2017/02/02 06:23:23 route.go:98: No Results found
 
#Trying to view tracking url in chrome
10.1.4.37 - - [02/Feb/2017:06:23:23 -0800] "GET /track?rid=3D631d46fc5f33810ef09efc6ad471064c5fc287ec8541f9c8fef8f5581c355cb2 HTTP/1.1" 404 43 "" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"

`

After opening the email, clicking the link and then trying to directly open the tracker (which still 404s) the phishing results show as,
Campaign Created February 2nd 2017 6:21 am
Email Sent February 2nd 2017 6:22 am
Clicked Link February 2nd 2017 6:23 am

**Comment by S0larflare** [comment]
Hmm, strange. How have you got it set up in your config.json file?

**Comment by derpynirvash** [comment]
config.json is default, didn't see the need to change anything in there. 

{
	"admin_server" : {
		"listen_url" : "127.0.0.1:3333",
		"use_tls" : false,
		"cert_path" : "example.crt",
		"key_path" : "example.key"
	},
	"phish_server" : {
		"listen_url" : "0.0.0.0:80",
		"use_tls" : false,
		"cert_path" : "example.crt",
		"key_path": "example.key"
	},
	"smtp" : {
		"host" : "smtp.example.com:25",
		"user" : "username",
		"pass" : "password"
	},
	"db_path" : "gophish.db",
	"migrations_path" : "db/migrations/"
}

**Comment by S0larflare** [comment]
Hmm, honestly I'm not sure. It's a shame you can't use the most recent source but the latest binary shouldn't have any issues regardless. Is port 80 definitely visible? Is there anything on the machine blocking the port or possibly using the port as well which might interfere - a separate webserver or somehting for example?

**Comment by derpynirvash** [comment]
So I was able to get build from source working, so I started fresh with the new source build, added my smtp settings, and the simplest possible email and landing pages. 

Here is the source from the email,
 <img alt=3D'' style=3D'display: none' src=3D'http://10.1.10.52/track?rid
=3DrEVFuq7'/> and also http://10.1.10.52?rid=3DrEVFuq7

And here is the output from gophish's console,

 2017/02/02 08:30:22 campaign.go:335: Found 1 Campaigns to run
 2017/02/02 08:30:22 worker.go:53: Worker received: test
 2017/02/02 08:30:23 worker.go:141: Creating email using template
 2017/02/02 08:30:23 worker.go:181: Sending Email to email@email.email
 2017/02/02 08:30:23 main.go:724: sqlC:/users/Administrator/Downloads/gowork/src
/github.com/gophish/gophish/models/campaign.go:1441.0052msINSERT INTO "events" (
"campaign_id","email","time","message","details") VALUES (?,?,?,?,?)[1 email@email.email
 2017-02-02 08:30:23.9937617 -0800 PST Email Sent ]
 
 2017/02/02 08:30:52 main.go:724: sqlC:/users/Administrator/Downloads/gowork/src
/github.com/gophish/gophish/models/campaign.go:144940µsINSERT INTO "events" ("ca
mpaign_id","email","time","message","details") VALUES (?,?,?,?,?)[1 email@email.email

 2017-02-02 08:30:52.3404549 -0800 PST Clicked Link {"payload":{"rid":["rEVFu
q7"]},"browser":{"address":"10.1.4.37","user-agent":"Mozilla/5.0 (Windows NT 6.1
; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/
537.36"}}]

10.1.4.37 - - [02/Feb/2017:08:30:52 -0800] "GET /?rid=rEVFuq7 HTTP/1.1" 200 56 "
" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Geck
o) Chrome/55.0.2883.87 Safari/537.36"

 2017/02/02 08:31:17 route.go:103: No Results found
 
10.1.4.37 - - [02/Feb/2017:08:31:17 -0800] "GET /track?rid=3DrEVFuq7 HTTP/1.1" 4
04 43 "" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, li
ke Gecko) Chrome/55.0.2883.87 Safari/537.36"
 2017/02/02 08:31:22 campaign.go:335: Found 0 Campaigns to run


You can see the link clicked being tracked and the landing page "http://10.1.10.52/?rid=rEVFuq7" loaded, however when I tried to go to "http://10.1.10.52/track?rid=3DrEVFuq7" in my browser, it 404'd again. 

It is probably worth to note the line " 2017/02/02 08:31:17 route.go:103: No Results found" which after looking at the source, that block of code is what handles the email tracking.

**Comment by derpynirvash** [comment]
Aaaand I see (part of) the issue,

If you look above I was getting this source for the email,

<img alt=3D'' style=3D'display: none' src=3D'http://10.1.10.52/track?rid
=3DrEVFuq7'/> and also http://10.1.10.52?rid=3DrEVFuq7

And the landing page link was http://10.1.10.52/?rid=rEVFuq7 and I was trying to use the tracker at, http://10.1.10.52/track?rid=3DrEVFuq7

The source html has a 3D in front of the rid, this wasn't there when clicking the link obviously, but is there when I copied the tracking url. Darn quoted-printable in the email formatting.

So the tracker is working properly. Just human error there.

Now to figure out why the email client isn't loading the tracking image!

**Comment by derpynirvash** [comment]
And everything is working fine now, sorry for wasting your time.

For anyone else reading, if you are using Google Apps your URL needs to be publicly reachable for tracker to work. Since for images in Gmail emails, google will show a cached copy from their servers, instead of pulling from the address directly. Which makes sense in hind sight.

**Comment by jordan-wright** [comment]
Thanks for the thorough analysis everyone! These kinds of things seem like potential wastes of time when the solution is found, but remember that there is always someone else with the same issue. Time was saved here.

Thank you for your diligence in tracking this down!
