### ISSUE TITLE
Users and Groups segregation issues

### ISSUE THREAD

**Issue by IAMPi** [gophish/gophish#531]
I've noticed there are issues with details from one user group leaks into another user group.  As an example:

Import user group one with a user list fully populated with details ( First name, last name, email, title)

Import a second user group with just email addresses.  This group two contains some of the same users from group one.   When I go to view the group two it now has details such as title.

**Comment by jordan-wright** [comment]
Interesting - thanks for the report! My guess is that the modal and datatable isn't getting properly cleared between modal sessions. I'll take a closer look later this week.

**Comment by jordan-wright** [comment]
Oh, I think I know what's causing this. I'll double check to confirm, but I believe this is the result of us keying off user email addresses when modifying groups. 

It is the assumption that emails are unique to users, and that there won't be the case of John and Joe both having the same email address.

Does this sound similar to what you're encountering? If so, is this behavior ok, or do you have a use case that would necessitate different behavior?

**Comment by IAMPi** [comment]
It makes sense.  My concern was whether this was expected or a bug. I was worried about  the integrity of the user lists and that users from one customer  list would leak into another customers list.

**Comment by jordan-wright** [comment]
Yep! This is expected. I can see both sides, but I think normally an email matches a single person, and it can be helpful to "auto fill" in details based on an email.

With that being the case, I'll go ahead and leave this behavior as is for now. Let me know if you run into any issues!
