### ISSUE TITLE
email sending delay

### ISSUE THREAD

**Issue by eyadgh** [gophish/gophish#533]
Hi ,
we i'm try to send email it takes 3 hours to receive , it was working fine before .

![image](https://cloud.githubusercontent.com/assets/24644790/22774990/b51a425c-eeba-11e6-9277-21f0cf354c2d.png)

**Comment by S0larflare** [comment]
I would suspect you have probably scheduled the campaign in the future (possibly mistakenly) and Gophish is waiting until then to send it. 

Something I think that should be added is an extra tab (next to the Overview tab in your screenshot) called something like 'Campaign Details' which shows pretty much what you put in when you created the campaign. As it is it's difficult to figure out some parts of the campaign after you've launched it.

**Comment by eyadgh** [comment]
sorry it was my mistake.  thanks.
