### ISSUE TITLE
Cant send multiple emails to the same address from different campaigns

### ISSUE THREAD

**Issue by adnanmig** [gophish/gophish#536]
Hi Guys,

I just started testing this project. I noticed that once I have created a campaign and sent an email (only my email is in the campaign), I cant send more emails when create other campaigns. It is like once the email is sent to me, my email is never able to receive any other emails. Could this be a bug?

**Comment by jordan-wright** [comment]
Huh- that's not supposed to happen..

Can you send the output from the terminal when the emails are sent? I'd be curious to know if there are any smtp errors or if it's the application throwing errors.

**Comment by adnanmig** [comment]
Hi,

So I created a copy of a campaign and ran it:
![screen shot 2017-02-12 at 13 39 02](https://cloud.githubusercontent.com/assets/25726443/22864973/e139da58-f128-11e6-9953-a0f68d6d9502.png)

**Comment by adnanmig** [comment]
Sorry, the previous one was a failure, check this output, email not received:
![screen shot 2017-02-12 at 13 44 43](https://cloud.githubusercontent.com/assets/25726443/22865020/9c3d7986-f129-11e6-943e-2618b60f5652.png)

**Comment by jordan-wright** [comment]
It's not in your spam folder is it? It looks like a successful smtp response code was received.

Also what smtp server are you hitting? Maybe it got held up there?

**Comment by adnanmig** [comment]
It is not in my spam, I am using my own smtp (hosted) server. first email was received in my inbox from the same server. This issue happened last week as well.

**Comment by jordan-wright** [comment]
What logs do you see in your smtp server? Seeing "Email Sent" in the gophish logs indicates that the smtp server sent a successful status code back implying that the email was successfully sent.

**Comment by adnanmig** [comment]
I dont have access to smtp server logs, email service is part of hosting. If this is not happening to anyone else, I guess it could be my email server.

**Comment by jordan-wright** [comment]
I haven't heard of it happening to anyone else, but I'm always willing to help troubleshoot anyway we can.

It seems like the next step would be to try a different smtp server (preferably one that exposes the smtp logs) to see if the problem persists.

Sorry for all the hassle!

**Comment by adnanmig** [comment]
That seems to be a logical next step, just remembered that my google account didnt work, I will try it again and let you know.

**Comment by jordan-wright** [comment]
👍 Sounds good! Let me know what you find out! Thanks for the quick responses when troubleshooting - much appreciated!

**Comment by jordan-wright** [comment]
Hey @adnanmig!

It's been about a week with no update, so I'm going to go ahead and close this one out for now. If you continue to run into issues using a different SMTP server, let me know and we'll continue tracking this down together.
