### ISSUE TITLE
How to add a new menu/page/url ?

### ISSUE THREAD

**Issue by shoki92** [gophish/gophish#542]

**Comment by S0larflare** [comment]
Can you be a bit more specific, not sure what you're after here?

**Comment by shoki92** [comment]
i want to create a new url/page
Eg : localhost:3333/gophish/mypage

i create a new html page(mypage) and route it... pls explain step by step. i am begineer

**Comment by S0larflare** [comment]
If what you are after is a _static_ page (e.g. a landing/education page) then put this in the "/static/endpoint/" folder of your installation, you'll then be able access this by going to "http(s)://www.phishingserver.co/static/staticpage.htm"


If you mean how do you make a new campaign, I'd suggest reading the documentation, it's all explained in there:
https://gophish.gitbooks.io/user-guide/content/

**Comment by jordan-wright** [comment]
As S0larflare has mentioned, you need to be more specific for us to be able to help you.

What page are you trying to make?
What do you want on that page?
What have you tried so far?
Are you building from source or using the pre built binaries?

**Comment by jordan-wright** [comment]
@shoki92 I haven't heard from you and there isn't much detail on this issue, so I'm going to close it out for now.

If you can let us know the answers to my questions in the previous comment, I would be happy to re-open and help you troubleshoot.

**Comment by CM19** [comment]
@S0larflare @jordan-wright Hey guys jumping in here as having a similar issue. Having trouble getting the pages to link; have made nano file and copied the static html code into it, saved it in gophish/static/endpoint/.  it is named static.html.
Cannot seem to find a link to redirect my landing page to that works; have tried EVERYTHING I can think of;
https://www.servername.blah/static/static.hml
www.servername.blah/static/static.html
x.x.x.x/static/static.html
https://x.x.x.x/static/static.html
And so on

What am I missing? Really desperate as the client was expecting me to have launched the campaign this morning and I still can't get the pages to link T.T

Please please and Thank you thank you

**Comment by HarisBinZahid** [comment]
I want to create a new page in navbar/menu for approval like if any campaign is created so it will not launched immediately it will show on new page as pending for approval and after approval it will be launched. I have tried to create a route and controller but its not loading showing 404 page not found
Its a dynamic page not a static and i am using 0.8.0 version.

![image](https://user-images.githubusercontent.com/32629571/66561458-f2928b00-eb72-11e9-9706-7a0bb3761549.png)

![image](https://user-images.githubusercontent.com/32629571/66561360-c414b000-eb72-11e9-8436-e1bdcefcba9c.png)
