### ISSUE TITLE
where to see error logs ?

### ISSUE THREAD

**Issue by shoki92** [gophish/gophish#543]

**Comment by S0larflare** [comment]
Currently it is all sent to the console. You can send this to a log file yourself if you wish but there currently isn't a bespoke error or output log.

**Comment by shoki92** [comment]
i could not see any error logs in my browser. where to see pls explain step by step because i am begineer

**Comment by S0larflare** [comment]
It would be getting output to a command window, i.e. cmd for windows or the console for *nix.

**Comment by snori74** [comment]
Of course, it makes sense to have 'gophish' running all the time, i.e. as a service. On a 14.04 Ubuntu box you might do this by installing the files into _/opt/gophish_, then starting it via a script _/etc/init/gophish_ that collects the output into a log file in the usual place:
```
description "The 'gophish' server"
author      "snori74"

start on filesystem or runlevel [2345]
stop on shutdown

script

    export HOME="/opt/gophish"
    echo $$ > /var/run/gophish.pid
    cd /opt/gophish
    exec /opt/gophish/gophish >> /var/log/gophish.log

end script

pre-start script
    echo "[`date`] Gophish server starting" >> /var/log/gophish.log
end script

pre-stop script
    rm /var/run/gophish.pid
    echo "[`date`] Gophish server going down..." >> /var/log/gophish.log
end script
```

**Comment by jordan-wright** [comment]
Great answers by both @S0larflare and @snori74.

I'm considering this one resolved. @shoki92, let us know if you continue to run into issues.

**Comment by TheManiac3** [comment]
> Currently it is all sent to the console. You can send this to a log file yourself if you wish but there currently isn't a bespoke error or output log.

Hey @S0larflare can you guide me how can i send web server to a file with accordance to date.
