### ISSUE TITLE
localhost:3333 doesn't open

### ISSUE THREAD

**Issue by AliYassine** [gophish/gophish#545]
Dear,
I am new on github and new on Linux, I downloaded goPhish since I need a tool to deploy a phishing attack on my department in college with the approval of our professors because we're planning to do some statistics about how many will visit the link, and how many will provide us with their emails, no password shall be taken. However, after I downloaded gohish when I go to localhost:3333 all it opens is this
![screenshot from 2017-02-21 07-51-06](https://cloud.githubusercontent.com/assets/25919306/23152428/add36f4c-f80a-11e6-90fd-06e153ff2294.png)

I don't know what to do, if I can get some help that would be amazing!
I am fairly new to this and I would very much like to succeed in it since it will be a good step in my academical life.
Thank you.

PS: if I go to localhost all I get is 404 page not found even though i already stopped apache2

**Comment by S0larflare** [comment]
Have you tried http**s**://localhost:3333?

**Comment by AliYassine** [comment]
yes I did, same results...

**Comment by AliYassine** [comment]
problem is fixed, turns out I have to go to 0.0.0.0:3333/login
however i do not understand why

**Comment by S0larflare** [comment]
Does 127.0.0.1:3333/login work?

**Comment by AliYassine** [comment]
no, but it worked when I went to 0.0.0.0:3333/login
