### ISSUE TITLE
Mysql Config Issue

### ISSUE THREAD

**Issue by benlavender** [gophish/gophish#547]
Hello, 

Attempting to run gophish using a remote MySQL service on the same subnet. However once ./gophish is called I receive the below:

 2017/02/24 20:42:23 models.go:84: no valid version found
no valid version found
 2017/02/24 20:42:23 gophish.go:76: Starting phishing server at http://
 2017/02/24 20:42:23 worker.go:36: Background Worker Started Successfully - Waiting for Campaigns
 2017/02/24 20:42:23 gophish.go:63: Starting admin server at http://
 2017/02/24 20:42:23 gophish.go:64: listen tcp :80: bind: address already in use

Here is my config.json contents;

{
        "admin_server" : {
                "listen_url" : "192.168.1.76:3333",
                "use_tls" : false,
                "cert_path" : "example.crt",
                "key_path" : "example.key"
        },
        "phish_server" : {
                "listen_url" : "192.168.1.76:80",
                "use_tls" : false,
                "cert_path" : "example.crt",
                "key_path": "example.key"
        },
        "smtp" : {
                "host" : "smtp.example.com:25",
                "user" : "username",
                "pass" : "password"
        },
        "migrations_path" : "db/migrations/"
        "db_name" : "mysql",
        "db_path" : "gpuser:Password@1@(192.168.1.75:3306)/gophish?charset=utf8&parseTime=True&loc=Local",
}

The issue is the Mysql config I’m adding, as per the user-guide.pdf this line should be correct.

**Comment by suffestuffie** [comment]
Are you sure it's correct? Cause i don't think that that @1 should be there.

**Comment by suffestuffie** [comment]
And secondly i think you already have a server running on port 80.

**Comment by benlavender** [comment]
Hi @suffestuffie, this only appears when the two MySQL lines are entered, the the password was “Password@1” then followed by the second @. I’ve attempted to use passwords without that symbol too with no affect. Also the port 80 notice only appears with this issue and loads fine when using a .sql file instead.

**Comment by jordan-wright** [comment]
Hey there!

Sorry for the delay. So, one of two things is likely happening:

- you might be using an older version of gophish that doesn't have mysql support (what folders do you have in your db/ folder)

- you are missing the migrations_prefix string in your config.json file. It should be set to "db/db_" I think. I'll need to add that to the user guide, but that's the default value making me think you might be on an older version.

Hope this helps!

**Comment by benlavender** [comment]
In the /db directory is:

dbconf.yml  
migrations

It’s the latest version you released on here as far as I’ aware.

So at the end of my config.json I should have?:

},
"migrations_prefix" : "db/db_"
"migrations_path" : "db/migrations/"
"db_name" : "mysql",
"db_path" : "gpuser:Password@1@(192.168.1.75:3306)/gophish?charset=utf8&parseTime=True&loc=Local",
}

**Comment by jordan-wright** [comment]
So looking through the releases, it looks like MySQL support is still only in the source branch.

You can either build from source to get support today, or I'm actually planning on doing a new release this weekend or early this week, so you could wait until then to continue using the prebuilt binaries.

**Comment by benlavender** [comment]
@jordan-wright thanks, I’ll give source a go today and for further use will use the compiled binaries.

**Comment by jordan-wright** [comment]
Hey @benlavender!

Glad to hear the source worked. If you can stay on the source, it's recommended since you can pull latest changes much quicker. Otherwise, I've uploaded new binaries that include the MySQL support.
