### ISSUE TITLE
2nd Effort Mail Failing

### ISSUE THREAD

**Issue by SEBreniac** [gophish/gophish#548]
**Problem:**

The problem that I ran into was while sending a very large campaign (close to 9000 users). The default configuration for an exchange server is to timeout a connection at 10 minutes. When this timeout is hit while GoPhish is sending out a campaign, GoPhish gets a timeout error message from exchange and assumes that it failed to send the email (which is true) and skips that email. After the timeout, GoPhish will then proceed to reconnect to the exchange server for the next email and continue sending until the 10 minute timeout is reached again.

The ultimate result for a very large campaign is 1 email dropped every 10 minutes (was somewhere around 1 in 2000 or so for our sending rate) which we ended up creating a follow-up campaign to resend the dropped messages.

**Idea:**

Allow the sending loop to perform some sort of "2nd effort" type failing when sending a message (perhaps with some exceptions for specific errors).

For example, the timeout errors can be solved by a simple reconnect and retry. Using this method, a message could be considered officially failed if the 2nd sending attempt also fails.

Note: I realize this isn't really a GoPhish error persay, but rather, it is an exchange configuration thing; however, the application could handle the error as suggested above to alleviate the need to change certain configurations on a mail server.

**Comment by S0larflare** [comment]
This is something I noticed while I've been working on a sending delay. I got around it by creating a new connection before that 10 minute period expires. Probably not the most elegant solution, personally I'd prefer if gomail had a retry functionality

Sent from my iPhone

On 28 Feb 2017, at 16:49, SEBreniac <notifications@github.com<mailto:notifications@github.com>> wrote:


Problem:

The problem that I ran into was while sending a very large campaign (close to 9000 users). The default configuration for an exchange server is to timeout a connection at 10 minutes. When this timeout is hit while GoPhish is sending out a campaign, GoPhish gets a timeout error message from exchange and assumes that it failed to send the email (which is true) and skips that email. After the timeout, GoPhish will then proceed to reconnect to the exchange server for the next email and continue sending until the 10 minute timeout is reached again.

The ultimate result for a very large campaign is 1 email dropped every 10 minutes (was somewhere around 1 in 2000 or so for our sending rate) which we ended up creating a follow-up campaign to resend the dropped messages.

Idea:

Allow the sending loop to perform some sort of "2nd effort" type failing when sending a message (perhaps with some exceptions for specific errors).

For example, the timeout errors can be solved by a simple reconnect and retry. Using this method, a message could be considered officially failed if the 2nd sending attempt also fails.

Note: I realize this isn't really a GoPhish error persay, but rather, it is an exchange configuration thing; however, the application could handle the error as suggested above to alleviate the need to change certain configurations on a mail server.

**Comment by S0larflare** [comment]
So I had a quick fiddle with this last week, essentially just creating a new dialler and resending the email as part of the for loop if the error was a connection error or broken pipe. It works, but annoyingly it still gets written as an error in the database (and therefore the GUI) even though the user will receive the 2nd email. I sort of know why it is happening, but fixing it was beyond me last week. I'll take another look when I get a chance, but I might have to just post what I have done and see if someone more well versed in go can correct my approach.

**Comment by jordan-wright** [comment]
Yes, this is an issue with the email sending loop. I'm planning to spend some time refactoring our emails to be queued a little better. This will allow re-sending both automatically (with exponential backoff) as well as on demand.

**Comment by jordan-wright** [comment]
This should be fixed as part of the refactor from #878. If you could give it a shot and let me know if it helps, I'd appreciate it!
