### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by CaptainBobby** [gophish/gophish#550]
I have created an application that pulls group data from the API so I am able to quickly determine the status of a target in our directory via LDAP (email, name mismatch or use no longer exists). I am now attempting to use your same api.groupId.put() function to push any changes back through the API, however this is not working due to the following response:

 Method PUT is not allowed by Access-Control-Allow-Methods in preflight response.

Is there any change that I can make on the server to allow this action?

**Comment by jordan-wright** [comment]
Hey @CaptainBobby,

Can you give a bit more details about what you're doing? Are you using the Python API client? If so, is there any specific problematic code you can share that reproduces the issue?

**Comment by CaptainBobby** [comment]
I am not using the Python API, I was hoping to push the changes via HTTP post or put. Perhaps this is not possible?
Basically I use an http get method to pull the data from gophish, load it into my own editable table where it also displays the status of the user in our eDirectory tree. This simplifies the process of eliminating a bad target, or fixing misspellings, before kicking off a new campaign on the GoPhish server.
I'm pretty new to the API world. If I'm acting like a newb, let me know. Thanks!

My function creates the group json data to send to server:
`function putGroup(gi){
      var targets = groupData[gi].targets;
      group = {
        id: groupData[gi].id,
        modified_date: groupData[gi].modified_date,
        name: groupData[gi].name,
        targets: targets
      }
      api.groupId.put(group)
          .success(function(data) {
              alert('Group updated successfully!');
          })
          .error(function(data) {
              alert('Failed to update group.');
          })
    }`

Using your function from gophish.js:
`function query(endpoint, method, data, async) {
    return $.ajax({
        url: "http://192.168.10.29:3333/api/" + endpoint + "?api_key=" + api_key,
        async: async,
        method: method,
        data: JSON.stringify(data),
        dataType: "json",
        contentType: "application/json"
    })
}

var api = {
  groupId: {
    put: function(group) {
        return query("/groups/" + group.id, "PUT", group, false)
    }
  }
}`

**Comment by jordan-wright** [comment]
Oh, I gotcha. Yeah, that's totally possible. When I have time later this evening or tomorrow I'll investigate a bit more and send over a solution.

**Comment by jordan-wright** [comment]
Hey @CaptainBobby, sorry for the delay.

You should be able to change this line to include "PUT" and "DELETE" and be good to go. https://github.com/gophish/gophish/blob/master/middleware/middleware.go#L69

When I get a chance, I'll make the change to the main repo.

Let me know if that works for you! Sorry for the trouble.

**Comment by CaptainBobby** [comment]
@jordan-wright, thanks for the response.

I made the changes to the line you suggested and restarted the gophish server but I'm still getting the same error mentioned in my original post.

**Comment by S0larflare** [comment]
Hi @CaptainBobby, you'll have to recompile it for it to work. Have you built it from source or are you using a pre built binary?

**Comment by CaptainBobby** [comment]
@S0larflare,

I will do that and let you know. It was a passing thought of mine that it might be necessary but it passed and was forgotten. ;-)

Thanks.

**Comment by CaptainBobby** [comment]
Worked like a charm! Thank you!
