### ISSUE TITLE
change from email address

### ISSUE THREAD

**Issue by rijudewan** [gophish/gophish#553]
it is possible to change the from email to something like reception domain to make it look more real
actual : James Ong <gophishingmy@gmail.com>
i want some thing like  James <james@comapny_domain.com>

Thank you

**Comment by S0larflare** [comment]
Depending on your setup - certainly! If you're using gmail, you might struggle (as they likely don't allow you to spoof your email address using their servers) but if you have your own SMTP server, then just change the From field to whatever you want it to be in the Sending Profile.

**Comment by rijudewan** [comment]
Thank you it works as u have mention .. using my own SMTP server
