### ISSUE TITLE
Cant save landing page

### ISSUE THREAD

**Issue by rijudewan** [gophish/gophish#554]
hi

after i import landing page for face or gmail i cant save it . i click the save button but nothing is happening

**Comment by jordan-wright** [comment]
Hi @rijudewan,

To help us debug the issue, please provide the exact steps you're taking to reproduce the problem - screenshots help.

Thanks!

**Comment by rijudewan** [comment]
thank you .. i just did a reinstall its working fine now .. not sure what went wrong after i deleted few landing page i wan not able to create new with import option

**Comment by jordan-wright** [comment]
Glad to hear you were able to get it working!
