### ISSUE TITLE
How to i link my landing page

### ISSUE THREAD

**Issue by rijudewan** [gophish/gophish#555]
Hi
how can i link my landing page to email without a source copy. i create a template myself and i want to link all the link to my landing page

**Comment by jordan-wright** [comment]
I _think_ I see what you're asking, and the answer is likely to refer to the section on [Template Variables](https://gophish.gitbooks.io/user-guide/content/template_reference.html) in the User Guide.

Specifically, you'll want to point your links to `{{.URL}}` which will point to the landing page.

Hope this helps! Let us know if you run into any other issues.
