### ISSUE TITLE
errror while using this ,plz help

### ISSUE THREAD

**Issue by devrajashwin** [gophish/gophish#556]
root@localhost:~/Desktop/gophish-master# ./gophish.go 
./gophish.go: line 1: package: command not found
./gophish.go: line 3: /0: Permission denied
./gophish.go: line 4: gophish: command not found
./gophish.go: line 6: syntax error near unexpected token `('
./gophish.go: line 6: `The MIT License (MIT)'

**Comment by jordan-wright** [comment]
Hi @devrajashwin,

Please review [the User Guide](https://gophish.gitbooks.io/user-guide/content/installation.html) where it explains how to build gophish from source. It does not appear that you are compiling Gophish and instead are attempting to execute the source code files which won't work.

Hope this helps! If you follow the instructions in the User Guide and run into any specific issues, let us know.
