### ISSUE TITLE
Having trouble importing users

### ISSUE THREAD

**Issue by TechTodd** [gophish/gophish#557]
I am trying to import users as i create a group. It creates the group fine, but it will not add the users. On the console i see the following:

`127.0.0.1 - - [10/Mar/2017:10:14:40 -0500] "POST /api/import/group HTTP/2.0" 200 80 "https://localhost:3333/users" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8"`

I am using the interface for this task and not the API interface. My datafile is a CSV in UTF-8 encoding. I followed the format in the API for the fields:

> First Name
Last Name
Position
Email
Company

Any help would be greatly appreciated.

**Comment by S0larflare** [comment]
Try removing the 'company' column from your csv. As far as I am aware that was never added

Sent from my iPhone

On 10 Mar 2017, at 15:32, TechTodd <notifications@github.com<mailto:notifications@github.com>> wrote:


I am trying to import users as i create a group. It creates the group fine, but it will not add the users. On the console i see the following:

127.0.0.1 - - [10/Mar/2017:10:14:40 -0500] "POST /api/import/group HTTP/2.0" 200 80 "https://localhost:3333/users" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8"

I am using the interface for this task and not the API interface. My datafile is a CSV in UTF-8 encoding. I followed the format in the API for the fields:

First Name
Last Name
Position
Email
Company

Any help would be greatly appreciated.

**Comment by TechTodd** [comment]
Ok, i tried that and nothing. My format is:

`fname,lname,email`

after i select the file and press "Choose"  no names get listed on the screen.

**Comment by dragontologist** [comment]
You need a few things: 1) four fields (even if one is just blank) and the last one is Position. 2) The categories need to be spelled out as the top line: "First Name,Last Name,Email,Position" 3) you can't have a space or incorrect format anywhere in the email fields.

**Comment by TechTodd** [comment]
That was it!  Thanks Dragontologist!  

Quick Side question, i can copy that gophish.db file to a different machine and it should pick it up and keep on rolling correct?  For example i am currently on my Mac, but after all the configuring and setup it will be run on a windows machine. just copy that 1 file?

**Comment by TechTodd** [comment]
I answered my own question. Thanks for all the help!
