### ISSUE TITLE
Internal mailer using AWS listener

### ISSUE THREAD

**Issue by DtachableGenius** [gophish/gophish#558]
So I'd like to set up gophish internally so I can use an internal SMTP server and spoof any email address I want easily.  However, the challenge remains for those that are "off network" won't be able to connect to the listener. 
 ----   Any guidance on setting up an internal admin box "for template config, email sending etc. , but have an external (AWS) listener and landing page?

**Comment by jordan-wright** [comment]
So, this kind of host separation isn't natively supported.

That being said, the important thing is that both hosts share the same database. If you expose the database such that both the internal and external host can reach it (say, by using a password protected mysql instance) that should be all you need to separate the functionality.

Then, just make sure your config instance and campaign setups all point to the correct host for the phishing URLs, etc. and you should be good to go.

**Comment by jordan-wright** [comment]
Hey @DtachableGenius, just wanted to check in - did this answer your question?

**Comment by DtachableGenius** [comment]
Ya, you can close it.  I figured there would have to be a shared database somehow just didn't really know how to go about doing it.  Thanks

**Comment by jordan-wright** [comment]
You bet! Don't hesitate to reach out if there's any other help we can give.
