### ISSUE TITLE
Suport of Russian letters in Sender name

### ISSUE THREAD

**Issue by Y0shiT0shi** [gophish/gophish#559]
Hi, Jordan.

Many thanks for your product, it's a great tool!

But I have a little problem. While creating Sending Profile I get an error if "From:" field contains russian letters in sender name.

For example. One russian word:
![gophish](https://cloud.githubusercontent.com/assets/25222439/23887355/3366e3e8-08a3-11e7-9d48-c72212fa4a1a.png)

And two russian words in sender name:
![gophish_2](https://cloud.githubusercontent.com/assets/25222439/23887388/68f4a496-08a3-11e7-9ed6-2da0912435f0.png)

**Comment by S0larflare** [comment]
I suspect this is a problem with gomail or the language itself rather than gophish, though I can't confirm it at the moment.

**Comment by Y0shiT0shi** [comment]
OK, thanks!

**Comment by jordan-wright** [comment]
This is indeed a problem with the Golang stdlib. You can find more information in #404 and #409.

I'm afraid I don't have a timeline for a fix atm. Since we already have issues created to track this problem, I'm going to go ahead and close this one out.

Thanks for the report @Y0shiT0shi!
