### ISSUE TITLE
0.3 Clone / Duplicate a campaign is not working

### ISSUE THREAD

**Issue by stracire** [gophish/gophish#560]
Since 0.3 cloning / Duplicating a campaign will not give the same landing page and e-mail template. It will display the first landing page and e-mail template record the system can find.

I really like to prepare a campaign as a test before I send them to an entire organisation. Therefore I really like to clone a prepared test-campaign and only change te receiver-group.

**Comment by stracire** [comment]
Sorry sounds like the same issue as:
https://github.com/gophish/gophish/issues/549

**Comment by jordan-wright** [comment]
Hey @stracire,

Indeed, this appears to be the same issue. I should have that one fixed soon. I'm going to go ahead and close this one out as a duplicate.

Thanks for the report!
