### ISSUE TITLE
URL not linking to landing page

### ISSUE THREAD

**Issue by Pavornoc** [gophish/gophish#561]
After creating the email template, the landing page, the sending profiles, and getting everything set up, I am unable to get the link within the email to go to the created landing page when I launch a campaign.  

I have the variable {{.URL}} within the email and the correct URL listed in the campaign creation page.  I've tried using HTTP, HTTPS, the FQN, and just the IP in the URL field for the New Campaign page and they never connect to the landing page, just the default page of the server (which just says "404 page not found").  I've been over the documentation several times, but I'm not sure what I'm missing.

Installed on Ubuntu 16.04 Server using Postfix for email relay.

Can anyone give me some assistance?

**Comment by jordan-wright** [comment]
What is the actual link that is being rendered in the emails that are received?

**Comment by Pavornoc** [comment]
Thank you so much for the quick reply, @jordan-wright!

I'm not sure what I did differently, but I walked away, came back, and now the URLs are pointing to the landing pages, but the landing pages themselves aren't rendering.  In the campaign status, I will see when the link has been clicked, but when I do, I just get a blank white page.  

I'm going to try hosting the page statically as you detailed in the documentation.

On the one hand, I hope it works, but on the other, I'm sorry if I've wasted your time!

**Comment by Pavornoc** [comment]
Ok, even hosting the html page statically gives me a blank page when I click on the link. What's odd is that when I view the page source, it has all the html code present, so it's being served but not rendering? I'm not sure why this would be.  I tested the link in Firefox and Chrome and got the same results. 

Does the GoPhish server need a certain amount of time to process/load newly created landing pages or anything like that? Sorry if that's a silly question, just wondering if I'm trying to access it too quickly.

**Comment by S0larflare** [comment]
Is this a page you have created yourself? Just a simple "Hello World" or is this one you have scraped from somewhere? If you have scraped one, it could have protections built in to only load where it is meant to. An example is the Apple login page, you'd have to make that mostly from scratch as it is loaded via scripts mostly.

**Comment by Pavornoc** [comment]
Ah, that may be it.  The two that I tried to scrape were Google Drive and Facebook.  I just ran a test with basic "Hello World" and that loaded.  Looks like I either need to scrape different targets, or build manually.  

Thank you for the help, @S0larflare, I appreciate it!  I'll close out the issue.
