### ISSUE TITLE
Need assistance on gophishing remote employees

### ISSUE THREAD

**Issue by alexismya2017** [gophish/gophish#562]
I installed gophish on Linux. I followed directions found online to do this and everything is set up properly. My goal is to phish my remote employees for training purposes. The employees are at remote locations, not at my location. The article I read told me once I completed the gophish installation that "If you are targeting users only on your LAN, then your good to go, If you are targeting your remote staff then you need to set a couple of firewall rules to allow the click back to get to the phishing VM." What firewall rules should be set up to allow the traffic to my virtual machine?

**Comment by S0larflare** [comment]
Essentially, you need to have a route for your target to be able to reach your machine. If you have gophish set up on your VM, then that VM would need to be routable on the internet (or if the remote users come in to your network through remote access, then it should work fine with it not being on the internet, provided there's nothing segregating them from your machine).

**Comment by alexismya2017** [comment]
I accidentally changed the mac address of my VM network card and cannot find an IP address for eth0. Who do you think I can get who can help me?

**Comment by S0larflare** [comment]
Does "ip addr show eth0" not work?

Sent from my iPhone

On 15 Mar 2017, at 16:45, alexismya2017 <notifications@github.com<mailto:notifications@github.com>> wrote:


I accidentally changed the mac address of my VM network card and cannot find an IP address for eth0. Who do you think I can get who can help me?

**Comment by jordan-wright** [comment]
I'm afraid that managing a virtual machine is out of the scope for the support we can offer.

I recommend reviewing the user documentation for your virtualization software to determine how to create and manage VM's. The documentation for your operating system can point you to the correct way to manage network settings in the VM itself.

**Comment by alexismya2017** [comment]
I get this when entering in "ip address show eth0"
2: eth0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 08:00:27:5a:7b:ae brd ff:ff:ff:ff:ff:ff

**Comment by alexismya2017** [comment]
I fixed network problem. Not able to understand how to

Essentially, you need to have a route for your target to be able to reach your machine. If you have gophish set up on your VM, then that VM would need to be routable on the internet (or if the remote users come in to your network through remote access, then it should work fine with it not being on the internet, provided there's nothing segregating them from your machine).

**Comment by alexismya2017** [comment]
Not sure how to do this. Would love instructions

**Comment by jordan-wright** [comment]
You just need to make sure people can reach the phishing server. This is, by default, listening on all interfaces which means that if your host is accessible from the internet, you'll be good to go.

If you're behind a firewall, you'll need to add rules to allow traffic go hit your phishing server. It is beyond the scope of our support to help with this since it is 100% specific to your network. It's no different than standing up any other web server so you'll just need to take the standard actions to expose the web server to the Internet so remote employees can reach it.

**Comment by alexismya2017** [comment]
Thank you so much Jordan! I have another question about setting up email. I will wait until next week to post this. Thanks again
