### ISSUE TITLE
gophish.exe as a Windows service

### ISSUE THREAD

**Issue by choquettejm** [gophish/gophish#566]
How would I go about running gophish.exe as a service on server startup, without having to be logged into the server.  For Windows server.

Thanks

**Comment by jordan-wright** [comment]
I've heard of people using [nssm](http://nssm.cc/) to do this, though I haven't tried it myself.

Let me know if that helps!

**Comment by choquettejm** [comment]
Thanks Jordan, so far so good.  It even survived a reboot.

**Comment by jordan-wright** [comment]
👍 Good deal! Glad it worked out for you.
