### ISSUE TITLE
GoPhish0.3 crashes when logging in

### ISSUE THREAD

**Issue by derWeihnachtsmann** [gophish/gophish#567]
Hey, 
I recently downloaded the v0.3. I re-imported my db and my config from my working v0.2. Unfortunately, when startig, GoPhish crashed. So I decided to remove the database file and start all over. but still same issue..

> 2017/03/22 15:05:39 worker.go:36: Background Worker Started Successfully - Waiting for Campaigns
 2017/03/22 15:05:39 models.go:98: no valid version found
no valid version found
 2017/03/22 15:05:39 gophish.go:79: Starting phishing server at https://mydomain.eu:443
 2017/03/22 15:05:39 gophish.go:66: Starting admin server at https://mydomain.eu:57931
10.14.10.139 - - [22/Mar/2017:15:05:42 +0100] "GET /login HTTP/2.0" 200 1064 "" "Mozilla/5.0 (Windows NT 6.3; WOW64)                                       AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
10.14.10.139 - - [22/Mar/2017:15:05:42 +0100] "GET /images/logo_inv_small.png HTTP/2.0" 200 1146 "https://mydomain.eu:57931/login" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/                                      56.0.2924.87 Safari/537.36"
10.14.10.139 - - [22/Mar/2017:15:05:42 +0100] "GET /images/logo_purple.png HTTP/2.0" 200 4735 "https://mydomain.eu:57931/login" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.                                      0.2924.87 Safari/537.36"
10.14.10.139 - - [22/Mar/2017:15:05:42 +0100] "GET /css/dist/gophish.css HTTP/2.0" 200 50138 "https://mydomain.eu:57931/login" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0                                      .2924.87 Safari/537.36"
10.14.10.139 - - [22/Mar/2017:15:05:42 +0100] "GET /js/dist/vendor.min.js HTTP/2.0" 200 225274 "https://mydomain.eu:57931/login" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56                                      .0.2924.87 Safari/537.36"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x72c056]

>goroutine 8 [running]:
github.com/jinzhu/gorm.(*DB).clone(0x0, 0xc4204776e0)
        /go/src/github.com/jinzhu/gorm/main.go:699 +0x76
github.com/jinzhu/gorm.(*DB).Where(0x0, 0x9bebc0, 0xc420010580, 0xc420010550, 0x1, 0x1, 0xc420173c20)
        /go/src/github.com/jinzhu/gorm/main.go:166 +0x2b
github.com/gophish/gophish/models.GetQueuedCampaigns(0xed0647bef, 0xc42a081078, 0xf4c320, 0x1, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/gophish/gophish/models/campaign.go:335 +0x189
github.com/gophish/gophish/worker.(*Worker).Start(0xf69360)
        /go/src/github.com/gophish/gophish/worker/worker.go:38 +0x196
created by github.com/gophish/gophish/controllers.init.1
        /go/src/github.com/gophish/gophish/controllers/api.go:31 +0x67

When I type wrong username and PW I get following Error:

>10.14.10.139 - - [22/Mar/2017:15:19:11 +0100] "GET /css/dist/gophish.css HTTP/2.0" 200 50138 "https://mydomain.eu:57931/login" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
10.14.10.139 - - [22/Mar/2017:15:19:11 +0100] "GET /js/dist/vendor.min.js HTTP/2.0" 200 225274 "https://mydomain.eu:57931/login" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
2017/03/22 15:19:21 http2: panic serving 10.14.10.139:31748: runtime error: invalid memory address or nil pointer dereference
goroutine 194 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc4201c6018, 0xc4203cdfaf, 0xc42022e1c0)
        /usr/local/go/src/net/http/h2_bundle.go:4592 +0x190
panic(0x9eaba0, 0xf0c150)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/jinzhu/gorm.(*DB).clone(0x0, 0xc4203cd2c0)
        /go/src/github.com/jinzhu/gorm/main.go:699 +0x76
github.com/jinzhu/gorm.(*DB).Where(0x0, 0x9bebc0, 0xc420011d00, 0xc420011ca0, 0x1, 0x1, 0xa770c9)
        /go/src/github.com/jinzhu/gorm/main.go:166 +0x2b
github.com/gophish/gophish/models.GetUserByUsername(0xc4202221b9, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4200e4bd0, ...)
        /go/src/github.com/gophish/gophish/models/user.go:39 +0x1bc
github.com/gophish/gophish/auth.Login(0xc42000b500, 0x9bebc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xf25920, ...)
        /go/src/github.com/gophish/gophish/auth/auth.go:46 +0xf5
github.com/gophish/gophish/controllers.Login(0xf238e0, 0xc4200b53a0, 0xc42000b500)
        /go/src/github.com/gophish/gophish/controllers/route.go:466 +0x191
net/http.HandlerFunc.ServeHTTP(0xa98fc0, 0xf238e0, 0xc4200b53a0, 0xc42000b500)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201be050, 0xf238e0, 0xc4200b53a0, 0xc42000b500)
        /go/src/github.com/gorilla/mux/mux.go:114 +0x10c
github.com/gorilla/csrf.(*csrf).ServeHTTP(0xc42025f860, 0xf238e0, 0xc4200b53a0, 0xc42000b300)
        /go/src/github.com/gorilla/csrf/csrf.go:267 +0x32d
net/http.(Handler).ServeHTTP-fm(0xf238e0, 0xc4200b53a0, 0xc42000b000)
        /usr/local/go/src/net/http/h2_bundle.go:4319 +0x4d
net/http.HandlerFunc.ServeHTTP(0xc4202749e0, 0xf238e0, 0xc4200b53a0, 0xc42000b000)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/gophish/gophish/middleware.CSRFExceptions.func1(0xf238e0, 0xc4200b53a0, 0xc42000b000)
        /go/src/github.com/gophish/gophish/middleware/middleware.go:27 +0xc4
net/http.HandlerFunc.ServeHTTP(0xc420274a00, 0xf238e0, 0xc4200b53a0, 0xc42000b000)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/gophish/gophish/middleware.GetContext.func1(0xf238e0, 0xc4200b53a0, 0xc42000b000)
        /go/src/github.com/gophish/gophish/middleware/middleware.go:57 +0x295
net/http.HandlerFunc.ServeHTTP(0xc420274a20, 0xf238e0, 0xc4200b53a0, 0xc42012c100)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/NYTimes/gziphandler.NewGzipLevelHandler.func1.1(0x7f6250cb3460, 0xc4200b5380, 0xc42012c100)
        /go/src/github.com/NYTimes/gziphandler/gzip.go:181 +0x15d
net/http.HandlerFunc.ServeHTTP(0xc420274a40, 0x7f6250cb3460, 0xc4200b5380, 0xc42012c100)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/gorilla/handlers.combinedLoggingHandler.ServeHTTP(0xf1eda0, 0xc42000e018, 0xf1ff20, 0xc420274a40, 0xf23de0, 0xc4201c6018, 0xc42012c100)
        /go/src/github.com/gorilla/handlers/handlers.go:77 +0x121
github.com/gorilla/handlers.(*combinedLoggingHandler).ServeHTTP(0xc420274a60, 0xf23de0, 0xc4201c6018, 0xc42012c100)
        <autogenerated>:9 +0x86
net/http.serverHandler.ServeHTTP(0xc420288000, 0xf23de0, 0xc4201c6018, 0xc42012c100)
        /usr/local/go/src/net/http/server.go:2568 +0x92
net/http.initNPNRequest.ServeHTTP(0xc420070700, 0xc420288000, 0xf23de0, 0xc4201c6018, 0xc42012c100)
        /usr/local/go/src/net/http/server.go:3088 +0x93
net/http.(*initNPNRequest).ServeHTTP(0xc420011000, 0xf23de0, 0xc4201c6018, 0xc42012c100)
        <autogenerated>:312 +0x74
net/http.(Handler).ServeHTTP-fm(0xf23de0, 0xc4201c6018, 0xc42012c100)
        /usr/local/go/src/net/http/h2_bundle.go:4319 +0x4d
net/http.(*http2serverConn).runHandler(0xc42022e1c0, 0xc4201c6018, 0xc42012c100, 0xc42047e1e0)
        /usr/local/go/src/net/http/h2_bundle.go:4599 +0x89
created by net/http.(*http2serverConn).processHeaders
        /usr/local/go/src/net/http/h2_bundle.go:4331 +0x4ac

>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x72c056]

>goroutine 8 [running]:
github.com/jinzhu/gorm.(*DB).clone(0x0, 0xc4200326e0)
        /go/src/github.com/jinzhu/gorm/main.go:699 +0x76
github.com/jinzhu/gorm.(*DB).Where(0x0, 0x9bebc0, 0xc4204862b0, 0xc4204862a0, 0x1, 0x1, 0xc420173d10)
        /go/src/github.com/jinzhu/gorm/main.go:166 +0x2b
github.com/gophish/gophish/models.GetQueuedCampaigns(0xed0647f15, 0xc41b38e05c, 0xf4c320, 0x1, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/gophish/gophish/models/campaign.go:335 +0x189
github.com/gophish/gophish/worker.(*Worker).Start(0xf69360)
        /go/src/github.com/gophish/gophish/worker/worker.go:38 +0x196
created by github.com/gophish/gophish/controllers.init.1
        /go/src/github.com/gophish/gophish/controllers/api.go:31 +0x67

System: Ubuntu 16.04.1 LTS x86_64
Only tried with pre compiled Binary, not with the Code.
Thank you so much for your help. Keep up the good work!

**Comment by S0larflare** [comment]
Looks like this is a problem with config.json, the migration path for the database changed from v0.2 -> v0.3 and mySQL support was added. If you're using the same config file it can cause issues


It should look something like this:


`{
        "admin_server" : {
                "listen_url" : "127.0.0.1:3333",
                "use_tls" : true,
                "cert_path" : "gophish_admin.crt",
                "key_path" : "gophish_admin.key"
        },
        "phish_server" : {
                "listen_url" : "0.0.0.0:80",
                "use_tls" : false,
                "cert_path" : "example.crt",
                "key_path": "example.key"
        },
        "db_name" : "sqlite3",
        "db_path" : "gophish.db",
        "migrations_prefix" : "db/db_"
}
`

**Comment by derWeihnachtsmann** [comment]
FIXED!
Thank you.

I edited the last three "db" - lines to get it to work and its perfect now.
Thank you for your fast support!

**Comment by S0larflare** [comment]
No problem :)
