### ISSUE TITLE
Issue installing v 0.3

### ISSUE THREAD

**Issue by 56slevin** [gophish/gophish#568]
Hello,

I'm working on upgrading to 0.3 and im getting a "TLS Handshake error" in the terminal when i attempt to login at 127.0.0.1:333. Any ideas?

**Comment by S0larflare** [comment]
Is there anything else shown in the terminal? What happens in the browser?

**Comment by 56slevin** [comment]
The browser promps me to download a file just named "login", The exact terminal error is "TLS handshake error froom 127.0.0.1:51658: tls: first record does not look like a tls handshake". I also get numerous errors such as "campaign.go:338: no such column: launch_date"

**Comment by S0larflare** [comment]
That makes me think that the config and/or the database is wrong. If you have just upgraded to 0.3 and copied over your config.json, you will probably have to update it. It should look similar to this (it's likely the end of it will need changing):

>{
>        "admin_server" : {
>                "listen_url" : "127.0.0.1:3333",
>                "use_tls" : true,
>                "cert_path" : "gophish_admin.crt",
>                "key_path" : "gophish_admin.key"
>        },
>        "phish_server" : {
>                "listen_url" : "0.0.0.0:80",
>                "use_tls" : false,
>                "cert_path" : "example.crt",
>                "key_path": "example.key"
>        },
>        "db_name" : "sqlite3",
>        "db_path" : "gophish.db",
>        "migrations_prefix" : "db/db_"
>}

**Comment by 56slevin** [comment]
my config file looks just like that verbatim. Could it be anything else?

**Comment by jordan-wright** [comment]
The new config uses https by default. Does it work when you try to connect over https?

**Comment by 56slevin** [comment]
It does! That makes sense. I figured it was something simple i missed. Thank you so much for the help!
