### ISSUE TITLE
cannot connect to SMTP server

### ISSUE THREAD

**Issue by saurabhcs0097** [gophish/gophish#570]
I am not able to connect to SMTP server, even for the gmail server as shown in example is not working , I am getting " dial tcp: lookup smtp.gmail.com: getaddrinfow: No such host is known." error, can you please help !.
Host :  smtp.gmail.com:587 , I have tried with port 467 too.

**Comment by jamlane** [comment]
I had this issue yesterday, it was my firewall blocking the connection.

**Comment by jordan-wright** [comment]
It looks like DNS may be having trouble finding smtp.gmail.com

**Comment by saurabhcs0097** [comment]
Thank you ! Jordan and Jamlane, resolved, please close this issue.
