### ISSUE TITLE
View Details is Empty

### ISSUE THREAD

**Issue by iamatulsingh** [gophish/gophish#572]
![2017-03-24 23_37_46-cat - gophish](https://cloud.githubusercontent.com/assets/20820833/24307721/42386842-10eb-11e7-863a-37cc0c5b48df.png)

View details of submitted data is empty.
one more thing is map doesn't show target location as well.

**Comment by S0larflare** [comment]
Details will be empty if no parameters are being passed by the form that's being captured. If you've scraped it from somewhere you might have to fiddle with the html of the form.

The map won't populate if it comes from an internal IP (as it cant geolocate it). External IPs should show

Sent from my iPhone

On 24 Mar 2017, at 18:12, iamatulsingh <notifications@github.com<mailto:notifications@github.com>> wrote:


[2017-03-24 23_37_46-cat - gophish]<https://cloud.githubusercontent.com/assets/20820833/24307721/42386842-10eb-11e7-863a-37cc0c5b48df.png>

View details of submitted data is empty.
one more thing is map doesn't show target location as well.

**Comment by iamatulsingh** [comment]
http://localhost:8080/?randomenumber

something like this was my url where landing page was opened.

**Comment by S0larflare** [comment]
What I mean is on your landing page you will have a form and when the submit button is clicked, gophish looks for parameters being passed, tries to grab them and puts them in the console there. However if the form is set up to do it in a special way, gophish might struggle. In that case the best way to proceed is to make the form simpler. At its heart, the form/page should be similar to this:



<!DOCTYPE html>
<html>
<body>

<form action="">
  Email:<br>
  <input type="text" name="email" value="">
  <br>
  Password:<br>
  <input type="text" name="password" type=password value="">
  <br><br>
  <input type="submit" value="Submit">
</form> 


</body>
</html>


(That's surprisingly difficult on mobile so apologies if it looks a bit off).

**Comment by iamatulsingh** [comment]
how can i use is online? i mean not on localhost... may be there i can check its map feature and more things.

**Comment by jordan-wright** [comment]
You can find instructions on exposing Gophish externally in the user guide. At a high level, it requires setting the phish URL to 0.0.0.0 in the config file and changing the campaign URL to point to your external IP address.

**Comment by jordan-wright** [comment]
Going ahead and closing this one since the original question was answered by @S0larflare.
