### ISSUE TITLE
GoPhish not updating the mail status

### ISSUE THREAD

**Issue by saurabhcs0097** [gophish/gophish#573]
Hi,

I have created a campaign and I am trying it locally in my network.
The URL field in campaign page is my local ip in my LAN network.
once the campaign is launched , I can see mail sent but no further status are seen. I cant even see the landing page on clicking the link in the mail.

Please help !
Thank you ,
Saurabh

**Comment by S0larflare** [comment]
What is the link in the email, is it {{.URL}} or something different?

**Comment by saurabhcs0097** [comment]
link in the mail is http://localIp?rid=long string

**Comment by jordan-wright** [comment]
When you say the link in the mail, do you mean the actual link you receive?

If so, what exactly do you see when you click the link? Do you see a log in the gophish terminal for the service being hit?

If you don't see any logs, the host likely can't reach gophish due to a firewall.

**Comment by saurabhcs0097** [comment]
Hi Jordan , thanks a lot for the response, I got this issue resolved , there was problem with the port that I configured in .json file.
but now I am facing issues in gathering the entered data. I have used LinkedIn login page but entered data is not reflected in report, however the tool updates the link Clicked but no progress thereafter.
 I am using GoPhish for first time so please execuse if my questions sounds novice.

Thank you!

**Comment by jordan-wright** [comment]
Hi @saurabhcs0097 glad to hear this got resolved. For the cloned page issue, please refer to [these similar](https://github.com/gophish/gophish/search?q=capturing+credentials&type=Issues&utf8=%E2%9C%93) issues for information about what's likely happening.
