### ISSUE TITLE
ideas for 'little improvements'

### ISSUE THREAD

**Issue by InfoSecOne** [gophish/gophish#575]
Hi, 
I've been using this software for a while now and I have some observations & ideas that I want to share - on my wish list are: 

- in Campaigns, add 'Scheduled at' date next to, 'Created at'
- show how many times, the email was opened/clicked (if more than 1 time)
- in email source view, can we add option to wrap a lines and maybe colour the syntax as HTML

**Comment by jordan-wright** [comment]
Thanks for reaching out!

I like the idea of syntax highlighting - I bet we could do something like that.

Re: the click + open counts - I don't know of a good place those could fit in the UI. You can see the information by expanding the recipient rows.

And I'll consider adding the scheduled date. If it fits in the UI, I have no problem with it 😄 

Thanks again for getting in touch!

**Comment by InfoSecOne** [comment]
Hi, I have a couple of more suggestion after using this amazing platform for a few months...

- LOGS, can we have a nice log file to capture all events? piping the output to a file manually every time when we starting ./gophis is quite annoying (I am using either ' | tee filename_date.txt ' '>>'
- Can we add a feature, where we can actually see what was settings were used for a given Campaign? (email template used, groups, landing page etc.) This is not visible after the campaign was saved/run. 
- Can we add a feature to delete a single user from a campaign that was already completed/running? i.e. I am adding my private email to each group to make sure that the emails were sent correctly, but I don't want to share this with the audience. I know that I can export results to a CSV file and delete it there, but who would do that if we had a new, nice feature like that.
- LANDING PAGE is not displayed/reachable when we forget to add http:// or https:// or use only IP address

**Comment by Raytri3** [comment]
-  LOGS would love to have a view into the postgress MTA logs via the GUI. Also, if they were exportable via the GUI that would be great as well. It will allow me to see any problems as they arise and also allow me to add them to my reports.

- When you schedule a campaign in the future the status for the campaign shows "sending" when it really isn't yet. Can we have a "scheduled" flag first and then switch to "sending" at time of campaign?

**Comment by jordan-wright** [comment]
If possible, let's keep separate requests on separate issues.

While some of these are doable (I'll post a larger response later), it would be nearly impossible for me to ever close this issue if it waited until everything in it was resolved.

Instead, I encourage y'all to make separate, single request issues that we can address and track separately.

Thanks for sending these ideas over!

**Comment by jordan-wright** [comment]
Going ahead and closing this one out since 2 of the 3 initial requests (scheduling campaigns and showing multiple clicks/credentials submits) have been implemented. In addition, as mentioned before, it's difficult to close out issues with more than one feature request.

Thanks again for sending this in!
