### ISSUE TITLE
MySQL Error 1292 when creating a new campaign.

### ISSUE THREAD

**Issue by deathkn3ll** [gophish/gophish#577]
Hallo,

Just setup a new GoPhish instance and try as I might to create a new Campaign, I get the following error:

> Error 1292: Incorrect datetime value: '0000-00-00' for column 'completed_date' at row 1

Quick google suggests it is as the error states, the datetime value isn't quite being handled correctly?

**Comment by jordan-wright** [comment]
Are you doing anything to schedule a campaign? What does your campaign setup look like?

**Comment by deathkn3ll** [comment]
Campaign setup was pretty much standard. Time was auto set as the current time for the campaign (didn't try a point in time ahead, that's an idea actually...)

**Comment by S0larflare** [comment]
Is this the first time you have installed Gophish, or have you upgraded?

**Comment by deathkn3ll** [comment]
First time install :)

**Comment by S0larflare** [comment]
Is this using the default SQLite, or have you set up a MySQL database? Is this built from source, or have you downloaded the latest stable build?

**Comment by deathkn3ll** [comment]
It is using a MySQL database (again from scratch). It was using the latest stable build.

**Comment by deathkn3ll** [comment]
Just as an update. I knocked up another box with Gophish on but using the default SQlite3 DB. The campaign seems to launch correctly, so it suggests an issue when using MySQL.

Will happily provide any more info if I can.

**Comment by S0larflare** [comment]
Well googling the error, I found this:

https://github.com/mantisbt-plugins/source-integration/issues/39

![image](https://cloud.githubusercontent.com/assets/8939757/24655064/6f2fa454-1934-11e7-9e38-422554aaf5c0.png)

So it would seem that you might be able to change the config to allow invalid dates in MySQL. Gophish adds 0000-00-00 as the date for completion of a campaign when it is created, then updates that value when it is actually completed, I don't think SQLite would be able to deal with a null value for a date, though I could be wrong. Jordan would probably know a fair bit better than I would.

**Comment by ferreirasc** [comment]
Hello!

With mysql 5.7, date value like 0000-00-00 00:00:00 is not allowed.

Add in [mysqld] section of your my.cnf (for me, it was in "/etc/mysql/mysql.conf.d"):

`sql_mode="NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"`

This works for me. :-)

**Comment by jordan-wright** [comment]
Closing this one out since it seems a workaround in the mysql config has been identified. Thanks @ferreirasc!
