### ISSUE TITLE
How can I use a domain for the phishing server instead of an IP address?

### ISSUE THREAD

**Issue by Nawor3565** [gophish/gophish#578]
First off, I'd like to say that I'm new to the way websites work internally, so I'm sorry for any mistakes. 

Anyway, I'm running a phishing campaign for the employees at my small business, and I forwarded the port that the phishing server uses so it can be accesses from anywhere else (the page mimics my business's login page, so no one else should be affected if they stumble upon it), but the fact that it leads to an IP address tips most people off. I bought a domain that resembles the business's, but is wrong enough that someone could tell it they looked closely, which is what I want to encourage. So my question is, how would I make the phishing server listen on the domain? I bought the domain through GoDaddy, if that has any effect. Thanks!

**Comment by jordan-wright** [comment]
You will need to setup an `A` record that points to the external IP address of the Gophish server.

Then, in your `config.json`, make sure you're listening on all interfaces in your `phish_server` entry. It should be something like `0.0.0.0:80`.

Finally, when you build a campaign you can use the domain name as the URL. Recipients should then be able to reach your Gophish server.

**Comment by Nawor3565** [comment]
Perfect! It worked like a charm. Thanks a ton!

**Comment by ade18** [comment]
Can you please clarify what what you meant by the external IP address of the Gophish Server. I am currently having issues with Gophish listening on a domain i registered.
