### ISSUE TITLE
Real world phishing integration

### ISSUE THREAD

**Issue by shadowempire123** [gophish/gophish#579]
Hi,
maybe somebody could help me with this question:

We are planning to build a Phishing awareness training into Microsoft Exchange.

First step is to integrate a "Report Phishing" button (via a macro or Microsoft add-in) in Outlook.
Clicking on the button will forward the current suspicious phishing email to an internal security email address (like phishingalert@ourcompany.com) and the mail will be "deleted" / "moved into the Junk mail folder".

On the other side we want to use gophish as a simulator.

So when we are running a phishing campaign there are two possibilities for reporting:
1.) click on the "Report Phishing" button (mail forwarded to phishingalert@ourcompany.com, deleted)
2.) click a link in the phishing mail -> will be reported to gophish as successful click

We would like to be able to add the correctly reported phishing also to the phishing campaign report.
Our idea was to build a webservice / api call to fetch all mails/responses from phishingalert@ourcompany.com and export these mails to gophish.

This would also make it possible to report "real world phishing attempts".
Any idea how to accomplish that.

As far as I see, the gophish import/email API only let you import emails as templates but it is not possible to modify the campaign report...?

Another question:
I hope I did not miss this in the documentation...
When a campaign was started there are only 2 outcomes: 
- link in the mail was not clicked (no response)
- link was clicked (phishing successful) + possible data catching (user&pwd)
So it is not possible to see, if somebody recognized the phishing attempt (like adding a link in the email: "got you! I did not fall into the phishing attempt" -> would set successfully recognized as phishing in the report)?

thx for some clarification

**Comment by jordan-wright** [comment]
There is no capability in Gophish to track reported emails. You could add it _fairly_ easily, but it's not a high priority item for us atm.

My best recommendation would be to use the Gophish API as well as an IMAP connection to your reporting inbox to consolidate the information into a new report.

Sorry we can't be of more help! The API is there to help make it easy to get campaign info out of Gophish. Getting custom campaign info into Gophish is a much harder problem 😄

**Comment by rfdevere** [comment]
Could you not abuse the position attribute to place a unique URL in the emails? Upload the contact import csv and in the 'position' column place in the custom tracking URL with a {{.Position}} in the email? Just an idea.  

Users would then receive the {{.URL}} link in the email to monitor for phishing and the {{.Position}} url for your reporting button.
