### ISSUE TITLE
503 issue a reset if you want to start over

### ISSUE THREAD

**Issue by mcb-phish** [gophish/gophish#580]
I have a large group of email addresses of our users and some of them become expired ( no longer a valid email address ) and once one of the email address is encounter  it produces in the log the following error
"could not send email 1: 503 issue a reset if you want to start over" .
But it also produces that same error for all consecutive email addresses in the group even if they are valid email addresses ???
 it seems to be in module worker.go where the code is as follow:

		err = gomail.Send(s, e)
		if err != nil {

where somehow the err is not reset to nil for following email addresses and therefore flags the remaining addresses as err (errors)

how does one issue a "reset"  ?

Best Regards

Mike

**Comment by jordan-wright** [comment]
Hey @mcb-phish, is this issue different than #534?

**Comment by mcb-phish** [comment]
I'm sorry ... nooo its not ... I thought #534 was closed ... Its still the same issue .
I did some tests (modified code and recompiled ) but i can not seem to clear the error after its been reported once for an invalid email address all subsequent email addresses are reported as errors but they are not invalid email addresses.... I was hoping i'd help in debugging ... :)

Mike

**Comment by jordan-wright** [comment]
Yeah, I'm afraid I haven't been able to update the code yet. Things in other projects have kept me tied up for a while. Fortunately, I'm hoping to move back into working on Gophish very soon.

For now, I'm going to go ahead and close this one out as a duplicate and we can work through #534 until we get it resolved 😄
