### ISSUE TITLE
links in email are getting stripped

### ISSUE THREAD

**Issue by morird74** [gophish/gophish#582]
I'm a bit of a newbie to this, but seemed to get everything setup fine from the start and sending test phishing emails.. The issue I am not having is all of a sudden, the links in the email's I send out are stripped. There is nothing to click. I tried creating different campaigns, tried sending to different email addresses, tried different email templates, even installed gophish on a different server.. still nothing. The only thing that has stayed constant is the email address I use to generate the phishing emails.. It is a gmail address. Is it possible that gmail is stripping the links? I don't know what else it could be.

**Comment by S0larflare** [comment]
If you view the source of the email that you receive, what do you see? 

Do all links get removed, or just the ones to the phishing server itself - i.e. {{.URL}}

Have you tried something simple like a link to google?

**Comment by morird74** [comment]
I figured out the issue.. I mistakenly stopped adding "http://" on the URL campaign field in-front of the IP address... which makes it not a link... Sorry about that, thank you for the quick response.
