### ISSUE TITLE
gophish crashing on html template 

### ISSUE THREAD

**Issue by raviteja7** [gophish/gophish#584]
Hello,
I built gophish from source. When I imported the site for the landing page, I am getting this error when clicked on the link after launching the campaign
 2017/04/04 14:28:35 route.go:246: template: html_template:201: unexpected "!" in command
2017/04/04 14:28:35 http: panic serving <redacted IP>: runtime error: invalid memory address or nil pointe                 r dereference
goroutine 12513 [running]:
net/http.(*conn).serve.func1(0xc420098640)
        /usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x9ec640, 0xf0f150)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
html/template.(*Template).escape(0x0, 0x0, 0x0)
        /usr/local/go/src/html/template/template.go:94 +0x38
html/template.(*Template).Execute(0x0, 0xf20720, 0xc420186460, 0xa16de0, 0xc420bed080, 0xc4205b1260, 0x7)
        /usr/local/go/src/html/template/template.go:117 +0x2f

Thanks

**Comment by jordan-wright** [comment]
It looks like the HTML contains some markup that Gophish thinks are template variables. Look for any instances of `{{` that are not your template variables, remove them, and see if the landing page still looks the way you expect it to look.

**Comment by jordan-wright** [comment]
Since there hasn't been any updates on this one in nearly 2 months, I'm going to close it out.

@raviteja7 if you are still having issues, let us know and we can re-open.
