### ISSUE TITLE
No tracking of user clicking on landing page.

### ISSUE THREAD

**Issue by krasian** [gophish/gophish#585]
I have 0.3-dev.  When I set up everything and run a campaign, it does not record users clicking on it.  Originally, in the email template I created, I had the CLICK HERE set to a hyperlink of {{.URL}} and 'Add Tracking Image' checked.

When users received the email, the {{.URL}} went to http://www.sophos.com instead of getting the actual landing page (which was imported from a Sophos email appliance login page but with the images inline).

I then replaced the hyperlink with the URL to a static page in the /static/ directory.  The users now see the correct page, but in both situations, neither showed a user actually clicking on the CLICK HERE in the email.

The results.csv shows (for both instances, but the ID different):
     **id,email,first_name,last_name,position,status,ip,latitude,longitude
     qhbFoJm,user1@xxx.com,First,Last,,Email Sent,,0,0
     wcVcVaJ,user2@xxx.com,First,Last,,Email Sent,,0,0**
In both instances, user1 clicked on the email link and the results.csv was after the user clicked.

Why am I not showing the info that the user clicked on the link?

**Comment by jordan-wright** [comment]
It sounds like the links are being re-written by a Sophos spam filter. Linking to a static page won't work because we don't track visits to static pages (and we won't be able to add this functionality due to the way the link tracking works).

The solution would be to whitelist emails from your Gophish IP address from the link rewriting in the Sophos appliance.

**Comment by krasian** [comment]
This shouldn't be closed.  The user1 email address is gmail.  Google does not use Sophos.

**Comment by jordan-wright** [comment]
@krasian,

> Google does not use Sophos.

Neither does Gophish. 😉  It sounds like maybe you put sophos.com in the URL field when making the campaign? I'm guessing the link to sophos.com probably ended with `?rid=1234567` or similar?

If so, you'll need to use the IP address or domain name that points to your Gophish phishing server, as we show in [the User Guide](https://gophish.gitbooks.io/user-guide/content/campaign/launching_the_campaign.html)

Note: For future reference, don't worry if I close out an issue. It's not a permanent action and it's not personal. Projects like gophish have _hundreds_ of issues come through and many of them have similar symptoms.

So, if an issue doesn't appear to be related to Gophish, or I feel I've answered the question, I'll close it out to avoid having issues stack up with no further response. Worst case, we realize it wasn't the right answer and re-open- no problem.

**Comment by krasian** [comment]
I don't know what caused the URL to be swapped.  It eventually worked when
I reinstalled everything except the DB.  The problem with the tracking was
a DOH -read the manual more thoroughly problem.  Please leave the ticket
closed!  Thank you!
