### ISSUE TITLE
Linux Daemon

### ISSUE THREAD

**Issue by doktor1360** [gophish/gophish#586]
Knowing this issue (#337) is closed, however I thought I'd add this; not perfect by any means but works like a champ...
file : /etc/init.d/gophish

<pre>
##!/bin/bash
# /etc/init.d/gophish
# initialization file for stop/start of gophish application server
#
# chkconfig: - 64 36
# description: stops/starts gophish application server
# processname:gophish
# config:/opt/goapps/src/github.com/gophish/gophish/config.json

# define script variables

processName=Gophish
process=gophish
appDirectory=/opt/goapps/src/github.com/gophish/gophish
logfile=/var/log/gophish/gophish.log
errfile=/var/log/gophish/gophish.error

start() {
    echo 'Starting '${processName}'...'
    cd ${appDirectory}
    nohup ./$process >>$logfile 2>>$errfile &
    sleep 1
}

stop() {
    echo 'Stopping '${processName}'...'
    pid=$(/usr/sbin/pidof ${process})
    kill ${pid}
    sleep 1 
}

status() {
    pid=$(/usr/sbin/pidof ${process})
    if [[ "$pid" != "" ]]; then
        echo ${processName}' is running...'
    else
        echo $processName' is not running...'
    fi
}

case $1 in
    start|stop|status) "$1" ;;
esac

</pre>

Hopefully this helps someone out...

**Comment by jordan-wright** [comment]
Excellent, thanks @doktor1360! I've gone ahead and added this to the User Guide.

Thanks again for sending this over!

**Comment by KhasMek** [comment]
This is really handy, thank you for posting it. I do have one nitpick however.

line 1
```
##!/bin/bash
```
really needs to be
```
#!/bin/bash
```
Otherwise the interpreter isn't invoked properly and the system returns a Exec format error.

**Comment by doktor1360** [comment]
Updated the comment - must have been a copy/paste error, wasn't actually in the script - however, agreed... it won't work bash won't like it all like that...

Thx @KhasMek for spotting it!

**Comment by ironc0in** [comment]
Can someone plz post equivalent commands for **Ubuntu**?

**Comment by S0larflare** [comment]
This is a bash script, should be fine in Ubuntu

**Comment by dudsan** [comment]
Thank you for posting this!

I've used your script as a starting point to set up a systemd .service unit and I thought I could pay back by posting it here.

file: /lib/systemd/system/gophish.service
```
[Unit]
Description=Gophish service
After=network-online.target

[Service]
Environment="GOPHISH_BIN_PATH=/opt/gophish/"
Environment="GOPHISH_LOG_PATH=/var/log/"
ExecStart=/bin/bash /root/gophish.sh
RestartSec=1
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

file: /root/gophish.sh
```
#!/bin/bash

GOPHISH_LOG_FILE=gophish.log
GOPHISH_ERR_FILE=gophish.err

check_bin_path() {
    if [[ -z "$GOPHISH_BIN_PATH" ]]; then
        exit 1
    fi
}

check_log_path() {
    if [[ -z "$GOPHISH_LOG_PATH" ]]; then
        exit 2
    fi
}

create_new_log_err() {
    GOPHISH_STAMP=`date +%Y%m%d%H%M%S-%N`
    if [[ -e $GOPHISH_LOG_PATH$GOPHISH_LOG_FILE ]]; then
        mv $GOPHISH_LOG_PATH$GOPHISH_LOG_FILE $GOPHISH_LOG_PATH$GOPHISH_LOG_FILE-$GOPHISH_STAMP
    fi
    
    if [[ -e $GOPHISH_LOG_PATH$GOPHISH_ERR_FILE ]]; then
        mv $GOPHISH_LOG_PATH$GOPHISH_ERR_FILE $GOPHISH_LOG_PATH$GOPHISH_ERR_FILE-$GOPHISH_STAMP
    fi
    
    touch $GOPHISH_LOG_PATH$GOPHISH_LOG_FILE
    touch $GOPHISH_LOG_PATH$GOPHISH_ERR_FILE
}

launch_gophish() {
    cd $GOPHISH_BIN_PATH
    ./gophish >> $GOPHISH_LOG_PATH$GOPHISH_LOG_FILE 2>> $GOPHISH_LOG_PATH$GOPHISH_ERR_FILE
}

check_bin_path
check_log_path
create_new_log_err
launch_gophish
```

After everything is in place # chmod +x /root/gophish.sh, then # systemctl daemon-reload. After this use # systemctl normally to start/status/stop/etc. gophish. This will create/stamp separate logs each time the service (re)starts and continuously check for exits on failure in order to restart it.

**Comment by Rzqu** [comment]
@doktor1360 Hi, for some reason when i try to use your code it returns an error with syntax for a *(*, Im using a TurnKey Linux distro based on debian, not sure if that makes a difference or not?

**Comment by jaredsiegel** [comment]
@dudsan Your instructions worked for me on Ubuntu 16.04.05. Thank you.

**Comment by anshu300** [comment]
anyone can you make video step by step

**Comment by gremaudc** [comment]
In most distribution, pidof tool is in the PATH. I think it is better to simply use "pidof" command in the script instead of specify full path.

**Comment by longshanks24** [comment]
I'm running into "service gophish does not support chkconfig" and wondering if someone can point me in the right direction.  Fairly new to Linux so this is hurting my brain.  I'm following the guide I found [here](https://airwalkconsulting.com/phishing-with-gophish-on-aws/).  When I get to the steps that call for "sudo chkconfig gophish on" the not supported chkconfig pops up.    I copied and pasted the script from the guide, which was copied and edited based on install location from here.  Hoping someone can shed light on what I'm doing wrong.

**Comment by doktor1360** [comment]
@longshanks24 - that guide appears to skip over and omit a coupa important commands. The 'chkconfig' command needs to 'add' the service and then set the run 'levels' before turning it 'on' if I'm reading all this correctly. Have a quick look at what I did - it's in the notes in the script at the top of this post...

However, as always:
[Standard Mgmt Disclaimer] - "_Your actual mileage may vary..._"

**Comment by jfarl** [comment]
> I'm running into "service gophish does not support chkconfig" and wondering if someone can point me in the right direction. Fairly new to Linux so this is hurting my brain. I'm following the guide I found [here](https://airwalkconsulting.com/phishing-with-gophish-on-aws/). When I get to the steps that call for "sudo chkconfig gophish on" the not supported chkconfig pops up. I copied and pasted the script from the guide, which was copied and edited based on install location from here. Hoping someone can shed light on what I'm doing wrong.

Try copying the script from this page instead of the linked article.

**Comment by olliewen** [comment]
> @dudsan Thank you for the systemd version. Most critically for any of this to work for me I needed to enable this to run on reboot (which is the entire point for me). `sudo systemctl enable gophish.service`
> 
> Also for me (running the AWS Ubuntu 18.04 AMI the default install was NOT /opt/gophish - so it was important to change the path to the gophish binary to in the file /lib/systemd/system/gophish.service to: `[Service]` `Environment="GOPHISH_BIN_PATH=go/src/github.com/gophish/gophis"`
> 
> Thank you @doktor1360 for getting this party started. Sorry for posting to closed topic but the "enable" command is just too important to not say something

You just need to change the comments in the /etc/init.d to this

```bash
#!/bin/bash
### BEGIN INIT INFO
# Provides:          gophish
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Starts GoPhish
### END INIT INFO
```

**Comment by aukhan288** [comment]
Is that possible to run gophish without command? like another web application

**Comment by Shakura8** [comment]
update, works even on new version of linux 24.04. 
If someone have issues with it . just pay attention to the bin Path .
for me it is :
Environment="GOPHISH_BIN_PATH=/opt/gophish/gophish/"
