### ISSUE TITLE
Fix Mobile Nav Dropdown Button

### ISSUE THREAD

**Issue by jordan-wright** [gophish/gophish#59]
On the webpage, the bootstrap dropdown button isn't showing up for mobile devices.

**Comment by StrangeUSB** [comment]
Hey, you should be able to add this to your CSS:
```
.icon-bar {
	background-color: #FFF;
}
```

**Comment by jordan-wright** [comment]
Closed via c1c8355a0d88a3aa960cff0758b3f976be68c1af.
