### ISSUE TITLE
Error when trying the branch attachment-support

### ISSUE THREAD

**Issue by Mlb66** [gophish/gophish#591]
Hello,
I'm interested by the implementation of the branch attachment-support, so I built the gophish branch for this function.
I had to remove a file gophish.go in the worker directory but otherwise the building ended ok.

When I execute the binary (I only updated the config.json for the admin server to be available on all interfaces), if I try and go to the admin page, I land on the error "Connection reset" on the browser. On the server I have the error (more in the pastebin) 2017/04/11 10:52:22 http: panic serving X.X.X.X:62919: interface conversion: interface {} is nil, not *sessions.Session
goroutine 34 [running]:
net/http.(*conn).serve.func1(0xc4200bba40)
        /usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x9db0c0, 0xc42011cf40)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf 

https://pastebin.com/DHVYgwTv

Do you have an idea of what went wrong ?

PS : Thanks for this great project... it's really useful for me

**Comment by Mlb66** [comment]
Hello again,
To solve this, I cloned the master branch and applied the changes in the commit of the #260 issue.
I managed to compile the result, i'm currently trying to use the attachment feature.

**Comment by RobinXaXa** [comment]
Hey,
I have the same issue,
how did you manage to get this version working exactly?

**Comment by Mlb66** [comment]
I took the current version of the branch master, and manually edited the 9 files indicated in #260.
I have an issue now when creating the template, the file *.auto are not automatically attached in the end. I have to look to the template html and js to see what's wrong now.

**Comment by RobinXaXa** [comment]
Okay I kinda did the same thing with the git commands
first git clone 'master'
and then
git merge origin/sttachment support

I now have the same issue than you,
I guess it's due to gophish version 0.3 
the last commit for attachment-support was 8 months ago i guess there must be some kind of conflict..

**Comment by Mlb66** [comment]
Managed it... The template.js that needs updating is the template.min.js in
/static/dist/app/

**Comment by RobinXaXa** [comment]
yup seen that:
here are all the conflicts that occurs when you merge attachement support to master:

```
/data/gophish# git status
On branch master
Your branch is up-to-date with 'origin/master'.

You have unmerged paths.
  (fix conflicts and run "git commit")

Changes to be committed:

        new file:   b.doc
        modified:   models/models.go
        new file:   static/db/PRgmoeW1
        modified:   worker/worker.go

Unmerged paths:
  (use "git add <file>..." to mark resolution)

        both modified:      controllers/route.go
        both modified:      static/js/src/app/campaign_results.js
        both modified:      static/js/src/app/templates.js
        both modified:      templates/templates.html
        both modified:      util/util.go

```
you might want to look into the others files :)

**Comment by Mlb66** [comment]
I did all the modifications by hand (the 2 js files just this morning in their min version) and it seems to work fine (I have tested it with the html attachment).

**Comment by RobinXaXa** [comment]
can you specify what changes did you added in the .js min version?
it would be greatly appreciated ! :)

**Comment by Mlb66** [comment]
for the min version, I copied/pasted the code of the normal js in a minifier (I used http://fmarcia.info/jsmin/test.html) and replaced the contents of the min files with the results.

**Comment by Mlb66** [comment]
@RobinXaXa : did you manage to compile the merged code ?

**Comment by jordan-wright** [comment]
To minify the code, I recommend setting up `gulp`. Then, you can `npm install --save-dev` to install the dependencies. Finally, when you want to minify the code, you can run `gulp build`.

**Comment by RobinXaXa** [comment]
Hey there,

I couldn't get my hands on  gophish last week,

This is where I am this morning:

- I git cloned the lattest version of Gophish
- I modified the files listed [here](https://github.com/gophish/gophish/commit/5eb1c3565dafb3595c8dd98db77b92ed1e122a09)
- then I ran a gulp build from the /static/js/src/app folder

- finaly i "go build" this version of Gophish.

Now i recieve Gophish's mails with the two attachements:
-a.html.auto
-b.doc.auto
However their size is 0 octet
I don't know why exactly, b.doc is in my main gophish folder..

While typing this i realized that there is a file i didn't modified but which is quoted on the attachement-support commit: static/db/PRgmoeW1

I don't know if it's revalent but i'll need some time to investigate!

**Comment by jordan-wright** [comment]
Going ahead and closing this since there hasn't been any updates in over a year. As a general note, any bugs with branches should be added as comments to that branch. That way, the author can see them and reply directly.

Thanks for getting in touch!
