### ISSUE TITLE
Auto-generating camapigns with the python client

### ISSUE THREAD

**Issue by RobinXaXa** [gophish/gophish#592]
Hi guys,

i'm currently attemting to automate the creation of severals campaigns via the python api client:

Here's to script i came up with so far:
basicly: 
- it makes you select which groups you want to send phishing to
    *it first create a list of selected groups like ['test0','test1',...]
    * and thenit create another list that create the [Group(name = test0... ]

- We want to create 1 campain per group with different senders/landing pages etc..
- to achieve this goal we create lists for each category (smtp,page,template) containing all of our configured items
- in the end, we randomly affect a template sender,landing page to a group and create the campaign

but I end up with the api returning the following error:

  File "campagneauto.py", line 176, in AjoutCampagneFullAuto
    campaign = api.campaigns.post(campaign)
  File "/usr/local/lib/python2.7/dist-packages/gophish/api/campaigns.py", line 21, in post
    return super(API, self).post(campaign)
  File "/usr/local/lib/python2.7/dist-packages/gophish/api/api.py", line 60, in post
    response = self.api.execute("POST", self.endpoint, json=(resource.as_dict()))
  File "/usr/local/lib/python2.7/dist-packages/gophish/models.py", line 24, in as_dict
    val = val.as_dict()
  File "/usr/local/lib/python2.7/dist-packages/gophish/models.py", line 24, in as_dict
    val = val.as_dict()
AttributeError: 'unicode' object has no attribute 'as_dict'

I tried to look into it but I can't find what's wrong :/
Does anyone have an idea ? :)

Best regards,
Robin

```
#Selecting groups
groups=[]
                print "Here is the list of existing groups: "
                ListeGroupe() #function to list all groups

                groupselec = []
                nbgrpman = raw_input("how many groups do you want to select ?: ")

                for i in range(int(nbgrpman)):
                        g = raw_input("Which group do you want to select?: ")
                        groupselec.append(g)
               
                for i in range(int(nbgrpman)):
                        groups.append([Group(name=groupselec[i])])
  
 #Selecting Senders (all by default)
        senders = []
        for smtp in api.smtp.get():
                senders.append(SMTP(name = smtp.name))

        #Slecting Templates (all by default)
        templates = []
        for template in api.templates.get():
                templates.append(Template(name = template.name))

        #Landing pages Slection
        parking = []
        for pages in api.pages.get():
                parking.append(Page(name = pages.name))

        urlph = raw_input("Please enter your tracking URL: ")

        for i in range(len(groups)):
                groupe = groups[i]
                print "groupe: ",groupe
                name = "test" + str(i)
                print name
                sender = random.choice(senders)
                print "Sender: ",sender
                template = random.choice(templates)
                print "Template: ",template
                garage = random.choice(parking)
                print "page parking: ",garage

                campaign  = Campaign(name=name, groups=groupe, page=garage,template=template, profile=sender, url=urlph)
                print "objet créé"
                campaign = api.campaigns.post(campaign)
                print campaign.id
```

**Comment by S0larflare** [comment]
I take it you got this one fixed? Anything that might help people in the future?

Sent from my iPhone

On 11 Apr 2017, at 15:55, RobinXaXa <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #592<https://github.com/gophish/gophish/issues/592>.

**Comment by RobinXaXa** [comment]
Hey,

Sorry it was a bit hars to close it with no indications

yup, i got it fixed, apparently :
```
        senders = []
        for smtp in api.smtp.get():
                senders.append(SMTP(name = smtp.name))
```
is not the way to go, i guess appending directly smtp.name created an unicode string or something like that :/

here's the fully functionning function :)
comments in french sorry, I don't have the time to change them back
```
   232  def AjoutCampagneFullAuto():
   233          #Selection des groupes
   234          print "Nous allons commencer par selectionner les groupes auquels les mails seront envoyés:"
   235          ch = raw_input("voulez vous utiliser des groupes existants, ou créer automatiquement des groupes ? 0 ou 1: ")
   236          if ch == '0':
   237                  groups=[]
   238                  print "voici la liste des groupes existants: "
   239                  ListeGroupe()
   240                  groupselec = []
   241                  nbgrpman = raw_input("combien de groupes voulez-vous selectionner ?: ")
   242                  for i in range(int(nbgrpman)):
   243                          g = raw_input("veuillez entrer le nom du groupe a ajouter: ")
   244                          groupselec.append(g)
   245
   246                  for i in range(int(nbgrpman)):
   247                          groups.append([Group(name=groupselec[i])])
   248
   249          elif ch == '1':
   250                  groups = imp_grp_pos()
   251
   252          print ""
   253          print "groupes choisis"
   254          print "===================================================================================="
   255
   256
   257          #initialisation de la table de dates
   258          datecamp = []
   259          print ("Veuillez saisir le chemin absolu de votre fichier de dates. pour la campagne en cours votre fichier doit contenir: ",len(groups), " dates.")
   260          dates = raw_input("fichier?: ")
   261          f = open(dates,'r')
   262          for i in f.readlines():
   263                  datecamp.append(i.rstrip())
   264          datecamp.remove ('')
   265
   266          #Selection des Senders (tous par default)
   267          senders = []
   268          for smtp in api.smtp.get():
   269                  senders.append(smtp.name)
   270
   271          #Selection des Templates (tous par default)
   272          templates = []
   273          for template in api.templates.get():
   274                  templates.append(template.name)
   275
   276          #Selection des pages de parking
   277          parking = []
   278          for pages in api.pages.get():
   279                  parking.append(pages.name)
   280
   281          urlph = raw_input("Veuillez saisir l'adresse du tracker gophish: ")
   282
   283          for i in range(len(groups)):
   284                  print "Voici les element de la campagne: "
   285
   286                  name = "test" + str(i)
   287                  print "le nom de la campagne est: ",name
   288
   289                  date = datecamp[i]
   290                  print "date: ", date
   291
   292                  groupe = groups[i]
   293                  print "groupe: ",groupe
   294
   295                  sender0 = str(random.choice(senders))
   296                  print "l'emmeteur des mails sera: ",sender0
   297                  sender = SMTP(name=sender0)
   298
   299                  template0 = str(random.choice(templates))
   300                  print "le template utilisé pour cette campagne est: ",  template0
   301                  template = Template(name=template0)
   302
   303                  garage0 = str(random.choice(parking))
   304                  print "la page de parking utilisée pour cette campagne est: ",garage0
   305                  garage = Page(name=garage0)
   306
   307
   308                  print "l'url de tracking est: ",urlph
   309
   310                  print ""
   311                  print ""
   312                  campaign  = Campaign(name=name, groups=groupe, page=garage,template=template, smtp=sender, url=urlph, launch_date=date)
   313                  campaign = api.campaigns.post(campaign)
```

**Comment by Sun-098** [comment]
Hi RobinXaXa ,
I tried the above code it executes without any error but the new campaign is not launched and instead of all the random choices I used the user's input
@RobinXaXa

**Comment by RobinXaXa** [comment]
Hey sun-098

This code is kinda old, 
Tout can checker m'y profile and look up for m'y gophish controller script, I'll open a wiki soon  for documentation but it works outil of the box 
Comments in the code are in french I'll try to upgrade this soon 

Feel free to open an issue on the repo I'll give you a reponse asap

**Comment by RobinXaXa** [comment]
Sorry for the typo, typing in the streets aint easy haha

**Comment by Sun-098** [comment]
Hi @RobinXaXa ,
I get the below error
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\code\code.py", line 660, in <module>
    main()
  File "C:\Users\Administrator\Desktop\code\code.py", line 565, in main
    ListeCampagne()
  File "C:\Users\Administrator\Desktop\code\code.py", line 29, in ListeCampagne
    for campaign in api.campaigns.get():
TypeError: 'Error' object is not iterable

**Comment by RobinXaXa** [comment]
Hmm that's weird, I can't reproduce this error.

did you set up your api key and gophish host properly in gophish.ini ?

**Comment by RobinXaXa** [comment]
![image](https://user-images.githubusercontent.com/23464278/28462810-3d33fbba-6e1d-11e7-96a8-5752cb022f8e.png)

**Comment by RobinXaXa** [comment]
I reproduced this error by entering a wrog API key in gophish.ini

```
Votre choix?: 1
Traceback (most recent call last):
  File "Gophish-Controller.py", line 657, in <module>
    main()
  File "Gophish-Controller.py", line 562, in main
    ListeCampagne()
  File "Gophish-Controller.py", line 26, in ListeCampagne
    for campaign in api.campaigns.get():
TypeError: 'Error' object is not iterable
```

**Comment by Sun-098** [comment]
Hi RobinXaXa,

Thanks a lot! It works but Is there a way to choose my own groups I need instead of the random ones or even if it is random I want to choose random people in the imported csv. Is that possible?

**Comment by RobinXaXa** [comment]
I'm not sure of what you mean, so i'll try to give you an answer 

When a campaign is created bythe script, a set of parameters are imported, the script is fetching all the groups that are present in gophish with theses lines:

```
	groupselect = []
	for groups in api.groups.get():
		groupselect.append(str(groups.name))
```
when i created this script i went with: 1 group = 1 campaign,
so the campaigns process iterates trough all groups and create 1 campaign per group.

if you want to choose which user is in which group you will need to edit Gophish.ini
```
[Groups]
attr_grp: random
Nb_groups: 1
```
and create multiple csvs with the user you want

--
Robin

**Comment by Sun-098** [comment]
Thank you i will work on that

Regards,

Sunmadhy Soundararajan

**Comment by Sun-098** [comment]
@RobinXaXa
Error->  Invalid JSON structure

**Comment by RobinXaXa** [comment]
can you give me some context ?

**Comment by Sun-098** [comment]
I had changed it to random in groups[ ]
And number of groups as 1. While creating campaigns  i give the name of
groups just like pages and sender but it throws back this error
Regards,

Sunmadhy Soundararajan

**Comment by RobinXaXa** [comment]
this error occur while group creation or campaign creation ?

**Comment by Sun-098** [comment]
Whole campaign creation if I want to give a group to send

Regards,

Sunmadhy Soundararajan

**Comment by RobinXaXa** [comment]
which campaign mode are you using ?
in manual mode i got this

![image](https://user-images.githubusercontent.com/23464278/28490406-a0db2884-6ed9-11e7-8d58-e495322ea319.png)

auto mode is working fine for me too

did you modify the code in campaign creation ?

**Comment by Sun-098** [comment]
I use manual mode. Yes I did change the code but it's just that for user to
enter their preferable group instead of random selection

Regards,

Sunmadhy Soundararajan

**Comment by RobinXaXa** [comment]
I need to know what you changed exactly if you want me to help you :)

**Comment by RobinXaXa** [comment]
in my opinion if you want to do this is to change in 

`def Ajout_Campagne_Manuel(options):`

there is a line:

`groupe = [Group(name=options[4][i])]`

replace it by:
```
print options[4]
groupe0 = raw_input("groupe to select: ")
groupe = [Group(name=groupe0)]
```
and it should be fine

**Comment by RobinXaXa** [comment]
![image](https://user-images.githubusercontent.com/23464278/28490477-435746a0-6edb-11e7-84a9-9b08a351a01a.png)

**Comment by Sun-098** [comment]
Yes I did the same changes in code but it shows and get the  error

Regards,

Sunmadhy Soundararajan

**Comment by RobinXaXa** [comment]
can you post a screenshot as i did ?

**Comment by Sun-098** [comment]
![img_20170722_164129477](https://user-images.githubusercontent.com/30150173/28490736-18e814de-6eff-11e7-8a9e-d27e5311055f.jpg)
Hi Robin

**Comment by RobinXaXa** [comment]
Send me your script and i'll check what's wrong

**Comment by Sun-098** [comment]
Hi @RobinXaXa,
Sorry for the very late reply due to bad internet connection
Here is the screenshot...
![image](https://user-images.githubusercontent.com/30150173/28508411-42ac032a-7058-11e7-8a34-5d59734728b7.png)

**Comment by Sun-098** [comment]
Hi @RobinXaXa 
Got it I had to use the group id to give the group I required
So my code goes like this
		n = raw_input("Please enter the group that will be associated with the campaign: ")
		n=int(n)
		groupe = [Group(name=options[4][n])]

**Comment by Sun-098** [comment]
Thanks @RobinXaXa for sharing.
You have solved my biggest issue of the month

**Comment by RobinXaXa** [comment]
oh yeah, yo need to enter the group name sorry :)

glad you got it fixed, If need need further help don't hesitate to open an issue on my repo, i4m looking for improovments to do to my script
