### ISSUE TITLE
Timeout loading campaign

### ISSUE THREAD

**Issue by krasian** [gophish/gophish#593]
I have a campaign that has over 2000 users.  When I go into the results, my browser consistently becomes unresponsive.  I am using 0.3.  I have tried:

host - Firefox 45.8.0
remote - IE 11.953.149393.0
remote - Edge 38.14393.0.0
remote - Firefox 52.0.2 (64-bit)
remote - Chrome 57.0.2987.133 (64-bit)

Firefox 52.0.2 on remote consistently gives me the same "Warning: Unresponsive script" message saying...
```
A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

Script: http://<hostname hidden>:3333/js/dist/vendor.min.js:1
```
Sometimes, if I click continue with the unresponsive script, it will eventually completely load (pointer back to an arrow and not 'waiting').  Other times, it never finishes.  Majority of all the times, it will show the first page of 10 in the background.

Is there a workaround?  Something I did wrong?  Any way to get the data?

**Comment by jordan-wright** [comment]
This is a known issue with large campaigns. We rolled out a temporary fix recently that increases the polling interval.

You can build from source to apply this change- let me know if that doesn't help!

**Comment by krasian** [comment]
Thank you!  Just tested and verified that this did resolve my problem!  Keep up the great work!
