### ISSUE TITLE
404 Error when hitting link to landing page

### ISSUE THREAD

**Issue by Cryptowave** [gophish/gophish#594]
Been working at this for a while I have the following configurations set up: 

Host = Ubuntu 14.04 LTS hosted in EC2
Security rules allow HTTPS and HTTP access from any source 

Email template works just fine {{.FirstName}} parameter is correct and displays proper first name. Please <a href="{{.URL}}">Click Here</a> to continue to the survey! displays a link titled click here, however this link leads to a 404 page with the proper IP of the server and an rid=values. 

I've verified Firewall rules are not causing the issue, disabled both EC2 and local box security settings to troubleshoot that. 

Verified my config was listening on port 80, currently 0.0.0.0:80.

Browsing to <myip>:80 when the campaign is not running yields a 404 error as well.

Splash page does not have any configurations enabled that would block access/cause issues there. 

Unsure why I'm getting these 404 errors, cannot track down to a problem locally. Emails are sending normally, email structure is functioning as expected, reporting in GoPhish is running properly, nothing appears to be wrong, at least within my knowledge level. 

Output from the console when I hit the link is here:
main.go:729: sql/home/gophish/go-project/src/github.com/gophish/gophish/models/campaign.go:144180.497µsINSERT INTO "events" ("campaign_id","email","time","message","details") VALUES (?,?,?,?,?)[8 <myemailaddress> 2017-04-17 23:04:27.965935246 +0000 UTC Clicked Link {"payload":{"rid":["PpAYbDQ"]},"browser":{"address":"<mypublicIP>","user-agent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"}}]
 2017/04/17 23:04:27 route.go:268: html/template:html_template: "<" in attribute name: " <=\"\" td=\"\">\n                </a"
204.115.117.128 - - [17/Apr/2017:23:04:27 +0000] "GET /?rid=PpAYbDQ HTTP/1.1" 404 19 "" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"

**Comment by jordan-wright** [comment]
Looks like there might be an issue with your landing page template. Search for {{ and see if there are any uses that are not related to Gophish. The last log line gives more information that may be helpful.

**Comment by Cryptowave** [comment]
Thanks for the quick response. I was able to scrape another page and get it working, didn't occur to me to try that initially. Looks like the issue is on my end with that page.
