### ISSUE TITLE
Import emails

### ISSUE THREAD

**Issue by Raytri3** [gophish/gophish#595]
I was configuring a lot of emails this evening and noticed a weird problem - if I was successful and the email template was imported successfully, on the next import the import screen would be clear; however, if for any reason I didn't complete the first import (e.g. not liking the way it looks) then when I went to do another one the last import was still there (As if it never cleared). This meant I had to delete it manually -not a big deal but worth noting. I would like to see one of 2 things: 1. a clear button on the email import screen or 2. functionality that clears the import window when a template errors out or is cancelled.

**Comment by jordan-wright** [comment]
Yeah, I've seen this before and it's just been too low priority to fix. I'll spend some time and knock this out - I know it can be inconvenient.

Sorry for the hassle. Thanks for reporting this!

**Comment by Raytri3** [comment]
thanks - you are doing great work. A simple (don't know how simple it
really is) "clear" button would be good.  One other feature that would be
helpful is to have more "template" items ( e.g. {{.FirstName}} ) or allow
us to customize them.

**Comment by n838901** [comment]
I can't get mine to import any emails.  I can copy/paste the source into the dialog but nothing happens.  I've tried various emails to see if that was the problem, but they all give the same result.

**Comment by jordan-wright** [comment]
Just a heads up, this was fixed as of ac3fe6aeae6cc0638bab1ede646e70328d8a85b4. Let me know if you run into any issues!
