### ISSUE TITLE
404 page not found when launching a campaign

### ISSUE THREAD

**Issue by j4schur** [gophish/gophish#596]
So I've read through most of the issues that other people have been having and I'm still getting the 404 page not found.  I've made sure there wasn't a firewall or port issue.  I'm spun up a simple python HTTP server to server out and I have no problem seeing that. I've created a simple landing page that just says Hello World and still nothing. I'm at a loss on what to look for next.  I'm running GoPhish on RHEL 7 load within AWS. 

`173.67.24.74 - - [18/Apr/2017:16:12:56 -0400] "GET /js/dist/app/campaign_results.min.js HTTP/2.0" 200 3887 "https://x.x.x.x:3333/campaigns/4" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
173.67.24.74 - - [18/Apr/2017:16:12:56 -0400] "GET /api/campaigns/4/results?api_key=12345{} HTTP/2.0" 200 267 "https://x.x.x.x:3333/campaigns/4" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
173.67.24.74 - - [18/Apr/2017:16:13:06 -0400] "GET /api/campaigns/4/results?api_key=12345{} HTTP/2.0" 200 267 "https://x.x.x.x:3333/campaigns/4" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
 2017/04/18 16:13:12 campaign.go:340: Found 1 Campaigns to run
 2017/04/18 16:13:12 worker.go:53: Worker received: test
 2017/04/18 16:13:13 worker.go:170: Creating email using template
 2017/04/18 16:13:13 worker.go:210: Sending Email to user@gmail.com
 2017/04/18 16:13:14 main.go:724: sql/go/src/github.com/gophish/gophish/models/campaign.go:144196.913µsINSERT INTO "events" ("campaign_id","email","time","message","details") VALUES (?,?,?,?,?)[4 user@gmail.com 2017-04-18 16:13:14.128718195 -0400 EDT Email Sent ]
173.67.24.74 - - [18/Apr/2017:16:13:17 -0400] "GET /api/campaigns/4/results?api_key=12345{} HTTP/2.0" 200 297 "https://x.x.x.x:3333/campaigns/4" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
173.67.24.74 - - [18/Apr/2017:16:13:26 -0400] "GET /api/campaigns/4/results?api_key=12345{} HTTP/2.0" 200 297 "https://x.x.x.x:3333/campaigns/4" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
173.67.24.74 - - [18/Apr/2017:16:13:36 -0400] "GET / HTTP/1.1" 404 43 "" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
173.67.24.74 - - [18/Apr/2017:16:13:36 -0400] "GET /api/campaigns/4/results?api_key=12345{} HTTP/2.0" 200 297 "https://x.x.x.x:3333/campaigns/4" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
173.67.24.74 - - [18/Apr/2017:16:13:47 -0400] "GET /api/campaigns/4/results?api_key=12345{} HTTP/2.0" 200 297 "https://x.x.x.x:3333/campaigns/4" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
`

**Comment by jordan-wright** [comment]
Looks like the email is sent ok. What are you using for the URL field? What link actually shows up in the email? Can you give an example of the email template you're using?

**Comment by j4schur** [comment]
I created a simple email template just to see if things were working.  Basically looked like this:

> Please reset your password, click [here](http://landingpage)

When I test it, I see the email but when I click on the click which points back to the public IP of my system.  I get the 404 page not found.

**Comment by S0larflare** [comment]
Is your link put in to the template as {{.URL}}?

Sent from my iPhone

On 19 Apr 2017, at 13:56, j4schur <notifications@github.com<mailto:notifications@github.com>> wrote:


I created a simple email template just to see if things were working. Basically looked like this:

Please reset your password, click here<http://landingpage>

When I test it, I see the email but when I click on the click which points back to the public IP of my system. I get the 404 page not found.

**Comment by j4schur** [comment]
Please disregard, it was a user error on my part.  Everything is working like a champ now.  
By the way, thank you for the quick support and the fantastic product.

**Comment by netstatmen** [comment]
Hi, could you explain how this issue was resolved? I'm currently stuck here, I'm putting {{.URL}} in the template with no luck. thanks

**Comment by jordan-wright** [comment]
Can you show us the template you're using? And what are you putting as the URL in your campaign?

Finally, do you see any errors in the terminal when you click the link in the email?

**Comment by netstatmen** [comment]
i have this error:
thanks for your help

 2017/09/19 19:37:36 worker.go:36: Background Worker Started Successfully - Waiting for Campaigns
goose: no migrations to run. current version: 20170219122503
 2017/09/19 19:37:36 gophish.go:83: Starting phishing server at http://192.168.1.67:80
 2017/09/19 19:37:36 gophish.go:66: Starting admin server at https://127.0.0.1:3333
127.0.0.1 - - [19/Sep/2017:19:37:38 -0700] "GET / HTTP/2.0" 302 53 "" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:37:38 -0700] "GET /login HTTP/2.0" 200 1062 "" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:37:38 -0700] "GET /images/logo_purple.png HTTP/2.0" 200 4735 "https://127.0.0.1:3333/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:37:38 -0700] "GET /css/dist/gophish.css HTTP/2.0" 200 50138 "https://127.0.0.1:3333/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:37:51 -0700] "POST /login HTTP/2.0" 302 23 "https://127.0.0.1:3333/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:37:51 -0700] "GET / HTTP/2.0" 200 1797 "https://127.0.0.1:3333/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:37:51 -0700] "GET /js/dist/app/dashboard.min.js HTTP/2.0" 200 1310 "https://127.0.0.1:3333/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:37:51 -0700] "GET /css/dist/gophish.css HTTP/2.0" 200 50138 "https://127.0.0.1:3333/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:37:51 -0700] "GET /api/campaigns/summary?api_key=91bd9b7de25f193b41385905d51dda235a047b7ddb372f8b66bd4533b5cebf7b&{} HTTP/2.0" 200 237 "https://127.0.0.1:3333/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:38:00 -0700] "GET /campaigns HTTP/2.0" 200 2456 "https://127.0.0.1:3333/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:38:00 -0700] "GET /js/dist/app/campaigns.min.js HTTP/2.0" 200 2188 "https://127.0.0.1:3333/campaigns" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:38:00 -0700] "GET /css/dist/gophish.css HTTP/2.0" 200 50138 "https://127.0.0.1:3333/campaigns" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:38:00 -0700] "GET /api/campaigns/summary?api_key=91bd9b7de25f193b41385905d51dda235a047b7ddb372f8b66bd4533b5cebf7b&{} HTTP/2.0" 200 237 "https://127.0.0.1:3333/campaigns" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:38:04 -0700] "GET /landing_pages HTTP/2.0" 200 2517 "https://127.0.0.1:3333/campaigns" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:38:04 -0700] "GET /css/dist/gophish.css HTTP/2.0" 200 50138 "https://127.0.0.1:3333/landing_pages" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:38:04 -0700] "GET /api/pages/?api_key=91bd9b7de25f193b41385905d51dda235a047b7ddb372f8b66bd4533b5cebf7b&{} HTTP/2.0" 200 93651 "https://127.0.0.1:3333/landing_pages" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:38:09 -0700] "GET /js/src/vendor/ckeditor/config.js?t=F0RD HTTP/2.0" 200 699 "https://127.0.0.1:3333/landing_pages" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:38:09 -0700] "GET /js/src/vendor/ckeditor/lang/en.js?t=F0RD HTTP/2.0" 200 3990 "https://127.0.0.1:3333/landing_pages" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:38:09 -0700] "GET /js/src/vendor/ckeditor/skins/bootstrapck/editor.css?t=F0RD HTTP/2.0" 200 5539 "https://127.0.0.1:3333/landing_pages" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:38:09 -0700] "GET /js/src/vendor/ckeditor/styles.js?t=F0RD HTTP/2.0" 200 1370 "https://127.0.0.1:3333/landing_pages" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:38:09 -0700] "GET /js/src/vendor/ckeditor/plugins/dialogadvtab/plugin.js?t=F0RD HTTP/2.0" 200 1512 "https://127.0.0.1:3333/landing_pages" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
 2017/09/19 19:38:36 campaign.go:340: Found 0 Campaigns to run
 2017/09/19 19:39:36 campaign.go:340: Found 0 Campaigns to run
127.0.0.1 - - [19/Sep/2017:19:40:04 -0700] "GET /landing_pages HTTP/2.0" 200 2522 "https://127.0.0.1:3333/campaigns" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:40:04 -0700] "GET /css/dist/gophish.css HTTP/2.0" 200 50138 "https://127.0.0.1:3333/landing_pages" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:40:04 -0700] "GET /api/pages/?api_key=91bd9b7de25f193b41385905d51dda235a047b7ddb372f8b66bd4533b5cebf7b&{} HTTP/2.0" 200 93651 "https://127.0.0.1:3333/landing_pages" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
 2017/09/19 19:40:12 main.go:724: sql/go/src/github.com/gophish/gophish/models/campaign.go:1441.0065msINSERT INTO "events" ("campaign_id","email","time","message","details") VALUES (?,?,?,?,?)[22 ned_00@hotmail.com 2017-09-19 19:40:12.7351224 -0700 MST Clicked Link {"payload":{"rid":["WlmtioU"]},"browser":{"address":"200.68.151.4","user-agent":"Mozilla/5.0 (Linux; Android 7.0) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/1.3 Chrome/60.0.3112.116 Mobile Safari/537.36"}}]
 2017/09/19 19:40:12 route.go:246: template: html_template:677: unexpected bad character U+003D '=' in command
2017/09/19 19:40:12 http: panic serving 200.68.151.4:45056: runtime error: invalid memory address or nil pointer dereference
goroutine 433 [running]:
net/http.(*conn).serve.func1(0xc042146a00)
        /usr/local/go/src/net/http/server.go:1721 +0xd7
panic(0x95e900, 0xd581e0)
        /usr/local/go/src/runtime/panic.go:489 +0x2dd
html/template.(*Template).escape(0x0, 0x0, 0x0)
        /usr/local/go/src/html/template/template.go:94 +0x3f
html/template.(*Template).Execute(0x0, 0xd2ad40, 0xc04214c8c0, 0x988d40, 0xc04244ac00, 0xc042253560, 0x7)
        /usr/local/go/src/html/template/template.go:117 +0x36
github.com/gophish/gophish/controllers.PhishHandler(0xd30c40, 0xc0421c2620, 0xc0422c6200)
        /go/src/github.com/gophish/gophish/controllers/route.go:266 +0xe0f
net/http.HandlerFunc.ServeHTTP(0xa0e160, 0xd30c40, 0xc0421c2620, 0xc0422c6200)
        /usr/local/go/src/net/http/server.go:1942 +0x4b
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0421bb3b0, 0xd30c40, 0xc0421c2620, 0xc0422c6200)
        /go/src/github.com/gorilla/mux/mux.go:114 +0x113
github.com/NYTimes/gziphandler.NewGzipLevelHandler.func1.1(0xfdc5f8, 0xc0422b8a20, 0xc042116000)
        /go/src/github.com/NYTimes/gziphandler/gzip.go:181 +0x164
net/http.HandlerFunc.ServeHTTP(0xc0421c2f20, 0xfdc5f8, 0xc0422b8a20, 0xc042116000)
        /usr/local/go/src/net/http/server.go:1942 +0x4b
github.com/gorilla/handlers.combinedLoggingHandler.ServeHTTP(0xd2c2c0, 0xc042004018, 0xd2d380, 0xc0421c2f20, 0xd31100, 0xc04223a2a0, 0xc042116000)
        /go/src/github.com/gorilla/handlers/handlers.go:77 +0x128
github.com/gorilla/handlers.(*combinedLoggingHandler).ServeHTTP(0xc0421c2f60, 0xd31100, 0xc04223a2a0, 0xc042116000)
        <autogenerated>:9 +0x8d
net/http.serverHandler.ServeHTTP(0xc0421ebb80, 0xd31100, 0xc04223a2a0, 0xc042116000)
        /usr/local/go/src/net/http/server.go:2568 +0x99
net/http.(*conn).serve(0xc042146a00, 0xd31880, 0xc0421ac800)
        /usr/local/go/src/net/http/server.go:1825 +0x619
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2668 +0x2d5
127.0.0.1 - - [19/Sep/2017:19:40:20 -0700] "GET /sending_profiles HTTP/2.0" 200 2637 "https://127.0.0.1:3333/landing_pages" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:40:20 -0700] "GET /js/dist/app/sending_profiles.min.js HTTP/2.0" 200 1934 "https://127.0.0.1:3333/sending_profiles" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:40:20 -0700] "GET /css/dist/gophish.css HTTP/2.0" 200 50138 "https://127.0.0.1:3333/sending_profiles" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:40:20 -0700] "GET /api/smtp/?api_key=91bd9b7de25f193b41385905d51dda235a047b7ddb372f8b66bd4533b5cebf7b&{} HTTP/2.0" 200 303 "https://127.0.0.1:3333/sending_profiles" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:40:22 -0700] "GET /landing_pages HTTP/2.0" 200 2519 "https://127.0.0.1:3333/sending_profiles" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:40:22 -0700] "GET /css/dist/gophish.css HTTP/2.0" 200 50138 "https://127.0.0.1:3333/landing_pages" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:40:23 -0700] "GET /api/pages/?api_key=91bd9b7de25f193b41385905d51dda235a047b7ddb372f8b66bd4533b5cebf7b&{} HTTP/2.0" 200 93651 "https://127.0.0.1:3333/landing_pages" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:40:26 -0700] "GET / HTTP/2.0" 200 1797 "https://127.0.0.1:3333/landing_pages" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:40:26 -0700] "GET /js/dist/app/dashboard.min.js HTTP/2.0" 200 1310 "https://127.0.0.1:3333/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:40:26 -0700] "GET /css/dist/gophish.css HTTP/2.0" 200 50138 "https://127.0.0.1:3333/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:40:26 -0700] "GET /api/campaigns/summary?api_key=91bd9b7de25f193b41385905d51dda235a047b7ddb372f8b66bd4533b5cebf7b&{} HTTP/2.0" 200 237 "https://127.0.0.1:3333/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:40:27 -0700] "GET /campaigns HTTP/2.0" 200 2454 "https://127.0.0.1:3333/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:40:27 -0700] "GET /js/dist/app/campaigns.min.js HTTP/2.0" 200 2188 "https://127.0.0.1:3333/campaigns" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:40:27 -0700] "GET /css/dist/gophish.css HTTP/2.0" 200 50138 "https://127.0.0.1:3333/campaigns" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:40:27 -0700] "GET /api/campaigns/summary?api_key=91bd9b7de25f193b41385905d51dda235a047b7ddb372f8b66bd4533b5cebf7b&{} HTTP/2.0" 200 237 "https://127.0.0.1:3333/campaigns" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
 2017/09/19 19:40:30 campaign.go:442: Deleting campaign 22
127.0.0.1 - - [19/Sep/2017:19:40:30 -0700] "DELETE /api/campaigns/22?api_key=91bd9b7de25f193b41385905d51dda235a047b7ddb372f8b66bd4533b5cebf7b HTTP/2.0" 200 98 "https://127.0.0.1:3333/campaigns" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:40:33 -0700] "GET /campaigns HTTP/2.0" 200 2454 "https://127.0.0.1:3333/campaigns" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:40:33 -0700] "GET /css/dist/gophish.css HTTP/2.0" 200 50138 "https://127.0.0.1:3333/campaigns" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [19/Sep/2017:19:40:33 -0700] "GET /api/campaigns/summary?api_key=91bd9b7de25f193b41385905d51dda235a047b7ddb372f8b66bd4533b5cebf7b&{} HTTP/2.0" 200 57 "https://127.0.0.1:3333/campaigns" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
 2017/09/19 19:40:36 campaign.go:340: Found 0 Campaigns to run

**Comment by jordan-wright** [comment]
It looks like theres an error in your landing page template. Specifically check out the error around the equals sign.

I'd look through the landing page for instances of {{ to see if you can find the offending template tag- it might be something buried in JavaScript or something.
