### ISSUE TITLE
need help with Campaign URL (newbie)

### ISSUE THREAD

**Issue by Noltje** [gophish/gophish#597]
Hi I am trying to set up a campaign to test gophish..
but I do not know what I am suppose to put as URL..
because when I put in my ip and port 80 when I click launch Campaign nothing happens.

**Comment by jordan-wright** [comment]
The URL is supposed to be the external IP address of your Gophish instance. You can find more information in the User Guide [here](https://gophish.gitbooks.io/user-guide/content/documentation/campaigns.html) and [here](https://gophish.gitbooks.io/user-guide/content/campaign/launching_the_campaign.html).

If this is what you are doing, can you please provide the output from the terminal after you try to launch the campaign? There is likely an error there that will indicate the problem.

**Comment by Noltje** [comment]
You mean the External IP address of the machine I have the gophish on ?

**Comment by jordan-wright** [comment]
Yes. From the link I pointed to in the previous comment:

> The URL field is what populates the {{.URL}} template value. This should be a URL or IP address that points to the Gophish phishing server and is reachable by the recipient.

I recommend reading through the User Guide since it gives details on what these fields are used for. Let us know if there is something missing in the User Guide and we'll add it.

**Comment by jordan-wright** [comment]
Closing this for now since there hasn't been an update in the past week.
