### ISSUE TITLE
.modal-open is not added back to body element

### ISSUE THREAD

**Issue by jacobboykin** [gophish/gophish#598]
When a nested modal is closed the .modal-open class is removed from the body even though a modal is still open, making it impossible to scroll to view the rest of the modal or press a cancel or save button.

![image](https://cloud.githubusercontent.com/assets/9063688/25199482/fb9b60be-2518-11e7-9949-e79cba775f04.png)

I've replicated this through the following submenus/modals in the admin portal:
- Sending Profiles >+ New Profile > Send Test Email
- Landing Pages > + New Page > Import Site
- Email Templates > + New Template > Import Email

and in the following browsers / OSs
- Windows 10 v1511: Chrome, Firefox, IE11
- Ubuntu 16.04: Firefox

My workaround for this at the moment is to zoom out the view in Chrome to see the entire modal. My monitors here at work have a 1440 x 900 resolution, so I'm guessing this might not be noticeable for users with larger resolutions. Let me know if you need further information.

**Comment by jordan-wright** [comment]
Ah - yep. Thanks for reporting this. I've run into this issue before but I'll have to spend a bit of time investigating a possible fix. Modal layering with bootstrap is tricky business (what year is it?!) so I'll have to do some digging to see if I can get this one knocked out.

**Comment by jacobboykin** [comment]
No worries! I'm still new to web dev but I'll try to poke around the source some more when I can to see if I can help out. Thanks!

**Comment by jordan-wright** [comment]
All fixed! Let me know if you run into any issues.

**Comment by jacobboykin** [comment]
Thanks for all of your hard work on this awesome project! 👍
