### ISSUE TITLE
API documentation links to local http instead of https page

### ISSUE THREAD

**Issue by lva** [gophish/gophish#601]
When browsing to the API documentation, there is a link to the localhost API documentation in the navigation bar on the left. This links however to an HTTP page, whereas this should link to a secure HTTPS page.

So instead of linking to http://localhost:3333/api/, it should be a link to https://localhost:3333/api/

This applies to both the API documentation in the tool as to the documentation hosted online (at https://getgophish.com/documentation/api/)

**Comment by jordan-wright** [comment]
Thanks for the report! I'll see if I can get this fixed. The long term fix will be to change the link to the new docs on [Gitbook.](https://www.gitbook.com/book/gophish/api-documentation/)

**Comment by lva** [comment]
Apparently it is not only the link in the navigation bar, but also the example links on the right are all still http links.
![capture](https://cloud.githubusercontent.com/assets/1962037/25651695/b166ea46-2fe4-11e7-82b1-46d8b7fbae6b.PNG)

**Comment by jordan-wright** [comment]
This has been fixed in https://github.com/gophish/gophish/commit/abafe3526b1d2d2bf765f6538a1cb46be0884005 with links to our new documentation on Gitbook.

Thanks for reporting this!
