### ISSUE TITLE
Tracking Image Not Working

### ISSUE THREAD

**Issue by XenomMayFire** [gophish/gophish#605]
Hi,

I'm using Windows 10, and I use Xampp to start the apache server on port 80. Then i use ngrok to foward the URL, to make it accessible to the public. 

I enter the forwarded URL from ngrok to the {{.URL}} and start campaign.

I opened the email and click the link. But it is not shown on the dashboard.

But, when i stop apache, and enter my local ipv4 in the {{.URL}} , the tracker is working fine.

I'm not sure what's the issue here, either xampp or the ngrok.

Thanks,

**Comment by jordan-wright** [comment]
I'm afraid I don't know enough about xampp or ngrok to help troubleshoot this. It sounds like Gophish is working as intended, and this support forum is strictly for bugs in gophish.

Sorry that we can't be of more help! I recommend checking out the xampp or ngrok docs/projects for support using them.

**Comment by XenomMayFire** [comment]
It's okay, i found out the problem and able to solve it. 

I saw in the different thread posted about someone else which have problem with tracking image. You said something about the port that being used by other process. I thought i would need xampp to be running as i wanted to make the server alive. but i was wrong. GoPhish itself is a server. Everything working fine now, and i'm able to foward the url using ngrok without any problem

Thanks for your time!

**Comment by jordan-wright** [comment]
Awesome! Glad you were able to get it worked out 😄
