### ISSUE TITLE
Issues with IE11

### ISSUE THREAD

**Issue by lovigag007** [gophish/gophish#609]
I am facing many issues in listing in gophish. Is it its default compatibility issue with IE11 or there are coding changes are needed?

**Comment by S0larflare** [comment]
I used to have issues with IE11 when launching campaigns. I tracked it down to Promises not being properly supported in IE. I use Firefox, though I believe Chrome works just fine, I'm not sure about Edge.

**Comment by jordan-wright** [comment]
I bet I could add a polyfill to support promises in IE, but yes, the recommended browser is Chrome.

I'll keep this issue open strictly to fix the Promises issue- I can't guarantee full compatibility with IE.

**Comment by jordan-wright** [comment]
This has been fixed in https://github.com/gophish/gophish/commit/dd905ecb3ab1f6b6e240394367d5ba59f8a55cf9. Let me know if you run into any issues!

**Comment by yanikl** [comment]
Gophish still has issues with IE11 nd Edge.
I can't open the landing page with IE.
