### ISSUE TITLE
Create JSON Serialized Field for Campaign Result

### ISSUE THREAD

**Issue by jordan-wright** [gophish/gophish#61]
In a nutshell, we need a way to capture form data submitted by the users when they hit a landing page. This gives us the ability to capture credentials (for data submit campaigns), or capture training result data if the user completed some training.

This should be stored in a separate JSON field in the database that is serialized from the POST variables sent to the PhishHandler.

**Comment by jordan-wright** [comment]
Marked as high priority due to the increase in usability this provides.

**Comment by richardontheinternet** [comment]
Essential addition, points if you can take that data and encrypt it somehow or store it safely. The reasoning is many people might have staff that use these tools and there is no reason that everyone in the crew needs to know the captured crews. In real testing you have 50 VPN accounts for some multinational and it's a real single point of weakness. I've had some versions of SET installed that had indexable web site folders and you could navigate to harvester.txt? So in a nutshell Admins can view collected crews and Standard users can't.
