### ISSUE TITLE
Throttle email delivery / email send interval

### ISSUE THREAD

**Issue by HarryR** [gophish/gophish#611]
When sending email out to a large block of users it would be good to be able to schedule the e-mails to be sent out gradually, options for this could include:

  * N emails, delivered at regular intervals between Begin and End dates
  * Static day of N seconds, or random delay between X and Y

This should help email deliverability over time and make it more difficult to reject a batch of emails, it would also allow multiple campaigns to run at the same time with different delays.

**Comment by S0larflare** [comment]
I'm working on this one at the moment (mk3. to be precise). The way I am making it will allow to specify an end date, the size of the batch and the interval between batches (this is static rather than randomised). I've also got a randomisation function so that it isn't going to everyone in order down a list.

Time to work on it has been a bit tight and due to some parts of GoPhish changing I've had to redo a few things differently, and there is one small issue, but I am hoping to get it done 'soonish'.

**Comment by HarryR** [comment]
Ah ok, that sounds promising.

This would be an awesome feature because we can have many campaigns spread out over a month or two.

**Comment by bringcoffeebringbeer** [comment]
I would love to see this.  I use Groups to track progress by Department - except that the whole department is getting the email at the same time!  

Love the system - thanks for what you do!

**Comment by liamosaur** [comment]
+1 for this feature.

My issue isn't being able to spread out emails over long time periods, it's being able to throttle the send rate so I don't end up with rate-limiting email rejections from the 3rd party SMTP server we use.

**Comment by jonfurmanski** [comment]
+1 for this feature

Also, not to keep expanding further, but if we can throttle either via rate limit or time based, it would be nice to specify what hours of the days the emails can be sent. I tend to like to send the emails during business hours.

**Comment by teddielong** [comment]
+1 - we have issues when sending emails as all are received at the same time (unless we manually group which is a nightmare).
Any update on timescales?  Thanks again for this, it's a great tool.

**Comment by cptwin** [comment]
Looking into this as well, did anyone else manage to create a solution?

**Comment by jordan-wright** [comment]
Refactoring the mailing system is a large task that I'm doing carefully. I don't have a timeline for it yet, other than saying it's the highest priority big item on my list.

**Comment by cptwin** [comment]
How would I go about requesting access to create a pull request? I've created a simple solution that would work in the interim.

**Comment by thryb** [comment]
Not related directly to gophish but we ran into that issue during a campaign. If you guys use postfix you can add the following to your main.cf which will delay the time between emails:

Time is in seconds.
smtp_destination_rate_delay = 120 
relay_destination_rate_delay = 120

Cheers

**Comment by the1aughingman** [comment]
I ran into this issue with one of my class projects and did a guide on setting everything up that the other students seem to have been able to replicate in a manner similar to thryb. It goes over the entire setup start to end and is a little wordy but they said it helped. Hope it helps anyone who comes here looking to put in a delay while the support for timed campaigns is being worked on. 

https://www.thelaughingman.org/home/2018/6/15/creating-a-delayed-gophsih-server

Feedback is always appreciated.

**Comment by cjundy26** [comment]
@thryb did you have to do anything else? Adding those lines into my configuration dont seem to do anything in terms of spacing out when emails are sent

**Comment by thryb** [comment]
@cjundy26 only restart the service then it was working.

**Comment by chkconfig** [comment]
+1 for this as well

**Comment by aderraik** [comment]
Hi guys!
I don't know if this is the right issue, but I'll write here.
I made a change into the SMTP configuration to introduce the _block size_ (the maximum number of emails to send in the same connection to the same domain).
I.e., some STMP receivers have a limitation to receive a bulk of emails in the same connection.
With this parameter, it sends the bulk, close the connection, open again and send the rest.
Stay in this loop until no more emails to send to the **same** domain.
I put in here: [My fork in branch blocking-emails](https://github.com/aderraik/gophish/tree/blocking-emails)
I don't know if is the right term...
Thanks.

**Comment by DeC1pher** [comment]
For me only this worked to send one mail every hour

```
smtp_destination_concurrency_limit = 1
default_destination_rate_delay = 3600s
```

Cheers!
