### ISSUE TITLE
List of GoPhish modules

### ISSUE THREAD

**Issue by XenomMayFire** [gophish/gophish#612]
Hi, i wanted to know is there any list for gophish module?

I mean the {{.FirstName}}, {{.URL}}... is there any full list of it? I can't find it. 

Thanks!

**Comment by jordan-wright** [comment]
https://gophish.gitbooks.io/user-guide/content/template_reference.html

**Comment by jordan-wright** [comment]
Going ahead and closing this since that link should answer your question. @XenomMayFire if there is other information you need, please don't hesitate to let me know.
