### ISSUE TITLE
Passwords are captured when Capture Passwords is unchecked

### ISSUE THREAD

**Issue by NZSmartie** [gophish/gophish#613]
Hi, just found this issue today when importing a login screen from an existing site.

In my case, the password input field had a capital P in the type attribute, which resulted in gophish capturing the password field instead of ignoring it. 
`<input name="passwd" size="30" type="Password" />` 

Work around is to make sure the type attribute is all lowercase:
`<input name="passwd" size="30" type="password" />` 

Cheers
Roman

**Comment by jordan-wright** [comment]
Good catch, thanks for the heads up! While I don't know that "Password" is correct according to the standard (and I'm too lazy to look it up, heh) I'll add a check for it in Gophish.
