### ISSUE TITLE
GoPhish keep on freezing

### ISSUE THREAD

**Issue by XenomMayFire** [gophish/gophish#614]
Hello,

I made a script for the landing page. But when paste it into gophish. it's UI just freezing.

Thanks

**Comment by jordan-wright** [comment]
We're going to need more info to help troubleshoot this.

What script? What was the landing page contents?

**Comment by jordan-wright** [comment]
Closing this since there hasn't been any updates in a couple of weeks. @XenomMayFire let us know if you have any more details on this and we can re open.
