### ISSUE TITLE
Change reported source IP from custom header value

### ISSUE THREAD

**Issue by killerbootz** [gophish/gophish#615]
Hi there. Love the app btw. Just curious if there is any functionality currently (either within the API or otherwise) to add or change the reported source IP, based on extra header information received from each connection? Thanks!

**Comment by jordan-wright** [comment]
Sorry for the delay on this one- I'm not quite sure what you mean. Are you referring to things like honoring the X-Forwarded-For header?

**Comment by killerbootz** [comment]
No problem, I'm running this behind a load-balancer which rewrites the source IP of the connection. I can add a header with the value of the original source IP, my only issue would be how to access the results of that header value (if that's a possibility). Thanks!

**Comment by jordan-wright** [comment]
So looking through the code, it does appear we honor the X-Forwarded-For header. If your load balanced sets that header to the original IP, the source IP will be correct.

**Comment by killerbootz** [comment]
That worked perfectly, thanks!

**Comment by jordan-wright** [comment]
Good deal! Glad you were able to get this one resolved.
