### ISSUE TITLE
Campaigns - how to view the "Schedule" for a queued item?

### ISSUE THREAD

**Issue by snori74** [gophish/gophish#616]
The GUI doesn't appear to give any way to check the schedule for a queued campaign.

The "Copy Campaign" allows you a roundabout way to peek at all the other details, but it changes the "Schedule" value to the current time. While that's not unreasonable, it means that's not a way to see the current value of "Schedule" for a queued campaign. 

The best option I think would be to add a new item on the "View results" page - perhaps replace "Campaign timeline" with "Queued: scheduled for 3:45pm 12/5/2017" - for queued campaigns.

**Comment by S0larflare** [comment]
If you update to the latest version, you can mouse over the campaign to get the schedule date:

![image](https://cloud.githubusercontent.com/assets/8939757/25899902/889bf2be-3589-11e7-8ca1-2908a91d672b.png)

**Comment by snori74** [comment]
Great, will test later today.

**Comment by jordan-wright** [comment]
Yep! This should be merged into the master branch. If you run into any issues @snori74, let me know and I'll reopen this one.

Thanks for the report!
