### ISSUE TITLE
Windows installation trouble

### ISSUE THREAD

**Issue by FluffyZack** [gophish/gophish#617]
I try to run the gophish.exe file in cmd but when I do so it is only outputting the server IP but not the admin server IP.  I have tried running as administrator already.

2017/05/08 18:57:30 gophish.go:83: Starting phishing server at http://0.0.0.0:80
 2017/05/08 18:57:30 gophish.go:84: listen tcp 0.0.0.0:80: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by S0larflare** [comment]
Try changing the config.json file to run it on port 81

Sent from my iPhone

On 9 May 2017, at 02:59, FluffyZack <notifications@github.com<mailto:notifications@github.com>> wrote:


I try to run the gophish.exe file in cmd but when I do so it is only outputting the server IP but not the admin server IP. I have tried running as administrator already.

2017/05/08 18:57:30 gophish.go:83: Starting phishing server at http://0.0.0.0:80
2017/05/08 18:57:30 gophish.go:84: listen tcp 0.0.0.0:80: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by jshaw87** [comment]
Are you running the command prompt as an administrator?

**Comment by jordan-wright** [comment]
Hey @FluffyZack just checking in on this, are you still running into issues? Perhaps [this](https://stackoverflow.com/questions/15619921/an-attempt-was-made-to-access-a-socket-in-a-way-forbidden-by-its-access-permissi) StackOverflow answer might help. But, changing the port to 81 would also likely work around this.

**Comment by FluffyZack** [comment]
Wow thanks for following up, I never tried port 81 I just ended up using a Linux VPS on DigitalOcean. Thanks for showing you care about the users :)

**Comment by jordan-wright** [comment]
The community is what makes Gophish great! I'm glad you were able to get this resolved.

It sounds like you were able to make it work via port 80 on the Linux VPS which is probably for the best. If you use a non-standard port like 81 then you'd have to remember that everytime you made a campaign.

Never hesitate to open other issues if you run into any other trouble. We're here to help! 😄
