### ISSUE TITLE
Report Features

### ISSUE THREAD

**Issue by jshaw87** [gophish/gophish#618]
Hi,

Would it be possible to have a reporting feature added to Gophish? This would ideally generate different types of graphs and statistics etc.

Thanks

**Comment by jordan-wright** [comment]
What kinds of reports are you looking for? We have the csv exports of raw events and high level statistics, and we also have the full API complete with a Python client that you can use to make reports however you'd like.

There are also community projects like the awesome GoReport project that can export reports for you.

All the documentation is [here](https://gophish.gitbooks.io/user-guide/content/documentation/reporting.html).

**Comment by jordan-wright** [comment]
Closing this out as there hasn't been any updates in 3 weeks. @jshaw87 if there was anything else you wanted to cover about Gophish reporting related to this issue, let us know and we can re-open.
