### ISSUE TITLE
phish-link get 404 not found.

### ISSUE THREAD

**Issue by jinq102030** [gophish/gophish#620]
Ran a campaign and the following is the email body received on my command line SMTP server which displayed the email body on console.   I pasted image tracking link in my browser, I can see the status for this campaign showing email opened.  But when I pasted the phish-link in browser, I got 404.   I do have a landing page configured for this campaign.  Wonder why.

By the way, I just checked out this repo today.   Thanks.

```html
<html>
<head>
	<title></title>
</head>
<body>
<p>please reset password&nbsp;<a href=3D"http://10.6.0.158?rid=3DwsPAwCI">h=
ere</a>&nbsp;!</p>

<p><img alt=3D'' style=3D'display: none' src=3D'http://10.6.0.158/track?rid=
=3DwsPAwCI'/></p>
</body>
</html>
```

**Comment by 304GEEK** [comment]
same issue here.

**Comment by jordan-wright** [comment]
Everything looks fine. Gophish usually sends these emails using quoted printable encoding, so "=3D" is actually just "=" encoded.

What happens if you paste the link and replace "=3D" with "="? Does it work then?

**Comment by jinq102030** [comment]
Thanks @jordan-wright, you are right, I overlooked the =3D. It's working great now.
