### ISSUE TITLE
Error starting: address already in use

### ISSUE THREAD

**Issue by alme5** [gophish/gophish#621]
I am trying to run the latest version on AWS Ubuntu 16.04 x64.
Apache is not running. netstat shows no port 80 nor 443.
Following error:
models.go:98: no valid version found
no valid version found
gophish.go:83: Starting phishing server at http://
worker.go:36: Background Worker Started Successfully - Waiting for Campaigns
 gophish.go:70: Starting admin server at http://
gophish.go:71: listen tcp :80: bind: address already in use

config file:
{
        "admin_server" : {
                "listen_url" : "0.0.0.0:8080",
                "use_tls" : false,
                "cert_path" : "gophish_admin.crt",
                "key_path" : "gophish_admin.key"
        },
        "phish_server" : {
                "listen_url" : "0.0.0.0:80",
                "use_tls" : false,
                "cert_path" : "example.crt",
                "key_path": "example.key"
        },
 Any help?

**Comment by S0larflare** [comment]
The admin server should have a different ip to your phish server. Having it as 0.0.0.0 wont work. Put it to 127.0.0.1 if you're going to connect locally or to it's network ip if you're connecting remotely

Sent from my iPhone

On 13 May 2017, at 19:05, alme5 <notifications@github.com<mailto:notifications@github.com>> wrote:


I am trying to run the latest version on AWS Ubuntu 16.04 x64.
Apache is not running. netstat shows no port 80 nor 443.
Following error:
models.go:98: no valid version found
no valid version found
gophish.go:83: Starting phishing server at http://
worker.go:36: Background Worker Started Successfully - Waiting for Campaigns
gophish.go:70: Starting admin server at http://
gophish.go:71: listen tcp :80: bind: address already in use

config file:
{
"admin_server" : {
"listen_url" : "0.0.0.0:8080",
"use_tls" : false,
"cert_path" : "gophish_admin.crt",
"key_path" : "gophish_admin.key"
},
"phish_server" : {
"listen_url" : "0.0.0.0:80",
"use_tls" : false,
"cert_path" : "example.crt",
"key_path": "example.key"
},
Any help?

**Comment by jordan-wright** [comment]
Also, the config looks to be an older version. Make sure you're using the config.json from the latest version since it includes stuff about the database path.

**Comment by jordan-wright** [comment]
Just checking in, were you able to confirm if you were using the latest version of the config.json?

**Comment by jordan-wright** [comment]
Going ahead and closing this since there haven't been any updates in a week. @alme5, if you're still having trouble, let us know if you're using the latest config.json and we can re-open to continue troubleshooting.
