### ISSUE TITLE
Inputting settings dont save. for anything!

### ISSUE THREAD

**Issue by jbilliau** [gophish/gophish#623]
When I create landing pages, email templates etc...nothing saves or looks like it does.  If I log back in, my new template is there, but not when I insert it at first.  Why would I have to log out for something to save?

Also when creating a new email template, when I import the source and save it all, nothing goes into the editor like it should.

So weird!

**Comment by jbilliau** [comment]
anyone?  Really wanna use this software but I've tried other browsers and both have the same results.

**Comment by jordan-wright** [comment]
The ideal browser is Chrome. Can you dump the output from the terminal when you add the landing page, import the template, etc.?

**Comment by jbilliau** [comment]
I get malformed MIME Header Line:

I tried 4 different email source codes form different emails just to test.  It says various things are malformed.  One said the Head tag, another said the <meta   blah blah...

I' can try to post the screenshots too.

**Comment by jbilliau** [comment]
ya its crazy.  even if i type the word test,  and thats it...then hit import email or whatever, i get the malformed error. Thats crazy!

Working in chrome as my 3rd and final browser to test

**Comment by jbilliau** [comment]
I dont understand how nobody has issues? I tried 3 different machines..and cant get import to work.  Its gotta be a bug, but how I'm the only one complaining of the issue is beyond me!!

**Comment by jordan-wright** [comment]
Don't worry, we'll get it figured out. Remember that importing an email requires you to put in the full MIME formatted raw content. So, if you're importing from gmail, for example, this is done by using the "Show Original" button.

Importing just content itself without the full structure won't work. This is why the word "test" doesn't work.

**Comment by jordan-wright** [comment]
And any screenshots are always helpful.

**Comment by jbilliau** [comment]
![screen2](https://cloud.githubusercontent.com/assets/28764809/26254080/5c238052-3c83-11e7-9e2e-f90c89a833a5.jpg)
![screen1](https://cloud.githubusercontent.com/assets/28764809/26254081/5c362b8a-3c83-11e7-91b9-e04484067eec.jpg)

Here are two from 2 diff email sources.  Oh and yes, I know about the show original.

**Comment by jbilliau** [comment]
I take that back...I always goto VIEW SOURCE

**Comment by jbilliau** [comment]
ok so, if I do what u say thru email....  I actually get it to work!

However, thats my personal account.  I'm trying to do emails from outlook and using view source.

I cant get it to work with outlook emails.

**Comment by jbilliau** [comment]
think I figured it out!

**Comment by jordan-wright** [comment]
Good deal! Glad you were able to get it resolved.

**Comment by meszicsaba84** [comment]
Hi, I also has the same issue. @jbilliau Can you share how could you solve this?
Background: I have installed Gophsih, GUI works, created sending profiles and groups, but when I would like to create a new template (using import email and "View original" from Gmail). When I click Save nothing happens. I attach the log I can see - but seems there is no error message? Can you please help?
![gophish_log](https://user-images.githubusercontent.com/114218758/191918066-9f716463-8304-4a8c-b458-7847901e3946.png)

**Comment by meszicsaba84** [comment]
Hi @jordan-wright , can you please help me with my issue above? I am using tmux - evilgenx2 is running in 1 session and gophish in another.
