### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by PunkAsPhuk** [gophish/gophish#624]
This has to be the most complicated install ever! Please can you stop advertising this as a simple install!

Any advice on how to install on Ubuntu, Kali, Win7, Win10? I don't mind which one.

I have already spent 4 hours going through here trying everything and still have nothing except grey hairs.

**Comment by S0larflare** [comment]
It might be difficult if you are building it from source, but installing one of the releases is pretty much download, run and go...

Can you give some info on what you have done and I'll be happy to help

**Comment by PunkAsPhuk** [comment]
Hi S0larflare,
Thanks for your offer! I'm running windows 10, have downloaded the zip file, extracted it. I'm now trying to "run the binary"
I've followed the instructions exactly from here https://github.com/gophish/gophish and from here https://www.gitbook.com/@gophish - Where is the binary supposed to come from? I have no .bin file anywhere in my gophish download?
I've also tried building it in my ubuntu and kali VMs but this threw up error after error so though it best to do it the "Easy" way...
Any ideas? Thanks in advance! :)

**Comment by PunkAsPhuk** [comment]
Ok, So it turns out "Run the binary" means the gophish.exe which needs to be run as administrator.

Having done this, I navigate to 127.0.0.1:3333 (as is outlined in config.json) however i get the following message;

This site can’t be reached
127.0.0.1 refused to connect.

Anybody got any suggestions?

**Comment by PunkAsPhuk** [comment]
Went for a coffee, now it's working! :) at last! :) Woohoo!

**Comment by jordan-wright** [comment]
Sorry for the hassle getting it up and running. If you have any suggestions on how we can be more clear in the documentation, I'm all ears.

Glad you got it working!

**Comment by PunkAsPhuk** [comment]
Not a problem, I think i was thrown by guides referring to binary files when installing on windows. I was looking for .bin files rather than .exe - If the userguide could be updated to be a little clearer in this respect for windows users that would be much better! 

Most of my experience is with windows rather than Linux and a lot of users from my background (workplace based IT Education) are more likely to have access to windows machines. 
  
It looks like you've put together a great little product here! Will definitely be used to support my Anti-Phishing teaching roll out to over 3000 staff! :)
