### ISSUE TITLE
Server 2008 R2 Wont install

### ISSUE THREAD

**Issue by CalebKauer** [gophish/gophish#625]
I am trying to educate my users on the dangerous of Malicious emails.  I came across GoPhish.

When I try to install it on my Server 2008 R2 box, the CMD pops up for half a second and then disappears.  Then nothing....I have allowed this file type already.  Any help would be greatly appreciated.

Thank you in advance.

**Comment by jbilliau** [comment]
try running it as administratr

**Comment by CalebKauer** [comment]
Sorry, I should have mentioned that I already tried that.

**Comment by S0larflare** [comment]
How are you running it? Just by clicking the executable? Run it through a cmd window or powershell or something like that.

Sent from my iPhone

On 18 May 2017, at 18:09, CalebKauer <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry, I should have mentioned that I already tried that.

**Comment by CalebKauer** [comment]
Thats not a bad idea, I will run it through CMD and let you know.

**Comment by jbilliau** [comment]
it wont work. I tried it and had the same issue. I do however have a reason and workaround.

**Comment by CalebKauer** [comment]
I'm all ears. Have been running in circles for two days.

**Comment by DeliriumNocturnum** [comment]
Just installed and set this up yesterday on 2008r2 -- extracted files, **opened CMD as administrator**, ran the exe from there and was off to the races.

**Comment by jbilliau** [comment]
I was testing. Although I havnt tested it officially thru the gui....maybe you can try.  Essentially it looks like port 80 is already a binded port in 2008 R2.  So it attaches to a PID and is essentially in use.  So it cant open the socket so closes out.

Open up the config.jason and change it to :   "listen_url" : "0.0.0.0:85",   for example.  Then run it. It should work then...  *prays*

**Comment by CalebKauer** [comment]
This is the error I get when running from CMD:

C:\Users\administrator.GRASS\Documents\gophish-v0.3-windows-64bit\gophish-v0.3-w
indows-64bit>gophish.exe
goose: no migrations to run. current version: 20170219122503
 2017/05/18 14:16:54 gophish.go:83: Starting phishing server at http://0.0.0.0:8
0
 2017/05/18 14:16:54 gophish.go:84: listen tcp 0.0.0.0:80: bind: An attempt was
made to access a socket in a way forbidden by its access permissions.

**Comment by CalebKauer** [comment]
jbilliau, where exactly do I change that?

**Comment by jbilliau** [comment]
I just told you, open the config file and change it

**Comment by CalebKauer** [comment]
Im sorry, I missed that.

**Comment by CalebKauer** [comment]
AHHH works like a charm! Thank you all! and thank you jbilliau for the explanation 💃

**Comment by jordan-wright** [comment]
Good deal! Glad you were able to get this resolved! Thanks for all the help @S0larflare, @jbilliau, and @DeliriumNocturnum!
