### ISSUE TITLE
Hello Devs

### ISSUE THREAD

**Issue by kaizoku-619** [gophish/gophish#626]
I just installed GoPhish on a ubuntu VM running on azure then i stopped the Apache2 service and executed gophish but when navigate to the IP I still get a "404 not found" error.
![screenshot from 2017-05-18 21-58-10](https://cloud.githubusercontent.com/assets/22129291/26223367/5373788e-3c0d-11e7-8909-237d91d8b507.png)

**Comment by wjwoodson** [comment]
Hi,
It sounds like you're navigating to a port where Apache2 is listening. You
should be able to access the admin ui at https://your_server_ip:3333

**Comment by wjwoodson** [comment]
It looks like you're navigating to the phishing server running at port 80 without having created any campaigns. You should be able to access the admin ui at https://{your_server_ip}:3333

**Comment by jordan-wright** [comment]
It's almost certain that's the issue - thanks @wjwoodson! @kaizoku-619, please refer to our [user guide](https://gophish.gitbooks.io/user-guide/content/getting_started.html) for more info on getting up and running.

I'm closing this one out for now. Let us know if that doesn't help resolve the issue and we can re-open.

**Comment by kaizoku-619** [comment]
Thank you @wjwoodson and @jordan-wright for the reply, the problem i have is that i can't access the admin ui even thought i'm navigating to https://{my_server_ip}:3333

**Comment by S0larflare** [comment]
If you're struggling, you could try changing the admin url to the IP address you're using to connect to the box. Then restart gophish and try connecting

Sent from my iPhone

On 19 May 2017, at 22:01, Bayrem Gharssellaoui <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you @wjwoodson<https://github.com/wjwoodson> and @jordan-wright<https://github.com/jordan-wright> for the reply, the problem i have is that i can't access the admin ui even thought i'm navigating to https://{my_server_ip}:3333

**Comment by kaizoku-619** [comment]
Hi @S0larflare I tried that, but that didn't work either..
![sketch 1](https://cloud.githubusercontent.com/assets/22129291/26275899/5ed09e00-3d20-11e7-95fe-1ce36000a57b.png)

**Comment by kaizoku-619** [comment]
Hi @S0larflare I tried it but that didn't work either 
![sketch 1](https://cloud.githubusercontent.com/assets/22129291/26275967/e0113550-3d21-11e7-8095-459f027ad722.png)

**Comment by jordan-wright** [comment]
When you have the config listening on all interfaces, what error do you see when you try to hit the admin panel? Do you see a connection log in the terminal?

**Comment by kaizoku-619** [comment]
When i have the config listening on all interfaces and i go to https://{my_server_ip}:3333 nothing happens on the browser and nothing happens on the terminal either
![screenshot from 2017-05-21 21-19-52](https://cloud.githubusercontent.com/assets/22129291/26287077/27dd1100-3e63-11e7-922f-b9ff8b445ddb.png)
![screenshot from 2017-05-21 21-21-15](https://cloud.githubusercontent.com/assets/22129291/26287079/2c7fd972-3e63-11e7-9d00-43a016e18dbd.png)

**Comment by jordan-wright** [comment]
If this is AWS, you might have firewall issues preventing the connection.

**Comment by kaizoku-619** [comment]
@jordan-wright i'm using azure ubuntu virtual machine

**Comment by jordan-wright** [comment]
It still looks almost certain like a firewall issue. These docs may help: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/nsg-quickstart-portal

**Comment by kaizoku-619** [comment]
Thank you @jordan-wright  I think that that was the issue.

**Comment by jordan-wright** [comment]
Good deal! Glad you were able to get it resolved.

**Comment by Ashely1434** [comment]
i'm still having trouble with this, even aftr opening the port 80

**Comment by S0larflare** [comment]
Ashley, you're best off opening a new issue and posting a screenshot of the problem
