### ISSUE TITLE
Found 0 Campaigns to run

### ISSUE THREAD

**Issue by xkb77x** [gophish/gophish#629]
When I attempt launch a campaign as well as send a test email I receive the following in my command prompt: "campaign.go.:340: Found 0 Campaigns to Run". 

I am running GoPhish 0.3.0 downloaded directly from Github not built from source on a Windows server 2012 R2. 

I did some searching around but did not find anyone with a similar issue. Any ideas as to why this error might be occurring?

Thanks

**Comment by jordan-wright** [comment]
When you launch the campaigns, what do you see in the terminal? (As soon as you click to launch the campaign).

The 0 campaigns to run message is a scheduled worker that runs once per minute to pick up any new campaigns, so we won't find the real issue there.

**Comment by xkb77x** [comment]
It is really strange because the campaign does not appear to actually launch either. The dialogue box for inputting campaign options sits on screen after hitting launch. The terminal only give the "Found 0..." information. I am wondering if I should try a clean install and give it another go?

**Comment by jordan-wright** [comment]
If you're using Chrome (recommended) you might open the Developer Tools and check the console for any errors after you try to launch the campaign. If you see any errors, post them here and we can help troubleshoot.

**Comment by xkb77x** [comment]
On Press of Launch Campaign:
SCRIPT5009: 'Promise' is undefined
File: vendor.min.js, Line: 17, Column: 17677

**Comment by jordan-wright** [comment]
What browser are you using?

**Comment by xkb77x** [comment]
Tried it out in Chrome. On launch GoPhish gives me a invalid JSON structure message.

Console in Chrome throws this error:

gophish.min.js:1 POST https://localhost:3333/api/campaigns/?api_key=b7ccbfc6c7193f3b358e0f8ec5c872d6ecb63ad1c768e961b8451aac115ad4eb 400 ()
send	@	vendor.min.js:3
ajax	@	vendor.min.js:3
query	@	gophish.min.js:1
post	@	gophish.min.js:1
(anonymous)	@	campaigns.min.js:1
preConfirm	@	campaigns.min.js:1
T	@	vendor.min.js:17
M	@	vendor.min.js:17

**Comment by jordan-wright** [comment]
Hmmmm... that's really odd. That POST should correspond to a network request you can see in the inspector. If you open the network inspector tab and view that request, what is the response body?

And do you see any errors in the terminal when you use Chrome to try and launch the campaign?

**Comment by xkb77x** [comment]
Here is what I am getting in the network tab of Chrome:
Error 400 on the POST
![image](https://cloud.githubusercontent.com/assets/20646134/26332893/9fb44242-3f0e-11e7-9643-708cc220e025.png)

**Comment by jordan-wright** [comment]
It looks like there is something wrong with the request that's being sent. Can you right click on the request and choose "Copy as curl command" and paste the curl output here? Feel free to redact any sensitive information, but please keep the request structure in tact.

My guess is that there is a missing field somewhere.

**Comment by xkb77x** [comment]
Here is the information from the curl cmd:

curl "https://localhost:3333/api/campaigns/?api_key=b7ccbfc6c7193f3b358e0f8ec5c872d6ecb63ad1c768e961b8451aac115ad4eb" -H "origin: https://localhost:3333" -H "accept-encoding: gzip, deflate, br" -H "x-requested-with: XMLHttpRequest" -H "accept-language: en-US,en;q=0.8" -H "user-agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" -H "content-type: application/json" -H "accept: application/json, text/javascript, */*; q=0.01" -H "referer: https://localhost:3333/campaigns" -H "authority: localhost:3333" -H "cookie: _gorilla_csrf=MTQ5NTQ5MzczOXxJbmhzT0RaUkwxTXdWQ3R4YjBkSVduRnVNREZDT0Nzdk1tMTZVbFpqT0ZkT1ZrbFhVVEpsUnlzNGVHYzlJZ289fLdwqAf8KnpSAFgx3M_42ulRFy1YdOMAh9ncxYvUT5S7; gophish=MTQ5NTQ5Mzc0NHx3YUNieVJaZ19vc0owVDdRWDZPU0c2TGE2bFJ1NE1wclZjR3NrUUpxZnM0R2FTcjhnU1F3STlMU0t3UUNTUkxLU1Y5TC1nWld3dlc4TFZNPXzAOpKscI4n7zHwE0NYe3T2OtZl_PjoigGxvo8itQH6nA==" --data-binary "^{^\^"name^\^":^\^"Test ^\^",^\^"template^\^":^{^\^"name^\^":^\^"Email^\^"^},^\^"url^\^":^\^"https://website.net^\^",^\^"page^\^":^{^\^"name^\^":^\^"Login Page^\^"^},^\^"smtp^\^":^{^\^"name^\^":^\^"email^@email.com^\^"^},^\^"launch_date^\^":^\^"Invalid date^\^",^\^"groups^\^":^[^{^\^"name^\^":^\^"Test^\^"^}^]^}" --compressed &
curl "https://localhost:3333/api/campaigns/?api_key=b7ccbfc6c7193f3b358e0f8ec5c872d6ecb63ad1c768e961b8451aac115ad4eb" -H "origin: https://localhost:3333" -H "accept-encoding: gzip, deflate, br" -H "x-requested-with: XMLHttpRequest" -H "accept-language: en-US,en;q=0.8" -H "user-agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" -H "content-type: application/json" -H "accept: application/json, text/javascript, */*; q=0.01" -H "referer: https://localhost:3333/campaigns" -H "authority: localhost:3333" -H "cookie: _gorilla_csrf=MTQ5NTQ5MzczOXxJbmhzT0RaUkwxTXdWQ3R4YjBkSVduRnVNREZDT0Nzdk1tMTZVbFpqT0ZkT1ZrbFhVVEpsUnlzNGVHYzlJZ289fLdwqAf8KnpSAFgx3M_42ulRFy1YdOMAh9ncxYvUT5S7; gophish=MTQ5NTQ5Mzc0NHx3YUNieVJaZ19vc0owVDdRWDZPU0c2TGE2bFJ1NE1wclZjR3NrUUpxZnM0R2FTcjhnU1F3STlMU0t3UUNTUkxLU1Y5TC1nWld3dlc4TFZNPXzAOpKscI4n7zHwE0NYe3T2OtZl_PjoigGxvo8itQH6nA==" --data-binary "^{^\^"name^\^":^\^"Test ^\^",^\^"template^\^":^{^\^"name^\^":^\^"email^\^"^},^\^"url^\^":^\^"https://website.net^\^",^\^"page^\^":^{^\^"name^\^":^\^"Login Page^\^"^},^\^"smtp^\^":^{^\^"name^\^":^\^"email^@email.com^\^"^},^\^"launch_date^\^":^\^"Invalid date^\^",^\^"groups^\^":^[^{^\^"name^\^":^\^"Test^\^"^}^]^}" --compressed &
curl "https://localhost:3333/api/campaigns/?api_key=b7ccbfc6c7193f3b358e0f8ec5c872d6ecb63ad1c768e961b8451aac115ad4eb" -H "origin: https://localhost:3333" -H "accept-encoding: gzip, deflate, br" -H "x-requested-with: XMLHttpRequest" -H "accept-language: en-US,en;q=0.8" -H "user-agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" -H "content-type: application/json" -H "accept: application/json, text/javascript, */*; q=0.01" -H "referer: https://localhost:3333/campaigns" -H "authority: localhost:3333" -H "cookie: _gorilla_csrf=MTQ5NTQ5MzczOXxJbmhzT0RaUkwxTXdWQ3R4YjBkSVduRnVNREZDT0Nzdk1tMTZVbFpqT0ZkT1ZrbFhVVEpsUnlzNGVHYzlJZ289fLdwqAf8KnpSAFgx3M_42ulRFy1YdOMAh9ncxYvUT5S7; gophish=MTQ5NTQ5Mzc0NHx3YUNieVJaZ19vc0owVDdRWDZPU0c2TGE2bFJ1NE1wclZjR3NrUUpxZnM0R2FTcjhnU1F3STlMU0t3UUNTUkxLU1Y5TC1nWld3dlc4TFZNPXzAOpKscI4n7zHwE0NYe3T2OtZl_PjoigGxvo8itQH6nA==" --data-binary "^{^\^"name^\^":^\^"Test ^\^",^\^"template^\^":^{^\^"name^\^":^\^"email^\^"^},^\^"url^\^":^\^"website.net^\^",^\^"page^\^":^{^\^"name^\^":^\^"Login Page^\^"^},^\^"smtp^\^":^{^\^"name^\^":^\^"email^@email.com^\^"^},^\^"launch_date^\^":^\^"Invalid date^\^",^\^"groups^\^":^[^{^\^"name^\^":^\^"Test^\^"^}^]^}" --compressed &
curl "https://localhost:3333/api/campaigns/?api_key=b7ccbfc6c7193f3b358e0f8ec5c872d6ecb63ad1c768e961b8451aac115ad4eb" -H "origin: https://localhost:3333" -H "accept-encoding: gzip, deflate, br" -H "x-requested-with: XMLHttpRequest" -H "accept-language: en-US,en;q=0.8" -H "user-agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" -H "content-type: application/json" -H "accept: application/json, text/javascript, */*; q=0.01" -H "referer: https://localhost:3333/campaigns" -H "authority: localhost:3333" -H "cookie: _gorilla_csrf=MTQ5NTQ5MzczOXxJbmhzT0RaUkwxTXdWQ3R4YjBkSVduRnVNREZDT0Nzdk1tMTZVbFpqT0ZkT1ZrbFhVVEpsUnlzNGVHYzlJZ289fLdwqAf8KnpSAFgx3M_42ulRFy1YdOMAh9ncxYvUT5S7; gophish=MTQ5NTQ5Mzc0NHx3YUNieVJaZ19vc0owVDdRWDZPU0c2TGE2bFJ1NE1wclZjR3NrUUpxZnM0R2FTcjhnU1F3STlMU0t3UUNTUkxLU1Y5TC1nWld3dlc4TFZNPXzAOpKscI4n7zHwE0NYe3T2OtZl_PjoigGxvo8itQH6nA==" --data-binary "^{^\^"name^\^":^\^"Test ^\^",^\^"template^\^":^{^\^"name^\^":^\^"email^\^"^},^\^"url^\^":^\^"website.net^\^",^\^"page^\^":^{^\^"name^\^":^\^"Login Page^\^"^},^\^"smtp^\^":^{^\^"name^\^":^\^"email^@email.com^\^"^},^\^"launch_date^\^":^\^"Invalid date^\^",^\^"groups^\^":^[^{^\^"name^\^":^\^"Test^\^"^}^]^}" --compressed

**Comment by jordan-wright** [comment]
It looks like there might be something wrong with the `launch_date` being sent. Are you using the datepicker provided? There's definitely something getting messed up somewhere there.

**Comment by jordan-wright** [comment]
And you still get the same error? Can you post a picture of the modal when you get the error (you can redact things where necessary)?

And is there still no other debug information being seen in the terminal?

**Comment by xkb77x** [comment]
That is only error I am getting when I attempt to launch the campaign. Here are the screen caps of pre and post launch.

Before launch:
![image](https://cloud.githubusercontent.com/assets/20646134/26591745/77b0f686-4513-11e7-99ad-9582166a2361.png)


After hitting launch:
![image](https://cloud.githubusercontent.com/assets/20646134/26591634/2565e9fe-4513-11e7-9e66-8286906040e8.png)

**Comment by nannal** [comment]
I'm also experiencing this with gophish 3.0 on mac osx & have tried to create campaigns in both firefox and chrome. 

Firefox campaign was created by duplicating one created in chrome and therefore any issues with config created by chrome may be affecting firefox output. 

I'll continue to test and update.

**Comment by martijn0x76** [comment]
I had the same problem. My Docker container (with GoPhish) was running on a different time/timezone. I solved it by setting the container to the correct time and timezone so it matches the time of my workstation.

**Comment by jordan-wright** [comment]
Hi @xkb77x sorry for the delay in getting back to you. Can you provide the output of the terminal when this error occurs? That might help us track down what's going on, since the frontend-ui isn't really giving us any clues.

**Comment by xkb77x** [comment]
I left GoPhish alone for a few day because some other stuff came up at work. When I went back to try and launch it again there was no issue. I didn't make any changes beyond the date being current so it would launch. I know that is not super helpful. 

Although despite having run about 10 campaigns since then and closing them all. Every minute the terminal produces the "campaign.go:340: Found 0 Campaigns to run" message.

**Comment by jordan-wright** [comment]
That's good there was no issue! Looks like this was the timezone issue I've been working out how to address.

The message you see about having 0 campaigns to run is normal - it's just the worker process checking for campaigns that are ready to be executed and finding no new campaigns.

Thanks for the update!
