### ISSUE TITLE
Landing page URL External question

### ISSUE THREAD

**Issue by jbilliau** [gophish/gophish#633]
So... right now I have this running on my desktop at work, but want to put the landing page on one of our public IP's.  So when I setup my new campaign the URL would be http://*.*.*.*  which would be a public IP.

I have an apache server already set to to.  I tried copying the static directory to it, but it doesnt work.  Am I going about this the wrong way?  I tried changing the phishing server url in the config and that didnt work either.

Or should I be installing the linux gohish on my apache server instead?

**Comment by jordan-wright** [comment]
Like the comment you made on #634, Apache (like IIS) is a webserver. Gophish has its own webserver so Apache and IIS aren't needed.

If you want to separate the phishing server and the admin server, you'll need multiple instances of Gophish each pointing to the same instance of MySQL so they share the database. You can see more about this in https://github.com/gophish/gophish/issues/558.

**Comment by jordan-wright** [comment]
Since issue #634 is close to this one, I'm going to close this out in favor of that one.
