### ISSUE TITLE
Gophish Python API Client

### ISSUE THREAD

**Issue by MihaRocket** [gophish/gophish#635]
I am trying to print campaign.name. But when i run the program it returns error: `ConnectionError: ('Connection aborted.', BadStatusLine('\x15\x03\x01\x00\x02\x02\n',))`.
My code:
```
from gophish import Gophish
api_key = 'user api key'
api = Gophish(api_key)

for campaign in api.campaigns.get():
    print campaign.name
```

**Comment by jordan-wright** [comment]
What is your admin server listen URL in your gophish config. Chances are, the API is using https and you're not or vice versa.

**Comment by jordan-wright** [comment]
You can find info on how to fix that [here](https://gophish.gitbooks.io/python-api-client/content/connecting-to-gophish.html).

**Comment by MihaRocket** [comment]
Oh sorry, I found out what was the problem. I forgot to write `verify=False`. Thanks anyway

**Comment by jordan-wright** [comment]
Good deal! Glad you were able to get it resolved.
