### ISSUE TITLE
Proxy/configuration for multiple campains with multiple domain name

### ISSUE THREAD

**Issue by Mlb66** [gophish/gophish#636]
Hello all,
I plan to run 3 campaigns simultaneously, each with a domain name and a landing page (with https access). In order to do that, the 3 landing pages should be "protected" by 3 different certificates (one for each domain). By design, gophish supports only one certificate.

I saw issue #349 that seems on the same need.

I'm thinking using a Apache server with virtual domains in front of the gophish server. Has anyone performed something like this ? Is there another way to try ?

**Comment by marcbudofsky** [comment]
@Mlb66 I've found that fronting GoPhish with Nginx works well for this - I create a new configuration for each domain name that I want to use, set up SSL (via letsencrypt) and then just proxy them all to point to the GoPhish server listening locally.

**Comment by jordan-wright** [comment]
Yep! That would be the way to do it. You can have a reverse proxy such as nginx or apache fronting Gophish to handle SSL termination. This will let you do all the cert juggling on the frontend and let Gophish handle traffic transparently.

I think the Nginx `proxy_pass` directive is what you're looking for. Here are a couple of resources that might help:

* [How To Configure Nginx with SSL as a Reverse Proxy for Jenkins](https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-with-ssl-as-a-reverse-proxy-for-jenkins)
* [Lets Encrypt with an nginx reverse proxy](https://serverfault.com/questions/768509/lets-encrypt-with-an-nginx-reverse-proxy)

**Comment by Mlb66** [comment]
Thanks for your (quick) replies.

I used the resources, and managed to do it with nginx in 10 min this morning.

If others find this thread, the Jenkins tuto mentioned by @jordan-wright is very-well adapted for gophish.
