### ISSUE TITLE
Scheduler uses inconsistent time source. 

### ISSUE THREAD

**Issue by nannal** [gophish/gophish#638]
Hi, 

We've recently had an issue where gophish was not sending out campaigns at the correct time, it was discovered that the client was entering the time into the scheduler which for them was "now" but due to DST reasons was "in 1 hour" to the server. 

Is it possible to reference the scheduled time directly from the servers system time & show its time when setting the schedule so as to avoid confusion.  

This in its worst case could mean that a client sets the time for scheduler up to 12 hours out of their intention which could fall well outside of the scoped timeframe.

**Comment by jordan-wright** [comment]
Thanks for the report @nannal! You're absolutely right, and this is an issue I'm planning on working out when I get the chance. I'll likely set it up where the datepicker is local to the server time and any datetimes returned by the API are in UTC for consistency.

I'm tracking this through #316 so I'll close this one out in favor of that issue.

Thanks again for the report!

**Comment by nannal** [comment]
Okay didn't know there was an issue already up for this, thanks for both confirming my suspicions and the promise of resolution.
