### ISSUE TITLE
 tls: unknown certificate authority

### ISSUE THREAD

**Issue by serpunja** [gophish/gophish#640]
![screenshot](https://cloud.githubusercontent.com/assets/24878620/26730012/3ad201ae-47b8-11e7-9560-17c38fa3e9d2.png)
 
conf:  openssl req -newkey rsa:2048 -nodes -keyout gophish_admin.key -x509 -days 365 -out gophish_admin.crt

Please help.

**Comment by jordan-wright** [comment]
Yes, this is also a self signed cert. If you don't want this error, you'll need to add the self signed cert to your device truststore or you'll need to use something like Let's Encrypt to generate a CA signed cert.

**Comment by serpunja** [comment]
>  "you'll need to add the self signed cert to your device truststore"
How to do this ?- link

**Comment by jordan-wright** [comment]
This is something that isn't Gophish specific. It would be quicker for you to do a Google search for your platform to find instructions.

https://www.google.com/search?num=100&q=add+self+signed+certificate+firefox

**Comment by serpunja** [comment]
O.K.
