### ISSUE TITLE
 Gophish tls: unknown certificate authority 

### ISSUE THREAD

**Issue by serpunja** [gophish/gophish#641]
![screenshot](https://cloud.githubusercontent.com/assets/24878620/26730012/3ad201ae-47b8-11e7-9560-17c38fa3e9d2.png)
 
conf:  openssl req -newkey rsa:2048 -nodes -keyout gophish_admin.key -x509 -days 365 -out gophish_admin.crt

Please help.

**Comment by jordan-wright** [comment]
Closing as duplicate of #640.
