### ISSUE TITLE
Not able to Get Results

### ISSUE THREAD

**Issue by AttackUnderWater** [gophish/gophish#642]
Hello,
I have configured and sent successfully a campaign. However I am not getting any results back. I have verified in the config.json that the ipaddress is the local on port 80 and that is what I put in the campaign config. The admin server works fine, the email is sent and received but no data goes back. I have turned the firewall off on that server as thought that may be the issue. There is no other service utilizing port 80. It is a server 2012 R2 dev server.
Any help would be greatly appreciated.

**Comment by jordan-wright** [comment]
What do you see when you hit the host on port 80?

**Comment by AttackUnderWater** [comment]
I get page not found. 404 Page not found?

**Comment by jordan-wright** [comment]
So it looks like you do manage to reach the phishing server. What does your email template look like? Are you using the {{.URL}} tags?

**Comment by jordan-wright** [comment]
@AttackUnderWater just checking in, what does your email template look like? Are you using the {{.URL}} tags?

**Comment by AttackUnderWater** [comment]
Soory got swamped i will che k on monday thanks



Chas Dodge
Network\System Administrator
Eggers Industries
920.562.2909
cdodge@eggersindustries.com


-------- Original message --------

**Comment by jordan-wright** [comment]
Going ahead and closing this since there hasn't been any updates in a good while. @AttackUnderWater if you're still running into issues, let me know and I'll be happy to re-open.

Thanks for getting in touch!
