### ISSUE TITLE
Alternate location for config file

### ISSUE THREAD

**Issue by kulinacs** [gophish/gophish#643]
It would be nice if a command line argument could be specified to allow the config file to be stored outside the current working directory, like `/etc/gophish/config.json`

**Comment by S0larflare** [comment]
You can move the whole thing to /etc/gophish and launch it from there.  You won't need to consider anything else unless you're changing the code and trying to build it again

Sent from my iPhone

On 3 Jun 2017, at 16:58, Nicklaus McClendon <notifications@github.com<mailto:notifications@github.com>> wrote:


It would be nice if a command line argument could be specified to allow the config file to be stored outside the current working directory, like /etc/gophish/config.json

**Comment by kulinacs** [comment]
I had considered that, but that doesn't follow the FHS. I'm looking to package this for a distro, so breaking things up according to the FHS is required.

**Comment by jordan-wright** [comment]
Yeah, it's a "todo" to create a flag to specify an alternate location for the config file. I'll keep this issue open to track that.

Thanks for the report!

**Comment by jordan-wright** [comment]
All fixed as of https://github.com/gophish/gophish/commit/772fe28c067bbd9ae291b26a1deaaf6ea9bea7ed. Just `go get -u ./...` and `go build` and you should be good to go.

The flag is `--config=config.json` or wherever you put your config.json file.

Let me know if you run into any issues!
