### ISSUE TITLE
Search suggestion is not working on IE where in Chrome and Firebox It is working perfectly.

### ISSUE THREAD

**Issue by anoopabbu** [gophish/gophish#644]
Search Suggestion is not working on IE, where It is working perfectly on Chrome and Firebox.
Package used for searching is Bloodhound.

**Comment by jordan-wright** [comment]
IE is not officially supported at the moment. It is recommended to use Gophish only with Chrome/FF.

**Comment by anoopabbu** [comment]
Thanks for your valuable feedback Mr. Jordan-wright
