### ISSUE TITLE
GPS Tracking - explained

### ISSUE THREAD

**Issue by ryan-es2** [gophish/gophish#645]
Hi all, 
I was hoping someone might be able to point me in the direction where I can find out how the tracking image can return GPS coordinates? I want to understand how this works so I can explain it, not sure exactly what to Google, particularly if it's a user on a mobile device, would it be based on the cell tower or does it somehow use the devices GPS.

Thanks in advance,

**Comment by jordan-wright** [comment]
Gophish doesn't use coordinates from the devices actual onboard GPS.

We use a free database offered by MaxMind which associates IP addresses to (fairly) accurate locations. It's not perfect, but does a decent job of getting down to the city/state/country level.

**Comment by ryan-es2** [comment]
Thanks for clarifying how this works. I was able to validate results with very high accuracy.
