### ISSUE TITLE
Change ClickedLink to something else

### ISSUE THREAD

**Issue by MihaRocket** [gophish/gophish#648]
I found this piece of code in gophish` Campaigns json:"campaigns" ClickedLink ...` and could I change 
ClickedLink to display something else (insert into 'events' value Test instead of ClickedLink)? Should I change it in binary file or should I change it in source code and compile it afterwards?

**Comment by jordan-wright** [comment]
Yes, you could change it. Changing the source will always be easier than patching the binary.

**Comment by jordan-wright** [comment]
Let me know if that didn't answer your question and we can reopen 😄
