### ISSUE TITLE
bulk import users using api

### ISSUE THREAD

**Issue by johnrachwan** [gophish/gophish#651]
I am trying to bulk import users into a group using a csv file the response its giving me is 200 but with an empty json file this is my code :

api_key = '25de4a855e175e75be278ba3636e5b7590be50f19a0f53d461daff4492bb18b9'
files = {'file': open('test.csv', 'rb')}
values = {'DB': 'photcat', 'OUT': 'csv', 'SHORT': 'short'}
response = requests.post("https://localhost:3333/api/import/group?api_key="+ api_key,files=files,data=values,verify=False)

Can anyone help me ?

**Comment by jordan-wright** [comment]
I'm going to assume that your `values` came from here: https://stackoverflow.com/questions/22567306/python-requests-file-upload. You don't need them with Gophish.

Other than that, your code _looks_ fine. What do you see if you print `response` and `response.text`?

**Comment by johnrachwan** [comment]
if i write response.text i dont get anything
if i type print response.json() i get empty brackets like this "{}"
Should the csv file have headers or not?
And in the documentation it is said to want firstname lastname position email and company why company?
i will attach the csv file i am using
![gophish](https://user-images.githubusercontent.com/29298441/26962964-83497220-4cf2-11e7-923f-e3b21ee118af.PNG)

**Comment by jordan-wright** [comment]
Yes, you need to include the headers. Does that change the response?

**Comment by johnrachwan** [comment]
No, as i showed the headers are already included in the csv file

**Comment by jordan-wright** [comment]
What output do you see in the Gophish terminal when you try to import the group? And to be clear, this endpoint doesn't actually make the group, it just returns JSON targets that can be used in the actual `api/groups` call later.

**Comment by johnrachwan** [comment]
I was able the csv in the gophish terminal no problem, but the response from the call to /api/import/group doesn't return anything at all. even though the server response is 200.
