### ISSUE TITLE
Track Image not work!

### ISSUE THREAD

**Issue by emresekeroglu** [gophish/gophish#654]
Hi, i dont track my campaigns. I tried every thing but i didn't get any results.
I use gmail profil.
And i tried on windows 10, kali linuz, linux mint and ubuntu. But i didn't get any results to these operating systems.

**Comment by jordan-wright** [comment]
There's not enough information to begin troubleshooting this.

We would need to know exactly what you tried, what errors you encountered (including screenshots, terminal output, etc.), what you expected to happen, what version of Gophish you're using, etc.

**Comment by jordan-wright** [comment]
@emresekeroglu just checking in - are you still running into issues? Please see the previous comment about what information we would need to help begin troubleshooting this. Without this information, there isn't much we can do.

**Comment by emresekeroglu** [comment]
Hi again yes i still get same issue,  i will try to explain the issue.
I do standart prosedure for tracking fake mail.
 Step 1: Install Sending Pofil with Gmail smtp ; smtp.gmail.com:465 (Mail sending don't get any issue for this step)
Step 2: Create Landing Page (Don't get any  issue for this step)
Step 3: Create an email templates and check tracking image, import to linkedin email  from mail source
Step 4: Create an user group
Step 5:  And finally I created the campaign by selecting the profiles (email templatre,landing page,sending profil, url and group)
Step 6: start the campaign end sending mail. I'm control the mail i got the mail and i open , clik the url. However i can't see dassboard opened or clicked info only last info 'email sent'

I hope telling true English grammer and you understandt me.

**Comment by jordan-wright** [comment]
Thanks for the update @emresekeroglu! What do you see when you click the link? Do you get a 404 page or do you see the correct landing page?

If you just see a "Connection refused" message or similar, there is some kind of networking or config problem preventing you from reaching the Gophish instance.

If you get a 404 page, there's likely something wrong with your template.

Let us know and we can continue troubleshooting.

**Comment by jordan-wright** [comment]
Just checking in @emresekeroglu, are you still running into issues? If so, please see the comment above and provide the requested information and we will continue troubleshooting.
