### ISSUE TITLE
Issue Capturing submitted data

### ISSUE THREAD

**Issue by conway220** [gophish/gophish#655]
I am unable to capture the submitted data. It completely doesn't show that it is capturing anything As seen in this image 
![image](https://user-images.githubusercontent.com/20257911/27146482-796aeb44-5107-11e7-99cd-878167a4cc2b.PNG)
It is enabled, as seen here:
![image2](https://user-images.githubusercontent.com/20257911/27146493-88256e66-5107-11e7-9314-80cd8ad35798.PNG)

This is an example of one of the forms 
`<form action="" style="padding-left:5px; padding-bottom: 10px; padding-top:10px">Full Legal Name : <input size="50" type="text"/> </form>`
This is my submit button, I don't know if this is preventing data capture
`<form action="" style="text-align:center"><input onclick="window.location.href=&#39;http://georgia.gov/&#39;" type="button" value="Submit"/> </form>`

Any help would be appreciated. Thank you!

**Comment by jordan-wright** [comment]
It's possible that the onclick is preventing the form submission. You might try removing that and see if that helps.

Also, any form inputs you want to capture need a "name" attribute specified. If you save a form without capturing data enabled, we remove these so if you then enable capturing data you'll have to re-add them manually.

**Comment by conway220** [comment]
Changing the submit button fixed it. Thank you!
