### ISSUE TITLE
GoPhish v0.3 Intermediate CA

### ISSUE THREAD

**Issue by horric29** [gophish/gophish#656]
I know the general answer in the past has been no support beyond self signed but, I have a public cert from GoDaddy for the site in question, and it's failing on some devices due to an intermediate certificate need from GoDaddy.  I have the intermediate certificate but, I'm having trouble figuring out how to use it with the standalone installer of GoPhish on Windows.  My problem devices are MAC's so I have the intermediate CA, just need to know how/what to do with it.  Without knowing the web server in use on the standalone I can't figure out how to actually import the intermediate CA.  

The use case is remote sales workers that we are trying to test which will need to access the public facing site on iDevices if they click on the phishing link.

**Comment by horric29** [comment]
I figured this out, it can be closed but, maybe helpful to other people.  I don't know what the web server is but, if its anything like NGINX the various certificates have to be concatenated together into one cert.  Super simple in windows  "type downloaded_certauthority_key.crt intermediate_certauthority_key.crt bundle_certauthority_key.crt > new_key.crt"  Do that, change the key name in config.json, reboot the gophish process, good to go!

**Comment by jordan-wright** [comment]
Good deal! Glad you were able to figure it out, and I appreciate you posting your solution. 😄
