### ISSUE TITLE
Provide static download links for latest versions.

### ISSUE THREAD

**Issue by derpadoo** [gophish/gophish#657]
Automating Gophish deployment and would like to pull the latest version from a static link.  The current latest link, https://github.com/gophish/gophish/releases/download/v0.3.0/gophish-v0.3-linux-64bit.zip, will change when the Gophish version is updated.

As an example, Metasploit provides http://downloads.metasploit.com/data/releases/metasploit-latest-linux-x64-installer.run which pulls the latest version and the link doesn't need to be updated in scripts based on the version number.

**Comment by jordan-wright** [comment]
I think I got this working with Cloudflare's Page Rules.

You should be able to hit https://getgophish.com/releases/latest/windows/64 where "windows" and "64" are the OS/architecture found on the [Releases](https://github.com/gophish/gophish/releases) page.

I'll manually update this page rule to point to the latest version when a new version is deployed (until I have time to automate it).

**Comment by derpadoo** [comment]
That did the trick...thank you!
