### ISSUE TITLE
How to remove duplicates from an array

### ISSUE THREAD

**Issue by anoopabbu** [gophish/gophish#663]
Please help me out to remove duplicate as Distinct is not supported by jinzhu gorm.
u := []UserDetailss{}
err = db.Table("users").Select("id,username,company_id").Where("company_id like ? AND roles=?", "%," + id + ",%",1).Find(&u).Error
if err != nil {
       Logger.Println(err)
        return us, err
}

**Comment by jordan-wright** [comment]
This is an issue you should make on the [jinzhu/gorm](https://github.com/jinzhu/gorm) repository. We cannot provide support for all the libraries used by Gophish.
