### ISSUE TITLE
Does it support "Attachment-Support"?

### ISSUE THREAD

**Issue by hakawati** [gophish/gophish#664]
I really need this feature.
It looks like it's available in version 0.2,
If possible, can you support it in version 0.3?

**Comment by jordan-wright** [comment]
We are tracking this issue through #227, so I'm going to close this out as a duplicate. There are multiple challenges to supporting attachment tracking in a meaningful way that works for the most people so I don't see it making the next release.

Keep an eye on issue #227 for any updates to that feature.
