### ISSUE TITLE
Open Tracking has stopped working, TLS errors

### ISSUE THREAD

**Issue by aj-broadhurst** [gophish/gophish#665]
Hey, I'm back with another question. I got everything set up great, and was successful in the first wave of emails. However, we're getting ready to send out a second wave of emails, but the open tracking has stopped working. It was previously all good, opens were tracking properly in both tests and actual execution. Now I'm getting TLS handshake errors, which I can tell are linked to the opens. If I send myself a mail, and try and open it, I get an error that links back to my IP.

The following is a sample of some of the errors:
```
2017/06/22 09:42:13 http: TLS handshake error from IP: tls: no cipher suite supported by both client and server
2017/06/22 16:59:14 http: TLS handshake error from IP: local error: tls: bad record MAC
2017/06/22 17:23:31 http: TLS handshake error from IP: tls: oversized record received with length 29556
2017/06/22 19:31:23 http: TLS handshake error from IP: tls: unsupported SSLv2 handshake received
2017/06/22 19:31:23 http: TLS handshake error from IP: tls: client offered an unsupported, maximum protocol version of 300
```
Any help in getting this resolved is greatly appreciated.  Thanks!

**Comment by jordan-wright** [comment]
Did anything change between this test and the previous one? Did you use a different Gophish version or config? Can you list parts of the config for your `phish_server`? Specifically the (redacted as necessary - we really just need the scheme) URL + the `use_tls` setting?

The TLS handshake errors are interesting... Especially since they're different errors spread out over a series of events.

**Comment by aj-broadhurst** [comment]
No, nothing changed. Same config, same version of Gophish. Yeah, I found it interesting as well. The errors repeat, but I can't seem to find a common denominator on when a type of error occurs. There's also one more error it looks like I missed adding:
`http: TLS handshake error from IP: EOF`
Here are the contents.
```
{
        "admin_server" : {
                "listen_url" : "127.0.0.1:3333",
                "use_tls" : true,
                "cert_path" : "gophish_admin.crt",
                "key_path" : "gophish_admin.key"
        },
        "phish_server" : {
                "listen_url" : "0.0.0.0:443",
                "use_tls" : true,
                "cert_path" : "/etc/letsencrypt/live/domain.com/cert.pem",
                "key_path": "/etc/letsencrypt/live/domain.com.com/privkey.pem"
        },
        "db_name" : "mysql",
        "db_path" : "usr:pswd@(:3306)/gophish?charset=utf8&p$
        "migrations_prefix" : "db/db_"
}
```

**Comment by jordan-wright** [comment]
It's odd because most of those errors look like they would originate from really, really old clients (only SSLv2 supported, no common cipher suites, etc.) And the config file looks fine to me.

What browser are you using? Do these errors appear every time you try and open the page in your browser?

**Comment by aj-broadhurst** [comment]
We're using Chrome. The errors are sporadic, sometimes open tracking works and sometimes it doesn't. I just got the go ahead to send another wave out, so I suppose this is less of a critical issue now, though I'd still like to get to the bottom of the errors if possible.

**Comment by jordan-wright** [comment]
Sorry for the delay in revisiting this. Are you still seeing these TLS errors?

If so, is it perfectly correlated to actually opening the email with an email client, or do you have a spam appliance that may be doing link checking when emails are being received?

**Comment by harshkrsingh** [comment]
i am facing the similar issue 
![image](https://github.com/user-attachments/assets/48747f67-3440-4afc-afc4-2e2e34578877)
