### ISSUE TITLE
GoPhish in Windows

### ISSUE THREAD

**Issue by Tiym** [gophish/gophish#667]
I'm trying to run GoPhish on a Windows PC (actually on 3 different PCs, running 7, 8.1 and 10).  I'm successfully sending emails and importing email templates.
My difficulty seems to be with the URL field in the Campaign.  Do I need to set up a VPS and use a URL associated with that?

**Comment by jordan-wright** [comment]
The URL needs to be the IP address or domain name of the windows machine running Gophish. It needs to be accessible to all clients who receive the emails.

**Comment by Tiym** [comment]
Thanks Jordan.  Probably should have been obvious!  I've now reached the landing page and recored my click on the link - success.
