### ISSUE TITLE
Send test email: Host not found

### ISSUE THREAD

**Issue by Svanekongen** [gophish/gophish#671]
Hello,

when i try to send a test mail, it gives me this error 

![hostnotfound](https://user-images.githubusercontent.com/29792723/27730590-0e5aa206-5d8a-11e7-827a-240fa2c44c09.png)

my dns works fine, and my mailserver is running iRedMail. i can send mails from one domain to another, but not from gophish

**Comment by jordan-wright** [comment]
Can you show what your sending config looks like? And we'll also want to see the output of running "dig" or "nslookup" from your host against the host name you have in your sending profile.

**Comment by Svanekongen** [comment]
i managed to find out that the issue was in my dns. thanks
