### ISSUE TITLE
Server misbehaving.

### ISSUE THREAD

**Issue by Svanekongen** [gophish/gophish#672]
Hello,

can you help med with this error?

dial tcp: lookup mailserver.fred3riksberg.dk on 192.168.0.20:53: server misbehaving

**Comment by jordan-wright** [comment]
This is also related to your DNS server. I'm afraid there really isn't anything we can do from the Gophish end to help diagnose this.

It looks like the error is thrown when there's an unexpected rcode being returned:

https://golang.org/src/net/dnsclient.go#L46

**Comment by jordan-wright** [comment]
Closing this one out since it almost certainly isn't related to Gophish. @Svanekongen please let us know if you come across any other information that shows this is a bug in Gophish itself.
