### ISSUE TITLE
/usr/bin/ld: $WORK/libgo-sqlite3.a410933476(sqlite3-binding.o): undefined reference to symbol 'pthread_mutexattr_settype@@GLIBC_2.2.5'

### ISSUE THREAD

**Issue by firebitsbr** [gophish/gophish#678]
VM Fedora 25 x86_64
Linux localhost.localdomain 4.11.8-200.fc25.x86_64 #1 SMP Thu Jun 29 16:13:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

go version go1.6.1 gccgo (GCC) 6.3.1 20161221 (Red Hat 6.3.1-1) linux/amd64

go build gophish.go

# command-line-arguments
/usr/bin/ld: $WORK/libgo-sqlite3.a410933476(sqlite3-binding.o): undefined reference to symbol 'pthread_mutexattr_settype@@GLIBC_2.2.5'
/usr/lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

@firebitsbr

**Comment by S0larflare** [comment]
If you're building from source, the command is just "go build". When it is finished, run the binary which has been built.

Sent from my iPhone

On 4 Jul 2017, at 22:08, Mauro Risonho de Paula Assumpcao <notifications@github.com<mailto:notifications@github.com>> wrote:


VM Fedora 25 x86_64
Linux localhost.localdomain 4.11.8-200.fc25.x86_64 #1<https://github.com/gophish/gophish/issues/1> SMP Thu Jun 29 16:13:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

go version go1.6.1 gccgo (GCC) 6.3.1 20161221 (Red Hat 6.3.1-1) linux/amd64

go build gophish.go

command-line-arguments

/usr/bin/ld: $WORK/libgo-sqlite3.a410933476(sqlite3-binding.o): undefined reference to symbol 'pthread_mutexattr_settype@@GLIBC_2.2.5'
/usr/lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

@firebitsbr<https://github.com/firebitsbr>

**Comment by jordan-wright** [comment]
Hey @firebitsbr just checking in, did @S0larflare's fix correct the issue?

**Comment by jordan-wright** [comment]
Closing this out as there haven't been any updates in two weeks. @firebitsbr let us know if @S0larflare's fix didn't work and we can continue to troubleshoot.
