### ISSUE TITLE
New Dashboard Graphs

### ISSUE THREAD

**Issue by jordan-wright** [gophish/gophish#680]
Related to #676 

When I first set out making Gophish, I wanted to use Highcharts for the graphs. The issue at the time is that Highcharts is free for OSS projects, but for non-OSS projects there is a significant licensing fee. With the original intent to have a paid Gophish option, I opted to use Chartist.js to generate graphs, which isn't nearly as powerful as Highcharts.

However, I've since decided that Gophish will always be 100% OSS. Therefore I've started the process of converting our graphs to Highcharts. This means the graphs are simpler code-wise, can now have zooming (for timelines), and will be responsive in most browsers 🎊 

Here's what the new dashboard graphs are looking like so far:

![image](https://user-images.githubusercontent.com/1317288/27941933-e72d302c-6298-11e7-9db1-fe592c79c61e.png)

### Graph Changes

There are a couple of changes to note with these new graphs. **They will also affect the results from the API.**

In a nutshell, some of the values we're getting back in the API are _slightly_ misleading depending on how they're interpreted. Every result in a campaign has a status, and we're only showing/graphing the current status for each result.

This sort of makes sense when things are in one pie chart, but when we split things out, this makes things a bit skewed. You may see 5 results with the status "clicked link", 1 result with the status "email opened", and 1 result with the status "email sent". We don't want to graph those values as-is, since it's assumed that if you clicked the link, you also opened the email, and you also received the email, etc.

Our graphs will compensate for this (even though the screenshot doesn't show it 😉). We will backfill the results accordingly. So, if a result status is "clicked link", we will backfill "email opened" and "email sent" in the graphs so that when looking at the campaign results, you will see those cumulative values.

These changes will be coming out fairly soon, I'm just finishing up the code this next week. Let me know if you have any questions or thoughts! My goal is to make sure everyone is on the same page before this is rolled out.

**Comment by andyg1** [comment]
@jordan-wright this is great news and a great step in the right direction. People I have been working with have fallen foul of the confusing total numbers trap a few times. We'd been experimenting with using GoReport as an alternative method of getting stats - 1) because (in the "quick" flag) it reports the numbers as per your description for your new graphing tool, and 2) the page load time on campaigns with large cohorts is too slow. GoReport bypasses this, but comes with the disadvantage of having to go into the terminal to get it....
I look forward to the launch of this new feature. Keep up the good work.

**Comment by S0larflare** [comment]
I quite like the look of this (although I quite like the current pie charts too!). This would be a good one to have user customisations built for it in the settings (colour of the graph etc). When you get it implimented I'll start looking in to adding to the settings page as a stop gap until a more perminent solution is implimented.

Good job as always

**Comment by S0larflare** [comment]
Just downloaded the latest source to have a look at this, really like it, good job!
