### ISSUE TITLE
Windows Install

### ISSUE THREAD

**Issue by dibadasa** [gophish/gophish#681]
Hello all, Having a lot of trouble with the windows install. Does anyone has any instructions on how to get the install to work??

**Comment by S0larflare** [comment]
There are instructions in the documentation. Are you building from source or using a prebuilt binary? What are you struggling with?

Sent from my iPhone

On 7 Jul 2017, at 19:08, dibadasa <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello all, Having a lot of trouble with the windows install. Does anyone has any instructions on how to get the install to work??

**Comment by jordan-wright** [comment]
Hi @dibadasa, as @S0larflare mentioned, we have installation instructions in [our documentation](https://gophish.gitbooks.io/user-guide/content/installation.html). In a nutshell, installation should be as simple as downloaded the zip file, extracting it to a folder, and executing the included `gophish.exe` file.

If you have any specific questions about installation, please don't hesitate to let us know. For now, I'm going to close this out since there hasn't been any updates in a few days. I can re-open as needed.

**Comment by dibadasa** [comment]
Please reopen the ticket, i'm just not able to run the program. I'm executed gophish.exe file, made changes to the config file, but still unable to run the program. 

Is there anything else I need to do? 

Please advise. 

Thanks!

**Comment by S0larflare** [comment]
try running gophish in a cmd window, what does the console say - are there any errors?

**Comment by dibadasa** [comment]
got this message.
please advise.
Thanks!
C:\>gophish
2017/07/12 14:40:54 worker.go:36: Background Worker Started Successfully - Wait
ing for Campaigns
goose: no migrations to run. current version: 20170219122503
2017/07/12 14:40:54 gophish.go:83: Starting phishing server at http://0.0.0.0:8
0
2017/07/12 14:40:54 gophish.go:84: listen tcp 0.0.0.0:80: bind: An attempt was
made to access a socket in a way forbidden by its access permissions.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by S0larflare** [comment]
It's likely that either something else is using port 80 already (are you running apache for example? I think someone traced it down to skype even) or that you don't have the permissions to bind the port. Try running a cmd prompt as admin and running gophish in that to see

Sent from my iPhone

On 12 Jul 2017, at 20:42, dibadasa <notifications@github.com<mailto:notifications@github.com>> wrote:

got this message.
please advise.
Thanks!
C:\>gophish
2017/07/12 14:40:54 worker.go:36: Background Worker Started Successfully - Wait
ing for Campaigns
goose: no migrations to run. current version: 20170219122503
2017/07/12 14:40:54 gophish.go:83: Starting phishing server at http://0.0.0.0:8
0
2017/07/12 14:40:54 gophish.go:84: listen tcp 0.0.0.0:80: bind: An attempt was
made to access a socket in a way forbidden by its access permissions.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by dibadasa** [comment]
Its a windows box, with local admin rights to the machine.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

> -------- Original Message --------
> Subject: Re: [gophish/gophish] Windows Install (#681)
> Local Time: July 12, 2017 3:54 PM
> UTC Time: July 12, 2017 8:54 PM
> From: notifications@github.com
> To: gophish/gophish <gophish@noreply.github.com>
> dibadasa <asad.abid@protonmail.com>, Mention <mention@noreply.github.com>
> It's likely that either something else is using port 80 already (are you running apache for example? I think someone traced it down to skype even) or that you don't have the permissions to bind the port. Try running a cmd prompt as admin and running gophish in that to see
> Sent from my iPhone

**Comment by dibadasa** [comment]
got it!!! working great now.. was issue with the local machine..
Thanks for all the help and assistance.. if the case is still open, please proceed with the close and resolved case.
Thanks,
Asad.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

> -------- Original Message --------
> Subject: Re: [gophish/gophish] Windows Install (#681)
> Local Time: July 13, 2017 8:56 AM
> UTC Time: July 13, 2017 1:56 PM
> From: asad.abid@protonmail.com
> To: gophish/gophish <reply@reply.github.com>
> Its a windows box, with local admin rights to the machine.
>
> Sent with [ProtonMail](https://protonmail.com) Secure Email.
>
>> -------- Original Message --------
>> Subject: Re: [gophish/gophish] Windows Install (#681)
>> Local Time: July 12, 2017 3:54 PM
>> UTC Time: July 12, 2017 8:54 PM
>> From: notifications@github.com
>> To: gophish/gophish <gophish@noreply.github.com>
>> dibadasa <asad.abid@protonmail.com>, Mention <mention@noreply.github.com>
>> It's likely that either something else is using port 80 already (are you running apache for example? I think someone traced it down to skype even) or that you don't have the permissions to bind the port. Try running a cmd prompt as admin and running gophish in that to see
>> Sent from my iPhone
