### ISSUE TITLE
How to view status: email was opened

### ISSUE THREAD

**Issue by tyago19** [gophish/gophish#683]
I installed goPhish did some tests, however the status "Opened" has not yet appeared in my timeline.
Is there a specific setting to see if the email was opened?

Best Regards,
Miranda.

**Comment by jordan-wright** [comment]
In many cases, email clients do not load external images due to privacy reasons. Does Gophish recognize clicked link events? If so, it's likely the case that the email client is setup to not load external images.

**Comment by tyago19** [comment]
Click event links are recognized.
What did you mean when you said "the email client is setup to not load external images."?

**Comment by jordan-wright** [comment]
Gophish tracks email opens by adding a link to an image hosted on the Gophish server. This is a common technique used by phishers and email marketers to track when an email has been opened.

This is a privacy risk. So, to protect privacy, some email clients like Outlook will prevent these images from being loaded. That's likely the case here.

Unfortunately, there isn't anything Gophish can do about that since that is a setting within the email client.

**Comment by riot1502** [comment]
![image](https://user-images.githubusercontent.com/20999504/28102075-7fb0cd7a-6692-11e7-8510-65feabe247a5.png)

Does the image look like such when getting blocked by Outlook?

**Comment by S0larflare** [comment]
Yes, it will look like that unless they choose to download the image when they get the ribbon pop up on the email "Outlook has blocked automatic download of pictures in this email" or something to that effect. Do you run your campaigns internally, or from outside of the company?

**Comment by riot1502** [comment]
I just started testing to myself & saw this happening.  Campaigns are being run internally right now.

**Comment by tyago19** [comment]
How do I host an image on the gophish server? And for cases that I will do the tests outside the company?

**Comment by jordan-wright** [comment]
The images are hosted on the Gophish server automatically when you select "Add tracking image" on the email template.

As with any campaign and specified in our docs, it's important that every targeted user is able to reach your Gophish instance. This may require exposing the Gophish phishing interface to the Internet.

**Comment by tyago19** [comment]
When I click on "Add tracking image" no image appears in the body of the email. Should it appear?

**Comment by tyago19** [comment]
It works now!

**Comment by jordan-wright** [comment]
Excellent, I'm glad to hear you were able to get it resolved.

**Comment by wilsonlht** [comment]
Hi tyago19, how do you solve it?

**Comment by tyago19** [comment]
The way Gophish tracks whether or not the email was opened is by adding a link to a hosted image on the server.
It is important to note that some e-mail clients are configured not to upload these images.

In this case you need to release on the email server to automatically load the images.

**Comment by wilsonlht** [comment]
Hi,

How to do that? My env is using Exchange.
