### ISSUE TITLE
Failing to run on a VPS running Windows 2012 r2

### ISSUE THREAD

**Issue by Tiym** [gophish/gophish#684]
GoPhish was running OK on my Windows 7 PC.  For various reasons I wanted to move to a VPS - this is running Windows 2012 r2.  I'm using the same config file.  When I run GoPhish the command window starts up and runs for about 1 second then disappears.
Any thoughts?  Do I need to change the config file? Server settings?

**Comment by jordan-wright** [comment]
What happens when you try to run it from a command prompt? So open cmd, cd into that directory and run gophish.exe. You should see the error that's occurring.

**Comment by Tiym** [comment]
I've run it from Powershell.  The first error message is:
File error: open .config.json: The system cannot find the file specified

config.json is in the same folder as gophish.exe

**Comment by Tiym** [comment]
Ok.  I foolishly thought I could run it without into the actual directory, just providing a path.  When run from the directory containing gophish.exe I get (omitting timestamps):
Background worker started successfully - waiting for campaigns
models.go:98: no valid version found
no valid version found
gophish.go:83: Starting phishing server at http://
gophish.go:70: Starting admin server at http://
gophish.go:84: listen tcp  :80:  bind:  An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by jordan-wright** [comment]
I think this is an issue thats popped up before. You might try referring to [these issues](https://github.com/gophish/gophish/search?q=bind&type=Issues&utf8=%E2%9C%93) to see if they help.

**Comment by Tiym** [comment]
Thanks Jordan.  I've been through all the issues in that list and edited the config.json file to try all the suggested ports.  Each time I get exactly the same sequence of messages.
