### ISSUE TITLE
Failed to run on Windows Server 2012 R2

### ISSUE THREAD

**Issue by InternSta** [gophish/gophish#687]
At the University I work at we had gophish set up on sqlite3, but decided we would migrate to MySQL. However since the migration tool wasn't working I decided to start from scratch. The database is set up but gophish isn't running. I don't know if the config file isn't set up properly or if its something to do with MySQL.

**Comment by S0larflare** [comment]
Can you post the config file? Have you set it to mysql?

**Comment by jordan-wright** [comment]
Hi @InternSta, just checking in, could you provide the information requested by @S0larflare? We'll be happy to help troubleshoot when we receive the updated information.
