### ISSUE TITLE
Can we have video page with viewers report

### ISSUE THREAD

**Issue by amol7111** [gophish/gophish#688]
Hey

Can we have video for failures and keep track of how much time every failure on that video.

It will add great thing for reporting.

**Comment by jordan-wright** [comment]
I don't have the time or resources to make something like this in the forseeable future. I'm planning on adding the idea of "training pages" but they will just be static landing pages like what we have now.

If you know of any graphic designers or producers interested in donating time to create professional videos for Gophish, please don't hesitate to send them my way. I'm always open to contributions.
