### ISSUE TITLE
Redirect Function Issues

### ISSUE THREAD

**Issue by loza0269** [gophish/gophish#690]
Hello,

I don't want to reopen past issues, but short of changing the source and building is there anyway i can fix this redirect issue.

I have a Dropbox login page as my landing page and want to redirect them to Dropbox.com (or anywhere) and when they submit data they get an error and stays on the login page. Any Ideas?

**Comment by jordan-wright** [comment]
What error do they receive? It's likely the case that the form is submitted by JavaScript included on the imported landing page. You'll need to adjust the HTML to ensure that JavaScript isn't interfering with the form submission.

**Comment by loza0269** [comment]
I'm receiving either a 401 or 405 error when I look in my browser console. I'm using Google Chrome. I tried using IE but no change. I believe its blocking due to redirecting from an internal domain to external.

**Comment by jordan-wright** [comment]
Yeah, sounds like there's something going on with the landing page, not necessarily Gophish itself. Youll want to make sure the landing page is using just a generic form to submit credentials.

**Comment by loza0269** [comment]
Well the form is submitting their credentials, but not redirecting out of the page.

**Comment by jordan-wright** [comment]
I'm afraid we'll need more information to help troubleshoot this, since we haven't been given much to go off of.

Where are the credentials being sent?
Are you sure they're going to the Gophish server?
What does the form in the HTML look like?
How did you set up your landing page in Gophish?
What is the response you receive (the full response) when the credentials are submitted?

**Comment by jordan-wright** [comment]
Going ahead and closing this since there haven't been any updates in a while. @loza0269 if you are still running into issues, take a look at the comment above and, if you can provide that info, I'd be more than happy to re-open this and we can continue troubleshooting.
