### ISSUE TITLE
email stuck for groups but working individually 

### ISSUE THREAD

**Issue by amol7111** [gophish/gophish#695]
Hey

I tried to create campaigns with group of people, but it stays ques. i tried to send test mail and it is working.

Let me know what should i try.

**Comment by jordan-wright** [comment]
What does "it stays ques." mean? Are there any errors in the Gophish terminal you can see when you try to launch the campaign?

**Comment by pranabk2** [comment]
It might be due to different time zone issues. Are you using Gophish server from your same time zone or different time zone?

**Comment by jordan-wright** [comment]
Closing this out since there haven't been any updates in a while. @amol7111 if you're still running into issues, let us know if @pranabk2's suggestion helped as well as answers to my previous comment and we can continue troubleshooting.
