### ISSUE TITLE
Use TLS on phish_server

### ISSUE THREAD

**Issue by Jintirpki** [gophish/gophish#696]
Hello! Can I use TLS on phishing sites? (Then my phish sites open:  https://127.0.0.1)
Just when I wrote in config.json:
    "phish_server" : {
                "listen_url" : "0.0.0.0:80",
                "use_tls" : true,
                "cert_path" : "example.crt",
                "key_path": "example.key"
} "

Gophish didn't starting. Please help me! : )

**Comment by S0larflare** [comment]
Yes, though with a bit of work. 1st, you would want to change the listening port from 80 to 443. Then you would need a certificate (im assuming example.crt and example.key don't actually exist in the dorectory). If you're wanting the certificate to be trusted, you'll either want to use an internal pki or something like lets encrypt

Sent from my iPhone

On 19 Jul 2017, at 10:32, Jintirpki <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello! Can I use TLS on phishing sites? (Then my phish sites open: https://127.0.0.1)
Just when I wrote in config.json:
"phish_server" : {
"listen_url" : "0.0.0.0:80",
"use_tls" : true,
"cert_path" : "example.crt",
"key_path": "example.key"
} "

Gophish didn't starting. Please help me! : )

**Comment by Jintirpki** [comment]
@S0larflare Thanks very much! 
I resolved my problem, 1st I use internal pki via command:

openssl req -newkey rsa:2048 -nodes -keyout gophish.key -x509 -days 365 -out gophish.crt

And change port from 80 to 443 and my config.json:

        "admin_server" : {
                "listen_url" : "MyServerIp:3333",
                "use_tls" : true,
                "cert_path" : "gophish_admin.crt",
                "key_path" : "gophish_admin.key"
        },
        "phish_server" : {
                "listen_url" : "0.0.0.0:443",
                "use_tls" : true,
                "cert_path" : "gophish.crt",
                "key_path": "gophish.key"
        },
       "db_name" : "sqlite3",
        "db_path" : "gophish.db",
        "migrations_prefix" : "db/db_"
}

You very helped me out! Thank you! : )
