### ISSUE TITLE
Gophish api Windows

### ISSUE THREAD

**Issue by Sun-098** [gophish/gophish#697]
@jordan-wright 

[No groups specified] - {if I leave off the groups data from below} -> When I get an old campaign data and post it 
or
[Invalid JSON structure] - {if the groups data is included}
I am getting this error when I try launch a campaign through api. I have search in many places I could not find a solution I tried with https://gitter.im/gophish/gophish?at=57a8f041f7f11a7936ad2886 solution but still i get it as invalid json structure
Any suggestions??

When I use api.campaigns.get() and store it in a json file, when use that for a new campaign json structure I get the output as Invalid json structure
 Please help

**Comment by jordan-wright** [comment]
Can you put the code your trying in this issue? Then we can continue trying to troubleshoot it.

**Comment by jordan-wright** [comment]
Closing this out since there hasn't been any updates in a good while.
