### ISSUE TITLE
API Campaign launch issue

### ISSUE THREAD

**Issue by Sun-098** [gophish/gophish#698]
Hi,

I'm using the below code to launch a campaign through API but I get an error "    group = [groups(name='XXX')]
TypeError: 'list' object is not callable" and I am not sure what to do with this
```python
import json
import requests
from gophish.models import *
from gophish.api import APIEndpoint
from gophish import Gophish
from pprint import pprint

api_key = 'XXX'
api = Gophish(api_key)
url= 'http://localhost:3333/api/campaigns/?api_key=XXX'
groups = api.groups.get()
pages = api.pages.get()
smtp = api.smtp.get()
templates = api.templates.get()
campaigns = api.campaigns.get()
group = [groups(name='XXX')]
page = pages(name='XXX')
template = templates(name='XXX')
profile = smtp(name='XXX')
url = 'http://XXX'
campaign = campaigns(
    name='API_Campaign', groups=groups, page=page,
    template=template, profile=profile)

campaign = api.campaigns.post(campaign)
for campaign in api.campaigns.get():
    print campaign.id
```

**Comment by jordan-wright** [comment]
`api.groups.get()` should return a list of groups. You are storing this in the `groups` variable.

You then later try to call this list as a function with the call to `groups(name='XXX')`, which won't work. You will need to iterate over the list and find the group with the right name.

Something like:

```python
def get_group_by_name(name):
    groups = api.groups.get():
    for group in groups:
        if group.name == name:
            return group
    return None
```

Hope this helps! The same situation would apply to the other types of data  (`pages`, `smtp`, etc.)

**Comment by Sun-098** [comment]
I get the below error:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\automaton\Working\trial_campaign.py", line 62, in <module>
    campaign = api.campaigns.post(campaign)
  File "C:\Python27\lib\gophish\api\campaigns.py", line 21, in post
    return super(API, self).post(campaign)
  File "C:\Python27\lib\gophish\api\api.py", line 64, in post
    response = self.api.execute("POST", self.endpoint, json=(resource.as_dict()))
  File "C:\Python27\lib\gophish\models.py", line 24, in as_dict
    val = val.as_dict()
AttributeError: 'unicode' object has no attribute 'as_dict'

**Comment by RobinXaXa** [comment]
Hey sun,
 you can use this to manually create a campaign:

def Ajout_Campagne_Manuel():
	urlph = <your tracker url>
	groupe = [Group(name= <group name>)]

	name = raw_input("Campaign name ?")

	sender0 = raw_input("Sender Name"? )
	sender = SMTP(name=sender0)

	template0 = raw_input("Template name? ")
	template = Template(name=template0)

	landing0 = raw_input("name of the landing page")
	landing= Page(name=garage0)

	campaign  = Campaign(name=name, groups=groupe, page=landing,template=template, 
                             smtp=sender, url=urlph)
	campaign = api.campaigns.post(campaign)
	try:
		print campaign.name, ' id: ', campaign.id
	except:
		print campaign.message

or you can use my beatiful repo:
https://github.com/RobinXaXa/Gophish-controller
i've updated the wiki in english, but there might be some typos feel free to open an issue if there's something you don't understand.

Cheers,

**Comment by Sun-098** [comment]
Hi RobinXaXa,
Thanks buddy!!!
What is this tracker URL? Is it the phish server(7070) or admin server(3333)?

**Comment by RobinXaXa** [comment]
the tracker URL is the phish server, 7070 in your case

**Comment by haxpak** [comment]
I am facing a problem with invalid JSON structure
```python
def GoSend(group):
    pages = api.pages.get()
    for page in pages:
        if (page.name == 'test'):
            toSendPage = page
    templates = api.templates.get()
    for template in templates:
        if (template.name == 'Key'):
            toSendTemplate = template
    senders = api.smtp.get()
    for sender in senders:
        if (sender.name == 'UWP keygen'):
            toSendSmtp = sender
    # toSendGroup = [Group(name=group.name)]
    # toSendPage = Page(name='test')
    # toSendTemplate = Template(name='Key')
    # toSendsmtp = SMTP(name='UWP keygen')
    toSendUrl = "<redacted>"
    campaign = Campaign(
    name=group.name, groups=group, page=toSendPage, 
    template=toSendTemplate, smtp=toSendSmtp, url=toSendUrl)
    result = api.campaigns.post(campaign)
    debug("[*] {} GoSend complete".format(ln()))
    return result
```

I am getting the following error :

```.
.
.
.
File "/usr/local/lib/python3.7/dist-packages/gophish/api/campaigns.py", line 20, in post
    return super(API, self).post(campaign)
  File "/usr/local/lib/python3.7/dist-packages/gophish/api/api.py", line 92, in post
    raise Error.parse(response.json())
gophish.models.Error: Invalid JSON structure
```
