### ISSUE TITLE
Use domain on phish site

### ISSUE THREAD

**Issue by Jintirpki** [gophish/gophish#699]
Hello, community!

Can I change name for phish sites?
By default Gophish called phish sites like this http://127.0.0.1/?rid=YWOHrpw. 

It would be great if user himself defined domain for phish site, for example http://127.0.0.1/blabla/example/phish_server/domain

**Comment by jordan-wright** [comment]
I believe you can specify any path except for `/track` since that's used by Gophish. You would specify this in the URL field when creating the campaign.

If this doesn't work, let me know what you're trying and what you're seeing and we can continue troubleshooting.

Thanks for the report!

**Comment by Jintirpki** [comment]
@jordan-wright Thank you! You're resolved my problem! :1st_place_medal:
