### ISSUE TITLE
Delay between send messages

### ISSUE THREAD

**Issue by Jintirpki** [gophish/gophish#700]
Do Gophish delay between send? And if does that  what time is it?

**Comment by pranabk2** [comment]
I also encountered this problem. You need to set the server time and your browser time the same geo location to overcome this issue.

**Comment by jordan-wright** [comment]
There is a worker that polls every minute for new campaigns to send. If you're not seeing the campaign get picked up in the terminal (you see "0 campaigns found" or similar), you may have a timezone issue which @pranabk2 gave details on how to resolve.

If you are referring to the feature request of wanting to set delays between emails, this is being handled by #611.

Hope this helps! Let us know if you have any other questions.

**Comment by Jintirpki** [comment]
@jordan-wright  Yes, I want to set delays between emails. Currently, this does not solve this problem... : ( 
 For phishing campaigns this function (to set delays between emails ) very important, because mail services (gmail, yahoo e.t.c.) will may baned you.
