### ISSUE TITLE
SSL Certificate Issue

### ISSUE THREAD

**Issue by pranabk2** [gophish/gophish#702]
Hi All,

I have taken a new certificate for my domain from Godaddy and got two files : domain_name.crt and bundle.crt. Now inside config.json file i can see there are only two sections where i can include the following cert_path and key_path.

```
{
	"admin_server" : {
		"listen_url" : "127.0.0.1:3333",
		"use_tls" : true,
		"cert_path" : "gophish_admin.crt",
		"key_path" : "gophish_admin.key"
	},
	"phish_server" : {
		"listen_url" : "172.X.X.X:443",
		"use_tls" : true,
		"cert_path" : "domain_name.crt",
		"key_path": "domain_name.key"
	},
	"db_name" : "sqlite3",
	"db_path" : "gophish.db",
	"migrations_prefix" : "db/db_"
}
```
The issue what i see here is , i don't have the option to include bundle.crt . When i execute a campaign i see my clients are saying there is a certificate error showing in their end which is reflected in Internet explorer. When i did more research and found i need to include the intermediate certificate to overcome those errors. Please suggest where do i include the intermediate certificate (bundle.crt) inside Gophish ?

**Comment by S0larflare** [comment]
You could use openssl or edit the .crt to put all the files in to one. Depending on the encoding you might need to convert it first. Then use that and the key you generated whilst creating the CSR. It should work

Sent from my iPhone

On 20 Jul 2017, at 18:52, pranabk2 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi All,

I have taken a new certificate for my domain from Godaddy and got two files : domain_name.crt and bundle.crt. Now inside config.json file i can see there are only two sections where i can include the following cert_path and key_path.

{
        "admin_server" : {
                "listen_url" : "127.0.0.1:3333",
                "use_tls" : true,
                "cert_path" : "gophish_admin.crt",
                "key_path" : "gophish_admin.key"
        },
        "phish_server" : {
                "listen_url" : "172.X.X.X:443",
                "use_tls" : true,
                "cert_path" : "domain_name.crt",
                "key_path": "domain_name.key"
        },
        "db_name" : "sqlite3",
        "db_path" : "gophish.db",
        "migrations_prefix" : "db/db_"
}


The issue what i see i don't have the option to include bundle.crt . When i execute a campaign i see my clients are saying there is a certificate error showing in their end showing in Internet Explorer. When i did more research and found i need to include the intermediate certificate to overcome those errors. Please suggest where do i include the intermediate certificate (bundle.crt) inside Gophish ?

**Comment by S0larflare** [comment]
If it doesn't, what is the error that is given as to why the cert isnt trusted?

Sent from my iPhone

On 20 Jul 2017, at 18:52, pranabk2 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi All,

I have taken a new certificate for my domain from Godaddy and got two files : domain_name.crt and bundle.crt. Now inside config.json file i can see there are only two sections where i can include the following cert_path and key_path.

{
        "admin_server" : {
                "listen_url" : "127.0.0.1:3333",
                "use_tls" : true,
                "cert_path" : "gophish_admin.crt",
                "key_path" : "gophish_admin.key"
        },
        "phish_server" : {
                "listen_url" : "172.X.X.X:443",
                "use_tls" : true,
                "cert_path" : "domain_name.crt",
                "key_path": "domain_name.key"
        },
        "db_name" : "sqlite3",
        "db_path" : "gophish.db",
        "migrations_prefix" : "db/db_"
}


The issue what i see i don't have the option to include bundle.crt . When i execute a campaign i see my clients are saying there is a certificate error showing in their end showing in Internet Explorer. When i did more research and found i need to include the intermediate certificate to overcome those errors. Please suggest where do i include the intermediate certificate (bundle.crt) inside Gophish ?

**Comment by pranabk2** [comment]
Do you mean i should include bundle.crt + domain_name.crt into one  certificate ?

**Comment by S0larflare** [comment]
Yes. Honestly it shouldn't make a difference but can do for chrome. The bundle will be the intermediate certificates and potentially the root.

Sent from my iPhone

On 20 Jul 2017, at 19:13, pranabk2 <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you mean i should include bundle.crt + domain_name.crt into one certificate ?

**Comment by pranabk2** [comment]
Thanks i will try to do that , if not i will comment back again later.

**Comment by pranabk2** [comment]
I have fixed the problem just opened the bundle.crt in notepad++ and appended the certificate details inside the domain_crt.cert . It worked like a charm. 👍  Many Thanks S0larflare for your recommendation.

**Comment by jordan-wright** [comment]
👍 Glad you were able to get this one resolved. Thank you so much for the continued great support @S0larflare!!
