### ISSUE TITLE
go phish hosted in Kali Linux

### ISSUE THREAD

**Issue by patilprateek** [gophish/gophish#706]
Hello,

I have installed go phish on Kali linux running in VM in my test environment. My requirement is to make this available on the internet so that when a campaign is run, i can track results of all users (internal on LAN/ external on public internet/ WiFi). Post installation, i just ran a test campaign, and was able to send emails to users and were delivered, but these when accessed on a corporate LAN and other on WiFi did not give me any results on the application and just showed the the mail sent status in the Campaigns section.

Any leads to how to make this working and changes/ modifications/ additions required. Thanks

Prateek

**Comment by jordan-wright** [comment]
Hi @patilprateek, thanks for reaching out!

I believe these docs will help: https://gophish.gitbooks.io/user-guide/content/installation.html#exposing-gophish-to-the-internet

Basically, you'll need to update your config file to cause the phishing server to listen on all interfaces (`0.0.0.0:80`) and make sure that there aren't firewall rules preventing access.

Hope this helps! If you continue to run into issues, let us know what you're trying and what you see when it doesn't work and we can re-open.

**Comment by patilprateek** [comment]
Hi Jordan,

Thanks for the response. I tried below things :-1: 
1) updated the config file to listen on all interfaces, but once done, the gophish console fails to load with this configuration, Also ./gophish command does not complete successfully hence causing the console not to load.
2) Keeping the settings to default, i am able to launch the campaign, the email is also sent, but do not get the phish test results in the report.( i am running the phish tool from my test environment, my o365 server is hosted in external environment. The email is received in mailbox - but the phish results are not getting captuerd in report.
3) Tried to run the version on a windows 7 OS machine, and getting attached error while i try to test send an email from the sending profile.
![capture](https://user-images.githubusercontent.com/24647080/29407100-d89a4a66-8360-11e7-9211-2b1d2e444a0c.PNG)
