### ISSUE TITLE
Phishing Links Return 404/debug Level

### ISSUE THREAD

**Issue by turnerdb** [gophish/gophish#707]
This is a recent problem.  It was working prior to this morning.  I am using an embedded video link from youtube in my landing page to redirect users to a video demo when they fail a phish test.  Only seem to be receiving 404s now.

html:
<iframe width="560" height="315" src="https://www.youtube.com/embed/JjcD2my2bzQ?autoplay=1;rel="false" frameborder="0" allowfullscreen="true"></iframe>

Also, is there a way to increase the logging level so this is easier to troubleshoot on our end?

Thank you.

**Comment by jordan-wright** [comment]
I'm afraid there isn't any additional debug logging. Does the 404 occur for the YouTube video or the phishing links?

Also, is this the same campaign that worked and then did not work, or did you launch a new campaign?

If you launched a new campaign, what did you use as the URL field in the campaign? Did anything else change with the email template that you can think of?

**Comment by turnerdb** [comment]
Additionally the clicks are getting back to the dashboard, so I guess there is where my confusion is.  Why does it make it back to the phishing server to be counted but can't load the redirect?

**Comment by jordan-wright** [comment]
Hmmm... I guess I'm not entirely sure what you mean by the redirects. What does the setup look like in terms of the URL you see in the phishing email, the HTML of the landing page, etc.

Another thing that might help is to watch your browsers developer tools network tab and console, which may indicate what's going on browser side.

**Comment by jordan-wright** [comment]
And nope! There's no limit to the number of active campaigns :)

**Comment by turnerdb** [comment]
So what I am doing is I import an email, lets say a google doc contribution invite.  That email has a link to join the google doc.  I make sure the box to replace links with landing page link is checked and import.  I then create my landing page and paste the embed link from a youtube video into the body of html code for the landing page.  I then create my campaign and uses said template and said landing page.  When the link in the email is clicked it should direct to the embedded URL link I used in the landing page.  I'm using an embedded link instead of just a normal url because I want it to autoplay and go fullscreen which the end user needing to invoke anything.

**Comment by turnerdb** [comment]
And now I just made a new embed link and it works again.  I must have edited/fat fingered something with the other code.  For now it looks like it is resolved.
