### ISSUE TITLE
Not Hosting Landing Page

### ISSUE THREAD

**Issue by loza0269** [gophish/gophish#708]
Hello,

Is there anyway to change where your email template points to, short of hard coding in to the HTML. To get a little more in depth, we don't want to start capturing peoples passwords on the network and we want people to be able to access it from outside the network without installing gophish on the external web server. So we decided that we would create a landing page on our external web server that basically just says you've been phished with some tips on how to avoid being phished. So my main question would be is there anyway to tell gophish to not host the landing page itself but to simply just send the users to the website directly. 

I know I could do this by setting up the links to point to the URL and then tell the email template not to change the links, but i already have a bunch of email templates in gophish and i dont want to have to re-create every email and change where it is pointing to and import it back in to gophish. Nor would it be productive to go through all the HTML of every email and change the URL.

**Comment by S0larflare** [comment]
You can host static pages on gophish itself, then you could make a landing page that just does an immediate redirect to that static "gotcha" page. I've done this in the past. Provided people don't have JS switched off it'll work fine.

Sent from my iPhone

On 25 Jul 2017, at 20:25, loza0269 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

Is there anyway to change where your email template points to, short of hard coding in to the HTML. To get a little more in depth, we don't want to start capturing peoples passwords on the network and we want people to be able to access it from outside the network without installing gophish on the external web server. So we decided that we would create a landing page on our external web server that basically just says you've been phished with some tips on how to avoid being phished. So my main question would be is there anyway to tell gophish to not host the landing page itself but to simply just send the users to the website directly.

I know I could do this by setting up the links to point to the URL and then tell the email template not to change the links, but i already have a bunch of email templates in gophish and i dont want to have to re-create every email and change where it is pointing to and import it back in to gophish. Nor would it be productive to go through all the HTML of every email and change the URL.

**Comment by jordan-wright** [comment]
@S0larflare is absolutely right- you can host static assets on Gophish as described in our docs: https://gophish.gitbooks.io/user-guide/content/documentation/landing_pages.html#static-assets

The other option would be to avoid checking the "capture credentials" checkbox which would still submit the form, but no data would be submitted. Then, you can set the redirect URL to point to your external webserver.

**Comment by jordan-wright** [comment]
Closing this out since hopefully that helps resolve the issue. Let me know if you're still running into issues and I'll be happy to reopen!

**Comment by loza0269** [comment]
Yea but say someone was to access it with there phone from outside the network, they wouldn't be able to access the landing page to be able to redirect them.

 Also, I don't even want a form I just want the "You've been phished" site to appear once they click the link and I already have that accessible through the internet, now i just want gophish to change the links to point to that.

**Comment by S0larflare** [comment]
In that case you could either expose it to the internet on port 80, which would allow people from outside the network to connect to the landing page which would then redirect or go through all the templates and changer the link to a static one. If your gophish instance is internal, wouldn't people getting the email as part of your company have to come in via a remote access solution to be able to get the email? Therefore they should be 'internal' at that point?

Sent from my iPhone

On 26 Jul 2017, at 14:51, loza0269 <notifications@github.com<mailto:notifications@github.com>> wrote:


Yea but say someone was to access it with there phone from outside the network, they wouldn't be able to access the landing page to be able to redirect them.

Also, I don't even want a form I just want the "You've been phished" site to appear once they click the link and I already have that accessible through the internet, now i just want gophish to change the links to point to that.

**Comment by loza0269** [comment]
We'd like to avoid exposing the VM to the internet, which is why we created the landing page on our external web server. And no we're Office 365, so you can access it anywhere whether you use the web console or the application.
