### ISSUE TITLE
gophish: listen tcp 0.0.0.0:80: bind: address already in use

### ISSUE THREAD

**Issue by calimerocalicali** [gophish/gophish#709]
I installed and started gophish on my mac OS10.10 yesterday and everything worked fine.

to start gophish used sudo ./gophish

today i tried to start gophish again using the same command and this is what i have

2017/07/27 12:34:34 worker.go:36: Background Worker Started Successfully - Waiting for Campaigns
goose: no migrations to run. current version: 20170219122503
 2017/07/27 12:34:34 gophish.go:83: Starting phishing server at http://0.0.0.0:80
 2017/07/27 12:34:34 gophish.go:84: listen tcp 0.0.0.0:80: bind: address already in use

I am really new to this, so apologies for the possible simple question. but, can you help out?

**Comment by knowtheunknown** [comment]
Hi!
You should stop your apache2 service before you run ./gophish:

>>  user@server: ~# sudo systemctl stop apache2.service

Greetings!

**Comment by calimerocalicali** [comment]
My Mac has yosemite installed, so the command you suggest does not work. I used instead
sudo apachectl -k stop

but i still have the same behavior.

**Comment by S0larflare** [comment]
Have you seen what is listening on port 80? Using netstat -tulpn and piping that into grep for example

Sent from my iPhone

On 28 Jul 2017, at 14:20, calimerocalicali <notifications@github.com<mailto:notifications@github.com>> wrote:


My Mac has yosemite installed, so the command you suggest does not work. I used instead
sudo apachectl -k stop

but i still have the same behavior.

**Comment by calimerocalicali** [comment]
netstat is an unknown command

**Comment by S0larflare** [comment]
Install netstat or use another method to work out what is listening on port 80 (there are several which are straightforward enough if you google it)

Sent from my iPhone

On 28 Jul 2017, at 15:29, calimerocalicali <notifications@github.com<mailto:notifications@github.com>> wrote:


netstat is an unknown command

**Comment by jordan-wright** [comment]
Yes, as @S0larflare mentioned there is another process listening on port 80. netstat, lsof, and others can help you identify which service it is to shut it down.

Since this doesn't appear to be an issue with Gophish itself, I'm going to close this issue. However, if you continue to run into issues, let us know and we can continue troubleshooting.

**Comment by gauravr15** [comment]
almost same thing happened to me but with bettercap, so does anyone has any solution

**Comment by IliasWhoElse** [comment]
try using `$sudo fuser -k 80/tcp` to free the port. For RHEL use `$sudo yum install psmisc `first
