### ISSUE TITLE
Duplicate users in table

### ISSUE THREAD

**Issue by StrangeUSB** [gophish/gophish#71]
If you close a modal using the escape key instead of the "Close" button it looks like any users in the group will get duplicated into the table when the modal is opened again.  There doesn't seem to be any issue when the users are saved though, the duplicates are ignored, so this is more of a UI issue.

![duplicate_users](https://cloud.githubusercontent.com/assets/6924235/12345475/cf4fa936-bb0e-11e5-87c2-e309e8ccdccd.png)

This can be fixed by binding to the escape key when modals are open and calling the ```dismiss()``` function when pressed.

This behavior is likely replicated where other modals are used and needs to be investigated further.

**Comment by jordan-wright** [comment]
Yeah, this is sadly a bit of a common issue. I've had problems cleaning up after the modals are closed out and it's been a pain to workout. This is similar to #41.

**Comment by jordan-wright** [comment]
I think this should be fixed - can you confirm when you get a chance!

**Comment by StrangeUSB** [comment]
Yeah that looks to work great!
