### ISSUE TITLE
Feature Request:  Change status of emails not yet actively being sent to "queued"

### ISSUE THREAD

**Issue by cclements** [gophish/gophish#710]
Small thing, but my heart skipped a beat after configuring a campaign to start tomorrow morning and seeing the emails status as "sending" in the campaign details page.  The general campaign listing page shows the campaign in "queued" state as expected.

**Comment by jordan-wright** [comment]
This should be fixed as part of the refactor from #878. If you could give it a shot and let me know if it helps, I'd appreciate it!
