### ISSUE TITLE
Your Account had been suspended 552

### ISSUE THREAD

**Issue by ARiITRrIX** [gophish/gophish#720]
Hey Guys 

i have a really big problem at gophish 0.3 ! If i create a new campaign gophish says by sending emails 
Your Account had been suspended, please contact us for reactivate. I don't know what was happen but can someone from you help me ?! Thx for any answer and I try to reinstall gophish. So guys for my Information 
I use Windows 10 Home, gophish for Windows Version 0.3 and ngrok for Server my smtp server was created at smtp2go.com 

bye ;)

**Comment by S0larflare** [comment]
I'm sorry, I don't understand. I've never seen that in the code (could have missed that) but it doesn't make any sense to me as there isn't an 'account' for gophish. You don't need to set anything up to download it, it isn't a cloud service or anything. Are you sure this isn't something from smtp2go?

**Comment by ARiITRrIX** [comment]
2017/08/09 15:08:07 worker.go:275: Creating email using template
 2017/08/09 15:08:07 worker.go:356: Sending Email to nilexemipi@mobilevpn.top
 2017/08/09 15:08:07 worker.go:359: gomail: could not send email 1: 552 Your account has been suspended. Please contact us to reactivate

This is the code at the CMD.exe startet at Administrator

**Comment by ARiITRrIX** [comment]
I run the gophish.exe after that i open in chrome https://127.0.0.1:3333 so then if i would like to open a campaign that will works but by sending mails gophish tell me this shit. I don't what should to to !!! #

**Comment by ARiITRrIX** [comment]
127.0.0.1 - - [09/Aug/2017:15:12:15 +0200] "POST /api/util/send_test_email?api_key=9ee238de34ac3b6c13d5a6f506ae2ba5d863a29618a96fc7cfa3d8c982b20282 HTTP/2.0" 500 125 "https://127.0.0.1:3333/sending_profiles" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36"
 2017/08/09 15:12:16 worker.go:275: Creating email using template
 2017/08/09 15:12:16 worker.go:356: Sending Email to nilexemipi@mobilevpn.top
 2017/08/09 15:12:16 worker.go:359: gomail: could not send email 1: 552 Your account has been suspended. Please contact us to reactivate
127.0.0.1 - - [09/Aug/2017:15:12:16 +0200] "POST /api/util/send_test_email?api_key=9ee238de34ac3b6c13d5a6f506ae2ba5d863a29618a96fc7cfa3d8c982b20282 HTTP/2.0" 500 125 "https://127.0.0.1:3333/sending_profiles" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36"


This is the full code

**Comment by S0larflare** [comment]
OK, so line 359 of worker.go is this:

`err = gomail.Send(dc, e)`

Which is calling on gomail (a different system) to send the specific email using the smtp details which has been set up. The error you're getting back appears to be from the SMTP server, in this case, smtp2go.com. I don't know why your account has been suspended, but it could see that you are trying to send phishing emails (even if they are meant to be used as training) and has therefore suspended you. You're best off talking to them.

**Comment by jordan-wright** [comment]
@S0larflare is correct- this message is coming from smtp2go, not Gophish. It appears that they had issues with how you were using their service. You may want to contact their support to work out the concerns.

Since this isn't on Gophish's end, I'm going to go ahead and close this out.
