### ISSUE TITLE
Sending different URLs to the campaign users

### ISSUE THREAD

**Issue by Th3shad0wfax** [gophish/gophish#722]
hello,
two suggestions I wish to share with you:
the first is to allow the user to send each campaign member a different URL as in importing users to the group by .csv file, it will be helpful in URLs too.
the second is to send feedback to the user from where the target opened the email, from Android, IOS, Windows,..

**Comment by Storm75** [comment]
Please ignore this

**Comment by jordan-wright** [comment]
Thanks for sending over this idea! I'm afraid I won't be implementing this feature, since I can't see this being used often at all. This seems like a very niche use case. If you could explain the exact use case and why it would be useful to the wider Gophish audience, I would be happy to re-consider.

As a workaround, you can use the API to spin up groups, launch campaigns with different urls, and compile all those results across multiple campaigns into a single report.

Hope this helps! Thanks again for sending over the idea.

**Comment by Th3shad0wfax** [comment]
I mean if I don't want the user to go to a landing page, I only want him to download a link hyperlinked in the template, and each user download a different link.for example if something works like this:in the csv file we add another header "URL", so that the user with email {{.Email}} when he click on a hyperlink he download the {{.URL}} provided in the csv, so that each user download different link.I tried to put the URL instead of the LastName and hyperlink a word with {{.LastName}}, it worked! but in the dashboard it doesn't show that the user clicked the link.  18.08.2017, 07:52, "Jordan Wright" <notifications@github.com>:Thanks for sending over this idea! I'm afraid I won't be implementing this feature, since I can't see this being used often at all. This seems like a very niche use case. If you could explain the exact use case and why it would be useful to the wider Gophish audience, I would be happy to re-consider.As a workaround, you can use the API to spin up groups, launch campaigns with different urls, and compile all those results across multiple campaigns into a single report.Hope this helps! Thanks again for sending over the idea.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by jordan-wright** [comment]
Gophish generates a unique ID for every recipient and sends the URL you put in the campaign options with that ID as a parameter. This is how it knows the link was clicked.

This parameter isn't known until the campaign is launched, so I'm afraid the way you're doing the csv upload via the last name field won't record clicks.

**Comment by Th3shad0wfax** [comment]
yes I knew that, thanks for answering18.08.2017, 16:10, "Jordan Wright" <notifications@github.com>:Gophish generates a unique ID for every recipient and sends the URL you put in the campaign options with that ID as a parameter. This is how it knows the link was clicked.

This parameter isn't known until the campaign is launched, so I'm afraid the way you're doing the csv upload via the last name field won't record clicks.
