### ISSUE TITLE
Can admin set local timezone for users ?

### ISSUE THREAD

**Issue by KaurBaljeet** [gophish/gophish#723]
Hello  @jordan-wright 
Can admin set the local timezone for users in the settings page? If yes, how ?
It will effect other modules like scheduling the campaigns according to that timezone, how we can manage that. Please describe it.

**Comment by jordan-wright** [comment]
That's not currently possible. The different timezone scheduling bug is well-known and something I'm planning on fixing soon. In a nutshell, everything will be served and stored at UTC with the JS on the frontend adjusting for local time to help when scheduling campaigns. Then everything will work as expected.

I'm tracking this in #316 so I'll close this one out for now to keep everything in one place.

Thanks for reaching out!
