### ISSUE TITLE
Campaign Emails are not being sent out

### ISSUE THREAD

**Issue by transform007** [gophish/gophish#731]
I’m using a VPS from DigitialOcean to run the admin server for GoPhish. I set up the template, the landing page, and group. The test email from the sending profile is being sent and received fine.

But when I launch a campaign, the email gets queued forever. When I try to the send the sample test email, it is sent out correctly with the template and everything. But the actual email is never sent out. It just says "sending". It might be a problem with the URL I’m using, but I’m not sure. I’m using the IP address from VPS as the URL in the campaign.

How can the test email send but not the campaign email?

Do you know what the problem might be? Not sure if I was clear enough.

Thanks.

**Comment by jordan-wright** [comment]
When you launch the campaign, what logs do you see in the terminal? Another cause of this is when your browser and the Gophish server are on separate timezones.

**Comment by transform007** [comment]
I think you're right. On the logs in terminal, its showing the time as 3 hours before my actual time. Any idea how I can change it?

**Comment by jordan-wright** [comment]
The easiest thing to do would be to change the server time zone (this depends on the OS). Eventually I'll have time to update the code to store everything as UTC where it's all consistent regardless of time zone.

**Comment by jordan-wright** [comment]
Closing this since it appears to be a timezone issue which we are tracking via #316
