### ISSUE TITLE
No link in the email to the landing pages once a campaign is activated and submitted. 

### ISSUE THREAD

**Issue by guysmileyy** [gophish/gophish#735]
I imported a landing page for a client we are going to perform a phishing engagement for. After registering a domain name then creating an email template a sending profile and all then a campaign. I send a test email to myself and my coworker. There is no link to the landing page that was created at all in the email that we receive. I used the api and verified that I could pull up the created landing pages and see them that way. I'm not sure why the landing page url isn't showing up in the email though. The tracking image fails to load as well in the email. I get a white square with a red x in place of the tracking image. If I look at the source I can get the url for the tracking image but nothing for the landing page. Upon entering the url for the tracking image the single pixel image loads and shows at that point that the email was viewed. But it is not showing viewed upon initial viewing since the single pixel image fails to load at that time.

**Comment by guysmileyy** [comment]
I figured out the issue. I needed to add {{.URL}} | The phishing URL variable to the email.

**Comment by jordan-wright** [comment]
👍 Glad you got it figured out!
