### ISSUE TITLE
Bug: 'Submitted data' dot is yellow on campaign timeline

### ISSUE THREAD

**Issue by skim-milk** [gophish/gophish#738]
The campaign timeline shows 'submitted data' dots as the same colour as 'clicked link'.

Presumably, the 'submitted data' should be red like in the details list.

**Comment by jordan-wright** [comment]
Are you using the latest version from source? A few weeks ago I moved all charts to use Highcharts (#680) and changed up the dashboard a bit. I'm not near my Gophish dev box atm so I can't verify to see if it's yellow on there, but just wanted to check to make sure this is affecting the latest version.

**Comment by skim-milk** [comment]
This was using `gophish-v0.3-linux-64bit.zip` from the releases page.

I'm not in a position to test the latest build at the moment, but happy to do it tonight :D

**Comment by jordan-wright** [comment]
I just checked with the latest and it looks like the "Submitted Data" events are red in the new timeline:

![image](https://user-images.githubusercontent.com/1317288/30043968-5e0307fc-91c0-11e7-8951-59f2ec7348d7.png)

Hopefully this fixes this one. Let me know if you have any questions!

**Comment by jordan-wright** [comment]
I'm finishing up a couple of other issues (like a refactoring of our mailing system) that, when done, will put Gophish in a position for a new binary release. In the meantime, the new timeline will only be available via building from source.

**Comment by skim-milk** [comment]
That's cool. :) Thanks for checking. I didn't note the version difference from source and the binaries.
I'll just build from source when I can. Go makes everything easy. :)
