### ISSUE TITLE
Sending profiles test

### ISSUE THREAD

**Issue by snori74** [gophish/gophish#739]
Very few mistakes in the formatting of the "From:" field will give a useful error message when a "send test Email" is done - typically they simply don't send.

Examples that give no error, but don't send:
   `mike (mike@gmail.com) <mike.walker@gmail.serv.co>`
  `mike (mike@gmail.com) <mike.walkergmail.serv.co>`
   `"mike <mike.walker@gmail.serv.co>`

This (using the Turkish 'dotless i') _will_ give an error:
    `klsjklsjklsj@ıphone.com`

These both work fine:
    `" mike (mike@gmail.com) "<mike.walker@gmail.serv.co>`
    `klsjklsjklsj@iphone.com`

**Comment by snori74** [comment]
`mike (mike@gmail.com) mike.walker@gmail.serv.co
mike (mike@gmail.com) <mike.walkergmail.serv.co>
"mike mike.walker@gmail.serv.co`

**Comment by jordan-wright** [comment]
Ok, this is fixed to show the error message that Gophish (and the underlying Go process) give us. It's worth noting that we're at the mercy of Golang's email address processor. This leads to some of those addresses being seen as invalid, as can be seen here: https://play.golang.org/p/L19HPs8JQI

**Comment by raviadds** [comment]
It worked! 
The format is 
"Firstname Lastname"  <email@domain.com>
