### ISSUE TITLE
Dialog box in  show cached content

### ISSUE THREAD

**Issue by snori74** [gophish/gophish#740]

**Comment by snori74** [comment]
When adding a "Sending Profile", if the "Send Test Email" button is used more than once, the first result (typically "Email sent!"), shows the second time - even before the email address is entered and the "Send" button is pressed. Also the "Send" button is also cached - showing as "sending".

While the "Send Test Email to" fields are also "cached" - that's not unreasonable.

**Comment by jordan-wright** [comment]
Oh, yeah, I guess that modal flash isn't being cleared. I'll get that handled.

Thanks for the report!

**Comment by jordan-wright** [comment]
All fixed. Let me know if you run into issues.

Thanks for sending this in!
