### ISSUE TITLE
Add "Build #"  to "Version"

### ISSUE THREAD

**Issue by snori74** [gophish/gophish#742]
After doing an update direct from the source on github, and recompiling, I still show "Version: 0.3" (under "Settings").

But I know that I have new code, and a new database layout.

- Is there somewhere in the interface that shows this?
- Surely some sort of "build #" would be a good idea?
- Should the version not actaully be something like "0.4 dev" to reflect that this dev source, not a binary release?

**Comment by jordan-wright** [comment]
You're right - the version should be updated. I'll likely make a VERSION file that contains the correct version. That way, we can eventually setup an updating mechanism based off this file.

I'll add that version file tomorrow. Thanks for the heads up!

**Comment by jordan-wright** [comment]
This is all fixed! I added the VERSION file, and also setup the CLI flags so you can run `./gophish --version`. I also incremented the version to 0.4-dev.
