### ISSUE TITLE
Requesting Addition of MySQL Config Documentation

### ISSUE THREAD

**Issue by michaelcippolito** [gophish/gophish#745]
Requesting documentation added to

https://gophish.gitbooks.io/user-guide/content/installation.html#using-mysql

to reflect fixing error 

> Error 1292: Incorrect datetime value: '0000-00-00' for column 'completed_date' at row 1

as previously documented at https://github.com/gophish/gophish/issues/577

Specifically, please add documentation as follows or similar:

> Add the following lines to the bottom of /etc/mysql/mysql.cnf:
> ```
> [mysqld]
> sql_mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
> ```

The above are the default modes for MySQL, but with NO_ZERO_IN_DATE and NO_ZERO_DATE removed.

Tested with Gophish 0.4-dev and `mysql  Ver 14.14 Distrib 5.7.19, for Linux (x86_64) using  EditLine wrapper`

Thank you for considering and in any case I hope this is helpful.

**Comment by jordan-wright** [comment]
Good catch! I remember running into this, but forgot to update the docs. All fixed 😄 

Thanks for sending this over!
