### ISSUE TITLE
RFC: Does Anyone Use the Map?

### ISSUE THREAD

**Issue by jordan-wright** [gophish/gophish#747]
Quick question, does anyone use the map on the campaign results? If so, what do you use it for?

I admittedly originally put it in Gophish simply to have feature-parity with some of the other frameworks out there. But the more I think about it, the more it seems to just kinda take up space. I'm not sure what knowing the geolocation of the people who clicked the phishing links really adds to the results.

So, depending on the response I get, I'm considering deprecated the map in 0.4. I've considered making it optional, but that gets into a weird workflow where other UI elements will be expected to be optional which causes a whole mess of a workflow and engineering to be worked out so, changes are, I'd just drop it completely unless there's a good reason not to.

Let me know what y'all think!

**Comment by snori74** [comment]
No. Not useful to me.

**Comment by PSt-dev** [comment]
Same here - no need for it.
Because it needs so much screen space, I have removed it in my fork

**Comment by S0larflare** [comment]
Same here. Although in my case all my campaigns are internal so it is never populated anyway :P

**Comment by jordan-wright** [comment]
Sounds good- thanks everyone! I agree with the points above. I'll decide this week if I want to just remove it all together, or make it an option that's off by default. Either way, it's going away :)

**Comment by jordan-wright** [comment]
Alright, I opted to make this an option that will be deprecated in upcoming versions.

I chose to go the route of making this available off the settings page, leaving room for future UI options as needed:

![image](https://user-images.githubusercontent.com/1317288/30518009-3a9b16ee-9b37-11e7-8a45-bbb3834a433b.png)

Since this is stored in `localStorage` (as opposed to the database) it will be off by default.

I appreciate everyone's input! Hopefully this will be a good compromise in the meantime as we transition away from the map which will give us [so much room for activities](https://media.giphy.com/media/yrFrXTTTcHIY0/giphy.gif)!

**Comment by acklenx** [comment]
Sorry to comment on a closed topic... but here goes anyway.  I think the lack of value may be that it is a world map instead of a US or state map.  I'm guess you're just using geoip which at least has city by city resolution (albeit, not the most accurate or reflect of where users actually are).  This will at least be more interesting.

**Comment by drewPrince** [comment]
New user to GoPhish.  Map isn't populating data yet.  I would think it could be handy if it does start working for us.  We have offices around the world and being able to identify trends for regions would be beneficial.  Could be a language/translation barrier/misunderstanding, a poor teacher in that region (or lack of training).

The higher % of "Emails Opened" in a region the brighter orange that region gets.  The higher % of "Links Clicked" the brighter the red gets for that region.  The higher % of "Passwords Entered" (or whatever that stat is called), the bigger the nuclear symbol gets.  Haha, that's just me and my stupid ideas.
