### ISSUE TITLE
Campaign Timeline doesn't scale far above 1000 targets

### ISSUE THREAD

**Issue by ecbftw** [gophish/gophish#749]
We created a campaign with 1166 targets and it launches fine, but upon viewing the stats for that campaign, the browser tab starts to become extremely slow.  It is slow loading to add all of the individual dots to the timeline, but then even after loading, it is excruciating to use the page (often having to wait several seconds to scroll down the page).  

As a temporary work around, if you have the patience for it, you can right-click and "inspect" the timeline element, then just delete it from the page using developer tools.  The tab immediately becomes snappy again.

My suggestion for addressing this is to switch the Campaign Timeline to a *cumulative histogram*, showing a separate distribution line for each type of event.  Use a server-side library to generate it as an SVG or other image format.  This should scale much better and will actually be easier for the user to interpret.  I have an implementation of this in Python for our reports, but I doubt you want to use that. =P

**Comment by jordan-wright** [comment]
Are you using the version built from source or a binary release? The latest source version switched to using highcharts which _should_ be more performant, but I haven't tried it with 1000+ targets yet.

**Comment by ecbftw** [comment]
Ah, good to know.  Still using latest release (0.3).  I'm in the midst of a 6 month long phishing test and don't want to change horses in mid-stream.  I'll try out that page once I'm able to upgrade.  Thanks!

**Comment by S0larflare** [comment]
If you don't want to (or can't) upgrade, you can increase the refresh period or remove it entirely. Depending on the version you'll have to edit either campaign_results.js or campaign_results.min.js, the period is near the end of it (the min.js is in SI notation so is 6E6 or something like that)

Sent from my iPhone

On 12 Sep 2017, at 20:48, ecbftw <notifications@github.com<mailto:notifications@github.com>> wrote:


Ah, good to know. Still using latest release (0.3). I'm in the midst of a 6 month long phishing test and don't want to change horses in mid-stream. I'll try out that page once I'm able to upgrade. Thanks!

**Comment by jordan-wright** [comment]
Hey @ecbftw just a heads up, I got some [good feedback on Reddit](https://www.reddit.com/r/sysadmin/comments/70zqnc/gophish_v04_released/dn815wk/) that campaigns with >= 1000 users are snappy in the UI now with our recent changes.

With this feedback, I'm going to go ahead and close this out for now. However, if you upgrade to the latest version and you're still running into issues, please don't hesitate to let me know and we can re-open to continue troubleshooting.

**Comment by ecbftw** [comment]
Makes total sense.  Thanks for the update and I'll let you know if I have trouble in newer versions when I get there.
