### ISSUE TITLE
bash: ./gophish: cannot execute binary file: Exec format error 

### ISSUE THREAD

**Issue by GBvenkatesh** [gophish/gophish#750]
Unable to execute the gophish.... it is Green in color and am executing it root

**Comment by jordan-wright** [comment]
What Linux distro are you running?

What exact steps did you take to get to this point?

**Comment by GBvenkatesh** [comment]
Am Using Kali Linux its Debian... i followed the instructions provided.
![image](https://user-images.githubusercontent.com/31404259/30407740-a40a3a7c-992c-11e7-9d0d-a9abc3b38d2c.png)

**Comment by jordan-wright** [comment]
What version of Gophish did you download?

**Comment by GBvenkatesh** [comment]
v.0.3 i have downloaded recently only 3 days back.

**Comment by jordan-wright** [comment]
Sorry I wasn't more clear. Which architecture did you download? Like, what zip file specifically?

**Comment by GBvenkatesh** [comment]
My Bad i was trying to run the Darwin variant in my Kali Linux. Just downloaded the Linux one and its works like champ. Thank you so much for the support!

**Comment by legend08thomas** [comment]
i am also using kali linux and its also desbian hmm i just trying to install genymotion its also showing the same error please help me !!!!!

![screenshot from 2018-01-19 20-28-16](https://user-images.githubusercontent.com/32392064/35156717-ac0e67d6-fd57-11e7-8b3f-039357b070ad.png)

**Comment by jordan-wright** [comment]
@legend08thomas this is the repository for Gophish, not "genymotion".
