### ISSUE TITLE
Enahancement Request File name on export should be report title

### ISSUE THREAD

**Issue by sonofapharmacist** [gophish/gophish#751]
when exporting results, can the file name be the title of the campaign?

instead of results.csv myCoolName.csv

**Comment by jordan-wright** [comment]
Yeah, makes sense, we can do that.

Thanks for the suggestion!

**Comment by jordan-wright** [comment]
This should be fixed now. I updated papaparse to the latest version and changed the export function to export results as campaign.name - Scope.csv format. So, say I have a campaign named "HR Campaign" and I export the results, it'll export as "HR Campaign - Results.csv".
