### ISSUE TITLE
unable to open exe file, following is the result on Anti Virus

### ISSUE THREAD

**Issue by bhargavi-git** [gophish/gophish#752]
Scan type: Auto-Protect Scan
Event: Security Risk Found!
Security risk detected: WS.Reputation.1

**Comment by jordan-wright** [comment]
I'm afraid there's very little I can do about this. For whatever reason, Symantec's auto reputation system seems to think a phishing framework has a low reputation. For now, I recommend whitelisting in Symantec and you should be good to go.

If this gets to be a big issue, I'll see what recourse I have with Symantec to try and get them to reevaluate it or something.

Thanks for the heads up!
