### ISSUE TITLE
Domain blacklisting

### ISSUE THREAD

**Issue by Jackbquick212** [gophish/gophish#754]
I've a quick question I wanted to run by you guys and see if someone's had this issue.

I haven't run into anything like this, as I haven't been actively running a GoPhish server, but I'm wondering what doing so will do to my ISP's AUPs if they find multiple phishing messages being sent from my server's IP and/or domain.  Is there a way to avoid this kind of problem from popping up, if I keep running campaigns every now and then?  Has anyone gone so far as to contact your ISP directly to tell them what you're doing, so they don't hit you with some legal warnings?

**Comment by jordan-wright** [comment]
There's no way you will always be able to *guarantee* that your ISP won't block the activity unless you get written permission from them. As a general rule though, it would be good to notify your ISP about your intentions to test your organization's exposure to phishing using Gophish just to see what they say and if they offer any guidance.

That said, the main issue will almost certainly be sending the emails. So, what you could do is setup two Gophish instances that share a MySQL database - one internal to your company that points to your SMTP server to send the emails and another that hosts the landing pages that are available externally. When setting up the campaign, you would point the URL to the external listener.

**Comment by jordan-wright** [comment]
Going ahead and closing this since it seems as though the original question has been answered. @Jackbquick212 let us know if you have any other questions about this - happy to help any way we can!

**Comment by Jackbquick212** [comment]
Sounds good, thanks Jordan.  If my ISP offers any helpful guidance on the issue, I'll try to throw it back up here in case someone could use similar info.
