### ISSUE TITLE
 mail: expected single address

### ISSUE THREAD

**Issue by stracire** [gophish/gophish#759]
Hi,

First of all, GoPhish is awesome!

I wanted to fool people by displaying another e-mailadres as the 'from' address. 
Usually I enter a from e-mail as: **Example < example@example.com >**
But in this case I want to enter: **A.different@email.com < example@example.com >**

I do get the error:  mail: expected single address.

Is there any workaround or is it possible to get this working?

**Comment by stracire** [comment]
I did some more research and discovered this can be done by using quotation marks.
**"a.different@email.com"< example@example.com >**

**Comment by S0larflare** [comment]
You can spoof it to whatever you want, though there is a chance (depending on your setup) that it might get blocked/rejected/dropped if you do so. If you're doing this all internally then you should be fine.

Anyway, in the sending profile you can either do:

Facebook Security<secure@facebook.com<mailto:secure@facebook.com>>

Which will then show just as that in an email client (headers would show it never originated from Facebook, but so long as nobody checks that, it looks legitimate)

Or you could go with a little more 'real world' one like:

"Facebook Security<security@facebookmail.com<mailto:security@facebookmail.com>>"<noreply@gjslvendhl.com<mailto:noreply@gjslvendhl.com>>"

Which would still catch out low hanging fruit and would be more typical of a real campaign that wouldn't necessarily get blocked by filters (as it isn't explicitly masquerading as coming from Facebook)

If all that makes any sense...

Sent from my iPhone

On 20 Sep 2017, at 10:31, stracire <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

First of all, GoPhish is awesome!

I wanted to fool people by displaying another e-mailadres as the 'from' address.
Usually I enter a from e-mail as: Example example@example.com<mailto:example@example.com>
But in this case I want to enter: A.different@email.com<mailto:A.different@email.com> example@example.com<mailto:example@example.com>

I do get the error: mail: expected single address.

Is there any workaround or is it possible to get this fixed?
