### ISSUE TITLE
Can't Access Landing Page From Windows 2012 VPS

### ISSUE THREAD

**Issue by whoami24** [gophish/gophish#761]
Hi 

I wanted if you have any solutions regarding unable to access landing page or URL from windows server.

I was successfully able to set up GOPHISH in my workstation able to send campaigns and see that updates from dashboard. But when i tried to do it from our VPS running on windows server 2012 r2, I can launch campaign but i can't access the landing page or URL from my workstations even from VPS itself. I tried adding the ports to firewall 81,3333 but still no luck.

**Comment by jordan-wright** [comment]
Do you see any errors when Gophish starts up? Specifically, you'll want to look for errors about binding to ports.

Then, on the server, try opening a browser and navigating to the gophish listener. This would be on port 80 by default, but you're specifying port 81 so you may have changed it.

If you see a 404 page, then it looks like Gophish is running. Next, you'll need to try it from an external host (btw - make sure your config.json has the phishing server listening on `0.0.0.0`). If you still can't reach it (getting a connection refused or connection timeout) check the FW logs to see if something is dropping unexpectedly.

Beyond that, we'll need more information about your config, what exactly you're trying that's not working, etc.

**Comment by whoami24** [comment]
Hi Jordan,

The first time i run it, i encounter the port 80 issue that is why i changed it to 81. now its working fine unless that i can't access the landing page from another computer.

![image](https://user-images.githubusercontent.com/32141008/30708900-3f50f0d8-9eb5-11e7-9e0d-c2049ab556ed.png)


I also try disabling the firewall no luck. my config.json is below:

{
	"admin_server" : {
		"listen_url" : "127.0.0.1:3333",
		"use_tls" : true,
		"cert_path" : "gophish_admin.crt",
		"key_path" : "gophish_admin.key"
	},
	"phish_server" : {
		"listen_url" : "0.0.0.0:81",
		"use_tls" : false,
		"cert_path" : "example.crt",
		"key_path": "example.key"
	},
	"db_name" : "sqlite3",
	"db_path" : "gophish.db",
	"migrations_prefix" : "db/db_"
}

**Comment by jordan-wright** [comment]
@whoami24 the best way for us to continue troubleshooting is for you to read through the last comment and verify that everything appears as you expect. Specifically, I'm referring to this part of the comment:

> If you see a 404 page, then it looks like Gophish is running. Next, you'll need to try it from an external host (btw - make sure your config.json has the phishing server listening on 0.0.0.0). If you still can't reach it (getting a connection refused or connection timeout) check the FW logs to see if something is dropping unexpectedly.

If you can look through this and let us know the results, it'd be appreciated!

**Comment by whoami24** [comment]
Hi Jordan,

I was able to do work-around for this. This is now resolve I can now use gophish smoothly :) . Thanks  for your time and advise.

**Comment by ferdinandion** [comment]
Helllo, I have almost same problem with that, 
I’ve installed gophish on VPS, it running but I can’t access gophish from browser, 

How to access gophish from my browser??

**Comment by whoami24** [comment]
@ferdinandion Make sure all gophish files are in the VPS. double check if you are accessing HTTPS or HTTP. and check your firewall configuration.
