### ISSUE TITLE
Can't change the font type in the landing page template

### ISSUE THREAD

**Issue by Pitergo** [gophish/gophish#762]
How can I change the font in the HTML under the landing page template.
I want to use the same font type which is already used in the original website that I imported in the landing page .

Also, how can I add the organization logo to the landing page when I import the site?

**Comment by stracire** [comment]
Use '!important' on your CSS to add more priority to your own stylesheet instead of the imported one.

You can upload files such as logo's to: **static/endpoint**
They will appear on **example.com/static/file**

**Comment by jordan-wright** [comment]
@stracire is correct - you can either inline styles in the HTML or you can host CSS files in the `static/endpoint/` directory.

I can't guarantee that the HTML preview will render the CSS stylesheets - it's kind of picky about what it shows for security reasons (e.g. it won't render scripts). However, things should render just fine when the user hits the landing page.

Hope this helps!
