### ISSUE TITLE
Unable to send test mail

### ISSUE THREAD

**Issue by shraddha92mhatre** [gophish/gophish#763]
Hello,

When I added profile and tried sending a test mail. I get the below error:

dial tcp 173.194.66.108:587: i/o timeout

**Comment by S0larflare** [comment]
That implies that your gophish server can't reach your mail server (173.194.66.108 on port 587). You might want to check your firewalls

Sent from my iPhone

On 21 Sep 2017, at 19:38, shraddha92mhatre <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

When I added profile and tried sending a test mail. I get the below error:

dial tcp 173.194.66.108:587: i/o timeout

**Comment by shraddha92mhatre** [comment]
So, I was trying to access external email from internal environment. I am now trying to send between internal environment. I didn't get that error but I got below error:

Unencrypted connection

**Comment by S0larflare** [comment]
Port 587 is typically for smtps (simple mail transfer protocol over ssl/tls). You'll either have to set it up to accept that or try port 25 if you're using plain 25

Sent from my iPhone

On 21 Sep 2017, at 21:46, shraddha92mhatre <notifications@github.com<mailto:notifications@github.com>> wrote:


So, I was trying to access external email from internal environment. I am now trying to send between internal environment. I didn't get that error but I got below error:

Unencrypted connection

**Comment by shraddha92mhatre** [comment]
Yes. I made changes accordingly and it is '25'. Still the error was coming:

Unencrypted connection

**Comment by shraddha92mhatre** [comment]
Changes were made in the server itself to allow connections, so it works. Thanks for your help. Issue Resolved!

**Comment by knaave** [comment]
Hi,

I have an issue as well, unfortunately. Error:  Max connection attempts exceeded - dial tcp [::1]:25: connect: connection refused. Unsure what's causing it.
