### ISSUE TITLE
Unicode problems with import of users

### ISSUE THREAD

**Issue by snori74** [gophish/gophish#764]
Import of users will accept a CSV, and look good in the interface, even when it has encoding which gophish later "chokes" when trying to send.

Log output from (with names changed to protect  the innocent):

`
2017/09/22 08:30:26 main.go:740: sql/opt/goapps/src/github.com/gophish/gophish/models/campaign.go:144194.704µsINSERT INTO "events" ("campaign_id","email","time","message","details") VALUES (?,?,?,?,?)[363 <adam.butler@commarc.co.nz> 2017-09-21 20:30:26.397145153 +0000 UTC Error Sending Email {"error":"gomail: could not send email 1: gomail: invalid address \"\\\"Adam Baker\\\" \u003c\\\"\u003cadam.baker\\\"@acme.com\u003e\u003e\": mail: expected single address, got \"\u003e\""}] 1
`

In the past I've found the import process to be very picky, which is annoying. This however is worse - everything looks to be working fine, the list of users and their emails looks fine in the GUI, and the dashbord says "Emails Sent" - it's only when looking one layer deeper at the individual emails (via "View Results"), that we see "Error" alongside each users - and deeper again in the log (as shown above) to get to the root cause. I can't see any way to know that there will be a problem before it happens.
![adam](https://user-images.githubusercontent.com/2436188/30720379-4d384856-9f7b-11e7-9324-8c14aa912a5c.png)

**Comment by jordan-wright** [comment]
Yeah, the csv decoding is pretty tricky. There's multiple parts to it:
* Getting the upload correct in the web-browser
* Storing it correctly in gophish
* Encoding it correctly in the mailer (this isn't supported nicely by Golang as it is - it's not that Gophish is inherently doing something bad).

That said, I'll keep this open until we can figure something out. If anyone has any suggestions or wants to help track this down, it'd be much appreciated! Sorry for the hassle!

**Comment by jordan-wright** [comment]
@snori74 at second glance, this doesn't really seem to appear unicode related. Instead, it seems like the issue may lie in the `<>` around the email address.

Can you provide the line in the CSV in question (feel free to change the names). I just need to see what the CSV actually looks like to test things on my end.

**Comment by snori74** [comment]
[UTF-2.txt](https://github.com/gophish/gophish/files/1324040/UTF-2.txt)
Indeed, looks like you're correct. I've attached two files, UTF-1.csv and UTF-2.csv. The first with `< >` around the email, the second not. In this case they're both ASCII:

`
UTF-1.txt: ASCII text, with CRLF line terminators
UTF-2.txt: ASCII text, with CRLF line terminators
`

Both work fine for the bulk import. The `< >` are retained in the display, but if you're used to seeing email addresses like this you'd not notice without taking especial 
[UTF-1.txt](https://github.com/gophish/gophish/files/1324039/UTF-1.txt)
care to do so.

On creating a campaign using them, UTF-1 gets "Error" again - while the other is fine.

I think the simplest action here is simply to reject the import of files with "invalid" email addresses. (while technically the <user@example.com> is valid "by the book",  if "gophish" is going to barf on it later, then it should not be allowed)

PS: Just tested manually entering an address like that via the New Group GUI - and got "No targets specified" - not a great error message, but it did prevent me entering "bad" data.

**Comment by jordan-wright** [comment]
Instead of returning an error, I'll just parse the email and return just the address. Shouldn't add much computational time and would be more fault tolerant because I agree with you - that should be valid enough.

I'll keep this issue open until I can get to it, unless you want to drop a patch in the util/util.go file in the csv function that calls mail.Parse on the email object and saves just the address.

**Comment by jordan-wright** [comment]
Ok, should be good to go now! I've updated Gophish to parse out the emails in `<email@example.com>` syntax. Let me know if you run into any issues!
