### ISSUE TITLE
Track Image missing

### ISSUE THREAD

**Issue by sbjohal** [gophish/gophish#766]
Hello Everyone, 

I am using windows based latest release of  GoPhish application along with XAMPP web server. Now When I am sending any email using GoPhish. I am not getting any results in tracking and tracking image is also missing. 

I would like to know if there is any special settings  required in this kind of setup. My web server is accessible publicly using Ngrok. The message I am getting in Ngrok while opening email "301 Moved Permanently"

Second Is there any place where I have to put any image or need to setup any path to pick an image?

Thanks
Gary Johal

**Comment by stracire** [comment]
Is the landing page loading? 

Does E-mail template does contain the tag **{{.Tracker}}**?

Also not all mail-clients load external content by default. Therefore I like to speak about 'At least ...% has opened the e-mail' instead of an exact percentage.

**Comment by jordan-wright** [comment]
I'd also suggest that XAMPP or any other webserver isn't needed. Gophish comes with its own webserver. Chances are, XAMPP is receiving the tracking requests, not Gophish.

That said, the tracking image is generated by Gophish- you don't store anything on your side.

Check out our docs on how to get Gophish up and running as well as how to setup the trackers and landing pages https://gophish.gitbooks.io/user-guide/content/getting_started.html

**Comment by sbjohal** [comment]
No, Landing page never load. .

Yes, Email Template containing tag {{.Tracker}}.

I have checked the issue through web mail as well, but still tracking image never appear.

**Comment by sbjohal** [comment]
Thanks Jordan, your advice made the trick. All set now after dropping the xampp.
