### ISSUE TITLE
Import users through .CSV

### ISSUE THREAD

**Issue by BramLangelaar1** [gophish/gophish#767]
Adding multiple users through a CSV file to a group is not working well. See the following images:

![image](https://user-images.githubusercontent.com/25822403/30754117-c5116466-9fc1-11e7-8d41-0c44599bb191.png)

![image](https://user-images.githubusercontent.com/25822403/30754134-d7aa3a3a-9fc1-11e7-930b-84a7643430b7.png)

![image](https://user-images.githubusercontent.com/25822403/30754186-14a542ae-9fc2-11e7-9ef8-0ee87d7365a1.png)

![image](https://user-images.githubusercontent.com/25822403/30754212-34a17622-9fc2-11e7-89d0-bed68aa1c638.png)

![image](https://user-images.githubusercontent.com/25822403/30754251-5500cd1e-9fc2-11e7-9216-68fa9605efb7.png)

Somehow, the trashcan appears (while in the adding screen) after adding the CSV file. But no users are added. Am I doing something wrong?

Like to hear from you!

**Comment by S0larflare** [comment]
Off the top of my head, I think you need to change the headers to 'FirstName' and 'LastName' without a space

Sent from my iPhone

On 22 Sep 2017, at 17:19, BramLangelaar1 <notifications@github.com<mailto:notifications@github.com>> wrote:


Adding multiple users through a CSV file to a group is not working well. See the following images:

[image]<https://user-images.githubusercontent.com/25822403/30754117-c5116466-9fc1-11e7-8d41-0c44599bb191.png>

[image]<https://user-images.githubusercontent.com/25822403/30754134-d7aa3a3a-9fc1-11e7-930b-84a7643430b7.png>

[image]<https://user-images.githubusercontent.com/25822403/30754186-14a542ae-9fc2-11e7-9ef8-0ee87d7365a1.png>

[image]<https://user-images.githubusercontent.com/25822403/30754212-34a17622-9fc2-11e7-89d0-bed68aa1c638.png>

[image]<https://user-images.githubusercontent.com/25822403/30754251-5500cd1e-9fc2-11e7-9216-68fa9605efb7.png>

Somehow, the trashcan appears (while in the adding screen) after adding the CSV file. But no users are added. Am I doing something wrong?

Like to hear from you!

**Comment by jordan-wright** [comment]
In this case, "First Name" and "Last Name" are correct. See https://gophish.gitbooks.io/user-guide/content/documentation/groups.html#bulk-uploading-users for more information.

@BramLangelaar1 what browser are you using? Do you see any errors in the Gophish console when you attempt the upload?

**Comment by BramLangelaar1** [comment]
@jordan-wright 

![image](https://user-images.githubusercontent.com/25822403/30796853-13aa0876-a1d4-11e7-9230-75772571c542.png)

I am getting this notification in the console, and I am using Chrome as browser.

**Comment by stracire** [comment]
Maybe this helps, maybe not...: For me, it works as long I save it as CSV(MS-DOS). There are other 'save ass CSV', but they all willAll other  give errors. Also to be sure, delete cells E,F,G,H. maybe there is a space somewhere in these cells that is ruining the import.

**Comment by BramLangelaar1** [comment]
Did not work for me unfortunately :(

**Comment by jordan-wright** [comment]
Out of curiosity, what are the actual values in the email fields? I see them hyperlinked in the excel file and the error is "Invalid email", which makes me think something in those values is messing up Gophish.

**Comment by BramLangelaar1** [comment]
@jordan-wright see the following image :-)

![image](https://user-images.githubusercontent.com/25822403/30808906-38fd7906-a200-11e7-9654-1d535b9e3c7d.png)

**Comment by BramLangelaar1** [comment]
@jordan-wright another (different, off-topic) question; on what level is Gophish protected from threats/vulnerabilities like these:
- Injection
- Broken Authentication and Session Management
- Cross-Site Scripting (XSS)
- Insecure Direct Object Reference
- Security Misconfiguration
- Sensitive Data Exposure
- Missing Function Level Access Control
- Cross-Site Request Forgery (CRFS)
- Using Components with Known Vulnerabilities
- Unvalidated Redirects and Forwards

**Comment by BramLangelaar1** [comment]
@jordan-wright 

Solution:

![image](https://user-images.githubusercontent.com/25822403/30905686-d0342088-a375-11e7-91e1-f630393f0851.png)

Important to use the following format: 

**NOTE:** Every person has to  be in cell A, don't split them up to cell B, C and D. Do use a new row for every person you want to add.

First Name,Last Name,Email,Position
Sjaak1,Langelaar1,example@gmail.com, baas1
Sjaak2,Langelaar2,example1@gmail.com, baas 2

**Comment by Sonn85** [comment]
I experienced sort of the same problem, but I changed the encoding to UTF-8 from UTF-8-BOM in Notepad++, which solved my issues.

![image](https://user-images.githubusercontent.com/31204821/31115850-29c8b67e-a824-11e7-86de-893db93f6d64.png)

**Comment by jacob630** [comment]
I found a fix that worked for me! I was experiencing the same issue. Until I switched around the order. 
First Name, Last Name, Position, Email. Once I fixed the order in the excel csv file. The group importing worked just fine.  (SEE BELOW)


![capture_github](https://user-images.githubusercontent.com/32524421/31194028-793f44ce-a90b-11e7-9f10-d01a018f519e.JPG)
![github_example](https://user-images.githubusercontent.com/32524421/31194040-7f6058ac-a90b-11e7-967d-89edf9015b1d.JPG)

**Comment by jacob630** [comment]
It's a bit confusing since the developer has it in the order of First Name, Last Name, Email, Position. Just flip the last two around and it should work. Save as .CSV file and it should work.

**Comment by jordan-wright** [comment]
This _shouldn't_ matter. The function that [parses the CSV](https://github.com/gophish/gophish/blob/master/util/util.go#L41) enumerates every record looking for the right headings and keeps track of which index that heading is located at. This means that order shouldn't be a factor, but I'll double to check to make sure something weird isn't going on.

I appreciate the heads up!

**Comment by jordan-wright** [comment]
Hi @BramLangelaar1 just wanted to check in on this since there hasn't been any update in a few months.

Are you still encountering this issue? I couldn't find anything odd going on in the code with regards to ordering.

**Comment by jordan-wright** [comment]
Closing this since there hasn't been any updates in quite a while and it's still not clear why this was happening, and it appears a workaround was found in the comments above.

**Comment by vysec** [comment]
The version I'm using doesn't seem to recognise "First Name" and inserts empty space...

**Comment by jordan-wright** [comment]
Which version are you using? The latest from source should have that fixed. :)

**Comment by vysec** [comment]
Ah issue was because I didn’t save in ASCII. Tool doesn’t support UTF8 very
well

**Comment by jordan-wright** [comment]
Ah, yes you’re absolutely right. I remember seeing similar issues in the past about UTF8 related parsing.

Would you be willing to upload a sample CSV that you’re seeing the issue appear on? I could see if I can use that to try and improve the parsing.

Thanks for the heads up about this!

**Comment by vysec** [comment]
There’s actually issues with even using Chinese names for targets :)

I ended up using x x as the name and last name but of course looks well
dodgy.

I can just create a Chinese UTF8 CSV in Excel for you. But it fails even on
just English UTF8. You can make that easily also.

Let me know. And fantastic work!

**Comment by bfishsw** [comment]
Had a similar problem using Excel 2011 on Mac to create the CSV file - data wouldn't be imported when saving as certain csv types.  Choosing "Windows Comma Separated (.csv)" as the file format worked for me.
