### ISSUE TITLE
Install issue with $GOPATH

### ISSUE THREAD

**Issue by Jackbquick212** [gophish/gophish#768]
So I think I'm probably missing something basic, but I can't get gophish installed.  I keep hitting issues with my $GOPATH, and I'm really not sure what the problem is.  Here's a screen of where I'm getting stuck:

![capture](https://user-images.githubusercontent.com/23238176/30786236-d244da16-a140-11e7-9630-0e02313d8013.PNG)

I've also got this in my .bashrc...

![image](https://user-images.githubusercontent.com/23238176/30786268-3eb2da9a-a141-11e7-9d89-9d668702987b.png)

Does anyone know what the issue here is?  It seems to be something with my $GOPATH, but I really can't figure it out either way.

**Comment by jordan-wright** [comment]
Looks like git isn't installed, which Go needs in order to use go get.

**Comment by Jackbquick212** [comment]
Ah...ok.  I'll give that a shot tonight.
