### ISSUE TITLE
Handle TLS issues on connect to SMTP server 

### ISSUE THREAD

**Issue by wjwoodson** [gophish/gophish#77]
Various errors can occur when attempting to send campaigns via a mail gateway using TLS. We should catch these and return them to the admin user. Possibly (probably in email lib) allow user to specify no, opportunistic, or forced TLS.

2016/01/17 11:23:31 worker.go:112: x509: certificate signed by unknown authority
2016/01/17 11:22:55 worker.go:112: x509: certificate is valid for server4.dev.us, not localhost

**Comment by jordan-wright** [comment]
I agree - I think this will need to be in the email library. I'll make an issue.

**Comment by olivier2557** [comment]
In the issue 109, you advise installing the self signed CA as a trusted certificate (on the machine running gophish I believe).

Can you hint on how this is done? At Linux level? At go level? At gophish level?

**Comment by jordan-wright** [comment]
This is done on the Linux level: http://unix.stackexchange.com/questions/90450/adding-a-self-signed-certificate-to-the-trusted-list

**Comment by jordan-wright** [comment]
Making this high priority due to the amount of emails/issues we've received about this.

**Comment by olivier2557** [comment]
Even with replacing the original /etc/ssl/certs/ca-certificates.crt with my own self created CA, I still get the error about unimplemented algorithm. Could that be because my CA is based on md5?

I have a strace output but I  cannot see anything sticking out.

**Comment by jcamil** [comment]
Olivier2557 - MD5 is not supported for "valid" TLS configurations.

Might want to consider Let's Encrypt?

**Comment by jordan-wright** [comment]
Indeed - here's a link that explains it:

https://github.com/golang/go/issues/10431
