### ISSUE TITLE
Tracking Image is not working for Outlook email

### ISSUE THREAD

**Issue by shraddha92mhatre** [gophish/gophish#771]
Hi,

I was trying to send phishing email to outlook inbox. The status I can track is till 'Email Sent' and not further. Does it not work with Outlook Inbox?

**Comment by shraddha92mhatre** [comment]
What does it mean while creating a campaign the URL parameter says "location of gophish listener (reachable by targets)"?

I am rdp into a server where gophish is running locally and trying to send phishing email to my organization's outlook mailbox.

**Comment by Jon0x1** [comment]
So by default, and outlook client disables external images. Do you see a banner on the top than you can click on to either download images or allow from sender? 

https://support.office.com/en-us/article/Block-or-unblock-automatic-picture-downloads-in-email-messages-15e08854-6808-49b1-9a0a-50b81f2d617a

**Comment by shraddha92mhatre** [comment]
I can see "If there are problems with how the message is displayed, click here to view it in a web browser." But the option to 'download image or allow it' is not present.

**Comment by Jon0x1** [comment]
Out of curiosity, have you sent to an email that is not using an outlook client like gmail to see if the tracking is still not working?

**Comment by shraddha92mhatre** [comment]
Well, right now I am just working on sending mails to organization's outlook mailbox and it is configured that way for internal communication. If I try to send to outside gmail account, it will block it from sending.

**Comment by Jon0x1** [comment]
I'm fairly new with this app as well. One last thing I noticed in the email templates, you should have a `{{.Tracker}}` in the template you are sending out so that the software can track it. 
 
https://gophish.gitbooks.io/user-guide/content/template_reference.html

**Comment by shraddha92mhatre** [comment]
I am a bit confused whether what should come in URL field of campaign. If go phish runs on browser at 127.0.0.1:3333. Should the URL field be 'http://127.0.0.1:3333'?

Yes it does have {{.Tracker}} in the template.

**Comment by Jon0x1** [comment]
By default 3333 (admin server) is used for the management interface, but port 80 (standard HTTP port) is used for tracking.  Port 80 (phish server) is what is listening for the requests from the clients/users.

**Comment by shraddha92mhatre** [comment]
how do you check if what you have entered in URL field is correct?

Sorry I am bombarding with lots of questions.

**Comment by Jon0x1** [comment]
The IP address should be the one setup for the server. It should be `http://<Server_IP>:80`. Also, make sure your OS firewall is allowing inbound TCP port 80 traffic.

**Comment by jordan-wright** [comment]
@Jon0x1 has done a great job of providing the right information, but I'd also like to point you to our excellent documentation here: https://gophish.gitbooks.io/user-guide/content/documentation/campaigns.html

In it, you'll see the following:

> The URL field is what populates the {{.URL}} template value. This should be a URL or IP address that points to the Gophish phishing server and is reachable by the recipient.+

We even show an example of this in action here: https://gophish.gitbooks.io/user-guide/content/campaign/launching_the_campaign.html

> Most of the settings should be self-explanatory. The only thing to look out for is the URL field. Since the IP address of our Gophish server is 192.168.1.1, that's what we'll use:+

Regarding the outlook question, if you search for other issues [pertaining to outlook](https://github.com/gophish/gophish/search?q=outlook&type=Issues&utf8=%E2%9C%93), you will find issues almost identical to this one including #689, #381, and #263.

I recommend reading through our documentation and looking through past issues - it's likely that the information you're looking for can be found between those two resources.

For now, I'm going to close this out as a duplicate. Thanks for getting in touch!
