### ISSUE TITLE
Trye to clone facebook login

### ISSUE THREAD

**Issue by ipushino** [gophish/gophish#774]
Hi
its my first test and am trying to clone the facebook login page its ok but thereis no data captured

**Comment by jordan-wright** [comment]
There is likely an issue with the form in the landing page. You will need to manually adjust it to be a standard HTML form.

There is all sorts of helpful information in [other issues](https://github.com/gophish/gophish/search?q=capture&type=Issues&utf8=%E2%9C%93) that will point you in the right direction, such as #510
