### ISSUE TITLE
Highcharts lib is missing in vendor folder

### ISSUE THREAD

**Issue by Letty** [gophish/gophish#775]
Hi,
i want to modify your charts inside the dashboard and campaign result page to my needs. Running the gulp file works. But when i browse to the pages, inside the console appears an error, Highcharts is not defined.
Having a look in your commit from 6th August shows the problem. Inside the minified vendor.js is Highcharts defined. But nothing is added to the vendor folder.

Did you forgot this file or is that on purpose, due to the fact that Highcharts is just free for non commercial use? 

Thanks.

**Comment by jordan-wright** [comment]
This was just a forgotten file. It's been on my "todo" to get it added.

I'll keep this open until it's fixed. Thanks for the heads up!
