### ISSUE TITLE
Feature Request: Preview Landing Page

### ISSUE THREAD

**Issue by W1R3D-Code** [gophish/gophish#778]
Would be very useful to be able to check a landing page renders ok after making changes, without having to launch a campaign first :)

I've had issues with landing pages just loading a '404 page not found' when there is an issue with malformed html, which is only visible if you look at the raw output

i.e.

` 2017/10/03 11:12:12 phish.go:141: html/template:html_template: "\"" in attribute name: " \")=\"\"....`

**Comment by jordan-wright** [comment]
Previewing landing pages will be trickier than just trying to render them on save and catching any errors, which sounds like it'll be a good stop gap in the meantime. I can make that happen.

Thanks for the heads up!

**Comment by stracire** [comment]
Not a fix, but a workaround: You only have to launch a test-campaign once. You can use the same e-mailed link to view the changes you are making to it.

**Comment by W1R3D-Code** [comment]
Thanks @stracire that's what I've been doing so far :) I keep just deleting the test campaign thinking that last change would definitely be the last ^.^

**Comment by jordan-wright** [comment]
Sorry for the delay closing this out. As of 0.7.0 you can preview a full campaign flow.

Enjoy! 😄
