### ISSUE TITLE
 No groups found!

### ISSUE THREAD

**Issue by jnorris1369** [gophish/gophish#779]
I have 2 groups built no errors in the groups yet when I try to start a campaign I get " No groups found!" and I am at a complete loss as to what to do the documentation doesn't cover this and no one else seems to have this issue is there a way to force it to recognize groups with the api or something? any help would be appreciated thanks

**Comment by jordan-wright** [comment]
What version of Gophish are you using? And you can confirm that you have two groups that appear on the groups page?

Whatever browser you're using, open up the network inspector and watch the network traffic when you open the "new campaign" modal. You'll see an api call to get your groups- check if there's anything weird in that response.

Also look in the terminal for any error output that might indicate what's going on.

**Comment by jnorris1369** [comment]
hmmm came in this morning its working fine now not sure what was going on thanks for your help

**Comment by jordan-wright** [comment]
🤷‍♂️ Oh well, I guess it works now 😄 

Good to hear you got it fixed.
