### ISSUE TITLE
Store SMTP servers utilized in campaigns

### ISSUE THREAD

**Issue by wjwoodson** [gophish/gophish#78]
Add DB table, API endpoints, GUI to manage SMTP server configuration. Update New Campaign modal to select from servers already configured

**Comment by jordan-wright** [comment]
Yeah, ideally we should give the one specified in the config as the default choice, with the option to change it.

I've also thought about integrating a built in smtp server so that we can already have on running. This gives one less piece that the admin needs to have setup to use gophish.

**Comment by jordan-wright** [comment]
Since this is a minor db change, I'm assigning this to 0.2.

**Comment by jordan-wright** [comment]
With this being pretty critical feedback, we're bumping this up. We'll integrate it after we have our database migrations setup in #55

**Comment by wifiuk** [comment]
i agree there should be a "default" smtp option, or a choice of servers we can choose

**Comment by jordan-wright** [comment]
@wifiuk, I agree. I think we're going to handle smtp servers the same way we do all the other "entities" such as templates and landing pages.

We'll add an extra field to specify if it's your default SMTP server or not.

**Comment by wifiuk** [comment]
@jordan-wright great idea.

**Comment by jordan-wright** [comment]
Moving this to 0.1.2 since I can't see this being done in 0.1.1 before next week.
