### ISSUE TITLE
Landing page will not load (404)

### ISSUE THREAD

**Issue by JstnPwll** [gophish/gophish#781]
I have gone through the steps to set up gophish and launch a test campaign. The landing page simply has "Hello World" text on it.  When I navigate to http://0.0.0.0:80 in my browser, I get a page that says "404 page not found".

The request shows up in the gophish console like this:

    127.0.0.1 - - [04/Oct/2017:19:18:09 -0400] "GET / HTTP/1.1" 404 19 "" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"

It seems as though gophish is simply not creating/serving the landing page despite receiving the GET request. Anything I might have done wrong?

**Comment by JstnPwll** [comment]
I discovered that the request must come with a valid `rid` parameter to render the landing page, which makes sense if multiple campaigns are configured to run on the same host simultaneously. I would have hoped that the landing page would always be rendered regardless of the parameters (if there is only one active campaign).

**Comment by jordan-wright** [comment]
Gophish generates unique ID's for every recipient in the campaign. This is how we can tell who visited the landing page. That's the `rid` parameter.

It would be confusing if we showed the landing page without an `rid` only if there was only campaign running. As soon as a new campaign launches, what page should we show? What do we track when there isn't an `rid` parameter, and how do we handle template values in the page?

To keep our design consistent, we'll keep the method of requiring an `rid` parameter generated by Gophish.
