### ISSUE TITLE
"Whitelisting" top tips

### ISSUE THREAD

**Issue by teddielong** [gophish/gophish#782]
Hi everyone

Special thanks to Jordan for his hard work on this. Such a great tool. 

I currently use GoPhish on Azure, via RDP to send phishing to a two charities I volunteer with. Our delivery rate is a bit hit and miss and whilst I appreciate there are various factors to consider, what are the key whitelisting options to consider? It would be great to create a list of top tips for everyone.

E.g:
1) whitelisting the IP addresses or domain where GoPhish is held?
2) should we also whitelist the mail server?
3) whitelist email header?

Would these help deliverability and what else are essential or good to do to help?

**Comment by stracire** [comment]
Whitelisting the mailserver is mostly necessary. The landingspage should load just fine if you put it on port :80 or :443 (http/https). Other ports are often blocked by the firewall. Also sometimes it is necessary to modify the receiving limitations of the receiving mailserver (amount of emails the mailservers accepts from other mailservers in a period of time), else it could take up to days to send a single campaign.

**Comment by teddielong** [comment]
Many thanks for the quick response!

As I'm sending out to some charities I volunteer at - what do you suggest re the mailserver? I've just been using a cheap 1and1 email account so far, but is it a bit risky for them to whitelist the entire 1and1 mailserver?  Would I need to set up my own dedicated mail server?

Had a few issues with landing pages being caught by Google as 'spammy' too, so I guess I'll need to keep changing the domains I use for that?

Good idea re the receiving limitations - presumably I can just get their IT man to allow 'X' amount from 'Y server'?

**Comment by stracire** [comment]
The first question you have to ask your self, do you want just spoof e-mails or really be in control of the domain (receiving replies). 

For small businesses, the default website host should be just fine. Many cheap hosts have send limitations of 500 each day. 

Paid mailservers often also have send limits, but they are pretty high. I have heard from others that Amazon cloud has pretty good solutions for renting just a mailserver. 

Another alternative is to set up your own mailserver on a VPS. I prefer this solution because you have full control over the send-settings and the logs.

**Comment by teddielong** [comment]
Is there not a danger to getting a small organisation to whitelist a paid mailserver (such as 1and1, office365 etc), as would they be technically allowing anyone using that server to definitely achieve deliver and bypass their spam?

I guess a paid mailserver could be an option - I like the idea of my own mailserver on a VPS, although it sounds a little above my knowledge and skills!!

**Comment by jordan-wright** [comment]
If you're using Gophish internally at your organization, it's recommended to use the existing mail infrastructure.

If you're using Gophish to test an organization who has given permission for you to run phishing simulations, you can use the paid VPS or use an existing email sending provider. For most providers, you have the option to pay for dedicated IP addresses from which you can send your email. If you want to go a step further, you can have the receiving organization whitelist a custom smtp header. Going the VPS route is an option, but setting up and maintaining a mail server is outside the scope of our support.

Hope this helps!
