### ISSUE TITLE
Messages not being delivered - 503 5.5.0 Sender already specified

### ISSUE THREAD

**Issue by bkeifer** [gophish/gophish#787]
I'm trying to send to a list of 600+ users, but only 210 are accepted by the mail server.  The rest show in the gophish error log with "503 5.5.0 Sender already specified".

It seems like gophish is trying to re-send the MAIL FROM information twice in one session.  Is there any way to tell gophish to create a new session for each message?

**Comment by bkeifer** [comment]
Interesting data points:

I tried sending the campaign a second time and the exact same number of messages were delivered.  Diffing the list of errors between the two campaigns show the lists are identical.  Same users got the same errors both times.

I used the API to grab the list of recipients that errored out and imported them into a new group.  I sent an identical campaign to this subset, and they all errored again.  These are known good addresses.

**Comment by jordan-wright** [comment]
It's likely the case that we're getting some kind of error message for a recipient and then we don't reset the connection (as you mentioned).

Issues exactly like this will hopefully be resolved when I finish refactoring our mailing system. I'll keep this issue open in the meantime and will update it when the refactor is complete. For now, you may consider breaking up the campaigns and using a tool like [GoReport](https://github.com/chrismaddalena/GoReport) to aggregate campaign statistics after the fact.

**Comment by WendySask** [comment]
Hi Jordan, 
We are experiencing the same issue trying to send ~ 1500 emails and ~400 fail but what's interesting is that when the first one errors, the next 20 also error:  

{"error":"gomail: could not send email 1: 550   5.1.1 \u003 <removed email address>\u003e: Recipient address rejected: User   unknown in relay recipient table"}
--
{"error":"gomail:   could not send email 1: 503 5.5.1 Error: nested MAIL command"}
{"error":"gomail:   could not send email 1: 503 5.5.1 Error: nested MAIL command"}...

**Comment by jordan-wright** [comment]
It appears that the cause of this is that one email will incur an error (any error, doesn't really matter which one) and the connection will continue as if nothing happened. This can put the connection out of sync.

Our upcoming changes to the mail queue will account for this and will properly reset after an error is received, which should fix this issue. I don't have a timeline, other than to indicate it's the issue I'm currently spending all my time to address.

**Comment by jordan-wright** [comment]
This should be fixed as part of the refactor from #878. If you could give it a shot and let me know if it helps, I'd appreciate it!
