### ISSUE TITLE
My email are landing into Spam in gmail

### ISSUE THREAD

**Issue by Avinashjaiswal420** [gophish/gophish#788]
Hello,

My all emails are landing into spam, can any one suggest.

Thanks

**Comment by snori74** [comment]
In my experience, gmail is very good at spotting spam, so you'll need to work very hard to 'beat' it. In particular, any attempt to 'spoof' - such as sending as support@facebook.com will be detected. 

One way around this is to use a misleading "display name" - e.g. "Facebook Support" <avin420@avin420.com> - but this will require you to own avin420.com and have things like PTR and SPF well setup.

**Comment by jordan-wright** [comment]
Another (preferred) option is to have the organization whitelist emails coming from your Gophish instance. Gophish is only meant to be used in engagements where you have clear authorization from the targeted organization to run a phishing simulation, so this shouldn’t be an issue.

This combined with the advice from @snori74 is about as good as we can do.

Hope this helps!

**Comment by PulkitSingh256** [comment]
I am just giving an idea. We know that spam filter works with identifying the content of email, subject and the text to image ratio. Maybe we can trick this filter by using homograph attack. We can change some of the letters of our text into some other language's alphabets which looks exactly like the Original word. Like this example this is a normal word " Google  "  and this is a homograph Code "Gооɡⅼе" you can see that they both look exactly same. And maybe we can trick Google into not marking our email as spam. Please tell me if it works as I am out right now and cannot test this.
