### ISSUE TITLE
Emails sent, but failed?!

### ISSUE THREAD

**Issue by krasian** [gophish/gophish#790]
When looking at campaigns, the status of the one in question shows 'Emails Sent'.  When I view results of the campaign, it shows 'Failed'.  When I go to one of the users at the very bottom, I see 'Error sending email'.  Expanding to see the details, I see 'gomail: could not send email 1: 501 5.1.7 Bad sender address syntax'.

I'm assuming the sending profile.  The only difference between this one and the other two I did that just worked is that this one has a From of 'First Last <noreply@myipaddress>' (just an example as I don't want real info exposed here).  For the ones that worked, I only had 'noreply@mydns.com' in the From.  Before you put anything into the field, it does say 'First Last <test@example.com>'.  The postfix log didn't like the IP, so I've tried with a domain name instead.

**Comment by S0larflare** [comment]
You were trying to send email to an address using an IP address? e.g. test@165.231.102.31 (random IP address)?

You can't do that, or, as far as understand, it is physically possible under the RFC with some fiddling...

test@[165.231.102.31]

But it is unlikely the email would be accepted by any ISP along the chain. You're best off using a domain name.

**Comment by jordan-wright** [comment]
@S0larflare is correct. This is almost certainly the case that you are using @x.x.x.x formatted email addresses, which to my understanding aren't valid.

**Comment by jordan-wright** [comment]
And I'm pretty sure we are tracking the UI confusion you mentioned in a separate issue, so I'll close this one out for now.
