### ISSUE TITLE
mail: missing phrase ?

### ISSUE THREAD

**Issue by ARiITRrIX** [gophish/gophish#792]
Hey guys,

I have a problem with my gophish. After I delete gophish 64bit V. 3.0 I got problems ! I downloaded and extracted gophish 4.0 and allowed firfox the gophish certificate to access my gophish. Then I went to Sending Profiles and here I put my data in. I allowed my gmail unsecure connection and apps ! Also the 2 way authentication is not active ! After I would like to test if gophish send the mails to my victims and gophish says mail: missing phrase! What can I do to fix this issue ?

THX for all answers and tipps to solve this ;)

Bye

**Comment by jordan-wright** [comment]
We'd need to see the email template and the sending profile you're using to help track this down.

**Comment by ARiITRrIX** [comment]
Thx for your answer here are the SC 
![screenshot-2017-10-8 sending profiles - gophish](https://user-images.githubusercontent.com/30866999/31316566-375818e2-ac30-11e7-8707-0853a2692810.png)

![gophish](https://user-images.githubusercontent.com/30866999/31316567-3b99c298-ac30-11e7-8fdf-68d601d6eab2.png)


I don't know how to fix them ;(

**Comment by S0larflare** [comment]
Change secure-instagram.com<http://secure-instagram.com> to secure@instagram.com<mailto:secure@instagram.com> or something, currently it's a malformed email

Sent from my iPhone

On 8 Oct 2017, at 12:55, ARiITRrIX <notifications@github.com<mailto:notifications@github.com>> wrote:


Thx for your answer here are the SC
[screenshot-2017-10-8 sending profiles - gophish]<https://user-images.githubusercontent.com/30866999/31316566-375818e2-ac30-11e7-8707-0853a2692810.png>

[gophish]<https://user-images.githubusercontent.com/30866999/31316567-3b99c298-ac30-11e7-8fdf-68d601d6eab2.png>

I don't know how to fix them ;(

**Comment by ARiITRrIX** [comment]
Thx oh Works;) The Problem solved
