### ISSUE TITLE
404 page not found on redirect

### ISSUE THREAD

**Issue by mnaylo** [gophish/gophish#793]
Hello, I have not been able to get my redirect to page working. Intended to go here: https://mnaylo.github.io/phish-rmh/. 

However, I am getting a 404 page not found after entering email and password. Any help would be greatly appreciated, code from landing page below.

         
          <form name="login" action="" method="get" accept-charset="utf-8"><input type="hidden" name="__original_url" value="https://mnaylo.github.io/benefits-rmh/"/>
            <ul>
              <label for="usermail">Email</label>
              <input type="email" name="usermail" placeholder="@rmhfranchise.com" required=""/>
              <label for="password">Password</label>
              <input type="password" required="" placeholder="password"/>
              <input type="submit" value="Login"/>
            </ul>
          </form>

**Comment by S0larflare** [comment]
When you say you're getting a 404 where is it redirecting you to? Did you put the redirect URL into the GoPhish Landing Page in the spae provided? If so, try simplyfiying the form:

 ```
 <form name="login" action="" method="get" accept-charset="utf-8">
        <ul>
          <label for="Email">Email</label>
          <input name="Email" placeholder="@rmhfranchise.com" required=""/>
          <label for="password">Password</label>
          <input type="password" name="password" required="" placeholder="password"/>
          <input type="submit" value="Login"/>
        </ul>
      </form>
```

**Comment by mnaylo** [comment]
Hi, thanks for your response. I do have the landing page specified in the space provided. 

I simplified the form as you suggested below, when I import the site it automatically adds <input type="hidden" name="__original_url" value="https://mnaylo.github.io/benefits-rmh/“/>

Then on test, redirects to: http://13.58.179.186:8080/?__original_url=https%3A%2F%2Fmnaylo.github.io%2Fbenefits-rmh&Email=matt%40rmh.com <http://13.58.179.186:8080/?__original_url=https://mnaylo.github.io/benefits-rmh&Email=matt@rmh.com>, '404 page not found’ presented in browser.

I manually removed the text which got added and it redirects to: http://13.58.179.186:8080/?Email=matt%40rmh.com <http://13.58.179.186:8080/?Email=matt@rmh.com> , '404 page not found’ presented in browser.

Thanks again for the help, if you spot any other problems, please let me know.

**Comment by jordan-wright** [comment]
Try changing the `action="get"` to `action="post"` and see if that helps.

**Comment by jordan-wright** [comment]
Closing this, since there haven't been any updates in a while. @mnaylo let me know if changing the action as indicated above doesn't help fix the issue and we can continue troubleshooting.
