### ISSUE TITLE
Setting up a shared MySQL database

### ISSUE THREAD

**Issue by Clunkline** [gophish/gophish#794]
Hi Jordan,

Some time ago I asked you if it was possible to setup gophish in a distributed way, refer to: https://github.com/gophish/gophish/issues/757.

So here is what I did and where I am now:

I have one system/IP 1 where the phishingpage is hosted(just a webserver in a managed hosting setup, so I can add websites, DB's etc. but cannot run or install all software). On the other system/IP 2 I have gophish running, with the basic setup (so a local sqlite3 DB). 

Because I want the Gophish server (2) listening for people sending their credentials on the webpage on the other server (1), you adviced me to use a shared MySQL database and point each instance to it(not sure what you mean with instance). I tried to set this up, but I couldn't make it work yet. Could you help me out a bit again?

I have created a MySQL database on system/IP 1 and added IP 2 to the whitelist so it can connect to it. I figured that I needed to make some changes in the configuration and searched in older closed issues about it. This ended up in me changing the config.json and what I added/changed was:

 "migrations_prefix" : "db/db_"
 "migrations_path" : "db/migrations/"
 "db_name" : "mysql",
 "db_path" : ***@***.***@(192.168.1.75:3306)/gophish?charset=utf8&parseTime=True&loc=Local"
(with correct information of course)

However after this change it doesn't work anymore and I assume/guess I need to make more changes..

My question(s): What actions do I need to take now to make this work ? For example: How do I point system 1/the phishing page to the DB? How do I copy the contents of the DB to my new DB? What files/lines need to be updated besides the config.json?

I really hope you can help me out again!
Thanks!

Jasper

**Comment by Clunkline** [comment]
Ok, after some more searching, i found out I made a mistake! I had the name of my DB at "db_name" parameter, and this should be MySQL and the name of my DB must be filled in before "?charset". After I changed this it worked! 

Now I only need to make it work to point the phishing pages also to this DB. If you have any  hints/tips/suggestions, thay are still welcome.

Jasper

**Comment by Clunkline** [comment]
So I have setup a MySQL server at IP1 and was able to point Gophish running on IP2 to this DB and I can succesfully create campains etc.

However, now I'm still stuck at the first problem: On IP1 I have created my Phishing page. But this is just a hosting package where I can login with DirectAdmin and place websites in only my "directory" on the webserver. How do i record clicks and credentials from those pages? How do i "connect"/"point" these to my My SQL database? As far as I understand, I can not just run any program (such as Gophish) there.

Could you please help me out with this?

Jasper

**Comment by jordan-wright** [comment]
Hi Jasper,

Unfortunately, you'll need two Gophish instances to do what you're trying to do. Everything in Gophish is stored in the database, including landing page content. The idea for hosting multiple instances is that you have one instance that handles the admin interface side of things and one that is externally reachable so it can host the landing pages.

Both of these are full Gophish instances and they both point to the same MySQL database.

Hope this helps! Let us know if you have any other questions.
