### ISSUE TITLE
Email Template Protocol Issue

### ISSUE THREAD

**Issue by caseyagil** [gophish/gophish#797]
I am following along your guide and typed in {{.URL}} within the Email Templates section.  And ensured <http> was selected.  However the issue I am running into is that GoPhish is automatically changing it back to <other> each time.  
"GoPhish Version 0.3" using the linux version (Ubuntu)

![screen shot 2017-10-11 at 3 41 56 am](https://user-images.githubusercontent.com/3718778/31427708-3305cea8-ae36-11e7-9dd2-5ae8198caa38.png)

**Comment by jordan-wright** [comment]
What do you mean "GoPhish is automatically changing it back to each time"?

What are you expecting to happen, and what do you see happening?

**Comment by stracire** [comment]
I can confirm that some html will change if you switch source-mode off. For example 
**<a><div>Text</div></a>** changes in <div>**<a>Text</a></div>** (Sorry, maybe not the best example). The visual view changes the source from a clickable button to a clickable text.
You will be fine if you stay in source-mode and save the template.

**Comment by jordan-wright** [comment]
I think the HTML may get adjusted like your example shows, but it shouldn't change the functionality.

@caseyagil can you share the HTML you're putting in the editor that changes when you toggle the source, as well as telling us what's happening as well as what you expect to happen?

**Comment by caseyagil** [comment]
Apologize for the super latent response.  I have figured out the issue, it was what stracire has mentioned and now I know not to do it!  Thank you for an amazing open-source product!

**Comment by jordan-wright** [comment]
👍  Good deal! Glad you were able to get it resolved.

**Comment by WaplWearnes** [comment]
Hi all. i just starting to use this Gophish application, I seem to have this issue of the protocol from "http"automatically change to "others" after i save the email template.
