### ISSUE TITLE
GoPhish with Mail-In-A-Box VPS

### ISSUE THREAD

**Issue by Jiglu1** [gophish/gophish#799]
Hi All,

I'm after some advice in relation to GoPhish.

If I was to create a mail-in-a-box mail server on a VPS (digital ocean droplet), how would GoPhish interact with this in order to run phishing campaigns? Is it just a case of entering the mail-in-a-box SMPT server settings into a local install of gophish on an internet connected machine and firing it away?

Thanks

**Comment by jordan-wright** [comment]
I don't have any experience with mail in a box so I'm not sure what it allows in terms of relaying. In a nutshell, once you stand up a mail server that has relaying enabled, you can point Gophish to the mail server (via the SMTP profile settings) and have it forward messages on your behalf.

Any mail in a box specific settings would need to be discussed with those devs.
