### ISSUE TITLE
quotedprintable not found

### ISSUE THREAD

**Issue by n0tty** [gophish/gophish#80]
When we do go get github.com/gophish/gophish at the end, we get
imports mime/quotedprintable: unrecognized import path "mime/quotedprintable"

due to this, the source will not build.

**Comment by n0tty** [comment]
Quite a few missing packages once I installed go1.5

**Comment by jordan-wright** [comment]
Hey there!

Thanks for letting us know about this. Could you dump out the full output of ```go get github.com/gophish/gophish``` as well as the output of ```go version```?

That should help us figure out what is going on in this case.

**Comment by n0tty** [comment]
Hey. I fixed this issue. So apparently there was some problem with my previous Go which was version 1.3
Even though I did an apt-get remove, it wasn't enough needed to remove all the dependencies with --auto-remove and then purge all the files. Only after that did GO v1.5.3 work the right way. Sorry, this isn't the software bug

**Comment by jordan-wright** [comment]
Awesome! That's great to hear. Let us know if you have any feedback!
