### ISSUE TITLE
Is Javascript not supported in "HTML" section of Email Templates?

### ISSUE THREAD

**Issue by shraddha92mhatre** [gophish/gophish#801]
Is Javascript not supported in "HTML" section of Email Templates? 

I was trying to enter current date and time dynamically in the email through below code:
<script language="javascript"> document.write(Date()) </script>

But it doesn't seem to support. There is no template variable for date like {{.FirstName}}. Is there any other way around to display current date and time? I am not looking for date-picker.

**Comment by S0larflare** [comment]
For security reasons JavaScript isn’t allowed to execute in email clients, it’s not a block with GoPhish itself

Sent from my iPhone

On 18 Oct 2017, at 21:18, shraddha92mhatre <notifications@github.com<mailto:notifications@github.com>> wrote:


Is Javascript not supported in "HTML" section of Email Templates?

I was trying to enter current date and time dynamically in the email through below code:

<script language="javascript"> document.write(Date()) </script>

But it doesn't seem to support. There is no template variable for date like {{.FirstName}}. Is there any other way around to display current date and time? I am not looking for date-picker.
