### ISSUE TITLE
What is it for?

### ISSUE THREAD

**Issue by netcenterbr** [gophish/gophish#803]
Hello friends,

I'm starting in the security area and working with endpoint and email protection software.

I found this tool that can help me test the level of protection of the tools I use.

However, I did not understand how the product works.

Basically, what I understand is that it will send emails with simulating pishing attacks.

But will it send email to a single targeted email? Or can I make more than one email?

Do I have to use any SMTP server to configure the submissions? Or does the product already have a mail sending server?

What's the difference from the free version to the paid version?

Thank you.

**Comment by jordan-wright** [comment]
Hi @netcenterbr, thanks for reaching out.

Phishing simulation tools aren't necessarily designed to help test email security controls. Instead, it tests an organization's exposure to phishing by determining how many employees would click on fake phishing emails.

Gophish sends emails to groups of users. You can run multiple campaigns to different groups, each with their own email.

You need an SMTP server setup to use Gophish. There is not a built-in server included.

There is no paid version, no will there be.

For all other questions, I highly, highly encourage you to refer to our excellent documentation: https://www.gitbook.com/book/gophish/user-guide/details.

Hope this helps!
