### ISSUE TITLE
The email arrived!

### ISSUE THREAD

**Issue by netcenterbr** [gophish/gophish#804]
Hi,

The email arrived!

I made a campaign using an email from (Gmail), sending it to two recipients of my company.

So, I think! Is my antispam system flawed? Should he block?

I opened the email but did not update the (open) status on the dashboard yet. After watching a video, I noticed that I should put the URL link in the campaign, with the name of my GoPish URL (localhost). So when I opened the email and clicked, the status of the dashboard was updated.

In order for dashboard status to work, the campaign URL link must be published on the Internet (as it says in the documentation) so people will click on it to communicate with my GoPhish Server. But should I publish it on what port? (TCP: 3333)?

Thank you.

**Comment by stracire** [comment]
Mostly the ports :80 and :443 aren't blocked, so I recommend to use these (they are the default settings). On the launch page: The URL you enter is https://domain.com or http://domain.com (without any port if you use the default ports).  

The links and the tracker inside the e-mail will use this entered URL and add an unique code.
Example link: **http://domain.com/**?rid=UoAQq3C

Test if the domain you are entering is available on the web. Enter it into your own browser and look if you get the following error:  404 page not found. You are using the right domain or IP if you get this message.

Please note, some mail clients do not load images by default, so you can't always notice if someone has opened the e-mail. The clicks however, never lie.
