### ISSUE TITLE
DashBoard informations

### ISSUE THREAD

**Issue by jerempan** [gophish/gophish#806]
Hello, 

I installed gophish and started my first campaign for test. First of all, it was just a test to see if I was getting the emails. No problems for that but i don't see on dashboard if the users click on the link or attachment. 

Do you have a answer for this problem ? 
![capture](https://user-images.githubusercontent.com/33053824/31933719-35014a2e-b8aa-11e7-8ac4-977be4a76708.PNG)

thanks you !

**Comment by S0larflare** [comment]
I’m assuming you have sent yourself the test email, if so, did you see the landing page you had set up when you clicked the link?

Sent from my iPhone

On 24 Oct 2017, at 09:58, jerempan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

I installed gophish and started my first campaign for test. First of all, it was just a test to see if I was getting the emails. No problems for that but i don't see on dashboard if the users click on the link or attachment.

Do you have a answer for this problem ?
[capture]<https://user-images.githubusercontent.com/33053824/31933719-35014a2e-b8aa-11e7-8ac4-977be4a76708.PNG>

thanks you !

**Comment by jerempan** [comment]
Thank you for the answer . I just have the content of the email with my attachment but my landing page is missing,..

**Comment by jordan-wright** [comment]
First, there is no attachment tracking in Gophish right now.

Second, what is the content of your email? What do you see when you click the link?

**Comment by jerempan** [comment]
My email contains a little text with a link to any website and a pdf attachment. What I don't understand is how to put landing page in the content of my mail.

**Comment by S0larflare** [comment]
If you put {{.URL}} in the email it will automatically make that into the link you specify when you start the campaign and match that with the landing page you chose. If you check the documentation this is pretty well explained, I’d suggest you check in there and let us know if you need help beyond that

Sent from my iPhone

On 25 Oct 2017, at 07:06, jerempan <notifications@github.com<mailto:notifications@github.com>> wrote:


My email contains a little text with a link to any website and a pdf attachment. What I don't understand is how to put landing page in the content of my mail.

**Comment by jerempan** [comment]
It works 👍  thank you all !

**Comment by jerempan** [comment]
I have an other question, Is there a user limit ?

**Comment by S0larflare** [comment]
What do you mean by user limit, a limit of how many people you can send the campaign to? Not really. You may notice lag with the console if you try to view a large campaign in it though. The biggest one I have done was around 5,500 people and the console was usable then (with a slight modification to turn off the refresh). Anything bigger than that, I'd recommend using the API.

**Comment by jerempan** [comment]
Okay great ! i want send my campaign to 100 users. i  will use a CSV file.
