### ISSUE TITLE
404 Page not found

### ISSUE THREAD

**Issue by Yannis765** [gophish/gophish#808]
Hallo Jordan, 
I spent the whole afternnoon to figure, why i am reaching the 404 page not found, but to no avail. 
I have set up some landing pages in the admin console, and am trying to reach them by typing http://localhost:3334(phish server is listening here) on my own machine. How can I not see any of the pages?
Is there a specific folder where i should install manually one of these landing webpages i created? Is the issue related to the rid parameter I've read somewhere? How can I access them from my local machine? 

I will appreciate your help. I have almost no strength to look into it further today. :)

**Comment by jordan-wright** [comment]
You will only see the pages if you launch a campaign. Gophish loads pages dynamically based on an `rid` parameter set for each target in a campaign.

Just visiting the root web server like you're doing will result in a 404 page.

**Comment by Yannis765** [comment]
Hi Jordan,
thank you for the fast reply. I launched a campaign, I used an e-mail with a link pointing to the localhost:3334, opened the e-mail from the same host, but still got the 404 page not found. Do I have to have a public ip, and the target should come from the outside world?

**Comment by Yannis765** [comment]
And the rid is not sent with any request :((

**Comment by Yannis765** [comment]
can you please share how the request should look like in the url
eg. www.public.ip?rid=eTLondw            ?
