### ISSUE TITLE
Starting with the Go phish

### ISSUE THREAD

**Issue by shirshendud** [gophish/gophish#809]
We would like to run a project of phishing at our organization and I am new to this wonderfully created project. There is a download button and on clicking several options are coming. I want to download gophish-v0.4-windows-32bit.zip but then I am able to see one Source code (zip) and another Source code (tar.gz). Can anyone please suggest as to which to download and then the next steps that I will be doing to launch the initial setup. My question might be very basic but I accept that I am a greenhorn at this. Kindly help

**Comment by S0larflare** [comment]
If what you are after is the latest release, then choose gophish-v0.4-windows-32bit.zip (or the 64bit varient if you have a 64bit machine and OS). That is pre-compiled and ready to go, just extract and run it.

If you want the very latest version of the code, then you would want to download the repo source, install go and any prerequisites and then build it. 

For most, downloading the binary and running it is all they need.

**Comment by jordan-wright** [comment]
Here’s a link to our excellent user guide which tells you how to install, configure, and run Gophish. I definitely recommend reading through this as it’ll answer most common questions.

Hope this helps!

https://gophish.gitbooks.io/user-guide/content/

**Comment by shirshendud** [comment]
Thank you very much for your help and prompt reply. Keep doing great things in the coming days.
