### ISSUE TITLE
Multiple phishing servers - https and http

### ISSUE THREAD

**Issue by ekleintop** [gophish/gophish#810]
I have a special use case that requires I have both an https and http phishing server running at the same time.  I modified gophish.go, config.go, and config.json to create a 3rd server - call it phishingserver2.  I can see the server listening on all 3 ports (1 for https admin, 1 for https phishing, and 1 for http phishing).  I also added a second router, CreatePhishingRouter2, in route.go to handle the second phishing server requests.  My issue is phishingserver2 never sends a response back to the browser.  Admin and phishingserver1 both respond as expected.  Am I missing something somewhere else that links the listening server to route.go?  

Many thanks,

Eric

**Comment by ekleintop** [comment]
Duh - firewall issue :( - apologies.

**Comment by russklvacek** [comment]
You say you modified the .go source files; is that a requirement to get a second phish server setup? I would like to setup a second phish server with it's own independent SSL cert etc. on a single host with only one admin console.
