### ISSUE TITLE
Template Reference Documentation

### ISSUE THREAD

**Issue by franckyz0r** [gophish/gophish#812]
Hi,

Please correct in template reference doc the following:
`{{.Tracker}} | An alias for <img src=" {{. TrackingUrl}} " />`
to:
`{{.Tracker}} | An alias for <img src=" {{. TrackingURL}} " />`
as for some might be confusing why the template editor will throw an error when saving if you use `TrackingUrl`.

I know is something very small, but for some that will copy-paste that placeholder would be nice.

Have a nice day!

**Comment by jordan-wright** [comment]
Good call - fixed!
