### ISSUE TITLE
Credentials are not being recorded

### ISSUE THREAD

**Issue by matthewclarkson007** [gophish/gophish#814]
This issue is only happening with 4.0. 

After the link is being clicked from the email which then takes the target to the site to enter their details, the ID and password being entered are not being recorded nor does it ever say "submitted". The campaign reaches, "Clicked link" and never goes any further. Is there a database entry where the credentials are stored ? Am I doing something wrong? 

I tested the same process with 2.0 and it works fine.

**Comment by jordan-wright** [comment]
So this wasn't the case in version 0.3? Can you post the HTML for the landing page template on this issue so we can take a look? We'll also need to see what settings you're using for the landing page ("capture credentials", etc.)

**Comment by matthewclarkson007** [comment]
I never checked 0.3. This is a landing page for Leetcode. Both capture passwords and capture submitted data are turned on. 

<!DOCTYPE html><html><head>
	<base href="https://leetcode.com/accounts/login/"/><meta charset="utf-8"/><script type="text/javascript">window.NREUM||(NREUM={}),__nr_require=function(e,n,t){function r(t){if(!n[t]){var o=n[t]={exports:{}};e[t][0].call(o.exports,function(n){var o=e[t][1][n];return r(o||n)},o,o.exports)}return n[t].exports}if("function"==typeof __nr_require)return __nr_require;for(var o=0;o<t.length;o++)r(t[o]);return r}({1:[function(e,n,t){function r(){}function o(e,n,t){return function(){return i(e,[c.now()].concat(u(arguments)),n?null:this,t),n?void 0:this}}var i=e("handle"),a=e(2),u=e(3),f=e("ee").get("tracer"),c=e("loader"),s=NREUM;"undefined"==typeof window.newrelic&&(newrelic=s);var p=["setPageViewName","setCustomAttribute","setErrorHandler","finished","addToTrace","inlineHit","addRelease"],d="api-",l=d+"ixn-";a(p,function(e,n){s[n]=o(d+n,!0,"api")}),s.addPageAction=o(d+"addPageAction",!0),s.setCurrentRouteName=o(d+"routeName",!0),n.exports=newrelic,s.interaction=function(){return(new r).get()};var m=r.prototype={createTracer:function(e,n){var t={},r=this,o="function"==typeof n;return i(l+"tracer",[c.now(),e,t],r),function(){if(f.emit((o?"":"no-")+"fn-start",[c.now(),r,o],t),o)try{return n.apply(this,arguments)}finally{f.emit("fn-end",[c.now()],t)}}}};a("setName,setAttribute,save,ignore,onEnd,getContext,end,get".split(","),function(e,n){m[n]=o(l+n)}),newrelic.noticeError=function(e){"string"==typeof e&&(e=new Error(e)),i("err",[e,c.now()])}},{}],2:[function(e,n,t){function r(e,n){var t=[],r="",i=0;for(r in e)o.call(e,r)&&(t[i]=n(r,e[r]),i+=1);return t}var o=Object.prototype.hasOwnProperty;n.exports=r},{}],3:[function(e,n,t){function r(e,n,t){n||(n=0),"undefined"==typeof t&&(t=e?e.length:0);for(var r=-1,o=t-n||0,i=Array(o<0?0:o);++r<o;)i[r]=e[n+r];return i}n.exports=r},{}],4:[function(e,n,t){n.exports={exists:"undefined"!=typeof window.performance&&window.performance.timing&&"undefined"!=typeof window.performance.timing.navigationStart}},{}],ee:[function(e,n,t){function r(){}function o(e){function n(e){return e&&e instanceof r?e:e?f(e,u,i):i()}function t(t,r,o,i){if(!d.aborted||i){e&&e(t,r,o);for(var a=n(o),u=m(t),f=u.length,c=0;c<f;c++)u[c].apply(a,r);var p=s[y[t]];return p&&p.push([b,t,r,a]),a}}function l(e,n){v[e]=m(e).concat(n)}function m(e){return v[e]||[]}function w(e){return p[e]=p[e]||o(t)}function g(e,n){c(e,function(e,t){n=n||"feature",y[t]=n,n in s||(s[n]=[])})}var v={},y={},b={on:l,emit:t,get:w,listeners:m,context:n,buffer:g,abort:a,aborted:!1};return b}function i(){return new r}function a(){(s.api||s.feature)&&(d.aborted=!0,s=d.backlog={})}var u="nr@context",f=e("gos"),c=e(2),s={},p={},d=n.exports=o();d.backlog=s},{}],gos:[function(e,n,t){function r(e,n,t){if(o.call(e,n))return e[n];var r=t();if(Object.defineProperty&&Object.keys)try{return Object.defineProperty(e,n,{value:r,writable:!0,enumerable:!1}),r}catch(i){}return e[n]=r,r}var o=Object.prototype.hasOwnProperty;n.exports=r},{}],handle:[function(e,n,t){function r(e,n,t,r){o.buffer([e],r),o.emit(e,n,t)}var o=e("ee").get("handle");n.exports=r,r.ee=o},{}],id:[function(e,n,t){function r(e){var n=typeof e;return!e||"object"!==n&&"function"!==n?-1:e===window?0:a(e,i,function(){return o++})}var o=1,i="nr@id",a=e("gos");n.exports=r},{}],loader:[function(e,n,t){function r(){if(!x++){var e=h.info=NREUM.info,n=d.getElementsByTagName("script")[0];if(setTimeout(s.abort,3e4),!(e&&e.licenseKey&&e.applicationID&&n))return s.abort();c(y,function(n,t){e[n]||(e[n]=t)}),f("mark",["onload",a()+h.offset],null,"api");var t=d.createElement("script");t.src="https://"+e.agent,n.parentNode.insertBefore(t,n)}}function o(){"complete"===d.readyState&&i()}function i(){f("mark",["domContent",a()+h.offset],null,"api")}function a(){return E.exists&&performance.now?Math.round(performance.now()):(u=Math.max((new Date).getTime(),u))-h.offset}var u=(new Date).getTime(),f=e("handle"),c=e(2),s=e("ee"),p=window,d=p.document,l="addEventListener",m="attachEvent",w=p.XMLHttpRequest,g=w&&w.prototype;NREUM.o={ST:setTimeout,SI:p.setImmediate,CT:clearTimeout,XHR:w,REQ:p.Request,EV:p.Event,PR:p.Promise,MO:p.MutationObserver};var v=""+location,y={beacon:"bam.nr-data.net",errorBeacon:"bam.nr-data.net",agent:"js-agent.newrelic.com/nr-1044.min.js"},b=w&&g&&g[l]&&!/CriOS/.test(navigator.userAgent),h=n.exports={offset:u,now:a,origin:v,features:{},xhrWrappable:b};e(1),d[l]?(d[l]("DOMContentLoaded",i,!1),p[l]("load",r,!1)):(d[m]("onreadystatechange",o),p[m]("onload",r)),f("mark",["firstbyte",u],null,"api");var x=0,E=e(4)},{}]},{},["loader"]);</script><script type="text/javascript">window.NREUM||(NREUM={});NREUM.info={"beacon":"bam.nr-data.net","queueTime":0,"licenseKey":"8d5fb92f6e","agent":"","transactionName":"ZwMAYEdSCktRWxZRXV5JJEFbUBBRX1ZNWV5cBxdAXR0FW1NXF1ZGHhALUUJAXnRfXwtWZFkDFRpSVhA=","applicationID":"2098939","errorBeacon":"bam.nr-data.net","applicationTime":19}</script>
	<title></title>
	<meta property="og:title" content=""/><meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport"/><meta name="description" content="Level up your coding skills and quickly land a job. This is the best place to expand your knowledge and get prepared for your next interview."/><meta property="og:image" content="/static/images/LeetCode_Sharing.png"/><meta property="og:description" content="Level up your coding skills and quickly land a job. This is the best place to expand your knowledge and get prepared for your next interview."/>
	<link href="/apple-touch-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
	<link href="/apple-touch-icon-60x60.png" rel="apple-touch-icon" sizes="60x60"/>
	<link href="/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
	<link href="/apple-touch-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/>
	<link href="/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
	<link href="/apple-touch-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/>
	<link href="/apple-touch-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
	<link href="/apple-touch-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>
	<link href="/apple-touch-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/>
	<link href="/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
	<link href="/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
	<link href="/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png"/>
	<link href="/favicon-160x160.png" rel="icon" sizes="160x160" type="image/png"/>
	<link href="/favicon-192x192.png" rel="icon" sizes="192x192" type="image/png"/><meta name="application-name" content="LeetCode"/><meta name="msapplication-TileColor" content="#da532c"/><meta name="msapplication-TileImage" content="/mstile-144x144.png"/><script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o)
  ,m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a
  ,m)})(window,document,'script','//www.google-analytics.com/analytics.js','ga'
  );
  ga('create', 'UA-6849839-6', 'leetcode.com');
  ga('require', 'displayfeatures');
  ga('send', 'pageview');
</script>
	<link href="/static/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet"/>
	<link href="/static/font-awesome/css/font-awesome.min.css" rel="stylesheet"/>
	<link href="/static/bootstrap-table/dist/bootstrap-table.min.css" rel="stylesheet"/>
	<link href="/static/CACHE/css/fff5b45a5139.css" rel="stylesheet" type="text/css"/>
	<style type="text/css">#id_remember {
    margin-right: 5px;
  }
	</style>
	<script src="/static/common/js/portability_check.js"></script><script src="/static/jquery/dist/jquery.min.js"></script><script src="/static/jquery-sticky/jquery.sticky.js"></script><script src="/static/clipboard/dist/clipboard.min.js"></script><script>
      $(document).ready(function(){
        $('.sticky').sticky({topSpacing:0});
      });

      var userStatus = {
        isSignedIn:  false,
        isPremium: false ,
        isAdmin:  false ,
        
      };

      function openNavList() {
        var menu = $('#nav-menu-btn');
        var navbar = $('.navbar-collapse');
        if(!navbar.hasClass('collapsing')) {
          if(navbar.hasClass('in')) {
            menu.removeClass('open');
          } else {
            menu.addClass('open');
          }
        }
      };
    </script><script src="/static/angular/angular.min.js"></script><script src="/static/jquery-ui-dist/jquery-ui.min.js"></script>
</head>
<body>
<div class="content-wrapper">
<div class="navbar navbar-inverse navbar-extra">
<div class="container">
<div class="navbar-header">
<div id="nav-user-mobile-app"> </div>
<button class="navbar-toggle pull-left" data-target=".navbar-collapse" data-toggle="collapse" id="nav-menu-btn" onclick="openNavList()" type="button"></button><a class="navbar-brand" href="/"><img alt="LeetCode" height="30px" src="/static/images/LeetCode_nav.png"/> </a></div>

<div class="navbar-collapse collapse">
<ul class="nav navbar-nav">
	<li class="visible-sm" id="storeNav"> </li>
	<li class="subscribe-sm" id="subscribe"><a href="/subscribe/"> Premium </a></li>
	<li id="problemsNav"><a href="/problemset/all/">Problems</a></li>
	<li class="dropdown"><a aria-expanded="false" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button">Mock </a>
	<ul class="dropdown-menu">
		<li><a href="/mockinterview/">Mock Interview</a></li>
		<li><a href="/mockinterview/session/list/">Past Sessions</a></li>
	</ul>
	</li>
	<li><a href="/contest/">Contest</a></li>
	<li class="hide" id="coursesNav"><a href="/courses/">Courses</a></li>
	<li id="articlesNav"><a href="/articles/">Articles</a></li>
	<li id="discussNav"><a href="https://discuss.leetcode.com" target="_blank">Discuss</a></li>
	<li class="visible-xs"><a href="/playground/" onclick="ga(&#39;send&#39;, &#39;event&#39;, &#39;playground&#39;, &#39;click&#39;, &#39;nav-bar&#39;);">Playground</a></li>
	<li class="hidden-sm" id="dot"><a>•</a></li>
	<li class="dropdown hidden-sm" id="storeNav"><a aria-expanded="false" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button"><span class="navitem-highlight">  Store </span> </a>
	<ul class="dropdown-menu store-dropdown">
		<li><a href="/store/" onclick="ga(&#39;send&#39;, &#39;event&#39;, &#39;store&#39;, &#39;click&#39;, &#39;nav&#39;);"><span class="text-orange">Redeem</span></a></li>
		<li><a href="/subscribe/" onclick="ga(&#39;send&#39;, &#39;event&#39;, &#39;subscribe&#39;, &#39;click&#39;, &#39;nav&#39;);"><span class="text-orange">Premium</span></a></li>
		<li><a href="/book/" onclick="ga(&#39;send&#39;, &#39;event&#39;, &#39;book&#39;, &#39;click&#39;, &#39;nav-bar&#39;);"><span class="text-orange">Book</span></a></li>
	</ul>
	</li>
	<li class="hide" id="storyNav"><a href="/story/" onclick="ga(&#39;send&#39;, &#39;event&#39;, &#39;story&#39;, &#39;click&#39;, &#39;nav&#39;);"><span class="navitem-highlight">Story</span></a></li>
</ul>

<ul class="nav navbar-nav navbar-right nav-user-module" id="navbar-right">
	<li class="subscribe-btn hidden-sm" id="subscribe"><a class="subscribe text-white" href="/subscribe/">Premium </a></li>
	<li class="hidden-xs hidden-sm" id="playgroundNav"> </li>
	<li id="nav-user-app"> </li>
</ul>
</div>
</div>
</div>

<div class="container">
<form action="" class="form-signin" method="POST"><input name="__original_url" type="hidden" value="https://leetcode.com/accounts/login//accounts/login/"/>
<h3 class="form-signin-heading">Sign In</h3>

<hr/> <input name="csrfmiddlewaretoken" type="hidden" value="g7NflG9Yr0EHrYK30GyWA6Wlmoo2HYrnkBa2p8rjV3hjEQA0QWehBCzkDr5irctp"/>
<div class="form-group"><input autofocus="autofocus" id="id_login" name="login" placeholder="Username or e-mail" required="" type="text"/></div>

<div class="form-group"><input id="id_password" name="password" placeholder="Password" required="" type="password"/></div>
<label class="form-group"><input id="id_remember" name="remember" type="checkbox"/>Remember Me</label>

<div class="form-group"><button class="btn btn-primary" type="submit">Sign In</button><a class="pull-right" href="/accounts/password/reset/">Forgot Password?</a></div>

<hr/>
<div class="row socialaccount_ballot">
<p class="text-center">or you can sign in with</p>
<style type="text/css">.socialaccount_providers li {
    float: left;
    list-style: none;
  }
  .socialaccount_providers li a {
    width: 40px;
    height: 40px;
    display: block;
    border: 0;
    text-indent: -999em;
    overflow: hidden;
    background-color: transparent;
    background-repeat: no-repeat;
    text-align: left;
    direction: ltr;
  }
  .github {
    background: transparent url(/static/icons/39x40/github.png) no-repeat 0 0;
    margin: 0 10px 10px 0;
  }
  .linkedin {
    background: transparent url(/static/icons/39x40/linkedin.png) no-repeat 0 0;
    margin: 0 10px 10px 0;
  }
  .facebook {
    background: transparent url(/static/icons/39x40/facebook.png) no-repeat 0 0;
    margin: 0 10px 10px 0;
  }
  .google {
    background: transparent url(/static/icons/39x40/google.png) no-repeat 0 0;
    margin: 0 10px 10px 0;
  }
</style>
<ul class="socialaccount_providers">
	<li><a class="socialaccount_provider facebook" href="/accounts/facebook/login/" title="Facebook">Facebook</a></li>
	<li><a class="socialaccount_provider google" href="/accounts/google/login/" title="Google">Google</a></li>
	<li><a class="socialaccount_provider linkedin" href="/accounts/linkedin/login/" title="LinkedIn">LinkedIn</a></li>
	<li><a class="socialaccount_provider github" href="/accounts/github/login/" title="GitHub">GitHub</a></li>
</ul>
</div>
</form>
</div>

<div id="playground-create-modal"> </div>
</div>

<footer class="site-footer">
<div class="container">
<hr/>
<div class="row">
<div class="col-sm-4 copyright"><span>Copyright © 2017 LeetCode</span></div>

<div class="col-sm-8 text-right">
<div class="links"><a data-target="#supportModal" data-toggle="modal">Contact Us</a>  |  <a href="/faq/">F<span class="hide-too-small">requently </span>A<span class="hide-too-small">sked </span>Q<span class="hide-too-small">uestions</span></a>  |  <a href="/tos/">Terms of Service</a></div>

<div class="privacy-policy"><a class="iubenda-white iubenda-embed" href="//www.iubenda.com/privacy-policy/499831" title="Privacy Policy">Privacy Policy</a></div>
</div>
</div>
</div>
</footer>

<div class="modal fade simple-modal" id="supportModal" role="dialog">
<div class="modal-center">
<div class="modal-dialog">
<div class="modal-content">
<div class="modal-header"><button aria-hidden="true" class="close" data-dismiss="modal" type="button">×</button><span class="text-lg text-300"> How can we help you?</span></div>

<div class="modal-body">
<div class="row text-center">
<div class="col-sm-4"><br/>
<a class="support-module btn btn-default" href="mailto:billing@leetcode.com?subject=Billing%20Issue&amp;body=Name:%0D%0A%0D%0AUsername:%0D%0A%0D%0AMessage:%0D%0A%0D%0A" target="_blank"><text>Billing &amp; Account</text> </a></div>

<div class="col-sm-4"><br/>
<a class="support-module btn btn-default" href="mailto:support@leetcode.com?subject=General%20Support&amp;body=Name:%0D%0A%0D%0AUsername:%0D%0A%0D%0AMessage:%0D%0A%0D%0A" target="_blank"><text>General Support</text> </a></div>

<div class="col-sm-4"><br/>
<a class="support-module btn btn-default" href="mailto:feedback@leetcode.com?subject=Other%20Inquiries&amp;body=Name:%0D%0A%0D%0AUsername:%0D%0A%0D%0AMessage:%0D%0A%0D%0A" target="_blank"><text>Other Inquiries</text> </a></div>
</div>
</div>
</div>
</div>
</div>
</div>
<script src="/static/bootstrap/dist/js/bootstrap.min.js"></script><script src="/static/bootstrap-table/dist/bootstrap-table.min.js"></script><script type="text/javascript" src="/static/CACHE/js/bf382ccd9617.js"></script><script src="https://cdn.ravenjs.com/3.19.1/raven.min.js" crossorigin="anonymous"></script><script src="/static/common/js/raven_config.js"></script><script type="text/javascript" src="/static/webpack_bundles/common-vendor.2d349bdd.js"></script><script type="text/javascript" src="/static/webpack_bundles/apps/authentication/nav_user.entry.3f02bf0b.js"></script><script type="text/javascript" src="/static/webpack_bundles/common/js/base.entry.d7b0bdf6.js"></script><script type="text/javascript" src="/static/webpack_bundles/apps/playground/create.entry.806c5fe0.js"></script><script>
  $(function() {
    $('input[type=text], input[type=password]').addClass('form-control');
    
    
    
    
    
    
    
    
  });
</script><script>
      (function($, w, d){
        var loader = function () {
          var s = d.createElement("script"),
              tag = d.getElementsByTagName("script")[0];
          s.src = "//cdn.iubenda.com/iubenda.js";
          tag.parentNode.insertBefore(s,tag);
          s.onload = setFooterStyles;
        };
        if (w.addEventListener) {
          w.addEventListener("load", loader, false);
        } else if (w.attachEvent) {
          w.attachEvent("onload", loader);
        } else { w.onload = loader; }

        $(function() {
          $('#navbar-right img').addClass('img-rounded');
          setFooterStyles();
        });

        function setFooterStyles() {
          var $footer = $('.site-footer'),
              height = $footer.outerHeight();
          $footer.css('margin-top', -height);
          $('.content-wrapper').css('margin-bottom', height);
        }
      }(jQuery, window, document));
      try {
        ace.config.set("basePath", "/static/ace-builds/src-noconflict/")
      } catch(err) {}
    </script>

</body></html>
