### ISSUE TITLE
Disable static folder browsing

### ISSUE THREAD

**Issue by wshi-sp** [gophish/gophish#815]
Is there a way to disable browsing the static folder by end users?  Right now, users can browse the folder and see list of files.  For example, type in http://x.x.x.x/static/ would give list of files in the static folder, which is a security concern.

**Comment by jordan-wright** [comment]
Yeah, this has been something I've been meaning to fix. Whether or not it's a security concern depends on if sensitive files are being stored in that folder.

However, I agree - this is something that we can fix. I'll knock this out after finishing up some other outstanding issues.

Thanks for the report!

**Comment by jordan-wright** [comment]
This should be fixed in the latest source. Let me know if you continue to run into issues with this.

Thanks for the report!

**Comment by valoulou** [comment]
Hello Jordan,

Do you have some news about this subject ? Because I tested the 0.6 version and it is possible to list the endpoint directory.

Thanks and good job for your tool

**Comment by jordan-wright** [comment]
Hi @valoulou,

This has been fixed in the latest source version but has not been included in a release yet. I don't have a solid timeline on when the next release will be, since we're in the middle of adding a few really awesome features 😄

**Comment by valoulou** [comment]
Ok perfect thanks
