### ISSUE TITLE
{{.URL}} link not opening with certain clients

### ISSUE THREAD

**Issue by jajueng** [gophish/gophish#817]
Hello,

We just recently setup GoPhish, and it seems as though our link to the landing page isn't working on certain devices/clients. It has worked fine on all Windows systems running Outlook 2016. However, Outlook on a mobile device doesn't open the link at all when clicked. Copying the link url provides the following:

`x-thread://-2111433710/21780`

Which obviously isn't the URL of our landing page.

When opening the email from Office365, the link isn't displayed as clickable and instead displays:

`[SERVERURL?rid=SeKGiYv]here.`

We also reported issues with the link not opening correctly on Thunderbird on a Linux client. The source for it looks like:

`<a href=3D"SERVERURL?rid=3DtPkSVFK">here</a>`

So it seems like the client doesn't know what the reference is? The same issue was reported in Outlook for Mac on a Macbook as well.

I didn't see anything in the documentation about this issue, so forgive me if it's a simple question or issue. I'd appreciate any help or feedback on the matter!

**Comment by jordan-wright** [comment]
Are you making sure to put the full URL in `http://x.x.x.x` format as the URL field when setting up the campaign?

**Comment by jajueng** [comment]
Hmmm no I did not! I think that's it, I left out the http://

Is an IP address required as well? I used the domain URL instead.

**Comment by jordan-wright** [comment]
The server URL should be fine, as long as it resolves to your Gophish listener.

I bet the http:// is what's messing it up. It's quite possible that some clients treat these links differently, with some thinking they're relative links.

Give the full URL a shot and let me know if that fixes the issue.

**Comment by jajueng** [comment]
Just tested it, that seemed to be it. I figured it would be something small. Thanks so much! 

Now to look into SQL errors when importing pages... But I think that's just an issue with the age of the SQL install we're using.

**Comment by jordan-wright** [comment]
Good deal! Glad you were able to get it resolved.
