### ISSUE TITLE
I cant get further information after launching GoPhish campaign.

### ISSUE THREAD

**Issue by coderun3** [gophish/gophish#818]
When I launch a campaign, it doesn't tell me if the person I sent the phishing email to have clicked on it and opened it up. It also doesn't show the submitted data. All it shows is an email sent successfully. Please help me solve it step by step because I've read all the other issues regarding mine. thank you and have a good one!

**Comment by jordan-wright** [comment]
We're going to need a lot more information before we can begin to help.

What have you tried? Can you provide the template you're using? What do you see in your browser when you click the link in the email? What do you see in the terminal output? Etc. etc.

**Comment by coderun3** [comment]
I first used Social scammer a program that makes free templates then I decided to not use the template and just have a link in the email template, but when I click the email in my inbox and go back to gophish and try refresh nothing there. Do I need to port forward or use ngrok as my listening url? i've tried everything.

**Comment by jordan-wright** [comment]
I'm afraid there's still not nearly enough information for us to troubleshoot.

Can you provide the email template? What are you putting in your campaign configuration? What do you see in the browser when you click the link? What terminal output do you see when you click the link and open the email?

**Comment by Th0r9ra** [comment]
@coderun3 email johnwade708@yahoo.com

**Comment by S0larflare** [comment]
You haven’t given any information at all here. Please use the template and give as much info about the problem as you can.

Sent from my iPhone

On 5 Jan 2018, at 11:04, Th0r9ra <notifications@github.com<mailto:notifications@github.com>> wrote:


@coderun3<https://github.com/coderun3> email johnwade708@yahoo.com<mailto:johnwade708@yahoo.com>
