### ISSUE TITLE
Landing page not working

### ISSUE THREAD

**Issue by jerempan** [gophish/gophish#819]
Hello everyone, 

 I have a problem with landing page, because landing page works if gophsih is local but if I move it to a server, it doesn't work anymore. I changed the ip in config. json...

Thank you in advance for your help.

I have version 0.4.

**Comment by jordan-wright** [comment]
We'll need more information to help troubleshoot this. Please refer to the original issue template for what information we need, which includes:

* Any terminal output you can provide
* The landing page in question
* What you see in the browser vs. what you expect to see
* What steps to reproduce the issue

**Comment by jerempan** [comment]
hello , 

thanks you for your feedback . it's resolved I put my gophish file locally on my server. It's better that way.
