### ISSUE TITLE
Logo is trimmed on mobile devices

### ISSUE THREAD

**Issue by jordan-wright** [gophish/gophish#82]
![image](https://cloud.githubusercontent.com/assets/1317288/12457680/87205014-bf6b-11e5-82b2-a38ff461cc0f.png)

Need to change the layout of the logo.

**Comment by rfdevere** [comment]
Seems to be iPhone 5 and slimmer iOS Devices with iPhone 6 & 6+ fine. Looking at https://dev.windows.com/en-us/microsoft-edge/tools/screenshots/#http://getgophish.com 

Nibblers opinion is worth a look in to provide a good overview of how the site is and great for finding issues you didn't know you had. http://nibbler.silktide.com/en_US/reports/getgophish.com
