### ISSUE TITLE
Unable to open through browser after installation

### ISSUE THREAD

**Issue by shirshendud** [gophish/gophish#820]
After the initial installation it is showing admin + phishing both are running but unable to open through browser . We checked SYSLOG and found 2 errors
1. **Its showing unable to connect DB**
2. **Its showing MySQL DB can't restart its process**
Please help

**Comment by jordan-wright** [comment]
Please refer to the "Using MySQL" section of our user guide: https://gophish.gitbooks.io/user-guide/content/installation.html

If this doesn't help, please provide your configuration file (with the MySQL password redacted as necessary) and the output from the terminal.
