### ISSUE TITLE
Dashboard Loading Circle Only

### ISSUE THREAD

**Issue by turnerdb** [gophish/gophish#821]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
v0.4.0
Brief description of the issue: 
On the dashboard screen, the new features won't load.  Just a loading circle.
What are you expecting to see happen? :
The new timeline and chart breakdown
What are you seeing happen?
Loading circle.
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
I upgraded my Kali instance first and everything works fine.  The live instance we use is on CentOS.  The dashboards loads just fine via Kali but only shows the loading circle on the CentOS box.

Thanks.

**Comment by turnerdb** [comment]
Seems to be an issue with all the new screens.  Can't get the details screen to load either.

**Comment by jordan-wright** [comment]
You might try opening your browsers developer console and seeing if there are any errors showing up. Chances are, api requests are failing for some reason.

**Comment by turnerdb** [comment]
campaign_results.min.js:1 Uncaught ReferenceError: Highcharts is not defined
    at HTMLDocument.<anonymous> (campaign_results.min.js:1)
    at d (vendor.min.js:2)
    at Object.fireWith [as resolveWith] (vendor.min.js:2)
    at Function.ready (vendor.min.js:1)
    at HTMLDocument.St (vendor.min.js:1)

Highcharts not defined.  Suggestions?

Thank you!

**Comment by jordan-wright** [comment]
You mentioned that this started happening after an upgrade, right? If so, I recommend making sure you're copying over the full `static` directory included in the latest release. It looks like it's not finding Highcharts, which makes me things there's something wrong with the static assets.

**Comment by jordan-wright** [comment]
Closing this one since there haven't been any updates in a while. @turnerdb if you're still having this issue, let me know if the previous comment doesn't help and we can continue troubleshooting.
