### ISSUE TITLE
Email-Opened/Clicked-Link Not Being Tracked

### ISSUE THREAD

**Issue by jhl090** [gophish/gophish#822]
First off, thank you Mr. Wright this is an awesome open-source project. I hope to contribute more functionality into this project asap.

**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: v0.4.0. No special configurations were created. I just downloaded the zip, extracted, and launched GoPhish via "sudo ./gophish" on my terminal. 

Brief description of the issue: "No Email Opened" or "Clicked Link" events reported after a campaign is launched against myself. 

What are you expecting to see happen? : After receiving the "malicious" message from the campaign, I open and click the link. On my dashboard, "No Email Opened" or "Clicked Link" events never reported.

What are you seeing happen? : "Email Sent" is the only reported event. 

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below: My landing page is only contains the following - "<html><head></head><body></body></html>". This is essentially a null landing page as I'm only testing "Email Opened" and "Clicked Link" reporting. From my intuition, landing pages are for recording submitted data. 

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
* Step 1 - Setup Sending Profile with a Gmail account and smtp.gmail.com:587 host

 * Step 2 - Create following Email Template in HTML:
<html>
<head>
	<title></title>
</head>
<body>
<p><a href="{{.URL}}">LINK</a></p>

<p>{{.Tracker}}</p>
</body>
</html>

 * Step 3 - Create following Landing Page in HTML:
 <html><head></head><body></body></html>

* Step 4 - Start Campaign with email template from Step 2 and landing page from Step 3 and URL:http://1.bp.blogspot.com/YDFVHT4cS4s/VStzEMGBH7I/AAAAAAAAihk/kyCRFhT19OU/s1600/Kevin-Mitnick-Security-Awareness-Training.jpg?rid=MFVfks2

This is the raw source code of the email sent, I've omitted some raw source for my privacy: 
Message-ID: <59fb7e6e.07ed620a.34d15.0268@mx.google.com>
From: dbpoison18@gmail.com
X-Google-Original-From: test@example.com
Date: Thu, 02 Nov 2017 13:22:06 -0700
Subject: SUBJECT
To: "Jim Lee" <...@...com>
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable
X-MS-Exchange-Organization-Network-Message-Id: 90ebbe04-f7ec-4fb1-bfee-08d5222f6430
X-MS-Exchange-Organization-AVStamp-Enterprise: 1.0
X-MS-Exchange-Organization-AuthSource:
X-MS-Exchange-Organization-AuthAs: Anonymous
MIME-Version: 1.0

<html><head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Dutf-8"><t=
itle></title>
</head>
<body>
<p><a href=3D"http://1.bp.blogspot.com/-YDFVHT4cS4s/VStzEMGBH7I/AAAAAAAAihk=
/kyCRFhT19OU/s1600/Kevin-Mitnick-Security-Awareness-Training.jpg?rid=3DMFVf=
ks2">LINK</a></p>

<p><img alt=3D"" style=3D"display: none" src=3D"http://1.bp.blogspot.com/-Y=
DFVHT4cS4s/VStzEMGBH7I/AAAAAAAAihk/kyCRFhT19OU/s1600/Kevin-Mitnick-Security=
-Awareness-Training.jpg/track?rid=3DMFVfks2"></p>
</body>
</html>

**Comment by jordan-wright** [comment]
Thanks for following the new issue template! That makes things much easier for us 😄 

It looks like the problem is likely that you are pointing your URL to that blogspot URL. Gophish expects the URL to point directly to your Gophish instance, since this is how we can tell if a link is opened or not.

You also don't need to include an `rid` parameter. Gophish generates these automatically for you, since they are unique to each target.

So, a good test would be to use the IP address of your Gophish listener as the URL. So if my Gophish server is as x.x.x.x, my URL in the campaign would be `http://x.x.x.x`.

Give this a shot and let us know if it fixes the issue for you!

**Comment by jhl090** [comment]
Resolved! Thank you Mr. Wright.
