### ISSUE TITLE
A bit of help with headers

### ISSUE THREAD

**Issue by alme5** [gophish/gophish#823]
Hello,

I checked the documentation but I did not seem to find anything about email headers there.
I am using the latest version of gophish: gophish-v0.4

Sender's email address is:  hr@test1@.com
I would like to send a phishing email to company test.com so that instead of having hr@test1.com in the email header they will only see hr@test.com or just HR.

I know this can be done with email headers but unfortunately I have not been able to find any documentation anywhere about it.  

Thank you in advance

**Comment by jordan-wright** [comment]
You can change the From header by configuring the "From" field in the sending profile: https://gophish.gitbooks.io/user-guide/content/documentation/sending_profiles.html

Hope this helps!
