### ISSUE TITLE
Server doesn't start on macOS High Sierra

### ISSUE THREAD

**Issue by aluisscp** [gophish/gophish#824]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.4

Brief description of the issue: 
Doesn't start.

What are you expecting to see happen? :
To start the server

What are you seeing happen?
Terminal exit error

Please provide any terminal output that may be relevant below:

```
Last login: Fri Nov  3 21:11:52 on ttys000
MacBook-Pro:~ Admin$ /Users/Admin/Downloads/gophish-v0-2.4-darwin-64bit/gophish ; exit;
 2017/11/03 21:14:16 worker.go:37: Background Worker Started Successfully - Waiting for Campaigns
 2017/11/03 21:14:16 gophish.go:58: open ./VERSION: no such file or directory
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 -  Open the gophish executable

**Comment by aluisscp** [comment]
I placed both missing files in gophish folder, from the source.zip and now I get this

'''
 2017/11/03 21:19:05 worker.go:37: Background Worker Started Successfully - Waiting for Campaigns
goose: migrating db environment 'production', current version: 0, target: 20170827141312
OK    20160118194630_init.sql
OK    20160131153104_0.1.2_add_event_details.sql
OK    20160211211220_0.1.2_add_ignore_cert_errors.sql
OK    20160217211342_0.1.2_create_from_col_results.sql
OK    20160225173824_0.1.2_capture_credentials.sql
OK    20160227180335_0.1.2_store-smtp-settings.sql
OK    20160317214457_0.2_redirect_url.sql
OK    20160605210903_0.2_campaign_scheduling.sql
OK    20170104220731_0.2_result_statuses.sql
OK    20170219122503_0.2.1_email_headers.sql
OK    20170827141312_0.4_utc_dates.sql
 2017/11/03 21:19:05 gophish.go:104: Starting phishing server at http://0.0.0.0:80
 2017/11/03 21:19:05 gophish.go:105: listen tcp 0.0.0.0:80: bind: permission denied
MacBook-Pro-de:gophish-v0-2.4-darwin-64bit Admin$ 

'''

**Comment by jordan-wright** [comment]
A couple of things:

It looks like you're trying to run the binary, but you downloaded the source files. If you want to use the pre-built binaries, I recommend downloading one of the [releases](../releases).

Then, when you've extracted the files and execute them, you'll see output similar to your second block. This indicates Gophish ran, but this error:

```
 2017/11/03 21:19:05 gophish.go:105: listen tcp 0.0.0.0:80: bind: permission denied
```

shows that Gophish doesn't have permission to bind to port 80. One solution would be to run the Gophish command using sudo so it can bind to the correct port. Another solution would be to change the phish server port in the config.json to a higher port, but this would make it trickier to run campaigns.
