### ISSUE TITLE
Targets array is missing id property per target

### ISSUE THREAD

**Issue by AuditeMarlow** [gophish/gophish#825]
**What version of Gophish are you using?**
v0.4.0

**Brief description of the issue**
When I fetch a group and its targets using the API (`GET /api/groups/{id?}`), I'm expecting an id property for every target. Sadly enough, this property is not present. When I want to update a group, I'll have to generate ids for the targets myself.

**What are you expecting to see happen?**
I expect the targets from a group to ship with the id property.

**What are you seeing happen?**
A targets array without the id property.

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Create a group with users/targets
 * Step 2 - Send a GET request to `/api/groups/`

**Comment by jordan-wright** [comment]
Thanks for reaching out!

What are you wanting to use the ID for? When you update a group via the API, you just need to specify the member details (name, email, etc.). Here's an example curl command for updating a group:

```
curl 'https://localhost:3333/api/groups/6?api_key=71561c40b9d9a7772fc073d3dbef1a48de03e622487cb25a88d377cad309d41f'
    -X PUT -H 'content-type: application/json'
    --data-binary $'{
    "name":"Example Company","targets":
        [{"first_name":"Jane","last_name":"Doe","email":"janedoe@example.com","position":""},
        {"first_name":"John","last_name":"Doe","email":"johndoe@example.com","position":""}],
    "id":6}'
```

Gophish will automatically add/remove users as necessary to match what you submit. It's only assumed that every email address in the group is unique.

**Comment by AuditeMarlow** [comment]
Hey Jordan, I wanted to use the ID to update a group, but as you've just explained, this is already neatly handled by the Gophish backend. Thanks for clarifying this. Suppose I no longer have any issues for you. :)
