### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by Kujsobs** [gophish/gophish#826]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.4.0

Brief description of the issue: 
Just installed gophish at kali linux. When trying to access the site, I get "Error 404". 

What are you expecting to see happen? :
Gophish starting page/login at 127.0.0.1:3333
What are you seeing happen?
"404 page not found", no other pictures or anything. Just plain small text "error 404"

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
127.0.0.1 - - [04/Nov/2017:20:47:31 +0000] "GET / HTTP/1.1" 404 43 "" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
2017/11/04 20:47:35 http: TLS handshake error from 127.0.0.1:48838: tls: first record does not look like a TLS handshake
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Installing. 
 * Step 1,5 - ./gophish
 * Step 2 - 127.0.0.1
 * Step 3 - Error 404

**Comment by jordan-wright** [comment]
This is expected. You are navigating to the phishing server which, without seeing an `rid` parameter that's generated for each target in a campaign, will return a generic 404 page.

You will need to navigate to https://127.0.0.1:3333 to view the admin page.

You can find more information here: https://gophish.gitbooks.io/user-guide/content/getting_started.html

And here: https://gophish.gitbooks.io/user-guide/content/documentation/landing_pages.html
