### ISSUE TITLE
Setting up Phish Server to Local Host of my Machine 

### ISSUE THREAD

**Issue by jhl090** [gophish/gophish#827]
What version of Gophish are you using?: v0.4.0

Brief description of the issue: 
- I'm trying to set the "listen_url" in my config.json file to the local host of my machine (running on macOS). I've been given permission from colleagues so that I can test the tracking functionalities like "Email Opened", "Clicked Link" etc. when I target their email addresses.
- Essentially, I wanna test sending emails to the outside world while using the local host of my machine as the phishing server. 

What are you expecting to see happen?: n/a 

What are you seeing happen?:
- When I execute GoPhish, my terminal outputs the following: 
gophish.go:104: Starting phishing server at http://mycomputerhost.local:8080
gophish.go:87: Starting admin server at https://127.0.0.1:3333
gophish.go:105: listen tcp: lookup mycomputerhost.local: no such host

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below: n/a 

Please provide as many steps as you can to reproduce the problem: 
- On my firewall settings, I ensured all incoming connections to GoPhish are allowed.
- In my terminal, I ensured that there were no running processes on port 8080.
- In my config.json file, I set "listen_url" field to mycomputerhost.local:8080 and did not edit any other fields. 

For my computer, "Internet Sharing" is disabled. Is this or something else causing issues?

**Comment by jordan-wright** [comment]
Consider setting that value to the default 0.0.0.0:80 instead of the DNS hostname for your machine. This will allow Gophish to bind to all interfaces.

I’m afraid any firewall specific issues are beyond the scope of the support we can provide, since they are system specific.

**Comment by jhl090** [comment]
This default IP does not allow tracking of events e.g. "Email Opened" for emails sent to the outside world. For example, a campaign consists of two identical emails sent to my email and a that 
of my colleague; only the events for the email sent to myself are tracked whereas events for the email sent to my colleague are never updated. The status of this email remains at "Email Sent".

**Comment by jordan-wright** [comment]
This falls back on the networking you have setup. I'm assuming your device running Gophish is on an internal network, whereas your colleague is on either the internal network or an external network.

The core issue is that you need to make sure that:

* The colleague's device is able to reach your Gophish server just considering the networking setup. This means that routing, firewalls, etc. are all taken care of. We're not able to provide support for this part.
* Your Gophish phishing server configuration is set up to be reachable by external hosts. This is what setting the phish_server to `0.0.0.0` does. It binds the Gophish server to each interface on your host, allowing it to be externally reachable.

If you set up Gophish correctly, and you still don't see any campaign updates from your colleague, and them clicking on the links in the emails do not show your landing page (and you don't see any logs in the terminal), it's almost certainly the case that there are networking issues to be worked out outside of the Gophish installation.
