### ISSUE TITLE
Request (dynamic rid parameter)

### ISSUE THREAD

**Issue by apatedolos** [gophish/gophish#830]
As title suggests, would it be possible to specify the "rid" parameter on an adhoc basis?

It would not be hard for this to be monitored and blocked based on the default ?rid format.

Thanks

**Comment by jordan-wright** [comment]
Hi @apatedolos, thanks for reaching out!

Unfortunately, I don't see us implementing this. Having a dynamic `rid` parameter is pretty core to how Gophish works. And designing the UX to accommodate this would be really tricky.

I'll go ahead and close this out for now, but I'd be interested in hearing what you're trying to do with manual `rid` parameters so we can figure out if there's a workaround for you.

**Comment by apatedolos** [comment]
Ok, I realized that this was not going to be a quick fix. The issue here is with getting the campaigns past security devices monitoring network traffic. As the format is always http://server/?rid=RandomString it would be fairly simple to set up a regex rule to monitor for this format on outbound traffic and block it. 

This could then leave gophish campaigns dead in the water.

**Comment by st3r30byt3** [comment]
+1 for this. If you send multiple campaigns targeting the same organisation, they basically all look alike meaning that they will either be reported at some point or blocked.

**Comment by S0larflare** [comment]
This has been asked for in other issues (e.g. #911 ) and was implimented [a few months back ](https://github.com/gophish/gophish/commit/c9ff8714a0beda15b985a5d0061df3bcbc2f8f9d). This should be part of the latest release, so upgrade to v0.6 or build from source.
