### ISSUE TITLE
Server not starting on Mac OS Sierra

### ISSUE THREAD

**Issue by metzjason** [gophish/gophish#832]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
v0.4

Brief description of the issue: 
I receive an error of no such file or directory - using the gophish-v0.4-darwin-32bit binary install
 
What are you expecting to see happen? :

expecting the install to complete but receiving an error

What are you seeing happen?

Please provide any terminal output that may be relevant below:

Last login: Wed Nov  8 19:19:47 on ttys001
/Users/admin/Downloads/gophish-v0.4-darwin-32bit/gophish ; exit;
MacBook-Pro-2:~ admin$ /Users/admin/Downloads/gophish-v0.4-darwin-32bit/gophish ; exit;
 2017/11/08 19:20:44 worker.go:37: Background Worker Started Successfully - Waiting for Campaigns
 2017/11/08 19:20:44 gophish.go:58: open ./VERSION: no such file or directory
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Opened the the gophish installer

I saw that there was someone with a similar problem but they were using source files - I am seeing this with just the binary. I have go installed (newest version) is there something else I need to be doing? Thanks!

**Comment by jordan-wright** [comment]
You might try just changing into the Gophish directory and executing Gophish from there.

**Comment by jordan-wright** [comment]
Going ahead and closing this since there haven't been any updates in a while and the previous comment _should_ (hopefully) fix the issue. @metzjason if the previous comment doesn't help and you're still running into the issue, let me know and we can continue troubleshooting.
