### ISSUE TITLE
Failed logins are not logged correctly (I think)

### ISSUE THREAD

**Issue by ponchohoncho** [gophish/gophish#833]
What version of Gophish are you using?: 0.4

Preface: I'm not intimately familiar with go or fail2ban, so what I'm seeing here may be an issue, it might not. Please let me know.

Brief description of the issue: I'm using an nginx reverse proxy in front of gophish to handle multiple domains and ssl certificates. Since gophish doesn't save any logs on its own, this has the added bonus of giving me gophish's http logs through nginx. I wanted to use fail2ban to detect failed logins, but found that the way gophish returned you to the login page was different from other webapps that had fail2ban log definitions, causing weirdness in the logs.

here's an example of a failed wordpress login
```
12.34.33.22 - - [07/Jun/2014:11:15:29 +0000] "POST /wp/wp-login.php HTTP/1.0" 200 4523 "-" "-"
```

a failed gophish login looks like this in /var/log/nginx/access.log
```
11.22.33.44 - - [time] "POST /login HTTP/1.1" 302 0 "https://gophish/login" "Browser UA String"
11.22.33.44 - - [time] "GET /login HTTP/1.1" 200 1137 "https://gophish/login" "Browser UA String"
```

a successful gophish login looks like this
```
11.22.33.44 - - [time] "POST /login HTTP/1.1" 302 0 "https://gophish/login" "Browser UA String"
11.22.33.44 - - [time] "GET / HTTP/1.1" 200 1713 "https://gophish/login" "Browser UA String"
```

the only difference is that failure takes you back to /login instead of /

I created a fail2ban definition to capture these two lines:

```
[Init]
maxlines = 2

[Definition]
failregex = ^<HOST> .*\"POST /login HTTP/1.1\" 302.*\n.*\"GET /login HTTP/1.1\".*
ignoreregex =
```

This is probably the worst regex ever. I'm just hoping that it can help someone.

What are you expecting to see happen? : I was hoping that a login failure would be captured in one log line instead of two, like other apps I've seen.

What are you seeing happen?: Honestly, I have no idea. Some status code isn't right? Who knows. I'm hoping you do.

I hope this has made some amount of sense. Thanks for an amazing tool! I'm very excited to antagonize my users with it.

**Comment by jordan-wright** [comment]
I'll have to consider this a bit more, since it _seems_ that what we're doing is reasonable. For example, a failed login on Twitter (since I was just using it recently) gives a 302 to their error page where it re-requests credentials.

It's possible that I could look into sending back a 401 instead which may be more semantically correct. I'll have to do some digging and I'm afraid this will probably be a low priority fix in the grand scheme of things.

I appreciate you sending this over, though! I'll keep you updated.

**Comment by jordan-wright** [comment]
I've changed the status code for a failed login to 401. Hope this helps!
