### ISSUE TITLE
Can't get api.campaigns.summary(campaign_id=xx) to return summary results

### ISSUE THREAD

**Issue by bwhunan** [gophish/gophish#834]
Greetings all:

I'm using this phishing platform and I have to say up front, it's really a fantastic tool! I have one active campaign and I'm trying to use the API so I can login via an SSH connection and get quick stats. I've come across an area in my python client that I can't seem to resolve. 

The following image shows my python client, gophish_status.py.

![gophish_status](https://user-images.githubusercontent.com/13454355/32611640-2bb059a6-c534-11e7-9a8a-62afba19dafc.PNG)

The resulting error produced is as follows:
![gophish_status_results](https://user-images.githubusercontent.com/13454355/32611663-3c327854-c534-11e7-89a6-148127691c95.PNG)

Has anyone else encountered this issue or am I overlooking something (I probably am!). ;)

Thanks in advance for your help!

**Comment by jordan-wright** [comment]
Hmm... that may be a bug - I'll need to investigate further. Thanks for sending over this report!

**Comment by jordan-wright** [comment]
Trying it locally I can't seem to reproduce the issue. Are you sure you're using the latest version of the Gophish Python API? You might try a `pip install -u gophish` to see if that gets you an updated version?

**Comment by bwhunan** [comment]
Thanks for getting back to me. I upgraded to the latest version; I'm now at 0.1.3 and I still have the same issue: summary() got multiple values for keyword argument 'campaign_id'. 

I can continue to get the values from api.campaigns.get() and via a for loop, display campaign name, status, etc... but I can't seem to get summary() working in order to return campaign stats (total, sent, opened, clicked...)

**Comment by milo2012** [comment]
@bwhunan I experienced a similar issue but its ok now.  
Please make sure that you are running the latest version of gophish.  
The issue could be due to a mismatch between the python API client and the gophish server.

You can check the version number under Settings in the Admin panel.

Hope that helps.

**Comment by the1aughingman** [comment]
I had a similar issue today. It appears that using pip for the upgrade still pushes a version that is different than the one on github (it did for me at least). I posted my fix with my issue earlier today. #1133

**Comment by jordan-wright** [comment]
Hey everyone,

Just a heads up, a little while back I released version 0.1.5 of the Python API client to PyPI. I recommend updating the version of the client being used, which should resolve this issue.

Thanks again for reporting this!
