### ISSUE TITLE
Feature Request: URL cruft

### ISSUE THREAD

**Issue by ponchohoncho** [gophish/gophish#837]
A lot of login URLs have a lot of cruft in them more than just the domain. In order to increase believably, it would be pretty great to be able to put extra stuff into the URL to make it appear like a legitimate login page.

Here are some examples

GMail
`https://accounts.google.com/signin/v2/identifier?service=mail&passive=true&rm=false&continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&ss=1&scc=1&ltmpl=default&ltmplcache=2&emr=1&osid=1&flowName=GlifWebSignIn&flowEntry=ServiceLogin`

LinkedIn
`https://www.linkedin.com/uas/login`

Facebook
`https://www.facebook.com/login/`

Office 365
`https://login.microsoftonline.com/common/oauth2/authorize?client_id=00000006-0000-0ff1-ce00-000000000000&response_mode=form_post&response_type=code+id_token&scope=openid+profile&state=OpenIdConnect.AuthenticationProperties%3dYeERqn1rRTY1V6CbZsSZ0VPranNu_s-wxiqPWPOyXXOWZRVspcitgKOJdG-WdkhG7gMWkh5u6fs_LF1aU7bpgAWnZ19quQSZdlgAU2zwjF4giyg-wwg04cyQmguS-ILY-LgZ4P_SOIDkuRmZaLcRKgcC4qfB2Bkr94VXu9ieMDuvOTgQIbDvGof6hlS6h1zW&nonce=636458661018272391.OGQzZDBmOGMtMzVmOS00NDFkLTliZTUtNWQ0MmVmMDgyNDliNGYwZGUxN2ItYzE2Zi00NmMzLTliMGYtNjEwZmNiYWNiNGE4&redirect_uri=https%3a%2f%2fportal.office.com%2flanding&ui_locales=en-US&mkt=en-US&client-request-id=b4f77587-63f8-4b7f-8877-c2d51fefac65&msafed=0`

Right now I simulate this by adding extra URL parameters in the email template so that links are extra crufty, but it's not elegant and it pollutes the captured data with all that junk.

Here's what I used in a fake LinkedIn email

`{{.URL}}&e=3D1aewf43e9gdiApi=email_security_password_reset`

The problem there is that I get that e variable in the resulting reports

Would it be possible to define the URL of the gophish listener (when setting up a campaign) with extra cruft and a variable that the backend would be able to pick out and ignore the rest? Something like

`http://phishdomain.com/uas/{{.RID}}/login/`

which would become (removing the ?= for a prettier/more convincing URL)

`http://phishdomain.com/uas/8eepTfr/login/`

**Comment by ponchohoncho** [comment]
I just noticed that the gophish server happily ignores extra cruft before the RID, so this works fine:

`https://fakelinkedin.com/uas/login/?rid=NSp1L11'

that solves half the problem, as I can make URLs decently crufty with that. It would be nice to get rid of the ?rid= bit for URLs that don't normally have parameters in them, but that's a smaller issue.

**Comment by jordan-wright** [comment]
Yep! You can have extra paths and things should work just fine. I’m afraid we won’t be removing the rid parameter, since that’s how Gophish uniquely identifies which campaign and recipient this request is from.

Thanks for reaching out!
