### ISSUE TITLE
Static VPN: Gophish error of: dial tcp: i/o timeout

### ISSUE THREAD

**Issue by factgasm** [gophish/gophish#838]
When trying to launch campaigns from behind a static vpn, Gophish generates an error of: **dial tcp: i/o timeout.**

staticvpnip.com's installation instructions are here:
https://staticvpnip.com/tutorials/8-linux-manual-vpn-configuration-openvpn

Once those installation instructions have been followed, there is no problem using webmail or Thunderbird ; they continue to work perfectly. So, it appears there is a conflict between Gophish and the VPN.

Please help.

Using v0.4 on Kali 2017.2.

**Comment by jordan-wright** [comment]
Hi there!

Thanks for reaching out. Im afraid there’s not much info here. Im going to close this out - can you please open a new issue and follow the issue template format? That format is provided to show what information we need to be able to help troubleshoot.

Thanks!
