### ISSUE TITLE
Models.go:98: no valid version found no valid version found 

### ISSUE THREAD

**Issue by MrNoobie** [gophish/gophish#839]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
v.0.4

Brief description of the issue: 
When I execute the binary, there seems to be a problem finding/creating the database.

What are you expecting to see happen? :
Something more similar to the example in the installation guide:

2016/01/10 23:13:42 worker.go:34: Background Worker Started Successfully - Waiting for Campaigns
 2016/01/10 23:13:42 models.go:64: Database not found... creating db at gophish.db
 2016/01/10 23:13:42 gophish.go:49: Admin server started at http://127.0.0.1:3333
 2016/01/10 23:13:42 gophish.go:51: Phishing server started at http://0.0.0.0:80

What are you seeing happen?
The following text:

C:\gophish-v0.4-windows-64bit>gophish
 2017/11/13 10:28:01 worker.go:37: Background Worker Started Successfully - Waiting for Campaigns
 2017/11/13 10:28:01 models.go:98: no valid version found no valid version found
 2017/11/13 10:28:01 gophish.go:104: Starting phishing server at http://0.0.0.0:80
 2017/11/13 10:28:01 gophish.go:91: Starting admin server at http://127.0.0.1:3333

...and when I try to log onto localIP:3333, this is what happens in the command line Interface:

127.0.0.1 - - [13/Nov/2017:10:28:04 +0100] "GET / HTTP/1.1" 302 29 "" "Mozilla/5
.0 (Windows NT 6.3; WOW64; Trident/7.0; LCJB; rv:11.0) like Gecko"
 2017/11/13 10:28:04 route.go:263: open templates/login.html: The system cannot
find the path specified.
2017/11/13 10:28:04 http: panic serving 127.0.0.1:51732: open templates/login.ht
ml: The system cannot find the path specified.
goroutine 34 [running]:
net/http.(*conn).serve.func1(0xc0422bd900)
        /usr/local/go/src/net/http/server.go:1721 +0xd7
panic(0x9bad60, 0xc042253800)
        /usr/local/go/src/runtime/panic.go:489 +0x2dd
html/template.Must(0xc042253770, 0xddc340, 0xc042253800, 0x1)
        /usr/local/go/src/html/template/template.go:360 +0x5b
github.com/gophish/gophish/controllers.Login(0xde1480, 0xc0422437a0, 0xc0422f050
0)
        /go/src/github.com/gophish/gophish/controllers/route.go:265 +0x7a9
net/http.HandlerFunc.ServeHTTP(0xa830d8, 0xde1480, 0xc0422437a0, 0xc0422f0500)
        /usr/local/go/src/net/http/server.go:1942 +0x4b
github.com/gorilla/mux.(*Router).ServeHTTP(0xc04226c000, 0xde1480, 0xc0422437a0,
 0xc0422f0500)
        /go/src/github.com/gorilla/mux/mux.go:133 +0x108
github.com/gorilla/csrf.(*csrf).ServeHTTP(0xc0422bd860, 0xde1480, 0xc0422437a0,
0xc0422f0300)
        /go/src/github.com/gorilla/csrf/csrf.go:267 +0x334
net/http.(Handler).ServeHTTP-fm(0xde1480, 0xc0422437a0, 0xc0422f0000)
        /usr/local/go/src/net/http/h2_bundle.go:4331 +0x54
net/http.HandlerFunc.ServeHTTP(0xc0422d2a20, 0xde1480, 0xc0422437a0, 0xc0422f000
0)
        /usr/local/go/src/net/http/server.go:1942 +0x4b
github.com/gophish/gophish/middleware.CSRFExceptions.func1(0xde1480, 0xc0422437a
0, 0xc0422f0000)
        /go/src/github.com/gophish/gophish/middleware/middleware.go:27 +0xcb
net/http.HandlerFunc.ServeHTTP(0xc0422d2a40, 0xde1480, 0xc0422437a0, 0xc0422f000
0)
        /usr/local/go/src/net/http/server.go:1942 +0x4b
github.com/gophish/gophish/middleware.GetContext.func1(0xde1480, 0xc0422437a0, 0
xc0422f0000)
        /go/src/github.com/gophish/gophish/middleware/middleware.go:57 +0x29c
net/http.HandlerFunc.ServeHTTP(0xc0422d2a60, 0xde1480, 0xc0422437a0, 0xc0422cd40
0)
        /usr/local/go/src/net/http/server.go:1942 +0x4b
github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0xfc0078, 0xc042252f9
0, 0xc0422cd400)
        /go/src/github.com/NYTimes/gziphandler/gzip.go:269 +0x180
net/http.HandlerFunc.ServeHTTP(0xc0422bf020, 0xfc0078, 0xc042252f90, 0xc0422cd40
0)
        /usr/local/go/src/net/http/server.go:1942 +0x4b
github.com/gorilla/handlers.combinedLoggingHandler.ServeHTTP(0xddc300, 0xc042004
018, 0xddd400, 0xc0422bf020, 0xde18c0, 0xc0420d2a80, 0xc0422cd400)
        /go/src/github.com/gorilla/handlers/handlers.go:77 +0x128
github.com/gorilla/handlers.(*combinedLoggingHandler).ServeHTTP(0xc0422d2a80, 0x
de18c0, 0xc0420d2a80, 0xc0422cd400)
        <autogenerated>:9 +0x8d
net/http.serverHandler.ServeHTTP(0xc0422e60b0, 0xde18c0, 0xc0420d2a80, 0xc0422cd
400)
        /usr/local/go/src/net/http/server.go:2568 +0x99
net/http.(*conn).serve(0xc0422bd900, 0xde2100, 0xc0422d4540)
        /usr/local/go/src/net/http/server.go:1825 +0x619
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2668 +0x2d5
 2017/11/13 10:28:04 route.go:263: open templates/login.html: The system cannot
find the path specified.
2017/11/13 10:28:04 http: panic serving 127.0.0.1:51733: open templates/login.ht
ml: The system cannot find the path specified.
goroutine 20 [running]:
net/http.(*conn).serve.func1(0xc0421d6be0)
        /usr/local/go/src/net/http/server.go:1721 +0xd7
panic(0x9bad60, 0xc042209b30)
        /usr/local/go/src/runtime/panic.go:489 +0x2dd
html/template.Must(0xc042209aa0, 0xddc340, 0xc042209b30, 0x1)
        /usr/local/go/src/html/template/template.go:360 +0x5b
github.com/gophish/gophish/controllers.Login(0xde1480, 0xc0421ca420, 0xc0421c8c0
0)
        /go/src/github.com/gophish/gophish/controllers/route.go:265 +0x7a9
net/http.HandlerFunc.ServeHTTP(0xa830d8, 0xde1480, 0xc0421ca420, 0xc0421c8c00)
        /usr/local/go/src/net/http/server.go:1942 +0x4b
github.com/gorilla/mux.(*Router).ServeHTTP(0xc04226c000, 0xde1480, 0xc0421ca420,
 0xc0421c8c00)
        /go/src/github.com/gorilla/mux/mux.go:133 +0x108
github.com/gorilla/csrf.(*csrf).ServeHTTP(0xc0422bd860, 0xde1480, 0xc0421ca420,
0xc0421c8a00)
        /go/src/github.com/gorilla/csrf/csrf.go:267 +0x334
net/http.(Handler).ServeHTTP-fm(0xde1480, 0xc0421ca420, 0xc0421c8700)
        /usr/local/go/src/net/http/h2_bundle.go:4331 +0x54
net/http.HandlerFunc.ServeHTTP(0xc0422d2a20, 0xde1480, 0xc0421ca420, 0xc0421c870
0)
        /usr/local/go/src/net/http/server.go:1942 +0x4b
github.com/gophish/gophish/middleware.CSRFExceptions.func1(0xde1480, 0xc0421ca42
0, 0xc0421c8700)
        /go/src/github.com/gophish/gophish/middleware/middleware.go:27 +0xcb
net/http.HandlerFunc.ServeHTTP(0xc0422d2a40, 0xde1480, 0xc0421ca420, 0xc0421c870
0)
        /usr/local/go/src/net/http/server.go:1942 +0x4b
github.com/gophish/gophish/middleware.GetContext.func1(0xde1480, 0xc0421ca420, 0
xc0421c8700)
        /go/src/github.com/gophish/gophish/middleware/middleware.go:57 +0x29c
net/http.HandlerFunc.ServeHTTP(0xc0422d2a60, 0xde1480, 0xc0421ca420, 0xc0421c860
0)
        /usr/local/go/src/net/http/server.go:1942 +0x4b
github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0xfc0078, 0xc04220959
0, 0xc0421c8600)
        /go/src/github.com/NYTimes/gziphandler/gzip.go:269 +0x180
net/http.HandlerFunc.ServeHTTP(0xc0422bf020, 0xfc0078, 0xc042209590, 0xc0421c860
0)
        /usr/local/go/src/net/http/server.go:1942 +0x4b
github.com/gorilla/handlers.combinedLoggingHandler.ServeHTTP(0xddc300, 0xc042004
018, 0xddd400, 0xc0422bf020, 0xde18c0, 0xc04231a0e0, 0xc0421c8600)
        /go/src/github.com/gorilla/handlers/handlers.go:77 +0x128
github.com/gorilla/handlers.(*combinedLoggingHandler).ServeHTTP(0xc0422d2a80, 0x
de18c0, 0xc04231a0e0, 0xc0421c8600)
        <autogenerated>:9 +0x8d
net/http.serverHandler.ServeHTTP(0xc0422e60b0, 0xde18c0, 0xc04231a0e0, 0xc0421c8
600)
        /usr/local/go/src/net/http/server.go:2568 +0x99
net/http.(*conn).serve(0xc0421d6be0, 0xde2100, 0xc0421c45c0)
        /usr/local/go/src/net/http/server.go:1825 +0x619
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2668 +0x2d5
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x7ac4ee]

goroutine 19 [running]:
github.com/jinzhu/gorm.(*DB).clone(0x0, 0xc04202b6c8)
        /go/src/github.com/jinzhu/gorm/main.go:715 +0x4e
github.com/jinzhu/gorm.(*DB).Where(0x0, 0x9951e0, 0xc042245e00, 0xc042245df0, 0x
1, 0x1, 0xc04224f400)
        /go/src/github.com/jinzhu/gorm/main.go:182 +0x32
github.com/gophish/gophish/models.GetQueuedCampaigns(0xed19b5cdd, 0xc033ac6ee8,
0x0, 0x1, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/gophish/gophish/models/campaign.go:343 +0x190
github.com/gophish/gophish/worker.(*Worker).Start(0xe577d0)
        /go/src/github.com/gophish/gophish/worker/worker.go:39 +0x1d6
created by github.com/gophish/gophish/controllers.init.1
        /go/src/github.com/gophish/gophish/controllers/api.go:31 +0x6e

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by MrNoobie** [comment]
I don't think we shall focus on the last line until further. I turned off the TLS-Connections in the Config.json files just to eliminate error Sources.

**Comment by jordan-wright** [comment]
Are you running Gophish from within its directory? You need to make sure you’re in the Gophish folder before running it, since it looks in the current directory for templates and database versioning files.

**Comment by MrNoobie** [comment]
Works perfectly on another computer, though. May be I will just use that one, until further :-). Really curious why it doesn't work here on this one.

**Comment by S0larflare** [comment]
Having a quick look, that seems to be the part of the setup which checks if the database matches the current version or whether it needs any migrations in order to update the schema. As you don't have a DB, it should instead create one. As that isn't happening, could it be that the directory is read only/it doesn't have permission to create or modify anything?

**Comment by jordan-wright** [comment]
In this case, looking at your folder structure @MrNoobie, it appears you're missing some folders in that directory. Namely, I at least don't see the `templates/` or `db/` folders, which should be present in any Gophish installation. Seeing the `old` folder makes me think this is probably an artifact from an upgrade process where things weren't completely extracted or copied over or something.

Adding those folders from a Gophish installation should help resolve the issue, but it sounds like you got it working on a different computer which is good to hear! I'll go ahead and close this out for now.

Thanks for getting in touch!
