### ISSUE TITLE
The ability to preview cloned sites and email templates

### ISSUE THREAD

**Issue by rfdevere** [gophish/gophish#84]
I think this will add to the great UI in the future, is there a way to render in a pop up 'on mouse over' box a preview of the site or an email template? It would give clarity to which site is being chosen and also a basic check the html is being displayed correctly.

**Comment by jordan-wright** [comment]
Hey @rfdevere,

Thanks for the great idea! I'll be looking into how we can make this happen on the backend, so I'll put this for 0.2 for now. You probably already noticed this, but a preview is available at least while editing the template or landing page by clicking the "Source" button in the editor:

![image](https://cloud.githubusercontent.com/assets/1317288/12466988/c14a21ca-bf9d-11e5-9cbf-697ba0dcbe3e.png)

This results in this window:

![image](https://cloud.githubusercontent.com/assets/1317288/12467017/d8b7bcc8-bf9d-11e5-9924-3aee82b712a2.png)

From here, you can actually click into the content to edit it WYSIWYG style. This will ensure that the HTML looks the way you want. If you want to view it in full-screen, you can do that to via the full screen button (to the left of the "Source" button).

**Comment by rfdevere** [comment]
Missed the source button completely, this issue should be closed down.

**Comment by jordan-wright** [comment]
The full on editing of CKEditor is what takes the template/landing pages editing to the *next level*. Being able to just click in the content and start editing is insanely cool.
