### ISSUE TITLE
 Error 1366: Incorrect string value: '\xC4\x8Ce\xC5\xA1t...' for column 'html' at row 1

### ISSUE THREAD

**Issue by polmuir** [gophish/gophish#840]
Hi, I'm having a problem import a site into creating a landing page.

I'm not a developer so apologies if this is known issues/obvious fix 

<!DOCTYPE html><html lang="en" class="os-mac"><head><base href="http://xxxxxx.co.uk"/>
<meta charset="UTF-8"/>
 <title>LinkedIn: Log In or Sign Up
 </title>
 <meta name="referrer" content="origin"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
 <meta name="pageImpressionID" content="64047a2e-983e-495b-a49a-c3643554d98e"/>
 <meta name="appName" content="chrome"/>
 <meta name="pageKey" content="uno-reg-guest-home"/>
 <meta name="treeID" content="Si9bYV7w9hRATww6KCsAAA=="/>
 <meta name="globalTrackingUrl" content="//www.linkedin.com/mob/tracking"/>
 <meta name="globalTrackingAppName" content="chrome"/>
 <meta name="globalTrackingAppId" content="webTracking"/>

<link rel="icon" href="https://static.licdn.com/scds/common/u/images/logos/favicons/v1/favicon.ico"/>
<link rel="apple-touch-icon-precomposed" href="https://static.licdn.com/scds/common/u/img/icon/apple-touch-icon.png"/>
<meta name="msapplication-TileImage" content="https://static.licdn.com/scds/common/u/images/logos/linkedin/logo-in-win8-tile-144_v1.png"/>
<meta name="msapplication-TileColor" content="#0077B5"/>
<meta name="application-name" content="LinkedIn"/>
<meta content="https://static.licdn.com/scds/concat/common/js?v=0.1.394" name="RemoteNavJSContentBaseURL"/>
<script type="text/javascript" src="https://static.licdn.com/scds/concat/common/js?h=7ndrn0f9fw0hum7uoqcjcnzne-95d8d303rtd0n9wj4dcjbnh2c-7vr4nuab43rzvy2pgq7yvvxjk-9qa4rfxekcw3lt2c06h7p0kmf"></script>
<link rel="stylesheet" type="text/css" href="https://static.licdn.com/scds/concat/common/css?h=as8kt5bqspxc01tl9cizqa37j"/>
<script></script>
Please provide any terminal output that may be relevant below:

2017/11/14 12:36:59 page.go:116: Error 1366: Incorrect string value: '\xC4\x8Ce\xC5\xA1t...' for column 'html' at row 1
185.46.209.66 - - [14/Nov/2017:12:36:59 +0000] "POST /api/pages/?api_key=99a74e7ee84085dcc00c93b5f345bfb78ed48dc2532d02529adfbbe48b3e2286 HTTP/2.0" 500 145 "https://gxxxxxxx.com:3333/landing_pages" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/604.3.5 (KHTML, like Gecko) Version/11.0.1 Safari/604.3.5"
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Create a new landing page
 * Step 2 - Import site

**Comment by jordan-wright** [comment]
It looks like the value you're trying to add to the database has some invalid characters. I'm afraid the only recommendation we can provide is to try and track down where '\xC4\x8Ce\xC5\xA1t...' appears in your HTML, remove those characters, and try to re-save the content.

If there's any other information you can give, such as what URL you're specifically trying to import, we can see if there's anything we can do on Gophish's end to make this more resilient, but for now I can't think of a workaround other than removing the affected characters.

Hope this helps!

**Comment by KINGSABRI** [comment]
Hey! 
I had the same issue when adding a new template and new landing page; I fixed the issue by login to mysql 

```
mysql -u root -pMYSQLPASS
```

Then alter the table that has column issue
```
USE gophish;
ALTER TABLE gophish.pages CONVERT TO CHARACTER SET utf8;
ALTER TABLE gophish.templates CONVERT TO CHARACTER SET utf8;
EXIT
```

HTH
