### ISSUE TITLE
Can't add extra parameters to the campaign URL

### ISSUE THREAD

**Issue by S0larflare** [gophish/gophish#844]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  Tested on 0.2 and 0.4

Brief description of the issue: If I add an extra parameter, for exampe {{.Email}} to the campaign URL, this isn't parsed before the URL is created, so rather than getting a link like http://www.example.com/example@example.com?rid=og8R7 I end up with http://www.example.com/{{.email}}?rid=og8R7

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 - 
 

Could we change things so that {{.Position}}, {{.Email}} {{.FirstName}} etc are parsed before the URL is generated (natrually leave {{.URL}} so we don't get any weird behaviour).

**Comment by jordan-wright** [comment]
Ah, yeah. Good call. I could see the expectation that params should be allowed in the URL.

I’ll get that fixed. Thanks for this issue, and all the other help you’re constantly providing this community!
