### ISSUE TITLE
Postgres

### ISSUE THREAD

**Issue by Paddyk3ll3h3r** [gophish/gophish#846]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
v0.4.0

Brief description of the issue: 
Just wondering does gophish support postgreSQL? Thanks
What are you expecting to see happen? :

What are you seeing happen?
n/a
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:
n/a
```html
Insert code here
```

Please provide any terminal output that may be relevant below:
n/a
Insert output here
n/a

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hey there, thanks for reaching out!

No, Gophish only supports MySQL and SQLite. I don’t have any current plans to support it since managing the migrations for two DB syntaxes already takes enough time :)

**Comment by lafriks** [comment]
@jordan-wright would you be willing to accept PR to support postgres?

**Comment by jordan-wright** [comment]
No, I’m only interested in supporting SQLite and MySQL for now.

Thanks for asking though!

**Comment by steffen-karlsson** [comment]
We have added full support for Postgres in GoPhish in this fork: https://github.com/corticph/gophish-postgres
