### ISSUE TITLE
Feedback from users opening emails

### ISSUE THREAD

**Issue by jmcgyver** [gophish/gophish#862]
What version of Gophish are you using?: 
**v0.4**

Brief description of the issue:
 **I've got the emails to send out to the test user account but when I interact/click the link there is no feedback going to the dashboard.**

What are you expecting to see happen? :
**Some form of feedback from the emails being sent**

What are you seeing happen? 
**It follows through to the link I've specified but there is nothing coming back to Gophish.**
![gophish no feedback](https://user-images.githubusercontent.com/34070225/33381317-afa6ec22-d4eb-11e7-987b-d4172054de1a.PNG)

**Comment by jordan-wright** [comment]
So this is a full campaign, right? Not just sending a test email?

If so, what do you see when you click the link? Do you see the landing page you expect to see?

**Comment by jmcgyver** [comment]
Correct it is a full campaign, when I click on the link it goes to the directed website that I have set up on the landing page.
Though the feedback never occurs on the dashboard after I click the link. Any ideas?

**Comment by jordan-wright** [comment]
When you say "it goes to the directed website that I have set up on the landing page.", what is the URL you're clicking on in the email? What is the URL you end up on in your browser after clicking the link?

The only reason I'm trying to get as specific as possible with this info is that if you're hitting the right Gophish URL, then I would expect the dashboard to get updated.

**Comment by jmcgyver** [comment]
The landing page i have set up for the test is an amazon login screen and when I click the link in the email it takes me to the amazon login screen. what should I set up for the listening URL in the campaign i'm thinking it has to do with the listening URL not being configured properly.

**Comment by jordan-wright** [comment]
You need to set the listen URL to point to the IP:port for the Gophish phishing server. It needs to be accessible to everyone who receives the email.

**Comment by jordan-wright** [comment]
Going ahead and closing this, since it seems we've found the underlying issue.

Hope this helps @jmcgyver!
