### ISSUE TITLE
Windows Installation problem

### ISSUE THREAD

**Issue by markcol2312** [gophish/gophish#864]
hy. I have a problem. I have download the binary for windows. When i start the file .exe the message is this:
goose: no migrations to run. current version: 20170827141312
 2017/11/30 14:57:57 worker.go:37: Background Worker Started Successfully - Waiting for Campaigns
 2017/11/30 14:57:57 gophish.go:104: Starting phishing server at http://0.0.0.0:80
 2017/11/30 14:57:57 gophish.go:87: Starting admin server at https://127.0.0.1:3333
 2017/11/30 14:58:58 campaign.go:348: Found 0 Campaigns to run
maybe i didn't undestand how this software work but i can't install this.
Can someone give me some good instruction to install correctly. I feel so stupid at the moment.
Thanks you

**Comment by jordan-wright** [comment]
Did you open your browser to https://127.0.0.1:3333? If so, what did you see?

**Comment by markcol2312** [comment]
ok perfect i just see the login. Which are the use and password? In which session i have to register?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

> -------- Original Message --------
> Subject: Re: [gophish/gophish] Windows Installation problem (#864)
> Local Time: 30 novembre 2017 3:23 PM
> UTC Time: 30 novembre 2017 14:23
> From: notifications@github.com
> To: gophish/gophish <gophish@noreply.github.com>
> markcol2312 <markcol@protonmail.com>, Author <author@noreply.github.com>
>
> Did you open your browser to https://127.0.0.1:3333? If so, what did you see?
>

**Comment by jordan-wright** [comment]
Please refer to our documentation that has all this information and more about how to use Gophish https://gophish.gitbooks.io/user-guide/content/getting_started.html
