### ISSUE TITLE
Tag attributes being scrubbed from form elements

### ISSUE THREAD

**Issue by leveled** [gophish/gophish#868]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.4

Brief description of the issue: Certain tag attributes on form elements are being scrubbed when hosted by gophish, which is preventing user submitted data from being captured

What are you expecting to see happen? Parameters such as username and password being passed in a post request to the server. 

What are you seeing happen? Parameters are not being passed 

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

Using `wdiff` on the html from the source login page and the one hosted by gophish, I noticed that several 'name' attributes were being scrubbed from elements like below 

```html
<input class="sg-form-control" id="signin_email" value="" [-name="__email"-] {+data-reactid=".0.2.1:0.1.1.0.1"+} label="Email Address" [-data-reactid=".0.2.1:0.1.1.0.1"-] type="email">

```

In my case these name attributes are necessary for user submitted data to be passed in a POST request.

**Comment by jordan-wright** [comment]
Did you save the HTML with the "Capture Submitted Data" option unchecked? If so, this will scrub the `name` attribute from all inputs to prevent data from being captured. Unfortunately, if you then re-save the page Gophish doesn't know what the original `name` attributes were.

Hope this helps! Let me know if this doesn't solve the issue.

**Comment by leveled** [comment]
That appeared to be the issue, thanks for the help. It was a silly mistake.
