### ISSUE TITLE
Problem to check email open in Dashboard and to check data submitted

### ISSUE THREAD

**Issue by markcol2312** [gophish/gophish#869]
Hy to everyone.
I use the last versione of Gophish from few days.
My problem is this: I created a new campaign to hack Facebook login. I think I have compiled everything well I took the template of the fb page from an old email. The email is sent but in the dashboard it does not appear when it is opened. Furthermore, if I enter my data for testing on the pishing page, they will not be recorded or reported as entered in the dashboard.
Here my fb pishing page code. Someone con help me? I don't undestand where i wrong.
Thank you
[new 1.txt](https://github.com/gophish/gophish/files/1528501/new.1.txt)

**Comment by markcol2312** [comment]
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional //EN">
<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<title>Facebook</title>
	<style type="text/css">@media all and (max-width: 480px){*[class].ib_t{min-width:100% !important}*[class].ib_row{display:block !important}*[class].ib_ext{display:block !important;padding:10px 0 5px 0;vertical-align:top !important;width:100% !important}*[class].ib_img,*[class].ib_mid{vertical-align:top !important}*[class].mb_blk{display:block !important;padding-bottom:10px;width:100% !important}*[class].mb_hide{display:none !important}*[class].mb_inl{display:inline !important}}
	</style>
</head>
<body bgcolor="#ffffff" dir="ltr" style="margin:0;padding:0;">
<table border="0" cellpadding="0" cellspacing="0" id="email_table" style="border-collapse:collapse;" width="100%;">
	<tbody>
		<tr>
			<td id="email_content" style="font-family:Helvetica Neue,Helvetica,Lucida Grande,tahoma,verdana,arial,sans-serif;background:#ffffff;">
			<table cellpadding="0" cellspacing="0" style="border-collapse:collapse;" width="100%">
				<tbody>
					<tr style="">
						<td colspan="3" height="20" style="line-height:20px;">&nbsp;</td>
					</tr>
					<tr>
						<td colspan="3" height="1" style="line-height:1px;"><span style="color:#FFFFFF;display:none !important;font-size:1px;">&nbsp; Salve &nbsp; Sembra che qualcuno abbia tentato di accedere al tuo account il giorno 3 dicembre alle ore 23:17 usando Chrome per Windows 10 . Il tuo account &egrave; sicuro; vogliamo solo assicurarci che tu non abbia provato a effettuare l&#39;accesso da una nuova postazione. &nbsp; Se pensi che sia stato qualcun altro, accedi a Facebook cos&igrave; potremo indicarti dei passaggi per proteggere il tuo account. &nbsp; Grazie, Il team di Facebook &nbsp;</span></td>
					</tr>
					<tr>
						<td style="display:block;width:15px;" width="15">&nbsp;&nbsp;&nbsp;</td>
						<td style="">
						<table cellpadding="0" cellspacing="0" style="border-collapse:collapse;" width="100%">
							<tbody>
								<tr style="">
									<td colspan="3" height="16" style="line-height:16px;">&nbsp;</td>
								</tr>
								<tr>
									<td align="left" style="height:32;line-height:0px;" valign="middle" width="32"><img height="32" src="https://static.xx.fbcdn.net/rsrc.php/v2/yk/r/_2faPUZhPI6.png" style="border:0;" width="32" /></td>
									<td style="display:block;width:15px;" width="15">&nbsp;&nbsp;&nbsp;</td>
									<td style="" width="100%"><span style="font-family:Helvetica Neue,Helvetica,Lucida Grande,tahoma,verdana,arial,sans-serif;font-size:19px;line-height:32px;color:#3b5998;">Hai effettuato l&#39;accesso a Facebook da una nuova postazione?</span></td>
								</tr>
								<tr style="border-bottom:solid 1px #e5e5e5;">
									<td colspan="3" height="16" style="line-height:16px;">&nbsp;</td>
								</tr>
							</tbody>
						</table>
						</td>
						<td style="display:block;width:15px;" width="15">&nbsp;&nbsp;&nbsp;</td>
					</tr>
					<tr>
						<td style="display:block;width:15px;" width="15">&nbsp;&nbsp;&nbsp;</td>
						<td style="">
						<table cellpadding="0" cellspacing="0" style="border-collapse:collapse;" width="100%">
							<tbody>
								<tr style="">
									<td height="28" style="line-height:28px;">&nbsp;</td>
								</tr>
								<tr>
									<td style=""><span style="font-family:Helvetica Neue,Helvetica,Lucida Grande,tahoma,verdana,arial,sans-serif;font-size:16px;line-height:21px;color:#141823;">Salve </span></td>
								</tr>
								<tr style="">
									<td height="14" style="line-height:14px;">&nbsp;</td>
								</tr>
								<tr>
									<td style=""><span style="font-family:Helvetica Neue,Helvetica,Lucida Grande,tahoma,verdana,arial,sans-serif;font-size:16px;line-height:21px;color:#141823;">Sembra che qualcuno abbia tentato di accedere al tuo account il giorno <strong>3 dicembre alle ore 23:17</strong> usando <strong>Chrome per Windows 10</strong>. Il tuo account &egrave; sicuro; vogliamo solo assicurarci che tu non abbia provato a effettuare l&#39;accesso da una nuova postazione.</span></td>
								</tr>
								<tr style="">
									<td height="14" style="line-height:14px;">&nbsp;</td>
								</tr>
								<tr>
									<td style=""><span style="font-family:Helvetica Neue,Helvetica,Lucida Grande,tahoma,verdana,arial,sans-serif;font-size:16px;line-height:21px;color:#141823;"><strong>Se pensi che sia stato qualcun altro,</strong> <a href="{{.URL}}" style="color:#3b5998;text-decoration:none;">accedi a Facebook</a> cos&igrave; potremo indicarti dei passaggi per proteggere il tuo account.</span></td>
								</tr>
								<tr style="">
									<td height="14" style="line-height:14px;">&nbsp;</td>
								</tr>
								<tr>
									<td style=""><span style="font-family:Helvetica Neue,Helvetica,Lucida Grande,tahoma,verdana,arial,sans-serif;font-size:16px;line-height:21px;color:#141823;">Grazie,<br />
									Il team di Facebook</span></td>
								</tr>
								<tr style="">
									<td height="14" style="line-height:14px;">&nbsp;</td>
								</tr>
							</tbody>
						</table>
						</td>
						<td style="display:block;width:15px;" width="15">&nbsp;&nbsp;&nbsp;</td>
					</tr>
					<tr>
						<td style="display:block;width:15px;" width="15">&nbsp;&nbsp;&nbsp;</td>
						<td style="">
						<table cellpadding="0" cellspacing="0" style="border-collapse:collapse;" width="100%">
							<tbody>
								<tr style="border-top:solid 1px #e5e5e5;">
									<td height="16" style="line-height:16px;">&nbsp;</td>
								</tr>
								<tr>
									<td style="font-family:Helvetica Neue,Helvetica,Lucida Grande,tahoma,verdana,arial,sans-serif;font-size:11px;color:#aaaaaa;line-height:16px;">Questo messaggio &egrave; stato inviato a <a href="{{.URL}}" style="color:#3b5998;text-decoration:none;">check@hotmail.it</a>, come da te richiesto.<br />
									Facebook, Inc., Attention: Community Support, Menlo Park, CA 94025</td>
								</tr>
							</tbody>
						</table>
						</td>
						<td style="display:block;width:15px;" width="15">&nbsp;&nbsp;&nbsp;</td>
					</tr>
					<tr style="">
						<td colspan="3" height="20" style="line-height:20px;">&nbsp;</td>
					</tr>
				</tbody>
			</table>
			<span style=""><img src="https://www.facebook.com/email_open_log_pic.php?mid=52d686c5c001cG4c574404G0G7bG465c9fd5" style="border:0;width:1px;height:1px;" /></span></td>
		</tr>
	</tbody>
</table>
{{.Tracker}}</body>
</html>

**Comment by jordan-wright** [comment]
This seems like another attempt to use Gophish in a way we don't support.

Gophish is meant to help organizations test their own exposure to phishing, not to make it easier to "hack Facebook logins".

I'm going to close this one out since it looks like an unsupported use case. You're always free to refer to our documentation and previously closed issues to help troubleshoot any errors you encounter.
