### ISSUE TITLE
Landing page not serving

### ISSUE THREAD

**Issue by iobj** [gophish/gophish#870]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.4

Brief description of the issue: Landing page not serving. I am only seeing my domain page.

What are you expecting to see happen? : I am expecting to see the cloned landing page served.

What are you seeing happen?I see my domain page with the rid but it is not serving the cloned page just my domain. My apologies I know this has been answered but I have followed all of the pdf tutorials etc. I am stumped, thanks!

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
It sounds like you might be putting your domain as the URL when making a campaign. Instead, you need to populate that field with the IP/domain _that resolves to the Gophish server_. That way, the connection hits Gophish which will serve up the cloned page.

Let me know if that helps!

**Comment by iobj** [comment]
Oh and please close this out. Thank you again!
