### ISSUE TITLE
E-mail sender fails after a number of messages sent with an attachment

### ISSUE THREAD

**Issue by vinas64** [gophish/gophish#871]
Hello

I'm using the gophish plattform to send a awareness e-mail to all users to explain what they should do.
This is done after a campaign.
When I try to send a e-mail to more than 500 users (With a 500kb attachment in PDF format) it fails after 130 users with the following error:
wsarecv: An established connection was aborted by the software in your host machine
Without a attachment I get no error and the message is sent with sucess.

**Comment by jordan-wright** [comment]
Hey there,

Thanks for reaching out! I haven't seen this before. Does it always fail after 130 users?

Are there any other terminal logs you can provide that might help show what's going on?

**Comment by vinas64** [comment]
It depends the size of attachment. What i notice now is that for aproximate 500kb attachment the message sending fail after message 131. I had to divide the 3000 users group to several groups with 130 users. And it goes ok. However it's not a solution. For a attachment with aprox. 170kb i can sendo to aprox 360 users after that it fail. I'm usina Windows server 2012

**Comment by jordan-wright** [comment]
Hmmm... That's odd. I've never seen this happen, but the mail queue refactor that I'm rolling out soon (got everything working last night, just want to do a bit more testing) should catch errors like this and adjust as needed so hopefully it'll fix this problem too.

I'll let you know when it's pushed out so you can give it a shot.

**Comment by vinas64** [comment]
i'm really appreciate that. this is the best tool i've found to evaluate the level of cyberawareness of my users. thank you very much

**Comment by jordan-wright** [comment]
This should be fixed as part of the refactor from #878. If you could give it a shot and let me know if it helps, I'd appreciate it!
