### ISSUE TITLE
# github.com/go-sql-driver/mysql ../../go-sql-driver/mysql/utils.go:81: undefined: cloneTLSConfig

### ISSUE THREAD

**Issue by hybrok** [gophish/gophish#872]
GoPhish v0.4

I'm receiving the following error when I attempt to install GoPhish:

```
# github.com/go-sql-driver/mysql
../../go-sql-driver/mysql/utils.go:81: undefined: cloneTLSConfig
```

I did some Googling on it, it says something about support being dropped for Go v1.6 and below, that might be it.

I'm not really sure what I can do to fix this, pls help :/

**Comment by jordan-wright** [comment]
Yep - I restarted the Travis CI builds and it looks to fail out with Go <= 1.6.

The only solution is to update your version of Golang. I'm afraid there isn't much we can do on the Gophish side to fix this, since it was a decision made by the authors of `go-sql-driver/mysql`.

Sorry for the hassle!
