### ISSUE TITLE
Feature request - Set a default SMTP server

### ISSUE THREAD

**Issue by S0larflare** [gophish/gophish#874]
Personally, I only ever use the one SMTP server for sending my emails as it is all internal, so having to put this in every time I want to crete a new sending profile is a (slight) pain. I'm currently migrating over to a new internal SMTP address, so I will now have to go through all of my old sending profiles and update them. I was wondering if it would be worth adding an option to set a 'default' smtp server (possibly with credentials if required) and then when setting a new profile have a tickbox to use the default. This would make it easier to create a sending profile, would make it easier to switch to a new SMTP server (for example if you are doing some Pen Testing/ Social Engineering and move SMTP servers a lot) and would still leave the current setup available if you want to use lots of different servers.

Thoughts?

**Comment by jordan-wright** [comment]
Sounds good. I think it would be a simple checkbox in the UI and be a flag in the database, so it shouldn't be that hard to do.

I'll see about adding this in. Thanks for the suggestion @S0larflare!

**Comment by jordan-wright** [comment]
Hey @S0larflare,

I think I inadvertently fixed this in https://github.com/gophish/gophish/commit/c9e800dda7c52b1a240242b7a8927e6dcb5cf11e 😄. I updated the modal to just populate dropdowns with the value if only one exists. So if you only have one sending profile, this will be populated by default.

I hope this helps!
