### ISSUE TITLE
Mailsploit feature

### ISSUE THREAD

**Issue by Cycl0pe** [gophish/gophish#876]
Hello,

First of all, thanks a lot for this amazing tool!

I was wondering if it will be clever to add a feature regarding the news from this week about [mailsploit](https://www.mailsploit.com/index) ?

Thanks for the response and have a good day!

Cy.

**Comment by jordan-wright** [comment]
Hey there!

Thanks for getting in touch. Mailsploit is cool, but it's a bit of an exotic attack, and many major mail clients will likely patch pretty quickly.

I'm open to accepting pull requests for this, but at this point it's not high on my radar. For anyone who's choosing to send a pull request, I recommend considering how to make this fit in nicely with how the rest of Gophish is structured. It should "just work", so ideally, it would be a one checkbox kind of thing that's handled transparently by Gophish in the background.
