### ISSUE TITLE
Feature request - Download file tracking

### ISSUE THREAD

**Issue by bl4ckswan** [gophish/gophish#880]
I think u should add Downloadfile tracking feauture

**Comment by wanoo** [comment]
+1

And a way to see how many people activate macro on a word document, it will be a nice data

Thanx

**Comment by jordan-wright** [comment]
Thanks for reaching out!

This is a duplicate of #227 so I'll close this one and we'll track the status from there. There's a branch (attachment-support) which has some initial work done by a community member, but it's both outdated (you'll need to merge it with master) and I'm not sure if it still works.

This is something I'm working to add, but I have a large backlog of important issues I'm working through at the moment so I don't have an estimated implementation time at this point.
