### ISSUE TITLE
Stop and Start Issues

### ISSUE THREAD

**Issue by Teh-Dango** [gophish/gophish#882]
What version of Gophish are you using?: 
The latest version available for go get building.

Brief description of the issue: 
If I start an instance then stop it with keyboard shortcut, may be my issue IDK, I try to stop and start again but I get a duplicate entry for admin for key username message. If I remove this admin user and try to start it works fine.

What are you expecting to see happen? :
I assumed, like with my other server, it would stop and start with no issue.

What are you seeing happen?
It appears it is trying to re-create the admin default user each time.

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Start phish server with ./gophish from the gophish dir.
 * Step 2 - Press ctrl+z
 * Step 3 - Start phish server with ./gophish from the gophish dir and messages echo.

This is my first issue submit ever so my apologies if something is not done correctly.

Thanks!

**Comment by Teh-Dango** [comment]
Also I am using mariadb instead of the mysql so IDK if that may be the cause here but it should be a drop in replacement.

**Comment by S0larflare** [comment]
If you’re doing ctrl + z you’re pausing it, if you restart it using fg do you still get strange behaviour?

Sent from my iPhone

On 11 Dec 2017, at 21:37, Teh Dango <notifications@github.com<mailto:notifications@github.com>> wrote:


Also I am using mariadb instead of the mysql so IDK if that may be the cause here but it should be a drop in replacement.

**Comment by Teh-Dango** [comment]
That makes sense lol. I will try this tmrw but I suspect it will work. I am still a noob in many linux aspects. I was under the impression it would terminate itself but after a bit of reading that is not the case.

**Comment by Teh-Dango** [comment]
It works fine when using fg. Picks right back up. Thank you for the help.
