### ISSUE TITLE
Can't acces gophish I've installed in VPS

### ISSUE THREAD

**Issue by ferdinandion** [gophish/gophish#883]
I've installed gophish on my VPS, 
it's running, I tried to make my gophish accesable using my VPS IP Address, 
but it can't access, even if it has been running/working but I can't still access it.

how can I acces gophish I've installed in my VPS?

**Comment by jordan-wright** [comment]
I'm afraid there isn't much I can do to help here since there isn't much information to go off of.

If you could, please open a new issue following the issue template format you see when you create an issue, filling in all the requested information. That will help us troubleshoot the issue.
