### ISSUE TITLE
Can't Access Gophish I've installed in VPS

### ISSUE THREAD

**Issue by ferdinandion** [gophish/gophish#885]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: Gophish v0.4.0

Brief description of the issue: I've installed gophish in my VPS, and I changed admin server listem url to my VPS's IP with port 3333

What are you expecting to see happen? : I can acces gophish by typing my VPS's IP:3333 in browser

What are you seeing happen? Unable to connect showed on browser,

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
i've changed my config.json like this, hope I can access gophish login page using my VPS IP
![img_3589](https://user-images.githubusercontent.com/34478643/33918508-53e74714-dfe6-11e7-9fd0-b59e1cb9a82b.JPG)

         
 * Step 2 - the Gophish working,
but I can't access gophish login page by using my VPS IP,
![img_3587](https://user-images.githubusercontent.com/34478643/33918565-a4c1dba4-dfe6-11e7-8ba4-4269af1fbc8a.JPG)

*Step 3 - All I've got just notification that unable to connect from browser

 i wish you could help me with this,

Thank you

**Comment by jordan-wright** [comment]
What happens if instead of the VPS external IP address you use `0.0.0.0:3333`? Also, are you trying to hit https://ip:3333? Because you have `use_tls` set to `false`, so you need to make sure you're requesting it over http.

If setting it to 0.0.0.0 and hitting it over http gives the same result, then it's probably a firewall preventing the connection.

**Comment by ferdinandion** [comment]
I already try using 0.0.0.0:3333 but its still unable to connect,
![img_3586](https://user-images.githubusercontent.com/34478643/33920295-c6f1c730-dfef-11e7-906f-c8dfeee310f9.JPG)
I've tried over http but its still unable to connect,

I alredy use iptables and the result is allowed all protocol (I assumed)
![img_3588](https://user-images.githubusercontent.com/34478643/33920350-0cda6fb8-dff0-11e7-97ce-c05814447f54.JPG)

Is there any way to fix this?

**Comment by jordan-wright** [comment]
What happens if you try `curl localhost:3333` on the box? If that works, then you almost definitely have a firewall issue.

I also don't immediately see an iptables entry that lets this connection happen. It seems like it would fall through and hit the reject rule.

**Comment by ferdinandion** [comment]
It's about the configuration on config.json
when i used 127.0.0.1:3333

its working and I can't acces gophish login page using my VPS IP

thank you

**Comment by ferdinandion** [comment]
I mean I can Acces my gophish login page using VPS IP

**Comment by horllste** [comment]
which vps hosting are you using?

**Comment by S0larflare** [comment]
So if you access it locally on the VPS, you can get to the console, but if you try to navigate to it from your personal machine you can't access it? Certainly seems like a firewall issue.

**Comment by ferdinandion** [comment]
@horllste I'm using VPS from ghost

@S0larflare yes it is, I guess it's about the firewall issue

**Comment by jordan-wright** [comment]
Closing this out since it doesn't seem to be a bug with Gophish, but rather a firewall issue on the VPS. @ferdinandion I recommend referring to your VPS and OS documentation for help setting up the right FW rules, since this is something that's outside the scope of our support.
