### ISSUE TITLE
error when sending test mail

### ISSUE THREAD

**Issue by ferdinandion** [gophish/gophish#887]
What version of Gophish are you using?: gophish v0.4.0

Brief description of the issue: when I tried to send test mail appear notification said "dial tcp: lookup smtp.bliibli.com on 8.8.8.8:53 no such host"

What are you expecting to see happen? : email sent

What are you seeing happen? 

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - I using my web mail server that I made, into the sending profile,

 * Step 2 - but it comes out said error

**Comment by jordan-wright** [comment]
It looks like `smtp.bliibli.com` isn't a valid hostname. You need to point your smtp profile to a valid hostname that resolves to an IP address.
