### ISSUE TITLE
./VERSION - The system cannot find the file specified

### ISSUE THREAD

**Issue by briangwellsins** [gophish/gophish#889]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: Version 4

Brief description of the issue: Cannot install - In Windows 10 64 bit, I am met with the following line of code in the CMD upon launching the executable: gophish.go:58: open ./VERSION: The system cannot find the file specified.

What are you expecting to see happen? : Installation to complete so that I can launch gophish

What are you seeing happen? Installation fail at the same place each time

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Download gophish, extract folder to root of C drive
 * Step 2 - Launch gophish.exe. Met with ./VERSION: The system cannot find the file specified.

**Comment by jordan-wright** [comment]
Is there a file called `VERSION` in the Gophish folder? If so, make sure you're changing into the Gophish directory before launching the program.

**Comment by briangwellsins** [comment]
Hi, yes, there is a file called VERSION in the root of the directory (same as the gophish.exe file). I have tried launching the exe directly, and I have also tried launching CMD (Both with and without admin rights), changing to the directory from within CMD, and launching the exe file from there, still get the same error both ways.

________________________________

**Comment by jordan-wright** [comment]
Hmmm... That's really odd. Gophish should be looking in the current directory (whatever your CWD is) for that file. So if you open cmd (might try a powershell prompt instead? Shouldn't make a difference but 🤷‍♂️ ) prompt, navigate into the Gophish directory and run `gophish.exe` from there, that _should_ work and works fine on my box.

Let me know if you make any progress. Otherwise, I'll see about changing this to point to the absolute path pointing to the Gophish directory to maybe clear up some issues for when people execute gophish outside of that directory.

**Comment by briangwellsins** [comment]
INTERESTINGLY enough..... this worked when I launched it in Powershell. It wouldn't work no matter what I did from the CMD. Now that one I do not understand. Strange.

________________________________

**Comment by jordan-wright** [comment]
Good deal! That is strange, but I’m glad you were able to find a workaround for this.
