### ISSUE TITLE
Add Back Button to Campaign Results Page

### ISSUE THREAD

**Issue by StrangeUSB** [gophish/gophish#89]
I keep wanting to press the giant red ```X``` to go back to the campaigns.

**Comment by StrangeUSB** [comment]
Thoughts?

![campaigns_back](https://cloud.githubusercontent.com/assets/6924235/12470333/db348466-bfb8-11e5-8623-0aa67d3a5b80.png)

**Comment by jordan-wright** [comment]
The good news is that the "X" won't be bothering you anymore as of #34, since it looks like:

![image](https://cloud.githubusercontent.com/assets/1317288/12470377/3020f00e-bfb9-11e5-9bfd-b8fcb54414cb.png)

However, I'm all for a back button if you want to drop one in!

**Comment by StrangeUSB** [comment]
Man I really need to do a pull on my branch.  I like the buttons with words a lot better, I'll see if I can fit a back button in there somewhere.

**Comment by StrangeUSB** [comment]
Example of what it could be with the export button:

![back](https://cloud.githubusercontent.com/assets/6924235/12471277/abd0e58a-bfc1-11e5-895e-8676a09ece7f.png)

**Comment by jordan-wright** [comment]
Hey, I like that a lot. I was worried about what color we would use, but I think you nailed it.

What's up with your font? Is the Roboto font not loading for you?

**Comment by StrangeUSB** [comment]
Ok cool, I can push this change to the csv-export branch or I can do it to master.

I guess I never realized it was off, I'm looking into it now.  Looks like the font is being loaded but not actually being used.

**Comment by jordan-wright** [comment]
Go ahead and push it to master once you've pulled the latest changes - I'm good with it!

**Comment by jordan-wright** [comment]
It looks like Source Sans Pro is used for me right now, too. That's odd... I could've sworn I changed it. I'll need to look into that.

**Comment by StrangeUSB** [comment]
Yeah that is what's actually being used, even if I manually set the font-family to roboto it looks the same.

Also chrome just looks a bit different (Chrome, Firefox, Safari)
![font_chrome](https://cloud.githubusercontent.com/assets/6924235/12471649/456d359c-bfc5-11e5-9eb7-e7e9fcbe455a.png)
![font_firefox](https://cloud.githubusercontent.com/assets/6924235/12471647/456a4ce2-bfc5-11e5-8f05-53fdc64d803c.png)
![font_safari](https://cloud.githubusercontent.com/assets/6924235/12471648/456c951a-bfc5-11e5-8a7a-add6d3a1b39c.png)

**Comment by jordan-wright** [comment]
Odd. Mine changes if I manually set it.

Your choice - which do you prefer:

![image](https://cloud.githubusercontent.com/assets/1317288/12471669/6fda9a86-bfc5-11e5-8d53-22b5258e8310.png)

**Comment by StrangeUSB** [comment]
I think it could be inheriting the font-family from flat-ui.css:160 
```CSS
body {
  font-family: "Source Sans Pro", Helvetica, Arial, sans-serif;
  font-size: 18px;
  line-height: 1.72222;
  color: #283F50;
  background-color: #ffffff;
}
``` 

I like the one on the right just a bit more.

**Comment by jordan-wright** [comment]
Yeah, I agree - for buttons I might keep Source Sans Pro. I would like to move the label style to be Roboto, though. I think it looks just a bit slicker for that inline table look.
