### ISSUE TITLE
Managing & Modifying Accounts and their permissions

### ISSUE THREAD

**Issue by kjohnson5** [gophish/gophish#891]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.4

Brief description of the issue: 
1. Unable to manage users. I created a few users but cannot manage the accounts. I am unable to see the accounts and edit any form of permission for the user. If I needed to delete the user how would I be able to do so?
2. Be able to create readonly users.
3. There should be able to give users just access to the campaign and not the ability to create campaign but see results from past campaigns or queued campaigns. I want to be able to create users who only have access to view the campaign and it's result without having to export the data and emailing it.

What are you expecting to see happen? :
1. I expect to be able to manage users. To see all the users that were create and delete user(s) account if needed while modifying their access level. 
2.  Be able to grant users the ability to only see campaigns that have already been run or those that are queued. These users should NOT have the ability to create anything such as the landing page, sending profile, etc. They should only be able to just view results of campaigns that were already created.

What are you seeing happen? I cannot see any users that were created. The users are able to login and they have admin access to create new profiles/templates and campaign. I cannot delete users or modify users in any capacity.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by S0larflare** [comment]
Unfortunately RBAC (role based access) isn’t currently implemented. Each account only has access to what it has itself created and there isn’t any GUI for user management. If you’re wanting to delete a user you’d have to delete them directly from the database

Sent from my iPhone

On 15 Dec 2017, at 20:25, kjohnson5 <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for reaching out! We're happy to help resolve issues as quickly as possible.

Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our documentation<https://getgophish.com/documentation/>, which covers how to use Gophish.

What version of Gophish are you using?: 0.4

Brief description of the issue:

  1.  Unable to manage users. I created a few users but cannot manage the accounts. I am unable to see the accounts and edit any form of permission for the user. If I needed to delete the user how would I be able to do so?
  2.  Be able to create readonly users.
  3.  There should be able to give users just access to the campaign and not the ability to create campaign but see results from past campaigns or queued campaigns. I want to be able to create users who only have access to view the campaign and it's result without having to export the data and emailing it.

What are you expecting to see happen? :

  1.  I expect to be able to manage users. To see all the users that were create and delete user(s) account if needed while modifying their access level.
  2.  Be able to grant users the ability to only see campaigns that have already been run or those that are queued. These users should NOT have the ability to create anything such as the landing page, sending profile, etc. They should only be able to just view results of campaigns that were already created.

What are you seeing happen? I cannot see any users that were created. The users are able to login and they have admin access to create new profiles/templates and campaign. I cannot delete users or modify users in any capacity.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

Insert code here

Please provide any terminal output that may be relevant below:

Insert output here


Please provide as many steps as you can to reproduce the problem:

  *   Step 1 -
  *   Step 2 -

**Comment by kjohnson5** [comment]
Is RBAC something that has already been requested for a future release? I think this product could really benefit from such as feature. 

Exactly how do you go about deleting a user from the database?

**Comment by jordan-wright** [comment]
Hi there! Sorry for the delay.

RBAC has been proposed in the past, but I have no plans to implement it in Gophish. It's a huge task that requires a major architectural overhaul.

Deleting a user from the database can be done with a SQL command to whichever database you're using. IIRC the records are stored in the `users` table. There are also various database GUI's to help make interacting with your database easier.
