### ISSUE TITLE
Need Help To Set a Gmail Caimpagn

### ISSUE THREAD

**Issue by markcol2312** [gophish/gophish#892]
Hy to everyone. I used from 2 weeks Gophish 0.4. 
I'm having a series of problems. I set the sending profile on an SMTP gmail port 587. The email test works and sends. For the landing page insert the login page of Gmail uploading the url. I click on capture date and password. For the template I copied the source source of an old Gmail email. As for the launch of the campaign I do not understand what I have to put in the url. The problem is the follow. The dashboard does not appear when the email is open, when the data is placed and is not registered anywhere.
I will give you my nickname and password of my Gophish myself to see what I have combined in desperation. In any case, the email is sent but when I open it and click on the link, it does not open any page. Can someone help me? Do I have to change settings on my PC to make the server work? If I provide you with the credentials, can you check the setting of my test?

**Comment by S0larflare** [comment]
Have you read through the [documentation](https://getgophish.com/documentation/)? It should help to guide you through how to set up campaigns.

The campaign url should point back to your gophish instance. Whoever you are testing needs to be able to reach this IP/URL.

**Comment by markcol2312** [comment]
Yes i have read the documentation and i follow step by step the instuction but it doesn't work.  Where i ca find that url? If i set my sending profile with an STMP of google?
If i gave you my credential of Gophish can you check what i wrong? I don't no how to do and for saturday i needs this software. In every case i know it's a strange request but i write here my User: Admin Password: Gente2312. If you can help me you can see i my software where i wrong it will be a wonderful Christman present

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by S0larflare** [comment]
Sorry I'm not going to log in to your Gophish instance (and you should not be sharing username/password with anybody). 

Is this on your personal PC or on a server?

**Comment by jordan-wright** [comment]
As @S0larflare mentioned, we're not going to log in to your Gophish instance. It's not going to happen.

It's still unclear what you're having issues with. @S0larflare gave a perfect explanation for the URL field. You should put the external IP address and port that the Gophish server is listening on.
