### ISSUE TITLE
Test Email Failing

### ISSUE THREAD

**Issue by bpraveen18** [gophish/gophish#893]
What version of Gophish are you using?: 
Version gophish-v0.4-windows-64bit
Brief description of the issue: 
I am setting up sending profiles and send a test email but getting error as "dial tcp: i/o timeout".
have used gmail SMTP
smtp.gmail.com:465 & smtp.gmail.com:587
What are you expecting to see happen? :
I was expecting that the email be sent successfully

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

**Comment by S0larflare** [comment]
Make sure your firewall isn't blocking the SMTP traffic on ports 465/487

**Comment by jordan-wright** [comment]
Yes, this almost certainly appears to be a firewall issue. With this being the case, I'm afraid there isn't anything we can do on our end to help get this one resolved.
