### ISSUE TITLE
Purchased Domains for phishing test

### ISSUE THREAD

**Issue by turnerdb** [gophish/gophish#894]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
v0.4
Brief description of the issue: 
We are trying to get our  purchased domains set up so we can use them in our phishing campaigns and not have them blocked.  We are getting a spf=temperror (google.com: error in processing during lookup of noreply@ourdomain: DNS error) smtp.mailfrom=noreply@ourdomain

We purchased domains in order to be seen as permitted senders on our GoPhish server public IP.  The emails keep going to spam which we believe is part of an issue with google so we are filling out a form to get off the list.
What are the proper steps/guide on setting up the domains settings to get everything working smoothly.
The emails are sending but we are receiving the above error.

**Comment by jordan-wright** [comment]
Hey there! It sounds like you don't have SPF setup for those domains. I recommend setting up SPF, DKIM, and DMARC for those domains. Probably the quickest way to do that is to setup the records via an email sending provider like Sendgrid or Amazon SES and use their settings. Then, you would point Gophish's SMTP settings to them.

Alternatively, you'd need to create the records correctly pointing the Gophish server.

**Comment by jordan-wright** [comment]
Going ahead and closing this out since it seems the initial question was responded to and there haven't been any updates in a while. @turnerdb let me know if this doesn't help fix the issue and we can continue troubleshooting.
