### ISSUE TITLE
AWS EC2 and gophish - Port 80 and Admin login issues

### ISSUE THREAD

**Issue by gethubish** [gophish/gophish#895]
**What version of Gophish are you using?:**  0.4

Thanks for creating this awesome app!  I had success getting it working on my laptop but have been trying for a couple of days to get it to work (I am new to Linux) on an AWS EC2 instance.   I have watched the [YTvideo for gophish](
https://www.youtube.com/watch?v=knc6Iq-hNcw) and read the AWS issues, and all the others, but don't see a consisting/final config for AWS (Ubuntu 14.0) setup.

I am now trying it out on an EC2 instance with Wordpress where I hope to house the landing pages as I am doing now on another Wordpress site.  

In the video, the config.json is left at 0.0.0.0:3333 for the Admin server (at 2:38) however one of the issue state that it should be your network IP:3333.

What's happening is:
When starting ./gophish - I get an error "port 80 already in use"
If I change to 8080 for the phish server then I don't get that error but the cursor doesn't come back

Regardless of what I try, the Admin page never displays. 

 **What I have tried from reading the issues**:
-stopping apache
-disabling IPv6 permanently
-8080 instead of 80 for the phish server
-using 0.0.0.0, 172.x.x.x (aws assigned ip)
-using 34.x.x.x (aws elastic/static) - i get a binding error using this IP
**In AWS**
-a new instance wtih Wordpress but w/o installing MySql
-starting/stopping the instance then starting gophish then trying the Admin page
-adding port 8080 to the security group

**What are you expecting to see happen? :** When I go to 172-x-x-x:3333 should get the Admin page 

**What are you seeing happen?** Timesout when I access 172-x-x-x:3333.  I can access the Wordpress admin page ok.

**Here is the before and after port listings**

_Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      1495/mysqld.bin
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1547/httpd.bin
tcp        0      0 127.0.0.1:21            0.0.0.0:*               LISTEN      597/vsftpd
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      888/sshd
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      1547/httpd.bin
tcp6       0      0 :::22                   :::*                    LISTEN      888/sshd
udp        0      0 0.0.0.0:27482           0.0.0.0:*                           546/dhclient
udp        0      0 0.0.0.0:68              0.0.0.0:*                           546/dhclient
udp6       0      0 :::34365                :::*                                546/dhclient

root@ip-172-x-x-x:/opt/gophish-v0.4-linux-64bit# ./gophish
 2017/12/22 07:02:05 worker.go:37: Background Worker Started Successfully - Waiting for Campaigns
goose: no migrations to run. current version: 20170827141312
 2017/12/22 07:02:05 gophish.go:104: Starting phishing server at http://0.0.0.0:8080
 2017/12/22 07:02:05 gophish.go:87: Starting admin server at https://172.x-x-x:3333
 2017/12/22 07:03:05 campaign.go:348: Found 0 Campaigns to run
 2017/12/22 07:04:05 campaign.go:348: Found 0 Campaigns to run
 2017/12/22 07:05:05 campaign.go:348: Found 0 Campaigns to run
........ for 10 minutes and still get "The server at 172.x.x.x is taking too long to respond" when trying 172.x.x.x:3333

Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 172.x-x-x:3333       0.0.0.0:*               LISTEN      1877/gophish
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      1495/mysqld.bin
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1545/httpd.bin
tcp        0      0 127.0.0.1:21            0.0.0.0:*               LISTEN      596/vsftpd
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      896/sshd
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      1545/httpd.bin
tcp6       0      0 :::8080                 :::*                    LISTEN      1877/gophish
tcp6       0      0 :::22                   :::*                    LISTEN      896/sshd
udp        0      0 0.0.0.0:6037            0.0.0.0:*                           544/dhclient
udp        0      0 0.0.0.0:68              0.0.0.0:*                           544/dhclient
udp6       0      0 :::41946                :::*                                544/dhclient_

**and config.json**

   _"admin_server" : {
                "listen_url" : "172.x.x.x:3333",
                "use_tls" : true,
                "cert_path" : "gophish_admin.crt",
                "key_path" : "gophish_admin.key"
        },
        "phish_server" : {
                "listen_url" : "0.0.0.0:8080",
                "use_tls" : false,
                "cert_path" : "example.crt",
                "key_path": "example.key"
        },
        "db_name" : "sqlite3",
        "db_path" : "gophish.db",
        "migrations_prefix" : "db/db_"_

So my questions are:
Any ideas on how to get to the admin screen to show?  
Also, the 172 IP will change on reboot, is there a method to refer to the 34 IP some how which doesn't change?
Also, I wasn't sure where to install gophish this so it is in /opt; please confirm if that is ok or an issue.

Thank you

**Comment by S0larflare** [comment]
you say you get a binding error for 34.x.x.x, can you show the error you're getting?

The problem with not being able to access the admin page appears to be firewall related. Try adding a rule to allow inbound on port 3333. That said if you are  exposing the admin page to the internet I would strengthen the password for GoPhish

**Comment by gethubish** [comment]
answering this in reverse:

**added custom TCP rule for 3333 (thanks for the heads up about pw)**
stop/start 172.x.x.x still hangs
however, just for grins I tried 34.x.x.x and instead of no connection I got a white browser page with lil garbage at the top left corner � (note: config.json was still at 172.x.x.x at this time) and these 174...lines appeared, 3 lines off the bat then another line each F5 on 34.x.x.x:3333 - repeated this after the below switch and the � reoccured - 172 in config but refreshing on 34 gets a connection - using FF and happens with Edge except no blank screen just the "handshake" lines

_2017/12/22 08:53:33 http: TLS handshake error from 174.xxx.x.xx:13357: tls: first record does not look like a TLS handshake
2017/12/22 08:53:47 http: TLS handshake error from 174.xxx.x.xx:8395: tls: first record does not look like a TLS handshake
 2017/12/22 08:53:52 campaign.go:348: Found 0 Campaigns to run_

**then I updated config.json to 34.x.x.x**
stop/start and 34.x.x.x yields this
root@ip-172-x-x-x:/opt/gophish-v0.4-linux-64bit# ./gophish
goose: no migrations to run. current version: 20170827141312
 2017/12/22 09:00:50 gophish.go:104: Starting phishing server at http://0.0.0.0:8080
 2017/12/22 09:00:50 worker.go:37: Background Worker Started Successfully - Waiting for Campaigns
 2017/12/22 09:00:50 gophish.go:87: Starting admin server at https://34.x.x.x:3333
 2017/12/22 09:00:50 gophish.go:89: listen tcp 34.x.x.x:3333: **bind: cannot assign requested address**
root@ip-172-31-22-42:/opt/gophish-v0.4-linux-64bit#

**updated config.json**

        _"admin_server" : {
                "listen_url" : "34.x.x.x:3333",
                "use_tls" : true,
                "cert_path" : "gophish_admin.crt",
                "key_path" : "gophish_admin.key"
        },
        "phish_server" : {
                "listen_url" : "0.0.0.0:8080",
                "use_tls" : false,
                "cert_path" : "example.crt",
                "key_path": "example.key"
        },
        "db_name" : "sqlite3",
        "db_path" : "gophish.db",
        "migrations_prefix" : "db/db_"_

note in case I mistyped
_172.x.x.x. gets "taking to long to respond"
34.x.x.x gets "unable to connect"_
regardless of what is in config.json

Also double checked the firewall was still disabled after reboot

_bitnami@ip-172-x-x-x:~$ sudo ufw status
Status: inactive
bitnami@ip-172-x-x-x:~$_

Do you know what the handshake lines are indicating?

**Comment by S0larflare** [comment]
Is your 172 address a private IP? As in between 172.16.0.0 and 172.31.255.255? If that is the case you won't be able to route to it externally like that. 


Your other bit, ie this:

```
2017/12/22 08:53:33 http: TLS handshake error from 174.xxx.x.xx:13357: tls: first record does not look like a TLS handshake
2017/12/22 08:53:47 http: TLS handshake error from 174.xxx.x.xx:8395: tls: first record does not look like a TLS handshake
2017/12/22 08:53:52 campaign.go:348: Found 0 Campaigns to run
```
Indicates that you're tryping to connect via http, change it to http**s** and hopefully you'll be good to go.

**Comment by jordan-wright** [comment]
In addition to everything @S0larflare mentioned, also note that Gophish may not work the way you expect it to work:

> I am now trying it out on an EC2 instance with Wordpress where I hope to house the landing pages as I am doing now on another Wordpress site.

Gophish doesn't support hosting landing pages anywhere but on Gophish. I mean, they would resolve, but you wouldn't see any stats like clicked link or submitted data, since wordpress would be catching that request, not Gophish.

If you're going with Gophish, I highly recommend keeping everything within Gophish and scrapping the Wordpress dependency if at all possible.

I'll leave this open to see if @S0larflare's comments help you get this one resolved.

**Comment by gethubish** [comment]
Thanks **@S0larflare** the SSL did the trick.  I actually missed that in the guide so I did the cert steps and added 443 as a port in AWS and with https 34.x..x.x browser access and 172.x.x.x config.json and it worked!

**Jordan**, I was never able to get tracking working on my laptop so I don't have anything to compare it to but I take your direction and scrap the instance and start over with just a plain EC2 Linux footprint.

I do need to mention "Import Email" always yielded blank results so I cut/paste into the HTML box but the links don't get updated.  I thought it was my laptop/browser so I waited until I could move to AWS but the same thing happens (_click Import Email - past in LinkedIn email - click Import- all boxes are still blank_).

Emails are delivered just fine, formatted like the original.  

**You can close this now :)** and if I cannot get tracking working then I'll circle back with a new issue.  After that I will retest _Import Email_.  And after that I will try to figure out setting it up [to always run in AWS](https://github.com/gophish/gophish/issues/586) :)

Thanks for all your help!
Merry Christmas!
