### ISSUE TITLE
Email Template Creation

### ISSUE THREAD

**Issue by LRRH** [gophish/gophish#896]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

I am simingly able to create an email template and when I hit save I get the message saying "template created successully".  However, the template doesn't show up as having been saved.  Any ideas?

**Comment by S0larflare** [comment]
What does the terminal show? Are there any errors?

When you say it doesn’t show, do you mean that it creates a blank email template or it doesn’t create anything at all?

Sent from my iPhone

On 22 Dec 2017, at 17:08, LRRH <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for reaching out! We're happy to help resolve issues as quickly as possible.

Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.

I am simingly about to create an email template and when I hit save I get the mssage saving template created successully. However, the template doesn't show up as having been saved. Any ideas?

**Comment by LRRH** [comment]
I get the message saying "Template added successfully!".  When I refresh the page email templates are still showing "No Templates Created, Let's Create One"

**Comment by S0larflare** [comment]
Odd. What does it say on the console? I suspect it is erroring out but not showing it to you. It might happen if there is some weird JavaScript or something. Is this a page you have imported or is it one you’ve built yourself? Can you make a simple ‘hello world’ page and save that successfully?

Sent from my iPhone

On 22 Dec 2017, at 17:14, LRRH <notifications@github.com<mailto:notifications@github.com>> wrote:


I get the message saying "Template added successfully!". When I refresh the page email templates are still showing "No Templates Created, Let's Create One"

**Comment by LRRH** [comment]
I created a very basic one and tried saving it, no errors appears to save.  Gonna try another browser 
		
		

		/JG
	




On Fri, Dec 22, 2017 at 11:17 AM -0600, "S0larflare" <notifications@github.com> wrote:










Odd. What does it say on the console? I suspect it is erroring out but not showing it to you. It might happen if there is some weird JavaScript or something. Is this a page you have imported or is it one you’ve built yourself? Can you make a simple ‘hello world’ page and save that successfully?





Sent from my iPhone





On 22 Dec 2017, at 17:14, LRRH <notifications@github.com<mailto:notifications@github.com>> wrote:








I get the message saying "Template added successfully!". When I refresh the page email templates are still showing "No Templates Created, Let's Create One"

**Comment by LRRH** [comment]
It was the browser, really strange.  I logged in with chrome and they all showed up

**Comment by S0larflare** [comment]
That is odd, what browser were you having issues with?

Sent from my iPhone

On 22 Dec 2017, at 17:25, LRRH <notifications@github.com<mailto:notifications@github.com>> wrote:


It was the browser, really strange. I logged in with chrome and they all showed up

**Comment by jordan-wright** [comment]
We’ll need to know the browser you’re using and what errors are appearing in the browsers developer console to help track this down.

As a rule of thumb, Chrome is generally the best supported browser, since that’s what I use for development.
