### ISSUE TITLE
AWS EC2 and Tracking Statistics Not Showing Up

### ISSUE THREAD

**Issue by gethubish** [gophish/gophish#897]
**What version of Gophish are you using?**:  0.4
**Brief description of the issue:**  Tracking statistics don't show up - except for emails sent
**What are you expecting to see happen?** : Open, Clicked, and Submitted - landing pages work OK
**What are you seeing happen?:** Not sure where to look to check troubleshoot issues

So I scrapped the original instance and I'm using a plain Linux LAMP version (no Unbuntu).  Gophish runs w/o errors and sends out emails OK.

I think one issue is the URL for the campaign or what uses it?  I have 8080 in my config.json and so I am using 34.x.x.x:8080 for the campaign URL (from reading other issues/suggestions).

I use Outlook 2010 but also switched to webmail seeing a suggestion about Outlook maybe blocking sending back stats (?)

**Netstat while running**
_Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address               Foreign Address             State   
tcp        0      0 172.x.x.x:3333          0.0.0.0:*                   LISTEN 
tcp        0      0 0.0.0.0:38341               0.0.0.0:*                   LISTEN 
tcp        0      0 0.0.0.0:111                 0.0.0.0:*                   LISTEN 
tcp        0      0 0.0.0.0:22                  0.0.0.0:*                   LISTEN 
tcp        0      0 127.0.0.1:25                0.0.0.0:*                   LISTEN 
tcp        0      0 :::111                      :::*                        LISTEN 
tcp        0      0 :::8080                     :::*                        LISTEN_ 

**config.json**

        _"admin_server" : {
                "listen_url" : "172.x.x.x:3333",
                "use_tls" : true,
                "cert_path" : "gophish_admin.crt",
                "key_path" : "gophish_admin.key"
        },
        "phish_server" : {
                "listen_url" : "0.0.0.0:8080",
                "use_tls" : false,
                "cert_path" : "example.crt",
                "key_path": "example.key"_

**Campagin URLs tried**:  https://34.216.49.130:8080, https://172.x.x.x:8080 (and http)

Do I need the https or http, tried it both ways with both AWS IP's with no change.
For the Sendign Profile, there are extra fields not in the documentation and I left these blank, Custom Header.  Want to confirm this has no effect.  Also stopped Apache while testing as read in the suggestions.

Any ideas?

**Comment by jordan-wright** [comment]
You don’t want to have Apache running. Gophish runs its own webserver - Apache will just get in the way unless you’re configuring it to correctly proxy connections to Gophish.

As mentioned in our documentation, the campaign URL should be the IP and port pointing to your Gophish phishing server. This should be reachable by the clients, so chances are the 34.x.x.x url is correct.

Whether you use http or https depends on your configuration. You’ll notice you have use_tls set to false, so you do not want to use tls, so you use http.

Finally, that’s not a guarantee tracking will work. Outlook is big about blocking tracking pixels so it may block Gophishs tracking attempts. Unfortunately, there’s nothing we can do to prevent that in Gophish.

**Comment by gethubish** [comment]
Ok thanks for the update.  Realize you cannot help Microsoft's handling of the emails.  Just was excited to see responses.  I tried with webmail as well.  Thanks for the all the input.

**Comment by gethubish** [comment]
I got this to work!  I thought I would circle back and record in case parts are of interest to others:

1) Restarted with just a Linux instance (no apache, mysql, php, or wordpress) 
2) Created bare bones pages, just for testing, using Word, saving as htm - I was counting on WordPress to create forms and the landing pages (as in my laptop test) but reading the /static section of the guide I figured out how to make MS Word htm pages and a simple form - ding suddenly remembered it's the browser that interprets the page!
3) Used an old LinkedIn email for the email template, like the YTube for the email.  Import email still doesn't work for me but cut/paste did - I used KompoZer to edit - I'm sure there is an easier way, just used to wp and other simlpe tools to build pages
4) Ended up not needing 8080 when I left Apache out so my config is still 172..:3333/0...:80 but my campaign URL is 34... which is the AWS elastic IP
5) The Outlook client all but set off an audible alarm when emails were received (BIG PINK block of text) so I switched to webmail where it only confirms you want to run a script. 

Sorry, I've never had a class so it takes a while to work through what others know from birth :)

Todo's left are still 
- setup for running  Gophish on start up - when I close my Putty window Gophish stops
- tighten up security - since I clearly out of my element Im sure there are holes that need to be tended to 
- try out on my test volunteers
- create slicker web pages/different editor
- look through attachment download section, not sure from the issues if this is in production yet?

Some suggestions:
- In the guide, [Templates and Email Templates](https://gophish.gitbooks.io/user-guide/content/documentation/templates.html) seem to be interchangeable on some pages.  May want to update the section header.  In the beginning, skipped this section trying to match the application menu with the menu for the guide
- Import site worked but Import email didn't - so "replacing links" then doesn't - wondering if there is a limit to volume of content?  Got around by just doing the guides "your password needs reset" example, just one sentance in the email template
- "Pre built binary" probably means something :) but maybe start out with "don't install LAMP/not for LAMP" - I think the overwhelming amount of info that let's you build your own everything maybe calls for some up front, "non prep" so to speak 
- Update the TY video to include the above - After ditching WordPress I still automatically associated EC2 with Web server/LAMP - might be good to note to start w/o anything on the box - maybe the cause of some of the port 80/8080 tickets - I was on a team managing Toy/Scion/Lex web properties so this was on me just hard to shake a know environment
- Update Sending Profile screenshot and add the new fields 

That enough for now, happy to help testing the attachment download feature if you need.  My goal is to help small business understand the urgency of training for phising attacks as they get more sophisticated.

![image](https://user-images.githubusercontent.com/34617876/34375814-5a343ce6-ea9d-11e7-9715-c2d2d5a0dbd2.png)
