### ISSUE TITLE
Copy of campaign changes items

### ISSUE THREAD

**Issue by krasian** [gophish/gophish#898]
What version of Gophish are you using?:  0.4

Brief description of the issue: When copying a campaign, items do not stay consistent in the copy.

What are you expecting to see happen? :  The copy have the same template, landing page, URL, sending profile, and groups.  Only the URL stayed the same.

Seems like this may be the same as #560 and #549, but those were with 0.3 and I am still experiencing them with 0.4.

**Comment by jordan-wright** [comment]
Can you give an exact workflow for when this happens? Like, what templates you expect to see, what you see instead, if you deleted anything or renamed anything, etc.

The trouble with #560 and #549 is that I never could reproduce the issues.

**Comment by krasian** [comment]
I uploaded a screen recording for you.  I ran three tests.  One of which has the problem explained above.  As you can see, some things don't seem to impact a successful copy such as URL or recipient group.  Also had the same issue with on 0.3
[Gophish_CopyCampProb.zip](https://github.com/gophish/gophish/files/1591536/Gophish_CopyCampProb.zip)
