### ISSUE TITLE
New campaign - drop downs not in alphabetical order

### ISSUE THREAD

**Issue by krasian** [gophish/gophish#899]
What version of Gophish are you using?:  0.4

Brief description of the issue:  When creating or changing a copied campaign, items in the drop downs are not in alphabetical order.

What are you expecting to see happen? :  The drop down items to be in alphabetical order or in some other user selectable order such as creation date.

What are you seeing happen?  Order appears to be sorted based on creation date.

**Comment by jordan-wright** [comment]
Yeah, makes sense. We can get this fixed. Thanks for the report!

**Comment by jordan-wright** [comment]
Sorry for the delay. I've gotten this fixed. Let me know if this doesn't solve the issue!
