### ISSUE TITLE
All users access to shared libraries

### ISSUE THREAD

**Issue by loza0269** [gophish/gophish#900]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

.4

Brief description of the issue: 

Not an actual issue, but I wanted to know if I could make it so all users on the gophish server could access the same resources. So if the admin added an email template all users can access the email template and vice verse.

What are you seeing happen?

I cant access any of the email templates created under a different user.

**Comment by jordan-wright** [comment]
RBAC w/ sharing of resources isn't available in Gophish. Unfortunately, all resources will need to be copied between users.

Implementing this is a huge task, so I don't anticipate getting it done anytime in the near future 🙁 Sorry for the inconvenience!
