### ISSUE TITLE
Change tracking image

### ISSUE THREAD

**Issue by egilas** [gophish/gophish#905]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: latest

Brief description of the issue: 
Tracking image is 1x1 pixel. Flagged as SPAM.

What are you expecting to see happen? : 
Want to be able to switch tracking image to a legit image, like a logo.

What are you seeing happen?
I've tried to replacing static/images/pixel.png without success.

**Comment by jordan-wright** [comment]
There are all sorts of things that could cause an email to be flagged as spam. Are you sure it's the tracking pixel causing this?

> I've tried to replacing static/images/pixel.png without success.

What do you mean "without success"?

**Comment by jordan-wright** [comment]
Closing this since there hasn't been any update in a while. @egilas if you are still running into this issue, let me know and we can always re-open to continue troubleshooting.
