### ISSUE TITLE
Tracker Image

### ISSUE THREAD

**Issue by jgoody** [gophish/gophish#906]
My tracker image in all of my email templates is showing as a dead picture.  Am I missing something?

**Comment by jgoody** [comment]
Looks like outlook blocks the tracker image from displaying, because I do not see the dead image in gmail.  Is that normal behavior?

**Comment by jordan-wright** [comment]
Hi there! Thanks for reaching out.

As a quick note, please follow our issue template for future issues.

For this issue, you will find guidance in the other [various issues](https://github.com/gophish/gophish/search?q=outlook&type=Issues&utf8=%E2%9C%93) mentioning Outlook and tracking images. Tl;dr Outlook blocks tracking images and I'm afraid there isn't anything we can do in Gophish to prevent it.
