### ISSUE TITLE
Imported landing page causes malfunction when hit 

### ISSUE THREAD

**Issue by atropineal** [gophish/gophish#907]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: gophish-v0.4-linux-64bit

Brief description of the issue: imported landing page can cause error when hit

What are you expecting to see happen?: successful landing page response

What are you seeing happen?: error in gophish log (see below) and empty http response

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

import https://www.meetup.com/find/?allMeetups=false&keywords=machine+learning&radius=10&userFreeform=XXX+XXX (XXX+XXX is a redacted London postcode)

Please provide any terminal output that may be relevant below:

```
gophish log showing error:

2018/01/04 14:31:26 phish.go:119: template: html_template:2037: unexpected "{" in command

curl output showing empty http response:

curl -v https://REDACTED:10443/RED/ACTED?rid=bGNN7di
*   Trying REDACTED
* Connected to REDACTED port 10443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 704 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
...
* ALPN, server accepted to use http/1.1
> GET /RED/ACTED?rid=bGNN7di HTTP/1.1
> Host: REDACTED:10443
> User-Agent: curl/7.47.0
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host REDACTED left intact
curl: (52) Empty reply from server
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - create any email
 * Step 2 - import https://www.meetup.com/find/?allMeetups=false&keywords=machine+learning&radius=10&userFreeform=XXX+XXX as landing page (XXX+XXX is a redacted London postcode)
* Step 3 - start campaign
* Step 4 - click on link and get error

**Comment by atropineal** [comment]
PS in this instance we worked around the issue by making a very simple HTML landing page that merely redirected the target's browser to the URL in question.  This workaround would not be appropriate if one needed to capture form input.

**Comment by jordan-wright** [comment]
This error means that your HTML has instances of `{` or `}` that aren't used for template variables. This causes Gophish's template parser to break.

The solution is to check for and remove any instances of curly braces in your HTML (that you aren't using for template values).

Hope this helps!
