### ISSUE TITLE
Show campaign event timestamps with to-the-second accuracy

### ISSUE THREAD

**Issue by atropineal** [gophish/gophish#909]
This is an enhancement request.  At the moment to-the-second accuracy timestamps are stored, but to-the-minute accuracy is shown.

As a professional whitehat, I sometimes need to correlate events on other systems with events in gophish, and where two or more targets have performed actions within the same minute this needs extra log analysis to figure out who is who - a small extra step that could be removed by increasing displayed timestamp accuracy.

**Comment by jordan-wright** [comment]
Where are you wanting to see the per-second timestamps? Is this regarding the events when you expand a particular target in the campaign view?

**Comment by atropineal** [comment]
Yes, that's correct.

**Comment by jordan-wright** [comment]
This is fixed!

![image](https://user-images.githubusercontent.com/1317288/34911496-61c76620-f891-11e7-8f70-58fb0fd45b6a.png)

Let me know if you run into any issues.

**Comment by atropineal** [comment]
Thank you! :-)
