### ISSUE TITLE
Phishing email goes to spam folder

### ISSUE THREAD

**Issue by Piratebayy** [gophish/gophish#912]
Everytime I send a Phishing email it directly goes to the "Spam/Junk" folder, does anyone know how to fix this since I've everything settled up.

Kind regards!

**Comment by jordan-wright** [comment]
Thanks for reaching out!

I'm going to close this out since it doesn't follow our issue template and the issue regarding emails landing in spam has been discussed [many times in the past.](https://github.com/gophish/gophish/search?q=spam&type=Issues&utf8=%E2%9C%93).
