### ISSUE TITLE
Fix CSS For Campaign Datatable

### ISSUE THREAD

**Issue by jordan-wright** [gophish/gophish#92]
Looks like a change we made at some point messed up our campaign datatable:

![image](https://cloud.githubusercontent.com/assets/1317288/12472621/d348cd90-bfcf-11e5-8938-3d25f678dfbb.png)

Now the buttons are stacked when they should be side by side. I'll take a look at this tomorrow but might need your help, @StrangeUSB if you have time. You're the CSS guru :smile:

**Comment by jordan-wright** [comment]
Specifically, it looks like the ```th``` for that column is getting a small width applied to it:

![image](https://cloud.githubusercontent.com/assets/1317288/12472742/f0847930-bfd0-11e5-90e2-902dcd6051d9.png)

Removing the width fixes the issue as you can see.

**Comment by StrangeUSB** [comment]
Ignore that pull request, I didn't see you had committed a fix for this already.  I think that fix should be good.
