### ISSUE TITLE
Issue installing GOPHISH, cannot find package "context" in any of:

### ISSUE THREAD

**Issue by Piratebayy** [gophish/gophish#922]
I have some issues with installing GoPhish on my VPS, I have followed all the installation instructions but I still get some errors:

root@199335:~/go/src/github.com/gophish/gophish# go build
gophish.go:30:2: cannot find package "context" in any of:
/usr/lib/go/src/pkg/context (from $GOROOT)
/.go/src/context (from $GOPATH)
/.go/src/github.com/jordan-wright/email/email.go:18:2: cannot find package "mime /quotedprintable" in any of:
/usr/lib/go/src/pkg/mime/quotedprintable (from $GOROOT)
/.go/src/mime/quotedprintable (from $GOPATH)

I have already set a $GOPATH with the export command.

If someone could help me out with teamviewer or something Iw ill give him some BTC :)

**Comment by Piratebayy** [comment]
If someon could help me over skype add me: matfonn

**Comment by jordan-wright** [comment]
Are you sure you want to build from source? You might it easier to use a [pre-built](https://github.com/gophish/gophish/releases) binary.

Otherwise, assuming your Go environment is set up correctly, you should be able to navigate into the Gophish folder and run `go get -v ./...` to get the dependencies.

**Comment by shuheiktgw** [comment]
I actually encountered the same problem when I tried to build gophish from the source.
I solved the problem by installing all the related library manually from Github.

**Comment by Piratebayy** [comment]
Solved thanks!

Only thing that doesn't work right now is that the tracking of: Email Opend, Link opend, and submitted doesn't get tracked.

Even tho everything is filled in correctly, for some reason I am not sure if the email is correct setted up since it doesn't have a <title> </title> for some reason.

**Comment by jordan-wright** [comment]
There have been many other issues that talk about various reasons why tracking won't work, but it's almost certainly one of these two things:

- You aren't using the `{{.URL}}` template tag in the links in your email
- The URL you're using in your campaign is incorrect. It should point to your Gophish phish server interface (by default port 80 on your Gophish server's IP address).

I recommend reviewing [our documentation](https://gophish.gitbooks.io/user-guide/content/campaign/launching_the_campaign.html) for more information.

Let us know if you continue to run into issues!

**Comment by Piratebayy** [comment]
When I set the URL in campaign to my IP of VPS it sets my {{.URL}} towards that, so when I get the email and press on the URL it brings me to my VPS IP.

**Comment by jordan-wright** [comment]
And do you see your landing page when you click on the link?

**Comment by Piratebayy** [comment]
Yes it does give a sign when I have opend the mail and link, but I want it to direct it to my official Phishing site with a good domain, since this is just the domain of the VPS.

Can't you redirect it to a other domain?

**Comment by jordan-wright** [comment]
Whatever you put in the URL field for a campaign is what's put in the email. If you want that to point to a domain, you need that domain to resolve to your Gophish listener. That's not something Gophish controls- it's all DNS.

And I thought the issue was that you didn't see the events show up, but you're saying it _does_ show the opened email and clicked link events?

**Comment by jordan-wright** [comment]
Going ahead and closing this since the original issue was solved and there hasn't been any updates in over a week.
