### ISSUE TITLE
Error in Create a new Email Template

### ISSUE THREAD

**Issue by ygoncalves1999** [gophish/gophish#924]
i'm using version v0.3

I'm creating a new email template.
at the moment insert variable {{FirstName}} the system returned this message:
template: html_template:6: function "FirstName" not defined

Can someone help me?

**Comment by S0larflare** [comment]
You want to use {{.FirstName}} the . is important.

**Comment by ygoncalves1999** [comment]
Thanks!!! You helped me a lot :D 

XOXO

**Comment by jordan-wright** [comment]
As always, thanks for the great support @S0larflare!
