### ISSUE TITLE
Rate limit exceeded

### ISSUE THREAD

**Issue by JonKristinn** [gophish/gophish#927]
What version of Gophish are you using?: 0.4 Windows

Brief description of the issue: Error when trying to launch campaign

What are you expecting to see happen? : All emails going out as designed

What are you seeing happen? At first only a handful of emails went out. When I tried to send just to the emails that got an error message in the original campaign, I get this error:
 2018/01/12 14:53:04 main.go:740: sql/go/src/github.com/gophish/gophish/models/campaign.go:1441.0014msINSERT INTO "events" ("campaign_id","email","time","message","details") VALUES (?,?,?,?,?)[11 [email address removed by poster] 2018-01-12 14:53:04.5741467 +0000 UTC Error Sending Email {"error":"gomail: could not send email 1: 450 rate limit exceeded"}] 1

**Comment by JonKristinn** [comment]
I tried several times today and always got the same error message. Then after posting this, I tried again and of course it then worked. Am launching my campaign tomorrow and would very much like to know what the problem is if it happens again.

**Comment by jordan-wright** [comment]
Hi @JonKristinn, thanks for reaching out!

This is an error returned by the mail server. It means that emails are being sent too quickly (according to the server's standards).

The best recommendation at this point would be to build Gophish from source following the instructions in our documentation. We haven't made a binary release with the code yet, but the master branch contains a refactor of the way we send emails, including the ability to backoff and retry later in the cases just like this where we receive a temporary error from the server.

I hope this helps!

**Comment by JonKristinn** [comment]
Thank you @jordan-wright for this. The reason I chose the windows installer was because it was not as technical. Is there any way to limit the email send rate in the Windows version? I tried to go through the source installation but so far have been unsuccessful.

**Comment by jordan-wright** [comment]
I’m afraid it isn’t possible to patch this functionality into the binary release.

If your test can wait a week, I will probably release a new version of Gophish sometime this week. You could use those binaries to get that functionality.

**Comment by JonKristinn** [comment]
I can certainly wait a week. I was successful in sending 10 emails out today but the rest of the group returned an error. Thank you @jordan-wright

**Comment by jordan-wright** [comment]
Hey @JonKristinn, just a heads up we've released [version v0.5.0](https://github.com/gophish/gophish/releases/tag/v0.5.0), which should fix this issue for you 😄 

I'm going to go ahead and close this one out. Let me know if you run into any issues!
