### ISSUE TITLE
Change mouseover popup

### ISSUE THREAD

**Issue by bofhzen** [gophish/gophish#928]
Hi everyone,
I'm making a phishing campaign in my company and I have a question:
how can I change the display popup when the user mouse-over an image?
Now it shows my IP but I need to change it to for example "click here"

Thank you
Regards

**Comment by jordan-wright** [comment]
What do you mean the "display popup" Is this in an email template or a landing page?

**Comment by bofhzen** [comment]
Hi ! Is a email template. I mean when in the sended email when you mouseover a image, a floating text appears in my case with my gophish server ip address. I want to change this text with another one.  
Thank you and sorry for my bad html skills. 
Regards

**Comment by stracire** [comment]
one of the following 2 issues are going on:
- You have made a link of the image. I doubt this can be changed (since, inspecting the URL is an important way to detect phishing).
- You have to modify title="text" within the HTML tag, but this only works if the mailcliënt supports this HTML.

**Comment by bofhzen** [comment]
Thank you!
I will try and see what happen

**Comment by bofhzen** [comment]
Finally I found the solution.
In Email Templates-HTML-Source
double click in the links and change the link info

thank you!
