### ISSUE TITLE
Unable to reach landing page using public ip as URL.

### ISSUE THREAD

**Issue by jerempan** [gophish/gophish#931]
Hello everyone, 

What version of Gophish are you using?: Version 0.4

Brief description of the issue: Unable to reach landing page using public ip as URL.

What are you expecting to see happen? :there is a error when i click on the link.

What are you seeing happen

I want to make a campaign that will be intended for people outside my network, that's why when creating my campaign I use my public ip as a URL. The outside person receives the mail but landing page does not work. 

 Thanks a lot !

**Comment by jordan-wright** [comment]
Hey @jerempan, thanks for reaching out!

We'll need some more information to help troubleshoot this issue:

* What error do you receive when you click on the link?
* What do you see when you visit the IP address directly?
* Do you see any logs in the Gophish terminal when you visit the IP address?
* What is your phishing server config? Is it set to listen on all interfaces?
* Have you confirmed that there are no firewall rules in place preventing the connection?

**Comment by jerempan** [comment]
Thank you for your answer, I opened a port near my operator. Its solved . Once again, thank you.
