### ISSUE TITLE
More information is needed on campaign results

### ISSUE THREAD

**Issue by wifiuk** [gophish/gophish#94]
In the campaign results screen there needs to be more information.
When i send emails . if there is an error it just says error, i cant click on it for more info, i need to login to the console and see what the error is in the terminal.

And when someone clicks on something, i think there needs to be more info, like browser version, plugins java version check etc...

I seem to remember this being in the original spt application ,,,

**Comment by jordan-wright** [comment]
@wifiuk - totally agree. These are two separate things we want to accomplish:

* Better error messages (especially for things like sending emails). I think you'll really like how we accomplish this once it's released.
* Full browser/plugin detection - this is absolutely on our list of "todo", and it's pretty high up there. You will find some commented HTML where we started to do this before we got pulled away towards other issues. Just know that while it may not be in the first release it's on it's way very soon!

Thanks for the great suggestions!

**Comment by jordan-wright** [comment]
Hey @wifiuk - I've created two issues, #96 and #95 to handle these, so I'm going to go ahead and close this issue. Keep an eye on the other two issues for implementation status.

Thanks again for these suggestions - keep them coming! :smile:
