### ISSUE TITLE
Enhancement: Assign user permissions to security roles

### ISSUE THREAD

**Issue by hatsaresilly** [gophish/gophish#940]
In a corporate setting, it would be great to be able to create various roles for the gophish admin portal. Ideally I would be able to create a role and assign various permissions to it, then assign users one or more roles. For example, I'd like to create a Read Only role that has access to view campaign results, but nothing else. A Template Creator role, that can add email templates and landing pages, but not create campaigns.

With granular permission assignment I would be able to delegate responsibilities to different teams or people.

**Comment by jordan-wright** [comment]
Hi @hatsaresilly, thanks for this suggestion! Role-based access control has been proposed in the past in #891, #900, #469, and, to some extent, #10.

This would require a huge re-architecting of the way Gophish is structured, so at this time I don't plan to implement RBAC. I apologize for the inconvenience.

Thanks again for getting in touch!
