### ISSUE TITLE
Enhancement: SAML Authentication

### ISSUE THREAD

**Issue by hatsaresilly** [gophish/gophish#941]
In a corporate setting, it would be great to be able to implement SSO for gophish using SAML. This request would be especially useful if #940 is implemented. Then one could allow the SSO to automatically assign the user the proper permissions when they log in.

**Comment by jordan-wright** [comment]
Hi @hatsaresilly, thanks for reaching out!

This is definitely a feature that really only enterprises could make good use of. With the development required combined with the smaller audience it would help, I don't plan on adding SAML support at this time. With extremely limited development time, I try to maximize the number of people who will benefit from the new additions.

However, if a community member wishes to submit a pull request for the functionality, I'd be happy to review and consider merging!

Sorry for the inconvenience. Thanks again for the suggestion!
