### ISSUE TITLE
Restricting Access Globally

### ISSUE THREAD

**Issue by GregCFTS** [gophish/gophish#943]
Gophish Version 4

Is it possible to deactivate the web portal while the campaign is running, so if someone were to find it through the IP address, it would deny them access?

I know that it has a login, but this is for additional security measures.

Cheers,

**Comment by jordan-wright** [comment]
Thanks for reaching out! There's no way to immediately shutdown the admin panel while the campaign is running (without restart Gophish), but you can always just restrict the admin panel to connections from localhost. This is how it is by default.

If you're concerned with people hitting the admin panel, I'd suggest keeping it to localhost and using ssh tunneling to reach it externally as needed.

Hope this helps!

**Comment by jordan-wright** [comment]
Going ahead and closing this out since it appears the original question has been answered. @GregCFTS let me know if you have any other questions and we can always re-open if needed.

Thanks again for reaching out!

**Comment by GregCFTS** [comment]
Hi Jordan,

Thanks for the information.

This is being run on a Windows Server, which setting is it to block access apart from on localhost?

Cheers.
