### ISSUE TITLE
Can't Connect Via HTTP

### ISSUE THREAD

**Issue by davidfornesm** [gophish/gophish#944]
#### What version of Gophish are you using?: 0.4
Also, I have tested on the docker container by MatteoGgl.

#### Brief description of the issue: 
I must connect to the admin server via HTTPS in order to get a valid response. Instead of using HTTP as is noted on gophish/gophish just under **setup**.

#### What are you expecting to see happen? :
I would expect to get a valid response over http, just like this one:
![valr](https://user-images.githubusercontent.com/27923974/35472457-c5e24592-036f-11e8-8f20-e280ff416a61.PNG)

#### What are you seeing happen?:
Upon trying to connect to the gophish admin server in this manner:
```
http://my-machines'-ip:3333
```
I wont get back a valid response, thus:
![invr](https://user-images.githubusercontent.com/27923974/35472446-91656376-036f-11e8-9637-33c798e019ee.PNG)
**ERR_INVALID_HTTP_RESPONSE**

#### Please provide as many steps as you can to reproduce the problem:
 The problem can be simply solved by using HTTPS:
```
https://my-machines'-ip:3333
```
Instead of HTTP:
```
http://my-machines'-ip:3333
```
So, I suggest that the section under Setup:
![sc](https://user-images.githubusercontent.com/27923974/35472563-b596b932-0371-11e8-8206-0224e17cd9f3.PNG)
Is changed to look like this:
![sch](https://user-images.githubusercontent.com/27923974/35472586-12730340-0372-11e8-9dc3-27d4e67957b6.PNG)
Just to avoid giving anyone that has just started using it any headaches.

**Comment by jordan-wright** [comment]
Thanks! This has been updated at https://gophish.gitbooks.io/user-guide/content/getting_started.html.

**Comment by jordan-wright** [comment]
I've also updated the README 😄 Thanks again!

**Comment by davidfornesm** [comment]
You're good homie <3
