### ISSUE TITLE
Drip Sending

### ISSUE THREAD

**Issue by skim-milk** [gophish/gophish#945]
What version of Gophish are you using?:
Git Master

Brief description of the issue:
It's not always a good idea to send all emails at once, as co-workers ask each other about them, and if you want to do slow, targeted work, drip sending would be GREAT.

What are you expecting to see happen? :
- A timer control for sending delay between emails (much like the time selection currently used when setting up a campaign, but for hours/minutes).
- Or, even something where you set the start and end time of the campaign, and GoPhish calculates the delay for you (leaving leeway at the end of the campaign).

**Comment by thryb** [comment]
#611

**Comment by jordan-wright** [comment]
Hi @skim-milk! Thanks for reaching out.

As @thryb mentioned, this definitely appears to be covered in #611, so I'll close this one out so we can track the progress there.

That said, just know this is the most important thing I'm working on for Gophish right now, so it won't be long before this is added! 😄 Now that we've thoughtfully refactored the way we send emails, we absolutely have the capability to do things like add random sending delays or re-send specific emails manually.

Keep an eye out on #611 for updates, which should be coming soon! Thanks again for reaching out, and keep the great ideas coming!
