### ISSUE TITLE
Specify URL in Campaign (Port Issue)

### ISSUE THREAD

**Issue by SparksLegend** [gophish/gophish#949]
A Similar issue has been raised before, however my issue has got to do with the requirement to specify a port number when configuring the Campaign URL, i.e. I do not want port 80 to be my default port for the IP address specified. E.g, if my URL 1.2.3.4, I need my port to then be 8282. But specifying the URL as 1.2.3.4:8282 does not work. When the user clicks on the link in the phishing email, it then brings up a 404 error. If I leave out the port number from the URL field, the click then resolves and the user is directed to the landing page. How do I ensure that the redirect in GoPhish uses the port number specified?

**Comment by S0larflare** [comment]
I have done this with alternate ports in the past without issue (when I want to test something but have other things running, for example). Have you changed the port in your config.json as well as putting the port in your campaign URL?

Is there a reason you don't want port 80? It's a bit more 'phishy' if you see a port number in an IP address as most people wouldn't expect to see one.

**Comment by SparksLegend** [comment]
Changing the port number in the .json file worked! 
And agreed on the "more phishy" part, however I need to contain the redirects. I don't want people routing to me on port 80, thats the only reason :) Thanks!
