### ISSUE TITLE
Add Error Message for Failed Email

### ISSUE THREAD

**Issue by jordan-wright** [gophish/gophish#95]
Need to implement the ability to gather and store the exact reason (according to SMTP, at least) that sending an email failed. Probably want to store this in ```models.Result```.

**Comment by rfdevere** [comment]
Remove there error message 'EOF' from failed test email and replace with more suitable, I'm assuming this means end of file? Verbose output needed.

**Comment by jordan-wright** [comment]
Going ahead and closing this since error details were introduced via 12975bf0c30feef8c14ebdfa41fa9faddbb6f951

Here's an example:

![image](https://cloud.githubusercontent.com/assets/1317288/13037208/74744bb6-d341-11e5-9e47-a89827274f50.png)

As far as the EOF issue, we might need to open another issue to track that one specifically so we can get all the details such as when it shows up, etc.
