### ISSUE TITLE
Can't access web interface

### ISSUE THREAD

**Issue by tacobelldog52** [gophish/gophish#950]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
v0.4 ( 16.04.3 LTS Ubuntu hosted on Amazon AWS )

Brief description of the issue: 

Updated config.json
`{
        "admin_server" : {
                "listen_url" : "0.0.0.0:3333",
                "use_tls" : true,
                "cert_path" : "cert.pem",
                "key_path" : "privkey.pem"
        },
        "phish_server" : {
                "listen_url" : "0.0.0.0:443",
                "use_tls" : true,
                "cert_path" : "cert.pem",
                "key_path": "privkey.pem"
        },
        "db_name" : "sqlite3",
        "db_path" : "gophish.db",
        "migrations_prefix" : "db/db_"
}`

However when I go to  the public-IP:3333 from a web browser I get "The server unexpectedly dropped the connection"

What are you expecting to see happen? :

The initial welcome to go-phish/first login screen

What are you seeing happen?

Browser error

**Comment by jordan-wright** [comment]
Just to check, are you requesting the page over HTTPS? If you try HTTP, it won’t work.

Also, do you see any errors when starting Gophish?

**Comment by tacobelldog52** [comment]
Wow! your comment just made my *facepalm* expect HTTPS:// everything is right with the world.

You rock / sorry for the stupidity
