### ISSUE TITLE
(For the community) Phishing Template ideas

### ISSUE THREAD

**Issue by S0larflare** [gophish/gophish#951]
Hi guys,

So I've been getting a little stuck lately when trying to come up with new phishing ideas for my company, so I thought I would see whether the community could pool some ideas, I'm happy to share some of the types of campaigns I have done in the past.

_**Some ground rules**_ - please don't post template/html/code, this isn't meant as a way to share **templates** but to share some **ideas**. A screenshot might be useful if there is no better way to get across what you mean, but I would think this should be the exception, rather than the rule.

So, without further ado...

* Amazon - Quite a simple one (but in my opinion a good one) is an amazon confirmation email. Standard amazon confirmation emails don't have your name or anything personalised within it, so are easy to use for phishing education. On the other end I did a standard amazon login page. [Good in that it is universal - many people use amazon - though actual takeup is usually low on internal campaigns]

* Google Play - Similar to the amazon email, just a confirmation of a purchase without any personalisation which forwards through to a Google login page. [Again, most people have a Google account and pretty much everyone other than Apple users will use Google Play]

* Parcel delivery - I have done this with a couple of different couriers, essentially the emails are of the "You've missed a parcel, click here for more info/to rearrange collection or it will be sent back". I tend to only track clicks on these rather than submissions as there isn't any data that would be useful in the context. [Very good around the holidays, particularly in the lead up to Christmas]

* iTunes - Basically the Apple varient of the Google Play email, so not going to go in to detail.

* Facebook - This one is a password reset email using the {{.FirstName}} variable, the phishing link is on "If you didn't request a new password, let us know." and forwards on to a facebook login page.

* LinkedIn - The first one I ever did using GoPhish, was pretty successful at the time too. I sent it out in the wake of hysteria surrounding LinkedIn being breached, had a lot of clickers for that one. The email said that there was abnormal account activity and suggested they changed their password, the link went to a 'password reset' page - quite a few obliged!

* Parking - I set up an email purporting to be from a parking company talking about a parking fine. Laid it on quite thick with the whole "aknowledge this or we will go to court and it will cost more" sort of thing and got a erasonable response. The landing page had two forms on it, one to contest the fine and one to pay it. Interestingly most opted to try and pay the fine!

* Payroll - Simple and effective, an email from 'HR' from a different email (I try to make most of my phishes easy to spot or at least have a few telltale signs) talking about a pay review and linking to the latest update. This one was very effective - apparently people really want to know about their pay!

They are a few of mine anyway, I was wondering what other ideas people had had any any particularly successful campaigns there had 

**Jordan I can appreciate this isn't exactly an issue so if you don't want this to be here feel free to close it

**Comment by jordan-wright** [comment]
Thanks for posting this! I’ll drop some ideas in the next day or so, but engaging with this awesome community is a perfect use of the Issues, so no worries :)

**Comment by S0larflare** [comment]
I was hoping for a better response than this, got to admit :P

**Comment by altafk** [comment]
Hi,

First of all I would like to thank the creator of this awesome software Mr. Jordan for educating the users about phishing.

Regarding the ideas about email templates about phishing I would like to say that the sky is the limit and that depends on one's  creativity. 

Here are some of my idea about the phishing templates which I find to be effective. 

1) someone has your password - informing the user that someone has their password and in order to secure their password they need to login and secure their account. 

2) company survey - creating a fake survey page about the company and making the user login with their credentials to fill in the survey feedback.

3)  server maintenance activity


Regards, 

Altaf Khan

**Comment by hhpmgr** [comment]
Based on what I see people falling for the most reliably are minor variations on a theme:

- Someone has shared a document with you, visit the link to access your document. Leads to a dropbox rip-off and offers a number of different services to authenticate with, i.e. O365 email, gmail, dropbox, etc...
- Same as above but attach a PDF document that simply contains the link to be clicked on with some dropbox or adobe branding. Clicking the link takes through to the same landing page as above. Yes, people actually fall for this.

**Comment by snori74** [comment]
I run regular campaigns for our customers, where a "fail" is clicking any web link - so we go direct to a "educational" landing page telling them this. No classic phishing login, creds capture etc. 

What we concentrate on, and what consistantly catches 20%+ of staff are:

  * "Hey look at theses pics from the weekend!" - from somone they don't know with a supposed link to a photosharing site
  * "Sad story" - again from someone they don't know, linking apparnatlty to a news site

These are very simple emails, no elaborate imports

* LinkedIn invite  - ditto

**Comment by ioannoug** [comment]
These are some really excellent ideas everyone!

How about impersonating C-level staff to request various sorts of information? C-level contact details and personal information should be easy to find online (for the sake of realism).
Passwords, customer personal data, financial information (i.e. bank account balance) are some information that members of staff would willingly pass to upper management.

**Comment by jordan-wright** [comment]
Going ahead and closing this one since there have been awesome ideas, but no updates in over 2 weeks. If anyone lands here in the future - don't hesitate to add ideas below! 😄 

Thanks for starting this great discussion @S0larflare!
