### ISSUE TITLE
If subject = blank don't send "SUBJECT:" to SMTP server

### ISSUE THREAD

**Issue by p292** [gophish/gophish#955]
Not an issue but a small feature request.
If Subject is left blank in a campaign, could gophish omit sending "SUBJECT:" to the SMTP server?

What I think happens currently:
Subject set to blank in template, SMTP receives:
MAIL FROM: phisher@phish.com
RCPT TO: victim@victimcorp.com
DATA
TO: Firstname Lastname
FROM: Mr Phisher
SUBJECT:

Hello You Phished etc

Ideally if subject left blank it'd be nice if gophish could send server:
MAIL FROM: phisher@phish.com
RCPT TO: victim@victimcorp.com
DATA
TO: Firstname Lastname
FROM: Mr Phisher

Hello You Phished etc

Reason: Some companies add (OUTSIDE MAIL) to subject, if subject is not sent then this doesn't get appended.

Thanks

**Comment by jordan-wright** [comment]
Hi there! Thanks for reaching out. This seems reasonable and easy to implement. Looking through the RFC, I show the subject being an optional header, so it seems to make sense that if it isn't provided, we'll just exclude it entirely.

**Comment by truekonrads** [comment]
PR submitted
