### ISSUE TITLE
change status bar output

### ISSUE THREAD

**Issue by banryu07** [gophish/gophish#962]
Im going to start a phishing camping at my company but want to change the status bar output that is showing when the user put the mouse over the link. I just try this:

```
<a href="javascript:void(0)" onclick="location.href='http:\\www.google.com'">Link</a>
<a href="link" onmouseover="window.status='http://www.google.com/';return true;" onmouseout="window.status='';">Go To Google</a>
```

But didnt work

Thanks

**Comment by jordan-wright** [comment]
Hi @banryu07 - I've formatted your comment a bit to help make it more readable- I hope you don't mind.

Can you give some more information about what you're trying to do? What status bar output are you referring to? Is this a link in the email or a link on the landing page?

Also, just note that everything in Gophish in terms of receiving status updates relies on connections being made directly to Gophish. All the links in your example point to google.com, which would not hit Gophish and therefore not show status updates.

**Comment by jordan-wright** [comment]
Hi @banryu07 - I'm going to go ahead and close this out since there hasn't been a response in over a week. If you're still running into issues, please take a look at the questions given above and we can always re-open this issue.

Thanks for reaching out!
