### ISSUE TITLE
Landing page / link in email

### ISSUE THREAD

**Issue by tacobelldog52** [gophish/gophish#965]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
latest
Brief description of the issue: 
Setup everything however after launching a campaign when an email is opened it doesn't show up and the lading page linked in the email gets an " ERR_CONNECTION_REFUSED "

What are you expecting to see happen? :
Stats update upon opening and a landing page rendered

What are you seeing happen?
Error page

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

**Comment by jordan-wright** [comment]
> Setup everything however after launching a campaign when an email is opened it doesn't show up and the lading page linked in the email gets an " ERR_CONNECTION_REFUSED "

What are you using as the link in your email template? Are you using the `{{.URL}}` template variable?

If so, what are you using as the URL when creating a campaign? You'll want to make sure it's pointing to the Gophish phishing server/port and that it's accessible from the machine clicking the link.

To check that it's accessible, you can try visiting the IP address directly. If it works, you should see a generic 404 page. If that doesn't work, then it's possible there's a firewall or some other network issue preventing your from reaching the server.

**Comment by tacobelldog52** [comment]
I clicked the button to change out the links if that's what you mean. I did change the config to use port 443.  The links in the email look valid domain.com/jrs34.

Port:3333 I get the admin side of go phish
root of domain I get: ERR_CONNECTION_REFUSED
Port 443 I get:ERR_CONNECTION_REFUSED

Did I mess something up by changing port 80 to 443 in the config?

**Comment by tacobelldog52** [comment]
Went through my email template I have

<p class="p3"><a href="{{.URL}}">I acknowledge I have read the above statement</a></p>

**Comment by stracire** [comment]
Did you change 127.0.0.1 to your IP or domain?

443 is used for https, you have to configure the certificates correctly else Gophish won't even start. Be aware of SSL warnings if you use http:// images like above.

**Comment by tacobelldog52** [comment]
https://domain.com:3333/ gives me the admin page and is secure. My config.json file looks like this

`  GNU nano 2.5.3              File: config.json                                   

{
        "admin_server" : {
                "listen_url" : "0.0.0.0:3333",
                "use_tls" : true,
                "cert_path" : "cert.pem",
                "key_path" : "privkey.pem"
        },
        "phish_server" : {
                "listen_url" : "0.0.0.0:443",
                "use_tls" : true,
                "cert_path" : "cert.pem",
                "key_path": "privkey.pem"
        },
        "db_name" : "sqlite3",
        "db_path" : "gophish.db",
        "migrations_prefix" : "db/db_"
}`

**Comment by tacobelldog52** [comment]
Must have had an extra space or something in there. It appears to be working now after re-writing the config manually.

**Comment by jordan-wright** [comment]
Glad to hear you were able to get it working!
