### ISSUE TITLE
max connection attempts reached

### ISSUE THREAD

**Issue by mantis-le-sin** [gophish/gophish#972]
Hi guys,
I just installed gophish and when I created a sending profile, and I tried to send a test email I receive this error:  max connection attempts reached

This happens with different profiles, the error is triggered before any authentication.

Same output using a Ubuntu and Kali machines, different IP and location.

Thanks
mantis

**Comment by hummelm10** [comment]
This seems to be related to #963 which is being addressed.

**Comment by jordan-wright** [comment]
Yep! Going to go ahead and close this out in favor of #963. Thanks for letting us know about this!
