### ISSUE TITLE
Set listen url to existing webserver

### ISSUE THREAD

**Issue by Svanekongen** [gophish/gophish#974]
Hello,

Is it possible to set the listen_url to a exsiting webserver instead of gohpish' creating one?

-thanks

**Comment by rfdevere** [comment]
When launching a campaign, it asks you to input a domain, whatever you put in there it will create links in outbound emails containing that domain...

So when launching a campaign you insert 'company.com' all your links are going to be 'company.com/6dDjk3' the /6dDjk3 is the unique part of the link created so you can track individual users.

In answer to your question you could send the links in emails to anything you wanted but you'd need to have the corresponding landing page ready.... which is going to get crazy messy and you'd have to ask yourself why. Hope that helps and shout if i've misunderstood.

**Comment by Svanekongen** [comment]
I think i have descriped my question wrong.

i can't start the ./gophish because becuase port :80 is already in use, can i change the listen_url to another server?

**Comment by rfdevere** [comment]
fuser -k 80/tcp

^That will clear you port 80 on Linux, then restart it using the port 80 or modify config file.

**Comment by Svanekongen** [comment]
Cool, thanks! :-)
