### ISSUE TITLE
Email Template doesn't display correctly on Outlook

### ISSUE THREAD

**Issue by bennywolf1991** [gophish/gophish#975]
What version of Gophish are you using?: GoPhish 0.5.0

Hello, I tried to send an html email from GoPhish to myself.

In the email template screen, I get this to work:
![image](https://user-images.githubusercontent.com/36514658/36272364-57496f54-124f-11e8-997f-a6d0a4c2e727.png)

However when I receive the email it looks like this:
![image](https://user-images.githubusercontent.com/36514658/36272382-67c2173c-124f-11e8-9f2b-735f43b9eb01.png)

Here's my source code:
![image](https://user-images.githubusercontent.com/36514658/36272398-70e52480-124f-11e8-8b7f-138622ebf21b.png)

Please help,

I'm starting to work on a phishing training campaign for my company and trying to replicate as many phishing emails that we've received in the past as possible. However, the email doesn't display correctly when I receive it on Outlook. Can anyone help?

Thanks,

Best Regards,

**Comment by S0larflare** [comment]
Yes, I occasionally come across things like this with outlook. Apparently outlook is a pain with css standards and doesn’t always play ball. Usually for things like that I tend to make it in to an embedded image which has the hyperlink, sort of a flat button.

Sent from my iPhone

On 15 Feb 2018, at 17:57, bennywolf1991 <notifications@github.com<mailto:notifications@github.com>> wrote:


What version of Gophish are you using?: GoPhish 0.5.0

Hello, I tried to send an html email from GoPhish to myself.

In the email template screen, I get this to work:
[image]<https://user-images.githubusercontent.com/36514658/36272364-57496f54-124f-11e8-997f-a6d0a4c2e727.png>

However when I receive the email it looks like this:
[image]<https://user-images.githubusercontent.com/36514658/36272382-67c2173c-124f-11e8-9f2b-735f43b9eb01.png>

Here's my source code:
[image]<https://user-images.githubusercontent.com/36514658/36272398-70e52480-124f-11e8-8b7f-138622ebf21b.png>

Please help,

I'm starting to work on a phishing training campaign for my company and trying to replicate as many phishing emails that we've received in the past as possible. However, the email doesn't display correctly when I receive it on Outlook. Can anyone help?

Thanks,

Best Regards,

**Comment by bennywolf1991** [comment]
Hello,

I've found out the issue. I replaced the href with {{.URL}} and set that URL to the webpage I want to direct to then change **button** to **a**. For some reasons Outlook doesn't understand the <button> tag.

**Comment by bennywolf1991** [comment]
So apparently this works

![image](https://user-images.githubusercontent.com/36514658/36313797-c8a16b82-1300-11e8-8cd0-128e094c034e.png)

![image](https://user-images.githubusercontent.com/36514658/36313862-09848b3e-1301-11e8-84e6-12654965952a.png)

So apparently Outlook can display the <a> tag (Although not correctly) but doesn't understand the <button> tag. Is this because of html version conflict?

**Comment by jordan-wright** [comment]
Unfortunately, mail clients like Outlook all have their own sets of HTML/CSS that they support. Outlook is notoriously tricky to work with.

This is why there's an entire industry around generating nice, marketing emails since it's really, really tricky to make an email that looks right on all clients. 😄 This is what makes Gophish's "import email" feature so powerful, since we can just import emails that have been created by other people.

Since there isn't really anything we can do on the Gophish side of things to fix this, I'm going to go ahead and close this out. Thanks for reaching out @bennywolf1991 and don't hesitate to let us know if you continue to run into issues!
