### ISSUE TITLE
User-reporting of phishing emails

### ISSUE THREAD

**Issue by S0larflare** [gophish/gophish#976]
So something I have been thinking about lately is reporting phishing emails. In my workplace we use Outlook, so I have made/modified an add-in to report emails when they are phishing/spam and to report them differently if they are one of my awareness campaigns. Collating this is a bit of a manual process and means me exporting data to a csv and then correlating it with the GoPhish data. Not difficult, but boring and a bit inefficient. So I had a thought, EMAIL_OPENED is triggered by a user visiting /track?rid=xxxxx, why can't we use a similar method for reporting and feed the data back in to GoPhish for use as a unified platform? So I have made a bit of a basic start, mostly reusing the code for /track and I have got it to update if a web request is made to /report?rid=xxxxx:

![image](https://user-images.githubusercontent.com/8939757/36678289-3fe13394-1b08-11e8-9134-ffb068f1034b.png)

Please excuse the terrible formatting (haven't bothered to make it sit nicely) and excuse the weird stats, I sort of broke that when I was fiddling with things

![image](https://user-images.githubusercontent.com/8939757/36678360-6df20f4c-1b08-11e8-81f0-9e2196eac739.png)

Anyway, it sort of works. But in trying to find out how to change the colour of 'Email Reported' in that second screenshot (I cannot for the life of me find where the colours are defined for that, for some reason it uses the email opened colour) I thought that really 'Reported' shouldn't be a status but a separate yes/no flag.

So I can definitely see the value of this (properly done, of course) to others, but it would require a 3rd party way of reporting the email (which would either be down to the individual companies to sort from scratch or other applications built to leverage this - e.g. I could release what I use at some point down the line). However this would make the entire module require a reasonable amount of work to get it off the ground, which is sort of entirely against the principle of GoPhish being a one click set up and go... Would you be able to give me your thoughts on this?

**Comment by rfdevere** [comment]
I know I was asked for this exact requirement today. It would be the best mod I could wish for. 

People focus on the click stat all the time but for me reported is the most important stat. 

The difference in Sent/Opened can tell you a lot about the technical defences of an organisation. 
The difference Opened/Clicked can you tell you about the culture and the risk in the org.
But by far the best is Opened/Reported as this means you can monitor education and progress.

You approach a board with "20% of users are clicking" its chaos, but spin that to "over the past 3 months our reporting rate is up X amount"

**Comment by jordan-wright** [comment]
Hey everyone,

Thanks for sending this over @S0larflare! Email reporting is indeed the other half of a phishing test. I completely agree with both yourself and @rfdevere that the reporting metric is, to me, just as important if not more important than who clicked.

Now, in terms of implementation, we have a few options. We would want to:

* Create the clients companies could use (like the Outlook extension you wrote or the [IsThisLegit](https://github.com/duo-labs/isthislegit/) Gmail button I wrote for my employer (shoutout to Duo for making that possible!)). Ideally, the clients are easy to set up and have a consistent interface for sending reports to Gophish.
* Write the API endpoint Gophish uses to report phishing emails. Seems to me to be as simple as `/report?rid=xxxxxx`.
* Build the logic for handling the "report" action (adding an event, changing the status, etc.). Seems like you've done a lot of that already.
* Figure out how to display it to the admin.

If you want to make a pull req to get the ball rolling, we can work together to make this happen. 😄 

Thanks as always for all y'all do and for the great discussion!

**Comment by S0larflare** [comment]
Ok so I’ve managed to put a bit of time into this today and ive got it pretty much working as intended now. Rather than updating the status there is now a boolean ‘reported’ field which gets updated. Just got to clean things up a little and fix the pie charts that I broke. Should be able to send a pull request some time next week

**Comment by S0larflare** [comment]
Almost done. I have fed the stats to the dashboard page, which I think is looking good:

![image](https://user-images.githubusercontent.com/8939757/36677942-63078b58-1b07-11e8-87a5-1fee70a33fe4.png)


I chose a light blue (and a nifty megaphone symbol) for the reporting stuff, but would be open to changing it. I just need to update the pie chart on the campaign results page. Not managed to get that one done cleanly. I might make the pull request and leave that one to you if you don't mind @jordan-wright as you might want to clean up and re-architect what I've done anyway :smile:

**Comment by rfdevere** [comment]
@S0larflair not all heros where capes... this is amazing stuff.

**Comment by jordan-wright** [comment]
@S0larflare that looks awesome!!

Definitely don't hesitate to drop a pull req whenever you're ready. More than happy to help you get this over the finish line.

Thanks so much for all your continued work on this.

**Comment by aaniceto** [comment]
Don't forget about #911.. /report?_models.RecipientParameter_=XXXXX

**Comment by S0larflare** [comment]
I've put a pull request in for this. Will need a little bit of tidying up but should work for what we want :smile:.

I haven't made this compatible with #911 @aaniceto but that's mainly as I started this before that change and I didn't want to break my work to make it compatible (a.k.a. I am a lazy little thing). It should just be a case of changing a couple of lines though, so isn't a biggie.

**Comment by jordan-wright** [comment]
This has been merged in #1014! Thanks again to @S0larflare for the initial pull request.

Next, we need to find clients that will work with this, since there will inevitably be support requests asking how to report emails. I'll see if I can find time to merge something into the [IsThisLegit](https://github.com/duo-labs/isthislegit/) extension, but it might be a while. @S0larflare or @rfdevere - do y'all have any other client recommendations we could try and make work with this functionality?

Going ahead and closing this since the actual functionality in Gophish has been added, but we can continue discussing here 😄

**Comment by matosha** [comment]
Hey all, just an implementation thing i do.
Inside the email, i include a "Report Phishing" hyper link with :
http://website.com/static/report.html?rid={{.RId}}

In the static folder i have a report.html that renders a trophy site, "Thanks for identifying the phishing!" or whatever. Inside that html i have an ajax call that does a request to "/report?rid=asdasd". This pulls the rid parameter and essentially replays it in the background.

**Comment by FortWIT** [comment]
If you aren't looking to do anything fancy other than get the report counter to increment on the dashboard for a user who correctly reported the email as a phising attempt, you can put a URL into your email template like this:

To report this email as spam or phishing click the link below:
http://phish_server/report?rid={{.RId}}

The user won't see anything happen on their end, the webpage just closes itself but the reporting option will be properly tracked for the user.  This has been tested and verified to work in version 7.1 of GoPhish.

**Comment by mrbangus** [comment]
@FortWIT - That would kind of give it away that it was a phishing campaign don't you think?

**Comment by FortWIT** [comment]
That depends on how savvy are your end users? The link wouldn't actually be "phish_server" if that's what your concerned with?  "phish_server" is just a place holder for the name and/or IP of your actual machine running the GoPhish software.  You can create a DNS alias to have the GoPhish server be called anything you want inside your organization.

**Comment by mrbangus** [comment]
Might be able to pull it off once...  But, because all the other emails they get that wouldn't have that link, they would catch on to it quick.

**Comment by mrbangus** [comment]
@FortWIT - I've actually implemented a different solution.  I edited the campaign_results.html file. arrowed down beneath the User Guide and API Documentation lines and added this code:
`<li>
<br /><br />
<ul>
<b>Email Reported</b>
<form action="http://phish (this will be whatever you name your server)/report?rid=" method="GET">
<input type="text" id="rid" name="rid" placeholder="XXX" />
<button type="submit" id="submit">Submit</button>
</form>
</ul>
<br />
<center>Please enter the RID Number for the user </center>
</li>`

This creates a text field with a submit button.
We've set up a spiceworks ticketing system and an email called suspicious@my company.com.  When someone gets a phishing email, we have them forward it to the suspicious address and it creates a ticket in spiceworks, which in return notifies me.  I evaluate the suspicious email and let the user know if it's legitimate or not.  If it's one that I sent out, I go into the gophish compaign, get the users id and paste it into the text box I created above and hit the submit button.  That way, it's reported and the user has no idea if it's my phishing campaign or a real phishing email.

**Comment by FortWIT** [comment]
@mrbangus Thanks for the code.  I like they way you've implemented keeping the reporting piece hidden from the end user so they don't get suspicious over the report link being in the actual campaign email.

**Comment by theashishchalke** [comment]
I wrote this Python script as an options for admins who can report on behalf of the user. Flow usecase as below:

1. User detects suspicious message and FORWARDs to admin email.
2. Admin verifies success. Copies the Users email address.
3. Runs the Python script to report to gophish that user has reported message.

**Disclaimer**: I'm still a newbie to python _and programming_ in general. Most of this was compiled in an intense day of reading the api documentation, googling and persistence. It may lack things like input validation, failure cases.  My original idea was to get it working. Improving it would be the next step. 

The script runs in the below fashion:

1. Pulls a list of all available campaigns and displays them in the campaign id.
2. **Asks** the admin for the campaign name to pull the RID. (Could have gone campaign ID way too)
3. Admin enters campaign ID.
4. Script uses the entered Campaign ID to pull JSON data via the RESTAPI
5. The Results section is parsed to a dictionary with UserEmail : RID format.
6. **Asks** the admin for the Users email address for whom Email Reporting has to be done.
7. Admin enters the email address.
8. Script pulls the RID against the email address and stores in a variable.
9. **Asks** the admin whether they want to Report - Y or N
10. If Y, Constructs the report URL with the RID fetched earlier and makes request. If N, exits.


If you need to use it in your environment, modify the below variables:
api_key = YOUR API KEY HERE
host = Gophish admin url
url = gophish admin url
campaignurl = The Campaigns URL #All my Campaigns have the same URL. If yours has a different one, it could be retrieved via the api or user supplied input.

![Report-email](https://user-images.githubusercontent.com/40175903/67007513-34887780-f105-11e9-8ac0-910e63cffc21.gif)


[report-email.txt](https://github.com/gophish/gophish/files/3739061/report-email.txt)

**Comment by adrianomarcmont** [comment]
Hi.
Based on response of @FortWIT, I wrote the javascript code below that dynamically query API when user is viewing a campaign and then update the action form of "reported phishing form" with the URL campaign. I hope this code will be improved by the community.

Edit templates/campaign_results.html and add the HTML. In the end of the template add the javascript.

**How to use**
Query the user in the table result, expand details, get the Rid, paste into form, click Add and then in the top o page click Refresh button

**HTML CODE**
```
<div class="row">
	<center>
	<b>Add Reported Phishing</b>
		<form id="ReportedPhishingForm" action="" method="GET">
			<input type="text" id="rid" name="rid" placeholder="Rid">
			<button type="submit" id="submit">Add</button>
		</form>
		Enter the rid of the user who reported Phishing
	</center> 
</div>
```

**JAVASCRIPT CODE**
```
<script>
var MyAPIKey = getAPIKey();
var currentGoPhishAdminURL = document.location.href;
var goPhishAdminURLCampaigns = currentGoPhishAdminURL.includes(document.location.origin+"/campaigns/");
var xmlhttp = new XMLHttpRequest();
xmlhttp.onreadystatechange = function() {
  if (this.readyState == 4 && this.status == 200) {
    var apiJSONResponse = JSON.parse(this.responseText);
	for(var i = 0; i < apiJSONResponse.length; i++) {
		if(goPhishAdminURLCampaigns=true){
			var campaignID = currentGoPhishAdminURL.split('/').pop();
			if(apiJSONResponse[i].id==campaignID){
				var campaignURL = apiJSONResponse[i].url;
				var reportedPhishingURL = campaignURL+"report?rid=";
				document.getElementById("ReportedPhishingForm").action = reportedPhishingURL;
			}
		}
	}
  }
};
xmlhttp.open("GET", "/api/campaigns/?api_key="+MyAPIKey, true);
xmlhttp.send();

function getAPIKey(){
	var xmlhttp = new XMLHttpRequest();
	xmlhttp.onreadystatechange = function() {
	  if (this.readyState == 4 && this.status == 200) {
		var pageResponse = this.responseText;
		var parser = new DOMParser();
		var parsedHtml = parser.parseFromString(pageResponse, 'text/html');
		var APIkeyValue = parsedHtml.scripts[0].innerText.split(":")[1].split("\"")[1];
		sessionStorage.setItem("MyAPIKey", APIkeyValue);
	  }
	};
	xmlhttp.open("GET", document.location.origin+"/settings", true);
	xmlhttp.send();
	var MyAPIKey = sessionStorage.getItem("MyAPIKey");
	return MyAPIKey;
}
</script>
```
