### ISSUE TITLE
Support: How do I get the mail sent to show name/not email

### ISSUE THREAD

**Issue by raviadds** [gophish/gophish#979]
Version of GoPhish: 0.5.0

Description: How can i get gmail or any other receiver to see the name of the sender and not the email of the sender.

What are you seeing happen?
I currently see just the name@domain.com when receive an email. I would like the email to show First Name, Last Name when it is received.

**Comment by jordan-wright** [comment]
To get the "First Last <firstlast@domain.com>" syntax to show up, you need to specify your "From" address in that format.

However, Gmail is special in that if you try to spoof that information (specifically the email address) they show your actual Gmail address in the inbox (if you authenticated to their SMTP service). This is almost certainly to prevent spoofing, which is a good thing! However, this means that there isn't a good way to change this within Gophish. You might be able to change the name, but not the email address.
