### ISSUE TITLE
Redirect and login at original site

### ISSUE THREAD

**Issue by androidisking** [gophish/gophish#980]
I am using the latest Gophish build from source on 20 Feb 2018.

I set up a testing campaign for our client and would like to redirect victims to the original website and login with the credentials they entered.

Using Linkedin as an example, I set up the landing page by importing from [https://www.linkedin.com](url)

Then I checked "Capture Submitted Data" and "Capture password"
The redirect url is set to [https://www.linkedin.com/uas/login-submit](url)

The redirect worked but I get this:

<img width="886" alt="screen shot 2018-02-21 at 11 50 08" src="https://user-images.githubusercontent.com/36696403/36476198-74a814bc-16fd-11e8-8b1f-ec9e2aa05c14.png">

Is there a way to get this to work?

**Comment by S0larflare** [comment]
How would this be useful as part of a test?

Linked in likely have protections in place to stop this

Sent from my iPhone

On 21 Feb 2018, at 10:53, androidisking <notifications@github.com<mailto:notifications@github.com>> wrote:


I am using the latest Gophish build from source on 20 Feb 2018.

I set up a testing campaign for our client and would like to redirect victims to the original website and login with the credentials they entered.

Using Linkedin as an example, I set up the landing page by importing from https://www.linkedin.com<url>

Then I checked "Capture Submitted Data" and "Capture password"
The redirect url is set to https://www.linkedin.com/uas/login-submit<url>

The redirect work but I get this:

[screen shot 2018-02-21 at 11 50 08]<https://user-images.githubusercontent.com/36696403/36476198-74a814bc-16fd-11e8-8b1f-ec9e2aa05c14.png>

Is there a way to get this to work?

**Comment by jordan-wright** [comment]
> So am I right to say that the redirection does not support submitting credentials to the original website?

This is correct and is due to how HTTP operates. Anytime a 302 is received after a POST, the next request is always a GET.

At this time, Gophish does not support automatically replaying captured credentials.
