### ISSUE TITLE
404 page over rides landing page

### ISSUE THREAD

**Issue by infosecwriter** [gophish/gophish#981]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: .5

Brief description of the issue: Landing page give a 404
404 page not found
<html><head>
	<title>Creds grabber</title>
</head>
<body>
<p>Chris 

What are you expecting to see happen? : the form code in the landing page template

What are you seeing happen? http://.../?rid=????? is a 404 page

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
email
<p><a href="{{.URL}}">This is a link to the landing page</a></p>

landing page
<html><head>
	<title>Creds grabber</title>
</head>
<body>
<p>{{.FirstName}} {{.LastName}} Your email {{.Email}} needs to be verified. please log in.</p>

<form accept-charset="utf-8" action="" method="post" name="login"><label for="Email">Email</label> <input name="Email" placeholder="@target" required=""/> <label for="password">Password</label> <input name="password" placeholder="password" required="" type="password"/> <input type="submit" value="Login"/> </form>

<p>If you feel you received this in error, please <a href="http://{{.URL}}">contact us.</a></p>

<p> </p>
<p>{{.Tracker}}</p>
</body></html>
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - click on the {{.URL}}
 * Step 2 - get 404 error and see the html code

**Comment by jordan-wright** [comment]
> Step 2 - get 404 error and see the html code

I'm not sure what's happening here. You say you're seeing a 404, but then you say you see the HTML? What does the 404 page look like? Also, what does it look like if you hit the URL directly without the `rid` parameter?

The email template looks correct, so my initial assumption is that you have another web server already listening on your phishing port. So when you make the request, it's getting picked up by that server instead of Gophish.

**Comment by jordan-wright** [comment]
Going ahead and closing this since there haven't been any updates in nearly a week. @infosecwriter if you're still running into issues, don't hesitate to let me know and I'll be more than happy to re-open this.
