### ISSUE TITLE
Cannot Monitor Email Opened, Clicked Linked and Submitted Data

### ISSUE THREAD

**Issue by Evekilel** [gophish/gophish#982]
I am using Gophish v0.5.0

I cannot successfully monitor emails opened, clicked link and submitted data.

I have successfully hosted the gophish server on the digital ocean.  I am not sure where the server should sit, to successfully monitor the phishing campaign.
I'm expecting it to monitor all the 4 items, email sent, opened, clicked link and submitted data

What are you seeing happen?
![img-20180220-wa0021](https://user-images.githubusercontent.com/8880955/36596331-71bb0cea-18b6-11e8-8d08-94449cd3b68b.jpg)
![gophish](https://user-images.githubusercontent.com/8880955/36595631-f5794b62-18b3-11e8-87a3-b867bff8b732.PNG)

**Comment by jordan-wright** [comment]
Can you provide the template you're using?

**Comment by Evekilel** [comment]
![gophish](https://user-images.githubusercontent.com/8880955/36626257-a6839eee-1940-11e8-86aa-1d3091d83cf4.png)

**Comment by Evekilel** [comment]
I needed to set a custom web page

**Comment by jordan-wright** [comment]
You need to make sure your links use the {{.URL}} template tag. That way the links are set up correctly.

Hope this helps!

**Comment by Evekilel** [comment]
Let me try that, I will update once successful

**Comment by Evekilel** [comment]
![image](https://user-images.githubusercontent.com/8880955/36643460-aff54ff0-1a5c-11e8-9b98-7cfca9141bf7.png)
I'm getting the error above

**Comment by jordan-wright** [comment]
It looks like during the process of creating the template (either copy/pasting or importing), a Unicode character that isn’t supported was inserted. You’ll need to find that character in the HTML and remove it.

**Comment by Evekilel** [comment]
Hi jordan,
Is the setting below accurate
![image](https://user-images.githubusercontent.com/8880955/36644216-f7382738-1a67-11e8-9e9a-58a2ea1f48ca.png)

<p>Kindly <a href="https://{{.URL}}">login here </a>(click on the hyperlink) to ensure upgrade of your email account as soon as you can, so that you do not experience service disruption during this period.</p>

Still gives me the error described above and therefore cannot successfully track it.

**Comment by S0larflare** [comment]
I find you are best off changing it to other rather than http/https when you’re using {{.URL}}

Could you post the template code if you’re still having problems?

Sent from my iPhone

On 25 Feb 2018, at 17:11, @evey_kilel <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi jordan,
Is the setting below accurate
[image]<https://user-images.githubusercontent.com/8880955/36644216-f7382738-1a67-11e8-9e9a-58a2ea1f48ca.png>

Kindly login here <https://{{.URL}}> (click on the hyperlink) to ensure upgrade of your email account as soon as you can, so that you do not experience service disruption during this period.

Still gives me the error described above and therefore cannot successfully track it.

**Comment by Evekilel** [comment]
![image](https://user-images.githubusercontent.com/8880955/36644432-88d86ccc-1a6b-11e8-9f39-42aa059e663e.png)

**Comment by jordan-wright** [comment]
That looks like it should work. Are you still running into issues with that?

**Comment by Evekilel** [comment]
Hi Jordan,

It didn't work,

**Comment by jordan-wright** [comment]
@Evekilel I'm afraid I can't help if I don't have any new information to work off of. When you say "It didn't work", what do you mean? What did you try, what did you see, etc. Screenshots, logs, etc. are all helpful.

I'm afraid until we have more information there just isn't any way for us to move forward troubleshooting.

**Comment by jordan-wright** [comment]
Closing this since there hasn't been any updates in a couple of weeks. @Evekilel if you're still running into issues, please take a look at the comment above as to some information that could help us troubleshoot and we can always re-open the issue.

Thanks again for getting in touch!
