### ISSUE TITLE
Installing on a VPS?

### ISSUE THREAD

**Issue by mettix** [gophish/gophish#983]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
Not using yet

Brief description of the issue: 
I wanted to know if I can install this on a VPS (running Virtualmin on Ubuntu. If yes how would you do this? 

Thanks in advance

**Comment by jordan-wright** [comment]
Hey there! Thanks for reaching out.

I highly recommend you review our [excellent documentation](https://getgophish.com/documentation/). I don't know about Virtualmin, but Gophish is easily installed on Ubuntu using one of our pre-built binaries.

If, after reading the documentation, you have any specific questions, don't hesitate to reach out!
