### ISSUE TITLE
Attachment Tracking/Invisible Tracking

### ISSUE THREAD

**Issue by GregCFTS** [gophish/gophish#984]
Hi,

Not sure if I'm posting this in the right place. Running GoPhishV5

I was wondering if there's a way to have attachments like a script file to open the landing page and track which user has downloaded the attached file?

Also, is there a way to hide the tracking image?

Cheers,

Greg

**Comment by S0larflare** [comment]
Attachment tracking isn’t really implemented in Gophish, there is an old branch that you might be able to use, but it’s white a way behind the current build. 

The 1x1 pixel image for tracking should be invisible, do you mean is there a way to not include it but still track emails being opened?

**Comment by GregCFTS** [comment]
Hi @S0larflare 

Thanks for letting me know.

Yes, the image is invisible, but  only when the images are downloaded. I guess because of this, there is no way to properly hide it.

Cheers.

**Comment by S0larflare** [comment]
Not as such, no. That said, you can probably make it auto-download. Are you using Outlook by any chance as that tends to block auto-download of pictures by default. If you are able to add the domain into the safe senders list, it shouldn't get blocked.

**Comment by GregCFTS** [comment]
Hi @S0larflare 

Yes, I am using Outlook. If I just add the domain to the sender list, that will resolve the issue?

Cheers.

**Comment by S0larflare** [comment]
Should do. Outlook is a bit of a pain in the way it evaluates it, so you have to put "@fakedomain.com" into the safe senders, then anything you receive which says it is from fakedomain.com should auto download the pictures. Stupidly, this means that if I trust github, for example, and someone spoofs a github address (let's assume SPF, DKIM, DMARC etc aren't being checked on your mailserver so it doesn't get blocked) then it will allow it. I'd prefer it if I could whitelist my gophish server, but unfortunately I can't, so you would have to add any and every phishing address you create in the sending profile to your safe senders and push it out via GPO.

**Comment by GregCFTS** [comment]
Makes sense, I guess to make it a realistic phishing scenario, it's better to not have it enabled by default, unless it's spoofing a common site that most people would have auto-download enabled by default, e.g. Amazon or whatever. 

Cheers.

**Comment by ShivaPoola143** [comment]
Anybody help...!! How track the attachment like whos open or downloaded and there is any possibility to capture that info.
