### ISSUE TITLE
Multi page landing page

### ISSUE THREAD

**Issue by horllste** [gophish/gophish#988]
Am not reporting a issue, i just wish someone could guide me or help with a little write-up on how to build multi-page landing page that will work on gophish.
for example a landing page that will request for email or username on a page and request for password on another page.
thanks

**Comment by jordan-wright** [comment]
Hi @horllste - thanks for reaching out!

Unfortunately, multi-page landing pages are not supported by Gophish at this time. Eventually I'll have time to work on the new campaign creator shown in #223 which should take care of this, but I don't have a timeline on this yet.

Thanks again for getting in touch!

**Comment by stefankahn** [comment]
Hi @jordan-wright 
Did you make any progress on this?

**Comment by pkyria14** [comment]
hello do we have any news about this?
