### ISSUE TITLE
Tracking Not Working?? Trying to implement phishing training offsite (across Internet), 

### ISSUE THREAD

**Issue by esvevan** [gophish/gophish#992]
What version of Gophish are you using?:   V0.5.0 linux x64

Brief description of the issue: I have Gophish up and running on a t.2micro Ubuntu instance on AWS.  Everything is working fine, so it would seem.  Emails send fine, links function correctly in emails ETC.  Problem I am running into is that none of the tracking features are working.  Gophish will not register opens, clicks, etc.  I do have the tracking option selected.  What am I doing wrong?

What are you expecting to see happen? :  Tracking to work while sending emails to an external IP

What are you seeing happen?  The tracker is falling within the /body and /html tags within my email template.  This seems like a possible issue.

**Comment by jordan-wright** [comment]
Hi @esvevan, thanks for reaching out.

> links function correctly in emails ETC. 

What do you mean by this?

What does your template look like? What are you using as the "URL" when making a campaign? What do you see when you click the link in the email (a screenshot would be preferred).

**Comment by esvevan** [comment]
So upon testing today, the landing page times out and lists the public IP address of my AWS instance as saying it xxx.xxx.xxx.xxx took too long to respond.  This makes me think there is a setting or possible firewall issue with my AWS instance I have yet to address.  

The template is from a mailchimp template that I emailed to myself then copied the raw data into gophish, 
The URL I am using is the public IP address of the AWS instance
<img width="907" alt="github screenshot" src="https://user-images.githubusercontent.com/17433749/36949965-63406488-1fac-11e8-82c5-10364c5c2476.PNG">
