### ISSUE TITLE
Invalid Username/Password - Don't remember changing from the default username/Password

### ISSUE THREAD

**Issue by Paddyk3ll3h3r** [gophish/gophish#994]

**Comment by S0larflare** [comment]
Well, you probably should change from the default, but if you have forgotten what you've changed it to you could go in to the database and change it directly. In SQLite3/MySQL look for the Users table

Username: "admin"
Password Hash: "$2a$10$IYkPp0.QsM81lYYPrQx6W.U6oQGw7wMpozrKhKAHUBVL4mkm/EvAS", //gophish

**Comment by Paddyk3ll3h3r** [comment]
![database](https://user-images.githubusercontent.com/32489324/37095543-2263999e-220e-11e8-85bb-d8b2f05d4b0e.JPG)
Im guessing this is where i need to make the change?

**Comment by S0larflare** [comment]
Yeah, that looks right. Check the username and change the hash to that above. That should change the paasword back to the default gophish. I would update it after logging in though.

**Comment by Paddyk3ll3h3r** [comment]
Having no luck with that. I installed Sqlite and i think that may have updated all sqlite files in my gophish folder and changed the password. Im working on a college assignment with a deadline and fear I havr lost all my campaigns.. Whats the hostname for the database?

**Comment by mcvic1rj** [comment]
Are you sure you are using the SQLite Db or are you using the MySql DB?
It will be this line and one below it in your config file. https://github.com/gophish/gophish/blob/c9ff8714a0beda15b985a5d0061df3bcbc2f8f9d/config.json#L14

**Comment by S0larflare** [comment]
You definitely haven't got more than one environment and are getting confused or something? Are you using MySQL or SQLite?

The database is by default gophish.db.

**Comment by Paddyk3ll3h3r** [comment]
![database](https://user-images.githubusercontent.com/32489324/37099698-ea2698aa-2218-11e8-9262-9c820b89699e.JPG)
this is the config file

**Comment by Paddyk3ll3h3r** [comment]
@S0larflare I installed Sqlite

**Comment by S0larflare** [comment]
type sqlite3, then 

`attach "gophish.db" as db1;`

then 

`.headers ON`

then

`select * from users`

Is your admin user in there?

**Comment by Paddyk3ll3h3r** [comment]
Sorry for the silly questions but is this supposed to be done from here? 
![database](https://user-images.githubusercontent.com/32489324/37100616-56aee02a-221b-11e8-81b5-072f279548c2.JPG)

**Comment by Paddyk3ll3h3r** [comment]
if i installed teamviewer would it be possible for you to have a look? i would really appreciate it

**Comment by S0larflare** [comment]
Yes, sorry. From the cmd window, navigate to your gophish directory (so that your database file is right there and you don't need to provide a path to it) and then run the above

**Comment by Paddyk3ll3h3r** [comment]
![database](https://user-images.githubusercontent.com/32489324/37102079-ec2fec72-221e-11e8-9ffa-a52c1be4ef0b.JPG)
Sqlite3 doesn't run

**Comment by MccoyTesting** [comment]
@S0larflare bro please can you email here testinglab66@Gmail.com 

I'm having same problem but I'm yet to figure it all out! How do I go about this when it's running on a vps?

**Comment by MccoyTesting** [comment]
> Are you sure you are using the SQLite Db or are you using the MySql DB?
> It will be this line and one below it in your config file.
> 
> https://github.com/gophish/gophish/blob/c9ff8714a0beda15b985a5d0061df3bcbc2f8f9d/config.json#L14
> 
> https://github.com/gophish/gophish/blob/c9ff8714a0beda15b985a5d0061df3bcbc2f8f9d/config.json#L15

Pleas would Making this changes to the config.json fix this up on gophish running on vps?

**Comment by S0larflare** [comment]
GoPhish doesn’t have a default password anymore, it gets generated the first time you run it and is shown in the console

**Comment by akakitten** [comment]
> 
> 
> GoPhish doesn’t have a default password anymore, it gets generated the first time you run it and is shown in the console

Noticed that too, but I continue to get an invalid token. Any ideas why?

**Comment by MccoyTesting** [comment]
What's your suggestions please ? I can't sign in into gophish, I think this started after I uninstalled and reinstalled it, the sqlite3 can't bring it up everytime i try running "sqlite3 gophish.db"
I think i'm getting something wrong, please what other suggestions do you have ? what's the code for editing this file while running it on a vps please?
Please note I'm running the gophish on a vps

> > Are you sure you are using the SQLite Db or are you using the MySql DB?
> > It will be this line and one below it in your config file.
> > https://github.com/gophish/gophish/blob/c9ff8714a0beda15b985a5d0061df3bcbc2f8f9d/config.json#L14
> > 
> > https://github.com/gophish/gophish/blob/c9ff8714a0beda15b985a5d0061df3bcbc2f8f9d/config.json#L15
> 
> Pleas would Making this changes to the config.json fix this up on gophish running on vps?



> GoPhish doesn’t have a default password anymore, it gets generated the first time you run it and is shown in the console

What's your suggestions please ? I can't sign in into gophish, I think this started after I uninstalled and reinstalled it, the sqlite3 can't bring it up everytime i try running "sqlite3 gophish.db"
I think i'm getting something wrong, please what other suggestions do you have ? what's the code for editing this file while running it on a vps please?
Please note I'm running the gophish on a vps
