### ISSUE TITLE
Gmail Issue

### ISSUE THREAD

**Issue by teddielong** [gophish/gophish#996]
Hi everyone

I appreciate this is less of an issue with GoPhish but more to do with Gmail, but despite having arranged IP whitelisting and also having whitelisted via header, Gmail then includes a warning to users that "this message was not sent to Spam based on your organisation’s request".  Does anyone know if there is a way around this?

Thanks

**Comment by mcvic1rj** [comment]
If you send a phish that just contains text like a normal email, does it still trigger that warning?

If so: I wonder if gmail does that for all whitelisted things now

If not: I would update your phish email template to see if you can get around their rules that are creating that warning

**Comment by jordan-wright** [comment]
My guess is that Gmail does this for emails it believes are spam but have also been whitelisted. I'm afraid there isn't anything we can do about this except to provide the same advice as always to correctly set up your email infrastructure. You can find good tips on things like how to set up dkim/dmarc/spf, etc [here](https://www.trustedsec.com/2018/03/take-employees-phishing/).

Hope this helps! Thanks for getting in touch, and I apologize that there isn't more we can do.
